js/common/modules/@arangodb/aql/explainer.js

Properly display vertex and edge collections for traversals when using the `OPTIONS` restrictions.
Description of bad behavior: https://github.com/arangodb/docs/pull/345#issuecomment-592108113
Jenkins: http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/9169/

Fix explainer output when restricting collections

---

arangod/RestHandler/RestAdminClusterHandler.cpp
tests/js/client/shell/shell-numberof-servers-cluster.js

The API `/_admin/cluster/numberOfServers` slightly changed in 3.7 compared to 3.6.
This PR reverts the change and also modifies the behavior in some other ways:
* allow sending HTTP PUT requests to the API with an empty JSON object `{}` as the request body. This was allowed in 3.6 as well. Sending such request does nothing, but it is allowed.
* allow using `null` values for setting the `numberOfDBServers` and `numberOfCoordinators` values. This is required for testing the API so the tests can reset the value each time.
* the return value of successful HTTP PUT requests in 3.6 was just `true`. In 3.7, we changed it to respond with `{"error":false,"code":200}`. This change is kept and will be documented as an API change.
Docs companion PR: https://github.com/arangodb/docs/pull/399
This PR …

(mostly) restore pre-3.7 API behavior

---

CHANGELOG

Only the changelog entry for:
https://github.com/arangodb/enterprise/pull/424
Jenkins:
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/9257/
Next attempt on the environment red run:
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/9275/

Changelog entry for enterprise only bug fix

---

CHANGELOG
arangod/Aql/GraphNode.cpp
arangod/Aql/GraphNode.h
arangod/Aql/KShortestPathsNode.cpp
arangod/Aql/KShortestPathsNode.h
arangod/Aql/ShortestPathNode.cpp
arangod/Aql/ShortestPathNode.h
arangod/Aql/TraversalNode.cpp
arangod/Aql/TraversalNode.h

Instantiation of AQL queries with graph traversals in One-Shard would previously fail. This is already fixed in devel.
This change is trivial.
In devel there are a bunch of additional tests that cover this in conjunction with satellite graphs, which I will maybe backport separately with another bugfix.

[3.6] Bug fix/fix one shard traversal instantiation

---

arangod/RestHandler/RestAdminClusterHandler.cpp
tests/js/client/shell/shell-numberof-servers-cluster.js

The API `/_admin/cluster/numberOfServers` slightly changed in 3.7 compared to 3.6.
This PR reverts the change and also modifies the behavior in some other ways:
* allow sending HTTP PUT requests to the API with an empty JSON object `{}` as the request body. This was allowed in 3.6 as well. Sending such request does nothing, but it is allowed.
* allow using `null` values for setting the `numberOfDBServers` and `numberOfCoordinators` values. This is required for testing the API so the tests can reset the value each time.
* the return value of successful HTTP PUT requests in 3.6 was just `true`. In 3.7, we changed it to respond with `{"error":false,"code":200}`. This change is kept and will be documented as an API change.
Docs companion PR: https://github.com/arangodb/docs/pull/399
This PR …

(mostly) restore pre-3.7 API behavior (#11364)

---

CHANGELOG
arangod/Agency/RestAgencyHandler.cpp
arangod/Aql/Ast.cpp
arangod/Aql/ExecutionPlan.cpp
arangod/Aql/ModificationExecutorHelpers.cpp
arangod/Aql/ModificationOptions.cpp
arangod/Aql/ModificationOptions.h
arangod/Cluster/ClusterMethods.cpp
arangod/ClusterEngine/ClusterCollection.cpp
arangod/ClusterEngine/ClusterCollection.h
arangod/MMFiles/MMFilesCollection.cpp
arangod/MMFiles/MMFilesCollection.h
arangod/RestHandler/RestDocumentHandler.cpp
arangod/RocksDBEngine/RocksDBCollection.cpp
arangod/RocksDBEngine/RocksDBCollection.h
arangod/StorageEngine/PhysicalCollection.h
arangod/Transaction/Methods.cpp
arangod/Utils/OperationOptions.h
arangod/V8Server/v8-collection.cpp
arangod/VocBase/LogicalCollection.cpp
arangod/VocBase/LogicalCollection.h
js/common/modules/@arangodb/aql/explainer.js
tests/Mocks/StorageEngineMock.cpp
tests/Mocks/StorageEngineMock.h
tests/js/common/shell/shell-insert-overwrite.js

* added overwriteMode "ignore" for AQL INSERT and non-AQL inserts.
* added tests for overwriteModes.
* fix a splice-subquery related bug in explainer for subqueries that don't return any data.
* fix an incorrect assertion in the agency.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9310/

added overwriteMode "ignore"

---

arangod/RocksDBEngine/RocksDBEngine.cpp

Add error output (in maintainer mode only) when some certain assertions fails.
This prints the collections map of the RocksDB storage engine in case a collection is reinserted into it but the slot is already used for a different collection.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9314/

Bug fix/debug rocksdb mapping error

---

arangod/Aql/AqlItemBlock.cpp
arangod/Aql/AqlItemBlock.h
arangod/Aql/AqlValue.cpp
arangod/Aql/AqlValue.h
arangod/Aql/BlocksWithClients.cpp
arangod/Aql/ExecutionBlockImpl.cpp
arangod/Aql/ExecutionNode.cpp
arangod/Aql/ExecutionNode.h
arangod/Aql/IResearchViewNode.cpp
arangod/Aql/IResearchViewNode.h
arangod/Aql/IndexNode.cpp
arangod/Aql/IndexNode.h
arangod/Aql/OutputAqlItemRow.cpp
arangod/Aql/OutputAqlItemRow.h
arangod/Aql/RegisterPlan.cpp
arangod/Aql/RegisterPlan.h
tests/IResearch/IResearchViewNode-test.cpp

Simplify register planning code a bit.
Keeps the inefficient and partially unused parameters in the Executor interfaces due to @goedderz request. Thus obsoletes https://github.com/arangodb/arangodb/pull/11336
This change is already covered by existing tests, such as *scripts/unittest catch, scripts/unittest shell_server_aql*.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9313/

simplify register planning code, a bit

---

3rdParty/iresearch/core/search/boolean_filter.cpp
3rdParty/iresearch/core/search/boolean_filter.hpp
CHANGELOG
tests/js/common/aql/aql-view-arangosearch-cluster.inc
tests/js/common/aql/aql-view-arangosearch-noncluster.js

fixed https://github.com/arangodb/arangodb/issues/11104
FOR s IN `v-site`
SEARCH ANALYZER(s.attributes.country.value != "w" OR false, "identity")
RETURN s.attributes.country.value
Empty result.
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/9332/

fixed iresearch analyzer NOT OR FALSE

---

CHANGELOG
arangod/RestHandler/RestCollectionHandler.cpp

Don't invoke collection key ranges compaction after performing a truncate operation on a RocksDB storage engine collection via the REST API's truncate endpoint.
The compaction was previously done to make RocksDB physically free data of key ranges that were supposed to be empty after the truncate, but it seems that the used version of RocksDB is struggling to achieve that goal. Although it does compact the ranges, it seems to read a lot of extra data from unrelated ranges as well, which blows up the overall time required to do the compactions. 
Most recent versions of RocksDB do not seem to have this problem anymore. But without upgrading RocksDB to the latest version the most sensible fix is to turn off the manual compaction and rely on RocksDB eventually freeing the key ranges that are …

do not run compaction after collection truncation

---

CHANGELOG
arangod/RocksDBEngine/RocksDBCollection.cpp

Don't perform unnecessary document lookups on the follower during the incremental sync protocol when the RocksDB storage engine is used.
This change is already covered by existing tests, such as *replication_sync*.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9331/

don't perform unnecessary document lookups in incremental sync

---

CHANGELOG
arangod/RestHandler/RestCollectionHandler.cpp

Don't invoke collection key ranges compaction after performing a truncate operation on a RocksDB storage engine collection via the REST API's truncate endpoint.
The compaction was previously done to make RocksDB physically free data of key ranges that were supposed to be empty after the truncate, but it seems that the used version of RocksDB is struggling to achieve that goal. Although it does compact the ranges, it seems to read a lot of extra data from unrelated ranges as well, which blows up the overall time required to do the compactions. 
Most recent versions of RocksDB do not seem to have this problem anymore. But without upgrading RocksDB to the latest version the most sensible fix is to turn off the manual compaction and rely on RocksDB eventually freeing the key ranges that are …

don't compact after collection truncation

---

CHANGELOG
arangod/GeneralServer/RestHandler.cpp
tests/js/client/load-balancing/response-header.js

Don't relay HTTP/1.1 response headers in load-balanced environment.
This should fix the issue described in https://github.com/arangodb/arangojs/issues/655
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9355/

don't relay HTTP/1.1 response headers

---

CHANGELOG
arangod/RestHandler/RestCollectionHandler.cpp

Don't invoke collection key ranges compaction after performing a truncate operation on a RocksDB storage engine collection via the REST API's truncate endpoint.
The compaction was previously done to make RocksDB physically free data of key ranges that were supposed to be empty after the truncate, but it seems that the used version of RocksDB is struggling to achieve that goal. Although it does compact the ranges, it seems to read a lot of extra data from unrelated ranges as well, which blows up the overall time required to do the compactions. 
Most recent versions of RocksDB do not seem to have this problem anymore. But without upgrading RocksDB to the latest version the most sensible fix is to turn off the manual compaction and rely on RocksDB eventually freeing the key ranges that are …

don't run compact after collection truncation

---

tests/js/client/load-balancing/response-header.js

Added a test for the issue described in https://github.com/arangodb/arangojs/issues/655
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9356/

add tests to make sure that HTTP/1.1 headers are not relayed

---

.gitignore
.hooks/pre-commit

Delete obsolete `.hooks` directory with obsolete command
Delete line from `.gitignore` that points to non-existing directory
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9365/

delete obsolete stuff

---

CHANGELOG
js/apps/system/_admin/aardvark/APP/frontend/js/templates/indicesView.html
js/apps/system/_admin/aardvark/APP/frontend/js/views/indicesView.js

Show index details in index overview of the web UI, e.g. the `expireAfter` attribute for TTL indexes or the `minLength` attribute for fulltext indexes
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9456/

show index details in web UI

---

arangod/Aql/ExecutionBlockImpl.cpp
tests/Aql/ExecutionBlockImplTest.cpp
tests/Aql/ExecutionBlockImplTestInstances.cpp
tests/Aql/SplicedSubqueryIntegrationTest.cpp

Removes the `constexpr` case distinction for new style vs old style executors

Remove isNewStyleExecutor constexpr

---

CHANGELOG
arangod/Graph/Graph.cpp
arangod/Graph/Graph.h
arangod/Graph/GraphManager.cpp
js/common/modules/@arangodb/general-graph-common.js
tests/js/client/server_parameters/test-sharding-restrictions-cluster.js

Fix example graph creation with `--cluster.min-replication-factor` set to > 1.
In case the startup option was used, example graphs were created with a replicationFactor value of 1, violating the requirements. Now, the default replication factor for the target database will be used.
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/434
This change is already covered by existing tests, such as *scripts/unittest server_parameters*.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9460/

fix graph creation with min-replication-factor set

---

arangod/CMakeLists.txt
arangod/Cluster/ClusterInfo.cpp
arangod/ClusterEngine/ClusterCollection.cpp
arangod/Indexes/IndexFactory.cpp
arangod/Replication/Syncer.cpp
arangod/RocksDBEngine/RocksDBCollection.cpp
arangod/RocksDBEngine/RocksDBPrimaryIndex.cpp
arangod/VocBase/Identifiers/IndexId.cpp
arangod/VocBase/Identifiers/IndexId.h
arangod/VocBase/Identifiers/LocalDocumentId.cpp
arangod/VocBase/Identifiers/LocalDocumentId.h
arangod/VocBase/Identifiers/ServerId.cpp
arangod/VocBase/Methods/Indexes.cpp
lib/Basics/Identifier.cpp
lib/Basics/Identifier.h
tests/IResearch/IResearchLinkCoordinator-test.cpp
tests/Mocks/StorageEngineMock.cpp

Currently the `Identifier` class has `isSet()` and `empty()` methods which assume that `0` is an invalid identifier for all derived types. At least `IndexId` uses `0` for primary indices, which causes some confusion and requires a weird workaround. This PR removes the `empty()` and `isSet()` methods from `Identifier` and moves them to the derived classes. It also removes the `clear()` method, as it also makes this assumption (replacing uses with `= [DerivedType]::none()` instead), and removes `IndexId::isNone()` as it is no longer necessary.
Enterprise component: https://github.com/arangodb/enterprise/pull/432

Specialize Identifier::empty() and related methods

---

arangod/VocBase/LogicalCollection.cpp
arangod/VocBase/LogicalCollection.h

Move std::atomic<bool> out of a sequence of non-atomic bools to class layout space waste.
Moving the atomics close together should be fine because they are written to just once or twice during the lifetime of the server.
Test plan: must compile without warnings
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9390/

reduce space waste

---

3rdParty/iresearch/core/index/merge_writer.cpp
CHANGELOG

Backport fix from upstream.
Verified by upstream tests.
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/9482/

Fix for 'docs out of order' error (internal issue #686)

---

3rdParty/iresearch/core/search/boolean_filter.cpp
3rdParty/iresearch/tests/search/boolean_filter_tests.cpp
CHANGELOG
arangod/IResearch/IResearchFeature.cpp
arangod/IResearch/IResearchFilterFactory.cpp
arangod/IResearch/IResearchFilterFactory.h
tests/IResearch/IResearchFeature-test.cpp
tests/IResearch/IResearchFilterFunction-test.cpp
tests/IResearch/IResearchQueryStartsWith-test.cpp
tests/js/common/aql/aql-view-arangosearch-cluster.inc
tests/js/common/aql/aql-view-arangosearch-noncluster.js

Supported several prefixes in STARTS_WITH function with min match count.
https://github.com/arangodb/backlog/issues/694
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/9498/

Supported STARTS_WITH with several prefixes

---

arangod/Cache/Cache.cpp

Fix possible divide-by-zero detected by `UndefinedBehaviorSanitizer`.
Jenkins: https://jenkins.arangodb.biz/job/arangodb-matrix-pr/9574/

Fix divide-by-zero in cache eviction handling.

---

CHANGELOG
arangod/Cluster/MaintenanceFeature.cpp
arangod/GeneralServer/GeneralServerFeature.cpp
arangod/IResearch/IResearchFeature.cpp
arangod/Pregel/PregelFeature.cpp
arangod/RocksDBEngine/RocksDBEngine.cpp
arangod/Scheduler/SchedulerFeature.cpp
arangod/StorageEngine/RocksDBOptionFeature.cpp
arangosh/Dump/DumpFeature.cpp
arangosh/Import/ImportFeature.cpp
arangosh/Restore/RestoreFeature.cpp
lib/ApplicationFeatures/EnvironmentFeature.cpp
lib/ApplicationFeatures/MaxMapCountFeature.cpp
lib/Basics/NumberOfCores.cpp
lib/Basics/NumberOfCores.h
lib/Basics/system-functions.cpp
lib/Basics/system-functions.h
lib/CMakeLists.txt

Lower the default values for `--rocksdb.block-cache-size` and `--rocksdb.total-write-buffer-size` for systems with less than 1 GB of RAM. For these systems the default value were presumably too high and needed manual adjustment.
Documentation companion PR: https://github.com/arangodb/docs/pull/419
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9565/

lower default values for small systems

---

arangod/Cache/Cache.cpp
tests/Cache/TransactionsWithBackingStore.cpp

Fixes a potential divide-by-zero error in the cache that was discovered by the undefined behavior sanitizer. Also adjusts a non-deterministic test which had an arbitrary success threshold to use a less-arbitrary threshold which should actually reveal something wrong (rather than just bad luck) if it isn't met.
Jenkins: https://jenkins.arangodb.biz/job/arangodb-matrix-pr/9579/

Fix potential divide-by-zero in cache and fix non-deterministic test

---

CHANGELOG
arangod/Graph/Graph.cpp
arangod/Graph/Graph.h
arangod/Graph/GraphManager.cpp
js/common/modules/@arangodb/general-graph-common.js
tests/js/client/server_permissions/test-sharding-restrictions-cluster.js

Fix example graph creation with `--cluster.min-replication-factor` set to > 1.
In case the startup option was used, example graphs were created with a replicationFactor value of 1, violating the requirements. Now, the default replication factor for the target database will be used.
Backport of #11445.
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/440
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9573/

fix example graph creation with `--cluster.min-replication-factor` set

---

Documentation/DocuBlocks/Rest/Administration/get_admin_modules_flush.md

Backport of: https://github.com/arangodb/arangodb/commit/8079d11747934722fd0d98ce50f321394286885e
From files:
- lib\Logger\LogTopic.cpp
- arangod\IResearch\IResearchCommon.cpp
~unclear if `libiresearch` is also a log topic~
libiresearch is not exposed, but possibly will be in 3.7.

Docs: Add missing log topics

---

arangod/Cache/Cache.cpp
tests/Cache/TransactionsWithBackingStore.cpp

Fixes a potential divide-by-zero error in the cache that was discovered by the undefined behavior sanitizer. Also adjusts a non-deterministic test which had an arbitrary success threshold to use a less-arbitrary threshold which should actually reveal something wrong (rather than just bad luck) if it isn't met.
Jenkins: https://jenkins.arangodb.biz/job/arangodb-matrix-pr/9580/ (blue except unrelated failures)

[3.6] Fix potential divide-by-zero in cache and fix non-deterministic test

---

arangod/Cache/Cache.cpp
tests/Cache/TransactionsWithBackingStore.cpp

Fixes a potential divide-by-zero error in the cache that was discovered by the undefined behavior sanitizer. Also adjusts a non-deterministic test which had an arbitrary success threshold to use a less-arbitrary threshold which should actually reveal something wrong (rather than just bad luck) if it isn't met.
Jenkins: https://jenkins.arangodb.biz/job/arangodb-matrix-pr/9581/ (blue except unrelated failures)

[3.5] Fix potential divide-by-zero in cache and fix non-deterministic test

---

lib/Basics/process-utils.cpp

If we close file descriptor 0, it becomes available again and can be reused when the next file one is opened. fd 0 being any "random" filehandle instead of stdin will be unexpected for the executed program.

Instead of just closing stdin, open "/dev/null"

---

CHANGELOG
arangod/RestHandler/RestAdminClusterHandler.cpp
arangod/RestHandler/RestAdminClusterHandler.h

Fix REST API `/_admin/cluster/removeServer`.
This also fixes the removal of servers via the web interface.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9628/

Fix REST API /_admin/cluster/removeServer.

---

CHANGELOG
arangod/ClusterEngine/ClusterRestCollectionHandler.cpp
arangod/ClusterEngine/ClusterRestCollectionHandler.h
arangod/MMFiles/MMFilesRestCollectionHandler.cpp
arangod/MMFiles/MMFilesRestCollectionHandler.h
arangod/RestHandler/RestCollectionHandler.cpp
arangod/RestHandler/RestCollectionHandler.h
arangod/RocksDBEngine/RocksDBRestCollectionHandler.cpp
arangod/RocksDBEngine/RocksDBRestCollectionHandler.h
arangod/V8Server/v8-collection.cpp
arangod/VocBase/Methods/Collections.cpp
arangod/VocBase/Methods/Collections.h

Fix potential undefined behavior in REST handler for `/_api/collection` for some operations in the cluster.
This change is already covered by existing tests, such as *http_server shell_client --cluster true*.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9682/

fix potential undefined behavior

---

3rdParty/iresearch/core/index/index_writer.cpp

warning log level was to high as consolidation interruptions are totally normal on highly loaded systems. This is expected situation, so lowered messages to DEBUG.
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/9709/

log level lowered for consolidation warnings

---

arangod/Aql/ExecutionEngine.cpp
arangod/Aql/ExecutionEngine.h
arangod/Aql/SharedQueryState.cpp
arangod/Aql/SharedQueryState.h

fix a spurious shutdown issue
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9697/

fix spurious shutdown errors

---

CHANGELOG
arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
arangod/RocksDBEngine/RocksDBEngine.cpp
arangod/RocksDBEngine/RocksDBEngine.h
tests/js/common/shell/shell-edge-index.js

Fix issue #11303 
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9735/

Feature 3.6/rocksdb disable edge cache

---

arangod/Network/Utils.cpp

Don't swallow error details in network responses in case they are present.
Right now some errors are reported as "no error" even in case there is a more detailed error message.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9744/

don't swallow error details in case there are some

---

tests/js/server/recovery/foxx-directories.js

Fix unstable recovery test that depended on timing.
This change is already covered by existing tests, such as *scripts/unittest recovery*.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9776/

fix an unstable test that depended on timing

---

arangod/RestHandler/RestJobHandler.cpp
tests/js/client/shell/shell-transaction.js

Make a sporadically failing test more stable
This change is already covered by existing tests, such as *scripts/unittest shell_client --test transaction.js*.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9783/

make sporadically failing test more stable

---

CHANGELOG
arangod/Cluster/HeartbeatThread.cpp
arangod/RestHandler/RestReplicationHandler.cpp
arangod/RestServer/DatabaseFeature.cpp
arangod/VocBase/Methods/Databases.cpp
arangod/VocBase/VocbaseInfo.cpp
arangod/VocBase/VocbaseInfo.h
tests/Aql/IndexNodeTest.cpp
tests/IResearch/common.cpp
tests/js/common/shell/01_shell-database.js

Fix invalid value of `isSystem` attribute for non-system databases.
Should fix https://github.com/arangodb/arangodb/issues/11243
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9632/

Fix invalid value of isSystem attribute for non-system databases.

---

CHANGELOG
arangod/Transaction/ManagerFeature.cpp

Transaction manager garbage collection was posted on the INTERNAL_LOW
lane, which is a very bad idea.
This can lead to deadlock if an exclusive lock from SynchronizeShard stays due to network failures. The cleanup after 5 minutes would be done by the transaction manager garbage collection. However, if all threads for the low prio queue are blocked on the lock, we have a deadlock.

Solve a deadlock problem in the cluster.

---

arangod/Replication/DatabaseInitialSyncer.cpp

Fixes only an invalid insertion.
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/9799/
No feature / test added here.

Fixed a now invalid assertion in initial syncer

---

CHANGELOG
arangod/Transaction/ManagerFeature.cpp

The transaction manager garbage collection was posted on the
INTERNAL_LOW lane, which is a very bad idea. This can lead to deadlock
if an exclusive lock from SynchronizeShard stays due to network
failures. The cleanup after 5 minutes would be done by the transaction
manager garbage collection. However, if all threads for the low prio
queue are blocked on the lock, we have a deadlock.

Fix a deadlock in the cluster.

---

CHANGELOG
arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
tests/js/common/shell/shell-edge-index.js

Fix issue #11303 
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9734/

Bug fix 3.5/fix issue 11303

---

arangod/Replication/common-defines.cpp

Don't exclude certain system collections from replication. This is not necessary, and most of the previously excluded collections are antique and not in use anymore, or it simply does not make any difference if their changes get replicated.
This change is already covered by existing tests, such as *replication tests*.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9849/

don't exclude certain antiquated collections from replication

---

arangod/RestServer/arangod.cpp

Reenable previously disabled crash handler.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9850/

reenable crash handler

---

arangod/Aql/GraphNode.cpp

Bug-fix for serialization of GraphNodes.
In Disjoint Case the disjoint flag has not been Properly serialized / deserialized.
This is not used in general production path, but there is a way to trigger this from user-side.
Jenkins:
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/9853/
Thank you @jsteemann for spotting it

Added isDisjoint and isSmart to serialization of GraphNodes

---

CHANGELOG
arangod/Aql/SingleRemoteModificationExecutor.cpp
tests/js/server/aql/aql-optimizer-optimize-cluster-single-document-operations.js

Fix issue #11590.
There was an issue when in a cluster a SingleRemoteNode was used to retrieve a document and this document either had an "old" or a "new" attribute. In this case, the document was not correctly returned.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9876/

fixed issue #11590

---

arangod/Aql/QuerySnippet.cpp

If an optimizer rule removed a superflous REMOTE/SCATTER, we end up in a situation where we need to plan a snippet without a remote node; we previously forgot to fill the `distIds` for the shards involved in this case.

Handle nullptr remote in snippet planning

---

CHANGELOG
arangod/Cluster/ClusterInfo.cpp
arangod/Cluster/v8-cluster.cpp
arangod/VocBase/Methods/Databases.cpp

A mutex was held for too long and therefore a deadlock could happen in dropCollection. This was introduced by the new regime for `loadPlan` and `loadCurrent`.

Fix drop collection hangers.

---

CHANGELOG
arangod/Cluster/ClusterInfo.cpp

Do not always loadPlan from agency if collections of a database are listed.
This is important for arangosync.

Port bugfix from 3.6 to 3.4.

---

CHANGELOG
arangod/Graph/KShortestPathsFinder.cpp
arangod/Graph/KShortestPathsFinder.h
tests/js/server/aql/aql-graph-k-shortest-path-early-abort-regression.js

(Backport of #11602)
Before this path the k-shortest-paths algorithm kept a record
of the weight of the done vertex furthest away from the centre,
and a record of the weight of the currently best path found.
This was used to stop search if
start.furthest + end.furthest > currentBest
which is wrong, as (wlog) the start side can find a any vertex in the
target side, including the target vertex itself. vertex on the target side that is closer to the target than the current furthest away.
We now stop search for a neighbourhood, if the known highest weight
is higher than current best path weight, as we are not
going to find a shorter path originating in this neighbourhood.

[3.5] Fix bug where early abort condition aborts too early 

---

CHANGELOG
arangod/Graph/KShortestPathsFinder.cpp
arangod/Graph/KShortestPathsFinder.h
tests/js/server/aql/aql-graph-k-shortest-path-early-abort-regression.js

(Backport of https://github.com/arangodb/arangodb/pull/11602)
Before this path the k-shortest-paths algorithm kept a record
of the weight of the done vertex furthest away from the centre,
and a record of the weight of the currently best path found.
This was used to stop search if
start.furthest + end.furthest > currentBest
which is wrong, as (wlog) the start side can find a any vertex in the
target side, including the target vertex itself. vertex on the target side that is closer to the target than the current furthest away.
We now stop search for a neighbourhood, if the known highest weight
is higher than current best path weight, as we are not
going to find a shorter path originating in this neighbourhood.

[3.6] Fix bug where early abort condition aborts too early 

---

CHANGELOG
arangod/Cluster/ClusterInfo.cpp

Port a bug fix to 3.5 from 3.6. Do not always loadPlan from agency when collections of a database are listed.

Port bug fix to 3.5

---

tests/Aql/MultiDependencySingleRowFetcherTest.cpp

Shuts up the compiler about comparing `int` to `size_t`.
Caused by  merging #11618

static cast to int to shutup compiler warning

---

lib/ApplicationFeatures/ConfigFeature.cpp

where the server tried to interpret
a directory as conf-file leading to
an early exit. Now the path is instead
ignored if it does not point to a
regular file.
This was especially a problem when
the original path was empty and
arangod tried to find a local
override. In this case the search
had '.local' as candidate witch is
a common directory in user homes.

Fix an arangod configuration bug

---

3rdParty/rocksdb/CMakeLists.txt

Disable compiling RocksDB tools when building ArangoDB.
Test plan: compilation must still work!
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9992/

disable building rocksdb tools when building arangodb

---

lib/ApplicationFeatures/ConfigFeature.cpp

where the server tried to interpret
a directory as conf-file leading to
an early exit. Now the path is instead
ignored if it does not point to a
regular file.
This was especially a problem when
the original path was empty and
arangod tried to find a local
override. In this case the search
had '.local' as candidate witch is
a common directory in user homes.

Fix an arangod configuration bug (#11632)

---

js/client/modules/@arangodb/testsuites/recovery.js

Remove 2 obsolete options being set for recovery tests.
These options were useful with MMFiles only and in 3.7 only trigger obsoletion warnings at startup.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10016/

remove obsolete options from recovery test

---

CHANGELOG
arangod/RocksDBEngine/RocksDBPrimaryIndex.cpp
tests/js/server/aql/aql-optimizer-primary-index-ranges.js

Fix edge cases in RocksDB primary index range lookups for operators >= and <.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10024/

Fixed edge cases in RocksDB primary index range lookups for operators >= and <.

---

arangod/Aql/Ast.cpp
arangod/Aql/Ast.h
arangod/Aql/AstNode.cpp
arangod/Aql/AstNode.h
arangod/Aql/Condition.cpp
arangod/Aql/IndexExecutor.cpp
arangod/Aql/OptimizerRules.cpp

AstNodes have a member `_computedValue` which can contain a pointer to dynamically allocated memory. this memory is owned by the AstNode and is freed when the AstNode is destroyed. this works fine for AstNodes that are dynamically created and destroyed in a query.
However, there were some singleton AstNodes which were created just once for the entire server process and were shared between all queries:
* NullNode
* FalseNode
* TrueNode
* ZeroNode
* EmptyStringNode
The initialization of the `_computedValue` attribute for these singleton nodes was not thread-safe, so it multiple queries computed the value for the same singleton node simultaneously, this could have caused races and a (small) one-time memory leak .
The fix now makes nodes per-query singleton nodes, so they can be reused within …

fix unprotected access to _computedValue

---

CHANGELOG
arangod/RocksDBEngine/RocksDBPrimaryIndex.cpp
tests/js/server/aql/aql-optimizer-primary-index-ranges-rocksdb.js

Fix edge cases in RocksDB primary index range lookups for operators >= and <.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10026/

Fix edge cases in RocksDB primary index range lookups for operators >= and <.

---

CHANGELOG
arangod/Aql/ModificationExecutorHelpers.cpp
arangod/Aql/ModificationExecutorHelpers.h

If a modification operation yields an `OperationResult` that is *not* `ok()` we need to throw, and not try to access an empty array of results (and then pretend everything is ok...)

Also throw if result is not ok()

---

CHANGELOG
arangod/IResearch/IResearchAnalyzerFeature.cpp
arangod/IResearch/IResearchAnalyzerFeature.h
arangod/RestHandler/RestViewHandler.cpp
arangod/V8Server/v8-views.cpp
tests/js/common/aql/aql-view-arangosearch-ddl-cluster.js

Added analyzer cache update on coordinator befor view create/update.
If cluster is just started analyzers cache is empty on coordinator. And attempt to create/update ArangoSearch view will fail due to not found analyzers. Now cache is reread for current database and system database (as analyzers from system database could be used also in other databases).
Fix is verified by js tests
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/10054/

Bug fix/internal issue #650

---

CHANGELOG
arangod/Aql/OptimizerRules.cpp
tests/js/server/aql/aql-optimizer-rule-move-filters-into-enumerate.js

Fixed issue #11652 
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10064/

fixed issue #11652: Error: AQL: missing variable #2 (1) for node #6 (FilterNode) while planning registers

---

arangod/Aql/AqlItemBlock.cpp
arangod/Aql/AqlItemBlock.h

Make AqlItemBlock's `_refCount` non-atomic again.
There should not be concurrent accesses of this variable, so making it atomic is a pessimization.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10067/

make refcounts non-atomic again

---

arangod/RocksDBEngine/RocksDBEngine.cpp
arangod/StorageEngine/EngineSelectorFeature.h

Disallow usage of the encryption key rotation APIs on coordinators. Calling the APIs on a coordinator exposed undefined behavior, as the API works on the RocksDB storage engine's internals, which is not present on a coordinator.
Instead, now a nicer HTTP 403 error message is returned.
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/470
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10104/

disallow encryption rotation APIs on coordinators

---

README_maintainers.md

- Does `./scripts/unittest all` also run all gtest tests?
- Should we mention Google Test and the `arangodbtests` binary in a separate section (own headline)? 
- Any noteworthy special features?

Mention arangodbtests (gtest) in README_maintainers.md

---

3rdParty/fuerte/src/H1Connection.cpp
3rdParty/fuerte/src/H1Connection.h
CHANGELOG
arangod/Network/Methods.cpp
arangod/Utils/CollectionNameResolver.cpp

Do not retry requests to FAILED servers.
Cache _unknown result in CollectionNameResolver.
Return fuerte::Error::Timeout on timeout rather than Cancelled.
See https://arangodb.atlassian.net/browse/BTS-27
This is the `devel` version of the fix.

Improve behaviour on dropping followers.

---

arangod/RocksDBEngine/RocksDBMetaCollection.cpp

Prevent an unintentional attempt to serialize a revision tree before it is constructed during an intermediate step in the collection upgrade process.
Jenkins: https://jenkins.arangodb.biz/job/arangodb-matrix-pr/10165/ (blue except unrelated known failures)

Fix unintentional attempt to serialize revision tree during collection upgrade

---

arangod/GeneralServer/HttpCommTask.cpp

Currently, all incoming requests are treated as HTTP/1 requests initially, and an `HttpCommTask` is created. If this is actually an HTTP/2 or VST request, then a subsequent comm task is created and the old one is discarded. Previously, we did not actually close this old task, so we ended up with an ever-growing number of zombie tasks objects. It did not leave the actual connections open, as those were transferred to the new tasks; however, it is effectively a memory leak and leads to incorrect connection statistics reporting.
Jenkins: https://jenkins.arangodb.biz/job/arangodb-matrix-pr/10167/ (blue except known unrelated failures)

Remove zombie HttpCommTasks

---

js/client/modules/@arangodb/testsuites/recovery.js
tests/js/server/recovery/crash-handler-abort.js
tests/js/server/recovery/crash-handler-assert.js
tests/js/server/recovery/crash-handler-segfault.js
tests/js/server/recovery/crash-handler-terminate-active.js
tests/js/server/recovery/crash-handler-terminate.js

Honor value of variable `ARANGODB_OVERRIDE_CRASH_HANDLER` in our tests, too
This change is already covered by existing tests, such as *scripts/unittest recovery*.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10201/

honor crash handler override variable in tests

---

arangod/GeneralServer/AuthenticationFeature.cpp

Ignore "hidden" files and symbolic links in jwt-secrets-folder and in encryption-key-folder.
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/475
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10209/

ignore hidden files and symbolic links in JWT secrets folder

---

arangod/Aql/AqlItemMatrix.cpp
tests/Aql/AqlItemMatrixTest.cpp
tests/CMakeLists.txt

Mostly added some Tests for AqlItemMatrix.
Clarified the behavior if shadowRow is last in a block,
I did not manage to trigger any bad behavior with the version before (besides the specific test) so I think this is not a production issue, maybe a minor slow down. (checking that an empty list is empty.)
Jenkins:
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/10213
Blue besides the known one.

Added test for AqlItemMatrix, fixed minor glitch

---

CHANGELOG
arangosh/Dump/DumpFeature.cpp
arangosh/Restore/RestoreFeature.cpp
tests/js/client/shell/shell-dump-integration.js

arangodump and arangorestore will now fail when using the `--collection` option and none of the specified collections actually exist in the database (on dump) or in the dump to restore (on restore). In case some of the specified collections exist, arangodump/restore will issue warnings about the invalid collections, but will continue to work for the valid collections.
Documentation PR: https://github.com/arangodb/docs/pull/452
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10217/

make arangodump/restore fail with invalid collection names

---

arangod/Agency/TransactionBuilder.h
arangod/Aql/AqlValue.h
arangod/Aql/BlocksWithClients.h
arangod/Aql/KShortestPathsExecutor.h
arangod/Aql/MaterializeExecutor.h
arangod/Aql/ScatterExecutor.h
arangod/Aql/SortedCollectExecutor.h
arangod/Aql/SortingGatherExecutor.h
arangod/Aql/SubqueryEndExecutor.h
arangod/Aql/SubqueryExecutor.h
lib/Containers/Enumerate.h
tests/Cache/Rebalancer.cpp
tests/Containers/EnumerateTest.cpp

Remove `noexcept` specifier on `= default`ed constructors, destructors or assignment operators.
Rationale: Those defaulted functions are automatically declared `noexcept` (or not), depending on the base and/or members. Adding the specifier explicitly overrides that (at least with recent compilers like GCC10).

Removed noexcept specifier on defaulted constructors etc.

---

Documentation/DocuBlocks/Rest/Collections/1_structs.md

https://arangodb.slack.com/archives/C1PJT16QP/p1590755388483700
The current API docs are not very specific about things like whether an attribute is returned only in Enterprise Edition. It's also unclear whether the server behavior is as intended (e.g. `isSmart` is present in Community Edition as well). I would like to defer improvements to this to the Swagger rewrite, and only add missing options for now.
https://jenkins01.arangodb.biz/view/Documentation/job/arangodb-ANY-examples/634/

Docs: Add missing isSmart and smartJoinAttribute options

---

arangod/RocksDBEngine/RocksDBMetaCollection.cpp
arangod/RocksDBEngine/RocksDBMetaCollection.h
arangod/RocksDBEngine/RocksDBMetadata.cpp

This is a partial fix for an issue with the new replication protocol. The new revision trees do not appear to be persisted fully correctly. One symptom has been failures when used in conjunction with hot backup. This PR fixes this particular symptom, but may not fix all issue with the persistence/recovery of the revision trees.
Jenkins: https://jenkins.arangodb.biz/job/arangodb-matrix-pr/10240/

Fix issue with hot backup and new replication protocol

---

CHANGELOG
arangod/RocksDBEngine/RocksDBMetaCollection.cpp
arangod/RocksDBEngine/RocksDBTransactionCollection.cpp
tests/js/server/recovery/recalculate-count-incremental.js
tests/js/server/recovery/recalculate-count.js

Fixed a bug in the internal `recalculateCount()` method that could lead to count adjustments being applied with the wrong sign.
Added tests.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10246/

Bug fix/recalculate count

---

CHANGELOG
js/apps/system/_api/foxx/APP/index.js
js/apps/system/_api/foxx/APP/schemas.js
tests/js/client/shell/shell-foxx-api-spec.js

Backport of https://github.com/arangodb/arangodb/pull/10348.
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/10270/

Fix idiomatic Foxx testing reports for 3.6

---

3rdParty/fuerte/include/fuerte/connection.h
CHANGELOG
arangod/Network/ConnectionPool.cpp
arangod/Network/ConnectionPool.h
arangod/Network/Utils.cpp

* Added missing mutex acquisition to ConnectionPool::cancelConnections().
* optimize ConnectionPool::pruneConnections() to make only a single pass over the connections.
This change is already covered by existing tests, such as *anything connection related*.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10260/

added missing mutex to ConnectionPool::cancelConnections()

---

arangod/Aql/AqlValue.cpp
arangod/Aql/AqlValue.h
arangod/Aql/Expression.cpp
arangod/Aql/Functions.cpp
arangod/Aql/Query.cpp

Remove dependency on `trx` object in AqlValue::toV8(...)
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10283/

remove dependency on trx object

---

3rdParty/velocypack/include/velocypack/Value.h
3rdParty/velocypack/src/Builder.cpp
3rdParty/velocypack/src/Value.cpp

Micro-optimize velocypack::Value by making its struct 16 bytes small instead of 24 bytes.
Additionally reorder cases in velocypack::Builder so the more frequent cases come first.
This change is already covered by existing tests, such as *velocypack tests*.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10277/

micro optimizations in velocypack

---

tests/js/client/agency/agency-test.js

Make one more agency test less sensitive to timing problems.
This should fix a spurious test failure that can happen in very slow/loaded environments.
This change is already covered by existing tests, such as *scripts/unittest agency*.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10294/

make agency test less sensitive to timing

---

arangod/Aql/DocumentProducingHelper.cpp
arangod/Aql/DocumentProducingHelper.h
arangod/Aql/OutputAqlItemRow.cpp
arangod/Aql/OutputAqlItemRow.h

When producing documents and using projections, recycle a velocypack::Builder
Additionally, use an optimized method for storing data in the target AqlItemBlock 
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10284/

when producing documents and using projections, recycle a velocypack::Builder

---

arangod/ClusterEngine/ClusterTransactionState.cpp

Don't reload the plan forcefully to receive the latest revision of analyzers at the start of each cluster transaction.
This change is already covered by existing tests, such as *scripts/unittest gtests, scripts/unittest shell_server_aql --cluster true*.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10313/
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10314/

don't force plan reload for analyzer revisions

---

arangod/Cluster/ClusterInfo.cpp

Removed code for rolling upgrades that's not needed anymore. Removing this also fixes rebootIds possibly not working correctly when a server is being shutdown with `remove_from_cluster=1`.

Remove old code for rolling upgrades. Fixes BTS-87.

---

CHANGELOG
arangod/Sharding/ShardingFeature.cpp

"shardingStrategy" entries can be missing for collections created with ArangoDB clusters in version 3.3 or earlier. A missing "shardingStrategy" entry can cause issues for certain queries that need to check the shard distribution on the DB-Servers.
This change transparently handles missing "shardingStrategy" entries.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10318/

Handle missing "shardingStrategy" in Plan agency entries for collections

---

arangod/Scheduler/SchedulerFeature.cpp

This fix can prevent the startup error
arangod terminated because of an exception: no section defined for program option --server.threads
from happening

explicitly define section "server" where it is needed.

---

CHANGELOG
js/apps/system/_admin/aardvark/APP/frontend/js/collections/arangoDocument.js
js/apps/system/_admin/aardvark/APP/frontend/js/views/documentsView.js

Fix the creation of edges in the web UI, which previously did not work due to a JavaScript error.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10367/

fix the creation of edges in the web UI

---

CHANGELOG
js/apps/system/_admin/aardvark/APP/frontend/js/collections/arangoCollections.js

Pick up selected "write concern" value entered in web UI when creating a collection in the cluster. Previously, the "write concern" value was not picked up correctly and collections were created with the default write concern.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10375/

pick up write concern from UI

---

CHANGELOG
js/apps/system/_admin/aardvark/APP/aardvark.js

Pass through proper AQL errors to web UI graph viewer, instead of turning them into HTTP 500 "Internal Server Error"s.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10380/

don't mangle AQL errors in web UI graph viewer

---

tests/js/common/shell/shell-collection-noncluster.js

Tries to fix the following spurious test failure:
```
* Test "shell_server"
[FAILED]  tests/js/common/shell/shell-collection-noncluster.js
"testEdgeCacheBehavior" failed: Error: at assertion #7: { "fields" : [ "_from", "_to" ], "figures" : { "cacheInUse" : true, "cacheLifeTimeHitRate" : 25.020309928492797, "cacheSize" : 1443200, "cacheUsage" : 939150, "cacheWindowedHitRate" : 0, "memory" : 2337006 }, "id" : "UnitLoadBehavior123/2", "name" : "edge", "selectivityEstimate" : 0.9973823620086466, "sparse" : false, "type" : "edge", "unique" : false }: (false) does not evaluate to true
(Error
at assertTrue (/work/ArangoDB/js/common/modules/jsunity/jsunity.js:71:19)
at tests/js/common/shell/shell-collection-noncluster.js:466:13
at Array.forEach (<anonymous>)
at Object.testEdgeCacheBehavior …
```

attempt to fix spuriously failing test about edge cache

---

lsan_arangodb_suppressions.txt

Removes remainders of libcurl from lsan_suppressions
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10360/

remove remainders of libcurl

---

CHANGELOG
arangod/IResearch/IResearchAnalyzerFeature.cpp
arangod/IResearch/IResearchAnalyzerFeature.h
tests/js/client/authentication/auth-analyzer-view-integration.js

Temporarily elevate permissions for analyzers.
This seems to be required in order to create views in other databases than `_system`, with users that do not have privileges to access the `_system` database.
When creating a new view, all analyzers a queried via an AQL qurery `FOR d IN _analyzers RETURN d`, which reads them from the `_analyzers` collection in the `_system` database. Without privileges to read from that collection, the query and thus the view creation fails.
This PR temporarily elevates the privileges for executing that query.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10416/

elevate permissions for analyzers

---

CHANGELOG
js/apps/system/_admin/aardvark/APP/frontend/js/views/collectionsView.js

Use smarter default value preset in web UI for replication factor in case there are constraints established for the replication factor by the startup options `--cluster.min-replication-factor` and `--cluster.max-replication-factor`.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10437/

Bug fix 3.7/smarter ui default value for replication factor

---

arangod/Cluster/ClusterInfo.cpp

[3.6] Remove old code for rolling upgrades. Fixes BTS-87.

---

arangod/Cluster/ClusterInfo.cpp

[3.5] Remove old code for rolling upgrades. Fixes BTS-87.

---

arangod/Transaction/Context.cpp
arangod/Transaction/Context.h
tests/Aql/LevenshteinMatchFunctionTest.cpp

Fixes the following memleak when executing the gtests:
``` 
Direct leak of 64 byte(s) in 2 object(s) allocated from:
#0 0x7fb5eb5b3947 in operator new(unsigned long) (/lib/x86_64-linux-gnu/libasan.so.5+0x10f947)
#1 0x55decd5b5640 in arangodb::transaction::Context::leaseStringBuffer(unsigned long) /home/jsteemann/ArangoAsan/arangod/Transaction/Context.cpp:135
#2 0x55decd5d1e44 in arangodb::transaction::StringBufferLeaser::StringBufferLeaser(arangodb::transaction::Methods*) /home/jsteemann/ArangoAsan/arangod/Transaction/Helpers.cpp:429
#3 0x55ded000060b in arangodb::aql::Functions::LevenshteinDistance(arangodb::aql::ExpressionContext*, arangodb::transaction::Methods*, std::vector<arangodb::aql::AqlValue, short_alloc<arangodb::aql::AqlValue, 64ul, 8ul> > const&) …
```

Bug fix/fix test memleak

---

CHANGELOG
js/server/modules/@arangodb/aql-helper.js

Fix bug in internal test helper function `removeCost`. It was not excluding costs. This can help fix some spurious assertion failures in AQL tests.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10457/

fix internal test helper function `removeCost`

---

arangod/Transaction/Context.cpp
arangod/Transaction/Context.h
tests/Aql/LevenshteinMatchFunctionTest.cpp

Fixes the following memleak when executing the gtests:
``` 
Direct leak of 64 byte(s) in 2 object(s) allocated from:
#0 0x7fb5eb5b3947 in operator new(unsigned long) (/lib/x86_64-linux-gnu/libasan.so.5+0x10f947)
#1 0x55decd5b5640 in arangodb::transaction::Context::leaseStringBuffer(unsigned long) /home/jsteemann/ArangoAsan/arangod/Transaction/Context.cpp:135
#2 0x55decd5d1e44 in arangodb::transaction::StringBufferLeaser::StringBufferLeaser(arangodb::transaction::Methods*) /home/jsteemann/ArangoAsan/arangod/Transaction/Helpers.cpp:429
#3 0x55ded000060b in arangodb::aql::Functions::LevenshteinDistance(arangodb::aql::ExpressionContext*, arangodb::transaction::Methods*, std::vector<arangodb::aql::AqlValue, short_alloc<arangodb::aql::AqlValue, 64ul, 8ul> > const&) …
```

fix a memleak that only happens in tests due to mocking

---

CHANGELOG
arangod/Cluster/ClusterInfo.cpp
arangod/Indexes/IndexFactory.cpp
arangod/RestHandler/RestReplicationHandler.cpp
arangosh/Restore/RestoreFeature.cpp
tests/js/client/shell/shell-restore-integration.js
tests/js/common/shell/shell-index-geo.js

Allow restoring arangodumps from ArangoDB 3.3 and before, taken with MMFiles, into a current version of ArangoDB.
Related ticket: https://arangodb.atlassian.net/browse/BTS-84 
This PR supersedes https://github.com/arangodb/arangodb/pull/11787
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10471/

Fix restoring old arangodumps from ArangoDB 3.3

---

CHANGELOG
arangod/Aql/Ast.cpp
arangod/Aql/ExecutionEngine.cpp
arangod/Aql/Query.cpp
arangod/Aql/Query.h
arangod/Aql/QueryCursor.cpp
arangod/Aql/SharedQueryState.cpp
arangod/RestHandler/RestCursorHandler.cpp
js/client/modules/@arangodb/test-utils.js
tests/js/client/shell/shell-query-dbserver-cluster.js

Allow queries on DB-Servers again, for debugging purposes.
This is not an official supported feature, but is sometimes used for debugging. Previous changes made it impossible to run a query on a local shard.
This is the 3.7 backport of the devel PR: https://github.com/arangodb/arangodb/pull/11886
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10497/

Allow AQL queries on DB-Servers again

---

scripts/startLocalCluster.sh

Fix usage of `scripts/startLocalCluster.sh` with a single DB-Server
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10481/

allow usage of `scripts/startLocalCluster.sh` with a single DBS

---

CHANGELOG
arangod/Network/ConnectionPool.cpp
arangod/Network/ConnectionPool.h
arangod/Replication/DatabaseInitialSyncer.cpp
arangod/Replication/GlobalInitialSyncer.cpp
arangod/Replication/Syncer.cpp
arangod/Replication/utilities.cpp
arangod/Replication/utilities.h
arangod/RocksDBEngine/RocksDBMetaCollection.cpp
arangod/RocksDBEngine/RocksDBMetadata.cpp
tests/IResearch/AgencyMock.cpp
tests/IResearch/AgencyMock.h

A recent PR (https://github.com/arangodb/arangodb/pull/11760) made some changes to how revision trees are serialized, and one line of code was not updated properly, leading to some nuisance logging on server startup.
Furthermore, there's an issue with the catch-up phase of replication overlapping with the initial phase, which creates problems for ArangoSearch now that the `_rev` values are used for `LocalDocumentId`. This should fix the overlap.
Backport of https://github.com/arangodb/arangodb/pull/11807
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10499/

Multiple fixes backported from devel

---

CHANGELOG
arangod/Network/ConnectionPool.cpp
arangod/Network/ConnectionPool.h
tests/Network/ConnectionPoolTest.cpp

Fixed unintentional connection re-use for cluster-internal communications.
3.6 backport of https://github.com/arangodb/arangodb/pull/11890.
This change is already covered by existing tests, such as *all cluster, Network gtest*.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10500/

Bug fix 3.6/fuerte connection pool reuse

---

CHANGELOG
tests/js/server/shell/shell-pregel.js

Fix non-deterministic test failure in Pregel WCC test.
https://arangodb.atlassian.net/browse/BTS-91
This change is already covered by existing tests, such as *shell_server --test pregel --cluster true*.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10520/

fixed non-determinstic test failure in Pregel WCC test

---

CHANGELOG
tests/js/server/recovery/check-warnings.js

Add a recovery test that checks that there are no warnings after a graceful shutdown
Context: https://arangodb.atlassian.net/browse/BTS-88
Backport of: https://github.com/arangodb/arangodb/pull/11814
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10519/

add recovery test

---

tests/Mocks/Servers.cpp

Fix reboot tracker warnings in unit tests.
https://arangodb.atlassian.net/browse/AR-68
This change is already covered by existing tests, such as *gtests*.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10526/

fix a few useless warnings

---

arangod/Aql/ExecutionBlock.cpp
arangod/Aql/Query.cpp
arangod/Aql/QueryCache.cpp
arangod/Aql/QueryList.cpp
arangod/Aql/QueryProfile.cpp
arangod/Aql/Timing.cpp
arangod/Aql/Timing.h
arangod/CMakeLists.txt

Use the `steady_clock` for AQL query profiling and not the `system_clock`.
The system_clock is not guaranteed to be monotonically increasing, and it may jump forward or backward anytime upon user or OS interaction.
The steady_clock however is monotonically increasing and thus can be used for measuring time differences between two timepoints without being affected by leaps forward or backward.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10538/

use "steady_clock" for profiling and not "system_clock"

---

arangod/Agency/Supervision.cpp

The Supervision must not try to enforce the replication factor for a collection during creation, i.e. while the `isBuilding` flag is set. Otherwise, if that happens and e.g. an `addFollower` job runs during creation, the collection creation will always fail.
This was found while inspecting the failures in the resilience_repair test suite noted in BTS-59 and BTS-71.
Relates to internal issues https://arangodb.atlassian.net/browse/BTS-59 and https://arangodb.atlassian.net/browse/BTS-71.
This change is already covered by existing tests, such as the *resilience* tests.

Leave isBuilding collections alone in the Supervision

---

arangod/Aql/ExecutionBlock.cpp
arangod/Aql/Query.cpp
arangod/Aql/QueryCache.cpp
arangod/Aql/QueryList.cpp
arangod/Aql/QueryProfile.cpp
arangod/Aql/Timing.cpp
arangod/Aql/Timing.h
arangod/CMakeLists.txt

Use the `steady_clock` for AQL query profiling and not the `system_clock`.
The system_clock is not guaranteed to be monotonically increasing, and it may jump forward or backward anytime upon user or OS interaction.
The steady_clock however is monotonically increasing and thus can be used for measuring time differences between two timepoints without being affected by leaps forward or backward.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10542/

use "steady_clock" for profiling and not "system_clock" (#11904)

---

arangod/Cluster/ClusterInfo.cpp
arangod/Cluster/ClusterMethods.cpp
js/common/bootstrap/errors.js
lib/Basics/errors.dat
lib/Basics/voc-errors.cpp
lib/Basics/voc-errors.h
lib/Rest/GeneralResponse.cpp

Introduce a special error code to signal that updating the plan on
creating a collection had a failed precondition, and maybe the
surrounding code should try again.
In particular stop abusing a pre-existing error code that has no
relation to this context.
Backport of https://github.com/arangodb/arangodb/pull/11882
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10554/

Do not abuse TRI_ERROR_REQUEST_CANCELED in Cluster code (#11882)

---

arangod/Aql/ExecutionBlockImpl.cpp
arangod/Aql/InputAqlItemRow.cpp
arangod/Aql/InputAqlItemRow.h
arangod/Aql/OutputAqlItemRow.cpp
arangod/Aql/ShadowAqlItemRow.cpp
arangod/Aql/ShadowAqlItemRow.h

Just PR adds an assertion around  passthrough blocks to make sure we actually pass through identical lines.
Also moves down a "move" operation.
I do not think that the earlier code is incorrect, as the only read value is copied instead of moved (because it it the meta information and only data is moved here) but it is more obvious that this is correct now.
Jenkins:
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10561/

Bug fix/assert on passthrough indexes (#11818)

---

CHANGELOG
arangod/Agency/AgencyComm.cpp
arangod/Agency/AgencyComm.h
arangod/Agency/AsyncAgencyComm.cpp
arangod/Cluster/ClusterFeature.cpp
arangod/Cluster/ClusterFeature.h
arangod/Cluster/HeartbeatThread.cpp
arangod/Cluster/ServerState.cpp
arangod/Cluster/ServerState.h

Speed up the cluster shutdown by waiting for shorter periods for transient agency writes on shutdown and in heartbeat thread.
Potentially fixes https://arangodb.atlassian.net/browse/BTS-90 and https://arangodb.atlassian.net/browse/BTS-104.
Backport of https://github.com/arangodb/arangodb/pull/11902/
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10573/

potential shutdown speedup (#11902)

---

arangod/IResearch/IResearchAnalyzerFeature.cpp
tests/js/common/aql/aql-view-arangosearch-feature.js

PR adds test case for loading analyzers in oneshard database.
Additional trace level logging added in maintainer mode to help debug oneshard optimization in future.
Suggest to not backport to 3.7 (as it contains no fixes in implementation) just leave in devel  to avoid same pitfall in future.

Bug fix/internal issue #720

---

arangod/Cluster/ClusterMethods.cpp

The go driver tests searches for non-existing IDs; this will loop forever, until a timeout occurs. 
This condition was wrong corrosponding to the comment above its line, correcting it fixes this behaviour.

fix condition where empty ID is ok

---

CHANGELOG

This is a missing changelog entry pertaining to #11880 and #11882 (and #11857)

Add CHANGELOG entry for failover graph not found error

---

CHANGELOG
arangod/Cluster/ClusterMethods.cpp

fix go driver backup tests - searching for non-existing backups in clusters
run go driver tests

Bug fix 3.7/fix condition where empty list is ok

---

arangod/GeneralServer/CommTask.cpp

always allow access to `_admin/server` APIs on active failover

Allow _admin/server prefix on followers

---

CHANGELOG
arangod/RestHandler/RestReplicationHandler.cpp

Allows restoring collections from v3.3.0 with their all-numeric collection GUID values, by creating a new, unambiguous collection GUID for them. 
v3.3.0 had a bug because it created all-numeric GUID values, which can be confused with numeric collection ids in lookups. v3.3.1 already changed the GUID routine to produce something non-numeric already, but collections created with v3.3.0 can still have an ambiguous GUID. This fix adjusts the restore routine to drop such GUID values, so it only changes something if v3.3.0 collections are dumped, dropped on the server and then restored with the flawed GUIDs.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10632/

Bug fix 3.4/fix all numeric guids on restore

---

CHANGELOG
arangod/RestHandler/RestReplicationHandler.cpp

Allows restoring collections from v3.3.0 with their all-numeric collection GUID values, by creating a new, unambiguous collection GUID for them. 
v3.3.0 had a bug because it created all-numeric GUID values, which can be confused with numeric collection ids in lookups. v3.3.1 already changed the GUID routine to produce something non-numeric already, but collections created with v3.3.0 can still have an ambiguous GUID. This fix adjusts the restore routine to drop such GUID values, so it only changes something if v3.3.0 collections are dumped, dropped on the server and then restored with the flawed GUIDs.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10635/

fix all-numeric collection GUIDs on restore

---

CHANGELOG
arangod/Cluster/ClusterInfo.cpp

In case that a coordinator organising a hotbackup crashes during the hotbackup a hotbackup lock in the agency is left behind. To fix this, there is already a cleanup routine in the agency supervision. Unfortunately, this cleanup routine did not fit to the actual way the lock was acquired. Therefore the lock does not work. This PR adjusts the way the lock is acquired to the cleanup routine, thereby enabling automatic cleanup of left over locks. This is important for Oasis, see https://arangodb.atlassian.net/browse/OASIS-252

Fix hotbackup agency lock cleanup.

---

CHANGELOG
arangod/Aql/Functions.cpp
arangod/Cluster/Maintenance.cpp
arangod/VocBase/LogicalCollection.cpp
js/apps/system/_admin/aardvark/APP/frontend/js/views/validationView.js
tests/js/common/shell/shell-validation.js

This PR should fix the error that a schema once set for a collection could not easily be removed.
Now schemas can be removed easily by saving a schema of either null or {} . Using an empty string a schema will produce an error in the web interface and will not remove the schema.
The PR also fixes the behavior for the SCHEMA_VALIDATE AQL function in case the first parameter was no document/object. In this case, the function will now return nulland register a warning in the query, so the user can handle it. 
Additional docs PR: https://github.com/arangodb/docs/pull/481
This change is already covered by existing tests, such as *shell_client / shell_server*.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10665/

fix schema validation test errors

---

CHANGELOG
arangod/Aql/OptimizerRules.cpp
tests/js/server/aql/aql-optimizer-undistribute-remove-regression.js

The `undistribute-remove-after-enum-coll` optimizer rule was a bit too eager and accidentally moved a call to `DOCUMENT` to a DBServer.
Fixes #11858

Fix undistributeRemoveAfterEnumColl rule.

---

tests/js/common/aql/aql-view-arangosearch-ddl-cluster.js
tests/js/common/aql/aql-view-arangosearch-ddl-noncluster.js
tests/js/common/aql/aql-view-arangosearch-feature.js

Made ArangoSearch tests tolerate analyzers left in collection by other tests. Tests now checks explicit 0 only if db is newly created by test itself. Otherwise checks are made like "count before test" = "count after test"
This change is covered by existing tests.
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/10734/

made analyzers count check deterministic

---

CHANGELOG
js/apps/system/_admin/aardvark/APP/frontend/js/templates/modalTable.ejs

Remove superflous `%>` output in the UI modal dialog in case the JSON editor was embedded
Reported via https://arangodb.atlassian.net/browse/QA-22?focusedCommentId=39910
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10773/

Remove superflous `%>` output in the UI modal dialog in case the JSON editor was embedded

---

CHANGELOG
arangod/Indexes/IndexFactory.cpp
arangod/RestHandler/RestReplicationHandler.cpp
tests/js/client/shell/shell-restore-integration.js

Currently, there is a difference in how we handle fulltext index creation between the cluster and single server. In the single server, a `minLength <= 0` parameter is simply overwritten with 1. In the cluster, it is honored when writing to the Plan, but then overwritten on the DBServers. This creates a discrepancy and leads to maintenance churn constantly recreating the index. The simple fix is to also do the overwrite to 1 in the Plan. 
Jenkins:

Fixed BTS-110: Fulltext index with minLength <= 0 not allowed.

---

arangod/Aql/AqlCallStack.cpp
arangod/Aql/ExecutionEngine.cpp
arangod/Aql/ExecutionEngine.h
arangod/Aql/Query.cpp
arangod/Aql/Query.h
arangod/Aql/QueryList.cpp
arangod/Aql/QueryList.h
arangod/Aql/QueryResult.h
arangod/Aql/QueryResultV8.h
arangod/Aql/SingleRemoteModificationExecutor.cpp
arangod/VocBase/vocbase.cpp
tests/Aql/ExecutionBlockImplTest.cpp
tests/Aql/SubqueryStartExecutorTest.cpp
tests/IResearch/IResearchIndex-test.cpp
tests/Transaction/Context-test.cpp
tests/Transaction/Manager-test.cpp
tests/js/common/shell/shell-query-spec.js
tests/js/server/aql/aql-graph-k-shortest-path.js

Clean up a bit in Query object and related parts.
The PR fixes wrong "started" values in QueryList.cpp (list of currently running queries), and fixes a few other small issues.
Additionally it avoids creating `_profile` objects for parse & explain operations and slightly simplifies the return value handling in error cases. 
I moved these changes out of another branch I currently have open, in order to keep the other branch smaller and to simplify reviews. 
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10802/

Bug fix/simplify query object

---

arangod/RocksDBEngine/RocksDBMetaCollection.cpp

Under certain circumstances, we leak a RocksDB iterator during recovery, which can under some circumstances, leak a great deal of data accessed by that iterator.
Covered by recovery tests with ASAN.
Jenkins: https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/10834/ (blue)
http://jenkins.arangodb.biz:8080/job/arangodb-ANY-linux-asan/314/

Fix AR-60: memory leak in recovery

---

CHANGELOG
arangod/Aql/QueryList.cpp
js/apps/system/_admin/aardvark/APP/frontend/js/templates/arangoTable.ejs
js/apps/system/_admin/aardvark/APP/frontend/js/views/queryManagementView.js
js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
js/apps/system/_admin/aardvark/APP/frontend/scss/_arangoTable.scss

Fixes a bit of web UI layout for the currently running and slow queries.
Previously, the query string was not properly left-aligned, due to usage of an HTML `<pre>` element inside a template that had lots of whitespace around the to-be-inserted query string. This effectly left-padding the query string, because a `<pre>` is supposed to keep and render all surrounding whitepace.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10836/

improve readability of queries in web UI's query view

---

tests/Aql/GatherExecutorCommonTest.cpp

Test only fix.
There is an invalid memory access, where a Referenced vector can go out of scope.
No change for Production code.
On Purpose no changelog.
Jenkins:
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/10856/

Bug fix/invalid memory access in gather test

---

lib/Basics/VelocyPackHelper.cpp
tests/Basics/VelocyPackHelper-test.cpp

Remove a Sonderlocke for patching double value in existing VPack chunks.
There was a potential optimized code branch for platforms that allow unaligned writes, but this only made the code more complex and can cause false-positive warnings with UBSan. So let's simplify this and rely on compilers to properly optimize it. It is called rarely anway.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10844/

remove a Sonderlocke for patching doubles in existing VPack chunks

---

lib/Basics/VelocyPackHelper.cpp
tests/Basics/VelocyPackHelper-test.cpp

Remove a Sonderlocke for patching double value in existing VPack chunks.
There was a potential optimized code branch for platforms that allow unaligned writes, but this only made the code more complex and can cause false-positive warnings with UBSan. So let's simplify this and rely on compilers to properly optimize it. It is called rarely anway.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10846/

Bug fix 3.7/remove sonderlocke

---

tests/Aql/GatherExecutorCommonTest.cpp

Test only fix.
On purpose no changelog, no production code modified
Backport of:
https://github.com/arangodb/arangodb/pull/12099
Jenkins:
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/10857/

Fixed invalid memory access

---

3rdParty/fuerte/include/fuerte/connection.h
3rdParty/fuerte/include/fuerte/types.h
3rdParty/fuerte/src/H2Connection.cpp
3rdParty/fuerte/src/H2Connection.h
arangod/GeneralServer/H2CommTask.cpp
arangod/GeneralServer/HttpCommTask.cpp

Support starting a non TLS http2 connection without upgrading from http 1.1
https://tools.ietf.org/html/rfc7540#section-3.4
https://172.16.10.101/job/arangodb-matrix-pr/10871/

Starting HTTP/2 with Prior Knowledge

---

arangod/Pregel/Algorithm.h
arangod/Pregel/Algos/ShortestPath.h
arangod/Pregel/Conductor.cpp
arangod/Pregel/Conductor.h
arangod/Pregel/GraphStore.cpp
arangod/Pregel/Utils.cpp
arangod/Pregel/Utils.h
arangod/Pregel/Worker.cpp
arangod/Pregel/WorkerConfig.cpp
arangod/Pregel/WorkerConfig.h

according to Michael Hackstein this was put in to optimize how many
documents were loaded when using MMFiles; since we don't use MMFiles anymore
this is not needed anymore.
The code where it was attempted to be used was the ShortestPath algorithm
which crashed anyway (because of an unimplemented loadDocument function).

Remove "lazyLoading"

---

CHANGELOG
arangod/Agency/Store.cpp

This is a rather trivial fix which needs porting to all branches.
This is the 3.7 port.
Manual test procedure:
1. Switch log level of topic "agency" to TRACE in the agency.
2. Kill -9 a dbserver.
If agency leader does not crash, the fix works.

Fixed a potential agency crash if trace logging is on.

---

tests/js/common/aql/aql-view-arangosearch-cluster.inc
tests/js/common/aql/aql-view-arangosearch-noncluster.js

Slightly better cleanup in case of testfailures.
Should fix issues like in http://172.16.10.101:8080/job/arangodb-ANY-linux-matrix/1062/EDITION=community,STORAGE_ENGINE=rocksdb,TEST_SUITE=cluster,limit=linux&&test||gce/artifact/testfailures.txt
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10900/

better test cleanup

---

js/client/modules/@arangodb/testsuites/communication.js
tests/js/client/communication/test-communication.js

Add testsuites for parallel communication to testing.js:
* `communication`: tests parallel communication
* `communication_ssl`: tests parallel communication with SSL
can be used via `scripts/unittest communication --cluster true`.
Communication tests are running for 5 minutes each, so they are disabled by default.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10942/

Feature 3.7/add communication testsuite

---

js/client/modules/@arangodb/testsuites/communication.js
tests/js/client/communication/test-communication.js

Add testsuites for parallel communication to testing.js:
* `communication`: tests parallel communication
* `communication_ssl`: tests parallel communication with SSL
can be used via `scripts/unittest communication --cluster true`.
Communication tests are running for 5 minutes each, so they are disabled by default.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10971/

Feature/add communication testsuite (#12148)

---

CHANGELOG
lib/Logger/LogAppenderSyslog.cpp
lib/Logger/LogAppenderSyslog.h

Fixed potential undefined behavior in syslog logging with ident string going out of scope after calling `openlog()`.
In 3.7 this is covered by PR https://github.com/arangodb/arangodb/pull/12141 and in devel by PR https://github.com/arangodb/arangodb/pull/12140.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10969/

fix potential undefined behavior in syslog logging

---

CHANGELOG
arangod/GeneralServer/RestHandler.cpp
arangod/Transaction/Manager.cpp

Properly set `Content-Type` to `application/x-velocypack` in case a VST request without Content-Type is being forwarded inside a load-balanced cluster from one coordinator to another.
Previously, if the incoming VST request did not have a proper content type set, `application/json` was assumed, which caused issues when parsing the forwarded request on the relayed-to coordinator.
Additionally:
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10964/

fix request forwarding with VST requests without Content-Type header set

---

CHANGELOG
lib/Basics/ReadWriteSpinLock.h

Add missing rollback of state changes when an attempt-based write operation on a spin lock fails.
This change is already covered by existing tests, such as *all*.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10995/

Added missing state rollback for failed attempt-based write locking of spin locks

---

arangod/Aql/EngineInfoContainerCoordinator.cpp
arangod/Aql/EngineInfoContainerCoordinator.h
arangod/Aql/ExecutionEngine.cpp
arangod/Aql/ExecutionEngine.h
arangod/Aql/Query.cpp
arangod/Aql/Query.h
arangod/Aql/QueryContext.h
arangod/Aql/QueryProfile.cpp
arangod/Aql/QueryProfile.h
arangod/Aql/QueryRegistry.cpp
arangod/Aql/QueryRegistry.h
arangod/Aql/SharedQueryState.h
arangod/Aql/types.h
tests/js/client/shell/shell-transaction.js

Make cleanup and killing exclusive operations.
Backport of https://github.com/arangodb/arangodb/pull/12078
Fixes https://arangodb.atlassian.net/browse/BTS-116
This change is already covered by existing tests, such as *shell_client, load_balancing*.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11002/

Atomic query killing (#12078)

---

CHANGELOG
arangod/Network/NetworkFeature.cpp

Disable internal protocol switch for cluster-internal communication, and hard-code its value to "http".
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10977/

disable internal protocol switch, and hard-code it to HTTP

---

CHANGELOG
lib/Logger/LogAppender.cpp
lib/Logger/LogAppender.h
lib/Logger/LogAppenderFile.cpp
lib/Logger/LogAppenderFile.h
lib/Logger/LogAppenderSyslog.cpp
lib/Logger/LogAppenderSyslog.h
tests/Agency/NodeTest.cpp
tests/Basics/LoggerTest.cpp
tests/Geo/ShapeContainerTest.cpp

(Backport of https://github.com/arangodb/arangodb/pull/12140)
* fix UB in syslog logger, with ident string going out of scope after `openlog` was called.
* fix infinite recursion when printing error messages about invalid logger configuration.
* fix sporadic use-after-free issue in logger shutdown 
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/499
Likely supersedes PR https://github.com/arangodb/arangodb/pull/12109.
Likely fixes https://arangodb.atlassian.net/browse/AR-60.
Unfortunately this needs manual testing.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10927/

Bug fix 3.7/fix logger issues

---

lib/Logger/LogAppender.cpp
lib/Logger/LogAppender.h
lib/Logger/LogAppenderFile.cpp
lib/Logger/LogAppenderFile.h
lib/Logger/LogAppenderSyslog.cpp
lib/Logger/LogAppenderSyslog.h
tests/Agency/NodeTest.cpp
tests/Basics/LoggerTest.cpp
tests/Geo/ShapeContainerTest.cpp

* fix UB in syslog logger, with ident string going out of scope after `openlog` was called.
* fix infinite recursion when printing error messages about invalid logger configuration.
* fix sporadic use-after-free issue in logger shutdown 
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/498
Likely supersedes PR https://github.com/arangodb/arangodb/pull/12109.
Likely fixes https://arangodb.atlassian.net/browse/AR-60.
Unfortunately this needs manual testing.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10926/
ASan run: http://172.16.10.101:8080/job/arangodb-ANY-linux-asan/329/

fix logger issues

---

tests/js/client/communication/test-communication.js

Make an insert operation in a test case succeed even if it is automatically retried.
This should fix spurious "unique constraint violation" errors in the `communication` testsuite.
This change is already covered by existing tests, such as *communication*.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11015/

make insert idempotent

---

tests/js/client/communication/test-communication.js

Make an insert operation in a test case succeed even if it is automatically retried.
This should fix spurious "unique constraint violation" errors in the `communication` testsuite.
This change is already covered by existing tests, such as *communication*.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11014/

Bug fix 3.6/make test insert idempotent

---

CHANGELOG
arangod/RestHandler/RestReplicationHandler.cpp
arangod/RestHandler/RestReplicationHandler.h
arangod/VocBase/Methods/Collections.cpp
arangod/VocBase/Methods/Collections.h

Fixes a bug, when you want to restore and already restored smart graph into the same database again. This caused an duplicate name issue before.
Restoring into a fresh Database is fine.
Restoring into a database without (or different) smart graphs is also fine.
Backport of:
https://github.com/arangodb/arangodb/pull/12154
Enterprise Part:
https://github.com/arangodb/enterprise/pull/494
Fixes:
https://arangodb.atlassian.net/browse/BTS-127
Jenkins:
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11016/

3.7 Bug fix/fix dump disjoint (#12154)

---

3rdParty/fuerte/include/fuerte/FuerteLogger.h
3rdParty/fuerte/include/fuerte/connection.h
3rdParty/fuerte/src/GeneralConnection.cpp
3rdParty/fuerte/src/GeneralConnection.h
3rdParty/fuerte/src/H1Connection.cpp
3rdParty/fuerte/src/H1Connection.h
CHANGELOG
arangod/Network/ConnectionPool.cpp
lib/Logger/LoggerFeature.cpp
tests/AsyncAgencyComm/AsyncAgencyCommTest.cpp
tests/IResearch/AgencyMock.cpp
tests/Network/MethodsTest.cpp

This fixes a race in the connection pool which could lead to a connection
being leased and then getting an idle timeout. This leads to sporadic network
request failures under TLS and inefficiencies under TCP.

Port connection pool fix from devel back to 3.7.

---

arangod/Aql/AllRowsFetcher.h
arangod/Cluster/ClusterFeature.cpp

Fix over-eager reporting of agency cache shutdown (currently logs every 100ms, which is too frequent).
No need to backport this to 3.6, as the agency cache does not exist there. The fix is included in some other PR for devel.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11019/

fix over-eager shutdown messaging

---

3rdParty/fuerte/include/fuerte/FuerteLogger.h
3rdParty/fuerte/include/fuerte/connection.h
3rdParty/fuerte/src/GeneralConnection.cpp
3rdParty/fuerte/src/GeneralConnection.h
3rdParty/fuerte/src/H1Connection.cpp
3rdParty/fuerte/src/H1Connection.h
CHANGELOG
arangod/Network/ConnectionPool.cpp
lib/Logger/LoggerFeature.cpp
scripts/startLocalCluster.sh
tests/AsyncAgencyComm/AsyncAgencyCommTest.cpp
tests/IResearch/AgencyMock.cpp
tests/Network/MethodsTest.cpp

This ensures that a connection which has already been leased out of the
connection pool can no longer run into its idle timeout.
This has to be ported to 3.7 but not to older versions.

Fix fuerte TLS connection breakages.

---

arangod/Agency/Inception.cpp

Do not assume leadership when restarted and cluster did not react to leader change yet. In particular to not server wrong data.
- Did you add tests for a new *RestHandler* subclass ?
- Did you add new mocks of underlying code layers to be able to verify your functionality ? 
- ...
Additionally:

Agency Restart Bug

---

CHANGELOG
arangod/Agency/Agent.cpp
arangod/Agency/Agent.h
arangod/Agency/AgentConfiguration.cpp
arangod/Agency/AgentConfiguration.h

Backport of https://github.com/arangodb/arangodb/pull/12083
We keep the Agent peer information more in sync now, this fixes an issue where temporarily the agency config could not be requested by a newly elected leader.
Jenkins:
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/10984/

3.7 Backport of Agency consistency of peer info

---

arangod/Auth/UserManager.cpp
arangod/Auth/UserManager.h

Don't include a method by default that is only used from within tests.
Simply needs to compile after the change.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11027/

hide a method by default that is only used from within tests

---

CHANGELOG
arangod/Cluster/v8-cluster.cpp
arangod/V8Server/v8-actions.cpp
tests/js/server/shell/shell-communication-methods-cluster.js

These will be called with JSON bodies, but the default content type is VPack. This will cause trouble and basically break those APIs for cluster internal usage.
Jenkins:
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11036/
Fixes:
https://arangodb.atlassian.net/projects/BTS/issues/BTS-128
tests:
Included in this PR.
Also there is indirect tests for this code in resilience tests, Foxx part.

bug-fix JSExposed cluster internal networking methods

---

arangod/GeneralServer/CommTask.h
arangod/GeneralServer/GeneralCommTask.cpp
arangod/GeneralServer/H2CommTask.cpp
arangod/GeneralServer/HttpCommTask.cpp

Fixed a race between a new request and the keepAlive timeout.
This change is already covered by existing tests, such as jsteemanns test which takes exactly 5mins.

KeepAlive Timeout Race

---

lib/Logger/LogAppender.cpp
lib/Logger/LogAppenderFile.cpp

Trying to fix use-after-free as found here:
http://172.16.10.101:8080/job/arangodb-ANY-mac-matrix/1063/EDITION=enterprise,STORAGE_ENGINE=rocksdb,TEST_SUITE=cluster,limit=mac/artifact/testfailures.txt
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/505
Should be covered by ASan runs and matrix tests.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11021/
http://172.16.10.101:8080/job/arangodb-ANY-linux-asan/333/

another attempt to please ASan

---

CHANGELOG
arangod/Cluster/v8-cluster.cpp
arangod/V8Server/v8-actions.cpp
tests/js/server/shell/shell-communication-methods-cluster.js

These will be called with JSON bodies, but the default content type is VPack. This will cause trouble and basically break those APIs for cluster internal usage.
Jenkins:
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11048/
Fixes:
https://arangodb.atlassian.net/projects/BTS/issues/BTS-128
Backport of:
https://github.com/arangodb/arangodb/pull/12202/
tests:
Included in this PR.
Also there is indirect tests for this code in resilience tests, Foxx part.

bug-fix JSExposed cluster internal networking methods (#12202)

---

CHANGELOG
arangod/Aql/FilterExecutor.cpp
tests/js/server/aql/aql-profiler-noncluster-nightly.js
tests/js/server/aql/aql-profiler.js
tests/js/server/aql/aql-skipping.js

Reverts an unintended behavior change in Filter Executor in comparison to 3.6
It will now again fetch full batches of documents instead of taking into account the requested limit.
Jenkins:
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11052/

Bug fix/overfetch in filter

---

CHANGELOG
arangod/Aql/OptimizerUtils.cpp
arangod/Aql/OptimizerUtils.h
arangod/Aql/TraversalNode.cpp
arangod/Graph/BaseOptions.cpp
arangod/Graph/BaseOptions.h
arangod/Graph/TraverserOptions.cpp
arangod/Graph/TraverserOptions.h

Fixes a bug in BFS search over smart-graphs.
There was. a small chance that a different index was picked, which caused the result to be incomplete.
Jenkins:
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11054/
Has enterprise part:
https://github.com/arangodb/enterprise/pull/509
Backport of:
https://github.com/arangodb/arangodb/pull/12079/

SmartBFS 2020 (#12079)

---

CHANGELOG
arangod/Aql/FilterExecutor.cpp
tests/js/server/aql/aql-profiler-noncluster-nightly.js
tests/js/server/aql/aql-profiler.js
tests/js/server/aql/aql-skipping.js

Reverts an unintended behavior change in Filter Executor in comparison to 3.6
It will now again fetch full batches of documents instead of taking into account the requested limit.
Backport of:
https://github.com/arangodb/arangodb/pull/12214
"Fixes"
https://arangodb.atlassian.net/browse/BTS-139
Jenkins:
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11065/

Bug fix 3.7/overfetch in filter

---

CHANGELOG
arangod/Cluster/ClusterInfo.cpp
arangod/Cluster/ClusterInfo.h
arangod/Cluster/MaintenanceFeature.cpp
arangod/Cluster/MaintenanceWorker.cpp
arangod/RestServer/Metrics.h
arangod/RestServer/MetricsFeature.cpp

This PR provides 3 metrics-related changes:
* Added cluster metrics `arangodb_load_plan_accum_runtime_msec` and `arangodb_load_current_accum_runtime_msec` to track the total time spent in `loadPlan()` and `loadCurrent()` operations.
* Fixed wrong reporting of failures in all maintenace failure counter metrics (`arangodb_maintenance_action_failure_counter`). Previously, each successful maintenance operation was reported as a failure, so the failure counters actually were counters for the number of successful maintenance actions.
* Adjusted the scale of the `arangodb_maintenance_action_queue_time_msec` to cover a more useful range.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11033/

fix and extend cluster metrics

---

CHANGELOG
arangod/Aql/ExecutionNode.cpp
arangod/Aql/Query.cpp

Profiling a parallel traversal query with a non-maintainer build results in a crash by dereferencing a nullptr. This PR fixes this by checking for nullptrs.
Jenkins: https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/11069/

Fix crash in cleanup of parallel traversal query

---

CHANGELOG
arangod/GeneralServer/CommTask.h
arangod/GeneralServer/GeneralCommTask.cpp
arangod/GeneralServer/H2CommTask.cpp
arangod/GeneralServer/HttpCommTask.cpp

Backport of #12194.
https://jenkins.arangodb.biz/job/arangodb-matrix-pr/11057/

Fixed a race between a new request and the keepAlive timeout.

---

Documentation/DocuBlocks/Rest/Database/get_api_database_new.md

The HTTP API expects the following structure:
- name: "string"
- options: { ... }
- users: [ {...}, {...} ]
The DocuBlock used the same parent ID for both options and users, leading to duplicate entries in both property descriptions.
Also adjusting description to actual server behavior (passwd and active not required).
https://jenkins01.arangodb.biz/view/Documentation/job/arangodb-ANY-examples/653/

Docs: Fix POST /_api/database request body parameters

---

arangod/Aql/Query.cpp
arangod/Aql/Query.h
arangod/Aql/QueryOptions.cpp
arangod/Aql/QueryOptions.h
arangod/Aql/RestAqlHandler.cpp
arangod/Aql/RestAqlHandler.h
arangod/RestServer/QueryRegistryFeature.cpp
arangod/V8Server/v8-vocbase.cpp

Do not store the query options redundantly in a builder object
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11090/

Do not store query opts

---

CHANGELOG
arangod/RestHandler/RestReplicationHandler.cpp
arangod/VocBase/vocbase.cpp

Fix spurious "lock timeout" errors that were observed during dump/restore tests.
Affects 3.7 and devel only.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11115/

fix spurious "lock timeout" errors when restoring collections

---

3rdParty/fuerte/src/AsioSockets.h

Reverts arangodb/arangodb#12259 as not safe.

Revert "avoid throwing exception in fuerte"

---

CHANGELOG
arangod/RocksDBEngine/RocksDBVPackIndex.cpp

Revive faster out-of-range comparator for secondary index scans that do a full collection index scan for index types "hash", "skiplist", "persistent". There is a performance gain of a few percent when running a query on a local collection with 1M entries, e.g. `FOR doc IN collection RETURN doc.value` (where `value` is indexed).
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11167/

Revive faster out-of-range comparator for secondary index scans

---

CHANGELOG
arangod/Aql/HashedCollectExecutor.cpp
tests/js/server/aql/aql-optimizer-collect-methods.js

Fixes: https://github.com/arangodb/arangodb/issues/12267
In case of Large values collected in multiple groups the memory management was incorrect, and a value could be freed although it is still in use. Which causes undefined behavior.
Requires back ports to all versions incl. 3.5.
Jenkins:
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11193/

Bug fix/invalid memory management in collect

---

CHANGELOG
arangod/Aql/HashedCollectExecutor.cpp
tests/js/server/aql/aql-optimizer-collect-methods.js

Backport of https://github.com/arangodb/arangodb/pull/12271
Fixes: https://github.com/arangodb/arangodb/issues/12267
In case of Large values collected in multiple groups the memory management was incorrect, and a value could be freed although it is still in use. Which causes undefined behavior.
Jenkins:
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11197/

Bug fix 3.5/invalid memory management in collect

---

arangod/Aql/AqlItemBlock.cpp
arangod/Aql/AqlItemBlock.h
arangod/Aql/AqlValue.cpp
arangod/Aql/AqlValue.h
tests/js/common/shell/shell-cluster-collection.js

Implement a simplification suggested by @graetzer in https://github.com/arangodb/arangodb/pull/12249#discussion_r458699618
This should use less memory and allow for slightly faster lookups in `_valueCount`.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11198/

make AQL fast again 11

---

CHANGELOG
arangod/Aql/HashedCollectExecutor.cpp
tests/js/server/aql/aql-optimizer-collect-methods.js

Backport of https://github.com/arangodb/arangodb/pull/12271
Fixes: https://github.com/arangodb/arangodb/issues/12267
In case of Large values collected in multiple groups the memory management was incorrect, and a value could be freed although it is still in use. Which causes undefined behavior.
Jenkins:
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11195/

Bug fix 3.7/invalid memory management in collect

---

arangod/Aql/AqlItemBlock.cpp
arangod/Aql/AqlItemBlock.h
arangod/Aql/AqlValue.cpp
arangod/Aql/AqlValue.h
tests/js/common/shell/shell-cluster-collection.js

Implement a simplification suggested by @graetzer in https://github.com/arangodb/arangodb/pull/12249#discussion_r458699618
This should use less memory and allow for slightly faster lookups in `_valueCount`.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11199/

try @graetzer's suggestion

---

tests/IResearch/IResearchViewCoordinator-test.cpp

Fix a compile warning when compiling arangodbtests.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11218/

fix compile warning in tests

---

CHANGELOG
arangod/Cluster/ClusterInfo.cpp
arangod/Cluster/ClusterInfo.h
arangod/ClusterEngine/ClusterCollection.cpp
arangod/ClusterEngine/ClusterCollection.h
arangod/StorageEngine/PhysicalCollection.cpp
arangod/StorageEngine/PhysicalCollection.h
arangod/VocBase/LogicalCollection.cpp
arangod/VocBase/LogicalCollection.h
tests/IResearch/IResearchViewDBServer-test.cpp

Add internal caching for LogicalCollection objects inside ClusterInfo::loadPlan
This allows avoiding the recreation of LogicalCollection objects that did not change from one loadPlan run to the next. It reduces CPU usage considerably on both Coordinators and DB-servers.
Collections with view links are currently excluded from the optimization (basically due to lack of time implementing it properly, this can be added in a seperate step).
This change is already covered by existing tests, such as *any cluster test, resilience tests*.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11237/

Add internal caching for LogicalCollection objects inside ClusterInfoloadPlan

---

CHANGELOG
arangod/Cluster/ClusterInfo.cpp
arangod/Cluster/ClusterInfo.h
arangod/ClusterEngine/ClusterCollection.cpp
arangod/ClusterEngine/ClusterCollection.h
arangod/StorageEngine/PhysicalCollection.cpp
arangod/StorageEngine/PhysicalCollection.h
arangod/VocBase/LogicalCollection.cpp
arangod/VocBase/LogicalCollection.h
tests/IResearch/IResearchViewDBServer-test.cpp

Add internal caching for LogicalCollection objects inside ClusterInfo::loadPlan
This allows avoiding the recreation of LogicalCollection objects that did not change from one loadPlan run to the next. It reduces CPU usage considerably on both Coordinators and DB-servers.
Collections with view links are currently excluded from the optimization (basically due to lack of time implementing it properly, this can be added in a seperate step).
This change is already covered by existing tests, such as *any cluster test, resilience tests*.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11231/

Add internal caching for LogicalCollection objects inside ClusterInfo::loadPlan

---

CHANGELOG
Documentation/DocuBlocks/Rest/Administration/post_admin_server_encryption.md
arangod/RocksDBEngine/RocksDBEngine.h

Add startup option `--rocksdb.encryption-key-rotation` to enable/disable the HTTP REST API for encryption key rotation.
The rotation API is disabled by default.
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/523
Docs PR: https://github.com/arangodb/docs/pull/511
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11263/

add toggle for encryption key rotation API

---

CHANGELOG
arangod/Graph/KShortestPathsFinder.cpp
arangod/Graph/KShortestPathsFinder.h
arangod/Graph/ShortestPathPriorityQueue.h
arangod/Graph/ShortestPathResult.h

Slightly improve performance of k-shortest-path queries, by reusing expensive objects
This change is already covered by existing tests, such as *AQL tests*.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11280/

forward-port changes from 3.7

---

CHANGELOG
js/apps/system/_admin/aardvark/APP/frontend/js/views/applicationDetailView.js

Fix the display of the Swagger UI of user-defined Foxx services in the web UI.
The display was broken after a recent update of jquery, so that trying to load the swagger UI with the service description into an iframe caused a JavaScript exception. This prevented the proper display of the services API UI.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11294/

fixed issue #12297

---

CHANGELOG
arangod/Agency/AgencyComm.cpp
arangod/Agency/RestAgencyHandler.cpp
arangod/Cluster/RestClusterHandler.cpp

Add option "redirectToLeader" to /_api/agency/state. This is a strictly internal API which is currently not documented. Without the option, it does not change in behaviour. The actual change in `/_api/cluster/agency-dump` only repairs a bug which can happen in rare cases when the request to the agency leader times out. In that case, stale agency data can be reported in the `.agency` component (which our debug scripts look at).

Fetch data for /_api/cluster/agency-dump always from leader.

---

CHANGELOG
arangod/Cluster/AgencyCallback.cpp
arangod/Cluster/AgencyCallback.h
tests/IResearch/IResearchFeature-test.cpp

A local AgencyCallback object does not need an AgencyComm instance.

Fix a unit test race.

---

arangod/Aql/ExecutionPlan.cpp
lib/Logger/LogAppender.cpp
lib/Logger/LogAppender.h
lib/Logger/LogBufferFeature.cpp
lib/Logger/LogGroup.h
lib/Logger/LogMacros.h
lib/Logger/LogThread.cpp
lib/Logger/LogThread.h
lib/Logger/LogTopic.cpp
lib/Logger/LogTopic.h
lib/Logger/LogVoidify.h
lib/Logger/Logger.cpp
lib/Logger/Logger.h
lib/Logger/LoggerFeature.cpp
lib/Logger/LoggerStream.cpp
lib/Logger/LoggerStream.h
tests/main.cpp

Currently audit logging owns its own LogAppenders and directly logs to them in the calling thread. On the other hand, the regular logger will generally dispatch messages to a background thread and write them out to the LogAppenders from there. This PR moves the audit appenders into the regular logging framework, introducing the notion of LogGroups. It then refactors the logging code a bit so that the audit logger and regular logger can call the same append method to dispatch messages to the background thread.
Enterprise component: https://github.com/arangodb/enterprise/pull/524
Jenkins: https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/11309/

Unify regular and audit logging

---

CHANGELOG
arangosh/Restore/RestoreFeature.cpp

Attempt to fix spurious failures (crashes) in arangorestore integration tests.
This change is already covered by existing tests, such as *restore integration test*.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11327/

wait until restore task queue is idle before shutting down

---

arangod/Aql/AqlValue.cpp
arangod/Aql/AqlValue.h
arangod/Aql/AstNode.cpp
arangod/Aql/DocumentExpressionContext.cpp
arangod/Aql/DocumentExpressionContext.h
arangod/Aql/Expression.cpp
arangod/Aql/ExpressionContext.h
arangod/Aql/Functions.cpp
arangod/Aql/KShortestPathsExecutor.cpp
arangod/Aql/QueryExpressionContext.h
arangod/Transaction/Context.h
tests/Aql/DateFunctionsTest.cpp
tests/Geo/GeoConstructorTest.cpp
tests/Geo/GeoFunctionsTest.cpp

Remove `AqlValue(VPackBuilder)` constructor, as it is simply redundant to `AqlValue(VPackSlice)`.
This change is already covered by existing tests, such as *all AQL tests*.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11323/

remove AqlValue(VPackBuilder) ctor, as it is just redundant

---

arangod/Cluster/ClusterInfo.cpp

Fix compiler warning in non-maintainer mode.
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11348/
http://jenkins.arangodb.biz:8080/job/arangodb-ANY-mac-packages/1039/

Avoid unused warning in non-maintainer compile

---

Documentation/DocuBlocks/Rest/Documents/post_create_document.md
Documentation/DocuBlocks/Rest/Documents/post_create_multiple_document.md

Change DocuBlock upstream: https://github.com/arangodb/docs/pull/509

Docs: overwrite requires _key attribute (sharding)

---

arangod/Cluster/ClusterInfo.cpp
arangod/Cluster/HeartbeatThread.cpp
arangod/IResearch/IResearchFeature.cpp
arangod/Scheduler/Scheduler.cpp
arangod/Scheduler/SupervisedScheduler.cpp
lib/Basics/ReadWriteLock.cpp
lib/Futures/Future.h

The lock is only required to serialize operations on the data the CV wait operations depends on. In some cases (e.g., when using atomics like in the ReadWriteLock) it is sufficient to lock and immediately unlock the mutex (i.e., an "empty critical secion") before calling notify.
Notifying a CV while holding the lock is a pessimization, because the notified thread will immediately try to acquire that lock and therefore be blocked again if the notifying thread has not yet released the lock.

Avoid notifying condition variables while holding a lock.

---

CHANGELOG
arangod/Transaction/Manager.cpp

This is the first part of a fix to not let hotbackup disturb imports. This allows a leader transaction to complete after the lockdown, since it can still start follower transactions to replicate the operations.

Let hotbackup only stop leader transactions.

---

CHANGELOG
arangod/Cluster/AgencyCallback.cpp
arangod/Cluster/AgencyCallback.h
tests/IResearch/IResearchFeature-test.cpp

A local AgencyCallback object does not need an AgencyComm instance.

Fix race bug in gtest.

---

CHANGELOG
arangod/Aql/SortedCollectExecutor.cpp
tests/js/server/aql/aql-optimizer-collect-methods.js

Fixed a bug where a `COLLECT` group, that should return `null`, would return `undefined` instead.

Bug fix/sorted collect reported null as undefined

---

CHANGELOG
arangod/Aql/OptimizerRules.cpp
tests/js/server/aql/aql-optimizer-rule-inline-subqueries.js

Don't apply optimizer rule `inline-subqueries` for subqueries that contain a COLLECT statement if the subquery itself is called from a FOR loop. Otherwise the COLLECT will be pulled out to caller level and be applied there, which may produce different results than when applied inside the subquery.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11466/

don't make inline-subqueries optimizer rule pull out COLLECTs

---

arangod/Aql/AqlItemBlock.cpp
arangod/Aql/AqlValue.cpp
arangod/Aql/AqlValue.h
arangod/Aql/Expression.cpp
arangod/Aql/FixedVarExpressionContext.cpp
arangod/Aql/Functions.cpp
arangod/Aql/Query.cpp
arangod/Aql/Query.h
arangod/Aql/QueryCursor.cpp
arangod/Aql/SortedCollectExecutor.cpp
arangod/Aql/SortedCollectExecutor.h
arangod/Aql/SubqueryEndExecutor.cpp
arangod/Aql/SubqueryEndExecutor.h
arangod/Graph/TraverserDocumentCache.cpp
arangod/IResearch/AqlHelper.h
arangod/IResearch/IResearchAnalyzerFeature.cpp
tests/IResearch/IResearchAnalyzerFeature-test.cpp

Reenable "Aqlvalue optimization" PR after temporarily reverting the changes.
There was a problem with the original PR which did not show up in our PR tests, but only when using ASan.
Memory was allocated in 3rdParty/velocypack/include/velocypack/Buffer.h using `malloc()` but deallocated in arangod/Aql/AqlValue.cpp using `delete[]`. ASan rightfully complained about this.
This PR should store the memory allocation type (new vs. malloc) inside the AqlValue for AqlValues of type `VPACK_MANAGED_SLICE`, so the correct deallocation method can be chosen at runtime.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11467/

reenable "Aqlvalue optimization" PR by @graetzer

---

CHANGELOG
lib/Futures/Future.h

This partially reverts an earlier commit:
https://github.com/arangodb/arangodb/pull/12206
After the above commit our clang compiled versions (mainly macOS) started to show undefined behavior.
I think in the case we have here, there is a race where a wait on the condition variable could trigger before the notify is send if the mutex is freed, which would cause the variable to be freed and causes undefined behavior
As @mpoeter has contributed the original version and has much more detail knowledge here I hope you have some time for a quick Review or comment here.
Additionally:
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11492/
> All new …

Attempt to fix undefined behaviour under Mac Os

---

CHANGELOG
arangod/Agency/FailedLeader.cpp
arangod/Cluster/FollowerInfo.h
arangod/Transaction/Methods.cpp

The fear is that a leader comes back exactly when the failover to
a different leader is happening, it could accept writes too early,
report success to the coordinator and then the client, and the failover
leads then to the writes being lost.
Measures taken:
1. After a restart, only accept writes once TakeoverShardLeadership has
run.
2. In FailedServer (failover code), add precondition that the chosen
failover candidate has not been deleted in the meantime.
Some of these problems have been observed in chaos runs but are not
easily reproducible.

Fix potential data loss when leader come back at an unlucky time.

---

arangod/Replication/DatabaseInitialSyncer.cpp
arangod/Replication/DatabaseInitialSyncer.h
arangod/Replication/GlobalInitialSyncer.cpp
arangod/Replication/ReplicationFeature.cpp

Enable concurrent synchronization of shards in the same database.
This change is already covered by existing tests, such as *replication tests, cluster tests, resilience tests*.
Started 2 runs:
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11346/
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11347/

allow concurrent synchronization of different shards per database

---

CHANGELOG
arangod/Agency/CleanOutServer.cpp
arangod/Agency/FailedLeader.cpp
arangod/Agency/Job.cpp
arangod/Agency/Job.h
arangod/Agency/ResignLeadership.cpp

In a failover or cleanout or resign leadership situation it is possible that in Current we have an already resigned leader. This needs to be taken into account when deciding which server to failover to or to move to. This fixes bad behaviour in corner cases.

Handle a few forgotten cases of already resigned leaders.

---

CHANGELOG
arangod/Agency/MoveShard.cpp
arangod/Agency/PathComponent.h
arangod/Cluster/Maintenance.cpp
arangod/RestHandler/RestAdminClusterHandler.cpp
arangod/RestHandler/RestAdminClusterHandler.h
tests/Agency/MoveShardTest.cpp
tests/Maintenance/MaintenanceTest.cpp
tests/js/server/resilience/move/moving-shards-cluster.js

During a move-shard job which moves the leader there is a
situation in which the old owner of a shard can reclaim ownership
(after having resigned already), with a small race where it allows to
write documents only locally, but then continue the move-shard to a
server without those documents. An additional bug in the MoveShard
Supervision job would then leave the shard in a bad configuration
with a resigned leader permanently in charge.
Additionally:

Bug fix/do not reclaim shard ownership.

---

CHANGELOG
arangod/VocBase/Methods/Transactions.cpp
arangosh/Shell/V8ClientConnection.cpp
lib/V8/v8-vpack.cpp
tests/js/common/shell/shell-transactions.js

Fixed issue #12304: insert in transaction causing com.arangodb.ArangoDBException: Response: 500, Error: 4 - Builder value not yet sealed. 
This happened when too deeply-nested documents (more than 63 levels of nesting) were inserted via an API that required a VelocyPack-to-JavaScript coversion or vice versa. 
While indefinite nesting is still not supported, the error message has been corrected from the internal HTTP 500 error "Builder value not yet sealed" to the correct HTTP 400 "Bad parameter".
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11510/

fixed issue #12304

---

CHANGELOG
arangod/Aql/Ast.cpp
arangod/Aql/Ast.h
tests/js/server/aql/aql-modify.js

Try to fix UPSERT behavior when fed with the same key, and a collection bind parameter.
Make UPSERT statement with collection bind parameter behave identical to its non-bind parameter counterpart.
For example, the query 
```
FOR d IN ["key_1", "key_2", "key_3", "key_1"] 
UPSERT d INSERT d UPDATE d IN @@collection
```
would fail with "unique constraint violation" when used with a collection bind parameter, but the equivalent query
```
FOR d IN ["key_1", "key_2", "key_3", "key_1"] 
UPSERT d INSERT d UPDATE d IN collectionName
```
with a hard-coded collection name would succeed. This is now fixed so both queries have the same behavior (no failure) in single server.
The fix does not yet work in the cluster. That will be addressed separately.
Potentially related issues: …

fix UPSERT behavior with collection bind parameter

---

Installation/Windows/Templates/NSIS.template.in

maybe its not yet invoked in /s mode?
https://arangodb.atlassian.net/browse/BTS-170 and more.

more debugging whether we found a previously installed arango

---

Documentation/DocuBlocks/Rest/Views/post_api_view_arangosearch.md

Add missing HTTP API descriptions to the relevant DocuBlock for these two features added in v3.7.1

API descriptions for primarySortCompression & storedValues

---

arangod/Aql/Functions.cpp
arangod/Cluster/ClusterInfo.cpp
arangod/VocBase/LogicalCollection.cpp
arangod/VocBase/LogicalCollection.h

Initially, we created the validation code with having multiple validators per collection in mind. But at some point we settled on having just one or zero schemas for each collection. This PR adjusts the underlying code to reflect that change:
There is either a schema present or no schema.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11632/

simplify validation code

---

CHANGELOG
arangod/GeneralServer/CommTask.cpp

Allow calling of REST APIs `/_api/engine/stats`, GET `/_api/collection` and GET `/_api/database/current` on followers in active failover deployments. 
This can help debugging and inspecting the follower.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11658/

allow calling additional APIs on followers

---

Documentation/DocuBlocks/Rest/Replication/get_api_replication_revisions_tree.md
Documentation/DocuBlocks/Rest/Replication/post_api_replication_revisions_tree.md
Documentation/DocuBlocks/Rest/Replication/put_api_replication_revisions_documents.md
Documentation/DocuBlocks/Rest/Replication/put_api_replication_revisions_ranges.md

Merkle tree replication is not in 3.7 GA, updating the minimum version number in which collections will be compatible in DocuBlock hint.
Note: it's not decided whether it will land in 3.8.0 or another release.

Docs: Fix revision based replication min version

---

arangod/Aql/AqlCallStack.cpp

Make AqlCallStack class slightly cheaper - this is a potential (minimal) performance improvement
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11670/

make AqlCallStack slightly cheaper

---

3rdParty/iresearch/core/index/index_writer.cpp
CHANGELOG

Backport for internal issue #747 fix to 3.5
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/11648/

Fix issue #747 (3.5) 

---

CHANGELOG
arangod/IResearch/IResearchLink.cpp
arangod/IResearch/IResearchLink.h
arangod/IResearch/IResearchRocksDBLink.h
arangod/IResearch/IResearchRocksDBRecoveryHelper.cpp
arangod/Indexes/Index.h
arangod/RocksDBEngine/RocksDBBuilderIndex.cpp
arangod/RocksDBEngine/RocksDBBuilderIndex.h
arangod/RocksDBEngine/RocksDBCollection.cpp
arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
arangod/RocksDBEngine/RocksDBEdgeIndex.h
arangod/RocksDBEngine/RocksDBIndex.cpp
arangod/RocksDBEngine/RocksDBIndex.h
arangod/RocksDBEngine/RocksDBVPackIndex.cpp
arangod/RocksDBEngine/RocksDBVPackIndex.h
tests/Mocks/StorageEngineMock.cpp

PR fixes possible deadlock inside ArangoSearch with removes followed by clear call inside same ArangoDB transaction.
So to perform index truncation ArangoSearch waits for removes transaction to be committed (or rollbacked) but it waits inside same transaction so it never ends. This would be the issue now only for already  EOLed MMFiles storage engine but could raise again during future development.
To fix this afterTruncate index handler is made aware of current transaction. For ArangoSearch - transaction state is wiped before truncation (anyway truncation will overwrite all operations).
This case is coverd existing recovery tests namely: 
view-arangosearch-link-populate-truncate.js
view-arangosearch-link-populate-truncate-no-flushthread.js …

Fix internal issue BTS-183

---

CHANGELOG
Documentation/DocuBlocks/Rest/Administration/get_admin_statistics.md
arangod/Statistics/Descriptions.cpp
arangod/Statistics/StatisticsWorker.cpp
arangod/V8Server/V8DealerFeature.cpp
arangod/V8Server/V8DealerFeature.h
arangod/V8Server/v8-statistics.cpp

Added metrics for V8 contexts usage:
* `arangodb_v8_context_alive`: number of V8 contexts currently alive.
* `arangodb_v8_context_busy`: number of V8 contexts currently busy. 
* `arangodb_v8_context_dirty`: number of V8 contexts currently dirty.
* `arangodb_v8_context_free`: number of V8 contexts currently free. 
* `arangodb_v8_context_max`: maximum number of concurrent V8 contexts.
* `arangodb_v8_context_min`: minimum number of concurrent V8 contexts.
Docs PR: https://github.com/arangodb/docs/pull/538
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11688/

add metrics for V8 contexts usage

---

arangod/Network/NetworkFeature.cpp

Underscore that the `--network.*` options are for cluster-internal communication.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11709/

underscore the purpose of config options a bit more

---

arangod/Cluster/ClusterInfo.cpp

will be repaired later, therefore it should not be WARN

---

CHANGELOG
arangod/Pregel/Algos/DMID/DMID.cpp
arangod/RocksDBEngine/RocksDBEngine.cpp
lib/Basics/files.cpp
lib/Basics/files.h
lib/Logger/LogAppenderFile.cpp

Added new metrics for the total and the free disk space for the mount used for the RocksDB database directory:
* `arangodb_rocksdb_free_disk_space`: provides the free disk space for the mount, in bytes
* `arangodb_rocksdb_total_disk_space`: provides the total disk space of the mount, in bytes
Should work on Linux already, may not yet work on MacOS or Windows.
Definitely needs manual testing by someone with the respective OSes available.
Docs PR: https://github.com/arangodb/docs/pull/539
Needs to be used in k8s operator as well, as filesystems may behave different there.

expose disk space metrics for RocksDB database directory

---

arangod/Cluster/ClusterInfo.cpp

will be repaired later, therefore it should not be WARN (#12569)

---

arangod/StorageEngine/RocksDBOptionFeature.cpp

Add "introduced in" info to new RocksDB startup options.
- GitHub issue / Jira ticket number: #11468 #11721

Add version info to RocksDB options new in v3.7.1

---

arangod/GeneralServer/GeneralCommTask.cpp

Fix BTS-200: https://arangodb.atlassian.net/browse/BTS-200
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11775/

fix BTS-200

---

tests/js/client/server_parameters/test-idle-timeouts.js

Adds tests for keep-alive timeouts with HTTP/1, HTTP/2 and VST protocols.
Currently only tests that the timeout is not applied when running a query with a longer runtime (e.g. timeout=5s, query runtime=10s).
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11784/

added test for keep-alive timeout

---

CHANGELOG
arangod/Aql/RegisterPlan.cpp
tests/js/server/aql/aql-registers-limit.js

Enforce a maximum result register usage limit in AQL queries. In an AQL query, every user-defined or internal (unnamed) variable will need a register to store results in.
AQL queries that use more result registers than allowed (currently 1000) will now abort deterministically during the planning stage with error 32 (`resource limit exceeded`) and the error message "too many registers (1000) needed for AQL query".
Before this fix, an AQL query that used more than 1000 result registers crashed the server when assertions were turned on, and the behavior was undefined when assertions were turned off.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11786/

fix undefined behavior in issue #9834

---

CHANGELOG
arangod/Cluster/ClusterMethods.cpp
arangod/Cluster/ClusterMethods.h
arangod/ClusterEngine/ClusterCollection.cpp
arangod/ClusterEngine/ClusterCollection.h
arangod/RestHandler/RestCollectionHandler.cpp
arangod/RestHandler/RestCollectionHandler.h
arangod/RocksDBEngine/RocksDBCollection.cpp
arangod/RocksDBEngine/RocksDBCollection.h
arangod/StorageEngine/PhysicalCollection.cpp
arangod/StorageEngine/PhysicalCollection.h
arangod/V8Server/v8-collection.cpp
arangod/VocBase/LogicalCollection.cpp
arangod/VocBase/LogicalCollection.h
js/client/modules/@arangodb/arango-collection.js
tests/Mocks/StorageEngineMock.cpp
tests/Mocks/StorageEngineMock.h
tests/js/common/shell/shell-figures-rocksdb.js

Added `details` option to figures command of a collection: `collection.figures(details)`
Setting `details` to `true` will return extended storage engine-specific details to the figures. The details are intended for debugging ArangoDB itself and their format is subject to change. Currently, the details are returned for the RocksDB storage engine only.
By default, `details` is set to `false`, so no details are returned and the behavior is identical to previous versions of ArangoDB.
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/545
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11781/

added "details" option to collection figures

---

CHANGELOG
arangod/Aql/Ast.cpp
arangod/Aql/Functions.cpp
arangod/Aql/Parser.cpp
arangod/Aql/Parser.h
arangod/Aql/QueryWarnings.cpp
arangod/Aql/QueryWarnings.h
arangod/Aql/grammar.cpp
arangod/Aql/grammar.y

Ensure that the argument to an AQL OPTIONS clause is always an object which does not contain any dynamic (run-time) values. 
Previously, this was only enforced for traversal options and options for data-modification queries. This change extends the check to all occurrences of OPTIONS.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11800/

Validate OPTIONS argument

---

CHANGELOG
arangod/Aql/QueryOptions.cpp
arangod/Aql/QueryOptions.h
arangod/RestServer/QueryRegistryFeature.cpp
arangod/RestServer/QueryRegistryFeature.h
tests/js/client/server_parameters/test-query-max-runtime.js

* Added startup option `--query.max-runtime` to limit the maximum runtime of
all AQL queries to a specified threshold value (in seconds). By default,
the threshold is 0, meaning that the runtime of AQL queries is not limited.
Setting it to any positive value will restrict the runtime of all AQL
queries unless it is overwritten in the per-query "maxRuntime" query option.
Please note that setting this option will affect *all* queries in all
databases, and also queries issues for administration and database-internal
purposes.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11819/

Added option `--query.max-runtime`

---

CHANGELOG
js/apps/system/_admin/aardvark/APP/frontend/js/views/loginView.js

Whenever an LDAP user was logged out due to a failed LDAP search, the UI kept infinitely reloading the login window. Another login was only possible with a new browser-tab. This pull request changes the behavior, such that the user is entirely logged out when the jwt login is not valid anymore and a subsequent login can be performed in the same browser-tab. 
Additionally:
Please note that for legal reasons we require you to sign the [Contributor …

Fix infinite UI reload

---

CHANGELOG
arangod/Statistics/StatisticsWorker.cpp

Exposes the following metrics via the `/_admin/metrics` endpoint:
- arangodb_http_request_statistics_total_requests: Total number of HTTP requests
- arangodb_http_request_statistics_async_requests: Number of asynchronously executed HTTP requests
- arangodb_http_request_statistics_http_delete_requests: Number of HTTP DELETE requests
- arangodb_http_request_statistics_http_get_requests: Number of HTTP GET requests
- arangodb_http_request_statistics_http_head_requests: Number of HTTP HEAD requests
- arangodb_http_request_statistics_http_options_requests: Number of HTTP OPTIONS requests
- arangodb_http_request_statistics_http_patch_requests: Number of HTTP PATCH requests
- arangodb_http_request_statistics_http_post_requests: Number of HTTP POST requests
- …

Expose request metrics

---

CHANGELOG
arangod/Scheduler/SupervisedScheduler.cpp
arangod/Scheduler/SupervisedScheduler.h

Exposed the following metrics via the `/_admin/metrics` endpoint:
- `arangodb_scheduler_awake_threads`: Number of awake worker threads
- `arangodb_scheduler_num_worker_threads`: Number of worker threads
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11862/

expose scheduler threads metrics

---

CHANGELOG
arangod/Replication/DatabaseInitialSyncer.cpp
arangod/Replication/ReplicationMetricsFeature.cpp
arangod/Replication/ReplicationMetricsFeature.h
arangod/Replication/TailingSyncer.cpp
arangod/RocksDBEngine/RocksDBEngine.cpp
arangod/RocksDBEngine/RocksDBIncrementalSync.cpp
lib/Basics/files.cpp
lib/Basics/files.h

* Added replication metrics `arangodb_replication_initial_sync_bytes_received` for the number of bytes received during replication initial sync operations and `arangodb_replication_tailing_bytes_received` for the number of bytes received for replication tailing requests. Also added `arangodb_replication_failed_connects` to track the number of connection failures or non-OK response during replication.
* Added metrics `rocksdb_free_inodes` and `rocksdb_total_inodes` to track the number of free inodes and the total/maximum number of inodes for the file system the RocksDB database directory is located in. These metrics will always be 0 on Windows.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11861/

more metrics

---

arangod/RocksDBEngine/RocksDBEngine.cpp
arangod/Statistics/StatisticsWorker.cpp

Fix some smaller metrics-related issues:
* feed metric "arangodb_http_request_statistics_async_requests" with correct input value
* fix a typo in description of metric "arangodb_http_request_statistics_http_patch_requests"
* remove requirement that metrics descriptions have to end with `\n` in order to work. This is unexpected and has led to a few metrics not being reported properly.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11845/

slighty clean up the metrics generation code

---

CHANGELOG
arangod/Scheduler/Scheduler.h
arangod/Scheduler/SupervisedScheduler.cpp
arangod/Scheduler/SupervisedScheduler.h
tests/Cluster/RebootTrackerTest.cpp

Added scheduler thread creation/destruction metrics:
- `arangodb_scheduler_threads_started`: Number of scheduler threads started
- `arangodb_scheduler_threads_stopped`: Number of scheduler threads stopped
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11865/

added extra metrics for scheduler threads

---

CHANGELOG
arangod/Agency/Supervision.cpp

Make the reboot tracker catch failed coordinators, too.
Previously the reboot tracker was invoked only when a DB server failed or was restarted, and when a coordinator was restarted.
Now it will also act if a coordinator just fails (without restart).
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11876/

Make the reboot tracker catch failed coordinators, too.

---

arangod/Agency/Supervision.cpp

Follow-up PR to https://github.com/arangodb/arangodb/pull/12606
Make the reboot tracker catch failed coordinators, too.
Previously the reboot tracker was invoked only when a DB server failed or was restarted, and when a coordinator was restarted.
Now it will also act if a coordinator just fails (without restart).
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11880/

fix reboot tracker

---

3rdParty/fuerte/src/GeneralConnection.h
3rdParty/fuerte/src/H1Connection.h
arangod/Cluster/ClusterFeature.cpp
arangod/Network/ConnectionPool.cpp
arangod/Network/ConnectionPool.h
arangod/Network/Methods.cpp
arangod/Network/NetworkFeature.cpp
tests/AsyncAgencyComm/AsyncAgencyCommTest.cpp
tests/IResearch/IResearchAnalyzerFeature-test.cpp
tests/IResearch/IResearchFeature-test.cpp
tests/Mocks/Servers.cpp
tests/Network/ConnectionPoolTest.cpp
tests/Network/MethodsTest.cpp

Make sure the connection pool removes idle connections before the remote closes them

Remove idle connections

---

CHANGELOG
arangod/Statistics/StatisticsFeature.cpp
arangod/Statistics/StatisticsFeature.h

Fix undefined behavior when accessing the `/_admin/metrics` API to retrieve
metrics when the server statistics history bookkeeping was turned off via
`--server.statistics-history false`. The default value for this option is
`true`, so the effect is limited to installations which have changed the
default and are using the API.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11931/

Fix accessing metrics API when statistics history is turned off

---

arangod/Transaction/Methods.cpp

Cleanup of leftovers (truncate) from https://github.com/arangodb/arangodb/pull/12598
Jenkins: https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/11804/

Add truncate context for audit logging

---

js/common/modules/@arangodb/common.js

Turn off upgrade checks in arangod in alpha/beta/preview Enterprise versions, too.
Previously it was already turned off for Enterprise versions, but only for stable releases.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11897/

turn off upgrade check even for alpha/beta/preview versions

---

arangod/VocBase/Methods/AqlUserFunctions.cpp

Simplify the removal code for AQL UDFs from running an AQL query to a single-key remove operation
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11953/

don't run a full-fledged AQL query to remove an AQL UDF by key

---

arangod/Actions/ActionFeature.cpp
arangod/CMakeLists.txt
arangod/GeneralServer/GeneralServerFeature.cpp
arangod/RestHandler/RestAdminExecuteHandler.cpp
arangod/RestHandler/RestAdminRoutingHandler.cpp
arangod/RestHandler/RestControlPregelHandler.cpp
arangod/RestHandler/RestTasksHandler.cpp
arangod/RestHandler/RestTransactionHandler.cpp
arangod/RestServer/DatabaseFeature.cpp
arangod/RestServer/DatabaseFeature.h
arangod/Scheduler/SchedulerFeature.cpp
arangod/Scheduler/SchedulerFeature.h
arangod/Statistics/StatisticsFeature.cpp
arangod/V8Server/V8DealerFeature.cpp
arangod/V8Server/V8DealerFeature.h
arangod/V8Server/v8-dispatcher.cpp
arangod/V8Server/v8-dispatcher.h
arangod/VocBase/Methods/Databases.cpp
arangod/VocBase/Methods/Tasks.cpp
js/client/bootstrap/modules/internal.js
js/common/bootstrap/modules/internal.js
tests/js/client/server_parameters/test-javascript-disabled.js

This PR adds safeguards against using V8 internally in environments that have JavaScript turned off via the `--javascript.enabled false` option.
The PR also moves a bit of V8 context initialization code from the Scheduler and the DatabaseFeature into the V8DealerFeature, so it is now all in one place.
Finally it adds a new metrics that tracks the total time it took to create V8 contexts.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11960/

Safeguards against using V8 when JavaScript is turned off

---

arangod/Aql/QueryRegistry.cpp
arangod/Auth/UserManager.cpp

The following existing code
```
auth::User user = auth::User::fromDocument(s);
result.try_emplace(user.username(), std::move(user));
```
moves frod `user` and accesses a member function of `user` in the same expression.
In practice, this should be safe, because the map's insert key should be calculated first, and the value is only moved from if the key does not exist in the map.
But I couldn't find any proof that this is guaranteed to be safe.
So changing it to an intentional and explicit copy to avoid potential UB:
```
auth::User user = auth::User::fromDocument(s);
// intentional copy, as we are about to move-away from user
std::string username = user.username();
result.try_emplace(std::move(username), std::move(user));
```
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12004/

take a copy before moving from the same object

---

arangod/Cluster/ClusterInfo.cpp
arangod/RestHandler/RestRepairHandler.cpp
arangod/RestHandler/RestStatusHandler.cpp
tests/js/client/shell/shell-admin-status.js

For generating the "hash" property value, the current Plan was retrieved to find out the number of Coordinators and DBServers. The return value of getPlan seems to have changed in 3.7, and the code here was not adjusted. 
This PR fixes it and adds a test.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12008/

fix "hash" property in /_admin/status?overview=true case

---

CMakeLists.txt

disabled range-loop-analysis for clang version 12.0.0 up to 12.1.0

---

arangod/GeneralServer/H2CommTask.cpp
arangod/GeneralServer/H2CommTask.h
arangod/GeneralServer/VstCommTask.cpp
arangod/GeneralServer/VstCommTask.h

Forward port of #12741
This PR adjusts the internal write queue size in server-side VST connections, so that the write queue does not overflow in case a client sends a massive amount of requests and the server produces responses to them at a faster rate than they can be sent out.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12031/

Use dynamically-sized response queue to prevent full queues

---

CHANGELOG
arangod/IResearch/IResearchFeature.cpp

backport of https://github.com/arangodb/arangodb/pull/12736

bug-fix-3.5/internal-issue-#762

---

CHANGELOG
arangod/Transaction/Methods.cpp

There are two cases in which a shard follower refuses to execute a
synchronous replication request by a shard leader.
One is if the follower has in the meantime taken over leadership for the
shard. The other is if it is simply no longer following that leader, for
example because of a restart or because it was dropped in the meantime
by another thread.
In the first case it is correct behaviour for the leader to run into an
error, because most likely it is no longer actually the leader.
In the second case it is better to drop the follower (even if already
dropped) and move on without an error.
This PR implements fixes this behaviour.
- Fix behaviour of a shard leader if follower does not play ball.
- Improve comment.
- CHANGELOG.

Fix shard leader behaviour if a follower does not play ball.

---

arangod/RestServer/DatabaseFeature.cpp

The announced default value for the new `--database.old-system-collections` options is `false`, but the original PR set it to `true` in the code unintentionally. This PR rectifies that.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12115/

fix default value for `--database.old-system-collections`

---

arangod/Aql/ModificationExecutorHelpers.cpp
arangod/Aql/OptimizerRulesCluster.cpp
tests/js/server/aql/aql-optimizer-optimize-cluster-single-document-operations.js

Prevent running into an assertion failure for numeric `_key` values.
Single-document AQL queries that are executed with a hard-coded, but (invalid) numeric literal value for `_key` can trigger an assertion failure in the cluster, due to the value of _key being interpreted as a string.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12098/

Bug fix/prevent assertion failure for numeric key

---

CHANGELOG
arangod/Agency/Constituent.cpp
arangod/Aql/ExecutionBlockImpl.cpp
arangod/Cluster/AgencyCallback.cpp
arangod/Cluster/AgencyCallback.h
arangod/Cluster/AgencyCallbackRegistry.cpp
arangod/Cluster/AgencyCallbackRegistry.h
arangod/Cluster/ClusterInfo.h
arangod/Cluster/FollowerInfo.h
arangod/Cluster/MaintenanceFeature.cpp
arangod/Cluster/RestAgencyCallbacksHandler.cpp
arangod/Graph/KShortestPathsFinder.h
arangod/IResearch/IResearchView.cpp

* Slightly improve parallelism for creating agency callbacks, by not creating the pseudorandom callback ids under the lock.
* Avoid unnecessary comparisons in AgencyCallback::checkValue(...).
* Added metric `arangodb_agency_callback_registered counter` for tracking the total number of agency callbacks that were registered.
* BE -> AE
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12089/

Bug fix/cleanup 20201003

---

arangod/Agency/RestAgencyHandler.cpp

Remove an invalid assertion that sporadically triggered at agency startup in maintenance mode only.
The assertion has been removed in 3.7 and devel for a while already.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12106/

remove wrong assertion that can ruin agency startup in maintainer mode

---

arangod/Network/Methods.cpp
arangod/Network/Methods.h
arangod/Network/types.h
arangod/Transaction/V8Context.cpp

Make sure to never have a null request member and actually set the response if `response.error == NoError`.
Additionally we now avoid recreating the request object everytime
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/12101/

Make sure response is set if no error is indicated

---

arangod/GeneralServer/GeneralServerFeature.cpp

Disable `/_api/tasks` REST handler automatically in case JavaScript is turned off.
The API is dysfunctional then anyway, and turning it off completely prevents undefined behavior when invoking it accidentially
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12105/

disable /_api/tasks API in case JavaScript is turned off

---

arangod/Aql/ModificationExecutorHelpers.cpp
arangod/Aql/OptimizerRulesCluster.cpp
tests/js/server/aql/aql-optimizer-optimize-cluster-single-document-operations.js

Prevent running into an assertion failure for numeric `_key` values.
Single-document AQL queries that are executed with a hard-coded, but (invalid) numeric literal value for `_key` can trigger an assertion failure in the cluster, due to the value of _key being interpreted as a string.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12100/

Bug fix 3.6/prevent assertion failure for numeric key

---

CHANGELOG
arangod/Cluster/SynchronizeShard.cpp
arangod/Replication/DatabaseInitialSyncer.cpp
arangod/Replication/DatabaseInitialSyncer.h
arangod/Replication/DatabaseTailingSyncer.cpp
arangod/Replication/GlobalInitialSyncer.cpp
arangod/Replication/GlobalInitialSyncer.h
arangod/Replication/InitialSyncer.h
arangod/Replication/TailingSyncer.cpp
arangod/Replication/utilities.cpp
arangod/Replication/utilities.h
arangod/Statistics/ConnectionStatistics.cpp
arangod/Statistics/ConnectionStatistics.h
arangod/Statistics/Descriptions.cpp
arangod/Statistics/RequestStatistics.cpp
arangod/Statistics/StatisticsFeature.cpp
arangod/Statistics/StatisticsFeature.h
arangod/Statistics/StatisticsWorker.cpp
arangod/Transaction/Methods.cpp
arangod/V8Server/v8-statistics.cpp
js/apps/system/_admin/aardvark/APP/frontend/js/models/arangoCollectionModel.js
js/apps/system/_admin/aardvark/APP/frontend/js/templates/modalCollectionInfo.ejs
js/apps/system/_admin/aardvark/APP/frontend/js/views/infoView.js

This PR improves observability in the following ways:
* Add database, shard name and error information to several shard-related log messages.
* Display shard names of a collection in the web interface when in the details view of the collection.
* Added HTTP requests metrics for tracking the number of superuser and normal user requests separately:
- `arangodb_http_request_statistics_superuser_requests`: Total number of HTTP requests executed by superuser/JWT
- `arangodb_http_request_statistics_user_requests`: Total number of HTTP requests executed by clients
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12091/

improvements for observability

---

arangod/Aql/ModificationExecutorHelpers.cpp
arangod/Aql/OptimizerRulesCluster.cpp
tests/js/server/aql/aql-optimizer-optimize-cluster-single-document-operations.js

Prevent running into an assertion failure for numeric `_key` values.
Single-document AQL queries that are executed with a hard-coded, but (invalid) numeric literal value for `_key` can trigger an assertion failure in the cluster, due to the value of _key being interpreted as a string.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12099/

Bug fix 3.7/prevent assertion failure for numeric key

---

CHANGELOG
arangod/Aql/AllRowsFetcher.cpp
arangod/Aql/AqlItemBlockInputMatrix.cpp
arangod/Aql/AqlItemMatrix.cpp
arangod/Aql/AqlItemMatrix.h
arangod/Aql/SortExecutor.cpp
tests/Aql/AqlItemMatrixTest.cpp
tests/Aql/InputRangeTest.cpp
tests/js/server/aql/aql-sort.js

SORT inside a subquery could sometimes swallow part of its input when it crossed block boundaries.

Fix SORT in subqueries when crossing block boundaries

---

CHANGELOG
arangod/Agency/AddFollower.cpp
arangod/Agency/FailedFollower.cpp
arangod/Agency/FailedLeader.cpp
arangod/Agency/Job.cpp
arangod/Agency/Job.h
arangod/Agency/MoveShard.cpp
arangod/Cluster/FollowerInfo.cpp
arangod/Cluster/Maintenance.cpp
arangod/Cluster/v8-cluster.cpp
tests/js/server/resilience/failover-failure/resilience-synchronous-repl-failureAt-cluster.js
tests/js/server/resilience/failover-view/resilience-synchronous-repl-with-arangosearch-view-cluster-grey.js
tests/js/server/resilience/failover/resilience-synchronous-repl-cluster.js
tests/js/server/resilience/move-view/moving-shards-with-arangosearch-view-grey-cluster-disabled.js
tests/js/server/resilience/move/moving-shards-cluster.js

Fix failoverCandidates for servers not in Plan.
Problem: we must never fail over to a server which is not in Plan
because it might not have the data.
TODO:
add a server to the Plan which is in failoverCandidates for this
shard or any of the ones with distributeShardsLike.
failoverCandidates.

Ensure failoverCandidates have no servers not in Plan.

---

CHANGELOG
Documentation/DocuBlocks/Rest/Administration/get_admin_modules_flush.md
arangod/Agency/State.cpp
lib/Logger/LogTopic.cpp
lib/Logger/Logger.h

Added optional verbose logging for agency write operations.
This logging is configurable by using the new log topic "agencystore".
The following log levels can be used for for the "agencystore" log topic to log writes to the agency:
* DEBUG: will log all writes on the leader
+ TRACE: will log all writes on both leaders and followers
The default log level for the "agencystore" log topic is WARN, meaning no agency writes will be logged.
Turning on this logging can be used for auditing and debugging, but it is not recommended in the general case, as it can lead to large amounts of data being logged, which can have a performance impact and will lead to higher disk space usage.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12164/

Added optional verbose logging for agency write operations

---

CHANGELOG
arangod/Aql/AllRowsFetcher.cpp
arangod/Aql/AqlItemBlockInputMatrix.cpp
arangod/Aql/AqlItemMatrix.cpp
arangod/Aql/AqlItemMatrix.h
arangod/Aql/SortExecutor.cpp
tests/Aql/AqlItemMatrixTest.cpp
tests/Aql/InputRangeTest.cpp
tests/js/server/aql/aql-sort.js

Backport of https://github.com/arangodb/arangodb/pull/12752

[3.7] Fix SORT in subqueries when crossing block boundaries

---

js/apps/system/_admin/aardvark/APP/frontend/js/collections/arangoDocuments.js

Always show documents for a collection in web interface, regardless of what `collection.count()` says. This fixes a potential race between fetching the count and fetching the documents.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12224/

always show documents for a collection in web interface

---

CHANGELOG
Documentation/DocuBlocks/Rest/Administration/get_admin_modules_flush.md
arangod/Agency/State.cpp
lib/Logger/LogTopic.cpp
lib/Logger/Logger.h

Added optional verbose logging for agency write operations.
This logging is configurable by using the new log topic "agencystore".
The following log levels can be used for for the "agencystore" log topic to log writes to the agency:
* DEBUG: will log all writes on the leader
+ TRACE: will log all writes on both leaders and followers
The default log level for the "agencystore" log topic is WARN, meaning no agency writes will be logged.
Turning on this logging can be used for auditing and debugging, but it is not recommended in the general case, as it can lead to large amounts of data being logged, which can have a performance impact and will lead to higher disk space usage.
Backport of https://github.com/arangodb/arangodb/pull/12793 …

Added optional verbose logging for agency write operations (#12793)

---

js/client/modules/@arangodb/arango-database.js

The client (arangosh) needs to re-assure with the server what the current state
is after the error. A cache must not stop that from happening - hence
flush it.
This miss-behaviour was discovered while using arangosh for load-testing.

If we fail to switch the database, flush the cache too.

---

arangosh/Import/ImportFeature.cpp

- validate whether the import file exists early so we can error out
before attempting to connect the server
- if we have a `--file` argument don't swallow unused option.
this improves the useability as seen in https://github.com/arangodb/arangodb/issues/12649

better validate commandline options

---

arangosh/Restore/RestoreFeature.cpp
arangosh/Utils/ManagedDirectory.cpp

arangoimport improperly handled filenames with less than 3 characters.
The specified input filename was checked for a potential ".gz" ending, but the check required the filename to have at least 3 characters.
This is now fixed.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12239/

Fix an issue in arangoimport filename handling

---

CHANGELOG
js/common/bootstrap/errors.js
lib/Basics/errors.dat
lib/Basics/voc-errors.cpp
lib/Basics/voc-errors.h

When inserting a document with a non-conforming key pattern into a smart vertex collection, the response error code and message are 1466 (ERROR_CLUSTER_MUST_NOT_SPECIFY_KEY) and "must not specify _key
for this collection".
This is misleading, because it is actually allowed to specify a key value for documents in such collection. However, there are some
restrictions for valid key values (e.g. the key must be a string and contain the smart graph attribute value at the front, followed by a
colon.
If any of these restrictions are not met, the server currently responds with "must not specify key for this collection", which is
misleading. This PR rectifies it so that the server responds with error 4003 (ERROR_KEY_MUST_BE_PREFIXED_WITH_SMART_GRAPH_ATTRIBUTE) and message "in smart vertex …

don't respond with misleading error in smart vertex collections

---

arangod/Cluster/ClusterMethods.cpp
arangod/IResearch/IResearchAnalyzerFeature.cpp
arangod/Sharding/ShardDistributionReporter.cpp

calling slices() on the `response` member in arangodb::network::Response is potentially unsafe if there are no prior checks, as `response` can be a nullptr.
This is in response to a test failure observed in http://172.16.10.101:8080/job/arangodb-matrix-pr-linux/13716/EDITION=community,STORAGE_ENGINE=rocksdb,TEST_SUITE=cluster,limit=(linux&&test)%7C%7Cgce/
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/559
Backport of https://github.com/arangodb/arangodb/pull/12760
- [] Backports required for: potentially 3.6
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12096/

avoid usage of potentially unsafe slices() method

---

arangod/Network/Methods.cpp
arangod/Network/Methods.h
arangod/Network/types.h

Make sure to never have a null request member and actually set the response if response.error == NoError.
Additionally we now avoid recreating the request object everytime
backport of https://github.com/arangodb/arangodb/pull/12766
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/12287/

Make sure response is set if no error is indicated (#12766)

---

lib/Basics/process-utils.cpp
lib/Basics/process-utils.h

Remove avoidable copies of arguments vectors.
This is a micro optimization.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12357/

nono copying

---

arangod/Cluster/ClusterMethods.cpp
arangod/Cluster/ClusterMethods.h
arangod/Cluster/DropCollection.cpp
arangod/Cluster/EnsureIndex.cpp
arangod/RestHandler/RestReplicationHandler.cpp
arangod/VocBase/Methods/Collections.cpp
arangod/VocBase/Methods/Databases.cpp

Don't log errors into the log in expected cases
In case of "expected" errors they are returned to the end user or client application, so they can handle the error. there is no need to additionally log these errors into the log and cause alerting.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12346/

Bug fix/cleanup 20201016

---

tests/js/server/replication/aql/replication-aql.js
tests/js/server/replication/fuzz/replication-fuzz-global.js
tests/js/server/replication/fuzz/replication-fuzz.js
tests/js/server/replication/ongoing/32/replication-ongoing-32.js
tests/js/server/replication/ongoing/frompresent/32/replication-ongoing-frompresent-32.js
tests/js/server/replication/ongoing/frompresent/replication-ongoing-frompresent.js
tests/js/server/replication/ongoing/global/replication-ongoing-global.js
tests/js/server/replication/ongoing/global/spec/replication-ongoing-global-spec.js
tests/js/server/replication/ongoing/replication-ongoing.js
tests/js/server/replication/random/replication-random.js
tests/js/server/replication/static/replication-static.js
tests/js/server/replication/sync/replication-sync.js

its easier to have the last argument be the other node than the first (which obviously is the same in the case of 1 argument)

since ARGUMENTS is const for .js 

---

arangod/RocksDBEngine/RocksDBMetaCollection.cpp
arangod/RocksDBEngine/RocksDBMetadata.cpp
arangod/RocksDBEngine/RocksDBReplicationContext.cpp
arangod/RocksDBEngine/RocksDBTransactionCollection.cpp
arangod/RocksDBEngine/RocksDBTransactionState.cpp

In a few places, we make counter adjustments in read-only contexts, in order to correct a counter which is out of sync with the underlying document store. This leads to broken invariants in the sequence tracking we use for these counters. This PR updates these cases to correctly place blockers and conditionally force a write of the settings in order to restore the invariants.
Jenkins: https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/12384/

[3.7] Fix read-only counter adjustments

---

arangod/Agency/AgencyComm.cpp
arangod/Agency/AgencyComm.h
arangod/Agency/AgencyFeature.cpp
arangod/Agency/AsyncAgencyComm.cpp
arangod/Aql/RemoteExecutor.cpp
arangod/Aql/RestAqlHandler.cpp
arangod/Network/Methods.cpp
arangod/Network/Utils.cpp
arangod/Network/Utils.h
arangod/Replication/DatabaseInitialSyncer.cpp
arangod/Replication/DatabaseTailingSyncer.cpp
arangod/Replication/GlobalInitialSyncer.cpp
arangod/Replication/GlobalTailingSyncer.cpp
arangod/Replication/TailingSyncer.cpp
arangod/Replication/utilities.cpp
arangod/Replication/utilities.h
lib/ApplicationFeatures/ConfigFeature.cpp
lib/ApplicationFeatures/V8SecurityFeature.cpp

Make sure the x-arango-source header is set for all internal requests.
There is currently no consequence from setting or not setting this header except that there will be additional request logging in log level DEBUG if the header is set. It is not used for anything else, but it may help with debugging. Now it is set consistently for internal requests.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12426/

make sure the x-arango-source header is set for all internal requests

---

arangod/RestHandler/RestReplicationHandler.cpp

Fix a potential lifecycle issue, when `_vocbase` is used from inside the callback, but the object has been destroyed/replaced already. This is an issue in current devel only. 3.7 or 3.6 are not affected.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12454/

fix potential lifecycle issue

---

arangod/Cluster/SynchronizeShard.cpp
arangod/RestHandler/RestReplicationHandler.cpp

Fix the shard-getting-in-sync procedure for MMFiles. 
We recently disabled the getting-in-sync shortcut, which is the right solution for the RocksDB storage engine, but MMFiles seems to depend on it. These changes were not released yet, but were still in testing. During testing it turned out that the changes harm the getting-in-sync protocol for MMFiles.
This PR reenables the shortcut just for MMFiles, and also avoids calling a non-implemented API for recalculating collection counts also in case the storage engine is MMFiles.
The test plan for this PR is to run `scripts/unittest dump --cluster true --storageEngine mmfiles`, which should show no replication errors with this PR.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12487/

fix the getting-in-sync of shards for MMFiles collections

---

arangod/RocksDBEngine/RocksDBReplicationContext.cpp
arangod/RocksDBEngine/RocksDBReplicationContext.h
arangod/RocksDBEngine/RocksDBReplicationManager.cpp
arangod/RocksDBEngine/RocksDBReplicationManager.h
arangod/RocksDBEngine/RocksDBRestReplicationHandler.cpp
tests/js/client/shell/shell-collection-counts-cluster.js

Fixes potential races when applying count updates on leaders if multiple followers of the same shard try to get in sync at the very same time, and all try to apply count updates individually.
This PR introduces a "leadership" for applying count updates, simply by scanning all existing ReplicationContexts for the same shard when creating a ReplicationContext on a leader. If there exists a ReplicationContext for the same shard already, then that context is considered responsible. Otherwise, the to-be-created context will assume responsibility for applying potential count updates.
The changes can be verified by running the following test (needs 3 DB servers):
```
scripts/unittest shell_client --cluster true --test tests/js/client/shell/shell-collection-counts-cluster-rocksdb.js --dbServers 3 …
```

fix count updates on leaders with multiple followers

---

CHANGELOG

This is just CHANGELOG PR.
The fix is enterprise only
Backport of https://github.com/arangodb/arangodb/pull/12900
Additionally:
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/12468/

Bug fix 3.7/indexes on disjoint smart edges

---

CHANGELOG
arangod/Cluster/SynchronizeShard.cpp
arangod/RestHandler/RestReplicationHandler.cpp
arangod/Transaction/Manager.cpp
arangod/Transaction/Methods.cpp
tests/js/client/shell/shell-collection-counts-cluster.js

Fixed very spurious errors if the `holdReadLockCollection` replication API for the getting-in-sync procedure of shards was called during server shutdown. In this case that method could ask the transaction manager for a specific transaction, but wasn't return one due to the server shutddown. 
A new failure point has been added to make the transaction manager always return a nullptr, so the problematic behavior can be reproduced. A test was added to set the failure point and trigger the issue.
Test invcation: `scripts/unittest shell_client --cluster true --test tests/js/client/shell/test-collection-counts-cluster.js`
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12535/

fix spurious error when accessing a nullptr transaction context

---

arangod/Cluster/SynchronizeShard.cpp

Fix the shard-getting-in-sync procedure for MMFiles. 
We recently disabled the getting-in-sync shortcut, which is the right solution for the RocksDB storage engine, but MMFiles seems to depend on it. These changes were not released yet, but were still in testing. During testing it turned out that the changes harm the getting-in-sync protocol for MMFiles.
This PR reenables the shortcut just for MMFiles, and also avoids calling a non-implemented API for recalculating collection counts also in case the storage engine is MMFiles.
The test plan for this PR is to run `scripts/unittest dump --cluster true --storageEngine mmfiles`, which should show no replication errors with this PR.
In addition, the PR also removes a collection count operation at the end of the getting-in-sync phase that was …

Bug fix 3.6/fix getting in sync for mmfiles

---

arangod/Aql/AstResources.cpp
arangod/Aql/QueryRegistry.cpp
tests/js/server/aql/aql-failures-cluster.js

Add tests for failing insertion into query registry.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12430/

add failure test for QueryRegistry::insertQuery

---

arangosh/Shell/V8ClientConnection.cpp
js/client/modules/@arangodb/testsuites/endpoints.js
tests/js/client/endpoint-spec.js

The debugging option `--server.force-json` should downgrade the arangosh connection and its requests to lean on JSON being used for the sake of sniffeability. 
Its here to aid development.

fix json forcing; add test

---

arangod/Aql/RestAqlHandler.cpp
arangod/IResearch/GeoFilter.cpp

Fix two bogus compile warnings issued by g++-10.
In both cases, it warns about potentially uninitialized variables, but these are false positives.
This PR slightly changes the code to please the compiler.
Example warning message:
```
/home/jsteemann/ArangoNoAsan/arangod/IResearch/GeoFilter.cpp: In function ‘iresearch::filter::prepared::ptr {anonymous}::prepareOpenInterval(const iresearch::index_reader&, const iresearch::order::prepared&, iresearch::boost_t, const string_ref&, const arangodb::iresearch::GeoDistanceFilterOptions&, bool)’:
/home/jsteemann/ArangoNoAsan/arangod/IResearch/GeoFilter.cpp:512:3: warning: ‘incl’ may be used uninitialized in this function [-Wmaybe-uninitialized]
512 |   if (incl) {
|   ^~
```
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12581/

Bug fix/fix gcc10 bogus compile warning

---

CHANGELOG
arangod/Aql/ShardLocking.cpp
arangod/Cluster/ClusterInfo.cpp
tests/js/server/aql/aql-failures-cluster.js

Backport of: https://github.com/arangodb/arangodb/pull/12911/
No issues on cherry-pick
We now directly abort if we failed to translate Collection => Shard in AQL setup.
This situation can happen if the collection or database is dropped.
Before we still would return an error and leave no harm, this situation is now just a bit cleaner.
Additionally:
Jenkins: http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/12574/
Please note that for legal reasons we require you to sign the …

3.6 AQL setup now abort if no shards are found

---

CHANGELOG
arangod/RocksDBEngine/RocksDBTransactionCollection.cpp
arangod/Transaction/Manager.cpp
tests/js/client/shell/shell-transaction-intermediate-commit-cluster.js

Fix a potential deadlock in cluster transaction code in `transactions::Manager::returnManagedTrx()`.
This method acquired the write-lock on the transactions bucket, and then can call into `abortManagedTrx` while the lock is still being held.
`abortManagedTrx` directly calls `statusChangeWithTimeout`, which itself unconditionally calls `updateTransaction`, which will also unconditionally try to acquire the same bucket lock. This would be a deadlock.
We have never seen this in practice, and according to the code it looks like it can only happening when `beginShutdown()` or `stop()` are called on the TransactionManagerFeature. If this deadlock ever happened, it should be pretty rare.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12588/

fix a potential deadlock in cluster transaction code

---

CHANGELOG
arangod/Transaction/Manager.cpp
js/client/modules/@arangodb/test-utils.js
tests/js/client/shell/shell-transaction-intermediate-commit-cluster-rocksdb.js

Fix a potential deadlock in cluster transaction code in `transactions::Manager::returnManagedTrx()`.
This method acquired the write-lock on the transactions bucket, and then can call into `abortManagedTrx` while the lock is still being held.
`abortManagedTrx` directly calls `statusChangeWithTimeout`, which itself unconditionally calls `updateTransaction`, which will also unconditionally try to acquire the same bucket lock. This would be a deadlock.
We have never seen this in practice, and according to the code it looks like it can only happening when `beginShutdown()` or `stop()` are called on the TransactionManagerFeature. If this deadlock ever happened, it should be pretty rare.
Backport of the actual fix in https://github.com/arangodb/arangodb/pull/12955 …

fix potential deadlock in cluster transactions

---

Documentation/DocuBlocks/Rest/Collections/1_structs.md
Documentation/DocuBlocks/Rest/Collections/post_api_collection.md
Documentation/DocuBlocks/Rest/Collections/put_api_collection_properties.md
Documentation/DocuBlocks/collectionCreateEdgeCollection.md
Documentation/DocuBlocks/collectionDatabaseCreate.md
Documentation/DocuBlocks/collectionProperties.md

Addendum to https://github.com/arangodb/docs/pull/565 and #12866
@jsteemann What about the `--database.maximal-journal-size` option?
Is it supposed to be removed as well, and hence this DocuBlock?
https://github.com/arangodb/arangodb/blob/devel/Documentation/DocuBlocks/databaseMaximalJournalSize.md
(referenced by arangodb/docs!)

Docs: Remove indexBuckets, journalSize, doCompact, isVolatile from docs

---

CHANGELOG
arangod/ClusterEngine/RocksDBMethods.cpp
tests/js/client/shell/shell-recalculate-count-cluster.js
tests/js/client/shell/shell-recalculate-count-noncluster.js

Fix REST API endpoint PUT `/_api/collection/<collection>/recalculateCount on coordinators. Coordinators sent a wrong message body to DB servers here, so the request could not be handled properly.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12634/

Fix REST API endpoint PUT `/_api/collection/<collection>/recalculateCount

---

CHANGELOG
arangod/Aql/AqlFunctionFeature.cpp
arangod/Aql/Function.cpp
arangod/RestServer/QueryRegistryFeature.cpp
arangod/RocksDBEngine/RocksDBMetaCollection.cpp
arangod/RocksDBEngine/RocksDBTransactionCollection.cpp
arangod/RocksDBEngine/RocksDBTransactionState.cpp
arangod/RocksDBEngine/RocksDBTransactionState.h
arangod/Statistics/ServerStatistics.cpp
arangod/Statistics/ServerStatistics.h
arangod/StorageEngine/TransactionState.cpp
arangod/StorageEngine/TransactionState.h
arangod/Transaction/Manager.cpp

* Added metrics for collection locks:
- `arangodb_collection_lock_timeouts_exclusive`: Number of lock timeouts when trying to acquire collection exclusive locks 
- `arangodb_collection_lock_timeouts_write`: Number of lock timeouts when trying to acquire collection write locks 
- `arangodb_collection_lock_acquisition_micros`: Total amount of collection lock acquisition time [μs]
- `arangodb_collection_lock_acquisition_time`: Total collection lock acquisition time histogram [s]
* Reduce lock timeout on followers to 15 seconds.
Rationale: we should not have any locking conflicts on followers, generally. Any shard locking should be performed on leaders first, which will then, eventually replicate changes to followers. replication to followers is only done once the locks have been acquired on …

add some instrumentation for collection locking

---

CMakeLists.txt

Attempt to reduce the size of the debug information packaged when using `USE_MINIMAL_DEBUGINFO`.
This should reduce the size of the debug info in the executable, by removing column info from source locations, and by gzipping debug info.
In my local RelWithDebInfo devel build, this change reduces the size of the arangod executable from 320MB to 150MB when it contains debug symbols.
Filesize comparison for bin/arangod, with and without this PR:
**Without this PR**:
```
FILE SIZE        VM SIZE    
--------------  -------------- 
26.1%  87.4Mi   0.0%       0    .debug_info
18.6%  62.2Mi   0.0%       0    .debug_str
18.1%  60.7Mi  68.1%  60.7Mi    .text
16.9%  56.7Mi   0.0%       0    .debug_ranges
9.8%  32.8Mi   0.0%       0    .debug_line
0.0%       0  16.1%  14.3Mi    .bss
3.8%  12.7Mi …
```

attempt to make the debug info for `USE_MINIMAL_DEBUGINFO` even smaller

---

CHANGELOG
arangod/RestHandler/RestCollectionHandler.cpp
arangod/RestHandler/RestDocumentHandler.cpp
arangod/RestHandler/RestIndexHandler.cpp
arangod/RestHandler/RestTransactionHandler.cpp
arangod/RestHandler/RestVocbaseBaseHandler.cpp
arangod/RestHandler/RestVocbaseBaseHandler.h
arangod/Transaction/Manager.cpp
arangod/Transaction/Manager.h
arangod/Transaction/Options.cpp
arangod/Transaction/Options.h
scripts/startLocalCluster.sh
tests/Transaction/Manager-test.cpp

Make sure all follower trxs know that they are follower trxs.
Before this patch, follower transactions created from AQL or other
El Cheapo transactions did not know they are follower transactions.
This could cause deadlocks between write transactions and hotbackups.
*The below list is not exhaustive, think thoroughly whether the provided information is …

Fix deadlocks between write transactions and hotbackup, take 2

---

arangosh/Benchmark/BenchFeature.cpp
arangosh/Benchmark/BenchFeature.h
arangosh/Benchmark/BenchmarkCounter.h
js/client/modules/@arangodb/testsuites/arangobench.js

this PR enables arangobench to be ran for a specific time duration instead of a specified count. 
So if you want to load your system for a while, this way its more convenient.
It may now also create the database it operates on on start.

add option to run arangobench for a duration, instead of a count of operations

---

CHANGELOG
arangod/RestHandler/RestAdminStatisticsHandler.cpp
arangod/RestServer/MetricsFeature.cpp
arangod/Statistics/ConnectionStatistics.cpp
arangod/Statistics/RequestStatistics.cpp
arangod/Statistics/StatisticsFeature.cpp
arangod/Statistics/StatisticsFeature.h
arangod/Statistics/StatisticsWorker.cpp
arangod/Statistics/StatisticsWorker.h
arangod/V8Server/v8-statistics.cpp
arangod/V8Server/v8-vocbase.cpp
scripts/startLocalCluster.sh
tests/js/client/server_parameters/statistics-history-off.js
tests/js/client/server_parameters/statistics-off.js
tests/js/client/server_parameters/statistics-on.js

Enable HTTP request statistics and provide metrics even in case `--server.statistics-history` is set to `false` (this option will set itself to off automatically on agency instances on startup if not explicitly set).
This change provides more metrics on all server instances, without the need to persist them in the instance's RocksDB storage engine. 
This PR also adds tests for the different combinations for the statistics options.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12676/

decouple metrics provisioning from server.statistics-history option

---

arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
arangod/RocksDBEngine/RocksDBEdgeIndex.h

Honors the `enableCache` index iterator flag in the edge index iterators. This flag is set to false when we will be loading all edges (e.g. in the startup phase of a Pregel run) to avoid overwhelming the cache and ejecting the actual hot set.
Link to Jenkins PR run: https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/12691/ (all blue)

Honor enableCache flag in edge index iterators.

---

arangod/V8Server/v8-actions.cpp
js/server/bootstrap/modules/internal.js
tests/js/client/shell/shell-deadlock-trx-hotbackup-cluster.js

Port a test from 3.7 to devel.
This test does concurrently:
- repeated hotbackups
- AQL writing transactions with exclusive lock

Add deadlock test for hotbackup

---

CHANGELOG
arangod/Scheduler/SchedulerFeature.cpp

Fix misleading log topic "cluster" for general shutdown message.
The shutdown has nothing to do with the cluster in particular, so the log message shouldn't use the "cluster" topic.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12730/

fix log topic for shutdown message

---

CMakeLists.txt

disable warning for clang 12 on macosx

Bug fix 3.5/clang 12

---

CMakeLists.txt

http://jenkins.arangodb.biz:8080/view/Mac/job/arangodb-matrix-pr-mac-onlycompile/1748/

Disable warning for clang-12 on macOS

---

CMakeLists.txt

Remove compiler directive `-felmininate-unused-debug-symbols` from CMakeLists.txt, because it is enabled by default on g++, and clang++ does not support it.
Backports are not required because we added the `USE_MINIMAL_DEBUGINFO` CMake variable only in devel.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12762/

remove compiler directive `-felmininate-unused-debug-symbols`

---

CHANGELOG
Documentation/DocuBlocks/Rest/Administration/get_admin_server_availability.md
Documentation/DocuBlocks/Rest/Administration/get_admin_statistics.md
arangod/Aql/QueryList.cpp
arangod/GeneralServer/RestHandler.cpp
arangod/GeneralServer/VstCommTask.cpp
arangod/Network/NetworkFeature.cpp
arangod/Network/NetworkFeature.h
arangod/Replication/ReplicationFeature.cpp
arangod/Replication/ReplicationFeature.h
arangod/RestHandler/RestAdminServerHandler.cpp
arangod/RestHandler/RestReplicationHandler.cpp
arangod/RestServer/QueryRegistryFeature.cpp
arangod/RestServer/QueryRegistryFeature.h
arangod/Scheduler/Scheduler.h
arangod/Scheduler/SchedulerFeature.cpp
arangod/Scheduler/SchedulerFeature.h
arangod/Scheduler/SupervisedScheduler.cpp
arangod/Scheduler/SupervisedScheduler.h
tests/Cluster/ClusterCommTest.cpp
tests/Cluster/RebootTrackerTest.cpp

This is a PR to add more observability.
**Metrics**:
* Added new metric `arangodb_network_forwarded_requests` to track the number of requests forwarded from one coordinator to another in a load-balancing context.
* Added new metric `arangodb_replication_cluster_inventory_requests` to track the number of requests received for cluster inventories. The cluster inventory API is called at the beginning of a dump process or by arangosync.
* Added new metric `arangodb_aql_all_query` to track the total number of AQL queries.
* Added new metric `arangodb_aql_total_query_time_msec` to track the combined runtime of AQL queries (slow queries and non-slow queries).
* Added more scheduler metrics:
* `arangodb_scheduler_threads_started`: Total number of scheduler threads started
* …

Improved observability

---

CHANGELOG
arangod/Network/NetworkFeature.cpp

Make the number of network I/O threads properly configurable via the startup option `--network.io-threads`. This option existed before, but its configured value was effectively clamped to a value of `1`.
This is a forward-port of some part of the 3.6 PR https://github.com/arangodb/arangodb/pull/13049
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12789/

Make the number of network I/O threads configurable

---

arangosh/Benchmark/BenchFeature.cpp

Renaming the variable for printing arangobench results was missed in one space while adding the `--duration` feature.

fix oversight spottet by @mpoeter

---

CHANGELOG
arangod/Cluster/MaintenanceFeature.cpp
arangod/Cluster/RestClusterHandler.cpp
arangod/GeneralServer/RestHandler.cpp
arangod/GeneralServer/RestHandler.h
arangod/Network/NetworkFeature.cpp
arangod/RestHandler/RestAdminLogHandler.cpp
arangod/RestHandler/RestAdminServerHandler.cpp
arangod/RestHandler/RestDocumentHandler.cpp
arangod/RestHandler/RestEngineHandler.cpp
arangod/RestHandler/RestJobHandler.cpp
arangod/RestHandler/RestPleaseUpgradeHandler.cpp
arangod/RestHandler/RestShutdownHandler.cpp
arangod/RestHandler/RestStatusHandler.cpp
arangod/RestHandler/RestVersionHandler.cpp
lib/Logger/LogTopic.cpp
lib/Logger/Logger.h

This is a multi-purpose PR:
It makes the number of network I/O threads properly configurable via the startup option `--network.io-threads`. This option existed before, but its configured value was effectively clamped to a value of `1`. 
This change requires forward ports to 3.7 and devel.
It also disables cluster maintenance background threads on coordinators.
The maintenance threads don't have any purpose on coordinators, so there is no need to start them there. This saves 2 or more background threads on coordinators. These threads should have mostly been idle before, so saving them will not have a huge impact except saving a few MB of thread stack memory.
The maintenance threads are already turned off on coordinators in 3.7 and devel for a while, so this does not need to be ported.
In …

Bug fix 3.6/cleanup 20201117

---

js/client/modules/@arangodb/testutils/test-utils.js

`runInLocalArangosh` eval's testcodes into the local arangosh.
However, so far it doesn't properly catch all errors, but rather slashes the SUT hiding the original error. 
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/12843/

make sure we catch syntax error while eval'ing in runInLocalArangosh

---

lib/ApplicationFeatures/CpuUsageFeature.cpp

Fixes a strange error from clang-12 which complains about an unused variable.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12848/

Fix clang warning about unused variable.

---

CHANGELOG
arangod/RestHandler/RestTransactionHandler.cpp
arangod/RestHandler/RestTransactionHandler.h

The cancelation of JavaScript transactions started via HTTP POST to `/_api/transaction` with the `x-arango-async` header set was previously unsafe, because the cancel code could run after the transaction was executed and its V8Context was already returned. In this case the `_v8Context` instance variable was a nullptr, but `cancel()` did not check for this.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12858/

Make cancelation of asynchronoulsly started JS transactions safe

---

CMakeLists.txt

Use compiler option `-Wsuggest-override` option only conditionally for clang, because it is only supported from version 11 onwards. Older versions don't have it and produce warnings.
Apple clang 12.0 does not seem to have it either, so disable it there too.
This hopefully fixes a glitch introduced only recently in devel, so I am intentionally not making a CHANGELOG entry for this.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12872/

use -Wsuggest-override option conditionally for clang

---

CHANGELOG
arangod/Agency/Supervision.h
arangod/RestHandler/RestAdminClusterHandler.cpp

Fix the activation of the agency supervision maintenance via the REST API `/_admin/cluster/maintenance`. This API stored a boolean value instead of an (expected) maintenance period end date/time string.
This affects 3.7 and devel only, but not 3.6.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12869/

fix activation of maintenance via REST API `/_admin/cluster/maintenance`

---

arangod/Aql/AqlExecuteResult.cpp
arangod/Aql/ExecutionBlockImpl.cpp
tests/js/server/aql/aql-shadowrow-block-return-regression.js

This PR fixes a false assertion in AQL ExecutionBlocks.
The assertion tests that something should be written in an AQL block if an executor is finished with it's work and claims there is even more data available.
This assertion tested for the actually existence of a value entry. If this value is NOT used later, it could actually be optimized away here, causing this assertion to trigger. (An empty row is written, but no value)
Now using the number of written rows.
This covers empty rows as well.
This PR does NOT change any production behavior and therefor has no CHANGELOG entry. The code modified here is not compiled into our release.
Jenkins:
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/12883/

Bug fix/executionblockimpl hasmore assertion

---

js/client/bootstrap/modules/internal.js

Let appendHeaders() check the protocol (#13038) and throw if the `http/1.1` header field isn't set.
Still doesn't support HTTP/2 or VST, but at least we will see an error should the protocol be changed at some point.
No longer filter out the header fields `server`, `connection` and `content-length`. This makes the generated examples slightly longer but accurate.
https://jenkins01.arangodb.biz/view/Documentation/job/arangodb-ANY-examples/698/
https://arangodb.atlassian.net/browse/DOC-71

Docs: Check protocol(), throw if not http/1.1, don't filter common headers

---

arangod/Aql/AqlExecuteResult.cpp
arangod/Aql/ExecutionBlockImpl.cpp
tests/js/server/aql/aql-shadowrow-block-return-regression.js

Backport of
https://github.com/arangodb/arangodb/pull/13094
This PR fixes a false assertion in AQL ExecutionBlocks.
The assertion tests that something should be written in an AQL block if an executor is finished with it's work and claims there is even more data available.
This assertion tested for the actually existence of a value entry. If this value is NOT used later, it could actually be optimized away here, causing this assertion to trigger. (An empty row is written, but no value)
Now using the number of written rows.
This covers empty rows as well.
This PR does NOT change any production behavior and therefor has no CHANGELOG entry. The code modified here is not compiled into our release.
Jenkins:
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/12897/

Bug fix 3.7/executionblockimpl hasmore assertion

---

CHANGELOG
arangod/Agency/Agent.cpp
arangod/Agency/Agent.h
arangod/Agency/RestAgencyHandler.cpp
arangod/Cluster/AgencyCache.cpp
arangod/Cluster/AgencyCache.h
arangod/Cluster/ClusterInfo.cpp
arangod/Cluster/DBServerAgencySync.cpp
arangod/Cluster/HeartbeatThread.cpp
arangod/RestServer/DatabaseFeature.cpp
arangod/RestServer/DatabaseFeature.h

Fix the initial population of the AgencyCache after a server restart.
The previous version used to poll from the agency with a commit index value of `1`, whereas I think it should be `0` for the initial call to get a full snapshot from the agency.
This PR also contains a code comment in DBServerAgencySync.cpp that we need to sort out. @kvahed suggested to wait here until we have got initial data from the agency, but I can't tell if it is necessary and what would be the side effects (blocking?). 
The changes in this PR seem to fix the issues found by mini chaos (:tm:), even without the change in DBServerAgencySync.cpp, but this may be coincidence.
This does not need a port for 3.5 or 3.6, as these versions do not have the AgencyCache machinery.  …

fix initial population of AgencyCache

---

CHANGELOG
arangod/GeoIndex/Index.cpp
arangod/GeoIndex/Near.cpp
lib/Geo/GeoParams.h
tests/js/server/aql/aql-queries-geo.js

Backport of #12917
Fix an issue where a query would not return a result when the geo index was used.
```
LET g = GEO_POINT(37.616522, 55.704235) 
FOR d IN geo 
FILTER GEO_DISTANCE(g, d.geometry) <= 0 
RETURN d
```
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12884/

Fix zero distance geo NN search

---

js/client/modules/@arangodb/testsuites/endpoints.js

On Windows the endpoints-test will allways report an empty list due to the `skip` callback for the unix domain sockets.
This is wrong and fixed hereby. 
this is a fix to tests.

fix status reporting of skipped endpoint tests

---

CHANGELOG
js/apps/system/_admin/aardvark/APP/frontend/js/views/clusterView.js
js/apps/system/_admin/aardvark/APP/statistics.js
js/server/modules/@arangodb/statistics-helper.js
tests/js/server/shell/shell-statistics-helper.js

The old implementation sent `statistcs/short` requests to all coordinators (including itself). The `statistics/short` handler is also implemented in JS and runs two DB queries. So for a cluster with 3 coordinators, the old implementation issued 3 network requests, which triggered a total of 6 DB queries and required 4 V8 contexts (one for the initial coordshort request, and one for each statistic/short request).
The new implementation only runs two DB queries without any additional requests to other coordinators, resulting in reduced load on the cluster.
In addition this reimplementation fixes the way statistics samples of coordinators are merged. Previously we simply took the timestamps from the samples of one coordinator and simply merged all samples based on their index. However, …

Reimplement coordshort request handler.

---

lib/ApplicationFeatures/ApplicationFeature.cpp
lib/ApplicationFeatures/ApplicationFeature.h
lib/ApplicationFeatures/ApplicationServer.cpp
lib/ApplicationFeatures/ApplicationServer.h

This fixes a bug in the `ApplicationServer`/`ApplicationFeature` framework. Specifically in the case that a derived feature registers as it's base type, the methods which determine feature order may not correctly respect dependencies. This hasn't had any concrete effect yet, as the dependencies which were broken in 3.7 and devel did not have any adverse effects. Thus, omitting a CHANGELOG entry, since it has no practical effect yet.
- [s] Backports required for: 3.7
Link to Jenkins PR run: https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/12949/

Fix issue with ApplicationFeature registration and startup order

---

arangosh/Benchmark/BenchFeature.cpp
arangosh/Benchmark/BenchFeature.h
arangosh/Benchmark/BenchmarkThread.h

forward port https://github.com/arangodb/arangodb/pull/13126
* fixed uint chaos
* fixed size_t chaos
Windows nightly will get stuck in the arangobench test.

Bug fix /arangobench (#13126)

---

CHANGELOG
lib/Logger/LogTimeFormat.cpp
lib/Logger/LogTimeFormat.h
lib/Logger/Logger.cpp
tests/Basics/LoggerTest.cpp

Avoid usage of expensive `std::regex`-based functionality for constructing date/time values for log messages.
This is a performance optimization only.
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/597
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12958/

avoid usage of std::regex for constructing date/time values for log messages

---

CHANGELOG
arangod/Statistics/StatisticsFeature.cpp
arangod/Statistics/StatisticsWorker.cpp
arangod/Statistics/StatisticsWorker.h

The `StatisticsWorker` thread was previously only running queries on the local RocksDB instance, but using the cluster-wide collection names. So effectively it did nothing except use a bit of background CPU. In this case it is better to turn off the background thread entirely on the DB servers.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12948/

turn off StatisticsWorker thread on DB servers

---

lib/V8/V8LineEditor.cpp

This concerns the detection of the arangosh repl whether a line is complete. When inside a multi-line comment, i.e. after a `/*`, after encountering a `*`, any `/` would end the comment; e.g. `/** GET /` would be seen as a terminated multi-line comment.
I couldn't find existing tests for this. Maybe some should be added in this PR, but if so, we need tests for the whole behaviour, not just this fix.

Fix multi comment detection

---

CHANGELOG
arangod/Aql/DocumentProducingHelper.cpp

Previously, there was no point at which a query was checked for being killed during early pruning. As the number of documents enumerated and filtered is unbounded, such a check is expedient.

Add kill-check during early pruning

---

CHANGELOG
lib/Basics/files.cpp
lib/Basics/operating-system.h

windows make directory would not throw on error
discovered during testing

fix make directory windows error handling

---

CHANGELOG
arangod/Aql/Functions.cpp
arangod/Pregel/PregelFeature.cpp
arangod/RestHandler/RestControlPregelHandler.cpp
arangod/V8Server/v8-collection.cpp
tests/js/common/shell/shell-pregel.js

Make all Pregel HTTP and JavaScript APIs also accept stringified execution number values, in addition to numeric ones. 
This allows passing larger execution numbers as strings, so that any data loss due to numeric data type conversion (uint32 => double) can be avoided. This change is downwards-compatible.
The change in this PR also makes the Pregel HTTP and JavaScript APIs for starting a run return a stringified execution number, e.g. "12345" instead of 12345. This is not downwards-compatible, so it will be noted in the upgrading section and will not be backported.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13099/

stringify Pregel execution numbers

---

arangod/Agency/AgencyComm.h
arangod/Aql/AqlValue.cpp
arangod/Cluster/ClusterRepairDistributeShardsLike.h
arangod/RestServer/Metrics.h
lib/V8/v8-utils.cpp

* Simplify two operations from divisions to bitwise arithmetic (moving from `% 1000 == 0` to `% 1024 == 0` enables this optimization in g++ with optimizations, as tested in compiler explorer)
* Removed stock include headers from Metrics.h
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13106

simplify operations from division to bit arithmetic

---

arangod/Aql/DocumentProducingHelper.cpp

Follow-up of https://github.com/arangodb/arangodb/pull/13151. Use `_numFiltered` instead of `_numScanned` to avoid edge cases.

Change from _numFiltered to _numScanned to avoid edge cases

---

CHANGELOG
arangod/Transaction/Methods.cpp
lib/Basics/StringUtils.cpp
lib/Basics/StringUtils.h
tests/Basics/StringUtilsTest.cpp

Fix cluster-internal replication of documents with special keys (containing the percent character, which has a special meaning when used inside URLs).
Cluster-internal replication of such documents did not work when only a single document was replicated, as the document key was used in a URL without URI-encoding.
This got unearthed by PR https://github.com/arangodb/arangodb/pull/13177, which will also put this under test.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13157/

Fix cluster-internal replication of documents with special keys

---

lib/ApplicationFeatures/GreetingsFeature.cpp
lib/Basics/CrashHandler.cpp
lib/Basics/debugging.h

Try to exclude assertion branches from code coverage. 
The assertions have a true branch and a false branch, but only one of them is executed during our coverage tests. The not-taken branch would raise an assertion failure and crash the server, thus we don't expect it to be executed under normal conditions. But we also do not want to count this as a non-executed branch.
This needs dedicated testing with the code coverage Jenkins job.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13162/

try to exclude assertion branches from coverage

---

arangod/IResearch/IResearchFeature.cpp

Adjust code to match https://github.com/arangodb/docs/pull/593/commits/72dcbffbed2d25b08145bd07618c37880f8c6531
Also add v3.8.0 as version, even though this isn't strictly necessary. We do this for other options however.
https://github.com/arangodb/arangodb/pull/13008
https://github.com/arangodb/arangodb/pull/13146
https://github.com/arangodb/docs/pull/593

Fix introduced/deprecated in versions for --arangosearch.*threads* startup option

---

lib/Rest/HttpRequest.cpp

Fix assertion failure when database is specified without URL path (e.g. `/_db/system`). In this case, in maintainer mode an assertion failure was triggered, but it didn't have any effect in non-maintainer
mode.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13076/

fix assertion failure when database is specified with no URL path

---

arangod/RestHandler/RestStatusHandler.cpp

This PR fixes typos in JEMALLOC_PROF section. This is not used unless malloc profile has been defined.

Bug fix 3.7/jemalloc prof

---

tests/IResearch/IResearchFeature-test.cpp
tests/IResearch/IResearchLink-test.cpp

Adjust some arangosearch tests to be more deterministic
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/13203/

bug-fix/make-arangosearch-tests-deterministic

---

arangod/Aql/MutexExecutor.cpp
arangod/V8Server/v8-actions.cpp

As we can't check query execution plans for traversal parallelization, this now adds a failure point that is only triggered during parallel execution. That way the tests have an unambiguous way to tell if traversal parallelism was applied or not.
Community part of https://github.com/arangodb/enterprise/pull/603
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13214

add a more effective test for parallel traversals

---

arangod/RocksDBEngine/RocksDBRestReplicationHandler.cpp
lib/Basics/NumberUtils.h

* Fix a potential signed integer underflow in NumberUtils, uncovered by unit tests with UBSan.
* Make sure that privileges for replication are sufficient when doing incremental sync.
It is unclear whether these issues are hit in practice (e.g. the NumberUtils issue depends on specific template instatiations and values), but the possibility at least exists.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13109/

two small unrelated fixes

---

tests/js/client/restart/test-foxx-selfheal-cluster.js

The `restart` suite seems to fail with connection errors on Windows.
This is potentially due to arangosh/fuerte not playing nice with connections that are established to a server that is shut down and then restarted.
This PR is an attempt to work around this issue. It may fix the problem in the tests, or it may not.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13241/

work around a potential issue found in `restart` test suite

---

tests/js/client/restart/test-foxx-selfheal-cluster.js

The `restart` suite seems to fail with connection errors on Windows.
This is potentially due to arangosh/fuerte not playing nice with connections that are established to a server that is shut down and then restarted.
This PR is an attempt to work around this issue. It may fix the problem in the tests, or it may not.
Backport of #13234
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13251/

work around a potential issue found in `restart` test suite (#13234)

---

arangod/Aql/AqlValueGroup.cpp
arangod/Aql/AqlValueGroup.h
arangod/Aql/HashedCollectExecutor.cpp
arangod/Aql/HashedCollectExecutor.h

`HashedCollectExecutor::findOrEmplaceGroup` first calls `find` and if we don't have a matching value we call `try_emplace`. In that case we have to calculate the hash twice (once for each function). On top of that, a rehash of the unordered_map has to recalculate the hashes of all entries. This can be quite expensive, especially for non-scalar values like lists or objects.
This PR introduces the `HashedAqlValueGroup` struct which holds a hash value in addition to the `AqlValue`s. This allows us to calculate the hash only once and store it in the struct. Since we already use our own `Hash` type for the unordered-map, we can simply extend it to return the memoized hash value. In addition to that, we can also make use of the memoized hash value in the `KeyEqual` comparer to short-circuit if …

Memoize hash for group values in HashedCollectExecutor.

---

CHANGELOG
arangod/Cluster/FollowerInfo.cpp

This fixes the sort order in maintainer mode for the sorting of
followerinfo lists. This is a trivial change.

Sort followerinfo in maintainermode right

---

CHANGELOG
arangod/Pregel/Conductor.cpp
arangod/Pregel/Conductor.h
tests/js/common/shell/shell-pregel.js

Added "startupTime", "computationTime" and "storageTime" to Pregel result statistics.
This makes the more detailed timings available as part of the Pregel job result, so it can be better understood how long the individual parts of a run took.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13301/

Added "startupTime", "computationTime" and "storageTime" to Pregel result statistics

---

tests/CMakeLists.txt
tests/Metrics/MetricsServerTest.cpp
tests/Metrics/MetricsTest.cpp
tests/Mocks/Servers.cpp
tests/Mocks/Servers.h

Add a `MockMetricsServer` for testing.
This is a very basic ApplicationServer with only the relevant features enabled for metrics to work.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13317/

add MockMetricsServer

---

UnitTests/OskarTestSuitesBlackList

Add `agency-restart` test suite to the blocklist in this version, as the test suite is only available in devel.
This is required for merging https://github.com/arangodb/oskar/pull/282

added agency-restart tests to the blocklist

---

arangod/RocksDBEngine/RocksDBUpgrade.cpp

Prevent a write to RocksDB during recovery in the case that the database already exists. If the database didn't already exist, it's okay to do the write. If it exists, we shouldn't write anything until after recovery has finished. Other than simply wanting to avoid writes during recovery for safety, we have also seen at least one case where a server shut down while in a write-stopped state, and on startup re-entered that write-stopped state; the write at startup then could not proceed, and the server was not able to proceed with recovery, start up, and serve health check requests.
Link to Jenkins PR run: https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/13334/ (all blue)

Prevent write during RocksDB recovery

---

arangosh/Shell/V8ShellFeature.cpp

When starting ArangoDB, the error that is provided when not adding the "--javascript.startup-directory" argument is:
`no 'javascript.startup-directory' has been supplied, giving up`
In my opinion this should be similar to the other arguments and thus be specified as:
`no '--javascript.startup-directory' has been supplied, giving up`
Please note that for legal reasons we …

Patch V8ShellFeature.cpp - Error feedback

---

CHANGELOG
arangod/GeneralServer/RestHandler.cpp
tests/js/client/load-balancing/response-header-noauth-cluster.js

Remove HTTP "Connection" header when forwarding requests in the cluster from one coordinator to another, and let the internal network layer handle closing of connections and keep-alive.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13352/

Remove HTTP "Connection" header when forwarding requests

---

arangod/Agency/AgencyCommon.h
arangod/Agency/AgencyFeature.cpp
arangod/Agency/Agent.cpp
arangod/Agency/State.cpp
arangod/Agency/State.h
arangod/Agency/v8-agency.cpp
arangod/Cluster/FollowerInfo.cpp
js/client/modules/@arangodb/testsuites/agency-restart.js
tests/js/server/agency-restart/few-writes.js
tests/js/server/agency-restart/many-writes.js
tests/js/server/agency-restart/no-compact-collection.js
tests/js/server/agency-restart/no-compaction.js
tests/js/server/agency-restart/no-log-collection.js

Add `agency-restart` test suite.
This test suite contains tests that put specific data into a single-host agency, crash and then restart it. On restart, it is checked if the data still exists and is as expected.
As few simple tests are added with this PR initially, and this can be extended over time.
The two small issues fixed by this PR will be backported separately.
Also includes bugfixes for reading back `clientId` values from persistence and for handling restarts with gone `log` or `compact` collections.
Requires merging of https://github.com/arangodb/oskar/pull/282 in order to execute the new test suite automatically.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13331/

add agency-restart test suite

---

arangod/Cluster/AgencyCache.cpp
arangod/Cluster/ClusterFeature.cpp
arangod/Cluster/ClusterFeature.h
arangod/Cluster/ClusterInfo.cpp
arangod/Cluster/ClusterInfo.h

Properly shut down AgencyCache and Syncers during testing.
These components are normally shut down by the ClusterFeature under normal conditions, and the ClusterFeature waits in its `stop` method for the proper shutdown.
However, in case the `stop` method is not run or does not complete, the components may be left running.
This PR thus tries to shut down the components in the destructor of the ClusterFeature once more, should they still be around.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13350/

properly shut down AgencyCache in tests

---

UnitTests/OskarTestSuitesBlackList

Add `agency-restart` test suite to the blocklist in this version, as the test suite is only available in devel.
This is required for merging https://github.com/arangodb/oskar/pull/282

add agency-restart tests to the blocklist

---

arangod/Aql/Query.cpp
arangod/Aql/QueryList.cpp
arangod/Aql/QueryProfile.h
arangod/Aql/QueryRegistry.cpp

Slightly improve audit logging for edge cases, e.g. empty query string/no bind variables, and when query was not inserted into the list of running queries because query tracking was turned off.
In addition, this PR should fix errors that were observed in the shell-query-kill test in cluster.
No backports are required because the changes to auditing were not done in 3.6 or 3.7 (only cosmetic changes were done in the stable branches).
There is also an enterprise part for this PR: https://github.com/arangodb/enterprise/pull/614
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13391/

improve audit logging messages and robustness

---

CHANGELOG
arangod/Cluster/AgencyCache.cpp
arangod/Cluster/AgencyCache.h
arangod/Cluster/ClusterFeature.cpp
arangod/Cluster/ClusterFeature.h
arangod/Cluster/ClusterInfo.cpp
arangod/Cluster/ClusterInfo.h
arangod/Cluster/DBServerAgencySync.cpp
arangod/GeneralServer/IoContext.cpp
tests/Mocks/Servers.cpp

Otherwise the maintenance, fired off by the heartbeat thread, may not wait for the initial data to arrive from the agency, which can cause Plan and Current to be empty when maintenance starts.
No backport for 3.6 is needed, as 3.6 has blocking agency communication here in case the Plan is not there.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13365/

Make internal ClusterInfo::getPlan() wait for initial plan load from agency

---

lib/Rest/HttpRequest.cpp

Fix assertion failure when database is specified without URL path (e.g. `/_db/system`). In this case, in maintainer mode an assertion failure was triggered, but it didn't have any effect in non-maintainer
mode.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13074/

fix assertion failure when database is specified without URL path

---

arangod/GeneralServer/IoContext.cpp

Port of 3.5 change: do not delete thread in case of exception, catch and report the exception instead.

do not kill thread in case of exception

---

CHANGELOG
arangod/Agency/State.cpp

Fix recovery of "clientId" values in Agency when restarting an agent from persistence. 
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13336/

fix reloading "clientId" values from persistence

---

CHANGELOG
arangod/RestServer/Metrics.cpp
arangod/RestServer/Metrics.h
tests/js/client/communication/test-communication.js
tests/js/client/shell/shell-transaction-intermediate-commit-cluster.js

Fix a minor syntax error in metrics for prometheus.
In case that a metrics has no labels, drop a pair of braces {} which
are officially not allowed in the Prometheus metrics output.
- [*] No backports required
- [*] This change is a trivial rework / code cleanup without any test coverage.

Minor syntactic fix in Prometheus metrics output

---

CHANGELOG
tests/js/server/shell/shell-foxx-cleanup-spec.js

I have observed some instability in this test:
tests/js/server/shell/shell-foxx-cleanup-spec.js
Namely, it relies on a directory which is only created after startup
by the foxx manager selfheal procedure. This is a race.
This PR adds a wait loop to stabilize the test.
This has been fixed for 3.6 in #13184 and in 3.7 in #13309

Stabilize Foxx cleanup test

---

arangod/Cluster/ClusterInfo.cpp

Remove now superfluous retry logic.
The retry logic was previously useful when we still contacted the agency after each failed attempt. However, nowadays we don't do this, so we can get away without ever retrying here.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13481/

remove now superfluous retry code

---

arangod/RocksDBEngine/RocksDBOptionFeature.cpp

Test PR to see if a specific change of RocksDB options in devel caused a performance regression to some AQL workloads.
We will merge this to devel and then check the performance results with the latest version.
If performance gets better, we will fix this properly, otherwise we will revert this change and try other fixes.
The performance regression was only introduced to devel, so backports needed for 3.7 or 3.6
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13482/

test PR to see if a specific change caused a performance regression

---

arangod/Cluster/Maintenance.cpp
arangod/VocBase/Methods/Databases.cpp
arangod/VocBase/VocbaseInfo.h
tests/js/common/shell/shell-one-shard.js

This PR will lead to two changes:
* for any newly created databases in `--cluster.force-one-shard` mode, the "sharding" attribute will automatically be set to "single" on database creation, even if not explicitly specified.
* for any newly created databases in the cluster, the "sharding" attribute will be stored on DB servers as well when set to "single".
That way the "sharding" attribute with a value of "single" will propagate to the DB servers so they have local access to it, and also it becomes independent of the value of the `--cluster.force-one-shard` flag for any databases after they have been created.
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/621
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13484/

store sharding attribute for databases on db servers

---

arangod/Cluster/Maintenance.cpp
arangod/Cluster/SynchronizeShard.cpp

Add more granular error reporting to `reportInCurrent` maintenance function, and add lots of assertions.
This is not a bugfix, but a vehicle to simplify debugging and bug hunts.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13495/

more granular error reporting in Maintenance

---

CHANGELOG
arangod/Statistics/StatisticsFeature.cpp

Added metric `arangodb_server_statistics_cpu_cores` to provide the number of CPU cores visibile to the arangod process. This is the number of CPU cores reported by the operating system to the process.
If the environment variable `ARANGODB_OVERRIDE_DETECTED_NUMBER_OF_CORES` is set to a positive value at instance startup, this value will be returned instead.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13512/

added metrics "arangodb_server_statistics_cpu_cores"

---

tests/js/common/shell/shell-pregel.js

Fix spurious error in shell-pregel.js `shell_client` or `shell_server` tests.
This is an error in the test only, which assumes that the attribute "storageTime" is always present in the result if "store" is true. However, this is not guaranteed, as the status of a Pregel run can be checked _before_ the run is completed. In that case, the "storageTime" attribute is intentionally missing from the result.
This is a test fix only, so there is no CHANGELOG entry for it.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13502/

fix spurious error in shell-pregel.js test suite

---

tests/js/client/communication/test-communication.js

This PR just fixes a test, that should only run in Enterprise mode, as the feature under test is enterprise only.
No Production Change.
Jenkins:
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/13479/

(3.7) Only run Test in Enterprise mode

---

CHANGELOG
lib/Basics/debugging.cpp
lib/Logger/LogThread.cpp
lib/Logger/Logger.cpp
lib/Logger/Logger.h

Added startup option `--audit.queue` to control audit logging queuing behavior (Enterprise Edition only):
The option controls whether audit log messages are submitted to a queue 
and written to disk in batches or if they should be written to disk directly 
without being queued.
Queueing audit log entries may be beneficial for latency, but can lead to
unqueued messages being lost in case of a power loss or crash. Setting
this option to `false` mimics the behavior from 3.7 and before, where
audit log messages where not queued but written in a blocking fashion.
There is also an enterprise companion PR: https://github.com/arangodb/enterprise/pull/626
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13534/

added configuration option `--audit.queue` for audit logging

---

README_maintainers.md
js/client/modules/@arangodb/testutils/result-processing.js
js/client/modules/@arangodb/testutils/test-utils.js
js/client/modules/@arangodb/testutils/testing.js
js/common/modules/@arangodb/mocha.js
js/common/modules/jsunity.js

This allows to re-run only those tests that failed in the previous test run. The information which tests previously failed is taken from the "UNITTEST_RESULT.json" (if available).
This should work for all jsunity and mocha tests.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13537/

Introduce --failed filter for unit tests.

---

CHANGELOG
arangod/Aql/AqlItemBlockInputMatrix.cpp
arangod/Aql/AqlItemBlockInputMatrix.h
arangod/Aql/ExecutionBlockImpl.cpp
tests/Aql/SortExecutorTest.cpp
tests/js/server/aql/aql-shadowrow-block-return-regression.js
tests/js/server/aql/aql-subquery.js

Backport of https://github.com/arangodb/arangodb/pull/12868
Fixes an assertion, and a very minor performance issue.
Reviewer Info:
This PR basically creates two versions of the same internal function, one that asserts on final state (which is to be expected during execution) and one without the final state assert, which can happen during the Construction of the object.
The constructor now uses the new variant.
Also added tests that triggered the assert on construction.
- [] Backports required for
Additionally:
> Bugs and features should furthermore be documented in the changelog so …

Bug fix 3.7/bts 223 (#12868)

---

arangod/Graph/Helpers/TraceEntry.h

Just Makes CLANG11 and GCC 10.* compile again, our Jenkins do not test those latest versions

Make CLANG-11 compile again

---

tests/Aql/KShortestPathsExecutorTest.cpp
tests/Aql/ShortestPathExecutorTest.cpp

This test does not have any User Impact.
It only reduces the amount of tested combinations of input / data in the tests.
It is fine to have the input format tested once, and the data tested once.
This speeds up initial load of tests by ~66% on my machine.
Also speeds up the tests of the specific files by factor of ~10 or more.
Jenkins:
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/13604/

Reduced the amount of test combinations in (K-)ShortestPathsTests.

---

arangod/Aql/AstNode.cpp
arangod/Aql/AstNode.h
tests/js/common/shell/shell-tasks.js

Make shell_client tasks test more deterministic.
Mark a few methods as `noexcept`.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13602/

small improvements

---

CHANGELOG
lib/Logger/LogAppenderFile.cpp

backport of "bug-fix-3.6/fix-audit-log-shutdown"

fix potential invalid derefence on audit log shutdown

---

arangod/Cluster/AgencyCache.cpp
arangod/Cluster/ClusterFeature.cpp
tests/Mocks/Servers.cpp

Fix a shutdown issue that happens at least during testing.
When `ClusterFeature` shuts down, it needs to make sure that its `_agencyCache` member was successfully shut down as well. So it tries to shut down the `_agencyCache` in `ClusterFeature::stop()` and in `ClusterFeature::~ClusterFeature()` (in case `stop` isn't called for whatever reason).
The `AgencyCache` itself updates metrics on shutdown, so it relies on the `MetricsFeature` to be valid.
Now, in case we are in `ApplicationServer::~ApplicationServer()`, the destructors of all ApplicationFeatures are called in a random order (features are stored in an unordered_map). In my case the `MetricsFeature` was destroyed before the `ClusterFeature`. Now, when `~ClusterFeature()` is executed, it tries to shut down the `_agencyCache` member, …

fix shutdown issue during gtests

---

CHANGELOG
arangod/Aql/QueryList.cpp
arangod/RestServer/QueryRegistryFeature.cpp
arangod/RestServer/QueryRegistryFeature.h
arangod/Scheduler/SupervisedScheduler.cpp

Added metric `arangodb_aql_current_query` to track the number of currently executing AQL queries.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13619/

Added metric `arangodb_aql_current_query`

---

arangod/Aql/ExecutionBlockImpl.cpp
arangod/Aql/ExecutionBlockImpl.h
arangod/Aql/MultiDependencySingleRowFetcher.cpp
arangod/Aql/MultiDependencySingleRowFetcher.h

This PR has no User Impact.
The modified place inject some test-case preparation code.
This should only be enabled with the GTEST flag enabled, and is independent of MAINTAINER_MODE which was used here wrongly.
Jenkins runs either both on or both of, so it slipped through.
Jenkins:
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/13613/

Replaced MAINTAINERMODE with GTEST makro to include testing code

---

tests/js/common/shell/shell-collection-noncluster.js

Attempt to improve an unstable test that depends on the edge cache usage.
The test *is* actually testing the edge cache usage statistics, but there are no guarantees that the edge cache will be used for a particular operation. It all depends on how much cache memory is available and how quickly a cache bucket can be locked.
So the test can fail spuriously.
This PR tries to minimally improve it, but it can stil fail.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13511/

attempt to improve a spuriously failing test

---

Documentation/DocuBlocks/Rest/Collections/post_api_collection.md

Adds a missing sentence to the documentation about the auto-increment key generator not being support in the cluster.
Affects only the documentation.
The documentation change has been made in devel already.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13628/

add missing sentence to documentation

---

arangod/ClusterEngine/ClusterCollection.cpp
arangod/ClusterEngine/ClusterEngine.cpp
arangod/ClusterEngine/ClusterEngine.h
arangod/ClusterEngine/ClusterIndex.cpp
arangod/IResearch/IResearchFeature.cpp
arangod/RocksDBEngine/RocksDBCollection.cpp
arangod/RocksDBEngine/RocksDBEngine.cpp
arangod/RocksDBEngine/RocksDBEngine.h

Small code cleanup PR
- only check for Mock storage engine in arangod/ClusterEngine in case we are building with google tests (otherwise there will be no Mock storage engine).
- fixed an unused variable warning for an unchcked return value for a call to RocksDBEngine::writeCreateCollectionMarker() in IResearchFeature when upgrading links.
- make RocksDBEngines's writeCreateCollectionMarker() return a Result instead of an int.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13697/

small code cleanup PR

---

CHANGELOG
arangod/Transaction/Methods.cpp

Improved logging for error 1489 ("a shard leader refuses to perform a replication operation"). The log message will now provide the database and shard name plus the differing information about the shard leader.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13696/

Improved logging for error 1489

---

tests/Aql/BitFunctionsTest.cpp

Fix a memleak that occurred only in AQL bit functions test code.
This does not affect any users, and does not need to be fixed in other versions.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13691/

fix a test-only memleak

---

CHANGELOG
arangod/RestHandler/RestDocumentHandler.cpp
tests/rb/HttpInterface/api-document-update-spec.rb

There is a small bug in the implementation of our API. If one updates
(or replaces) a single document and gives the key only in the URL
but not in the body of the document, and also adds the option 
`ignoreRevs=false` and specifies the `_rev` in the body, then this
rev is silently rewritten to 0 due to a bug.
This PR fixes this bug. Also see #13232.

Bug in behavior of ignoreRevs=false

---

arangod/Aql/EngineInfoContainerDBServerServerBased.cpp
arangod/StorageEngine/TransactionState.cpp
arangod/Transaction/Manager.cpp
arangod/Transaction/Manager.h
tests/js/client/shell/shell-transaction.js

Make sure that `lockTimeout` value is at least >= 0.
Passing in a value < 0 did not do any harm, but is clear a user error. So in this case, we will now tell the user.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13706/

validate lockTimeout value for transactions to be >= 0

---

CHANGELOG
arangod/RestHandler/RestDocumentHandler.cpp
tests/rb/HttpInterface/api-document-update-spec.rb

There is a small bug in the implementation of our API. If one updates
(or replaces) a single document and gives the key only in the URL
but not in the body of the document, and also adds the option
ignoreRevs=false and specifies the _rev in the body, then this
rev is silently rewritten to 0 due to a bug.
This PR fixes this bug. Also see #13232.
- [*] :hankey: Bugfix 
- [*] Backports required for: 3.6, 3.7
- [*] This PR adds tests that were used to verify all changes:
- [*] Added **Regression Tests**

Bug in behaviour of ignoreRevs=false

---

CHANGELOG
arangod/GeneralServer/CommTask.cpp
arangod/GeneralServer/RequestLane.h
arangod/GeneralServer/RestHandler.cpp
arangod/GeneralServer/RestHandler.h
arangod/RestServer/Metrics.h
arangod/RestServer/MetricsFeature.cpp
arangod/Scheduler/Scheduler.h
arangod/Scheduler/SupervisedScheduler.cpp
arangod/Scheduler/SupervisedScheduler.h

Added gauge `arangodb_scheduler_current_current_queue_time` to estimate the amount of time it takes a low priority queue item to bubble up to the queue's head (in ms).
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13698/

Added metric for current scheduler dequeue time

---

tests/CMakeLists.txt

The g++ unit test in `tests/Aql/OldSubqueriesTest.cpp` depends on the build being compiled with the `USE_FAILURE_TESTS=On` build option.
If the option is not set, the test will fail.
This PR hopefully fixes it, and only compiles and links the OldSubqueriesTest g++ unit test if `USE_FAILURE_TEST=On`.
It should not have any effect on end users. Because it is an internal change to the tests and only affects devel, there is intentionally no CHANGELOG entry written for it.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13736/

disable OldSubqueriesTest g++ unit test if USE_FAILURE_TESTS=Off

---

arangod/Aql/AqlItemBlockInputRange.cpp
arangod/Aql/AqlItemBlockInputRange.h
arangod/Aql/IdExecutor.cpp
tests/Aql/IdExecutorTest.cpp

This changes the method a IDExecutor skips over rows.
There are some assertions that it does not skip over shadowRows during i'ts produce phase (violates the API)
which have not ben triggered by our tests.
However as the IDExecutor will always skip over the entire input, this API violation is not relevant, it just does the operation in a different way than intended.
Now we explicitly only forward up to the next shadow row in produce.
=> No User Impact
=> No Changelog
- [] :hammer: Refactoring/simplification
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/13739/
> Bugs …

Fixed a too eager fast forwarding in ID executor.

---

lib/Basics/StringUtils.h
tests/Basics/StringUtilsTest.cpp

Added variadic `concat` and `join` functions to `StringUtils`.

StringUtils concat and join

---

CMakeLists.txt
Documentation/CMakeLists.txt
arangod/CMakeLists.txt

A minor change in the build system to no longer delete some custom targets during `make clean`. Namely:
- Installation/Windows/Plugins/exitcodes.nsh
- js/common/bootstrap/errors.js
- js/common/bootstrap/exitcodes.js
- lib/Basics/exitcodes.cpp
- lib/Basics/exitcodes.h
- lib/Basics/voc-errors.cpp
- lib/Basics/voc-errors.h
- README
- arangod/Aql/grammar.cpp
- arangod/Aql/tokens.cpp
The previous behaviour is undesirable, for one because those files are part of the source tree, and not just in the build directory. Second, because deleting some of these make both subsequent `make` or `cmake` commands fail, making it impossible to regenerate the files without checking them out again.

Set CLEAN_NO_CUSTOM for some directories

---

CHANGELOG
arangod/Cluster/ClusterTrxMethods.cpp
arangod/Cluster/ServerState.h
arangod/Cluster/SynchronizeShard.cpp
arangod/Cluster/TakeoverShardLeadership.cpp
arangod/Replication/DatabaseInitialSyncer.cpp
arangod/RestHandler/RestImportHandler.cpp
arangod/RocksDBEngine/RocksDBCollection.cpp
arangod/RocksDBEngine/RocksDBMetaCollection.cpp
arangod/RocksDBEngine/RocksDBMetadata.h
arangod/Transaction/ClusterUtils.cpp
arangod/Transaction/Manager.cpp
arangod/Transaction/Manager.h
arangod/Transaction/ManagerFeature.cpp
arangod/Transaction/ManagerFeature.h
arangod/Transaction/Methods.cpp
arangosh/Dump/DumpFeature.cpp
arangosh/Import/ImportFeature.cpp
tests/RocksDBEngine/TransactionManagerTest.cpp

This PR contains a zoo of small changes:
* Adds new metric `arangodb_transactions_expired` to track the total number of expired and then garbage-collected transactions
* Clarifies scope of another metric in the CHANGELOG
* Improves debug and warning log messages, by providing a bit more context
* Downgrades some log messages for recoverable errors into warnings (to comply with our log levels policy)
* micro-optimization for arangodump (no allocation of StringBuffer for masking data when no masking is used)
* micro-optimization for `/_api/import` handling: we can turn off `returnOld` even in case `onDuplicate=update` or `onDuplicate=replace`, because we are only using the "old" attribute in the return to distinguish inserts from updates/replaces. Setting `returnOld` is overkill here …

Various micro-optimizations

---

README_maintainers.md
arangod/RestHandler/RestStatusHandler.cpp

This adds documentation for memory profiling to README_maintainers.md.
It also fixes memory profiling for `devel`.
This is no user facing capability.

Fix and document memory profiling

---

CHANGELOG
arangod/RestServer/MetricsFeature.cpp

Turn off option `--server.export-read-write-metrics` for now, until there is certainty about the runtime overhead it introduces. I agreed on this with @neunhoef today.
There is currently some investigation ongoing by @neunhoef to measure the overhead of metrics in general, which will likely trigger some follow-up optimizations and lead to this option being turned on again by default. But we can do this all separately.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13813/

Turn off option `--server.export-read-write-metrics` for now

---

CHANGELOG
arangod/IResearch/IResearchFeature.cpp
arangod/IResearch/IResearchLink.cpp
arangod/VocBase/Methods/Upgrade.cpp
arangod/VocBase/Methods/Upgrade.h
tests/IResearch/IResearchFeature-test.cpp

PR fixes BTS-284 issue by moving  upgrading ArangoSearchLinks task to stage of DATABASE_EXISTING from DATABASE_UPGRADE as this task needs  enabled Cluster Feature which is not available during DATABASE_UPGRADE phase.
Also introduced new 'hint' flag for upgrade tasks DATABASE_ONLY_ONCE to mark tasks which should be run only once if was not run before and for new databases this task should either be run on DATABASE_INIT (if corresponding flag is set) or should be considered executed. Previously that was implicitly declared as having only DATABASE_UPGRADE flag for task. But as new name upgrade task is also 'one-shot' but has DATABASE_EXISTING this implicit consideration became unusable.
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/13828/

Bug fix 3.7/bts 284

---

CHANGELOG
js/apps/system/_api/foxx/APP/index.js
js/server/modules/@arangodb/foxx/manager.js
tests/js/client/shell/shell-foxx-api-spec.js

Fixes #12363. Backport of #12694 for 3.7.
This fixes a bug in the Foxx HTTP API where the `development` query parameter would not be parsed before being handed over to the Foxx Manager, resulting in `"false"` being interpreted as `true`.
Additionally:

Correctly handle development flag in upgrade (3.7)

---

CHANGELOG
js/apps/system/_api/foxx/APP/index.js
js/server/modules/@arangodb/foxx/service.js
tests/js/client/shell/shell-foxx-api-spec.js
tests/js/common/test-data/apps/with-configuration2/manifest.json

Fixes #12543. Backport of #12728 for 3.7.
This fixes the behavior of Foxx that was supposed to discard unused stored configuration options when options are renamed or removed after a service has been upgraded. These will result in warnings until discarded.
Additionally the warnings now indicate which configuration options they refer to, making them more meaningful to users.
The changes to tests in this PR overlap with #12694 but should merge cleanly.
Additionally:

Discard unused Foxx config when saving config in production (3.7)

---

arangod/Aql/AqlFunctionFeature.cpp
arangod/Aql/AqlFunctionFeature.h
arangod/Aql/Ast.cpp
arangod/Aql/Ast.h
arangod/Aql/Function.h
arangod/Aql/IndexNode.cpp
arangod/Aql/OptimizerRules.cpp
arangod/Aql/OptimizerRulesReplaceFunctions.cpp
arangod/Aql/grammar.cpp
arangod/Aql/grammar.y
tests/js/server/aql/aql-functions-misc.js

Add `Internal` flag for AQL functions.
Functions flagged `Internal` cannot be invoked by end users in queries, but they can be inserted by AQL-internal optimizations and transformations. That way we can add specialized internal functions for various purposes without having to provide API stability for them.
Internal functions are (intentionally) not listed in the documentation nor are they returned by any of the AQL functions inspection APIs.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13833/

Add `Internal` flag for AQL functions.

---

lib/V8/v8-utils.cpp

Don't log empty JavaScript exceptions.
In case we log a JavaScript exception to the logfile, unrecoverable exceptions without a message currently log "JavaScript exception:", which looks like a bug.
For example, this happens if the arangosh is ended by a script with something similar to `process.exit(1)`.
In this case, the exception that this thrown internally is unrecoverable, and does not have any message attached. So we can as well skip logging it.
`process.exit(...)` is not available in arangod, so this should mostly affect arangosh.
I found this by accident when working on https://github.com/arangodb/cluster-maintenance/pull/44, which always printed "JavaScript exception:" whenever I made mistakes with the startup parameters for the commands I tried. …

don't log empty JavaScript exception

---

CHANGELOG
lib/Logger/LoggerFeature.cpp

Remove logging options `--log.api-enabled` and `--log.keep-logrotate` for client tools (arangosh, arangodump, arangorestore etc.), as these options are only meaningful for arangod.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13831/

Remove logging options `--log.api-enabled` and `--log.keep-logrotate` for client tools

---

js/client/modules/@arangodb/testutils/process-utils.js

this fixes an incident where the server comes up, but we can't reach it because of other reasons.

add timeout if the server seems to be alive but we can't reach it after er 5 minutes bail out.

---

arangod/IResearch/IResearchRocksDBLink.h
arangod/RocksDBEngine/RocksDBBuilderIndex.cpp
arangod/RocksDBEngine/RocksDBBuilderIndex.h
arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
arangod/RocksDBEngine/RocksDBEdgeIndex.h
arangod/RocksDBEngine/RocksDBFulltextIndex.cpp
arangod/RocksDBEngine/RocksDBFulltextIndex.h
arangod/RocksDBEngine/RocksDBGeoIndex.cpp
arangod/RocksDBEngine/RocksDBGeoIndex.h
arangod/RocksDBEngine/RocksDBIndex.cpp
arangod/RocksDBEngine/RocksDBIndex.h
arangod/RocksDBEngine/RocksDBPrimaryIndex.cpp
arangod/RocksDBEngine/RocksDBPrimaryIndex.h
arangod/RocksDBEngine/RocksDBTtlIndex.cpp
arangod/RocksDBEngine/RocksDBTtlIndex.h
arangod/RocksDBEngine/RocksDBVPackIndex.cpp
arangod/RocksDBEngine/RocksDBVPackIndex.h

Make OperationOperations parameter const in internal RocksDB index APIs.
This is an internal API change only, and has no effect for end users or externally visible APIs.
As this is a simple internal-only change, there is intentionally no CHANGELOG entry.
If this change does not work, the compiler will tell us.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13858/

make OperationOptions const in index operations

---

CHANGELOG
arangod/RestHandler/RestAdminLogHandler.cpp
arangod/RestHandler/RestAdminLogHandler.h
lib/Logger/LogBufferFeature.cpp
lib/Logger/LogBufferFeature.h
lib/Logger/LogGroup.h
lib/Logger/Logger.cpp
lib/Logger/Logger.h
lib/Logger/LoggerFeature.cpp
lib/Logger/LoggerFeature.h
lib/V8/v8-utils.cpp
tests/js/client/server_parameters/log-max-length-default.js
tests/js/client/server_parameters/log-max-length-large.js
tests/js/client/server_parameters/log-max-length-small.js
tests/js/client/server_parameters/test-log-api-enabled-false.js
tests/js/client/server_parameters/test-log-api-enabled-true.js
tests/js/client/server_parameters/test-log-in-memory-level-err.js
tests/js/client/server_parameters/test-log-in-memory-level-fatal.js
tests/js/client/server_parameters/test-log-in-memory-level-info.js
tests/js/client/server_parameters/test-log-in-memory-level-warn.js
tests/js/client/server_parameters/test-log-in-memory-off.js

Enterprise companion PR: https://github.com/arangodb/enterprise/pull/644
Docs PR: https://github.com/arangodb/docs/pull/616
Improvements for logging. This adds the following startup options to arangod:
- `--log.max-entry-length`: controls the maximum line length for individual log messages that are written into normal logfiles by arangod (note: this does not include audit log messages). 
Any log messages longer than the specified value will be truncated and the suffix '...' will be added to them. The purpose of this parameter is to shorten long log messages in case there is not a lot of space for logfiles, and to keep rogue log messages from overusing resources. 
The default value is 128 MB, which is very high and should effectively mean downwards-compatiblity with previous arangod …

improvements for logging

---

arangod/VocBase/Methods/Upgrade.cpp
tests/IResearch/IResearchFeature-test.cpp

Additional fix for BTS-284. Forces DATABASE_UPGRADE  flag during database.auto-upgrade even iv Version check reports VERSION_MATCH. This covers upgrade between patches (e.g. 3.7.6->3.7.7)
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/13869/

force DATABASE_UPGRADE flag on upgrade

---

arangod/VocBase/Methods/Upgrade.cpp
tests/IResearch/IResearchFeature-test.cpp

Additional fix for BTS-284. Forces DATABASE_UPGRADE  flag during database.auto-upgrade even iv Version check reports VERSION_MATCH. This covers upgrade between patches (e.g. 3.7.6->3.7.7)
Backport to 3.7 https://github.com/arangodb/arangodb/pull/13498
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/13872/

Bug fix/bts 284.2

---

arangod/Cluster/AgencyCache.h

Don't allow discarding the result of AgencyCache::waitFor(), because as consequence, all kinds of things can go wrong.
This PR will prevent this from happening by adding the `[[nodiscard]]` attribute to the method, so its result must be handled.
If something does not work or some existing code does not handle the result yet, the compiler will tell us by issuing a warning, which will be turned into a compile error.
This is an internal change without any end-user visibility, so it is intentionally lacking a CHANGELOG entry.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13877/

for obvious reasons, don't discard the future!

---

CHANGELOG
Documentation/DocuBlocks/Rest/Administration/get_admin_log.md
Documentation/DocuBlocks/Rest/Collections/get_api_collections.md
arangod/RestHandler/RestAdminLogHandler.cpp
arangod/RestHandler/RestAdminLogHandler.h
lib/Logger/LogBufferFeature.cpp
lib/Logger/LogBufferFeature.h
lib/Logger/LogGroup.h
lib/Logger/Logger.cpp
lib/Logger/Logger.h
lib/Logger/LoggerFeature.cpp
tests/Basics/LoggerTest.cpp
tests/js/client/server_parameters/log-json-max-length-small.js
tests/js/client/server_parameters/log-json.js
tests/js/client/server_parameters/test-log-api-enabled-true.js
tests/js/client/shell/shell-admin-log.js

Docs PR: https://github.com/arangodb/docs/pull/617
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/646
More improvements for logging:
* Added new REST API endpoint GET `/_admin/log/entries` to return log entries in a more intuitve format, putting each log entry with all its properties into an object. The API response is an array with all log message objects that match the search criteria.
This is an extension to the already existing API endpoint GET `/_admin/log`, which returned log messages fragmented into 5 separate arrays.
The already existing API endpoint GET `/_admin/log` for retrieving log messages is now deprecated, altough it will stay available for some time.
* Truncation of log messages now takes JSON format into account, so that the truncation of oversized …

more logging improvements

---

arangod/Agency/Store.h
arangod/Cluster/AgencyCache.h
arangod/Cluster/MaintenanceFeature.h
arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
arangod/RocksDBEngine/RocksDBVPackIndex.cpp

Minimal code cleanup. Fixes whitespace in function declarations, adds a code comment, plus adds an early exit for case in which `_estimator` is null in indexes. This situation should never occur, however, it is better to make the code safe by not derefencing a pointer that under some (other) conditions can be a nullptr.
This is an internal-only change and should not require any CHANGELOG entry.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13901/

micro cleanup

---

CHANGELOG
arangod/GeneralServer/GeneralServerFeature.cpp

The TLS reload route doesn't pass up own error messages. 
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/13928/

Bug fix/fix tls reload result

---

CHANGELOG
arangod/GeneralServer/GeneralServerFeature.h

backport of https://github.com/arangodb/arangodb/pull/13529
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/13933/

fix reloading of TLS certificates error reporting

---

js/common/modules/@arangodb/aql/explainer.js

Prepare AQL query explainer code in 3.7 for a forthcoming change to the explain output of DistributeNodes in 3.8, so that the 3.7 explainer can handle both types of DistributeNode.
This change will only have an effect if a 3.7 explainer is used against a 3.8 cluster, which is relatively unlikely, but possible.
There is intentionally no CHANGELOG entry for this, as it is a very minor adjustment only.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13910/

prepare explainer code for 3.8 DistributeNode output

---

arangod/Replication/DatabaseInitialSyncer.cpp
arangod/RocksDBEngine/RocksDBCollection.cpp
arangod/RocksDBEngine/RocksDBIncrementalSync.cpp
arangod/RocksDBEngine/RocksDBMethods.h
arangod/RocksDBEngine/RocksDBPrimaryIndex.cpp
arangod/RocksDBEngine/RocksDBVPackIndex.cpp
arangod/Utils/OperationOptions.cpp
arangod/Utils/OperationOptions.h

Renames an internal boolean flag to a more appropriate name, and adds a code comment about its (updated) purpose.
This is an internal-only change, without user-visibile effects, so it is intentionally missing a CHANGELOG entry.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13945/

rename an internal flag

---

CHANGELOG
scripts/startLeaderFollower.sh
scripts/startLocalCluster.sh
scripts/startStandAloneAgency.sh

Try to raise file descriptors limit in local start scripts.
The start scripts in `scripts/` (used for development, not production) now try to raise the file descriptors limit to 128K.
That is not guaranteed to work, so they also add the startup parameter `--server.descriptors-minimum 0` to also allow the startup even when only few file descriptors can be used.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13962/

try to raise file descriptors limit in local start scripts

---

tests/js/common/shell/shell-ttl.js

Attempt to make shell-ttl test more robust in cluster.
This only adjusts the test, but no server code. So no CHANGELOG entry was made for it.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13968/

attempt to make ttl test more reliable

---

CHANGELOG
arangod/ClusterEngine/ClusterEngine.cpp
arangod/ClusterEngine/ClusterTransactionCollection.cpp
arangod/Replication/DatabaseInitialSyncer.cpp
arangod/RocksDBEngine/CMakeLists.txt
arangod/RocksDBEngine/RocksDBCollection.cpp
arangod/RocksDBEngine/RocksDBCollection.h
arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
arangod/RocksDBEngine/RocksDBFulltextIndex.cpp
arangod/RocksDBEngine/RocksDBGeoIndex.cpp
arangod/RocksDBEngine/RocksDBIncrementalSync.cpp
arangod/RocksDBEngine/RocksDBIndex.cpp
arangod/RocksDBEngine/RocksDBIndex.h
arangod/RocksDBEngine/RocksDBMetaCollection.cpp
arangod/RocksDBEngine/RocksDBMethods.cpp
arangod/RocksDBEngine/RocksDBMethods.h
arangod/RocksDBEngine/RocksDBPrimaryIndex.cpp
arangod/RocksDBEngine/RocksDBPrimaryIndex.h
arangod/RocksDBEngine/RocksDBReplicationContext.cpp
arangod/RocksDBEngine/RocksDBSavePoint.cpp
arangod/RocksDBEngine/RocksDBSavePoint.h
arangod/RocksDBEngine/RocksDBTransactionState.h
arangod/RocksDBEngine/RocksDBVPackIndex.cpp
arangod/RocksDBEngine/RocksDBVPackIndex.h
arangod/Utils/OperationOptions.h
tests/js/server/replication/sync/replication-sync-malarkey.js

Partial backport of https://github.com/arangodb/arangodb/pull/13507
Improve incremental sync replication for single server and cluster to cope with multiple secondary index unique constraint violations (before this was limited to a failure in a single unique secondary index). this allows replicating the leader state to the follower in basically any order, as any *other* conflicting documents in unique secondary indexes will be detected and removed on the follower.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13916/

Improve incremental sync replication

---

CHANGELOG
arangod/Cluster/ClusterInfo.cpp
arangod/Cluster/ClusterInfo.h
arangod/ClusterEngine/ClusterCollection.cpp
arangod/RocksDBEngine/RocksDBCollection.cpp
arangod/RocksDBEngine/RocksDBMetaCollection.cpp
arangod/StorageEngine/PhysicalCollection.cpp
arangod/StorageEngine/PhysicalCollection.h
arangod/VocBase/Methods/Indexes.cpp
js/common/modules/@arangodb/foxx/store.js
tests/js/server/shell/shell-index-parallel-drop-create.js

* Avoid a potential deadlock when dropping indexes.
A deadlock could theoretically happen for a thread that is attempting to drop an index in case there was another thread that tried to create or drop an index in the very same collection at the very same time. We haven't managed to trigger the deadlock with concurrency tests, so it may have been a theoretical issue only. The underlying code was changed anyway to make sure this will not cause problems in reality.
* Make dropping of indexes in cluster retry in case of precondition failed.
When dropping an indexes of a collection in the cluster, the operation could fail with a "precondition failed" error in case there were simultaneous index creation or drop actions running for the same collection. The error was returned properly internally, …

Improvements for dropping indexes

---

arangod/Pregel/Conductor.cpp
tests/js/common/shell/shell-statement.js
tests/js/server/shell/shell-index-parallel-drop-create.js

Adds 3 unrelated changes:
* Add a missing index-create-drop test that was forgotten when forward-porting a change to devel
* Clean up streaming cursor in `shell-statement` test
* Fix log message in Pregel
These are all internal, minor fixes, so the PR intentionally does not add a CHANGELOG entry.
The missing test is present in 3.6 and 3.7, so does not need to be added there.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13977/

added a missing test, clean up in another

---

CHANGELOG
js/apps/system/_admin/aardvark/APP/frontend/js/views/databaseView.js

Improve the wording for sharding options displayed in the web interface.
Instead of offering `flexible` and `single`, now use the more intuitive `Sharded` and `OneShard` options, and update the help text for them (refer to attached screenshots for details).
We may need to adjust documentation referring to "single" and "flexible" before we can merge this. We also need to decide whether this should be backported to 3.7 or not.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13971/

improve wording for database sharding options in UI

---

CHANGELOG
arangod/Aql/Collection.cpp
arangod/Aql/Collection.h
arangod/Aql/GraphNode.cpp
arangod/Aql/QuerySnippet.cpp
arangod/Sharding/ShardingInfo.cpp
arangod/Sharding/ShardingInfo.h
arangod/VocBase/LogicalCollection.cpp
arangod/VocBase/LogicalCollection.h

Potential bugfix/workaround for issues with disjoint smart graph queries that have a "WITH" declaration and that can refer to other collections/shards, on different servers.
Given a query such as
```
WITH a, c
FOR v, e IN 1 .. 1 ANY "a/11:82238118" b 
FOR doc in c
FILTER doc.color == e.color
RETURN doc
```
and collections with the following setup:
* `a` is a disjoint smart vertex collection, with 3 shards, on 3 different servers
* `b` is a disjoint smart edge collection, with 3 shards, on 3 different servers
* `c` is an unrelated collection, with just 1 shard, on only one server
The problem here is that `a` and `b` are distributed in the same way, but `c` is not. Especially, on some servers that there will be no shards for `c`.
Now, when the query snippets are created, all extra vertex …

potential bugfix for disjoint smartgraph queries that refer to collections on other servers

---

CHANGELOG
arangod/Aql/QueryCursor.cpp
arangod/Utils/Cursor.h
tests/js/common/shell/shell-statement.js

Backport of https://github.com/arangodb/arangodb/pull/13516
Fix profiling of AQL queries with the `silent` and `stream` options sets in combination. Using the `silent` option makes a query execute, but discard all its results instantly. This led to some confusion in streaming queries, which can return the first query results once they are available, but don't necessarily execute the full query.
Now, `silent` correctly discards all results even in streaming queries, but this has the effect that a streaming query will likely be executed completely when the `silent` option is set. This is not the default however, and the `silent` option is normally not set. There is no change for streaming queries if the `silent` option is not set. …

Fix profiling of streaming AQL queries

---

CHANGELOG
arangod/Aql/IndexExecutor.cpp
arangod/Aql/IndexExecutor.h
tests/js/server/aql/aql-queries-optimizer-count.js

This PR fixes issue #DEVSUP-720:
Within an AQL query, the "COLLECT WITH COUNT INTO" statement could lead to a wrong count output when used in combination with an index which has been created with an array index attribute.
Ticket: 
Link to Jenkins PR run: http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/13997/

Fixed a count collect bug

---

CHANGELOG
Installation/Windows/Plugins/exitcodes.nsh
arangod/RestServer/FileDescriptorsFeature.cpp
js/common/bootstrap/exitcodes.js
lib/Basics/exitcodes.dat
lib/Basics/exitcodes.h

The required ulimit -n value is 8k according to the changelog entry. This PR adjusts the code to actually do this. 
The previously existing 65536 shouldn't be used in any case, since the ubuntu user default seems to be 65535 - 
which would be a better fit and introduce less support cases.
Details see https://arangodb.atlassian.net/browse/BTS-311

adjust value to changelog entry

---

CHANGELOG
arangod/RestServer/BootstrapFeature.cpp
arangod/RestServer/BootstrapFeature.h

Try to stabilize a flaky foxx test.
Ideally, this could fix https://arangodb.atlassian.net/browse/BTS-268
The problem seems to have been a race a coordinator startup between databases appearing in Current and the JavaScript code that runs on coordinators at startup.
On initial start, the coordinator created the system database by writing an entry in the agency's Plan. It did not wait for the system database to appear in Current. So it happily went on executing the JavaScript startup code for coordinators, which iterates over all databases and registers an in-memory value for each.
In case all DB servers now created the system database in Current quickly enough, this was not a problem, and everything went fine.
However, in case not all DB servers created the system database in Current …

Fixed issue BTS-268: fix a flaky Foxx test.

---

CHANGELOG
arangod/Aql/Collection.cpp
arangod/Aql/Collection.h
arangod/Aql/GraphNode.cpp
arangod/Aql/QuerySnippet.cpp
arangod/Sharding/ShardingInfo.cpp
arangod/Sharding/ShardingInfo.h
arangod/VocBase/LogicalCollection.cpp
arangod/VocBase/LogicalCollection.h

Forward Port of:
https://github.com/arangodb/arangodb/pull/13538
There have been no merge conflicts.
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/649
Potential bugfix/workaround for issues with disjoint smart graph queries that have a "WITH" declaration and that can refer to other collections/shards, on different servers.
Given a query such as
```
WITH a, c
FOR v, e IN 1 .. 1 ANY "a/11:82238118" b 
FOR doc in c
FILTER doc.color == e.color
RETURN doc
```
and collections with the following setup:
* `a` is a disjoint smart vertex collection, with 3 shards, on 3 different servers
* `b` is a disjoint smart edge collection, with 3 shards, on 3 different servers
* `c` is an unrelated collection, with just 1 shard, on only one server
The problem here is that `a` and `b` …

Bug fix/disjoint smart graph heterogeneous sharding

---

CHANGELOG
CMakeLists.txt

For Windows builds, remove the defines `_SILENCE_ALL_CXX17_DEPRECATION_WARNINGS` and `_ENABLE_ATOMIC_ALIGNMENT_FIX` from our CMakeListst.txt.
These defines were needed to build Boost components with MSVC in older versions of Boost and MSVC.
Both of these defines are obsolete nowadays.
The `_SILENCE_ALL_CXX17_DEPRECATION_WARNINGS` define was used inside Boost, but is not used there in the version we currently use.
The `_ENABLE_ATOMIC_ALIGNMENT_FIX` was necessary for MSVC to produce correct code in the past. It is also obsolete by now (refer to https://github.com/microsoft/STL/issues/717).
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/14036/

Remove outdated compile definitions for MSVC/Boost

---

arangod/Replication/DatabaseInitialSyncer.cpp
arangod/Replication/ReplicationFeature.cpp
tests/js/client/shell/shell-quick-keys-noncluster.js
tests/js/server/replication/sync/replication-sync-malarkey.js

Cleanup after initial syncer "quick" feature addition (https://github.com/arangodb/arangodb/pull/13394) was merged:
- fixes wrong version number for new startup option
- adds code comments
- adds new test that explicitly tests the "quick" parameter
- adds missing lower bound for the wait time
Re the last point, the previous calculation used a default value of 300 implictly, but in a non-obvious way:
```
if (ndocs > 3750000) { // only bother beyond a 
maxWaitTime = ndocs * 80;
}
```
This would fall apart if the default value of 300 seconds for the wait time was ever adjusted, and it was not obvious in the code how 3850000 and the default wait time were related.
This is now
```
// use a lower bound for maxWaitTime of 180M microseconds, i.e. 180 seconds
constexpr uint64_t …
```

clean up after initial syncer changes, add tests

---

arangod/RestServer/MetricsFeature.cpp
lib/Logger/LoggerFeature.cpp

Enterprise companion PR: https://github.com/arangodb/enterprise/pull/651
Fix wrong version numbers introduced for backported logging options.
The docs say the options are available in 3.7.8, and that was also the idea.
However, 3.7.8 was built based on 3.7.7 with just a single commit on top, and that rendered all plans invalid.
This PR fixes the version number in the docs to 3.7.9, which will be the real release these options become available.
It also fixes the version number for another option, which was planned for 3.7.8, but was then introduced in 3.7.7.
This change only affects the docs, so there is intentionally no CHANGELOG entry for it.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/14045/

fix version number for options additions

---

lib/Logger/LogBufferFeature.cpp
lib/Logger/Logger.cpp
lib/Logger/Logger.h

Fix a potentially wrong length calculation after log messages were shrunk.
Reproduction: compile with ASan and execute:
```
scripts/unittest server_parameters --test log-max --cluster true
```
ASan errors are gone with the fix in place.
New ASan run:
http://172.16.10.101:8080/job/arangodb-ANY-linux-asan/560/
This is a fix for a yet-unreleased feature, so intentionally no CHANGELOG entry added for it.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/14050/
http://172.16.10.101:8080/job/arangodb-ANY-linux-asan/560/

fix a potential wrong length calculation after log messages were shrunk

---

3rdParty/velocypack/include/velocypack/velocypack-common.h

Rollback vpack part of changes in https://github.com/arangodb/arangodb/pull/13569 as performance tests have discovered a regression.
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/14052/

revert vpack optimizations due to bad performance tests results

---

CHANGELOG
lib/ApplicationFeatures/ApplicationServer.cpp
lib/ApplicationFeatures/ShellColorsFeature.cpp
lib/ApplicationFeatures/ShellColorsFeature.h
lib/ProgramOptions/ProgramOptions.cpp
lib/ProgramOptions/ProgramOptions.h
lib/ProgramOptions/Section.cpp
lib/ProgramOptions/Section.h

Small improvements for program options documentation:
* add optional hyperlink to program option sections, so that one can link to our docs
* add optional subheadlines to program options, so that it is possible to add better grouping
This is experimental and may not be followed to the end.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/14048/

add optional hyperlink for program option sections, add subheadlines

---

lib/Logger/Logger.cpp
lib/Logger/Logger.h

Small cleanup for some logging code
* moved some parts of LogMessage from header to cpp file, so less recompilation will be required if that code is changed later on
* verify that `_offset` does not point outside the log message after shrinking. this is very unlikely, because offset is something between 20 or 30 characters only, and the minimum log message length for shrinking is 256 characters. so it is a theoretical issue right now, but the fix will be useful should the limits/bounds be changed later.
Inspired by a fix that was necessary for 3.7, but didn't affect devel: https://github.com/arangodb/arangodb/pull/13580
Intentionally no CHANGELOG entry written, as it is an internal code cleanup PR only, without effects for end users. …

move some parts of LogMessage from header to cpp file

---

CHANGELOG
arangosh/CMakeLists.txt
arangosh/Dump/arangodump.cpp
arangosh/Restore/RestoreFeature.cpp
arangosh/Restore/arangorestore.cpp
arangosh/Utils/ClientManager.cpp
arangosh/Utils/ClientManager.h
arangosh/Utils/ProgressTracker.h
js/client/modules/@arangodb/testsuites/dump.js
js/client/modules/@arangodb/testutils/process-utils.js

Add JWT secret support for arangodump and arangorestore, i.e. they now also provide the command-line options `--server.ask-jwt-secret` and `--server.jwt-secret-keyfile` with the same meanings as in arangosh.
This also adds a new test suite `dump_jwt` to the tests.
Oskar PR: https://github.com/arangodb/oskar/pull/293
Blocklist PRs for older branches:
* 3.6: arangodb/arangodb#13586
* 3.7: arangodb/arangodb#13587
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/14054/

Add JWT secret support for arangodump and arangorestore

---

js/client/modules/@arangodb/testutils/result-processing.js

This PR adds the setup/teardown times to the `locateLongRunning` analyzer suite:
```
shell_client - startup [1.005397081375122] => run [12.465092658996582] => shutdown [3.002624034881592]
' - 0:12 - ^ 0:01 v 0:00 - 9 - [0:13] - tests/js/common/shell/shell-pregel-4.js':
processStatistics:
minorPageFaults: 79432
majorPageFaults: 160
userTime: 10.71
systemTime: 1.3499999999999999
numberOfThreads: 3
residentSize: 48750592
residentSizePercent: 0.0007243830738783703
virtualSize: 1779642368
rchar: 54943
wchar: 11176252
syscr: 6825
syscw: 13060
read_bytes: 155648
write_bytes: 13414400
cancelled_write_bytes: 2134016
stats:
- '0:04 - testMultiWCCParallelismMemoryMapping'
- '0:04 - testMultiWCCParallelism'
- '0:01 - testMultiWCC'
- '0:00 - testWithEdgeCollectionRestrictions'
- '0:00 - …
```

better visualize time consumed during setup / teardown

---

CHANGELOG
arangod/IResearch/IResearchLink.cpp

added logging of elapsed time of ArangoSearch commit/consolidation/cleanup jobs
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/14116/

3.7: added elapsed time logging

---

CHANGELOG
arangod/IResearch/IResearchLink.cpp

added logging of elapsed time of ArangoSearch commit/consolidation/cleanup jobs
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/14115/

added  elapsed time logging

---

arangod/Replication/ReplicationFeature.cpp
arangod/RestServer/QueryRegistryFeature.cpp
arangod/RocksDBEngine/RocksDBEngine.cpp
arangod/RocksDBEngine/RocksDBOptionFeature.cpp
arangosh/Dump/DumpFeature.cpp
arangosh/Shell/ConsoleFeature.cpp
lib/Logger/LogBufferFeature.cpp
lib/Logger/LoggerFeature.cpp

Don't list e.g. v3.5.0 if v3.4.5 implies that a feature is available in subsequent releases, as discussed with Jörg.
This only affects --help and the docs.

Docs: Don't list implied introducedIn versions

---

CHANGELOG
arangod/Agency/Supervision.cpp
arangod/Agency/Supervision.h
tests/Agency/SupervisionTest.cpp

Backport cleanup routine for hotbackup transfer jobs to 3.6.
See https://github.com/arangodb/arangodb/pull/13585
- [*] Bug-Fix for a *released version*
- [*] Added new C++ **Unit Tests** (Either GoogleTest or Catch-Test)

Cleanup hotbackup transfer jobs in agency

---

CHANGELOG
arangosh/Dump/DumpFeature.cpp
arangosh/Dump/DumpFeature.h
arangosh/Restore/RestoreFeature.cpp
tests/js/client/shell/shell-dump-integration.js

Added `--shard` option to arangodump, so that dumps can be restricted to one or multiple shards only.
In addition fix an unrelated assertion failure in arangorestore when using `--create-collection false` and clean up an old option in arangodump.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/14202/

Allow dumping of individual shards with arangodump

---

arangosh/Restore/RestoreFeature.cpp
arangosh/Utils/ProgressTracker.h
js/client/modules/@arangodb/testsuites/dump.js
js/client/modules/@arangodb/testutils/test-utils.js
js/client/modules/@arangodb/testutils/testing.js
tests/js/client/communication/test-kill.js
tests/js/client/shell/shell-deadlock-trx-hotbackup-cluster.js

Fix `dump_with_crashes` test suite, plus a few unrelated wrong usage of the global asan/tsan flags.
This PR only adjusts tests. There is no need for CHANGELOG or backports.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/14207/

fix dump tests

---

CHANGELOG
js/apps/system/_admin/aardvark/APP/frontend/scss/_general.scss
js/apps/system/_admin/aardvark/APP/frontend/scss/_queryView.scss
js/apps/system/_admin/aardvark/APP/react/public/assets/src/mode-aql.js

Avoid rare display issue in Web UI where `fi` is turned into a ligature that throws off the cursor position.
This seems to occur only on very few systems and we we not able to reproduce it, but it shouldn't hurt to disable ligatures.
Also fixes a mistake of [#13399](https://github.com/arangodb/arangodb/pull/13399/files#diff-f3cdfd124afe97d1e97528e938a91ca713fc35d46a65025b1ce950e2fe4b5e11) which added the AQL bit handling functions to a generated file instead of its source file. The rebuild also updates the generated file with missing AQL functions and fixes a typo.

Disable ligatures in CSS for Ace editor / fix mode-aql.js

---

CHANGELOG
js/apps/system/_admin/aardvark/APP/aardvark.js

* Fixed a bug in the web interface that displayed the error "Not authorized to
execute this request" when trying to create an index in the web interface in a
database other than `_system` with a user that does not have any access
permissions for the `_system` database.
The error message previously displayed error actually came from an internal
request made by the web interface, but it did not affect the actual index
creation.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/14266/

Fixed web UI "not authorized to execute this request" error

---

CHANGELOG
Documentation/DocuBlocks/Rest/Graph/general_graph_edge_create_http_examples.md
arangod/Graph/GraphOperations.cpp
js/common/bootstrap/errors.js
lib/Basics/error-registry.h
lib/Basics/errors.dat
lib/Basics/voc-errors.h
lib/Rest/GeneralResponse.cpp
tests/js/client/http/api-gharial-spec.js
tests/rb/HttpInterface/api-general-graph-spec.rb

Follow-up PR to #13560 to correct the error message to "referenced vertex collection is not part of graph" instead of "... does not exist". In the latter case, a different error and HTTP status 404 is returned. The actual check that raises error 1947 only looks at the edge definitions to determine if the vertex collection is part of the graph.

BTS-309: Rename error message 1947 to match actual behavior

---

CHANGELOG
arangod/Agency/Supervision.cpp

This PR fixes the following problem: If one switches the agency
supervision to maintenance mode and leaves this on for more than
24h, then the first run of the supervision maintenance would erase all
coordinators (and dbservers which are not shard leaders) in the agency
data. This leads to the coordinators (and potentially dbservers) become
invisible in the UI.
The reason for this is that after 24h the heartbeats arriving in the
agency have not been processed in the agency supervision (due to it
being in maintenance mode), therefore the subroutine
`cleanupExpiredServers` would erase the servers as a cleanup job.
The fix is to run this subroutine *after* the most recent heartbeats
have been processed and to update the transient store snapshot in
between.
*(Please describe the changes in …

Fix lost coordinators in UI after long maintenance

---

Documentation/DocuBlocks/Rest/Indexes/post_api_index_ttl.md

Using the document creation time is only one option, so the description was misleading.

TTL index: Correct & improve API description of expireAfter

---

tests/js/client/shell/shell-deadlock-trx-hotbackup-cluster.js

(Hopefully) make a hot backup test more stable, by allowing a certain number of failed hot backup attempts.
Failed attempts are possible if during the hot backup the cluster configuration changes. This possibility cannot be totally excluded.
So we allow _some_ failures in the test.
This only changes the behavior of a test, so there is no CHANGELOG entry for it.
The test change is already present in devel.

make a hot backup test less whimsical

---

arangod/RestHandler/RestAdminLogHandler.cpp
arangod/RestHandler/RestAdminLogHandler.h

The recently introduced feature to support viewing DBServer logs (#13637) used a blocking function to fetch the logs from the DB server.
This PR adaptes this function so that it uses the future in a non-blocking way.
No changelog entry is mande since this is a minor improvement for a new feature that already has a changelog entry.

Make reportLogs function non-blocking.

---

arangod/RocksDBEngine/RocksDBZkdIndex.cpp
arangod/RocksDBEngine/RocksDBZkdIndex.h
tests/js/server/aql/aql-optimizer-zkdindex-multi.js
tests/js/server/aql/aql-optimizer-zkdindex.js

This is feature development branch. It belongs to #13650 and will be merged into it. This branch adds support for strict comparsion operators. While the zkd index itself only allows the non-strict variants (and equality) we can add support for the strict operators by post-filtering in the index node in aql.

[zkd] Strict comparsion

---

arangosh/Export/ExportFeature.cpp
arangosh/Utils/ManagedDirectory.cpp

Write errors during arangoexport (in case e.g. the disk was full) were just ignored. Throw an exception instead.

Let arangoexport throw an exception in case of write errors

---

tests/js/client/shell/shell-vst-dump.js

Adds an extra integration test for the changes in https://github.com/arangodb/arangodb/pull/13638.
The test can be executed via
```
scripts/unittest shell_client --vst true --test shell-vst-dump.js
```
This PR only contains a test, so it intentionally lacks a CHANGELOG entry.

add an extra VST test

---

CHANGELOG
arangod/Aql/AqlItemMatrix.cpp
arangod/Aql/AqlItemMatrix.h
arangod/Aql/SortExecutor.cpp

Backported AQL sort performance improvements from devel (by @gnusi and @Dronplane).
This change can improve the performance of local sorts operations, e.g.
**Baseline (3.7.9)**:
Query String (94 chars, cacheable: false):
FOR i IN 1..500000 LET value = CONCAT('testvalue-to-be-sorted', i) SORT value ASC RETURN value
Id   NodeType            Calls    Items   Runtime [s]   Comment
1   SingletonNode           1        1       0.00003   * ROOT
2   CalculationNode         1        1       0.00003     - LET #2 = 1 .. 500000   /* range */   /* simple expression */
3   EnumerateListNode     500   500000       0.08725     - FOR i IN #2   /* list iteration */
4   CalculationNode       500   500000       0.22722       - LET value = CONCAT("testvalue-to-be-sorted", i)   /* simple …

Backported AQL sort performance improvements from devel

---

CHANGELOG
arangod/Aql/Functions.cpp
tests/js/server/aql/aql-functions.js

Fixed issue #13632: Query Fails on Upsert with Replace_nth
The problem was caused by the same AqlValueMaterializer being used to hold two objects at the same time, which obviously does not work.
No backports are required for 3.6, as REPLACE_NTH does not exist in 3.6.

fixed issue #13632

---

CHANGELOG
arangod/RestServer/FileDescriptorsFeature.cpp
lib/ApplicationFeatures/EnvironmentFeature.cpp

Lower the default value for required file descriptors from 64k to 8k.
this is done to avoid prolonged downtimes for users upgrading to 3.8 using _improperly configured environments_. In this case we still want to start, because the only other alternative is to fail hard and render the instance unavailable.
The very much preferred solution would be to expect a properly configured environment that can handle a large number of open files, and refuse to start otherwise. But that seems too much to expect in reality, as many people don't like reading upgrade notices, log warnings etc. and would get stuck then.
Still hopeful that we can get this through with the next major release (i.e. 4.0).

lower the default value for required file descriptors from 64k to 8k.

---

js/apps/system/_admin/aardvark/APP/frontend/js/templates/replicationView.ejs
js/apps/system/_admin/aardvark/APP/frontend/js/views/replicationView.js

Fix revolting "master"/"slave" terms in the replication UI of the web interface, and replace them with more adequate "leader"/"follower" terms.

fix anachronistic "master"/"slave" terms in the replication UI

---

CHANGELOG
arangod/Aql/CostEstimate.cpp
arangod/Aql/ExecutionNode.cpp
tests/js/server/aql/aql-optimizer-costs.js

When a NoResults node is in a spliced subquery the cost estimation will crash because the `estimateCosts` for the SubqueryStartNode was not called. Thus the stack for item estimates was not populated. Now the NoResults node
calls its parents `estimateCosts` and then sets the costs to zero.

SubQuery NoResults Cost Estimation

---

CHANGELOG
arangod/ClusterEngine/ClusterIndex.cpp
arangod/ClusterEngine/ClusterIndex.h
arangod/RocksDBEngine/RocksDBIndexFactory.cpp
arangod/RocksDBEngine/RocksDBVPackIndex.cpp
arangod/RocksDBEngine/RocksDBVPackIndex.h
arangod/VocBase/Methods/Indexes.cpp
arangod/VocBase/Methods/Indexes.h
arangod/VocBase/Methods/UpgradeTasks.cpp
js/apps/system/_admin/aardvark/APP/frontend/js/templates/indicesView.ejs
js/apps/system/_admin/aardvark/APP/frontend/js/views/indicesView.js
lib/Basics/StaticStrings.cpp
lib/Basics/StaticStrings.h
tests/js/common/shell/shell-index-estimates.js
tests/js/server/recovery/index-selectivity.js

Don't store selectivity estimate values for newly created system collections
Not storing the estimates has a benefit especially for the `_statistics`
system collections, which are written to periodically even on otherwise
idle servers. In this particular case, the actual statistics data was way
smaller than the writes caused by the index estimate values, causing a
disproportional overhead just for maintaining the selectivity estimates.
The change now turns off the selectivity estimates for indexes in all newly
created system collections, and for new user-defined indexes of type
"persistent", "hash" or "skiplist", there is now an attribute "estimates"
which can be set to `false` to disable the selectivity estimates for the index.
The attribute is optional. Not setting it will lead to the …

Don't store selectivity estimate values for newly created system collections

---

CHANGELOG
arangod/ClusterEngine/ClusterCollection.cpp
arangod/ClusterEngine/ClusterCollection.h
arangod/RestHandler/RestCollectionHandler.cpp
arangod/RocksDBEngine/RocksDBBackgroundThread.cpp
arangod/RocksDBEngine/RocksDBCollection.cpp
arangod/RocksDBEngine/RocksDBEngine.cpp
arangod/RocksDBEngine/RocksDBEngine.h
arangod/RocksDBEngine/RocksDBIndex.cpp
arangod/RocksDBEngine/RocksDBMetaCollection.cpp
arangod/RocksDBEngine/RocksDBMetaCollection.h
arangod/StorageEngine/PhysicalCollection.cpp
arangod/StorageEngine/PhysicalCollection.h
arangod/VocBase/LogicalCollection.cpp
arangod/VocBase/LogicalCollection.h
tests/Mocks/StorageEngineMock.cpp
tests/Mocks/StorageEngineMock.h

When dropping a collection or an index with a larger amount of documents, the
key range for the collection/index in RocksDB gets compacted. Previously, the
compaction was running in foreground and thus would block the deletion operations.
Now, the compaction is running in background, so that the deletion operations
can return earlier.
The maximum number of compaction jobs that are executed in background can be
configured using the new startup parameter `--rocksdb.max-parallel-compactions`,
which defaults to 2.
Performance implications of this change still need to be determined.

Compact collection and index ranges in background

---

CHANGELOG
arangosh/Utils/ManagedDirectory.cpp
arangosh/Utils/ManagedDirectory.h

On Windows `TRI_read_return_t` is defined as `int`, so previously `ManagedDirectory::File::offset()` was broken for files > 2GB.
This manifested itself as missing progress reports in arangoimport,

Fix return type of ManagedDirectory::File::offset().

---

tests/js/client/shell/shell-promtool.js

This PR adds a test to validate the output of our metrics API against Prometheus' `promtool` command.
The test intentionally only executes on Linux, and only if the `PROMTOOL_PATH` environment variable is set to the path containing the `promtool` executable. If `PROMTOOL_PATH` is set, but the executable cannot be found, the test will error out.
The test also requires `sh` to be a shell that supports input/output redirection, and `true` to be an executable that returns exit code 0 (we use `sh -c true` as a test to check the shell functionality).
Example invocation:
```
PROMOTOOL_PATH=/home/jsteemann/Downloads/prometheus/ scripts/unittest shell_client --test shell-promtool.js --cluster true
```
The promtool executable is part of a Prometheus distribution, and can be found in each Prometheus …

validate metrics API output against promtool

---

CHANGELOG
arangod/Cluster/ClusterFeature.cpp
arangod/Cluster/ClusterFeature.h
arangod/Cluster/ClusterInfo.cpp
arangod/Cluster/v8-cluster.cpp
tests/js/server/dump/dump-rocksdb-cluster.js
tests/js/server/dump/dump-rocksdb-modify.js

When a hotbackup is restored to a cluster which is a lot "younger" than
the one where it was taken, the entry Sync/LatestID in the agency in the
new cluster is a lot smaller than the one in the old cluster. Therefore,
the unique key generation does no longer work well. Therefore, it makes
sense to put the Sync/LatestID into the hotbackup and restore it with a
hotbackup restore. This solves the key generation problem at least in
this hotbackup related case.
This PR is a back port of the implementation of that, from #13699 .
Old hotbackups can still be restored, even if they do not contain
Sync/LatestID.

Bug fix 3.6/save unique id counter in agency with each hotback

---

Documentation/DocuBlocks/Rest/Administration/get_admin_log.md
Documentation/DocuBlocks/Rest/Administration/get_admin_metrics.md

Added missing parameters to REST API documentation.
This is a documentation-only change, so there is intentionally no CHANGELOG for it.

added missing documentation for extended REST APIs

---

Documentation/Metrics/allMetrics.yaml
Documentation/Metrics/arangodb_collection_lock_acquisition_micros_total.yaml
Documentation/Metrics/arangodb_collection_lock_acquisition_time.yaml
Documentation/Metrics/arangodb_collection_lock_sequential_mode_total.yaml
Documentation/Metrics/arangodb_collection_lock_timeouts_exclusive_total.yaml
Documentation/Metrics/arangodb_collection_lock_timeouts_write_total.yaml
Documentation/Metrics/arangodb_collection_truncate_time.yaml
Documentation/Metrics/arangodb_collection_truncates_replication_total.yaml
Documentation/Metrics/arangodb_collection_truncates_total.yaml
Documentation/Metrics/arangodb_document_insert_time.yaml
Documentation/Metrics/arangodb_document_read_time.yaml
Documentation/Metrics/arangodb_document_remove_time.yaml
Documentation/Metrics/arangodb_document_replace_time.yaml
Documentation/Metrics/arangodb_document_update_time.yaml
Documentation/Metrics/arangodb_document_writes_replication_total.yaml
Documentation/Metrics/arangodb_document_writes_total.yaml

Slightly improve documentation for a few metrics.
This is a documentation-only PR, so it intentionally has no CHANGELOG entry.
I ran the generateAllMetrics script and added the generated file to the PR.

document some metrics

---

CHANGELOG
arangod/Transaction/Methods.cpp

There is a bug in DOCUMENT method in AQL. That only shows up if upgraded from 3.6.* to 3.7.5
Where the DOCUMENT method may not return any documents anymore. This PR will only do a hot-fix
of the issue, the inconsistency in 3.6 and 3.7 format is not yet sorted out, but only DOCUMENT hits this case for now.
Original 3.7 PR:
https://github.com/arangodb/arangodb/pull/13324
Please note that for legal reasons we require you to sign the [Contributor …

Forward port of bugfix in AQL Document within one-shard database created in 3.6 series

---

CHANGELOG
lib/Basics/ResultError.h

Fix error message in case of index unique constraint violations.
The index error messages were lacking the actual base error description (i.e. "unique constraint violated") and only showed the index details. The issue was introduced only in devel in Feb.

Fix error message in case of index unique constraint violations.

---

tests/Graph/GenericGraphProviderTest.cpp

Fixed logical error. Type SingleServerProvider in "else if tree" used instead of the ClusterProvider type.
Found during testing.

Fixed logical error in MockGraphProviderTest

---

CHANGELOG
arangod/IResearch/IResearchLinkMeta.cpp

Backport of https://github.com/arangodb/arangodb/pull/13770
Fix an assertion failure that occurred when restoring view definitions from a cluster into a single server.
The assertion failure occured when running the following test
```
scripts/unittest dump_mixed_cluster_single --cluster true
```

Fix an assertion failure that occurred when restoring view definitions from a cluster into a single server

---

CHANGELOG
arangod/Replication/ReplicationFeature.cpp

Backport of https://github.com/arangodb/arangodb/pull/13772
Revert "change feature order so that ServerIdFeature is before ReplicationFeature (#13741)"
This reverts commit 959e27b26f80c5dd76c842a6155eb77d6de0d598.
This was an unsafe change, so we just roll it back.

Revert "change feature order so that ServerIdFeature is before ReplicationFeature (#13741)"

---

CHANGELOG
arangod/IResearch/IResearchLinkMeta.cpp

Fix an assertion failure that occurred when restoring view definitions from a cluster into a single server.
The assertion failure occured when running the following test
```
scripts/unittest dump_mixed_cluster_single --cluster true
```

Fix an assertion failure that occurred when restoring view definitions from a cluster into a single server.

---

CHANGELOG
arangod/Replication/ReplicationFeature.cpp

Revert "change feature order so that ServerIdFeature is before ReplicationFeature (#13743)"
This reverts commit 48dba7dd84a42fb164522134e941ea81d7efd5fe.
This was an unsafe change, so we now just roll it back.

Revert "change feature order so that ServerIdFeature is before ReplicationFeature (#13743)"

---

arangod/Replication/ReplicationFeature.cpp

Backport of https://github.com/arangodb/arangodb/pull/13772
Revert "change feature order so that ServerIdFeature is before ReplicationFeature"
This reverts commit 48dba7dd84a42fb164522134e941ea81d7efd5fe.
This was an unsafe change, so we just roll it back.

Revert "change feature order so that ServerIdFeature is before ReplicationFeature"

---

tests/Graph/GenericGraphProviderTest.cpp

Internal PR.
There is a variable that is unused within the test, but the called function has required side-effects.
No user impact.
Backport of https://github.com/arangodb/arangodb/pull/13785

Fixed unused variable warning

---

CHANGELOG
lib/Logger/LogAppender.cpp
lib/Logger/LogAppender.h

Backport of #13789 
`haveAppenders` is called as part of audit logging. It accesses `_topics2appenders` and `_globalAppenders` but previously did not hold a lock while doing so.
This problem only showed up because previously we used `operator[]` which inserts a new entry if none is found and this caused a memory leak in the ASan tests.

Fix race in LogAppender::haveAppenders.

---

CHANGELOG
arangod/Cluster/RebootTracker.cpp
arangod/Cluster/RebootTracker.h
arangod/Transaction/Manager.cpp
arangod/Transaction/Manager.h
arangod/Transaction/Options.cpp
arangod/Transaction/Options.h
tests/Mocks/Servers.cpp
tests/Mocks/Servers.h
tests/main.cpp

Partial backport of https://github.com/arangodb/arangodb/pull/13731
Use RebootTracker to abort cluster transactions on DB servers should the originating coordinator die or be rebooted. The previous implementation left the coordinator's transactions open on DB servers until they timed out there. 
Now, the coordinator's unavailability or reboot will be detected as early as it is reported by the agency, and all open transactions from that coordinator will be auto-aborted on DB servers.

Use RebootTracker to abort cluster transactions on DB servers

---

js/client/modules/@arangodb/testsuites/recovery_cluster.js

set the http-timeout on the arangosh doing the `setup` for the testcase. By it aborting after 60s we don't wait 15 minutes for the coordinator to return.

fix cluster recovery test timeouts

---

lib/Logger/Logger.h

This is a simple easy of use-PR for development that will NOT have any impact on customers.
For coverage testing we have a build flag to enable all LOG messages to be generated (ignoring the log level) s.t. these lines do not flag untested.
As an unwanted side-effect: If build with this flag, the ASSERT output in development mode was also discarded and not printed.
With this PR we will print assertions again even if we compile with the log-message flags.

Always enable FATAL log level, even with build unconditional log lines

---

CHANGELOG
arangod/Cluster/ClusterFeature.cpp
arangod/Cluster/ClusterFeature.h
arangod/RestHandler/RestAdminClusterHandler.cpp
arangod/V8Server/v8-actions.cpp
js/apps/system/_admin/aardvark/APP/aardvark.js
js/apps/system/_admin/aardvark/APP/frontend/js/routers/router.js
js/apps/system/_admin/aardvark/APP/frontend/js/templates/maintenanceView.ejs
js/apps/system/_admin/aardvark/APP/frontend/js/templates/navigationView.ejs
js/apps/system/_admin/aardvark/APP/frontend/js/templates/subNavigationView.ejs
js/apps/system/_admin/aardvark/APP/frontend/js/views/footerView.js
js/apps/system/_admin/aardvark/APP/frontend/js/views/maintenanceView.js
js/apps/system/_admin/aardvark/APP/frontend/js/views/navigationView.js
js/server/bootstrap/modules/internal.js
tests/js/client/server_permissions/test-cluster-jwt-policy-all.js
tests/js/client/server_permissions/test-cluster-jwt-policy-compat.js
tests/js/client/server_permissions/test-cluster-jwt-policy-write.js

Docs PR: https://github.com/arangodb/docs/pull/651
Add an option to lock down `/_admin/cluster` REST APIs.
* Add an option for locking down all endpoints in the `/_admin/cluster` REST
API for callers without a proper JWT set in the request. There is a new
startup option `--cluster.api-jwt-policy` that allows *additional* checks
for a valid JWT in requests to sub-routes of `/_admin/cluster`. The
possible values for the startup option are:
- "jwt-all": requires a valid JWT for all accesses to `/_admin/cluster` and
its sub-routes. If this configuration is used, the "Cluster" and "Nodes"
sections of the web interface will be disabled, as they are relying on the
ability to read data from several cluster APIs.
- "jwt-write": requires a valid JWT for write accesses (all HTTP methods
except HTTP …

Add an option to lock down `/_admin/cluster`.

---

CHANGELOG
arangod/GeneralServer/CommTask.cpp
arangod/Statistics/ConnectionStatistics.h

Fix connectionTime statistic. This statistic should provide the distribution of the connection lifetimes, but in previous versions the tracking was broken and no values were reported.

Fix connectionTime statistic.

---

CHANGELOG
arangod/GeneralServer/CommTask.cpp
arangod/Statistics/ConnectionStatistics.h

Backport of #13829
Fix connectionTime statistic. This statistic should provide the distribution of the connection lifetimes, but in previous versions the tracking was broken and no values were reported.

Bug fix 3.8/connection time statistic

---

Documentation/Metrics/allMetrics.yaml
Documentation/Metrics/arangodb_agency_commit_hist.yaml
Documentation/Metrics/arangodb_agency_compaction_hist.yaml
Documentation/Metrics/arangodb_agency_local_commit_index.yaml
Documentation/Metrics/arangodb_heartbeat_failures_total.yaml
Documentation/Metrics/arangodb_heartbeat_send_time_msec.yaml
Documentation/Metrics/arangodb_load_current_runtime.yaml
Documentation/Metrics/arangodb_load_plan_runtime.yaml
Documentation/Metrics/arangodb_network_forwarded_requests_total.yaml
arangod/Agency/Agent.cpp
arangod/Agency/RestAgencyHandler.cpp

Adds yaml documentation for the following metrics:
* arangodb_network_forwarded_requests_total 
* arangodb_heartbeat_failures_total 
* arangodb_heartbeat_send_time_msec 
* arangodb_agency_commit_hist 
* arangodb_agency_compaction_hist 
* arangodb_agency_local_commit_index 
* arangodb_load_current_runtime 
* arangodb_load_plan_runtime

documentation for more metrics

---

js/client/modules/@arangodb/testsuites/dump.js

Limit CI resource usage for the test from a random time to 20 attempts

to keep the execution time under control only permit 20 attempts of crashing the restore process

---

arangod/Statistics/StatisticsFeature.cpp

Backport of #13837
Add some assertions in maintainer mode that the metrics from the statistics feature are in sync with the new metrics used for documentation.

Feature 3.8/auto check statistics metrics

---

3rdParty/rocksdb/6.8/third-party/gtest-1.8.1/fused-src/gtest/gtest.h

This fixes a lot of compile warnings when compiling our own tests, which rely on gtest's TYPED_TEST. An `override` specifier was missing in gtest, so that using the TYPED_TEST macro from gtest always caused compile warnings.
This is an internal change for compiling the tests only, thus no need to write a CHANGELOG entry.

fix compile warnings about missing override specifier

---

CHANGELOG
CMakeLists.txt
arangod/Pregel/Conductor.cpp
lib/Logger/LogMacros.h
lib/Logger/Logger.h
lib/Logger/LoggerStream.cpp
lib/Logger/LoggerStream.h

Enterprise companion PR: https://github.com/arangodb/enterprise/pull/663
Remove CMake control variable `UNCONDITIONALLY_BUILD_LOG_MESSAGES`.
Now, any maintainer mode build will build all log messages automatically, so we will have full coverage of log message construction during our tests. In non-maintainer mode, log messages are still only built when actually required. This simplifies the build and increases coverage.

clean up logging a bit

---

CMakeLists.txt
lib/Basics/exitcodes.cpp
lib/CMakeLists.txt
utils/generateExitCodesFiles.py

Remove an unused file. This also has the benefit of cmake no longer shooting itself in the foot by removing it after switching branches or so, and no longer being able to configure the project because of it.

Removed (empty) exitcodes.cpp

---

CHANGELOG
arangod/Pregel/Conductor.cpp

Backport of some changes from https://github.com/arangodb/arangodb/pull/13870
Enterprise PR: https://github.com/arangodb/enterprise/pull/664
* Fix errors caused by creating some log messages in log level DEBUG in log
topics PREGEL and GRAPHS. Setting the log level to DEBUG for these topics
could lead to errors when running some Pregel jobs or SmartGraph traversals.

Fix some log messages

---

CHANGELOG
arangod/Aql/QueryCursor.cpp
arangod/RestHandler/RestCursorHandler.cpp

Fix velocypack errors in cursor API in case an exception occurs while the cursor result is being filled with data. In this case, the result could be in an arbitrary state (e.g. halfway produced), so adding more attributes to the result such as "error" and "code" was potentially unsafe. If the result was not properly built, trying to add "error" and "code" attributes could have led to arbitrary velocypack errors, which were then reported back to callers, masking the original error.
Now the original error is returned, and no attempt is made to write into the result after an exception has occurred.
The fix has already been made in devel and 3.8.

don't mask errors in cursor API with vpack errors

---

Documentation/Metrics/arangodb_intermediate_commits_total.yaml
Documentation/Metrics/arangodb_replication_cluster_inventory_requests_total.yaml
Documentation/Metrics/arangodb_replication_tailing_apply_time_total.yaml
Documentation/Metrics/arangodb_replication_tailing_request_time_total.yaml

Backport of #13873
Fix typos in metric documentation.

bug-fix 3.8/Fix typos in metric documentation.

---

CHANGELOG
arangod/RocksDBEngine/RocksDBOptionFeature.cpp

Backport of https://github.com/arangodb/arangodb/pull/13887
Deprecate option `--rocksdb.exclusive-writes`
The option was meant to serve only as a stopgap measure while porting applications from the MMFiles storage engine to RocksDB.

Deprecate option `--rocksdb.exclusive-writes`

---

CHANGELOG
arangod/GeneralServer/GeneralCommTask.h
arangod/GeneralServer/H2CommTask.cpp
arangod/GeneralServer/H2CommTask.h
arangod/GeneralServer/HttpCommTask.cpp
arangod/GeneralServer/HttpCommTask.h
arangod/GeneralServer/VstCommTask.cpp
arangod/GeneralServer/VstCommTask.h

Fix URLs in request logging
Fix logging of urls when using `--log.level requests=debug`. There was an issue since v3.7.7 with the wrong URL being logged in request logging if multiple requests were sent over the same connection. In this case, the request logging only reported the first URL requested in the connection, even for all subsequent requests.

Fix URLs in request logging

---

Documentation/Metrics/arangodb_intermediate_commits_total.yaml
Documentation/Metrics/arangodb_replication_cluster_inventory_requests_total.yaml
Documentation/Metrics/arangodb_replication_failed_connects_total.yaml
Documentation/Metrics/arangodb_replication_tailing_apply_time_total.yaml
Documentation/Metrics/arangodb_replication_tailing_request_time_total.yaml

Fix typos in metric documentation.
@neunhoef We should extend the script to validate that the yaml files contain only defined attributes, so we can catch typos in the attribute names.

Fix typos in metric documentation.

---

arangod/RestServer/Metrics.h

Make metrics `low()`/`high()` methods return data by value, not by reference.
This fixes a potential issue with accessing invalid memory.

make metrics low()/high() functions return by value

---

CHANGELOG
arangod/RestServer/Metrics.h

Backport of https://github.com/arangodb/arangodb/pull/13895
Make metrics `low()`/`high()` methods return data by value, not by reference.
This fixes a potential issue with accessing invalid memory.

 make metrics low()/high() functions return by value

---

CHANGELOG
arangod/RestServer/Metrics.h

Backport of https://github.com/arangodb/arangodb/pull/13895
Make metrics `low()`/`high()` methods return data by value, not by reference.
This fixes a potential issue with accessing invalid memory.

make metrics' low()/high() methods return by value

---

CHANGELOG
arangod/Aql/ExecutionPlan.cpp
arangod/RestServer/QueryRegistryFeature.cpp
arangod/RestServer/QueryRegistryFeature.h
js/common/bootstrap/errors.js
lib/Basics/error-registry.h
lib/Basics/errors.dat
lib/Basics/voc-errors.h
tests/js/client/server_parameters/test-allow-collections-in-expressions-off.js
tests/js/client/server_parameters/test-allow-collections-in-expressions-on.js
tests/js/server/aql/aql-optimizer-rule-parallelize-gather-cluster.js

Backport of https://github.com/arangodb/arangodb/pull/13872
Docs PR: https://github.com/arangodb/docs/pull/660
Added startup option `--query.allow-collections-in-expressions` to control whether collection names can be used in arbitrary places in AQL expressions, e.g. `collection + 1`. This was allowed before, as a collection can be seen as an array of documents. However, referring to a collection like this in a query would materialize all the collection's documents in RAM, making such constructs prohibitively expensive for medium-size to large-size collections.
The option can now be set to `false` to prohibit accidental usage of collection names in AQL expressions. With that setting, using a collection inside an arbitrary expression will trigger the error `collection used as expression …

Control unintended usage of collection names in AQL

---

arangod/Cluster/MaintenanceFeature.cpp
arangod/Cluster/MaintenanceRestHandler.cpp

Harden `MaintenaceFeature::addAction` function against invalid inputs.

harden addAction function against invalid inputs

---

CHANGELOG
arangod/Aql/AqlItemBlockManager.cpp
tests/js/client/server_permissions/test-memory-limit.js

Backport of https://github.com/arangodb/arangodb/pull/13902
Fixed issue [BTS-353](https://arangodb.atlassian.net/browse/BTS-353). This fixes a memleak when running into an out-of-memory situation while repurposing an existing AqlItemBlock.
This bugfix can be validated by running `scripts/unittest server_parameters --test tests/js/client/server_parameters/test-memory-limit.js` in an ASan-enabled build.

Fixed issue BTS-353

---

arangod/Agency/Node.h
tests/Agency/NodeTest.cpp

Fix self-assignment in Node.h's `SmallBuffer`, and add tests for self-assignment for copy & move.
This is an internal change and currently has no user-visible effects (self-assignment is currently not used).

fix self-assignment in SmallBuffer

---

CHANGELOG
CMakeLists.txt
lib/Logger/LogMacros.h
lib/Logger/Logger.h
lib/Logger/LoggerStream.cpp
lib/Logger/LoggerStream.h

Remove CMake control variable `UNCONDITIONALLY_BUILD_LOG_MESSAGES`.
This removes a bit of coverage for log messages in case the CMake variable was turned on. However, it isn't consistently used even by our own builds. In devel/3.9 this is properly fixed by always generating all log messages in maintainer mode, thus having maximum coverage without requiring additional build variables.
There is also an Oskar PR to remove the variable there: https://github.com/arangodb/oskar/pull/312

Remove CMake control variable `UNCONDITIONALLY_BUILD_LOG_MESSAGES`

---

arangod/Cluster/SynchronizeShard.cpp
arangod/Cluster/SynchronizeShard.h
arangod/Network/NetworkFeature.cpp
arangod/RestHandler/RestReplicationHandler.cpp
arangod/Sharding/ShardDistributionReporter.cpp
tests/js/client/shell/shell-revisions-noncluster.js

Fix an invalid internal timeout value of 0s, which lead to an assertion failure/division by zero issue.
Fix an internal "builder value not yet sealed" error when exchanging documents via the `/_api/replication/revisions/documents` API that in total were bigger than the hard-coded chunk size of 16MB.
Both issues are present in 3.8/devel only.

fix some issues found during manual fuzzing

---

arangod/IResearch/IResearchAnalyzerFeature.cpp
tests/IResearch/IResearchAnalyzerFeature-test.cpp
tests/js/common/aql/aql-view-arangosearch-feature.js

Fix for BTS-357
TOKENS function will now correctly process analyzer with non-string value types

Bug fix/bts 357

---

CHANGELOG
arangod/Cluster/ClusterMethods.cpp
arangod/RestHandler/RestCollectionHandler.cpp

Backport of https://github.com/arangodb/arangodb/pull/13931
Added error handling for figures command in cluster. Previously errors returned by shards were ignored when aggregating the individual responses.

Added error handling for cluster figures command

---

Documentation/DocuBlocks/Rest/Administration/get_admin_log.md

Minor change to avoid duplicate headline and to mark the old endpoint as deprecated more clearly.

DocuBlock: Improve deprecation hint for /_admin/log

---

arangod/RestHandler/RestCollectionHandler.cpp

behave honest to the wrongly API on DB-Server using instead of silently ignoring the collection cretion or asserting.
use arangosh to create a collection on a dbserver.
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/14776/

instead of silently ignoring / asserting return an error if one tries to create a collection on a dbserver

---

arangod/GeneralServer/GeneralServerFeature.cpp

Backport of https://github.com/arangodb/arangodb/pull/13948
Deprecate startup options `--http.hide-product-header` and `--http.allow-method-override`.
These options are seldomly used and do not provide a lot of value.
The options are only marked as deprecated by this PR, but are still functional.

deprecate startup options `--http.hide-product-header` and `--http.allow-method-override`

---

arangod/Aql/Collection.cpp

Instead of running into an assertion failure and not getting proper error messages from testing.js, make arangod throw a meaningful exception message, so we can better understand what is going on in the context of BTS-354.

better debugging for BTS-354

---

Documentation/DocuBlocks/Rest/Collections/post_api_collection.md
Documentation/DocuBlocks/collectionDatabaseCreate.md
Documentation/DocuBlocks/collectionProperties.md

Fix wrong data type in the documentation (`array` should be `object`).
This is a documentation-only bugfix.

fix error in the documentation

---

CHANGELOG
arangod/Aql/EngineInfoContainerDBServerServerBased.cpp
arangod/Aql/ExecutionEngine.cpp
arangod/Aql/Query.cpp
arangod/Aql/Query.h
arangod/Aql/QueryContext.h
arangod/Aql/QueryCursor.cpp
arangod/Aql/QueryCursor.h
arangod/Aql/QueryProfile.cpp
arangod/Aql/QueryRegistry.cpp
arangod/Aql/QueryRegistry.h
arangod/IResearch/IResearchAqlAnalyzer.cpp
arangod/RestHandler/RestCursorHandler.cpp
arangod/RestServer/DatabaseFeature.cpp
arangod/Utils/Cursor.h
arangod/Utils/CursorRepository.cpp
arangod/V8Server/v8-voccursor.cpp
js/client/bootstrap/modules/internal.js
tests/js/common/shell/test-kill-queries.js

Backport of https://github.com/arangodb/arangodb/pull/13939
No changes applied
This PR adds many tests for killing AQL queries at specific "dangerous" positions.
It also fixes all sub-optimal handlings of those Kill commands.
* Sometimes internal ASSERTIONS were wrong (they expect the query to be active although it could be killed)
* A Cluster query will only trigger cleanup once. This was handled later before but caused the test to endless loop.
* A dropped database will now clear and garbage collect all lingering cursors, without this an AQLFeature lease was kept forever prohibiting the Server to shutdown. (Only if a query is killed, and the DB was dropped before the garbage collection kicked in, so unlikely)
* I killed cursor can now be removed from the Cursor list on demand as long as …

Bug fix 3.8/bts 346

---

tests/js/client/server_permissions/test-foxx-apis-on.js

Fix a Foxx test that called "ensureFoxxInitialized" too early.

fix a test

---

3rdParty/fuerte/src/AsioSockets.h
CHANGELOG

Backport of https://github.com/arangodb/arangodb/pull/13960
Prevent arangod from terminating with "terminate called without an active exception" (SIGABRT) in case an out-of-memory exception occurs during creating an ASIO socket connection.

Prevent program crash in case of OOM during connecting

---

CHANGELOG
arangod/Aql/AqlCallStack.cpp
arangod/Aql/AqlCallStack.h
arangod/Aql/AsyncExecutor.cpp
arangod/Aql/AsyncExecutor.h
arangod/Aql/BlocksWithClients.cpp
arangod/Aql/BlocksWithClients.h
arangod/Aql/DistributeClientBlock.cpp
arangod/Aql/DistributeExecutor.cpp
arangod/Aql/DistributeExecutor.h
arangod/Aql/ExecutionBlock.h
arangod/Aql/ExecutionBlockImpl.cpp
arangod/Aql/ExecutionBlockImpl.h
arangod/Aql/ExecutionEngine.cpp
arangod/Aql/MutexExecutor.cpp
arangod/Aql/MutexExecutor.h
arangod/Aql/Query.cpp
arangod/Aql/RemoteExecutor.cpp
arangod/Aql/RemoteExecutor.h
arangod/Aql/ScatterExecutor.cpp
arangod/Aql/ScatterExecutor.h
arangod/Aql/SingleRowFetcher.cpp
js/common/modules/@arangodb/aql/explainer.js
tests/Aql/WaitingExecutionBlockMock.cpp
tests/Aql/WaitingExecutionBlockMock.h

This PR contains two changes:
1) show peak memory usage in AQL query profiling output
2) slightly improve the efficiency of some internal AQL APIs by copying less data
Re 2): the efficiency gains will be potentially not noticable, but avoiding a few copies here and there should do no harm.

add peak memory usage to AQL query profiling output

---

CHANGELOG
arangod/Cluster/ClusterMethods.cpp

This fixes a problem found with the new testagent. In document batch
operations (which are also used for import jobs) there is a problem in
the error handling if a shard is completely off line (all replicas
cannot be reached for 15 minutes). In that case, the errors for the
individual documents of the batch for that shard are multiplied, for
each document, as many errors are created as the batch size is.
This essentially squares the number of bad responses.
- Do not multiply shard errors.
- CHANGELOG.
- [*] Backports required for: 3.6, 3.7. 3.8
- [*] Jira ticket number: …

Fix shard error multiplication

---

arangod/RestServer/FlushFeature.cpp

The FlushFeature uses the Instance of DatabaseFeature during start().
This instance is only set during start() of DatabaseFeature but the dependency is not defined.
As the startup is consistent after a build it by accident worked, now we force it to be correct.
Hence no changelog as it will not have visible effect.

Fix ordering of Database and FlushFeatures

---

3rdParty/velocypack/include/velocypack/velocypack-common.h

Try to address performance regression from https://github.com/arangodb/backlog/issues/800
Move from switch to mutually excluding constexpr ifs (as switch is not constexpr`ed by compiler and this functions takes more time than should even compared to old version).
https://jenkins.arangodb.biz:3456/view/PR/job/arangodb-matrix-pr/14953/

move from switсh to constexpr ifs

---

Documentation/DocuBlocks/Rest/Administration/get_admin_statistics.md
Documentation/DocuBlocks/Rest/Administration/get_admin_statistics_description.md

Backport of https://github.com/arangodb/arangodb/pull/13997
Docs PR: https://github.com/arangodb/docs/pull/685
Deprecates the `/_admin/statistics` API in favor of `/_admin/metrics/v2`.
The latter API provides a lot more information than the former.
This is a documentation-only change, thus no CHANGELOG entry.

deprecate the /_admin/statistics API in favor of /_admin/metrics/v2

---

Documentation/DocuBlocks/Rest/Bulk/post_api_export.md

Follow-up to #13929 and https://github.com/arangodb/docs/pull/685/files#diff-b6a39937a28a7120bf661455c493fc356859177f566d7503a61098e462695a3bR319-R326

Add deprecation warning to /_api/export (#13929)

---

CHANGELOG
Documentation/DocuBlocks/Rest/Cursors/put_api_cursor_identifier.md
arangod/RestHandler/RestCursorHandler.cpp
js/apps/system/_admin/aardvark/APP/frontend/js/collections/arangoDocuments.js
tests/js/client/load-balancing/load-balancing-cursor-auth-cluster.js
tests/js/client/load-balancing/load-balancing-cursor-noauth-cluster.js
tests/js/client/load-balancing/load-balancing-transactions-noauth-cluster.js
tests/rb/HttpInterface/api-cursor-spec.rb

Jira ticket: https://arangodb.atlassian.net/browse/APM-75
Backport of https://github.com/arangodb/arangodb/pull/14004
Docs PR: arangodb/docs#686
Add HTTP REST API endpoint POST `/_api/cursor/<cursor-id>` as a drop-in replacement for PUT `/_api/cursor/<cursor-id>`. The POST API is functionally equivalent to the existing PUT API. The benefit of using the POST API is that HTTP POST requests will not be considered as idempotent, so proxies may not retry them if they fail. This was the case with the existing PUT API, as HTTP PUT requests can be considered idempotent according to the HTTP specification.
The POST API is now used internally by ArangoDB's own requests in devel, including the web UI and the client tools. Previous versions (i.e. 3.8 and 3.7) will not make use of the new API for …

Added REST API POST `/_api/cursor/<cursor-id>`

---

Documentation/DocuBlocks/Rest/Collections/put_api_collection_load.md
Documentation/DocuBlocks/Rest/Collections/put_api_collection_unload.md

Add deprecation notes to collection load/unload functions in the docs.
Docs PR: https://github.com/arangodb/docs/pull/690
This PR only contains documentation changes.

deprecate collection load/unload functions

---

CHANGELOG
arangod/RestHandler/RestReplicationHandler.cpp
arangod/RestHandler/RestReplicationHandler.h
tests/js/client/authentication/restore.js

Backport of https://github.com/arangodb/arangodb/pull/14021
Fix crashes during arangorestore operations due to usage of wrong pointer value for updating user permissions.

Fix crashes during arangorestore operations

---

CHANGELOG
arangod/RestHandler/RestReplicationHandler.cpp
arangosh/Restore/RestoreFeature.cpp
arangosh/Restore/RestoreFeature.h
arangosh/Utils/ManagedDirectory.cpp
arangosh/Utils/ManagedDirectory.h
arangosh/Utils/ProgressTracker.h
js/client/modules/@arangodb/testsuites/dump.js
js/client/modules/@arangodb/testutils/process-utils.js
lib/Maskings/Maskings.cpp
lib/Maskings/Maskings.h
tests/js/client/shell/shell-dump-integration.js
tests/js/server/dump/dump-maskings.js

Partial backport of https://github.com/arangodb/arangodb/pull/14010
Docs PR: https://github.com/arangodb/docs/pull/688
Improve parallelism capabilities of arangorestore.
arangorestore can now dispatch restoring data chunks of a collection to idle background threads, so that multiple restore requests can be in flight for the same collection concurrently.
This can improve restore speed in situations when there are idle arangorestore threads left (number of threads can be configured via arangorestore's `--threads` option) and the dump file for the collection is large.
Previously the thread that read the data for file a collection would send HTTP requests to the server and block until the response came back. So even when there were idle threads available they could not be used.
With the …

Improve parallelism capabilities of arangorestore.

---

CHANGELOG
arangosh/Export/ExportFeature.cpp
arangosh/Export/ExportFeature.h
js/client/modules/@arangodb/testsuites/export.js

This adds the option `--query-max-runtime` to arangoexport, so that the maximum runtime of AQL queries can be restricted.

Added `--query-max-runtime` option for arangoexport

---

CHANGELOG
arangod/Utils/Cursor.h
arangod/Utils/CursorRepository.cpp
tests/rb/HttpInterface/api-cursor-spec.rb

Backport of https://github.com/arangodb/arangodb/pull/14044
Make the time-to-live (TTL) value of a streaming cursor only count after the first response has been sent to the client.

Improve TTL handling for streaming cursors

---

CHANGELOG
arangod/RestHandler/RestReplicationHandler.cpp

Backport of https://github.com/arangodb/arangodb/pull/14047
Revert the use of UsePadding velocypack options in RestReplicationHandler.cpp, as it obviously leads to an ASan heap buffer overflow in some restore tests.
The UsePadding behavior was introduced in RestReplicationHandler.cpp only one or two days ago and was not released.

remove the use of UsePadding velocypack options

---

CHANGELOG
arangod/Transaction/V8Context.cpp
arangod/Transaction/V8Context.h

Backport of https://github.com/arangodb/arangodb/pull/14049
Fixed issue BTS-373: ASan detected possible heap-buffer-overflow at `arangodb::transaction::V8Context::exitV8Context()`.

fixed issue BTS-373

---

3rdParty/fuerte/src/H2Connection.cpp
3rdParty/fuerte/src/VstConnection.cpp
CHANGELOG

We had an assertion failure in fuerte in 
3rdParty\fuerte\src\H2Connection.cpp:746
The reason is that there may be requests with an expiry time of
Clock::time_point::max() and at destruction time, when all requests
must be aborted, these must be aborted, too. So far, we compared with
< and thus lost those with Clock::time_point::max() as expire time. Now we
use <=.
This is a trivial change and is covered by existing tests.
Otherwise, the PR speaks for itself.

Fix assertion failure in fuerte

---

3rdParty/iresearch/core/index/index_writer.cpp
CHANGELOG
tests/js/common/aql/aql-view-arangosearch-feature.js

Fix case when documents are removed from just-consolidated segment making it empty.
Now the commit is not aborted but empty segment is written (effectively clearing the index, as this is actually expected)
Fixes BTS-279 ES-810
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/15115/

fix internal-issue #798 

---

CHANGELOG
arangod/Network/Methods.cpp
tests/Network/MethodsTest.cpp

Currently, if a server that is shutting down is using sendRequestRetry,
an immediate error "Timeout" is reported. This is wrong and should
better be a 503 TRI_ERROR_SHUTTING_DOWN.
This was found in chaos tests with the new test agent.
- Report proper error on shutdown in sendRequestRetry.
- CHANGELOG.
- [*] Back-/Forwardports required for: 3.7, devel, 3.6
- [*] This change is a trivial rework / code cleanup without any further 
test coverage.
- [*] This change is already covered by existing tests, such as chaos
tests.

Fix return code on shutting down in sendRequestRetry

---

tests/js/common/shell/shell-pregel-basics-example.js
tests/js/common/shell/shell-pregel-components.js
tests/js/common/shell/shell-pregel-random.js
tests/js/common/shell/shell-pregel-start-cluster.js

Fix some potential issues in Pregel tests
Some tests considered a Pregel job done if it is not in state "running" anymore. however, after running comes "storing", and checking job results while still storing is too early!
This PR unifies the behavior so tests wait until a job is not in state "running" **and** not in state "storing".
This is a test bugfix, so it intentionally doesn't have a CHANGELOG entry.

fix some potential issues in Pregel tests

---

CHANGELOG
arangod/Cluster/MaintenanceFeature.cpp
arangod/GeneralServer/HttpCommTask.cpp

This is a PR with very tiny fixes.
It does 2 things:
1. Fix removeDBErrors busy loop error.
2. Respond correctly on wrong HTTP version and too large body.
The first is a bug in the error reporting in case of a create database
has not worked. This error is currently reported in a busy loop to the
agency, if it happens. The fix clears the error after the first report.
The second is a bug in the parsing of HTTP headers and the corresponding
responses. In case the HTTP version is not 1.1 or 1.0, we now report
505 HTTP VERSION NOT SUPPORTED (and do not simply close off the
connection). In case that the content length is larger than 1 GB, we
now respond with a proper 413 REQUEST ENTITY TOO LARGE instead of
simply closing the connection.
This is the first easy step to fix these error responses. …

Fix maintenance amok and HTTP responses

---

CHANGELOG
arangod/Network/ConnectionPool.cpp

This fixes a relatively subtle use-after-free bug in the connection
pool. It only showed up in a specific cluster failure test and only
if the glibc malloc (as opposed to jemalloc) was used. A lock guard
destructor was using already freed memory and destroyed some
glibc/malloc internal thread local data structures.
- Fix a use-after free.
- CHANGELOG.
The fix speaks for itself and does not need any additional tests. It
was manually verified that this fixes the observed problem.
This is a backport of https://github.com/arangodb/arangodb/pull/14110
from 3.8 to 3.6.

Fix move after free bug in connection pool

---

CHANGELOG
arangod/Aql/OptimizerRules.cpp
tests/js/server/aql/aql-graph-traverser.js

Fixed issue #14122: when the optimizer rule "inline-subqueries" is applied, it may rename some variables in the query. The variable renaming was however not carried out for traversal PRUNE conditions, so the PRUNE conditions could still refer to obsolete variables, which would make the query fail with errors such as
Query: AQL: missing variable ... for node ... while planning registers

Fixed issue #14122

---

CHANGELOG
arangod/Cluster/ActionBase.cpp
arangod/Cluster/ActionBase.h
arangod/Cluster/CreateCollection.cpp
arangod/Cluster/CreateCollection.h
arangod/Cluster/DropCollection.cpp
arangod/Cluster/DropCollection.h
arangod/Cluster/Maintenance.cpp
arangod/Cluster/MaintenanceWorker.cpp
arangod/Cluster/ResignShardLeadership.cpp
arangod/Cluster/ResignShardLeadership.h
arangod/Cluster/SynchronizeShard.cpp
arangod/Cluster/SynchronizeShard.h
arangod/Cluster/TakeoverShardLeadership.cpp
arangod/Cluster/TakeoverShardLeadership.h
arangod/Cluster/UpdateCollection.cpp
arangod/Cluster/UpdateCollection.h

Improve exception safety for cluster maintenance threads.
If the `nextState()` method in MaintenanceWorker.cpp threw an exception, the maintenance thread was stopped and not restarted. Now this is properly caught, and the action will be set to `FAILED` state.
In addition, shard unlock in maintenance actions that had to do with shards was potentially unsafe, because it was happening in an action's `setState()` method but could require several memory allocations, with potential to throw exceptions before unlocking is carried out.
Shard unlocking is now ensured by storing the shard name as an instance variable, so there do not need to be lookups and temporary string creations to find out the shard name. In SynchronizeShard.cpp, shard unlocking was also put into a scopeGuard so we will see a …

Improve exception safety for maintenance thread & shard unlocking

---

3rdParty/fuerte/include/fuerte/connection.h
3rdParty/fuerte/src/GeneralConnection.h
3rdParty/fuerte/src/H2Connection.h
CHANGELOG

This fixes two bugs in fuerte with HTTP/2 and VST connections.
- Do not call callbacks more than once. This could happen since in HTTP/2 a request lingers in form of an HTTP/2 stream for some time longer after its callback has been called by a timeout. If the next timeout (for a different request) is hit, the callback could be called a second time. This is now prevented by keeping some more state.
- Fix bug with timeouts in H2 connections in fuerte. This was a simple typo in the tracking if we are reading and/or writing.
- CHANGELOG.
- [*] Backports required for: 3.6, 3.7 and 3.8
- [*] The behavior in this PR was *manually tested*
- [*] This change is already covered by existing tests: Fuerte tests

Fix bugs in fuerte with H2 and VST connections

---

arangod/Pregel/PregelFeature.h

Fixes a missing initialization of `_recoveryManagerPtr` which could lead to random crashes.

Make sure _recoveryManagerPtr is initialized correctly.

---

CHANGELOG
arangod/Cluster/ActionBase.cpp
arangod/Cluster/ClusterFeature.cpp
arangod/Cluster/DropCollection.cpp
arangod/Cluster/DropDatabase.cpp
arangod/Cluster/Maintenance.cpp
arangod/Cluster/MaintenanceFeature.cpp
arangod/Cluster/MaintenanceFeature.h
arangod/Cluster/SynchronizeShard.cpp
arangod/Replication/DatabaseInitialSyncer.cpp
arangod/RestHandler/RestReplicationHandler.cpp
arangod/RocksDBEngine/RocksDBBackgroundThread.cpp
arangod/RocksDBEngine/RocksDBEngine.cpp
arangod/RocksDBEngine/RocksDBMetaCollection.cpp
arangod/RocksDBEngine/RocksDBMetaCollection.h
arangod/RocksDBEngine/RocksDBMetadata.cpp
arangod/RocksDBEngine/RocksDBTypes.h
arangod/RocksDBEngine/RocksDBV8Functions.cpp
arangod/VocBase/Identifiers/RevisionId.cpp
arangod/VocBase/Identifiers/RevisionId.h
arangod/VocBase/LogicalCollection.cpp
arangod/VocBase/Methods/Collections.cpp
js/common/modules/@arangodb/aql/explainer.js
lib/Basics/StaticStrings.cpp
lib/Basics/StaticStrings.h
lib/Basics/hashes.h
lib/Containers/MerkleTree.cpp
lib/Containers/MerkleTree.h
tests/Containers/MerkleTreeTest.cpp
tests/js/server/recovery/check-warnings.js

Improve error reporting for Merkle tree operations, and improve robustness of the trees.
In addition reduce memory usage for unused trees by hibernating them.
This also adds a backoff procedure in case there are repeated synchronization failures for the same shard. If there are too many failures in a row, it will finally drop the follower shard, so it can be completely rebuilt from the leader data.
Additional tests for replication and tree operations will follow separately.
Additional tests will follow in a separate PR.

Shard synchronization improvements

---

arangod/Cluster/ClusterTypes.cpp
arangod/Cluster/ClusterTypes.h
arangod/Cluster/RebootTracker.cpp
arangod/Transaction/Status.cpp
arangod/Transaction/Status.h
lib/Basics/AttributeNameParser.cpp
lib/Basics/AttributeNameParser.h
lib/Basics/Identifier.cpp
lib/Basics/Identifier.h
lib/Basics/Result.cpp
lib/Basics/Result.h
lib/Basics/debugging.h

Many of our `operator<<`s were defined in `::`. This prevented other operators being put in appropriate namespaces, because then the operators in `::` could no longer be found in namespaces containing such `operator<<`s.
This PR cleans that up a little.
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/676

Fix operator<< lookup

---

arangod/RocksDBEngine/RocksDBMetaCollection.cpp
tests/js/server/recovery/revision-trees-compression-format-bottommost.js
tests/js/server/recovery/revision-trees-compression-format-snappy.js
tests/js/server/recovery/revision-trees-compression-format-uncompressed.js

Extend the ranges considered valid for compressed revision tree sizes in tests.
The actuall compressed sizes depend on the the _rev values, and thus the rangeMax value used by the tree. This has a large influence on compressibility.

fix some non-deterministic tests

---

CHANGELOG
arangod/Aql/Collection.cpp
arangod/Aql/Collection.h

Backport of https://github.com/arangodb/arangodb/pull/14133
Fix assertions failed reported in https://arangodb.atlassian.net/browse/BTS-354

fixed issue BTS-354 (#14133)

---

CHANGELOG
arangod/Transaction/Methods.cpp

*Fixes BTS-416, where a shard leader instead of correctly reporting shutdown, claimed that it couldn't dropa shard follower resulting to 500 error towards client*
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/15444/

[3.8] correctly report shutdown as shard leader

---

CHANGELOG
arangod/Aql/Condition.cpp
arangod/Indexes/SortedIndexAttributeMatcher.cpp
arangod/Indexes/SortedIndexAttributeMatcher.h
tests/js/server/aql/aql-index-choice.js

Fixes BTS-417
In some cases an index did not consider both bounds (lower and upper) for a close range scan if both bounds are expressed using the same operator, e.g., `FILTER doc.beginDate >= lb AND ub >= doc.beginDate`.
The newly added tests revealed yet another issue with the condition optimization in case of redundant conditions which result in suboptimal range calculation with an additional filter. But that needs to be fixed in a separate PR.

Fix index range calculation for queries where both bounds are expressed using the same operator.

---

CHANGELOG
arangod/Aql/ExecutionPlan.cpp
arangod/Graph/TraverserOptions.cpp
js/common/bootstrap/errors.js
lib/Basics/error-registry.h
lib/Basics/errors.dat
lib/Basics/voc-errors.h
tests/js/server/aql/aql-graph-weighted-traversal.js

A negative edge weight can crash the server in a weighted traversal.

Throw an exception when a negative edge weight is detected.

---

Documentation/Metrics/arangodb_aql_global_query_memory_limit_reached_total.yaml
Documentation/Metrics/arangodb_aql_local_query_memory_limit_reached_total.yaml
arangod/RestServer/QueryRegistryFeature.cpp
tests/js/client/server_parameters/test-global-memory-limit.js
tests/js/client/server_parameters/test-memory-limit.js

Rename some metrics that were introduced in 3.8 so that they have Prometheus-compatible names.

fix metrics names

---

3rdParty/iresearch/external/unicorn/unicorn/utility.hpp
3rdParty/velocypack/include/velocypack/Slice.h
arangod/Cluster/TraverserEngine.cpp
arangosh/Utils/ProgressTracker.h
lib/Basics/StringHeap.h
tests/IResearch/IResearchTestCompressor.h

I use Arch Linux. Thus my default system compiler is now gcc-11.1. I made some adjustments to make ArangoDB compile on Arch Linux. I explained all changes below. Almost all of them are adding **missing** includes.
- `lib/Basics/StringHeap.h` uses `std::size_t` but does not include `cstddef`.
- `3rdParty/iresearch/external/unicorn/unicorn/utility.hpp` uses `std::shared_ptr` but does not include `memory`.
- `arangosh/Utils/ProgressTracker.h` uses `std::unique_lock` but does not include `mutex`.
- See https://gcc.gnu.org/gcc-11/porting_to.html#header-dep-changes:
>  The following headers are used less widely in libstdc++ and may need to be included explicitly when compiled with GCC 11:
>
>    <limits> (for std::numeric_limits)
>    <memory> (for std::unique_ptr, std::shared_ptr etc.)
> …

Fixed code to be compatible with gcc-11.1

---

3rdParty/V8/CMakeLists.txt
3rdParty/jemalloc/CMakeLists.txt
3rdParty/libunwind/CMakeLists.txt

This reverts a change from #14164, which inadvertently prevented make from finding its job server, e.g.:
```
make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
```
We can later find out the reason and how to make it work for ninja as well, this is just to make builds work in parallel again for those three libraries.

Allow make to find its jobserver again

---

Documentation/DocuBlocks/Rest/AQL/GetApiQueryCurrent.md

Backports required: 3.7, 3.8
https://github.com/arangodb/arangodb/blob/fbb60b75b7dcf182f1f12c1f7003fa875180901f/arangod/Aql/QueryExecutionState.cpp#L33-L46

Docs: List possible execution state strings for GET /_api/query/current

---

utils/makeDashboards.py

This change is necessary for metrics on k8s. For counters, the
averaging period is changed from 1 minute to 3 minutes, since on k8s
scraping is done less frequently.

Small change on creation scripts for metrics

---

CHANGELOG
arangod/Aql/WindowExecutor.cpp
tests/js/server/aql/aql-window-malarkey.js

Backport of https://github.com/arangodb/arangodb/pull/14229
Fixed issue BTS-424: https://arangodb.atlassian.net/browse/BTS-424
The WINDOW node produced invalid output for invalid outputs.

Fixed issue BTS-424: fix invalid input row handling in WINDOW execution.

---

CHANGELOG
arangod/Aql/OptimizerRulesCluster.cpp
tests/js/server/aql/aql-optimizer-optimize-cluster-single-document-operations.js

https://arangodb.atlassian.net/browse/BTS-422
Backport of https://github.com/arangodb/arangodb/pull/14215
* Fixed BTS-422: SingleRemoteModification in AQL behaves different.
This disables the optimizer rule `optimize-cluster-single-document-operations`
for array inputs, e.g.
INSERT [...] INTO collection
REMOVE [...] IN collection
For the cases, the optimization is not pulled off, and the normal insert/
update/replace/remove behavior is executed, which will fail because of an
array being used as input.

fixed issue BTS-422

---

arangod/Aql/Collection.cpp
arangod/Aql/Collection.h

Backport of https://github.com/arangodb/arangodb/pull/14133
Fix assertions failed reported in https://arangodb.atlassian.net/browse/BTS-354
2nd attempt after changes in previous PR https://github.com/arangodb/arangodb/pull/14190 got clobbered.

fix BTS-354 once more

---

arangod/RocksDBEngine/RocksDBV8Functions.cpp

For consistency, rename "storedTree" attribute to just "stored". 
This affects a not-yet-published API, so there is intentionally no changelog entry for it.
The same change for devel is contained in https://github.com/arangodb/arangodb/pull/14220.
We don't need any backports to 3.7 or earlier.

rename "storedTree" attribute to just "stored".

---

js/common/modules/@arangodb/examples/examples.js

Add a tiny dataset to be used for WINDOW aggregation queries in the documentation.
- Add more data points? -> Good enough, easy to understand with just a few data points
- Convert `time` to actual ISO datetime string to enable `WINDOW DATE_TIMESTAMP(t.time) WITH { ... }`? (the current example query does not make sense) -> Converted to ISO compatible string, but still requires cast to numeric timestamp - not sure how performant that is on large datasets, but it's easier to follow

Add observationsSampleDataset for docs

---

tests/js/server/aql/aql-traversal-grinder.js

Grindr tests for traversals.
This PR only adds tests for existing traversal functionality.
In particular, it covers the case fixed by https://github.com/arangodb/enterprise/pull/687

additional grinder tests for traversals

---

CHANGELOG
arangod/Aql/BlocksWithClients.cpp
arangod/Aql/BlocksWithClients.h
arangod/Aql/ExecutionBlockImpl.cpp
arangod/Aql/ExecutionBlockImpl.h
arangod/Aql/OptimizerRules.cpp
arangod/Aql/QueryRegistry.cpp
tests/Aql/ExecutionBlockImplTest.cpp
tests/js/server/aql/aql-optimizer-rule-parallelize-gather-cluster.js

Partly addresses https://arangodb.atlassian.net/browse/BTS-439.
Allow an INSERT operation for a multi-shard collection to execute in
parallel on different DB servers.
Previously INSERTs for a multi-shard collection were executed
sequentially on each DB servers. This could lead to slow execution time,
a large memory usage (DISTRIBUTE has to buffer data for all other DB
servers in memory until the DB servers asks for them) and also query
timeouts.

Parallel multi-shard INSERTs

---

CHANGELOG
arangod/Aql/ParallelUnsortedGatherExecutor.cpp
tests/js/server/aql/aql-skipping-cluster.js

Fix BTS-442: a query with fullCount on a sharded collection hangs indefinitely when LIMIT is less then number of available documents.

Fix BTS-442

---

arangod/Cluster/MaintenanceFeature.cpp
arangod/Cluster/MaintenanceFeature.h
tests/Maintenance/MaintenanceFeatureTest.cpp

Make sure threads are properly joined before exiting test scopes.
This is a potential bugfix for BTS-451: https://arangodb.atlassian.net/browse/BTS-451
This change only affects a test, so no CHANGELOG entry added.

potential bugfix for BTS-451

---

js/client/modules/@arangodb/testutils/block-cache-test-helper.js

For unknown reasons, the block cache usage values returned by the engine stats in this test seem to be unstable, even in single server on Linux. 
There is potentially some other, yet unknown action, that populates parts of the RocksDB block cache.
Being unable to reproduce the issue locally, this is an attempt to cut a part of the test in exchange for test stability.
This is a test-only modification, so it is intentionally missing a CHANGELOG entry.

try to improve unstable fillBlockCache test

---

CHANGELOG
lib/Random/RandomGenerator.cpp

Backport of https://github.com/arangodb/arangodb/pull/14272/
BTS-450: RandomGenerator caught assertion during a value generation within `dump_maskings` testsuite. Ensure correct conversion between 64 and 32bit.

BTS-450: RandomGenerator caught assertion during a value generation

---

CHANGELOG
arangod/Cluster/ServerState.cpp

*Fix BTS-466. Sporadically breaking cluster starts in jenkins on OSX, where the agency is being bootstrapped by a fellow member but the initialisation has not finished yet.*

BTS-446 Cluster machines fail to integrate on OSX jenkins runs

---

tests/Containers/MerkleTreeTest.cpp

Make assertion about generated string size less strict in a test that relies on random values being inserted.
This is a test-only bugfix, so it does not have a CHANGELOG entry.

make test more robust

---

js/client/modules/@arangodb/testutils/process-utils.js
js/client/modules/@arangodb/testutils/result-processing.js

This PR improves the testinfrastructure to fetch probably happening asserts in running server instances into the test summary.
In future test errors caused by server asserts will look like this in `testfailures.txt`:
```
* Test "shell_server_aql"
[FAILED]  tests/js/server/aql/aql-traversal-grinder.js
"test" failed: server unavailable for testing. Connection closed by remote
Suites failed: 2 Tests Failed: 0
[shell_server_aql] :     2021-06-01T15:09:00Z [1226204] C FATAL [a7902] {crash} p^_^R% ArangoDB 3.9.0-devel enterprise [linux], thread 5 [SchedWorker] caught unexpected signal 6 (SIGABRT): assertion failed in /home/willi/src/devel4/enterprise/Enterprise/Cluster/SmartWeightedPathEnumerator.cpp:248 [operator()]: !vertexSlice.isString() - image base address: 0x000056136224c000 …
```

search for the servers assert log messages, and print them, add them to testfailures.txt

---

CHANGELOG
CMakeLists.txt
cmake/InstallArangoDBJSClient.cmake

Forward port of https://github.com/arangodb/arangodb/pull/14261
`eslint` was still mentioned in the package.json and package-lock.json of build packages. However, eslint was not distributed in the package. Removed these entries when installing.
This also fixes security warnings by package scanners.

remove eslint from package.json

---

lib/Random/RandomGenerator.cpp
lib/Random/RandomGenerator.h
tests/Basics/RandomTest.cpp

Add extra tests for random number generator functionality.
This only adds tests and exposes one existing rng function for testing.

add more tests for random generator

---

3rdParty/iresearch/core/analysis/token_stopwords_stream.cpp
tests/js/common/aql/aql-view-arangosearch-feature.js

Add hex parameter to stopwords analyzer to clarify processing of stopword tokens
Related docs PR https://github.com/arangodb/docs/pull/711

add hex parameter to stopwords analyzer

---

CHANGELOG
Documentation/Metrics/arangodb_agency_append_hist.yaml
Documentation/Metrics/arangodb_connection_pool_connections_current.yaml
Documentation/Metrics/arangodb_connection_pool_leases_successful_total.yaml
utils/generateAllMetricsDocumentation.py
utils/makeDashboards.py

This adds a test to the utils/generateAllMetricsDocumentation.py script
to check if the value in the name attribute of a documentation snippet
matches the file name.
Also corrects a few mistakes which went unnoticed.
Also fixes the averaging time for histogram metrics from 60s to 3m (which is necessary for k8s deployments).
This is the backported to 3.8 from devel. No further backports needed.

Metrics names in snippets fix

---

lib/Logger/LoggerFeature.cpp

According to https://github.com/arangodb/docs/pull/474/files#diff-836e267255d7145a3792f742141791ed7d3a393116990126ea0b9811bb2d2e84R277 the source function name is also logged
The startup option is actually `--log.line-number`.

Docs: `--log.line-number` also logs function name

---

js/client/modules/@arangodb/testutils/block-cache-test-helper.js

Test case reduction following up to https://github.com/arangodb/arangodb/pull/14284
For unknown reasons, the block cache usage values returned by the engine stats in this test seem to be unstable, even in single server on Linux.
There is potentially some other, yet unknown action, that populates parts of the RocksDB block cache.
Being unable to reproduce the issue locally, this is an attempt to cut a part of the test in exchange for test stability.
This is a test-only modification, so it is intentionally missing a CHANGELOG entry.

cut yet some more code from the fillBlockCache test

---

3rdParty/rocksdb/6.8/env/fs_posix.cc
CHANGELOG
arangod/RocksDBEngine/RocksDBEngine.cpp
lib/Basics/files.cpp

* Backport bugfix from upstream rocksdb repository for calculating the free disk space for the database directory (rocksdb PR 8370). Before the bugfix, rocksdb could overestimate the amount of free disk space when the arangod process was run as non-privileged users.

Backport rocksdb diskspace bugfix

---

CHANGELOG
arangod/GeneralServer/HttpCommTask.cpp
arangod/GeneralServer/HttpCommTask.h
tests/js/client/shell/shell-request.js

Fix URL request parsing in case data is handed in in small chunks. Previously the URL could be cut off if the chunk size was smaller than the URL size.

Fix URL request parsing.

---

arangod/Aql/LateMaterializedOptimizerRulesCommon.h

See PR title. Some member variables are not properly initialized.
g++-11 can warn about those.

fixes warnings about potentially uninitialized vars with g++11

---

3rdParty/iresearch/core/search/disjunction.hpp
CHANGELOG
tests/js/common/aql/aql-view-arangosearch-noncluster.js

Fix for DEVSUP-753: fixed UB triggered by visit on exhausted disjunction iterator
DEVSUP-753

Bug fix/fix devsup 753

---

lib/Logger/LoggerFeature.cpp

Docs: `--log.line-number` also logs function name (#14326)

---

CHANGELOG
lib/ProgramOptions/ProgramOptions.cpp

Improve usability of hidden options:
`--help` mentions that these exist and how to display them.
This is a usability improvement.

Improve usability of hidden options:

---

CHANGELOG
arangod/Cluster/ClusterTraverser.cpp
arangod/Graph/SingleServerTraverser.cpp
arangod/Graph/Traverser.cpp
arangod/Graph/Traverser.h
arangod/Graph/TraverserCache.cpp
tests/js/server/aql/aql-graph-traverser.js

* Fixed DEVSUP-799: unique vertex getter may point to invalid memory after
being resetted, resulting in undefined behavior for traversals returning
unique vertices from inner FOR loops.

Fix DEVSUP-799

---

arangod/RocksDBEngine/RocksDBTransactionState.cpp
tests/js/server/shell/shell-collection-failures-noncluster.js

Add a failure point and a test for `addOperation` returning an error

added test for addOperation returning an error

---

js/client/modules/@arangodb/testsuites/chaos.js
js/client/modules/@arangodb/testutils/test-utils.js
js/common/modules/@arangodb/replication-common.js
js/common/modules/jsunity.js
tests/js/client/chaos/test-chaos-load-common.inc
tests/js/client/chaos/test-module-chaos-load-cluster-nightly.js
tests/js/client/chaos/test-module-chaos-load-cluster.js

Add a chaos test suite with a cluster-chaos-load test which revealed several issues in the replication system.

Add new chaos test suite.

---

arangod/Aql/Query.cpp
arangod/Aql/QueryContext.cpp
arangod/Aql/QueryContext.h
tests/Mocks/Servers.cpp
tests/main.cpp

devel port of https://github.com/arangodb/arangodb/pull/14447
Enable an assertion in `QueryContext::collections()` that was previously enabled only when not compiling with Google tests enabled.
The assertion is valid and is now globally enabled, except when running unittest from gtest.
This is an internal change (for testing) without any user-visible change, thus there is no CHANGELOG entry for it.

enable assertion in QueryContext::collections()

---

arangod/Graph/Cursors/RefactoredSingleServerEdgeCursor.cpp
arangod/Graph/Cursors/RefactoredSingleServerEdgeCursor.h
arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
js/server/modules/@arangodb/testutils/aql-graph-traversal-generic-tests.js

Use lambda helper method to remove duplicate code usage and unify readAll(getExtra vs !getExtra)
- Also added a test.

unify method used in cursor readAll - GORDO-1210

---

Documentation/DocuBlocks/Rest/Administration/delete_api_shutdown.md
Documentation/DocuBlocks/Rest/Administration/get_api_shutdown.md

This only adds documentation for the soft coordinator shutdown feature
into docublocks.

Soft coordinator shutdown documentation

---

CHANGELOG
arangod/GeneralServer/AcceptorTcp.cpp
arangod/GeneralServer/AcceptorTcp.h

Potentially fixes this issue: https://github.com/arangodb/arangodb/issues/14431
I first fixed this issued in https://github.com/arangodb/arangodb/pull/14029/commits/da1e761c7443c34204ea7e1e5be66d3babb454aa after TSan reported a data race. From the race, I figured that it would be possible to cause a segfault, but unfortunately I was never able to trigger any. Thus there is not additional test to cover this.

Fix potential segfault in tcp/ssl socket handling.

---

CHANGELOG
arangod/Aql/WindowNode.cpp

Fix numeric overflow in AQL WINDOW node cost estimation if the number of preceding rows was set to `unbounded`. This error was detected by UBSan.

Fix numeric overflow in WINDOW cost estimtation

---

CHANGELOG
arangod/Pregel/PregelFeature.cpp
arangod/Scheduler/Scheduler.h

Fixes a potential memleaks with Pregel conductors, as shown by the nightly ASan tests.
This PR also moves the usages of the `_gcHandle` under the mutex because there is a potential race condition when accessing it.

Fix potential memleak in Pregel conductor garbage collection.

---

CHANGELOG
arangod/Agency/AgencyComm.cpp
arangod/Cluster/ClusterFeature.cpp
tests/js/server/shell/shell-cluster-agency.js

* Fix ArangoAgency::version(), which always returned an empty string instead
of the agency's correctly reported version. This also fixes the agency
version in the startup log messages of the cluster.

Fix ArangoAgency::version()

---

CHANGELOG
arangod/Cluster/CreateCollection.cpp
arangod/Cluster/FollowerInfo.cpp
arangod/Cluster/FollowerInfo.h
arangod/Cluster/Maintenance.cpp
arangod/Cluster/SynchronizeShard.cpp
arangod/Cluster/SynchronizeShard.h
arangod/Cluster/TakeoverShardLeadership.cpp
arangod/RestHandler/RestReplicationHandler.cpp
arangod/Transaction/Methods.cpp
arangod/Transaction/Methods.h
lib/Basics/StaticStrings.cpp
lib/Basics/StaticStrings.h
tests/Maintenance/MaintenanceTest.cpp
tests/js/client/shell/shell-following-term-id-cluster.js

Synchronous replication requests (for insert, replace, update, delete
and truncate operations) have been checked on the follower in so far,
that it was checked that they come from the correct leader (the one the
follower believes to be following). However, it can in rare cases happen
that a follower is dropped and a replication request from before the
dropping only hits the follower after it has gotten in sync again.
This is very bad since it can lead to inconsistent data on shard
replicas which are deemed to be "in sync" and thus equal.
This PR attacks this problem: Whenever a leader/follower relationship is
established, the leader invents a random number and sends it to the
follower together with the confirmation that it has aqcuired an
exclusive lock on the shard (one relative late …

Following term id for 3.7

---

CHANGELOG
arangod/RocksDBEngine/RocksDBBackgroundErrorListener.cpp
arangod/RocksDBEngine/RocksDBBackgroundErrorListener.h
arangod/RocksDBEngine/RocksDBEngine.cpp
arangod/RocksDBEngine/RocksDBEngine.h

Backport of https://github.com/arangodb/arangodb/pull/14470
* APM-107: Added metric "rocksdb_read_only" to determine whether RocksDB is currently in read-only mode due to a background error. The metric will have a value of "1" if RocksDB is in read-only mode and "0" if RocksDB is in normal operations mode. If the metric value is "1" it means all writes into RocksDB will fail, so inspecting the logfiles and acting on the actual error situation is required.
PR was tested manually by starting arangod using a space-constrained tmpfs directory, and writing data into it until RocksDB went into read-only mode. While doing that, metrics were retrieved periodically so check if the "rocksdb_read_only" metric flipped from "0" to "1".
Also verified manually that it goes back to "0" if RocksDB is able …

Added (gauge) metric "rocksdb_read_only"

---

3rdParty/rocksdb/6.8/env/env_encryption.cc
CHANGELOG
tests/js/server/recovery/empty-journal.js

Backport of https://github.com/arangodb/arangodb/pull/14477
* Fix startup issues with encryption-at-rest enabled when there were empty
(0 byte) RocksDB WAL files present. Such empty files caused RocksDB to
abort the startup, reporting corruption. However, empty WAL files are
possible in case of server crashes etc. Now, if a WAL file is completely
empty, there will be no attempt to read the encryption meta data from it,
so the startup succeeds.
A PR for facebook/rocksdb will be opened seperately: https://github.com/facebook/rocksdb/pull/8499

Fix handling of empty WAL files with encryption at rest

---

tests/js/client/shell/shell-aql-query-setup-timeout.js

Improve shell-aql-query-setup-timeout test
- added a missing `fail()`
- allow 2 different errors codes (both are possible)
This PR only makes a change to the test, so there is intentionally no CHANGELOG entry for it.

improve shell-aql-query-setup-timeout test

---

CHANGELOG
arangod/Replication/DatabaseInitialSyncer.cpp
arangod/RocksDBEngine/RocksDBMetaCollection.cpp
arangod/RocksDBEngine/RocksDBMetadata.cpp
arangod/RocksDBEngine/RocksDBReplicationContext.cpp
arangod/RocksDBEngine/RocksDBSettingsManager.cpp
arangod/RocksDBEngine/RocksDBSettingsManager.h
arangod/RocksDBEngine/RocksDBTransactionCollection.cpp
arangod/RocksDBEngine/RocksDBTransactionState.cpp
tests/js/client/chaos/test-chaos-load-common.inc

Forward port of https://github.com/arangodb/arangodb/pull/14498
Slightly extend chaos tests and add some fixes that occurred during chaos, in particular:
* always remove `blocker` object for revision trees in case of replication failure
* fix `hasBlockerUpTo` function
* fix invalid assertion
In addition, the devel version of this PR adds an optimization for collection serialization, which is done by reusing a scratch string to save allocations.

Fix invalid assertion and always remove blocker object on replication failure

---

arangod/Pregel/Conductor.h
arangod/Pregel/PregelFeature.cpp

BTS-519: https://arangodb.atlassian.net/browse/BTS-519
This change avoids holding the _mutex of PregelFeature while calling into each Conductor for velocypackification. The velocypackification of a Conductor requires holding the Conductor's _callbackMutex as well, and we prefer holding only one mutex at a time.
There don't need to be backports for this, as the fix for code changes that are only present in devel.

BTS-519: avoid holding 2 mutexes at the same time

---

lib/V8/v8-utils.cpp

fix a g++-9 compile warning for a potentially uninitialized var

---

CHANGELOG
arangod/Aql/Ast.h
arangod/Aql/grammar.cpp
arangod/Aql/grammar.y
arangod/IResearch/IResearchFilterFactory.cpp
tests/IResearch/IResearchFilterFunction-test.cpp
tests/js/server/aql/aql-options-verification.js
tests/js/server/aql/aql-parse.js

BTS-408: https://arangodb.atlassian.net/browse/BTS-408
Treat positive or negative signed numbers as constants immediately during AQL query parsing.
Previously, a value of `-1` was parsed initially as `unary minus(value(1))`, which was not treated in the same way as a constant value `value(-1)`.
The value was later optimized to just `value(-1)`, but this only happened during constant-folding after parsing. Any operations that referred to the unfolded values during parsing thus did not treat such values as constants.

Fixed BTS-408

---

CHANGELOG
arangod/V8Server/V8DealerFeature.cpp
lib/Basics/FileUtils.cpp
lib/Basics/files.cpp
lib/Basics/files.h
lib/Basics/operating-system.h
tests/js/client/server_parameters/test-copy-installation.js

Partial fix of BTS-516 (https://arangodb.atlassian.net/browse/BTS-516)
Improve startup file copying of JavaScript files
* Make `--javascript.copy-installation` also copy the `node_modules` sub directory. This is required so we have a full copy of the JavaScript dependencies and not one that excludes some infrequently changed modules. In addition, file copying now intentionally excludes .map files as they are not needed.
* Revive unused code for file copying on Linux using `splice()`. This can have performance advantages compared to other copying implementations. 
* The file copying routine in `--javascript.copy-installation` was also optimized to significantly do less stat calls, and the file/directory filtering code was also sped up.

Improve startup file copying of JavaScript files

---

arangod/Aql/ExecutionBlockImpl.cpp
utils/checkLogIds.py

Fix a duplicate log id, and adapt the corresponding script to check these kind of log macros.
Necessary so https://github.com/arangodb/oskar/pull/331 can be merged.
- Oskar PR: https://github.com/arangodb/arangodb/pull/14523

Fix duplicate log id in ExecutionBlockImpl

---

CHANGELOG
arangod/Aql/QueryOptions.cpp

On OSX the default stack size for worker threads (non-main thread) is 512kb which is rather low, so we have to use a lower default for the max. number of nodes per callstack,

Use lower defaultMaxNodesPerCallstack for Mac.

---

UnitTests/OskarTestSuitesBlockList

Disable replication2_client test in oskar.

[3.6] Disable replication2_client test in oskar.

---

arangod/Aql/ExecutionBlockImpl.cpp
arangod/Aql/ExecutionBlockImpl.h
tests/Aql/ExecutionBlockImplTest.cpp

Remember exception in ExecutionBlock and return it on next invocation.
normally any exception returned by an ExecutionBlock is directly handled
by the block's caller.
However, if the same block is asked semi-concurrently (only protected by
the RestAqlHandler's lease), then there can still be other requests in
flight that wait to enter the block. if an exception escapes the block,
it may be left in an invalid state, so we have to prevent other threads
from entering it afterwards and continue with that invalid state.
This is fixed in devel via https://github.com/arangodb/arangodb/pull/14267

remember exception in ExecutionBlock

---

arangod/Aql/ExecutionBlockImpl.cpp
utils/checkLogIds.py

Backport of https://github.com/arangodb/arangodb/pull/14522

[3.8] Fix duplicate log id in ExecutionBlockImpl

---

CHANGELOG
arangod/RocksDBEngine/Methods/RocksDBTrxBaseMethods.cpp
arangod/RocksDBEngine/RocksDBEngine.cpp
arangod/RocksDBEngine/RocksDBSyncThread.cpp

Enable RocksDB SyncWAL() calls on Windows as well.
Previously they were disabled for Windows but enabled for all other platforms. For Windows, there was a workaround. The reason for not calling SyncWAL() on Windows previously was that RocksDB reported the operation as unsupported.
Tested manually on Windows that it now works.

experiment to check if SyncWAL works on Windows

---

arangod/Graph/Enumerators/TwoSidedEnumerator.h

Devel port of https://github.com/arangodb/arangodb/pull/14553
Attempt to pacify specific clang compiler version. This is just a workaround and may not fix the problem.

attempt to pacify clang-1100

---

tests/js/common/shell/test-kill-queries.js

Disable a test that only works with failure points enabled.

disable a test that only works with failure points enabled

---

CHANGELOG

Backport of https://github.com/arangodb/enterprise/pull/710
Changelog entry for https://github.com/arangodb/enterprise/pull/715
Some LDAPs (e.g. on Windows) do not support setting referrals and restart options. 
Ignore errors in this case and do not try again to set these options.

CHANGELOG entry

---

arangod/IResearch/IResearchFilterFactory.cpp

By compiling with clang 11, found through a warning that a function overload declaration of appendExpression was not being used.
```
/arangodb/arangodb_clang/arangod/IResearch/IResearchFilterFactory.cpp:515:19: warning: unused function 'appendExpression' [-Wunused-function]
FORCE_INLINE void appendExpression(irs::boolean_filter& filter,
```

Removed unused function declaration

---

CHANGELOG

Backport of https://github.com/arangodb/enterprise/pull/689
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/718
BTS-453: "echo -n" does not work reliably. It strongly depends on the log-in shell.

do not use -n on echo, this might not be supported and is not necessary (3.6)

---

CHANGELOG
arangod/Cluster/HeartbeatThread.cpp

…te of cluster info
*Allow timely update of database server lists of isolated database servers.* **Fixes BTS-505**
Link to Jenkins PR run: https://jenkins.arangodb.biz/job/arangodb-matrix-pr/16437/

[3.8] timely update of database servers in cluster cache

---

UnitTests/OskarTestSuitesBlockList
js/client/modules/@arangodb/testsuites/ldap.js

We will not backport the dual ldap tests to 3.6 because it is almost EOL.

Ignore dual LDAP tests in 3.6

---

CHANGELOG
arangod/RestServer/ServerFeature.cpp

Bugfix for https://arangodb.atlassian.net/browse/BTS-536
Now stating `--server.rest-server false` does not require the additional `--console` argument for upgrading a server.
Starting with `--server.rest-server false --database.auto-upgrade true` now works and does not require the extra `--console` argument. Previously the startup was just aborted with an error message.
I couldn't find a good way to test this with the `server_parameters` test suite. This test suite assumes a running server after starting up with arbitrary startup options. But here we won't have a running server after startup. So I tested the changes manually for single server and coordinator.

fix BTS-536 "Upgrading without rest-server is aborted by error".

---

CHANGELOG
CMakeLists.txt

* Change optimization level for debug builds back to `-O0` (from `-Og`)
because `-Og` seems to cause debuggability issues in some environments.

Revert change from `-O0` to `-Og`

---

CHANGELOG
arangod/Agency/State.cpp

*Append physical compaction of log collection to every Raft log compaction (BTS-542).*
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/16548/

bts 542: huge memory use agent

---

3rdParty/immer/v0.6.2/immer/detail/combine_standard_layout.hpp

Fix a compilation issue with `immer` that affects all gcc x.1 versions.

Fixing immer gcc x.1 compilation issues.

---

CHANGELOG
arangod/RocksDBEngine/RocksDBColumnFamilyManager.h
arangod/RocksDBEngine/RocksDBEngine.cpp

If the column family `ReplicatedLogs` is missing, we silently create it.

Bug fix/replicated logs missing column family

---

arangod/Replication2/ReplicatedLog/LogLeader.cpp

Fix a duplicate log id. Not caught by oskar because a necessary PR isn't merged yet. No CHANGELOG required, it was introduced in devel only.
Introduced in: https://github.com/arangodb/arangodb/pull/14486
Oskar PR that adds the necessary check: https://github.com/arangodb/oskar/pull/327
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/16566/
Used with this oskar branch: https://github.com/arangodb/oskar/pull/327

Fix duplicate log id

---

CHANGELOG
arangod/Pregel/Conductor.cpp
arangod/Pregel/GraphStore.cpp
arangod/Pregel/GraphStore.h
arangod/Pregel/Iterators.h
arangod/Pregel/Worker.cpp

Improve log messages for Pregel by passing the execution number around in most log messages.
Also log a clear INFO message at the start of each run with the relevant settings.
For data storage, also introduce a logging for the progress (remaining vertices to store).

improve Pregel log messages by giving them more context

---

CHANGELOG

For the users perspective, this Bugfix changes an invalid document inside a disjointEdgeCollection (having different from and to shard keys, which is disallowed) to return a BAD_PARAMETER instead of a DATASOURCE_NOT_FOUND error when asked for the responsible shard.
In Maintainer-Mode this avoids an assertion, and now exists in an earlier state.
Changes in EE only.
https://jenkins.arangodb.biz:3456/job/arangodb-matrix-pr/16630/
Please note …

Bug-Fix: getResponsibleShard on Disjoint-Edge-Collections

---

js/apps/system/_admin/aardvark/APP/frontend/js/views/footerView.js

Use slightly more sensible internal timeout values (e.g. an adaptive timeout) for determining the "last significant" user action. Inspired by @Simran-B.
This slightly improves a new feature in 3.9, so intentionally no CHANGELOG for it (there is one for the original feature, APM-79).

use more sensible values for timeouts/renewals

---

CMakeLists.txt

Add `-fstandalone-debug` for our Clang Debug builds, so we get debug symbols for the STL etc.

Add -fstandalone-debug for Clang Debug builds

---

CHANGELOG
arangod/Aql/Ast.cpp
tests/js/server/aql/aql-queries-simple.js

Backport of https://github.com/arangodb/arangodb/pull/14603
Bugfix for issue #14592

fixed issue #14592: IS_NULL(@x) isn't recognized as a constant expression

---

lib/Basics/Guarded.h
tests/Basics/GuardedTest.cpp
tests/Mocks/Death_Test.h

Added an `unlock` method to `MutexGuard`, fixed the `tryLockedGuard` implementation, and added tests for both.

Added MutexGuard::unlock(), fixed tryLockedGuard, added tests

---

arangod/Aql/grammar.cpp
arangod/Aql/grammar.y

Fix wording of a parse error that is raised when specifying more than one result variable for a collection- or view-based FOR loop in an AQL query.
This only changes wording in an error message, so intentionally no CHANGELOG entry made.

fix a typo in a parse error message

---

lib/Basics/debugging.cpp

Suppress cppcheck errors for code that intentionally causes errors/crashes (during debugging in maintainer mode).

suppress intentional failures for cppcheck tests

---

3rdParty/fuerte/FuerteH1TCP.tla
3rdParty/fuerte/src/H1Connection.cpp
CHANGELOG

Some newer Macs with a newer clang compiler have run into an assertion
in fuerte. As it turns out, the TLA+ model was predicting this. The
actual code simply has the assertion in the wrong place. This PR
should fix this.
- Move assertion to the right place where the model has it.
- CHANGELOG.
(Please describe the changes in this PR for reviewers - mandatory)
[*] Bugfix (requires CHANGELOG entry)
Backports:
[*] Backports required for: 3.7 and 3.8, this is the 3.8 backport
Related Information
(Please reference tickets / specification / other PRs etc)
[*] GitHub issue / Jira ticket number: https://arangodb.atlassian.net/browse/BTS-552
Testing & Verification
(Please pick either of the following options)
[*] This change was suggested by our TLA+ model.
[*] This change is …

Fix wrong assertion in fuerte

---

CHANGELOG
arangod/Cluster/ClusterFeature.cpp
arangod/Cluster/ClusterFeature.h

Backport of https://github.com/arangodb/arangodb/pull/14678
Reintroduce `--cluster.index-create-timeout` startup option, because we want the timeout to be configurable for arangosync testing. The option was obsoleted and the timeout was set to a hard-coded value in a recent PR. We now make it configurable again so we can set it to very small timeouts for testing.

reintroduce --cluster.index-create-timeout for testing

---

CHANGELOG
arangod/Cluster/ClusterInfo.cpp
arangod/Cluster/ClusterInfo.h

Fix a potential multi-threading issue in index creation on coordinators, when an agency callback was triggered at the same time the method `ensureIndexCoordinatorInner` was left.
Found this randomly by checking the results of another Jenkins job:
https://jenkins.arangodb.biz/job/arangodb-matrix-pr-linux/17920/EDITION=community,STORAGE_ENGINE=mmfiles,TEST_SUITE=cluster,limit=linux&&(test%7C%7Cbuild)%7C%7Cgce/artifact/testfailures.txt

fix potential issue during cluster index creation

---

CHANGELOG
Documentation/Metrics/arangodb_http2_connections_total.yaml
Documentation/Metrics/arangodb_request_body_size_http1.yaml
Documentation/Metrics/arangodb_request_body_size_http2.yaml
Documentation/Metrics/arangodb_request_body_size_vst.yaml
Documentation/Metrics/arangodb_vst_connections_total.yaml
arangod/GeneralServer/GeneralCommTask.h
arangod/GeneralServer/GeneralServerFeature.cpp
arangod/GeneralServer/GeneralServerFeature.h
arangod/GeneralServer/H2CommTask.cpp
arangod/GeneralServer/HttpCommTask.cpp
arangod/GeneralServer/VstCommTask.cpp
js/client/modules/@arangodb/testutils/process-utils.js
js/server/modules/@arangodb/test-helper.js
tests/js/client/communication/test-communication.js
tests/js/client/server_parameters/test-export-document-metrics-off-noncluster.js
tests/js/client/server_parameters/test-export-document-metrics-on-noncluster.js
tests/js/client/shell/shell-check-metrics-move-noncluster.js
tests/js/client/shell/shell-process-metrics-cluster.js

Add protocol specific metrics.
This adds histograms about the body sizes of requests, distinguishing
HTTP/2, VST and HTTP/1.1 requests.
Also: Adds metrics about total number of accepted HTTP/2 and VST
connections.
Also: Switches metrics tests to /_admin/metrics/v2 in more tests.
(Please describe the changes in this PR for reviewers - mandatory)
[*] New feature (requires CHANGELOG entry, feature documentation and release notes)
Backports:
[*] This is the backport for 3.8
Testing & Verification
(Please pick either of the following options)
[*] The behavior in this PR was manually tested
[*] There are new JS tests to test the metrics.
Documentation
All new features should be accompanied by corresponding documentation.
Bugs and features should furthermore be documented in the …

Protocol specific metrics

---

CHANGELOG
tests/IResearch/IResearchDocument-test.cpp

Add tests for concurrent access to the typed analyzer inside FieldIterator (fix itselfa was introduced during updating iresearch from upstream)

add test for concurrent access to the typed analyzer 

---

CHANGELOG
arangod/Aql/OptimizerRules.cpp
tests/js/server/aql/aql-optimizer-rule-late-document-materialization-arangosearch.inc
tests/js/server/aql/aql-optimizer-rule-late-document-materialization.js
tests/js/server/aql/aql-queries-optimizer-limit-cluster.js

PR modifies distributeSortToClusterRule optimizer rule. While moving SORT node to the DBServer  insertion point is not right after REMOTE node but rule tries to skip as much CALCULATION nodes as possible (e.g. if calculation results are not used in sort). This is similar to what is done by moveCalculationsDownRule.
That will make it possible to use late materialization. Also SORT could be constrained so less calculations will be executed.

Bug fix/search 238 late materialization with constrained heap

---

CHANGELOG
arangod/IResearch/IResearchAqlAnalyzer.cpp

This PR aimed to eliminate some memory leaks after changes in https://github.com/arangodb/arangodb/pull/14585

Fix for memory leaks

---

tests/IResearch/CMakeLists.txt
tests/IResearch/IResearchAnalyzerFeature-test.cpp
tests/IResearch/IResearchTestCommon.cpp
tests/IResearch/IResearchTestCommon.h
tests/IResearch/IResearchView-test.cpp

Currently, the following warning happens during initialization of arangodbtests:
```
WARN: [...]/arangodb/3rdParty/iresearch/core/utils/attributes.cpp:88 type name collision detected while registering attribute, ignoring: type 'TestAttribute' from [...]/arangodb/tests/IResearch/IResearchView-test.cpp:153, previously from [...]/arangodb/tests/IResearch/IResearchAnalyzerFeature-test.cpp:124
WARN: [...]/arangodb/3rdParty/iresearch/core/analysis/analyzers.cpp:262 type name collision detected while registering analyzer, ignoring: type 'TestAnalyzer' from [...]/arangodb/tests/IResearch/IResearchView-test.cpp:229, previously from [...]/arangodb/tests/IResearch/IResearchAnalyzerFeature-test.cpp:258
```
This PR moves the duplicate analyzer and attribute into a separate file.

Deduplicate TestAnalyzer and TestAttribute

---

3rdParty/README_maintainers.md
3rdParty/snappy/snappy-1.1.9/CMakeLists.txt
CHANGELOG
arangod/Aql/Query.cpp
lib/CMakeLists.txt
lib/Containers/MerkleTree.cpp
lib/Containers/MerkleTreeHelpers.cpp
lib/Containers/MerkleTreeHelpers.h

This restores the compilation of Snappy to how it was done before commit 573f7ebfdd0f5856970b2ea93555175d5ee9743b. That commit disabled the hack in Snappy that turns of RTTI in its CMakeLists.txt.
The reason for enabling RTTI for Snappy compilation in that previous commit was that we were deriving from two Snappy source files, which are supposed to be used as interfaces. However, g++ cannot link files which have base classes compiled without RTTI and derived classes that use RTTI. That's why RTTI was enabled for the Snappy files in that commit.
That required changes to the original Snappy CMakeLists.txt, and may have had an adverse impact on performance (still to be proven by our performance tests). Now, instead of turning RTTI on for Snappy, we turn it back off and in addition we turn …

disable RTTI for snappy compilation

---

CHANGELOG
arangod/Network/NetworkFeature.cpp

* Fix cluster-internal network protocol to HTTP/1 for now. Any other protocol
selected via the startup option `--network.protocol` will automatically be
switched to HTTP/1. The startup option `--network.protocol` is now deprecated
and hidden by default. It will be removed in a future version of arangod.
The rationale for this change is to move towards a single protocol for
cluster-internal communication instead of 3 different ones.
Note: we may move to a different protocol in the future, but this will then
be an internal-only change.
Docs PR: https://github.com/arangodb/docs/pull/761

Fix cluster-internal network protocol to HTTP/1

---

CHANGELOG
arangod/RocksDBEngine/RocksDBCollection.cpp

Truncate must not trigger intermediate commits while in a streaming transaction, because that would be against the assumption that streaming transactions never do intermediate commits.

Fix: truncate must not trigger intermediate commits in streaming trx.

---

CHANGELOG
arangod/RocksDBEngine/RocksDBEngine.cpp

Allow startup of arangod with an existing database directory that was missing the ZkdIndex column family.

Allow startup of arangod with an existing database

---

arangosh/Benchmark/testcases/RandomShapesTest.h
arangosh/Benchmark/testcases/ShapesAppendTest.h
arangosh/Benchmark/testcases/ShapesTest.h
arangosh/Benchmark/testcases/StreamCursorTest.h
arangosh/Benchmark/testcases/TransactionMultiCollectionTest.h
arangosh/Benchmark/testcases/TransactionMultiTest.h

Deprecate several other arangobench test cases which are pretty outdated and serve no apparent purpose from the end user perspective.
CHANGELOG entry is missing intentionally, as this is a very minor change.

deprecate several extra arangobench testcases

---

arangod/RocksDBEngine/RocksDBComparator.cpp

This is a micro-optimization for the code in RocksDBComparator. It may or may not have an impact on performance. The regular performance tests will show this.

micro-optimize RocksDBComparator

---

CHANGELOG
arangod/RestHandler/RestImportHandler.cpp
tests/rb/HttpInterface/api-import-spec.rb

devel port of https://github.com/arangodb/arangodb/pull/14772
* Fixed issue #14720: Bulk import ignores onDuplicate in 3.8.0.
The "onDuplicate" attribute was ignored by the `/_api/import` REST API when
not specifying the "type" URL parameter.

Fixed issue #14720

---

arangod/Aql/DistributeExecutor.cpp
arangod/Aql/DistributeExecutor.h

Fix UB in DistributeExecutor.
The `extractInput` method created an AqlValue on the stack, and returned a VPackSlice that may have pointed into it. This slice may have random contents after leaving the method, when the stack was cleaned up and the AqlValue overwritten with other data.
This only affects devel, but no previous versions.

fix UB in DistributeExecutor

---

tests/js/client/chaos/test-chaos-load-common.inc

Reduce nr of combinations and runtime of nightly chaos load tests.

---

js/client/modules/@arangodb/testutils/process-utils.js

Improve tests by outputting base directory belonging to ports in overview
```
[agent] up with pid 1771231 on port 23287 - /tmp/arangosh_wq3Hhk/shell_client/agency/data0
[agent] up with pid 1771232 on port 4699 - /tmp/arangosh_wq3Hhk/shell_client/agency/data1
[agent] up with pid 1771233 on port 20088 - /tmp/arangosh_wq3Hhk/shell_client/agency/data2
[dbserver] up with pid 1771436 on port 6045 - /tmp/arangosh_wq3Hhk/shell_client/dbserver0/data
[dbserver] up with pid 1771437 on port 20867 - /tmp/arangosh_wq3Hhk/shell_client/dbserver1/data
[dbserver] up with pid 1771438 on port 3926 - /tmp/arangosh_wq3Hhk/shell_client/dbserver2/data
[coordinator] up with pid 1771440 on port 8583 - /tmp/arangosh_wq3Hhk/shell_client/coordinator0/data
[coordinator] up with pid 1771442 on port 16944 - …
```

output database directory of instance for better reference

---

CONTRIBUTING.md

The [link](https://help.github.com/send-pull-requests/) is not active anymore, it's better ti use this [one](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork) and it's even more suitable for this particular case.

docs: fix github docs link

---

CHANGELOG
arangod/Aql/AttributeNamePath.cpp
tests/js/server/aql/aql-optimizer-rule-reduce-extraction-to-projection.js

https://arangodb.atlassian.net/browse/BTS-562
* Fixed BTS-562: reduce-extraction-to-projection optimization returns null for
one attribute if nested attributes are named the same.

Fixed BTS-562

---

arangod/Aql/SimpleModifier.cpp

This is an interim solution so everything works safely when we branch off 3.9. the proper solution is to keep the modification operations truly asynchronously, but this requires some lifecycle fix for AQL queries first. The latter will be addressed when there is time next.

make AQL modification operations blocking again

---

CHANGELOG
arangod/Aql/InputAqlItemRow.cpp
tests/js/client/shell/shell-query-dbserver-cluster.js

Prevent stealing of values from AQL const registers. These values must stay constant until the end of the query.
This fixes an issue for queries that produce constant results (known at query compile time) when the queries are executed directly on a DB server in a cluster (which is not supported, but may happen for troubleshooting).

prevent stealing of values from Aql const registers

---

arangod/RestHandler/RestAdminClusterHandler.cpp

This is a rather trivial bug fix which addreses BTS-584.
It fixes a regression on /_admin/cluster/health if an agent is off line,
since the health endpoint retried for too long to reach the agent before
giving up.
This is a trivial fix which is covered by QA tests.

Fix /_admin/cluster/health if one agent gone

---

CHANGELOG
arangod/RocksDBEngine/RocksDBVPackIndex.cpp
tests/js/server/shell/shell-array-index-noncluster.js

This fixes BTS-548, see details there. Longer story short: if there is an array index and there is a document update or replace, then we had a shortcut which bypasses the array index update if none of the indexed attributes has changed. In the array
case the change of an array to an empty array was not recognized and thus the index was not updated.
- Fix attributesEqual for update/replace array index changes.
- CHANGELOG.
(Please describe the changes in this PR for reviewers - mandatory)
[*] Bugfix (requires CHANGELOG entry)
[*] CHANGELOG entry made
Backports:
No backports required
[*] Backports required for: 3.7, 3.8
Related Information
(Please reference tickets / specification / other PRs etc)
[*] GitHub issue / Jira ticket number: BTS-548
Testing & Verification
(Please …

Fix BTS-548 array index wrong optimization

---

CHANGELOG
arangod/Replication/GlobalInitialSyncer.cpp
arangod/RestServer/DatabaseFeature.cpp
arangod/VocBase/vocbase.cpp
arangod/VocBase/vocbase.h

Enterprise companion PR: https://github.com/arangodb/enterprise/pull/760
* Avoid the acquisition of a recursive read lock on server shutdown, which
could in theory lead to shutdown hangs at least if a concurrent thread is
trying to modify the list of collections (very unlikely and never observed
until now).

Avoid acquisition of recursive read lock on server shutdown

---

arangod/Utils/OperationOptions.cpp

Add proper initialization to `OperationOptions` flag `documentCallFromAql`.
This was missing before. No CHANGELOG entry added, because the flag was only recently backported to 3.8 and was not yet released.
Note: this does not need any backport to 3.7 because the option does not exist there, and forward port to devel because in devel the variable is properly initialized.

add missing initialization to OperationOptions flag

---

js/server/modules/@arangodb/test-helper.js

This is just a stabilization of an enterprise test.
In this part of the PR there is a generic helper method that is used in the test, and could be used by others potentially.
Relevant change is here:
https://github.com/arangodb/enterprise/pull/762
As this is only test code, this PR has on purpose no Changelog entry, User-space remains unmodified.

Stabilize Hybrid Smart Graph Test [EE only]

---

CHANGELOG
arangosh/Shell/ClientFeature.cpp
arangosh/Shell/ClientFeature.h
lib/ProgramOptions/ProgramOptions.h

Hide help text fragment about VST connection strings in client tools that do not support VST.

Hide help text fragment about VST connection strings

---

CHANGELOG
arangod/Cluster/ClusterMethods.cpp
arangod/Cluster/ClusterMethods.h
arangod/Cluster/ClusterTrxMethods.cpp
arangod/Cluster/ClusterTrxMethods.h
arangod/ClusterEngine/ClusterTransactionState.cpp
arangod/Transaction/Methods.cpp
arangod/Transaction/Methods.h
arangod/Transaction/MethodsApi.h

Backport of #14810.
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/764

[3.8] Make all synchronous transaction methods set skipScheduler for network requests

---

arangod/Cache/Table.cpp

Backport of https://github.com/arangodb/arangodb/pull/14849
Properly throw an exception in case an invalid state is encounteredin TableCache::clear(). The previous implementation just used `throw;`, which is not valid here.
This is a trivial code improvement for an issue that we have never seen happening anywhere.

properly throw an exception in case an invalid state is encountered

---

lib/Basics/Mutex.h

Backport of https://github.com/arangodb/arangodb/pull/14851
Improve portability of `__has_include` macro, as advertised in gcc docs:
https://gcc.gnu.org/onlinedocs/cpp/_005f_005fhas_005finclude.html

improve usage of `__has_include`

---

arangod/Replication2/Streams/StreamInformationBlock.tpp

Rename variables to work around false positive in CppCheck.

[BTS-596] Fixing CppCheck warnings.

---

arangod/Replication2/ReplicatedLog/LogStatus.cpp

LCI was not forwarded correctly because deserializer missing field. [CINFRA-113](https://arangodb.atlassian.net/browse/CINFRA-113)

[CINFRA-113] LCI not displayed properly

---

CHANGELOG
arangod/RocksDBEngine/RocksDBEngine.cpp
arangod/RocksDBEngine/RocksDBThrottle.cpp
arangod/RocksDBEngine/RocksDBThrottle.h

* Fix race in RocksDB throttle listener, when it was getting started lazily during server shutdown.

fix race in RocksDB throttle startup

---

CHANGELOG
arangod/Cache/Table.cpp
arangod/RocksDBEngine/Listeners/RocksDBThrottle.cpp
arangod/RocksDBEngine/Listeners/RocksDBThrottle.h
arangod/RocksDBEngine/RocksDBEngine.cpp

* Fix race in RocksDB throttle listener, when it was getting started lazily during server shutdown.

Fix race in RocksDBThrottle

---

arangod/Aql/ConstFetcher.cpp
arangod/Aql/ExecutionBlock.cpp
arangod/Aql/ExecutionBlockImpl.cpp
arangod/Aql/ExecutionBlockImpl.h
arangod/Aql/RestAqlHandler.cpp
arangod/Aql/UnsortedGatherExecutor.cpp
tests/js/server/aql/aql-gather-block-cluster.js

There were certain situations in which an unsorted gather could miss some documents, because it accidentally skipped some dependencies.
In detail, this happened when the input blocks began with a non-relevant shadow row. In that case, the UnsortedGatherExecutor was called repeatedly until all inputs had blocks, and stayed on the named non-relevant shadow row. Then, the ExecutionBlockImpl would forward the shadow rows, but not reset the UnsortedGatherExecutor. Leaving it in a state where it already marked all but the last dependency as finished. Therefore missing possible rows in those dependencies.
This PR fixes this by just adding a single line that resets the executor, exactly when all dependencies have fetched some input and the ExecutionBlockImpl can proceed by forwarding the …

Fix missing rows in unsorted gather

---

arangod/Replication2/ReplicatedLog/InMemoryLog.cpp
arangod/Replication2/ReplicatedLog/InMemoryLog.h
arangod/Replication2/ReplicatedLog/LogCommon.cpp
arangod/Replication2/ReplicatedLog/LogCommon.h
arangod/Replication2/ReplicatedLog/LogLeader.cpp
arangod/Replication2/ReplicatedLog/LogLeader.h
arangod/Replication2/ReplicatedLog/ReplicatedLogIterator.h
tests/CMakeLists.txt
tests/Replication2/Mocks/FakeFollower.h
tests/Replication2/ReplicatedLog/LeaderAppendEntriesTest.cpp
tests/Replication2/ReplicatedLog/WaitForSyncTest.cpp

This PR adds support for the waitForSync flag that is specified on a per entry basis. [Ticket](https://arangodb.atlassian.net/browse/CINFRA-20).

[CINFRA-20] Added support for waitForSync per entry.

---

arangod/Replication2/ReplicatedLog/PersistedLog.h
arangod/RestHandler/RestLogHandler.h
arangod/RocksDBEngine/RocksDBPersistedLog.h
arangod/RocksDBEngine/RocksDBZkdIndex.h
arangosh/Restore/RestoreFeature.cpp
lib/Basics/EncodingUtils.h
lib/Basics/exitcodes.h
lib/Rest/CommonDefines.h
lib/SimpleHttpClient/ConnectionCache.h
utils/generateExitCodesFiles.py

Remove an unused function from the RestoreFeature, and replace a left include guard leftovers with `#pragma once`s.

fix compile warning about unused function

---

CHANGELOG
lib/Basics/ResourceUsage.cpp

DEVSUP-898: Change error message for queries that use too much memory from "resource limit exceeded" to "query would use more memory than allowed".

Change query out of memory error message

---

js/client/modules/@arangodb/testutils/process-utils.js
tests/js/client/communication/test-communication.js
tests/js/client/communication/test-kill.js
tests/js/client/shell/shell-arango-secure-installation-noncluster.js
tests/js/client/shell/shell-dump-integration.js
tests/js/client/shell/shell-restore-integration.js

This change only applies to the JavaScript test suites.
In some places, instead of using the path supplied with `--build` to detect the paths to a tool (like `arangorestore`), the path of the directory `arangosh` is in was used instead. Apart from being inconsistent, this isn't generally true. `scripts/unittest` prefers to take the path for arangosh from the environment variable `ARANGOSH`, and tries certain fixed fallbacks otherwise (starting with `build/bin/arangosh`, and finally to executing a `find` command which will return the first executable named `arangosh` it can find 🙄). However, at no place the build directory specified by `--build` is used. Thus, if the build directory isn't called `build`, usually the wrong binaries will be used.

Remove hacks trying to detect tool paths, which do not always work

---

js/apps/system/_admin/aardvark/APP/frontend/js/views/graphManagementView.js

satellites now attached more closer to the edge definition itself, tried to improve description so that it is clear that this input box is about new collections and not existing ones

UI Improvement HybridSmartGraphs

---

CHANGELOG
arangod/Replication/DatabaseInitialSyncer.cpp
arangod/RocksDBEngine/RocksDBRestReplicationHandler.cpp
arangod/RocksDBEngine/RocksDBV8Functions.cpp
lib/Containers/MerkleTree.cpp
lib/Containers/MerkleTree.h
tests/Containers/MerkleTreeTest.cpp
tests/js/server/recovery/revision-trees-sync.js

* Improve performance of getting-in-sync protocol when using revision trees
(for collections created with 3.8). The protocol optimization allows skipping
the unused parts of the revision trees in the data transfer, which can
substantially reduce the amount of data to be transfered for small and medium
collections when trying to get back into sync.
This optimization is already contained in 3.9 and 3.10.
It is opt-in, so it is downwards-compatible to 3.8.x (x <= 2)

Improve revision tree sync performance

---

CHANGELOG
arangod/Cache/BucketState.cpp
arangod/Cache/BucketState.h
arangod/Cache/Cache.cpp
arangod/Cache/Cache.h
arangod/Cache/Manager.cpp
arangod/Cache/Manager.h
arangod/Cache/ManagerTasks.cpp
arangod/Cache/PlainCache.cpp
arangod/Cache/Table.cpp
arangod/Cache/Table.h
arangod/Cache/TransactionalCache.cpp
tests/Cache/BucketState.cpp

* Fixed potential undefined behavior in edge cache during cache migration tasks.
There was a short window of time in which an already freed Table could be
used by concurrently running edge lookups.
The bug can happen when using the edge cache and at the same time a migration task for the same cache is executed.
This requires that concurrent cache access(es) and a cache migration happen for the same edge collection/shard's edge cache at the same time. And still then it is a matter of luck/misfortune because there is only a small window of time in which a raw pointer to the cache's Table is used and dereferenced, while the migration task deletes this very same Table.
A migration to a larger cache is kicked off when after a cache insert the cache goes above 25% fill grade. A migration is …

Fixed potential UB in edge cache migration

---

3rdParty/velocypack/CMakeLists.txt
3rdParty/velocypack/examples/CMakeLists.txt
3rdParty/velocypack/tests/CMakeLists.txt
3rdParty/velocypack/tools/CMakeLists.txt

Enable interprocedure optimizations / link-time optimizations for the VelocyPack library.
All changes in this PR are reflected in the following PR for arangodb/velocypack as well: https://github.com/arangodb/velocypack/pull/102
The overhead on build/links times seems minimal, at least when I tried this locally. This is probably because VelocyPack is a small library, and many things are implemented in header files already.

enable interprocedural optimizations for velocypack library

---

CHANGELOG
arangod/GeneralServer/AuthenticationFeature.cpp
arangod/GeneralServer/GeneralServerFeature.cpp

cleanup duplicate code. See https://github.com/arangodb/arangodb/blob/devel/arangod/GeneralServer/GeneralServerFeature.cpp#L174 for the remaining place.
```
./bin/arangod --server.allow-method-override true  --server.hide-product-header false --server.keep-alive-timeout 10 --no-server false  /tmp/blarg
```
However, 
```
./bin/arangod --server.default-api-compatibility true /tmp/blarg 
Error while processing command-line options for arangod:
unknown option '--'
Did you mean one of these?
--gid     switch to group-id after reading config files
--hund    make ArangoDB bark on startup
--log     the global or topic-specific log level
--uid     switch to user-id after reading config files
Use --help or --help-all to get an overview of available …
```

remove duplicate code, arangod/GeneralServer/GeneralServerFeature.cpp already has these.

---

3rdParty/fakeit-gtest/fakeit.hpp
3rdParty/immer/v0.6.2/extra/guile/scm/detail/invoke.hpp
3rdParty/immer/v0.6.2/extra/guile/scm/detail/subr_wrapper.hpp
3rdParty/immer/v0.6.2/tools/include/nonius.h++
3rdParty/iresearch/external/absl/absl/container/internal/btree.h
3rdParty/iresearch/external/absl/absl/meta/type_traits.h
3rdParty/iresearch/external/absl/absl/types/compare.h
3rdParty/iresearch/external/absl/absl/types/internal/variant.h
3rdParty/iresearch/external/openfst/fst/memory.h
3rdParty/s2geometry/dfefe0c/CMakeLists.txt
3rdParty/s2geometry/dfefe0c/src/s2/third_party/absl/container/inlined_vector.h
3rdParty/s2geometry/dfefe0c/src/s2/third_party/absl/meta/type_traits.h
3rdParty/s2geometry/dfefe0c/src/s2/util/gtl/btree.h
lib/Futures/Future.h
lib/Futures/Try.h
lib/Futures/Utilities.h

Fix various places where STL features have been used that have been deprecated in C++17 and removed in C++20.

Bug fix/avoid cpp17 deprecations

---

arangod/Cluster/UpdateCollection.cpp

releave error message serverity of maintainer mode logmessage to reduce eventlog spam on CI machines

releave error message serverity of maintainer mode logmessage

---

arangod/Agency/AgencyComm.cpp
scripts/startLocalCluster.sh

* make scripts/startLocalCluster.sh start slightly faster by checking for available servers every 1/4 seconds.
* additionally, set the agency's compaction-keep-size to 50000, up from previously 2000. this allows better debugging of local clusters.

make scripts/startLocalCluster.sh start slightly faster

---

CHANGELOG
arangod/Cluster/Action.cpp
arangod/Cluster/Action.h
arangod/Cluster/ActionBase.cpp
arangod/Cluster/ActionBase.h
arangod/Cluster/CreateCollection.cpp
arangod/Cluster/DBServerAgencySync.cpp
arangod/Cluster/EnsureIndex.cpp
arangod/Cluster/Maintenance.cpp
arangod/Cluster/Maintenance.h
arangod/Cluster/MaintenanceFeature.cpp
arangod/Cluster/MaintenanceFeature.h
arangod/Cluster/MaintenanceWorker.cpp
arangod/Cluster/MaintenanceWorker.h
arangod/Cluster/SynchronizeShard.cpp
arangod/Cluster/SynchronizeShard.h
lib/Logger/LogTopic.cpp
tests/Maintenance/MaintenanceFeatureMock.h
tests/Maintenance/MaintenanceFeatureTest.cpp

This PR addresses the problem described in
https://arangodb.atlassian.net/browse/BTS-637
Problem description:
If a dbserver fails and is killed and the supervision is active,
then it is highly likely that a failover will happen before it can come
back. In particular with large processes, this is going to happen. This
immediately triggers a FailedServer job and and as a consequence a lot
of FailedLeader and FailedFollower jobs.
As a consequence, lots of new followers for shards are configured in the Plan.
Now there is a race: Between shard replicas that have the data
and need to get in sync quickly, and newly deployed shard replicas
which need to fetch the data in its entirety. If this happens on
a server, they compete for places in the (low prio) queue of the
MaintenanceFeature . If the …

Introduce slow track in maintenance

---

CHANGELOG
arangod/Cluster/SynchronizeShard.cpp
arangod/Cluster/SynchronizeShard.h
arangod/Replication/DatabaseInitialSyncer.cpp
arangod/Replication/DatabaseInitialSyncer.h
arangod/Replication/DatabaseTailingSyncer.cpp
arangod/Replication/DatabaseTailingSyncer.h
arangod/Replication/GlobalTailingSyncer.cpp
arangod/Replication/GlobalTailingSyncer.h
arangod/Replication/ReplicationClients.cpp
arangod/Replication/Syncer.cpp
arangod/Replication/TailingSyncer.cpp
arangod/Replication/TailingSyncer.h
arangod/RestHandler/RestReplicationHandler.cpp
arangod/RestHandler/RestWalAccessHandler.cpp
arangod/RocksDBEngine/RocksDBEngine.cpp
js/apps/system/_admin/aardvark/APP/frontend/js/routers/router.js
js/apps/system/_admin/aardvark/APP/frontend/js/templates/shardsView.ejs
js/apps/system/_admin/aardvark/APP/frontend/js/views/shardsView.js
js/apps/system/_admin/aardvark/APP/frontend/scss/_shards.scss

Backport of https://github.com/arangodb/arangodb/pull/15085
* Close a potential gap during shard synchronization when moving from the
initial sync step to the WAL tailing step. In this small gap the leader 
could purge some of the WAL files that would be required by the following
WAL tailing step. This was possible because at the end of the initial sync
step, the snapshot on the leader is released, and there is a small window
of time before the follower will issue its first WAL tailing request.
* Improve Shards overview in web UI: the number of currently syncing shards is
now displayed per collection. Additionally, shards on failed servers are now
displayed in a different color.

Feature 3.8/shard sync improvements

---

CHANGELOG
CMakeLists.txt

Improves several build configuration settings for MSVC:
- remove `/Ob1` which limited inline function expansion to functions explicitly marked as `inline`.
- enable SSE42 and ASM_OPTIMIZATIONS
- increase the reserved stack size from the default 1MB to 4MB. This should allow execution of larger queries without overflowing the stack.
- enable COMDAT folding and elimination of functions and data that are never referenced. This reduced the size of the arangod.exe for a non-maintainer build from 61MB to 39MB and the PDB from 753MB to 443MB.

[3.9] MSVC build optimizations

---

tests/js/client/shell/shell-transaction-dropped-followers-cluster.js

Backport of https://github.com/arangodb/arangodb/pull/15091
Add more test cases to dropped-followers test.
This PR only extends an already existing test, so intentionally no CHANGELOG entry added.

added test cases

---

CHANGELOG
arangod/Cluster/FollowerInfo.cpp
arangod/Cluster/FollowerInfo.h
arangod/Cluster/SynchronizeShard.cpp
arangod/RestHandler/RestReplicationHandler.cpp
arangod/Transaction/Methods.cpp
tests/js/client/shell/shell-following-term-id-cluster.js

Backport of https://github.com/arangodb/arangodb/pull/15101
* Fix issues during rolling upgrades from 3.8.0 to 3.8.x (x >= 1) and from
3.7.x (x <= 12) to 3.8.3. The problem was that older versions did not handle
following term ids that are sent from newer versions during synchronous
replication operations.

Fix issues with following term ids during rolling upgrade

---

Documentation/DocuBlocks/Rest/Cursors/post_api_cursor.md
Documentation/DocuBlocks/Rest/Cursors/post_api_cursor_identifier.md
Documentation/DocuBlocks/Rest/Cursors/put_api_cursor_identifier.md

Documentation for https://arangodb.atlassian.net/browse/APM-185 and https://arangodb.atlassian.net/browse/APM-68. 
During the execution of a query in a cluster, for methods POST and PUT, there are cases in which there are 2 other  HTTP return codes: 410 and 503. 
The server will respond with HTTP 410 if a server which will process the query
or is the leader for a shard which is used in the query stops responding, but 
the connection has not been closed.
The server will respond with HTTP 503 if a server which will process the query
or is the leader for a shard which is used in the query is down, either for 
going through a restart, a failure or connectivity issues.
Obs.: for DELETE, this can be the case as well, must find an example in which these codes are returned.
No tests required.

Added documentation for APM-68 and APM-185

---

CHANGELOG
lib/Basics/CrashHandler.cpp

Extend Windows minidumps with memory regions referenced from CPU registers or the stack to provide more contextual information in case of crashes.

Extend Windows minidump with referenced memory regions.

---

Documentation/DocuBlocks/Rest/Cursors/post_api_cursor.md
Documentation/DocuBlocks/Rest/Cursors/post_api_cursor_identifier.md
Documentation/DocuBlocks/Rest/Cursors/put_api_cursor_identifier.md

Backport for https://github.com/arangodb/arangodb/pull/15095.
Documentation for https://arangodb.atlassian.net/browse/APM-185 and https://arangodb.atlassian.net/browse/APM-68. 
During the execution of a query in a cluster, for methods POST and PUT, there are cases in which there are 2 other  HTTP return codes: 410 and 503. 
The server will respond with HTTP 410 if a server which will process the query
or is the leader for a shard which is used in the query stops responding, but 
the connection has not been closed.
The server will respond with HTTP 503 if a server which will process the query
or is the leader for a shard which is used in the query is down, either for 
going through a restart, a failure or connectivity issues.
Obs.: for DELETE, this can be the case as well, must find an …

Added documentation for backport for PR 15095

---

CHANGELOG
arangod/RocksDBEngine/RocksDBIncrementalSync.cpp
tests/js/server/replication/ongoing/global/replication-ongoing-global.js
tests/js/server/replication/ongoing/replication-ongoing.js
tests/js/server/replication/sync/replication-sync-malarkey.js

Backport of https://github.com/arangodb/arangodb/pull/15120
* Fixed an issue in old incremental sync protocol with document keys that
contained special characters (`%`). These keys could be send unencoded in
the incremental sync protocol, leading to wrong key ranges being transfered
between leader and follower, and thus causing follow-up errors and preventing
getting in sync.

Bugfixes for old incremental sync protocol

---

CHANGELOG
arangod/RocksDBEngine/RocksDBIncrementalSync.cpp
tests/js/server/replication/sync/replication-sync-malarkey.js

* Fixed an issue in old incremental sync protocol with document keys that
contained special characters (`%`). These keys could be send unencoded in
the incremental sync protocol, leading to wrong key ranges being transfered
between leader and follower, and thus causing follow-up errors and preventing
getting in sync.

Fixed an issue in old incremental sync protocol

---

CHANGELOG
arangod/Aql/ExecutionBlockImpl.cpp
arangod/RocksDBEngine/RocksDBIncrementalSync.cpp
tests/js/server/replication/sync/replication-sync-malarkey.js
utils/checkLogIds.py

* Fixed an issue in old incremental sync protocol with document keys that
contained special characters (`%`). These keys could be send unencoded in
the incremental sync protocol, leading to wrong key ranges being transfered
between leader and follower, and thus causing follow-up errors and preventing
getting in sync.

Fixed issues with old incremental sync protocol

---

arangod/RocksDBEngine/Listeners/RocksDBThrottle.cpp

Remove 2 unused variables, so clang-13 does not complain about them.
This only affects compilation, but is not a user-visible change. Thus intentionally no CHANGELOG entry added for this PR.

remove unused variables

---

Documentation/DocuBlocks/Rest/Cursors/post_api_cursor.md
Documentation/DocuBlocks/Rest/Cursors/post_api_cursor_identifier.md
Documentation/DocuBlocks/Rest/Cursors/put_api_cursor_identifier.md

Backport for https://github.com/arangodb/arangodb/pull/15095.
Documentation for https://arangodb.atlassian.net/browse/APM-185 and https://arangodb.atlassian.net/browse/APM-68. 
During the execution of a query in a cluster, for methods POST and PUT, there are cases in which there are 2 other  HTTP return codes: 410 and 503. 
The server will respond with HTTP 410 if a server which will process the query
or is the leader for a shard which is used in the query stops responding, but 
the connection has not been closed.
The server will respond with HTTP 503 if a server which will process the query
or is the leader for a shard which is used in the query is down, either for 
going through a restart, a failure or connectivity issues.
Obs.: for DELETE, this can be the case as well, must find an …

Bug fix 3.9/documentation server failure 410

---

js/client/modules/@arangodb/test-helper.js

This only cleans up helper code used during testing. It does not cause any behavior changes.
3.9 and devel do not need this cleanup.

remove redundant implementation of debugClearFailAt

---

arangod/Replication/DatabaseInitialSyncer.cpp

Backport of https://github.com/arangodb/arangodb/pull/15137
do not clobber replication failure if a success callback is set

do not clobber replication failure if a success callback is set

---

CHANGELOG
arangosh/Backup/BackupFeature.cpp

* Make the `--version` and `--version-json` commands usable in arangobackup
when no positional argument (operation type) was specified. Previously,
arangobackup insisted on specifying the operation type alongside the
`--version` or `--version-json` commands.

improve usability of --version for arangobackup

---

js/client/modules/@arangodb/testsuites/aql.js
js/client/modules/@arangodb/testutils/process-utils.js
tests/js/client/shell/shell-promtool-cluster.js

Backport of https://github.com/arangodb/arangodb/pull/15145
Fix non-deterministic dropping of followers during tests
This change increases the supervision grace period from 10 seconds to a higher value when running the `shell_client` tests. it seems that 10 seconds is not enough on overloaded servers, so that we randomly get failedLeader jobs during the tests, which can lead to spurious dropping of followers. this is a problem because some tests assume that during the tests no followers are getting dropped.

fix non-deterministic dropping of followers during tests

---

Documentation/DocuBlocks/Rest/Administration/get_admin_license.md
Documentation/DocuBlocks/Rest/Administration/put_admin_license.md

Related: https://github.com/arangodb/docs/pull/790
It's currently not possible to add a working example of setting a new license successfully (no demo license key). Kaveh looks into it. Meanwhile, we need to put the examples in the description text.
**Backport of https://github.com/arangodb/arangodb/pull/14892**

Add DocuBlocks for /_admin/license endpoint (#14892)

---

arangod/Replication2/ReplicatedLog/LogCommon.h
arangod/Replication2/ReplicatedLog/LogLeader.cpp
arangod/Replication2/ReplicatedLog/ReplicatedLogFeature.cpp
arangod/RocksDBEngine/RocksDBPersistedLog.cpp
tests/Replication2/ReplicatedLog/AppendEntriesBatchTest.cpp

The naming was misleading, as it  did not reflect the maximum size of
a batch that is sent, but a threshold that triggers sending of a batch
of log updates.
We also disable the command line options for `ReplicatedLog` when not building in maintainer mode to not cause confusion with documentation building, or accidentally offering unfinished options to users of released versions.

[CINFRA-129] Rename max{...} to threshold{...}

---

3rdParty/fuerte/src/AsioSockets.h
3rdParty/fuerte/src/GeneralConnection.h

Implicit `this` captures are deprecated as of c++20, so better remove them before things break.

Add some explicit captures for this

---

tests/Replication2/ReplicatedLog/AppendEntriesBatchTest.cpp

Fix missing rename of _thresholdNetworkBatchSize.

Fix missing rename of _thresholdNetworkBatchSize.

---

CHANGELOG
arangod/RocksDBEngine/RocksDBIncrementalSync.cpp
tests/js/server/replication/ongoing/global/replication-ongoing-global.js
tests/js/server/replication/ongoing/replication-ongoing.js
tests/js/server/replication/sync/replication-sync-malarkey.js

Backport of https://github.com/arangodb/arangodb/pull/15120
* Fixed an issue in old incremental sync protocol with document keys that
contained special characters (`%`). These keys could be send unencoded in
the incremental sync protocol, leading to wrong key ranges being transfered
between leader and follower, and thus causing follow-up errors and preventing
getting in sync.

Bug fix 3.8/fix incremental sync keys

---

CMakeLists.txt

The repo string for EE was incorrect and the same as CE (3.9)

---

CHANGELOG
arangod/Replication/DatabaseInitialSyncer.cpp
arangod/Replication/Syncer.cpp
arangod/Replication/TailingSyncer.cpp
arangod/RocksDBEngine/RocksDBIncrementalSync.cpp

This PR aims to get rid of the NO_INDEXING hint during initial shard
synchronization. To avoid performance losses, we will commit the
transaction after each chunk (5000 documents).
This PR also fixes some unsafe uses of LogicalCollection pointers.
- In handleSyncKeysRocksDB commit after each chunk.
- CHANGELOG.
- [*] :hankey: Bugfix 
- [*] :muscle: The behavior in this PR was *manually tested*
- [*] Backports required for: This will be forward ported to 3.8, 3.9
and devel.
- [*] GitHub issue / Jira ticket number: This is a followup work to
https://github.com/arangodb/arangodb/pull/15117
- [*] This change …

Avoid NO_INDEXING inc sync

---

arangod/Aql/AqlItemBlock.h
arangod/Aql/HashedCollectExecutor.h
lib/Containers/FlatHashMap.h

Prefer using absl::flat_hash_map<...> instead of std::unordered_map<...> where applicable. It's always faster.
https://martin.ankerl.com/2019/04/01/hashmap-benchmarks-01-overview/

prefer using absl::flat_hash_map

---

CHANGELOG
arangod/RocksDBEngine/RocksDBCollection.cpp

Removed an invalid assertion in `removeDocument` that assertion could be triggered during chaos testing in maintainer mode.
The assertion is invalid under the following circumstances:
* `removeDocument` is called by `truncate`
* the `truncate` has created an iterator for the collection's documents in which the document still existed
* another concurrent thread removed a document from the snapshot
* the thread that performs the truncate does an intermediate commit
Then the thread that performs truncate will be unable to find the document in the database that still exists in the snapshot. Thus the assertion will fire.
This fixes https://arangodb.atlassian.net/browse/BTS-601

Removed an invalid assertion in `removeDocument`

---

CHANGELOG
arangod/Aql/Ast.cpp
arangod/Aql/Ast.h
arangod/Aql/AstNode.h
arangod/Aql/ConditionFinder.cpp
arangod/Aql/ExecutionPlan.cpp
arangod/Aql/Optimizer.cpp
arangod/Aql/OptimizerRules.cpp
arangod/Aql/OptimizerRules.h
arangod/Aql/grammar.cpp
arangod/Aql/grammar.h
arangod/Aql/grammar.hpp
arangod/Aql/grammar.y
tests/js/server/aql/aql-read-own-writes.js

Backport of https://github.com/arangodb/arangodb/pull/15176
* Simplify the tagging of EnumerateCollectionNodes and IndexNodes with the
"read-own-writes" flag. Previously the tagging only happened after all query
optimizations were completed, making the tag unavailable to the optimizer.
Now the tag is set early on, so it is accessible by the query optimizer.
This change is required to complete https://arangodb.atlassian.net/browse/BTS-624

Feature 3.8/simplify read own writes tagging

---

CHANGELOG
arangod/Aql/Ast.cpp
arangod/Aql/Ast.h
arangod/Aql/AstNode.h
arangod/Aql/ConditionFinder.cpp
arangod/Aql/ExecutionPlan.cpp
arangod/Aql/Optimizer.cpp
arangod/Aql/OptimizerRules.cpp
arangod/Aql/OptimizerRules.h
arangod/Aql/grammar.cpp
arangod/Aql/grammar.h
arangod/Aql/grammar.hpp
arangod/Aql/grammar.y
tests/js/server/aql/aql-read-own-writes.js

Backport of https://github.com/arangodb/arangodb/pull/15176
* Simplify the tagging of EnumerateCollectionNodes and IndexNodes with the
"read-own-writes" flag. Previously the tagging only happened after all query
optimizations were completed, making the tag unavailable to the optimizer.
Now the tag is set early on, so it is accessible by the query optimizer.
This change is required to complete https://arangodb.atlassian.net/browse/BTS-624

Feature 3.9/simplify read own writes tagging

---

.gitignore
Documentation/Metrics/arangodb_arangosearch_cleanup_time.yaml
Documentation/Metrics/arangodb_arangosearch_commit_time.yaml
Documentation/Metrics/arangodb_arangosearch_consolidation_time.yaml
Documentation/Metrics/arangodb_arangosearch_index_size.yaml
Documentation/Metrics/arangodb_arangosearch_num_buffered_docs.yaml
Documentation/Metrics/arangodb_arangosearch_num_docs.yaml
Documentation/Metrics/arangodb_arangosearch_num_failed_cleanups.yaml
Documentation/Metrics/arangodb_arangosearch_num_failed_commits.yaml
Documentation/Metrics/arangodb_arangosearch_num_failed_consolidations.yaml
Documentation/Metrics/arangodb_arangosearch_num_files.yaml
Documentation/Metrics/arangodb_arangosearch_num_live_docs.yaml
Documentation/Metrics/arangodb_arangosearch_num_segments.yaml
arangod/IResearch/IResearchLink.cpp
arangod/IResearch/IResearchLink.h
arangod/IResearch/IResearchView.cpp
arangod/RestServer/Metrics.h
arangod/RestServer/MetricsFeature.cpp
arangod/RestServer/MetricsFeature.h
arangod/VocBase/Identifiers/LocalDocumentId.cpp
arangod/VocBase/Identifiers/LocalDocumentId.h
arangod/VocBase/Identifiers/RevisionId.cpp
arangod/VocBase/Identifiers/RevisionId.h
tests/IResearch/IResearchLinkTest.cpp
tests/IResearch/IResearchQueryNoMaterializationTest.cpp

Add metrics for IResearchLink
And small refactoring
Based on this PR: https://github.com/arangodb/arangodb/pull/14532
<details><summary> 
<b>Example of usage (Single Server):</b>
</summary>
```
$ curl --header 'accept: application/json' --dump - http://localhost:8529/_admin/metrics | grep arangosearch
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 65129  100 65129    0 # HELP arangodb_arangosearch_cleanup_time Some average time of last cleanups in microseconds
0arangodb_arangosearch_cleanup_time{role="SINGLE",viewId="hFAEF893B47B8/252",collId="205",shardName="",dbName="1"} 0
arangodb_arangosearch_cleanup_time{role="SINGLE",viewId="hFAEF893B47B8/252",collId="211",shardName="",dbName="1"} 0
11# HELP …
```

Search-183

---

arangod/StorageEngine/PhysicalCollection.cpp
arangod/StorageEngine/PhysicalCollection.h

VPack slices only contain a single pointer data member, so they can be
passed around by value. It is not necessary to pass them by reference.

do not pass VPack slices as const references

---

CONTRIBUTING.md

Remove some older ArangoDB versions from CONTRIBUTING.md. Documentation only.

remove old versions from CONTRIBUTING.md

---

arangod/Cluster/MaintenanceFeature.cpp
arangod/Cluster/MaintenanceFeature.h
scripts/startLocalCluster.sh

Avoid duplication of arangod process startup options in `scripts/startLocalCluster.sh`. The options were previously specified twice for agents, and twice for DB servers/coordinators. Now they are specified only once for agents and once for DB servers/coordinators.
In addition, also log an annoying maintenance log message later during the startup process, so that it actually is logged to the configured logfile and not stdout.

avoid duplication of arangod process options

---

CHANGELOG
CMakeLists.txt

Backport for #15213 and #15219
Disable COMDAT folding (aka Identical Code Folding) on Windows, because it can break a program that depends on unique addresses for functions or read-only data members (which apparently we do).

[3.8] Disable COMDAT folding.

---

CHANGELOG
arangod/RocksDBEngine/RocksDBCollection.cpp

Whenever we find a document in the primary index, but then fail to
locate the actual document in the documents column family, we write
an ERROR into the log. In maintainer mode, we trigger an assertion
failure.
- Report inconsistency between primary index and actual documents better.
- CHANGELOG.
- [*] Minor visibility improvements in case of data corruption
- [*] Backport for 3.9: *(Please link PR)*
- [*] Backport for 3.8: *(Please link PR)*
- [*] Backport for 3.7: *(Please link PR)*
- [*] GitHub issue / Jira ticket number: https://arangodb.atlassian.net/browse/BTS-653
- [*] …

Better corruption visibility

---

CHANGELOG
arangod/RocksDBEngine/RocksDBCollection.cpp
arangod/RocksDBEngine/RocksDBCommon.cpp
arangod/RocksDBEngine/RocksDBCommon.h
arangod/RocksDBEngine/RocksDBEngine.cpp
arangod/RocksDBEngine/RocksDBIndex.cpp
arangod/RocksDBEngine/RocksDBV8Functions.cpp

Backport of https://github.com/arangodb/arangodb/pull/15148
* Make `db.<collection>.figures(true)` operate on the same snapshot when
counting the number of documents in the documents column family and the
indexes. This ensures consistency for the results of a single figures result.

ensure consistency for `db.<collection>.figures(true)` count results

---

CHANGELOG
Documentation/DocuBlocks/Rest/Indexes/post_api_index.md
Documentation/DocuBlocks/Rest/Indexes/post_api_index_fulltext.md

https://arangodb.atlassian.net/browse/APM-217
APM-217: deprecate the usage of fulltext indexes.
This is a documentation-only PR.

APM-217: deprecate the usage of fulltext indexes.

---

tests/js/client/communication/test-communication.js

This increases the test timeout to 30s to detect a deadlock.

[BTS-565] 3.8 Timeout without deadlock

---

tests/js/server/replication/ongoing/replication-ongoing.js

This is a test-only change.
Fix a spuriously failing replication test that is due to us not waiting for `waitForSync`.
This should fix the error
```
* Test "replication_ongoing"
[FAILED]  tests/js/server/replication/ongoing/replication-ongoing.js
"testPrimaryKeyConflict_ReplOther" failed: Error: at assertion #2: assertEqual: (slave) is not equal to (master)
```
Fixes for this have been done in 3.8, 3.9 and devel already.

fix a spuriously failing replication test

---

tests/js/client/communication/test-communication.js

This increases the test timeout to 30s to detect a deadlock.

[BTS-565] 3.7 Timeout without deadlock

---

CHANGELOG
CMakeLists.txt

Backport for #15213 and #15219
Disable COMDAT folding (aka Identical Code Folding) on Windows, because it can break a program that depends on unique addresses for functions or read-only data members (which apparently we do).

[3.7] Disable COMDAT folding.

---

arangod/Cluster/SynchronizeShard.cpp

Add back "doSoftLockOnly" attribute for shard sync protocol.
This attribute was previously always present when the follower sent its request to the leader, but it was unintentionally removed during the development of 3.7.16. the change has not been released in any version.
No other version was affected.

add back "doSoftLockOnly" attribute for shard sync protocol

---

CHANGELOG
client-tools/Benchmark/BenchFeature.cpp
client-tools/Benchmark/BenchFeature.h
js/client/modules/@arangodb/testsuites/arangobench.js

In arangobench, the concurrency flag is called `--concurrency`, but, in the other tools, it is called `--threads`, so this PR changes arangobench flag name to `--threads` to be in accordance with the other tools.
No backports needed
- [ x] This PR adds tests that were used to verify all changes:

Changed flag name from --concurrency to --threads

---

3rdParty/CMakeLists.txt

make velocypack IPO setting depend on global IPO setting

make velocypack IPO setting depend on global IPO setting

---

tests/js/client/communication/test-communication.js

This increases the test timeout to 30s to detect a deadlock.

[BTS-565] 3.9 Timeout without Deadlock
