- js/common/modules/org/arangodb/foxx/preprocessor.js
I am following the [My First Foxx App](https://docs.arangodb.com/cookbook/FoxxFirstSteps.html) cookbook, and reached the step where API documentation is added to the basic get controller implementation. After completing this step, the API documentation part of the ArangoDB web interface failed with the following message:
Sorry the code is not documented properly
"Unable to read api 'todos' from path http://localhost:8529/_db/_system/_admin/aardvark/docu/dev%3Atodos%3Atodos/dev/todos?api_key=false (server returned Internal Error)"
I discovered by experimentation that this error was produced when using Windows (CR/LF) line endings in my todos.js controller file. Switching to Unix line endings fixed the problem.
Suggest this would be a showstopper for a naive programmer.
> API documentation fails with Windows line endings

- CHANGELOG
- js/server/modules/org/arangodb/foxx/request_context.js
- js/server/tests/shell-foxx.js
So far the `allowInvalid` flag was pretty useless to guard against invalid request bodies.
I've adjusted it so the request body is actually validated against the model if the model has a schema (unless `allowInvalid` is enabled). This may cause some routes to break, but only those that relied on `allowInvalid: false` to protect them against arbitrary garbage (unsuccessfully) yet would accept well-formed garbage just fine. I think this constitutes a bugfix, actually.
Also, if the request body model doesn't have a schema, the validation is skipped as before.
Additionally you can now use bare joi schemas to define your request bodies, which makes the `bodyParam` behave more like the other param definitions. It doesn't automagically wrap them in Foxx models either, it just passes the result …
> Allow bodyParam to take joi schemas and actually validate data

- CHANGELOG
- Documentation/Books/Users/Foxx/Develop/Model.mdpp
- Documentation/Books/Users/Foxx/Develop/Repository.mdpp
- UnitTests/Makefile.unittests
- js/server/modules/org/arangodb/foxx/model.js
- js/server/modules/org/arangodb/foxx/repository.js
- js/server/tests/shell-foxx-model.js
- js/server/tests/shell-foxx-repository-events-spec.js
This PR implements some small improvements for Foxx models.
This fixes #1284 and #1257.
I was considering making Foxx Models static event emitters, but it requires a lot of contortion to isolate the events emitted by sub-types. Having `Foxx.Model` listen to and emit all events doesn't seem particular useful either. Having the events on the repository isn't entirely satisfying (separation of concerns etc) but seems to be the cleanest solution to #1257 by far.
The PR also allows passing joi object schemas (rather than the conventional object-with-schemas-as-properties). This allows easier re-use of joi schemas.
> Foxx improvements (fixes #1284, #1257)

- js/server/modules/org/arangodb/foxx/request_context.js
Ideally, more refactoring would be done to rename `errorClass` to `errorConstructorOrName` all the way down to routing.js and adding an example for using errorResponse to catch "ValidationError" and return status 422.
> adding missing documentation for errorResponse

- Documentation/Books/Users/Foxx/Develop/Sessions.mdpp
More specifically, attribute names for header and cookie info.
> Corrected documentation examples for Foxx Sessions

- lib/SimpleHttpClient/ClientConnection.cpp
- lib/SimpleHttpClient/SslClientConnection.cpp
select() modifies the given timeout variable.  Calling select() again
will run with the remaining timeout.  However, method prepare()
overwrote the reduced timeout in each iteration.
> lib/SimpleHttpClient: don't reset timeout after EINTR

- js/server/assets/swagger/index-alt.html
- js/server/assets/swagger/index.html
https://github.com/swagger-api/swagger-ui#parameters
This was hacked in `onComplete` function for the admin documentation, but for the mounted documentation it was always unfolded. Swagger 2.0 has a configuration parameter for this.
> Documentation should be expanded by default

- .gitignore
If using cmake, same files are generated.
It would be easier to just `git add .` for new files and not checking for `Untracked files`
> Git ignore for CMAKE generated files

- Documentation/Books/Makefile
- Documentation/Books/Users/README.mdpp
- Documentation/Books/Users/book.json
Many ebook readers (and reading apps) generate covers from metadata like the book title. Therefore it makes sense to place the version string there instead of the first paragraph.
Not sure what it tries to read from the book metadata below the title on the right side ("*Unknown*"), maybe it's the description?
http://help.gitbook.com/format/configuration.html#description
> Make version more prominent in documentation

- Documentation/Books/Users/Foxx/Install/README.mdpp
Some code blocks were broken because of an extra backtick. Uses space indent now.
> Fix Foxx docs markdown

- js/common/modules/org/arangodb/arango-collection-common.js
- js/server/modules/org/arangodb/arango-database.js
Yet to be fixed:
1. `... has an attribute @LIT{c} of ... `:<br>
`@LIT{c}` appears literally in documentation, is it resolved if used in .cpp/.h only?
2. `byExampleSkiplist()` and `byExampleHash()` list alternative signatures without further explanation, and do not actually implement it. They only pass the *example* argument on:
var sq = this.byExample(example);
Required change to support `.byExample*(index-id, "foo", 5, "bar", 1337)` as alternative to `(index-id, {foo: 5, bar: 1337})`:
var sq = this.byExample.apply(this, Array.prototype.slice.call(arguments).slice(1))
but better check arguments.length and don't apply/call if there are only 2 arguments, for better performance. But is it supposed to the implemented at all?
> Minor documentation fixes

- Documentation/Books/Users/Advanced/Arangob.mdpp
- Documentation/Books/Users/Aql/Advanced.mdpp
- Documentation/man1/arangob
- js/server/modules/org/arangodb/aql.js
8 or spaces of indentation create a code block in markdown, but wasn't intended
> Documentation formatting

- Documentation/Books/Users/AqlExtending/Conventions.mdpp
- Documentation/Books/Users/AqlExtending/Functions.mdpp
- Documentation/Books/Users/AqlExtending/README.mdpp
documentation change: point out that  AQL User Functions are defined on the selected database (not globally)
> documentation: point out the User Function is defined on the selected database

- Documentation/Books/Users/Graphs/README.mdpp
Just the basics, noticed a few typos and cleaned them up.
> documentation: Clean up typos on graphs page.

- cmake/TargetArch.cmake
Recognition of architecture by compiler (preprocessor) error
Runs as on ODROID C2, Pine A64 
Similar change:
https://github.com/anqixu/ueye_cam/blob/master/cmake_modules/TargetArch.cmake
> Complete to __aarch64__ achritectur

- lib/Basics/operating-system.h
Adapting to a new 64 bit architecture (aarch64) at the exceptions for TRI_PADDING_32
> Adapting to 64 bit ARM architecture (aarch64)

- js/common/bootstrap/modules/internal.js
If queue job return error, it never retry execute because stuck when check variable result.
error detail:
```
TypeError: Cannot convert object to primitive value at hasOwnProperty (native)
at global.DEFINE_MODULE.exports.flatten (/usr/share/arangodb3/js/common/bootstrap/modules/internal.js:1493:39)    
at Object.exports.work (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/queues/worker.js:121:13)    
at eval (eval at undefined, <anonymous>:8:59)
at eval (eval at undefined, <anonymous>:11:17)    
at eval (eval at undefined, <anonymous>:11:29)
```
> Error when job retried: Cannot convert object to primitive value

- cmake/CheckCXX11Features.cmake
The result of the check is stored in a sub-directory and not directly in the build folder
> Improve of the C++ feature check.

- js/apps/system/_admin/aardvark/APP/frontend/js/templates/queryView.ejs
- js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
Add a Save button, New button and a Title to view the current Query.
Try to make this change with minimal impact on already existed behavior.
I'm really not a front-end person, soo I may need some help to make the modifications more "pretty" or adjust to fit some system standard.
> Add 'Save' and 'New' button for Query Editor #1906

- 3rdParty/V8/CMakeLists.txt
in  standalone.gypi is the target_arch derived from host_arch and host_arch is automatically detected. The cross-compiler is misconfigured and ICU is compiled with settings for x64. This change overrides host_arch.
> Set host_arch by CROSS_COMPILING

- 3rdParty/V8/V8-5.0.71.39/tools/gyp/v8.gyp
ArangoDB use no snapshot, but use v8_use_snapshot=true for creating  additinal libs (v8_libbase, 'v8_libplatform). Due this change can be used v8_use_snapshot=false.
Note: this works only with gyp and Unix make. Ninja don't work with v8_use_snapshot=false.
> Adding dependencies by no v8_use_snapshot

- js/server/modules/@arangodb/foxx/manager.js
When install/upgrade, arangodb response is "No such file or directory".
This is because serviveInfo path already join with temporary Path, and then
in "uploadToPeerCoordinators" it join twice with temporary path.
Another problem, arangodb upgrade url is "update" not "upgrade".
Last problem, when Sync foxx with another cluster, use "coordinatorTransactionID"
but there is no that key response from ArangoClusterComm.
Sample response from ArangoClusterComm
```
{
"results": [
{
"clientTransactionID": "6100001",
"coordTransactionID": "80",
"operationID": "69",
"endpoint": "tcp://0.0.0.0:8631",
"singleRequest": false,
"shardID": "",
"status": "RECEIVED",
"headers": {
"content-length": "38",
"x-arango-response-code": "201 Created"
},
"body": "{\"filename\":\"uploads/tmp-1-622403075\"}"
}
], …
```
> fix upgrade/install foxx in cluster environment

- Documentation/Books/Manual/GettingStarted/Installing/MacOSX.mdpp
Took me a while to find how to change server.endpoint. When editing provided plist file and using `brew services start arangodb` `ProgramArguments` from plist are ignored for some reason. So the only way to switch from `127.0.0.1:8529` to `0.0.0.0:8529` was to edit `arangod.conf` file and restart services with brew. After that I was able to access web interface remotely.
> Adding note about configuration file and endpoint.

- scripts/build-xc64-deb.sh
since boost 1.62 works the aarch64 (arm64) arichtecture out of the box
> add aarch64 build script

- scripts/build-deb.sh
After @dothebart pointed this script out I used it to build a package for Ubuntu 16.10. To do so I needed to figure out which packages needed to be installed and where the packages go after they are built.
I thought capturing those things in a comment might be helpful for others.
Let me know if I got the deps wrong.
> Add explanatory comment to build-deb

- js/server/modules/@arangodb/foxx/queues/worker.js
On queue.push method, success callback always give empty result, because result variable never assigned as output.
```
queue.push(
{mount: 'some path', name: 'some queue'},
{data},
{
success: function(result, jobData, job){
//result always empty
console.log(result);
}
}
)
```
> Fix result value from queue worker

- arangod/Cluster/ClusterInfo.cpp
This removes the coord list hack introduced in #2479.
Right now this hack is used to ensure the coordinator list used when distributing services and self-healing coordinators is always fresh but these changes should no longer be necessary.
It seems this particular list is only used in JavaScript right now so this should not affect cluster logic outside of Foxx.
> Remove coord list hack

- lib/ApplicationFeatures/SupervisorFeature.cpp
As discussed, this rephrases the child process exit messages to be a little more intuitive.
> Reword 'horrible' messages

- CHANGELOG
- Documentation/Books/Manual/Appendix/JavaScriptModules/ArangoDB.md
- Documentation/Books/Manual/ReleaseNotes/NewFeatures32.md
- js/common/modules/@arangodb/common.js
As discussed this adds `require('@arangodb').time` with documentation.
I don't think we currently have tests for `internal.time` which this wraps, so maybe this is the right time (hah) to add them.
This PR should be safe to backport to 3.1 and 3.0 if we want to do that.
> Expose internal.time

- arangod/Agency/AgencyComm.cpp
- arangod/Agency/Agent.cpp
- scripts/startStandAloneAgency.sh
Agent.cpp busy waiting in run method. 
AgencyComm.cpp will grow connection timeout from 1.0 to maximal 5.0 in sendWithFailover.
1.0 often at very high loads too short in ssl context.
> fixing the agency comm issues detected with the go-driver tests

- Documentation/Books/Manual/Administration/Configuration/GeneralArangod.md
- Documentation/Books/Manual/Administration/Configuration/RocksDB.md
- Documentation/Books/Manual/Administration/Configuration/Wal.md
- Documentation/Books/Manual/Appendix/JavaScriptModules/WAL.md
- Documentation/Books/Manual/Architecture/WriteAheadLog.md
- WAL is not available with rocksdb
- WAL commands don't output usefull data for rocksdb
- have to manually migrate to rocksdb.
> Document storage engine choice

- etc/jenkins/arangod-agency.conf
- etc/jenkins/arangod-agent.conf
- etc/jenkins/arangod-coordinator.conf
- etc/jenkins/arangod-dbserver.conf
- etc/jenkins/arangod-single.conf
- etc/jenkins/arangod.conf
fixed jenkins configuration files to point to the proper default include
> jenkins configuration files where erroneously pointing to 'testing'

- arangod/RestServer/LockfileFeature.cpp
- lib/Basics/files.cpp
This fixes the error messages in several cases when the lockfile `LOCK` for the arangod database cannot be acquired using fcntl. The error messages are now much more sensible and not misleading.
This also fixes a wrong file-open mode for lockfiles.
> fix lockfile-related messages

- cmake/InstallArangoDBJSClient.cmake
after a discussion with @hkernbach yesterday we isolated source files for the aardvark UI which don't need to be delivered with the packages. 
This patch adds blacklist items to speed up the install process.
> don't install aardvark source files into packages

- arangod/RocksDBEngine/RocksDBVPackIndex.cpp
The ArangoDB VPackIndex now does not attempt to compute an Estimate on Coordinator. Caused the coordinator to crash
> Fix Index Estimates in RocksDB coordinator.

- lib/Basics/operating-system.h
This should fix the following warning on MSVC:
C:\b\willi_arangodb\lib\Logger\LogAppenderFile.cpp(227): warning C4996: 'fdopen': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _fdopen. See online help for details. [C:\b\y\lib\arango.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\ucrt\stdio.h(2448): note: see declaration of 'fdopen'
> added wrapper for fdopen

- CHANGELOG
- js/common/modules/@arangodb/foxx/manager-utils.js
Foxx disabling development mode creates non-deterministic service bundle
> Fix issue #2677

- Documentation/DocuBlocks/Rest/Foxx/api_foxx_service_install.md
- Documentation/DocuBlocks/Rest/Foxx/api_foxx_service_replace.md
- Documentation/DocuBlocks/Rest/Foxx/api_foxx_service_upgrade.md
- js/apps/system/_api/foxx/APP/index.js
- js/apps/system/_api/foxx/APP/multipart.js
- js/apps/system/_api/foxx/APP/schemas.js
Some minor adjustments to the Foxx API:
* the list route now allows filtering system services, analogous to the ArangoDB API for listing collections
* the install/upgrade/replace routes now take options as JSON objects rather than JSON strings containing serialized JSON objects
This was initially done to allow passing the options via multipart uploads which can't contain objects, but I've adjusted the multipart handling to attempt to parse string values as JSON before giving up and treating them as plain strings. This shouldn't be a problem unless someone uses a valid JSON value as source, for example (e.g. `source=25` would parse to a Number) but that seems unlikely. We might want to write tests for this edge case behaviour however (are there any weird objects we can pass via source that …
> Allow passing plain JSON data for config/deps

- Documentation/DocuBlocks/Rest/Foxx/api_foxx_tests_run.md
- js/apps/system/_api/foxx/APP/index.js
Keeping track of the appropriate Accept headers is a bit cumbersome for drivers so having a catchall flag to opt in helps.
> Add "idiomatic" flag to Foxx tests

- js/apps/system/_api/foxx/APP/index.js
This _should_ already behave correctly but having it explicit helps when reading the code.
> Explicitly return 204 status code on commit

- lib/ApplicationFeatures/EnvironmentFeature.cpp
As per Max's request, I've changed the warning to only display if the overcommit ratio is set too low to utilize all available physical RAM, and adjusted the message to recommend setting between this floor and 100 (for all ram + swap). Max, if you could check that this fixes your issue, I'd appreciate it.
> Changed VM overcommit recommendation for user-friendliness.

- arangod/GeneralServer/HttpCommTask.cpp
The problem happened when the two first chunks of a VST message arrived
together on a connection that was newly switched to VST.
> Fix a hangup in VST.

- arangod/MMFiles/MMFilesEngine.cpp
- arangod/MMFiles/MMFilesLogfileManager.cpp
- arangod/MMFiles/MMFilesLogfileManager.h
- arangod/RestServer/DatabaseFeature.cpp
database feature now comes first. this ensures that the mmfiles collector thread
(owned by the mmfiles logfile manager) can always access the list of databases,
and that this list is not destroyed while the collector thread is still running.
> change init order of mmfiles logfile manager and database feature

- arangod/VocBase/TraverserOptions.cpp
In some cases the condition was checked against such in MMFiles.
This caused a ASSERTION to kick in.
> Fixed a bug to resolve externals in Traversal Condition checker.

- arangod/RestHandler/RestVocbaseBaseHandler.cpp
Returning the proper index data was already implemented for the JavaScript APIs, but missing in the HTTP API.
> properly return index in case of unique constraint violation

- lib/ApplicationFeatures/ConfigFeature.cpp
- lib/ProgramOptions/IniFileParser.h
Vector options in configuration files including others which set
them as well had been ignored. This patch fixes this behaviour.
> Fix configuration file reader in the presence of @include.

- arangod/RestServer/DatabaseFeature.cpp
- arangod/RestServer/arangod.cpp
- arangod/StorageEngine/StorageEngine.h
- arangod/StorageEngine/StorageEngineFeature.h
so that other features can indicate that they need a storage engine
but do not need to reference a concrete storage engine such as "mmfiles"
or "rocksdb"
> add a generic "StorageEngine" feature

- arangod/Agency/Agent.cpp
- arangod/Agency/Job.cpp
- arangod/Agency/RestAgencyPrivHandler.h
- arangod/Agency/State.cpp
- Store to reset at `operator=`
- Clear both key value stores with rebuildDBs
- Fixed all agency std::sto[u]ll to use StringUtils
> correct-funny-fail-rotation-after-compaction-bugfix

- arangod/Agency/AgencyFeature.cpp
- arangod/Agency/Agent.cpp
should really be done in the thread lib but that is a bit risky so
shortly before the release
> Carrotfix to only stop inception thread if it has been started

- arangod/V8Server/V8DealerFeature.cpp
otherwise there may be issues when v8 code is still running that refers to authentication features
> make the V8 feature depend on the authentication feature

- arangod/MMFiles/MMFilesCollection.cpp
- arangod/MMFiles/MMFilesCollection.h
- arangod/MMFiles/MMFilesLogfileManager.cpp
- arangod/MMFiles/MMFilesWalRecoveryFeature.cpp
- arangod/RestServer/DatabaseFeature.cpp
- arangod/RestServer/DatabaseFeature.h
- arangod/RocksDBEngine/RocksDBCounterManager.cpp
- arangod/RocksDBEngine/RocksDBCounterManager.h
- arangod/RocksDBEngine/RocksDBEngine.cpp
This patch slightly simplifies the `recoveryDone()` API and makes responsibility a bit clearer.
It also implements the call to `recoveryDone()` from within the RocksDB engine.
> slightly move responsibility for recovery

- CHANGELOG
- arangod/VocBase/RevisionCacheChunk.cpp
- arangod/VocBase/RevisionCacheChunk.h
going on will remove not all revisions from the revisions map, so they will still point to the chunk that is about to be removed
> do not go on happily in case of OOM but abort the operation

- arangod/RestServer/FeatureCacheFeature.cpp
- arangod/RestServer/FeatureCacheFeature.h
- lib/ApplicationFeatures/ApplicationServer.cpp
Call beginShutdown() for all started features when there is a hard shutdown
> improve shutdown and feature reusability in tests

- js/client/tests/authentication/user-access-right-foxx-spec.js
In irregular intervals we get `ArangoError: service files missing`, this is a workaround
```
[FAIL] register a foxx service
ArangoError: service files missing
Mount: /UnitTest_ro_rw_rw_mount
at Object.exports.checkRequestResult (js/client/modules/@arangodb/arangosh.js:96:21)
at Object.install (js/client/modules/@arangodb/foxx/manager.js:281:12)
at Context.it (js/client/tests/authentication/user-access-right-foxx-spec.js:105:27)
```
> Fixing occasional foxx errors

- CHANGELOG
- arangod/Agency/Store.cpp
also added asserts for that the mutex is actually held everywhere where it is required
> used the required mutex in Store::clear to avoid races

- js/client/modules/@arangodb/process-utils.js
The pull request was recated because tests fail to find the arangobench executable.
```
it: feature/js_to_cpp_transaction_handler $=
»  bash -x ./scripts/unittest all
+ export PID=17621
+ PID=17621
+ export GLIBCXX_FORCE_NEW=1
+ GLIBCXX_FORCE_NEW=1
+ test -n ''
+ export EXT=
+ EXT=
+ PS=/
++ expr 1024 + 15271
+ export PORT=16295
+ PORT=16295
+ NUMA=
++ which numactl
+ NUMA='numactl --interleave=all'
+ '[' -z '' ']'
+ '[' -x build/bin/arangosh ']'
+ ARANGOSH=build/bin/arangosh
+ declare -a EXTRA_ARGS
++ uname -s
+ '[' Linux == Darwin ']'
++++ readlink -m ./scripts/unittest
+++ dirname /mnt/c9/jan/arangodb2/scripts/unittest
++ dirname /mnt/c9/jan/arangodb2/scripts
+ EXEC_PATH=/mnt/c9/jan/arangodb2
+ '[' -x build/bin/arangosh ']'
++ readlink -m build/bin/arangosh
+ …
```
> fix building with relative paths

- js/actions/_admin/foxx/app.js
- js/apps/system/_admin/aardvark/APP/foxxes.js
fixed the following error when installing a foxx service via github
`via InternalServerError: Could not connect to 'http+ssl://github.comarangodb-foxx:443' 'getaddrinfo for host 'github.comarangodb-foxx': nodename nor servname provided, or not known'`
> Fix foxx github url

- Documentation/Books/build.sh
fix cookbook being an old version
> remove directory first, so we don't copy it into a sub directory

- arangosh/Import/ImportFeature.cpp
- arangosh/Import/ImportHelper.cpp
- arangosh/Import/SenderThread.cpp
- When arangoimp has parsed the input file already, errors from the `arangod` server are not reported to the user anymore
- Arangoimp does not properly wait for all sender threads to finish, if the _hasError path is set too early
> Fixing error reporting in arangoimp

- arangod/Cluster/ClusterMethods.cpp
It used the internally optimized function to extract _key values, which fails on Compact objects
> Fixed ModifyDocument on coordinator.

- js/client/modules/@arangodb/process-utils.js
- add retry for cleanup when deleting of directory fails
- if we fail 5 times, let the final cleanup handle it.
> Work around windows processes not releasing resources

- arangod/Agency/Agent.cpp
- arangod/Agency/Compactor.cpp
- arangod/Agency/Compactor.h
This fixes a possible deadlock between the compactor thread and the agent thread. Furthermore, the agent main thread now waits for all its agency subthreads to terminate at shutdown.
> Bug fix/agency compactor deadlock

- arangod/Agency/AgencyFeature.cpp
- arangod/Agency/Supervision.cpp
- arangod/Cluster/ClusterFeature.cpp
- arangod/Cluster/ServerState.cpp
- arangod/Cluster/ServerState.h
- arangod/RestHandler/RestVersionHandler.cpp
This is a mechanism to detect the host an `arangod` instance is running on, even if it has been started in a container. This is used to ensure data locality with the `arangosync` tool.
> Add host id detection and show in /_admin/cluster/Health.

- CHANGELOG
- arangod/V8Server/V8DealerFeature.cpp
- arangod/V8Server/V8DealerFeature.h
this is required to ensure the console gets one dedicated V8 context and all other
operations have at least one extra context. This requirement was not enforced
anymore.
> minimum number of V8 contexts in console mode must be 2, not 1

- arangod/RestServer/InitDatabaseFeature.cpp
- arangod/RestServer/UpgradeFeature.cpp
- make sure the question is only output after log messages are sent to the console
- make sure error messages are sent before re-quoting for the next try
- inform the user whether the password has been sent
> Fix the password dialog

- Installation/Pipeline/Jenkinsfile.groovy
Fixes the groovy jenkins file to default checkout 3.3 enterprise of no special branch exists.
> Bug fix/jenkins ee checkout 3.3

- arangod/Agency/Agent.cpp
- arangod/Agency/Agent.h
- arangod/Agency/State.cpp
Fixing holes in State.
When an Agent takes over lead, we need to make sure that we do not start with index 0 with sendAppendEntries but with first uncompacted one.
> Bug fix/agency restart after compaction and holes in log

- CHANGELOG
- lib/Logger/Logger.cpp
this requires `--log.line-number` option to be set to true
> show function name in log output

- arangod/MMFiles/MMFilesEngine.cpp
- arangod/MMFiles/MMFilesEngine.h
- arangod/RestHandler/RestReplicationHandler.cpp
- arangod/RocksDBEngine/RocksDBEngine.h
- arangod/StorageEngine/StorageEngine.h
- arangod/Transaction/Methods.cpp
- We wrongly overwrote the original tick-based `waitForSync` method in mmfiles
- This reverses this mistake by adding `waitForSyncTick`
- Add another storage engine method for a timeout based `waitForSyncTimeout`
> Fixed wait for sync in mmfiles

- 3rdParty/rocksdb/v5.6.X/env/io_posix.cc
this is consistent with facebook PR 2573: https://github.com/facebook/rocksdb/pull/2573
Fadvise() is a wrapper function for posix_fadvise().  It is only useful on Linux platforms.  The Fadvise() call was suggesting to the operating system that all cached data for the open file should be flushed.  When used with WAL tailing, this was causing all reads of WAL files to read from disk not from cache.  This was a performance hit for various ArangoDB activities that use the WAL tailing feature.
Issue was first spotted by @darkfrog26 and reported here:  https://github.com/arangodb/arangodb/issues/3291
> removed posix_fadvise call from PosixSequentialFile::Read().

- arangod/Agency/Supervision.cpp
- arangod/Cluster/HeartbeatThread.cpp
This is a bug-fix where on coordinator crash any other coordinator tries to become the new Foxx-Master.
As it is a highlander position only one of them will succeed.
The Supervision is responsible to remove a FoxxMaster if it is killed in action
> Reactivated the failover of the FoxxMaster

- arangod/Agency/State.cpp
Term is a number not a string in snapshots.
> Fix AGENCY_DUMP when a compaction snapshot is present.

- arangod/Agency/State.cpp
Term is a number not a string.
> Port fix of AGENCY_DUMP to 3.2

- Installation/Pipeline/Jenkinsfile.groovy
- Installation/Pipeline/Jenkinsfile.groovy.in
Let jenkins remove the build folder archive after it has been snyced over to/from the cache.
This a small step to reduce file-size usage on our jenkins.
@fceller we need to wait and validate if the jenkins-pipeline succeeds with this modification.
> Let jenkins remove the build folder archive locally

- arangod/MMFiles/MMFilesRestReplicationHandler.cpp
- arangod/Replication/Syncer.cpp
- arangod/RocksDBEngine/RocksDBReplicationTailing.cpp
- arangod/RocksDBEngine/RocksDBWalAccess.cpp
- arangod/StorageEngine/WalAccess.cpp
Should fix sporadic asserts in 3.2 as well, once we backport it
> Removing unsafe asserts in wal tailing v3.3

- arangod/Agency/AgencyComm.cpp
- Crashes nastily if you use an invalid port
> Handle invalid endpoints in AgencyComm

- Documentation/Books/AQL/Fundamentals/DataTypes.md
String was opened by `'` and should be closed with `'` not `"`.
> Fix endquote of example string literal.

- tests/Cluster/ShardDistributionReporterTest.cpp
Replaced usleep by this_thread::sleep_for as usleep can return to early letting the test fail
> Windows USleep Bugfix 3.2

- tests/Cluster/ShardDistributionReporterTest.cpp
Replaced usleep by this_thread::sleep_for as usleep can return to eary letting the test fail
> Randomly failing windows catch test fix

- arangod/RocksDBEngine/RocksDBThrottle.cpp
Add defensive coding and logging in response to a divide by zero. ColumnFamilyData::RecalculateWriteStallConditions() called SetBytePerSecond() with a zero. This caused a divide by zero.
Could have been a race condition due to our SetThrottle() called without db mutex. No proof, just likely.
Race would be due "needed_delay" being set early in RecalculateWriteStallConditions() and write_controller's actual write delay being zero (forced to one), by the time write delay read.
> Defend against a divide by zero (3.3 version)

- lib/ApplicationFeatures/ShellColorsFeature.cpp
Fix for #3753 
Confirmed to work on latest Windows 10 as well.
> Fix for missing constant in older Windows versions (issue 3742)

- Documentation/Books/AQL/CommonErrors.md
- Documentation/Books/AQL/Functions/Array.md
- Documentation/Books/AQL/Functions/Geo.md
- Documentation/Books/AQL/Functions/String.md
- Documentation/Books/AQL/Graphs/Traversals.md
- Documentation/Books/AQL/styles/website.css
- Documentation/Books/Cookbook/styles/website.css
- Documentation/Books/HTTP/styles/website.css
- Documentation/Books/Manual/Administration/Configuration/README.md
- Documentation/Books/Manual/Architecture/StorageEngines.md
- Documentation/Books/Manual/GettingStarted/README.md
- Documentation/Books/Manual/styles/website.css
* Add WITH to graph traversal syntax
* State clearer what where whitespace is ignored in conf files
* Add cross-references between POSITION() and CONTAINS()
* Mention GeoJSON in the description of the useLonLat option
* Troubleshooting: unexpected long running queries
Add remark that collection literals are inferior to FOR constructs and should not be used accidentally instead of variable names
* Add storage engine comparison table, replace hint to note that users might want to pick RocksDB for an installation
* CSS: No margin extra margin after last paragraph in callouts / hint boxes
> Minor documentation changes, part 1 (from devel, squashed)

- arangod/RocksDBEngine/RocksDBThrottle.cpp
Add defensive coding and logging in response to a divide by zero.  ColumnFamilyData::RecalculateWriteStallConditions() called SetBytePerSecond() with a zero.  This caused a divide by zero.  
Could have been a race condition due to our SetThrottle() called without db mutex.  No proof, just likely.
Race would be due "needed_delay" being set early in RecalculateWriteStallConditions() and write_controller's actual write delay being zero (forced to one), by the time write delay read.
> Defend against a divide by zero

- arangod/Cluster/ClusterComm.cpp
- arangod/Statistics/StatisticsFeature.cpp
- arangod/Statistics/StatisticsFeature.h
- arangod/Statistics/StatisticsWorker.cpp
- arangod/Statistics/StatisticsWorker.h
- arangod/V8Server/v8-collection.cpp
This branch tidies up the statistics a bit.
* re-use VelocyPack builders in order to save memory allocations (statistics thread will be invoked very often while the server is running)
* put the AQL queries that are executed by the statistics thread into const static strings, so they can be reused and do not need to be rebuild every time the statistics thread is invoked
* increase the statistics calculation interval from 1 second to the 3.2/3.3 value of 10 seconds
* make statistics garbage collection less intrusive, but more evenly spread its work across multiple invocations
* also add try...catch around the thread main loop, because a thread should not be left with an exception (and if an exception happens, it should resume its work later)
* change statistics values from floats to double, …
> Bug fix/tidy up statistics

- lib/Logger/Logger.cpp
For example, the following log level now does not cause a warning anymore
v8 = trace
previously the log levels had to be specified without any whitespace around
> allow specification of log topics with whitespace in the argument

- UnitTests/unittest.js
so we can see it in the oversight of the jenkins job.
> if catch ran, and crashed emmit that to the xml file 

- .gitattributes
The files `VERSION` and `Installation\Pipeline\Jenkinsfile.groovy` keep showing as modified for me in Git under Windows.
Git converts the line endings to CRLF in the working copy, but shouldn't see this as a change - yet it does. 
This should circumvent this problem without touching the global git settings.
> Bug fix/git enforce more lf line endings

- Documentation/Books/Manual/ReleaseNotes/NewFeatures33.md
Until we have proper docs about automatic failover, point to blog article.
> Add link to sub-headline of blog post temporarily

- arangod/Agency/AgencyComm.cpp
- arangod/Cluster/ClusterInfo.cpp
Have twice seen coordinator go into long loop on shutdown.  Added two tests for isStopping() to break the loops.
Both loops were part of ClusterInfo::ensureIndexCoordinator()'s call tree.  First is in AgencyComm::sendWithFailover().  It would loop for 50 seconds.  Second is within ClusterInfor::ensureIndexCoordinatorWithoutRollback() which would retry if lower layers failed.  Combined, the two retry loops could delay coordinator stop by 10 minutes or more.
The changes also help coordinators stop slightly quicker even when not caught in the ensureIndexCoordinator() retry operations.
> Break retry loops on shutdown

- arangod/Agency/AgencyComm.cpp
- arangod/Cluster/ClusterInfo.cpp
Have twice seen coordinator go into long loop on shutdown. Added two tests for isStopping() to break the loops.
Both loops were part of ClusterInfo::ensureIndexCoordinator()'s call tree. First is in AgencyComm::sendWithFailover(). It would loop for 50 seconds. Second is within ClusterInfor::ensureIndexCoordinatorWithoutRollback() which would retry if lower layers failed. Combined, the two retry loops could delay coordinator stop by 10 minutes or more.
The changes also help coordinators stop slightly quicker even when not caught in the ensureIndexCoordinator() retry operations.
> Bug fix 3.3:  Break retry loops on shutdown

- arangod/Agency/AgencyComm.cpp
- arangod/Cluster/ClusterInfo.cpp
Have twice seen coordinator go into long loop on shutdown. Added two tests for isStopping() to break the loops.
Both loops were part of ClusterInfo::ensureIndexCoordinator()'s call tree. First is in AgencyComm::sendWithFailover(). It would loop for 50 seconds. Second is within ClusterInfor::ensureIndexCoordinatorWithoutRollback() which would retry if lower layers failed. Combined, the two retry loops could delay coordinator stop by 10 minutes or more.
The changes also help coordinators stop slightly quicker even when not caught in the ensureIndexCoordinator() retry operations.
> Bug fix 3.2:  Break retry loops on shutdown

- arangod/Agency/Supervision.cpp
There exists a race condition where the leader agent could begin health checks before a server has sent its "short name" in a message that is asynchronous to its heartbeat message.  This would cause Node.cpp to throw and Supervisor thread would not catch.  Therefore Supervisor thread terminated.
Code contains two fixes relating to same scenario:
1.  Explicitly check if short name exists for a server.  If not, simply log a message and continue to other servers.
2. Add try/catch around call to Supervisor::doChecks() to catch any future throws that crop up.  Log the throws but keep Supervisor thread operational.
> Fix supervisor thread crash

- arangod/Agency/Supervision.cpp
From PR 4083 for devel:  
There exists a race condition where the leader agent could begin health checks before a server has sent its "short name" in a message that is asynchronous to its heartbeat message. This would cause Node.cpp to throw and Supervisor thread would not catch. Therefore Supervisor thread terminated.
Code contains two fixes relating to same scenario:
Explicitly check if short name exists for a server. If not, simply log a message and continue to other servers.
Add try/catch around call to Supervisor::doChecks() to catch any future throws that crop up. Log the throws but keep Supervisor thread operational.
> Bug fix 3.2:  Fix supervisor thread crash

- arangod/CMakeLists.txt
- arangod/Cluster/ClusterFeature.cpp
- arangod/Cluster/ClusterFeature.h
- arangod/Cluster/ReplicationTimeoutFeature.cpp
- arangod/Cluster/ReplicationTimeoutFeature.h
- arangod/MMFiles/MMFilesEngine.h
- arangod/RestServer/arangod.cpp
- arangod/RocksDBEngine/RocksDBEngine.h
- arangod/StorageEngine/StorageEngine.h
- arangod/Transaction/Methods.cpp
- arangod/Transaction/Methods.h
From PR 3996 on devel:
chooseTimeout() was setting the timeout too low for ClusterComm::processRequests() when data size was 500K. This update adds 100ms of timeout per 4096 of data body. So the routine now dynamically responds to message size.
The function is now chooseTimeout(size_t count, size_t total_bytes). A new hidden option variable exists call cluster.synchronous-replication-timeout-per-4k. This allows the default 100ms (0.1 seconds) to be changed at start-up.
The total_bytes parameter contains the sum of all messages in this batch. This assumes there might be shared resources along the communication and/or destination database path that have to process all the bytes, not just one message's data.
> Bug fix 3.3:  Make chooseTimeout() dynamic

- arangod/Agency/Supervision.cpp
From PR 4083 for devel:
There exists a race condition where the leader agent could begin health checks before a server has sent its "short name" in a message that is asynchronous to its heartbeat message. This would cause Node.cpp to throw and Supervisor thread would not catch. Therefore Supervisor thread terminated.
Code contains two fixes relating to same scenario:
Explicitly check if short name exists for a server. If not, simply log a message and continue to other servers.
Add try/catch around call to Supervisor::doChecks() to catch any future throws that crop up. Log the throws but keep Supervisor thread operational.
> Bug fix 3.3: Fix supervisor thread crash

- arangod/Agency/Agent.cpp
- arangod/Agency/Agent.h
- arangod/Agency/RestAgencyHandler.cpp
- arangod/Agency/Supervision.cpp
This PR replaces Agent::executeLocked() with the pair executeLockedRead() and executeLockedWrite().  There are no users of executeLockedWrite() at this time.  Provided as an example lock management for future code.  executeLockedRead() uses the read only lock for the readDB to enhance parallel performance.  The _ioLock is still held exclusively during this call.
> Create read only version of executeLocked

- arangod/Agency/Agent.cpp
- arangod/Agency/Agent.h
- arangod/Agency/RestAgencyHandler.cpp
- arangod/Agency/Supervision.cpp
from PR 4177 on devel:
This PR replaces Agent::executeLocked() with the pair executeLockedRead() and executeLockedWrite(). There are no users of executeLockedWrite() at this time. Provided as an example lock management for future code. executeLockedRead() uses the read only lock for the readDB to enhance parallel performance. The _ioLock is still held exclusively during this call.
> Bug fix 3.3:  Create read only version of executeLocked

- arangod/CMakeLists.txt
- arangod/Cluster/ClusterFeature.cpp
- arangod/Cluster/ClusterFeature.h
- arangod/Cluster/ReplicationTimeoutFeature.cpp
- arangod/Cluster/ReplicationTimeoutFeature.h
- arangod/MMFiles/MMFilesEngine.h
- arangod/RestServer/arangod.cpp
- arangod/RocksDBEngine/RocksDBEngine.h
- arangod/StorageEngine/StorageEngine.h
- arangod/Transaction/Methods.cpp
- arangod/Transaction/Methods.h
from PR 3996 on devel:
chooseTimeout() was setting the timeout too low for ClusterComm::processRequests() when data size was 500K. This update adds 100ms of timeout per 4096 of data body. So the routine now dynamically responds to message size.
The function is now chooseTimeout(size_t count, size_t total_bytes). A new hidden option variable exists call cluster.synchronous-replication-timeout-per-4k. This allows the default 100ms (0.1 seconds) to be changed at start-up.
The total_bytes parameter contains the sum of all messages in this batch. This assumes there might be shared resources along the communication and/or destination database path that have to process all the bytes, not just one message's data.
> Bug fix 3.2:  Make chooseTimeout() dynamic

- lib/SimpleHttpClient/Communicator.cpp
From PR 3866 on devel & 3.3:
Communicator::HandleResult() was returning an error message upon connection timeout that forced ClusterCommResult::fromError() to assume sendWasComplete should be marked true. This created a mild logging error during Agency gossip. But real fear is that some yet to be identified operation might assume the server received a message when in fact the server was not available.
CURL_OPERATION_TIMEOUT appears to be used both for connection timeout and overall operation timeout (such as awaiting a response). Added code detects the difference by retrieving the total time of connection. If zero, the connection never happened.
> Bug Fix 3.2:  connection timeout treated as "send complete"

- arangod/MMFiles/MMFilesCollectorThread.cpp
- arangod/MMFiles/MMFilesLogfileManager.cpp
- arangod/MMFiles/MMFilesWalLogfile.h
- js/server/tests/recovery/documents.js
- js/server/tests/recovery/many-documents.js
I just found that in latest devel the WAL recovery for MMFiles does not always take place as expected. It seems to happen in some situations only.
I have added two recovery tests that should demonstrate the problem. In order to reproduce it, undo the `#if 0` change I made in `MMFilesWalLogfile.h` in this PR. Everything should work fine with the `#if 0` in place, but without it I sometimes do not see the WAL file recovery actually working after restart. So data that was in the WAL before shutdown does not make it in the collections after restart.
Run the recovery tests as follows: `scripts/unittest recovery --test documents.js`
For me at least one of the tests fails if the `#if 0` code part is changed back.
This needs proper investigation, and it needs a proper fix. The `#if 0` will …
> temporarily break flush thread feature in order to prevent some loss

- CHANGELOG
- Documentation/Books/Manual/Foxx/Configuration.md
- Documentation/Books/Manual/Foxx/Dependencies.md
- js/server/modules/@arangodb/foxx/manifest.js
Via #3818.
This does not change the current behaviour of Foxx but logs warnings so we can deprecate troublesome names/keys in the future. It also documents the expected constraints that were previously not clearly defined anywhere.
> Warn about Foxx manifest names

- CMakeLists.txt
- Installation/Jenkins/build.sh
We need this in order to not have misleading versions on nightly builds from stable branches.
> use --forceVersionNightly to set the bugfix part of the version to 'nightly'

- Installation/Jenkins/build.sh
- enable CATCH tests explicitely, for some reason this doesn't happen anymore
- don't copy dlls manually anymore, the install process does this for us.
> Fix windows packaging

- Installation/Pipeline/Jenkinsfile.groovy
- Installation/Pipeline/Jenkinsfile.groovy.in
Fixed a type in VariableName of the pipeline script. This caused the Script to be unable to build custom combinations.
> Jenkins Pipeline Fix Undefined Variable

- js/apps/system/_api/foxx/APP/index.js
- js/server/modules/@arangodb/foxx/service.js
Having the option to get the same response format from the get/put/patch routes reduces the overhead for tools like foxx-cli. This should be backported to 3.2 and 3.1 after merging.
> More consistent config/deps output in Foxx API (devel)

- CHANGELOG
- arangod/Aql/Ast.cpp
- js/server/tests/aql/aql-queries-optimizer.js
AQL optimizer was trying to resolve attribute accesses
to attributes of constant object values at query compile time, but only did so far
the very first attribute in each object
this fixes https://stackoverflow.com/questions/48648737/beginner-bug-in-for-loops-from-objects
> fix internal issue #1848

- Documentation/Books/Manual/Graphs/README.md
- Documentation/Books/Manual/README.md
- Documentation/Books/Manual/ReleaseNotes/KnownIssues32.md
- Documentation/Books/Manual/ReleaseNotes/NewFeatures24.md
- Documentation/Books/Manual/ReleaseNotes/NewFeatures26.md
- Documentation/Books/Manual/ReleaseNotes/UpgradingChanges27.md
- Documentation/Books/Manual/ReleaseNotes/UpgradingChanges30.md
Fixes #4505 - Broken links to 2.8 -> 3.0 migration guides in release notes
> Docs: Use relative links for cross references

- arangod/RocksDBEngine/RocksDBCuckooIndexEstimator.h
Changes in previous PR to avoid rescanning entire table each time we needed to compute the estimate led to incorrect estimates in some cases where we did cuckooing. This produced failing replication tests at the very least, and snuck in to devel. This PR fixes the bookkeeping so we get correct estimates and don't have to do the table scanning.
> Fix selectivity computation.

- arangod/RestHandler/RestAqlUserFunctionsHandler.cpp
- arangod/VocBase/Methods/AqlUserFunctions.cpp
- lib/Basics/StaticStrings.cpp
- lib/Basics/StaticStrings.h
do allow input to /_api/aqlfunction choose between
/_api/aqlfunction/<name> (new style)
and
/_api/aqlfunction?prefix=... (old style)
This provides more downwards-compatibility to existing API clients
Additionally look for "prefix" URL parameter as this used to be
the parameter we communicated for earlier versions of ArangoDB.
> do allow input to /_api/aqlfunction choose between

- Installation/logrotate.d/arangod.systemd
- cmake/ArangoDBInstall.cmake
- cmake/packages/deb.cmake
- cmake/packages/packages.cmake
- we have to be able to configure a usergroup per distro target.
ArangoDBInstall is invoked before the distro specific stuff.
-> moving install into packages.cmake
- default to the user group of the file to be "arangodb"
- on debian systems logfiles are written with the "adm" group - overriding the default.
- fix the name of the service for enterprise packages
> Fix logrotate configuration

- arangod/RocksDBEngine/RocksDBTransactionCollection.cpp
- arangod/VocBase/Methods/Transactions.cpp
- lib/V8/v8-vpack.cpp
- lib/V8/v8-vpack.h
previously this did not work when the "action" attribute was a JavaScript function
> properly convert the JS object to VPack for transactions

- Documentation/Scripts/codeBlockReader.py
We must keep newlines when copying the markdown blocks into the documentation; else it will destroy the structure of documents.
fixes #4716
> fix codeblock reader - keep newlines

- lib/Basics/operating-system.h
http://man7.org/linux/man-pages/man3/usleep.3.html - why we did the internal define instead of using the documented define for user code - no clue.
> remove remaining defines of our old usleep usage - 

- Documentation/Books/build.sh
This way, it will be called on full builds as well as single book builds
> Move execution of codeBlockReader.py to build-book()

- Documentation/Books/build.sh
This way, it will be called on full builds as well as single book builds
> [3.1] Move execution of codeBlockReader.py to build-book()

- Documentation/Books/build.sh
This way, it will be called on full builds as well as single book builds
> [3.0] Move execution of codeBlockReader.py to build-book()

- 3rdParty/CMakeLists.txt
- 3rdParty/V8/CMakeLists.txt
- 3rdParty/V8/v5.7.492.77/src/isolate.h
- Installation/Jenkins/build.sh
- fix distribution of ICU library dirs, respect DRY.
- comment out assertion for fetching of Isolate - we use this to test
whether there are one (as documented) thus this is not a mistake
- add switch to build v8 + icu debug enabled.
> Fix building V8 with debug mode

- CHANGELOG
- arangod/Cluster/ClusterFeature.cpp
- arangod/Cluster/ClusterFeature.h
- arangod/RestHandler/RestReplicationHandler.cpp
- arangod/VocBase/Methods/Indexes.cpp
I actually did not fix it by adding (yet another) startup option, but by increasing the default timeout for index creation. The adjusted timeout (3600s) is now in line with the timeout used for index creation that was used already when restoring an index from a dump (3600s).
> increase timeout for index creation

- Documentation/Books/HTTP/AdministrationAndMonitoring/README.md
- Documentation/DocuBlocks/Rest/Cluster/get_cluster_health.md
This is a backport of documentation/cluster-health-api (https://github.com/arangodb/arangodb/pull/4834) to 3.3
> Doc- backport cluster health API documentation

- js/client/modules/@arangodb/testsuites/rspec.js
> Windows should now use rspec.bat by default. No stunts with handed in ruby and rspec foo required but still possible.

- Documentation/Books/AQL/Invocation/WithArangosh.md
- Documentation/Books/Manual/Appendix/References/CollectionObject.md
- Documentation/Books/Manual/Appendix/References/DBObject.md
- Documentation/Books/Manual/DataModeling/Collections/README.md
- Documentation/Books/Manual/DataModeling/Databases/WorkingWith.md
- js/client/modules/@arangodb/arango-collection.js
- js/client/modules/@arangodb/arango-database.js
*url() methods are probably internal and should be ignored.
Missing:
- coll.shards(): cluster only
- more?
Open questions:
- what about deprecated methods?
- ensureGeoConstraint only prints an error that tells to use ensureGeoIndex / ensureIndex
- Other geo-related methods are superseeded by AQL queries
- what about some other oddball methods?
- db._id(): where is this actually used?
- _help(): does this work in Foxx too? It nothing but a string meant for arangosh however
- _flushCache(), _refresh(): are these internal?
> Doc - Add some missing db and collection methods

- Documentation/Books/Manual/Graphs/README.md
- Documentation/Books/Manual/README.md
- Documentation/Books/Manual/ReleaseNotes/KnownIssues32.md
- Documentation/Books/Manual/ReleaseNotes/NewFeatures24.md
- Documentation/Books/Manual/ReleaseNotes/NewFeatures26.md
- Documentation/Books/Manual/ReleaseNotes/UpgradingChanges27.md
- Documentation/Books/Manual/ReleaseNotes/UpgradingChanges30.md
Port of #4520 to devel
Found two typos in top readme, will port them back to 3.3.
> Docs - Use relative links for cross references

- Documentation/Books/Manual/Architecture/WriteAheadLog.md
Backporting the latest changes Simon did on devel. Just copying and pasting the doc file from devel to here
The original changes from Simon were originally pushed into documentation/replication-refactor, and then merged on devel. Not able to cherry pick as that commit included other things
Can be merged imho
Internal Ref: https://github.com/arangodb/planning/issues/1880
> Doc - WAL: MMFile / RocksDB distinction

- Documentation/Examples/10_workWithAQL_debugging1.generated
- Documentation/Examples/10_workWithAQL_debugging2.generated
- Documentation/Examples/10_workWithAQL_debugging3.generated
add missing examples that are required to build the documentation
> add missing generated examples

- js/apps/system/_admin/aardvark/APP/foxxes.js
>  Don't log stacktrace when fishbowl update fails (3.3)

- Documentation/Books/Manual/Foxx/GraphQL.md
>  Mention graphql-js 0.12 in Foxx GraphQL docs (3.2)

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
ui query editor now has the same behavior as java driver while parsing a queries bind parameters
> same behavior as java driver while parsing a queries bind parameters

- Installation/MacOSX/Bundle/arangodb-cli.sh.in
- scripts/build-bundle.sh
fixed a bug when e.g a 3.2 version wants to upgrade to a 3.3 version. This action failed with the first attempt (start application once). The second start then worked. This wrong behaviour is fixed with that PR.
> Bug fix 3.3/mac os build bundle update failure

- arangod/Scheduler/SocketTask.cpp
A profiling run with VTune showed that a lot of time is spent to acquire the lock in line 153 in `SocketTask::addWriteBuffer`. When the task is created and added to the job queue, a potentially waiting SchedulerThread immediately gets notified and starts executing the task - and immediately gets blocked when trying to aqcuire the lock, because the lock is actually held by the thread that created the task.
As far as I could see it is not necessary to create these tasks to execute `processAll` since `SocketTask::asyncReadSome` (which initially acquires that lock) implicitly calls `processAll` anyway (my tests all worked fine), but someone who is more familiar with this code should doublecheck this.
During the profiling run I just executed a bunch of requests using `arangobench` on my 4-core …
> Do not create superfluous task to run processAll.

- Documentation/Books/Manual/Foxx/GraphQL.md
>  Mention graphql-js 0.12 in Foxx GraphQL docs (3.3)

- README.md
Backport of https://github.com/arangodb/arangodb/commit/03fe0fdcb44e0cd8c6d58dc21866906373528a11
We don't care much about 3.1 and older, so not going to backport it further
> remove travis as compiling takes too long

- CHANGELOG
- js/common/bootstrap/modules.js
- js/common/tests/shell/shell-locals-spec.js
Extending Node's module object in TS is tricky so let's provide a fake module for compatibility.
This allows writing the following:
```typescript
import { createRouter } from "@arangodb/foxx";
import { context } from "@arangodb/locals";
const router = createRouter();
context.use(router);
```
instead of
```typescript
import { createRouter } from "@arangodb/foxx";
const context = (module as Foxx.Module).context;
const router = createRouter();
context.use(router);
```
or without typings
```typescript
import { createRouter } from "@arangodb/foxx";
const context = (module as any).context;
const router = createRouter();
context.use(router);
```
This should probably be backported to 3.3 and 3.2 if it passes review.
> Add @arangodb/locals module

- CHANGELOG
- js/server/modules/@arangodb/foxx/manifest.js
- js/server/tests/shell/shell-foxx-manifest-spec.js
This PR adds support for specifying a $schema value in the Foxx service manifest.
Foxx will now warn about (but ignore) invalid $schema values and default to the canonical JSON schema hosted at http://json.schemastore.org/foxx-manifest -- this aids tool based validation.
> Allow specifying Foxx manifest.json $schema value

- js/apps/system/_admin/aardvark/APP/aardvark.js
- js/apps/system/_admin/aardvark/APP/frontend/js/arango/arango.js
- js/apps/system/_admin/aardvark/APP/frontend/js/templates/queryView.ejs
- js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
- js/common/modules/@arangodb/aql/explainer.js
* Adeded a route to aardvark to export a debug dump, it can optinally contain anonymized example data
* Added the Download Debug Button to UI
* fixed zip file download of query dump file
* removed not needed vars
* Added JWT token authentication and error display on debug dump button
* Fixed Error reporting on download debug dump.
* Anonymization does not anonymize system attributes any more.
* Anonymize in explainer debugDump will now anonymize bindVars and will not anonymize system document attributes.
> Feature/debugdump ui (#5187)

- .gitattributes
- Documentation/Examples/.gitattributes
- README_maintainers.md
This switches the swagger json merge strategy to 'ours';
As pointed out here, one needs to define that 'ours'-merge driver:
https://medium.com/@porteneuve/how-to-make-git-preserve-specific-files-while-merging-18c92343826b
It will always prefer your version over the devel version.
> set merge strategy to binary for autogenerated files

- CHANGELOG
- arangod/Cluster/HeartbeatThread.cpp
- arangod/Cluster/HeartbeatThread.h
Isolated scenario where a background task of handlePlanChange could take a long time executing, then cause and a potentially infinite executions of the same task.  Two changes:
1.  fix infinite loop by setting _lastSyncTime within runBackgroundJob()
2. change 1 could potential block quick response to an agency notification of plan change, so added code to make agency callback ignore _lastSyncTime limit.
> correct race condition leading to infinite job execution

- arangod/GeneralServer/AuthenticationFeature.cpp
- arangod/RestServer/CheckVersionFeature.cpp
- arangod/RestServer/CheckVersionFeature.h
- arangod/RestServer/LockfileFeature.cpp
- arangod/RestServer/LockfileFeature.h
- arangod/V8Server/V8DealerFeature.cpp
Fixed undefined behaviour when starting arangodb with --database.check-version true as done by our scripts.
This bug was never part of any official release so no need to bother for any installation out there.
> fixes database.check-version

- js/common/bootstrap/errors.js
- js/common/modules/@arangodb/general-graph.js
- lib/Basics/errors.dat
- lib/Basics/voc-errors.cpp
- lib/Basics/voc-errors.h
- utils/generateErrorfile.py
Removed `ERROR_ARANGO_COLLECTION_NOT_FOUND` and added it as an alias for `ERROR_ARANGO_DATA_SOURCE_NOT_FOUND` in JS for backwards compatibility.
> Removed ERROR_ARANGO_COLLECTION_NOT_FOUND

- CHANGELOG
- Documentation/Books/Manual/Administration/Arangoimport.md
- arangod/Cluster/HeartbeatThread.cpp
- arangosh/CMakeLists.txt
- arangosh/Import/AutoTuneThread.cpp
- arangosh/Import/AutoTuneThread.h
- arangosh/Import/ImportFeature.cpp
- arangosh/Import/ImportFeature.h
- arangosh/Import/ImportHelper.cpp
- arangosh/Import/ImportHelper.h
- lib/Basics/Thread.cpp
Google Compute and other VM providers limit the throughput of disk devices.  Google's limit is more strict for smaller disk rentals, than for larger.  Specifically, a user could choose the smallest disk space and be limited to 3 Mbytes per second.
Arangodb's import previously defaulted to pushing data in blocks of 3 Mbytes per thread, as often as possible (default of 2 threads).  The data pushed would back-up on the server and result in a TimeoutError.  The TimeoutError is very frustrating to new users.  The users were required to learn how to lower the default block size and default thread count ... and the new parameters would still not be guaranteed to work.
This branch creates a default algorithm that adjusts the block size dynamically based upon the actual throughput of the server …
> Add pacing logic to arangoimp

- js/client/modules/@arangodb/foxx/manager.js
The foxx-cli tool has been released and tested on Windows, Linux and Docker. Accordingly we will now warn users to switch from foxx-manager to foxx-cli starting with ArangoDB 3.4.0 and remove foxx-manager fully in ArangoDB 4.0.
@mpv1989 maybe we should replace the URL with a link to the Foxx CLI docs when they land in the ArangoDB tools documentation? Assuming this happens before 3.4. What do you think of a chapter on switching from foxx-manager to help users transition?
> Deprecate foxx-manager

- CHANGELOG
- Documentation/Books/HTTP/AdministrationAndMonitoring/README.md
- Documentation/DocuBlocks/Rest/Administration/get_admin_server_availability.md
- arangod/GeneralServer/GeneralCommTask.cpp
- arangod/GeneralServer/RestHandlerFactory.cpp
- arangod/RestHandler/RestAdminServerHandler.cpp
- arangod/RestHandler/RestAdminServerHandler.h
This a public API, which can be used without authentication.
It is meant to be used in the context of server monitoring only
> added REST API endpoint GET /_admin/server/availability

- 3rdParty/iresearch/core/analysis/token_attributes.hpp
- 3rdParty/iresearch/core/formats/formats_10.cpp
- 3rdParty/iresearch/core/formats/formats_10_attributes.hpp
- 3rdParty/iresearch/core/index/index_reader.hpp
- 3rdParty/iresearch/core/index/iterators.cpp
- 3rdParty/iresearch/core/index/transaction_store.cpp
- 3rdParty/iresearch/core/iql/query_builder.cpp
- 3rdParty/iresearch/core/search/bm25.hpp
- 3rdParty/iresearch/core/search/boolean_filter.hpp
- 3rdParty/iresearch/core/search/tfidf.hpp
- 3rdParty/iresearch/core/store/data_input.hpp
- 3rdParty/iresearch/core/store/data_output.hpp
- 3rdParty/iresearch/core/store/fs_directory.cpp
- 3rdParty/iresearch/core/store/mmap_directory.hpp
- 3rdParty/iresearch/core/store/store_utils.hpp
- 3rdParty/iresearch/core/utils/fst_matcher.hpp
- 3rdParty/iresearch/core/utils/iterator.hpp
Adds missing override specifiers to a lot of overridden functions.
Reduces compiler warnings.
> add missing override specifiers

- lib/Basics/threads-posix.cpp
- tests/main.cpp
OSX default stack size for threads is at 512k, needs tweaking.
> Bug fix/default stack size on osx too small

- CMakeLists.txt
Use SYSTEM declaration when including asio and ICU, in order to reduce the number of compile warnings.
> remove asio and ICU compile warnings spam

- arangod/Agency/AgencyComm.cpp
- arangod/Cluster/HeartbeatThread.cpp
Agency response for the path `/.agency` looked different from what the code expected, therefore `HeartbeatThread::updateAgentPool` was a no-op:
```
curl http://localhost:4002/_api/agency/read -v --data '[["/arango/Supervision"]]' | jq
[
{
".agency": {
"active": [
"AGNT-8e571095-2bcb-4967-9f8f-8c8897c4c6b7",
"AGNT-b5fc37f0-e677-4445-bb27-0f62ef6c07d8",
"AGNT-362e7e17-d27a-442f-becc-55cd690a0dd7"
],
"timeoutMult": 2,
"id": "AGNT-362e7e17-d27a-442f-becc-55cd690a0dd7",
"pool": {
"AGNT-362e7e17-d27a-442f-becc-55cd690a0dd7": "tcp://[::1]:4002",
"AGNT-8e571095-2bcb-4967-9f8f-8c8897c4c6b7": "tcp://[::1]:4003",
"AGNT-b5fc37f0-e677-4445-bb27-0f62ef6c07d8": "tcp://[::1]:4001"
},
"size": 3,
"term": 2
}
}
```
> Fixing agency pool update

- CHANGELOG
- Documentation/Books/Manual/Administration/Configuration/SSL.md
- arangosh/Shell/ClientFeature.cpp
- lib/SimpleHttpClient/SslClientConnection.cpp
- lib/Ssl/SslServerFeature.cpp
- lib/Ssl/SslServerFeature.h
- lib/Ssl/ssl-helper.cpp
- lib/Ssl/ssl-helper.h
or when connecting with a client tool via an SSLv2 connection.
SSLv2 has been disabled in the OpenSSL library by default in recent versions
because of security vulnerabilities inherent in this protocol.
This also fixes a compile error when having installed a recent
version of OpenSSL on the system which does not provide SSLv2 at all.
> abort startup when using SSLv2 for a server endpoint

- Installation/MacOSX/Bundle/arangodb-cli.sh.in
- scripts/build-bundle.sh
fixed a bug when e.g a 3.2 version wants to upgrade to a 3.3 version. This action failed with the first attempt (start application once). The second start then worked. This wrong behaviour is fixed with that PR.
> Bug fix/mac os build bundle update failure

- arangod/Indexes/Index.cpp
- arangod/RocksDBEngine/RocksDBCollection.cpp
- arangod/Transaction/Methods.cpp
- arangod/VocBase/LogicalCollection.cpp
- arangod/VocBase/LogicalCollection.h
- js/common/tests/shell/shell-collection-rocksdb.js
- js/server/tests/shell/shell-collection-rocksdb-noncluster.js
- abort creation of RocksDBCollection object in case invalid indexes are passed into it
- do not refetch cluster index selectivity estimates in every situation
> Bug fix 3.3/fixes 1805

- Documentation/Books/Cookbook/Compiling/Debian.md
Port from [3.3](https://github.com/arangodb/arangodb/pull/5442) to devel
> Updated paths to fit ArangoDB v3

- js/client/modules/@arangodb/testsuites/readOnly.js
According to the CHANGELOG, the permission resolution has been changed in devel as follows:
The new fallback rule for collections for which an access level is not explicitly specified:
Choose the higher access level of:
* Any wildcard access grant in the same database, or on "*/*"
* The access level for the current database
* The access level for the `_system` database
> fix read-only tests

- arangod/Aql/OptimizerRules.cpp
make optimizer rule "remove-filter-covered-by-index" not stop after removing
a sub-condition from a FILTER statement, but pass the optimized FILTER
statement again into the optimizer rule for further optimizations.
This allows optimizing away some more FILTER conditions than before.
> more eager "remove-filter-covered-by-index" rule

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/views/documentView.js
fixed internal issue https://github.com/arangodb/planning/issues/2256: ui, document id not showing up when deleting a document
> ui, document id not showing up when deleting a document

- js/client/modules/@arangodb/process-utils.js
- js/client/modules/@arangodb/testsuites/catch.js
- js/client/modules/@arangodb/testsuites/config.js
- js/client/modules/@arangodb/testsuites/dfdb.js
- js/client/modules/@arangodb/testsuites/export.js
- js/client/modules/@arangodb/testsuites/recovery.js
- js/client/modules/@arangodb/testsuites/upgrade.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/780/  (failed because of error in linux code branch)
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-windows/65/ [success in terms that the restore tests ran]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/782/ [success]
> disable circumventing of coredumps for windows

- Documentation/DocuBlocks/Rest/AQL/post_api_aqlfunction.md
- UnitTests/HttpInterface/api-aqlfunction-spec.rb
- arangod/RestHandler/RestAqlUserFunctionsHandler.cpp
- arangod/VocBase/Methods/AqlUserFunctions.cpp
- js/client/modules/@arangodb/aql/functions.js
- js/common/tests/shell/shell-aqlfunctions.js
add attribute "isNewlyCreated" to the response
Fixes issue #5629
> make API for POST /_api/aqlfunction downwards-compatible again

- js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
include result with length = 1 to enable table view and csv download for a query with only 1 result
> fix table validation

- Documentation/Books/Cookbook/Compiling/Windows.md
- For compiling ArangoDB version below 3.0, fix the link by pointing to 2.8 documentation.
- Typos
> Doc Fix: typos and modify link

- Documentation/Books/AQL/book.json
- Documentation/Books/Cookbook/book.json
- Documentation/Books/HTTP/book.json
- Documentation/Books/Manual/book.json
VERSION_NUMBER is automatically being substituted with the content of the `VERSION` file in book.json. This PR adds a new configuration field `"version"` with the ArangoDB version (VERSION_NUMBER), e.g. `v3.1.29` or `3.4.devel ...`.
This version string is then used by the [arangodb-outdated](https://github.com/Simran-B/gitbook-plugin-arangodb-outdated) plugin to add a sentence about EOL of v<i>X.X</i>. If no version could be determined (should never be the case), the entire sentence is left out as it would make little sense without a version. The second sentence about the docs being obsolete is shown regardless.
However, the updated plugin replaces the **Latest Manual** link to `https://docs.arangodb.com/latest/<path-the-user-is-looking-at>` with label **Try latest**. If the structure / …
> Docs: EOL note for 3.1

- .gitattributes
This should fix issues under Windows with Cygwin, which requires LF line endings for certain files.
The concrete error when building docs caused by CRLF line ending for file `Documentation/Books/SummaryBlacklist.txt` was:
```
not all files of HTTP are mapped to the summary!
files found       |    files in summary
README.md
SUMMARY.md
```
@dothebart Do we need to add any more rules found in devel `.gitattributes`?
https://github.com/arangodb/arangodb/blob/devel/.gitattributes
Need to check if we need to port this to other branches as well.
> Documentation 3.1/force LF for certain files

- .gitattributes
Force LF line endings for certain files to avoid build errors on Windows in Cygwin
> Update .gitattributes: Force LF line endings

- Documentation/Books/Cookbook/book.json
- Documentation/Books/Users/book.json
Add version field to book.json for arangodb-outdated plugin, add version number to Cookbook
This will add an EOL notice.
> Docs: Add version to Gitbook configs

- ISSUE_TEMPLATE.md
…for better user and support experience
This this really necessary? `Docker - official Docker library`
Can't we simplify that, e.g. to _official Docker image/registry_? (what is a Docker library?)
Preview below:
---
* __ArangoDB Version__: 3.3.10       
* __Storage Engine__: RocksDB            
* __Deployment Mode__: Active Failover      
* __Configuration__: 3 agents              
* __Infrastructure__: AWS              
* __Operating System__: Debian 8       
* __Used Package__: .deb             
__Affected feature__:
arangodump while import script runs in arangosh
__AQL query (if applicable)__:
`db._query("FOR i IN 1..10000 INSERT { val: i } INTO test")`
__AQL explain (if applicable)__:
```
Query string:
FOR i IN 1..10000 INSERT { val: i } INTO test
Id   NodeType …
```
> Use HTML comments and use indention 

- Documentation/Books/Manual/SUMMARY.md
- Documentation/Books/Manual/Troubleshooting/Arangoinspect.md
... without description of all options, because we don't have program options generation stuff in 3.3.
Maybe this is already sufficient? We could also add a handwritten list of the most important options like here: https://docs.arangodb.com/3.3/Manual/Troubleshooting/Arangobench.html#startup-options
Most of the options are from arangosh and have no real relevance for arangoinspect:
https://github.com/arangodb/arangodb/blob/devel/Documentation/Examples/arangoinspect.json
> Copy Arangoinspect docs from devel to 3.3

- Documentation/Books/Cookbook/UseCases/CrawlingGithubPromises.md
- Documentation/Scripts/codeBlockReader.py
backport fixes:
- fixed documentation build script to detect missing endDocuBlock
- remove deprecated link for queue-it [issue 5214](https://github.com/arangodb/arangodb/issues/5214)
> fix documentation build script

- Documentation/Books/Manual/Administration/Configuration/README.md
- Documentation/Books/Manual/Programs/Arangod/Options.md
Add brief description of startup parameter usage to Arangod Options page (which should close the gap between the General Options headline and the table caused by the ToC)
Changed hint regarding whitespace in parameter values in config files - I believe @jsteemann changed this at some point so that whitespace in parameter values does not matter anymore, but I'm not sure if this was shipped in 3.3.0 or later. The following works in 3.3.10 in arangod.conf:
```
[log]
level = info
level	 = 		threads 	     	=     	  trace		   
```
> Docs: Improve program option / startup parameter description

- arangod/Cluster/ClusterComm.cpp
- arangod/Cluster/ClusterComm.h
in ClusterComm::fireAndForgetRequests but use safer accessor methods
> do not dereference potential nullptrs

- CHANGELOG
- Documentation/Books/HTTP/General/README.md
- arangod/GeneralServer/RestHandler.cpp
- lib/Basics/StaticStrings.cpp
- lib/Basics/StaticStrings.h
There are also documentation changes required in arangodb/kube-arangodb#212, but we might want to hold off on those until this is backported if that documentation needs to be valid for 3.3.
> Finishing touches for cursor load balancer support.

- UnitTests/OskarTestSuitesBlackList
Added 3.2 tests blacklist for Oskar with "shell_client_aql" suite.
> Add 3.2 tests blacklist for Oskar

- 3rdParty/curl/curl-7.57.0/lib/http.h
- lib/SimpleHttpClient/Communicator.cpp
in front of each request with a body size > 1024.
this should reduce latency for cluster-internal requests
> make curl not send "Expect: 100-continue" headers

- arangod/Aql/BasicBlocks.h
- arangod/Aql/ClusterBlocks.cpp
- arangod/Aql/ClusterBlocks.h
- arangod/Aql/ExecutionBlock.cpp
- arangod/Aql/ExecutionBlock.h
- arangod/Aql/ExecutionEngine.h
- arangod/Aql/RestAqlHandler.cpp
- arangod/Aql/RestAqlHandler.h
Removed `hasMore()` and `/_api/aql/hasMore` everywhere, respectively the just introduced variants `hasMoreState()` and `/_api/aql/hasMoreState`, as they are currently unused in devel and seem to have been unused at least in 3.2 and 3.3.
> Remove hasMore

- utils/generateSwagger.py
Wrap each line in code tag. This will make all lines show in the proper style (mono-spaced etc.).
It does not seem to have any effect on doc generation, although the api-docs.json is used there too (`x-examples` is appended to `description` in generateSwagger.py and the description is actually used in generateMdFiles.py, but no `<code>` elements are visible in the final HTML?)
> Docs: Improve Swagger presentation of example code

- Documentation/Books/Manual/Programs/Arangoimport/Details.md
This paragraph got lost in programs refactor
> Docs: Re-add automatic pacing paragraph for arangoimport

- CHANGELOG
- js/common/modules/@arangodb/general-graph.js
- js/common/tests/shell/shell-general-graph.js
The edge definition comparison relied on the object's key order and therefore sometimes failed when the edge definitions where actually equal.
> [3.3] Bugfix: Creating a graph failed erroneously

- UnitTests/OskarTestSuitesBlackList
Prevents Oskar from running these suites against 3.2 builds.
> Add Oskar suite blacklist.

- CHANGELOG
- arangod/RocksDBEngine/RocksDBThrottle.cpp
The SetThrottle() routine previously replaced its DelayToken every time called.  This procedure was intended to keep our calculated bytes-per-second active instead of any other value that rocksdb's code might subsequently set.  Unfortunately, The GetDelayToken() code within rocksdb also clears all timings currently in use and forces a big wait upon the very next write.  This could happen multiple times a second under heavy load.
The code now retrieves a DelayToken only if one is not previously held.  Subsequent rewrites of our bytes-per-second value now use a different API that does not clear current timings.
> BugFix 3.3:  adjust SetThrottle() to only call GetDelayToken() first time.

- CHANGELOG
- arangod/RocksDBEngine/RocksDBThrottle.cpp
The SetThrottle() routine previously replaced its DelayToken every time called. This procedure was intended to keep our calculated bytes-per-second active instead of any other value that rocksdb's code might subsequently set. Unfortunately, The GetDelayToken() code within rocksdb also clears all timings currently in use and forces a big wait upon the very next write. This could happen multiple times a second under heavy load.
The code now retrieves a DelayToken only if one is not previously held. Subsequent rewrites of our bytes-per-second value now use a different API that does not clear current timings.
> Bugfix Devel: adjust SetThrottle() to only call GetDelayToken() first time.

- .gitignore
This fixes `/bin` showing up when created as a symlink and avoids accidentally ignoring unrelated folders called "bin" elsewhere in the repository.
This eliminates the current workaround which is symlinking *from* `build/bin` *to* `bin`, which routinely results in problems when trashing `build` and forgetting to manually set up the symlink again.
This needs review because we might be intentionally ignoring artefact folders called "bin" elsewhere in the tree. Those should be blacklisted explicitly (i.e. `/path/to/bin`). If that's not possible the PR should fail review and we probably need to ignore both `/bin` and `bin/`.
> git ignore /bin correctly

- Documentation/Books/HTTP/SUMMARY.md
- Documentation/DocuBlocks/Rest/Views/delete_api_view.md
- Documentation/DocuBlocks/Rest/Views/get_api_view_name.md
- Documentation/DocuBlocks/Rest/Views/patch_api_view_properties.md
- Documentation/DocuBlocks/Rest/Views/patch_api_view_properties_iresearch.md
- Documentation/DocuBlocks/Rest/Views/post_api_view.md
- Documentation/DocuBlocks/Rest/Views/post_api_view_iresearch.md
- Documentation/DocuBlocks/Rest/Views/put_api_view_properties.md
- Documentation/DocuBlocks/Rest/Views/put_api_view_properties_iresearch.md
- remove blank spaces in REST-blocks
- add missing link
- remove type from "@RESTSTRUCT{[field-name],post_api_view_fields,,optional,post_api_view_field_props}"
- replace in @RESTHEADER `#<view-type>` with `#arangosearch`
> fix-iresearch-doc

- arangod/Cluster/ClusterRepairOperations.cpp
- js/server/tests/resilience/repair-distribute-shards-like-spec.js
- tests/Cluster/ClusterRepairsTest.cpp
Changes backported from #5649, plus fix of `js/server/tests/resilience/repair-distribute-shards-like-spec.js`.
> [3.3] Bugfix: Add missing plan version increments in repair-distributeShardsLike

- CMakeLists.txt
This option is totally unused in our build, so it doesn't need to be set.
> remove unused define

- arangod/Cluster/EngineEqualityCheckFeature.cpp
- lib/ApplicationFeatures/ClusterPhase.cpp
deferring the engine check to after the coordinator is fully
bootstrapped reduces the number of bogus startup errors when
firing up a new cluster
> do not run storage engine equality check too early

- js/client/modules/@arangodb/process-utils.js
- js/client/modules/@arangodb/testsuites/backup.js
this may reduce log spam about failed server jobs when shutting
down the instances used for testing
> issue a call to /_admin/cluster/maintenance before shutdown

- js/server/tests/shell/shell-readonly-mode-spec.js
Fixes a non-determinisitic read-only test. It is required to wait for heartbeats otherwise it may get injected an older one.
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/415/
> Bug fix/non deterministic test

- arangod/RocksDBEngine/RocksDBEngine.cpp
- arangod/RocksDBEngine/RocksDBEngine.h
I added this hidden option to 3.3 to assist in other work I am doing.  This PR is for devel/3.4 branch.
Usage requires setting both the new option rocksdb.debug-logging = true and existing log.level = rocksdb=debug. Let me know if there is a way to better do this via one option.
> Feature devel: add rocksdb.debug-logging bool option

- arangod/RocksDBEngine/RocksDBEngine.cpp
- arangod/RocksDBEngine/RocksDBEngine.h
I added this hidden option to 3.3 to assist in other work I am doing.  If approved for 3.3, I will immediately do same for devel.  
Usage requires setting both the new option rocksdb.debug-logging = true and existing log.level = rocksdb=debug.  Let me know if there is a way to better do this via one option.
> Feature 3.3: add rocksdb.debug-logging bool option

- Documentation/Books/Manual/Indexing/IndexBasics.md
Fix example, make usage and utilization clearer
Preview Build:
- https://docs.arangodb.com/review/documentation/vertex-centric-indices/Manual/Indexing/IndexBasics.html#vertex-centric-indexes
> Docs: Clarify some aspects about vertex-centric indices

- Documentation/Books/Drivers/README.md
- Documentation/Books/Manual/README.md
Disable page-toc, use headlines again on first pages of Manual and Drivers book
> Docs: Make use of new per-page settings for page-toc plugin

- arangod/Cluster/HeartbeatThread.cpp
log "HeartbeatThread ok" message in debug log level only
> add missing mutex for _deadThreads handling

- tests/IResearch/RestHandlerMock.cpp
Fix GeneralRequestMock constructor sequence to behave properly with `clang-900.0.39.2`.
> Fix GeneralRequestMock constructor sequence

- Documentation/Books/AQL/Functions/String.md
- Documentation/Books/Manual/ReleaseNotes/NewFeatures34.md
Sorry, couldn't check if the PR breaks the documentation or not, because the documentation seems to be broken already right now.
---
Build Preview:
- https://docs.arangodb.com/review/documentation/add-tokens-aql-function-to-general-aql/Manual/
> add TOKENS AQL function to general list of AQL functions

- js/client/modules/@arangodb/arango-statement.js
getBatchSize() instead setBatchSize() in Get query options.
> Fix a typo in ArangoShell help()

- Documentation/README_maintainers.md
Just in case someone wants to find out more (there is a good README how to build the container)
> Docs: Add link to build-docker-containers for documentation

- Documentation/Books/Manual/Administration/Cluster/README.md
- Documentation/Books/Manual/Administration/Configuration/Compaction.md
- Documentation/Books/Manual/DataModeling/Collections/DatabaseMethods.md
- Documentation/Books/Manual/Graphs/Pregel/README.md
- Documentation/Books/Manual/Indexing/IndexBasics.md
- Documentation/Books/Manual/ReleaseNotes/UpgradingChanges34.md
- Documentation/DocuBlocks/Rest/Collections/get_api_collection_properties.md
- Documentation/DocuBlocks/Rest/Collections/post_api_collection.md
- Documentation/DocuBlocks/collectionProperties.md
- arangod/Sharding/ShardingFeature.cpp
- arangod/Sharding/ShardingFeature.h
- arangod/Sharding/ShardingStrategyDefault.cpp
- arangod/Sharding/ShardingStrategyDefault.h
- js/common/tests/shell/shell-community-sharding-compat-cluster.js
in arangod/Sharding/ShardingStrategiesDefault.*
The sharding strategy "enterprise-compat" is now also available
in the community version so users can switch between enterprise
and community version and vice versa without incompatibilities.
There are mock sharding strategy implementations of the enterprise
sharding strategies for smart edge collections now in the community
edition too. These do not actually shard any data, but they allow
increase the compatibility between enterprise and community edition
in case a downgrade is done from enterprise to community while
using smart edge collections.
When doing that, the previous smart edge collection will now have
a mock smart-edge collection sharding strategy that will always
throw an exception when actually asked for the location of a …
> centralized more of the sharding strategies code

- arangod/Agency/AgencyComm.cpp
- arangod/Cluster/AgencyCallback.cpp
- arangod/Cluster/ClusterInfo.cpp
- arangod/Cluster/FollowerInfo.cpp
- lib/ApplicationFeatures/ApplicationServer.h
This PR adds ApplicationServer::isRetryOK().  Today this function merely calls ApplicationServer::isStopping().  This additional function exists because various classes, such as threads and features, also include an isStopping() call.  This creates confusion about when various logic steps versus retry actions should or should not occur.  The new function creates a single, distinctive name for deciding when communication retries are appropriate.
This PR also includes fixes that use isRetryOK() to address two recent scenarios where a coordinator refused to shutdown due to all agents having shutdown more quickly.
Other code identified manually that decides whether or not to retry is also updated to use isRetryOK().
> bugfix:  establish unique function name & implementation for communication retry status

- CHANGELOG
- arangod/Cluster/HeartbeatThread.cpp
- arangod/Cluster/HeartbeatThread.h
Isolated scenario where a background task of handlePlanChange could take a long time executing, then cause and a potentially infinite executions of the same task. Two changes:
fix infinite loop by setting _lastSyncTime within runBackgroundJob()
change 1 could potential block quick response to an agency notification of plan change, so added code to make agency callback ignore _lastSyncTime limit.
> Bugfix 3.3: correct race condition leading to infinite job execution

- CHANGELOG
- arangod/Agency/AgencyComm.cpp
- arangod/Cluster/AgencyCallback.cpp
- arangod/Cluster/ClusterInfo.cpp
- arangod/Cluster/FollowerInfo.cpp
- lib/ApplicationFeatures/ApplicationServer.h
This PR adds ApplicationServer::isRetryOK(). Today this function merely calls ApplicationServer::isStopping(). This additional function exists because various classes, such as threads and features, also include an isStopping() call. This creates confusion about when various logic stops versus retry actions should or should not occur. The new function creates a single, distinctive name for deciding when communication retries are appropriate.
This PR also includes fixes that use isRetryOK() to address two recent scenarios where a coordinator refused to shutdown due to all agents having shutdown more quickly.
Other code identified manually that decides whether or not to retry is also updated to use isRetryOK().
> Bugfix-3.3: establish unique function name & implementation for communication retry status

- arangod/Aql/Ast.cpp
- arangod/Aql/Expression.cpp
- arangod/Aql/Functions.cpp
- arangod/Aql/Functions.h
the validation has already been done before, so it does not need
to be repeated for each function call invocation
> remove unnecessary parameter validation

- CHANGELOG
- Documentation/Books/Manual/Administration/Configuration/GeneralArangod.md
- arangod/Aql/ExecutionNode.cpp
- arangod/Aql/Optimizer.cpp
- arangod/Aql/Optimizer.h
- arangod/Aql/OptimizerRule.h
- arangod/Aql/OptimizerRules.cpp
- arangod/Aql/QueryOptions.cpp
- arangod/RestServer/QueryRegistryFeature.cpp
- arangod/RestServer/QueryRegistryFeature.h
- js/server/tests/aql/aql-optimizer-collect-methods.js
- js/server/tests/aql/aql-optimizer-rule-interchange-adjacent-enumerations-noncluster.js
- add startup option `--query.optimizer-max-plans value`
- honor "maxNumberOfPlans" in all cases
- lower default value for "maxNumberOfPlans" from 192 to 128
> speed up AQL query plan generation

- js/server/modules/@arangodb/index.js
This PR adds formatting of semversioned versions. 
Keeping the old mechanism if verion is not given in semver format. 
Please remove this check, if this is not needed anymore (keep backward compatibility in mind?)
> semver foxx plain func

- js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
This PR optimizes the fallback to json as default within the query editor if no internet connection is available, but a map was selected to render geojson (which needs an active internet connection).
> optimized geo json fallback in query editor

- arangod/Cluster/MaintenanceFeature.cpp
Fixing bug, that results in default value for maintenance threads being to low to pass validation checks.
> Bugfix/No Maintenance threads default to low

- CHANGELOG
- arangod/Graph/BreadthFirstEnumerator.cpp
- arangod/Graph/BreadthFirstEnumerator.h
- arangod/Graph/EdgeDocumentToken.h
- js/server/tests/aql/aql-graph.js
Fixes issue #5941 path uniqueness was not validated if breath first search was executed.
Jenkins:
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/888/
> Bug fix 3.3/pathuniqueness in bfs

- js/apps/system/_admin/aardvark/APP/aardvark.js
creating a duplicate graph now results in in the error message:
`Example Graphs: graph already exists`
creating a graph with with already existing collections now results in the error message:
`Example Graphs: the collection: ["array","of", "collections"] already exists. Please clean up and try again.`
> improve graph error messages in the UI

- arangod/Cluster/ServerState.cpp
This is needed because the change is propagated via the agency and the
heartbeat, which only happens once per second.
> Wait 2s after switching server mode before answering.

- arangod/ClusterEngine/ClusterTransactionManager.h
- arangod/ClusterEngine/ClusterTransactionState.cpp
- arangod/MMFiles/MMFilesTransactionManager.cpp
- arangod/RocksDBEngine/RocksDBTransactionManager.h
- arangod/RocksDBEngine/RocksDBTransactionState.cpp
in the storage engines that do not need them
the only engine using these objects is MMFiles. the other engines
can get away with not creating these objects
> do not create empty useless transaction data objects

- CHANGELOG
- arangod/Graph/BreadthFirstEnumerator.cpp
The following changes did not make into 3.4 apparently:
https://github.com/arangodb/arangodb/pull/6303/commits/1e725646d343871b031b9fd48676f8965c3fd3b1#diff-d6a329b541cdda9e5ddff2c3e96e637d
> Forward port changelog changes and typo fixes from #6303

- arangod/Aql/RegexCache.cpp
- arangod/Aql/RegexCache.h
Entries in `_likeCache` were emplaced with potentially wrong key. This could have led to memleaks.
> fix leak in regex cache

- arangod/Aql/Aggregator.cpp
- arangod/Aql/Aggregator.h
- arangod/Aql/CollectBlock.cpp
Builder objects are only needed in few of them
This saves allocates for the "hash" COLLECT variant when
there are many distinct groups
> do not use a Builder object in every Aggregator

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
catch 501 (not implemented) in the query editor (ui)
> catch 501 (not implemented) in the query editor (ui)

- arangod/RestHandler/RestReplicationHandler.cpp
- arangod/RocksDBEngine/RocksDBCollection.cpp
- arangod/RocksDBEngine/RocksDBIncrementalSync.cpp
- arangod/RocksDBEngine/RocksDBPrimaryIndex.cpp
- arangod/Transaction/Methods.cpp
- arangod/VocBase/ManagedDocumentResult.cpp
- arangod/VocBase/ManagedDocumentResult.h
- arangosh/Restore/RestoreFeature.cpp
- tests/js/server/shell/shell-collection-not-loaded-mmfiles-timecritical-noncluster.js
* improve arangorestore progress reporting a bit
* rename MMFiles-specific test accordingly (test is not supposed to work with RocksDB at all)
* speed up restoring of documents with primary key conflicts (fixes issue #6379)
* changed some instances of `!res.ok()` to `res.fail()`
* reuse existing `ManagedDocumentResult` instances, simplify its API a bit
> Bug fix/optimizations 210918

- lib/Basics/memory-map.h
according to man msync, there is no need for the end address to be page-aligned
also use uintptr_t consistently instead of intptr_t
> modify msync code so that only base address is page-aligned

- Documentation/Books/HTTP/Agency/README.md
Docs building broken by upper-case letter in anchor link: https://github.com/arangodb/arangodb/commit/0a9afccde5a6f89b7c057b9d894353258dc04c93
@graetzer anchor links use lower-case letters only and at least our tests are case-sensitive
> Fix anchor link and typos

- Documentation/Books/HTTP/Agency/README.md
Related to: https://github.com/arangodb/arangodb/pull/6617
> Fix typos in agency text, no broken link in 3.3

- js/apps/system/_admin/aardvark/APP/frontend/js/views/applicationDetailView.js
Fix  the web UI to properly display JSON properties of foxx service configuration, without this, it was displaying `[Object object]` instead of the proper JSON "stringified" configuration (see the screenshot below).
This PR does not include the grunt generated files, I guess they are generated automatically by your CD/CI before packaging a new version.
> Properly display JSON properties of user defined foxx services configuration within the web UI

- arangod/Agency/MoveShard.cpp
This was forgotten when we added the `remainsFollower` flag.
> Increase Plan/Version if follower is removed in MoveShard.

- js/apps/system/_admin/aardvark/APP/frontend/js/templates/applicationsView.ejs
- js/apps/system/_admin/aardvark/APP/frontend/js/templates/viewsView.ejs
- js/apps/system/_admin/aardvark/APP/frontend/js/views/applicationsView.js
- js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
- js/apps/system/_admin/aardvark/APP/frontend/js/views/viewsView.js
In readonly mode disable the `New View/Service` Buttons. Fixed a stupid warning about lower case constructors.
Fixes arangodb/release-3.4#64
> [3.4] Disable New View/Service in UI

- lib/SimpleHttpClient/GeneralClientConnection.cpp
- lib/SimpleHttpClient/SimpleHttpClient.cpp
Reset retry counter only when previously connected in order to not disable the retry check.
Abort the `doRequest` loop when on shutdown.
> Stop AgencyRequests on Shutdown

- lib/SimpleHttpClient/GeneralClientConnection.cpp
- lib/SimpleHttpClient/SimpleHttpClient.cpp
Reset retry counter only when previously connected in order to not disable the retry check.
Abort the `doRequest` loop when in shutdown.
> [3.4] Stop AgencyRequests on Shutdown

- CHANGELOG
- arangod/Aql/SharedQueryState.cpp
- arangod/Cluster/ClusterComm.cpp
- lib/SimpleHttpClient/Communicator.cpp
- lib/SimpleHttpClient/Communicator.h
- tests/SimpleHttpClient/CommunicatorTest.cpp
java-benchmark using 64 threads on aql_get test encountered errors. The errors coincided with the coordinator experiencing time outs when connecting to database servers. Detail study of logs, code, and packet traces revealed that libcurl was aggressive closing connections, sometimes 20 at a time, during periods when those connections were going to be needed real soon.
Disabling all connection closing worked immediately. However, that leaves the possibility having a large number of open connections that never get used again after a burst.
The fix is to dynamical adjust libcurl's maximum connection size. The code watches for the maximum number of actions over 5 minutes (using one minute intervals). The code then sets the maximum connection number based upon history and new requests.
> Bugfix devel: dynamic management of libcurl's open connections

- arangod/Scheduler/Scheduler.cpp
- arangod/Scheduler/SchedulerFeature.h
Addressing three critical omissions from recent PR:
1. _nrMinimalThreads was defaulting to 2, which therefore caused auto sizing of this value to be skipped.  Now defaults to zero so code will autosize based upon cpu core count.  The autosize creates execution environment that does NOT block critical tasks (that end up causing all schedulers to lock for 120 seconds).
2. canPostDirectly() used "<=" when "<" needed.  Creates opportunity to post one more task than count of threads.  Posting extra tasks to boost io_context can cause delays on poster's thread.
3. threadShouldStop() now returns only false.  This needs extensive testing and discussions about performance impact if original code restored.  Performance goes down in case where function returns true.
I intentionally did NOT create a …
> Bugfix-3.4:  correct omissions from recent scheduler thread PR

- 3rdParty/iresearch/core/utils/locale_utils.cpp
Failed to compile with clang 6 on linux.
> [3.4] fix clang compile error

- arangod/Statistics/StatisticsWorker.cpp
this should prevent errors such as `WARNING caught exception during statistics processing: Expecting Object` from the statistics during version upgrades
> suppress statistics warnings

- arangod/Indexes/SkiplistIndexAttributeMatcher.cpp
this was implemented previously as well, but only honored the number of
attributes defined by the index, not the number of attributes that were
actually part of the filter condition
> prefer an index if more index attributes cover a filter condition

- js/client/modules/@arangodb/crash-utils.js
- js/client/modules/@arangodb/process-utils.js
Procdump doesn't indicate by exit code whether a dump occured or not.
it just does some random undocumented exit code.
Put in a propper coredump filename on the start, remember it on the
instance structure, and check for the files existence to find out
whether procdump took a dump.
> Don't listen to procdumps exit code

- CHANGELOG
Removed the headings for 3.4.0-RC.4 and "merged" what was there under the 3.4.0-RC.3
Since 3.4.0-RC.3 has not been released yet - to avoid possible confusion from users and customers
Thanks,
> Update CHANGELOG 3.4

- UnitTests/unittest.js
> initialize the testresult summary with an abort message, in case we don't finish successfully

- arangod/Scheduler/Scheduler.cpp
- arangod/Scheduler/SchedulerFeature.cpp
- arangod/Scheduler/SchedulerFeature.h
This PR restores some of the prior Scheduler logic that would delete "excess" threads.  The asio io_context object appears to have latency issues when too many threads are active but unused.  There is a similar latency problem when too few threads exist and the code tries to spawn new threads.  
Recently optimized for the latter case by always starting all threads and never deleting any.  Worked great for tests with using large number of clients.  Worked worse for tests with single client.
This branch returns to the previous code for number to start and when to delete.  It also adds a comment about why this is happening.
Original testing was based largely upon Coordinator throughput.  It ws the subsequent testing with the code also running on db servers that better demonstrated the loss …
> Bugfix 3.4:  update Scheduler thread logic based upon testing

- arangod/Cluster/SynchronizeShard.cpp
- arangod/Sharding/ShardingInfo.cpp
- arangod/VocBase/LogicalCollection.h
- arangod/VocBase/LogicalDataSource.h
- tests/RocksDBEngine/IndexEstimatorTest.cpp
- tests/Sharding/ShardDistributionReporterTest.cpp
* allow index estimator test to be run without further dependencies (crashed otherwise with nullptr access)
* remove stray "toJson()" call
* fix memleak in ShardDistributionReporter test and make it not cast away constness
> Bug fix/fix catch test issues

- CHANGELOG
- arangod/Agency/AgencyComm.cpp
During an arangod startup loop, the error checking was missing. If e.g. a database arangod instance tried to connect to the agency, it tried for an unlimited time. This pull request is now checking if we got an 401 http error code (unauthorized) and exists if true. 
**Please review.**
If this PR seems to be fine, we need to create a second PR for 3.4 branch as well.
> Bug fix/agency loop wrong credentials

- CHANGELOG
- arangod/Agency/AgencyComm.cpp
During an arangod startup loop, the error checking was missing. If e.g. a database arangod instance tried to connect to the agency, it tried for an unlimited time. This pull request is now checking if we got an 401 http error code (unauthorized) and exists if true.
> Bug fix 3.3/agency loop wrong credentials

- CHANGELOG
- arangod/Agency/AgencyComm.cpp
During an arangod startup loop, the error checking was missing. If e.g. a database arangod instance tried to connect to the agency, it tried for an unlimited time. This pull request is now checking if we got an 401 http error code (unauthorized) and exists if true.
> Bug fix 3.4/agency loop wrong credentials

- CHANGELOG
- arangod/Agency/AgencyComm.cpp
During an arangod startup loop, the error checking was missing. If e.g. a database arangod instance tried to connect to the agency, it tried for an unlimited time. This pull request is now checking if we got an 401 http error code (unauthorized) and exists if true.
> Bug fix 3.2/agency loop wrong credentials

- CHANGELOG
- Documentation/Books/Manual/Administration/Configuration/RocksDB.md
- arangod/RocksDBEngine/RocksDBEngine.cpp
- lib/ApplicationFeatures/RocksDBOptionFeature.cpp
- lib/ApplicationFeatures/RocksDBOptionFeature.h
> added option `--rocksdb.total-write-buffer-size`

- arangod/Cluster/ClusterMethods.cpp
- arangod/RestHandler/RestReplicationHandler.cpp
Write requests from coordinator to leaders now have a longer timeout
to allow for stopped writes by a follower trying to get in sync.
Also improve error logging in the `restore` REST handler.
> Repair arangorestore.

- js/client/modules/@arangodb/index.js
when just starting the arangosh without a connection to a server
and running code such as `require("internal")`, the shell always
printed "connection class corrupted", which is somewhat misleading.
just don't print this error here, as it is useless
> stop printing `connection class corrupted` in arangosh

- Installation/release.sh
this calculates an SHA1 sum over all files in js and enterprise/js.
makes the presence of the `sha1sum` executable a requirement for running the release script.
> calculate SHA1 sum for JS files on installation

- Installation/release.sh
- cmake/ArangoDBInstall.cmake
- cmake/InstallArangoDBJSClient.cmake
- js/JS_SHA1SUM.txt
this calculates an SHA1 sum over all files in js and enterprise/js.
makes the presence of the `sha1sum` executable a requirement for running the release script.
> Bug fix 3.3/calculate js sha1 sum

- arangod/Aql/ExecutionPlan.cpp
- arangod/Aql/ExecutionPlan.h
- arangod/Aql/Optimizer.cpp
- arangod/Aql/Optimizer.h
- arangod/Aql/Query.cpp
- lib/Basics/RollingVector.h
- tests/IResearch/common.cpp
As part of this PR I removed the limitation that `RollingVector` could only be used with trivial types, since I could not find any reason that justified it (please let me know if you disagree). That allowed me to use unique_ptrs instead of raw pointers for the execution plans.
Profiling runs showed that a highly significant portion of `createPlans` is spent in the lookups in `_disabledIds` - this should be improved by this PR. An even larger portion is spent in `upper_bound` to find the next rule to be applied. I have though about how to improve this as well, but this would require bigger changes so I will tackle this in a separate PR.
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/1941/
> Bug fix/refactor query optimizer

- arangod/Scheduler/Scheduler.cpp
- lib/SimpleHttpClient/Communicator.cpp
- lib/SimpleHttpClient/Communicator.h
Two PRs from 3.4:
- add defensive coding to Communicator.cpp that removes Communicator object dependency from lambda function sent to Scheduler:  https://github.com/arangodb/arangodb/pull/7144
- revert accidental change to constant in Scheduler.cpp:  https://github.com/arangodb/arangodb/pull/7208
> Bugfix:  backport defensive Communicator change and revert constant change in Scheduler

- arangod/Cluster/ClusterComm.cpp
- arangod/Cluster/ClusterComm.h
This change is believed to address the segfault discussed here:
https://github.com/arangodb/release-3.4/issues/127
The original ClusterComm::stopBackgroundThreads() did not actually guarantee that the Communicator object on the background thread had stopped.  This appears to have allowed the background thread to continue posting response tasks to Supervisor after Supervisor was destroyed.  Segfaults happen.
Background thread stopping happens in two steps.  First tell all threads to stop.  This allows parallel shutdown activity.  Second, check each thread to see that it has stopped and wait until it does.
> Bug fix 3.4:  verify communication thread has fully stopped in ClusterComm

- arangod/Cluster/ClusterComm.cpp
- arangod/Cluster/ClusterComm.h
Missed in previous PR that ClusterCommThread destructor was calling Thread::shutdown.  The new code created a deadlock waiting for slow STOPPED state.
The actual target bug, segfault during Agency shutdown, is still unresolved.
> Bugfix 3.4:  revert recently added condition variable in ClusterCommThread stop

- CHANGELOG
- js/server/modules/@arangodb/foxx/queues/worker.js
- tests/js/server/shell/shell-foxx-queues.js
This fixes a bug where `maxFailures` would be ignored if set to `-1` or `Infinity` and removes a useless check for `false` (which is not supported by the API).
> Fix Foxx Queues infinite maxFailures

- Documentation/Books/Manual/Appendix/JavaScriptModules/Queries.md
- Documentation/Books/Manual/ReleaseNotes/NewFeatures34.md
- arangod/RestHandler/RestQueryHandler.cpp
- arangod/V8Server/v8-vocbase.cpp
- tests/js/common/shell/shell-query-stream-timecritical-spec.js
Seems I broke this test with some prior changes, and this went unnoticed because of the `timecritical` appendix.
> fix failing non-deterministic query-stream test

- js/server/tests/shell/shell-foxx-queues.js
This fixes a bug introduced in #7225 due to a bad cherry-pick.
> Fix pathForTesting -> startupPath

- 3rdParty/CMakeLists.txt
- arangod/IResearch/IResearchDocument.cpp
- arangod/IResearch/IResearchDocument.h
- arangod/IResearch/IResearchFilterFactory.cpp
- arangod/IResearch/IResearchFilterFactory.h
- arangod/IResearch/IResearchPrimaryKeyFilter.cpp
- arangod/IResearch/IResearchPrimaryKeyFilter.h
- arangod/IResearch/IResearchView.cpp
- arangod/IResearch/IResearchViewBlock.cpp
- arangod/IResearch/IResearchViewBlock.h
- tests/IResearch/IResearchDocument-test.cpp
* refactor arangosearch pks
* minor refactoring
* store PK as BigEndian since it leads to more compact index representation
* force iresearch to not to use libbfd
* fix tests
> [3.4] Feature/arangosearch pk endianness (#7306)

- arangod/GeneralServer/GeneralCommTask.cpp
As follower in an active failover answer a request with not a leader, even if the database does not exist.
> [3.3] ActiveFailover Follower DB Not Found bug

- arangod/Scheduler/Scheduler.cpp
- arangod/Scheduler/Scheduler.h
A recent bug made a late call to Scheduler::post after the _ioContext had been reset.  The bug has been fixed.  But the bug demonstrated that post() is vulnerable to late calls that might creep into the codebase in the future.
This PR adds a test for NULL within _ioContext upon entry to the post() function.  When seen, the callback occurs immediately using the call's thread ... and logs a warning.  
This does NOT defend against race conditions with _ioContext clearing simultaneously to the post() call and/or clearing during the processing inside the post() function.
> Bugfix 3.4:  Null pointer defense in Scheduler::post(callback)

- Documentation/Books/Manual/Foxx/Scripts.md
repeatTimes can only be a number (or undefined), not a function. Tested it in 3.3.17
> opts.repeatTimes incorrect value types corrected

- js/apps/system/_admin/aardvark/APP/frontend/js/views/viewView.js
finally reload the properties of a view if the view inside the ui is set back to readOnly: false.
> refresh properties after switching back to edit mode

- js/server/modules/@arangodb/foxx/manager.js
Just removes a debug log output, and an always active debug trigger. Now code is back to original state. It has not been used by former PR.
> Removed debug-log output from foxx manager

- arangosh/Import/ImportHelper.cpp
Do not access the array of field names to search for removed attributes if the index is out of bounds. (i.e. malformed input data)
> ArangoImport Crash

- arangosh/Import/ImportHelper.cpp
Do not access the array of field names to search for removed attributes if the index is out of bounds. (i.e. malformed input data)
> ArangoImport Crash 

- Documentation/Books/AQL/Functions/String.md
Removed redundant content, placed paragraph with a remark about LENGTH() back where it belongs
> Docs: Fix LEVENSHTEIN_DISTANCE function description

- arangosh/Restore/RestoreFeature.cpp
Just a minor improvement in help on error output.
> Improved help message for a failed restore of foxx services

- Documentation/Books/Manual/Upgrading/VersionSpecific/Upgrading34.md
As requested, some documentation about upgrade tasks carried out when upgrading from 3.3 to 3.4.
If ok, then this PR needs a backport to 3.4 and probably 3.3 (if you think it makes sense).
> notes about upgrading

- arangod/Cluster/HeartbeatThread.cpp
- arangod/Cluster/ServerState.cpp
- arangod/Cluster/ServerState.h
- arangod/RestServer/BootstrapFeature.cpp
- js/server/modules/@arangodb/foxx/manager.js
Fixes an error found with the node resilience tests. There, a coordinator is stopped, a foxx service is changed, then the coordinator is restarted. Sometimes the service isn't immediately available when the coordinator is up.
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/2304/
> [3.4] Reload Foxx routes during startup

- arangod/Indexes/IndexFactory.cpp
- arangod/RestHandler/RestReplicationHandler.cpp
Fixes a problem with trying to restore indexes of type "primary" into a single server from a cluster dump.
> dont fail when restoring a cluster dump into a single server

- arangod/MMFiles/MMFilesCollection.cpp
> Disable warning about persistent IDs during upgrade procedure.

- arangod/MMFiles/MMFilesCollection.cpp
> [3.4] Disable warning about persistent IDs during upgrade procedure.

- Documentation/Books/Manual/Deployment/ActiveFailover/UsingTheStarter.md
- Documentation/Books/Manual/Deployment/Cluster/UsingTheStarter.md
- Documentation/Books/Manual/Deployment/SingleInstance/UsingTheStarter.md
This copies over a last minute change in the starter documentation
to 3.4.
Build:
- http://jenkins01.arangodb.biz:8080/job/arangodb-documentation/164/
Branch in the starter repo (changes needs to be ported there as well, fyi @Simran-B ) https://github.com/arangodb-helper/arangodb/tree/documentation/starter-license-key
Needs to be forward ported to devel
> License key documentation in starter.

- Documentation/Books/Manual/ReleaseNotes/NewFeatures34.md
~~Will it be in 3.4.1 or already in 3.4.0? If it's 3.4.1, then we need to point that out somehow...~~
Looks to me like it's in the release though:
- https://github.com/arangodb/arangodb/pull/7634
- https://github.com/arangodb/arangodb/commits/v3.4.0
Also backport this to 3.4 branch.
> Docs: Mention GEO_MULTIPOLYGON() in 3.4 release notes

- arangod/Cluster/SynchronizeShard.cpp
instead of
```
2018-12-05T15:43:16Z [14614] P ERROR {maintenance} CancelBarrier: failed to send message to leader : status \x06
```
> nicer log messages with stringified status value

- arangod/Cluster/ClusterComm.cpp
This PR contains 3.4 PRs #7232 and 7239.  Basically two changes:
1.  This change is believed to address the segfault discussed here:
arangodb/release-3.4#127
The original ClusterComm::stopBackgroundThreads() did not actually guarantee that the Communicator object on the background thread had stopped. This appears to have allowed the background thread to continue posting response tasks to Supervisor after Supervisor was destroyed. Segfaults happen.
Background thread stopping happens in two steps. First tell all threads to stop. This allows parallel shutdown activity. Second, check each thread to see that it has stopped and wait until it does.
2.  Move two ClusterCommThread functions from the middle of the source file to location at end of source file to be next to all other …
> Bugfix: port 3.4 change to stopBackgroundThreads.

- Documentation/Books/Manual/SUMMARY.md
The devel documentation build is broken, missing files in SUMMARY.md
see https://github.com/arangodb/arangodb/pull/7686/files
```
not all files of Manual are mapped to the summary!
files found       |    files in summary
ReleaseNotes/KnownIssues35.md
ReleaseNotes/UpgradingChanges35.md
```
> Doc: fix build - add missing SUMMARY entries

- arangod/Aql/IndexNode.cpp
- arangod/Aql/Query.cpp
- arangod/ClusterEngine/ClusterIndex.cpp
- arangod/ClusterEngine/ClusterIndex.h
- arangod/Indexes/Index.h
- arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
- arangod/RocksDBEngine/RocksDBEdgeIndex.h
- tests/js/server/aql/aql-optimizer-index-only-rocksdb.js
Ported from devel.
Allow the RocksDB edge index to return the opposite vertex id from the index itself and not extract the document first.
> Feature3.4/improve edgeindex covered

- Documentation/Examples/arangodump.json
- Documentation/Examples/arangorestore.json
- arangosh/Dump/DumpFeature.cpp
- arangosh/Restore/RestoreFeature.cpp
(same as devel https://github.com/arangodb/arangodb/pull/7701)
> Documents that arangorestore/arangodump threads option is from v3.4.0 on

- CHANGELOG
Jan, I have added a missed entry in the changelog - I took this from 3.3.22
I did not add other 2 entries that you added in 3.3.22 because I am not sure. You added them in PR 7827 (same PR I am taking the entry from), which was done for 3.4 as well
I will leave this to you - please review my commit and consider this additional entries, if appropriate for 3.4.2:
```
* when detecting parse errors in the JSON input sent to the restore API, now
abort with a proper error containing the problem description instead of aborting
but hiding there was a problem.
* remove Swagger map files from the build to reduce package sizes 
* do not respond with an internal error in case of JSON parse errors detected
in incoming HTTP requests 
```
Thanks,
> 3.4.2 changelog - missing entries

- arangod/Indexes/Index.cpp
- arangod/Indexes/Index.h
- arangod/MMFiles/MMFilesPathBasedIndex.cpp
- arangod/MMFiles/MMFilesPathBasedIndex.h
- arangod/RocksDBEngine/RocksDBVPackIndex.cpp
- arangod/RocksDBEngine/RocksDBVPackIndex.h
- arangod/Transaction/Methods.cpp
- js/common/modules/@arangodb/aql/explainer.js
This allows using
```
db._explain(query, bind, { allPlans: true });
```
showing all execution plans.
> support db._explain with all plans

- Documentation/Books/HTTP/Replications/README.md
- Documentation/Books/Manual/Administration/MasterSlave/ReplicationApplier.md
There is also a global applier since 3.3.0
Needs to be backported to 3.3 and 3.4 docs.
http://jenkins01.arangodb.biz:8080/view/Documentation/job/arangodb-documentation/238/
> Update remark about per-database replication

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
> fix #7900 - null bind values do not change to empty string anymore

- CHANGELOG
- Documentation/Books/AQL/ExecutionAndPerformance/QueryStatistics.md
- arangod/Aql/ExecutionStats.cpp
- arangod/Aql/ExecutionStats.h
- arangod/Aql/Query.cpp
- arangod/Aql/Query.h
- arangod/Aql/ResourceUsage.h
- js/server/modules/@arangodb/aql-helper.js
- js/server/modules/@arangodb/aql-profiler-test-helper.js
- tests/js/server/aql/aql-modify-cluster.js
- tests/js/server/aql/aql-modify-noncluster.js
- tests/js/server/aql/aql-modify-subqueries.js
showing the peak memory usage of the executed query. In a cluster, the value contains the peak memory usage
across all shards, but it is not summed up across shards.
> added "peakMemoryUsage" in query results figures,

- arangod/RestHandler/RestQueryHandler.cpp
- arangod/Transaction/Methods.cpp
- arangosh/Shell/ClientFeature.h
- arangosh/Shell/V8ClientConnection.cpp
- arangosh/Shell/V8ClientConnection.h
- js/client/client.js
This PR contains two changes:
* if an index cannot be used for sorting, its sort cost was previously returned as 0. 
this will in fact favor indexes that can be used for filtering but not for sorting over indexes that can be used for both.
this change is to report the sort cost for indexes that cannot be used for sorting to n * log(n), where n is the number of documents that optimizer expects to come out of the index after filtering
* only spend up to 10 seconds for initially fetching the list of collections in arangosh
fetching the list of collections is a blocking operation, and the default timeout for this is very high. if the server is blocked by whatever reason, then the shell is unusable until the collections list request returns. to avoid this, the initial request is limited to 10 …
> Bug fix 3.4/misc issues

- Documentation/Examples/arangod.json
- arangod/GeneralServer/AuthenticationFeature.cpp
The option should no longer be used.
Ref: https://github.com/arangodb/arangodb/pull/7863/files#diff-830e1f420da6281d48b409dc935de9e3R136
> --server.jwt-secret is insecure. Use --server.jwt-secret-keyfile instead.
Therefore, we should mark it as deprecated. This PR will add "Deprecated in: v3.3.22, v3.4.2" to the documentation on this page:
https://docs.arangodb.com/3.4/Manual/Programs/Arangod/Options.html#server-options
> Doc - Deprecate --server.jwt-secret startup option

- Documentation/Examples/arangod.json
- arangod/GeneralServer/AuthenticationFeature.cpp
Backport of https://github.com/arangodb/arangodb/pull/7947/
> Doc - Deprecate --server.jwt-secret startup option (3.4)

- arangod/RocksDBEngine/RocksDBMethods.cpp
- arangod/RocksDBEngine/RocksDBTransactionState.cpp
- lib/V8/v8-vpack.cpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/4082/
A single read operation via `trx.document(...)` does not need any snapshot guarantees. In fact we probably only create unnecessary overhead by blocking compactions
> Do not acquire snapshot for single read

- arangosh/Dump/DumpFeature.cpp
> [3.3] Fix broken validation of tick range in arangodump.

- arangosh/Dump/DumpFeature.cpp
> [3.4] Fix broken validation of tick range in arangodump.

- arangosh/Dump/DumpFeature.cpp
> Fix broken validation of tick range in arangodump.

- CHANGELOG
- arangod/Aql/CollectBlock.cpp
- arangod/Aql/CollectBlock.h
- tests/js/server/aql/aql-optimizer-rule-remove-redundant-sorts.js
See https://github.com/arangodb/arangodb/pull/8037.
> Sorted COLLECT: avoid nullptr deref when skipping and fix non-invalidated input variables

- tests/js/server/replication/replication-fuzz-global.js
- tests/js/server/replication/replication-fuzz.js
- tests/js/server/replication/replication-ongoing-32.js
- tests/js/server/replication/replication-ongoing-frompresent-32.js
- tests/js/server/replication/replication-ongoing-frompresent.js
- tests/js/server/replication/replication-ongoing-global-spec.js
- tests/js/server/replication/replication-ongoing-global.js
- tests/js/server/replication/replication-ongoing.js
- tests/js/server/replication/replication-random.js
It seems the replication ongoing tests may have failed with MMFiles in case the WAL-to-disk-syncing on the master had considerable delays.
> more mmfiles replication tests changes

- arangod/Aql/ExecutionNode.cpp
- arangod/Aql/LimitExecutor.cpp
- arangod/Aql/LimitExecutor.h
- tests/Aql/LimitExecutorTest.cpp
- tests/js/server/aql/aql-subquery.js
The mutation could not be reset during initializeCursor, thus the offset was broken in subsequent iterations of a subquery.
> Bug fix: do not mutate the offset in the LimitExecutor

- CHANGELOG
- js/common/modules/@arangodb/common.js
This fixes a bug where the following would result in garbage:
```js
aql`
something
${aql.join([])}
something
`;
```
The expected result would be that the `aql.join` is omitted entirely, the observed result was that an empty query object is added as a `bindVar`. The cause was that `aql.join` generates a query object with an empty query string and the `isAqlQuery` function checks for truthiness (empty strings are false).
> Fix isAqlQuery with empty query

- Documentation/Books/Manual/Installation/Windows.md
`<` and `>` can not be properly escaped with backslashes, at least not in Gitbook / marked.
Thanks to Vadim for spotting!
https://docs.arangodb.com/3.4/Manual/Installation/Windows.html
http://jenkins01.arangodb.biz:8080/view/Documentation/job/arangodb-documentation/316/
> Doc - Windows Installation - Use code tags and env vars

- CHANGELOG
- js/node/package.json
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/3145/
> upgraded to 4.17.11 because of CVE-2018-16487

- lib/Basics/Thread.cpp
This fixes a race condition where the thread function would return early when _state is already set to `STOPPING`. This was most likely the cause for the crash of the nightly tests.
> Set thread's state to `STOPPED` when the thread function finishes.

- Documentation/Books/Manual/Graphs/Traversals/UsingTraversalObjects.md
- Documentation/Books/Manual/ReleaseNotes/UpgradingChanges34.md
It is the (shared) implementation of /_api/traversal - which we deprecated in v3.4.0
Action/route: [js/actions/api-traversal.js](https://github.com/arangodb/arangodb/blob/devel/js/actions/api-traversal.js)
Traverser included from: [js/common/modules/@arangodb/graph/traversal.js](https://github.com/arangodb/arangodb/blob/devel/js/common/modules/%40arangodb/graph/traversal.js)
> Doc - Add missing deprecation note for traversal module

- Documentation/Books/AQL/Fundamentals/DataTypes.md
- explain what (un)quoted means
- explain Null and Boolean types
- number literals 1 > n > -1 don't require a leading zero anymore (e.g. `.5` is possible in devel/3.5)
- formatting
> Doc - Rework AQL Data Types page

- Documentation/Books/AQL/Fundamentals/DataTypes.md
Backport of #8287 but listing `.5` as invalid number literal (not supported until 3.5.0)
> Doc - Rework AQL Data Types page (3.4)

- Documentation/Books/Manual/Graphs/Traversals/UsingTraversalObjects.md
- Documentation/Books/Manual/ReleaseNotes/UpgradingChanges34.md
Backport of #8293
http://jenkins01.arangodb.biz:8080/view/Documentation/job/arangodb-documentation/350/
> Doc - Add missing deprecation note for traversal module (#8293)

- arangod/IResearch/IResearchAnalyzerFeature.h
In file included from /home/mop/projects/arangodb/tests/IResearch/IResearchQueryNumericTerm-test.cpp:47:
/home/mop/projects/arangodb/arangod/IResearch/IResearchAnalyzerFeature.h:36:1: warning: class 'TRI_vocbase_t' was previously declared as a struct [-Wmismatched-tags]
class TRI_vocbase_t; // forward declaration
^
/home/mop/projects/arangodb/arangod/VocBase/vocbase.h:121:8: note: previous use is here
struct TRI_vocbase_t {
^
/home/mop/projects/arangodb/arangod/IResearch/IResearchAnalyzerFeature.h:36:1: note: did you mean struct here?
class TRI_vocbase_t; // forward declaration
^~~~~
> 🚨 Fix struct vs class warning

- arangod/Aql/ExecutionPlan.cpp
- arangod/Aql/ExecutionPlan.h
- arangod/Aql/Optimizer.cpp
Should fix the following assertion failures:
```
#0  a_crash () at ./arch/x86_64/atomic_arch.h:108
#1  abort () at src/exit/abort.c:11
#2  0x0000000000c8de70 in arangodb::aql::ExecutionPlan::~ExecutionPlan (this=0x7f7257075340, __in_chrg=<optimized out>)
at /work/ArangoDB/arangod/Aql/ExecutionPlan.cpp:237
#3  0x000000000065cc68 in std::default_delete<arangodb::aql::ExecutionPlan>::operator() (this=<optimized out>, __ptr=0x7f7257075340)
at /usr/include/c++/6.4.0/bits/unique_ptr.h:76
#4  std::unique_ptr<arangodb::aql::ExecutionPlan, std::default_delete<arangodb::aql::ExecutionPlan> >::~unique_ptr (
this=0x7f7266d30958, __in_chrg=<optimized out>) at /usr/include/c++/6.4.0/bits/unique_ptr.h:239
```
> fix an assertion failure when plans are shut down in an invalid state

- Documentation/Books/Manual/Administration/MasterSlave/DatabaseSetup.md
- Documentation/Books/Manual/Administration/MasterSlave/ReplicationApplier.md
- Documentation/Books/Manual/Administration/MasterSlave/ServerLevelSetup.md
- arangod/Replication/DatabaseInitialSyncer.cpp
- arangod/Replication/GlobalInitialSyncer.cpp
- arangod/Replication/ReplicationApplierConfiguration.cpp
- arangod/Replication/ReplicationApplierConfiguration.h
- js/server/server.js
Additionally, make active failover do an incremental sync instead of
a full sync. Finally, don't drop system collections when resyncing,
but only truncate them. This can avoid problems when a follower is
killed/stopped between having dropped a system collection and recreating
it.
> document `includeFoxxQueues` attribute and persist it

- 3rdParty/rocksdb/v5.6.X/port/win/env_win.cc
This is same fix submitted to 3.4 and devel branches.
WinEnvIO::NowNanos() typically overflows its int64_t due to the way code "preserves" the nanoseconds.  This code actually preserves the accuracy.  The code includes a condition statement that will support future machines where clock frequency is sub-nanosecond.
> BugFix 3.3:  Correct RocksDB NowNano() for overflow

- CHANGELOG
- arangod/Agency/RemoveFollower.cpp
- arangod/Agency/Supervision.cpp
- arangod/RestHandler/RestReplicationHandler.cpp
- tests/Agency/RemoveFollowerTest.cpp
- tests/Agency/RemoveFollowerTest.json
- Ignore satellite collections in shrinkCluster in agency.
- Abort RemoveFollower job if not enough in-sync followers or leader failure.
- Break quick wait loop in supervision if leadership is lost.
- In case of resigned leader, set isReady=false in clusterInventory.
- Fix catch tests.
> Various agency fixes.

- CHANGELOG
- arangod/Agency/FailedFollower.cpp
- arangod/Agency/FailedLeader.cpp
- Check if transaction failed before accessing the result.
- FailedFollower has the same bug.
> Port agency crash fixes to 3.3.

- CHANGELOG
- arangod/Agency/FailedFollower.cpp
- arangod/Agency/FailedLeader.cpp
- Check if transaction failed before accessing the result.
- FailedFollower has the same bug.
> Fix an agency crash.

- arangod/Agency/RemoveFollower.cpp
- arangod/Agency/Supervision.cpp
- arangod/RestHandler/RestReplicationHandler.cpp
- tests/Agency/RemoveFollowerTest.cpp
- tests/Agency/RemoveFollowerTest.json
- In case of resigned leader, set isReady=false in clusterInventory.
- Break quick wait loop in supervision if leadership is lost.
- Abort RemoveFollower job if not enough in-sync followers or leader failure.
- Ignore satellite collections in shrinkCluster in agency.
- Fix catch tests.
> Various agency improvements.

- arangod/RestHandler/RestHotBackupHandler.cpp
- arangod/RocksDBEngine/RocksDBHotBackup.cpp
- arangod/RocksDBEngine/RocksDBHotBackup.h
- arangod/RocksDBEngine/RocksDBHotBackupCoord.h
This implements /_admin/hotbackup/list POST method for single server / db server.  It returns a JSON object like {"server": "server_id_string", "hotbackups":["entry 1 of directory name array", "entry 2 of directory name array"]}.  Special directory names like CREATING and FAILSAFE are filtered from the list.
Sample:
{"error":false,"code":200,"result":{"server":"SNGL-9231534b-e1aa-4eb6-881a-0b6c798c6677","hotbackups":["SNGL-9231534b-e1aa-4eb6-881a-0b6c798c6677_2019-02-25T18.35.16Z_before_restore","SNGL-9231534b-e1aa-4eb6-881a-0b6c798c6677_2019-02-25T18.21.11Z","SNGL-9231534b-e1aa-4eb6-881a-0b6c798c6677_2019-02-25T18.55.02Z_before_restore","SNGL-9231534b-e1aa-4eb6-881a-0b6c798c6677_2019-02-25T18.32.58Z_bubba_backup","SNGL-9231534b-e1aa-4eb6-881a-0b6c798c6677_2019-03-05T20.35.58Z_before_resto …
> Feature 3.4:  Implement list command for single server hot backup

- tests/Mocks/StorageEngineMock.cpp
This bug showed up while implementing some tests for path finding.
Thanks to Michael Hackstein <michael@arangodb.com> for debugging.
> StorageEngineMock: Prevent deadlock

- tests/Graph/ConstantWeightShortestPathFinder.cpp
The test tried to abort a transaction twice which made the testing process crash sometimes. This removes the symptom (crashing), but not the cause: 
The transaction is shared between the query and the `ShortestPathOptions` and deleting the query leaves the transaction in a state that causes it to crash when `abort()` is called.
> Fix crash in test for ConstantWeightShortestPathFinder

- utils/generateExamples.sh
Skip Examples/*.json generation if the available build is a Community Edition version. This should avoid accidental commits to these files which remove Enterprise Edition only startup options.
> Doc - Dump program options only if on Enterprise Edition

- Documentation/Examples/arangobench.json
- Documentation/Examples/arangod.json
- Documentation/Examples/arangodump.json
- Documentation/Examples/arangoexport.json
- Documentation/Examples/arangoimport.json
- Documentation/Examples/arangoinspect.json
- Documentation/Examples/arangorestore.json
- Documentation/Examples/arangosh.json
- lib/Logger/LoggerFeature.cpp
The version information should be added for all new options, especially if they were introduced in a bugfix release for a GA version (here v3.4.5).
http://jenkins01.arangodb.biz:8080/view/Documentation/job/arangodb-documentation/383/
> Doc - setIntroducedIn for log.file-group/mode

- CHANGELOG
There are 2 entrys for `fixed issue #8165: AQL optimizer` in v3.4.5 and v3.4.4.
Removing the v3.4.5 entry since the fix is already included in v.3.4.4.
> Changelog: remove duplicate entry

- Documentation/Books/AQL/book.json
- Documentation/Books/Cookbook/book.json
- Documentation/Books/HTTP/book.json
- Documentation/Books/Manual/book.json
In order to remove obsolete docs from Google, pages actually have to be readable by Google (robots.txt) and it we need this meta tag to disallow indexing/showing it in their results.
> Doc - Add noindex, nofollow meta tag (3.2)

- 3rdParty/rocksdb/6.0.fb/port/win/env_win.cc
- 3rdParty/rocksdb/6.0.fb/port/win/env_win.h
We updated our version of RocksDB to 6.0.fb. This obviously does not include the NowNanos fix done in latest RocksDB master.
This patch ports the following fix from facebook/rocksdb:
```
commit 88d85b6820453fc6d83ee699e33013eb6810472f
Author: Burton Li <pul@microsoft.com>
Date:   Thu Mar 21 15:10:38 2019 -0700
fix NowNanos overflow (#5062)
Summary:
The original implementation of WinEnvIO::NowNanos() has a constant data overflow by:
li.QuadPart *= std::nano::den;
As a result, the api provides a incorrect result.
e.g.:
li.QuadPart=13477844301545
std::nano::den=1e9
The fix uses pre-computed nano_seconds_per_period_ to present the nano seconds per performance counter period, in the case if nano::den is divisible by perf_counter_frequency_. Otherwise it falls back to use high_resolution_clock. …
```
> added missing fix for NowNanos from upstream RocksDB

- js/client/modules/@arangodb/process-utils.js
- js/client/modules/@arangodb/test-utils.js
- add timestamps in some prints
- fix detection of `runThere` timeouts
- add agency state dumper
- add forcefull cluster killer, so we see what the whole cluster was doing.
> improve timeout behaviour of test utils

- CHANGELOG
- arangod/VocBase/Methods/Upgrade.cpp
- arangod/VocBase/Methods/UpgradeTasks.cpp
- arangod/VocBase/Methods/UpgradeTasks.h
This saves the creation of one collection per DB, which will sum up for installations with many databases and especially in the cluster.
> create _frontend collection lazily

- CHANGELOG
- arangod/Agency/Job.cpp
- arangod/Agency/MoveShard.cpp
- arangod/Agency/Supervision.cpp
- js/server/modules/@arangodb/cluster.js
- tests/Agency/MoveShardTest.cpp
- tests/js/server/resilience/moving-shards-cluster.js
- tests/js/server/resilience/moving-shards-with-arangosearch-view-grey-cluster.js
- tests/js/server/resilience/repair-distribute-shards-like-spec-grey.js
- tests/js/server/resilience/resilience-synchronous-repl-cluster.js
- tests/js/server/resilience/resilience-synchronous-repl-failureAt-cluster.js
- tests/js/server/resilience/resilience-synchronous-repl-with-arangosearch-view-cluster.js
- tests/js/server/resilience/shard-distribution-spec.js
This addresses a problem found in the k8s chaos tests: A MoveShard job could be confused by a failover happening. In this case the MoveShard job would essentially wait forever and lock the toServer.
As a consequence, the removeFollower logic would end up in a bad cycle of scheduling a removeFollower job only to abort it immediately.
Therefore, we now abort a MoveShard job, if any of the servers it has in the Plan for the shard becomes FAILED. Furthermore, we only schedule a removeFollower job, if enough replicas are actually in sync (in Current).
Finally, since the _statistics collections are only created after the bootstrap, a problem during resilience tests could arise, which can occur if collections are created during a cleanOutServer job. This problem will be solved eventually, but …
> Better logic for AddFollower/RemoveFollower scheduling.

- arangod/Auth/TokenCache.cpp
- arangod/Auth/TokenCache.h
- arangod/GeneralServer/GeneralCommTask.cpp
- arangod/GeneralServer/GeneralCommTask.h
- arangod/GeneralServer/HttpCommTask.cpp
- arangod/GeneralServer/HttpCommTask.h
- arangod/GeneralServer/VstCommTask.cpp
- arangod/GeneralServer/VstCommTask.h
Allow the restriction to specific paths in a JWT. This best explained by an example:
```
{"server_id":"foo", "allowed_paths":["/_api/version"]}
```
```
{"server_id":"foo", "allowed_paths":["/_admin/statistics"]}
```
Currently most tools (operator, prometheus exporter) use the superuser token everywhere.
Older versions of arangodb will ignore this attribute and thus adding `allowed_paths` to a token, that allowed access in the first place, will remain valid.
This is a first step to a more evolved method of specifying permissions (including groups, collections, ...) via jwt.
> Feature devel/allowed paths jwt

- arangod/VocBase/LogicalCollection.cpp
Potential fix for DC2DC losing the smartJoinAttribute propery of a collection
I need some help testing this is in an actual DC2DC setup.
> preserve smart-join attribute in DC2DC as well

- arangod/Agency/RestAgencyHandler.cpp
- arangod/Agency/RestAgencyHandler.h
- js/client/modules/@arangodb/process-utils.js
- js/client/modules/@arangodb/testing.js
Fix test shutdown by:
* not making agency config/state/dump produce many many warnings about unknown CustomTypeHandler.
* not printing "[Object object]" for every agent whose data is dumped
* turning off useless sock stats
> Bug fix 3.4/fix test muell

- arangod/Agency/RestAgencyHandler.cpp
- arangod/Agency/RestAgencyHandler.h
- js/client/modules/@arangodb/process-utils.js
- js/client/modules/@arangodb/testing.js
Fix test shutdown by:
* not making agency config/state/dump produce many many warnings about unknown CustomTypeHandler.
* not printing "[Object object]" for every agent whose data is dumped
* turning off useless sock stats
> Bug fix/fix test muell

- js/client/modules/@arangodb/process-utils.js
- js/client/modules/@arangodb/testing.js
- don't dump agency by default on all errors
- don't write junit xml reports by default
> Reduce test leftovers on disk

- Documentation/Books/Manual/Architecture/DeploymentModes/Cluster/DataModels.md
I hope the diff is self-explanatory.
> Fix typo in DataModels documentation

- arangod/V8Server/v8-collection.cpp
- lib/Basics/VelocyPackHelper.cpp
- lib/Basics/VelocyPackHelper.h
The functionality provided by `AttributeExcludeHandler` is not used in ArangoDB anymore.
Attributes are filtered assembled by `TRI_SanitizeObject` and `TRI_SanitizeObjectWithEdges` anyway.
> remove unused attributeExcludeHandler

- CHANGELOG
- js/client/modules/@arangodb/arango-database.js
- js/server/modules/@arangodb/arango-database.js
- tests/js/common/shell/shell-database.js
This corrects the behavior of `db._query` when using `aql` template strings so additional arguments no longer result in an error. An object as initial argument is now always assumed to contain at least the query and bindVars.
> Handle extra args to db._query when using aql templates

- arangod/Aql/grammar.cpp
- arangod/Aql/grammar.y
- tests/js/server/aql/aql-graph-k-shortest-path.js
* catch if the user gives more than one variable in grammar.y
* also give a correct error message
> K_SHORTEST_PATHS queries only support one variable in FOR

- CHANGELOG
- Documentation/Books/Manual/Programs/Arangodump/Examples.md
- Documentation/Examples/arangodump.json
- arangosh/Dump/DumpFeature.cpp
- arangosh/Dump/DumpFeature.h
- arangosh/Restore/RestoreFeature.cpp
- arangosh/Utils/ManagedDirectory.cpp
- arangosh/Utils/ManagedDirectory.h
This is ported from 3.4.  The feature defaults to off in 3.4, but defaults to active in this branch.
This feature utilizes the gzip library to compress collection data written to disk.
arangorestore is updated to automatically recognize whether collection uses gzipped files or not.  It will automatically unzip the collections during ingest.
> Feature: Add compress-output feature to arangodump

- tests/CMakeLists.txt
- tests/Graph/ConstantWeightShortestPathFinder.cpp
- tests/Graph/GraphTestTools.cpp
- tests/Graph/GraphTestTools.h
- tests/Graph/KShortestPathsFinder.cpp
* Move the functions which are used both in ConstantWeightShortestPathFinder
and KShortestPathsFinder into GraphTestTools
* Don't display spurious error messages when there are multiple options
for found paths anymore
> Improve path finder tests

- Documentation/Books/HTTP/AqlQueryCursor/README.md
- Documentation/Books/HTTP/SUMMARY.md
- Documentation/Books/HTTP/Transaction/JsTransaction.md
- Documentation/Books/HTTP/Transaction/README.md
- Documentation/Books/HTTP/Transaction/StreamTransaction.md
- Documentation/Books/Manual/Architecture/DeploymentModes/Cluster/Architecture.md
- Documentation/Books/Manual/DataModeling/OperationalFactors.md
- Documentation/Books/Manual/ReleaseNotes/NewFeatures35.md
- Documentation/Books/Manual/Transactions/Durability.md
- Documentation/Books/Manual/Transactions/Limitations.md
- Documentation/Books/Manual/Transactions/LockingAndIsolation.md
- Documentation/Books/Manual/Transactions/README.md
- Documentation/DocuBlocks/Rest/Transactions/delete_api_transaction.md
- Documentation/DocuBlocks/Rest/Transactions/get_api_transaction.md
- Documentation/DocuBlocks/Rest/Transactions/post_api_transaction.md
- Documentation/DocuBlocks/Rest/Transactions/post_api_transaction_begin.md
- Documentation/DocuBlocks/Rest/Transactions/put_api_transaction.md
- arangod/RestHandler/RestTransactionHandler.cpp
- arangod/Transaction/Manager.cpp
- arangod/Transaction/Options.cpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/5688/
http://jenkins01.arangodb.biz:8080/view/Documentation/job/arangodb-documentation/414/
name is not necessarily final yet
> Stream Transaction HTTP docs

- CHANGELOG
- js/common/modules/@arangodb/aql/explainer.js
Fix the order in which collections are dropped and created in a debugDump:
- collections with `distributeShardsLike` referring to prototype collections must be dropped first, before the prototypes are dropped
- collections with `distributeShardsLike` referring to prototype collections must be created after the prototypes are created
Also make the debugDump work with traversal queries that refer to multiple edge collections
> make the creation of debug packages smart graph-aware

- js/common/modules/@arangodb/aql/explainer.js
Fix the order in which collections are dropped and created in a debugDump:
- collections with `distributeShardsLike` referring to prototype collections must be dropped first, before the prototypes are dropped
- collections with `distributeShardsLike` referring to prototype collections must be created after the prototypes are created
Also make the debugDump work with traversal queries that refer to multiple edge collections
> make creating debug packages smart graph-aware

- Documentation/Books/Manual/Programs/Arangod/Server.md
- Documentation/Books/Manual/Programs/Arangosh/Examples.md
- Documentation/Examples/arangosh.json
- arangosh/Shell/ClientFeature.cpp
Internal refs:
- https://github.com/arangodb/planning/issues/3226
- https://github.com/arangodb/planning/issues/2783
**Note:**
Examples need to be generated and the arangosh.json file has to be committed for old Jenkins.
Possibly to be extended with additional options (VelocyStream?).
We may want to add a more detailed explanation to the [arangosh details page](https://docs.arangodb.com/devel/Manual/Programs/Arangosh/Details.html).
> Arangosh: server.endpoint must start with http+ssl:// if server uses SSL

- Documentation/Books/AQL/Functions/Document.md
- Documentation/Books/AQL/Functions/Numeric.md
- Documentation/Books/AQL/Functions/String.md
> Doc - Correct AQL function examples

- Documentation/Books/Manual/Deployment/StandaloneAgency/README.md
Changed documentation for standalone agency, set port of first agent to 8531, offset +10 for other agents for ArangoDB standard consistency
> Change standalone agency doc

- Documentation/Books/Manual/Programs/Arangod/Server.md
- Documentation/Books/Manual/Programs/Arangosh/Examples.md
- Documentation/Examples/arangosh.json
- arangosh/Shell/ClientFeature.cpp
Backport of https://github.com/arangodb/arangodb/pull/7329
> Doc - Arangosh: server.endpoint must start with http+ssl:// if server uses SSL

- js/common/modules/@arangodb/graph-examples/example-graph.js
> fix jslint inside example graph tests

- arangod/Aql/OptimizerRules.cpp
- tests/js/server/aql/aql-optimizer-rule-collect-in-cluster.js
This fixes the issue that the `collect-in-cluster` optimizer rule was applied even for single-shard collections, when it was pessimizing the plan.
> fix an issue, add tests

- arangod/RocksDBEngine/RocksDBOptimizerRules.cpp
- tests/js/server/aql/aql-optimizer-rule-reduce-extraction-to-projection-rocksdb.js
The optimizer rule "reduce-extraction-to-projection" may choose to turn a full scan into an index scan.
Make it honor any index hints given in the query.
> honor index hints in optimizer rule

- arangod/Agency/AgencyComm.cpp
sendWithFailover() not intended to be used directly or indirectly if arangod is running as an Agent.  There was no protection in the case of misuse.  This PR detects the problem and prevents a SEGFAULT.
> Bugfix:  Add protective barrier to sendWithFailover() in case MANAGER is nullptr

- CHANGELOG
- arangod/GeneralServer/GeneralCommTask.cpp
- tests/js/client/shell/shell-async-request.js
* Fix a crash when using the "x-arango-async" header for sending an async request and the server's request queue was full.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/4519/
> fix crash in async request handling when request queue is full

- arangod/Aql/ExecutionEngine.cpp
Fixes a test failure in api-export-spec-timecritical-noncluster.rb
> Make ExecutionEngine respect the batch size.

- CHANGELOG
- arangod/GeneralServer/GeneralCommTask.cpp
- js/client/tests/shell/shell-async-request.js
* Fix a crash when using the "x-arango-async" header for sending an async request and the server's request queue was full.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/4520/
> fix async request handling when server queue is full

- CHANGELOG
- arangod/RocksDBEngine/RocksDBIndexFactory.cpp
- js/apps/system/_admin/aardvark/APP/frontend/js/templates/indicesView.ejs
Only offer indexes of type "persistent" in the web UI when creating a new index with the RocksDB storage engine, and hide the previously shown index types "hash" and "skiplist".
This is because the implementation of the 3 index types is absolutely identical for the RocksDB engine, and offering 3 types with different names but identical implementation confuses end users.
In a previous iteration we only offered the "hash" index type in the web UI for RocksDB, but it turns out that this description wasn't a good choice, because the index is actually no hash index. "skiplist" doesn't match either, only "persistent" somehow adequately describes the index.
Additional documentation PR: …
> only offer indexes of type "persistent" in the web UI for the RocksDB engine

- CHANGELOG
- arangod/Aql/Aggregator.cpp
- tests/js/server/aql/aql-optimizer-collect-aggregate.js
Fixed an edge case of handling `null` values in the AQL function `MIN` for input sequences that started with a `null` value. 
In this case, `null` was always returned as the minimum value even though other non-null values may have followed, and `MIN`  was supposed to return `null` only if there are no input values or all input values are `null`.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/4552/
> fix handling of initial `null` values in AQL function `MIN`

- arangod/RestServer/CheckVersionFeature.cpp
- arangod/VocBase/Methods/Upgrade.cpp
Fix creation of VERSION files for new databases in the cluster, and make sure that `--database.check-version` does not choke on existing databases with a VERSION file.
This needs a manual test!
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/4581/
> fix VERSION files on upgrade and database creation in cluster

- CHANGELOG
This should be tagged as v3.4.6 without records related to v3.4.7!
> Add ArangoSearch notice and minor fix to v3.4.6

- lib/Basics/Common.h
Remove a define that slows down Windows debug builds considerably.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/4598/
> remove define that slows down Windows debug builds

- arangod/GeneralServer/GeneralCommTask.cpp
- arangod/GeneralServer/GeneralCommTask.h
- arangod/GeneralServer/HttpCommTask.h
- arangod/GeneralServer/VstCommTask.cpp
- arangod/GeneralServer/VstCommTask.h
- arangod/Scheduler/Scheduler.h
- arangod/Scheduler/SupervisedScheduler.cpp
- arangod/Scheduler/SupervisedScheduler.h
Exclude VST requests from direct execution on the IO thread.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/4580/
> exclude VST requests from direct execution

- arangod/GeneralServer/GeneralCommTask.cpp
Only execute requests directly in the scheduler if there is a single client for an IoContext.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/4602/
> only execute requests directly if there is one client on the IoContext

- js/server/assets/swagger/index.html
For some reason swagger-ui renders some text in code blocks in white on light background. This changes that text to be rendered in black instead.
> Fix white swagger code

- arangod/Aql/IndexHint.cpp
- arangod/Aql/IndexHint.h
Fix handling of AQL index hints on upgrading.
When upgrading a cluster from 3.4 to 3.5, the 3.5 DB server nodes will try to read index hint data from the AQL query plan snippets. They assume that the "hint" part of the snippet is an object, which is only guaranteed if the plan was generated by a 3.5 coordinator. 3.4 coordinators however don't populate the "hint" attribute in the plan at all, so it will not be an object here.
3.5 DB servers then can't find the attribute and crash with an assertion failure.
> fix processing of AQL index hints when upgrading

- arangod/ClusterEngine/ClusterSelectivityEstimates.cpp
- arangosh/Shell/V8ClientConnection.cpp
This is an attempt at fixing compilation errors when using `libstdc++` that comes with `gcc-9.1.0`; we just let GCC deduce the template parameter, which is a `std::shared_ptr` which is handled atomically (as opposed to the `fuerte::Connection` or `ClusterSelectivityEstimates::InternalData`).
If the intent is to handle the `Connection` or the `InternalData` atomically we need different changes, as the `atomic` operations require the type to be `TriviallyCopyable` which in particular means for it to not have any virtual members.
Disclaimer: I have no idea (tm) why this worked before (or, why it works now, if it did before).
> Fix some uses of atomics

- lib/Futures/Future.h
Following a warning I noticed when compiling with `gcc-9.1.0`.
> Remove std::move as it prevents copy elision

- lib/Basics/files.cpp
- tests/Basics/files-test.cpp
Attempt to fix the behavior of TRI_Dirname, which seems to do wrong things.
This PR adds tests that were used to verify all changes: tests/Basics/files-test.cpp
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/4707/
> fix dirname behavior

- arangod/Pregel/Conductor.cpp
- arangod/Pregel/Conductor.h
- arangod/Pregel/GraphStore.cpp
- arangod/Pregel/Iterators.h
- arangod/Pregel/TypedBuffer.h
* display elapsed time per gss, and not cumulative time since start
* fix uninitialized member in RangeIterator move constructor
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/4722/
> Bug fix 3.4/pregel micro improvements

- CHANGELOG
- lib/CMakeLists.txt
- lib/ProgramOptions/IniFileParser.h
- lib/ProgramOptions/Parameters.cpp
- lib/ProgramOptions/Parameters.h
- tests/Basics/InifileParserTest.cpp
- tests/CMakeLists.txt
Fixed parsing of ArangoDB config files with inlined comments. Previous versions didn't handle line comments properly if they were appended to an otherwise valid option value.
For example, the comment in the line
```
max-total-wal-size = 1024000 # 1M
```
was not ignored and made part of the value. In the end, the value was interpreted as if
```
max-total-wal-size = 10240001000000
```
was specified.
This version fixes the handling of comments in the config files so that they behave as intended.
Got aware of this problem while trying to reproduce https://github.com/arangodb/arangodb/issues/5414
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/4716/
> fix handling of comments in config files

- CHANGELOG
- lib/CMakeLists.txt
- lib/ProgramOptions/IniFileParser.h
- lib/ProgramOptions/Parameters.cpp
- lib/ProgramOptions/Parameters.h
- tests/Basics/InifileParserTest.cpp
- tests/CMakeLists.txt
Fixed parsing of ArangoDB config files with inlined comments. Previous versions didn't handle line comments properly if they were appended to an otherwise valid option value.
For example, the comment in the line
```
max-total-wal-size = 1024000 # 1M
```
was not ignored and made part of the value. In the end, the value was interpreted as if
```
max-total-wal-size = 10240001000000
```
was specified.
This version fixes the handling of comments in the config files so that they behave as intended.
Got aware of this problem while trying to reproduce https://github.com/arangodb/arangodb/issues/5414
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/4714/
> fix handling of comments in ini files

- js/client/modules/@arangodb/testing.js
remove i.e. `bin/arangobench` and try to run `scripts/unittest shell_server` - you will now get:
```
Error: unable to locate build-deb/bin/arangobench
================================================================================
TEST RESULTS
================================================================================
* Test "ALL"
[FAILED]  0
"test" failed: unable to locate build-deb/bin/arangobench
* Overall state: Fail
Marking crashy!
Suites failed: 1 Tests Failed: 1
2019-06-04T10:11:52Z [98874] ERROR [8a210] JavaScript exception in file 'UnitTests/unittest.js' at 337,3: peng!
2019-06-04T10:11:52Z [98874] ERROR [409ee] !  throw 'peng!';
2019-06-04T10:11:52Z [98874] ERROR [cb0bd] !  ^
``` …
> output setup failures to testfailures.txt

- arangod/V8Server/V8DealerFeature.cpp
Fix invalid & improperly checked string accesses when copying JS files at startup
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/4743/
> fix path length checks when copying js files

- CHANGELOG
- arangosh/Shell/ClientFeature.cpp
- arangosh/Shell/ClientFeature.h
Allow the shell to use a jwt secret stored in a file. This is useful for executing scripts in environments that do not allow interactive terminals.
> Added --server.jwt-secret-keyfile to arangosh.

- arangod/RestHandler/RestCursorHandler.cpp
- js/client/modules/@arangodb/arango-statement.js
- js/common/modules/@arangodb/arango-statement-common.js
- tests/js/client/shell/shell-statement.js
Allow specifying the "stream" attribute for streaming cursors also on the top level of requests to POST /_api/cursor
This change is already covered by existing tests, such as streaming cursor tests.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/4746/
> allow "stream" attribute on top level

- arangosh/Export/ExportFeature.cpp
Fix error messages in arangoexport.
Previously, when the server returned an HTTP 404 error, arangoexport unconditionally turned this error into a "collection not found" error, which may or may not be appropriate.
Instead, make it return the server's actual error message.
Additionally, move away from TRI_ERROR_INTERNAL.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/4784/
> fix error messages @matthewvon

- arangod/Aql/AqlItemMatrix.h
- arangod/Aql/ClusterNodes.h
- arangod/Cluster/ClusterComm.h
- arangod/Cluster/CriticalThread.h
- arangod/Cluster/HeartbeatThread.h
- arangod/Scheduler/Scheduler.h
- arangod/Utils/VersionTracker.h
- arangod/VocBase/LogicalView.h
don't include Logger.h in header files in case we don't need it.
This change is already covered by existing tests: compilation on all platforms
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/4788/
> don't include the Logger in header files if it's not necessary

- arangod/Aql/Ast.cpp
Normalize filter conditions so that attribute accesses are normally on the left hand side of the condition. This will turn `3 == doc.value` into `doc.value == 3`. This allows for future optimizations and easier handling of conditions.
Note that there will still be condition with attribute accesses on the right hand side, such as `doc.value1 == doc.value2`.
This change is already covered by existing tests, such as *all AQL tests*.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/4789/
> normalize AQL filter conditions, so that attribute accesses are normally placed on the left hand side of the condition

- CHANGELOG
- arangosh/Export/ExportFeature.cpp
Fix error messages in arangoexport.
Previously, when the server returned an HTTP 404 error, arangoexport unconditionally turned this error into a "collection not found" error, which may or may not be appropriate.
Instead, make it return the server's actual error message.
Additionally, move away from TRI_ERROR_INTERNAL.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/4810/
> Bug fix 3.4/fix arangoexport error messages

- CHANGELOG
- arangod/RocksDBEngine/RocksDBEngine.cpp
- arangod/RocksDBEngine/RocksDBEngine.h
- js/client/modules/@arangodb/testsuites/wal.js
- tests/js/client/wal_cleanup/wal-cluster-rocksdb.js
Remove archived RocksDB WAL files from the archive on agent servers. Previously WAL files were retained even agent servers due to an error.
Also added a test suite in this PR. The test suite needs separate activation in Jenkins so that it will run
`scripts/unittest wal_cleanup --storageEngine rocksdb --cluster true`
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/4821/
> remove archived RocksDB WAL files on agent servers

- arangod/RocksDBEngine/RocksDBEngine.cpp
- arangod/RocksDBEngine/RocksDBEngine.h
- js/client/modules/@arangodb/testsuites/wal.js
- tests/js/client/wal_cleanup/wal-cluster-rocksdb.js
Remove archived RocksDB WAL files from the archive on agent servers. Previously WAL files were retained even agent servers due to an error.
Also added a test suite in this PR. The test suite needs separate activation in Jenkins so that it will run
`scripts/unittest wal_cleanup --storageEngine rocksdb --cluster true`
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/4822/
> attempt to remove expired WAL files on agents

- arangod/RestHandler/RestReplicationHandler.cpp
- arangosh/Restore/RestoreFeature.cpp
* reorder collections when restoring them, so that system collections are restored first. This should fix potential issues when the restore operation stops in the middle due to other errors, which may leave a database around with some important system collections missing
* additionally turn off some enterprise functionality (replicationFactor "satellite", smartGraphAttribute, smartJoinAttribute, enterprise sharding strategies)
This change is already covered by existing tests, such as dump/restore tests.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/4696/
> Bug fix 3.4/improve arangorestore

- js/server/modules/@arangodb/aql-helper.js
- tests/js/server/aql/aql-graph-traverser.js
This enables it to be used in other tests, most notably the enterprise traverser tests which show the same floating point fluctuation problems as the community edition traverser tests.
There will be a PR on the enterprise edition that depends on this PR.
> Move roundCost function to utilities

- CHANGELOG
- arangod/Cluster/ClusterInfo.cpp
Backport of https://github.com/arangodb/arangodb/pull/9219
Add check in coordinator index creation process to verify that the index has not been dropped between polling attempts. Previously, this could result in the creation request hanging and timing out instead of recognizing that a simultaneous drop request had been made.
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/4802/
> [3.3] Add drop-check for index creation in cluster

- arangod/V8Server/v8-statistics.cpp
Allow internal contexts to access the statistics. I think REST requests using the `_system` database should get this context.
> Allow statistics for internal contexts.

- arangod/Agency/MoveShard.cpp
If a MoveShard job is in `pending` state and the collection it refers to is dropped, the lock on the `toServer` was not released.
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/4883/
> [3.3] MoveShard release Lock when collection dropped

- arangod/Agency/MoveShard.cpp
If a MoveShard job is in `pending` state and the collection it refers to is dropped, the lock on the `toServer` was not released.
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/4882/
> [3.4] MoveShard release Lock when collection dropped

- arangod/Agency/MoveShard.cpp
If a MoveShard job is in `pending` state and the collection it refers to is dropped, the lock on the `toServer` was not released.
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/4881/
> [devel] MoveShard release Lock when collection dropped

- js/client/modules/@arangodb/testsuites/gtest.js
This PR enables you to filter for gtest-cases the same way you would filter for jsunity testcases:
```
./scripts/unittest gtest --testCase 'InifileParserTest.test_options'
```
> adopt  option to do the right thing with gtests

- arangod/Cluster/ClusterInfo.cpp
When we try dropping a collection `A` for which there are other collections
that have distributeShardsLike set to `A`, mention this in the error message.
> Try improving error message

- arangod/Cluster/FollowerInfo.cpp
- arangod/Cluster/FollowerInfo.h
Added special lock for local data. Use read and write locking. Do not hold read lock during agency transactions.
This change is already covered by existing tests.
> FollowerInfo Lock during AgencyTRX

- arangod/Cluster/FollowerInfo.cpp
- arangod/Cluster/FollowerInfo.h
Added special lock for local data. Use read and write locking. Do not hold read lock during agency transactions.
This change is already covered by existing tests.
> [3.4] FollowerInfo Lock during AgencyTRX

- lib/Basics/RocksDBUtils.cpp
- lib/Basics/RocksDBUtils.h
Only assemble strings in `convertStatus` when actually necessary.
Additionally, remove the unused `prefix` and `postfix` parameters from the method.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/4941/
> only build the status messages if actually necessary

- js/client/modules/@arangodb/test-utils.js
- js/client/modules/@arangodb/testsuites/rspec.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/4943/
http://jenkins01.arangodb.biz:8080/job/arangodb-ANY-windows-matrix/237/
> fix the option to specify a ruby executeable from the outside in instead of leaning on rspec.bat to do its job (3.4)

- arangod/RocksDBEngine/RocksDBCollection.cpp
- arangod/RocksDBEngine/RocksDBTransactionCollection.cpp
- arangod/RocksDBEngine/RocksDBTransactionCollection.h
Do not buffer index estimates unnecessary
This change is already covered by existing tests, such as index testsuites
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/4961/
> do not buffer index estimates

- CHANGELOG
- arangod/Replication/ReplicationFeature.cpp
- arangod/Replication/ReplicationFeature.h
- arangod/RestHandler/RestReplicationHandler.cpp
- arangod/RestHandler/RestWalAccessHandler.cpp
- arangod/RocksDBEngine/RocksDBReplicationTailing.cpp
- lib/Basics/ScopeGuard.h
- tests/rb/HttpReplication/api-replication-global-spec.rb
Make it possible to limit the number of concurrently running WAL tailing operations.
This option can be used as a last resort to reduce the load put on a server by concurrently running WAL tailing invocations, e.g. from arangosync.
By default, the number of parallel invocations is not limited.
The PR also fixes assertions failure when WAL tailing is called with a `from` tick in the future, i.e. a `from` value that is not yet in the database. 
The changes were manually tested.
This change is already covered by existing replication tests.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/4967/
> make it possible to limit the number of parallel WAL tailing invocations

- arangod/ClusterEngine/ClusterIndex.cpp
- arangod/Indexes/SimpleAttributeEqualityMatcher.cpp
- arangod/Indexes/SortedIndexAttributeMatcher.cpp
- arangod/Indexes/SortedIndexAttributeMatcher.h
- arangod/MMFiles/MMFilesPersistentIndex.cpp
- arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
- arangod/RocksDBEngine/RocksDBPrimaryIndex.cpp
- arangod/RocksDBEngine/RocksDBVPackIndex.cpp
- tests/js/common/shell/shell-general-graph.js
Previously the edge index in RocksDB was assumed to have a value-lookup complexity of O(1), but all user-defined indexes (e.g. hash, skiplist) had an assumed lookup complexity of O(log n).
This almost always favored the edge index over used defined indexes, even though the user-defined indexes were more specific.
For example, a query such as
```
FOR doc IN edgeCollection
FILTER doc._from == @from && doc.other == @other
RETURN doc
```
will very likely have used the edge index even if a more specialized index on `["_from", "other"]` was available.
This PR assigns a complexity of O(log n) to edge index lookups in terms of optimizer assumptions.
Additionally, when determining which index to use for a given query, the optimizer will now try to take into account the number of filter conditions …
> don't unfairly favor the edge index when comparing it to more specialized indexes on `_from`/`_to` plus other attributes

- arangod/RestHandler/RestAnalyzerHandler.cpp
- arangod/V8Server/v8-analyzers.cpp
- tests/RestHandler/RestAnalyzerHandler-test.cpp
- tests/V8Server/v8-analyzers-test.cpp
- tests/js/common/aql/aql-view-arangosearch-cluster.inc
Fixed parsing json object encoded as string (like ``` "{ \"locale\": \"en.UTF-8\", \"stopwords\": [ ] }"``` ).
Fixed generating proper error message if analyzer properties could not be parsed into  json object.
https://jenkins.arangodb.biz/job/arangodb-matrix-pr/5005/
> Bug fix/fix cluster tests for analyzers

- arangod/Aql/IndexNode.cpp
Use `nextCovering` iterator method when range-scanning the RocksDB primary key.
This change is already covered by existing tests, such as AQL tests.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5010/
> use index projections when range-scanning the primary index and filtering on _key

- arangod/Scheduler/Scheduler.h
- arangod/Scheduler/SupervisedScheduler.cpp
- arangod/Scheduler/SupervisedScheduler.h
- arangod/Statistics/Descriptions.cpp
- arangod/Statistics/StatisticsWorker.cpp
Some statistics were not populated in current devel because of the refactored Scheduler code.
They were reported as "non-representable type" instead. This PR tries to bring back the statistics that were available in 3.4, at least for the metrics that are still available.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5027/
> fix JSON statistics for Scheduler

- 3rdParty/velocypack/include/velocypack/Builder.h
- 3rdParty/velocypack/include/velocypack/Compare.h
- 3rdParty/velocypack/include/velocypack/Serializable.h
- 3rdParty/velocypack/include/velocypack/Value.h
- 3rdParty/velocypack/include/velocypack/velocypack-aliases.h
- 3rdParty/velocypack/src/Compare.cpp
- 3rdParty/velocypack/src/Serializable.cpp
- arangod/RestHandler/RestRepairHandler.cpp
- lib/CMakeLists.txt
Update velocypack library from upstream repository arangodb/velocypack
This change is already covered by existing tests, such as *velocypack tests*, *arangodb tests*.
Additionally:
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5018/
> update velocypack version

- arangod/Agency/MoveShard.cpp
- arangod/Agency/Node.cpp
- arangod/Agency/Store.cpp
- arangod/Agency/Supervision.cpp
- arangod/Aql/Ast.cpp
- arangod/Aql/Functions.cpp
- arangod/Aql/QueryCache.cpp
- arangod/Cluster/ClusterInfo.cpp
- arangod/Indexes/Index.cpp
- arangod/Indexes/IndexFactory.cpp
- arangod/Replication/TailingSyncer.cpp
- arangod/RestServer/BootstrapFeature.cpp
- arangod/RocksDBEngine/RocksDBVPackIndex.cpp
- lib/Basics/VelocyPackHelper.cpp
- lib/Basics/VelocyPackHelper.h
- tests/Aql/AqlItemRowTest.cpp
- tests/Mocks/StorageEngineMock.cpp
Add `VelocyPackHelper::equal` method as shortcut for `VelocyPackHelper::compare(...) == 0`.
Calls to `compare` that checked for equality move been changed to call `equal`.
The `compare` method has been tagged with attribute `warn_unused_result` as well.
This change is already covered by existing tests, such as most tests that used compare before.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5032/
> add VelocyPackHelper::equal method

- arangod/Aql/DistinctCollectExecutor.cpp
- arangod/Aql/DistinctCollectExecutor.h
- arangod/Aql/ExecutionBlockImpl.cpp
Add `initializeCursor` method back to `DistinctCollectExecutor`. It existed in 3.4 but was missing in devel. It may be handy to free some temporary results and reduce overall memory usage.
This change is already covered by existing tests, such as *AQL collect tests*.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5028/
> add initializeCursor back to DistinctCollectExecutor

- arangod/RocksDBEngine/RocksDBCollection.cpp
Prevent a race when unloading the collection while using it
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/6616/
> Add lock on unload

- tests/IResearch/IResearchComparer-test.cpp
- tests/IResearch/IResearchViewSorted-test.cpp
Fix arangosearch tests that did not use env variable IRESEARCH_TEST_RESOURCE_DIR to determine the location for test files.
This change is already covered by existing tests, such as *arangosearch catch tests*.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5047/
> fix tests that didn't properly use env variable to look for test

- arangod/Agency/AgencyFeature.cpp
- arangod/IResearch/IResearchAnalyzerFeature.cpp
- arangod/IResearch/IResearchFeature.cpp
- arangod/MMFiles/MMFilesLogfileManager.cpp
- arangod/MMFiles/MMFilesLogfileManager.h
- lib/ApplicationFeatures/AQLPhase.cpp
- tests/IResearch/IResearchAnalyzerFeature-test.cpp
- tests/RestServer/FlushFeature-test.cpp
- rename iresearch analyzer feature
- ensure `MMFilesLogFileManager::SafeToUseInstance` is safe to use in multi-threaded context
> Bug fix/rename iresearch analyzer feature

- arangod/Cluster/FollowerInfo.cpp
- arangod/Transaction/Methods.cpp
- arangod/Transaction/Methods.h
* Remove superfluous warnings when a CAS operation fails when adding/dropping followers. The warnings are superfluous here because the operation is retried anyway, and if it finally fails there will be another warning.
* Remove redundant method for finding the most suitable index. Instead, use just one method for it.
This change is already covered by existing tests, such as *all AQL tests*.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5118/
> Bug fix/fixes 08 07 2019

- arangod/Aql/EngineInfoContainerDBServer.cpp
- arangod/Aql/EngineInfoContainerDBServer.h
- tests/Agency/MoveShardTest.cpp
Fix the infamous warning _During AQL query shutdown: Query ID ... not found on server:..._
Previously, one query snippet per collection would be made responsible for initializeCursor and shutdown. That doesn't work for views, as one snippet can hold multiple collections; because of that, multiple snippets can get responsible to initialize/shutdown the same parent.
Now, for each RemoteNode, one RemoteBlock is chosen to be responsible.
This change is already covered by existing tests, such as the `shell_server_aql` suite.
> Bug fix/fix snippet responsibility for views

- CHANGELOG
- arangod/Cluster/ClusterInfo.cpp
Discovered that some rocksdb error messages were not getting copied all the way to the client. The generic error number arrived, but not the specific error message. This updates code at the coordinator level to always report error messages retrieved from the agency updates.
[XX] Bug-Fix for at least devel and 3.4 ... considering 3.3
[XX ] The behavior in this PR can be (and was) manually tested (support / qa / customers can test it)
The behaviour change can only be verified via automatic tests
> BugFix 3.4: Some error results have messages that are not reporting

- arangod/Cluster/ClusterInfo.cpp
Discovered that some rocksdb error messages were not getting copied all the way to the client. The generic error number arrived, but not the specific error message. This updates code at the coordinator level to always report error messages retrieved from the agency updates.
[XX] Bug-Fix for at least devel and 3.4 ... considering 3.3
[XX ] The behavior in this PR can be (and was) manually tested (support / qa / customers can test it)
The behaviour change can only be verified via automatic tests
> BugFix 3.3:  Some error results have messages that are not reporting

- CHANGELOG
- arangod/Cluster/ClusterInfo.cpp
Discovered that some rocksdb error messages were not getting copied all the way to the client.  The generic error number arrived, but not the specific error message.  This updates code at the coordinator level to always report error messages retrieved from the agency updates.
- [XX] Bug-Fix for at least devel and 3.4 ... considering 3.3
- [XX ] The behavior in this PR can be (and was) *manually tested* (support / qa / customers can test it)
> BugFix:  Some error results have messages that are not reporting

- CHANGELOG
- arangod/Cluster/ClusterInfo.cpp
Discovered that some rocksdb error messages were not getting copied all the way to the client. The generic error number arrived, but not the specific error message. This updates code at the coordinator level to always report error messages retrieved from the agency updates.
[XX] Bug-Fix for at least devel and 3.4 ... considering 3.3
[XX ] The behavior in this PR can be (and was) manually tested (support / qa / customers can test it)
The behaviour change can only be verified via automatic tests
> BugFix 3.5:  Some error results have messages that are not reporting

- CHANGELOG
- arangod/Cluster/ActionBase.cpp
- arangod/Cluster/MaintenanceFeature.cpp
- arangod/Cluster/MaintenanceFeature.h
Prevent duplicate actions from popping up in the maintenance.
This change is already covered by existing tests, such as *all cluster DDL tests*.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5167/
> prevent duplicate actions from popping up

- 3rdParty/rocksdb/6.2/port/win/env_win.cc
Port bugfix made in upstream RocksDB repository for NowMicros function
What we will need to do is to test this version on Windows 7 & 10.
https://jenkins01.arangodb.biz/job/arangodb-ANY-windows-matrix/327/
> port fix for NowMicros

- CHANGELOG
- arangod/GeneralServer/HttpCommTask.cpp
- arangod/GeneralServer/SocketTask.cpp
- arangod/GeneralServer/SocketTask.h
This ports https://github.com/arangodb/arangodb/pull/9477/files to 3.5:
Actually use a keep-alive timeout in the documented way
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/5221/
> Port changes to fix the keep alive timeout

- CHANGELOG
- arangod/Cluster/ActionBase.cpp
- arangod/Cluster/MaintenanceFeature.cpp
- arangod/Cluster/MaintenanceFeature.h
Prevent duplicate DDL actions from popping up
This change is already covered by existing tests, such as *all cluster DDL tests*.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5213/
> bug-fix-3.5/fix-duplicate-actions

- arangod/Aql/EngineInfoContainerDBServer.cpp
- arangod/Cluster/ClusterInfo.cpp
- arangod/RestHandler/RestAdminLogHandler.cpp
Avoid a few copies
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5241/
> micro optimizations

- lib/Rest/HttpRequest.cpp
Currently "audit_client" testuite has a failing test  "testUnauthorized". This is due to an errornous behaviour change in the comm tasks that builds the _fullUrl_ property
This change is already covered by existing tests, such as the **audit_client** testsuite
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/5260/
> fix the audit client testsuite

- CHANGELOG
- arangosh/Import/ImportFeature.cpp
- arangosh/Import/ImportHelper.cpp
- arangosh/Import/SenderThread.cpp
- arangosh/Import/SenderThread.h
arangoimport would not report, or stop execution, on local communication errors.  This could leave a user believing import succeeded when actually many records might not have posted.
Communications errors for CSV import will now additionally report line numbers that were within the batch being posted.
> Bugfix: Import would not report communication errors

- CHANGELOG
- arangosh/Import/ImportFeature.cpp
- arangosh/Import/ImportHelper.cpp
- arangosh/Import/SenderThread.cpp
- arangosh/Import/SenderThread.h
from devel: https://github.com/arangodb/arangodb/pull/9494
arangoimport would not report, or stop execution, on local communication errors. This could leave a user believing import succeeded when actually many records might not have posted.
Communications errors for CSV import will now additionally report line numbers that were within the batch being posted.
... easy test is to import a CSV file that takes 15 or so minutes ... use this setting: --server.request-timeout 1 ... existing code will not fail. Check the number of lines imported versus number of lines in file. My sample file only import about 10% of the lines. New code will report error, stop, and list lines that were pending at time of failure.
> Bugfix 3.4: Import would not report communication errors

- CHANGELOG
Backport https://github.com/arangodb/arangodb/commit/85257fff271d18cb9a5a4c1b38178ee910625f3e to 3.5 to add info about the updated JavaScript dependencies (#8773).
> Add updated JS deps to changelog (#8773)

- CHANGELOG
- arangosh/Import/ImportFeature.cpp
- arangosh/Import/ImportHelper.cpp
- arangosh/Import/SenderThread.cpp
- arangosh/Import/SenderThread.h
from devel: #9494
arangoimport would not report, or stop execution, on local communication errors. This could leave a user believing import succeeded when actually many records might not have posted.
Communications errors for CSV import will now additionally report line numbers that were within the batch being posted.
... easy test is to import a CSV file that takes 15 or so minutes ... use this setting: --server.request-timeout 1 ... existing code will not fail. Check the number of lines imported versus number of lines in file. My sample file only import about 10% of the lines. New code will report error, stop, and list lines that were pending at time of failure.
> Bugfix 3.3: Import would not report communication errors

- CHANGELOG
- arangosh/Import/ImportFeature.cpp
- arangosh/Import/ImportHelper.cpp
- arangosh/Import/SenderThread.cpp
- arangosh/Import/SenderThread.h
from devel: #9494
arangoimport would not report, or stop execution, on local communication errors. This could leave a user believing import succeeded when actually many records might not have posted.
Communications errors for CSV import will now additionally report line numbers that were within the batch being posted.
... easy test is to import a CSV file that takes 15 or so minutes ... use this setting: --server.request-timeout 1 ... existing code will not fail. Check the number of lines imported versus number of lines in file. My sample file only import about 10% of the lines. New code will report error, stop, and list lines that were pending at time of failure.
> Bugfix 3.5: Import would not report communication errors

- arangod/GeneralServer/HttpCommTask.cpp
- arangod/Scheduler/SupervisedScheduler.cpp
Fix an uninitialized value
Fix a typo in a message
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5301/
> Bug fix/fix uninitialized value

- CHANGELOG
- arangod/Aql/CountCollectExecutor.h
- arangod/Aql/OutputAqlItemRow.h
- tests/Aql/CountCollectExecutorTest.cpp
- tests/Aql/RowFetcherHelper.cpp
- tests/Aql/RowFetcherHelper.h
- tests/js/server/aql/aql-optimizer-collect-count.js
CountCollect (e.g. `COLLECT WITH COUNT INTO ...` without group variables) now skips, rather than fetches, as it should.
I verified that the added tests would have catched the bug.
> Bug fix/count collect should skip

- CHANGELOG
- arangod/Cluster/ClusterInfo.cpp
- arangod/Cluster/ClusterInfo.h
- arangod/Cluster/ClusterMethods.cpp
Fix multiple possible races in cluster collection creation.
Before it was possible for concurrent operations to create a collection with the same name multiple times. The change now will acquire the current Plan and validate if a collection of the same name exists in it. It then tries to create the collection in the agency, using the retrieved plan version as a precondition. If a concurrent operation has updated the plan in between, the whole operation, including a new shard distribution, will be retried. The sleep time before a retry has been lower from 5 seconds to 100 milliseconds.
Additionally now two agency calls are saved for each collection creation.
Caveat: as we are using the previous plan version as a precondition when creating the collection, it is possible that this change …
> Bug fix 3.4/fix races in collection creation

- 3rdParty/iresearch/core/index/index_writer.cpp
- 3rdParty/iresearch/core/index/index_writer.hpp
- 3rdParty/iresearch/core/index/segment_writer.cpp
- arangod/IResearch/IResearchLink.cpp
- arangod/IResearch/IResearchRocksDBRecoveryHelper.cpp
Starting 806d56389cf rocksdb recovery helper for arangosearch doesn't handle removals correctly.
> bug-fix/internal-issue-#609.1: properly handle removals during recovery

- CHANGELOG
- arangod/Aql/EngineInfoContainerDBServer.cpp
- arangod/Aql/EngineInfoContainerDBServer.h
Fixed a query abort error for smart joins if both collections were restricted to a single shard using the "restrict-to-single-shard" optimizer rule.
Related enterprise PR: https://github.com/arangodb/enterprise/pull/276
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/5347/
> Bug fix 3.5/fix smart join restrictions

- CHANGELOG
- arangod/Aql/EngineInfoContainerDBServer.cpp
- arangod/Aql/EngineInfoContainerDBServer.h
- arangod/Aql/OptimizerRules.cpp
Fix a query abort error in case a smart join was used but both collections were restricted to a single shard using the "restrict-to-single-shard" optimizer rule.
Accompanying enterprise PR with test:
https://github.com/arangodb/enterprise/pull/274
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/5346/
> fix a query abort error in smart joins if both collections were

- arangod/Aql/EngineInfoContainerDBServer.cpp
- arangod/Aql/EngineInfoContainerDBServer.h
Fixed a query abort error for smart joins if both collections were restricted to a single shard using the "restrict-to-single-shard" optimizer rule.
Related enterprise PR: https://github.com/arangodb/enterprise/pull/275
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/5348/
> fixed an issue with smart joins if both collections were restricted to a

- arangod/Scheduler/SupervisedScheduler.cpp
Fixes undefined behavior when thread count climbs to 32 or higher.
Fixes the following UBSAN error:
```
arangod/Scheduler/SupervisedScheduler.cpp:320:34: runtime error: shift exponent 32 is too large for 32-bit type 'int'
``` 
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5361/
> fix undefined behavior in Scheduler calculations

- arangod/Indexes/IndexFactory.cpp
- arangod/MMFiles/MMFilesCollection.cpp
- arangod/MMFiles/MMFilesTtlIndex.cpp
- arangod/MMFiles/MMFilesTtlIndex.h
- arangod/RestServer/TtlFeature.cpp
- arangod/RocksDBEngine/RocksDBCollection.cpp
- arangod/RocksDBEngine/RocksDBTtlIndex.cpp
- arangod/RocksDBEngine/RocksDBTtlIndex.h
- tests/js/common/shell/shell-ttl.js
if a TTL index is already present on a collection, the previous behavior
was to make subsequent calls to `ensureIndex` fail unconditionally with
the error "there can only be one ttl index per collection".
now, we are comparing the attributes of the to-be-created index with the
attributes of the existing TTL index and make it only fail when the
attributes differ. if the attributes are identical, the `ensureIndex`
call succeeds and returns the existing index.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5366/
> make TTL indexes behave like other indexes on creation

- CHANGELOG
- arangod/Indexes/IndexFactory.cpp
- arangod/MMFiles/MMFilesCollection.cpp
- arangod/MMFiles/MMFilesTtlIndex.cpp
- arangod/MMFiles/MMFilesTtlIndex.h
- arangod/RestServer/TtlFeature.cpp
- arangod/RocksDBEngine/RocksDBCollection.cpp
- arangod/RocksDBEngine/RocksDBTtlIndex.cpp
- arangod/RocksDBEngine/RocksDBTtlIndex.h
- tests/js/common/shell/shell-ttl.js
if a TTL index is already present on a collection, the previous behavior
was to make subsequent calls to ensureIndex fail unconditionally with
the error "there can only be one ttl index per collection".
now, we are comparing the attributes of the to-be-created index with the
attributes of the existing TTL index and make it only fail when the
attributes differ. if the attributes are identical, the ensureIndex
call succeeds and returns the existing index.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5367/
> Bug fix 3.5/make ttl indexes behave like others

- CHANGELOG
- arangod/RestServer/DatabasePathFeature.cpp
- js/common/modules/@arangodb/foxx/store.js
- lib/ApplicationFeatures/TempFeature.h
Added startup error for bad temporary directory setting
If the temporary directory (`--temp.path`) setting is identical to the database directory (--database.directory) this can eventually lead to data loss, as temporary files may be created inside the temporary directory, causing overwrites of existing database files/directories with the same names.
Additionally the temporary directory may be cleaned at some point, and this would lead to an unintended cleanup of the database files/directories as well.
Now, if the database directory and temporary directory are set to the same path, there will be a startup error warning about potential data loss (though in ArangoDB 3.4 allowing to continue the startup - in 3.5 and higher we will abort the startup).
This change is a trivial rework / code …
> Added startup error for bad temporary directory setting.

- js/client/modules/@arangodb/testsuites/export.js
AES_set_encrypt_key() was changed to AES_set_decrypt_key() during debug.  It was not reverted before check-in and merge.  Change in enterprise branch reverts.
Change in this branch cleans up unit test that would periodically fail depending up on how often executed.
> bugfix-3.4:  Revert decrypt

- arangod/Aql/Functions.cpp
- tests/js/server/aql/aql-functions-string.js
Fix Github issue #9558
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5399/
> fixed a bug in RTRIM implementation, fixed issue #9558

- arangod/Statistics/StatisticsWorker.cpp
backport of https://github.com/arangodb/arangodb/pull/9581
> don't keep the memory stats in the collections to save disk space

- arangod/RocksDBEngine/RocksDBVPackIndex.cpp
Remove a non-optimization
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5447/
> remove an optimization that is none

- arangod/GeneralServer/CommTask.cpp
- arangod/GeneralServer/CommTask.h
- arangod/GeneralServer/HttpCommTask.cpp
This change is already covered by existing tests
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/5474/
> Add missing shared_from_this

- arangod/Cluster/ClusterInfo.cpp
- arangod/Cluster/ClusterInfo.h
- arangod/Cluster/v8-cluster.cpp
- tests/js/server/shell/shell-responsibleservers-cluster.js
Added internal function ClusterInfo::getResponsibleServers to atomically retrieve the current leaders for a given set of shard ids.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5489/
> added internal function getResponsibleServers()

- CHANGELOG
- arangod/Cluster/AgencyCallback.cpp
- arangod/Cluster/AgencyCallback.h
Fix agency callbacks waiting too long when they were already signaled
I think it is possible that the following sequence of events occurs:
1) agency callback is registered by main thread
2a) agency callback is executed, changes some state which should enable the DDL operation to proceed
2b) agency callback framework calls signal() on the callback's condition variable
3) main thread goes into AgencyCallback::executeByCallbackOrTime(timeout) and waits for the entire timeout
The problem here seems to be that the signal sent in 2b is before the main thread actually waits for being signaled. So the signal is effectively lost, and the main thread will wait for its full timeout, and then do the refetchAndUpdate for the callback. Which will finally work, however, the default timeout for the …
> fix agency callback dumbness

- CHANGELOG
- arangod/Cluster/AgencyCallback.cpp
- arangod/Cluster/AgencyCallback.h
- arangod/Cluster/ClusterInfo.cpp
Fix agency callbacks waiting too long when they were already signaled
I think it is possible that the following sequence of events occurs:
1) agency callback is registered by main thread
2a) agency callback is executed, changes some state which should enable the DDL operation to proceed
2b) agency callback framework calls signal() on the callback's condition variable
3) main thread goes into AgencyCallback::executeByCallbackOrTime(timeout) and waits for the entire timeout
The problem here seems to be that the signal sent in 2b is before the main thread actually waits for being signaled. So the signal is effectively lost, and the main thread will wait for its full timeout, and then do the refetchAndUpdate for the callback. Which will finally work, however, the default timeout for the …
> fix lagging agency callbacks

- tests/js/client/load-balancing/load-balancing-async-auth-cluster.js
- tests/js/client/load-balancing/load-balancing-async-noauth-cluster.js
make old load_balancing tests more deterministic
This change is already covered by existing tests, such as *load_balancing*.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5533/
> attempt to fix load_balancing tests in slow test environments

- 3rdParty/iresearch/core/utils/async_utils.cpp
- CHANGELOG
- tests/IResearch/Containers-test.cpp
this is a quick mitigation only, which reduces maximum wait time from 1
second to 100 milliseconds without changing other behavior.
the main problem of notifying pending writers without successfully
acquiring the required mutex still needs proper addressing.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5527/
> Bug fix 3.4/reduce arangosearch rwlock waits

- arangod/RestServer/arangod.cpp
- arangod/Scheduler/SupervisedScheduler.cpp
Fix undefined behavior when shifting signed 4 byte int 31 bits to the right
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5543/
> fix yet another undefined behavior

- CHANGELOG
- lib/ApplicationFeatures/EnvironmentFeature.cpp
It's time to re-add the check for `overcommit_memory=2`.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5565/
> Bug fix 3.4/re add overcommit memory 2 warning

- CHANGELOG
- lib/ApplicationFeatures/EnvironmentFeature.cpp
It's time to re-add the check for `overcommit_memory=2`.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5566/
> Bug fix 3.3/re add overcommit memory 2 warning

- CHANGELOG
- arangosh/Shell/V8ClientConnection.cpp
- arangosh/Shell/V8ClientConnection.h
make arangosh not fail the next operation if the previous operation was aborted by the end user.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5521/
> Bug fix 3.5/make arangosh reconnect

- CHANGELOG
- arangod/Cluster/AgencyCallback.cpp
- arangod/Cluster/AgencyCallback.h
- arangod/Cluster/ClusterInfo.cpp
Fix agency callbacks waiting too long when they were already signaled
I think it is possible that the following sequence of events occurs:
1) agency callback is registered by main thread
2a) agency callback is executed, changes some state which should enable the DDL operation to proceed
2b) agency callback framework calls signal() on the callback's condition variable
3) main thread goes into AgencyCallback::executeByCallbackOrTime(timeout) and waits for the entire timeout
The problem here seems to be that the signal sent in 2b is before the main thread actually waits for being signaled. So the signal is effectively lost, and the main thread will wait for its full timeout, and then do the refetchAndUpdate for the callback. Which will finally work, however, the default timeout for the …
> fix lagging AgencyCallbacks

- CHANGELOG
- arangod/Cluster/CreateCollection.cpp
- arangod/Cluster/FollowerInfo.cpp
- arangod/Cluster/FollowerInfo.h
- arangod/Cluster/ResignShardLeadership.cpp
- arangod/Cluster/ResignShardLeadership.h
- arangod/Cluster/UpdateCollection.cpp
- arangod/RestHandler/RestReplicationHandler.cpp
- arangod/RestHandler/RestReplicationHandler.h
During a controlled leader change (i.e. when the leader has stopped writes) the new leader can make assumptions about the state of other followers. In that case the new leader can assume that the old followers are in sync and directly place them into Current. 
However, the new leader has to inform the other followers that it has taken over leadership.
> [3.5.1] Fast Controlled Leaderchange

- arangod/Utils/CollectionNameResolver.cpp
- arangod/Utils/CollectionNameResolver.h
Simplify CollectionNameResolver a little bit
This change is already covered by existing tests, such as *all*.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5582/
> get rid of _resolvedNames and _nameLock

- arangod/Agency/AgencyComm.cpp
- arangod/Agency/AgencyComm.h
- arangod/Cluster/ClusterInfo.cpp
Less copying of vpack & other data in ClusterInfo::loadPlan()
This change is already covered by existing tests, such as *all cluster tests*.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5584/
> less copying in ClusterInfo::loadPlan()

- CHANGELOG
- arangod/Aql/Functions.cpp
- arangod/RocksDBEngine/RocksDBFulltextIndex.cpp
Improve error message for FULLTEXT AQL function
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5646/
> fixed issue #9679

- arangod/RocksDBEngine/RocksDBPrimaryIndex.cpp
- arangod/RocksDBEngine/RocksDBVPackIndex.cpp
Fixed error message "Invalid argument: assume_tracked is set but it is not tracked yet" when trying to write to the same keys in concurrent RocksDB transactions. This error will now be reported as a "Lock timeout" error, with error code 1200.
This change is already covered by existing tests, such as *document tests*.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5661/
> fix return codes for concurrent writes to same documents

- js/common/bootstrap/errors.js
- lib/Basics/errors.dat
- lib/Basics/voc-errors.cpp
- lib/Basics/voc-errors.h
In #9523, we re-used an old error code that was deleted in #9402. This mitigates that.
> Fixed error code to not re-use an old one

- arangod/RocksDBEngine/RocksDBEngine.cpp
- arangod/RocksDBEngine/RocksDBThrottle.h
The statistics from rocksdb were unknowingly focused upon "default" column family and therefore excluding values from the seven column families used by ArangoDB.  This PR updates several values such that they report the sum across the seven column families.  The corrected statistics are essential to performance measurement.
The current value of the RocksDBThrottle is a new statistic added in this PR.
Upon merge, the same code will go to devel, 3.5.x, and maybe 3.3 branches.
> Bugfix 3.4:  Clean up rocksdb getStatistics()

- arangod/Aql/ShortStringStorage.h
- arangod/RocksDBEngine/RocksDBEngine.cpp
- arangod/RocksDBEngine/RocksDBThrottle.h
The statistics from rocksdb were unknowingly focused upon "default" column family and therefore excluding values from the seven column families used by ArangoDB. This PR updates several values such that they report the sum across the seven column families. The corrected statistics are essential to performance measurement.
The current value of the RocksDBThrottle is a new statistic added in this PR.
From 3.4 branch.
> Bugfix:  Correct rocksdb statistics to report column family sums.

- CHANGELOG
- arangod/RocksDBEngine/RocksDBEngine.cpp
- arangod/RocksDBEngine/RocksDBThrottle.h
The statistics from rocksdb were unknowingly focused upon "default" column family and therefore excluding values from the seven column families used by ArangoDB. This PR updates several values such that they report the sum across the seven column families. The corrected statistics are essential to performance measurement.
The current value of the RocksDBThrottle is a new statistic added in this PR.
From 3.4 branch.
> Bugfix 3.5.1: Correct calculation of rocksdb statistics to be sum of column families

- CHANGELOG
- arangod/RocksDBEngine/RocksDBEngine.cpp
- arangod/RocksDBEngine/RocksDBThrottle.h
The statistics from rocksdb were unknowingly focused upon "default" column family and therefore excluding values from the seven column families used by ArangoDB. This PR updates several values such that they report the sum across the seven column families. The corrected statistics are essential to performance measurement.
The current value of the RocksDBThrottle is a new statistic added in this PR.
From 3.4 branch.
> Bugfix 3.3: Correct calculation of rocksdb statistics to be sum of column families

- tests/RocksDBEngine/ShaEventListener.cpp
Fix memory leaks in hotbackup tests
This change is already covered by existing tests, such as *hotbackup gtest*.
Additionally:
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5698/
> fix a leak in hotbackup tests

- UnitTests/unittest.js
- arangosh/Shell/ShellFeature.cpp
- arangosh/Shell/ShellFeature.h
- arangosh/Shell/V8ShellFeature.cpp
When the arangosh is exited using the exit() JavaScript functions,
there is no memory cleanup, and ASan reports several leaks.
Instead of calling man 3 exit() use man 2 _exit(), which performs
some cleanup before killing the process.
This change is already covered by existing tests, such as `scripts/unittest iihihhhf`.
Additionally:
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5699/
> use _exit instead of exit to prevent memory leaks

- arangod/RocksDBEngine/RocksDBIterators.cpp
- arangod/RocksDBEngine/RocksDBIterators.h
- arangod/RocksDBEngine/RocksDBPrimaryIndex.cpp
- arangod/RocksDBEngine/RocksDBPrimaryIndex.h
- arangod/RocksDBEngine/RocksDBVPackIndex.cpp
- arangod/RocksDBEngine/RocksDBVPackIndex.h
Make the runtime bool parameter that determines whether an iterator is a forward or a backward iterator a template parameter.
This should help with inlining and improve branch prediction in case many queries are run that are concurrently using a mix of forward and backward iteration.
This change is already covered by existing tests, such as *shell_server_aql, replication_sync*.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5720/
> make forward/reverse iteration a template parameter

- arangod/RocksDBEngine/RocksDBEngine.cpp
- lib/ApplicationFeatures/RocksDBOptionFeature.cpp
- lib/ApplicationFeatures/RocksDBOptionFeature.h
Honor user-defined values for `--rocksdb.max-write-buffer-number` if within an acceptable range (i.e. 9 or greater). Ignore values that don't make sense.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5762/
> issue #9654: make `--rocksdb.max-write-buffer-number` work

- CHANGELOG
- lib/Utilities/ShellBase.cpp
In ArangoDB 2.8 one could cut'n'paste code snippets including their `arangosh>` prefixes as seen here: 
https://www.arangodb.com/docs/stable/graphs.html#example-graphs
This wasn't possible anymore. This PR fixes that.
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/5750/
> fix pasting from the documentation

- arangod/RocksDBEngine/RocksDBCollection.cpp
Don't fill RocksDB caches on per-document truncate operation
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5706/
> dont fill cache on truncate

- CHANGELOG
- arangod/RocksDBEngine/RocksDBEngine.cpp
- lib/ApplicationFeatures/ApplicationServer.h
- lib/ApplicationFeatures/RocksDBOptionFeature.cpp
- lib/ApplicationFeatures/RocksDBOptionFeature.h
Honor user-defined values for `--rocksdb.max-write-buffer-number` if within an acceptable range (i.e. 9 or greater). Ignore values that don't make sense.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5764/
> issue #9654

- arangod/IResearch/IResearchLinkCoordinator.cpp
Fix an invalid static_cast during gtest execution.
This change is already covered by existing tests, such as *arangosearch gtests*.
Additionally:
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5768/
> Bug fix/fix invalid cast

- CHANGELOG
- arangod/Agency/MoveShard.cpp
- tests/Agency/MoveShardTest.cpp
Fixing bug in moveShard::abort. In the case the new leader has not confirmed in current, the from server is written back twice into the Plan.
Additionally:
> [3.4] Move Shard Bug 4567124

- CHANGELOG
- arangod/Agency/MoveShard.cpp
- tests/Agency/MoveShardTest.cpp
Fixing bug in moveShard::abort. In the case the new leader has not confirmed in current, the from server is written back twice into the Plan.
Additionally:
> [3.3] Move Shard Bug 4567124

- arangod/Pregel/Conductor.cpp
- arangod/Replication/InitialSyncer.cpp
- lib/Basics/FunctionUtils.cpp
- lib/Basics/FunctionUtils.h
Downgrade WARN messages to INFO level
because the failed operations will be retried and likely succeed later on.
Additionally, fix a compile warning for a potentially uninitialized
value in FunctionUtils.h. Finally, don't abort the server process if
the batch ping timer cannot be requeued in initial replication, as this
is not a critical error. Replication can still be retried, and even has
a chance to succeed without the batch ping timer being requeued.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5783/
> downgrade WARN messages to INFO level

- arangod/Scheduler/SupervisedScheduler.cpp
- arangod/Scheduler/SupervisedScheduler.h
Fix potential spurious wakeups in the scheduler which may make a thread act too early.
Not sure which side effects this had, but it looks fishy.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5807/
> fix potential spurious wakeups in scheduler code

- js/common/modules/@arangodb/aql/explainer.js
Show query string length and cacheability info in explainer
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5804/
> show query string length and cacheability in explain output

- CHANGELOG
- arangod/ClusterEngine/ClusterTransactionCollection.cpp
- arangod/ClusterEngine/ClusterTransactionCollection.h
- arangod/RestHandler/RestTransactionHandler.cpp
- arangod/Transaction/Manager.cpp
- arangod/Transaction/Manager.h
- lib/Futures/Promise.h
- tests/js/client/shell/shell-transaction.js
Enforce stricter limits for stream transactions
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5816/
> Enforce stricter transaction limits (#9740)

- arangod/Pregel/Conductor.cpp
Port a minor leftover change from devel to 3.5 that affects Pregel conductor.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5811/
> port change from devel by @danielhlarkin

- arangod/Aql/AqlFunctionFeature.cpp
Mark the AQL functions `FULLTEXT`, `NEAR`, `WITHIN` and `WITHIN_RECTANGLE` as cacheable, so they can be used in conjunction with the AQL query results cache (at least on single server).
Previously, these functions were marked as non-cacheable, because they accepted somewhat dynamic collection input which could not be tracked by the optimizer. However, this was changed with 3.4.0, and all these functions require the collection name to be specified unambiguously and for the optimizer to detect easily. Additionally, all of these functions are replaced at query planning time with appropriate index-accessing subqueries, whose results are cacheable normally.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/580 …
> mark AQL functions FULLTEXT, NEAR, WITHIN, WITHIN_RECTANGLE as cacheable

- arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
- arangod/RocksDBEngine/RocksDBFulltextIndex.cpp
- arangod/RocksDBEngine/RocksDBGeoIndex.cpp
- arangod/RocksDBEngine/RocksDBKey.cpp
- arangod/RocksDBEngine/RocksDBKey.h
- arangod/RocksDBEngine/RocksDBVPackIndex.cpp
- lib/Geo/Utils.cpp
- lib/Geo/Utils.h
Improve performance of non-intersection geo queries
This change is already covered by existing tests, such as existing integration tests in shell_server_aql
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/5854/
> Improve performance of non-intersection queries

- arangod/Cluster/ReplicationTimeoutFeature.cpp
- arangod/Cluster/ReplicationTimeoutFeature.h
- arangod/ClusterEngine/ClusterEngine.h
- arangod/MMFiles/MMFilesEngine.h
- arangod/RocksDBEngine/RocksDBEngine.h
- arangod/StorageEngine/StorageEngine.h
- tests/Mocks/StorageEngineMock.h
This PR makes the timeout for synchronous replication configurable, with a default considerably larger than the current one. In particular, it is chosen such that the normal failed-follower logic in the agency will kick in if the server stops responding (is actually dead) prior to the replication operation timing out on its own (in case the operation is just slow). Therefore, it is much less likely that we will react to a slow operation by considering the follower failed and triggering shard recovery.
Jenkins: http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/5855/
> Minimize unnecessary dropping of followers due to poorly set synchronous replication timeouts

- arangod/Cluster/FollowerInfo.cpp
- arangod/Cluster/SynchronizeShard.cpp
- arangod/Scheduler/SupervisedScheduler.cpp
Give up trying to persist follower info in agency for collections that have been dropped in the meantime. The previous implementation cycled forever, occupying one scheduler thread just with the retries.
Add try..catch for scheduler supervisor, and extend extend try..catch block scope for scheduler workers. Those threads should never be terminated with an exception failure but just continue running.
This change is already covered by existing tests, such as *scripts/unittest shell_client --cluster true*.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5840/
> Bug fix/multi bugs

- CHANGELOG
- arangod/StorageEngine/EngineSelectorFeature.cpp
Remove storage engine warning, as requested in planning/#4407
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/5861/
> remove now-obsolete warning

- CHANGELOG
- arangod/Cluster/FollowerInfo.cpp
- arangod/Cluster/SynchronizeShard.cpp
Give up trying to persist follower info in agency for collections that have been dropped in the meantime. The previous implementation cycled forever, occupying one scheduler thread just with the retries.
This change is already covered by existing tests, such as *scripts/unittest shell_client --cluster true*.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5843/
> Bug fix 3.4/multi bugs

- CHANGELOG
- lib/Basics/files.cpp
Don't create `arangosh_XXXXXX` directories anymore.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/5872/
> don't create `arangosh_XXXXXX` directories

- CHANGELOG
- arangod/Cluster/ReplicationTimeoutFeature.cpp
- arangod/Cluster/ReplicationTimeoutFeature.h
- arangod/ClusterEngine/ClusterEngine.h
- arangod/MMFiles/MMFilesEngine.h
- arangod/RocksDBEngine/RocksDBEngine.h
- arangod/StorageEngine/StorageEngine.h
- tests/IResearch/StorageEngineMock.h
This PR makes the timeout for synchronous replication configurable, with a default considerably larger than the current one. In particular, it is chosen such that the normal failed-follower logic in the agency will kick in if the server stops responding (is actually dead) prior to the replication operation timing out on its own (in case the operation is just slow). Therefore, it is much less likely that we will react to a slow operation by considering the follower failed and triggering shard recovery.
Jenkins: http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/5874/
> [3.4] Minimize unnecessary dropping of followers due to poorly set synchronous replication timeouts

- CHANGELOG
- arangod/Aql/IndexBlock.cpp
Fix issue #9794 
Affects only 3.4. 3.5 and devel work already due to a different implementation of the ExecutionBlocks.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5894/
> issue #9794: Limit with offset results in an infinite query that can't be cancelled

- CHANGELOG
- arangod/GeneralServer/SocketTask.cpp
Adjusted log level for message "keep alive timeout - closing stream!" from INFO to DEBUG.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5888/
> adjust log level for "closing stream" message

- CHANGELOG
- arangod/IResearch/IResearchFilterFactory.cpp
- tests/IResearch/IResearchFilterIn-test.cpp
- tests/IResearch/IResearchQueryIn-test.cpp
- tests/IResearch/IResearchQueryInRange-test.cpp
- tests/js/common/aql/aql-view-arangosearch-cluster.inc
- tests/js/common/aql/aql-view-arangosearch-noncluster.js
Fixed issue #9795.  Fixed NOT IN clause in ArangoSearch.
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/5907/
> Fixed issue #9795 Fixed NOT IN clause in ArangoSearch

- arangod/Cluster/ClusterComm.cpp
- arangod/Cluster/ClusterComm.h
- arangod/MMFiles/MMFilesCollection.cpp
- arangod/Replication/Syncer.cpp
- arangod/Scheduler/SupervisedScheduler.h
- arangod/VocBase/Methods/Collections.cpp
- lib/Basics/LocalTaskQueue.cpp
- lib/Basics/LocalTaskQueue.h
- lib/SimpleHttpClient/Callbacks.h
- lib/SimpleHttpClient/Communicator.cpp
- tests/Mocks/StorageEngineMock.cpp
Fix return value check for Scheduler::queue() and derived method
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/300
This change is already covered by existing tests, such as *compilation*.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/5935/
> fix return value checks

- arangod/Agency/Agent.cpp
Check the return code but ignore it explicitly.
> This fixes an earlier oversight.

- arangod/Cluster/ServerState.cpp
- arangod/Cluster/ServerState.h
Check for duplicate server endpoints registered in the agency in `/Current/ServersRegistered`.
Duplicate endpoints will be registered if more than one arangod instance is started with the sam value for startup option `--cluster.my-address`. This can happen unintentionally due to typos in the configuration, copy&paste remainders etc.
Inspired by a community Github issue: https://github.com/arangodb/arangodb/issues/9800
In case a duplicate endpoint is detected on startup, a warning will be written to the log, indicating which other server has already "acquired" the same endpoint.
Startup will *not* be aborted however, because I am unclear about whether there are situations when such configuration could be valid.
Manually tested.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/5949/
> check for duplicate server endpoints on cluster startup

- arangod/Cluster/ServerState.cpp
Fix handling of return value when reboot id cannot be retrieved from the agency
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/5946/
> fix return value when reboot id cannot be retrieved

- CHANGELOG
- arangod/RocksDBEngine/RocksDBPrimaryIndex.cpp
- tests/js/server/aql/aql-primary-index-noncluster.js
Fix Github issue #9862
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5963/
> fixed issue #9862

- arangod/RocksDBEngine/RocksDBBuilderIndex.cpp
Don't issue a warning when the RocksDB transaction log iterator indicates more data (TryAgain).
This change is already covered by existing tests, such as *background indexing tests*.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5973/
> don't issue a warning when transaction log iterator reports more data

- CHANGELOG
- arangod/Cluster/ClusterMethods.cpp
- tests/js/common/shell/shell-babies.js
Fix non-deterministic occurrences of "document not found" errors when doing multi-document lookups on a sharded collection with custom shard keys
This change is already covered by existing tests, such as *babies tests, but only partly covered*.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/5976/
> Bug fix 3.5/babies unknown shard

- CHANGELOG
- arangod/Cluster/ClusterMethods.cpp
- js/common/tests/shell/shell-babies.js
Fix non-deterministic occurrences of "document not found" errors when doing multi-document lookups on a sharded collection with custom shard keys
This change is already covered by existing tests, such as *babies tests, but only partly covered*.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/5978/
> fix non-deterministic occurrences of "document not found" errors

- arangod/Aql/IResearchViewNode.cpp
- arangod/IResearch/IResearchFeature.cpp
- tests/IResearch/IResearchFilterBoolean-test.cpp
- tests/IResearch/IResearchQueryMinMatch-test.cpp
- tests/IResearch/IResearchQueryPhrase-test.cpp
- tests/IResearch/IResearchQueryScorer-test.cpp
- tests/js/common/aql/aql-view-arangosearch-cluster.inc
- tests/js/common/aql/aql-view-arangosearch-noncluster.js
Made functions ANALYZER, BOOST and MIN_MATCH callable during optimization
Fixed determinig ArangoSearch filter volatility in cases of  non-deterministic function call in condition
Added tests.
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/5995/
> Fix for internal issue #633

- lib/Logger/LoggerFeature.cpp
Automatically turn values for deprecated startup option parameters  `--log.use-microtime` and `--log.use-local-time` into equivalent option values of the new, preferred option `--log.time-format`.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/6058/
> Automatically convert log startup options

- arangod/Transaction/Manager.cpp
Avoid seperate lookup plus follow-up insert/emplace operations for transactions.
Additionally add the transaction id and more location information to error messages which were previously undistinguishable.
@graetzer: I don't know the reason why previously we had seperated the find from the following emplace operation. Maybe the transaction object must not be created if it already exists in the map. 
In this case my PR will cause damage. Can you please double-check?
This change is already covered by existing tests, such as *cluster transaction tests*.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/6034/
> avoid lookup plus sequent insert/emplace for the fast path

- lib/SimpleHttpClient/Communicator.cpp
- lib/V8/v8-utils.cpp
- tests/js/server/replication/ongoing/replication-ongoing.js
- tests/js/server/replication/static/replication-static.js
- tests/js/server/replication/sync/replication-sync.js
- tests/rb/HttpInterface/api-view-arangosearch-spec-noncluster.rb
Clean up views in tests that forgot to.
Also set up the views in tests that require them, so that individual tests don't implicitly depend on their predecessors.
This change is already covered by existing tests, such as *the tests changed by this PR*.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/6074/
> drop views on test teardown

- CHANGELOG
- arangosh/Restore/RestoreFeature.cpp
- arangosh/Utils/ClientTaskQueue.h
Make arangorestore restore the `_users` collection at the very end only.
This is because updating documents in `_users` may change the credentials for the arangorestore user itself, which may lead to all follow-up requests by arangorestore being rejected with "authorized"/"forbidden" by arangod.
Also, if multiple databases are restored (`--all-databases` option), then the `_system` database will be restored last.
This change is already covered by existing tests, such as *dump/restore tests*.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/6024/
> restore _users collection at the very end only

- CHANGELOG
- arangod/RestHandler/RestIndexHandler.cpp
- arangod/RestHandler/RestVocbaseBaseHandler.cpp
- arangod/StorageEngine/TransactionState.h
- arangod/Transaction/Manager.cpp
Make smart graphs transaction-aware too.
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/308
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/6053/
> make smart graphs transaction-aware

- arangod/Aql/ExecutionPlan.cpp
- tests/js/server/aql/aql-optimizer-rule-remove-unnecessary-filters.js
- tests/js/server/aql/aql-profiler.js
Don't produce FILTER nodes for filter conditions that are known to be always false. Instead, produce a NoResultsNode.
Don't produce FILTER nodes for filter conditions that are known to be always true.
As a side effect, this may optimize certain queries that will not produce any results.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/6112/
> improve handling of FILTERs that are known to always produce true or false

- arangod/Agency/AgencyComm.cpp
- arangod/Cluster/ClusterInfo.cpp
- arangod/Cluster/HeartbeatThread.cpp
- arangod/MMFiles/MMFilesWalRecoverState.cpp
- arangod/RestHandler/RestReplicationHandler.cpp
- arangod/RestServer/DatabaseFeature.cpp
- arangod/RestServer/DatabaseFeature.h
- arangod/VocBase/Methods/Databases.cpp
- arangod/VocBase/Methods/Databases.h
- tests/IResearch/IResearchAnalyzerFeature-test.cpp
- tests/IResearch/IResearchFeature-test.cpp
- tests/IResearch/IResearchView-test.cpp
- tests/RestHandler/RestUsersHandler-test.cpp
- tests/RestServer/FlushFeature-test.cpp
- tests/V8Server/v8-analyzers-test.cpp
- tests/V8Server/v8-users-test.cpp
In case of duplicate name errors, report the name and type of the duplicate object, e.g. "duplicate database name 'xyz'".
This should help analyzing duplicate name errors in the future.
However, I was not able to fabricate duplicate name errors in devel. I was able to fabricate them in 3.4 and 3.5, but since the "atomic database creation" feature has been merged into devel, I can't think of a way to produce them any more.
Still, in devel it is possible that when concurrently creating & dropping databases with the same user, there is a race for the user's permissions, which can lead to spurious write-write conflicts that turn into a "precondition failed" error on the client level. These should be fixed by this PR by just retrying the failed update on the user permissions until a timeout is …
> Bug fix/harden database creation against duplicate name

- arangod/Aql/Ast.cpp
- arangod/Aql/ClusterNodes.cpp
- arangod/Aql/ExecutionPlan.cpp
- arangod/Aql/IResearchViewNode.cpp
- arangod/Aql/IResearchViewOptimizerRules.cpp
Handle K_SHORTEST_PATHS cases where it was forgotten.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/6139/
> handle K_SHORTEST_PATHS where it was forgotten

- CHANGELOG
- arangod/Cluster/ClusterInfo.cpp
- arangod/Cluster/HeartbeatThread.cpp
- arangod/MMFiles/MMFilesWalRecoverState.cpp
- arangod/RestHandler/RestReplicationHandler.cpp
- arangod/RestServer/DatabaseFeature.cpp
- arangod/RestServer/DatabaseFeature.h
- arangod/VocBase/Methods/Databases.cpp
- arangod/VocBase/Methods/UpgradeTasks.cpp
- tests/Cluster/ClusterInfo-test.cpp
- tests/IResearch/IResearchAnalyzerFeature-test.cpp
- tests/IResearch/IResearchFeature-test.cpp
- tests/IResearch/IResearchLinkCoordinator-test.cpp
- tests/IResearch/IResearchLinkHelper-test.cpp
- tests/IResearch/IResearchView-test.cpp
- tests/IResearch/IResearchViewCoordinator-test.cpp
- tests/IResearch/IResearchViewDBServer-test.cpp
- tests/RestHandler/RestAnalyzerHandler-test.cpp
- tests/RestHandler/RestUsersHandler-test.cpp
- tests/RestServer/FlushFeature-test.cpp
- tests/V8Server/v8-analyzers-test.cpp
- tests/V8Server/v8-users-test.cpp
Harden database creation against spurious "duplicate name" errors
that were caused by other parallel operations lazily creating required
system collections in the same database.
Problems can occur when during database creation some JS code runs
that attempts to create the same system collection that the "create database"
operation tries to create concurrently. There is a small window of overlap
here in which this can make database creation fail.
Additionally improve error messages in case an attempt of creating a database
object (database, collection, view) fails due to a "duplicate name" error.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/6126/
> Harden database creation against spurious "duplicate name" errors

- arangod/Aql/ExecutionPlan.cpp
- tests/js/server/aql/aql-optimizer-rule-remove-unnecessary-filters.js
- tests/js/server/aql/aql-profiler.js
Don't produce FILTER nodes for filter conditions that are known to be always false. Instead, produce a NoResultsNode.
Don't produce FILTER nodes for filter conditions that are known to be always true.
As a side effect, this may optimize certain queries that will not produce any results.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/6114/
> improve handling of FILTERs with constant expressions

- CHANGELOG
- arangosh/Import/ImportHelper.cpp
- arangosh/Import/QuickHistogram.h
- arangosh/Import/SenderThread.cpp
This is a back port of PR 9856 (3.4).
Existing latency report stated number of requests posted to db server. But there was not tracking of how many objects / records were contained in each request. This PR utilizes the unused statistic location and populates it with total count of objects within the requests.
> Bugfix 3.5: Add object counts to arangoimport latency

- arangod/RestHandler/RestCursorHandler.cpp
- arangod/RestHandler/RestIndexHandler.cpp
- arangod/RestHandler/RestVocbaseBaseHandler.cpp
- arangod/Transaction/Manager.cpp
- arangod/Transaction/Manager.h
- tests/Transaction/Manager-test.cpp
improve logging for cluster transactions, and make them more robust
don't make transaction operations fail immediately if they cannot
acquire the transaction lock instantly. it is somewhat expected that
sometimes the garbage collection comes in-between and acquires locks
for a short amount of time - this should not lead to failures in
other operations on the transaction
This change is already covered by existing tests, such as *cluster transaction tests*.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/6086/
> Bug fix 3.5/fix transaction errors

- arangod/Agency/AgencyStrings.h
- arangod/Cluster/ServerState.cpp
- arangod/Cluster/ServerState.h
This PR cleans up some bits in `arangod/ServerState.cpp`
* remove unused function `mkdir`
* remove some out of date (and out of place) comments
* move a function that tests for agency initialisation into a separate functions. This is mainly for readability.
This change is a trivial rework / code cleanup without additional test coverage,
this change is already covered by existing tests, such as *(please describe tests)*.
> Cleanup ServerState.cpp

- arangod/Aql/AstHelper.h
Fix an assert that is just wrong
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/6159/
> fix wrong assertion in AstHelper.h

- CHANGELOG
- arangod/Agency/Agent.cpp
- arangod/V8Server/v8-general-graph.cpp
Fixed undefined behavior when creating a smart graph in single server
Fixed output of `require("@arangodb/{smart|general}-graph")._listObjects()` function, which did not return the `_id` value of graphs correctly
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/303
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/5953/
> Bug fix 3.4/fix smart graph issues

- CHANGELOG
- arangod/Agency/AgencyFeature.cpp
- arangod/Agency/Agent.cpp
- arangod/RocksDBEngine/RocksDBEngine.cpp
- arangod/Statistics/StatisticsFeature.cpp
- arangod/Statistics/StatisticsFeature.h
This PR adds two independent changes, and a related Agency change:
- rocksdb Write Amplification is now calculated and reported with existing rocksdb statistics.  This is essential for judging impact of compactions (and changes to compaction options).
- StatisticsWorker has demonstrated a tendency to cause increased compactions which heavily impact throughput.  The new --server.statistics-history option allows just the StatisticsWorker portion of statistics to be disabled.  
- statistics are now active for Agency.  Previously AgencyFeature.cpp completely disabled statistics for an agent daemon.  The disabling code is removed.  StatisticsFeature.cpp now notices if the daemon is for an agent and automatically disables statistics-history to avoid current performance issues.
> Bugfix 3.4: Calculate Write Amplification / Flag to disable StatisticsWorker

- arangod/Agency/AgencyComm.h
- arangod/Aql/Expression.cpp
- arangod/Cluster/ClusterComm.cpp
- arangod/Cluster/ClusterInfo.cpp
- arangod/Cluster/ClusterMethods.cpp
- arangod/Cluster/FollowerInfo.h
- arangod/Replication/ReplicationApplier.cpp
- arangod/RestHandler/RestCollectionHandler.cpp
- arangod/RestHandler/RestCursorHandler.cpp
- arangod/RestHandler/RestReplicationHandler.cpp
- arangod/RestServer/ConsoleThread.cpp
- arangod/RestServer/ScriptFeature.cpp
- arangod/RestServer/arangod.cpp
- arangod/Transaction/Methods.cpp
- arangod/Utils/SingleCollectionTransaction.cpp
- arangod/Utils/SingleCollectionTransaction.h
- arangod/V8Server/v8-vocbase.cpp
- lib/Rest/VstResponse.h
- tests/HotBackup/HotBackupCoordinatorTest.cpp
- tests/IResearch/IResearchAnalyzerFeature-test.cpp
Don't use assertion failures when an unknown collection/shard is used in a transaction, but throw an exception instead - so that issues can be investigated easier.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/6148/
> don't assert/crash when using an unknown collection/shard

- scripts/quickieTest.sh
This is nowadays needed to enable cluster health checks in testing.js.
> Switch on Supervision in quickietest.

- arangod/Aql/ConstrainedSortExecutor.cpp
- js/server/modules/@arangodb/aql-profiler-test-helper.js
- tests/js/server/aql/aql-profiler.js
- tests/js/server/aql/aql-queries-optimizer-sort-limit.js
These are strictly additional tests for the constrained heap sort in AQL. Motivated by https://github.com/arangodb/arangodb/pull/9981 mainly to have some more tests for sort-limit with fullCount.
> Additional sort-limit tests

- CHANGELOG
- arangod/Aql/OptimizerRule.h
- arangod/Aql/OptimizerRules.cpp
- tests/js/server/aql/aql-queries-optimizer-sort-limit.js
Bug-fix for the AQL optimizer rule `sort-limit`. It allowed too many types of nodes for nodes between the `SORT` and `LIMIT` node, which enabled the constrained sort strategy for nodes that must not use it.
> Bug fix/sort limit rule too lax

- arangod/Cache/Manager.cpp
Added assertions to the cache manager, making sure the memory usage value it tracks internally does not go below the expected minimum allocation value.
There was a [bug in the memory accounting](https://github.com/arangodb/arangodb/pull/10028) previously that led to an underflow of the `_globalAllocation` value, which was fixed by @danielhlarkin. 
This PR makes sure the bug will not happen again.
This change is already covered by existing tests, such as *edge cache tests*.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/6328/
> add assertions for Cache memory usage not underflowing its minimal usage

- CHANGELOG
- arangod/Aql/ExecutionNode.h
- arangod/Aql/ExecutionPlan.cpp
- arangod/Aql/ExecutionPlan.h
- arangod/Aql/OptimizerRules.cpp
- arangod/Aql/SortingGatherExecutor.cpp
- arangod/Aql/SortingGatherExecutor.h
- tests/js/server/aql/aql-profiler-cluster.js
- tests/js/server/aql/aql-profiler.js
- tests/js/server/aql/aql-queries-optimizer-sort-limit-cluster.js
- tests/js/server/aql/aql-queries-optimizer-sort-limit.js
Avoid overfetch in SortingGather. Related to #9981. Error was noticed in a test in #9395.
Also disables the sort-limit, if both in cluster and fullCount is enabled for the query. This will be addressed in another PR, because the fix for SortingGather will be more complicated.
This change is already covered by existing tests, such as `tests/js/server/aql/aql-queries-optimizer-sort-limit.js`.
> Avoid overfetch in sorting gather executor

- arangod/Cluster/ClusterInfo.cpp
- arangod/Cluster/ClusterInfo.h
> [3.4] Removed erroneous noexcept specifier for rebootIds() accessor

- 3rdParty/velocypack/src/Slice.cpp
Try to improve comparion speed a bit for Slice::get(...) using binary search, try to improve string comparisons as well.
This change is already covered by existing tests, such as *almost all ArangoDB tests*.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/6405/
> improve binary search a bit, improve string comparisons

- CHANGELOG
- lib/Basics/files.cpp
make sure that we don't get more than one leading directory separator in front of the path, so windows doesn't mistakenly look it up as a UNC.
verify time used to run `arangosh --version` - if takes longer than a second, an UNC may be triggered and timed out.
> Fix windows path handling not to slip into UNC lookup

- arangod/Aql/AqlTransaction.cpp
- arangod/Aql/EngineInfoContainerDBServerServerBased.cpp
- arangod/Aql/Query.cpp
- arangod/Aql/Query.h
- arangod/Cluster/TraverserEngine.cpp
- arangod/Replication/ReplicationApplierConfiguration.cpp
- arangod/Transaction/Methods.h
Fix `skipInaccessible` in AQL queries. This was broken due to new query snippet planning code.
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/327
This change is already covered by existing tests, such as *authentication*.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/6443/
> fix skipInaccessible

- arangod/Aql/QueryOptions.cpp
- arangod/Aql/QueryOptions.h
Remove an unused attribute from query plan serialization
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/6448/
> remove unused AQL attribute

- arangod/Aql/ExecutionBlock.cpp
- arangod/Aql/RemoteExecutor.cpp
- arangod/Aql/RemoteExecutor.h
- arangod/Aql/RestAqlHandler.cpp
Add additional information to AQL query tracing, to make it easier to follow a query, especially in a cluster. This affects `profile >= 3` only: These levels are not documented and only used for debugging.
This change is already covered by existing tests, such as `shell_server_aql`.
> Improved query tracing, especially useful for cluster queries

- arangod/Agency/AgencyFeature.h
- lib/ApplicationFeatures/ApplicationServer.h
Use a static_cast instead of a dynamic_cast to save runtime performance in release mode
This change is already covered by existing tests, such as *full test suite*.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/6449/
> use static_cast instead of dynamic_cast

- utils/generateExamples.sh
Backport of #9932 
An additional check if the binary exists (because it's not there in v3.5.0) shouldn't be necessary, as the v3.5.0 tag does not include this change.
> Docs: Dump program options of arangobackup as well

- CHANGELOG
- arangod/Aql/Functions.cpp
- js/common/modules/@arangodb/aql/explainer.js
- tests/js/server/aql/aql-functions-list.js
Fix Github issue #10062 
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/6402/
> fixed issue #10062: AQL: Could not extract custom attribute

- arangod/VocBase/Methods/Databases.cpp
- tests/js/client/authentication/auth-analyzer.js
Fix LDAP tests that were broken since atomic database creation feature merge.
All LDAP tests in devel were broken. 3.5 was not affected.
This change is already covered by existing tests, such as *all LDAP tests*.
https://jenkins01.arangodb.biz/view/3.devel/job/arangodb-devel-matrix-nightly/200/
> fix broken LDAP tests

- js/apps/system/_admin/aardvark/APP/aardvark.js
Attempt to fix wrong replication mode displayed in replication UI, described in https://github.com/arangodb/planning/issues/3410
It is unclear whether this PR will actually help anything, but it shouldn't make things worse.
*This change is a trivial rework / code cleanup without any test coverage.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/6508/
> attempt to improve replication UI in edge cases

- arangod/Agency/StoreCallback.cpp
- arangod/Aql/IResearchViewExecutor.cpp
- arangod/Cluster/ClusterMethods.cpp
- arangod/IResearch/IResearchAnalyzerFeature.cpp
- arangod/VocBase/Methods/UpgradeTasks.cpp
Fix the log ids that were fucked up by two teams.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/6529/
> fix broken & duplicate logIds

- arangod/Aql/IResearchViewExecutor.cpp
- arangod/Cluster/ClusterMethods.cpp
- arangod/IResearch/IResearchAnalyzerFeature.cpp
- arangod/VocBase/Methods/UpgradeTasks.cpp
Fix broken log ids
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/6530/
> fix logIds

- 3rdParty/velocypack/include/velocypack/Buffer.h
Use malloc/realloc/free instead of new/delete.
This is a test to see if using realloc upon increasing the size of a Buffer will help us avoid many reallocations (and copying data) for larger Buffers.
Additionally:
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/6496/
> use malloc/realloc/free in velocypack::Buffer

- lib/Basics/FileUtils.cpp
can be manually validated on windows using 
`arangosh --version  --log.level config=trace `
> make sure we don't build paths that start with two \'s

- arangod/V8Server/V8DealerFeature.cpp
- arangosh/Shell/V8ShellFeature.cpp
- lib/Basics/FileUtils.cpp
- tests/js/client/permissions/copy-installation.js
- tests/js/client/server_permissions/test-copy-installation.js
When copying js files at startup, there can be problems when copying symlinks.
All these symlinks are in .bin subdirectories, and we can just ignore them while copying.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/6563/
> ignore files in .bin when copying js files

- lib/Basics/FileUtils.cpp
Reverts arangodb/arangodb#10144
```
$ ./arangosh.exe --version --log.level config=trace
{config} checking root location '\'
{config} checking config file 'c:\Users\Вадим\Desktopetcrelativearangosh.conf'
{config} checking config file '\etc\arangodb3arangosh.conf'
{config} checking config file 'c:\Users\Вадим\Desktoparangosh.conf'
{config} checking config file 'C:\Users\Вадим.arangodbarangosh.conf'
{config} checking config file '\etc\arangodb3arangosh.conf'
{config} cannot find any config file
{config} checking override '.local'
{config} no override file found
{config} loading ''
```
Trace looks a little bit weird. It seems we removed too much.
> Revert "make sure we don't build paths that start with two \'s"

- arangod/Aql/Condition.cpp
- arangod/Aql/Condition.h
- arangod/Aql/Functions.cpp
- arangod/Aql/IndexNode.cpp
- arangod/Aql/Query.cpp
- arangod/Aql/Query.h
- arangod/Aql/RestAqlHandler.cpp
- arangod/Aql/RestAqlHandler.h
- arangod/Aql/TraversalConditionFinder.cpp
- arangod/Aql/TraversalNode.cpp
- arangod/Aql/TraversalNode.h
- lib/Basics/AttributeNameParser.cpp
Use std::unique_ptr instead of raw pointers to make ownership more transparent.
Reorder members in aql::Query to reduce space waste.
However, the AQL tests should continue to work just fine.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/6570/
> cleanup some of the internal APIs a bit

- arangod/Aql/tokens.cpp
- arangod/Aql/tokens.ll
- tests/js/server/aql/aql-parse.js
Properly report parse errors for extraneous unterminated string literals at the end of AQL query strings.
For example, in the query `RETURN 1 "abc`, the `RETURN 1` was parsed fully, and the `"abc` part is only parsed partly and then forgotten. But as the `RETURN 1` is already a proper query, the unterminated string literal at the end was not reported.
This PR fixes this, also for unterminated single quoted string literals and unterminated multi-line comments.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/6577/
> Bug fix/fix parsing unterminated strings

- CHANGELOG
- arangod/Aql/tokens.cpp
- arangod/Aql/tokens.ll
- tests/js/server/aql/aql-parse.js
Properly report parse errors for extraneous unterminated string literals at the end of AQL query strings.
For example, in the query `RETURN 1 "abc`, the `RETURN 1` was parsed fully, and the `"abc` part is only parsed partly and then forgotten. But as the `RETURN 1` is already a proper query, the unterminated string literal at the end was not reported.
This PR fixes this, also for unterminated single quoted string literals and unterminated multi-line comments.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/6578/
> Bug fix 3.5/fix parsing unterminated strings

- arangod/Aql/IndexExecutor.cpp
- arangod/Aql/IndexExecutor.h
Removed `union CallbackMethod` in IndexExecutor. It's members are `std::function`s, which aren't trivially destructible. While in this specific case it was probably of no consequence, the destructors of the members were not called, and this can leak memory.
As the memory is not problematic here, it seems safest to just use two separate members, rather than always destructing manually. An `std::variant` would be a viable alternative, too.
> Replace union by separate members

- 3rdParty/fuerte/include/fuerte/types.h
- 3rdParty/fuerte/src/types.cpp
Fix generating examples via `utils/generateExamples.sh`.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/6596/
> fix generating examples

- 3rdParty/iresearch/core/search/conjunction.hpp
- 3rdParty/iresearch/core/search/phrase_iterator.hpp
IResearch. Do not seek again if you did it (an iterator has already been moved).
Issue: https://github.com/arangodb/arangodb/issues/10090
phrase_iterator.hpp contains the issue fix.
conjunction.hpp contains optimizations.
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-linux/8270/
> Fixed repeatable seek to the same document

- arangod/Aql/OptimizerRulesFeature.cpp
This PR just adds a comment that the `subquery-splicing` optimizer must run last if enabled (and why) to prevent people from stumbling over this.
> Add a comment that subquery splicing should run last

- arangod/Aql/RestAqlHandler.cpp
- arangod/GeneralServer/RestHandler.h
Decrease payload size for some lambdas
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/6592/
> decrease payload size of some lambdas

- lib/Basics/HashSet.h
Don't prematurely manipulate state in HashSet on insert/emplace.
Only modify the state after the insert/emplace operation has succeeded.
If insert/emplace threw an exception, the hash set was potentially broken beforehand. This PR should fix thas situation.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/6619/
> don't taint hash set if insert/emplace fails for whatever reason

- Documentation/DocuBlocks/Rest/Views/post_api_view_arangosearch.md
Follow-up PR to #9597, also see #9822
- Double line-breaks break indention
> ArangoSearch refactor (part 2)

- arangod/Aql/DependencyProxy.cpp
Fix an error we've seen occasionally during PR tests in `api-simple-modify-example-cluster-spec.rb`. `DependencyProxy::skipSome` did not work correctly with multiple dependencies if `atMost` was reached, returning `DONE` early.
*(or)*
*(or)*
- Did you add tests for a new *RestHandler* subclass ?
- Did you add new mocks of underlying code layers to be able to verify your functionality ? 
- ...
> Bugfix for recurring Jenkins error in api-simple-modify-example-cluster-spec.rb

- arangosh/Import/ImportFeature.cpp
Fix an arangoimport output issue reported in #10183. The other problem reported (data is imported into the wrong database) is not fixed by this PR, as I wasn't able to reproduce.
This change is already covered by existing tests, such as *scripts/unittest importing*.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/6629/
> fixed issue #10183: Arangoimport imports on _system when you try to create a new database

- arangosh/Export/ExportFeature.cpp
- arangosh/Export/ExportFeature.h
- js/client/modules/@arangodb/testsuites/export.js
- lib/Basics/files.cpp
- tests/js/server/export/export-setup-cluster.js
- tests/js/server/export/export-setup.js
Make arangoexport enclose CSV values that contain line breaks in `"`.
This change is already covered by existing tests, such as *scripts/unittest export*.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/6644/
> fixed issue #10193

- CHANGELOG
- arangod/GeneralServer/GeneralServer.cpp
Remove debug log messages "found comm task... " that could occur on server shutdown.
This only applies to 3.5. The log message is not present in devel or 3.4.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/6640/
> remove debug logging

- CHANGELOG
- arangosh/Export/ExportFeature.cpp
- arangosh/Export/ExportFeature.h
- js/client/modules/@arangodb/testsuites/export.js
- lib/Basics/files.cpp
- tests/js/server/export/export-setup-cluster.js
- tests/js/server/export/export-setup.js
Make arangoexport enclose CSV values that contain line breaks in `"`.
This change is already covered by existing tests, such as *scripts/unittest export*.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/6643/
> Bug fix 3.5/issue 10193

- arangod/RestHandler/RestDocumentHandler.cpp
- arangod/RestHandler/RestEdgesHandler.cpp
- arangod/RestHandler/RestGraphHandler.cpp
- arangod/RestHandler/RestImportHandler.cpp
- arangod/RestHandler/RestVocbaseBaseHandler.cpp
- arangod/RestHandler/RestVocbaseBaseHandler.h
- arangod/Transaction/Methods.cpp
This bug is about:
```js
conspire = function() {
let theories = [
"docker", "ubuntu", "k8s", "json", "vst", "c#", "javascript", "collectd", 
"sleep", "satellite collections", "gyp", "lto", "macos", "smart joins",  
"el cheapo", "v8", "salat", "windows", "transactions", "oskar", "fuerte",
"ccache", "libmusl"
];
let conspiracy = {};
while (Object.keys(conspiracy).length < 3) {
conspiracy[theories[Math.floor(Math.random() * theories.length)]] = true;
}
return Object.keys(conspiracy);
};
print("It is caused by:", conspire().join(" + "));
```
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/6646/
> fix random willi bug

- CHANGELOG
- arangod/Aql/tokens.cpp
- arangod/Aql/tokens.ll
- tests/js/server/aql/aql-parse.js
Properly report parse errors for extraneous unterminated string literals at the end of AQL query strings.
For example, in the query `RETURN 1 "abc`, the `RETURN 1` was parsed fully, and the `"abc` part is only parsed partly and then forgotten. But as the `RETURN 1` is already a proper query, the unterminated string literal at the end was not reported.
This PR fixes this, also for unterminated single quoted string literals and unterminated multi-line comments.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/6579/
> Bug fix 3.4/fix parsing unterminated strings

- arangosh/Utils/ManagedDirectory.cpp
the effect can be observed when using arangoimp for a file in i.e. `~`, it will then recurse through the whole home.
> don't scan the specified directory recursively 

- lib/Logger/LoggerFeature.cpp
As suggested by Omar: https://github.com/arangodb/docs/pull/177
To be backported to 3.5 at least.
Open questions:
- What other protocols aside from `file://` are supported?
- How do paths look like on Windows?
- Linux seems to be `file://` + `/absolute/path/file.ext`
- Windows `file://` + ???
> Doc - Added "log-output" example

- CHANGELOG
- arangod/Aql/DependencyProxy.cpp
- tests/js/server/aql/aql-skipping-cluster.js
Backport of https://github.com/arangodb/arangodb/pull/10190.
Note that the situation where this bug appears can never arise in 3.5. Though there is actually no bug to be fixed, this is just to be on the safe side.
> [3.5] Fix AQL skip in cluster sometimes causing documents to be forgotten

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/manifest.json
This fixes a longstanding regression in 3.x that broke search in the document editor in code view. The browser search doesn't work in ACE and the JSON Editor uses a searchbox extension that for some reason needs to be loaded dynamically via a hardcoded path. This PR simply maps that path to the file it's looking for.
I've reported this issue internally before.
> [3.5] Fix document search (Ctrl+F/Cmd+F)

- 3rdParty/fuerte/src/HttpConnection.cpp
- 3rdParty/fuerte/src/message.cpp
- 3rdParty/fuerte/src/vst.cpp
- lib/Rest/VstResponse.cpp
Fix response content-type
This change is already covered by existing tests, such as the http_server suite
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/6692/
> Fix content-type for JS APIs

- js/common/modules/@arangodb/replication-common.js
- tests/js/server/replication/aql/replication-aql.js
- tests/js/server/replication/fuzz/replication-fuzz-global.js
- tests/js/server/replication/fuzz/replication-fuzz.js
- tests/js/server/replication/ongoing/32/replication-ongoing-32.js
- tests/js/server/replication/ongoing/frompresent/32/replication-ongoing-frompresent-32.js
- tests/js/server/replication/ongoing/frompresent/replication-ongoing-frompresent.js
- tests/js/server/replication/ongoing/global/replication-ongoing-global.js
- tests/js/server/replication/ongoing/global/spec/replication-ongoing-global-spec.js
- tests/js/server/replication/ongoing/replication-ongoing.js
- tests/js/server/replication/random/replication-random.js
- tests/js/server/replication/static/replication-static.js
- tests/js/server/replication/sync/replication-sync.js
The resilient testsuites family frequently disconnects from leader / follower to work out test states. 
This may lead to instability in tests if the system fails to connect in one of these reconnects.
Known popular reasons for failing connects are IP-Port shortages. 
To circumvent testfailure this PR will re-attempt connecting to the SUT after an increasing grace period several times. 
Example of such a failed testrun:
```
2019-10-11T14:45:18.866Z [ RUN        ] testChangeCollection1_Repl
2019-10-11T14:45:20.653Z [     PASSED ] testChangeCollection1_Repl (setUp: 7ms, test: 1515ms, tearDown: 265ms)
2019-10-11T14:45:20.654Z [ RUN        ] testChangeCollection2_Repl
2019-10-11T14:45:52Z [10128] ERROR [9d7ea] Could not connect to endpoint 'tcp://127.0.0.1:10033', username: 'replicator-user' …
```
> when changing between leader and follower re-attempt connecting to circumvent OS resource shortages

- tests/RocksDBEngine/ShaEventListener.cpp
Fix a leak in hot backup gtests. Backport of b6d1058eb059cdcc014583925a57d94b40e86d29
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/6719/
> fix leak in hot backup tests

- arangod/V8Server/V8DealerFeature.cpp
- arangosh/Shell/V8ShellFeature.cpp
Fix possible string length underflow when `--javascript.copy-installation` was used for arangosh
This change is already covered by existing tests, such as *scripts/unittest permissions --test copy-installation*.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/6761/
> fix underflow in copying code

- CHANGELOG
- arangod/Aql/Ast.cpp
- arangod/Aql/Ast.h
- arangod/Aql/AstNode.h
- arangod/Aql/grammar.cpp
- arangod/Aql/grammar.y
- tests/js/server/aql/aql-graph-traverser.js
Disallow the usage of subqueries in AQL traversal PRUNE conditions, as they caused undefined behavior.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/6703/
> disallow subqueries in AQL traversal PRUNE conditions

- js/client/modules/@arangodb/result-processing.js
- js/client/modules/@arangodb/test-utils.js
if readTestResult isn't able to load or parse results, its likely we derived an error message which we shouldn't overwrite; instead append our failure.
> Fix testresult

- Documentation/DocuBlocks/Rest/Indexes/post_api_index_fulltext.md
- Documentation/DocuBlocks/Rest/Indexes/post_api_index_hash.md
- Documentation/DocuBlocks/Rest/Indexes/post_api_index_persistent.md
- Documentation/DocuBlocks/Rest/Indexes/post_api_index_skiplist.md
- Documentation/DocuBlocks/Rest/Indexes/post_api_index_ttl.md
Parameters are named wrong
http://jenkins01.arangodb.biz:8080/view/Documentation/job/arangodb-ANY-examples/402/
> fix docublocks parameter naming

- arangod/Aql/RemoteExecutor.cpp
- arangod/Aql/SharedQueryState.cpp
- arangod/Aql/SharedQueryState.h
Two bugs were introduced in devel (namely in #10077 and #10206):
- The `shared_ptr` to the SharedQueryState wasn't captured in the callback executed by fuerte
- The same callback's execution wasn't protected by the SharedQueryState any longer
> Avoid a race and a use-after-free bug in the RemoteExecutor

- 3rdParty/fuerte/include/fuerte/connection.h
- 3rdParty/fuerte/src/HttpConnection.cpp
- 3rdParty/fuerte/src/VstConnection.cpp
- 3rdParty/fuerte/src/requests.cpp
- 3rdParty/fuerte/src/vst.cpp
- lib/Futures/Future.h
- lib/Futures/Promise.h
- lib/Futures/SharedState.h
Move move operation under critical section, to avoid undefined behavior when spurious wakeups occur and the waiting thread may continue with a half-ready, half-uninitialized object.
:crossed_fingers: 
This change is already covered by existing tests, such as *scripts/unittest shell_server_aql --cluster true*.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/6791/
> Bug fix/some future massaging

- js/apps/system/_admin/aardvark/APP/frontend/js/views/clusterView.js
Don't show "NaN" in web interface for cluster RAM usage if statistics are disabled or otherwise not available. Instead, display "n/a".
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/6789/
> don't show "NaN" in web interface for cluster RAM usage

- CHANGELOG
- arangod/Aql/Graphs.cpp
- arangod/Aql/TraversalNode.cpp
- arangod/Aql/TraversalNode.h
- js/client/modules/@arangodb/testsuites/rspec.js
- lib/ApplicationFeatures/RocksDBOptionFeature.cpp
- lib/Basics/FileUtils.cpp
- lib/Basics/files.cpp
- lib/Basics/tri-zip.cpp
Backport of https://github.com/arangodb/arangodb/pull/10073
* make sure that we don't get more than one leading directory separator in front of the path, so windows doesn't mistakenly look it up as a UNC.
> Fix windows path handling not to slip into UNC lookup (#10073)

- arangod/CMakeLists.txt
- lib/CMakeLists.txt
Add a depedency so error files get (re)built when arangod is built.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/6790/
> make sure error files get built when arangod is built

- js/common/bootstrap/errors.js
- lib/Basics/errors.dat
- lib/Basics/voc-errors.cpp
- lib/Basics/voc-errors.h
Fix error message
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/6785/
> fix error message

- 3rdParty/fuerte/src/HttpConnection.cpp
- 3rdParty/fuerte/src/http.cpp
- 3rdParty/fuerte/src/http.h
Avoid temporary strings & copying when url-encoding and url-decoding parameters in fuerte.
If fuerte request header parameters are used (soonish, will be introduced by PR https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/6826/), the url-encoding and decoding code in this PR will be tested implicitly.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/6827/
> url-encode and -decode in place

- 3rdParty/iresearch/CMakeLists.txt
- [x ] Strictly *new functionality* (i.e. a new feature / new option, no need for porting)
- [ x] The behavior in this PR can be (and was) *manually …
> make ccache optional

- js/server/modules/@arangodb/aql-helper.js
Only modifies test code.
Supposed to fix: a randomly and seldomly failing test case in devel, because of non-exact matching index estimates.
Jenkins
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/6860/
> TestFix: Rounding inconvenience in selectivity Estimates

- arangod/Agency/Agent.cpp
- arangod/Agency/Agent.h
- arangod/Agency/Constituent.cpp
- arangod/Agency/Constituent.h
- arangod/Agency/Supervision.cpp
- arangod/Agency/Supervision.h
- arangod/Graph/Graph.cpp
- arangod/Graph/Graph.h
- arangod/Graph/GraphOperations.cpp
- arangod/Graph/GraphOperations.h
- arangod/VocBase/Methods/Collections.cpp
- arangod/VocBase/Methods/Collections.h
Avoid copying strings in several cases
However, existing tests should pass.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/6880/
> avoid string copies in several cases

- arangod/Auth/TokenCache.cpp
- arangod/Auth/TokenCache.h
Some micro optimizations
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/6874/
> Bug fix/micro optimize auth

- 3rdParty/velocypack/src/Builder.cpp
Set `_pos` properly when creating a Builder from a shared_ptr<Buffer>
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/6895/
> set `_pos` when creating a Builder using a shared_ptr<Buffer>

- arangosh/Shell/V8ClientConnection.cpp
So far we would not identify buffers in the arangosh fuerte wrappers. 
This pr copies this behaviour from JS_Download at https://github.com/arangodb/arangodb/blob/devel/lib/V8/v8-utils.cpp#L732
This request will send the actual content after the patch instead of `repr` from text.
```
arango.POST("/_api/version", require("fs").readFileSync("/tmp/somefile.txt"))
```
Future versions of the Foxx tests will rely on this fix.
> identify buffers and handle them appropriate

- lib/Basics/overload.h
- tests/Basics/overload-test.cpp
- tests/CMakeLists.txt
Add template class `overload` to allow for convenient usages of `std::visit`.
> Added overload template

- 3rdParty/fuerte/src/HttpConnection.cpp
- 3rdParty/fuerte/src/connection.cpp
- arangosh/Shell/V8ClientConnection.cpp
This masks the ugly "Connection reset by peer" errors that occur if a user operation is carried out in arangosh on a connection that was already closed by the peer.
Instead of throwing the error in the user's face, the shell will silently try to reconnect and execute the operation once again. If that still fails, the error is propagated.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7003/
> make arangosh automatically reconnect if the server closes the connection

- arangod/CMakeLists.txt
- arangod/IResearch/IResearchAnalyzerCollectionFeature.cpp
- arangod/IResearch/IResearchAnalyzerCollectionFeature.h
- arangod/RestServer/arangod.cpp
Always create potentially missing `_analyzers` collection on startup. This fixes an issue with not being able to create that collection during regular cluster upgrades.
The collection is created in all databases.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7014/
> always create `_analyzers` collection if missing

- arangod/Aql/Expression.cpp
- arangod/Aql/OptimizerRules.cpp
Added assert that verifies that no V8 stuff will be used when there is early-pruning.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7023/
> added an assert

- arangod/CMakeLists.txt
- arangod/IResearch/IResearchAnalyzerCollectionFeature.cpp
- arangod/IResearch/IResearchAnalyzerCollectionFeature.h
- arangod/RestServer/arangod.cpp
Always create potentially missing `_analyzers` collection on startup. This fixes an issue with not being able to create that collection during regular cluster upgrades.
The collection is created in all databases.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7016/
> Bug fix 3.5/always create analyzers collection 35

- js/apps/system/_admin/aardvark/APP/frontend/js/views/collectionsItemView.js
- js/apps/system/_admin/aardvark/APP/frontend/js/views/documentView.js
- js/apps/system/_admin/aardvark/APP/frontend/js/views/documentsView.js
- js/apps/system/_admin/aardvark/APP/frontend/js/views/indicesView.js
- js/apps/system/_admin/aardvark/APP/frontend/js/views/infoView.js
- js/apps/system/_admin/aardvark/APP/frontend/js/views/settingsView.js
- js/apps/system/_admin/aardvark/APP/frontend/scss/_tiles.scss
We do allow very long collection names, but they cannot be displayed properly in the web UI's navigation. So truncate the display at 64 characters. Collection names are ASCII-only, so it is ok to truncate at an arbitrary byte offset.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7035/
> truncate displayed collection names in web UI at 64 chars

- arangod/Aql/ExecutionEngine.cpp
- arangod/Aql/RestAqlHandler.cpp
- arangod/RestServer/BootstrapFeature.cpp
- tests/js/server/aql/aql-failures-cluster.js
Improve cluster query shutdown in case there are multiple coordinator snippets, and shutdown fails.
Query shutdown can fail, for example, when the root query snippet on the coordinator sends the shutdown requests to the DB server(s), but these cannot be reached. In this case, any additional query snippets from the same query may remain active until they are TTL-killed.
This is a problem especially when there are multiple coordinator snippets from the same query. These should be cleaned up ASAP, and it should be possible as we are on the coordinator already when we are performing the shutdown.
So in case shutdown goes wrong, we will now go over all coordinator snippets and kill them explicitly. …
> try to improve query shutdown in case DB server(s) can't be reached

- 3rdParty/iresearch/core/index/index_writer.cpp
- CHANGELOG
Fixed applying consolidation results with pending removals on commit.
Flush procedure checks existing removals for consolidated segments before applying pending removals
Fix is verified by IResearch unit-tests
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/7041/
> Fix ArangoSearch consolidation results commit (3.5 backport)

- 3rdParty/iresearch/core/index/index_writer.cpp
- CHANGELOG
Fixed applying consolidation results with pending removals on commit.
Flush procedure checks existing removals for consolidated segments before applying pending removals
Fix is verified by IResearch unit-tests
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/7040/
> Fix ArangoSearch consolidation results commit  (3.4 backport)

- tests/js/server/aql/aql-subquery.js
Make cluster AQL test work with a variable number of db servers
This change is already covered by existing tests, such as *scripts/unittest shell_server_aql --cluster true*.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7082/
> make test work with more than 2 db servers

- CHANGELOG
- js/server/modules/@arangodb/foxx/manager.js
This never worked in the cluster and is not used in single server.
> Remove unneeded upsert of system services to _app.

- arangod/Aql/Ast.cpp
- tests/js/server/aql/aql-subquery.js
Micro optimization
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7081/
> yet another micro-optimization

- arangod/GeneralServer/HttpCommTask.cpp
Fix use-after-free error and wrong behavior for HTTP 100 Continue case.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7112/
> fix use-after-free for HTTP 100 Continue case

- js/actions/api-cluster.js
Permissions for `rebalanceShards` where messed. Previously only a rebalancing of the `_system` database was possible. And only for admin users.
> Fixed wrong permissions for rebalanceShards.

- CHANGELOG
- arangod/Agency/AgencyFeature.cpp
- scripts/startLeaderFollower.sh
- scripts/startLocalCluster.sh
Originally this PR was intended to change the default value for `--agency.supervision-grace-period` for active failover setups.
However, it turned out not to be possible to set the grace period based on the deployment mode on agency startup, as the agency is not aware of the deployment mode.
So what's left in this PR is a bit of cleanup, and the actual relevant change is in the documentation PR: https://github.com/arangodb/docs/pull/215
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7109/
> Something about `--agency.supervision-grace-period`

- arangod/Indexes/Index.cpp
Put index type name into exception error message for easier debugging.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7156/
> show type of index when non-implemented exception is thrown

- arangod/Indexes/Index.cpp
Put index type name into exception error message for easier debugging.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7157/
> show index type in not implemented exception

- arangod/Aql/OptimizerRules.cpp
This change is already covered by existing tests, such as shell_server_aql.
Jenkins: http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/7152/
> Don't modify a finalized node.

- arangod/Aql/Ast.cpp
- arangod/Aql/Ast.h
Centralize redundant code that was used by both AstNode::clone and AstNode::shallowCopyForModify
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7165/
> centralize cloning functionality for AstNodes

- CHANGELOG
- arangod/Aql/Functions.cpp
- tests/js/server/aql/aql-functions-string.js
Allow usage of `RANDOM_TOKEN` AQL function with an argument value of `0`.
This produces an empty string now, whereas in previous versions of ArangoDB it threw an invalid value exception.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7141/
> allow using `RANDOM_TOKEN` AQL function with an argument value of `0`.

- arangod/Transaction/Methods.cpp
Fix an invalid assertion that is triggered during testing.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7160/
> fix invalid assertion

- arangod/IResearch/IResearchView.cpp
- arangod/IResearch/IResearchViewCoordinator.cpp
- arangod/MMFiles/MMFilesCollection.cpp
- arangod/RestHandler/RestIndexHandler.cpp
- arangod/RocksDBEngine/RocksDBCollection.cpp
- arangod/RocksDBEngine/RocksDBEngine.cpp
- arangod/Transaction/Methods.cpp
- arangod/Transaction/Methods.h
- arangod/VocBase/LogicalCollection.cpp
- arangod/VocBase/LogicalDataSource.cpp
- arangod/VocBase/LogicalDataSource.h
- tests/js/common/shell/aql-index-usage-rocksdb.js
Don't consider in-progress indexes when determining the set of available indexes to be used for AQL queries. It seems that at least in the cluster such indexes could be shown and considered useful for supporting AQL queries.
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/358
Also added a new test for this.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7168/
> Bug fix/dont use indexes in progress

- arangod/IResearch/IResearchView.cpp
- arangod/IResearch/IResearchViewCoordinator.cpp
- arangod/MMFiles/MMFilesCollection.cpp
- arangod/RestHandler/RestIndexHandler.cpp
- arangod/RocksDBEngine/RocksDBCollection.cpp
- arangod/RocksDBEngine/RocksDBEngine.cpp
- arangod/Transaction/Methods.cpp
- arangod/Transaction/Methods.h
- arangod/VocBase/LogicalCollection.cpp
- arangod/VocBase/LogicalDataSource.cpp
- arangod/VocBase/LogicalDataSource.h
- tests/js/common/shell/aql-index-usage-rocksdb.js
Don't consider in-progress indexes when determining the set of available indexes to be used for AQL queries. It seems that at least in the cluster such indexes could be shown and considered useful for supporting AQL queries.
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/357
Also added a new test for this.
> don't return any in-progress indexes

- arangod/Agency/AgencyFeature.cpp
- arangod/RocksDBEngine/RocksDBEngine.cpp
- arangod/Statistics/StatisticsFeature.cpp
- arangod/Statistics/StatisticsFeature.h
Added `--server.statistics-history` startup option to devel. This option was present in 3.5 but missing in devel.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7184/
> added missing option `--server.statistics-history`, which was present in 3.5

- 3rdParty/iresearch/core/index/index_writer.cpp
- CHANGELOG
Fixed applying consolidation results with pending removals on commit.
Flush procedure checks existing removals for consolidated segments before applying pending removals
Fix is verified by IResearch unit-tests
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/7039/
> Fix ArangoSearch consolidation results commit

- arangod/Aql/InsertModifier.h
- arangod/Aql/ModificationExecutorHelpers.cpp
- arangod/Aql/RemoveModifier.h
- arangod/Aql/SimpleModifier.cpp
- arangod/Aql/SimpleModifier.h
- arangod/Aql/UpdateReplaceModifier.h
- arangod/Aql/UpsertModifier.cpp
- arangod/Aql/UpsertModifier.h
Fix some more cppcheck complaints
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/359
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7174/
> more cppcheck

- CMakeLists.txt
- README
- utils/generateREADME.sh
Don't make the generation of README rely on `html2text` and `markdown` executables.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7101/
> don't make generation of README rely on html2text & markodwn executables

- arangod/IResearch/IResearchFilterFactory.cpp
Added braces to make condition more explicit and remove gcc warning
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/7234/
> Add braces

- lib/Basics/crc1.S
- lib/Basics/crc4.S
- lib/Basics/crc5.S
Handwritten assembly files trigger executable stack section because the lack a signaling section that they do not require stack segment to be executable.
If a binary has an executable stack can be checked via `execstack <binary>`. If the output contains a `X` in front of the filename the binary has a executable stack. Otherwise it is listed with `-`.
Alternatively use `readelf -l <binary>`.
> Prevent executable stacks

- arangod/Cluster/HeartbeatThread.cpp
- arangod/Replication/ReplicationApplierConfiguration.cpp
- arangod/Replication/ReplicationFeature.cpp
- arangod/Replication/ReplicationFeature.h
- tests/js/common/replication/replication.js
This targets *3.5.4*.
Make replication timeouts configurable via startup options.
The following options are available (for active failover and master-slave replication):
```
--replication.connect-timeout
--replication.request-timeout
```
Values can be specified in seconds. If these options are used, they will be used for replication requests, overriding any hard-coded defaults or explicitly configured timeouts.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7252/
> make replication timeouts configurable via startup options

- arangod/GeneralServer/VstCommTask.cpp
When using OpenSSL reading and writing are concurrent operations as both call into OpenSSL and one might need to write before one can read and vice versa. Thus this needs to be synchronized.
> SSL Vst CommTask

- tests/js/server/aql/aql-view-arangosearch-server.js
Made test testRemoveIndexOnCreationFail  tolerant to links present in test database before  test run.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/7263/
> Made test tolerant to leftover links from previous test-runs

- arangod/Aql/SubqueryEndExecutor.cpp
- tests/Aql/SubqueryEndExecutorTest.cpp
If a subquery was spliced, and did not get any input rows, the SubqueryEnd
executor still expected a relevant ShadowRow to be handed through, and ran into
an assertion (or otherwise crashed the server) if it didn't get one.
> Fix bug in SubqueryEndExecutor

- arangod/Aql/RestAqlHandler.cpp
We observed the following crash occasionally in devel:
```
[Current thread is 1 (LWP 16044)]
#0  a_crash () at ./arch/x86_64/atomic_arch.h:108
#1  abort () at src/exit/abort.c:29
#2  0x00007f5dc7b433b9 in __gnu_cxx::__verbose_terminate_handler () at /home/buildozer/aports/main/gcc/src/gcc-9.2.0/libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00007f5dc7af6195 in __cxxabiv1::__terminate (handler=<optimized out>) at /home/buildozer/aports/main/gcc/src/gcc-9.2.0/libstdc++-v3/libsupc++/eh_terminate.cc:47
#4  0x00007f5dc7b43087 in __cxa_call_terminate (ue_header=ue_header@entry=0x7f5d8f62b4a0) at /home/buildozer/aports/main/gcc/src/gcc-9.2.0/libstdc++-v3/libsupc++/eh_call.cc:54
#5  0x00007f5dc7af5dd6 in __cxxabiv1::__gxx_personality_v0 (version=<optimized out>, actions=6, …
```
> Catch exceptions in noexcept methods

- arangosh/Shell/V8ClientConnection.cpp
- arangosh/Shell/V8ClientConnection.h
- actually remember connection error messages we got from the remote
- add server error to connection failure logmessage (usefull when running arangosh noninnteractive with i.e. permission problems
- throw anonymous exception in stringify() if we don't have an instance, this happenes when invoked via PrintObject()
- throw meaning full error messages if methods are invoked in the wrong way.
- connect an arangosh to a non existant arangod, or a non existant database. You should see a proper error message, when interactive and when invoked via script execution function
- invoking `global` at the prompt shouldn't output errors
> fix arangosh error message handling.

- arangod/Transaction/Methods.cpp
Fix truncate operation in synchronous replication.
Previously, when sending the HTTP PUT /_api/collection/<collection>/truncate, an empty body was sent with the request.
This lead to a parse error on the follower, which was then always dropped.
This PR sends an empty object instead of a completely empty body, so the followers can parse the request and subsequently can carry out the truncate operation.
This doesn't affect 3.5.
This change is already covered by existing tests, such as *many tests, e.g. dump*.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7303/
> fix truncate operation in synchronous replication

- arangod/Aql/SubqueryStartExecutor.cpp
fetchRow must not be called with `atMost == 0`, which can happen if
output.numRowsLeft() == 1.
> Fix SubqueryStartExecutor

- arangod/Aql/EngineInfoContainerDBServerServerBased.cpp
- arangod/Aql/ExecutionEngine.cpp
- arangod/Aql/ExecutionEngine.h
- arangod/Aql/Query.cpp
- arangod/Aql/RestAqlHandler.cpp
- lib/Basics/StaticStrings.cpp
- lib/Basics/StaticStrings.h
This fixes a rolling upgrade issue 3.5.* -> devel
During upgrade the AQL should be performed in 3.5 format, this has not been forwarded correctly inside the DBServers.
Jenkins:
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7282/
> Actually use the given format to execute a query

- arangod/Utils/CollectionNameResolver.cpp
Check whether `name` is empty when resolving collection name before we access it.
While we're here, use `isdigit` instead of check whether character is between `0` and `9`.
This *might* relate to the crash seen in https://github.com/arangodb/arangodb/issues/9302#issuecomment-504027431 but is hard to verify.
I do not know whether there is a simple way to test these functions, in particular how an empty collection name can get through.
> Fix potential segfault

- arangod/Aql/AqlItemBlock.cpp
- arangod/Aql/AqlItemBlock.h
- arangod/Aql/InputAqlItemRow.cpp
- arangod/Aql/InputAqlItemRow.h
- arangod/Aql/RemoteExecutor.cpp
- tests/Aql/AqlItemBlockTest.cpp
Fixes another bug found by rolling upgrade tests.
Now an upgrade DBServer complies with the old format of initialize cursor again.
As a side effect there is a generalized toVelocyPack() method on AqlItemBlocks to serialize any slice out of them.
Right now we only use 0->end aka ALL
And x -> x+1 aka initializeCursor
Added c++ test.
Only internal API.
Jenkins:
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7319/
> Bug fix/input row serialization

- arangod/RestServer/ServerFeature.cpp
Fix handling of obsolete option `--vst.maxsize`.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7388/
> obsolete option `--vst.maxsize` requires a value if specified

- arangod/Cluster/RestClusterHandler.cpp
- arangod/Cluster/RestClusterHandler.h
- arangod/GeneralServer/CommTask.cpp
- arangod/GeneralServer/RestHandler.h
- arangod/RestHandler/RestAdminLogHandler.cpp
- arangod/RestHandler/RestAdminServerHandler.cpp
- arangod/RestHandler/RestDocumentHandler.cpp
- arangod/RestHandler/RestEngineHandler.cpp
- arangod/RestHandler/RestJobHandler.cpp
- arangod/RestHandler/RestPleaseUpgradeHandler.cpp
- arangod/RestHandler/RestShutdownHandler.cpp
- arangod/RestHandler/RestStatusHandler.cpp
- arangod/RestHandler/RestVersionHandler.cpp
Ask the handler for direct execution instead of just looking at the RequestLane. This became necessary because in some cases the IOContext executed long running tasks and the server became unresponsive.
> Direct Execution RestHandler

- arangod/RestHandler/RestDocumentHandler.cpp
Don't use *isDirect* in cluster, when we will very likely have blocking communication.
Additionally, allow usage of *isDirect* in more (single server) cases.
This change is already covered by existing tests, such as *shell_client, http_server*.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7440/
> use isDirect for slightly different cases

- 3rdParty/fuerte/src/HttpConnection.cpp
- 3rdParty/fuerte/src/VstConnection.cpp
- 3rdParty/fuerte/src/helper.cpp
- arangosh/Shell/V8ClientConnection.cpp
Make the arangosh not say "could not connect" when we used with a keep alive timeout of 0
- [x ] There is a GitHub Issue reported by a Community User: https://github.com/arangodb/arangodb/issues/9288
This change is already covered by existing tests, such as client testsuites
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/9142/
> Try to fix keep alive 0

- tests/js/common/shell/shell-query-spec.js
Try to eliminate more non-determinism from the test.
This change is already covered by existing tests, such as *scripts/unittest shell_server shell_client --test tests/js/common/shell/shell-query-spec.js*.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7460/
> fix the fix

- 3rdParty/fuerte/src/GeneralConnection.cpp
This fixes `ssl_server` cluster tests failing on mac & windows.
> don't re-use connection objects on windows and mac either

- arangod/Replication/ReplicationFeature.cpp
From 3.5.3 release email:
> * Make the timeouts for replication requests (for active failover and master-slave replication) configurable via startup options:
>
>      --replication.connect-timeout
>      --replication.request-timeout
`--dump-options` reports them as being introduced in v3.5.4
Blocks update of online docs for 3.5.3
> Replication: New startup options available from v3.5.3 on, not v3.5.4

- 3rdParty/iresearch/core/utils/log.hpp
- arangod/IResearch/IResearchAnalyzerFeature.cpp
Fix potential buffer overflow in arangosearch.
This change is already covered by existing tests, such as `scripts/unittest shell_server_aql --test tests/js/common/aql/aql-view-arangosearch-feature.js`.
*(or)*
Additionally:
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7522/
> Bug fix/lol jenkins branch names

- arangod/IResearch/IResearchAnalyzerFeature.cpp
Remove potentially dangerous `noexcept` declarations in functions that use dynamic memory allocation.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7523/
> remove invalid noexcept declarations

- arangosh/Shell/ConsoleFeature.cpp
- lib/Logger/LoggerFeature.cpp
- lib/ProgramOptions/Option.cpp
- lib/ProgramOptions/ProgramOptions.cpp
As agreed with @Simran-B, tag a few dynamic options as "Dynamic", so it is clear that their default value depends on the runtime environment.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7533/
> tag dynamic options with Dynamic flags attribute

- lib/Basics/debugging.cpp
It seems as if our macs need a little more time for the suicide.
```
2019-11-28T13:53:18Z [93394] S WARNING [d8a5f] activating intentional failure point 'FlushCrashAfterSyncingMinTick'. the server will misbehave!
2019-11-28T13:53:18Z [93394] S WARNING [bde58] crashing after syncing min tick: summon Baal!
2019-11-28T13:53:18Z [93394] S FATAL [36a91] assertion failed in /Users/jenkins/vm13-mac/oskar/work/ArangoDB/lib/Basics/debugging.cpp:115: false
Thu Nov 28 2019 14:53:41 GMT+0100 (Central European Standard Time) Finished: ABORTED Signal: 6 Time elapsed: 27.486166954040527 - 
```
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7476/
> wait for suicide to actually take place before we fail this

- js/common/modules/@arangodb/aql/explainer.js
Bugfix for Explain only.
No critical change, data is all correct.
It helps a user to better read the Explain output.
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7552/
> Explain now prints the RETURN of a spliced subquery again

- arangod/RocksDBEngine/RocksDBCollection.cpp
Create separate PR for locking bugfix, so it can be merged already, before https://github.com/arangodb/arangodb/pull/10621 is completely ready.
This change is already covered by existing tests:
* start single server
* connect with arangosh and run `while (require("jsunity").runTest("tests/js/common/shell/aql-index-usage-rocksdb.js"));` until it fails/crashes/succeeds
Additionally:
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7566/
> already reap lock bugfix

- arangod/Auth/UserManager.cpp
in case multiple coordinators were used, the one that won the cluster
bootstrap race created the "root" user and was fine afterwards. other
coordinators however were not notified of the new user, and were denying
all incoming requests with an HTTP 401 "not allowed to execute this
request" response.
the change in this PR triggers an increase of the UserVersion counter
in the agency, so that other coordinators eventually get aware of the
root user being added.
Start a cluster with 2 coordinators and authentication, and poll `/_api/version` for both of them repeatedly, e.g.
```
while true; do curl --insecure --user "root:" -X GET http://127.0.0.1:8530/_api/version -v --dump - 2>&1; done
while true; do curl --insecure --user "root:" -X GET http://127.0.0.1:8531/_api/version -v --dump - 2>&1; …
```
> fix startup when using multiple coordinators.

- tests/js/common/shell/shell-ttl.js
Try to make `shell-ttl` test in cluster less timing-dependent.
This change is already covered by existing tests, such as `scripts/unittest shell_client --test shell-ttl --cluster true`.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7581/
> try to make shell-ttl less time-dependent

- arangod/VocBase/Methods/UpgradeTasks.cpp
Addition to: 
- https://github.com/arangodb/arangodb/pull/10652
Also, the fishbowl collection needs to be created every time.
> Bug fix 3.6/always create fishbowl collections

- arangod/VocBase/Methods/UpgradeTasks.cpp
unconditionally create statistics collections when the database is created
it is not advisable to not create them when the statistics are turned off, because the server may later be restarted with statistics turn on. and then the collections will be missing
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7599/
> always create the statistics collections

- arangod/GeoIndex/Near.cpp
- arangod/GeoIndex/Near.h
- arangod/RestServer/InitDatabaseFeature.cpp
- lib/Geo/GeoJson.cpp
(very) slightly speed up geo index functionality
This change is already covered by existing tests, such as *scripts/unittest shell_sever_aql*.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7621/
> Bug fix 3.6/small issues 10122019

- CHANGELOG
- arangod/Graph/GraphOperations.cpp
- tests/js/common/shell/shell-general-graph.js
Short: fixed editing single occurrence of an edge definition in case of multiple available graphs. 
e.g. Graph A has edge definition Z
e.g. Graph B has edge definition Y
Now we want to change edge definition Z. This will be tried for both graphs and will fail for Graph B. 
This PR fixed that behaviour.
`./scripts/unittest shell_client --test tests/js/common/shell/shell-general-graph.js`
> bug-fix single-edge-definition-editing

- js/apps/system/_admin/aardvark/APP/frontend/js/views/collectionsView.js
- js/apps/system/_admin/aardvark/APP/frontend/js/views/databaseView.js
Fixes several web UI glitches:
* adds missing description for "Sharding" attribute when creating a new database
* fixes setting of default values for new collections in databases created with "sharding" = "single" attribute. In this case, the attributes "Replication factor" and "Write concern" were not populated with default values
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7690/
> fix some UI issues for database defaults

- arangod/Aql/AstNode.cpp
- arangod/Aql/AstNode.h
- arangod/Aql/Condition.cpp
- arangod/Aql/Condition.h
- arangod/Transaction/Methods.cpp
Bug-fix for internal issue #9750 
As was discovered major performance penalty was in condition optimizations.
This PR optimizes AstNode operations by introducing fast version of removeMemberUnckecked function  - removeMemberUncheckedUnordered . This function achieves removal speedup by sacrificing node members order (swap + pop_back is used for removal ).
This fix is covered by existing AQL/AST tests
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/7719/
> Optimized AstNode members removals while condition optimizing

- arangod/VocBase/Methods/Collections.cpp
- arangod/VocBase/VocbaseInfo.cpp
- tests/js/common/shell/01_shell-database.js
Restrict _database_ name to 64 characters again, as it has been the case in 3.5 and ever before.
A previous PR for devel/3.6 allowed collection name lengths of 256 characters (raised from 64 chars), and as an unintended side effect this also allowed database names of 256 chars length.
This PR fixes the side effect, so database names are again restricted to 64 chars, while collection names can be up to 256 chars.
This change is already covered by existing tests, such as *scripts/unittest shell_server --test database*.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7717/
> restrict database length to 64 characters again

- arangod/Aql/DocumentProducingHelper.cpp
- arangod/Aql/IndexExecutor.cpp
Fixed context.incrScanned() for index
1. WithProjectionsCoveredByIndex (was a wrong place)
2. Late materialization (was duplicated)
> fix context.incrScanned

- arangod/Aql/ClusterNodes.cpp
- js/client/modules/@arangodb/test-utils.js
- js/common/modules/jsunity/jsunity.js
- tests/js/client/server_permissions/test-optimizer-rules.js
- tests/js/client/server_permissions/test-parallel-gather-writes-cluster-off.js
- tests/js/client/server_permissions/test-parallel-gather-writes-cluster-on.js
Added tests for `--query.optimizer-rules` and `--query.parallelize-gather-writes`.
Fixed a bug in handling the value of `--query.parallelize-gather-writes`
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7734/
> added tests & bugfix for query options

- CHANGELOG
- arangod/Aql/AstNode.cpp
- arangod/Aql/AstNode.h
- arangod/Aql/EngineInfoContainerCoordinator.h
- arangod/Aql/OptimizerRules.cpp
- arangod/Aql/Query.cpp
- arangod/Cluster/ClusterInfo.cpp
- arangod/Indexes/SimpleAttributeEqualityMatcher.cpp
- arangod/Indexes/SortedIndexAttributeMatcher.cpp
- arangod/RestServer/DatabaseFeature.cpp
- arangod/Sharding/ShardingInfo.cpp
- arangod/Sharding/ShardingInfo.h
- arangod/Sharding/ShardingStrategy.cpp
- arangod/Sharding/ShardingStrategy.h
- arangod/VocBase/vocbase.h
- arangosh/Backup/BackupFeature.cpp
- lib/Basics/RecursiveLocker.h
- tests/js/server/aql/aql-optimizer-rule-parallelize-gather-cluster.js
Fix an issue with parallel AQL making too many queries parallel even in case they were not eligible for parallelization.
Now, for a query to be eligible, it must have exactly one GatherNode, not multiple. In case there are multiple GatherNodes, it is not possible to prevent the query from using the same transaction object on the same database server from multiple threads.
```
// for example consider the following query, joining the shards of two collections 
// on 2 database servers:
//
//   (4)      DBS1                            DBS2               database
//        users, shard 1                 users, shard 2          servers
//       --------------------------------------------------------
//   (3)                      Gather                             coordinator 
// …
```
> don't make queries parallel if they are not eligible

- arangod/Aql/OptimizerRules.cpp
- tests/js/server/aql/aql-optimizer-rule-parallelize-gather-cluster.js
Exclude any queries using subqueries from parallelization
This change is already covered by existing tests, such as *scripts/unittest shell_server_aql --cluster true*.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7749/
> exclude any queries with subqueries from parallelization

- arangod/GeneralServer/CommTask.cpp
- arangod/GeneralServer/CommTask.h
this changes the body of HTTP 503 errors during maintenance from
```
{"errorNum":403,"errorMessage":"forbidden"}
```
to
```
{"errorNum":503,"errorMessage":"service unavailable due to startup or maintenance mode"}
```
This change is already covered by existing tests, such as *scripts/startLocalCluster.sh, scripts/unittest ... --cluster true*.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7756/
> fix a misleading message during maintenance

- arangod/Agency/Supervision.cpp
Fix a race that could prevent startup. Supervision now ignores system collections with `isBuilding`. Before that it deleted collections that have been created during bootstrap from a coordinator that was not listed in health.
This was found by automated tests.
> [3.6] Exclude system collections from supervision clean up.

- Documentation/DocuBlocks/Rest/BackupRestore/post_admin_backup_create.md
- arangod/Cluster/ClusterMethods.cpp
Properly document and fix the timeout behavior when creating backups. see https://github.com/arangodb/planning/issues/4761
This change is already covered by existing tests, such as https://github.com/arangodb/arangodb-java-driver/blob/b4cb92c058a044acd79bef7de6a30e51de1b2805/src/test/java/qa/ForceBackupTest.java#L237.
> Bug fix 3.6/backup timeout trx abort+docu

- arangod/Sharding/ShardingInfo.cpp
- arangod/VocBase/Methods/Collections.cpp
- tests/js/common/shell/shell-one-shard.js
Fixes a few usability issues reported via https://github.com/arangodb/release-3.6/issues/41
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7793/
> a few usability fixes for minReplicationFactor/writeConcern

- 3rdParty/iresearch/core/index/index_writer.cpp
Bug-fix for dangling readers in cache left by consolidation. Issue results in errors 32 in cleanup procedure on windows. Also old segments is not freed until server reboot leading to disk space consumption on all platforms.
Fixes internal issue #656 and ticket ES-483
Fix is verified by upstream project tests
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/7813/
> Fixed removed dangling  readers from cache

- arangod/Cluster/HeartbeatThread.cpp
The heartbeat thread updates the agency endpoint once per second but did not put the leader in front, instead it put them in lexicographic order. Thus in case the leader is not the first server, each server in the cluster forgets every second which server was the actual leader and asked the first named follower, just to be redirected immediately.
> Heartbeat Agency Endpoint Update

- arangod/Auth/UserManager.cpp
in case multiple coordinators were used, the one that won the cluster
bootstrap race created the "root" user and was fine afterwards. other
coordinators however were not notified of the new user, and were denying
all incoming requests with an HTTP 401 "not allowed to execute this
request" response.
the change in this PR triggers an increase of the UserVersion counter
in the agency, so that other coordinators eventually get aware of the
root user being added.
It looks like in 3.5 this change is actually not needed, as the coordinators
start fine. But the "fix" doesn't do any harm.
Start a cluster with 2 coordinators and authentication, and poll `/_api/version` for both of them repeatedly, e.g.
```
while true; do curl --insecure --user "root:" -X GET http://127.0.0.1:8530/_api/version -v …
```
> speculative fix for multi-coordinator bootstrap

- 3rdParty/iresearch/core/index/index_writer.cpp
- CHANGELOG
Bug-fix for dangling readers in cache left by consolidation. Issue results in errors 32 in cleanup procedure on windows. Also old segments is not freed until server reboot leading to disk space consumption on all platforms.
Fixes internal issue #656 and ticket ES-483
Fix is verified by upstream project tests
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/7814/
> Fixed removing outdated readers from cache

- js/server/modules/@arangodb/foxx/queues/manager.js
This feels more like a hacky solution to the problem that the retry loop does not quit, even when shutting down; What should really happen is that we only retry on the exceptions that are "acceptable", but for that I have to first find out which ones are.
> Bug-Fix and Refactoring work on resetDeadJobs

- cmake/packages/client/nsis.txt
backport of https://github.com/arangodb/arangodb/pull/10822
> 3.6: propagate js version variable into the client package

- tests/js/client/shell/shell-transaction.js
This is an attempt to make the "abort all write transactions" test more robust.
It adds an extra delay, which still is not 100% reliable, but should improve things.
This change is already covered by existing tests, such as *scripts/unittest shell_client --cluster true --test shell-transaction.js*.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7807/
> try to make test more robust

- arangod/Aql/ClusterNodes.cpp
- arangod/Aql/OptimizerRules.cpp
- tests/js/server/aql/aql-optimizer-rule-parallelize-gather-cluster.js
Disable parallelization of GatherNodes when queries includes traversals, shortest_path or k_shortest_path components.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7907/
> disable parallel AQL when there are traversals or shortest paths queries

- arangod/Aql/AqlItemBlock.cpp
- arangod/Aql/AqlItemBlockManager.cpp
- tests/js/server/aql/aql-shadowrow-block-return-regression.js
If we don't reset shadow row indices, this set might contain shadow rows from
previous uses and lead to havoc.
This will need to be backported to 3.6, and a new test should be be added too before merging.
This should solve (at least) #10804
> Fix returning blocks with shadow rows to the AqlItemBlockManager

- arangod/Aql/Expression.cpp
- arangod/Aql/Query.cpp
* Remove & unify strange error messages in Expression.cpp
* honor "silent" option and don't store query results in query cache if it is set
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/7948/
> clean up strange things

- Documentation/DocuBlocks/Rest/Replication/get_api_replication_applier_state.md
- Documentation/DocuBlocks/Rest/Replication/get_api_wal_access_tail.md
- Documentation/DocuBlocks/Rest/Replication/put_api_replication_applier.md
- Documentation/DocuBlocks/Rest/Replication/put_api_replication_applier_adjust.md
- Documentation/DocuBlocks/Rest/Replication/put_api_replication_applier_start.md
- Documentation/DocuBlocks/Rest/Replication/put_api_replication_applier_stop.md
Add missing "global" query parameter to replication API documentation
> added missing description of "global" query parameter in replication

- arangod/Aql/AllRowsFetcher.cpp
- arangod/Aql/AllRowsFetcher.h
- arangod/Aql/ConstrainedSortExecutor.cpp
- arangod/Aql/DependencyProxy.h
- arangod/Aql/ExecutionBlock.cpp
- arangod/Aql/ExecutionBlock.h
- arangod/Aql/ExecutionBlockImpl.cpp
- arangod/Aql/ExecutionEngine.cpp
- arangod/Aql/MultiDependencySingleRowFetcher.cpp
- arangod/Aql/MultiDependencySingleRowFetcher.h
- arangod/Aql/Query.cpp
- arangod/Aql/RestAqlHandler.cpp
- arangod/Aql/SimpleModifier.h
- arangod/Aql/SingleRowFetcher.cpp
- arangod/Aql/SingleRowFetcher.h
- arangod/Aql/SortingGatherExecutor.cpp
- arangod/Aql/SubqueryExecutor.cpp
- arangod/Indexes/SortedIndexAttributeMatcher.cpp
- arangod/MMFiles/MMFilesPrimaryIndex.cpp
- arangod/Transaction/Methods.h
- tests/Aql/DependencyProxyMock.h
- tests/Aql/RowFetcherHelper.h
- tests/Aql/UpsertExecutorTest.cpp
Speed up AQL upsert unit tests by using a smaller batch size value.
Additionally this makes the DefaultBatchSize value adjustable by unit tests.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7869/
> speed up AQL upsert unit tests

- arangod/Cluster/RestClusterHandler.cpp
- arangod/GeneralServer/RestHandler.h
- arangod/RestHandler/RestAdminLogHandler.cpp
- arangod/RestHandler/RestAdminServerHandler.cpp
- arangod/RestHandler/RestDocumentHandler.cpp
- arangod/RestHandler/RestEngineHandler.cpp
- arangod/RestHandler/RestJobHandler.cpp
- arangod/RestHandler/RestPleaseUpgradeHandler.cpp
- arangod/RestHandler/RestShutdownHandler.cpp
- arangod/RestHandler/RestStatusHandler.cpp
- arangod/RestHandler/RestVersionHandler.cpp
Remove leftovers of `allowDirectExecution`. This functionality is not used anymore.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/7990/
> remove remainders of allowDirectExecution

- CHANGELOG
- arangod/CMakeLists.txt
The product version information (right-click on .exe in explorer, Properties, Details tab) as well as the application icon were missing for:
- arangod.exe
- arango-dfdb.exe
- arango-init-database.exe
- arango-secure-installation.exe
Fixes #10867
> Bug fix 3.6/windows exe product info

- 3rdParty/velocypack/include/velocypack/Slice.h
- 3rdParty/velocypack/src/Builder.cpp
Fix edge case in VelocyPack when the padding of a 1-byte offsetSize array is removed but the first few entries of the array contain a Slice of type None.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8072/
> fix edge case with padding in VelocyPack arrays

- arangosh/Restore/RestoreFeature.cpp
As already implemented in 3.5 and newer versions, we need to restore the `_users` collection last! That change is missing in 3.4, and ported with that PR.
> Bug fix 3.4/restore feature collection order

- arangod/Cluster/AgencyCallback.cpp
- arangod/Cluster/AgencyCallback.h
- arangod/Cluster/ClusterInfo.cpp
- arangod/Cluster/ClusterInfo.h
- arangod/Cluster/HeartbeatThread.cpp
Fix a dangling reference to AgencyComm when creating an AgencyCallback from inside the CollectionWatcher object.
This change is already covered by existing tests, such as *all cluster tests - some crashed on Windows due to the issue*.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8111/
> fix dangling reference to AgencyComm in AgencyCallback ctor

- CHANGELOG
- arangod/Scheduler/SupervisedScheduler.cpp
- arangod/Scheduler/SupervisedScheduler.h
Don't use `alignas` for this shared_ptr, as it is not necessary but confuses Valgrind.
If the change is not made, Valgrind will report "invalid free/delete errors" in the Scheduler randomly.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8073/
> don't use alignas for these shared_ptrs, as it confuses Valgrind and is not necessary

- js/client/modules/@arangodb/process-utils.js
This patch should eventually give the server a second chance. Seen like this in a testrun:
```
Mon Jan 20 2020 01:25:45 GMT+0100 (Central European Standard Time) tickeling cluster node https://127.0.0.1:11497
Determining server IDs
queued request on failed connection
2020-01-20T00:25:46Z [6304] ERROR [9d7ea] Could not connect to endpoint 'ssl://127.0.0.1:11497', username: 'root' - Server message: Connection reset by peer
[ArangoError 10: Connection reset by peer] ArangoError: Connection reset by peer
at startInstanceCluster (c:\vm02-windows\oskar\work\ArangoDB\js\client\modules\@arangodb\process-utils.js:1752:10)
at Object.startInstance (c:\vm02-windows\oskar\work\ArangoDB\js\client\modules\@arangodb\process-utils.js:2038:7)
at Object.performTests …
```
> give the instance a second try if it resets our connection

- arangod/Aql/IResearchViewOptimizerRules.cpp
- arangod/Aql/IndexNodeOptimizerRules.cpp
- tests/js/server/aql/aql-optimizer-rule-late-document-materialization-arangosearch.js
- tests/js/server/aql/aql-optimizer-rule-late-document-materialization-rocksdb.js
Fixes a crash described in https://github.com/arangodb/arangodb/issues/10845#issuecomment-575723029
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8129/
> added bugfix for https://github.com/arangodb/arangodb/issues/10845#issuecomment-575723029

- arangod/IResearch/IResearchViewStoredValues.cpp
- tests/IResearch/IResearchQueryNoMaterialization-test.cpp
- tests/IResearch/IResearchView-test.cpp
Wrong behavior: If a stored value column name prefix is equal to column name prefix then the exists function returns true.
Fixed. A stored value column name has a different prefix.
https://github.com/arangodb/backlog/issues/675
> Fixed exists function with stored values column

- arangod/IResearch/IResearchFilterFactory.cpp
- tests/IResearch/IResearchFilterFunction-test.cpp
- tests/IResearch/IResearchQueryPhrase-test.cpp
Allowed empty array as PHRASE function parameter. Empty arrays  just skipped without affecting resulting ArangoSearch filter while accumulating offsets ( 'a', 1, [], 2, 'b' is equal to 'a', 3, 'b'). If only empty array(s) given, search will yeld no results, but will be considered valid.
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/8194/
> Allowed empty arrays as PHRASE parameter

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/react/src/store/cluster/middleware.tsx
Disable a not needed health call. The function was only built for development as a POC. Only commented out as we need it in the future
> disable health react request till we need it

- tests/IResearch/IResearchFeature-test.cpp
Fix spurious test failure in IResearchFeature-test.cpp complaining about "deallocated1".
This PR just deactivates the test for this, because it is non-deterministic.
The reason for the bug is that the `read_write_lock::unlock()` function is non-deterministic about waking about waiting others.
There is also a bug report for this: https://github.com/arangodb/backlog/issues/618
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8278/
> fix spurious test failure re "deallocated1"

- arangod/Utils/CursorRepository.cpp
- tests/rb/HttpInterface/api-cursor-spec.rb
- tests/rb/HttpInterface/api-query-analysis-spec.rb
Attempt to make two rb tests more robust
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8301/
> try to make some rb tests more robust

- tests/CMakeLists.txt
remove compile definition that is only relevant for removed catch testing framework
Just needs to compile & execute the tests fine
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8331/
> catch is dead

- arangosh/Shell/V8ClientConnection.cpp
Note that contrary to 3.7 we have no easy access to the `ClientFeature` in the constructor of the `V8ClientConnection`. On the other hand, the `_requestTimeout` is set in the `connection` method in 3.6. Anyway, it seems that JS is querying the timeout before the connection has been established.
> Fix uninitialized value in V8ClientConnection.

- arangosh/Shell/V8ClientConnection.cpp
> Fix uninitialized value _requestTimeout in V8ClientConnection.

- arangod/GeneralServer/AuthenticationFeature.cpp
this change hides the warning message about `--server.jwt-secret` being
insecure in case the end user has not set the option at all.
previously the warning was displayed also when not specifying the
option.
the problem was caused by not checking whether the end user had set the
option, but by checking an internal string that was filled also in other
cases then when using the `--server.jwt-secret` option.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8376/
> disable warning about `--server.jwt-secret`

- CHANGELOG
- arangod/RestHandler/RestPleaseUpgradeHandler.cpp
- arangod/VocBase/Methods/Upgrade.cpp
Remove misleading upgrade instructions
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8488/
> removing misleading upgrade instructions

- arangod/Aql/SharedAqlItemBlockPtr.h
Allow self-assignment of `SharedAqlItemBlockPtr`. Just to adhere to best practices, and there is no reason to disallow this (for the copy-assignment).
> Allow self-assignment of SharedAqlItemBlockPtr

- arangod/Aql/ExecutionBlockImpl.cpp
Internal team gordo PR.
Adds an assertion around SKIP. That makes sure that if an executor claims to skip `n` documents that those `n` documents are removed from the inbound call.
Jenkins:
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/8504/
> Additional Assertion in ExecutionBlockImpl

- Documentation/DocuBlocks/Rest/BackupRestore/post_admin_backup_create.md
- arangod/Cluster/ClusterMethods.cpp
Properly document and fix the timeout behavior when creating backups. see https://github.com/arangodb/planning/issues/4761
This change is already covered by existing tests, such as https://github.com/arangodb/arangodb-java-driver/blob/b4cb92c058a044acd79bef7de6a30e51de1b2805/src/test/java/qa/ForceBackupTest.java#L237.
> Fixing documentation and timeout.

- arangosh/Restore/RestoreFeature.cpp
- arangosh/Shell/ClientFeature.cpp
Fix error message when database creation fails for `--create-database` option
additionally, pass the specified replication factor from `--replication-factor` option when creating a database.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8516/
> fix error message when database creation fails for `--create-database` option

- arangod/Aql/DocumentProducingHelper.cpp
- arangod/Aql/IndexExecutor.cpp
- arangod/Aql/OptimizerRules.cpp
- tests/js/server/aql/aql-optimizer-collect-count.js
Fixes the issue reported in DEVSUP-554:
when there is a covering index scan and at the same time an early pruning filter is applied on the index data, the filter saw wrong document input in case there was either a LIMIT or a COLLECT WITH COUNT node pulling data from the IndexExecutor in "skipping" mode.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8550/
> fixed devsup-554

- js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
Fixed handling of `geometry` attributes in query editor of the web UI.
Previously, document attributes named `geometry` were treated in a special way, assuming they were JSON objects. In case a document contained a `geometry` attribute that had a non-object value (e.g. `null`) the web UI threw a JavaScript exception and would not display AQL query results properly.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8546/
> fix handling of `geometry` attributes

- CHANGELOG
- arangod/Aql/DocumentProducingHelper.cpp
- arangod/Aql/IndexExecutor.cpp
- arangod/Aql/OptimizerRules.cpp
- tests/js/server/aql/aql-optimizer-collect-count.js
Fixes the issue reported in DEVSUP-554:
when there is a covering index scan and at the same time an early pruning filter is applied on the index data, the filter saw wrong document input in case there was either a LIMIT or a COLLECT WITH COUNT node pulling data from the IndexExecutor in "skipping" mode.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8549/
> fixed DEVSUP-554 and disabled "collect-in-cluster" when a LIMIT is found

- arangod/Aql/OptimizerRules.cpp
- tests/js/server/aql/aql-optimizer-rule-move-filters-into-enumerate.js
Fixed queries having the following structure
```
FOR doc IN collection
FILTER doc.nonIndexedAttribute     // expression
FOR sub IN doc.nonIndexedAttribute // same expression
```
For such queries, the FILTER was moved into the first FOR loop for early pruning. Afterwards, the leftover CalculationNode that evaluated `doc.nonIndexedAttribute` was removed. This was wrong however, because the same expression was reused in the second FOR loop. There was code considering this, but due to a bug it did not work if the expression in the FILTER was reused in t
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8578/
> fixed optimizer rule `move-filters-into-enumerate`

- lib/Basics/ArangoGlobalContext.cpp
- lib/Basics/ArangoGlobalContext.h
- lib/Basics/CrashHandler.cpp
- lib/Logger/LogBufferFeature.cpp
- lib/Logger/LogBufferFeature.h
* Make crash handler a bit more robust
* Activate Windows event log logger
* Create in-memory log appender only when needed
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8612/
> Bug fix/crash handler precautions

- CHANGELOG
- arangod/Aql/ModificationExecutor.cpp
- arangod/Aql/ModificationExecutor.h
> [3.6] Guard  AqlValues properly in ModificationExecutor

- js/client/modules/@arangodb/process-utils.js
- js/client/modules/@arangodb/testing.js
- lib/Basics/process-utils.cpp
This PR changes the test timeout from effectively 4.5 minutes to 10 minutes. 
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr-linux/10354/EDITION=community,STORAGE_ENGINE=mmfiles,TEST_SUITE=single,limit=(linux&&test)%7C%7Cgce/ would show errnous timeout behaviour; rspec would continue running. 
running with a 15 seconds timeout will now do:
```
./scripts/unittest http_replication --test tests/rb/HttpReplication/api-replication-global-spec.rb --oneTestTimeout 3
...
fetches the empty follow log
tails the WAL with a tick far in the future
Killing rspec - ["--color","-I","tests/arangodbRspecLib","--format","d","--format","j","--out","/tmp/arangosh_Cso8Bt/http_replication/testresult.json","--require","/tmp/arangosh_Cso8Bt/http_replication/testconfig.rb","tests/rb/HttpReplication/api-rep …
```
> fix test timeout handling

- js/client/modules/@arangodb/testing.js
http://jenkins01.arangodb.biz:8080/view/Windows/job/arangodb-ANY-windows-matrix/988/EDITION=enterprise,STORAGE_ENGINE=rocksdb,TEST_SUITE=cluster,limit=test&&windows/ showed 10 minutes is not enough.
> increase timeout to 15 minutes

- arangod/Cluster/Maintenance.cpp
- arangod/Cluster/MaintenanceFeature.cpp
- arangod/Cluster/MaintenanceStrings.h
- arangod/Cluster/ResignShardLeadership.cpp
When using `db.<collection>.properties({ cacheEnabled: true });` this didn't have any effect. The `cacheEnabled` attribute was ignored here, but it shouldn't have been.
This PR fixes the behavior.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8680/
> honor cacheEnabled attribute in collection properties update in coordinator case

- Documentation/DocuBlocks/Rest/Database/get_api_database_current.md
...about the non-existing API /_api/database/properties
Backport of https://github.com/arangodb/arangodb/commit/4ccfb073de32754e931282a6c93c71df5707d078
> Docs: Remove misleading statement

- arangod/Aql/ExecutionPlan.cpp
- arangod/Graph/BreadthFirstEnumerator.cpp
- arangod/Graph/NeighborsEnumerator.cpp
- arangod/Graph/PathEnumerator.cpp
- arangod/Graph/PathEnumerator.h
- arangod/Graph/TraverserOptions.cpp
- arangod/Graph/TraverserOptions.h
- arangod/Transaction/Helpers.cpp
- arangod/Transaction/Helpers.h
- js/common/modules/@arangodb/aql/explainer.js
- tests/js/server/aql/aql-traversal-restrict-vertex-collections.js
Add a new query option to restrict a traversal to only visit certain vertex collections. The filtering can be done at the edge, and thus save additional query time to the storage engine or to other database servers to retrieve the vertex for post-filtering.
Enterprise component: https://github.com/arangodb/enterprise/pull/396
Jenkins:
http://172.16.10.101:8080/job/arangodb-matrix-pr/8675/ (blue except for Windows)
http://172.16.10.101:8080/job/arangodb-matrix-pr-windows/2642/
> Restrict vertex collections in traversal

- 3rdParty/fuerte/src/H1Connection.cpp
- 3rdParty/fuerte/src/H2Connection.cpp
- 3rdParty/fuerte/src/VstConnection.cpp
Fix an assertion by swapping the order here
- [ x] Bug-Fix for *devel-branch* (i.e. no need for backports?)
This change is already covered by existing tests, such as all of them
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-linux/10401/
> Attempt to fix assert

- CHANGELOG
- arangod/Cluster/Maintenance.cpp
- arangod/Cluster/MaintenanceFeature.cpp
- arangod/Cluster/MaintenanceStrings.h
- arangod/Cluster/ResignShardLeadership.cpp
When using `db.<collection>.properties({ cacheEnabled: true });` this didn't have any effect. The `cacheEnabled` attribute was ignored here, but it shouldn't have been.
This PR fixes the behavior.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8686/
> Honor `cacheEnabled` attribute when updating the properties of a collection in case of the cluster

- CHANGELOG
- arangod/GeneralServer/AuthenticationFeature.cpp
Prevent startup error `specifiy either '--server.jwt-secret-keyfile' or  '--server.jwt-secret-folder' but not both.` from occurring when specifying the JWT secret keyfile option.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8693/
> Bug fix/fix jwt option

- CHANGELOG
- arangod/GeneralServer/SslServerFeature.cpp
- arangod/RocksDBEngine/RocksDBEventListener.cpp
- lib/Basics/files.cpp
- lib/Basics/files.h
- tests/Basics/files-test.cpp
Use OpenSSL's EVP interface instead of the deprecated low-level APIs
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/398
From https://www.openssl.org/docs/man1.1.0/man3/SHA256_Final.html:
> Applications should use the higher level functions EVP_DigestInit(3) etc. instead of calling the hash functions directly.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8690/
> use EVP interface

- CHANGELOG
- js/client/modules/@arangodb/testsuites/dump.js
- tests/js/server/dump/dump-mmfiles-cluster.js
- tests/js/server/dump/dump-rocksdb-cluster.js
- tests/js/server/dump/dump-setup-cluster.js
Backport of #11095.
Note that the actual fix is in the enterprise repository, this just adds a regression test.
> [3.6] Fix restore for smart collections

- arangod/Aql/Functions.cpp
- arangod/Transaction/Context.cpp
- arangod/Transaction/Context.h
- lib/Basics/StringUtils.cpp
- lib/Basics/StringUtils.h
- tests/Aql/JaccardFunctionTest.cpp
Fix memleaks in Jaccard function tests
Slightly optimize LEVENSHTEIN_DISTANCE function performance
This change is already covered by existing tests, such as *shell_server_aql*, *catch*.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8704/
> fix some test memleaks, slightly optimize LEVENSHTEIN_DISTANCE function

- CHANGELOG
- js/client/modules/@arangodb/testsuites/dump.js
- tests/js/server/dump/dump-mmfiles-cluster.js
- tests/js/server/dump/dump-rocksdb-cluster.js
- tests/js/server/dump/dump-setup-cluster.js
Backport (maybe) of (#11095)
*Note* that the actual fix ~(if needed)~ is in the enterprise repository.
This only adds a regression test.
> [3.5] Fix restore for smart collections 

- CHANGELOG
- arangosh/Benchmark/test-cases.h
Make arangobench return a proper error message in case its initial collection creation attempt fails.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8774/
> make arangobench return a proper error message

- arangod/Aql/ExecutionBlockImpl.cpp
InternalTG PR.
Some tests have been red, however executors are implemented, the issue was in ShadowRow handling outside of the executors.
> Activate CalculationExecutors

- arangod/Aql/DocumentProducingHelper.cpp
Fix a nullptr dereference uncovered by ASan tests in `scripts/unittest shell_server_aql --test tests/js/server/aql/aql-optimizer-collect-count.js`
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8788/
> fix nullptr dereference

- lib/Basics/CrashHandler.cpp
Avoid call to `backtrace_symbols` from within signal handler as `backtrace_symbols` may malloc.
Instead, write backtrace to a file descriptor using `backtrace_symbols_fd` and read it back later on (this is async signal-safe).
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8835/
> avoid call to backtrace_symbols because it may malloc

- arangod/Aql/RegisterPlan.cpp
- arangod/Aql/RegisterPlan.h
Factor out repeated code parts into two methods.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8834/
> simplify the register planning code a bit

- arangod/Aql/Ast.cpp
Produce smaller output arrays when calculating the intersection of two IN lists.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8861/
> produce smaller output arrays when calculating the intersection of two IN lists

- arangod/Aql/AstNode.cpp
- arangod/Aql/AstNode.h
- arangod/Graph/TraverserOptions.cpp
This frees uses of AstNode from having to remember to call `stealComputedValue()` on the AstNode before re-purposing it.
This change is already covered by existing tests, such as *shell_server_aql, shell_client*.
Additionally:
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8856/
> remove the need to call stealComputedValue for AstNodes

- js/client/modules/@arangodb/crash-utils.js
- js/client/modules/@arangodb/process-utils.js
- when the process is gone we can't get any more stats from it - continue processing anyways since i.e. crash analysis may happen
- disable coredumping for gdb
- move 'bt full' to the end so we get as much information as possible before we enter the danger zone.
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/8857/
> Bug fix/disable gdb coredumping

- js/client/modules/@arangodb/result-processing.js
- js/client/modules/@arangodb/test-utils.js
This PR improves the result representation in the test summary if the test was aborted due to a timeout.
> make more clear why a test was abortet

- arangod/RestHandler/RestReplicationHandler.cpp
- arangod/RestHandler/RestReplicationHandler.h
- arangod/StorageEngine/PhysicalCollection.h
- arangosh/Restore/RestoreFeature.cpp
- arangosh/Restore/RestoreFeature.h
- lib/Basics/StaticStrings.cpp
- lib/Basics/StaticStrings.h
The goal of this PR is to automatically assign new revision IDs to restored documents. Previously, we would always preserve the `_rev` values when restoring documents. This prevents us from guaranteeing that different documents in the same collection have distinct `_rev` values when the number of shards is changed. There is a hidden option to force preservation of the IDs for certain special circumstances, but in general it should not be set.
This change is already covered by existing tests, such as dump.
> Replace revision IDs on restore.

- arangod/Cache/TransactionManager.cpp
- arangod/Cache/TransactionManager.h
In some profiling runs the TransactionManager begin/end methods showed up very significantly due to high contention on the lock. To improve that, I made them lock-free by putting all counters in a 128-bit struct that is updated in a CAS-loop.
> Make TransactionManager::begin/end lock-free.

- CHANGELOG
- arangod/RocksDBEngine/RocksDBOptimizerRules.cpp
- tests/js/server/aql/aql-optimizer-rule-remove-sort-rand-limit-rocksdb.js
Fix `SORT RAND() LIMIT 1` optimization for RocksDB when only a projection of the attributes was used. When a projection was used and that projection was covered by an index (e.g. `_key` via the primary index), then the access pattern was transformed from random order collection seek to an index access, which always resulted in the same index entry to be returned and not a random one.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8986/
> fix SORT RAND() LIMIT 1 optimizer rule

- Documentation/DocuBlocks/Rest/Replication/get_api_replication_revisions_tree.md
- Documentation/DocuBlocks/Rest/Replication/post_api_replication_revisions_tree.md
- Documentation/DocuBlocks/Rest/Replication/put_api_replication_revisions_documents.md
- Documentation/DocuBlocks/Rest/Replication/put_api_replication_revisions_ranges.md
- arangod/RestHandler/RestReplicationHandler.cpp
- arangod/RestHandler/RestReplicationHandler.h
- lib/Basics/StaticStrings.cpp
- lib/Basics/StaticStrings.h
- lib/Containers/MerkleTree.cpp
Add DocuBlocks for the new Merkle tree-based replication APIs and do a tiny bit of handler cleanup.
Jenkins, just in case: http://172.16.10.101:8080/job/arangodb-matrix-pr/8977/ (all blue)
> Add docublocks for Merkle tree-based replication APIs

- CHANGELOG
- arangod/RocksDBEngine/RocksDBOptimizerRules.cpp
- tests/js/server/aql/aql-optimizer-rule-remove-sort-rand-limit-rocksdb.js
Fix `SORT RAND() LIMIT 1` optimization for RocksDB when only a projection of the attributes was used. When a projection was used and that projection was covered by an index (e.g. `_key` via the primary index), then the access pattern was transformed from random order collection seek to an index access, which always resulted in the same index entry to be returned and not a random one.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9019/
> fix SORT RAND() LIMIT 1 optimizer rule (#11262)

- arangod/Graph/Graph.cpp
- arangod/Graph/Graph.h
- lib/Basics/Exceptions.h
When orphan collections were provided to the gharial API as an array, but the elements weren't strings, in maintainer mode an assertion would trigger. The production check wasn't active, however, and would have led to a generic velocypack error.
This remove the assertion (because it can be triggered by using an external API wrongly), and fixed the production check that should have thrown a meaningful exception (but didn't).
This change is trivial. It removes a maintainer-mode assertion, and adds a more helpful error message in production.
> Fixed production check, removed assertion

- 3rdParty/iresearch/core/search/wildcard_filter.cpp
- 3rdParty/iresearch/core/search/wildcard_filter.hpp
- 3rdParty/iresearch/core/utils/wildcard_utils.cpp
- 3rdParty/iresearch/core/utils/wildcard_utils.hpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/9057/
> fix for ArangoSearch LIKE operator with escape sequence

- CHANGELOG
- lib/ApplicationFeatures/TempFeature.cpp
- lib/Basics/CrashHandler.cpp
- lib/Basics/CrashHandler.h
Prevent accessing the temporary path before a user-specified temporary path could be read via `--temp.path`.
This PR fixes a regression introduced in devel about 2 weeks ago.
This change is already covered by existing tests, such as *scripts/unittest paths_server*.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9072/
> Bug fix/fix temp file usage

- tests/Aql/NgramMatchFunctionTest.cpp
- tests/Aql/NgramPosSimilarityFunctionTest.cpp
- tests/Aql/NgramSimilarityFunctionTest.cpp
Fixed g++9 generated warnings
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/9074/
> Ngram-tests warnings fix

- js/client/modules/@arangodb/result-processing.js
if the SUT is aborted the `UNITTEST_RESULT.json` may look like this - 
```
{"resilience_failover":{"startupTime":5.142500638961792,"tests/js/server/resilience/failover/resilience-synchronous-repl-cluster-grey.js":{"status":false,"message":"server unavailable for testing: Error reading from: 'http+tcp://127.0.0.1:12324' 'timeout during read'"},"SKIPPED":{"status":false,"message":"failedtest"},"testDuration":1801.927895307541,"shutdownTime":483.58957076072693,"failed":2,"status":false},"status":false,"crashed":true}
```
if there was no test following the test in which the system aborted, message will be empty:
```
{"resilience_failover":{"startupTime":5.142500638961792,"tests/js/server/resilience/failover/resilience-synchronous-repl-cluster-grey.js":{"status":false,"message":"server …
```
> if no tests were following the timouted tests, don't add that message

- lib/ApplicationFeatures/TempFeature.cpp
- lib/Basics/files.cpp
One of the previous commits accidentially disabled stack trace printing for crashes.
This commit turns it back on.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9099/
> reenable stack trace printing

- arangod/Aql/TraversalExecutor.cpp
- arangod/Aql/TraversalExecutor.h
- arangod/Graph/PathEnumerator.cpp
- arangod/Graph/PathEnumerator.h
- tests/js/server/aql/aql-traversal-reset-regression.js
When executing subqueries the `TraversalExecutor` is reconstructed in place, which left the traverser, which is contained in the `TraversalExecutorInfos` in an undefined state. This patch resets the traverser on construction.
As a side effect the `PathEnumerator` is also fixed, which did not reset its `_activeCursors` variable correctly.
> Traversal Bugfix 

- arangod/VocBase/LogicalCollection.cpp
- arangod/VocBase/Methods/Collections.cpp
- lib/Basics/StaticStrings.cpp
- lib/Basics/StaticStrings.h
- tests/js/common/shell/shell-collection.js
Currently in devel, new collections will be created with the `usesRevisionAsDocumentId` flag set, which is wrong. This fixes it. This also adds a new flag `syncByRevision` to the collection properties so that clients can determine whether the collection supports the new replication protocol.
Jenkins: https://jenkins01.arangodb.biz/job/arangodb-matrix-pr/9110/
> Fix usesRevisionAsDocumentId population and add syncByRevision flag

- arangod/Aql/KShortestPathsExecutor.cpp
- arangod/Aql/ShortestPathExecutor.cpp
- arangod/Graph/AttributeWeightShortestPathFinder.cpp
- arangod/Graph/AttributeWeightShortestPathFinder.h
- arangod/Graph/ConstantWeightShortestPathFinder.cpp
- arangod/Graph/ConstantWeightShortestPathFinder.h
- arangod/Graph/KShortestPathsFinder.cpp
- arangod/Graph/KShortestPathsFinder.h
- arangod/Graph/ShortestPathFinder.cpp
- arangod/Graph/ShortestPathFinder.h
- tests/Aql/ShortestPathExecutorTest.cpp
Make sure the KShortestPathsExecutor resets the KShortestPathFinder correctly, including all caches.
Unfortunately there is no easy way to reproduce failure, so no regression test.
> KShortestPathsExecutor must reset its KShortestPathFinder, including all caches.
