arangodb/arangodb

- js/client/modules/@arangodb/testsuites/recovery.js
Add tests for encryption key rotation
Companion PR to https://github.com/arangodb/enterprise/pull/487
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10560/
> fix and test encryption rotation

- arangod/Aql/Ast.cpp
- arangod/Aql/GraphNode.cpp
- arangod/Aql/QueryContext.cpp
- arangod/Aql/QueryContext.h
> [3.7] Use ResultT for looking up graphs

- CHANGELOG
> Add CHANGELOG entry for failover graph not found error

- arangod/Aql/AqlCallStack.cpp
- arangod/Aql/AqlCallStack.h
- arangod/Aql/AqlExecuteResult.cpp
- arangod/Aql/AqlItemBlockInputMatrix.cpp
- arangod/Aql/AqlItemBlockInputMatrix.h
- arangod/Aql/AqlItemBlockInputRange.cpp
- arangod/Aql/AqlItemBlockInputRange.h
- arangod/Aql/DependencyProxy.cpp
- arangod/Aql/ExecutionBlockImpl.cpp
- arangod/Aql/ExecutionPlan.cpp
- arangod/Aql/MultiAqlItemBlockInputRange.cpp
- arangod/Aql/MultiAqlItemBlockInputRange.h
- arangod/Aql/OutputAqlItemRow.cpp
- arangod/Aql/RemoteExecutor.cpp
- arangod/Aql/SkipResult.cpp
- arangod/Aql/SkipResult.h
This change is already covered by existing tests, such as *all AQL tests*.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10578/
> Bug fix/make aql fast again 8

- arangod/Aql/Query.cpp
Query profiling is currently broken when using parallel traversals, looks like code that was leftover during a merge
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/10637/
> Fix query profile with parallel traversals

- arangod/GeneralServer/CommTask.cpp
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/10641/
> Bug fix 3.7/tryagain admin server whitelist

- arangod/Aql/Query.cpp
Jenkins run: http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/10641/
Enterprise PR: https://github.com/arangodb/enterprise/pull/490
> Fix query profile traversals

- tests/Aql/RowFetcherHelper.cpp
- tests/Aql/RowFetcherHelper.h
These caused compile warnings.
> Remove some unused variables

- tests/js/server/aql/aql-iresearch-view-executor-regression.js
This only adds a test.
No user-visible change.
No Api change.
No Production Change.
=> No changelog requried.
Jenkins:
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/10670/
> Added regression test for ViewExecutor Skip as well

- CHANGELOG
- arangod/Aql/IResearchViewExecutor.cpp
- tests/IResearch/IResearchQueryJoin-test.cpp
- tests/js/server/aql/aql-iresearch-view-executor-regression.js
> [3.7] Fix IResearchViewExecutor to return upstream state, not DONE 

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/aardvark.js
- js/apps/system/_admin/aardvark/APP/frontend/js/arango/arango.js
- js/apps/system/_admin/aardvark/APP/frontend/js/views/viewView.js
Same as: https://github.com/arangodb/arangodb/pull/11989
> Bug fix 3.7/ui passthrough errors aardvark jobs

- arangod/Aql/Ast.cpp
- arangod/Aql/GraphNode.cpp
- arangod/Aql/Query.cpp
- arangod/Aql/Query.h
> [3.6] Use ResultT for looking up graphs

- CHANGELOG
Added a CHANGELOG entry for #11901
> Added a CHANGELOG entry for #11901

- CHANGELOG
Added a CHANGELOG entry for #11893
> Added a CHANGELOG entry for #11893

- CHANGELOG
Added a CHANGELOG entry for #11892
> Added a CHANGELOG entry for #11892

- tests/IResearch/IResearchFeature-test.cpp
> fix iresearch mac startsyncers test problems

- arangod/Aql/ConstFetcher.cpp
- arangod/Aql/ConstFetcher.h
- arangod/Aql/IdExecutor.cpp
- arangod/Aql/IdExecutor.h
- arangod/Aql/InputAqlItemRow.cpp
- arangod/Aql/InputAqlItemRow.h
- arangod/Aql/MultiDependencySingleRowFetcher.cpp
- arangod/Aql/MultiDependencySingleRowFetcher.h
- arangod/Aql/ShadowAqlItemRow.cpp
- arangod/Aql/ShadowAqlItemRow.h
- arangod/Aql/SingleRowFetcher.cpp
- arangod/Aql/SingleRowFetcher.h
Remove uncalled methods from the code base, or mark some methods that are only used in tests as test-only.
The compiler will validate if any of these methods is still used somewhere.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10761/
> remove some unused methods, or mark them as test-only

- arangod/IResearch/IResearchFilterFactory.cpp
- tests/js/common/aql/aql-view-arangosearch-cluster.inc
- tests/js/common/aql/aql-view-arangosearch-noncluster.js
disallow using V8 dependent function in SEARCH statement
covered by newly added JS tests
> bug-fix/internal-issue-#724

- CHANGELOG
- arangod/IResearch/IResearchFilterFactory.cpp
- tests/js/common/aql/aql-view-arangosearch-cluster.inc
- tests/js/common/aql/aql-view-arangosearch-noncluster.js
> [3.7] bug-fix/internal-issue-#724

- CHANGELOG
- arangod/IResearch/IResearchFilterFactory.cpp
- tests/js/common/aql/aql-view-arangosearch-cluster.inc
- tests/js/common/aql/aql-view-arangosearch-noncluster.js
> [3.6] bug-fix/internal-issue-#724

- CHANGELOG
- arangod/IResearch/IResearchFilterFactory.cpp
- tests/js/common/aql/aql-view-arangosearch-cluster.inc
- tests/js/common/aql/aql-view-arangosearch-noncluster.js
> [3.5] bug-fix/internal-issue-#724

- CHANGELOG
- arangod/Auth/TokenCache.cpp
- arangod/GeneralServer/HttpCommTask.cpp
- arangod/RestHandler/RestAdminLogHandler.cpp
- arangod/RestHandler/RestAdminLogHandler.h
- lib/Logger/LoggerFeature.cpp
- lib/Logger/LoggerFeature.h
- lib/SimpleHttpClient/Communicator.cpp
- lib/SimpleHttpClient/SimpleHttpClient.cpp
This is a backport of a fix in devel.
> Correct some log entries.

- arangod/RocksDBEngine/RocksDBMetaCollection.cpp
Backport of https://github.com/arangodb/arangodb/pull/12086
Jenkins: https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/10835/ (blue)
http://jenkins.arangodb.biz:8080/job/arangodb-ANY-linux-asan/315/
> [3.7] Fix AR-60: memory leak in recovery

- arangod/GeneralServer/CommTask.cpp
- arangod/GeneralServer/CommTask.h
- arangod/GeneralServer/H2CommTask.cpp
- arangod/GeneralServer/H2CommTask.h
- arangod/GeneralServer/HttpCommTask.cpp
- arangod/GeneralServer/RestHandlerFactory.cpp
- arangod/GeneralServer/RestHandlerFactory.h
- arangod/GeneralServer/VstCommTask.cpp
- arangod/RestHandler/RestBatchHandler.cpp
- arangod/RestHandler/RestHandlerCreator.h
- arangod/Statistics/RequestStatistics.h
- lib/Rest/HttpResponse.h
> fix concurrency issue in H2CommTask

- 3rdParty/fuerte/include/fuerte/connection.h
- 3rdParty/fuerte/include/fuerte/types.h
- 3rdParty/fuerte/src/H2Connection.cpp
- 3rdParty/fuerte/src/H2Connection.h
- arangod/GeneralServer/H2CommTask.cpp
- arangod/GeneralServer/HttpCommTask.cpp
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/10882/
Improves compatibility with h2spec testing tool
> Feature 3.7/http2 prior knowledge

- CHANGELOG
- arangod/Agency/AgencyComm.cpp
- arangod/Cluster/ClusterInfo.cpp
> agency locks for hot backup with client id

- 3rdParty/iresearch/core/search/levenshtein_filter.cpp
- arangod/IResearch/IResearchFilterFactory.cpp
> bug-fix/internal-issue-#678

- 3rdParty/iresearch/core/search/levenshtein_filter.cpp
- arangod/IResearch/IResearchFilterFactory.cpp
> [3.7] bug-fix/internal-issue-#678

- arangod/Cluster/ClusterInfo.cpp
- arangod/Cluster/ClusterMethods.cpp
This ports some things back from devel. No functionality is actually
changed, only better readability and error messages.
> Improve code around agency hotbackup locks.

- CHANGELOG
- arangod/Graph/GraphManager.cpp
- arangod/Graph/GraphManager.h
- arangod/Graph/GraphOperations.cpp
Same as: https://github.com/arangodb/arangodb/pull/12143
> Bug fix 3.5/edit edge vertex validation

- ubsan_arangodb_suppressions.txt
Add proper suppressions for UndefinedBehaviorSanitizer (UBSan).
This change is already covered by existing tests, such as *nightly ASan tests*.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10982/
> add proper suppressions for UBSan

- 3rdParty/V8/gyp/LICENSE
- LICENSES-OTHER-COMPONENTS.md
- PULL_REQUEST_TEMPLATE.md
- utils/generateLicense.py
- utils/node-module-licenses.py
* Add V8 gyp license
* Update license information, add date & missing ones
* Add remark to generateLicense.py (broken)
Backport of #11553
> Documentation/license 3rdparty (#11553)

- tests/js/client/communication/test-communication.js
Try to provide more debug output for `communication` test suite in case it fails
This change is already covered by existing tests, such as *communication*.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11010/
> add debugging facilities to communication test

- arangod/Aql/AllRowsFetcher.h
- arangod/Aql/AqlCall.h
- arangod/Aql/AqlCallStack.cpp
- arangod/Aql/BlocksWithClients.cpp
- arangod/Aql/BlocksWithClients.h
- arangod/Aql/ConstFetcher.cpp
- arangod/Aql/ExecutionBlock.cpp
- arangod/Aql/ExecutionBlock.h
- arangod/Aql/MutexExecutor.cpp
- arangod/Aql/MutexExecutor.h
- arangod/Aql/OutputAqlItemRow.cpp
- arangod/Aql/QueryOptions.cpp
- arangod/Aql/QueryOptions.h
- arangod/Aql/SubqueryExecutor.cpp
- arangod/Cache/Manager.cpp
- arangod/Cluster/ActionDescription.cpp
- arangod/Cluster/ClusterFeature.cpp
- arangod/Cluster/SynchronizeShard.cpp
- arangod/Graph/GraphManager.cpp
- arangod/Scheduler/SupervisedScheduler.cpp
- arangod/Statistics/StatisticsWorker.cpp
- lib/Utilities/ScriptLoader.cpp
Really minor and unimportant stuff.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11018/
> fix a couple of really minor issues

- Documentation/DocuBlocks/Rest/Collections/1_structs.md
- Documentation/DocuBlocks/Rest/Collections/post_api_collection.md
> Fix schema attribute in Swagger for POST /_api/collection

- CHANGELOG
- arangod/Aql/ExecutionNode.cpp
- arangod/Aql/Query.cpp
Backport of https://github.com/arangodb/arangodb/pull/12219
Jenkins: https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/11070/
> [3.7] Fix crash in cleanup of parallel traversal query 

- CHANGELOG
- arangod/Cluster/ClusterMethods.cpp
- arangod/RestHandler/RestAdminServerHandler.cpp
- arangod/RocksDBEngine/RocksDBEngine.h
- lib/Basics/FileUtils.cpp
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/10988/
> Actually copy encryption files

- README.md
> Updated Introduction and added Oasis Section

- arangod/Aql/ExecutionEngine.cpp
- arangod/Aql/Query.cpp
- arangod/Aql/SharedQueryState.cpp
- arangod/Aql/SharedQueryState.h
- arangod/RestServer/QueryRegistryFeature.cpp
- arangod/RestServer/QueryRegistryFeature.h
Backport of https://github.com/arangodb/arangodb/pull/12234
> [3.7] Make maximum query parallelism configurable.

- 3rdParty/fuerte/src/AsioSockets.h
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/11151/
related to https://arangodb.atlassian.net/browse/BTS-146
> avoid throwing exception in fuerte

- 3rdParty/fuerte/src/AsioSockets.h
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/11153/
> Add try catch around SSL options

- CHANGELOG
- arangod/Cluster/ClusterInfo.cpp
- tests/js/server/resilience/analyzers/analyzers-revision-cluster.js
Backport for PR #12160 
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11239/
> Bug fix 3.7/analyzers revisions for updated cluster

- js/client/modules/@arangodb/process-utils.js
- js/client/modules/@arangodb/test-utils.js
backport of https://github.com/arangodb/arangodb/pull/12282
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11236/
> 3.6: fix aggregation of death message of SUT in case of instance death

- arangod/Agency/Agent.cpp
don't use c++17 language features
> fix c++14 compilation

- js/client/modules/@arangodb/process-utils.js
- js/client/modules/@arangodb/test-utils.js
backport of https://github.com/arangodb/arangodb/pull/12260
> Bug fix 3.7/fix test status sut died

- js/client/modules/@arangodb/process-utils.js
- js/client/modules/@arangodb/test-utils.js
Backport of https://github.com/arangodb/arangodb/pull/12284 
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11240/
> 3.5: fix aggregation of death message of SUT in case of instance death

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/arango/arango.js
Fix issue #12248 
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11281/
> fixed issue #12248

- arangod/Cluster/ClusterInfo.cpp
Attempt to fix BTS-137 by making sure we reload plan if view isn't found
Jenkins: https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/11270/ (blue except unrelated)
> Attempt to fix BTS-137

- CHANGELOG
- arangod/RestHandler/RestCollectionHandler.cpp
Fix issue #12349 
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11324/
> fixed issue #12349: arangosh compact Arangoerror 404.

- Documentation/DocuBlocks/Rest/Collections/1_structs.md
- Documentation/DocuBlocks/Rest/Collections/post_api_collection.md
- Documentation/DocuBlocks/Rest/Database/get_api_database_new.md
- Documentation/DocuBlocks/Rest/Graph/1_structs.md
- Documentation/DocuBlocks/Rest/Graph/general_graph_create_http_examples.md
- Documentation/DocuBlocks/Rest/Graph/general_graph_list_http_examples.md
- Documentation/DocuBlocks/collectionProperties.md
Forward port of commits to #12230
> Docs: Add additional EE only remarks

- 3rdParty/fuerte/src/AsioSockets.h
bts-146 @KVS85 
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/11351/
> another pointless bugfix

- arangod/Aql/QueryCursor.cpp
- arangod/RestHandler/RestCursorHandler.cpp
- tests/js/common/shell/shell-query-stream.js
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/11353/
> Fix a hanging query shutdown

- CMakeLists.txt
Backport of https://github.com/arangodb/arangodb/pull/11845.
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11394/
> Fix compiler versions check in CMake

- CHANGELOG
- arangod/Aql/IResearchViewNode.cpp
- tests/IResearch/IResearchViewNode-test.cpp
- tests/js/common/aql/aql-view-arangosearch-cluster.inc
- tests/js/common/aql/aql-view-arangosearch-noncluster.js
Backport fix for internal issue #739
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/11388/
> Bug fix 3.5/internal issue #739

- arangod/RocksDBEngine/RocksDBIndex.cpp
- arangod/RocksDBEngine/RocksDBKeyBounds.cpp
- arangod/RocksDBEngine/RocksDBKeyBounds.h
- arangod/RocksDBEngine/RocksDBVPackIndex.cpp
- tests/RocksDBEngine/KeyTest.cpp
- tests/js/client/shell/shell-transaction.js
Backport of https://github.com/arangodb/arangodb/pull/12328
Jenkins: https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/11311/ (blue except known unrelated failures)
> Speed up full-range scan in indexes

- arangod/Cluster/ClusterInfo.cpp
- arangosh/Benchmark/test-cases.h
- tests/js/common/shell/shell-explain-cluster.js
Fix minor issues. See commits.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11317/
> Bug fix 3.7/small issues 20200731

- Documentation/DocuBlocks/Rest/Documents/post_create_document.md
- Documentation/DocuBlocks/Rest/Documents/post_create_multiple_document.md
> Docs: overwrite requires _key attribute (sharding)

- CHANGELOG
- arangod/Aql/SortedCollectExecutor.cpp
- tests/js/server/aql/aql-optimizer-collect-methods.js
> [3.6] Bug fix/sorted collect reported null as undefined

- CHANGELOG
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/11439/
> CHANGELOG only for hotbackup s3 validation fix.

- arangod/Cluster/ClusterMethods.cpp
- arangod/Network/Utils.cpp
https://arangodb.atlassian.net/browse/BTS-163
> Improve robustness of error handling

- CHANGELOG
- arangod/Aql/SortedCollectExecutor.cpp
- tests/js/server/aql/aql-optimizer-collect-methods.js
> [3.5] Bug fix/sorted collect reported null as undefined

- CHANGELOG
- arangod/Cluster/ClusterMethods.cpp
- arangod/Cluster/FollowerInfo.cpp
- arangod/ClusterEngine/ClusterTransactionState.cpp
- arangod/MMFiles/MMFilesLogfileManager.cpp
- arangod/RestHandler/RestDocumentHandler.cpp
- arangod/RocksDBEngine/RocksDBTransactionState.cpp
- arangod/StorageEngine/TransactionState.h
- arangod/Transaction/Context.cpp
- arangod/Transaction/Context.h
- arangod/Transaction/Hints.h
- arangod/Transaction/Manager.cpp
- arangod/Transaction/Manager.h
- arangod/Transaction/Methods.cpp
- tests/RocksDBEngine/TransactionManagerTest.cpp
This is about hotbackup running into blockages, if hotbackup has stopped
new write transactions, but a leader write transaction is already ongoing
and the corresponding follower transaction can no longer be started.
> Port a fix from 3.6 to 3.5.

- PULL_REQUEST_TEMPLATE.md
This PR simplifies our PR template, so that filling it out becomes less work.
> simplify PR template

- 3rdParty/CMakeLists.txt
> Exclude immer lib from installation

- tests/js/common/aql/aql-view-arangosearch-cluster.inc
- tests/js/common/aql/aql-view-arangosearch-noncluster.js
Adds tests for case introduced by internal issue #748 
Devel does not have this issue as code for reading values was rewritten. But in sake of coverage added tests with more than two sorted values.
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/11477/
> Bug fix/internal issue #748

- arangod/Aql/ClusterNodes.cpp
Do as the code comments said:
remove some attributes from serialization that were last used in ArangoDB 3.3.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11484/
> obey them comments

- arangod/Aql/Query.cpp
- arangod/Aql/RestAqlHandler.cpp
- arangod/GeneralServer/AsyncJobManager.cpp
- arangod/RestHandler/RestCursorHandler.cpp
- tests/js/client/communication/test-kill.js
- tests/js/client/shell/shell-aql-kill.js
Fix for https://arangodb.atlassian.net/browse/BTS-167
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/11499/
> Fix cancel cursor via Job API

- CHANGELOG
- arangod/VocBase/LogicalCollection.cpp
- arangod/VocBase/Methods/Collections.cpp
- js/client/modules/@arangodb/process-utils.js
- tests/js/server/shell/shell-followers-cluster.js
> [3.7] Set writeConcern on DBServers

- CHANGELOG
- arangod/Cluster/ClusterTrxMethods.cpp
- tests/js/common/shell/shell-aqlfunctions.js
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/11445/
> Improve Cluster udfs (#12407)

- arangod/Cluster/ClusterMethods.cpp
- arangod/Network/Utils.cpp
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/11447/
> Improve robustness of error handling (#12412)

- CHANGELOG
- arangod/Aql/RestAqlHandler.cpp
- arangod/Aql/SharedQueryState.cpp
- arangod/Cluster/ClusterComm.cpp
- arangod/Cluster/ClusterComm.h
- arangod/Cluster/ClusterMethods.cpp
- arangod/GeneralServer/AsyncJobManager.cpp
- arangod/RestHandler/RestCursorHandler.cpp
- scripts/startLocalCluster.sh
- tests/js/client/shell/shell-aql-kill.js
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/11497/
> Fix canceling a cursor handler via Job API

- arangod/Aql/Functions.cpp
- arangod/IResearch/IResearchFilterFactory.cpp
- tests/Aql/LevenshteinMatchFunctionTest.cpp
- tests/IResearch/IResearchFilterFunction-test.cpp
- tests/IResearch/IResearchQueryLevenshteinMatch-test.cpp
- tests/js/common/aql/aql-view-arangosearch-noncluster.js
https://github.com/arangodb/backlog/issues/731
> bug-fix/internal-issue-#731

- arangod/Aql/Functions.cpp
- arangod/IResearch/IResearchFilterFactory.cpp
- tests/Aql/LevenshteinMatchFunctionTest.cpp
- tests/IResearch/IResearchFilterFunction-test.cpp
- tests/IResearch/IResearchQueryLevenshteinMatch-test.cpp
- tests/js/common/aql/aql-view-arangosearch-noncluster.js
> bug-fix/internal-issue-#731 (#12457)

- CHANGELOG
- arangod/Cluster/ClusterFeature.cpp
> Bug fix 3.6/too early access to vocbase for clusterfeature

- CHANGELOG
This was a user-PR and the changelog entry forgotten.
> Add fixed issue #8941 to CHANGELOG

- 3rdParty/iresearch/core/index/index_writer.cpp
- 3rdParty/iresearch/core/index/index_writer.hpp
- CHANGELOG
- arangod/IResearch/IResearchLink.cpp
- arangod/IResearch/IResearchLink.h
- arangod/IResearch/IResearchMMFilesLink.h
- arangod/IResearch/IResearchRocksDBLink.h
- arangod/IResearch/IResearchRocksDBRecoveryHelper.cpp
- tests/js/server/recovery/view-arangosearch-link-populate-truncate-no-flushthread.js
- tests/js/server/recovery/view-arangosearch-link-populate-truncate-replay.js
- tests/js/server/recovery/view-arangosearch-link-populate-truncate.js
Backporting fix for internal issue #742 to 3.6
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/11558/
> Fix storing storage engine tick for truncate operation (3.6) 

- Documentation/DocuBlocks/Rest/Graph/1_structs.md
- Documentation/DocuBlocks/Rest/Graph/general_graph_list_http_examples.md
Same as: https://github.com/arangodb/arangodb/pull/12466/commits but for 3.7
> added isDisjoint to docublocks

- 3rdParty/iresearch/core/index/index_writer.cpp
- 3rdParty/iresearch/core/index/index_writer.hpp
- CHANGELOG
- arangod/IResearch/IResearchLink.cpp
- arangod/IResearch/IResearchLink.h
- arangod/IResearch/IResearchRocksDBLink.h
- arangod/IResearch/IResearchRocksDBRecoveryHelper.cpp
- tests/js/server/recovery/view-arangosearch-link-populate-truncate-no-flushthread.js
- tests/js/server/recovery/view-arangosearch-link-populate-truncate-replay.js
- tests/js/server/recovery/view-arangosearch-link-populate-truncate.js
Backporting fix for internal issue #742 to 3.7
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/11556/
> Fix storing storage engine tick for truncate operation (3.7)

- arangod/Aql/IResearchViewNode.cpp
- arangod/Aql/OptimizerRules.cpp
- tests/IResearch/IResearchQueryJoin-test.cpp
- tests/IResearch/IResearchQueryOptions-test.cpp
- tests/IResearch/IResearchQuerySelectAll-test.cpp
- tests/IResearch/IResearchViewNode-test.cpp
- tests/IResearch/common.cpp
- tests/IResearch/common.h
- tests/js/common/aql/aql-view-arangosearch-cluster.inc
- tests/js/common/aql/aql-view-arangosearch-noncluster.js
- tests/js/server/aql/aql-optimizer-rule-late-document-materialization-arangosearch-primary-sort.inc
- tests/js/server/aql/aql-optimizer-rule-late-document-materialization-arangosearch.inc
fix for https://github.com/arangodb/backlog/issues/744
> bug-fix/internal-issue-#744

- 3rdParty/iresearch/core/index/index_writer.cpp
- 3rdParty/iresearch/core/index/index_writer.hpp
- CHANGELOG
- arangod/IResearch/IResearchLink.cpp
- arangod/IResearch/IResearchLink.h
- arangod/IResearch/IResearchMMFilesLink.h
- arangod/IResearch/IResearchRocksDBLink.h
- arangod/IResearch/IResearchRocksDBRecoveryHelper.cpp
- tests/js/server/recovery/view-arangosearch-link-populate-truncate-no-flushthread.js
- tests/js/server/recovery/view-arangosearch-link-populate-truncate-replay.js
- tests/js/server/recovery/view-arangosearch-link-populate-truncate.js
Backport for fix internal issue #742 to 3.5
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/11563/
> Fix storing storage engine tick for truncate operation (3.5)

- 3rdParty/fuerte/src/GeneralConnection.h
- 3rdParty/fuerte/src/H1Connection.cpp
- 3rdParty/fuerte/src/H1Connection.h
- 3rdParty/fuerte/src/H2Connection.cpp
Additional assertions suggested by TLA+ model.
Some comment corrections.
Some code removals.
> This is a sub-PR to suggest some changes.

- CHANGELOG
- arangod/Aql/Ast.cpp
- arangod/Aql/grammar.cpp
- arangod/Aql/grammar.y
- tests/js/server/aql/aql-graph-traverser.js
- tests/js/server/aql/aql-graph.js
- tests/js/server/aql/aql-with-collections.js
Bugfix for Github issue #12507. 
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11620/
> Bug fix/issue 12507

- 3rdParty/iresearch/core/index/index_writer.cpp
- 3rdParty/iresearch/external/kaldi/src/fstext/determinize-star-inl.h
PR fixes internal issue #747 (fix is verified by upstream tests)
Also PR contains minor fix for ASAN detected issue (trivial change without test coverage)
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/11625/
> Internal issue fix #747  + ASAN issue

- CHANGELOG
- arangod/IResearch/AqlHelper.cpp
- arangod/IResearch/AqlHelper.h
- arangod/IResearch/IResearchFilterFactory.cpp
- tests/IResearch/IResearchQueryPhrase-test.cpp
- tests/IResearch/IResearchQueryStartsWith-test.cpp
- tests/js/common/aql/aql-view-arangosearch-cluster.inc
- tests/js/common/aql/aql-view-arangosearch-noncluster.js
backport of #12496 
also includes fix for https://github.com/arangodb/backlog/issues/738
> bug-fix/internal-issue-#741 (#12496)

- Documentation/DocuBlocks/Rest/Graph/general_graph_create_http_examples.md
Backport of https://github.com/arangodb/arangodb/pull/12466/files#diff-f08d5faf317d385c8c25e7fa23ac8d02
> Add another isDisjoint to DocuBlock

- js/apps/system/_admin/aardvark/APP/frontend/js/templates/userPermissionView.ejs
Typo fix, should potentially be backported.
This was suggested by a user in the #improvements Community Slack channel.
> UI: Change authentication to authorization level in userPermissionView.ejs

- arangod/StorageEngine/RocksDBOptionFeature.cpp
> Add version info to RocksDB options new in v3.7.1

- ISSUE_TEMPLATE.md
Slightly simplify issue template
> update our ISSUE_TEMPLATE to 2020

- Documentation/DocuBlocks/Rest/Transactions/get_api_transactions.md
Fix errors in transaction API documentation.
> fix error in docs

- CHANGELOG
- Installation/Windows/Plugins/exitcodes.nsh
- js/common/bootstrap/exitcodes.js
- lib/ApplicationFeatures/LanguageFeature.cpp
- lib/Basics/exitcodes.cpp
- lib/Basics/exitcodes.dat
- lib/Basics/exitcodes.h
- tests/Basics/icu-helper.cpp
backport of https://github.com/arangodb/arangodb/pull/12493
> Feature 3.5/icu exit code

- Installation/Windows/Templates/NSIS.template.in
backport of  https://github.com/arangodb/arangodb/pull/12504
> more debugging whether we found a previously installed arango (#12504)

- CHANGELOG
- arangod/IResearch/IResearchLink.cpp
- arangod/IResearch/IResearchLink.h
- arangod/IResearch/IResearchMMFilesLink.h
- arangod/IResearch/IResearchRocksDBLink.h
- arangod/IResearch/IResearchRocksDBRecoveryHelper.cpp
- arangod/Indexes/Index.h
- arangod/MMFiles/MMFilesCollection.cpp
- arangod/MMFiles/MMFilesIndex.h
- arangod/RocksDBEngine/RocksDBBuilderIndex.cpp
- arangod/RocksDBEngine/RocksDBBuilderIndex.h
- arangod/RocksDBEngine/RocksDBCollection.cpp
- arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
- arangod/RocksDBEngine/RocksDBEdgeIndex.h
- arangod/RocksDBEngine/RocksDBIndex.cpp
- arangod/RocksDBEngine/RocksDBIndex.h
- arangod/RocksDBEngine/RocksDBVPackIndex.cpp
- arangod/RocksDBEngine/RocksDBVPackIndex.h
- tests/Mocks/StorageEngineMock.cpp
Backport for fix BTS-183
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/11706/
> Fix internal issue BTS 183 (3.5)

- CHANGELOG
- arangod/IResearch/IResearchLink.cpp
- arangod/IResearch/IResearchLink.h
- arangod/IResearch/IResearchMMFilesLink.h
- arangod/IResearch/IResearchRocksDBLink.h
- arangod/IResearch/IResearchRocksDBRecoveryHelper.cpp
- arangod/Indexes/Index.h
- arangod/MMFiles/MMFilesCollection.cpp
- arangod/MMFiles/MMFilesIndex.h
- arangod/RocksDBEngine/RocksDBBuilderIndex.cpp
- arangod/RocksDBEngine/RocksDBBuilderIndex.h
- arangod/RocksDBEngine/RocksDBCollection.cpp
- arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
- arangod/RocksDBEngine/RocksDBEdgeIndex.h
- arangod/RocksDBEngine/RocksDBIndex.cpp
- arangod/RocksDBEngine/RocksDBIndex.h
- arangod/RocksDBEngine/RocksDBVPackIndex.cpp
- arangod/RocksDBEngine/RocksDBVPackIndex.h
- tests/Mocks/StorageEngineMock.cpp
Backport for fix BTS-183
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/11703/
> Fix internal issue BTS 183  (3.6)

- Documentation/DocuBlocks/Rest/Views/post_api_view_arangosearch.md
> API descriptions for primarySortCompression & storedValues

- CHANGELOG
- arangod/IResearch/IResearchLink.cpp
- arangod/IResearch/IResearchLink.h
- arangod/IResearch/IResearchRocksDBLink.h
- arangod/IResearch/IResearchRocksDBRecoveryHelper.cpp
- arangod/Indexes/Index.h
- arangod/RocksDBEngine/RocksDBBuilderIndex.cpp
- arangod/RocksDBEngine/RocksDBBuilderIndex.h
- arangod/RocksDBEngine/RocksDBCollection.cpp
- arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
- arangod/RocksDBEngine/RocksDBEdgeIndex.h
- arangod/RocksDBEngine/RocksDBIndex.cpp
- arangod/RocksDBEngine/RocksDBIndex.h
- arangod/RocksDBEngine/RocksDBVPackIndex.cpp
- arangod/RocksDBEngine/RocksDBVPackIndex.h
- tests/Mocks/StorageEngineMock.cpp
Backported fix for BTS-183
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/11699/
> Fix internal issue BTS-183 (3.7)

- arangod/Statistics/StatisticsWorker.cpp
Additionally:
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11762/
> Fix arangodb_process_statistics_user_time description (3.7)

- arangod/Statistics/StatisticsWorker.cpp
Additionally:
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11760/
> Fix arangodb_process_statistics_user_time description

- arangod/GeneralServer/CommTask.cpp
Fix BTS-200: https://arangodb.atlassian.net/browse/BTS-200
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11774/
> fix BTS-200

- tests/js/common/aql/aql-view-arangosearch-cluster.inc
- tests/js/common/aql/aql-view-arangosearch-noncluster.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11795/
http://jenkins01.arangodb.biz:8080/view/Mac/job/arangodb-ANY-mac-matrix/1221/
> Add waitForSync to unstable ArangoSearch tests (3.6)

- tests/js/common/aql/aql-view-arangosearch-cluster.inc
- tests/js/common/aql/aql-view-arangosearch-noncluster.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11797/
http://jenkins01.arangodb.biz:8080/view/Mac/job/arangodb-ANY-mac-matrix/1223/
> Add missing ArangoSearch tests to 3.7

- tests/js/common/aql/aql-view-arangosearch-cluster.inc
- tests/js/common/aql/aql-view-arangosearch-noncluster.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11796/
http://jenkins01.arangodb.biz:8080/view/Mac/job/arangodb-ANY-mac-matrix/1222/
> Add waitForSync to unstable ArangoSearch tests

- arangod/Agency/AgencyComm.cpp
- arangod/Agency/AgencyComm.h
> [3.5] Try to improve error message extraction

- 3rdParty/fuerte/src/GeneralConnection.h
- 3rdParty/fuerte/src/H1Connection.cpp
> cancel timer when expired

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/views/loginView.js
Whenever an LDAP user was logged out due to a failed LDAP search, the UI kept infinitely reloading the login window. Another login was only possible with a new browser-tab. This pull request changes the behavior, such that the user is entirely logged out when the jwt login is not valid anymore and a subsequent login can be performed in the same browser-tab. 
Additionally:
Please note that for legal reasons we require you to sign the [Contributor …
> Fix infinite UI reload

- arangod/Agency/AgencyComm.cpp
- arangod/Agency/AgencyComm.h
> [3.7] Try to improve error message extraction

- arangod/GeneralServer/CommTask.cpp
- arangod/Transaction/Methods.cpp
Backport of https://github.com/arangodb/arangodb/pull/12632
Jenkins: https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/11805/
> Add truncate context for audit logging

- README_maintainers.md
- js/client/modules/@arangodb/testsuites/drivers.js
- js/client/modules/@arangodb/testsuites/php.js
> add php unittest support

- arangod/Transaction/V8Context.cpp
- arangod/VocBase/Methods/Transactions.cpp
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/12022/
> fix assertion

- arangod/IResearch/IResearchFeature.cpp
Bug-fix for https://arangodb.atlassian.net/browse/ES-696
> bug-fix/internal-issue-#762

- CHANGELOG
- arangod/IResearch/IResearchFeature.cpp
backport of https://github.com/arangodb/arangodb/pull/12736
> bug-fix-3.7/internal-issue-#762

- CHANGELOG
- arangod/Aql/AqlCall.h
- arangod/Aql/LimitExecutor.cpp
- arangod/Aql/LimitExecutor.h
- js/server/modules/@arangodb/aql-profiler-test-helper.js
- tests/js/server/aql/aql-profiler.js
Backport of https://github.com/arangodb/arangodb/pull/12719
> [3.7] Fix LIMIT with COLLECT WITH COUNT INTO

- arangod/GeneralServer/H2CommTask.cpp
- arangod/GeneralServer/H2CommTask.h
- arangod/GeneralServer/VstCommTask.cpp
- arangod/GeneralServer/VstCommTask.h
Jenkins: https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/12028/
> Use dynamically-sized response queue to prevent full queues

- CHANGELOG
- arangod/IResearch/IResearchFeature.cpp
backport of https://github.com/arangodb/arangodb/pull/12736
> bug-fix-3.6/internal-issue-#762

- CHANGELOG
- arangod/Agency/AgentCallback.cpp
> overly verbose

- CHANGELOG
- arangod/RestHandler/RestReplicationHandler.cpp
- arangod/RestHandler/RestTransactionHandler.cpp
- arangod/Transaction/Manager.cpp
- arangod/Transaction/Manager.h
- tests/Transaction/Manager-test.cpp
- tests/js/client/shell/shell-transaction.js
Jenkins: https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/12085/
> Fix BTS-191

- arangod/Agency/Agent.cpp
- arangod/Agency/Agent.h
- arangod/Agency/Constituent.cpp
- arangod/Agency/Constituent.h
- arangod/Agency/State.cpp
- lib/Logger/LogThread.cpp
> [3.7] efficient empty appends

- arangod/Aql/SortingGatherExecutor.cpp
- tests/js/client/shell/shell-aql-regression-cluster.js
In case of a softlimit 0 do not update a empty dependency. This triggered an assertion in maintainer mode.
It seems that the behavior in production code was correct, just suboptimal. So a CHANGELOG entry seems unnecessary.
> Bugfix Sorting Gather Executor

- arangod/Aql/SortingGatherExecutor.cpp
- tests/js/client/shell/shell-aql-regression-cluster.js
> [3.7] Bugfix Sorting Gather Executor

- Documentation/DocuBlocks/Rest/Administration/put_admin_compact.md
https://github.com/arangodb/arangodb/pull/12559
https://github.com/arangodb/arangodb/pull/12583
https://github.com/arangodb/arangodb/pull/12573
https://github.com/arangodb/arangodb/pull/12572
Needs backports 3.5..3.7
https://jenkins01.arangodb.biz/view/Documentation/job/arangodb-ANY-examples/675/
> Document PUT /_admin/compact

- CHANGELOG
- arangod/Aql/QueryList.cpp
- arangod/Aql/QueryList.h
- arangod/RestServer/QueryRegistryFeature.cpp
- arangod/RestServer/QueryRegistryFeature.h
Add option to hide query string in log / WebUI
Additionally:
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/12226/
> Add option to hide query string in log / WebUI

- arangod/Cluster/RebootTracker.cpp
- arangod/RestHandler/RestReplicationHandler.cpp
Improve some log messages
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12232/
> add more details to error messages

- CHANGELOG
- arangod/Aql/QueryList.cpp
- arangod/Aql/QueryList.h
- arangod/RestServer/QueryRegistryFeature.cpp
- arangod/RestServer/QueryRegistryFeature.h
Add new options for query string tracking
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12229/
> added new options for query string tracking

- Documentation/DocuBlocks/Rest/Administration/put_admin_compact.md
> Document PUT /_admin/compact (#12666)

- arangod/RestServer/TtlFeature.cpp
- tests/js/common/shell/shell-ttl.js
reproduce the case that @Jirka-Mayer describes in https://github.com/arangodb/arangodb/issues/12807
> mixed ttl and persistent index

- arangod/Aql/CollectNode.cpp
- arangod/Aql/CollectNode.h
- arangod/Aql/CollectOptions.h
- arangod/Aql/ExecutionNode.cpp
- arangod/Aql/ExecutionPlan.cpp
- arangod/Aql/OptimizerRules.cpp
Refactor the collect vars
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/12178/
> Refactor collect vars

- CHANGELOG
- arangod/Cluster/ClusterMethods.cpp
- arangod/Cluster/ClusterMethods.h
- arangod/ClusterEngine/ClusterRestWalHandler.cpp
- arangod/ClusterEngine/ClusterV8Functions.cpp
- arangod/GeneralServer/RestHandler.cpp
- arangod/RocksDBEngine/RocksDBRestWalHandler.cpp
- arangod/Statistics/RequestStatistics.cpp
- arangod/Statistics/RequestStatistics.h
Remove some obsolete internal parameters
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12176/
> remove some obsolete internal parameters

- Documentation/DocuBlocks/Rest/Collections/get_api_collection_figures.md
> HTTP API: New details URL parameter for figures endpoint (#12662)

- CHANGELOG
- arangod/Agency/FailedLeader.cpp
- tests/Agency/FailedLeaderTest.cpp
Additionally:
Jenkins:
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/12270/
> Port of PR #12848 Improved FailedLeader job

- arangod/RocksDBEngine/RocksDBCuckooIndexEstimator.h
- arangod/RocksDBEngine/RocksDBMetaCollection.cpp
- arangod/RocksDBEngine/RocksDBMetadata.cpp
- arangod/RocksDBEngine/RocksDBMetadata.h
- arangod/RocksDBEngine/RocksDBRecoveryManager.cpp
- arangod/RocksDBEngine/RocksDBReplicationContext.cpp
- arangod/RocksDBEngine/RocksDBSettingsManager.cpp
Port of https://github.com/arangodb/arangodb/pull/12864 and https://github.com/arangodb/arangodb/pull/12882
Jenkins: https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/12385/
> Persist count changes from recovery to avoid lost updates 

- UnitTests/OskarTestSuitesBlackList
Added `restart` testsuite to the block-list.
I intend to add the `restart` test suite to 3.6, 3.7 and devel.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12374/
> block-list the _restart_ tests

- arangod/RocksDBEngine/RocksDBMetaCollection.cpp
- arangod/RocksDBEngine/RocksDBReplicationContext.cpp
- arangod/RocksDBEngine/RocksDBTransactionCollection.cpp
- arangod/RocksDBEngine/RocksDBTransactionState.cpp
Port of https://github.com/arangodb/arangodb/pull/12882
Jenkins: https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/12386/
> [3.6] Fix read-only counter adjustments

- CHANGELOG
- arangosh/Shell/ClientFeature.cpp
- lib/Endpoint/Endpoint.h
- lib/Endpoint/EndpointIpV4.cpp
- lib/Endpoint/EndpointIpV4.h
- lib/Endpoint/EndpointIpV6.cpp
- lib/Endpoint/EndpointIpV6.h
- lib/V8/v8-utils.cpp
backport of  https://github.com/arangodb/arangodb/pull/12873
> Feature 3.7/dont connet broadcast bind address

- CHANGELOG
- arangod/Cluster/SynchronizeShard.cpp
- arangod/Cluster/SynchronizeShard.h
- arangod/MMFiles/MMFilesCollection.cpp
- arangod/MMFiles/MMFilesCollection.h
- arangod/MMFiles/MMFilesDitch.h
- arangod/Replication/DatabaseInitialSyncer.cpp
- arangod/Replication/DatabaseInitialSyncer.h
- arangod/RestHandler/RestReplicationHandler.cpp
- arangod/RocksDBEngine/RocksDBCollection.cpp
- arangod/RocksDBEngine/RocksDBCollection.h
- arangod/RocksDBEngine/RocksDBCollectionMeta.cpp
- arangod/RocksDBEngine/RocksDBCollectionMeta.h
- arangod/RocksDBEngine/RocksDBCommon.cpp
- arangod/RocksDBEngine/RocksDBCommon.h
- arangod/RocksDBEngine/RocksDBCuckooIndexEstimator.h
- arangod/RocksDBEngine/RocksDBIncrementalSync.cpp
- arangod/RocksDBEngine/RocksDBRecoveryManager.cpp
- arangod/RocksDBEngine/RocksDBReplicationContext.cpp
- arangod/RocksDBEngine/RocksDBReplicationContext.h
- arangod/RocksDBEngine/RocksDBSettingsManager.cpp
- arangod/RocksDBEngine/RocksDBTransactionCollection.cpp
- arangod/RocksDBEngine/RocksDBTransactionState.cpp
- arangod/StorageEngine/PhysicalCollection.cpp
- arangod/StorageEngine/PhysicalCollection.h
- arangod/Transaction/Methods.cpp
- js/client/modules/@arangodb/process-utils.js
- js/client/modules/@arangodb/testsuites/recovery.js
- tests/js/client/shell/shell-collection-counts-cluster-rocksdb.js
- tests/js/server/recovery/collection-count.js
Fix collection counts on replication and getting-in-sync.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12410/
> make collection counts get in sync on replication

- js/client/modules/@arangodb/arango-collection.js
Fix return value of truncate operation to again return undefined.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12429/
> fix return value of truncate back to undefined

- arangod/Aql/AstResources.cpp
- arangod/Aql/QueryRegistry.cpp
- tests/js/server/aql/aql-failures-cluster.js
Add tests for failing insertion into query registry.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12431/
> add failure test for QueryRegistry::insertQuery

- CHANGELOG
This is just CHANGELOG PR.
The fix is enterprise only
Additionally:
> Bug fix/indexes on disjoint smart edges

- 3rdParty/iresearch/core/search/disjunction.hpp
- 3rdParty/iresearch/core/search/ngram_similarity_filter.cpp
backport of fixes from iresearch upstream, covered by corresponding upstream unit tests
> bug-fix-3.7/internal-issue-#767

- README_maintainers.md
> fixed java driver documentation: JDK 11 is required

- js/common/bootstrap/errors.js
- lib/Basics/errors.dat
- lib/Basics/voc-errors.cpp
- lib/Basics/voc-errors.h
> make error message more clear

- arangod/Aql/AqlItemBlock.cpp
- js/common/modules/@arangodb/aql/explainer.js
Generate a more verbose internal error message for debugging
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12316/
> improve internal error message for an internal error

- CHANGELOG
> fix typos in CHANGELOG

- PULL_REQUEST_TEMPLATE.md
Slightly simplify the PR template, hopefully making it a bit quicker to fill out.
This only changes PULL_REQUEST_TEMPLATE.md
There is also an enterprise part for this PR, which will add a PULL_REQUEST_TEMPLATE file for the arangodb/enterprise repository: https://github.com/arangodb/enterprise/pull/579
Additionally:
> try to simplify the PR template a bit

- arangod/Agency/State.cpp
- arangod/Cluster/AgencyCache.cpp
- arangod/Cluster/ClusterFeature.cpp
- arangod/Cluster/ClusterInfo.cpp
- arangod/Cluster/RestClusterHandler.cpp
- arangod/RocksDBEngine/RocksDBMetadata.cpp
This PR fixes a few things which were found in the 3.7 version when
I ported the last round of scalability changes to devel and 3.6.
The `_log_size` one is an actual bug, the others are more for prettiness
and consistency between the branches.
- Please compiler.
- Fix _log_size in agency State.
- Typo.
- Correct error messagesCorrect error messages.
- Small performance tuning.
- Tiny performance improvement.
> Some cleanup for scalability improvements.

- arangosh/Shell/ClientFeature.cpp
- js/client/modules/@arangodb/testsuites/arangosh.js
- js/client/modules/@arangodb/testsuites/endpoints.js
This was broken temporarily during unreleased 3.7.5 development via https://github.com/arangodb/arangodb/pull/12885.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12474/
> re-allow VST connections in arangosh

- CHANGELOG
- arangod/IResearch/IResearchRocksDBRecoveryHelper.h
- tests/CMakeLists.txt
- tests/IResearch/IResearchRocksDBRecoveryHelper-test.cpp
- tests/js/server/recovery/view-arangosearch-link-populate.js
Backport for fix BTS-233
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/12571/
> Bug fix 3.7/bts 233

- CHANGELOG
- arangod/Cluster/ClusterMethods.cpp
- arangod/Cluster/ClusterMethods.h
- arangod/IResearch/IResearchLinkHelper.cpp
Backport of: https://github.com/arangodb/arangodb/pull/12901/
No cherry-pick conflicts.
When we created a view on a SmartEdgeCollection, the internal handling on the
index disallowed to unlink the view again.
Additionally:
Jenkins:
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/12451/
> Bug fix/unlink view on smart edge collection (#12901)

- CHANGELOG
- arangod/Cluster/AgencyCache.cpp
- arangod/Cluster/AgencyCache.h
- arangod/Cluster/ClusterInfo.cpp
> [3.7] change set history clearing agency cache

- CHANGELOG
- arangod/IResearch/IResearchRocksDBRecoveryHelper.h
- tests/CMakeLists.txt
- tests/IResearch/IResearchRocksDBRecoveryHelper-test.cpp
- tests/js/server/recovery/view-arangosearch-link-populate.js
Backport fix BTS-233
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/12573/
> Bug fix 3.7/bts-233.2

- 3rdParty/CMakeLists.txt
- 3rdParty/fuerte/src/AsioSockets.h
- 3rdParty/jemalloc/CMakeLists.txt
- CHANGELOG
- CMakeLists.txt
- arangod/Cluster/ClusterFeature.cpp
- arangod/Cluster/ClusterFeature.h
- arangod/Cluster/HeartbeatThread.cpp
- arangod/Cluster/HeartbeatThread.h
- arangod/RestHandler/RestStatusHandler.cpp
- arangod/RestHandler/RestStatusHandler.h
> added memory profiles, fixed memory leak

- CHANGELOG
- arangod/IResearch/IResearchRocksDBRecoveryHelper.h
- tests/CMakeLists.txt
- tests/IResearch/IResearchRocksDBRecoveryHelper-test.cpp
- tests/js/server/recovery/view-arangosearch-link-populate.js
Backport fix for issue BTS-233
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/12598/
> 3.5 backport fix BTS-233

- CHANGELOG
- arangod/IResearch/IResearchRocksDBRecoveryHelper.h
- tests/CMakeLists.txt
- tests/IResearch/IResearchRocksDBRecoveryHelper-test.cpp
- tests/js/server/recovery/view-arangosearch-link-populate.js
Backport fix BTS-233
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/12596/
> 3.6 backport fix BTS-233 

- 3rdParty/CMakeLists.txt
- 3rdParty/fuerte/src/AsioSockets.h
- 3rdParty/jemalloc/CMakeLists.txt
- CHANGELOG
- CMakeLists.txt
- arangod/Cluster/ClusterFeature.cpp
- arangod/Cluster/ClusterFeature.h
- arangod/Cluster/HeartbeatThread.cpp
- arangod/Cluster/HeartbeatThread.h
- arangod/RestHandler/RestStatusHandler.cpp
- arangod/RestHandler/RestStatusHandler.h
adding memory profiler (requires USE_JEMALLOC_PROF)
> Feature 3.7/jeprof

- CHANGELOG
- arangod/Agency/Supervision.cpp
- arangod/Cluster/HeartbeatThread.cpp
Added missing exception handling to supervision thread and part of the heartbeat thread where it was previously missing.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12611/
> catch exceptions in supervision and heartbeat thread

- CHANGELOG
- arangod/Agency/Supervision.cpp
- arangod/Cluster/HeartbeatThread.cpp
Added missing exception handling to supervision thread and part of the heartbeat thread where it was previously missing.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12610/
> added missing exception handling to supervision and heartbeat threads

- 3rdParty/json-schema-validation/src/validation.cpp
- CHANGELOG
- tests/js/common/shell/shell-validation.js
Backport of #12932
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/12615/
> Fix #12778: Typo in special property string for schema validation

- CHANGELOG
- arangosh/Benchmark/BenchFeature.cpp
- arangosh/Benchmark/BenchFeature.h
- arangosh/Benchmark/BenchmarkCounter.h
- js/client/modules/@arangodb/testsuites/arangobench.js
Backport of https://github.com/arangodb/arangodb/pull/12997
> Feature 3.7/arangobench by duration

- CHANGELOG
- arangod/Aql/GraphNode.cpp
- arangod/Aql/GraphNode.h
- arangod/Aql/ShortestPathNode.cpp
- arangod/Aql/ShortestPathNode.h
- arangod/Aql/TraversalNode.cpp
- arangod/Aql/TraversalNode.h
- js/server/modules/@arangodb/aql-graph-traversal-generic-tests.js
3.7 backport of https://github.com/arangodb/arangodb/pull/13020.
> Bug fix 3.7/prune one shard

- CHANGELOG
- arangod/Cluster/ClusterMethods.cpp
- arangod/Cluster/ClusterMethods.h
- arangod/IResearch/IResearchViewCoordinator.cpp
- tests/js/server/dump/dump-cluster.js
Backport of #12988
Enterprise PR: https://github.com/arangodb/enterprise/pull/587
> [3.7] smartgraph view no duplicate data

- CHANGELOG
- Documentation/DocuBlocks/Rest/Administration/get_admin_server_availability.md
- Documentation/DocuBlocks/Rest/Administration/get_admin_statistics.md
- arangod/Aql/QueryList.cpp
- arangod/GeneralServer/RestHandler.cpp
- arangod/GeneralServer/VstCommTask.cpp
- arangod/Network/NetworkFeature.cpp
- arangod/Network/NetworkFeature.h
- arangod/Replication/ReplicationFeature.cpp
- arangod/Replication/ReplicationFeature.h
- arangod/RestHandler/RestAdminServerHandler.cpp
- arangod/RestHandler/RestReplicationHandler.cpp
- arangod/RestServer/QueryRegistryFeature.cpp
- arangod/RestServer/QueryRegistryFeature.h
- arangod/Scheduler/Scheduler.h
- arangod/Scheduler/SchedulerFeature.cpp
- arangod/Scheduler/SchedulerFeature.h
- arangod/Scheduler/SupervisedScheduler.cpp
- arangod/Scheduler/SupervisedScheduler.h
- tests/Cluster/ClusterCommTest.cpp
- tests/Cluster/RebootTrackerTest.cpp
Backport of https://github.com/arangodb/arangodb/pull/13035 for 3.6.9
> Feature 3.6.9/even more observability

- js/client/modules/@arangodb/testsuites/arangobench.js
Arangobench can write a json result file. 
This PR adds checks to the arangobench testsuite, that make it write these report files, and check for basic entegrity of the contents. 
Report-Files look like this: 
```json
{ 
"histogram" : { 
"0" : { 
"IntervalSize" : 0.000006542205810546875, 
"50.000000" : 0.00032711029052734375, 
"80.000000" : 0.00033365249633789064, 
"85.000000" : 0.0003401947021484375, 
"90.000000" : 0.0003467369079589844, 
"95.000000" : 0.00035327911376953125, 
"99.000000" : 0.00035982131958007814 
} 
}, 
"totalNumberOfOperations" : 1, 
"runs" : 1, 
"keepAlive" : true, 
"async" : false, 
"batchSize" : 0, 
"replicationFactor" : 1, 
"numberOfShards" : 1, 
"waitForSync" : false, 
"concurrencyLevel" : 1, 
"testCase" : "version", 
"complexity" : 1, 
"database" : …
```
> check for correctness of the json report file

- CHANGELOG
- arangod/Aql/IResearchViewNode.cpp
- arangod/Aql/IResearchViewNode.h
- arangod/Aql/IResearchViewOptimizerRules.cpp
- tests/IResearch/IResearchQueryNoMaterialization-test.cpp
- tests/js/server/aql/aql-optimizer-rule-no-document-materialization-arangosearch.js
Backport fix for 3.7
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/12793/
> Fix internal issue #777 for 3.7

- arangosh/Benchmark/BenchFeature.cpp
- js/client/modules/@arangodb/testsuites/arangobench.js
backport of https://github.com/arangodb/arangodb/pull/13044
> Feature 3.7/arangobench add json report check2

- 3rdParty/fuerte/src/AsioSockets.h
- 3rdParty/fuerte/src/GeneralConnection.cpp
- 3rdParty/fuerte/src/HttpConnection.cpp
- 3rdParty/jemalloc/CMakeLists.txt
- CHANGELOG
- CMakeLists.txt
- arangod/RestHandler/RestStatusHandler.cpp
- arangod/RestHandler/RestStatusHandler.h
> Fuerte shutdown TLS fix and jeprof support.

- CHANGELOG
- arangod/Aql/Query.cpp
> Feature 3.6.9/aql query peak mem usage log

- CHANGELOG
- arangod/Agency/Agent.cpp
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/12906/
> clean up callbacks and empty promises in single host agency

- 3rdParty/fuerte/include/fuerte/message.h
- 3rdParty/fuerte/include/fuerte/types.h
- 3rdParty/fuerte/src/message.cpp
- 3rdParty/fuerte/src/types.cpp
- CHANGELOG
- arangod/V8Server/v8-actions.cpp
- arangosh/Shell/V8ClientConnection.cpp
- lib/Basics/StaticStrings.cpp
- lib/Basics/StaticStrings.h
- lib/Rest/GeneralRequest.h
- lib/Rest/HttpRequest.cpp
- lib/Rest/VstRequest.cpp
- tests/js/client/shell/shell-foxx-api-spec.js
- tests/js/common/test-data/apps/headers/index.js
Backport of https://github.com/arangodb/arangodb/pull/13068#event-4052110924
> 3.7: forward headers that are treated special into foxx as well. (#13068)

- js/client/modules/@arangodb/testsuites/endpoints.js
re-sync testsuite with devel, partial backport of https://github.com/arangodb/arangodb/pull/13113 broke this.
> Bug fix 3.7/fix endpoints status reporting 2

- arangosh/Benchmark/BenchFeature.cpp
- arangosh/Benchmark/BenchFeature.h
- arangosh/Benchmark/BenchmarkThread.h
Note that "unsigned long" != "uint64_t" under Windows.
> Bug fix 3.7/arangobench

- js/client/modules/@arangodb/testsuites/go.js
- js/client/modules/@arangodb/testsuites/js.js
- js/client/modules/@arangodb/testutils/process-utils.js
This adds the ability to pass multiple coordinators into arangojs tests.
https://github.com/arangodb/arangojs/issues/699
> add multiple coordinator support

- arangosh/Benchmark/BenchFeature.cpp
- arangosh/Benchmark/BenchFeature.h
- arangosh/Benchmark/BenchmarkCounter.h
- arangosh/Benchmark/BenchmarkOperation.h
- arangosh/Benchmark/BenchmarkThread.h
- arangosh/Benchmark/arangobench.cpp
- arangosh/Benchmark/test-cases.h
- js/client/modules/@arangodb/testsuites/arangobench.js
backport of https://github.com/arangodb/arangodb/pull/13132 and sync features / tests
> Bug fix 3.6/arangobench

- CHANGELOG
- arangod/Agency/Agent.cpp
- arangod/Agency/Agent.h
- arangod/Agency/RestAgencyHandler.cpp
- arangod/Cluster/AgencyCache.cpp
*Fix the agents' poll API to redirect to leader*
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/12967/
> fix agency poll api redirects

- arangod/VocBase/Methods/Transactions.cpp
- arangod/VocBase/Methods/Transactions.h
- lib/Endpoint/Endpoint.cpp
- lib/Endpoint/Endpoint.h
- lib/Endpoint/EndpointIp.cpp
- lib/Endpoint/EndpointIp.h
- lib/Endpoint/EndpointSrv.cpp
- lib/Endpoint/EndpointSrv.h
- lib/Endpoint/EndpointUnixDomain.cpp
- lib/Endpoint/EndpointUnixDomain.h
Remove code that is now unused.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13008/
> simplifications

- 3rdParty/iresearch/core/utils/async_utils.cpp
> fix use-after-free issue reported by ASAN

- 3rdParty/iresearch/core/utils/async_utils.cpp
backport of https://github.com/arangodb/arangodb/pull/13180
> bug-fix-3.7/internal-issue-#775

- 3rdParty/iresearch/core/utils/file_utils.cpp
- arangod/Cluster/ClusterInfo.cpp
PR fixes logging for two cases:
1. Logging ERROR in file removal in case of file not exists replaced with DEBUG
2. Fixed logging in analyzer modification finish in ClusterInfo. Communication error erroneously logged as "precondition failed" loosing all error related information. Now non-precondition related errors logged properly.
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/12653/
> Bug fix/search logging fixes

- tests/IResearch/IResearchFeature-test.cpp
- tests/IResearch/IResearchLink-test.cpp
backport of https://github.com/arangodb/arangodb/pull/13217
> bug-fix-3.7/make-arangosearch-tests-determintistic (#13217)

- arangod/RestHandler/RestStatusHandler.cpp
> Bug fix 3.7/jemalloc prof

- arangod/RestHandler/RestStatusHandler.cpp
> fixed typos

- arangod/RestHandler/RestStatusHandler.cpp
- tests/IResearch/IResearchFeature-test.cpp
- tests/IResearch/IResearchLink-test.cpp
> Bug fix 3.7/make arangosearch tests determintistic

- js/client/bootstrap/modules/internal.js
Backport of #13062
Depends on: #13041
> Docs: Check protocol(), throw if not http/1.1, don't filter common headers

- lib/ApplicationFeatures/ApplicationFeature.cpp
- lib/ApplicationFeatures/ApplicationFeature.h
- lib/ApplicationFeatures/ApplicationServer.cpp
- lib/ApplicationFeatures/ApplicationServer.h
Backport of https://github.com/arangodb/arangodb/pull/13129
Link to Jenkins PR run: https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/12950/
> [3.7] Fix issue with ApplicationFeature registration and startup order

- arangosh/Shell/V8ShellFeature.cpp
- js/client/modules/@arangodb/crash-utils.js
- lib/CMakeLists.txt
- lib/Utilities/IsArangoExecutable.cpp
- lib/Utilities/IsArangoExecutable.h
backport of https://github.com/arangodb/arangodb/pull/13013
> tell users they must not use arangosh to invoke these (#13013)

- arangod/Replication/DatabaseInitialSyncer.cpp
- arangod/Utils/SingleCollectionTransaction.cpp
- arangod/Utils/SingleCollectionTransaction.h
- tests/js/server/replication/sync/replication-sync.js
Add a new test to check behavior of new, revision-based replication protocol in the presence of frequent intermediate commits.
Link to Jenkins PR run: https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/13235/
> Add test for new replication protocol with intermediate commits

- ERROR_LEVELS.md
added description of ERROR LEVELS
> added error level description

- Documentation/DocuBlocks/Rest/Collections/get_api_collection_checksum.md
- Documentation/DocuBlocks/collectionChecksum.md
#13195
https://github.com/arangodb/docs/pull/596
> collection.checksum() supported in cluster now

- 3rdParty/fuerte/src/AsioSockets.h
- CHANGELOG
Ensure that the hostname is set for SNI in SSL
> Bug fix 3.7/ssl sni

- ERROR_LEVELS.md
added description of ERROR LEVELS
> Features 3.7/error levels

- CHANGELOG
- arangod/Aql/OptimizerRules.cpp
- arangod/Cluster/RestClusterHandler.cpp
- arangod/GeoIndex/Index.cpp
- tests/js/server/aql/aql-optimizer-geoindex.js
Backport of https://github.com/arangodb/arangodb/pull/13196.
> [3.7] Fixed AR-113 and added regression tests

- CHANGELOG
- arangod/Aql/OptimizerRules.cpp
- arangod/GeoIndex/Index.cpp
- tests/js/server/aql/aql-optimizer-geoindex.js
> [3.5] Fixed AR-113 and added regression tests

- arangosh/Shell/V8ShellFeature.cpp
- lib/CMakeLists.txt
- lib/Utilities/IsArangoExecutable.cpp
- lib/Utilities/IsArangoExecutable.h
backport of https://github.com/arangodb/arangodb/pull/13013
> 3.6: tell users they must not use arangosh to invoke these (#13013)

- arangod/RocksDBEngine/RocksDBOptionFeature.cpp
Clean up after a speculative change made yesterday.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13486/
> clean up after temporary changes

- tests/js/client/communication/test-communication.js
This PR just deactivates a test in Community version, as the tested feature is only available enterprise.
No Production change included.
> Only run satellite test in Enterprise mode

- 3rdParty/velocypack/include/velocypack/Exception.h
- 3rdParty/velocypack/include/velocypack/Iterator.h
- 3rdParty/velocypack/include/velocypack/Slice.h
- 3rdParty/velocypack/src/Exception.cpp
- lib/Basics/VelocyPackHelper.h
Updated VPack 3rdParty folder. unpackTuple in arangodb now uses unpackTuple from velocypack.
> UnpackTuple VPack

- arangod/RocksDBEngine/RocksDBIterators.cpp
- arangod/RocksDBEngine/RocksDBMethods.cpp
- arangod/RocksDBEngine/RocksDBTransactionState.cpp
Add some exceptions for cases that really went wrong in RocksDBMethods.cpp (should not happen, but the exceptions won't do any harm).
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13555/
> add exceptions in case something is really wrong

- CHANGELOG
- js/client/client.js
Print a version mismatch (major/minor version difference) between the arangosh version and the remote arangod version at arangosh startup.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13575/
> print client/server version mismatch at arangosh startup

- tests/Network/ConnectionPoolTest.cpp
port of "bug-fix-3.6/fix-unittest-memleak"
> fix a memleak that only happened during gtest execution

- CHANGELOG
- arangod/Aql/AstNode.cpp
- arangod/Aql/AstNode.h
backport of "bug-fix-3.6/fix-potential-leak-in-ast-node-repurposing"
> Bug fix 3.6.11/fix potential leak in ast node repurposing

- arangod/Aql/Functions.cpp
Use the popcount implementation from iresearch in the BIT_POPCOUNT AQL function
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13643/
> use iresearch's popcount implementation

- UnitTests/OskarTestSuitesBlackList
Blocklist the new devel test suite `dump_no_envelope` in 3.7.
Accompanying 3.6 PR to the following Oskar PR: https://github.com/arangodb/oskar/pull/287
Oskar PR: https://github.com/arangodb/oskar/pull/287
> blocklist a new test for devel

- CHANGELOG
This PR accompanies arangodb/enterprise#634.
It is a pure CHANGELOG entry for the other bugfix.
> Error reporting for hotbackup restore

- CHANGELOG
- js/client/modules/@arangodb/testsuites/ldap.js
backport of https://github.com/arangodb/arangodb/pull/13434
> added {USER} replacement

- CHANGELOG
- js/client/modules/@arangodb/testsuites/ldap.js
> allow {} in ldap.search-filter

- 3rdParty/fuerte/src/AsioSockets.h
- CHANGELOG
> added SNI fix

- arangod/Aql/AqlFunctionFeature.cpp
- arangod/Aql/Functions.cpp
- tests/js/server/aql/aql-functions-date.js
Integrate the changes from https://github.com/arangodb/arangodb/pull/13334 into devel.
Extra PR so that we can run Jenkins PR tests on it.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13812/
> DATE_TIMEZONEINFO

- CHANGELOG
- arangod/Aql/DocumentProducingHelper.cpp
- arangod/Aql/DocumentProducingHelper.h
Backport of https://github.com/arangodb/arangodb/pull/13514
> [3.7] Bug fix/check for kill more consistently

- arangod/GeneralServer/GeneralServer.cpp
Improves GeneralServer by leveraging <algorithm> for the intention of getting the least-clients context, and improves legibility on the stopWorking() timeout implementation.
> Small refactoring, clarifying intent

- CHANGELOG
- arangod/IResearch/IResearchRocksDBLink.cpp
bug fix for ES-784
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/13990/
> Bug-fix-3.7/es-784

- CHANGELOG
- arangod/Aql/DocumentProducingHelper.cpp
- arangod/Aql/DocumentProducingHelper.h
> [3.6] Bug fix/check for kill more consistently

- arangod/IResearch/IResearchRocksDBLink.cpp
fix for ES-748
https://github.com/arangodb/arangodb/pull/13549
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/13989/
> bug-fix/es-784

- CHANGELOG
- arangod/Aql/IndexExecutor.cpp
- arangod/Aql/IndexExecutor.h
- tests/js/server/aql/aql-queries-optimizer-count.js
Backport of: https://github.com/arangodb/arangodb/pull/13553
Please see full details there.
> Fixed a count collect bug

- CHANGELOG
- arangod/Aql/IndexExecutor.cpp
- arangod/Aql/IndexExecutor.h
- tests/js/server/aql/aql-queries-optimizer-count.js
Backport of: https://github.com/arangodb/arangodb/pull/13553
Please see full details there.
> Fixed a count collect bug 

- 3rdParty/velocypack/include/velocypack/velocypack-common.h
PR improves reading ints from vpack by creating customized code for each integer size
Many thanks to @mpoeter for cool code simplification idea!
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/14053/
> speedup integers reading from Vpack

- UnitTests/OskarTestSuitesBlackList
Add `dump_jwt` test suite to blocklist.
Accompanying PR for Oskar PR https://github.com/arangodb/oskar/pull/293
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/14062/
> add dump_jwt test to blocklist

- tests/js/client/communication/test-kill.js
when running with asan/tsan/code coverage we significantly slow down, be more patient.
> increase the timeout if we're runnig in asan / code coverage

- js/client/modules/@arangodb/testsuites/dump.js
Attempt to fix `dump_with_crashes` test. This test can result in `write-write conflicts` when 
https://github.com/arangodb/arangodb/pull/13589
https://github.com/arangodb/arangodb/pull/13590
> Added a small delay before restarting the restore procedure.

- UnitTests/OskarTestSuitesBlackList
Disable `dump_with_crashes` test.
> [3.7] Disabled test dump_with_crashes.

- tests/js/server/replication/fuzz/replication-fuzz-global.js
this PR fixes the replication fuzzing test and synchronizes it with the release-test-automation.
> fix replication fuzz test

- arangod/Scheduler/SupervisedScheduler.cpp
Remove a few unused variables from the scheduler.
The variables removed in this PR had no purpose anymore.
This is a minor change with no user-visible impact, so no CHANGELOG entry was made for it.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/14120/
> remove a few unused variables from the scheduler

- UnitTests/OskarTestSuitesBlackList
Disable `dump_with_crashes` test.
> [3.6] Disable dump_with_crashes.

- arangosh/Restore/RestoreFeature.cpp
- js/client/modules/@arangodb/testsuites/dump.js
- use proper exit method
- increase idle period for instrumented builds
> Bug fix/use proper exit method

- arangod/RestServer/QueryRegistryFeature.cpp
- arangod/RocksDBEngine/RocksDBEngine.cpp
- arangod/StorageEngine/RocksDBOptionFeature.cpp
- arangosh/Dump/DumpFeature.cpp
- arangosh/Shell/ConsoleFeature.cpp
- lib/Logger/LoggerFeature.cpp
> Docs: Don't list implied introducedIn versions

- arangod/Replication/DatabaseInitialSyncer.cpp
the scope of the builder variable would lead to use after free issues.
> fix use after free

- Documentation/DocuBlocks/Rest/Indexes/post_api_index_ttl.md
> TTL index: Correct & improve API description of expireAfter

- arangod/ClusterEngine/ClusterIndex.cpp
- arangod/ClusterEngine/ClusterIndexFactory.cpp
- arangod/Indexes/IndexFactory.cpp
- arangod/RocksDBEngine/RocksDBZkdIndex.cpp
- arangod/RocksDBEngine/RocksDBZkdIndex.h
- arangod/Zkd/ZkdHelper.cpp
- arangod/Zkd/ZkdHelper.h
- tests/Zkd/Conversion.cpp
- tests/Zkd/Library.cpp
- tests/js/server/aql/aql-optimizer-zkdindex-multi.js
- tests/js/server/aql/aql-optimizer-zkdindex.js
Adding support for index usage in cluster. Feature branch for #13650 .
> [zkd] Cluster support

- arangod/Indexes/IndexFactory.cpp
- arangod/RocksDBEngine/RocksDBZkdIndex.cpp
- tests/Zkd/Conversion.cpp
- tests/js/server/aql/aql-optimizer-zkdindex-multi.js
Development branch for #13650. Adds support for nested fields, i.e. you can specify a dimension as `a.x`.
> Added support for nested fields - excluding expansions.

- arangod/RocksDBEngine/RocksDBIndexFactory.cpp
- arangod/RocksDBEngine/RocksDBKeyBounds.cpp
- arangod/RocksDBEngine/RocksDBTypes.cpp
- arangod/RocksDBEngine/RocksDBTypes.h
- arangod/RocksDBEngine/RocksDBValue.cpp
- arangod/RocksDBEngine/RocksDBValue.h
- arangod/RocksDBEngine/RocksDBZkdIndex.cpp
- arangod/RocksDBEngine/RocksDBZkdIndex.h
- tests/js/server/aql/aql-optimizer-zkdindex-multi.js
- tests/js/server/aql/aql-optimizer-zkdindex-unique.js
Feature PR for #13650. Adds support for unique constraints.
> [zkd] Unique Constraints

- arangod/Indexes/IndexFactory.cpp
- arangod/Indexes/IndexFactory.h
- arangod/RocksDBEngine/RocksDBIndexFactory.cpp
- tests/js/server/aql/aql-optimizer-zkdindex-multi.js
- tests/js/server/aql/aql-optimizer-zkdindex-restricted.js
- tests/js/server/aql/aql-optimizer-zkdindex-unique.js
- tests/js/server/aql/aql-optimizer-zkdindex.js
Feature PR for #13650. Add a flag to the index definition that is required and allows forward compatibility for future releases.
> [zkd] Forward Compat

- arangod/RocksDBEngine/RocksDBColumnFamilyManager.cpp
- arangod/RocksDBEngine/RocksDBColumnFamilyManager.h
- arangod/RocksDBEngine/RocksDBEngine.cpp
- arangod/RocksDBEngine/RocksDBOptionFeature.cpp
- arangod/RocksDBEngine/RocksDBZkdIndex.cpp
This is a FeaturePR for #13650. It creates a new column family for the index data.
> [zkd] Column Family

- Documentation/DocuBlocks/Rest/Indexes/post_api_index_zkd.md
> [zkd] DocuBlock

- CHANGELOG
- arangod/Aql/IndexExecutor.cpp
- tests/js/server/aql/aql-optimizer-rule-optimize-count.js
Bugfix for https://github.com/arangodb/arangodb/issues/13675
> Index Count Optimization Uniqueness

- Documentation/DocuBlocks/Rest/Indexes/post_api_index.md
- Documentation/DocuBlocks/Rest/Indexes/post_api_index_persistent.md
Docublocks changes accompanying the docs PR https://github.com/arangodb/docs/pull/637
This is a documentation-only PR.
> documentation for index selectivity estimates

- tests/Graph/ClusterTraverserCacheTest.cpp
Test change only.
There was a hidden Merge conflict of an API name that changed and was used within the test.
This should now be sorted out, no production change => No Changelog.
> Fixed hidden merge conflct that causes TestFile to not compile anymore

- Documentation/Metrics/allMetrics.yaml
- Documentation/Metrics/arangodb_shards_number.yaml
- utils/makeDashboards.py
This is a very small fix for the makeDashBoards script.
Also corrects one documentation snippet.
> Small bugfixes in makedashboard script.

- CHANGELOG
- arangod/Agency/MoveShard.cpp
- tests/Agency/MoveShardTest.cpp
*MoveSahard is hardened agains unexpected VPack input for array iterators*
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/14389/
> Moveshard Iterator hardening as detected by chaos

- arangod/RestServer/MetricsFeature.cpp
Micro PR to fix some bugs in the name translation table for metrics.
> Fix some bugs in the renaming table of metrics.

- Documentation/Metrics/allMetrics.yaml
- Documentation/Metrics/arangodb_http_request_statistics_async_requests_total.yaml
- Documentation/Metrics/arangodb_http_request_statistics_http_delete_requests_total.yaml
- Documentation/Metrics/arangodb_http_request_statistics_http_get_requests_total.yaml
- Documentation/Metrics/arangodb_http_request_statistics_http_head_requests_total.yaml
- Documentation/Metrics/arangodb_http_request_statistics_http_options_requests_total.yaml
- Documentation/Metrics/arangodb_http_request_statistics_http_patch_requests_total.yaml
- Documentation/Metrics/arangodb_http_request_statistics_http_post_requests_total.yaml
- Documentation/Metrics/arangodb_http_request_statistics_http_put_requests_total.yaml
- Documentation/Metrics/arangodb_http_request_statistics_other_http_requests_total.yaml
- Documentation/Metrics/arangodb_http_request_statistics_superuser_requests_total.yaml
- Documentation/Metrics/arangodb_http_request_statistics_total_requests_total.yaml
- Documentation/Metrics/arangodb_http_request_statistics_user_requests_total.yaml
Improve a few metrics documentation texts.
This does the HTTP/VST request statistic ones.
- [*] No backports required
> Improve a few metrics documentation texts

- Documentation/Metrics/allMetrics.yaml
- Documentation/Metrics/arangodb_agency_cache_callback_number.yaml
- Documentation/Metrics/arangodb_agency_callback_number.yaml
- Documentation/Metrics/arangodb_agency_callback_registered_total.yaml
- Documentation/Metrics/arangodb_agency_client_lookup_table_size.yaml
- Documentation/Metrics/arangodb_agency_log_size_bytes.yaml
- Documentation/Metrics/arangodb_aql_all_query_total.yaml
- Documentation/Metrics/arangodb_aql_current_query.yaml
- Documentation/Metrics/arangodb_aql_global_memory_limit.yaml
- Documentation/Metrics/arangodb_aql_global_memory_usage.yaml
- Documentation/Metrics/arangodb_aql_query_time.yaml
- Documentation/Metrics/arangodb_aql_slow_query_time.yaml
- Documentation/Metrics/arangodb_aql_total_query_time_msec_total.yaml
- Documentation/Metrics/arangodb_dropped_followers_total.yaml
- Documentation/Metrics/arangodb_intermediate_commits_total.yaml
- Documentation/Metrics/arangodb_network_request_duration_as_percentage_of_timeout.yaml
- Documentation/Metrics/arangodb_refused_followers_total.yaml
- Documentation/Metrics/arangodb_server_statistics_cpu_cores.yaml
- Documentation/Metrics/arangodb_server_statistics_idle_percent.yaml
- Documentation/Metrics/arangodb_server_statistics_iowait_percent.yaml
- Documentation/Metrics/arangodb_server_statistics_physical_memory.yaml
- Documentation/Metrics/arangodb_server_statistics_server_uptime_total.yaml
- Documentation/Metrics/arangodb_server_statistics_system_percent.yaml
- Documentation/Metrics/arangodb_server_statistics_user_percent.yaml
- Documentation/Metrics/arangodb_transactions_aborted_total.yaml
- Documentation/Metrics/arangodb_transactions_committed_total.yaml
- Documentation/Metrics/arangodb_transactions_expired_total.yaml
- Documentation/Metrics/arangodb_transactions_started_total.yaml
- arangod/RestServer/MetricsFeature.cpp
- arangod/RestServer/MetricsFeature.h
Backport of https://github.com/arangodb/arangodb/pull/13769
Added documentation for several metrics.
> document several metrics

- utils/generateAllMetricsDocumentation.py
Fix python script to generate/check metrics to not depend on locale.
This is a bug fix for an internal script.
> Make metrics script more robust

- Documentation/DocuBlocks/Rest/Cursors/post_api_cursor.md
> Docs: Correct description of streaming cursor

- CHANGELOG
- arangod/Aql/IResearchViewNode.cpp
- tests/js/common/aql/aql-view-arangosearch-cluster.inc
- tests/js/common/aql/aql-view-arangosearch-noncluster.js
Fix a regression introduced by streaming transactions
https://github.com/arangodb/backlog/issues/802
> bug-fix/internal-issue-#802

- utils/generateAllMetricsDocumentation.py
Fix python script to generate/check metrics to not depend on locale.
This is a bug fix for an internal script.
> make metrics check/generation script more robust

- arangod/RocksDBEngine/RocksDBZkdIndex.cpp
- arangod/Zkd/ZkdHelper.cpp
- arangod/Zkd/ZkdHelper.h
This is a feature branch for #13650. This is a speedup for the testInBox and compareWithBox function.
> [zkd] testInBox speedup

- CHANGELOG
- arangod/IResearch/IResearchFeature.cpp
- tests/js/common/aql/aql-view-arangosearch-cluster.inc
- tests/js/common/aql/aql-view-arangosearch-noncluster.js
backport of https://github.com/arangodb/arangodb/pull/13786
> bug-fix-3.8/internal-issue-#806

- CHANGELOG
- arangod/Aql/IResearchViewNode.cpp
- tests/js/common/aql/aql-view-arangosearch-cluster.inc
- tests/js/common/aql/aql-view-arangosearch-noncluster.js
backport of https://github.com/arangodb/arangodb/pull/13797
> bug-fix-3.7/internal-issue-#802

- CHANGELOG
- arangod/IResearch/IResearchFeature.cpp
- tests/js/common/aql/aql-view-arangosearch-cluster.inc
- tests/js/common/aql/aql-view-arangosearch-noncluster.js
> bug-fix-3.7/internal-issue-#806

- js/client/modules/@arangodb/testsuites/recovery_cluster.js
backport of https://github.com/arangodb/arangodb/pull/13792
> Bug fix 3.8/test cluster recovery connection timeout

- js/client/modules/@arangodb/testsuites/recovery_cluster.js
backport of https://github.com/arangodb/arangodb/pull/13792
> fix cluster recovery test timeouts (#13792)

- Documentation/Metrics/allMetrics.yaml
- Documentation/Metrics/arangodb_connection_pool_connections_created_total.yaml
- Documentation/Metrics/arangodb_connection_pool_connections_current.yaml
- Documentation/Metrics/arangodb_connection_pool_lease_time_hist.yaml
- Documentation/Metrics/arangodb_connection_pool_leases_failed_total.yaml
- Documentation/Metrics/arangodb_connection_pool_leases_successful_total.yaml
- utils/makeDashboards.py
Add documentation for the metrics of the connection pools.
Also: Improve dashboard titles.
> Connection pool metrics documentation

- Documentation/Metrics/allMetrics.yaml
- Documentation/Metrics/arangodb_client_connection_statistics_bytes_received.yaml
- Documentation/Metrics/arangodb_client_connection_statistics_bytes_sent.yaml
- Documentation/Metrics/arangodb_client_connection_statistics_client_connections.yaml
- Documentation/Metrics/arangodb_client_connection_statistics_connection_time.yaml
- Documentation/Metrics/arangodb_client_connection_statistics_io_time.yaml
- Documentation/Metrics/arangodb_client_connection_statistics_queue_time.yaml
- Documentation/Metrics/arangodb_client_connection_statistics_request_time.yaml
- Documentation/Metrics/arangodb_client_connection_statistics_total_time.yaml
Add documentation for connection statistics metrics.
> Add documentation for connection statistics metrics.

- Documentation/Metrics/allMetrics.yaml
- Documentation/Metrics/arangodb_client_connection_statistics_bytes_received.yaml
- Documentation/Metrics/arangodb_client_connection_statistics_bytes_sent.yaml
- Documentation/Metrics/arangodb_client_connection_statistics_client_connections.yaml
- Documentation/Metrics/arangodb_client_connection_statistics_connection_time.yaml
- Documentation/Metrics/arangodb_client_connection_statistics_io_time.yaml
- Documentation/Metrics/arangodb_client_connection_statistics_queue_time.yaml
- Documentation/Metrics/arangodb_client_connection_statistics_request_time.yaml
- Documentation/Metrics/arangodb_client_connection_statistics_total_time.yaml
Backport of #13842
Add documentation for connection statistics metrics.
> documentation-3.8/Add documentation for connection statistics metrics.

- Documentation/Metrics/allMetrics.yaml
- Documentation/Metrics/arangodb_v8_context_alive.yaml
- Documentation/Metrics/arangodb_v8_context_busy.yaml
- Documentation/Metrics/arangodb_v8_context_created_total.yaml
- Documentation/Metrics/arangodb_v8_context_creation_time_msec_total.yaml
- Documentation/Metrics/arangodb_v8_context_destroyed_total.yaml
- Documentation/Metrics/arangodb_v8_context_dirty.yaml
- Documentation/Metrics/arangodb_v8_context_enter_failures_total.yaml
- Documentation/Metrics/arangodb_v8_context_entered_total.yaml
- Documentation/Metrics/arangodb_v8_context_exited_total.yaml
- Documentation/Metrics/arangodb_v8_context_free.yaml
- Documentation/Metrics/arangodb_v8_context_max.yaml
- Documentation/Metrics/arangodb_v8_context_min.yaml
This adds documentation for the V8 metrics.
> V8 metrics documentation

- Documentation/Metrics/allMetrics.yaml
- Documentation/Metrics/arangodb_replication_synchronous_requests_total_number_total.yaml
- Documentation/Metrics/arangodb_replication_synchronous_requests_total_time_total.yaml
- Documentation/Metrics/arangodb_replication_tailing_apply_time_total.yaml
- Documentation/Metrics/arangodb_replication_tailing_bytes_received_total.yaml
- Documentation/Metrics/arangodb_replication_tailing_documents_total.yaml
- Documentation/Metrics/arangodb_replication_tailing_follow_tick_failures_total.yaml
- Documentation/Metrics/arangodb_replication_tailing_markers_total.yaml
- Documentation/Metrics/arangodb_replication_tailing_removals_total.yaml
- Documentation/Metrics/arangodb_replication_tailing_request_time_total.yaml
- Documentation/Metrics/arangodb_replication_tailing_requests_total.yaml
Same as: https://github.com/arangodb/arangodb/pull/13845
> 3.8 Feature/cleanup replication sync tailing metric statistics

- 3rdParty/fuerte/include/fuerte/connection.h
- CHANGELOG
- arangosh/Shell/V8ClientConnection.cpp
- arangosh/Shell/V8ClientConnection.h
backport of https://github.com/arangodb/arangodb/pull/13598
> Feature 3.6/arangosh connection cache (#13821)

- Documentation/Metrics/arangodb_replication_cluster_inventory_requests_total.yaml
- Documentation/Metrics/arangodb_replication_failed_connects_total.yaml
- Documentation/Metrics/arangodb_scheduler_low_prio_queue_last_dequeue_time.yaml
Three typos, forward-port 3.8 -> devel.
> Perfect harmony devel 3.8 metrics

- arangod/IResearch/IResearchAqlAnalyzer.cpp
Removes now redundant check for Undefined return type.
> remove check

- arangod/IResearch/IResearchAnalyzerFeature.cpp
- arangod/IResearch/IResearchAnalyzerFeature.h
- arangod/IResearch/IResearchAnalyzerValueTypeAttribute.h
- arangod/IResearch/IResearchAqlAnalyzer.cpp
- arangod/IResearch/IResearchAqlAnalyzer.h
- arangod/IResearch/IResearchDocument.cpp
- arangod/IResearch/IResearchDocument.h
- arangod/IResearch/IResearchVPackTermAttribute.h
- tests/IResearch/IResearchAqlAnalyzer-test.cpp
- tests/IResearch/IResearchDocument-test.cpp
- tests/js/common/aql/aql-view-arangosearch-feature.js
Backport https://github.com/arangodb/arangodb/pull/13894 for 3.8
> Feature 3.8/return type for aql analyzer

- arangod/Aql/AqlCall.h
- arangod/Aql/InputAqlItemRow.cpp
- arangod/Cache/CachedValue.cpp
- arangod/Cluster/ClusterInfo.cpp
- arangod/Cluster/ClusterInfo.h
- arangod/Graph/Providers/ClusterProvider.h
- arangod/Graph/Providers/SingleServerProvider.h
- arangod/IResearch/ExpressionFilter.cpp
- arangod/IResearch/GeoFilter.cpp
Some fixes for warnings produced by cppcheck.
> some fixes for cppcheck warnings

- Documentation/DocuBlocks/Rest/Administration/get_admin_log.md
- Documentation/DocuBlocks/Rest/Administration/get_api_endpoint.md
> DocuBlock: Improve deprecation hint for /_admin/log

- tests/js/client/communication/test-communication.js
backport of https://github.com/arangodb/arangodb/pull/13925
> 3.8: convert test to making it use the fuerte arango connection

- lib/Basics/SharedAtomic.h
- utils/cppcheck.sh
Link to Jenkins PR run: http://jenkins01.arangodb.biz:8080/job/arangodb-ANY-cppcheck/20/
> ignore internal cppcheck errors

- CHANGELOG
- arangod/ClusterEngine/ClusterCollection.cpp
- arangod/ClusterEngine/ClusterCollection.h
- arangod/RocksDBEngine/RocksDBCollection.cpp
- arangod/RocksDBEngine/RocksDBCollection.h
- arangod/RocksDBEngine/RocksDBVPackIndex.cpp
- arangod/StorageEngine/PhysicalCollection.h
- arangod/VocBase/LogicalCollection.cpp
- tests/Mocks/StorageEngineMock.cpp
- tests/Mocks/StorageEngineMock.h
> [3.7] BTS-352

- CHANGELOG
- arangod/Aql/IResearchViewExecutor.cpp
- arangod/Aql/MaterializeExecutor.cpp
- arangod/ClusterEngine/ClusterCollection.cpp
- arangod/ClusterEngine/ClusterCollection.h
- arangod/Graph/Cache/RefactoredTraverserCache.cpp
- arangod/Graph/Cursors/RefactoredSingleServerEdgeCursor.cpp
- arangod/Graph/SingleServerEdgeCursor.cpp
- arangod/Indexes/IndexIterator.cpp
- arangod/RocksDBEngine/RocksDBCollection.cpp
- arangod/RocksDBEngine/RocksDBCollection.h
- arangod/RocksDBEngine/RocksDBGeoIndex.cpp
- arangod/RocksDBEngine/RocksDBVPackIndex.cpp
- arangod/StorageEngine/PhysicalCollection.h
- tests/Mocks/StorageEngineMock.cpp
- tests/Mocks/StorageEngineMock.h
Backport for https://github.com/arangodb/arangodb/pull/13967
> [3.8] BTS-352

- tests/js/client/shell/shell-deadlock-trx-hotbackup-cluster.js
Improve the test that executes hot backups concurrently with exclusive transactions.
Slightly lower the requirements (less successful exclusive transactions are required), and make the test finish successfully earlier, once it has completed enough backups and transactions.
This PR only changes the test, so intentionally no CHANGELOG written for it.
> improve hotbackup vs. trx test

- CHANGELOG
- lib/Logger/LogTopic.cpp
This is a forward port of the 3.6 feature request.
> added failover LDAP provider (#13917)

- CHANGELOG
- arangod/Cluster/HeartbeatThread.cpp
- arangod/Cluster/HeartbeatThread.h
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/14971/
> [3.8] timely update of rebootIds and cluster memberships in clusterinfo

- 3rdParty/iresearch/core/formats/formats_10.cpp
- CHANGELOG
backport of https://github.com/arangodb/arangodb/pull/14013
> bug-fix-3.8/internal-issue-#700

- 3rdParty/iresearch/core/formats/formats_10.cpp
- CHANGELOG
backport of https://github.com/arangodb/arangodb/pull/14013
> bug-fix-3.7/internal-issue-#700

- 3rdParty/iresearch/core/formats/formats_10.cpp
- CHANGELOG
Fix for https://github.com/arangodb/backlog/issues/700
> bug-fix/internal-issue-#700

- 3rdParty/iresearch/core/formats/formats_10.cpp
- CHANGELOG
Backport of https://github.com/arangodb/arangodb/pull/14013
> bug-fix-3.6/internal-issue-#700

- README_maintainers.md
Just ran into `/bin/sh: yarn: not found`
> Web UI: Mention that Node.js and Yarn need to be installed for building

- CHANGELOG
- arangod/IResearch/IResearchLink.cpp
Backport of https://github.com/arangodb/arangodb/pull/14027
> BTS-374 (#14027)

- arangod/RestHandler/RestReplicationHandler.cpp
Revert the use of UsePadding velocypack options in RestReplicationHandler.cpp, as it obviously leads to an ASan heap buffer overflow in some restore tests.
The UsePadding behavior was introduced in RestReplicationHandler.cpp only one or two days ago and was not released.
> remove the use of UsePadding velocypack options

- CHANGELOG
- arangod/Aql/OptimizerRules.cpp
- tests/js/server/aql/aql-optimizer-rule-remove-redundant-or.js
Backport of https://github.com/arangodb/arangodb/pull/13993
> [3.6] Fix BTS-340: Prevent overzealous remove-redundant-or

- CHANGELOG
- arangod/Aql/OptimizerRules.cpp
- tests/js/server/aql/aql-optimizer-rule-remove-redundant-or.js
> [3.7] Fix BTS-340: Prevent overzealous remove-redundant-or

- CHANGELOG
- arangosh/Shell/V8ClientConnection.cpp
- lib/Basics/StaticStrings.cpp
- lib/Basics/StaticStrings.h
- tests/js/client/shell/shell-foxx-interface.js
- tests/js/client/shell/shell-vpack.js
backport of https://github.com/arangodb/arangodb/pull/14001
> 3.8: chop request functions into handy bits, reuse code (#14001)

- CHANGELOG
- arangod/Aql/OptimizerRules.cpp
- tests/js/server/aql/aql-optimizer-rule-remove-redundant-or.js
Backport of https://github.com/arangodb/arangodb/pull/13993
> [3.8] Fix BTS-340: Prevent overzealous remove-redundant-or

- 3rdParty/iresearch/core/index/index_writer.cpp
- CHANGELOG
- tests/js/common/aql/aql-view-arangosearch-feature.js
Backport of  https://github.com/arangodb/arangodb/pull/14067
> 3.7: fix internal-issue #798

- 3rdParty/iresearch/core/index/index_writer.cpp
- CHANGELOG
- tests/js/common/aql/aql-view-arangosearch-feature.js
Backport of https://github.com/arangodb/arangodb/pull/14067
> 3.8: fix internal-issue #798

- 3rdParty/iresearch/core/index/index_writer.cpp
- CHANGELOG
- tests/js/common/aql/aql-view-arangosearch-feature.js
Backport of https://github.com/arangodb/arangodb/pull/14067
> 3.6: fix internal-issue #798

- CHANGELOG
- arangod/Cluster/ActionBase.cpp
- arangod/Cluster/ActionBase.h
- arangod/Cluster/CreateCollection.cpp
- arangod/Cluster/CreateDatabase.cpp
- arangod/Cluster/DropCollection.cpp
- arangod/Cluster/DropDatabase.cpp
- arangod/Cluster/DropIndex.cpp
- arangod/Cluster/EnsureIndex.cpp
- arangod/Cluster/NonAction.cpp
- arangod/Cluster/ResignShardLeadership.cpp
- arangod/Cluster/SynchronizeShard.cpp
- arangod/Cluster/TakeoverShardLeadership.cpp
- arangod/Cluster/UpdateCollection.cpp
- arangod/IResearch/IResearchLink.cpp
- tests/Maintenance/MaintenanceFeatureTest.cpp
> [3.7] Only guarded access to actionbase result

- tests/js/common/shell/shell-pregel-start-cluster.js
- tests/js/server/shell/shell-pregel.js
> Bug fix 3.6/fix pregel tests

- tests/js/common/shell/shell-pregel-start-cluster.js
- tests/js/common/shell/shell-pregel.js
> Bug fix 3.7/fix pregel tests

- Documentation/DocuBlocks/Rest/Cursors/put_api_cursor_identifier.md
> Docs: Add deprecation remark to PUT /_api/cursor/{cursor-identifier} title

- arangod/Agency/AgencyComm.cpp
- arangod/Agency/AgencyComm.h
- arangod/Pregel/Conductor.h
- arangod/Pregel/Worker.h
- arangosh/Dump/DumpFeature.cpp
3 unrelated changes
* Remove commented-out code
* Do not include unused Boost files in header files
* Move from boost::clamp to std::clamp
> Small code cleanup

- arangod/RocksDBEngine/RocksDBTransactionState.h
- lib/Containers/MerkleTree.cpp
- lib/Containers/MerkleTree.h
- tests/Containers/MerkleTreeTest.cpp
Adds some diagnostic log message to Merkle tree grow code in case an error is triggered.
This is meant to improve our debugging.
> add diagnostics to Merkle tree

- CHANGELOG
- arangod/Aql/Collection.cpp
- arangod/Aql/Collection.h
- arangod/Auth/UserManager.cpp
- arangod/GeneralServer/CommTask.cpp
- arangod/GeneralServer/H2CommTask.cpp
- arangod/GeneralServer/H2CommTask.h
- arangod/GeneralServer/HttpCommTask.cpp
- arangod/GeneralServer/HttpCommTask.h
- arangod/GeneralServer/VstCommTask.cpp
- arangod/RestServer/BootstrapFeature.cpp
- arangod/RestServer/BootstrapFeature.h
- js/common/bootstrap/errors.js
- lib/Basics/errors.dat
- lib/Basics/voc-errors.h
- lib/Rest/GeneralResponse.cpp
- tests/js/client/authentication/auth.js
This temporarily reverts commit b738ea666fde19a3a0f38fc9f6cfdd1e784d80b8, as the change has caused problems during cluster startup in some situations.
Will be revisited next week.
> Revert "Bug fix 3.8/collection not available during start up (#14087)"

- CHANGELOG
- arangod/Aql/Collection.cpp
- arangod/Aql/Collection.h
Fix assertions failed reported in https://arangodb.atlassian.net/browse/BTS-354
> fixed issue BTS-354

- CHANGELOG
- arangod/Cluster/ClusterInfo.cpp
- scripts/startLocalCluster.sh
- tests/js/common/shell/shell-cluster-collection.js
*Fix response when isBuilding could not be removed from newly created collection, when agency precondition fails. This can happen, when own rebootId increment has triggered plan entry to be removed.*
https://github.com/arangodb/arangodb/pull/14136
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/15297/
>  coordinators isbuilding removal error handling

- 3rdParty/iresearch/core/formats/formats_10.cpp
backport a minor regression fix from iresearch upstream
- [] No backports required
> bug-fix/internal-issue-#700-1

- 3rdParty/iresearch/core/formats/formats_10.cpp
- [ч] :hankey: Bugfix (requires CHANGELOG entry)
> bug-fix-3.8/internal-issue-#700-1 (#14155)

- 3rdParty/V8/CMakeLists.txt
- 3rdParty/immer/v0.6.2/CMakeLists.txt
- 3rdParty/jemalloc/CMakeLists.txt
- 3rdParty/libunwind/CMakeLists.txt
Tried to build using Ninja, and the changes in this PR fix some issues it reported in 3rdParty.
These changes should not do any harm to non-Ninja builds, so we can use them and slightly improve the situation, even though full Ninja support is not there yet.
> fix some complaints from Ninja about 3rdParty CMakeLists

- CHANGELOG
- arangod/Cluster/ClusterInfo.cpp
- arangosh/Shell/V8ClientConnection.cpp
- js/client/modules/@arangodb/testsuites/dump.js
- tests/js/server/dump/dump-move-shard.js
*Fix BTS-403 where conflicting Current in the agency break dbserver maintenance*
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/15364/
> [3.7] clear current entries of overriden plan entries by hot restore

- arangod/Cluster/MaintenanceFeature.cpp
- arangod/RocksDBEngine/RocksDBMetaCollection.cpp
- arangod/RocksDBEngine/RocksDBMetaCollection.h
- arangod/RocksDBEngine/RocksDBMetadata.cpp
- arangod/RocksDBEngine/RocksDBV8Functions.cpp
- arangod/VocBase/LogicalCollection.cpp
- arangod/VocBase/Methods/Collections.cpp
- lib/Containers/MerkleTree.cpp
- lib/Containers/MerkleTree.h
- tests/Containers/MerkleTreeTest.cpp
- tests/js/server/recovery/revision-trees-compression-format-bottommost.js
- tests/js/server/recovery/revision-trees-compression-format-snappy.js
- tests/js/server/recovery/revision-trees-compression-format-uncompressed.js
- tests/js/server/recovery/revision-trees-corrupt.js
- tests/js/server/recovery/revision-trees-forced-hibernation-after.js
- tests/js/server/recovery/revision-trees-forced-hibernation-before.js
- tests/js/server/recovery/revision-trees-insert-fails-existing-tree.js
- tests/js/server/recovery/revision-trees-insert-fails.js
- tests/js/server/recovery/revision-trees-remove-fails-existing-tree.js
- tests/js/server/recovery/revision-trees-remove-fails.js
- tests/js/server/replication/sync/replication-sync-malarkey.js
Test cases for revision trees.
Also contains a bugfix for an existing replication test.
> Revision tree tests

- js/client/bootstrap/modules/internal.js
Fix example generation that was apparently broken by #14001
https://jenkins01.arangodb.biz/view/Documentation/job/arangodb-ANY-examples/731/
> Docs: Cast response.body from Buffer to string

- CHANGELOG
- arangod/Aql/Functions.cpp
- arangod/Aql/OptimizerRules.cpp
- arangod/Aql/WindowNode.cpp
- arangod/Aql/grammar.cpp
- arangod/Aql/grammar.h
- arangod/Aql/grammar.hpp
- arangod/Aql/grammar.y
- js/common/modules/@arangodb/aql/explainer.js
- lib/Basics/datetime.cpp
- tests/js/server/aql/aql-window-cumulative-sum.js
- tests/js/server/aql/aql-window-malarkey.js
Fix various issues related to the new WINDOW operation (see BTS-402)
- Improved explain output for ISO 8601 duration strings and fixed missing week component.
- Improved validation of input data and error messages.
- Prevent FILTERs from being moved beyond a WINDOW.
> Bug fix3.8/window operation issues

- CHANGELOG
- arangod/Aql/Functions.cpp
- arangod/Aql/OptimizerRules.cpp
- arangod/Aql/WindowNode.cpp
- arangod/Aql/grammar.cpp
- arangod/Aql/grammar.h
- arangod/Aql/grammar.hpp
- arangod/Aql/grammar.y
- js/common/modules/@arangodb/aql/explainer.js
- lib/Basics/datetime.cpp
- tests/js/server/aql/aql-window-cumulative-sum.js
- tests/js/server/aql/aql-window-malarkey.js
Fix various issues related to the new WINDOW operation (see BTS-402)
- Improved explain output for ISO 8601 duration strings and fixed missing week component.
- Improved validation of input data and error messages.
- Prevent FILTERs from being moved beyond a WINDOW.
> Fix various issues related to the new WINDOW operation (see BTS-402)

- CHANGELOG
- arangod/Transaction/Methods.cpp
**
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/15443/
> correctly report shutdown as shard leader

- arangod/Agency/AgencyComm.cpp
- arangod/Agency/AgencyComm.h
- arangod/Cluster/ClusterInfo.cpp
Reduce number of heap allocations in ClusterInfo
> reduce number of heap allocations in cluster info

- arangod/RestHandler/RestReplicationHandler.cpp
- arangod/RocksDBEngine/RocksDBMetaCollection.cpp
- arangod/RocksDBEngine/RocksDBMetaCollection.h
- arangod/StorageEngine/PhysicalCollection.cpp
- arangod/StorageEngine/PhysicalCollection.h
- lib/Containers/MerkleTree.cpp
Sub-PR to add runtime verification of MerkleTrees.
> Add tree verification at run time triggered by API, add tests

- CHANGELOG
- arangod/Actions/RestActionHandler.cpp
- arangod/GeneralServer/GeneralServerFeature.cpp
- arangod/GeneralServer/GeneralServerFeature.h
- tests/js/client/server_parameters/http-permanently-redirect-root-off.js
- tests/js/client/server_parameters/http-permanently-redirect-root-on.js
- tests/js/client/server_parameters/http-redirect-root-to-301.js
- tests/js/client/server_parameters/http-redirect-root-to-302.js
> Feature/redirect root (#14185)

- CHANGELOG
- lib/Containers/MerkleTree.cpp
- lib/Containers/MerkleTree.h
- tests/Containers/MerkleTreeTest.cpp
- tests/js/server/recovery/revision-trees-compression-format-uncompressed.js
> shave off the lowest levels of the tree

- utils/generateAllMetricsDocumentation.py
> Check return value flow of metrics YAML generator

- Documentation/DocuBlocks/Rest/AQL/GetApiQueryCurrent.md
> Docs: List possible execution state strings for GET /_api/query/current

- CHANGELOG
In case that the async or referrals or restart option is false, explicitly disable this in OpenLDAP. The current implementation only explicitly enabled it, but did not disable it.
> ensure that ON and OFF are set

- js/common/modules/@arangodb/examples/examples.js
> Add observationsSampleDataset for docs (#14226)

- tests/js/server/aql/aql-traversal-grinder.js
Grindr tests for traversals.
This PR only adds tests for existing traversal functionality.
In particular, it covers the case fixed by https://github.com/arangodb/enterprise/pull/687
The tests in this PR will crash if the fix in https://github.com/arangodb/enterprise/pull/687 is not applied.
> additional grindr tests for traversals

- 3rdParty/iresearch/core/analysis/pipeline_token_stream.cpp
- 3rdParty/iresearch/core/analysis/pipeline_token_stream.hpp
- CHANGELOG
- arangod/IResearch/IResearchAnalyzerFeature.cpp
- arangod/IResearch/IResearchIdentityAnalyzer.cpp
- arangod/IResearch/IResearchIdentityAnalyzer.h
- tests/js/common/aql/aql-view-arangosearch-feature.js
Pipeline analyzer could hold arbitrary analyzers in pipe. And if one piped analyzer emits output non compatible with next analyzer in the pipe - crash could occur. PR adds validation procedure to verify type acceptance between pipe members.
> Bug fix/check analyzers in pipeline

- 3rdParty/iresearch/core/analysis/pipeline_token_stream.cpp
- 3rdParty/iresearch/core/analysis/pipeline_token_stream.hpp
- CHANGELOG
- arangod/IResearch/IResearchAnalyzerFeature.cpp
- arangod/IResearch/IResearchIdentityAnalyzer.cpp
- arangod/IResearch/IResearchIdentityAnalyzer.h
- tests/js/common/aql/aql-view-arangosearch-feature.js
Backport for https://github.com/arangodb/arangodb/pull/14278
https://jenkins.arangodb.biz/job/arangodb-matrix-pr/15694/
> Bug fix/check analyzers in pipeline (#14278)

- js/client/modules/@arangodb/testsuites/ldap.js
Fixed AUTO testsuite detection
> fixed AUTO testsuite detection

- CHANGELOG
- lib/Geo/ShapeContainer.cpp
- tests/js/server/aql/aql-queries-geo.js
backport of https://github.com/arangodb/arangodb/pull/14314
> [3.8] BTS-457

- 3rdParty/iresearch/core/analysis/token_stopwords_stream.cpp
Fix printing errorneous token.
> Fix token printnig in stopwords analyzer

- CHANGELOG
- CMakeLists.txt
- cmake/InstallArangoDBJSClient.cmake
This reverts commit 8010d85251c3814b3d11f931ffe3526956dafc16.
> Revert "remove eslint from package.json (#14290)"

- CHANGELOG
- arangod/Cluster/Maintenance.cpp
- arangod/Cluster/SynchronizeShard.cpp
- arangod/Scheduler/SchedulerFeature.cpp
Improve specific warning log messages.
> Slightly improve specific warning messages for better readability.

- CHANGELOG
- js/common/modules/@arangodb/aql/explainer.js
Backport of #14298
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/15734/
> [3.8] Explain indexes of SHORTEST_PATH, K_SHORTEST_PATHS and K_PATHS

- 3rdParty/iresearch/core/analysis/token_stopwords_stream.cpp
- tests/js/common/aql/aql-view-arangosearch-feature.js
Backport of https://github.com/arangodb/arangodb/pull/14318
> add hex parameter (#14318)

- 3rdParty/iresearch/core/search/disjunction.hpp
- CHANGELOG
- tests/js/common/aql/aql-view-arangosearch-noncluster.js
> 3.8 Bug fix/fix devsup 753 (#14373)

- js/client/modules/@arangodb/process-utils.js
- js/client/modules/@arangodb/result-processing.js
backport of https://github.com/arangodb/arangodb/pull/14302
> search for the servers assert log messages, and print them, add them to testfailures.txt (#14302)

- tests/js/client/restart/test-soft-shutdown-cluster.js
arangosh connection should be reinitialized after a Coordinator restart
Link to Jenkins PR run: http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/15838/
> Fix soft shutdown test on Windows

- CHANGELOG
- arangod/Auth/UserManager.cpp
- arangod/Auth/UserManager.h
- tests/Auth/UserManagerClusterTest.cpp
- tests/CMakeLists.txt
* This PR fixes the internal version handling of the UserManager, w.r.t. the Cluster. The UserManager could get off-sync with the Cluster wide UserVersion, which is eventually repaired, however before this repair, the user manager could already think that it got the latest version where in fact it did not load it due to the off-sync. In "normal" clusters this is off-sync is silently repaired and hidden due to the mechanisms that actually modify the users, so no impact there, but a DC-2-DC follower could get into a bad situation where the Follower Datacenter does not regularly (or even at all)updates the user list.
> All new features should be accompanied by …
> Bug fix/user manager version race

- Documentation/DocuBlocks/Rest/Administration/get_admin_metrics_v2.md
- Documentation/Scripts/codeBlockReader.py
> Add `/_admin/metrics/v2` DocuBlock (#14324)

- UnitTests/OskarTestSuitesBlockList
Add chaos test suite to blocklist.
Accompanying PR for Oskar PR https://github.com/arangodb/oskar/pull/328
> Add chaos test to blocklist

- cmake/OptimizeForArchitecture.cmake
> Add Comet lake support. Enforce minimum required architecture: westmere.

- arangod/Graph/PathManagement/PathValidator.cpp
- arangod/Graph/PathManagement/PathValidator.h
Renamed method for better clarity.
> renamed evalExpression -> evaluateVertexExpression

- arangod/Graph/Enumerators/OneSidedEnumerator.cpp
- arangod/Graph/Enumerators/OneSidedEnumerator.h
Fix init sequence of variables being initialised while constructing OneSidedEnumerator.
> fix init of variables, test: GORDO-1213

- CHANGELOG
- arangosh/Restore/RestoreFeature.cpp
- arangosh/Restore/RestoreFeature.h
Forward port of https://github.com/arangodb/arangodb/pull/14437.
> [BTS-491][devel] ArangoRestore connect Retry

- 3rdParty/iresearch/external/absl/absl/base/dynamic_annotations.h
Fix macros definition for absl version used with iresearch
> Fix Asan build 

- CHANGELOG
- arangod/Cluster/Maintenance.cpp
> [3.7] Fixed a velocypack type error in maintenance::reportInCurrent

- tests/js/server/aql/aql-optimizer-rule-late-document-materialization-arangosearch-primary-sort.inc
- tests/js/server/aql/aql-optimizer-rule-late-document-materialization-arangosearch-stored-values.inc
- tests/js/server/aql/aql-optimizer-rule-late-document-materialization-arangosearch.inc
- tests/js/server/dump/dump-setup-common.inc
- tests/js/server/dump/dump-test.inc
- utils/jslint.sh
> quod licet iovi non licet bovi

- arangod/GeneralServer/AcceptorUnixDomain.h
- arangod/Network/ClusterUtils.h
- arangod/Network/Utils.h
- arangod/RestServer/RestartAction.h
Replace include guards with `#pragma once`
> pragma oncify

- arangod/V8Server/V8DealerFeature.cpp
JavaScript file handling improvements:
* adjust the path to node_modules to the local copy if appropriate
* add adjusted paths (to local copy) to JavaScript allow lists
> JavaScript file handling improvements:

- UnitTests/OskarTestSuitesBlockList
Disable replication2_client test in oskar.
> [3.7] Disable replication2_client test in oskar.

- 3rdParty/iresearch/external/absl/absl/base/dynamic_annotations.h
> 3.8 Fix Asan build

- UnitTests/OskarTestSuitesBlockList
Disable replication2_client test in oskar.
> [3.8] Disable replication2_client test in oskar.

- arangod/Aql/ExecutionBlockImpl.cpp
- utils/checkLogIds.py
> [3.7] Fix duplicate log id in ExecutionBlockImpl

- CHANGELOG
- arangod/Cluster/HeartbeatThread.cpp
…te of cluster info
*Allow timely update of database server lists of isolated database servers.* **Fixes BTS-505**
Link to Jenkins PR run: https://jenkins.arangodb.biz/job/arangodb-matrix-pr/16435/
> timely update of database servers in cluster cache

- js/client/modules/@arangodb/testsuites/ldap.js
Correctly join the tests paths. There was a typo in the original PR that went unoticed.
> fixed path

- arangod/Graph/WeightedEnumerator.cpp
Please see all details here: https://github.com/arangodb/enterprise/pull/722
> Hybrid Smart DisjointCE Changes 

- CHANGELOG
- arangod/Aql/Query.cpp
backport for https://github.com/arangodb/arangodb/pull/14612
> [3.8] Fix BTS-539

- lib/Basics/FeatureFlags.cpp
Disables replication 2.0 for 3.9/devel branch.
> Disable replication 2.0.

- CHANGELOG
- arangod/Transaction/Manager.cpp
- js/common/modules/jsunity.js
Fix handling of Disjoint Smart Edge Collections during _api/transaction/begin calls
> Bug fix/begin trx disjoint

- js/common/modules/jsunity.js
We now need to have unique testCase names whenever we have multiple suites per file again.
Sorry.
> Revert JSUnity improvement

- Documentation/DocuBlocks/Rest/Collections/get_api_collection_name.md
- Documentation/DocuBlocks/Rest/Collections/put_api_collection_load.md
- Documentation/DocuBlocks/Rest/Collections/put_api_collection_unload.md
Missing Swagger documentation adjustments for APM-132 (https://arangodb.atlassian.net/browse/APM-132?focusedCommentId=59788)
> docs for APM-132

- Documentation/DocuBlocks/Rest/Collections/1_structs.md
- Documentation/DocuBlocks/Rest/Collections/post_api_collection.md
- Documentation/DocuBlocks/Rest/Collections/put_api_collection_properties.md
> documentation-3.7/swagger-2021-08-24

- Documentation/DocuBlocks/Rest/Database/get_api_database_new.md
- Documentation/DocuBlocks/Rest/User Management/README.md
> Docs: Correct database and user API statements (BTS-429)

- Documentation/DocuBlocks/Rest/Collections/1_structs.md
- Documentation/DocuBlocks/Rest/Collections/post_api_collection.md
- Documentation/DocuBlocks/Rest/Collections/put_api_collection_properties.md
> documentation-3.8/swagger-2021-08-24

- arangod/Graph/ConstantWeightShortestPathFinder.h
- lib/Basics/operating-system.h
> Bug fix 3.8/mac 10 4

- arangod/Graph/ConstantWeightShortestPathFinder.h
- lib/Basics/operating-system.h
> fix for old clang

- CHANGELOG
- arangod/Cluster/HeartbeatThread.cpp
- js/server/leader.js
- js/server/modules/@arangodb/foxx/queues/manager.js
- tests/js/client/active-failover/basic.js
- tests/js/common/test-data/apps/crud/README.md
- tests/js/common/test-data/apps/crud/main.js
- tests/js/common/test-data/apps/crud/manifest.json
- tests/js/common/test-data/apps/crud/models/xxx.js
- tests/js/common/test-data/apps/crud/models/yyyy.js
- tests/js/common/test-data/apps/crud/routes/xxx.js
- tests/js/common/test-data/apps/crud/routes/yyyy.js
- tests/js/common/test-data/apps/crud/scripts/setup.js
- tests/js/common/test-data/apps/crud/scripts/teardown.js
- tests/js/common/test-data/apps/crud/test/example.js
backport of https://github.com/arangodb/arangodb/pull/14754
> 3.8 bug fix/fix active failover foxx failover

- CHANGELOG
- arangod/Cluster/HeartbeatThread.cpp
- js/server/leader.js
- js/server/modules/@arangodb/foxx/queues/manager.js
- tests/js/client/active-failover/basic.js
- tests/js/common/test-data/apps/crud/README.md
- tests/js/common/test-data/apps/crud/main.js
- tests/js/common/test-data/apps/crud/manifest.json
- tests/js/common/test-data/apps/crud/models/xxx.js
- tests/js/common/test-data/apps/crud/models/yyyy.js
- tests/js/common/test-data/apps/crud/routes/xxx.js
- tests/js/common/test-data/apps/crud/routes/yyyy.js
- tests/js/common/test-data/apps/crud/scripts/setup.js
- tests/js/common/test-data/apps/crud/scripts/teardown.js
- tests/js/common/test-data/apps/crud/test/example.js
backport of https://github.com/arangodb/arangodb/pull/14754
> 3.7 bug fix/fix active failover foxx failover

- arangod/Pregel/Conductor.cpp
- arangod/Pregel/GraphStore.cpp
- arangod/Pregel/Worker.cpp
- utils/checkLogIds.py
> fix logId check

- tests/js/client/chaos/test-chaos-load-common.inc
> Reduce nr of combinations and runtime of nightly chaos load tests.

- CHANGELOG
- arangod/Aql/OptimizerRules.cpp
- tests/js/server/aql/aql-optimizer-rule-remove-collect-variables.js
Backport of https://github.com/arangodb/arangodb/pull/14824
> [3.8] Fix crash in optimizer rule remove-collect-variables

- CHANGELOG
- arangod/Aql/DocumentProducingNode.cpp
- arangod/Aql/ExecutionNode.cpp
- arangod/Aql/Expression.cpp
- arangod/Aql/Expression.h
- arangod/Aql/LateMaterializedOptimizerRulesCommon.h
- tests/js/server/aql/aql-optimizer-rule-late-document-materialization.js
> fixed issue #14819

- Documentation/DocuBlocks/Rest/Administration/get_engine.md
- Documentation/DocuBlocks/Rest/BackupRestore/post_admin_backup_create.md
- Documentation/DocuBlocks/Rest/BackupRestore/post_admin_backup_delete.md
- Documentation/DocuBlocks/Rest/BackupRestore/post_admin_backup_download.md
- Documentation/DocuBlocks/Rest/BackupRestore/post_admin_backup_list.md
- Documentation/DocuBlocks/Rest/BackupRestore/post_admin_backup_restore.md
- Documentation/DocuBlocks/Rest/BackupRestore/post_admin_backup_upload.md
- Documentation/DocuBlocks/Rest/Collections/1_structs.md
- Documentation/DocuBlocks/Rest/Collections/put_api_collection_load_indexes_in_memory.md
- Documentation/DocuBlocks/Rest/Collections/put_api_collection_recalculate_count.md
- Documentation/DocuBlocks/Rest/Cursors/post_api_cursor.md
- Documentation/DocuBlocks/Rest/Replication/get_api_replication_revisions_tree.md
- Documentation/DocuBlocks/Rest/Replication/post_api_replication_revisions_tree.md
- Documentation/DocuBlocks/Rest/Replication/put_api_replication_revisions_documents.md
- Documentation/DocuBlocks/Rest/Replication/put_api_replication_revisions_ranges.md
- Documentation/DocuBlocks/Rest/Transactions/post_api_transaction.md
- Documentation/DocuBlocks/Rest/Transactions/post_api_transaction_begin.md
https://jenkins01.arangodb.biz/view/Documentation/job/arangodb-ANY-examples/1133/
> Docs: Remove some direct and indirect MMFiles references

- js/apps/system/_admin/aardvark/APP/frontend/js/templates/indicesView.ejs
- js/apps/system/_admin/aardvark/APP/frontend/js/views/indicesView.js
Signed-off-by: Aditya Mukhopadhyay <aditya@arangodb.com>
This PR adds a feature to enable creating ZKD indexes through the Aardvaark Web UI.
Link to Jenkins PR run: https://jenkins.arangodb.biz:3456/view/PR/job/arangodb-matrix-pr/17253/
> Added support for adding ZKD index through Web UI.

- js/apps/system/_admin/aardvark/APP/frontend/js/templates/indicesView.ejs
Signed-off-by: Aditya Mukhopadhyay <aditya@arangodb.com>
This PR adds a label to the ZKD index in the web UI to flag it as experimental.
Link to Jenkins PR run: https://jenkins.arangodb.biz:3456/view/PR/job/arangodb-matrix-pr/17279/
> Added label to mark ZKD index as experimental.

- arangod/Aql/IResearchViewExecutor.cpp
Don't copy slices unless it's absolutely necessary
- [ x No backports required
> Micro-optimization for ArangoSearch executor

- js/apps/system/_admin/aardvark/APP/frontend/js/views/graphManagementView.js
Port of: https://github.com/arangodb/arangodb/pull/15033
> UI Improvement HybridSmartGraphs

- LICENSES-OTHER-COMPONENTS.md
Update third-party licenses information.
This change only affects LICENSES-OTHER-COMPONENTS.md, so there is intentionally no CHANGELOG entry.
> update third party licenses file

- LICENSES-OTHER-COMPONENTS.md
Backport of https://github.com/arangodb/arangodb/pull/15054
Update third-party licenses information.
This change only affects LICENSES-OTHER-COMPONENTS.md, so there is intentionally no CHANGELOG entry.
> update third party licenses file (#15054)

- CHANGELOG
- arangod/Aql/ExecutionBlockImpl.cpp
- tests/Aql/FixedOutputExecutionBlockMock.cpp
- tests/Aql/FixedOutputExecutionBlockMock.h
- tests/Aql/SubqueryStartExecutorTest.cpp
- tests/CMakeLists.txt
Backport of https://github.com/arangodb/arangodb/pull/15038
No conflicts.
> Bug fix 3.7/devsup 899

- 3rdParty/iresearch/core/index/field_data.cpp
- 3rdParty/iresearch/core/index/field_data.hpp
- 3rdParty/iresearch/core/index/segment_writer.cpp
- 3rdParty/iresearch/core/utils/directory_utils.cpp
- CHANGELOG
Includes fixes for:
https://arangodb.atlassian.net/browse/SEARCH-261
https://arangodb.atlassian.net/browse/SEARCH-260
> [3.7] Bug-fix SEARCH-261, SEARCH-260

- arangod/Replication2/ReplicatedLog/LogCommon.cpp
- arangod/Replication2/ReplicatedLog/LogCommon.h
- arangod/Replication2/ReplicatedLog/LogStatus.cpp
- arangod/Replication2/ReplicatedLog/LogStatus.h
- arangod/Replication2/ReplicatedLog/types.cpp
- arangod/Replication2/ReplicatedLog/types.h
- arangod/RestHandler/RestLogHandler.cpp
- arangod/RestServer/FileDescriptorsFeature.cpp
- tests/CMakeLists.txt
- tests/Replication2/Serialization/LogStatusTest.cpp
Writing some simple tests for serialization and deserialization of LogStatus.
> First version of LogStatus tests

- tests/js/client/shell/shell-transaction-dropped-followers-cluster.js
Backport of https://github.com/arangodb/arangodb/pull/15091
Add more test cases to dropped-followers test.
This PR only extends an already existing test, so intentionally no CHANGELOG entry added.
> added test cases

- arangod/Replication2/ReplicatedLog/Algorithms.cpp
- arangod/Replication2/ReplicatedLog/Algorithms.h
Removed some comments from code, so we keep the documentation in one place only. Some minor changes that should not affect functionality.
> tidying up

- 3rdParty/iresearch/core/formats/columnstore2.cpp
- 3rdParty/iresearch/core/formats/columnstore2.hpp
- 3rdParty/iresearch/core/index/field_data.cpp
- 3rdParty/iresearch/core/index/field_data.hpp
- 3rdParty/iresearch/core/index/segment_writer.cpp
- 3rdParty/iresearch/core/index/segment_writer.hpp
- 3rdParty/iresearch/core/utils/directory_utils.cpp
- 3rdParty/iresearch/core/utils/directory_utils.hpp
- 3rdParty/iresearch/external/absl/absl/container/internal/btree.h
- 3rdParty/iresearch/external/absl/absl/meta/type_traits.h
- 3rdParty/iresearch/external/absl/absl/types/compare.h
- 3rdParty/iresearch/external/absl/absl/types/internal/variant.h
- 3rdParty/iresearch/external/openfst/fst/memory.h
- 3rdParty/iresearch/tests/formats/columnstore2_test.cpp
- 3rdParty/iresearch/tests/index/consolidation_policy_tests.cpp
- 3rdParty/iresearch/tests/index/index_tests.cpp
- 3rdParty/iresearch/tests/index/index_tests.hpp
- 3rdParty/iresearch/tests/utils/directory_utils_tests.cpp
backport fix for https://arangodb.atlassian.net/jira/software/projects/SEARCH/boards/15?selectedIssue=SEARCH-259 from iresearch upstream
> buf-fix/arangosearch-columnstore2

- 3rdParty/iresearch/core/formats/columnstore2.cpp
- 3rdParty/iresearch/core/formats/columnstore2.hpp
- 3rdParty/iresearch/core/index/field_data.cpp
- 3rdParty/iresearch/core/index/field_data.hpp
- 3rdParty/iresearch/core/index/segment_writer.cpp
- 3rdParty/iresearch/core/index/segment_writer.hpp
- 3rdParty/iresearch/core/utils/directory_utils.cpp
- 3rdParty/iresearch/core/utils/directory_utils.hpp
- 3rdParty/iresearch/tests/formats/columnstore2_test.cpp
- 3rdParty/iresearch/tests/index/consolidation_policy_tests.cpp
- 3rdParty/iresearch/tests/index/index_tests.cpp
- 3rdParty/iresearch/tests/index/index_tests.hpp
- 3rdParty/iresearch/tests/utils/directory_utils_tests.cpp
backport fix for https://arangodb.atlassian.net/jira/software/projects/SEARCH/boards/15?selectedIssue=SEARCH-259 from iresearch upstream
> bug-fix-3.9/arangosearch-columnstore2

- arangod/Aql/Aggregator.cpp
- arangod/Aql/DistinctCollectExecutor.cpp
- arangod/Aql/DistinctCollectExecutor.h
- arangod/Aql/DocumentProducingHelper.cpp
- arangod/Aql/DocumentProducingHelper.h
- arangod/Aql/Functions.cpp
- arangod/Graph/NeighborsEnumerator.cpp
- arangod/Graph/NeighborsEnumerator.h
- lib/Containers/FlatHashSet.h
Prefer using absl::flat_hash_set<...> instead of std::unordered_set<...> where applicable. It's always faster.
https://martin.ankerl.com/2019/04/01/hashmap-benchmarks-01-overview/
> Prefer using absl::flat_hash_set

- tests/js/common/shell/shell-pregel-multicollection-edgecol.js
Contains tests from https://github.com/arangodb/arangodb/pull/15164
> add test for Pregel "parallelism" attribute

- arangod/Aql/AqlItemBlock.h
- arangod/Aql/HashedCollectExecutor.h
- lib/Containers/FlatHashMap.h
Prefer using absl::flat_hash_map<...> instead of std::unordered_map<...> where applicable. It's always faster.
https://martin.ankerl.com/2019/04/01/hashmap-benchmarks-01-overview/
> prefer using absl::flat_hash_map<...> (#15173)

- arangod/IResearch/IResearchView.cpp
IResearchView: remove duplicated code for Improving readability
> IResearchView: remove duplicated code

- tests/js/common/shell/shell-pregel-multicollection-edgecol.js
Contains tests from https://github.com/arangodb/arangodb/pull/15164
> add a new for pregel "parallelism" attribute

- arangod/Agency/Node.h
- arangod/Cluster/SynchronizeShard.cpp
- arangod/Cluster/SynchronizeShard.h
Clean up some replication code in devel, as requested during review of PR https://github.com/arangodb/arangodb/pull/15138.
> clean up some replication code

- CONTRIBUTING.md
Update list of client tools in `CONTRIBUTING.md`. The previous list was a bit outdated. Documentation only.
> update list of tools

- CMakeLists.txt
Follow up PR for #15213 to disable ICF explicitly and add a comment explaining why.
> Disable ICF explicitly.

- js/client/modules/@arangodb/air/pregel-example-graphs.js
This PR fixed the test: `tests/js/client/shell/shell-custom-pregel-timecritical.js`
which is executable via:
```
scripts/unittest shell_client --cluster true --test tests/js/client/shell/shell-custom-pregel-timecritical.js
```
- No backports needed. Devel related only.
> fixed smart graph creation for pregel smart graph example

- Documentation/DocuBlocks/Rest/Cursors/post_api_cursor.md
Docs PR: https://github.com/arangodb/docs/pull/829
Clarify the meaning of an attribute in a HTTP API, by adding one more sentence to the documentation
> clarify meaning of an API attribute

- .github/CODEOWNERS
Does not change any code, but adds an initial CODEOWNERS file to the repository. This currently mentions only 2 subdirectories, but it can be augmented later with more directories.
> [EM-1] test with CODEOWNERS file

- lib/Basics/CrashHandler.cpp
> [3.7] Feature/debugger breakin on assertion

- lib/Basics/CrashHandler.cpp
> [3.8] Feature/debugger breakin on assertion

- lib/Logger/LogContext.h
Fixes a compatibility issue when building with gcc11.
> Fix gcc11 compatibility issue.

- js/client/modules/@arangodb/process-utils.js
backport of https://github.com/arangodb/arangodb/pull/15294
> Bug fix 3.7/use procdump on force shutdown to generate dump

- tests/IResearch/IResearchLinkTest.cpp
> [Search-183] Add cleanup time test

- CHANGELOG
- arangod/Aql/ConstrainedSortExecutor.cpp
- arangod/Aql/MaterializeExecutor.cpp
- arangod/Aql/MaterializeExecutor.h
- tests/js/server/aql/aql-optimizer-rule-late-document-materialization.js
> [BTS-611] [3.7] Bugfixes in constrained sort and late materialize

- CHANGELOG
- arangod/Aql/ConstrainedSortExecutor.cpp
- arangod/Aql/MaterializeExecutor.cpp
- arangod/Aql/MaterializeExecutor.h
- tests/js/server/aql/aql-optimizer-rule-late-document-materialization.js
> [BTS-611] [3.8] Bugfixes in constrained sort and late materialize

- Documentation/DocuBlocks/Rest/Administration/get_admin_license.md
- Documentation/DocuBlocks/Rest/Administration/put_admin_license.md
- Documentation/DocuBlocks/Rest/Collections/post_api_collection.md
- utils/generateSwagger.py
the license feature documentation was missing the post body. Added hereby.
> add the missing body description

- lib/Basics/CrashHandler.cpp
> [3.9] Feature/debugger breakin on assertion 

- Documentation/DocuBlocks/Rest/Administration/get_admin_license.md
- Documentation/DocuBlocks/Rest/Administration/put_admin_license.md
- Documentation/DocuBlocks/Rest/Collections/post_api_collection.md
- utils/generateSwagger.py
backport of https://github.com/arangodb/arangodb/pull/15307
> add the missing body description (#15307)

- js/client/modules/@arangodb/testutils/process-utils.js
backport of https://github.com/arangodb/arangodb/pull/15294
> Bug fix 3.9/use procdump on force shutdown to generate dump

- .clang-format
(in-preparation for https://github.com/arangodb/arangodb/pull/15083)
> Update .clang-format style file

- utils/generateExamples.py
backport of https://github.com/arangodb/arangodb/pull/15342
> catch AQL-Errors for better error messages (#15342)

- js/common/modules/@arangodb/examples/examples.js
backport of https://github.com/arangodb/arangodb/pull/15350
> add integration for another long existing example

- arangod/CMakeLists.txt
- arangod/Replication2/ReplicatedLog/ILogInterfaces.cpp
- arangod/Replication2/ReplicatedLog/ILogInterfaces.h
- arangod/Replication2/ReplicatedLog/LogFollower.cpp
- arangod/Replication2/ReplicatedLog/LogFollower.h
- arangod/Replication2/ReplicatedLog/LogLeader.h
- arangod/Replication2/ReplicatedLog/ReplicatedLog.h
- arangod/Replication2/ReplicatedState/ReplicatedState.h
- arangod/Replication2/ReplicatedState/ReplicatedState.tpp
- arangod/Replication2/Streams/LogMultiplexer.h
- arangod/Replication2/Streams/LogMultiplexer.tpp
- arangod/VocBase/vocbase.cpp
- tests/Replication2/Mocks/AsyncFollower.cpp
- tests/Replication2/Mocks/AsyncFollower.h
- tests/Replication2/Mocks/FakeFollower.h
- tests/Replication2/Mocks/FakeReplicatedLog.h
- tests/Replication2/Mocks/PersistedLog.h
- tests/Replication2/ReplicatedLog/ConcurrencyTests.cpp
- tests/Replication2/ReplicatedLog/TestHelper.h
Added ILogLeader and ILogFollower interfaces for testing purposes. This allows us to write mocks for different components.
> [CINFRA-165] ILogLeader and ILogFollower

- arangod/CMakeLists.txt
- arangod/Replication2/ReplicatedLog/ILogInterfaces.cpp
- arangod/Replication2/ReplicatedLog/ILogInterfaces.h
- arangod/Replication2/ReplicatedLog/LogFollower.cpp
- arangod/Replication2/ReplicatedLog/LogFollower.h
- arangod/Replication2/ReplicatedLog/LogLeader.h
- arangod/Replication2/ReplicatedLog/ReplicatedLog.h
- arangod/Replication2/ReplicatedState/ReplicatedState.h
- arangod/Replication2/ReplicatedState/ReplicatedState.tpp
- arangod/Replication2/Streams/LogMultiplexer.h
- arangod/Replication2/Streams/LogMultiplexer.tpp
- arangod/VocBase/vocbase.cpp
- tests/CMakeLists.txt
- tests/Replication2/Mocks/AsyncFollower.cpp
- tests/Replication2/Mocks/AsyncFollower.h
- tests/Replication2/Mocks/AsyncLeader.cpp
- tests/Replication2/Mocks/AsyncLeader.h
- tests/Replication2/Mocks/FakeFollower.h
- tests/Replication2/Mocks/FakeReplicatedLog.h
- tests/Replication2/Mocks/PersistedLog.h
- tests/Replication2/ReplicatedLog/ConcurrencyTests.cpp
- tests/Replication2/ReplicatedLog/TestHelper.h
- tests/Replication2/Streams/MultiplexerConcurrencyTest.cpp
Adds an AsyncLeader such that promises are resolved in a different thread. This hopefully fixes the issue we saw earlier.
Ticket: https://arangodb.atlassian.net/browse/CINFRA-164
> [CINFRA-164] LogMultiplexer AsyncLeader

- arangod/IResearch/IResearchLink.cpp
We fix data race on _dataStore.meta
> Fix data race

- lib/Futures/Future.h
- lib/Futures/Utilities.h
> Fix future::thenFinal

- utils/generateExamples.js
- utils/generateExamples.py
- utils/generateSwagger.sh
backport of https://github.com/arangodb/arangodb/pull/15365
> Documentation 3.8/fix bind value errors

- utils/generateExamples.js
- utils/generateExamples.py
- utils/generateSwagger.sh
backport of https://github.com/arangodb/arangodb/pull/15365
> Documentation 3.7/fix bind value errors

- utils/generateExamples.js
- utils/generateExamples.py
- utils/generateSwagger.sh
backport of https://github.com/arangodb/arangodb/pull/15365
> Documentation 3.9/fix bind value errors

- 3rdParty/iresearch/core/utils/async_utils.cpp
https://github.com/iresearch-toolkit/iresearch/pull/330
> Fix possible deadlock in iresearch thread pool

- 3rdParty/iresearch/core/utils/async_utils.cpp
> Fix possible deadlock in iresearch thread pool 3.8

- 3rdParty/iresearch/core/utils/async_utils.cpp
> Fix possible deadlock in iresearch thread pool 3.9

- 3rdParty/iresearch/core/utils/async_utils.cpp
> Fix possible deadlock in iresearch thread pool 3.7

- Documentation/DocuBlocks/Rest/Administration/get_admin_server_mode.md
- Documentation/DocuBlocks/Rest/Administration/get_admin_server_tls.md
- Corrected documentation for admin server to reflect that the end point is protected.
changes not needed before 3.7
> ES-1006 Documentation/fix admin server tls documentation 3.7

- Documentation/DocuBlocks/Rest/Administration/get_admin_server_mode.md
- Documentation/DocuBlocks/Rest/Administration/get_admin_server_tls.md
-Corrected documentation for admin server to reflect that the end point is protected.
> ES-1006 Correcting documentation for server admin

- CHANGELOG
- arangod/IResearch/IResearchLink.cpp
> [3.7] add a limit (#15367)

- CHANGELOG
- arangod/IResearch/IResearchLink.cpp
> [3.8] add a limit (#15367)

- CHANGELOG
- arangod/IResearch/IResearchLink.cpp
Backport of https://github.com/arangodb/arangodb/pull/15367
> [3.9] add a limit (#15367)

- arangod/RestServer/UpgradeFeature.cpp
- js/client/modules/@arangodb/testsuites/server_permissions.js
- tests/js/client/server_parameters/database-password-noncluster.js
Backport of https://github.com/arangodb/arangodb/pull/15286
Don't complain about missing user when starting in initialization mode.
> don't complain about missing root user on initialization

- CHANGELOG
- arangosh/Import/ImportHelper.cpp
- arangosh/Import/ImportHelper.h
- js/client/modules/@arangodb/testsuites/importing.js
- js/client/modules/@arangodb/testutils/process-utils.js
- tests/js/common/test-data/import/import-data-with-header.csv
- tests/js/server/import/import-setup.js
- tests/js/server/import/import-teardown.js
- tests/js/server/import/import.js
Backport for https://github.com/arangodb/arangodb/pull/15395;
3.8 backport for https://github.com/arangodb/arangodb/pull/15395.
- x ] Added new **integration tests** (e.g. in shell_server / shell_server_aql)
> Bugfix 3.8/presupp 439

- arangod/Cluster/UpdateReplicatedLogAction.cpp
- arangod/Replication2/ReplicatedLog/Algorithms.cpp
- arangod/Replication2/ReplicatedLog/Algorithms.h
- arangod/Replication2/ReplicatedLog/LogLeader.cpp
- arangod/Replication2/ReplicatedLog/LogLeader.h
- lib/Basics/ResultT.h
Speed up the maintenance by making databases dirty after an async operation on the replicated log completed.
> [CINFRA-193] Speed up Maintenance

- CHANGELOG
- arangod/Aql/ExecutionEngine.cpp
- arangod/Aql/ExecutionNode.cpp
- arangod/Aql/ExecutionNode.h
- arangod/Aql/IResearchViewOptimizerRules.cpp
- arangod/Aql/IndexNodeOptimizerRules.cpp
- arangod/Aql/MaterializeExecutor.cpp
- arangod/Aql/OptimizerRule.h
- arangod/Aql/OptimizerRules.cpp
- tests/js/client/shell/shell-aql-regression-cluster.js
- tests/js/server/aql/aql-optimizer-rule-late-document-materialization-arangosearch.inc
- tests/js/server/aql/aql-optimizer-rule-late-document-materialization.js
- tests/js/server/aql/aql-queries-optimizer-limit-cluster.js
Backport of https://github.com/arangodb/arangodb/pull/15401
> [3.9] BTS-693 fix for limit with materializer

- CHANGELOG
- arangod/Aql/ExecutionEngine.cpp
- arangod/Aql/ExecutionNode.cpp
- arangod/Aql/ExecutionNode.h
- arangod/Aql/IResearchViewOptimizerRules.cpp
- arangod/Aql/IndexNodeOptimizerRules.cpp
- arangod/Aql/MaterializeExecutor.cpp
- arangod/Aql/OptimizerRule.h
- arangod/Aql/OptimizerRules.cpp
- tests/js/client/shell/shell-aql-regression-cluster.js
- tests/js/server/aql/aql-optimizer-rule-late-document-materialization-arangosearch.inc
- tests/js/server/aql/aql-optimizer-rule-late-document-materialization.js
- tests/js/server/aql/aql-queries-optimizer-limit-cluster.js
> [3.8] BTS-693 fix for limit with materializer 

- .github/workflows/clang-format.yml
Addresses false-negatives of [this nature](https://github.com/arangodb/arangodb/runs/4659813949?check_suite_focus=true)
> [devel] patch clang-format sha value

- .github/workflows/clang-format.yml
Addresses false-negatives of [this nature](https://github.com/arangodb/arangodb/runs/4659813949?check_suite_focus=true)
> [3.9] patch clang-format sha value

- CHANGELOG
- arangod/Aql/ExecutionEngine.cpp
- arangod/Aql/ExecutionNode.cpp
- arangod/Aql/ExecutionNode.h
- arangod/Aql/IResearchViewOptimizerRules.cpp
- arangod/Aql/IndexNodeOptimizerRules.cpp
- arangod/Aql/MaterializeExecutor.cpp
- arangod/Aql/OptimizerRule.h
- arangod/Aql/OptimizerRules.cpp
- tests/js/client/shell/shell-aql-regression-cluster.js
- tests/js/server/aql/aql-optimizer-rule-late-document-materialization-arangosearch.inc
- tests/js/server/aql/aql-optimizer-rule-late-document-materialization.js
- tests/js/server/aql/aql-queries-optimizer-limit-cluster.js
> [3.7] BTS-693 fix for limit with materializer

- cmake/RocksDBConfig.cmake.in
> Delete obsolete symlink

- UnitTests/OskarTestSuitesBlockList
> Disable replcation2 server test.

- UnitTests/OskarTestSuitesBlockList
> Disable replication2 server test.

- tests/Aql/DecaysFunctionTest.cpp
- tests/js/server/aql/aql-functions-numeric.js
Add more tests for the DECAY_* functions.
> [BTS-705] Add more decay tests

- arangod/Replication2/ReplicatedLog/LogLeader.cpp
- arangod/Replication2/ReplicatedLog/LogLeader.h
- arangod/Replication2/ReplicatedState/FollowerStateManager.tpp
- arangod/Replication2/ReplicatedState/LeaderStateManager.tpp
- tests/Replication2/ReplicatedState/LeaderRecoveryTest.cpp
This PR fixes memory leaks in the replication2 unit tests.
> [CINFRA-214] Fixing memory leaks in replication2 tests.

- CHANGELOG
- arangod/Aql/OptimizerRules.cpp
- tests/js/server/aql/aql-optimizer-rule-remove-collect-variables.js
Fix for issue https://github.com/arangodb/arangodb/issues/15476.
> Fixed issue #14576: FATAL {crash} occurs on a simple query.

- tests/Aql/DecaysFunctionTest.cpp
- tests/js/server/aql/aql-functions-numeric.js
Add more tests for the DECAY_* functions.
> [3.9] [BTS-705] Add more decay tests

- arangod/RocksDBEngine/RocksDBMetadata.cpp
- arangod/RocksDBEngine/RocksDBMetadata.h
- arangod/RocksDBEngine/RocksDBReplicationContext.cpp
- arangosh/Benchmark/BenchmarkThread.h
- tsan_arangodb_suppressions.txt
https://github.com/arangodb/arangodb/pull/15504
> Fix data race 3.9

- .githooks/pre-commit-linux
- .githooks/pre-commit-macos
- .githooks/pre-commit-windows
- .github/workflows/clang-format.yml
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/851
Changes for clang-format:
* exclude 3rdParty from formatting
* include .ipp and .tpp files in formatting
* set explicit timeout for github action
> clang-format adjustments

- js/apps/system/_admin/aardvark/APP/frontend/js/views/navigationView.js
- js/apps/system/_admin/aardvark/APP/frontend/js/views/notificationView.js
Remove stray `console.log()` calls in web UI code.
> remove stray console.log calls

- CHANGELOG
- arangod/Scheduler/SchedulerFeature.cpp
- arangosh/Backup/arangobackup.cpp
- arangosh/Benchmark/arangobench.cpp
- arangosh/Dump/arangodump.cpp
- arangosh/Export/arangoexport.cpp
- arangosh/Import/arangoimport.cpp
- arangosh/Restore/arangorestore.cpp
- arangosh/Shell/arangosh.cpp
- arangosh/VPack/arangovpack.cpp
- lib/Basics/signals.cpp
- lib/Basics/signals.h
backport of https://github.com/arangodb/arangodb/pull/15445
> Bug fix 3.9/fix exit code

- ISSUE_TEMPLATE.md
- PULL_REQUEST_TEMPLATE.md
This PR simplifies the PULL_REQUEST_TEMPLATE.md in several ways, making it slightly easier to fill out.
The documentation section has been removed, because it was never filled out. The CLA section was removed because there is now the CLA bot. The testing section has been streamlined.
The PR is meant as a basis for discussion with other developers.
No backports yet.
> simplify PR template a bit

- CHANGELOG
*change log license feature grace period upgrade / initial install*
> license grace period

- arangod/Pregel/Algos/AIR/Accumulators.cpp
- lib/Containers/MerkleTree.cpp
- lib/Rest/Version.cpp
- lib/VPackDeserializer/deserialize-with.h
- lib/VPackDeserializer/validate.h
> Address cpp-check issues

- lib/Basics/debugging.h
> Address cppcheck issues

- arangod/Pregel/Algos/AIR/Accumulators.cpp
- lib/Containers/MerkleTree.cpp
- lib/Rest/Version.cpp
- lib/VPackDeserializer/deserialize-with.h
- lib/VPackDeserializer/validate.h
> Address cpp-check issues (#15541)

- 3rdParty/V8/gyp/common.py
- 3rdParty/V8/gyp/msvs_emulation.py
- 3rdParty/V8/gypfiles/standalone.gypi
- 3rdParty/V8/v7.9.317/third_party/jinja2/tests.py
- CMakeLists.txt
backport of https://github.com/arangodb/arangodb/pull/15502 and https://github.com/arangodb/arangodb/pull/15552
> Fixed python imports to work with 3.10 (#15502)

- 3rdParty/V8/gyp/common.py
- 3rdParty/V8/gyp/msvs_emulation.py
- 3rdParty/V8/gypfiles/standalone.gypi
- 3rdParty/V8/v7.9.317/third_party/jinja2/tests.py
- CMakeLists.txt
- lib/Basics/debugging.h
> Bug fix 3.9/cppcheck issues 2

- CHANGELOG
Add the CHANGELOG entry that reflects that boost was upgraded in #15503 
> Add CHANGELOG for boost 1.78.0 upgrade

- arangod/Aql/IResearchViewNode.cpp
- arangod/IResearch/Containers.h
- arangod/IResearch/IResearchLink.cpp
- arangod/IResearch/IResearchLink.h
- arangod/IResearch/IResearchLinkHelper.cpp
- arangod/IResearch/IResearchView.cpp
- arangod/IResearch/IResearchView.h
- arangod/IResearch/IResearchViewCoordinator.cpp
- arangod/IResearch/IResearchViewCoordinator.h
- arangod/IResearch/IResearchViewMeta.cpp
- arangod/IResearch/IResearchViewMeta.h
- tests/IResearch/ContainersTest.cpp
- tests/IResearch/IResearchFeatureTest.cpp
- tests/IResearch/IResearchViewDBServerTest.cpp
- tests/IResearch/IResearchViewTest.cpp
BTS-735, BTS-736 and other tsan issues fix
> BTS-735, BTS-736 and other tsan issues fix

- arangod/V8Server/v8-analyzers.cpp
- arangod/V8Server/v8-collection-util.cpp
- arangod/V8Server/v8-views.cpp
- lib/V8/v8-globals.cpp
Add debug logging to find out what goes wrong with V8-weak wrapping on the wintendo.
> BTS-713: Bug fix/debug weak wrappers

- Documentation/DocuBlocks/Rest/Administration/delete_api_shutdown.md
> BTS-758 | Documentation-3.7/soft-coordinator-shutdown-fix

- Documentation/DocuBlocks/Rest/Administration/delete_api_shutdown.md
> BTS-758 | Documentation-3.8/soft-coordinator-shutdown-fix

- Documentation/DocuBlocks/Rest/Administration/delete_api_shutdown.md
> BTS-758 | Documentation-3.9/soft-coordinator-shutdown-fix

- tests/IResearch/IResearchFeature-test.cpp
Backport of https://github.com/arangodb/arangodb/pull/15603
> [3.9] BTS-501

- arangod/Aql/IResearchViewNode.cpp
- arangod/IResearch/Containers.h
- arangod/IResearch/IResearchCommon.h
- arangod/IResearch/IResearchLink.cpp
- arangod/IResearch/IResearchLink.h
- arangod/IResearch/IResearchLinkHelper.cpp
- arangod/IResearch/IResearchView.cpp
- arangod/IResearch/IResearchView.h
- arangod/IResearch/IResearchViewCoordinator.cpp
- arangod/IResearch/IResearchViewCoordinator.h
- arangod/IResearch/IResearchViewMeta.cpp
- arangod/IResearch/IResearchViewMeta.h
- tests/IResearch/Containers-test.cpp
- tests/IResearch/IResearchFeature-test.cpp
- tests/IResearch/IResearchQueryNoMaterialization-test.cpp
- tests/IResearch/IResearchView-test.cpp
- tests/IResearch/IResearchViewDBServer-test.cpp
https://github.com/arangodb/enterprise/pull/867
> BTS-735, BTS-736 3.9

- CHANGELOG
- arangod/Aql/EngineInfoContainerDBServerServerBased.cpp
- arangod/Aql/EngineInfoContainerDBServerServerBased.h
- arangod/Aql/GraphNode.cpp
- arangod/Aql/GraphNode.h
- arangod/Aql/Query.cpp
- arangod/Aql/Query.h
Backport of: https://github.com/arangodb/arangodb/pull/15604
There is also an EE companion.
> Backport Bug fix 3.9/bts 729

- CHANGELOG
- js/client/modules/@arangodb/testutils/collect-crud-api-generic-tests.js
- js/common/modules/@arangodb/testutils/collection-wrapper-util.js
- js/server/modules/@arangodb/testutils/collection-modification-aql-generic-tests.js
- tests/js/client/shell/shell-document.js
Backport of devel pr (already got merged):
- https://github.com/arangodb/arangodb/pull/15591
Please see detailed description there. 
There will be also an EE PR as well.
> Backport 3.9 BTS-740

- Documentation/DocuBlocks/Rest/Administration/get_admin_log.md
This is the linking for documentation for https://github.com/arangodb/docs/pull/883 and https://github.com/arangodb/arangodb/pull/15493
> Updated documentation

- CONTRIBUTING.md
- js/client/modules/@arangodb/testsuites/rta_makedata.js
- js/client/modules/@arangodb/testutils/process-utils.js
RTA has a set of javascript tests that check the integrity of certain structures.
> add testsuite to invoke the makedata suite from the RTA

- lib/Logger/LogContext.h
Fixes a potential memory leak and some data races.
> Fix sanitizer issues in LogContext

- tests/IResearch/ContainersTest.cpp
> Fix unstable Containers test

- tests/IResearch/IResearchFeature-test.cpp
Backport of https://github.com/arangodb/arangodb/pull/15603
> [3.8] BTS-501

- arangod/Cluster/ClusterFeature.cpp
Gracefully shutdown heartbeat thread for single server.
> Shutdown heartbeat thread properly

- CHANGELOG
- arangod/Aql/WindowNode.cpp
- tests/js/server/aql/aql-window-malarkey.js
Fix null pointer access when using WINDOW operation with a COUNT/LENGTH aggregate function without any arguments.
> Fix nullptr access with WINDOW operation.

- arangod/Cluster/ClusterFeature.cpp
Gracefully shutdown heartbeat thread for single server
> [3.8] Gracefully shutdown heartbeat thread for single server

- lib/ApplicationFeatures/ApplicationServer.h
Add some comments on how to use ApplicationServerT
> Add comments on how to use ApplicationServerT

- arangod/Cluster/ClusterFeature.cpp
Gracefully shutdown heartbeat thread for single server.
> [3.9] Gracefully shutdown heartbeat thread for single server.

- Documentation/DocuBlocks/Rest/Collections/put_api_collection_compact.md
Backport of #15680
Verification run: https://jenkins.arangodb.biz:3456/view/Documentation/job/arangodb-ANY-examples/1634/
> BTS-766 | Docs: Add DocuBlock for PUT /_api/collection/<coll>/compact

- CHANGELOG
Adds zkd index lookahead flag to changelog.
> Added changelog entry for zkd index lookahead.

- CHANGELOG
- js/node/node_modules/.package-lock.json
- js/node/node_modules/i/LICENSE
- js/node/node_modules/i/README.md
- js/node/node_modules/i/lib/defaults.js
- js/node/node_modules/i/lib/inflect.js
- js/node/node_modules/i/lib/inflections.js
- js/node/node_modules/i/lib/methods.js
- js/node/node_modules/i/lib/native.js
- js/node/node_modules/i/lib/util.js
- js/node/node_modules/i/package.json
- js/node/package-lock.json
- js/node/package.json
Backport of #15732 for 3.8. Updates `i` to the latest bugfix release.
> [3.8] i@0.3.7

- arangod/Cluster/ClusterInfo.cpp
- arangod/Cluster/ClusterInfo.h
Micro optimization for ClusterInfo. Trivial change, but performance effect will be unnoticable.
This is a trivial internal code change, so there are no docs and no changelog entry. No backports are planned.
> micro optimization for ClusterInfo

- 3rdParty/iresearch/external/text/include/boost/stl_interfaces/config.hpp
- 3rdParty/iresearch/external/text/include/boost/stl_interfaces/fwd.hpp
- 3rdParty/iresearch/external/text/include/boost/stl_interfaces/view_interface.hpp
> Fix clang-12 compilation

- arangod/Replication2/ReplicatedState/Supervision.cpp
- arangod/Replication2/ReplicatedState/SupervisionAction.cpp
- arangod/StorageEngine/HotBackupCommon.h
- lib/VPackDeserializer/enum.h
- lib/VPackDeserializer/values.h
- tests/Greenspun/PrimitivesTest.cpp
- tests/Pregel/typedbuffer.cpp
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/896
Fix code formatting violations in devel. This is a trivial PR.
> fix formatting violations in devel

- .github/workflows/clang-format.yml
- arangod/VocBase/LogicalDataSource.cpp
- arangod/VocBase/vocbase.cpp
Improve linting action.
Relies on https://github.com/arangodb/clang-format-action/pull/2 to be merged and tagged as version 1.0.3.
> improve clang-format

- .github/workflows/clang-format.yml
- arangod/VocBase/vocbase.cpp
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/900
Activate and modernize central clang-format lint check on Github for 3.9 commits
This PR updates 3.9 to the same state of linting that is in devel.
> update formatting hook

- arangod/Cluster/ClusterMethods.cpp
> Fix: BTS-806

- arangod/Cluster/ClusterInfo.cpp
- arangod/Cluster/ClusterInfo.h
- arangod/Cluster/DBServerAgencySync.cpp
- arangod/Cluster/HeartbeatThread.cpp
- arangod/Cluster/Maintenance.cpp
- arangod/Cluster/Maintenance.h
- arangod/Cluster/MaintenanceFeature.cpp
- arangod/Cluster/MaintenanceFeature.h
- arangod/Network/Methods.cpp
- arangod/Pregel/Recovery.cpp
- arangod/Pregel/Recovery.h
- arangod/StorageEngine/TransactionState.h
- arangod/Transaction/ClusterUtils.cpp
Fix incorrect abort transaction
And some small refactoring
> Fix incorrect abort transaction and some refactoring

- arangod/Transaction/ClusterUtils.cpp
https://github.com/arangodb/arangodb/pull/15820
Fix abort transaction on failed coordinators
> Fix abort transaction on failed coordinators

- CHANGELOG
Update CHANGELOG for update snowball
> Update CHANGELOG for update snowball

- arangod/Agency/AgencyPaths.h
- arangod/Agency/Supervision.cpp
- arangod/Replication2/ReplicatedState/Supervision.cpp
- arangod/Replication2/ReplicatedState/Supervision.h
- arangod/Replication2/ReplicatedState/SupervisionAction.cpp
- arangod/Replication2/ReplicatedState/SupervisionAction.h
This PR refactors the Replicated State Supervision Actions. A similar PR is available for the replicated log part. The initial design turned out to not be optimal.
> [CINFRA-272] Refactor Supervision Action Replicated State

- arangod/Replication2/ReplicatedState/FollowerStateManager.h
- arangod/Replication2/ReplicatedState/FollowerStateManager.tpp
This PR optimizes the locking in the `FollowerStateManager`, in particular in the performance critical poll-apply-loop. This is all covered by existing tests. It also includes some code cleanup.
> [CINFRA-270] Optimized locking calls in FollowerStateManager.

- arangod/IResearch/IResearchDataStore.h
- arangod/IResearch/IResearchInvertedIndex.h
- tests/IResearch/IResearchInvertedIndexIteratorTest.cpp
- tests/IResearch/IResearchViewDBServerTest.cpp
- tests/IResearch/IResearchViewTest.cpp
Fix typo and add more asserts to test
> Fix typo and add more asserts to test

- Documentation/DocuBlocks/Rest/Cursors/post_api_cursor_identifier.md
- Documentation/DocuBlocks/Rest/Cursors/put_api_cursor_identifier.md
Backport of https://github.com/arangodb/arangodb/pull/15752
> BTS-668 | List code, error, errorNum, errorMessage, and extra attributes for subsequent cursor batches

- Documentation/DocuBlocks/Rest/Collections/post_api_collection.md
> Docs: POST /_api/collection code uses boolean for enforceReplicationFactor and waitForSyncReplication

- Documentation/DocuBlocks/Rest/Administration/get_admin_modules_flush.md
> Docs: Add log topic libiresearch

- js/client/modules/@arangodb/test-utils.js
backport of https://github.com/arangodb/arangodb/pull/15847
> Bug fix 3.7/improve rspec error handling on windows

- Documentation/DocuBlocks/Rest/Administration/get_admin_log.md
> Docs: Add log topic libiresearch. Remove compactor, datafiles

- Documentation/DocuBlocks/Rest/Administration/get_admin_log.md
> Docs: Add log topics all (pseudo), license, libiresearch. Remove compactor, datafiles

- js/client/modules/@arangodb/testutils/test-utils.js
backport of https://github.com/arangodb/arangodb/pull/15847
> Bug fix 3.8/improve rspec error handling on windows

- js/client/modules/@arangodb/testutils/test-utils.js
backport of https://github.com/arangodb/arangodb/pull/15847
> Bug fix 3.9/improve rspec error handling on windows

- arangod/RocksDBEngine/ReplicatedRocksDBTransactionCollection.cpp
- lib/Basics/FeatureFlags.cpp
This mainly causes some additional tests to run. It is not fully functional.
> [CINFRA-215] Enable FeatureFlag Replication2

- tests/Replication2/ReplicatedLog/SupervisionTest.cpp
> [CINFRA-whatever] Fix some warnings in SupervisionTest.cpp

- arangod/Replication2/ReplicatedLog/Supervision.cpp
Add some (hopefully useful) comments to `Supervision.cpp`
> [CINFRA-301] Some comments on Supervision.cpp

- CHANGELOG
Update for changelog after merging this PR: https://github.com/arangodb/arangodb/pull/15817
> Update for changelog

- arangod/IResearch/IResearchLinkCoordinator.cpp
- arangod/Metrics/ClusterMetricsFeature.cpp
- arangod/Metrics/ClusterMetricsFeature.h
> Fix possible livelock

- arangod/Transaction/Helpers.cpp
- arangod/Transaction/Helpers.h
- arangod/VocBase/Validators.h
A trivial PR that only updates comments and deletes an unnecessary semicolon.
> updated comments

- arangod/GeneralServer/AuthenticationFeature.cpp
See https://github.com/arangodb/docs/pull/936
> BTS-820 | Clarify effect of `--server.session-timeout`

- lib/Containers/FlatHashMap.h
- lib/Containers/FlatHashSet.h
- lib/Containers/NodeHashMap.h
- lib/Containers/NodeHashSet.h
* Don't use internal stuff in our using 
* Checkout IResearch to master
> Some fixes for abseil dependency

- tests/IResearch/IResearchFeature-test.cpp
Fix desired threads number detection in test
> [3.7] fix unstable test

- arangod/Aql/AqlCall.h
- arangod/Aql/OutputAqlItemRow.cpp
- arangod/Aql/OutputAqlItemRow.h
Add noexcept declarations to frequently called AQL functions.
There are no intentions to backport these changes.
> add noexcept declarations to frequently called AQL functions

- arangod/WasmServer/WasmModuleCollection.cpp
- tests/js/client/shell/shell-wasm.js
I thought I changed this already, apparently not.
> Use shard name for collection on DB server

- Documentation/DocuBlocks/Rest/Transactions/post_api_transaction.md
- Documentation/DocuBlocks/Rest/Transactions/post_api_transaction_begin.md
> Docs: Add unit to lockTimeout (seconds)

- scripts/clang-format.ps1
> clang-format: Pass through arguments from PowerShell wrapper to .sh script

- lib/ApplicationFeatures/LanguageFeature.cpp
Backport of #16039
Follow-up PR to https://github.com/arangodb/arangodb/pull/15912
Docs PR: https://github.com/arangodb/docs/pull/946
> Docs: Deprecate --default-language and set version for --icu-language

- lib/V8/v8-deadline.cpp
- lib/V8/v8-deadline.h
- lib/V8/v8-no-deadline.cpp
- lib/V8/v8-utils.cpp
addendum to https://github.com/arangodb/arangodb/pull/15979 : also make process control respect the deadlines.
> BTS-824: adjust deadline for forked processes timeouts

- arangod/Network/Utils.cpp
> Remove unused variables

- arangod/Replication2/ReplicatedLog/Supervision.cpp
- arangod/Replication2/ReplicatedLog/Supervision.h
- arangod/Replication2/ReplicatedLog/SupervisionAction.h
Report all planned participants in election outcome, even if they have not written to current yet.
> [CINFRA-202] Report all planned participants in election outcome

- arangod/Replication2/ReplicatedState/Supervision.cpp
- arangod/Replication2/ReplicatedState/SupervisionAction.h
- tests/js/server/replication2/replication2-supervision-replicated-state-target-cluster.js
Fix for replicated state supervision. Do not remove servers as  long as other servers don't have the snapshot.
> [CINFRA-353] Fix for Replicated State Supervision

- arangod/Replication2/ReplicatedState/UpdateReplicatedState.cpp
See https://github.com/arangodb/arangodb/pull/16045#discussion_r840400099
> [CINFRA-340] Remove dead code

- lib/Basics/Common.h
Simplify some common macros for Windows. 
Potentially we can rid of a few `#undef` commands by now. Jenkins compilation on Windows will tell...
No backports are needed for this PR.
> simplify macros for Windows

- lib/Inspection/Status.h
- lib/Inspection/VPack.h
- lib/Inspection/VPackLoadInspector.h
- lib/Inspection/VPackSaveInspector.h
- lib/Inspection/detail/traits.h
- tests/Basics/InspectionTest.cpp
> Type Inspection: add support for unsafe types.

- tests/Replication2/ReplicatedState/PrototypeConcurrencyTest.cpp
Using AsyncMockLog to break stack overflow. Enable test again.
> [CINFRA-315] Prototype Concurrency Test Fix

- arangod/Aql/QueryList.cpp
https://github.com/arangodb/arangodb/pull/16111
> Make comments clearer

- tests/Replication2/ModelChecker/ModelChecker.h
- tests/Replication2/ModelChecker/Predicates.h
Fixing code to compile with apple clang.
> [CINFRA] Bug Fix for mac compilation

- js/client/modules/@arangodb/testsuites/importing.js
backport of https://github.com/arangodb/arangodb/pull/16170
> fix assertion handling to produce actual error states

- arangod/RocksDBEngine/RocksDBChecksumEnv.cpp
Improve error reporting in case deletion of checksum file goes wrong.
> improve error handling for checksum files

- Documentation/DocuBlocks/Rest/Administration/put_admin_license.md
Backport of https://github.com/arangodb/arangodb/pull/16177
> Use 201 status code for put license

- UnitTests/OskarTestSuitesBlockList
- js/client/modules/@arangodb/testsuites/replication.js
- tests/js/common/replication_api/shell-api-replication-global.js
- tests/js/common/replication_api/shell-api-replication.js
backport of https://github.com/arangodb/arangodb/pull/16189
> add testsuite missing in backport

- arangod/RocksDBEngine/RocksDBCuckooIndexEstimator.cpp
- arangod/RocksDBEngine/RocksDBCuckooIndexEstimator.h
- tests/RocksDBEngine/IndexEstimatorTest.cpp
Add batch operations support for cuckoo index estimator.
This is a potential performance optimization to reduce the amount of time used for locking/unlocking the cuckoo index estimator internals.
> add support for batch operations on cuckoo index estimator

- scripts/startLocalCluster.sh
Remove obsolete STORAGE_ENGINE variable from script.
> remove obsolete STORAGE_ENGINE variable

- arangod/Replication2/StateMachines/Prototype/PrototypeCore.cpp
- arangod/Replication2/StateMachines/Prototype/PrototypeCore.h
- arangod/Replication2/StateMachines/Prototype/PrototypeLeaderState.cpp
- arangod/Replication2/StateMachines/Prototype/PrototypeLeaderState.h
- arangod/Replication2/StateMachines/Prototype/PrototypeLogEntry.cpp
- arangod/Replication2/StateMachines/Prototype/PrototypeLogEntry.h
- arangod/Replication2/StateMachines/Prototype/PrototypeStateMethods.cpp
- arangod/Replication2/StateMachines/Prototype/PrototypeStateMethods.h
- arangod/Replication2/Streams/LogMultiplexer.tpp
- arangod/Replication2/Streams/Streams.h
- arangod/Replication2/Streams/Streams.tpp
- arangod/RestHandler/RestPrototypeStateHandler.cpp
- arangod/RestHandler/RestPrototypeStateHandler.h
- tests/Replication2/ReplicatedState/PrototypeStateMachineTest.cpp
- tests/js/server/replication2/replication2-prototype-replicated-state-cluster.js
This PR implements compare exchange operation on the prototype.
> [CINFRA-375] Prototype Compare Exchange

- arangod/Aql/IResearchViewNode.cpp
- arangod/Aql/IResearchViewNode.h
- arangod/Aql/QuerySnippet.cpp
- arangod/IResearch/IResearchView.cpp
- arangod/IResearch/ViewSnapshot.cpp
- arangod/IResearch/ViewSnapshot.h
- tests/IResearch/IResearchQueryGeoContainsTest.cpp
- tests/IResearch/IResearchQueryGeoDistanceTest.cpp
- tests/IResearch/IResearchQueryGeoInRangeTest.cpp
- tests/IResearch/IResearchQueryGeoIntersectsTest.cpp
- tests/IResearch/IResearchQueryInRangeTest.cpp
- tests/IResearch/IResearchViewCountApproximateTest.cpp
- tests/IResearch/IResearchViewDBServerTest.cpp
- tests/IResearch/IResearchViewNodeTest.cpp
- tests/IResearch/IResearchViewSortedTest.cpp
- tests/IResearch/IResearchViewTest.cpp
- tests/IResearch/MakeViewSnapshot.h
> Remove assert(false) and make code better

- CHANGELOG
- arangod/IResearch/IResearchKludge.cpp
- arangod/IResearch/IResearchLink.cpp
- arangod/IResearch/IResearchRocksDBRecoveryHelper.cpp
- arangod/RocksDBEngine/Methods/RocksDBTrxBaseMethods.cpp
- arangod/RocksDBEngine/RocksDBCollection.cpp
- tests/js/server/recovery/view-arangosearch-link-populate-drop-view-no-flushthread.js
Backport of https://github.com/arangodb/arangodb/pull/16224
> [3.8] BTS-860 ignore link create on recovery

- js/server/modules/@arangodb/testutils/replicated-logs-helper.js
- js/server/modules/@arangodb/testutils/replicated-logs-http-helper.js
- js/server/modules/@arangodb/testutils/replicated-logs-predicates.js
- tests/js/server/replication2/replication2-maintenance-replicated-log-cluster.js
- tests/js/server/replication2/replication2-replicated-log-http-api-cluster.js
This PR adds tests that assert, that database servers drop a replicated log, once it is dropped from Plan.
There will be a follower up PR that handles dropping a replicated log from Plan, once it is dropped from target.
> [CINFRA-374] Delete Replicated log

- CHANGELOG
- arangod/Aql/OptimizerRules.cpp
- tests/js/server/aql/aql-optimizer-rule-interchange-adjacent-enumerations-cluster.js
- tests/js/server/aql/aql-optimizer-rule-interchange-adjacent-enumerations-noncluster.js
Backport of https://github.com/arangodb/arangodb/pull/16283
Fixed Github issue #16279: assertion failure/crash in AQL query optimizer when permuting adjacent FOR loops that depended on each other.
> fixed issue #16279

- Documentation/DocuBlocks/Rest/Pregel/get_api_control_pregel_overview.md
- Documentation/DocuBlocks/Rest/Pregel/get_api_control_pregel_status.md
Docs PR: https://github.com/arangodb/docs/pull/992
Add documentation for Pregel API that lists currently ongoing jobs.
> add documentation for Pregel jobs API

- CHANGELOG
- arangod/IResearch/Geo.cpp
*Fixes verbose logging of 100+GB of logs in big import*
> [3.8] fix verbose geojson parsing

- js/client/modules/@arangodb/testsuites/gtest.js
added gtest_replication2 to the test suites
> Feature/replication 2.0 unittests

- CHANGELOG
- Documentation/DocuBlocks/Rest/Collections/post_api_collection.md
- Documentation/DocuBlocks/Rest/Collections/put_api_collection_properties.md
*fix default collection property cache enabled*
> [3.8] fix default collection property cache enabled

- CHANGELOG
- Documentation/DocuBlocks/Rest/Collections/post_api_collection.md
- Documentation/DocuBlocks/Rest/Collections/put_api_collection_properties.md
*fix default collection property cache enabled*
> [3.9] fix default collection property cache enabled

- tests/Definition/rlog/pr.fish
This PR adds the minimal test definitions for RLOG PR. It will require changes to Oskar. 
> added rlog test definition

- js/server/modules/@arangodb/testutils/replicated-logs-helper.js
- tests/js/server/replication2/replication2-supervision-replicated-log-target-cluster.js
This PR adds tests that have been written a while ago and then have been forgotten.
> [CINFRA] Adding old tests

- arangod/Replication2/ReplicatedLog/LogStatus.cpp
- arangod/Replication2/ReplicatedLog/LogStatus.h
Attempt to work around GCCs maybe-uninitialized errors.
> [CINFRA] Try to fix maybe uninitialized error.

- tests/Replication2/ReplicatedLog/SupervisionTest.cpp
There was a bug in the supervision, that would pick a server from current, without checking if it is still in plan. This was fixed. This PR adds a test for that.
> [CINFRA-355] Only consider participants in Plan

- arangod/Replication2/ReplicatedLog/Supervision.cpp
- arangod/Replication2/ReplicatedLog/SupervisionAction.cpp
- js/client/modules/@arangodb/testsuites/replication2.js
Tihs PR reduces the spam created by the log supervision in the agency log. It implements a similar mechanism compared to what the replicated state supervision does.
> [CINFRA] Log Supervision Spam Reduction

- arangod/Replication2/ReplicatedLog/InMemoryLog.cpp
This PR adds more information to an assertion that triggered during on of the PR runs. Hopefully with more information we can find its cause. While touching the file, I added more production asserts and more information to most of them.
> [CINFRA-388] InMemoryLog assertions

- js/client/modules/@arangodb/testsuites/wal.js
https://github.com/arangodb/arangodb/pull/15998 introduced a main overhaul of the test framework, This file was overlooked since its not run by the ci yet.
> adjust testsuite to new invocation mechanisms

- arangod/Replication2/ReplicatedLog/Supervision.cpp
- arangod/Replication2/ReplicatedLog/SupervisionContext.h
- tests/js/server/replication2/replication2-supervision-replicated-log-target-cluster.js
- tests/js/server/replication2/replication2-supervision-replicated-state-cluster.js
Fixed some tests that depended on a specific timing or a specific order in which things happen. However, the supervision is free to take other paths that are valid. And the test should accept those as well.
> [CINFRA-411] Mac Test Issues

- arangod/Agency/CleanOutServer.cpp
- arangod/Agency/FailedServer.cpp
- arangod/Agency/Helpers.cpp
- arangod/Agency/Helpers.h
- arangod/Agency/ResignLeadership.cpp
- arangod/Agency/Supervision.cpp
- arangod/CMakeLists.txt
- tests/Agency/CleanOutServerTest.cpp
- tests/Agency/CleanOutServerTest.json
- tests/Agency/SupervisionTest.cpp
> [CINFRA-412] Disable some supervision jobs for replication 2 DBs

- arangod/RocksDBEngine/RocksDBPersistedLog.cpp
RocksDB benefits from sorted write batches. currently we collect all log iterators and then write each of them into the write batch. A log iterator guarantees that its entries are in ascending order. But the log ids might not be ascending. Sort the vector if iterators first by logid.
> [CINFRA-25] Sorted write batches for RocksDB

- tests/sepp/RocksDBOptions.cpp
- tests/sepp/RocksDBOptions.h
SEPPify the `compressionType` startup option
> seppify compressionType attribute

- js/server/modules/@arangodb/testutils/collection-modification-aql-generic-tests.js
This PR removes a deletion that was requested to be removed after BTS-750 was merged.
[x] 3.9: https://github.com/arangodb/arangodb/pull/16384
> Removed requested line

- arangod/Aql/DistributeClientBlock.cpp
- arangod/Aql/DistributeExecutor.cpp
- arangod/Aql/DistributeExecutor.h
- arangod/Aql/ParallelUnsortedGatherExecutor.cpp
- arangod/Aql/ScatterExecutor.cpp
- arangod/Aql/UnsortedGatherExecutor.cpp
Small cleanup inside cluster executors code
> small cluster blocks cleanup

- arangod/IResearch/AqlHelper.cpp
- arangod/Replication2/Methods.cpp
- lib/SimpleHttpClient/SslClientConnection.cpp
> Fix compile warnings/errors with clang14 and gcc11

- .github/CODEOWNERS
- tests/test-definitions.txt
The purpose of this PR is to manage the set of tests executed by jenkins in the arangodb repo. This PR adds a script that produces output for oskar, provided a test definition file. The test definition file is added as well.
Replaces https://github.com/arangodb/arangodb/pull/16052
> pick state of https://github.com/arangodb/arangodb/pull/16052

- tests/test-definitions.txt
test must not be run in cluster
> these are only eligible in single server

- tests/test-definitions.txt
Fix bit-rot of the original PR.
> add api tests

- 3rdParty/V8/gyp/buildtime_helpers/mac_tool.py
- 3rdParty/iresearch/core/store/data_input.hpp
- 3rdParty/iresearch/core/utils/type_info.hpp
- 3rdParty/iresearch/external/absl/absl/functional/function_ref.h
- arangod/RocksDBEngine/Listeners/RocksDBThrottle.cpp
- tests/Auth/UserManagerClusterTest.cpp
Backport of https://github.com/arangodb/arangodb/pull/16434.
> Update mac_tool.py (#3.8)

- 3rdParty/iresearch/core/store/data_input.hpp
- 3rdParty/iresearch/external/absl/absl/functional/function_ref.h
- arangod/RocksDBEngine/Listeners/RocksDBThrottle.cpp
> Fix some warnings 3.9

- tests/js/client/server_parameters/exclusive-collections-off.js
> fix flaky test

- arangod/Agency/ActiveFailoverJob.cpp
- arangod/Agency/AddFollower.cpp
- arangod/Agency/AgencyFeature.cpp
- arangod/Agency/AgencyFeature.h
- arangod/Agency/Agent.cpp
- arangod/Agency/Agent.h
- arangod/Agency/AgentCallback.cpp
- arangod/Agency/CleanOutServer.cpp
- arangod/Agency/FailedFollower.cpp
- arangod/Agency/FailedLeader.cpp
- arangod/Agency/FailedServer.cpp
- arangod/Agency/MoveShard.cpp
- arangod/Agency/ResignLeadership.cpp
- arangod/Agency/Supervision.cpp
- arangod/Agency/Supervision.h
- arangod/Network/Methods.cpp
- tests/Agency/CleanOutServerTest.cpp
- tests/Agency/FailedFollowerTest.cpp
- tests/Agency/FailedLeaderTest.cpp
- tests/Agency/MoveShardTest.cpp
This PR tries to refactor the supervision code, without changing its behavior. Additionally
- unused data types have been removed
- an unused shutdown mechanism has been removed
- The network feature included the supervision.h and this caused the methods.cpp and utils.cpp to be rebuild every time on modifies the supervision.
> [CINFRA] Agency Supervision Refactor

- arangod/Replication2/ReplicatedLog/LogLeader.cpp
- arangod/Replication2/ReplicatedLog/LogLeader.h
- arangod/Replication2/ReplicatedLog/LogStatus.cpp
- arangod/Replication2/ReplicatedLog/LogStatus.h
- arangod/Replication2/ReplicatedLog/types.h
- tests/Replication2/ReplicatedLog/AppendEntriesBatchTest.cpp
- tests/Replication2/Serialization/LogStatusTest.cpp
Add lastMatchedIndex and use this instead of lastAckedIndex. lastAckedIndex is not initalized to 0 and only incremented.
> [CINFRA-463] Added last matched index.

- js/client/modules/@arangodb/testsuites/agency-restart.js
- js/client/modules/@arangodb/testsuites/arangobench.js
- js/client/modules/@arangodb/testsuites/arangosh.js
- js/client/modules/@arangodb/testsuites/authentication.js
- js/client/modules/@arangodb/testsuites/config.js
- js/client/modules/@arangodb/testsuites/dump.js
- js/client/modules/@arangodb/testsuites/endpoints.js
- js/client/modules/@arangodb/testsuites/fail.js
- js/client/modules/@arangodb/testsuites/foxxmanager.js
- js/client/modules/@arangodb/testsuites/fuerte.js
- js/client/modules/@arangodb/testsuites/gtest.js
- js/client/modules/@arangodb/testsuites/importing.js
- js/client/modules/@arangodb/testsuites/permissions_client.js
- js/client/modules/@arangodb/testsuites/queryCacheAuthorization.js
- js/client/modules/@arangodb/testsuites/readOnly.js
- js/client/modules/@arangodb/testsuites/recovery.js
- js/client/modules/@arangodb/testsuites/recovery_cluster.js
- js/client/modules/@arangodb/testsuites/server_permissions.js
- js/client/modules/@arangodb/testsuites/version.js
- js/client/modules/@arangodb/testutils/instance-manager.js
- js/client/modules/@arangodb/testutils/instance.js
- js/client/modules/@arangodb/testutils/process-utils.js
- js/client/modules/@arangodb/testutils/testing.js
- js/client/modules/@arangodb/testutils/testrunner.js
- js/client/modules/@arangodb/testutils/tmpDirManager.js
- js/common/modules/jsunity.js
- reduce testreport file to minimal size
-  remove old magic list of cleanup directories and handle cleanup of testdata inside more special testcases.
> Testcase success temporary data cleanup refactoring

- arangod/Replication2/ReplicatedLog/AgencyLogSpecification.h
- arangod/Replication2/ReplicatedState/Supervision.cpp
- arangod/Replication2/ReplicatedState/SupervisionAction.h
- tests/Replication2/Helper/AgencyLogBuilder.h
- tests/Replication2/Helper/ModelChecker/HashValues.h
- tests/Replication2/ReplicatedState/SupervisionTest.cpp
Fix convergence for replicated state.
> [CINFRA-472] Convergence Fix

- tests/js/common/aql/aql-view-arangosearch-ddl-noncluster.js
if test would throw in the meanwhile it would leave databases behind.
> make sure tests clean up by adding finally

- CHANGELOG
- arangod/IResearch/Geo.cpp
*Fixes verbose logging of 100+GB of logs in big import*
>  fix verbose analysis failures

- arangod/Aql/DistributeClientBlock.cpp
Fix a "heap use after scope" issue reported by ASan.
> fix ASan issue in DistributeBlock

- js/client/modules/@arangodb/testutils/instance-manager.js
- js/client/modules/@arangodb/testutils/testing.js
dumping the agency on shutdown was not working after the instance manager rewrite. Fixed by this PR.
> fix agency dumping, turn it on by default

- arangod/Pregel/Common.h
- arangod/Pregel/Conductor.cpp
- arangod/Pregel/Conductor.h
- arangod/Pregel/GraphStore.cpp
- arangod/Pregel/GraphStore.h
- arangod/Pregel/PregelFeature.cpp
- arangod/Pregel/Status/ConductorStatus.h
- arangod/Pregel/Status/WorkerStatus.h
- arangod/Pregel/Utils.cpp
- arangod/Pregel/Utils.h
- arangod/Pregel/Worker.cpp
Add infrastructure to report pregel worker status to conductor
Based on Draft PR https://github.com/arangodb/arangodb/pull/16338
> [PREGEL] Report worker status to conductor every 1000 loaded vertices

- CHANGELOG
- arangod/Pregel/Conductor.cpp
- arangod/Pregel/Conductor.h
- arangod/Pregel/PregelFeature.cpp
- tests/js/client/load-balancing/load-balancing-pregel-auth-cluster.js
- tests/js/client/load-balancing/load-balancing-pregel-noauth-cluster.js
- tests/js/common/shell/shell-pregel-basics-example.js
- tests/js/common/shell/shell-pregel-components.js
- tests/js/common/shell/shell-pregel-multicollection-edgecol.js
- tests/js/common/shell/shell-pregel-random.js
- tests/js/common/shell/shell-pregel-start-cluster.js
Add loading state that is used when graph is loaded into memory
> [PREGEL] APM-538 Add loading state

- arangod/Pregel/GraphStore.cpp
- arangod/Pregel/GraphStore.h
- arangod/Pregel/Status/Status.h
- arangod/Pregel/Utils.cpp
- arangod/Pregel/Utils.h
- arangod/Pregel/Worker.cpp
- tests/Pregel/StatusTest.cpp
Add number of vertices measurements.
Additionally, make all measurement variables optional to print them only when they are set.
> [PREGEL] APM-538 Add reporting for storing state observables

- arangod/Pregel/GraphStore.h
- arangod/Pregel/Status/Status.h
- arangod/Pregel/Utils.cpp
- arangod/Pregel/Utils.h
- arangod/Pregel/Worker.cpp
- arangod/Pregel/Worker.h
- tests/Pregel/StatusTest.cpp
Report observables in running state per gss.
> [PREGEL] APM-538 add reporting for running state observables

- arangod/Pregel/Worker.cpp
Removes a stray LOG_DEVEL call.
> Remove stray LOG_DEVEL

- js/client/modules/@arangodb/testsuites/aql.js
> work around BTS-903: turn of logging for the queries facility.

- arangod/Agency/Supervision.cpp
- arangod/Replication2/ReplicatedLog/LogCommon.cpp
- js/common/modules/@arangodb/testutils/replicated-logs-predicates.js
- tests/js/server/replication2/replication2-regression.js
This adds tests for the case writeConcern > ReplicationFactor and fixes what ever broke.
> [CINFRA-352] WriteConcern > ReplicationFactor tests

- arangod/RocksDBEngine/RocksDBEngine.cpp
- arangod/Transaction/Methods.cpp
- tests/js/client/shell/transaction/shell-transaction-intermediate-commit-babies-cluster.js
- tests/js/client/shell/transaction/shell-transaction.js
- tests/test-definitions.txt
Added test suite `shell_client_transaction` to the CI matrix. Was added (and some files moved there) in https://github.com/arangodb/arangodb/pull/16414/files#diff-c7ccb564e3e90efc9e6dd3d9e620cb037a3f7eada565c9615564303a9026e292.
> [CINFRA-492] Add suite shell_client_transaction

- arangod/IResearch/Search.cpp
* Remove unnecessary sleep
* Fix collection name in get properties for cluster
> [Search-324] Fix slow search view creation

- arangod/IResearch/IResearchView.cpp
- arangod/IResearch/IResearchViewCoordinator.cpp
- arangod/IResearch/Search.cpp
- arangod/VocBase/LogicalView.cpp
- arangod/VocBase/LogicalView.h
- tests/IResearch/IResearchLinkTest.cpp
[Make search view properties update work for cluster](https://github.com/arangodb/arangodb/commit/92eaf80939fd2933d54478f795c249f0d62658fb)
Please looks only last two commits, others just cherry pick from other pr (already approved and fine jenkins)
> Search-326 Fix search view properties update for cluster

- js/common/modules/@arangodb/testutils/replicated-logs-helper.js
- js/common/modules/@arangodb/testutils/replicated-logs-predicates.js
- tests/js/server/replication2/replication2-supervision-replicated-log-target-cluster.js
This ensures that all append entries requests have been processed by all followers before continuing with the test. Otherwise some check might fail due to partially processed requests. For more, see ticket.
> [CINFRA-491] WaitForReplicatedComplete for SimpleFailoverTest

- lib/Basics/hashes.cpp
- lib/Basics/hashes.h
- tests/Basics/HashesTest.cpp
Remove an unused hash function from the code
> remove unused hash function

- client-tools/Benchmark/BenchmarkThread.h
Add whitespace to error message to make it more readable.
> make error message more readable

- CHANGELOG
- arangod/RocksDBEngine/RocksDBOptionFeature.cpp
3.10 backport of https://github.com/arangodb/arangodb/pull/16611
> Feature 3.10/rocksdb change default compression

- arangod/GeneralServer/GeneralServerFeature.cpp
- arangod/Replication2/ReplicatedLog/ReplicatedLogFeature.cpp
- arangod/Replication2/ReplicatedState/ReplicatedStateFeature.cpp
- arangod/Replication2/StateMachines/BlackHole/BlackHoleStateMachineFeature.cpp
- arangod/VocBase/vocbase.cpp
Clean up replication 2 features and make them disable when replication 2 is disabled.
> [CINFRA] Proper feature dependencies

- arangod/Aql/Functions.cpp
- arangod/Pregel/Conductor.cpp
- tests/js/common/shell/shell-pregel-basics-example.js
After finding out that the bug fixed in https://github.com/arangodb/arangodb/pull/16551 was a feature and cancelling this PR, this PR adds some tests to check this feature. Documentation improvement: https://github.com/arangodb/docs/pull/1062.
> [PREGEL] Add aql pregel result test

- arangod/Aql/Ast.cpp
- arangod/Aql/Ast.h
- arangod/Aql/StandaloneCalculation.cpp
- arangod/Sharding/ShardingInfo.cpp
- arangod/Sharding/ShardingInfo.h
- arangod/VocBase/ComputedValues.cpp
- arangod/VocBase/ComputedValues.h
- arangod/VocBase/LogicalCollection.cpp
- arangod/VocBase/Methods/Collections.cpp
- tests/js/common/shell/shell-collection-computed-values.js
Bugfixes for computed values after initial tests.
> follow-up bugfixes for computed values

- CHANGELOG
- arangod/RestServer/TimeZoneFeature.cpp
backport of https://github.com/arangodb/arangodb/pull/16661
> turn down severety, fix error message

- tests/Mocks/IResearchInvertedIndexMock.h
* Mock is working
* WIP
* wip
* clean up
> Backport in 3.10 for Feature/inverted index tests backport

- Documentation/DocuBlocks/Rest/Administration/post_admin_cluster_rebalance.md
- Documentation/DocuBlocks/Rest/Administration/post_admin_cluster_rebalance_execute.md
- Documentation/DocuBlocks/Rest/Administration/put_admin_cluster_rebalance.md
Fix /_admin/cluster/rebalance DocuBlocks.
> Fix /_admin/cluster/rebalance DocuBlocks (3.10)

- arangod/Aql/OptimizerRulesFeature.cpp
- arangod/GeneralServer/GeneralServerFeature.cpp
- arangod/Pregel/PregelFeature.cpp
- arangod/RestServer/DatabaseFeature.cpp
- arangod/RestServer/EndpointFeature.cpp
- arangod/RestServer/QueryRegistryFeature.cpp
- arangod/RocksDBEngine/RocksDBOptionFeature.cpp
- client-tools/Benchmark/BenchFeature.cpp
- client-tools/Export/ExportFeature.cpp
- client-tools/Import/ImportFeature.cpp
- client-tools/Restore/RestoreFeature.cpp
- client-tools/Shell/V8ShellFeature.cpp
- lib/ApplicationFeatures/ConfigFeature.cpp
- lib/ApplicationFeatures/LanguageFeature.cpp
- lib/Logger/LoggerFeature.cpp
> BTS-874 | Documentation/immutable-startup-options

- CHANGELOG
*Enterprise Only Change, see entry in Enterprise PR*
> Bug fix/insert enterprise edge

- CHANGELOG
*Enterprise Only Change, see entry in Enterprise PR*
Backport of:
https://github.com/arangodb/arangodb/pull/16669
> Bug fix 3.10 /insert enterprise edge

- Documentation/DocuBlocks/Rest/Administration/post_admin_cluster_rebalance.md
- Documentation/DocuBlocks/Rest/Administration/post_admin_cluster_rebalance_execute.md
- Documentation/DocuBlocks/Rest/Administration/put_admin_cluster_rebalance.md
Fix /_admin/cluster/rebalance DocuBlocks.
> Fix /_admin/cluster/rebalance DocuBlocks

- arangod/CMakeLists.txt
- arangod/Pregel/Conductor.cpp
- arangod/Pregel/Conductor.h
- arangod/Pregel/Conductor/StoringState.cpp
- arangod/Pregel/Conductor/StoringState.h
- arangod/Pregel/WorkerConductorMessages.h
Second PR for adding a state machine to the pregel conductor. 
Adds storing state to conductor state machine
> [PREGEL] Add storing state to conductor state machine

- arangod/CMakeLists.txt
- arangod/Pregel/Conductor.cpp
- arangod/Pregel/Conductor.h
- arangod/Pregel/Conductor/CanceledState.cpp
- arangod/Pregel/Conductor/CanceledState.h
- arangod/Pregel/Conductor/LoadingState.cpp
- arangod/Pregel/Conductor/StoringState.cpp
Third PR for adding a state machine to the pregel conductor.
Adds canceled state to conductor state machine
> [PREGEL] Add cancel state to conductor state machine

- tests/test-definitions.txt
backport of https://github.com/arangodb/arangodb/pull/16617
> Feature/reprio test definitions (#16617)

- tsan_arangodb_suppressions.txt
> Suppress absl::Mutex false positive atomic race

- CHANGELOG
- arangod/Aql/AqlFunctionFeature.cpp
- arangod/Aql/Functions.cpp
- arangod/Aql/Functions.h
- tests/js/server/aql/aql-functions.js
Enterprise PR: https://github.com/arangodb/enterprise/pull/994.
backport of #16717
> Add VALUE AQL function for dynamic access by a specified attribute path

- tests/js/client/shell/transaction/shell-transaction-intermediate-commit-cluster.js
> Fixing testSingleTransactionIntermediateCommitsOnFollowerWithRollback.

- CHANGELOG
- arangod/Aql/OptimizerRules.cpp
- tests/js/server/aql/aql-optimizer-collect-count.js
- tests/js/server/aql/aql-queries-optimizer-sort.js
Backport of: https://github.com/arangodb/arangodb/pull/16718
Please see all notes there.
> Fixed illegal optimizer rule on multiple consecutive SORTs

- CHANGELOG
- arangod/Cluster/ClusterInfo.cpp
- arangod/GeneralServer/CommTask.cpp
- arangod/RestHandler/RestControlPregelHandler.cpp
- arangod/RestHandler/RestCursorHandler.cpp
- arangod/RestHandler/RestQueryHandler.cpp
- arangod/RestHandler/RestTransactionHandler.cpp
- js/client/modules/@arangodb/testsuites/restart.js
- tests/js/client/load-balancing/load-balancing-cursor-noauth-cluster.js
- tests/js/client/load-balancing/load-balancing-pregel-noauth-cluster.js
- tests/js/client/load-balancing/load-balancing-queries-noauth-cluster.js
- tests/js/client/load-balancing/load-balancing-transactions-noauth-cluster.js
- tests/js/client/restart/test-restart-coordinator-transactions.js
Backport of https://github.com/arangodb/arangodb/pull/16739
* Improve error handling for passing wrong transaction ids / cursor ids /
pregel job ids to request forwarding. Also prevent the error "transaction
id not found" in cases when request forwarding was tried to a coordinator
that was recently restarted.
Fixes https://arangodb.atlassian.net/browse/ES-1026
> fix "transaction not found" issues

- Documentation/DocuBlocks/Rest/Pregel/get_api_control_pregel_overview.md
- Documentation/DocuBlocks/Rest/Pregel/get_api_control_pregel_status.md
> [PREGEL] Update pregel status documentation

- arangod/Aql/ClusterQuery.cpp
- arangod/Aql/ClusterQuery.h
- arangod/Aql/Query.cpp
- arangod/Aql/Query.h
- arangod/Aql/QueryOptions.h
- lib/Futures/Future.h
- tests/Cache/Rebalancer.cpp
- tests/Cache/TransactionsWithBackingStore.cpp
- tests/Fuerte/ConnectionFailuresTest.cpp
- tests/Futures/FutureTest.cpp
- tests/IResearch/IResearchFeatureTest.cpp
- tests/IResearch/IResearchViewNodeTest.cpp
- tests/Network/MethodsTest.cpp
- tsan_arangodb_suppressions.txt
> Backport fix data races to 3.10

- arangod/InternalRestHandler/InternalRestTraverserHandler.cpp
- js/server/modules/@arangodb/testutils/aql-graph-traversal-generic-graphs.js
- js/server/modules/@arangodb/testutils/aql-graph-traversal-generic-tests.js
Backport of: https://github.com/arangodb/arangodb/pull/16721
EE Companion: https://github.com/arangodb/enterprise/pull/999
> BTS-933: SmartSearch error handling 

- tests/js/client/load-balancing/load-balancing-key-generator-noauth-cluster.js
attempt to fix an unstable test in a multi-coordinator setup.
> attempt to fix an unstable test

- arangod/Aql/ClusterQuery.cpp
- arangod/Aql/ClusterQuery.h
- arangod/Aql/Query.cpp
- arangod/Aql/Query.h
- tests/IResearch/IResearchViewNodeTest.cpp
> Fix data race on query vptr

- arangod/Sharding/ShardingStrategy.cpp
- arangod/Sharding/ShardingStrategy.h
- arangod/Sharding/ShardingStrategyDefault.cpp
- arangod/Sharding/ShardingStrategyDefault.h
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/1004
Small performance optimizations for the sharding code
> improvements for sharding

- arangod/Cluster/ClusterInfo.cpp
Just refactoring, not important.
* [Remove unnecessary mutex lock](https://github.com/arangodb/arangodb/commit/7663b90297a108998ccc283388ad5f02bb504fc2)
* [Make first call safe too and small refactoring](https://github.com/arangodb/arangodb/commit/7606c38118ccdbbb97ab6c95c2ece9ff3efc2171)
> Make syncer better

- arangod/Aql/Functions.cpp
- arangod/Pregel/Conductor.cpp
- arangod/Pregel/Conductor.h
- arangod/Pregel/Conductor/CanceledState.h
- arangod/Pregel/Conductor/ComputingState.h
- arangod/Pregel/Conductor/DoneState.cpp
- arangod/Pregel/Conductor/DoneState.h
- arangod/Pregel/Conductor/FatalErrorState.cpp
- arangod/Pregel/Conductor/FatalErrorState.h
- arangod/Pregel/Conductor/InErrorState.h
- arangod/Pregel/Conductor/InitialState.h
- arangod/Pregel/Conductor/LoadingState.h
- arangod/Pregel/Conductor/RecoveringState.h
- arangod/Pregel/Conductor/State.h
- arangod/Pregel/Conductor/StoringState.h
- arangod/Pregel/PregelFeature.cpp
- arangod/Pregel/Worker.cpp
- arangod/Pregel/Worker.h
- arangod/V8Server/v8-collection.cpp
Use PregelResult struct instead of VPackBuilders
> [PREGEL] Return pregel results struct instead of using VPackBuilder

- arangod/Aql/ExecutionBlockImpl.cpp
- arangod/Aql/IResearchViewExecutor.cpp
- arangod/Aql/IResearchViewExecutor.h
- arangod/Aql/IResearchViewNode.cpp
- arangod/IResearch/AqlHelper.h
- arangod/IResearch/IResearchIdentityAnalyzer.cpp
- arangod/IResearch/IResearchIdentityAnalyzer.h
- arangod/IResearch/ViewSnapshot.cpp
- arangod/IResearch/ViewSnapshot.h
- tests/IResearch/IResearchAnalyzerFeatureTest.cpp
- tests/IResearch/IResearchViewCountApproximateTest.cpp
- tests/IResearch/IResearchViewNodeTest.cpp
> Feature/apm 128 leftovers (#16757)

- arangod/RocksDBEngine/RocksDBTempStorage.cpp
- arangod/RocksDBEngine/RocksDBTempStorage.h
fix "unused member" compile warnings in community edition
> fix "unused member" compile warnings in community edition

- arangod/Cluster/TraverserEngine.cpp
Micro-optimize and clean up setup code for cluster traversals.
> micro-optimize traversal setup code

- arangod/Cluster/EnsureIndex.cpp
- arangod/Cluster/SynchronizeShard.cpp
Level down some informational messages to debug, because they were perceived as errors by some end users.
> level down some informational message to debug

- arangod/Pregel/Conductor.cpp
- arangod/Pregel/PregelFeature.cpp
The found deadlock is not fixed in here.
> [PREGEL] Fix staging bugs

- arangod/IResearch/IResearchInvertedIndexMeta.cpp
> Rename primarySort.primarySortCompression to primarySort.compression

- arangod/Aql/Functions.cpp
- arangod/Pregel/CMakeLists.txt
- arangod/Pregel/Conductor.cpp
- arangod/Pregel/Conductor.h
- arangod/Pregel/ExecutionNumber.cpp
- arangod/Pregel/ExecutionNumber.h
- arangod/Pregel/GraphStore.cpp
- arangod/Pregel/GraphStore.h
- arangod/Pregel/OutgoingCache.cpp
- arangod/Pregel/PregelFeature.cpp
- arangod/Pregel/PregelFeature.h
- arangod/Pregel/REST/RestControlPregelHandler.cpp
- arangod/Pregel/WorkerConductorMessages.h
- arangod/Pregel/WorkerConfig.cpp
- arangod/Pregel/WorkerConfig.h
- arangod/V8Server/v8-collection.cpp
> [PREGEL] Use wrapper class around ExecutionNumber

- js/common/modules/@arangodb/test-helper-common.js
- js/common/modules/@arangodb/testutils/replicated-logs-helper.js
- js/server/modules/@arangodb/test-helper.js
- tests/js/server/resilience/failover/resilience-failure-oracle.js
- tests/js/server/resilience/move/moving-shards-cluster.js
this was here, and removed. We need it for the tests in the nightlies.
> re-add functions lost in merchcident of cd74fb3501276ae1efd4e40b5e48d8448021c4f3

- CMakeLists.txt
- tests/CMakeLists.txt
- tests/sepp/CMakeLists.txt
> [CMAKE] Move building  SEPP into its own place

- Documentation/DocuBlocks/Rest/Graph/general_graph_create_http_examples.md
*Documentation only PR. adds separators between graph creation calls.*
> Added headers for graph creation examples

- CHANGELOG
- arangod/Aql/OptimizerUtils.cpp
- arangod/RocksDBEngine/RocksDBCollection.cpp
- tests/js/server/aql/aql-inverted-index.js
Backport of https://github.com/arangodb/arangodb/pull/16824
Enterprise part https://github.com/arangodb/enterprise/pull/1017
> Bug fix 3.10/handle not in nested search

- Documentation/DocuBlocks/Rest/Graph/general_graph_create_http_examples.md
*DocuBlocks only PR. This will add code examples for HTTP create graph API*
> Documentation 3.10/add topics for graph creations

- CHANGELOG
- arangod/IResearch/IResearchDataStore.cpp
- arangod/IResearch/IResearchDataStore.h
- arangod/IResearch/IResearchInvertedIndex.cpp
- arangod/IResearch/IResearchKludge.cpp
- arangod/IResearch/IResearchKludge.h
- arangod/IResearch/IResearchLink.cpp
Backport https://github.com/arangodb/arangodb/pull/16847
Enterprise PR: https://github.com/arangodb/enterprise/pull/1023
> Bug fix 3.10/search 329 fix nested removes

- tests/js/client/shell/transaction/shell-transaction-intermediate-commit-cluster.js
Backport of original test bugfix done by @maierlars
> Fixing testSingleTransactionIntermediateCommitsOnFollowerWithRollback

- js/client/modules/@arangodb/testsuites/chaos.js
- js/client/modules/@arangodb/testutils/testrunner.js
if test files are not a unique key, the testsuite needs to adopt this properly, else only the last result of same name will be represented in the summary.
Add Hook to the testrunner, implement it in chaos.js to make name uniq.
> Fix chaos test result transport

- js/client/modules/@arangodb/testsuites/chaos.js
- js/client/modules/@arangodb/testutils/testrunner.js
Backport of:
https://github.com/arangodb/arangodb/pull/16876
> Bug fix 3.10/fix chaos test identifiers

- CHANGELOG
- arangod/Aql/AqlFunctionFeature.cpp
- arangod/Aql/Functions.cpp
- arangod/Aql/Functions.h
- tests/js/server/aql/aql-functions-string.js
> Bug fix/search 357 (#16896)

- arangod/Aql/AqlFunctionFeature.cpp
- arangod/Aql/Functions.cpp
- tests/IResearch/IResearchQueryAndTest.cpp
- tests/js/server/aql/aql-functions-string.js
> Make SUBSTRING_BYTES work similar to SUBSTRING (#16912)

- CHANGELOG
- arangod/Aql/OptimizerUtils.cpp
- tests/js/server/aql/aql-inverted-index.js
Backport of  https://github.com/arangodb/arangodb/pull/16908
> Bug fix 3.10/search 368

- arangod/IResearch/IResearchLink.cpp
- tests/IResearch/IResearchInvertedIndexConditionTest.cpp
- tests/IResearch/IResearchInvertedIndexIteratorTest.cpp
- tests/IResearch/IResearchLinkTest.cpp
- tests/IResearch/common.cpp
- tests/IResearch/common.h
- tests/Mocks/IResearchInvertedIndexMock.cpp
- tests/Mocks/IResearchInvertedIndexMock.h
- tests/Mocks/IResearchLinkMock.h
> BTS-959 Fix

- 3rdParty/iresearch/core/formats/columnstore2.cpp
- 3rdParty/iresearch/core/index/index_writer.cpp
- CHANGELOG
> [3.9] SEARCH-350

- CHANGELOG
- arangod/Aql/OptimizerRules.cpp
Backport of #16846 . Enterprise buddy: https://github.com/arangodb/enterprise/pull/1026
> [3.9] [BTS-951] Fix removeUnnecessaryRemoteScatterRule

- arangod/IResearch/IResearchLink.cpp
- tests/IResearch/IResearchInvertedIndexConditionTest.cpp
- tests/IResearch/IResearchInvertedIndexIteratorTest.cpp
- tests/IResearch/IResearchLinkTest.cpp
- tests/IResearch/common.cpp
- tests/IResearch/common.h
- tests/Mocks/IResearchInvertedIndexMock.cpp
- tests/Mocks/IResearchInvertedIndexMock.h
- tests/Mocks/IResearchLinkMock.h
> BTS-959 Fix 3.10

- arangod/Aql/IResearchViewExecutor.cpp
- arangod/Aql/IResearchViewOptimizerRules.cpp
- arangod/IResearch/AqlHelper.h
- arangod/IResearch/IResearchDataStore.cpp
- arangod/IResearch/IResearchDataStore.h
- arangod/IResearch/IResearchFilterFactory.cpp
- arangod/IResearch/IResearchFilterFactory.h
- arangod/IResearch/IResearchInvertedIndex.cpp
- arangod/IResearch/IResearchInvertedIndexMeta.cpp
- arangod/IResearch/IResearchInvertedIndexMeta.h
- arangod/IResearch/ViewSnapshot.cpp
- arangod/IResearch/ViewSnapshot.h
- tests/IResearch/IResearchFilterArrayInTest.cpp
- tests/IResearch/IResearchInvertedIndexMetaTest.cpp
- tests/IResearch/common.cpp
- tests/IResearch/common.h
For ArangoSearch indexes with nested fields <all> filter is replaced with <column_existance> filter over PK column - so only top-level documents are returned.
> Bug fix/search 343

- CHANGELOG
> [3.10] SEARCH-350

- CHANGELOG
- arangod/IResearch/Containers.h
- arangod/IResearch/IResearchDataStore.cpp
- arangod/IResearch/IResearchDataStore.h
- arangod/IResearch/IResearchInvertedIndex.cpp
- arangod/IResearch/IResearchInvertedIndex.h
- arangod/IResearch/IResearchLink.cpp
- arangod/IResearch/IResearchRocksDBInvertedIndex.h
- arangod/IResearch/IResearchView.h
- arangod/IResearch/Search.cpp
- arangod/IResearch/ViewSnapshot.cpp
- arangod/IResearch/ViewSnapshot.h
- lib/Basics/locks-win32.cpp
- lib/Basics/locks-win32.h
- tests/IResearch/IResearchInvertedIndexConditionTest.cpp
- tests/IResearch/IResearchLinkTest.cpp
- tests/js/common/shell/shell-view-search-alias.js
> MBkkt backport fixes

- 3rdParty/iresearch/core/search/min_match_disjunction.hpp
- 3rdParty/iresearch/core/search/ngram_similarity_filter.cpp
> Harden iresearch checks

- 3rdParty/iresearch/core/search/min_match_disjunction.hpp
Refresh potenitally invalidated iterator.
> [3.9] Update potentially invalidated iterator

- lib/Inspection/ValidateInspector.h
- tests/Basics/InspectionTest.cpp
A simple Inspector that only checks the configured field and object invariants.
> Introduce ValidateInspector

- arangod/Pregel/Conductor/ClusterWorkerApi.cpp
- arangod/Pregel/Conductor/ClusterWorkerApi.h
- arangod/Pregel/Conductor/Conductor.cpp
- arangod/Pregel/Conductor/Conductor.h
- arangod/Pregel/Conductor/SingleServerWorkerApi.cpp
- arangod/Pregel/Conductor/SingleServerWorkerApi.h
- arangod/Pregel/Conductor/States/CanceledState.cpp
- arangod/Pregel/Conductor/States/ComputingState.cpp
- arangod/Pregel/Conductor/States/ComputingState.h
- arangod/Pregel/Conductor/States/StoringState.cpp
- arangod/Pregel/NetworkConnection.cpp
- arangod/Pregel/PregelFeature.cpp
- arangod/Pregel/Worker/Worker.cpp
- arangod/Pregel/Worker/Worker.h
- arangod/Pregel/WorkerConductorMessages.h
- arangod/Pregel/WorkerInterface.h
Use futures to start gss in both conductor and worker
> [PREGEL] use future to start gss

- CHANGELOG
- arangod/Aql/OptimizerRules.cpp
> [3.10] [BTS-951] Fix removeUnnecessaryRemoteScatterRule

- arangod/IResearch/Search.cpp
- arangod/IResearch/ViewSnapshot.cpp
> Fix waitForSync for non-maintainer build

- 3rdParty/iresearch/core/search/min_match_disjunction.hpp
Update potenitally invalidated iterator.
> [3.8] Update potenitally invalidated iterator.

- js/client/modules/@arangodb/pregel.js
- js/server/modules/@arangodb/pregel.js
- tests/js/client/restart/test-soft-shutdown-cluster.js
- tests/js/client/restart/test-soft-shutdown-pregel-cluster.js
Addressing some structural issues with the soft shutdown tests
* Use the instance manager throughout to make sure that coordinators used in a test are left in a consistent state
* Split out the Pregel test from the file, as it has separate issues; this way they are more visible
* Minor fix to the Pregel test so that it converges in due course.
> Fixes to `test-soft-shutdown-cluster.js`

- js/client/modules/@arangodb/pregel.js
- js/server/modules/@arangodb/pregel.js
- tests/js/client/restart/test-soft-shutdown-cluster.js
- tests/js/client/restart/test-soft-shutdown-pregel-cluster.js
> [3.10] Fixes to `test-soft-shutdown-cluster.js`

- tests/test-definitions.txt
backport of https://github.com/arangodb/arangodb/pull/17032
> adjust naming to better reflect their meaning

- CHANGELOG
- arangod/IResearch/GeoFilter.cpp
*Tons of useless SPAM in logs to detriment of the customer and our own debug efforts*
> [3.9] Removed endless and useless SPAM from WARN

- Documentation/DocuBlocks/Rest/Graph/general_graph_create_http_examples.md
Documentation only PR. Added missing descriptions for HTTP Graph examples.
> Docs/added missing descriptions for HTTP Graph examples

- arangod/IResearch/IResearchInvertedIndex.cpp
- arangod/IResearch/IResearchInvertedIndexMeta.cpp
- arangod/IResearch/Search.cpp
- arangod/RestHandler/RestReplicationHandler.cpp
- arangod/StorageEngine/HotBackup.cpp
- client-tools/Restore/RestoreFeature.cpp
- tests/js/server/dump/dump-authentication.js
- tests/js/server/dump/dump-setup-cluster.js
- tests/js/server/dump/dump-setup-common.inc
- tests/js/server/dump/dump-setup-mixed.js
- tests/js/server/dump/dump-setup.js
- tests/js/server/dump/dump-test.inc
https://github.com/arangodb/arangodb/pull/16993
> Inverted index hotbackup 3.10

- CHANGELOG
Backport of https://github.com/arangodb/arangodb/pull/17056
> Bug fix 3.10/search 374

- arangod/Aql/Functions.cpp
- tests/Aql/DistanceFunctionTest.cpp
Backport for https://github.com/arangodb/arangodb/pull/17055
> Bugfix 3.10/BTS-980

- arangod/IResearch/IResearchInvertedIndexMeta.cpp
- arangod/IResearch/IResearchLinkMeta.cpp
- tests/IResearch/IResearchIndexTest.cpp
- tests/IResearch/IResearchInvertedIndexMetaTest.cpp
- tests/IResearch/IResearchLinkMetaTest.cpp
> [SEARCH-362] Handle nested fields in CE

- arangod/IResearch/IResearchInvertedIndexMeta.cpp
- arangod/IResearch/IResearchLinkMeta.cpp
- tests/IResearch/IResearchIndexTest.cpp
- tests/IResearch/IResearchInvertedIndexMetaTest.cpp
- tests/IResearch/IResearchLinkMetaTest.cpp
> [SEARCH-362] Handle nested fields in CE (#17070)

- arangod/Transaction/Methods.cpp
Backport of https://github.com/arangodb/arangodb/pull/17075
Verify the obtained shared_pointer to `LogicalCollection` so that when it is a nullptr, we do not dereference it and crash, but fail with a proper error message instead.
> BTS-970: verify collection pointer before dereferencing it

- arangod/RocksDBEngine/RocksDBMetaCollection.cpp
Backport of https://github.com/arangodb/arangodb/pull/17051
Add more logging in case of revision tree insert/remove failures
> add more logging

- js/client/modules/@arangodb/testutils/crash-utils.js
- js/client/modules/@arangodb/testutils/instance-manager.js
- js/client/modules/@arangodb/testutils/instance.js
backport of https://github.com/arangodb/arangodb/pull/17082
> Testframework: Fix handling in crash analysis

- arangod/IResearch/IResearchFeature.cpp
- tests/js/common/aql/aql-arangosearch-offset-info-community.js
- tests/js/common/aql/aql-view-arangosearch-noncluster.js
- tests/js/common/test-data/search/texts/north.txt
Various tests and fixes for `OFFSET_INFO`
> Feature/qa 310/add offset info test cases devel branch

- arangod/IResearch/IResearchInvertedIndex.cpp
- arangod/IResearch/IResearchInvertedIndexMeta.cpp
- arangod/IResearch/IResearchInvertedIndexMeta.h
- arangod/IResearch/IResearchLinkMeta.h
- arangod/IResearch/IResearchRocksDBInvertedIndex.cpp
- arangod/IResearch/IResearchRocksDBInvertedIndex.h
- arangod/IResearch/Search.cpp
- arangod/RestHandler/RestReplicationHandler.cpp
- arangod/StorageEngine/HotBackup.cpp
- client-tools/Restore/RestoreFeature.cpp
- tests/IResearch/IResearchInvertedIndexMetaTest.cpp
- tests/js/server/dump/dump-authentication.js
- tests/js/server/dump/dump-setup-cluster.js
- tests/js/server/dump/dump-setup-common.inc
- tests/js/server/dump/dump-setup-mixed.js
- tests/js/server/dump/dump-setup.js
- tests/js/server/dump/dump-test.inc
> Inverted index hotbackup and fix for collection name

- arangod/Transaction/Methods.cpp
BTS-970: more checks for potential nullptr dereferences
> more checks for potential nullptr dereferences

- tests/Basics/InspectionTest.cpp
> Fix compiler warning

- arangod/Pregel/Conductor/Conductor.cpp
- arangod/Pregel/Conductor/Conductor.h
- arangod/Pregel/Conductor/States/CanceledState.cpp
- arangod/Pregel/Conductor/States/DoneState.cpp
- arangod/Pregel/Conductor/States/FatalErrorState.cpp
- arangod/Pregel/Conductor/States/StoringState.cpp
- arangod/Pregel/IncomingCache.cpp
- arangod/Pregel/IncomingCache.h
- arangod/Pregel/OutgoingCache.cpp
- arangod/Pregel/PregelFeature.cpp
- arangod/Pregel/Status/ConductorStatus.h
- arangod/Pregel/Utils.cpp
- arangod/Pregel/Utils.h
- arangod/Pregel/Worker/Worker.cpp
- arangod/Pregel/Worker/Worker.h
- arangod/Pregel/WorkerConductorMessages.h
Use the general message for all communication between conductor and workers.
> [PREGEL] use general messages for all communication between conductor and workers

- arangod/Pregel/Aggregator.h
- arangod/Pregel/Algos/SCC.cpp
- arangod/Pregel/Algos/SCC.h
- arangod/Pregel/Graph.h
Improved explanation of Pregel's SCC algorithm, trivial changes according to clang-tidy.
> [PREGEL] Improved explanation of Pregel SCC and tidification

- arangod/Cluster/ClusterInfo.cpp
- arangod/Cluster/ClusterInfo.h
- arangod/Metrics/ClusterMetricsFeature.cpp
- arangod/Metrics/ClusterMetricsFeature.h
- tests/js/common/aql/aql-view-arangosearch-ddl-cluster.js
- tests/js/common/shell/shell-view-search-alias.js
- tests/js/server/dump/dump-setup-common.inc
- tests/js/server/dump/dump-test.inc
- tests/js/server/recovery/view-search-alias-populate-cluster.js
- tests/js/server/recovery/view-search-alias-populate.js
- tests/test-definitions.txt
* Fix recovery for search-alias view
* Add test for full update properties of search-alias view
* Make ClusterMetricsFeature more available: data that updated eventually now became available faster
* Add and fix tests for iresearch cluster metrics (figures/stats)
> FIxes and tests

- CHANGELOG
- arangod/Aql/OptimizerRules.cpp
- arangod/IResearch/IResearchDocument.cpp
- arangod/IResearch/IResearchInvertedIndexMeta.cpp
- arangod/IResearch/IResearchInvertedIndexMeta.h
- tests/js/server/aql/aql-inverted-index.js
Backports of  https://github.com/arangodb/arangodb/pull/17101 and  https://github.com/arangodb/arangodb/pull/17095
Enterprise part: https://github.com/arangodb/enterprise/pull/1070
> Bug fix 3.10/SEARCH-373 SEARCH-386

- arangod/RocksDBEngine/RocksDBOptionFeature.cpp
Backport of https://github.com/arangodb/arangodb/pull/17132
Added missing parameter documentation for components
> added missing parameter documentation for components

- CHANGELOG
- arangod/Aql/GraphNode.cpp
- arangod/Aql/GraphNode.h
EE PR:  https://github.com/arangodb/enterprise/pull/1073
Backport of DEVEL PR. Please see all related information in this PR:
- https://github.com/arangodb/enterprise/pull/1069
> [BTS-1017] Fix optimizer rule for Hybrid Disjoint Smart Graphs

- tests/js/common/aql/aql-view-arangosearch-ddl-cluster.js
- tests/js/server/dump/dump-test.inc
- tests/js/server/recovery/view-search-alias-populate-cluster.js
> Make iresearch tests more reliable
