arangodb/arangodb

- js/actions/api-edges.js
Add missing return codes to API docs of read in/out/any edges operation.
> Add missing return codes to API docs.

- Documentation/Books/Users/Traversals/ExampleData.mdpp
Hi! 
I'm currently exploring ArangoDB and reading through documentation. It's of great help, pretty clear structured and full of useful examples. Many thanks!
For section 'Traversals/Example Data' I would suggest adding instructions for creating graph out of given data. This would make reproducing the example traversals even more easy and smooth. 
Please find my version of queries in the PR.
Elena Bolshakova
> A small suggestion for 'Traversals/Example Data' documentation section 

- arangod/RestHandler/RestReplicationHandler.cpp
little detail for the docs. stumbled over this while reading the replication dump.
aaaaand I forgot my editor removes trailing whitespace, I hope you don't mind
> replication dump response doc detail

- js/actions/_api/collection/app.js
update from MB (1000 * 1000) to MiB (1024 * 1024)
https://en.wikipedia.org/wiki/Mebibyte
> docs: update MB to MiB

- Documentation/Books/Users/IndexHandling/WhichIndex.mdpp
> Correct some typos in documentation about indexes.

- Documentation/Books/Users/Foxx/Install/README.mdpp
Added a section with examples of how to use configuration from the cli.
> added Configuration

- js/client/modules/org/arangodb/foxx/manager.js
Added updateDeps to foxx-manager cli for use with salt. please give good look over this.
> added updateDeps

- js/client/modules/org/arangodb/foxx/manager.js
Reverts arangodb/arangodb#1416
> Revert "added updateDeps"

- Documentation/Books/Users/Edges/README.mdpp
- Documentation/Examples/012_documentsCollectionUpdateByExample.generated
- arangod/V8Server/v8-collection.cpp
- arangod/V8Server/v8-vocbase.cpp
- js/common/modules/org/arangodb/arango-collection-common.js
As for me as a new user, there were parts in documentation, that could be improved:
* Misleading edge modification
* No clear example to distinguish replace/update operations
* No context in first Graph operation example
* There were easier way to create new user with new database/
> Small documentation improvements

- js/apps/system/_admin/aardvark/APP/frontend/js/modules/org/arangodb/tutorial.js
- js/client/modules/org/arangodb/tutorial.js
> Correct misspelling in tutorial

- js/apps/system/_admin/aardvark/APP/frontend/js/bootstrap/module-internal.js
- js/apps/system/_admin/aardvark/APP/frontend/js/modules/org/arangodb/arango-collection-common.js
> added generated files

- lib/Basics/messages.h
Hello, just a small contribution to ArangoDB, I've added bye message for portuguese language.
> Added PT bye message

- Documentation/Books/Users/WebInterface/README.mdpp
application renamed to service in Web Interface description
> 'application' renamed to 'service' in Web Interface description

- Documentation/Books/Users/Aql/ArrayFunctions.mdpp
- Documentation/Books/Users/IndexHandling/README.mdpp
indent correctly examples in Aql/ArrayFunctions for improved readability
add missing links in Indexing main chapter (/IndexHandling/README.mdpp)
> documentation: minor updates 

- js/server/modules/@arangodb/foxx/manager.js
- js/server/modules/@arangodb/foxx/routing.js
This backports the exportcache fix from 2.8 to devel
> Backport exportcache fix

- Documentation/Books/Users/AqlExtending/Conventions.mdpp
> doc: added statement about direct access to _aqlfunctions

- js/server/tests/aql/aql-functions-types.js
- js/server/tests/aql/aql-logical.js
> Add unit tests for TO_BOOL() and unary not with a whole document

- arangod/Aql/FunctionDefinitions.cpp
- arangod/Aql/Functions.cpp
- arangod/Aql/Functions.h
- js/server/modules/@arangodb/aql.js
- js/server/tests/aql/aql-functions-string.js
> Add ATAN2() and adjust/extend tests for CONCAT() and CONCAT_SEPARATOR()

- Documentation/DocuBlocks/Rest/Graph edges/API_EDGE_REPLACE.md
rm Note: The attributes _from and _to of an edge are immutable
> Edge Replace: _to and _from are required

- js/apps/system/_admin/aardvark/APP/frontend/js/config/dygraphConfig.js
- js/apps/system/_admin/aardvark/APP/frontend/js/views/dashboardView.js
> Fix dygraph data cleanup logic

- js/server/modules/@arangodb/foxx/context.js
this fixes #1898
returns only documented values and hides internal values.
> custom toJSON for FoxxContext

- CMakeLists.txt
change  the server port with cmake param *-DSNAP_PORT=<number>*
> creating snap package (with -DUSE_SNAPCRAFT=ON)

- 3rdParty/CMakeLists.txt
add_definitions(..) should be befor add_subdirectory(..)
> fix bugfix

- cmake/dump_vars.cmake
dump of
- COMPILE_DEFINITIONS
- MACROS
- VARIABLES
> refactoring dump_vars

- js/client/modules/@arangodb/arango-query-cursor.js
This restores the cursor position after the toString() method consumed the first 10 results.
#2257
> restore the cursor position

- Documentation/Books/Manual/Deployment/ArangoDBStarter.md
This PR updates documentation regarding ArangoDBStarter's changes to be released soon.
Not to be merged until starter release has been updated.
> Update docs to reflect changed in ArangoDB starter 0.7

- Documentation/Books/AQL/ExecutionAndPerformance/Optimizer.md
The explanation did not match the example output.
> Updated Optimizer rule documentation.

- CHANGELOG
- js/common/test-data/apps/minimal-working-service/index.js
- js/common/test-data/apps/minimal-working-service/manifest.json
- js/server/modules/@arangodb/actions.js
- js/server/modules/@arangodb/foxx/manager.js
- js/server/tests/shell/shell-foxx-routing-consistency-spec.js
> Implement clusterfoxx mounting logic

- js/apps/system/_api/foxx/APP/index.js
- js/server/modules/@arangodb/foxx/manager.js
* Manager should distinguish between errors and services
* Foxx API should not require service to exist for uninstall
if force option is used
> Fix Foxx API error

- Documentation/Books/Manual/Administration/Replication/README.md
- Documentation/Books/Manual/DataModeling/Collections/DatabaseMethods.md
- Documentation/DocuBlocks/Rest/Cursors/JSF_post_api_cursor.md
This reverts commit 5d1263a4fe15115d17db32de01df599701deb695.
> Revert "remove satelites"

- lib/ApplicationFeatures/EnvironmentFeature.cpp
and activate it again properly for next beta
> turn off overcommit check temporarily

- Installation/Windows/Templates/NSIS.template.in
- enable to choose the app directory too, so we write foxxes into the proper locations
- strip out more fuzz about global installation and services
- add a custom uninstaller page showing which directories we intend to delete
- more cleanup
> Work on the NSIS installer

- arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
> enable RVO

- arangod/Cache/Cache.cpp
- arangod/Cache/Cache.h
- arangod/Cache/Finding.cpp
- arangod/Cache/Finding.h
- arangod/Cache/Manager.cpp
- arangod/Cache/PlainCache.cpp
- arangod/Cache/PlainCache.h
- arangod/Cache/TransactionalCache.cpp
- arangod/Cache/TransactionalCache.h
- arangod/Graph/TraverserDocumentCache.cpp
- arangod/RocksDBEngine/RocksDBCollection.cpp
- arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
- arangod/RocksDBEngine/RocksDBIndex.cpp
- arangod/RocksDBEngine/RocksDBPrimaryIndex.cpp
- tests/Cache/Manager.cpp
- tests/Cache/PlainCache.cpp
- tests/Cache/Rebalancer.cpp
- tests/Cache/TransactionalCache.cpp
- tests/Cache/TransactionalStore.cpp
Addresses arangodb/planning#192
> Augmented cache API and fixed a potential deadlock scenario.

- Installation/debian/config.in
- Installation/debian/templates.in
- improve wording in some of the debconf dialogs
- fix password / password repeat comparison
- fix cancel button for storage engine dialog.
> Work on the debian packages

- js/server/tests/aql/aql-graph-traverser.js
Fixing wrong AQL statements in `js/server/tests/aql/aql-graph-traverser.js`
> Bugfix for cluster bug

- 3rdParty/rocksdb/v5.6.X/util/crc32c_sse4.cc
Fix a problem reported by @baslr on GNU/Linux
> fix even more issues with SSE detection

- Documentation/DocuBlocks/Rest/Collections/JSF_put_api_collection_load_indexes_in_memory.md
- lib/Basics/Mutex.cpp
> to be but not to bee

- UnitTests/HttpInterface/api-users-spec.rb
- arangod/StorageEngine/TransactionState.h
- arangod/VocBase/AuthInfo.cpp
https://github.com/arangodb/planning/issues/414
> fix authinfo caching

- lib/SimpleHttpClient/Communicator.cpp
- lib/SimpleHttpClient/Communicator.h
Should fix https://github.com/arangodb/planning/issues/413
> should fix https://github.com/arangodb/planning/issues/413

- js/server/tests/aql/aql-graph-traverser.js
Missing aassertTrue declaration
> missing assertTrue entry in global

- Documentation/Books/Manual/DataModeling/Documents/DocumentMethods.md
https://github.com/arangodb/planning/issues/423
> fix curd operation documentation for arrays

- arangod/GeneralServer/GeneralServerFeature.cpp
- arangod/RestServer/DatabaseFeature.cpp
- arangod/VocBase/AuthInfo.cpp
Sorry apparently this never needed to work on the coordinator :-(
> Fixing enumerate db's in cluster

- arangod/V8Server/v8-vocbase.cpp
===>>>> DO **NOT** MERGE! <<<< ===
match v8 and rest calls response
> change "parameters" to "bindVars"

- cmake/OptimizeForArchitecture.cmake
> add kabylake arch

- arangod/Aql/AstNode.cpp
- arangod/Aql/Functions.cpp
- arangod/Aql/Query.cpp
- arangod/RocksDBEngine/RocksDBAqlFunctions.cpp
- arangod/RocksDBEngine/RocksDBIndexFactory.cpp
For finding the root cause of Github issue #2810
> do not throw OOM errors in case something else has happened

- scripts/build-docker.sh
build docker to build using stretch container
> build docker to build using stretch container

- js/client/modules/@arangodb/arango-database.js
Should probably be merged before the release
> Fix engine stats in arangosh

- 3rdParty/V8/v5.7.0.0/src/base/logging.cc
- 3rdParty/V8/v5.7.0.0/src/base/platform/platform-posix.cc
- arangod/V8Server/v8-collection.cpp
- arangod/V8Server/v8-query.cpp
- arangod/V8Server/v8-replication.cpp
- arangod/V8Server/v8-vocbase.cpp
Make V8 log error messages to syslog on Linux before V8 terminates the process
> Bug fix/v8 syslog

- arangod/V8Server/v8-users.cpp
Need to call reloadAllUsers explicitly on all coordinators.
> Fix _admin/auth/reload.

- arangod/V8Server/v8-dispatcher.cpp
- js/client/tests/shell/shell-foxx-queue-spec.js
Multiple registration of the same queue was possible. The queue document in _queue was saved multiple times with the same key/id
> Fix Foxx queue registration

- CHANGELOG
- Documentation/Books/Manual/ReleaseNotes/KnownIssues32.md
- arangod/MMFiles/MMFilesCollection.cpp
> fixed issue #3075: Error when upgrading arangoDB on linux ubuntu 16.04

- arangod/V8Server/v8-dispatcher.cpp
- js/client/tests/authentication/user-access-right-foxx-queue-general-spec.js
Fixes an error with foxx queues under authentication.
> Bug fix/foxx queue auth (devel)

- arangosh/Import/ImportHelper.cpp
> Report proper error for arangoimp create collection failure.

- js/client/tests/authentication/user-access-right-foxx-queue-general-spec.js
Jenkins occasionally trips on this test, this small change should fix it
> Making foxx-queues test deterministic

- Installation/arangodb-helper
- Installation/debian/postinst.in
build and tested on stretch in systemd container
> fix systemd issues when reinstalling a package

- arangod/Transaction/Methods.cpp
Increase minimal timeout for RocksDB case. Computation based on body size not document count.
> Bug fix/fight drop follower

- arangod/Aql/ClusterBlocks.cpp
- js/server/modules/@arangodb/cluster.js
Lower lots of log levels to avoid errors in situations that can happen in production.
> Bug fix/log levels sync repl

- arangod/RocksDBEngine/RocksDBRestReplicationHandler.cpp
> Add tick to batch result.

- arangod/RocksDBEngine/RocksDBReplicationContext.cpp
Also: Make hash computations for chunks independent.
> Fix bug in RocksDB incremental collection sync for empty colls.

- arangod/Aql/ExecutionPlan.cpp
- arangod/Graph/Traverser.cpp
- arangod/Graph/Traverser.h
- arangod/RestServer/BootstrapFeature.cpp
- arangod/RestServer/UpgradeFeature.cpp
- arangod/VocBase/AuthInfo.cpp
- arangod/VocBase/AuthInfo.h
- Fixing a race condition between coordinators
- Adding missing user reload call
Should fix some driver tests
> Fixing Cluster Authentication

- Documentation/Books/AQL/styles/header.js
- Documentation/Books/Cookbook/styles/header.js
- Documentation/Books/HTTP/styles/header.js
- Documentation/Books/Manual/styles/header.js
so its similar to all other books that also start with a capital letter.
> the Cookbook deserves a capital C!

- Installation/Jenkins/build.sh
- keep MD5-sum in cache file
- check MD5-sum against last download
- don't keep a copy in the checkout directory
- move git logout to TRAP.
> Fix handling of last download of sync'er and starter

- cmake/packages/bundle.cmake
With the sync'er we need more space in the DMG.
> increase the size of the image, we need more space now.

- 3rdParty/CMakeLists.txt
- lib/Basics/win-utils.cpp
- lib/Basics/win-utils.h
"Just call WSAStartup once and never clean up. Seriously, this is kind of a piece of leftover architecture from Win3.1 and Win32s." - ok.
> remove remaints of libev.

- arangod/VocBase/Methods/Databases.cpp
Java client tests revealed that...
> Database info was returning VPack none...was "none" before

- UnitTests/HttpInterface/api-replication-mmfiles-spec.rb
- UnitTests/HttpInterface/api-replication-rocksdb-spec.rb
- UnitTests/HttpInterface/arangodb.rb
* Improved the arangodb ruby module for tests to allow usage of different databases
* Added Further Tests for non _system database
> Tests/replication tests (#3404)

- Installation/Pipeline/Jenkinsfile.groovy
Fixes the groovy file to build the 3.2 enterprise version if no other exists.
> Fixed Jenkinsfile to default to 3.2 enterprise release

- arangod/V8Server/v8-collection.cpp
- arangod/V8Server/v8-dispatcher.cpp
- js/server/modules/@arangodb/foxx/queues/index.js
- lib/Rest/Version.cpp
> Fix asan detection in clang

- js/common/tests/http/document-babies-spec.js
Testing babies API in cluster is performed hereafter with replication and sharding.
> Babies API in cluster with replicated collection

- CHANGELOG
- Documentation/Books/Manual/Graphs/GeneralGraphs/Management.md
- Documentation/Books/Manual/Graphs/SmartGraphs/Management.md
- Documentation/DocuBlocks/Rest/Graph/JSF_general_graph_create_http_examples.md
- js/common/modules/@arangodb/general-graph.js
- js/common/tests/http/api-gharial-creation-cluster-spec.js
- js/common/tests/shell/general-graph-creation-cluster-spec.js
- js/common/tests/shell/general-graph-creation-spec.js
In the general graph case and api-gharial replicationFactor and numberOfShards could not be set on the graph object, it worked only for smart-graphs.
WIth this PR this inconsitency is removed, community graphs now also support setting numberOfShards and replicationFactor.
> Bug fix/general graph cluster fixes

- arangod/Agency/AgencyComm.cpp
Agency must not return empty body on 200
> Return the result of the inquiry

- .gitattributes
as described at https://gist.github.com/tmaybe/4c9d94712711229cd506
> ignore autogenerated files during merge: 

- Documentation/Books/Manual/Deployment/Distributed.md
- Documentation/Books/Manual/Deployment/Docker.md
- Documentation/Books/Manual/Deployment/Local.md
- arangod/Cluster/ServerState.cpp
- Currently specifying this option might crash a newly started clusterm, this commit fixes this
> Fix --cluster.my-local-info

- CHANGELOG
- arangod/Aql/AqlFunctionFeature.cpp
- arangod/Aql/Functions.cpp
- arangod/Aql/Functions.h
- js/server/modules/@arangodb/aql.js
- js/server/tests/aql/aql-functions-string.js
backport aql substring c++ version from 3.2 to devel
> cpp aql substring, fixed v8 substring

- arangod/Agency/Supervision.cpp
- arangod/Cluster/HeartbeatThread.cpp
, it was not modified anymore after the current master dies
> Reactivated the failover of the FoxxMaster

- arangod/V8Server/v8-dispatcher.cpp
- js/client/tests/authentication/user-access-right-foxx-queue-general-spec.js
- js/common/test-data/apps/queue/setup.js
- js/common/test-data/apps/queue/teardown.js
- Due to recent changes in the permissions API, createQueue did not working in every server context.
- This pull request should set this straight
> Fixing permission problem in createQueues

- arangod/Agency/AgencyFeature.cpp
- arangod/Agency/AgencyFeature.h
- arangod/Agency/Agent.cpp
- arangod/Agency/Agent.h
- arangod/Agency/AgentConfiguration.cpp
- arangod/Agency/AgentConfiguration.h
- arangod/Agency/Constituent.cpp
- arangod/Agency/State.cpp
This ports all the additional fixes in the agency we found for 3.2.6 back to devel.
> Fix agency restart problems.

- arangod/Cluster/ClusterInfo.cpp
- arangod/VocBase/LogicalCollection.cpp
- js/client/modules/@arangodb/arango-collection.js
- js/server/tests/shell/shell-properties-cluster-spec.js
Allow changing `replicationFactor` via properties call
> Changing replication factor in 3.2

- Installation/debian/prerm.in
- cmake/packages/deb.cmake
> Bug fix/stop on purge

- Installation/debian/prerm.in
- cmake/packages/deb.cmake
> fix deb.cmake to include prerm script

- arangod/Pregel/PregelFeature.cpp
- arangod/Pregel/Worker.cpp
- arangod/Pregel/Worker.h
- arangod/RestHandler/RestPregelHandler.cpp
- arangod/V8Server/v8-collection.cpp
- lib/Rest/HttpResponse.cpp
- Fixing broken response logic
- Needs more investigating I suppose
> Fixing Pregel module

- lib/ApplicationFeatures/EnvironmentFeature.cpp
* warn about custom MALLOC_CONF value
* print info if IPv6 is disabled
* print OS info on Linux
> more startup environment checks

- 3rdParty/velocypack/include/velocypack/Compare.h
- 3rdParty/velocypack/include/velocypack/ValueType.h
- 3rdParty/velocypack/include/velocypack/velocypack-aliases.h
- 3rdParty/velocypack/src/ValueType.cpp
- CHANGELOG
- arangod/Agency/Node.cpp
> bug fix for agency precondition checks

- scripts/cluster-run-common.sh
- scripts/shutdownLocalCluster.sh
- scripts/startLocalCluster.sh
This should help you to bring the cluster up again when you
continue to work after some time without investigating the
port numbers.
> Store parameters of startLocalCluster.sh

- arangod/Aql/AstNode.cpp
- arangod/Aql/OptimizerRules.cpp
- js/server/tests/aql/aql-optimizer-geoindex.js
Using indexes with a single filed is now possible
> fixes: geoindex type 1 queries

- CHANGELOG
smart graphs would yield an invalid vpack structure
> Cluster inventory fix

- arangod/Agency/AgencyFeature.cpp
- arangod/Agency/AgencyFeature.h
- arangod/Agency/Agent.cpp
- arangod/Agency/Agent.h
- arangod/Agency/AgentCallback.cpp
- arangod/Agency/AgentConfiguration.cpp
- arangod/Agency/AgentConfiguration.h
- arangod/Agency/Constituent.cpp
- arangod/Agency/Constituent.h
- arangod/Agency/Inception.cpp
- arangod/Agency/Inception.h
- arangod/Agency/State.cpp
- arangod/Cluster/ServerState.h
This ports the agency restart enhancements from devel to the 3.2 branch.
> Port agency restart enhancements to 3.2

- arangod/Agency/AgencyFeature.cpp
- arangod/Agency/AgentConfiguration.cpp
- arangod/Agency/AgentConfiguration.h
- arangod/Agency/Compactor.cpp
* make copying of AgentConfiguration thread-safe
* ensure proper shutdown order of AgencyFeature => Agent => other features
> fix some threading issues

- arangod/RocksDBEngine/RocksDBReplicationTailing.cpp
Backporting changes from devel, removing asserts, adding checks #3677
> Removing unsafe asserts in wal tailing v3.2

- arangod/Agency/AgencyComm.cpp
- arangod/Agency/AgencyFeature.cpp
- arangod/Agency/AgencyFeature.h
- arangod/Agency/Agent.cpp
- arangod/Agency/Agent.h
- js/server/tests/resilience/resilience-synchronous-repl-cluster.js
Remove precondition that was not needed in AgencyComm::removeValues.
> Fix agency shutdown bug.

- arangod/MMFiles/MMFilesRestReplicationHandler.cpp
- arangod/RocksDBEngine/RocksDBReplicationTailing.cpp
- arangod/RocksDBEngine/RocksDBRestReplicationHandler.cpp
- arangod/RocksDBEngine/RocksDBTransactionState.cpp
- Fixes solve a problem with intermediate commits and replication
- Should address github.com/arangodb/arang…odb/issues/3252
> Backporting two fixes from devel

- arangod/Aql/AstNode.h
- arangod/Aql/Condition.cpp
- arangod/Aql/ConditionFinder.cpp
- js/server/tests/aql/aql-optimizer-useindexes.js
Moves attribute accesses to the LHS when using <,>,<=,>=
> Stricter normalization for filter and sort conditions

- arangod/Cluster/ClusterComm.cpp
Correcting my childish mistake: was calling erase() on an iterator while same iterator was still controlling a loop.  Moved erase to after loop completes.
> Don't erase iterator in middle of its loop

- js/server/tests/replication/replication-ongoing-global.js
- js/server/tests/replication/replication-ongoing.js
Adding adaptive timeouts to make tests deterministic
> Fix occasional Replication Ongoing hiccups

- arangod/RocksDBEngine/RocksDBThrottle.cpp
This PR contains two subtle adjustments to the smoothing algorithm:
1.  RocksDB has a setting max_delayed_write_rate which will actually throttle our calculated throttle.  The primary fix in this PR is to override max_delated_write_rate.
2.  This throttle was based upon an environment that did not have regular, small write buffers / .sst files.  The small files have a non-disk overhead that influences the throttle rate down over the long term inappropriately.  Now, only large compactions are used within the smoothing algorithm.
> Throttle adjustments for high speed arrays

- Documentation/Books/Cookbook/README.mdpp
- Documentation/Books/HTTP/README.mdpp
- Documentation/Books/build.sh
- fix reference to the drivers page. Thanks to @m00ki3 for pointing this out.
- add documentation build script for compatibility with 3.2
- fix heading in cookbook
> Documentation 3.1/fix driver link

- arangod/VocBase/AuthInfo.cpp
by using a single transaction in the agency. This has a much lower potential to be unsuccessful
> Improved CAS in AuthInfo sync-code

- js/apps/system/_api/foxx/APP/index.js
- js/server/modules/@arangodb/foxx/service.js
>  More consistent config/deps output in Foxx API (3.2)

- arangod/Cluster/ClusterInfo.cpp
- arangod/Cluster/HeartbeatThread.cpp
- arangod/Cluster/ServerState.cpp
Cannot inquire about AgencyGeneralTransaction at current. 
Replacing all occurences with AgencyWriteTransaction was straightorward
> replaced all AgencyGeneralTransactions by AgencyWriteTransaction

- Documentation/Books/Manual/Administration/Arangoimp.md
- Documentation/Books/Manual/Administration/Arangorestore.md
> update wrong information in arangorestore documentation

- arangod/Aql/Functions.cpp
Fixes UNIQUE and UNION_DISTINCT
> Resolving externals before using them with VelocyPackHelper::VPackHash

- arangod/Aql/Functions.cpp
(cherry picked from commit 99e0da77177cb91e480a52c78355037f2dffbb3a)
> Resolving externals before using them with VelocyPackHelper::VPackHash (3.2)

- CHANGELOG
- arangod/Graph/TraverserOptions.cpp
- js/server/tests/aql/aql-graph-traverser.js
> Reduce planning time of high depth Traversals

- .gitattributes
See https://github.com/arangodb/arangodb/pull/3941
> Bug fix 3.3/git enforce more lf line endings

- configure/windows_common.ps1
- configure/windows_vs2015_RelWithDebInfo.ps1
- configure/windows_vs2017_Debug.ps1
- configure/windows_vs2017_RelWithDebInfo.ps1
- configure/windows_vs2017_Release.ps1
solve internal issue: https://github.com/arangodb/planning/issues/1464
> check alternative registry key if the fist one is not found

- Documentation/Books/AQL/Tutorial/Geospatial.md
- Documentation/Books/AQL/Tutorial/Join.md
- Documentation/Books/AQL/Tutorial/Traversal.md
> Small AQL tutorial improvements

- CMakeLists.txt
Reverts arangodb/arangodb#4077
> Revert "enable iresearch feature by default"

- arangod/RocksDBEngine/RocksDBCounterManager.cpp
(cherry picked from commit ab9faf56ce81a214a20683f7512db063ef9b063b)
> Make sure recalculated counts are actually stored

- arangod/RestHandler/RestReplicationHandler.cpp
Please review, let's discuss possible side-effects tomorrow
> Passing incremental sync option to initial syncer

- arangod/Cluster/ClusterComm.cpp
From PR 3740 on devel/3.3:
Correcting my childish mistake: was calling erase() on an iterator while same iterator was still controlling a loop. Moved erase to after loop completes.
> Bug Fix 3.2:  Don't erase iterator in middle of its loop

- Installation/Pipeline/Jenkinsfile.groovy
- Installation/Pipeline/Jenkinsfile.groovy.in
We want to avoid that custom builds that do nothing pass all tests and
are listed as green.
> Make sure pipeline tries to build something.

- arangod/Aql/BasicBlocks.cpp
- arangod/Aql/CalculationBlock.cpp
- arangod/Aql/ClusterBlocks.cpp
- arangod/Aql/EnumerateCollectionBlock.cpp
- arangod/Aql/EnumerateListBlock.cpp
- arangod/Aql/ExecutionBlock.cpp
- arangod/Aql/ExecutionBlock.h
- arangod/Aql/ExecutionNode.h
- arangod/Aql/IndexBlock.cpp
- arangod/Aql/ModificationBlocks.cpp
- arangod/Aql/OptimizerRules.h
- arangod/Aql/RestAqlHandler.cpp
- arangod/Aql/ShortestPathBlock.cpp
- arangod/Aql/SubqueryBlock.cpp
- arangod/Aql/TraversalBlock.cpp
Improvements from the probably obsolete push-limits-branch.
> Improve error handling and tracing of getSome

- cmake/packages/client/nsis.txt
> build client path the same way in the client package as in the server package

- js/common/tests/http/grants-spec.js
> add wait to test

- arangod/RocksDBEngine/RocksDBEngine.cpp
> ensure proper shutdown of throttle

- cmake/packages/client/nsis.txt
> build client path the same way in the client package as in the server package.

- 3rdParty/velocypack/include/velocypack/Builder.h
- 3rdParty/velocypack/src/Builder.cpp
- arangod/Cluster/ClusterComm.cpp
- arangod/RocksDBEngine/RocksDBEngine.cpp
- lib/Basics/NumberUtils.h
Fixes several warnings and errors reported by MSVC
> Bug fix/msvc fixes

- CHANGELOG
- arangod/Aql/ClusterBlocks.cpp
- arangod/Aql/SortBlock.cpp
- js/server/tests/aql/aql-failures-noncluster.js
> fix memory hunger of cache

- arangod/Aql/QueryRegistry.cpp
- arangod/Aql/QueryRegistry.h
created PR: https://github.com/arangodb/arangodb/pull/4240 for 3.2 branch
> Feature 3.2/small optimizations for query registry

- lib/Rest/VstMessage.h
https://github.com/arangodb/arangodb/issues/4284
> fix issue #4284 - exception in scheduler loop

- arangod/Aql/DocumentProducingBlock.cpp
unfolded a few runtime if branches, so we now have a bit more code (bad) but slightly better runtime performance (good)
> unfold code to remove a few runtime ifs

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
original issue: https://github.com/arangodb/arangodb/issues/4217
> Bug fix 3.2/ui query parameter issue 4217

- arangod/MMFiles/MMFilesWalAccess.cpp
- arangod/RocksDBEngine/RocksDBReplicationTailing.cpp
- arangod/RocksDBEngine/RocksDBWalAccess.cpp
Did previously throw exceptions in mmfiles
> Adding view rename case to replication handlers

- cmake/packages/bundle.cmake
> with the new swagger increasing in size, and the advent of iresearch increasing by 20 MB.

- CHANGELOG
- arangod/Cluster/ClusterInfo.h
- arangod/Cluster/ShardDistributionReporter.cpp
- arangod/Cluster/ShardDistributionReporter.h
- arangod/Cluster/v8-cluster.cpp
- js/actions/api-cluster.js
- js/apps/system/_admin/aardvark/APP/frontend/js/templates/shardsView.ejs
- js/apps/system/_admin/aardvark/APP/frontend/js/views/nodesView.js
- js/apps/system/_admin/aardvark/APP/frontend/js/views/shardsView.js
- js/apps/system/_admin/aardvark/APP/frontend/scss/_shards.scss
- js/server/bootstrap/modules/internal.js
- js/server/modules/@arangodb/cluster.js
- tests/Cluster/ShardDistributionReporterTest.cpp
optimized shard distribution api and ui.
those changes are already approved and included in the development branch.
> optimized shard distribution api and ui

- CHANGELOG
- arangod/V8Server/v8-users.cpp
> Bug fix 3.3/issue 4222

- CHANGELOG
- arangod/V8Server/v8-users.cpp
auth. test went through. ui works correctly.
> Bug fix 3.2/issue 4222

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/arango/arango.js
- js/apps/system/_admin/aardvark/APP/frontend/js/views/documentsView.js
> Bug fix 3.2/issue 1683

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/arango/arango.js
- js/apps/system/_admin/aardvark/APP/frontend/js/views/documentsView.js
> Bug fix 3.3/issue 1683

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
> Bug fix 3.2/issue 1684

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
> Bug fix 3.3/issue 1684

- CHANGELOG
- lib/V8/v8-helper.h
> fixed issue #4308: Crash when getter for error.name throws an error

- 3rdParty/CMakeLists.txt
- 3rdParty/iresearch/CMakeLists.txt
- 3rdParty/iresearch/core/CMakeLists.txt
- arangod/IResearch/AqlHelper.cpp
> fix `centos` build issue

- Documentation/Books/AQL/Views/IResearch.md
- arangod/IResearch/IResearchAnalyzerFeature.cpp
- arangod/IResearch/IResearchDocument.cpp
- arangod/IResearch/IResearchDocument.h
- arangod/IResearch/IResearchLinkMeta.cpp
- arangod/IResearch/IResearchLinkMeta.h
- js/server/tests/aql/aql-view-iresearch-ddl.js
- js/server/tests/aql/aql-view-iresearch.js
- tests/IResearch/IResearchDocument-test.cpp
- tests/IResearch/IResearchIndex-test.cpp
- tests/IResearch/IResearchLinkMeta-test.cpp
- tests/IResearch/IResearchQueryAnd-test.cpp
- tests/IResearch/IResearchQueryComplexBoolean-test.cpp
- tests/IResearch/IResearchQueryJoin-test.cpp
- tests/IResearch/IResearchQueryOr-test.cpp
- tests/IResearch/IResearchQueryPhrase-test.cpp
- tests/IResearch/VelocyPackHelper-test.cpp
> standardize on the 'analyzer' and 'trackListPositions' naming

- arangod/VocBase/AuthInfo.cpp
Fixes database-level permission revocation (back to "use default") in cluster
> fix revoke operation

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
fixed internal issue https://github.com/arangodb/planning/issues/81
> Bug fix 3.2/quotation marks query editor

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
fixed internal issue https://github.com/arangodb/planning/issues/81
> Bug fix 3.3/quotation marks query editor

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
fixed internal issue https://github.com/arangodb/planning/issues/81
> Bug fix/quotation marks query editor

- Installation/CI/linux/nightly-docker.sh
> added build script for nightly docker images

- Installation/Pipeline/build_OS_EDITION_MAINTAINER.sh
- etc/jenkins/arangosh.conf
- fix the output logging of arangosh here too
- don't bail out if we fail to delete the libarangoserver
> Bug fix/jenkins

- Documentation/DocuBlocks/Rest/Collections/JSF_post_api_collection.md
> distributeShardsLike documented for /_api/collection

- js/actions/_admin/foxx/app.js
> Fix legacy Foxx HTTP API compat layer (#4265)

- js/actions/_admin/foxx/app.js
- js/apps/system/_admin/aardvark/APP/foxxes.js
- js/server/modules/@arangodb/foxx/manager.js
This adds the fix from #4450 for store names as well.
>  Fix legacy Foxx HTTP API compat layer (#4265) Part 2

- js/apps/system/_api/foxx/APP/index.js
- js/server/modules/@arangodb/foxx/service.js
>  More consistent config/deps output in Foxx API (3.3)

- js/actions/_admin/foxx/app.js
- js/apps/system/_admin/aardvark/APP/foxxes.js
- js/server/modules/@arangodb/foxx/manager.js
This adds the fix from #4451 for store names as well.
> Fix legacy Foxx HTTP API compat layer (#4265) Part 2

- 3rdParty/iresearch/external/snowball/CMakeLists.txt
- Installation/Pipeline/Jenkinsfile.groovy
- Installation/Pipeline/Jenkinsfile.groovy.in
- configure/windows_common.ps1
- js/server/tests/resilience/shard-distribution-spec.js
> Bug fix/fix windows jenkins

- js/common/test-data/apps/service-with-app-folder/app/index.js
- js/common/test-data/apps/service-with-app-folder/assets/app/index.js
- js/common/test-data/apps/service-with-app-folder/manifest.json
- js/server/modules/@arangodb/foxx/manager.js
- js/server/tests/shell/shell-foxx-cleanup-spec.js
> Don't greedily delete legit app folders (#4395)

- Documentation/DocuBlocks/Rest/Foxx/api_foxx_configuration_replace.md
- Documentation/DocuBlocks/Rest/Foxx/api_foxx_configuration_update.md
- Documentation/DocuBlocks/Rest/Foxx/api_foxx_dependencies_replace.md
- Documentation/DocuBlocks/Rest/Foxx/api_foxx_dependencies_update.md
- Documentation/DocuBlocks/Rest/Foxx/api_foxx_service_install.md
- Documentation/DocuBlocks/Rest/Foxx/api_foxx_service_list.md
- Documentation/DocuBlocks/Rest/Foxx/api_foxx_service_replace.md
- Documentation/DocuBlocks/Rest/Foxx/api_foxx_service_upgrade.md
- js/apps/system/_api/foxx/APP/index.js
- js/client/tests/shell/shell-foxx-api-spec.js
- js/common/test-data/apps/echo-script/echo.js
- js/common/test-data/apps/echo-script/manifest.json
- js/common/test-data/apps/itzpapalotl/itzpapalotl.js
- js/common/test-data/apps/itzpapalotl/manifest.json
- js/common/test-data/apps/minimal-working-setup-teardown/controller.js
- js/common/test-data/apps/minimal-working-setup-teardown/index.js
- js/common/test-data/apps/minimal-working-setup-teardown/manifest.json
- js/common/test-data/apps/minimal-working-setup-teardown/setup.js
- js/common/test-data/apps/minimal-working-setup-teardown/teardown.js
- js/common/test-data/apps/service-service/index.js
- js/common/test-data/apps/with-configuration/manifest.json
- js/common/test-data/apps/with-dependencies/manifest.json
- js/common/test-data/apps/with-tests/manifest.json
- js/common/test-data/apps/with-tests/test1.js
- js/common/test-data/apps/with-tests/test2.js
- js/server/modules/@arangodb/foxx/manager.js
- js/server/modules/@arangodb/foxx/service.js
* configuration
* dependencies
> Bugfix Foxx API tests

- CHANGELOG
- arangod/V8Server/V8DealerFeature.cpp
> Create javascript.app-path if it does not exist

- arangod/V8Server/v8-vocindex.cpp
> Add getIndexes() to completion in arangod-console

- arangod/V8Server/V8Context.cpp
- arangod/V8Server/V8Context.h
- arangod/V8Server/V8DealerFeature.cpp
- arangod/V8Server/V8DealerFeature.h
- arangod/VocBase/Methods/AqlUserFunctions.cpp
> Add V8ContextDealerGuard to provide safe access to isolate

- CHANGELOG
- arangod/Aql/Ast.cpp
- js/server/tests/aql/aql-queries-optimizer.js
AQL optimizer was trying to resolve attribute accesses
to attributes of constant object values at query compile time, but only did so far
the very first attribute in each object
this fixes https://stackoverflow.com/questions/48648737/beginner-bug-in-for-loops-from-objects
> fix internal issue #1848

- CHANGELOG
- Documentation/Books/Manual/Administration/Configuration/GeneralArangod.md
- arangod/RestServer/UpgradeFeature.cpp
Backport of PR #4534, fixing issue #4160
> Issue #4160: Clearer log messages during upgrade

- Documentation/Scripts/fetchRefs.sh
- README_maintainers.md
Include Willi's script to synchronize doc from external repos into our official doc
> Doc - sync script

- js/apps/system/_admin/aardvark/APP/frontend/js/views/navigationView.js
Issue https://github.com/arangodb/arangodb/issues/4508
> removed not needed menu entry for cluster logs

- arangod/Cluster/ClusterMethods.cpp
> Translate the distirbuteLike collection of SmartEdges as well.

- js/server/tests/resilience/shard-distribution-spec.js
> Fixes jslint for tests

- arangod/MMFiles/MMFilesRestReplicationHandler.cpp
- arangod/MMFiles/MMFilesWalAccess.cpp
- arangod/MMFiles/mmfiles-replication-dump.cpp
- arangod/MMFiles/mmfiles-replication-dump.h
- arangod/Replication/GlobalInitialSyncer.cpp
- arangod/Replication/GlobalInitialSyncer.h
- arangod/Replication/Syncer.cpp
- arangod/Replication/TailingSyncer.cpp
- arangod/Replication/TailingSyncer.h
- arangod/RestHandler/RestWalAccessHandler.cpp
- arangod/RestServer/DatabaseFeature.cpp
- arangod/RestServer/DatabaseFeature.h
- arangod/RocksDBEngine/RocksDBBackgroundThread.cpp
- arangod/RocksDBEngine/RocksDBIncrementalSync.cpp
- arangod/RocksDBEngine/RocksDBReplicationCommon.cpp
- arangod/RocksDBEngine/RocksDBReplicationCommon.h
- arangod/RocksDBEngine/RocksDBReplicationManager.cpp
- arangod/RocksDBEngine/RocksDBReplicationTailing.cpp
- arangod/RocksDBEngine/RocksDBRestReplicationHandler.cpp
- arangod/RocksDBEngine/RocksDBWalAccess.cpp
- arangod/StorageEngine/WalAccess.h
- arangod/VocBase/vocbase.cpp
- lib/Basics/StaticStrings.cpp
- lib/Basics/StaticStrings.h
> forward port of replication bugfixes from 3.2

- Documentation/Books/Manual/Administration/DC2DC/README.md
- Documentation/Books/Manual/Deployment/DC2DC.md
- Documentation/Books/Manual/Deployment/DC2DC/ArangoSyncMaster.md
- Documentation/Books/Manual/Deployment/DC2DC/ArangoSyncWorkers.md
- Documentation/Books/Manual/Deployment/DC2DC/Cluster.md
- Documentation/Books/Manual/Deployment/DC2DC/KafkaZookeeper.md
- Documentation/Books/Manual/Deployment/DC2DC/PrometheusGrafana.md
- Documentation/Books/Manual/GettingStarted/DC2DC/README.md
- Documentation/Books/Manual/Monitoring/DC2DC/README.md
- Documentation/Books/Manual/SUMMARY.md
- Documentation/Books/Manual/Scalability/DC2DC/Applicability.md
- Documentation/Books/Manual/Scalability/DC2DC/Introduction.md
- Documentation/Books/Manual/Scalability/DC2DC/README.md
- Documentation/Books/Manual/Scalability/DC2DC/Requirements.md
- Documentation/Books/Manual/Security/DC2DC/README.md
- Documentation/Books/Manual/Troubleshooting/DC2DC/README.md
> Doc - ArangoSync doc integration

- Documentation/Books/AQL/Functions/String.md
- arangod/Aql/AqlFunctionFeature.cpp
- arangod/Aql/Functions.cpp
- arangod/Aql/Functions.h
- js/server/tests/aql/aql-functions-string.js
- lib/ApplicationFeatures/LanguageFeature.cpp
- lib/ApplicationFeatures/LanguageFeature.h
- Initialize ICU::Lang in the language feature
- Implement C++ version using ICU.
- add V8/C++ tests, add more tests comparing extreme values
- document the behaviour on extreme values.
> Implement FIND_FIRST and FIND_LAST in c++

- arangod/RocksDBEngine/RocksDBReplicationTailing.cpp
- arangod/RocksDBEngine/RocksDBWalAccess.cpp
- js/client/modules/@arangodb/testsuites/replication.js
- js/server/tests/replication/replication-fuzz-global.js
- js/server/tests/replication/replication-fuzz.js
- js/server/upgrade-database.js
> Bug fix 3.3/handle single delete

- arangod/RocksDBEngine/RocksDBReplicationTailing.cpp
- arangod/RocksDBEngine/RocksDBWalAccess.cpp
- js/client/modules/@arangodb/testsuites/replication.js
- js/server/tests/replication/replication-fuzz-global.js
- js/server/tests/replication/replication-fuzz.js
- js/server/upgrade-database.js
forward port bugfixes from 3.2
> Bug fix/handle single delete

- CHANGELOG
- Documentation/DocuBlocks/Rest/Foxx/api_foxx_service_replace.md
- js/apps/system/_api/foxx/APP/index.js
- js/client/tests/shell/shell-foxx-api-spec.js
- js/server/modules/@arangodb/foxx/manager.js
* PUT /_api/foxx/service: Respect force flag
* PATCH /_api/foxx/service: Check whether a service under given mount exists
> Fix Foxx API (3.3)

- CHANGELOG
- Documentation/DocuBlocks/Rest/Foxx/api_foxx_service_replace.md
- js/apps/system/_api/foxx/APP/index.js
- js/client/tests/shell/shell-foxx-api-spec.js
- js/server/modules/@arangodb/foxx/manager.js
* PUT /_api/foxx/service: Respect force flag
* PATCH /_api/foxx/service: Check whether a service under given mount exists
> Fix Foxx API (3.2)

- js/apps/system/_admin/aardvark/APP/frontend/js/views/clusterView.js
https://github.com/arangodb/planning/issues/1762
> ui dashboard http correct label

- etc/arangodb3/arangod.conf.in
> fix documentation link as pointed out in #4632

- arangod/Cache/Metadata.cpp
Internal Ref: https://github.com/arangodb/planning/issues/1923
> Fix a small logic issue in cache resize metadata method.

- arangod/RocksDBEngine/RocksDBTransactionCollection.cpp
- arangod/VocBase/Methods/Transactions.cpp
- lib/V8/v8-vpack.cpp
- lib/V8/v8-vpack.h
previously this did not work when the "action" attribute was a JavaScript function
> properly convert the JS object to VPack for transactions

- arangod/RocksDBEngine/RocksDBCollection.cpp
> Remove invalid assertions

- Installation/debian/prerm.in
backport https://github.com/arangodb/arangodb/pull/4673
> fix debian prerm script

- CHANGELOG
- arangod/Aql/ExecutionEngine.cpp
- arangod/Aql/OptimizerRules.cpp
- js/server/tests/aql/aql-multi-modify.js
Should fix issue #4651 
Some cluster optimization rules created a wrong execution plan, which could even lead to crashes in some cases.
> fixed issue #4651

- arangod/MMFiles/MMFilesRestReplicationHandler.cpp
- arangod/RocksDBEngine/RocksDBRestReplicationHandler.cpp
- arangod/Utils/ExecContext.h
- arangod/VocBase/vocbase.cpp
- don't load collections if we're not allowed to read from them
- don't list collections for dump if we're not allowed to read from them
> fix dumping permission checks;

- CHANGELOG
> Documentation 3.3/changelog fix

- js/apps/system/_admin/aardvark/APP/frontend/js/arango/arango.js
> fix UI in non-authenticated mode

- Documentation/Books/Manual/Administration/Configuration/Ldap.md
> Improve the description of --ldap.tls-version

- arangod/Aql/ClusterNodes.cpp
- arangod/Aql/ClusterNodes.h
- arangod/Aql/CollectNode.cpp
- arangod/Aql/CollectNode.h
- arangod/Aql/ExecutionEngine.cpp
- arangod/Aql/ExecutionEngine.h
- arangod/Aql/ExecutionNode.cpp
- arangod/Aql/ExecutionNode.h
- arangod/Aql/IndexNode.cpp
- arangod/Aql/IndexNode.h
- arangod/Aql/ModificationNodes.cpp
- arangod/Aql/ModificationNodes.h
- arangod/Aql/ShortestPathNode.cpp
- arangod/Aql/ShortestPathNode.h
- arangod/Aql/SortNode.cpp
- arangod/Aql/SortNode.h
- arangod/Aql/TraversalNode.cpp
- arangod/Aql/TraversalNode.h
- arangod/IResearch/IResearchViewNode.cpp
- arangod/IResearch/IResearchViewNode.h
> Factory method for execution block

- CHANGELOG
- arangod/Agency/Job.cpp
Reverts arangodb/arangodb#4665
Does not compile
> Revert "bug fix for jobs looking at distrubuteShardsLike and virtual collections"

- js/apps/system/_admin/aardvark/APP/frontend/js/views/installUploadServiceView.js
> fixed wrong detection of file types

- js/common/bootstrap/errors.js
- lib/Basics/errors.dat
- lib/Basics/voc-errors.cpp
- lib/Basics/voc-errors.h
- lib/SimpleHttpClient/SimpleHttpClient.cpp
- lib/V8/v8-utils.cpp
> Fixed false http error codes in timeout case. Also reactivated retry in error case. (#4760)

- utils/generateExamples.py
allow aql docublock examples without a dataset
> devel: Bug fix/docublock example generation

- arangod/Aql/RegexCache.cpp
- arangod/Aql/RegexCache.h
- arangod/VocBase/Methods/Upgrade.cpp
- arangod/VocBase/Methods/Version.cpp
- lib/SimpleHttpClient/SimpleHttpClient.cpp
> Bug fix/fix mac wincompile

- Documentation/DocuBlocks/Rest/Simple Queries/put_api_simple_all.md
- arangod/RestHandler/RestSimpleQueryHandler.cpp
- arangosh/Export/ExportFeature.cpp
- js/client/modules/@arangodb/simple-query.js
> Using stream cursor in arangoexport and arangosh

- Documentation/Books/Manual/Administration/Configuration/Ldap.md
> Fix spelling, improve anchor links

- Documentation/Books/AQL/Functions/Geo.md
- arangod/Aql/AqlFunctionFeature.cpp
- arangod/Aql/AqlFunctionFeature.h
- arangod/Aql/Functions.cpp
- arangod/Aql/Functions.h
- tests/CMakeLists.txt
- tests/Geo/GeoConstructorTest.cpp
merge geo constructors, including: 
- tests
- docu
> S2 index constructor

- Documentation/Examples/GRAPHTRAV_07_traverse_8.generated
> Doc - Explain colour - 2nd part

- arangod/VocBase/vocbase.cpp
> add nullptr check

- Documentation/DocuBlocks/Rest/AQL/JSF_delete_api_aqlfunction.md
- Documentation/DocuBlocks/Rest/Administration/JSF_get_admin_database_version.md
- Documentation/DocuBlocks/Rest/Administration/JSF_get_admin_routing_reloads.md
- Documentation/DocuBlocks/Rest/Administration/JSF_get_admin_server_role.md
- Documentation/DocuBlocks/Rest/Administration/JSF_get_admin_statistics.md
- Documentation/DocuBlocks/Rest/Administration/JSF_get_admin_statistics_description.md
- Documentation/DocuBlocks/Rest/Administration/JSF_get_admin_time.md
- Documentation/DocuBlocks/Rest/Administration/JSF_get_api_cluster_endpoints.md
- Documentation/DocuBlocks/Rest/Administration/JSF_post_admin_execute.md
- Documentation/DocuBlocks/Rest/Cluster/JSF_cluster_check_port_GET.md
- Documentation/DocuBlocks/Rest/Cluster/JSF_cluster_statistics_GET.md
- Documentation/DocuBlocks/Rest/Cluster/JSF_cluster_test_GET.md
- Documentation/DocuBlocks/Rest/Cursors/JSF_post_api_cursor_identifier.md
- Documentation/DocuBlocks/Rest/Indexes/JSF_get_api_index.md
- Documentation/DocuBlocks/Rest/Indexes/JSF_get_api_reads_index.md
- Documentation/DocuBlocks/Rest/Indexes/JSF_post_api_index_delete.md
- Documentation/DocuBlocks/Rest/Simple Queries/JSA_put_api_simple_all.md
- Documentation/DocuBlocks/Rest/Simple Queries/JSA_put_api_simple_any.md
- Documentation/DocuBlocks/Rest/User Management/README.md
- Documentation/DocuBlocks/Rest/wal/JSF_get_admin_wal_properties.md
- Documentation/DocuBlocks/Rest/wal/JSF_get_admin_wal_transactions.md
- Documentation/DocuBlocks/Rest/wal/JSF_put_admin_wal_flush.md
- Documentation/DocuBlocks/Rest/wal/JSF_put_admin_wal_properties.md
removed newline after `@RESTDESCRIPTION`
> 3.3: Doc - removed newline after restdescription

- tests/Aql/EngineInfoContainerCoordinatorTest.cpp
> Removed fakeit namespace. Kills windows

- arangod/Aql/Condition.cpp
- js/server/tests/aql/aql-queries-array.js
> fixed issue #4900

- CHANGELOG
- arangod/Agency/RemoveFollower.cpp
- tests/Agency/RemoveFollowerTest.cpp
- tests/Agency/RemoveFollowerTestLarge.json
> Bugfix / Supervision: removeFollower should remove the last follower(s) first

- tests/Aql/EngineInfoContainerCoordinatorTest.cpp
- tests/Aql/RestAqlHandlerTest.cpp
> Deactivated tests that mocked destructors. Does not seem to work with any optimization build and made jenkins red

- CHANGELOG
- arangod/Agency/Job.cpp
> bug fix for jobs looking at distrubuteShardsLike and virtual collections

- arangod/IResearch/IResearchLink.cpp
- arangod/IResearch/IResearchLink.h
- arangod/IResearch/IResearchRocksDBRecoveryHelper.cpp
> issue 348.2: hold view lock directly instead of via an Ayncself pointer

- README_maintainers.md
- arangod/Aql/Functions.cpp
- lib/Basics/datetime.cpp
> Bug fix/date function portability

- Documentation/Books/Manual/GettingStarted/ComingFromSql.md
- Documentation/Books/Manual/GettingStarted/README.md
- Documentation/Books/Manual/README.md
- Documentation/Books/Manual/SUMMARY.md
- Documentation/Books/Manual/Scalability/Architecture.md
May use this to backport further documentation fixes.
> Doc - Fix typos (#4553)

- Documentation/Books/Manual/GettingStarted/ComingFromSql.md
- Documentation/Books/Manual/GettingStarted/README.md
- Documentation/Books/Manual/Graphs/README.md
- Documentation/Books/Manual/README.md
- Documentation/Books/Manual/ReleaseNotes/KnownIssues32.md
- Documentation/Books/Manual/ReleaseNotes/NewFeatures24.md
- Documentation/Books/Manual/ReleaseNotes/NewFeatures26.md
- Documentation/Books/Manual/ReleaseNotes/UpgradingChanges27.md
- Documentation/Books/Manual/ReleaseNotes/UpgradingChanges30.md
- Documentation/Books/Manual/SUMMARY.md
- Documentation/Books/Manual/Scalability/Architecture.md
> Doc - Fix typos

- utils/generateSwagger.py
https://lgtm.com/projects/g/arangodb/arangodb/alerts/?mode=list
> Doc - fix lgtm.com alerts

- arangod/MMFiles/MMFilesEngine.cpp
- arangod/RocksDBEngine/RocksDBEngine.cpp
- arangod/VocBase/vocbase.cpp
> remove code duplication

- CHANGELOG
- arangod/Auth/TokenCache.cpp
- arangod/GeneralServer/AuthenticationFeature.cpp
- arangosh/Benchmark/arangobench.cpp
- arangosh/Dump/arangodump.cpp
- arangosh/Export/arangoexport.cpp
- arangosh/Import/arangoimp.cpp
- arangosh/Restore/arangorestore.cpp
- arangosh/Shell/ClientFeature.cpp
- arangosh/Shell/ClientFeature.h
- arangosh/Shell/V8ClientConnection.cpp
- arangosh/Shell/V8ClientConnection.h
- arangosh/Shell/V8ShellFeature.cpp
- arangosh/Shell/arangosh.cpp
- lib/SimpleHttpClient/SimpleHttpClient.cpp
- lib/SimpleHttpClient/SimpleHttpClient.h
> added --server.ask-jwt-secret to arangosh

- CHANGELOG
- Documentation/Books/HTTP/MiscellaneousFunctions/README.md
- Documentation/DocuBlocks/Rest/Administration/JSF_get_admin_status.md
- arangod/CMakeLists.txt
- arangod/GeneralServer/GeneralServerFeature.cpp
- arangod/GeneralServer/RestHandlerFactory.cpp
- arangod/RestHandler/RestStatusHandler.cpp
- arangod/RestHandler/RestStatusHandler.h
- arangod/RestHandler/RestVersionHandler.cpp
devel version of feature-3.3/admin-status
> added /_admin/status

- Documentation/DocuBlocks/Rest/Administration/get_admin_server_id.md
> Doc - Issue #4868

- CHANGELOG
- arangod/Agency/FailedLeader.cpp
- Internal Ref: https://github.com/arangodb/planning/issues/2215
> internal issue #2215

- CHANGELOG
- arangod/Agency/FailedLeader.cpp
- Internal ref: https://github.com/arangodb/planning/issues/2215
> fix internal issue #2215's todo timeout on failed leader job

- CHANGELOG
- arangod/Agency/Agent.cpp
- arangod/Agency/Agent.h
- arangod/Agency/Supervision.cpp
major fix for internal issue https://github.com/arangodb/planning/issues/2215
> Bug fix/supervision engine starting early on leadership change

- CHANGELOG
- arangod/Agency/Agent.cpp
- arangod/Agency/Agent.h
- arangod/Agency/Supervision.cpp
> supervision fix for internal issue #2215 backport to 3.3

- CHANGELOG
- arangod/Agency/Agent.cpp
- arangod/Agency/Agent.h
- arangod/Agency/Supervision.cpp
> 3.2 backport of supervision starting early after leadership change

- Documentation/Books/AQL/Operations/Collect.md
- Documentation/Books/AQL/Operations/Insert.md
- Documentation/Books/AQL/Operations/Update.md
> fix Issue 4778

- arangod/Aql/ExecutionEngine.cpp
- arangod/Aql/QueryRegistry.h
- arangod/Aql/RestAqlHandler.cpp
- arangod/RestServer/QueryRegistryFeature.cpp
- arangod/RestServer/QueryRegistryFeature.h
- tests/Auth/UserManagerTest.cpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/253/
> Adding ttl option for the query registry

- arangod/Agency/Node.cpp
> Bug fix/node smapping logs

- arangod/MMFiles/MMFilesPrimaryIndex.cpp
- arangod/RocksDBEngine/RocksDBPrimaryIndex.cpp
- arangod/Transaction/Methods.cpp
- arangod/Transaction/Methods.h
- arangod/Utils/CollectionNameResolver.cpp
- arangod/Utils/CollectionNameResolver.h
There is also a corresponding PR in enterprise repository.
> fix lookups by _id

- CHANGELOG
- arangod/MMFiles/MMFilesPrimaryIndex.cpp
- arangod/RocksDBEngine/RocksDBPrimaryIndex.cpp
- arangod/Transaction/Methods.cpp
- arangod/Transaction/Methods.h
- arangod/Utils/CollectionNameResolver.cpp
- arangod/Utils/CollectionNameResolver.h
there is also a connected PR in the enterprise repository
> fix lookups by _id for smart graph edges

- CHANGELOG
- arangod/RestHandler/RestCollectionHandler.cpp
- arangod/RestHandler/RestReplicationHandler.cpp
- arangod/V8Server/v8-collection.cpp
- arangod/VocBase/Methods/Collections.cpp
- arangod/VocBase/Methods/Collections.h
This has an enterprise part with identical name
> Bug fix 3.3/drop smart collection restore

- arangod/CMakeLists.txt
- arangod/IResearch/IResearchFeature.cpp
- arangod/IResearch/IResearchLink.cpp
- arangod/IResearch/IResearchLink.h
- arangod/IResearch/IResearchViewDBServer.cpp
- arangod/IResearch/IResearchViewDBServer.h
- arangod/VocBase/LogicalView.cpp
- tests/CMakeLists.txt
- tests/IResearch/AgencyCommManagerMock.cpp
- tests/IResearch/AgencyCommManagerMock.h
- tests/IResearch/IResearchViewDBServer-test.cpp
> issue 383.1: initial stub implementation of IResearchViewDBServer

- lib/Basics/process-utils.cpp
> if the process to spawn doesn't contain a path, do a lookup in the host path of it

- arangosh/Dump/DumpFeature.cpp
- arangosh/Utils/ManagedDirectory.cpp
> Fix warnings on Windows related to parallelized arangodump

- 3rdParty/CMakeLists.txt
- 3rdParty/boost/CMakeLists.txt
- CMakeLists.txt
> reduces warnings during build

- Documentation/Scripts/generateMdFiles.py
- utils/generateSwagger.py
> 3.1: Documentation 3.1/fix restdescription cutout

- CHANGELOG
- js/common/bootstrap/modules.js
- js/common/tests/shell/shell-locals-spec.js
> Add @arangodb/locals module (3.2)

- Documentation/Scripts/generateMdFiles.py
- utils/generateSwagger.py
> fix the condition when blocks end, so we can pick blocks with empty lines in them

- Documentation/Books/build.sh
> fix documentation build script

- README.md
Backport of https://github.com/arangodb/arangodb/commit/03fe0fdcb44e0cd8c6d58dc21866906373528a11
> remove travis as compiling takes too long

- Documentation/Books/Drivers/Java/Reference/README.md
- Documentation/Books/Drivers/SpringData/Reference/README.md
- Documentation/Books/Manual/Deployment/Kubernetes/DeploymentResource.md
- Documentation/Books/Manual/Deployment/Kubernetes/ServicesAndLoadBalancer.md
- Documentation/Books/Manual/Programs/Starter/Options.md
- Documentation/Books/Manual/Tutorials/Kubernetes/README.md
Simple update from external repos
> Doc - Updates from external repos

- Documentation/Books/Manual/Appendix/JavaScriptModules/ArangoDB.md
> Warn about passing user input to aql.literal()

- Documentation/Books/AQL/ExecutionAndPerformance/ExplainingQueries.md
- Documentation/DocuBlocks/Rest/Cursors/post_api_cursor.md
- Documentation/Examples/01_workWithAQL_databaseExplain.generated
- Documentation/Examples/01_workWithAQL_databaseProfileQuery.generated
- Documentation/Examples/RestCursorProfileQuery.generated
- js/common/modules/@arangodb/aql/explainer.js
- js/common/tests/shell/shell-statement.js
Had to move that code below the recursiveWalk function
> Fixing subqueries in aql profiler

- arangod/RestServer/LockfileFeature.cpp
- lib/Basics/CleanupFunctions.cpp
- lib/Basics/CleanupFunctions.h
- lib/Basics/Common.h
- lib/CMakeLists.txt
- lib/Logger/Logger.h
Added cleanup functions class that allows to execute functions on unexpected shutdown (like FATAL_EXIT). First use: delete the LOCK file.
> Added error cleanup functions

- Documentation/Books/Cookbook/Monitoring/Collectd.md
Changing this receipe to use the general admin/statistics call.
> as @kwando pointed out, we removed the aardvark statistics endpoint;

- arangod/Aql/AqlFunctionFeature.cpp
- arangod/Aql/Functions.cpp
- arangod/Aql/Functions.h
- js/server/tests/aql/aql-functions.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/366/
> add native implementation of the FAIL aql function

- lib/Basics/errors.dat
> missing entry for error 1498 in dat file

- arangod/Aql/EngineInfoContainerCoordinator.cpp
> fix undefined macro expansion

- CHANGELOG
- arangod/Aql/RegexCache.cpp
- js/server/tests/aql/aql-functions-string.js
> Fix AQL LIKE function - escapes * when building pattern.

- Documentation/Books/Manual/Administration/Arangoimport.md
This is a continuation of the previous bug-fix/mv-import-progress branch.  Some suggested edits to the manual did not get added before the first branch merged.
> apply edits suggested by Willi

- arangod/Aql/ExecutionNode.h
> fix invalid enum value

- arangod/Aql/OptimizerRules.cpp
> fix valgrind issues

- arangod/Cluster/ClusterRepairDistributeShardsLike.cpp
- arangod/Cluster/ClusterRepairOperations.cpp
- arangod/Cluster/ClusterRepairOperations.h
- arangod/RestHandler/RestRepairHandler.cpp
Fixes compile error on MacOs, stupid size_t ...
> Bug fix/compile issues on mac

- 3rdParty/velocypack/src/Dumper.cpp
- arangod/GeneralServer/VstCommTask.cpp
- arangod/GeneralServer/VstCommTask.h
- arangod/MMFiles/MMFilesRestReplicationHandler.cpp
- arangod/Replication/DatabaseInitialSyncer.cpp
- arangod/Replication/DatabaseInitialSyncer.h
- arangod/Replication/Syncer.cpp
- arangod/Replication/Syncer.h
- arangod/Replication/TailingSyncer.cpp
- arangod/RestHandler/RestBaseHandler.cpp
- arangod/RestHandler/RestBaseHandler.h
- arangod/RocksDBEngine/RocksDBIterators.h
- arangod/RocksDBEngine/RocksDBReplicationContext.cpp
- arangod/RocksDBEngine/RocksDBReplicationContext.h
- arangod/RocksDBEngine/RocksDBRestReplicationHandler.cpp
- arangod/VocBase/Methods/Indexes.cpp
- lib/Basics/VelocyPackHelper.cpp
- lib/Basics/VelocyPackHelper.h
- lib/Rest/GeneralResponse.cpp
- lib/Rest/GeneralResponse.h
- lib/Rest/HttpRequest.cpp
- lib/Rest/HttpResponse.cpp
- lib/Rest/VstRequest.cpp
- lib/Rest/VstResponse.cpp
Same as https://github.com/arangodb/arangodb/pull/5274
> Simple dump speedup

- arangod/Aql/ConditionFinder.cpp
- arangod/Aql/ExecutionNode.cpp
- arangod/Aql/ExecutionNode.h
- arangod/Aql/ExecutionPlan.cpp
- arangod/Aql/ExecutionPlan.h
- arangod/Aql/OptimizerRules.cpp
- arangod/Aql/TraversalConditionFinder.cpp
> refactor execution node type enum to be less error prone

- CHANGELOG
- arangod/V8Server/V8DealerFeature.cpp
> run V8 garbage collection less often than before

- arangod/Aql/BasicBlocks.h
- arangod/Aql/EngineInfoContainerCoordinator.cpp
- arangod/IResearch/IResearchLink.cpp
- arangod/IResearch/IResearchViewDBServer.cpp
- arangod/IResearch/IResearchViewNode.cpp
- arangod/IResearch/IResearchViewOptimizerRules.cpp
- arangod/VocBase/LogicalView.h
- lib/Meta/utility.h
- tests/IResearch/IResearchViewCoordinator-test.cpp
- tests/IResearch/IResearchViewNode-test.cpp
> do not scatter empty view

- js/client/tests/shell/shell-foxx-manager-spec.js
- js/common/test-data/apps/heal-during-setup/index.js
- js/common/test-data/apps/heal-during-setup/manifest.json
- js/common/test-data/apps/heal-during-setup/setup.js
- js/server/modules/@arangodb/foxx/manager.js
- js/server/modules/@arangodb/foxx/service.js
> [3.3] Fix race condition between foxx install and selfHeal

- arangod/Aql/BasicBlocks.cpp
- arangod/Aql/CalculationBlock.cpp
- arangod/Aql/ClusterBlocks.cpp
- arangod/Aql/ClusterNodes.h
- arangod/Aql/CollectBlock.cpp
- arangod/Aql/CollectNode.cpp
- arangod/Aql/Condition.cpp
- arangod/Aql/ConditionFinder.cpp
- arangod/Aql/EngineInfoContainerDBServer.cpp
- arangod/Aql/ExecutionEngine.cpp
- arangod/Aql/ExecutionNode.cpp
- arangod/Aql/ExecutionNode.h
- arangod/Aql/ExecutionPlan.cpp
- arangod/Aql/IndexBlock.cpp
- arangod/Aql/IndexNode.cpp
- arangod/Aql/ModificationBlocks.cpp
- arangod/Aql/ModificationNodes.cpp
- arangod/Aql/OptimizerRules.cpp
- arangod/Aql/ShortestPathNode.cpp
- arangod/Aql/SortCondition.cpp
- arangod/Aql/SortNode.cpp
- arangod/Aql/SortNode.h
- arangod/Aql/TraversalConditionFinder.cpp
- arangod/Aql/TraversalNode.cpp
> safer casts for ExecutionNode types

- arangod/Aql/ExecutionNode.h
- arangod/RocksDBEngine/RocksDBCommon.cpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/465/
> Compiler error on osx

- arangod/Agency/AgencyComm.cpp
- arangod/Cluster/HeartbeatThread.cpp
Same as https://github.com/arangodb/arangodb/pull/5316
> Fixing agency pool update

- arangod/VocBase/AuthUserEntry.cpp
backport a7b1bcb055bac21a8713793a23850e646de23dcf
> 3.2: backport 'fix scoping of vpack object builder (#5351) '

- arangod/RocksDBEngine/RocksDBCollection.cpp
- arangod/Transaction/Methods.cpp
Backporting some optimizations for CRUD operations from devel to 3.3
> improve performance of some RocksDB CRUD operations

- CHANGELOG
- js/client/tests/authentication/user-access-right-foxx-queue-general-spec.js
- js/client/tests/shell/shell-foxx-queue-spec.js
- js/common/test-data/apps/queue/index.js
- js/server/modules/@arangodb/foxx/queues/manager.js
> Fix Foxx queues

- Documentation/Books/Manual/Graphs/README.md
[Contributor Agreement.pdf](https://github.com/arangodb/arangodb/files/1698027/Contributor.Agreement.pdf)
> Fixed spelling errors

- arangod/Cluster/HeartbeatThread.cpp
> agency pool size had to be larger 1

- CHANGELOG
- arangod/Aql/ClusterBlocks.cpp
- arangod/Aql/ClusterBlocks.h
- arangod/Aql/RestAqlHandler.cpp
This PR is a backport from devel and 3.3
> issue one HTTP call less per cluster AQL query

- lib/ApplicationFeatures/ConfigFeature.cpp
> Fix typo in conf search for arangoimp.

- arangod/Agency/Inception.cpp
The remaining is following in a bit. Need to quickly fix an issue for Max.
> inception ignored leaders configuration

- arangod/Aql/ExecutionPlan.cpp
- arangod/Aql/ExecutionStats.cpp
- arangod/Aql/ExecutionStats.h
- arangod/Aql/Query.cpp
- js/common/tests/shell/shell-statement.js
- js/server/modules/@arangodb/aql-helper.js
- js/server/tests/aql/aql-fullcount.js
- js/server/tests/aql/aql-modify-cluster.js
- js/server/tests/aql/aql-modify-noncluster.js
- js/server/tests/aql/aql-modify-subqueries.js
Please check if this fixes the "number of documents" issue in the web interface.
> fix incompatibility after fullCount change

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/views/indicesView.js
https://github.com/arangodb/arangodb/issues/5035
> fixed a vulnerability issue within the web ui's index view

- arangod/Aql/Ast.cpp
- arangod/Aql/ClusterNodes.cpp
- arangod/Aql/EngineInfoContainerDBServer.cpp
- arangod/Aql/ExecutionEngine.cpp
- arangod/Aql/ExecutionNode.cpp
- arangod/Aql/ExecutionPlan.cpp
- arangod/Aql/Functions.cpp
- arangod/Aql/GraphNode.cpp
- arangod/Aql/IndexNode.cpp
- arangod/Aql/ModificationNodes.cpp
- arangod/Aql/OptimizerRules.cpp
- arangod/Aql/Query.h
- arangod/Aql/QueryProfile.cpp
- arangod/Aql/QueryRegistry.cpp
- arangod/IResearch/IResearchLinkHelper.cpp
- arangod/IResearch/IResearchViewNode.cpp
- arangod/IResearch/IResearchViewNode.h
> issue 389.9: return TRI_vocbase_t& from Query::vocbase()

- lib/Basics/Common.h
- lib/Basics/ScopeGuard.h
and make TRI_DEFER use it
all existing occurrences of TRI_DEFER will be replaced later, when a few big outstanding PRs have been merged
> added new ScopeGuard implementation

- Documentation/Books/Cookbook/Compiling/Debian.md
> Updated paths to fit ArangoDB v3

- arangod/Aql/ClusterNodes.cpp
- arangod/Aql/EngineInfoContainerDBServer.cpp
- arangod/Aql/EngineInfoContainerDBServer.h
> add missing ifdefs

- arangod/GeneralServer/RestHandlerFactory.cpp
> allow accessing "/_admin/status" on follower

- CHANGELOG
- arangod/GeneralServer/RestHandlerFactory.cpp
> allow accessing /_admin/status on follower

- arangod/ClusterEngine/ClusterEngine.cpp
- arangod/ClusterEngine/ClusterEngine.h
- arangod/ClusterEngine/ClusterIndexFactory.cpp
- arangod/ClusterEngine/ClusterIndexFactory.h
- arangod/IResearch/IResearchFeature.cpp
- arangod/IResearch/IResearchLinkCoordinator.cpp
- arangod/IResearch/IResearchLinkCoordinator.h
- arangod/IResearch/IResearchMMFilesLink.cpp
- arangod/IResearch/IResearchRocksDBLink.cpp
- arangod/IResearch/IResearchView.cpp
- arangod/Indexes/IndexFactory.cpp
- arangod/Indexes/IndexFactory.h
- tests/IResearch/IResearchLinkCoordinator-test.cpp
- tests/IResearch/IResearchViewCoordinator-test.cpp
- tests/IResearch/StorageEngineMock.cpp
> issue 381.4.1: create a separate IResearchLink implementation for use with ClusterEngine

- Documentation/Books/Manual/Deployment/DC2DC/README.md
- Documentation/Books/Manual/Deployment/README.md
- Documentation/Books/Manual/SUMMARY.md
- Documentation/Books/Manual/Scalability/DC2DC/README.md
> Doc - DC2DC - Improve directory structure

- Documentation/Books/Manual/Administration/Configuration/SSL.md
configure endpoints with http+ssl instead tcp.
_Needs discussion_
> Doc fix: SSL endpoints

- Documentation/Books/Manual/SUMMARY.md
- Documentation/Books/Manual/Troubleshooting/Cluster/AgencyDump.md
Procedure to create an Agency Dump
> Doc - Agency dump page

- CHANGELOG
- js/client/modules/@arangodb/inspector.js
fixing typos adding change log entry
> typos is api acquisitions

- arangod/RestHandler/RestReplicationHandler.cpp
- arangod/V8Server/v8-replication.cpp
applied requested replication changes as in https://github.com/arangodb/arangodb/pull/5555
> replication ui requested changes

- arangod/Aql/AqlTransaction.cpp
- arangod/Aql/ClusterNodes.cpp
- arangod/Aql/ClusterNodes.h
- arangod/Aql/Collection.cpp
- arangod/Aql/Collection.h
- arangod/Aql/CollectionAccessingNode.cpp
- arangod/Aql/CollectionAccessingNode.h
- arangod/Aql/Collections.cpp
- arangod/Aql/Condition.cpp
- arangod/Aql/ConditionFinder.cpp
- arangod/Aql/EngineInfoContainerDBServer.cpp
- arangod/Aql/EnumerateCollectionBlock.cpp
- arangod/Aql/EnumerateCollectionBlock.h
- arangod/Aql/ExecutionNode.cpp
- arangod/Aql/ExecutionNode.h
- arangod/Aql/ExecutionPlan.cpp
- arangod/Aql/GraphNode.cpp
- arangod/Aql/IndexNode.cpp
- arangod/Aql/IndexNode.h
- arangod/Aql/ModificationBlocks.cpp
- arangod/Aql/ModificationNodes.cpp
- arangod/Aql/ModificationNodes.h
- arangod/Aql/OptimizerRules.cpp
- arangod/Aql/ShortestPathNode.cpp
- arangod/Aql/TraversalNode.cpp
- arangod/CMakeLists.txt
- arangod/IResearch/IResearchViewNode.cpp
- js/common/modules/@arangodb/aql/explainer.js
- tests/IResearch/IResearchViewNode-test.cpp
Move the _collection/_vocbase-related parts of ExecutionNodes into CollectionAccessingNode.*
> cleanup collection/vocbase interface of ExecutionNodes

- arangod/Aql/EngineInfoContainerDBServer.cpp
> fix ms compilation

- js/apps/system/_admin/aardvark/APP/frontend/js/templates/navigationView.ejs
enables the "arangosearch" view in the web ui
> added views nagivation entry for arangosearch into the web ui

- UnitTests/unittest.js
- js/client/modules/@arangodb/testing.js
- lib/V8/v8-utils.cpp
> Bug fix/improve test status handling

- arangod/Transaction/Methods.cpp
- arangod/Transaction/Methods.h
> issue 380.3: remove code duplication and simplify logic

- js/actions/api-cluster.js
- js/server/modules/@arangodb/cluster.js
- js/server/tests/resilience/moving-shards-cluster.js
This is so far intentionally undocumented, since we want to collect
experience with it first.
> Add an API to query for status of moveShard and cleanOutServer jobs.

- Documentation/Books/Users/Advanced/Arangob.md
> 2.8: fix: blog posts links were interchanged

- Documentation/Books/Manual/Troubleshooting/Arangobench.md
> 3.2: fix: blog posts links were interchanged

- Documentation/Books/AQL/Graphs/Traversals.md
> clarify WITH for cluster traversal

- arangod/Aql/OptimizerRules.cpp
- js/server/tests/aql/aql-optimizer-collect-count.js
> prevent an optimization from destroying variables

- arangod/Auth/UserManager.cpp
- arangod/GeneralServer/GeneralCommTask.cpp
- arangod/GeneralServer/HttpCommTask.cpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/781/
> Fix boostrap 503 response

- Documentation/Books/Manual/Programs/Arangoinspect/Examples.md
- Documentation/Books/Manual/Programs/Arangoinspect/Options.md
- Documentation/Books/Manual/Programs/Arangoinspect/README.md
- Documentation/Books/Manual/Programs/README.md
- Documentation/Books/Manual/SUMMARY.md
- Documentation/Examples/arangoinspect.json
- utils/generateExamples.sh
Initial draft. I'm not sure about the following:
> For non-cluster deployments,
> you may authenticate with a user name and password instead:
> 
>     arangoinspect --server.ask-jwt-secret false --server.username "root" --server.password "foobar"
Is a JWT-secret only used in clusters, or also other deployment modes? Is it only possible to use username/password for single server instances?
> Docs for arangoinspect

- Documentation/Books/Manual/Deployment/Kubernetes/DeploymentReplicationResource.md
- Documentation/Books/Manual/Deployment/Kubernetes/DeploymentResource.md
- Documentation/Books/Manual/SUMMARY.md
- Documentation/Books/Manual/Tutorials/Kubernetes/DC2DC.md
- Documentation/Books/Manual/Tutorials/Kubernetes/README.md
- Documentation/Books/Manual/Tutorials/README.md
Internal Ref: https://github.com/arangodb/planning/issues/2555
It also backport latest changes in the kube deployment chapter
> Doc - Kube tutorial backport

- js/server/tests/aql/aql-optimizer-rule-remove-unnecessary-remote-scatter-cluster.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/806/
> fix broken test rule

- arangod/Aql/CollectionAccessingNode.cpp
- arangod/Aql/CollectionAccessingNode.h
- arangod/Aql/ModificationNodes.cpp
- js/common/modules/@arangodb/aql/explainer.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-pr/20/
> add the primary indices to the AQL modification nodes serialization and their explain output

- Documentation/Books/AQL/Functions/Geo.md
- Documentation/Books/Manual/Indexing/Geo.md
- Documentation/Books/Manual/Indexing/WorkingWithIndexes.md
- Documentation/Books/Manual/ReleaseNotes/UpgradingChanges34.md
- Documentation/DocuBlocks/collectionEnsureIndex.md
- arangod/Aql/EngineInfoContainerDBServer.cpp
- arangod/Aql/Functions.cpp
- arangod/GeoIndex/Index.cpp
- arangod/GeoIndex/Index.h
- js/server/tests/aql/aql-queries-geo.js
- lib/Geo/GeoJson.cpp
- lib/Geo/GeoJson.h
- lib/Geo/ShapeContainer.cpp
- lib/Geo/ShapeContainer.h
- tests/Geo/GeoJsonTest.cpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/802/
> Adding MultiPolygon support, fixing some outstanding bugs

- arangod/Aql/EngineInfoContainerDBServer.cpp
- arangod/Aql/EngineInfoContainerDBServer.h
> fix broken tests

- Documentation/Books/Cookbook/FoxxFirstStepsLegacy.md
- Documentation/Books/Users/FirstSteps/GettingFamiliar.md
- Documentation/Books/Users/Installing/Linux.md
- Documentation/Books/Users/Installing/MacOSX.md
> Documentation 2.8/fix download link

- arangod/Cluster/ClusterInfo.cpp
- arangod/Cluster/HeartbeatThread.cpp
- arangod/Cluster/HeartbeatThread.h
- arangod/ClusterEngine/ClusterEngine.cpp
- arangod/GeneralServer/GeneralCommTask.cpp
- arangod/MMFiles/MMFilesCleanupThread.cpp
- arangod/MMFiles/MMFilesCleanupThread.h
- arangod/Replication/TailingSyncer.cpp
- arangod/RestServer/BootstrapFeature.cpp
- arangod/RestServer/DatabaseFeature.cpp
- arangod/RestServer/DatabaseFeature.h
- arangod/RocksDBEngine/RocksDBBackgroundThread.cpp
- arangod/StorageEngine/StorageEngine.h
- arangod/V8Server/v8-vocbase.cpp
- arangod/VocBase/Methods/Databases.cpp
- arangod/VocBase/voc-types.h
- tests/IResearch/IResearchLinkCoordinator-test.cpp
- tests/IResearch/IResearchViewCoordinator-test.cpp
- tests/IResearch/StorageEngineMock.cpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/89/
> Remove Coordinator DBs

- CHANGELOG
> improves changelog 3311

- arangod/Aql/Functions.cpp
- arangod/Pregel/Conductor.cpp
- arangod/Pregel/Conductor.h
- arangod/Pregel/PregelFeature.cpp
- arangod/Pregel/Worker.cpp
- arangod/Pregel/Worker.h
- arangod/V8Server/v8-collection.cpp
- js/server/modules/@arangodb/aql.js
- js/server/tests/shell/shell-pregel.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-pr/16/
> Converting Pregel AQL function to c++ and fixing a bug

- arangod/Transaction/Methods.cpp
- arangod/Transaction/Methods.h
the previous change of mine did not work properly
> fix "silent" option for synchronous replication

- ISSUE_TEMPLATE.md
Please comment. Merge if you think this is fine.
> Shorter and easier to use issue template (proposal)

- Documentation/Books/Cookbook/Compiling/Windows.md
> 3.3-Doc Fix: typos and link

- js/client/modules/@arangodb/testsuites/audit.js
Note that there is also a corresponding PR in enterprise.
> added test suite for audit log

- Documentation/Books/Cookbook/Administration/Migrate2.8to3.0.md
- Documentation/Books/Drivers/JS/Reference/Collection/Indexes.md
- Documentation/Books/Manual/Deployment/StandaloneAgency/README.md
- Documentation/Books/Manual/Programs/Starter/Security.md
Requires:  https://github.com/arangodb/arangojs/pull/548 to complete.
> Doc - fix links

- arangod/MMFiles/MMFilesCollectorThread.cpp
- arangod/MMFiles/MMFilesCompactorThread.cpp
- arangod/MMFiles/MMFilesEngine.cpp
- arangod/MMFiles/MMFilesEngine.h
- arangod/RocksDBEngine/RocksDBEngine.cpp
- arangod/RocksDBEngine/RocksDBEngine.h
adds functions MMFilesEngine::disableCompaction() and MMFilesEngine::enableCompaction().
> turn off MMFiles collection and compaction

- Documentation/Books/Drivers/README.md
- Documentation/Books/build.sh
Internal ref: https://github.com/arangodb/planning/issues/1504
> Docs: Add drivers integrations section

- Documentation/Books/AQL/Operations/Insert.md
> fix aql-insert-options

- Documentation/Books/Manual/Architecture/StorageEngines.md
> fix planning issue 2623

- CHANGELOG
- arangod/GeneralServer/GeneralCommTask.cpp
- arangod/RocksDBEngine/RocksDBIndex.cpp
- js/client/tests/authentication/auth.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/203/
> Fix deleting rocksdb views and dump_authentication

- Documentation/Books/AQL/Operations/Remove.md
- Documentation/Books/AQL/Operations/Replace.md
- Documentation/Books/AQL/Operations/Update.md
- Documentation/Books/AQL/Operations/Upsert.md
- arangod/Aql/ExecutionPlan.cpp
- arangod/Aql/ModificationBlocks.cpp
- arangod/Aql/ModificationBlocks.h
- arangod/Aql/ModificationOptions.cpp
- arangod/Aql/ModificationOptions.h
- js/server/tests/aql/aql-modify.js
Forward port of @mchacki 's fix in #5760
> Bug fix/internal issue 2658 (#5760)

- Documentation/Books/AQL/Operations/Insert.md
- Documentation/Books/Manual/SUMMARY.md
- Documentation/Books/Manual/Security/ChangeRootPassword.md
Created a page that documents the procedure on how to reset the root password
> Doc - Change Root Password page

- 3rdParty/rocksdb/v5.14.X/CMakeLists.txt
> make the string cached so its not regenerated on each invokation, and thus re-creates the lib

- 3rdParty/iresearch/core/formats/formats_10.cpp
- arangod/IResearch/IResearchFeature.cpp
> Bug fix/internal issue #417

- Documentation/Books/Manual/Administration/Auditing/README.md
- Documentation/Books/Manual/Administration/Configuration/Ldap.md
- Documentation/Books/Manual/Administration/Encryption/README.md
- Documentation/Books/Manual/Administration/Satellites.md
- Documentation/Books/Manual/Graphs/SmartGraphs/README.md
Added `This feature is only available in the Enterprise Edition.` for features that are only available for EE
Internal ref:
- arangodb/planning#1677
> Doc - added ee note

- arangod/Aql/EngineInfoContainerDBServer.cpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/138/
> Fix enterprise auth tests (skipInaccessible)

- Documentation/Books/Manual/Administration/Cluster/README.md
Internal Ref:
- https://github.com/arangodb/planning/issues/2326
> Doc - Cluster Administration Improvements

- UnitTests/OskarTestSuitesBlackList
Added 3.3 tests blacklist for Oskar with "shell_client_aql" suite,
> Add 3.3 tests blacklist for Oskar

- arangod/Aql/Ast.cpp
- arangod/Aql/AstNode.h
- arangod/Aql/Condition.cpp
- arangod/Aql/ExecutionBlock.cpp
- arangod/Aql/IndexNode.cpp
- arangod/Aql/IndexNode.h
- arangod/Aql/ShortestPathBlock.cpp
- arangod/ClusterEngine/ClusterCollection.cpp
- arangod/GeneralServer/HttpCommTask.cpp
- arangod/Indexes/Index.cpp
- arangod/Indexes/PersistentIndexAttributeMatcher.cpp
- arangod/MMFiles/MMFilesSkiplistIndex.cpp
- arangod/Replication/TailingSyncer.cpp
This should fix the currently failing catch tests
> Bug fix/fixes 0907

- arangod/GeneralServer/HttpCommTask.cpp
This caused Aardvark to reload endlessly when visiting `http://localhost:8529/_db/_system/_admin/aardvark/index.html#login`.
CI run: http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/265/
> Avoid 403 forbidden response when authentication is off

- arangod/Aql/ExecutionBlock.cpp
- arangod/Aql/ExecutionBlock.h
- arangod/Aql/OptimizerRulesFeature.cpp
- arangod/RestServer/AqlFeature.cpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/263/
> don't use rumpelstilskin-lookup to map block strings to block types

- 3rdParty/iresearch/core/formats/formats_10.cpp
> backport fixes from IResearch upstream

- arangod/RocksDBEngine/RocksDBThrottle.cpp
The SetThrottle() routine previously replaced its DelayToken every time called. This procedure was intended to keep our calculated bytes-per-second active instead of any other value that rocksdb's code might subsequently set. Unfortunately, The GetDelayToken() code within rocksdb also clears all timings currently in use and forces a big wait upon the very next write. This could happen multiple times a second under heavy load.
The code now retrieves a DelayToken only if one is not previously held. Subsequent rewrites of our bytes-per-second value now use a different API that does not clear current timings.
> Bugfix 3.2:  adjust SetThrottle() to only call GetDelayToken() first time.

- README_maintainers.md
- UnitTests/HttpInterface/api-batch-spec.rb
- arangod/RestHandler/RestBatchHandler.cpp
this addresses https://github.com/arangodb/arangodb/issues/5827
> more RFC compliance when parsing http headers - support quotes

- arangod/Aql/ClusterBlocks.cpp
- arangod/Aql/ClusterBlocks.h
- arangod/Aql/Parser.cpp
- arangod/Aql/Query.cpp
Fix leaking AqlItemBlocks in SortingGatherBlock.
> fix AQL leak

- CHANGELOG
- js/common/modules/@arangodb/general-graph.js
- js/common/tests/shell/shell-general-graph.js
Related to https://github.com/arangodb/arangodb/pull/5843.
> [3.3] Bugfix: Creating a graph failed erroneously (v2)

- Documentation/Books/Drivers/README.md
Internal ref:
- https://github.com/arangodb/planning/issues/1504
https://github.com/arangodb/planning/issues/2644
> Doc - Links changelog of the Go driver

- js/common/modules/@arangodb/general-graph.js
Internal Ref:
- https://github.com/arangodb/planning/issues/2279
> Fixed behavior of graph._countCommonNeighbors with includeData true.

- Documentation/Books/Drivers/README.md
- Documentation/Books/Drivers/SUMMARY.md
- Documentation/Books/Drivers/SparkConnector/GettingStarted/README.md
- Documentation/Books/Drivers/SparkConnector/README.md
- Documentation/Books/Drivers/SparkConnector/Reference/Java.md
- Documentation/Books/Drivers/SparkConnector/Reference/README.md
- Documentation/Books/Drivers/SparkConnector/Reference/Scala.md
- VERSIONS
https://github.com/arangodb/planning/issues/2643
> Doc - Drivers: add headings + sync spark-connector

- lib/Basics/ReadWriteLock.h
- lib/Basics/ReadWriteSpinLock.h
update copyright, use uint32_t everywhere
> Update RW lock headers

- arangod/RestServer/CheckVersionFeature.cpp
- arangod/RestServer/arangod.cpp
- etc/arangodb3/arango-dfdb.conf.in
- etc/arangodb3/arangod.conf.in
- etc/jenkins/arango-dfdb.conf
- etc/relative/arango-dfdb.conf
- etc/testing/arango-dfdb.conf
- js/client/modules/@arangodb/testsuites/version.js
There is now also `scripts/unittest version` for testing the version check.
> Bug fix/fix version check

- Documentation/Books/Cookbook/Compiling/Debian.md
- Documentation/Books/Drivers/Java/Reference/Collection/CollectionManipulation.md
- Documentation/Books/Drivers/Java/Reference/Database/Queries.md
- Documentation/Books/Drivers/Java/Reference/Graph/README.md
- Documentation/Books/Manual/Administration/Auditing/AuditConfiguration.md
- Documentation/Books/Manual/Administration/Auditing/AuditEvents.md
- Documentation/Books/Manual/Administration/Auditing/README.md
- Documentation/Books/Manual/Administration/Configuration/Ldap.md
- Documentation/Books/Manual/Administration/Configuration/SSL.md
- Documentation/Books/Manual/Administration/DC2DC/README.md
- Documentation/Books/Manual/Administration/Encryption/README.md
- Documentation/Books/Manual/Administration/ManagingUsers/README.md
- Documentation/Books/Manual/Administration/Satellites.md
- Documentation/Books/Manual/DataModeling/Collections/DatabaseMethods.md
- Documentation/Books/Manual/Deployment/DC2DC/README.md
- Documentation/Books/Manual/Deployment/Kubernetes/DeploymentResource.md
- Documentation/Books/Manual/Graphs/SmartGraphs/README.md
- Documentation/Books/Manual/Monitoring/DC2DC/README.md
- Documentation/Books/Manual/ReleaseNotes/NewFeatures32.md
- Documentation/Books/Manual/ReleaseNotes/NewFeatures33.md
- Documentation/Books/Manual/Scalability/DC2DC/README.md
- Documentation/Books/Manual/Scalability/DC2DC/Requirements.md
- Documentation/Books/Manual/Security/DC2DC/README.md
- Documentation/Books/Manual/Troubleshooting/DC2DC/README.md
- Documentation/Books/Manual/Tutorials/DC2DC/README.md
- Documentation/Books/Manual/Tutorials/Kubernetes/DC2DC.md
- Documentation/Books/Manual/Tutorials/Starter/README.md
- Documentation/DocuBlocks/Rest/Collections/post_api_collection.md
- Documentation/DocuBlocks/Rest/Cursors/post_api_cursor.md
- Documentation/DocuBlocks/Rest/Graph/general_graph_create_http_examples.md
Hint box for EE note, always call it Enterprise Edition
Related PRs:
- https://github.com/arangodb-helper/arangodb/pull/185
- https://github.com/arangodb/arangosync/pull/432
> Docs: Enterprise Edition hint boxes

- Documentation/Books/Manual/Administration/Auditing/README.md
- Documentation/Books/Manual/Administration/Encryption/README.md
- Documentation/Books/Manual/Deployment/DC2DC.md
- Documentation/Books/Manual/Tutorials/Kubernetes/DC2DC.md
Internal Ref:
- https://github.com/arangodb/planning/issues/1677
> Doc - some EE notes in 3.3

- Documentation/DocuBlocks/Rest/Views/patch_api_view_properties_iresearch.md
- Documentation/DocuBlocks/Rest/Views/put_api_view_properties_iresearch.md
- js/apps/system/_admin/aardvark/APP/api-docs.json
-  fix RESTSTRUCT
- commit new swagger
> Doc: fix build

- arangod/RestServer/LockfileFeature.cpp
- lib/Basics/CleanupFunctions.cpp
- lib/Basics/CleanupFunctions.h
- lib/Basics/Common.h
- lib/CMakeLists.txt
- lib/Logger/Logger.h
Forward Port of a feature included in 3.3 a while ago.
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/399/
> Bug fix/lock file cleanup

- CHANGELOG
- Documentation/Books/AQL/Functions/Geo.md
- Documentation/Books/Manual/ReleaseNotes/UpgradingChanges34.md
- UnitTests/HttpInterface/api-miscellaneous-spec.rb
- arangod/Aql/OptimizerRulesReplaceFunctions.cpp
- arangod/RestHandler/RestStatusHandler.cpp
- js/server/tests/aql/aql-queries-geo.js
> compatibilty 3.3 <-> 3.4

- js/server/tests/shell/shell-readonly-mode-spec.js
This fixes a non-deterministic read only test (backported from devel)
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/416/
> Fixing non-deterministic readonly spec test

- js/apps/system/_admin/aardvark/APP/frontend/js/views/viewsView.js
Added `result` property to response for `getViews()`.
> Fix response processing for view Views

- arangod/Aql/OptimizerRules.cpp
- arangod/Aql/OptimizerRules.h
- js/server/tests/aql/aql-modify-cluster.js
> bug-fix/double-modification-bug

- arangod/IResearch/IResearchView.cpp
- arangod/IResearch/IResearchViewMeta.cpp
- arangod/IResearch/IResearchViewMeta.h
- tests/IResearch/IResearchView-test.cpp
> ensure cleanup policy is triggered

- js/server/tests/replication/replication-fuzz-global.js
Fix `replicationFuzzGlobal` test from `js/server/tests/replication/replication-fuzz-global.js`.
> Fix replicationFuzzGlobal test

- Documentation/Books/Manual/Foxx/Reference/Modules/Auth.md
- Documentation/Books/Manual/Views/ArangoSearch/README.md
> Doc: fix build (fix links + anchors)

- CHANGELOG
- arangod/Aql/EnumerateListBlock.cpp
- js/server/tests/aql/aql-queries-optimizer-limit-noncluster.js
> fixed issue #6031: Broken LIMIT in nested list iterations

- arangod/ClusterEngine/ClusterIndexFactory.cpp
- arangod/ClusterEngine/ClusterIndexFactory.h
- arangod/Indexes/IndexFactory.h
- arangod/VocBase/Methods/Indexes.cpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/498/
> fix exception in ClusterIndexFactory

- lib/ApplicationFeatures/ConfigFeature.cpp
- lib/Basics/ArangoGlobalContext.cpp
- lib/Basics/ArangoGlobalContext.h
- lib/Basics/files.cpp
- lib/Basics/files.h
Make `./etc/relative` the first path to look in for config files
> always look in etc/relative first for config files

- arangod/Statistics/StatisticsWorker.cpp
to successful initial creation of these collections
Instead, try to create the indexes on every instance start
That way even if the index creation failed initially, the indexes
will be created on the next startup, and no user intervention
is required but restarting
The previous implementation did not create the indexes at all
then, and left the user with a message saying "please create
the index manually"
> do not couple creation of indexes on statistics collections

- CHANGELOG
- arangod/Aql/OptimizerRules.cpp
- js/server/tests/aql/aql-modify-cluster.js
> fix timeout issue next try: no subquery nodes on dbservers

- js/client/modules/@arangodb/arango-view.js
@gnusi please check the properties list
> restrict attributes

- arangod/Aql/QueryCursor.cpp
- arangod/Aql/QueryCursor.h
- arangod/MMFiles/MMFilesExportCursor.cpp
- arangod/MMFiles/MMFilesExportCursor.h
- arangod/RestHandler/RestCursorHandler.cpp
- arangod/RestHandler/RestCursorHandler.h
- arangod/RestHandler/RestSimpleHandler.cpp
- arangod/RestHandler/RestSimpleHandler.h
- arangod/RestHandler/RestSimpleQueryHandler.cpp
- arangod/RestHandler/RestSimpleQueryHandler.h
- arangod/RocksDBEngine/RocksDBRestExportHandler.cpp
- arangod/RocksDBEngine/RocksDBRestExportHandler.h
- arangod/Utils/Cursor.h
- arangod/VocBase/Methods/Indexes.cpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/515/
> Make stream cursors non-blocking

- CHANGELOG
- arangod/Cluster/ClusterInfo.cpp
- js/common/tests/shell/shell-index.js
> fixed parallel creation of indexes in cluster

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/views/documentView.js
fix for https://github.com/arangodb/arangodb/issues/5648
> fixed ui bug when saving invalid document type

- 3rdParty/iresearch/core/utils/file_utils.cpp
- 3rdParty/iresearch/core/utils/file_utils.hpp
- 3rdParty/iresearch/core/utils/utf8_path.cpp
> issue 427.4: ackport utf8_path changes from iresearch upstream

- CHANGELOG
- arangod/RestHandler/RestReplicationHandler.cpp
- js/client/modules/@arangodb/testsuites/backup.js
- js/client/modules/@arangodb/testsuites/replication.js
- js/client/tests/active-failover/basic.js
- js/server/tests/replication/replication-ongoing-global.js
Now includes users in dump process under authentication.
//fyi: @sleto-it @lservini
> Bug fix/dump restore under authentication

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/scss/_nodes.scss
https://github.com/arangodb/planning/issues/2566
> webui, fixed misalignment of a table

- CHANGELOG
> Update CHANGELOG - 3.3.14

- arangod/Graph/Graph.cpp
this PR fixes the creation/deletion of graphs within the new c++ gharial api. 
(occured in: mmfiles + community)
> fixing gharial graph constructor for community and mmfiles

- js/common/tests/http/api-gharial-creation-cluster-spec.js
- js/common/tests/shell/general-graph-creation-cluster-spec.js
added lost gharial tests from 3.2 branch to devel branch
> added lost gharial tests

- Documentation/Books/AQL/CommonErrors.md
- Documentation/Books/AQL/Extending/Conventions.md
- Documentation/Books/AQL/Extending/README.md
- Documentation/Books/AQL/Functions/Date.md
- Documentation/Books/AQL/Functions/Miscellaneous.md
- Documentation/Books/Manual/ReleaseNotes/UpgradingChanges34.md
- arangod/Aql/AqlFunctionFeature.cpp
- arangod/Aql/AstNode.h
- arangod/Aql/ExecutionNode.cpp
- arangod/Indexes/Index.cpp
- arangod/Indexes/PersistentIndexAttributeMatcher.cpp
- arangod/Indexes/SimpleAttributeEqualityMatcher.cpp
- arangod/Indexes/SkiplistIndexAttributeMatcher.cpp
- arangod/RocksDBEngine/RocksDBComparator.cpp
- arangod/RocksDBEngine/RocksDBComparator.h
- js/common/modules/@arangodb/aql/explainer.js
- js/server/tests/aql/aql-failures-noncluster.js
- js/server/tests/aql/aql-optimizer-costs.js
- js/server/tests/aql/aql-optimizer-indexes-sort.js
- js/server/tests/aql/aql-optimizer-indexes.js
- js/server/tests/aql/aql-optimizer-keep.js
- js/server/tests/aql/aql-sparse.js
Use sparse indexes in slightly more cases than before.
Make AQL function `PASSTHRU` deterministic, and separate it from `NOOPT`.
> Bug fix/more sparsung

- lib/ProgramOptions/Option.cpp
- lib/ProgramOptions/Option.h
- lib/ProgramOptions/ProgramOptions.cpp
- lib/ProgramOptions/ProgramOptions.h
- lib/ProgramOptions/Section.h
accompanied by PR https://github.com/arangodb/enterprise/pull/128
> add `enterpriseOnly` documentation sections

- Documentation/Books/Manual/ReleaseNotes/NewFeatures34.md
- Documentation/Books/Manual/ReleaseNotes/UpgradingChanges34.md
- arangod/Aql/AqlFunctionFeature.cpp
- arangod/Aql/AqlFunctionFeature.h
- arangod/Aql/Ast.cpp
- arangod/Aql/AstNode.cpp
- arangod/Aql/ExecutionNode.cpp
- arangod/Aql/ExecutionPlan.cpp
- arangod/Aql/Function.cpp
- arangod/Aql/Function.h
- arangod/Aql/Functions.cpp
- arangod/Aql/Functions.h
- arangod/Graph/Graph.h
- arangod/IResearch/IResearchAnalyzerFeature.cpp
- arangod/IResearch/IResearchFeature.cpp
- arangod/RestHandler/RestJobHandler.cpp
- js/apps/system/_admin/aardvark/APP/frontend/js/views/spotlightView.js
- js/common/tests/shell/shell-view-arangosearch-noncluster.js
- tests/IResearch/ExpressionFilter-test.cpp
- tests/IResearch/IResearchFilter-test.cpp
- tests/IResearch/IResearchFilterBoolean-test.cpp
- tests/IResearch/IResearchFilterCompare-test.cpp
- tests/IResearch/IResearchFilterFunction-test.cpp
- tests/IResearch/IResearchFilterIn-test.cpp
- tests/IResearch/IResearchOrder-test.cpp
- tests/IResearch/IResearchQueryJoin-test.cpp
- tests/IResearch/IResearchQueryStringTerm-test.cpp
seperate Deterministic and Cacheable attributes for AQL functions
fix a few wrong AQL function attributes (namely for UUID)
make AQL function DATE_NOW deterministic
adjust documentation
> make AQL functions construction easier

- arangod/IResearch/IResearchLink.cpp
- arangod/IResearch/IResearchView.cpp
- arangod/IResearch/IResearchView.h
- tests/IResearch/IResearchView-test.cpp
> issue 450.2: remove redundant functions from IResearchView API

- Documentation/Books/Manual/Transactions/Limitations.md
see: https://github.com/arangodb/planning/issues/1911
> Removed Limitation note in transaction

- Documentation/Books/Manual/Transactions/Limitations.md
see: https://github.com/arangodb/planning/issues/1911
> Removed Limitation note in transaction 

- arangod/Aql/QueryCursor.cpp
- arangod/Utils/Cursor.h
- js/client/tests/shell/shell-query-stream.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/715/
> Fixing crashes on UPDATE / INSERT queries

- js/client/tests/http/api-gharial-spec.js
(originally from devel branch) 
see pr: https://github.com/arangodb/arangodb/pull/6201
> added gharial tests

- js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
PR for https://github.com/arangodb/planning/issues/2309
> UI: Improve debug package description dialog

- arangod/Auth/TokenCache.cpp
- arangod/Auth/UserManager.cpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/730/
https://github.com/arangodb/planning/issues/2905#issuecomment-414677078
> Fix authentication

- 3rdParty/fuerte/include/fuerte/connection.h
- 3rdParty/fuerte/include/fuerte/types.h
- 3rdParty/fuerte/src/HttpConnection.cpp
- 3rdParty/fuerte/src/HttpConnection.h
- 3rdParty/fuerte/src/VstConnection.cpp
- 3rdParty/fuerte/src/VstConnection.h
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/734/
> Fuerte retries connections

- Documentation/DocuBlocks/Rest/Views/patch_api_view_properties_iresearch.md
- Documentation/DocuBlocks/Rest/Views/post_api_view_iresearch.md
- Documentation/DocuBlocks/Rest/Views/put_api_view_properties_iresearch.md
- arangod/IResearch/IResearchView.cpp
> issue 450.4: address issues with impropper comparison

- Documentation/DocuBlocks/Rest/Views/patch_api_view_properties_iresearch.md
- Documentation/DocuBlocks/Rest/Views/post_api_view_iresearch.md
- Documentation/DocuBlocks/Rest/Views/put_api_view_properties_iresearch.md
- UnitTests/HttpInterface/api-view-arangosearch-spec-noncluster.rb
- arangod/IResearch/IResearchView.cpp
- arangod/IResearch/IResearchViewMeta.cpp
- arangod/IResearch/IResearchViewMeta.h
- js/common/tests/aql/aql-view-arangosearch-ddl-cluster.js
- js/common/tests/aql/aql-view-arangosearch-ddl-noncluster.js
- js/common/tests/shell/shell-view-arangosearch-noncluster.js
- js/server/tests/recovery/view-arangosearch-create.js
- js/server/tests/recovery/view-arangosearch-modify-properties.js
- js/server/tests/recovery/view-arangosearch-properties.js
- js/server/tests/recovery/view-arangosearch-recreate.js
- js/server/tests/recovery/view-arangosearch-rename-recreate-flush.js
- js/server/tests/recovery/view-arangosearch-rename-recreate.js
- js/server/tests/recovery/view-arangosearch-rename.js
- tests/IResearch/IResearchView-test.cpp
- tests/IResearch/IResearchViewCoordinator-test.cpp
- tests/IResearch/IResearchViewDBServer-test.cpp
- tests/IResearch/IResearchViewMeta-test.cpp
> issue 450.5: rename consolidation-related configuration properties and remove locale

- arangod/Cluster/HeartbeatThread.cpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/768/
> Make sure leader is doing a full resync

- 3rdParty/fuerte/src/Basics/Endian.h
- 3rdParty/fuerte/src/HttpConnection.cpp
- arangod/Cluster/HeartbeatThread.cpp
- arangod/GeneralServer/GeneralCommTask.cpp
- arangod/RestHandler/RestAdminServerHandler.cpp
- arangod/RestServer/DatabaseFeature.cpp
- arangod/RocksDBEngine/RocksDBWalAccess.cpp
- js/client/tests/active-failover/basic.js
- js/client/tests/active-failover/readonly.js
- lib/Basics/Endian.h
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/777/
> Various small changes

- arangod/RestHandler/RestDatabaseHandler.cpp
- js/actions/api-cluster.js
- All cluster routes are coordinator only (except maintenance mode)
- Fix an unrelated issue in the WebUI
> Make cluster routes check roles

- Documentation/Books/AQL/Functions/Array.md
- Documentation/Books/Manual/ReleaseNotes/NewFeatures34.md
- arangod/Aql/AqlFunctionFeature.cpp
> add AQL function CONTAINS_ARRAY as alias for POSITION

- Documentation/Books/Manual/Graphs/GeneralGraphs/README.md
> Included Link to Graph Course

- CHANGELOG
- js/apps/system/_api/foxx/APP/index.js
- js/common/bootstrap/modules.js
- js/common/bootstrap/modules/console.js
- js/common/modules/@arangodb/foxx/manager-utils.js
- js/common/modules/@arangodb/util.js
- js/common/tests/shell/shell-foxx-manager-utils-spec.js
- js/server/modules/@arangodb/foxx/manager.js
> Better Foxx errors (3.3)

- arangod/Cluster/ClusterMethods.cpp
- arangod/Cluster/ClusterMethods.h
- arangod/Transaction/Methods.cpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/852/
> Remove header from trx::methods

- CHANGELOG
- Documentation/Books/Manual/ReleaseNotes/NewFeatures34.md
Fixes arangodb/team-orco-planning#17
> add information about library upgrades

- tests/js/server/tests/resilience/moving-shards-with-arangosearch-view-cluster.js
- tests/js/server/tests/resilience/resilience-synchronous-repl-with-arangosearch-view-cluster.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/881/
> Enable views usage in designated tests

- Documentation/Books/Manual/ReleaseNotes/KnownIssues34.md
- Documentation/Books/Manual/ReleaseNotes/README.md
- Documentation/Books/Manual/SUMMARY.md
Tests:
- https://master.jenkins.arangodb.info/job/PATCH_DOCUMENTATION/319/
> add known issues for 3.4 release

- CHANGELOG
- arangod/Graph/BreadthFirstEnumerator.cpp
- arangod/Graph/BreadthFirstEnumerator.h
- arangod/Graph/EdgeDocumentToken.h
- tests/js/server/tests/aql/aql-graph.js
Jenkins: http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/892/
No code changes between 3.3 and devel here.
> Forward port of bugfix to issue #5941 from 3.3.15

- js/apps/system/_admin/aardvark/APP/frontend/scss/_modals.scss
fixes alignment of the checkbox element for some browsers.
> fixed the checkbox alignment inside a modal element

- arangod/Cluster/EngineEqualityCheckFeature.cpp
- arangod/MMFiles/MMFilesLogfileManager.cpp
- arangod/MMFiles/MMFilesWalRecoveryFeature.cpp
- arangod/RestServer/CheckVersionFeature.cpp
- arangod/RestServer/DatabaseFeature.cpp
- arangod/RestServer/DatabaseFeature.h
- arangod/RestServer/ServerIdFeature.cpp
- arangod/RestServer/SystemDatabaseFeature.cpp
- arangod/RestServer/SystemDatabaseFeature.h
- arangod/RocksDBEngine/RocksDBRecoveryManager.cpp
Add a dependency to the SystemDatabaseFeature to several other features.
> more explicit order for SystemDatabaseFeature

- js/client/modules/@arangodb/testsuites/readOnly.js
> fix failing readOnly test

- CHANGELOG
- arangosh/Restore/RestoreFeature.cpp
- arangosh/Restore/RestoreFeature.h
added more detailed progress output to arangorestore, showing the percentage of how much data is restored for bigger collections plus a set of overview statistics after each processed collection
> more detailed progress output for arangorestore

- Documentation/Books/Manual/ReleaseNotes/NewFeatures34.md
adds a note to NewFeatures3.4.md
> new features geo aql editor

- arangod/RestHandler/RestReplicationHandler.cpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/971/
> use less VPackBuilders when restoring data into a collection

- scripts/startLeaderFollower.sh
- scripts/startLocalCluster.sh
also capture stderr as originally intended (was not logged)
> fix logging of stdout for agency nodes

- arangod/Agency/AgentCallback.cpp
- arangod/Cluster/AgencyCallback.cpp
Suppress some error messages which are expected on a shutdown.
> suppress some messages which are expected on shutdown

- arangod/Pregel/GraphStore.cpp
- arangod/Pregel/GraphStore.h
- tests/js/server/shell/shell-pregel.js
>  Fix pregel during import

- arangod/Pregel/GraphStore.cpp
- arangod/Pregel/GraphStore.h
- tests/js/server/shell/shell-pregel.js
Should address https://github.com/arangodb/arangodb/issues/5205
> Fix pregel during import

- Documentation/Books/Manual/ReleaseNotes/NewFeatures34.md
- js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
See https://github.com/arangodb/arangodb/pull/6371
> query result map added tooltips, added recognition of geometry attribute

- js/apps/system/_admin/aardvark/APP/frontend/js/routers/versionCheck.js
- js/server/modules/@arangodb/index.js
- tests/js/common/tests/shell/shell-version-check-spec.js
see https://github.com/arangodb/arangodb/pull/6312
> Feature 3.4/new versioning scheme

- Documentation/Books/AQL/Views/ArangoSearch/README.md
- Documentation/Books/Manual/Views/ArangoSearch/Analyzers.md
- Documentation/Books/Manual/Views/ArangoSearch/DetailedOverview.md
- Documentation/Books/Manual/Views/ArangoSearch/README.md
- Documentation/Books/Manual/Views/ArangoSearch/Scorers.md
Some minor changes to improve visual output
> Docs: Arangosearch - Fixes to formatting

- Documentation/Books/Manual/Highlights.md
> Doc - 3.4 Highlights

- js/client/tests/http/api-gharial-spec.js
- js/common/modules/@arangodb/general-graph.js
fixed issue: https://github.com/arangodb/arangodb/issues/3456
> fixed duplicate orphan bug

- arangod/Cluster/HeartbeatThread.cpp
- arangod/Cluster/HeartbeatThread.h
- arangod/Cluster/UpdateCollection.cpp
Cherry pick of #6342 for devel
> Dedicated thread for Phase 1&2 - devel

- arangod/MMFiles/MMFilesWalRecoverState.cpp
- arangod/Replication/TailingSyncer.cpp
- arangod/RestHandler/RestViewHandler.cpp
- arangod/V8Server/v8-views.cpp
- arangod/VocBase/Methods/Collections.cpp
- arangod/VocBase/vocbase.cpp
- arangod/VocBase/vocbase.h
> issue 465.5: when renaming a datasource use the object from within vocbase

- arangod/Graph/Graph.cpp
- arangod/Graph/Graph.h
gharial vertexCollsusing using sorted type now
> gharial vertexCollsusing using sorted type now

- 3rdParty/iresearch/core/search/disjunction.hpp
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-windows-onlycompile/993/
> Bug fix/vs2017 15.8.2 iresearch build

- arangod/Pregel/GraphStore.cpp
- arangod/Pregel/GraphStore.h
- arangod/Pregel/PregelFeature.cpp
- arangod/RestHandler/RestControlPregelHandler.cpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/1010/
> Fix Pregel Graph Loading Logic

- arangod/Replication/DatabaseInitialSyncer.cpp
- js/client/modules/@arangodb/process-utils.js
- js/client/modules/@arangodb/testsuites/replication.js
Add some debugging for the replication_sync test, as this test is unstable with MMFiles.
> add some debugging for unstable replication_sync test

- arangod/RestHandler/RestBatchHandler.cpp
- arangod/RestHandler/RestBatchHandler.h
> Rest Batch Handler Memleak [3.4]

- arangod/RestHandler/RestBatchHandler.cpp
- arangod/RestHandler/RestBatchHandler.h
> Rest Batch Handler Memleak [devel]

- js/apps/system/_admin/aardvark/APP/frontend/scss/_queryView.scss
added missing css for the leaflet map tooltip
> added missing css for the leaflet map tooltip

- Documentation/DocuBlocks/Rest/Graph/general_graph_edge_definition_remove_http_examples.md
- tests/js/client/http/api-gharial-spec.js
Added tests because of https://github.com/arangodb/arangodb/issues/3456
> added gharial tests, updated docu

- CHANGELOG
- arangod/Graph/BreadthFirstEnumerator.cpp
The following changes did not make into devel apparently:
https://github.com/arangodb/arangodb/pull/6303/commits/1e725646d343871b031b9fd48676f8965c3fd3b1#diff-d6a329b541cdda9e5ddff2c3e96e637d
> Forward port changelog changes and typo fixes from #6303

- tests/js/client/authentication/user-access-right-task-update-view-arangosearch-spec.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/1043/
> Fix ArangoSearch authentication update task test

- arangod/Aql/ClusterBlocks.cpp
- arangod/Aql/EnumerateCollectionBlock.cpp
- arangod/Aql/EnumerateListBlock.cpp
- arangod/Aql/ExecutionBlock.cpp
- arangod/Aql/ExecutionBlock.h
- arangod/Aql/IndexBlock.cpp
- arangod/Aql/TraversalBlock.cpp
- arangod/IResearch/IResearchViewBlock.cpp
- tests/Aql/WaitingExecutionBlockMock.cpp
- tests/IResearch/ExecutionBlockMock.cpp
- tests/js/server/aql/aql-profiler.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/1046/
> Trace skipSome() calls

- arangod/Aql/ClusterBlocks.cpp
- arangod/Aql/ExecutionBlock.cpp
> Fix skipSome PR

- arangod/Cluster/ClusterInfo.cpp
- arangod/Cluster/ClusterMethods.cpp
- arangod/Graph/BaseOptions.cpp
- arangod/Indexes/Index.h
- arangod/Transaction/Methods.cpp
- arangod/VocBase/LogicalCollection.cpp
- arangod/VocBase/Methods/Indexes.cpp
- arangod/VocBase/Methods/Indexes.h
Fix duplicate serialization of cluster index selectivity
> fix cluster index selectivity

- arangod/Cluster/HeartbeatThread.cpp
- arangod/RestServer/VocbaseContext.cpp
- arangod/Utils/ExecContext.h
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/1082/
> Fix ReadOnly Mode without auth-enabled

- arangod/CMakeLists.txt
- arangod/IResearch/IResearchFeature.cpp
- arangod/IResearch/IResearchView.cpp
- arangod/IResearch/IResearchView.h
- arangod/IResearch/IResearchViewCoordinator.cpp
- arangod/IResearch/IResearchViewSingleServer.cpp
- arangod/IResearch/IResearchViewSingleServer.h
- arangod/RestHandler/RestReplicationHandler.cpp
- arangod/VocBase/LogicalCollection.cpp
- arangod/VocBase/vocbase.cpp
- arangosh/Restore/RestoreFeature.cpp
- tests/IResearch/IResearchView-test.cpp
- tests/js/common/shell/shell-view-arangosearch-link-noncluster.js
- tests/js/common/shell/shell-view-arangosearch-noncluster.js
- tests/js/server/dump/dump-mmfiles-cluster.js
- tests/js/server/dump/dump-mmfiles.js
- tests/js/server/dump/dump-rocksdb-cluster.js
- tests/js/server/dump/dump-rocksdb.js
- tests/js/server/dump/dump-setup-cluster.js
- tests/js/server/dump/dump-setup.js
- tests/js/server/recovery/view-arangosearch-link-create-no-flushthread.js
- tests/js/server/recovery/view-arangosearch-link-create.js
This is a cherry pick of #6466 for 3.4.
> Completely export views dump restore [3.4]

- arangod/Cluster/v8-cluster.cpp
- arangod/ClusterEngine/ClusterEngine.cpp
- arangod/RestServer/DatabasePathFeature.cpp
- arangod/RestServer/DatabasePathFeature.h
- arangod/V8Server/V8DealerFeature.cpp
- arangod/V8Server/V8DealerFeature.h
- arangosh/Shell/V8ShellFeature.cpp
- arangosh/Shell/V8ShellFeature.h
- js/JS_SHA1SUM.txt
- js/client/modules/@arangodb/process-utils.js
- js/server/modules/@arangodb/foxx/manager.js
- lib/Basics/StaticStrings.cpp
- lib/Basics/StaticStrings.h
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/1110/
> Copy installation files on startup

- arangod/Aql/AqlItemBlock.cpp
but not the ability to produce them. This way we can support
running 3.3 as part of a mixed 3.3/3.4 cluster, and do not
break any clusters that run mixed versions of 3.3 current and
either 3.2 or 3.3 older versions
> add ability to 3.3 to read compressed AqlItemBlocks

- arangod/Agency/ActiveFailoverJob.cpp
- arangod/Cluster/HeartbeatThread.cpp
- arangod/Replication/TailingSyncer.cpp
- arangod/RestHandler/RestReplicationHandler.cpp
- arangod/RestHandler/RestShutdownHandler.cpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/1158/
> Properly check syncer erros, catch more exceptions

- arangod/RocksDBEngine/RocksDBIncrementalSync.cpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/1169/
> Use physical collection directly

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
catch 501 (not implemented) in the query editor (ui)
> catch 501 (not implemented) in the query editor (ui)

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
catch 501 (not implemented) in the query editor (ui)
> catch 501 (not implemented) in the query editor (ui) 

- arangosh/Dump/DumpFeature.cpp
> Remove unused variable check from arangodump

- arangod/RocksDBEngine/RocksDBCollection.cpp
- arangod/RocksDBEngine/RocksDBMethods.cpp
- arangod/RocksDBEngine/RocksDBMethods.h
> Bug fix/add pinnable slice for lookups

- 3rdParty/fuerte/src/HttpConnection.cpp
- 3rdParty/fuerte/src/VstConnection.cpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/2140/
> Do not retry connect on canceled connections

- arangod/Aql/OptimizerRules.cpp
- tests/js/server/aql/aql-modify-cluster.js
- tests/js/server/aql/aql-modify-subqueries.js
- tests/js/server/aql/aql-shardids-cluster.js
> Backport #6182 and #6549.

- arangod/Agency/CleanOutServer.cpp
- arangod/Agency/MoveShard.cpp
- arangod/Agency/MoveShard.h
- tests/Agency/CleanOutServerTest.cpp
- tests/Agency/FailedFollowerTest.cpp
- tests/Agency/FailedLeaderTest.cpp
- tests/Agency/MoveShardTest.cpp
Fixes arangodb/team-clifton-planning#40.
Docs arangodb/documents#22
> cleanoutServer Bug Fix

- Documentation/Books/Manual/ReleaseNotes/KnownIssues34.md
http://jenkins01.arangodb.biz:8080/job/arangodb-documentation/69
> More known issues for ArangoSearch in 3.4

- arangod/Agency/CleanOutServer.cpp
- arangod/Agency/MoveShard.cpp
- arangod/Agency/MoveShard.h
- tests/Agency/CleanOutServerTest.cpp
- tests/Agency/FailedFollowerTest.cpp
- tests/Agency/FailedLeaderTest.cpp
- tests/Agency/MoveShardTest.cpp
> Bug fix 3.4/cleanout server dropping wrong follower

- arangod/Agency/CleanOutServer.cpp
- arangod/Agency/MoveShard.cpp
- arangod/Agency/MoveShard.h
- tests/Agency/CleanOutServerTest.cpp
- tests/Agency/FailedFollowerTest.cpp
- tests/Agency/FailedLeaderTest.cpp
- tests/Agency/MoveShardTest.cpp
> Bug fix 3.3/cleanout server dropping wrong follower

- arangod/Agency/AgencyComm.cpp
- arangod/Aql/RestAqlHandler.cpp
- arangod/Aql/SharedQueryState.cpp
- arangod/Aql/SharedQueryState.h
- arangod/Cluster/ClusterComm.cpp
- arangod/Cluster/ClusterComm.h
- arangod/Cluster/HeartbeatThread.cpp
- arangod/Graph/Graph.cpp
- arangod/Graph/GraphManager.cpp
- arangod/Transaction/Methods.cpp
- arangod/Transaction/Methods.h
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/1230/
> Fix superfluous  QueryRegistry::close, cleanup

- arangod/Aql/RestAqlHandler.cpp
- arangod/Aql/SharedQueryState.cpp
- arangod/Aql/SharedQueryState.h
- arangod/Transaction/Methods.cpp
- arangod/Transaction/Methods.h
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/1240/
>  Backport #6579 to 3.4 

- arangod/RestHandler/RestReplicationHandler.cpp
- arangod/RocksDBEngine/RocksDBCollection.cpp
- arangosh/Restore/RestoreFeature.cpp
- tests/js/server/shell/shell-collection-not-loaded-mmfiles-timecritical-noncluster.js
Backport of https://github.com/arangodb/arangodb/pull/6573
> Bug fix 3.4/optimizations 210918

- Documentation/DocuBlocks/Rest/Replication/get_api_replication_applier_state.md
- Documentation/DocuBlocks/Rest/Replication/put_api_replication_makeSlave.md
- arangod/Replication/DatabaseInitialSyncer.cpp
- arangod/Replication/ReplicationApplierState.cpp
Fix replication from 3.3 to 3.4 by not requiring "views" attribute.
> Bug fix 3.4/replication 33 to 34

- CHANGELOG
- arangod/Aql/ClusterBlocks.cpp
- arangod/Aql/ClusterBlocks.h
- arangod/Aql/ClusterNodes.cpp
- tests/js/server/aql/aql-gather-block-cluster.js
Fix invalid state in GatherBlock, leading to the coordinator doing endless requests to the DB server for more data
> fixed issue #6601

- Documentation/Books/HTTP/Agency/README.md
- Documentation/Books/HTTP/General/README.md
- arangod/Auth/TokenCache.cpp
- arangod/Auth/UserManager.cpp
- arangod/Auth/UserManager.h
- arangod/GeneralServer/GeneralCommTask.cpp
- arangod/RestServer/VocbaseContext.cpp
- js/client/tests/authentication/auth-cluster.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/1256/
> Fix crash on Agency / DBserver with user JWT tokens

- Documentation/Books/HTTP/Agency/README.md
Port from devel: https://github.com/arangodb/arangodb/pull/6617
> Fix anchor link and typos

- arangod/Agency/Supervision.cpp
- arangod/Agency/Supervision.h
- tests/Agency/CleanUpLostCollectionTest.cpp
- tests/Agency/CleanUpLostCollectionTest.json
- tests/CMakeLists.txt
> Feature 3.4/cleanup lost collections

- arangod/Replication/DatabaseInitialSyncer.cpp
- arangod/Replication/DatabaseInitialSyncer.h
- arangod/Replication/Syncer.cpp
- arangod/VocBase/vocbase.cpp
- tests/js/server/replication/replication-ongoing-global.js
- tests/js/server/replication/replication-ongoing.js
- tests/js/server/replication/replication-sync.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/1293/
> Fix error in dump test, create views before syncing data

- arangod/Agency/Supervision.cpp
- arangod/Cluster/Action.h
- arangod/Cluster/MaintenanceWorker.cpp
> Added try-catch-block.

- arangod/Agency/Supervision.cpp
- arangod/Cluster/Action.cpp
- arangod/Cluster/Action.h
- arangod/Cluster/MaintenanceWorker.cpp
Fixes arangodb/team-clifton-planning#55
> Catch all exceptions to prevent maintenance workers from crashing.

- tests/js/client/resilience/foxxmaster.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/1319/
> Change tests setUp/tearDown to be common

- 3rdParty/rocksdb/v5.16.X/db/range_del_aggregator.cc
- 3rdParty/rocksdb/v5.16.X/db/range_del_aggregator_test.cc
Forward port of facebook/rocksdb commit 17edc82a4ba3d4455b9fe86632f11e47df4a16e1
> forward-port some RocksDB bugfix

- arangod/RestServer/ServerFeature.cpp
- arangod/RestServer/ServerFeature.h
- arangosh/Shell/ClientFeature.cpp
- lib/ApplicationFeatures/LanguageFeature.cpp
backport https://github.com/arangodb/arangodb/pull/6679
> Bug fix 3.4/fix windows cp defaults

- js/apps/system/_admin/aardvark/APP/frontend/js/views/viewView.js
> Backport #6630 into 3.4

- arangod/Sharding/ShardDistributionReporter.cpp
- tests/Sharding/ShardDistributionReporterTest.cpp
Display shard sync progress for shards that are not in the `_system` database.
> Bug fix/display sync progress

- Documentation/Books/Manual/BackupRestore/README.md
- Documentation/Books/Manual/SUMMARY.md
Internal Ref:
- https://github.com/arangodb/planning/issues/3042
> Doc - Backup Improvement

- Documentation/Books/Manual/BackupRestore/README.md
- Documentation/Books/Manual/SUMMARY.md
Internal Ref:
- https://github.com/arangodb/planning/issues/3042
> Doc - Backup Improvements

- arangod/Indexes/Index.cpp
- tests/js/common/aql/aql-view-arangosearch-ddl-cluster.js
- tests/js/common/aql/aql-view-arangosearch-ddl-noncluster.js
* Fix muliple links per collection issue (arangodb/release-3.4#48).
* Fix comparison.
* Added test
* Fix suite name.
* Address some edge cases.
* Clear views on teadown in tests
* Update aql-view-arangosearch-ddl-cluster.js
* Update aql-view-arangosearch-ddl-noncluster.js
* Fix jslint errors
* Added some comments about the comparison.
> Fix multiple links per collection issue (#6661)

- Documentation/Books/Manual/Programs/Arangod/Javascript.md
- arangosh/Shell/V8ShellFeature.cpp
> Document --javascript.copy-installation

- 3rdParty/iresearch/core/analysis/token_attributes.hpp
- 3rdParty/iresearch/core/formats/formats_10.cpp
- 3rdParty/iresearch/core/formats/formats_10_attributes.hpp
- 3rdParty/iresearch/core/formats/formats_burst_trie.cpp
- 3rdParty/iresearch/core/index/iterators.cpp
- 3rdParty/iresearch/core/index/transaction_store.cpp
- 3rdParty/iresearch/core/iql/query_builder.cpp
- 3rdParty/iresearch/core/search/bm25.hpp
- 3rdParty/iresearch/core/search/boolean_filter.hpp
- 3rdParty/iresearch/core/search/tfidf.hpp
- 3rdParty/iresearch/core/store/data_input.hpp
- 3rdParty/iresearch/core/store/data_output.hpp
- 3rdParty/iresearch/core/store/fs_directory.cpp
- 3rdParty/iresearch/core/store/mmap_directory.hpp
- 3rdParty/iresearch/core/store/store_utils.hpp
- 3rdParty/iresearch/core/utils/fst_matcher.hpp
- 3rdParty/iresearch/core/utils/iterator.hpp
- 3rdParty/iresearch/core/utils/locale_utils.cpp
- 3rdParty/iresearch/core/utils/mmap_utils.cpp
Adds "override" where it makes sense and the compiler suggests it.
> added missing override specifiers

- arangod/Aql/CollectBlock.cpp
- arangod/Aql/OptimizerRules.cpp
- arangod/ClusterEngine/ClusterEngine.cpp
- arangod/ClusterEngine/ClusterEngine.h
- arangod/GeneralServer/GeneralCommTask.cpp
- arangod/RocksDBEngine/RocksDBCollection.cpp
- arangod/RocksDBEngine/RocksDBCollection.h
- arangod/RocksDBEngine/RocksDBEngine.cpp
- arangod/RocksDBEngine/RocksDBEngine.h
- arangod/RocksDBEngine/RocksDBRecoveryManager.cpp
- arangod/RocksDBEngine/RocksDBTransactionCollection.cpp
- arangod/StorageEngine/StorageEngine.h
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/2344/
> Do not load counters until recovey is done

- tests/Agency/CleanUpLostCollectionTest.cpp
- tests/Agency/CleanUpLostCollectionTest.json
> [3.4]Cleanup Lost Collections test bug fix

- tests/Agency/CleanUpLostCollectionTest.cpp
- tests/Agency/CleanUpLostCollectionTest.json
Fixes one of arangodb/release-3.4#67
> Cleanup Lost Collections test bug fix

- js/apps/system/_admin/aardvark/APP/frontend/js/templates/applicationsView.ejs
- js/apps/system/_admin/aardvark/APP/frontend/js/templates/viewsView.ejs
- js/apps/system/_admin/aardvark/APP/frontend/js/views/applicationsView.js
- js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
- js/apps/system/_admin/aardvark/APP/frontend/js/views/viewsView.js
In readonly mode disable the `New View/Service` Buttons. Fixed a stupid warning about lower case constructors.
Fixes arangodb/release-3.4#64
> Disable New View/Service in UI

- Documentation/Books/Manual/Programs/Arangod/Ldap.md
- arangod/Agency/Store.cpp
- arangod/Auth/TokenCache.cpp
- arangod/Auth/TokenCache.h
- arangod/Auth/User.cpp
- arangod/Auth/User.h
- arangod/Auth/UserManager.h
- arangod/GeneralServer/GeneralCommTask.cpp
- arangod/GeneralServer/HttpCommTask.cpp
- arangod/GeneralServer/VstCommTask.cpp
- arangod/Statistics/RequestStatistics.cpp
- arangod/VocBase/Methods/Databases.cpp
- lib/Logger/Logger.cpp
- lib/Logger/Logger.h
- lib/Logger/LoggerFeature.cpp
- lib/Logger/LoggerFeature.h
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/1401/
There is also an accompanying enterprise PR:
https://github.com/arangodb/enterprise/pull/155
> Bug fix 3.4/even more ldap debugging

- Documentation/Books/Manual/Programs/Arangod/Ldap.md
- arangod/Agency/Store.cpp
- arangod/Auth/TokenCache.cpp
- arangod/Auth/TokenCache.h
- arangod/Auth/User.cpp
- arangod/Auth/User.h
- arangod/Auth/UserManager.h
- arangod/GeneralServer/GeneralCommTask.cpp
- arangod/GeneralServer/HttpCommTask.cpp
- arangod/GeneralServer/VstCommTask.cpp
- arangod/Statistics/RequestStatistics.cpp
- arangod/VocBase/Methods/Databases.cpp
- lib/Logger/Logger.cpp
- lib/Logger/Logger.h
- lib/Logger/LoggerFeature.cpp
- lib/Logger/LoggerFeature.h
There is also an accompanying enterprise PR for this:
https://github.com/arangodb/enterprise/pull/156
> Bug fix/even more ldap debugging

- arangod/Aql/CollectBlock.cpp
- arangod/Aql/OptimizerRules.cpp
- arangod/ClusterEngine/ClusterEngine.cpp
- arangod/ClusterEngine/ClusterEngine.h
- arangod/GeneralServer/GeneralCommTask.cpp
- arangod/RocksDBEngine/RocksDBCollection.cpp
- arangod/RocksDBEngine/RocksDBCollection.h
- arangod/RocksDBEngine/RocksDBEngine.cpp
- arangod/RocksDBEngine/RocksDBEngine.h
- arangod/RocksDBEngine/RocksDBRecoveryManager.cpp
- arangod/RocksDBEngine/RocksDBTransactionCollection.cpp
- arangod/StorageEngine/StorageEngine.h
Backport of https://github.com/arangodb/arangodb/pull/6719 to 3.4
> Backport #6719 to 3.4

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/views/indicesView.js
This issue fixes the internal issue: 
- https://github.com/arangodb/planning/issues/1983
> Bug fix/internal issue 1983

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/views/indicesView.js
This issue fixes the internal issue: 
- https://github.com/arangodb/planning/issues/1983
> Bug fix 3.4/internal issue 1983

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/views/indicesView.js
This issue fixes the internal issue: 
- https://github.com/arangodb/planning/issues/1983
> Bug fix 3.3/internal issue 1983

- lib/SimpleHttpClient/GeneralClientConnection.cpp
- lib/SimpleHttpClient/SimpleHttpClient.cpp
> [3.3] Stop AgencyRequests on Shutdown

- js/apps/system/_admin/aardvark/APP/frontend/js/templates/supportView.ejs
> UI: Add Drivers & Integrations column + fix links for 3.4

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/views/settingsView.js
fixed https://github.com/arangodb/planning/issues/2764
> Bug fix/internal issue 2764

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/views/settingsView.js
fixed https://github.com/arangodb/planning/issues/2764
> Bug fix 3.3/internal issue 2764

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/views/settingsView.js
fixed https://github.com/arangodb/planning/issues/2764
> Bug fix 3.4/internal issue 2764

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/arango/arango.js
- js/apps/system/_admin/aardvark/APP/frontend/js/views/databaseView.js
- js/apps/system/_admin/aardvark/APP/frontend/js/views/graphManagementView.js
fixes: https://github.com/arangodb/planning/issues/2785
> Bug fix 3.3/internal issue 2785

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/arango/arango.js
- js/apps/system/_admin/aardvark/APP/frontend/js/views/databaseView.js
- js/apps/system/_admin/aardvark/APP/frontend/js/views/graphManagementView.js
- js/apps/system/_admin/aardvark/APP/frontend/js/views/viewsView.js
fixes: https://github.com/arangodb/planning/issues/2785
> Bug fix 3.4/internal issue 2785

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/arango/arango.js
- js/apps/system/_admin/aardvark/APP/frontend/js/views/databaseView.js
- js/apps/system/_admin/aardvark/APP/frontend/js/views/graphManagementView.js
- js/apps/system/_admin/aardvark/APP/frontend/js/views/viewsView.js
fixes: https://github.com/arangodb/planning/issues/2785
> Bug fix/internal issue 2785

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/views/graphViewer.js
fixed https://github.com/arangodb/planning/issues/2688
> Bug fix 3.4/internal issue 2688

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/collections/arangoDocuments.js
fixed: https://github.com/arangodb/planning/issues/2957
> fix internal issue #2957

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/views/graphViewer.js
fixed https://github.com/arangodb/planning/issues/2688
> Bug fix 3.3/internal issue 2688

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/collections/arangoDatabase.js
- js/apps/system/_admin/aardvark/APP/frontend/js/views/databaseView.js
fixed: https://github.com/arangodb/planning/issues/2992#issuecomment-420633739
> fixed a caching bug in IE11

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/routers/router.js
- js/apps/system/_admin/aardvark/APP/frontend/js/views/indicesView.js
fixes: https://github.com/arangodb/planning/issues/2035#issuecomment-426994864
> Bug fix 3.3/internal issue 2035

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/routers/router.js
- js/apps/system/_admin/aardvark/APP/frontend/js/views/indicesView.js
fixes: https://github.com/arangodb/planning/issues/2035#issuecomment-426994864
> Bug fix 3.4/internal issue 2035

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
this pr fixes: https://github.com/arangodb/planning/issues/2770
> Bug fix/internal issue 2770

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
this pr fixes: https://github.com/arangodb/planning/issues/2770
> Bug fix 3.3/internal issue 2770

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
this pr fixes: https://github.com/arangodb/planning/issues/2770
> Bug fix 3.4/internal issue 2770

- arangod/RestHandler/RestDocumentHandler.cpp
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-linux/2469/
> Do not ignore document revision on updates

- arangod/RestHandler/RestDocumentHandler.cpp
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-linux/2470/
> do not ignore document revision

- arangod/IResearch/IResearchView.cpp
- arangod/IResearch/IResearchView.h
- arangod/RestServer/FlushFeature.cpp
> Bug fix/arangosearch lock issue

- arangod/MMFiles/MMFilesIncrementalSync.h
- arangod/Pregel/Conductor.cpp
- arangod/Pregel/Conductor.h
- arangod/Pregel/Worker.cpp
- arangod/Pregel/Worker.h
- arangod/Replication/DatabaseInitialSyncer.cpp
- arangod/Replication/DatabaseInitialSyncer.h
- arangod/Replication/DatabaseTailingSyncer.cpp
- arangod/Replication/GlobalInitialSyncer.cpp
- arangod/Replication/GlobalInitialSyncer.h
- arangod/Replication/GlobalTailingSyncer.cpp
- arangod/Replication/InitialSyncer.cpp
- arangod/Replication/InitialSyncer.h
- arangod/Replication/TailingSyncer.cpp
- arangod/Replication/utilities.cpp
- arangod/Replication/utilities.h
- arangod/RocksDBEngine/RocksDBIncrementalSync.cpp
- lib/SimpleHttpClient/SimpleHttpClient.cpp
- lib/SimpleHttpClient/SimpleHttpClient.h
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/1543/
> Refactor stuff, add async batch extension task (#6875)

- js/client/modules/@arangodb/crash-utils.js
- js/client/modules/@arangodb/process-utils.js
- js/client/modules/@arangodb/test-utils.js
- js/client/modules/@arangodb/testing.js
> Don't talk to a server when we know its dead. Print current testsuite on Falure.

- 3rdParty/iresearch/core/utils/locale_utils.cpp
See https://github.com/arangodb/arangodb/pull/6883
> Fix compile error on clang

- lib/Basics/win-utils.cpp
> add missing include

- arangod/RocksDBEngine/RocksDBSettingsManager.cpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/1550/
> Do not delete ticks before counters

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/aardvark.js
- js/apps/system/_admin/aardvark/APP/frontend/js/views/dashboardView.js
same as: https://github.com/arangodb/arangodb/pull/6907
> Bug fix 3.4/check statistics before request

- arangod/RocksDBEngine/RocksDBIncrementalSync.cpp
- arangod/RocksDBEngine/RocksDBRestReplicationHandler.cpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/1575/
> Fix an intermediate commit error

- arangod/Auth/UserManager.cpp
- arangod/RestServer/BootstrapFeature.cpp
- arangod/RestServer/BootstrapFeature.h
> [3.4] Suppress startup warning about no user table.

- lib/SimpleHttpClient/SimpleHttpClient.cpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/1578/
> Fix SimpleHttpClient assertions

- Documentation/Books/Manual/DataModeling/Views/README.md
Internal ref: https://github.com/arangodb/planning/issues/3105
> Docs: Fix link to ArangoSearch main chapter

- arangod/IResearch/IResearchView.cpp
- arangod/RestServer/FlushFeature.cpp
> issue 485.1: reduce scope of lock in FlushFeature

- tests/js/server/resilience/moving-shards-with-arangosearch-view-cluster.js
Regards https://github.com/arangodb/release-3.4/issues/84
> [3.4] Fixed error num comparison

- tests/js/server/resilience/moving-shards-with-arangosearch-view-cluster.js
Regards https://github.com/arangodb/release-3.4/issues/84
> Fixed error num comparison

- arangod/Auth/UserManager.cpp
- arangod/RestServer/BootstrapFeature.cpp
- arangod/RestServer/BootstrapFeature.h
> Suppress startup warning about no user table.

- js/common/modules/jsunity.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/1594/
> Added timestamps to each test for jsUnity

- js/common/modules/jsunity.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/1595/
> Added timestamps to each test for jsUnity (3.4)

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/statistics.js
Statistics could not be displayed when one server of a group was ahead of the others.
> fixed gathering of coordinator statistics in a cluster environment

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/statistics.js
Statistics could not be displayed when one server of a group was ahead of the others.
> 3 4 fixed gathering of coordinator statistics in a cluster environment

- arangod/Graph/Graph.cpp
- arangod/Graph/Graph.h
- arangod/Graph/GraphManager.cpp
- tests/js/common/shell/shell-general-graph.js
- Improved the rename c++ function in gharial (only used in general graph currently) 
- added test 
Devel PR: https://github.com/arangodb/arangodb/pull/6451
> Bug fix 3 4/gharial  improvement rename

- Documentation/Books/AQL/ExecutionAndPerformance/Optimizer.md
- Documentation/Books/AQL/ExecutionAndPerformance/README.md
- Documentation/Books/AQL/Fundamentals/README.md
- Documentation/Books/AQL/Tutorial/Traversal.md
- Documentation/Books/AQL/Views/README.md
- Documentation/Books/Manual/Administration/Cluster/README.md
- Documentation/Books/Manual/Architecture/DeploymentModes/Cluster/README.md
- Documentation/Books/Manual/DataModeling/GraphsVerticesEdges.md
- Documentation/Books/Manual/Deployment/Cluster/README.md
- Documentation/Books/Manual/Graphs/GeneralGraphs/README.md
- Documentation/Books/Manual/Graphs/Pregel/README.md
- Documentation/Books/Manual/Graphs/SmartGraphs/README.md
- Documentation/Books/Manual/Graphs/Traversals/README.md
- Documentation/Books/Manual/Indexing/IndexBasics.md
- Documentation/Books/Manual/Indexing/WorkingWithIndexes.md
- Documentation/Books/Manual/Troubleshooting/Cluster/README.md
- Documentation/Books/Manual/Tutorials/README.md
> Doc - Training material links (#6683)

- arangod/GeneralServer/RestHandler.cpp
Fixed bad token generation when username is empty. 
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/1635/
> Cluster Proxy JWT Bug

- tests/js/server/resilience/moving-shards-with-arangosearch-view-cluster.js
http://jenkins01.arangodb.biz:8080/view/3.4/job/arangodb-3.4-linux-matrix/87/
> [3.4] More fixes for moving-shards-with-arangosearch-view-cluster.js

- 3rdParty/rocksdb/v5.16.X/include/rocksdb/utilities/transaction.h
- 3rdParty/rocksdb/v5.16.X/utilities/transactions/pessimistic_transaction.cc
- 3rdParty/rocksdb/v5.16.X/utilities/transactions/pessimistic_transaction.h
- arangod/Auth/TokenCache.cpp
- arangod/RocksDBEngine/RocksDBCollection.cpp
- arangod/RocksDBEngine/RocksDBCuckooIndexEstimator.h
- arangod/RocksDBEngine/RocksDBEngine.cpp
- arangod/RocksDBEngine/RocksDBTransactionCollection.cpp
- arangod/RocksDBEngine/RocksDBTransactionCollection.h
- arangod/RocksDBEngine/RocksDBTransactionState.cpp
- arangod/RocksDBEngine/RocksDBTransactionState.h
- lib/Basics/Exceptions.cpp
- lib/Basics/Exceptions.h
- lib/Basics/ScopeGuard.h
- tests/js/client/active-failover/basic.js
- tests/js/client/active-failover/readonly.js
- tests/js/server/recovery/nosync-rangedelete-truncate-multi-rocksdb.js
- tests/js/server/shell/shell-collection-rocksdb-failures-noncluster.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/1639/
> Propper commit Sequence Numbers (#6958)

- arangod/GeneralServer/RestHandler.cpp
> [3.3] Cluster Proxy JWT Bug

- CHANGELOG
- arangod/Aql/Ast.cpp
- arangod/RocksDBEngine/RocksDBTransactionManager.h
- arangod/RocksDBEngine/RocksDBTransactionState.cpp
- tests/js/server/aql/aql-queries-simple.js
first commit in this PR is unrelated to the problem, just an optimization for which I was too lazy to create a separate PR
> Bug fix 3.4/fix array sorting

- 3rdParty/iresearch/core/error/error.cpp
- 3rdParty/iresearch/core/error/error.hpp
- 3rdParty/iresearch/core/formats/format_utils.cpp
- 3rdParty/iresearch/core/formats/format_utils.hpp
- 3rdParty/iresearch/core/formats/formats_10.cpp
- 3rdParty/iresearch/core/formats/formats_burst_trie.cpp
- 3rdParty/iresearch/core/formats/skip_list.cpp
- 3rdParty/iresearch/core/index/directory_reader.cpp
- 3rdParty/iresearch/core/index/index_writer.cpp
- 3rdParty/iresearch/core/index/merge_writer.cpp
- 3rdParty/iresearch/core/shared.hpp
- 3rdParty/iresearch/core/store/directory_attributes.hpp
- 3rdParty/iresearch/core/store/fs_directory.cpp
- 3rdParty/iresearch/core/utils/compression.cpp
- 3rdParty/iresearch/core/utils/directory_utils.cpp
- 3rdParty/iresearch/core/utils/locale_utils.cpp
- 3rdParty/iresearch/core/utils/ref_counter.hpp
- 3rdParty/iresearch/core/utils/utf8_path.cpp
- 3rdParty/iresearch/tests/formats/formats_test_case_base.hpp
- 3rdParty/iresearch/tests/index/consolidation_policy_tests.cpp
- 3rdParty/iresearch/tests/index/index_tests.cpp
- arangod/IResearch/IResearchView.cpp
- arangod/RestHandler/RestViewHandler.cpp
> issue 2921: make error message more detailed

- 3rdParty/iresearch/core/analysis/text_token_stream.cpp
- 3rdParty/iresearch/core/error/error.cpp
- 3rdParty/iresearch/core/error/error.hpp
- 3rdParty/iresearch/core/formats/format_utils.cpp
- 3rdParty/iresearch/core/formats/format_utils.hpp
- 3rdParty/iresearch/core/formats/formats_10.cpp
- 3rdParty/iresearch/core/formats/formats_burst_trie.cpp
- 3rdParty/iresearch/core/formats/skip_list.cpp
- 3rdParty/iresearch/core/index/directory_reader.cpp
- 3rdParty/iresearch/core/index/index_writer.cpp
- 3rdParty/iresearch/core/index/merge_writer.cpp
- 3rdParty/iresearch/core/shared.hpp
- 3rdParty/iresearch/core/store/directory_attributes.hpp
- 3rdParty/iresearch/core/store/fs_directory.cpp
- 3rdParty/iresearch/core/utils/compression.cpp
- 3rdParty/iresearch/core/utils/directory_utils.cpp
- 3rdParty/iresearch/core/utils/index_utils.cpp
- 3rdParty/iresearch/core/utils/locale_utils.cpp
- 3rdParty/iresearch/core/utils/object_pool.hpp
- 3rdParty/iresearch/core/utils/ref_counter.hpp
- 3rdParty/iresearch/core/utils/utf8_path.cpp
- 3rdParty/iresearch/tests/formats/formats_test_case_base.hpp
- 3rdParty/iresearch/tests/index/consolidation_policy_tests.cpp
- 3rdParty/iresearch/tests/index/index_tests.cpp
- 3rdParty/iresearch/tests/index/merge_writer_tests.cpp
- arangod/IResearch/IResearchView.cpp
- arangod/RestHandler/RestViewHandler.cpp
> Bug fix 3.4/internal issue #2921

- 3rdParty/velocypack/src/Validator.cpp
- 3rdParty/velocypack/src/asm-functions.cpp
- 3rdParty/velocypack/src/asm-functions.h
- 3rdParty/velocypack/src/asm-utf8check.cpp
- 3rdParty/velocypack/src/asm-utf8check.h
- arangod/Aql/RestAqlHandler.cpp
- arangod/RestServer/ServerFeature.cpp
- arangod/RestServer/ServerFeature.h
- arangosh/Shell/ClientFeature.cpp
- arangosh/Shell/ClientFeature.h
- lib/CMakeLists.txt
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/1669/
> Use SSE42 for UTF-8 string validation

- Documentation/Books/Manual/BackupRestore/README.md
Internal ref:
https://github.com/arangodb/planning/issues/3042
@sleto-it Made the last part a red hint box. We could also add another (maybe just a yellow one?) about possible data loss if you want.
http://jenkins01.arangodb.biz:8080/job/arangodb-documentation/113/
> Highlight importance of backups

- Documentation/Books/Manual/BackupRestore/README.md
> Doc - Highlight importance of backups (#7007)

- arangod/RocksDBEngine/RocksDBCollection.cpp
- arangod/RocksDBEngine/RocksDBRecoveryManager.cpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/2686/
> Truncate index extimate fix

- 3rdParty/iresearch/.travis.yml
- 3rdParty/iresearch/core/analysis/token_streams.cpp
- 3rdParty/iresearch/core/error/error.hpp
- 3rdParty/iresearch/core/formats/format_utils.cpp
- 3rdParty/iresearch/core/formats/format_utils.hpp
- 3rdParty/iresearch/core/formats/formats_10.cpp
- 3rdParty/iresearch/core/formats/formats_burst_trie.cpp
- 3rdParty/iresearch/core/index/directory_reader.cpp
- 3rdParty/iresearch/core/index/index_writer.cpp
- 3rdParty/iresearch/core/index/transaction_store.cpp
- 3rdParty/iresearch/core/store/fs_directory.cpp
- 3rdParty/iresearch/core/store/store_utils.cpp
- 3rdParty/iresearch/core/utils/compression.cpp
- 3rdParty/iresearch/core/utils/directory_utils.cpp
- 3rdParty/iresearch/core/utils/directory_utils.hpp
- 3rdParty/iresearch/core/utils/locale_utils.cpp
- 3rdParty/iresearch/core/utils/ref_counter.hpp
- 3rdParty/iresearch/core/utils/string.hpp
- 3rdParty/iresearch/core/utils/string_utils.hpp
- 3rdParty/iresearch/tests/utils/block_pool_test.cpp
- 3rdParty/iresearch/tests/utils/ref_counter_tests.cpp
> [3.4] fix ASAN issues in arangosearch

- 3rdParty/iresearch/.travis.yml
- 3rdParty/iresearch/core/analysis/token_streams.cpp
- 3rdParty/iresearch/core/error/error.hpp
- 3rdParty/iresearch/core/formats/format_utils.cpp
- 3rdParty/iresearch/core/formats/format_utils.hpp
- 3rdParty/iresearch/core/formats/formats_10.cpp
- 3rdParty/iresearch/core/formats/formats_burst_trie.cpp
- 3rdParty/iresearch/core/index/directory_reader.cpp
- 3rdParty/iresearch/core/index/index_writer.cpp
- 3rdParty/iresearch/core/index/transaction_store.cpp
- 3rdParty/iresearch/core/store/fs_directory.cpp
- 3rdParty/iresearch/core/store/store_utils.cpp
- 3rdParty/iresearch/core/utils/compression.cpp
- 3rdParty/iresearch/core/utils/directory_utils.cpp
- 3rdParty/iresearch/core/utils/directory_utils.hpp
- 3rdParty/iresearch/core/utils/locale_utils.cpp
- 3rdParty/iresearch/core/utils/ref_counter.hpp
- 3rdParty/iresearch/core/utils/string.hpp
- 3rdParty/iresearch/core/utils/string_utils.hpp
- 3rdParty/iresearch/tests/utils/block_pool_test.cpp
- 3rdParty/iresearch/tests/utils/ref_counter_tests.cpp
> fix ASAN issues in arangosearch

- arangod/Aql/Functions.cpp
Should fix https://github.com/arangodb/release-3.4/issues/109
> fix release-3.4 issue 109

- Documentation/Books/Manual/Programs/FoxxCLI/README.md
Internal ref: https://github.com/arangodb/planning/issues/2879
> Foxx CLI: Add link to blog post

- CHANGELOG
- Documentation/DocuBlocks/Rest/Foxx/api_foxx_service_upgrade.md
- js/apps/system/_api/foxx/APP/index.js
- js/server/modules/@arangodb/foxx/manager.js
- js/server/modules/@arangodb/foxx/routing.js
- js/server/modules/@arangodb/foxx/service.js
- tests/js/client/shell/shell-foxx-api-spec.js
- tests/js/common/test-data/apps/fails-on-mount/index.js
- tests/js/common/test-data/apps/fails-on-mount/manifest.json
> Fix Foxx API handling of broken services (3.4)

- arangod/Agency/AgencyComm.cpp
- arangod/Agency/AgencyComm.h
- arangod/Cluster/HeartbeatThread.cpp
- arangod/VocBase/Methods/Databases.cpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/1702/
> Better agency pool update

- tests/js/common/aql/aql-view-arangosearch-ddl-cluster.js
- tests/js/common/aql/aql-view-arangosearch-ddl-noncluster.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/1710/
> Execute all ArangoSearch DDL tests on both cluster and single (3.4)

- tests/js/common/aql/aql-view-arangosearch-ddl-cluster.js
- tests/js/common/aql/aql-view-arangosearch-ddl-noncluster.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/1709/
> Execute all ArangoSearch DDL tests on both cluster and single

- Documentation/Books/Manual/ReleaseNotes/KnownIssues34.md
> update ArangoSearch known issues

- arangod/Agency/Agent.cpp
- arangod/Agency/State.cpp
- arangod/Aql/EngineInfoContainerDBServer.cpp
- arangod/Aql/QueryCursor.cpp
- arangod/Cluster/ClusterComm.cpp
- arangod/GeneralServer/GeneralServerFeature.cpp
- arangod/Graph/GraphManager.cpp
- arangod/Graph/GraphOperations.cpp
- arangod/RestHandler/RestReplicationHandler.cpp
- arangod/RestServer/AqlFeature.cpp
- arangod/RestServer/DatabaseFeature.cpp
- arangod/RestServer/QueryRegistryFeature.cpp
- arangod/RestServer/QueryRegistryFeature.h
- arangod/RestServer/TraverserEngineRegistryFeature.cpp
- arangod/RestServer/TraverserEngineRegistryFeature.h
- arangod/RocksDBEngine/RocksDBRecoveryManager.cpp
- arangod/RocksDBEngine/RocksDBRecoveryManager.h
- arangod/RocksDBEngine/RocksDBRestHandlers.cpp
- arangod/VocBase/Methods/AqlUserFunctions.cpp
- arangod/VocBase/Methods/Collections.cpp
- arangosh/Shell/V8ClientConnection.cpp
- arangosh/Shell/V8ClientConnection.h
- lib/Logger/LogAppender.cpp
- tests/IResearch/ExecutionBlockMock-test.cpp
- tests/IResearch/IResearchViewCoordinator-test.cpp
- tests/IResearch/IResearchViewNode-test.cpp
- tests/IResearch/common.cpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/1708/
> Silence tsan warnings

- js/actions/_admin/foxx/app.js
- tests/js/server/shell/shell-foxx-routing-consistency-spec.js
> if we run in maintainer mode, be more patient

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/views/graphViewer.js
- js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
same as https://github.com/arangodb/arangodb/pull/7057
> Bug fix 3.4/ui graph parsing

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/views/graphViewer.js
- js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
same as https://github.com/arangodb/arangodb/pull/7057
> Bug fix 3.3/ui graph parsing

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/views/graphManagementView.js
- js/apps/system/_admin/aardvark/APP/frontend/js/views/viewsView.js
same as https://github.com/arangodb/arangodb/pull/7067
> Bug fix 3.4/ui events routing

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/views/graphManagementView.js
same as https://github.com/arangodb/arangodb/pull/7067 (except the arangosearch views)
> Bug fix 3.3/ui events routing

- arangod/ClusterEngine/ClusterEngine.cpp
- tests/IResearch/common.cpp
This hopefully fixes some issues in the Windows version of the catch tests.
This is only a guess, so it should be manually tried and confirmed.
> potentially fix failing Windows catch test

- 3rdParty/iresearch/core/index/index_writer.cpp
- arangod/ClusterEngine/ClusterIndex.h
- arangod/IResearch/IResearchLink.cpp
- arangod/IResearch/IResearchLink.h
- arangod/IResearch/IResearchLinkCoordinator.h
- arangod/IResearch/IResearchMMFilesLink.h
- arangod/IResearch/IResearchRocksDBLink.h
- arangod/IResearch/IResearchRocksDBRecoveryHelper.cpp
- arangod/Indexes/Index.h
- arangod/MMFiles/MMFilesCollection.cpp
- arangod/MMFiles/MMFilesIndex.h
- arangod/RocksDBEngine/RocksDBCollection.cpp
- arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
- arangod/RocksDBEngine/RocksDBEdgeIndex.h
- arangod/RocksDBEngine/RocksDBIndex.cpp
- arangod/RocksDBEngine/RocksDBIndex.h
- arangod/RocksDBEngine/RocksDBVPackIndex.cpp
- arangod/RocksDBEngine/RocksDBVPackIndex.h
- tests/IResearch/StorageEngineMock.cpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/1751/
> Fixing truncate index estimates (Try 4)

- 3rdParty/iresearch/core/index/index_writer.cpp
- arangod/ClusterEngine/ClusterIndex.h
- arangod/IResearch/IResearchLink.cpp
- arangod/IResearch/IResearchLink.h
- arangod/IResearch/IResearchLinkCoordinator.h
- arangod/IResearch/IResearchMMFilesLink.h
- arangod/IResearch/IResearchRocksDBLink.h
- arangod/IResearch/IResearchRocksDBRecoveryHelper.cpp
- arangod/Indexes/Index.h
- arangod/MMFiles/MMFilesCollection.cpp
- arangod/MMFiles/MMFilesIndex.h
- arangod/RocksDBEngine/RocksDBCollection.cpp
- arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
- arangod/RocksDBEngine/RocksDBEdgeIndex.h
- arangod/RocksDBEngine/RocksDBIndex.cpp
- arangod/RocksDBEngine/RocksDBIndex.h
- arangod/RocksDBEngine/RocksDBVPackIndex.cpp
- arangod/RocksDBEngine/RocksDBVPackIndex.h
- tests/IResearch/StorageEngineMock.cpp
(cherry picked from commit 7113e779fbc5b905107a69839973a25f5d6842d9)
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/1763/
> Next try at truncate (#7090)

- arangod/Cache/CacheManagerFeature.cpp
- arangod/Cluster/ClusterComm.cpp
- arangod/Cluster/ClusterComm.h
- arangod/GeneralServer/GeneralCommTask.cpp
- arangod/GeneralServer/RequestLane.h
- arangod/GeneralServer/RestHandler.cpp
- arangod/GeneralServer/RestHandler.h
- arangod/MMFiles/MMFilesCollection.cpp
- arangod/Pregel/Conductor.cpp
- arangod/Pregel/GraphStore.cpp
- arangod/Pregel/PregelFeature.cpp
- arangod/Pregel/Recovery.cpp
- arangod/Pregel/Worker.cpp
- arangod/Replication/Syncer.cpp
- arangod/RestHandler/RestBatchHandler.cpp
- arangod/RestHandler/RestTestHandler.cpp
- arangod/Scheduler/Scheduler.cpp
- arangod/Scheduler/Scheduler.h
- arangod/Scheduler/SchedulerFeature.cpp
- arangod/VocBase/LogicalCollection.cpp
- arangod/VocBase/Methods/Collections.cpp
- arangod/VocBase/Methods/Tasks.cpp
- js/apps/system/_admin/aardvark/APP/frontend/js/routers/startApp.js
- lib/Basics/StaticStrings.cpp
- lib/Basics/StaticStrings.h
- lib/SimpleHttpClient/Callbacks.h
- lib/SimpleHttpClient/Communicator.cpp
- lib/SimpleHttpClient/Communicator.h
- tests/Cluster/ClusterCommTest.cpp
This includes the second half of jsteeman's MEDIUM scheduler changes and recent tunings to original 3.4 Scheduler back port.
> Bugfix:  More 3.4 scheduler changes backported

- arangod/Cluster/ClusterComm.cpp
- arangod/Cluster/ClusterComm.h
- lib/SimpleHttpClient/Communicator.cpp
https://github.com/arangodb/release-3.4/issues/102
> [3.3] Stop curl from trying to POST stdin

- arangod/Cluster/ClusterComm.cpp
- arangod/Cluster/ClusterComm.h
- lib/SimpleHttpClient/Communicator.cpp
See https://github.com/arangodb/release-3.4/issues/102.
CI is green: http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/1760/
> [3.4] Stop curl from trying to POST stdin

- arangod/Cluster/ClusterComm.cpp
- lib/SimpleHttpClient/Communicator.cpp
https://github.com/arangodb/release-3.4/issues/102
> Stop curl from trying to POST stdin

- 3rdParty/iresearch/core/error/error.hpp
- 3rdParty/iresearch/core/formats/formats_10.cpp
- 3rdParty/iresearch/core/index/index_writer.cpp
- 3rdParty/iresearch/core/utils/string_utils.hpp
- 3rdParty/iresearch/core/utils/timer_utils.cpp
- 3rdParty/iresearch/core/utils/timer_utils.hpp
- 3rdParty/iresearch/tests/formats/formats_10_tests.cpp
- 3rdParty/iresearch/tests/index/index_profile_tests.cpp
- 3rdParty/iresearch/tests/index/transaction_store_tests.cpp
- 3rdParty/iresearch/tests/tests_main.cpp
- 3rdParty/iresearch/tests/tests_shared.hpp
- 3rdParty/iresearch/tests/utils/memory_tests.cpp
> [3.4] update iresearch

- arangod/Cluster/SynchronizeShard.cpp
- arangod/Replication/DatabaseInitialSyncer.cpp
- arangod/Replication/utilities.cpp
- arangod/Replication/utilities.h
- arangod/RocksDBEngine/RocksDBIterators.cpp
- arangod/RocksDBEngine/RocksDBIterators.h
- arangod/RocksDBEngine/RocksDBReplicationContext.cpp
- arangod/RocksDBEngine/RocksDBReplicationContext.h
- arangod/RocksDBEngine/RocksDBReplicationManager.cpp
- arangod/RocksDBEngine/RocksDBReplicationManager.h
- arangod/RocksDBEngine/RocksDBRestReplicationHandler.cpp
- arangod/RocksDBEngine/RocksDBTransactionState.cpp
- arangod/RocksDBEngine/RocksDBTransactionState.h
- arangod/Transaction/Context.cpp
- arangod/Transaction/Context.h
- arangod/Transaction/SmartContext.cpp
- arangod/Transaction/StandaloneContext.cpp
- arangod/Transaction/V8Context.cpp
- tests/js/client/shell/shell-rep_li_cat_ion-rocksdb-noncluster.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/1752/
- Allow parallel dump & incremental sync
- Allow us to patch the collection count
> RocksDB replication thread safety

- 3rdParty/fuerte/src/Basics/Format.h
- arangod/RocksDBEngine/RocksDBFormat.h
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/1773/
> Fix undefined behaviour

- CHANGELOG
- arangod/Cluster/ClusterInfo.cpp
Reverts arangodb/arangodb#7104
> Revert "fixes some misbehaviour within the coordinator agency callbacks"

- 3rdParty/iresearch/core/search/filter.hpp
- arangod/CMakeLists.txt
- arangod/IResearch/IResearchDocument.cpp
- arangod/IResearch/IResearchDocument.h
- arangod/IResearch/IResearchFilterFactory.cpp
- arangod/IResearch/IResearchFilterFactory.h
- arangod/IResearch/IResearchPrimaryKeyFilter.cpp
- arangod/IResearch/IResearchPrimaryKeyFilter.h
- arangod/IResearch/IResearchView.cpp
- arangod/IResearch/IResearchView.h
- tests/IResearch/ExpressionFilter-test.cpp
- tests/IResearch/IResearchDocument-test.cpp
> [3.4] arangosearch speedup removals

- arangod/Aql/Condition.cpp
- arangod/Aql/EngineInfoContainerDBServer.cpp
- arangod/Aql/ExecutionStats.cpp
- arangod/Aql/Expression.cpp
- arangod/Aql/Functions.cpp
- arangod/Aql/IndexBlock.cpp
- arangod/Aql/PlanCache.cpp
- arangod/Aql/QueryCache.cpp
- arangod/Aql/QueryList.cpp
- arangod/Aql/QueryRegistry.cpp
- arangod/Cluster/ClusterMethods.cpp
- arangod/GeneralServer/GeneralCommTask.cpp
- arangod/GeoIndex/Near.cpp
- arangod/Graph/Graph.cpp
- arangod/Graph/GraphCache.cpp
- arangod/Indexes/SkiplistIndexAttributeMatcher.cpp
- arangod/MMFiles/MMFilesCollectorCache.h
- arangod/MMFiles/MMFilesEngine.cpp
- arangod/Pregel/AggregatorHandler.cpp
- arangod/Pregel/Algos/SLPA.cpp
- arangod/RestHandler/RestReplicationHandler.cpp
This is an import of @mpoeter 's PR https://github.com/arangodb/arangodb/pull/7123 into our repository for testing.
> Bug fix/refactor find emplace

- arangod/Aql/QueryCursor.cpp
- arangod/Aql/QueryCursor.h
- arangod/MMFiles/MMFilesExportCursor.cpp
- arangod/Replication/InitialSyncer.cpp
- arangod/RestHandler/RestCursorHandler.cpp
- arangod/Transaction/Methods.cpp
- arangod/Transaction/Methods.h
- arangod/Transaction/V8Context.cpp
- arangod/Utils/Cursor.h
- arangod/Utils/CursorRepository.cpp
- arangod/Utils/CursorRepository.h
- arangod/V8Server/V8DealerFeature.cpp
- arangod/V8Server/v8-users.cpp
- arangod/V8Server/v8-voccursor.cpp
- arangod/VocBase/Methods/Transactions.cpp
- js/server/bootstrap/modules/internal.js
- js/server/modules/@arangodb/arango-statement.js
- lib/V8/v8-globals.cpp
- lib/V8/v8-globals.h
- tests/js/common/shell/shell-query-stream-timecritical-spec.js
- tests/js/common/shell/shell-query-stream.js
- tests/js/common/shell/shell-transactions.js
(cherry picked from commit b883026f4564ad7add1702279dc96b2e0bc1ebee)
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/2931/
> Server stream cursor (#7186)

- arangod/Cluster/DBServerAgencySync.cpp
- arangod/Transaction/Methods.cpp
(cherry picked from commit 99ba608be98a44b8ce1d0e681107271a22f42761)
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/2924/
> Fix a crash in DBServerAgencySync

- arangod/ClusterEngine/ClusterTransactionCollection.cpp
- arangod/ClusterEngine/ClusterTransactionCollection.h
- arangod/MMFiles/MMFilesTransactionCollection.cpp
- arangod/MMFiles/MMFilesWalRecoverState.cpp
- arangod/MMFiles/MMFilesWalRecoverState.h
- arangod/Replication/Syncer.cpp
- arangod/Replication/TailingSyncer.cpp
- arangod/RocksDBEngine/RocksDBReplicationContext.cpp
- arangod/RocksDBEngine/RocksDBReplicationContext.h
- arangod/RocksDBEngine/RocksDBReplicationTailing.cpp
- arangod/RocksDBEngine/RocksDBTransactionCollection.cpp
- arangod/StorageEngine/TransactionCollection.h
- arangod/Utils/CollectionGuard.h
- arangod/VocBase/vocbase.cpp
- arangod/VocBase/vocbase.h
- tests/IResearch/StorageEngineMock.cpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/1935/
also make sure collections are not dropped during replication
> Use shared_ptr for LogicalCollection

- js/common/modules/@arangodb/aql/explainer.js
> [3.4] Fix query profiling discrepancy in console.

- js/server/modules/@arangodb/aql-profiler-test-helper.js
- tests/js/server/aql/aql-profiler-noncluster.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/1943/
> Add view profiling tests (3.4)

- js/server/modules/@arangodb/aql-profiler-test-helper.js
- tests/js/server/aql/aql-profiler-noncluster.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/1942/
> Add view profiling tests

- tests/js/client/authentication/user-access-right-task-update-view-arangosearch-spec.js
- tests/js/client/authentication/user-access-right-update-view-arangosearch-spec.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/1952/
> Fix update-view-arangosearch-spec tests

- tests/js/client/authentication/user-access-right-task-update-view-arangosearch-spec.js
- tests/js/client/authentication/user-access-right-update-view-arangosearch-spec.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/1953/
> Fix update-view-arangosearch-spec tests (3.4)

- arangod/Cluster/ClusterInfo.cpp
- arangod/Sharding/ShardingInfo.cpp
- tests/IResearch/IResearchLinkCoordinator-test.cpp
- tests/IResearch/IResearchViewCoordinator-test.cpp
(cherry picked from commit 386fc0e9adb12198f8d0724e6ea2533268c82a94)
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/2992/
> Simplify dropDatabaseCoordinator & fix some bugs (#7211)

- arangod/ClusterEngine/ClusterTransactionCollection.cpp
- arangod/ClusterEngine/ClusterTransactionCollection.h
- arangod/MMFiles/MMFilesTransactionCollection.cpp
- arangod/MMFiles/MMFilesWalRecoverState.cpp
- arangod/MMFiles/MMFilesWalRecoverState.h
- arangod/Replication/Syncer.cpp
- arangod/Replication/TailingSyncer.cpp
- arangod/RocksDBEngine/RocksDBReplicationContext.cpp
- arangod/RocksDBEngine/RocksDBReplicationContext.h
- arangod/RocksDBEngine/RocksDBReplicationTailing.cpp
- arangod/RocksDBEngine/RocksDBTransactionCollection.cpp
- arangod/StorageEngine/TransactionCollection.h
- arangod/Utils/CollectionGuard.h
- arangod/VocBase/vocbase.cpp
- arangod/VocBase/vocbase.h
- tests/IResearch/StorageEngineMock.cpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/2993/
> Use shared_ptr for LogicalCollection (#7220)

- arangod/CMakeLists.txt
- arangod/IResearch/ExpressionFilter.cpp
- arangod/IResearch/ExpressionFilter.h
- arangod/IResearch/IResearchExpressionContext.cpp
- arangod/IResearch/IResearchExpressionContext.h
- arangod/IResearch/IResearchViewBlock.cpp
- arangod/IResearch/IResearchViewBlock.h
- tests/IResearch/ExpressionContextMock.cpp
- tests/IResearch/ExpressionContextMock.h
- tests/IResearch/IResearchQueryJoin-test.cpp
> bug-fix/internal-issue-#6289

- arangod/CMakeLists.txt
- arangod/IResearch/ExpressionFilter.cpp
- arangod/IResearch/ExpressionFilter.h
- arangod/IResearch/IResearchExpressionContext.cpp
- arangod/IResearch/IResearchExpressionContext.h
- arangod/IResearch/IResearchViewBlock.cpp
- arangod/IResearch/IResearchViewBlock.h
- tests/IResearch/ExpressionContextMock.h
- tests/IResearch/IResearchQueryJoin-test.cpp
> Bug fix 3.4/internal issue #6289

- js/client/modules/@arangodb/testsuites/endpoints.js
backport https://github.com/arangodb/arangodb/pull/7254
> Bugfix 3.4/fix typo in endpoints test

- arangod/IResearch/IResearchFeature.cpp
> make ArangoSearch error messages more descriptive

- arangod/IResearch/IResearchFeature.cpp
> [3.4] make ArangoSearch error messages more descriptive

- arangod/Cluster/ClusterFeature.cpp
* Start ClusterComm threads in `ClusterFeature::start`. Stop ClusterComm threads in `ClusterFeature::stop`.
* Do not free objects in `Scheduler::shutdown`. Let the `unique_ptr` do their job. Stop ClusterComm threads in `ClusterFeature::stop`, but free instance in `ClusterFeature::unprepare`.
* `io_context` may contains lambdas that hold `shared_ptr`s to `Tasks` the required a functional `VocBase` in their destructor.
> Port bug fix 3.4/cluster comm threads start stop (#6939) to devel.

- tests/js/common/shell/shell-index.js
> add more information when timeout failing the index creation tests

- arangod/Cluster/SynchronizeShard.cpp
Should address https://github.com/arangodb/release-3.4/issues/142.
> [3.4] Fix nullptr dereference in SynchronizeShard.

- CHANGELOG
- js/server/modules/@arangodb/foxx/queues/worker.js
- tests/js/server/shell/shell-foxx-queues.js
> Fix Foxx Queues infinite maxFailures (3.4)

- arangod/Cluster/ClusterFeature.cpp
- lib/Basics/win-utils.cpp
> fix buffer overrun, remove unused variable

- 3rdParty/iresearch/core/shared.hpp
- 3rdParty/iresearch/core/utils/locale_utils.cpp
- 3rdParty/iresearch/core/utils/locale_utils.hpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-windows-onlycatch/9/
> Bug fix/fix vs15.9 codecvt macro

- 3rdParty/iresearch/core/shared.hpp
- 3rdParty/iresearch/core/utils/locale_utils.cpp
- 3rdParty/iresearch/core/utils/locale_utils.hpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-windows-onlycatch/10/
> Bug fix/fix vs15.9 codecvt macro (3.4)

- arangosh/Shell/V8ClientConnection.cpp
this should fix https://github.com/arangodb/planning/issues/3225
> print "401 unauthorized" message again

- arangod/GeneralServer/GeneralCommTask.cpp
Allow accessing _api/cluser/endpoints as authenticated user via the _system database.
Port of #7342
> Endpoints via _system

- arangod/GeneralServer/GeneralCommTask.cpp
Allow accessing `_api/cluser/endpoints` as authenticated user via the `_system` database.
> [3.3] Endpoints via _system

- arangod/GeneralServer/GeneralCommTask.cpp
Allow accessing _api/cluser/endpoints as authenticated user via the _system database.
Port of #7342
> [3.2] Endpoints via _system

- arangod/MMFiles/MMFilesCollection.cpp
- arangod/MMFiles/MMFilesCollection.h
- arangod/VocBase/LogicalCollection.h
- js/common/modules/@arangodb/aql/explainer.js
> [3.4] Updates to collection versioning.

- Documentation/Books/Manual/Administration/ActiveFailover/README.md
- Documentation/Books/Manual/Architecture/DeploymentModes/ActiveFailover/Architecture.md
see: https://github.com/arangodb/planning/issues/3198
> added ":true" to "X-Arango-Allow-Dirty-Read" header

- arangod/Cluster/SynchronizeShard.cpp
- arangod/Replication/TailingSyncer.cpp
- arangod/RocksDBEngine/RocksDBCollection.cpp
- arangod/RocksDBEngine/RocksDBCollection.h
- arangod/RocksDBEngine/RocksDBCommon.cpp
- arangod/RocksDBEngine/RocksDBEngine.cpp
- arangod/RocksDBEngine/RocksDBMethods.cpp
- arangod/RocksDBEngine/RocksDBMethods.h
- arangod/RocksDBEngine/RocksDBRecoveryManager.cpp
- arangod/RocksDBEngine/RocksDBTransactionState.h
- arangod/RocksDBEngine/RocksDBWalAccess.cpp
- lib/ApplicationFeatures/RocksDBOptionFeature.cpp
- tests/js/server/replication/replication-ongoing-32.js
- tests/js/server/replication/replication-ongoing-global-spec.js
- tests/js/server/replication/replication-ongoing-global.js
- tests/js/server/replication/replication-ongoing.js
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-linux/3201/
> Faster index creation

- arangod/IResearch/IResearchLinkHelper.cpp
- arangod/IResearch/IResearchView.cpp
- arangod/IResearch/IResearchViewCoordinator.cpp
- arangod/MMFiles/MMFilesCollection.cpp
- arangod/RocksDBEngine/RocksDBCollection.cpp
> Hide internal link properties

- arangod/Cluster/SynchronizeShard.cpp
- arangod/Replication/TailingSyncer.cpp
- arangod/RocksDBEngine/RocksDBCollection.cpp
- arangod/RocksDBEngine/RocksDBCollection.h
- arangod/RocksDBEngine/RocksDBCommon.cpp
- arangod/RocksDBEngine/RocksDBEngine.cpp
- arangod/RocksDBEngine/RocksDBMethods.cpp
- arangod/RocksDBEngine/RocksDBMethods.h
- arangod/RocksDBEngine/RocksDBTransactionState.h
- arangod/RocksDBEngine/RocksDBWalAccess.cpp
- tests/js/server/replication/replication-ongoing-32.js
- tests/js/server/replication/replication-ongoing-global-spec.js
- tests/js/server/replication/replication-ongoing-global.js
- tests/js/server/replication/replication-ongoing.js
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-linux/3241/
> Faster index creation (#7348)

- README.md
> Changed Link to Design Objectives

- arangod/Aql/AqlFunctionFeature.cpp
- arangod/Aql/AqlFunctionFeature.h
- arangod/Cluster/ServerState.cpp
- arangod/IResearch/ApplicationServerHelper.cpp
> Bug fix/less exceptions

- js/client/modules/@arangodb/testsuites/readOnly.js
(cherry picked from commit 800acadfcabc508cf9c65a18e7c0032b4bfb0c62)
> add timeout

- arangod/Aql/Query.cpp
- arangod/RocksDBEngine/RocksDBCollection.cpp
- arangod/RocksDBEngine/RocksDBIndex.cpp
- arangod/RocksDBEngine/RocksDBMethods.h
- arangod/RocksDBEngine/RocksDBVPackIndex.cpp
- arangod/Transaction/Hints.h
- arangod/Transaction/Methods.h
> disable RocksDB indexing for some secondary index operations

- js/client/modules/@arangodb/process-utils.js
> Bug fix 3.3/log dump output

- js/apps/system/_admin/aardvark/APP/frontend/js/arango/arango.js
- js/apps/system/_admin/aardvark/APP/frontend/js/collections/arangoViews.js
- js/apps/system/_admin/aardvark/APP/frontend/js/models/arangoViewModel.js
- js/apps/system/_admin/aardvark/APP/frontend/js/routers/router.js
- js/apps/system/_admin/aardvark/APP/frontend/js/templates/viewView.ejs
- js/apps/system/_admin/aardvark/APP/frontend/js/views/collectionsView.js
- js/apps/system/_admin/aardvark/APP/frontend/js/views/viewView.js
- js/apps/system/_admin/aardvark/APP/frontend/js/views/viewsView.js
This PR optimizes the ArangoSearch UI in the Web Interface.
If all looks good, needs a PR for 3.4, too.
Same as: https://github.com/arangodb/arangodb/pull/7354
> use of job api for patching and removing views #7354

- tests/js/server/shell/shell-collection-rocksdb-failures-noncluster.js
add some more tests for intermediate commits
> add some more intermediate commit tests

- Documentation/Books/Manual/DataModeling/OperationalFactors.md
- Documentation/Books/Manual/ReleaseNotes/NewFeatures34.md
- Documentation/Books/Manual/SUMMARY.md
- Documentation/Books/Manual/Transactions/Limitations.md
http://jenkins01.arangodb.biz:8080/job/arangodb-documentation/132/
> Operational factors [3.4]

- Documentation/Books/Manual/Programs/Arangorestore/Examples.md
- Documentation/Books/Manual/Programs/Arangorestore/README.md
- arangod/Replication/DatabaseInitialSyncer.cpp
- arangod/Replication/Syncer.cpp
- arangod/RocksDBEngine/RocksDBRestReplicationHandler.cpp
- arangod/VocBase/vocbase.cpp
- arangosh/Restore/RestoreFeature.cpp
- arangosh/Restore/RestoreFeature.h
- tests/js/server/dump/dump-mmfiles-cluster.js
(cherry picked from commit c584527d79296fd7afd0df812fd10a32c4924eab)
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/3296/
> Fix restore of views, add --view option (#7425)

- arangod/Replication/ReplicationApplierConfiguration.cpp
- arangod/Replication/TailingSyncer.cpp
- tests/js/server/replication/replication-ongoing-32.js
- tests/js/server/replication/replication-ongoing-global-spec.js
- tests/js/server/replication/replication-ongoing-global.js
- tests/js/server/replication/replication-ongoing.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/3317/
> switch default for requireFromPresent

- arangod/Replication/ReplicationApplierConfiguration.cpp
- arangod/Replication/TailingSyncer.cpp
- tests/js/server/replication/replication-ongoing-32.js
- tests/js/server/replication/replication-ongoing-global-spec.js
- tests/js/server/replication/replication-ongoing-global.js
- tests/js/server/replication/replication-ongoing.js
(cherry picked from commit f90b48f792b41ea1b731108743aa7233d3b3eb38)
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/3334/
> switch default message for requireFromPresent (#7439)

- Documentation/Books/Manual/Architecture/DeploymentModes/ActiveFailover/Architecture.md
(cherry picked from commit 307482515f664cc8edbdda9c2676c474a3372c8b)
> Doc - Active Failover bug fixes and improvements (#7242)

- CHANGELOG
- arangod/Agency/MoveShard.cpp
Wait until all servers (except the old leader) are in sync.
> Fix moving shard leaders.

- arangod/IResearch/IResearchRocksDBRecoveryHelper.cpp
> issue 506.1: backport 3.4: address issue with multiple identical document insertions on rocksdb recovery

- 3rdParty/CMakeLists.txt
- 3rdParty/iresearch/core/CMakeLists.txt
This patch overcomes the caching issues that we have on MSVC + MSBuild.
> Bug fix/copy schmutz

- arangod/Agency/Supervision.cpp
- arangod/Cluster/ServerState.cpp
Export Version and Engine in Cluster Health
> [3.4] Version/Engine Cluster Health

- CHANGELOG
- arangod/Agency/Supervision.cpp
- arangod/Cluster/ClusterFeature.cpp
- arangod/Cluster/ServerState.cpp
> [3.3] Version/Engine Cluster Health

- CHANGELOG
- arangod/Agency/Supervision.cpp
- arangod/Cluster/ServerState.cpp
Devel port of #7463 
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/2244/
> Version/Engine Cluster Health

- arangod/GeneralServer/GeneralCommTask.cpp
Add redirect header to response.
> Add redirect header to response.

- Documentation/Books/Manual/Deployment/ArangoDBStarter.md
GitHub Issue: https://github.com/arangodb/arangodb/issues/7255
- add new starter options.
- add output of the commands.
> Doc: 3.3-update latest starter options

- arangod/Aql/Function.cpp
- arangod/Aql/Function.h
- arangod/Aql/Functions.h
- arangod/IResearch/IResearchAnalyzerFeature.cpp
- arangod/IResearch/IResearchFeature.cpp
- arangod/RocksDBEngine/RocksDBCollection.cpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/3394/
> Micro-Optimize AQL CXX calls

- Documentation/Books/Manual/Installation/LinuxOSConfiguration.md
> Doc - Recommend overcommit_memory 0 or 1 on Linux (planning#3151)

- arangod/Cluster/ClusterInfo.cpp
- arangod/Cluster/ClusterInfo.h
Cleanup and repair error handling in index creation in the cluster.
> Port changes to fix index creation from devel to 3.3.

- Documentation/Books/Manual/Views/ArangoSearch/DetailedOverview.md
http://jenkins01.arangodb.biz:8080/view/Documentation/job/arangodb-documentation/133/
> Add decription for new ArangoSearch view properties

- 3rdParty/CMakeLists.txt
> use jemalloc for client tools as well

- CHANGELOG
- Documentation/Books/Manual/Programs/Arangod/Cache.md
- Documentation/Books/Manual/Programs/Arangod/Rocksdb.md
- Documentation/Books/Manual/ReleaseNotes/UpgradingChanges34.md
- arangod/Cache/CacheManagerFeature.cpp
- arangod/RocksDBEngine/RocksDBEngine.cpp
- lib/ApplicationFeatures/RocksDBOptionFeature.cpp
- lib/ApplicationFeatures/RocksDBOptionFeature.h
changed default value for `--rocksdb.block-cache-size`
> added option `--rocksdb.enforce-block-cache-size-limit`

- Documentation/Books/Manual/Upgrading/VersionSpecific/Upgrading34.md
Cherry-pick of https://github.com/arangodb/arangodb/pull/7454
> Doc - 3.3 to 3.4 notes about upgrading (#7454)

- arangod/Actions/RestActionHandler.cpp
- arangod/Actions/actions.cpp
- arangod/Graph/GraphManager.cpp
- arangod/IResearch/IResearchLinkHelper.cpp
- arangod/IResearch/IResearchView.cpp
- arangod/IResearch/IResearchViewCoordinator.cpp
- arangod/RestHandler/RestReplicationHandler.cpp
- arangod/RestHandler/RestViewHandler.cpp
- arangod/RocksDBEngine/RocksDBTransactionState.cpp
- arangod/V8Server/v8-views.cpp
- arangod/VocBase/Methods/Upgrade.cpp
> Bug fix/cxxcheck 28112018

- arangod/Cluster/ClusterInfo.cpp
> improve logging in ClusterInfo::loadPlan

- Documentation/Books/AQL/Operations/Insert.md
- Documentation/Books/AQL/Operations/Remove.md
- Documentation/Books/AQL/Operations/Replace.md
- Documentation/Books/AQL/Operations/Update.md
- Documentation/Books/AQL/Operations/Upsert.md
- Documentation/Books/Manual/DataModeling/OperationalFactors.md
- Documentation/Books/Manual/ReleaseNotes/NewFeatures34.md
- arangod/RocksDBEngine/RocksDBCollection.cpp
- arangod/RocksDBEngine/RocksDBTransactionState.cpp
- arangod/StorageEngine/TransactionState.cpp
- arangod/StorageEngine/TransactionState.h
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/3424/
> Document RocksDB exclusive option

- arangod/Aql/Function.cpp
- arangod/Aql/Function.h
- arangod/Aql/Functions.h
- arangod/IResearch/IResearchAnalyzerFeature.cpp
- arangod/IResearch/IResearchFeature.cpp
- arangod/RocksDBEngine/RocksDBCollection.cpp
(cherry picked from commit 8ddb9a063b8d54c7efe022418e3012ed18d7bc79)
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/3397/
> Micro-Optimize AQL CXX calls (#7486)

- Documentation/Books/Manual/DataModeling/OperationalFactors.md
- arangod/ClusterEngine/ClusterCollection.cpp
- arangod/ClusterEngine/ClusterCollection.h
- arangod/IResearch/IResearchLinkHelper.cpp
- arangod/IResearch/IResearchRocksDBRecoveryHelper.cpp
- arangod/MMFiles/MMFilesCollection.cpp
- arangod/MMFiles/MMFilesCollection.h
- arangod/MMFiles/MMFilesWalRecoverState.cpp
- arangod/Replication/DatabaseInitialSyncer.cpp
- arangod/Replication/ReplicationApplier.cpp
- arangod/Replication/Syncer.cpp
- arangod/RestHandler/RestReplicationHandler.cpp
- arangod/RocksDBEngine/RocksDBCollection.cpp
- arangod/RocksDBEngine/RocksDBCollection.h
- arangod/StorageEngine/PhysicalCollection.h
- arangod/VocBase/LogicalCollection.cpp
- arangod/VocBase/LogicalCollection.h
- arangod/VocBase/Methods/Indexes.cpp
- arangod/VocBase/Methods/UpgradeTasks.cpp
- tests/IResearch/IResearchLink-test.cpp
- tests/IResearch/IResearchQueryTraversal-test.cpp
- tests/IResearch/StorageEngineMock.cpp
- tests/IResearch/StorageEngineMock.h
(cherry picked from commit d0efd95a379904f5228ae30207cba3b3ae564d25)
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/3399/
> Restore index refactor (#7470)

- arangod/IResearch/Containers.h
as discussed with arangosearch team. fix provided by @vasiliy-arangodb 
will open a devel pr within the next minutes.
> fixed some asan search stuff

- js/apps/system/_admin/aardvark/APP/frontend/js/views/viewView.js
the backbone model did not receive an update after rename of a view
> fixed ui not updating its view name propertly

- tests/OskarTestSuitesBlackList
> [3.3] Blacklist upgrade data tests.

- Documentation/Books/AQL/Operations/Insert.md
- Documentation/Books/AQL/Operations/Remove.md
- Documentation/Books/AQL/Operations/Replace.md
- Documentation/Books/AQL/Operations/Update.md
- Documentation/Books/AQL/Operations/Upsert.md
- Documentation/Books/Manual/DataModeling/OperationalFactors.md
- Documentation/Books/Manual/ReleaseNotes/NewFeatures34.md
- arangod/RocksDBEngine/RocksDBCollection.cpp
- arangod/RocksDBEngine/RocksDBTransactionState.cpp
- arangod/StorageEngine/TransactionState.cpp
- arangod/StorageEngine/TransactionState.h
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-linux/3461/
> Document RocksDB exclusive option (#7517)

- arangod/Cluster/ClusterInfo.cpp
* improve logging in ClusterInfo::loadPlan
* address review comments
> improve logging in ClusterInfo::loadPlan (#7511)

- arangod/IResearch/Containers.h
- arangod/IResearch/IResearchLinkMeta.cpp
- arangod/IResearch/IResearchLinkMeta.h
* ensure UnorderedRefKeyMap keys are valid after copying
* minor improvement
> ensure UnorderedRefKeyMap keys are valid after copying (#7549)

- Documentation/DocuBlocks/Rest/Cluster/get_cluster_health.md
- arangod/Agency/Supervision.cpp
Removed advertised endpoints from cluster health. (Badly ported and reviewed code) Fixed Timestamp UI Bug.
> [3.3] Cluster Health Timestamp Bugfix

- arangod/Aql/ClusterBlocks.cpp
- arangod/Aql/ExecutionPlan.cpp
- arangod/Aql/SortBlock.cpp
- arangod/Aql/SortRegister.cpp
- arangod/Aql/SortRegister.h
- arangod/IResearch/IResearchFeature.cpp
- arangod/IResearch/IResearchViewBlock.cpp
> treat all iresearch scores as float_t for 3.4

- arangod/Aql/ClusterBlocks.cpp
- arangod/Aql/SortBlock.cpp
- arangod/Aql/SortRegister.cpp
- arangod/Aql/SortRegister.h
- arangod/IResearch/IResearchFeature.cpp
- arangod/IResearch/IResearchViewBlock.cpp
* treat all iresearch scores as float_t for 3.4
* cleanup
* attempt to fix tests
* another attempt to fix tests
> treat all iresearch scores as float_t for 3.4 (#7573)

- tests/js/common/aql/aql-view-arangosearch-cluster.js
- tests/js/common/aql/aql-view-arangosearch-nondeterministic-cluster.js
> re-enable arangosearch scoring tests in cluster

- arangod/Agency/CleanOutServer.cpp
- arangod/Cluster/ClusterInfo.cpp
- arangod/Cluster/ClusterMethods.cpp
- arangod/Cluster/DBServerAgencySync.cpp
- arangod/Cluster/FollowerInfo.h
- arangod/Cluster/Maintenance.cpp
- arangod/Transaction/Methods.cpp
> [devel] Bug fix/bad leader report current

- Documentation/Books/Manual/ReleaseNotes/KnownIssues33.md
- Documentation/Books/Manual/ReleaseNotes/README.md
- Documentation/Books/Manual/SUMMARY.md
Build:
- http://jenkins01.arangodb.biz:8080/job/arangodb-documentation/156/
> Doc - 3.3 Known Issues

- Documentation/Books/Manual/ReleaseNotes/KnownIssues34.md
> Documentation 3.4/update known issues (arangosearch)

- Documentation/Books/Manual/ReleaseNotes/KnownIssues34.md
> Doc - Known Issues 3.4

- arangod/VocBase/Methods/Version.cpp
same as https://github.com/arangodb/arangodb/pull/7652
> parse version fix

- Documentation/Books/AQL/Functions/Geo.md
- Documentation/Books/Manual/ReleaseNotes/NewFeatures34.md
Contains backports of:
- https://github.com/arangodb/arangodb/pull/7651 3.4 Release notes
- https://github.com/arangodb/arangodb/pull/7637/commits/a92ab195b87d63c916044ab82684fd02c577fc16 Edit done to 3.4->devel backport (3.4 was already merged, so can't edit it there)
http://jenkins01.arangodb.biz:8080/view/Documentation/job/arangodb-documentation/167/
> Documentation 3.4/geo multipolygon

- Documentation/Books/Cookbook/SUMMARY.md
- Documentation/Books/Cookbook/UseCases/MonetaryDataWithoutPrecisionLoss.md
- Documentation/Books/Cookbook/UseCases/README.md
Backport from devel: https://github.com/arangodb/arangodb/pull/7149
> Doc - Create MonetaryDataWithoutPrecisionLoss.md (#7149)

- Documentation/Books/Manual/Administration/Cluster/README.md
> Doc: change replica amount

- Documentation/Examples/aqlGeoMultiPolygon_1.generated
Should fix build error in old Jenkins:
https://master.jenkins.arangodb.info/job/RELEASE__BuildDocumentation/787/console
> Docs: Add missing example file for GEO_MULTIPOLYGON()

- Documentation/Examples/arangod.json
- Documentation/Examples/arangodump.json
- Documentation/Examples/arangoexport.json
- Documentation/Examples/arangorestore.json
- Documentation/Examples/arangosh.json
@sleto-it I built 3.4 EE and committed the .json files, which now include the EE only options again
> Use program option JSON files generated with Enterprise Edition

- Documentation/Books/Manual/Upgrading/GeneralInfo/README.md
Backport of https://github.com/arangodb/arangodb/pull/7663
> 3.3 to 3.4 starter update - info + added "highly"

- Documentation/Books/HTTP/Indexes/Fulltext.md
- Documentation/Books/HTTP/Indexes/Hash.md
- Documentation/Books/HTTP/Indexes/Persistent.md
- Documentation/Books/HTTP/Indexes/Skiplist.md
- Documentation/Books/Manual/ReleaseNotes/NewFeatures26.md
- Documentation/Books/Manual/ReleaseNotes/UpgradingChanges26.md
- Documentation/DocuBlocks/Rest/Documents/put_read_all_documents.md
- Documentation/DocuBlocks/Rest/Simple Queries/put_api_simple_all.md
- Documentation/DocuBlocks/Rest/Simple Queries/put_api_simple_by_example.md
- Documentation/DocuBlocks/Rest/Simple Queries/put_api_simple_fulltext.md
- Documentation/DocuBlocks/Rest/Simple Queries/put_api_simple_near.md
- Documentation/DocuBlocks/Rest/Simple Queries/put_api_simple_range.md
- Documentation/DocuBlocks/Rest/Simple Queries/put_api_simple_within.md
- Documentation/DocuBlocks/Rest/Simple Queries/put_api_simple_within_rectangle.md
Backport of #7657 
Internal ref:
- https://github.com/arangodb/planning/issues/2932#issuecomment-442836329
Test build: http://jenkins01.arangodb.biz:8080/view/Documentation/job/arangodb-documentation/171/
> Documentation 3.4/deprecate simple all keys

- Documentation/Books/Manual/SUMMARY.md
- Documentation/Books/Manual/Uninstallation/README.md
https://github.com/arangodb/arangodb/pull/5830/files
Note: The Installation/Windows.md page has something about uninstalling, should probably be moved to here
---
Preview build:
- http://web01.arangodb.biz/documentation/uninstallation/Manual/Uninstallation/
> Docs: new page for Uninstallation (Split PR #5830)

- Documentation/Books/Manual/SUMMARY.md
- Documentation/Books/Manual/Upgrading/CommunityToEnterprise.md
- Documentation/Books/Manual/Upgrading/README.md
Internal Ref:
- https://github.com/arangodb/planning/issues/3310
Build:
- http://jenkins01.arangodb.biz:8080/job/arangodb-documentation/174/
> Doc - Community to Enterprise Upgrade

- Documentation/Books/Manual/ReleaseNotes/NewFeatures34.md
You might want to help in rephrasing / describing with more details, if possible, thanks
> Doc - cite the tar.gz in what's new

- Documentation/Books/Manual/Installation/LinuxOSConfiguration.md
- Documentation/Books/Manual/Installation/LinuxOSTuningScripts.md
- Documentation/Books/Manual/SUMMARY.md
Preview Build:
- http://web01.arangodb.biz/documentation/linux-operating-system-scripts/Manual/Installation/LinuxOSTuningScripts.html
> Doc - Scripts to Optimize OS

- Documentation/Books/Manual/Installation/MacOSX.md
https://github.com/arangodb/arangodb/pull/5830/files
---
Preview build:
- http://web01.arangodb.biz/documentation/installation-refactor-macosx/Manual/Installation/MacOSX.html
> Docs: Installation refactor MacOSX (Split PR #5830)

- Documentation/Books/Manual/Deployment/ProductionChecklist.md
- Documentation/Books/Manual/Deployment/README.md
- Documentation/Books/Manual/SUMMARY.md
Build:
- http://jenkins01.arangodb.biz:8080/job/arangodb-documentation/177/
> Doc - Production Checklist

- Documentation/Books/Manual/ReleaseNotes/35.md
- Documentation/Books/Manual/ReleaseNotes/KnownIssues35.md
- Documentation/Books/Manual/ReleaseNotes/NewFeatures35.md
- Documentation/Books/Manual/ReleaseNotes/UpgradingChanges35.md
Uses/adjusts headlines to follow the recently edited 2.1 - 3.4 pages
> Docs: Placeholder pages for 3.5 Release Notes

- CHANGELOG
- arangod/GeneralServer/GeneralCommTask.cpp
- arangod/RestServer/arangod.cpp
- tests/js/client/authentication/auth.js
* Call license key check.
* Add CHANGELOG entry.
> Call license key check. (#7594)

- arangosh/Dump/DumpFeature.cpp
- arangosh/Restore/RestoreFeature.cpp
Mention collection names and more context in dump & restore error messages
> improve error messages

- CHANGELOG
- js/server/modules/@arangodb/foxx/manifest.js
> Fix TypeError for invalid manifests (3.2)

- arangod/Cluster/ServerState.cpp
- arangod/Cluster/ServerState.h
- js/server/modules/@arangodb/foxx/manager.js
See https://github.com/arangodb/arangodb/pull/7531
> [3.3] Reload Foxx routes during startup

- arangod/Cluster/HeartbeatThread.cpp
- arangod/Cluster/ServerState.cpp
- arangod/Cluster/ServerState.h
- arangod/RestServer/BootstrapFeature.cpp
- js/server/modules/@arangodb/foxx/manager.js
See https://github.com/arangodb/arangodb/pull/7531
> Reload Foxx routes during startup

- js/server/modules/@arangodb/foxx/router/request.js
- tests/js/server/shell/shell-foxx-request-spec.js
This (hopefully) fixes a bug in the Windows build.
> Fix windows test for Foxx socket request URL

- arangod/Agency/Supervision.cpp
Someone (me) forgot to rename the field everywhere.
> [3.4] LastAcked(Time)

- CHANGELOG
- arangod/GeoIndex/Index.cpp
> [3.4] Ignore invaild geo coordinates when indexing.

- CHANGELOG
- lib/Basics/threads-win32.cpp
> Bug fix 3.4/fix thread shutdown

- CHANGELOG
- lib/Basics/threads-win32.cpp
Fix threads shutdown on _WIN32.
> fix thread shutdown on _WIN32

- CHANGELOG
- lib/Basics/threads-win32.cpp
Fix thread shutdown on _WIN32.
> Bug fix/fix thread shutdown

- CHANGELOG
- lib/Basics/threads-win32.cpp
> Bug fix 3.2/fix thread shutdown

- arangod/Aql/OptimizerRulesReplaceFunctions.cpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/2493/
> fixed item 3 of issue #7009

- CHANGELOG
- arangod/RestHandler/RestReplicationHandler.cpp
Fixes a rare thread local dead lock situation during syncing of followers.
> Bug fix 3.4/fix tombstones

- CHANGELOG
- arangod/RestHandler/RestReplicationHandler.cpp
> Fix a rare deadlock situation in Replication sync phase

- 3rdParty/iresearch/CMakeLists.txt
- 3rdParty/iresearch/core/CMakeLists.txt
- 3rdParty/iresearch/tests/CMakeLists.txt
> fix cmake parameters coincidence

- arangod/IResearch/IResearchViewBlock.cpp
- tests/IResearch/IResearchQueryStartsWith-test.cpp
> [3.4] fix issue #7777

- 3rdParty/iresearch/core/utils/attributes.hpp
- 3rdParty/iresearch/core/utils/file_utils.cpp
- 3rdParty/iresearch/core/utils/index_utils.cpp
- 3rdParty/iresearch/core/utils/index_utils.hpp
- 3rdParty/iresearch/core/utils/ref_counter.hpp
- 3rdParty/iresearch/core/utils/text_format.hpp
- arangod/IResearch/IResearchViewMeta.cpp
> update ArangoSearch consolidation policy

- 3rdParty/iresearch/core/utils/attributes.hpp
- 3rdParty/iresearch/core/utils/file_utils.cpp
- 3rdParty/iresearch/core/utils/index_utils.cpp
- 3rdParty/iresearch/core/utils/index_utils.hpp
- 3rdParty/iresearch/core/utils/ref_counter.hpp
- 3rdParty/iresearch/core/utils/text_format.hpp
- arangod/IResearch/IResearchViewMeta.cpp
> update ArangoSearch consolidation policy (#7801)

- Documentation/Books/Manual/ReleaseNotes/KnownIssues35.md
> update known issues 3.5

- arangod/IResearch/IResearchDocument.cpp
- arangod/IResearch/IResearchDocument.h
- arangod/IResearch/IResearchLink.cpp
- arangod/IResearch/IResearchLinkCoordinator.cpp
- arangod/IResearch/IResearchPrimaryKeyFilter.cpp
- arangod/IResearch/IResearchPrimaryKeyFilter.h
- arangod/IResearch/IResearchView.cpp
- arangod/IResearch/IResearchView.h
- arangod/IResearch/IResearchViewBlock.cpp
- arangod/IResearch/IResearchViewBlock.h
- arangod/IResearch/IResearchViewNode.cpp
- tests/IResearch/IResearchDocument-test.cpp
- tests/IResearch/IResearchView-test.cpp
- tests/IResearch/IResearchViewDBServer-test.cpp
- tests/IResearch/IResearchViewNode-test.cpp
> issue 511.5: remove cid from IResearchPrimaryKey since iresearch data-stores are per-collction, minor code cleanup

- arangod/Replication/DatabaseTailingSyncer.cpp
- arangod/VocBase/Methods/Upgrade.h
- tests/js/server/replication/replication-ongoing-global.js
- tests/js/server/replication/replication-ongoing.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/3753/
> Fix restrictCollections param on database replication

- lib/SimpleHttpClient/ClientConnection.cpp
- lib/SimpleHttpClient/GeneralClientConnection.cpp
- lib/SimpleHttpClient/GeneralClientConnection.h
- lib/SimpleHttpClient/SslClientConnection.cpp
- make all parts of the simple http client depend on the 'CommunicationPhase'
- Assert whether we are in an open/close loop
> Fix Cluster shutdown handling of http connections

- UnitTests/OskarTestSuitesBlackList
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-linux/3772/
> Bug fix/upgrade data tests windows 3.3

- UnitTests/OskarTestSuitesBlackList
- js/client/modules/@arangodb/testsuites/upgrade-data.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/2581/
> Remove procdump usage while taring archives

- UnitTests/OskarTestSuitesBlackList
- js/client/modules/@arangodb/testsuites/upgrade-data.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/2582/
> Remove procdump usage while taring archives (3.4)

- UnitTests/OskarTestSuitesBlackList
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/2592/
> Add 3.2, 3.3, 3.4 upgrade-data tests to oskar blacklist for 3.2
