arangodb/arangodb

- CHANGELOG
- arangod/Agency/AgencyStrings.h
- arangod/Agency/Supervision.cpp
- arangod/Agency/Supervision.h
- lib/Basics/StaticStrings.cpp
- lib/Basics/StaticStrings.h
- tests/Agency/SupervisionTest.cpp
This is a forward-port from 3.8 of https://github.com/arangodb/arangodb/pull/15230
Add proper cleanup if a dbserver is restarted, shut down or crashes
during a hotbackup upload or download job. In this case we need to
detect this in the Supervision by looking at the rebootId, report
the upload or download job for this DBServer as failed, and clear the
lock for this operation and its destination.
The problem was that no rebootId was saved with the job, no cleanup
routine existed and the destination lock could remain, which would
prevent successful retries by the operator in production.
(Please describe the changes in this PR for reviewers - mandatory)
[*] hankey Bugfix (requires CHANGELOG entry)
[*] book CHANGELOG entry made
Backports:
[*] this is the forward port from 3.8 …
> Hotbackup blockage after DBServer restart

- tests/CMakeLists.txt
When compiling with clang-13 on Ubuntu 20.04 I got some linking errors during fuertetest linking.
This is due to a missing dependency. Example of one such error:
```
ld.lld: error: undefined symbol: arangodb::ServerState::instance()
>>> referenced by RocksDBIndex.cpp:178 (/home/apetenchea/work/branches/arangodb-clang/arangod/RocksDBEngine/RocksDBIndex.cpp:178)
```
The fix is to add **arangoserver** as a dependency to **fuertetest**.
> Fixing clang-13 linker error when building tests

- CHANGELOG
- arangod/Cluster/ClusterTraverser.cpp
- arangod/Graph/BreadthFirstEnumerator.cpp
- arangod/Graph/BreadthFirstEnumerator.h
- arangod/Graph/NeighborsEnumerator.cpp
- arangod/Graph/NeighborsEnumerator.h
- arangod/Graph/PathEnumerator.h
- arangod/Graph/SingleServerTraverser.cpp
- arangod/Graph/WeightedEnumerator.cpp
- arangod/Graph/WeightedEnumerator.h
- tests/Aql/TraversalExecutorTest.cpp
Fix GitHub issue #15084.
Enterprise companion: https://github.com/arangodb/enterprise/pull/821
Fixed a potential use-after-free on Windows for queries that used the NeighborsEnumerator (though other PathEnumerators might have been affected as well).
The reason was that in some cases the MSVC STL unordered_map/unordered_set calculates hashes in `clear`, but the stringHeap that stored the strings which were reference by the stringRefs in the unordered_set was cleared before the set.
> Fixed a potential use-after-free on Windows.

- tests/IResearch/IResearchLinkTest.cpp
This assertion checked that the `сleanup` after the second removes, which removes 100 times fewer documents than the first, works faster or the same. Apparently, sometimes this isn't true, locally it isn't reproduced for me. So I just removed this statement
> [Search-183] Fix strange test failed

- js/client/modules/@arangodb/testutils/process-utils.js
generate procdump on forcefull shutdown regardless whether we previously had a procdump running or its disabled
> generate procdump on forcefull shutdown regardless whether we previously

- CHANGELOG
- arangod/Cluster/TakeoverShardLeadership.cpp
This fixes BTS-535.
When a shard leader takes over its leadership it has to make sure that
it is a FailoverCandidate. This check needs an up-to-date version of
the information in `Current` and this has to have made its way through
the agency cache to the ClusterInfo cache.
This PR fixes the waiting condition to avoid test instabilities.
- not decided yet
- [*] GitHub issue / Jira ticket number: https://arangodb.atlassian.net/browse/BTS-535
- [*] This change is a trivial rework / code cleanup without any test coverage.
- [*] The behavior in this PR was *manually tested*
- [*] This change …
> [BTS-535] Fix waiting for Current/Version for TakeoverShardLeadership

- tests/IResearch/CMakeLists.txt
PR #15151 adjusted arangodbtests but iresearch-arangodbtests target also needs same adjustments as includes were changed.
> Fix cmake for arangodb-iresearch target

- tests/js/client/communication/test-communication.js
This increases the test timeout to 30s to detect a deadlock.
> [BTS-565] Timeout without deadlock

- tests/CMakeLists.txt
Fixing missing header include paths for replication2 test binary.
> Fix Replication2 Test Binary Includes

- CHANGELOG
- client-tools/Restore/RestoreFeature.cpp
- lib/SimpleHttpClient/HttpResponseChecker.cpp
- lib/SimpleHttpClient/HttpResponseChecker.h
- tests/SimpleHttpClient/HttpResponseCheckerTest.cpp
- tests/js/client/communication/test-communication.js
This PR fixes the error messages on the client requests of arangorestore displaying passwords in plain text, trimming the json fields from the payload that display the password.
The server code still has to be changed and would require some extra thought into it.
Examples of error messages displaying the password in plain text, as in the ticket https://arangodb.atlassian.net/browse/BTS-580:
```
2021-09-13T15:45:52Z [4120] ERROR [7a35f] {restore} Could not create database '😀': got invalid response from server: HTTP 400: 'database name invalid' while executing creating database' with this payload: '{"name":"😀","options":{"replicationFactor":1},"users":[{"username":"root","passwd":"hustensaft"}]}'
2021-09-13T15:45:52Z [4120] ERROR [cb69f] {restore} got invalid response from server: HTTP 400: …
```
> [BTS-580] Trim password field from payload in arangorestore error messages

- CHANGELOG
- arangod/Cluster/ClusterTraverser.cpp
- arangod/Graph/BreadthFirstEnumerator.cpp
- arangod/Graph/BreadthFirstEnumerator.h
- arangod/Graph/NeighborsEnumerator.cpp
- arangod/Graph/NeighborsEnumerator.h
- arangod/Graph/PathEnumerator.h
- arangod/Graph/SingleServerTraverser.cpp
- tests/Aql/TraversalExecutorTest.cpp
Fix GitHub issue #15084.
Enterprise companion: https://github.com/arangodb/enterprise/pull/824
Fixed a potential use-after-free on Windows for queries that used the NeighborsEnumerator (though other PathEnumerators might have been affected as well).
The reason was that in some cases the MSVC STL unordered_map/unordered_set calculates hashes in `clear`, but the stringHeap that stored the strings which were reference by the stringRefs in the unordered_set was cleared before the set.
> [3.7] Fixed a potential use-after-free on Windows.

- CHANGELOG
- Documentation/Metrics/arangodb_revision_tree_hibernations_total.yaml
- Documentation/Metrics/arangodb_revision_tree_memory_usage.yaml
- Documentation/Metrics/arangodb_revision_tree_resurrections_total.yaml
- Documentation/Metrics/rocksdb_wal_sequence.yaml
- Documentation/Metrics/rocksdb_wal_sequence_number.yaml
- arangod/RocksDBEngine/RocksDBEngine.cpp
- arangod/RocksDBEngine/RocksDBEngine.h
- arangod/RocksDBEngine/RocksDBMetaCollection.cpp
- arangod/RocksDBEngine/RocksDBMetaCollection.h
- lib/Containers/MerkleTree.cpp
- lib/Containers/MerkleTree.h
- tests/Containers/MerkleTreeTest.cpp
- tests/js/client/shell/shell-promtool-cluster.js
Backport of https://github.com/arangodb/arangodb/pull/15225
Added memory usage tracking for revision trees
* Added the following metrics for revision trees:
- `arangodb_revision_tree_hibernations_total`: number of times a revision tree was compressed in RAM and set to hibernation
- `arangodb_revision_tree_resurrections_total`: number of times a revision tree was resurrected from hibernation and uncompressed in RAM
- `arangodb_revision_tree_memory_usage`: total memory usage (in bytes) by all active revision trees
* Added metric `rocskdb_wal_sequence` to track the current tip of the WAL's sequence number.
> Added memory usage tracking for revision trees

- CHANGELOG
- arangod/RocksDBEngine/Listeners/RocksDBThrottle.cpp
- arangod/RocksDBEngine/Listeners/RocksDBThrottle.h
- arangod/RocksDBEngine/RocksDBEngine.cpp
- arangod/RocksDBEngine/RocksDBEngine.h
Backport of https://github.com/arangodb/arangodb/pull/15317
Docs PR: https://github.com/arangodb/docs/pull/841
Added startup options to adjust previously hard-coded parameters for the RocksDB throttle:
- `--rocksdb.throttle-frequency`: frequency for write-throttle calculations (in milliseconds, default value is 60000, i.e. 60 seconds).
- `--rocksdb.throttle-slots`: number of historic measures to use for throttle value calculation (default value is 63).
- `--rocksdb.throttle-scaling-factor`: adaptiveness scaling factor for write-throttle calculations (default value is 17). There is normally no need to change this value.
- `--rocksdb.throttle-slow-down-writes-trigger`: number of level 0 files whose payload is not considered in throttle calculations when penalizing the presence of L0 files. …
> added various startup options for throttle configuration

- lib/Basics/voc-errors.h
- utils/generateErrorfile.py
Currently error codes are defined as `constexpr` values. Adding a new error codes requires to recompile every file that uses any error code. If instead the error codes are defined as macros, then adding a new macro does not change the output of the preprocessor and thus allows ccache to substitute the file with a cache object file (not a direct substitution, but after preprocessing)
This will increase compilation performance and developers are more willing to add new error codes.
> Use Macros for Error Codes

- arangod/Replication2/ReplicatedLog/LogCommon.cpp
- arangod/Replication2/ReplicatedLog/types.cpp
Remove 2 occurences of VPackStringRef that slipped in
> remove 2 occurences of VPackStringRef that slipped in

- CHANGELOG
- arangod/RocksDBEngine/RocksDBCommon.cpp
- arangod/RocksDBEngine/RocksDBCommon.h
- arangod/RocksDBEngine/RocksDBEngine.cpp
Cancel ongoing RocksDB compactions on server shutdown.
This is an attempt to fix hangs in threads that are waiting in RocksDB compactions during the server shutdown.
> cancel ongoing RocksDB compactions on shutdown

- CMakeLists.txt
Currently our cmake files, for MSVC, set `-std=c++latest` via `CMAKE_CXX_FLAGS`. However, as we provide `set(CMAKE_CXX_STANDARD 20)`, cmake itself passes `-std=c++20`, possibly overriding the former.
None.
https://github.com/arangodb/arangodb/pull/15171
> Fix usage of -std=c++latest vs. -std=c++20 in MSVC

- utils/generateExamples.py
AQL-Examples may fail. Catch these errors and produce better error messages.
this testrun should show a proper errormessage now:
https://jenkins.arangodb.biz/view/Documentation/job/arangodb-ANY-examples/1391/
The error handling is copied from the code used for the other docublocks:
https://github.com/arangodb/arangodb/blob/devel/Documentation/Scripts/exampleHeader.js#L219
> catch AQL-Errors for better error messages

- tests/Replication2/ReplicatedState/ReplicatedStateTest.cpp
- tests/Replication2/ReplicatedState/StateMachines/MyStateMachine.cpp
The modified test now checks if entries survive after a follower is recreated.
> [CINFRA-163] Improve replicated state test

- CHANGELOG
- arangod/RocksDBEngine/RocksDBCommon.cpp
- arangod/RocksDBEngine/RocksDBCommon.h
- arangod/RocksDBEngine/RocksDBEngine.cpp
Backport of https://github.com/arangodb/arangodb/pull/15331
Cancel ongoing RocksDB compactions on server shutdown.
This is an attempt to fix hangs in threads that are waiting in RocksDB compactions during the server shutdown.
> cancel ongoing RocksDB compactions on shutdown (#15331)

- js/common/modules/@arangodb/examples/examples.js
`@arangodb/examples/example-users.js` has been existing for very long in our source. connect it to the general example documentation facility.
- 3.9: https://github.com/arangodb/arangodb/pull/15358
- 3.8: https://github.com/arangodb/arangodb/pull/15359
- 3.7: https://github.com/arangodb/arangodb/pull/15360
This would enable using it in the documentation.
> add integration for another long existing example

- tests/js/client/shell/shell-transaction.js
For databases with replicationVersion 2 we internally use a ReplicatedRocksDBTransactionState for the transaction. Since this class is currently not covered by unittests, some integration tests are now parameterized to cover both cases.
> [CINFRA-130] Add integration tests for ReplicatedRocksDBTransactionState.

- utils/generateExamples.js
- utils/generateExamples.py
- utils/generateSwagger.sh
Documentation: handle syntax errors in bind-values accordingly and give better errormessages to the user.
an example of such an error output looks like this:
```
[0.003465414047241211s] done with  working_with_date_time
RUN FAILED TO JSON PARSE BIND VALUES: COMBINING_GRAPH_02_show_geo, Expecting property name enclosed in double quotes
Unparseable JSON: {bonn: [7.0998, 50.7340],
radius: 400000
}
```
- 3.9 https://github.com/arangodb/arangodb/pull/15368
- 3.8 https://github.com/arangodb/arangodb/pull/15369
- 3.7 https://github.com/arangodb/arangodb/pull/15370
> go python3; handle bindvalue errors accordingly.

- Documentation/DocuBlocks/Rest/Administration/get_admin_server_mode.md
- Documentation/DocuBlocks/Rest/Administration/get_admin_server_tls.md
Corrected documentation for admin server to reflect that the end point is protected.
> ES-1006 Correcting documentation for server admin

- arangod/GeneralServer/AcceptorTcp.cpp
- arangod/GeneralServer/AcceptorUnixDomain.cpp
Remove a workaround that allowed compilation with g++-11 a while ago.
The workaround is not necessary anymore, as the compile issue was properly fixed via commit 6c9531a480a33dff7c84934104da11de1fd8fffe.
This is an internal change. No previous version was affected.
Verified that this version compiles with g++-10 and g++-11.
> remove a workaround that was accidentially committed

- arangod/RocksDBEngine/Listeners/RocksDBThrottle.cpp
- arangod/RocksDBEngine/Listeners/RocksDBThrottle.h
Removed non-portable thread priority adjustment code that worked opposite to what the code comments described.
It seems to have _lowered_ the priority of flush/compaction threads instead of raising it. 
Plus, raising the priority would only have been successful under some adjustments to the setup/environment, which are and were not part of our recommended setup.
> remove non-portable thread priority adjustment code

- CHANGELOG
- arangod/Cluster/ServerState.cpp
Make "numberOfCores" and "physicalMemory" available to agency, for any potential future shard rebalancing algorithms.
> make "numberOfCores" and "physicalMemory" available to agency

- CHANGELOG
- arangod/Cluster/SynchronizeShard.cpp
- arangod/Replication/DatabaseInitialSyncer.cpp
- arangod/Replication/DatabaseInitialSyncer.h
Backport of https://github.com/arangodb/arangodb/pull/15363
Allow initial, full dump shard synchronization to abort prematurely if it turns out that the follower was removed from the plan as a follower (e.g. if there are enough other in-sync followers).
> abort shard synchronization in case the follower becomes undesired

- arangod/Replication2/Methods.h
- arangod/RestHandler/RestLogHandler.cpp
- arangod/V8Server/v8-replicated-logs.cpp
- js/client/modules/@arangodb/replicated-logs.js
- tests/js/common/shell/shell-replicated-logs-cluster.js
This pull requests sets the following default values for some of the methods:
- head?limit=10
- tail?limit=10
- slice?start=0&end=11
- poll?first=0&limit=10
Constants are used instead of hardcoded values.
Some tests were modified to ensure consistency between the V8 implementation and the HTTP client.
> [CINFRA-181] Rest API default limits

- CHANGELOG
- arangod/RocksDBEngine/Listeners/RocksDBThrottle.cpp
- arangod/RocksDBEngine/Listeners/RocksDBThrottle.h
- arangod/RocksDBEngine/RocksDBEngine.cpp
- arangod/RocksDBEngine/RocksDBEngine.h
- arangod/RocksDBEngine/RocksDBOptionFeature.cpp
- arangod/RocksDBEngine/RocksDBOptionFeature.h
Changed various default values for RocksDB to tune operations for different
typical scenarios like gp2 type volumes and gp3 type volumes and locally
attached SSDs with RAID0:
- `--rocksdb.level0-slowdown-trigger` has been decreased from 20 to 16
- `--rocksdb.level0-stop-trigger` has been increased from 36 to 256
- `--rocksdb.max-background-jobs` has been increased to the number of cores
and is no longer limited to 8
- `--rocksdb.enabled-pipelined-write` is now `true` by default instead of `false`
- `--rocksdb.throttle-frequency` has been decreased from 60000ms down to
1000ms per iteration, which makes the RocksDB throttle react much quicker
- `--rocksdb.pending-compactions-slowdown-trigger` has been decreased from
64 GB down to 8 GB
- `--rocksdb.pending-compactions-stop-trigger` has been …
> New RocksDB tuning for pending compactions

- CMakeLists.txt
Currently, cmake enables compiler's C++ language extensions. E.g. passing `-std=gnu++2a` rather than `-std=c++2a` to g++. This PR disables that behavior.
None.
> Disable C++ language extensions

- .github/workflows/clang-format.yml
* Addresses cases of [false-positives](https://github.com/arangodb/arangodb/runs/4650363227?check_suite_focus=true) and [false-negatives](https://github.com/arangodb/arangodb/runs/4650724350?check_suite_focus=true)
* Minor cleanup to the `git diff` command
* Action now only triggers on Pull Requests that point to `devel`, and that modify files within within `arangod`, `client-tools`, `lib`, or `tests`
* Add `workflow_dispatch` event to allow this Action to be triggered manually from the [Actions](https://github.com/arangodb/arangodb/actions) menu
> [devel] fix: clang-format workflow

- STYLEGUIDE.md
* taken from its [confluence page](https://arangodb.atlassian.net/wiki/spaces/DEV/pages/1780908145/Linting+with+Clang+Format).
> styleguide: clang-format documentation

- .githooks/pre-commit-linux
- .githooks/pre-commit-macos
- .githooks/pre-commit-windows
- scripts/clang-format-linux.sh
- scripts/clang-format-macos.sh
- scripts/clang-format-windows.sh
Copy of #15442 for `3.9`
* adds the [T] value to the `--diff-filter` flag, to stay consistent with the [current clang-format action implementation](https://github.com/arangodb/arangodb/blob/3.9/.github/workflows/clang-format.yml#L19)
[Link]( https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---diff-filterACDMRTUXB82308203) to `--diff-filter` documentation
> [3.9] fix: clang-format git diff filter

- .githooks/pre-commit-linux
- .githooks/pre-commit-macos
- .githooks/pre-commit-windows
- scripts/clang-format-linux.sh
- scripts/clang-format-macos.sh
- scripts/clang-format-windows.sh
* adds the [T] value to the `--diff-filter` flag, to stay consistent with the [current clang-format action implementation](https://github.com/arangodb/arangodb/blob/devel/.github/workflows/clang-format.yml#L19)
[Link]( https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---diff-filterACDMRTUXB82308203) to `--diff-filter` documentation
> [devel] fix: clang-format git diff filter

- arangod/Replication2/ReplicatedLog/LogCommon.cpp
- tests/Replication2/Serialization/LogCommonTest.cpp
softWriteConcern default to writeConcern if it is not found during de-serialization.
> [CINFRA-191] softWriteConcern defaults to writeConcern

- CHANGELOG
- arangod/GeneralServer/GeneralServerFeature.cpp
- arangod/RestHandler/RestSupportInfoHandler.cpp
- tests/js/client/server_permissions/test-support-info-api-admin-noncluster.js
- tests/js/client/server_permissions/test-support-info-api-admin-off-noncluster.js
BTS-707: rename "hardened" option value for `--server.support-info-api` startup option to "admin".
Docs PR: https://github.com/arangodb/docs/pull/863
> BTS-707: rename "hardened" option value

- CHANGELOG
- lib/Basics/Identifier.cpp
- lib/Basics/Identifier.h
Fixes a performance regression caused by different hash calculation for primitive types like `uint64_t` and new the `Identifier` wrapper and derived types.
> [ES-1025] Fix performance regression caused by different hash calculation.

- arangod/Sharding/ShardingInfo.cpp
- tests/js/common/shell/01_shell-database.js
Verify that replicationFactor is >= writeConcern when creating databases.
> verify that replicationFactor >= writeConcern

- tests/IResearch/IResearchLinkTest.cpp
I couldn't expect that cleanup time with nothing to clean should be less than 1 ms
> Fix wrong expect in iresearch link metrics test

- arangod/Agency/AddFollower.cpp
- arangod/Agency/Agent.cpp
- arangod/Agency/CleanOutServer.cpp
- arangod/Agency/MoveShard.cpp
- arangod/Agency/Node.cpp
- arangod/Agency/RemoveFollower.cpp
- arangod/Agency/ResignLeadership.cpp
- arangod/Agency/State.cpp
- arangod/Agency/Store.cpp
- arangod/Agency/Supervision.cpp
- arangod/Agency/Supervision.h
- arangod/Cluster/ClusterInfo.cpp
- arangod/Cluster/Maintenance.cpp
- tests/Agency/CleanUpLostCollectionTest.cpp
Internal code cleanup by removing obsolete `__FILE__` and `__LINE__` mentions from error messages. These are obsolete because each log message has a unique log id anyway.
> small code cleanup

- tests/js/server/aql/aql-vector-functions.js
Add tests for vector functions edge cases.
This only adds tests. No changelog nor documentation needed.
> add tests for vector functions

- js/server/modules/@arangodb/testutils/replicated-logs-helper.js
- tests/js/server/replication2/replication2-supervision-replicated-log-target-cluster.js
After a test suspended a server,we should wait for the server to recover in the supervision. Otherwise it might not be ready for the second test. When it comes back it changes it's reboot id and thus the next test will fail.
> [CINFRA-207] Wait for server to recover after test suspend

- 3rdParty/V8/gyp/common.py
- 3rdParty/V8/gyp/msvs_emulation.py
- 3rdParty/V8/v7.9.317/third_party/jinja2/tests.py
Allow to compile with python 3.10.
> Allow to compile with python 3.10

- lib/SimpleHttpClient/SimpleHttpClient.cpp
Fix an issue found by Cppcheck. Container contents was accessed before emptiness were checked. Check was inversed.
> fix cpp-check found issue

- PULL_REQUEST_TEMPLATE.md
This PR simplifies the PULL_REQUEST_TEMPLATE.md in several ways, making it slightly easier to fill out.
The documentation section has been removed, because it was never filled out. The CLA section was removed because there is now the CLA bot. The testing section has been streamlined.
The PR is meant as a basis for discussion with other developers.
> simplify PR template

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/views/databaseView.js
- lib/Basics/FileUtils.cpp
- lib/Basics/files.cpp
- scripts/startLocalCluster.sh
It was observed that sometimes hotbackup upload can miss some files
during the upload, rendering the uploaded backups corrupt.
The reason is that the files of the backup are listed by an rclone
subprocess and after a recent change we sometimes truncate the output
of this file listing and therefore do not upload some files in the
backup.
This is the backport for 3.7.
- [*] GitHub issue / Jira ticket number: https://arangodb.atlassian.net/browse/BTS-734
- [*] This is accompanied by a PR in the enterprise repository: https://github.com/arangodb/enterprise/pull/858
*(Please pick …
> BTS-734 hotbackup upload can miss files

- arangod/Replication2/ReplicatedLog/LogCommon.cpp
- lib/Basics/StringUtils.h
- tests/Basics/StringUtilsTest.cpp
If you write something like
```cpp
basics::StringUtils::concatT(curServersKnown, '/', serverId);
```
it **does** not what you think it does. The reason is, that for a `char` type, `concatT` will (like for all numerical data types) call `std::to_string`. Hence the above results in something like
```cpp
"/Current/ServersKnown45PRMR-XXXXX"
```
I had to debug that and I never want to do it again. After this change `concatT` refuses to compile using a `char` as parameter.
Same applies to `joinT`.
Instead use
```cpp
basics::StringUtils::concatT(curServersKnown, "/", serverId);
```
or
```cpp
basics::StringUtils::concatT("The value is: ", static_cast<int>(myCharVariable));
```
> Refuse to concat a char.

- 3rdParty/V8/gyp/common.py
- 3rdParty/V8/gyp/msvs_emulation.py
- 3rdParty/V8/gypfiles/standalone.gypi
- 3rdParty/V8/v7.9.317/third_party/jinja2/tests.py
- CMakeLists.txt
backport of https://github.com/arangodb/arangodb/pull/15502 and https://github.com/arangodb/arangodb/pull/15552
> Fixed python imports to work with 3.10 (#15502)

- CHANGELOG
- arangod/Aql/OptimizerRulesCluster.cpp
- tests/js/server/aql/aql-optimizer-rule-optimize-cluster-single-document-operations.js
* Disable optimizer rule "optimize-cluster-single-document-operations" when a
collection is accessed in exclusive mode, because the optimized query would
use a slightly different mode of locking then.
> Disable an optimizer rule in exclusive lock mode

- arangod/Aql/Ast.cpp
- arangod/Aql/Ast.h
- arangod/Aql/Variable.h
the `_constAstNode` member in `Variable` was used before to track
the constant value of a variable in an AQL query. For example, in
`LET a = 1`, the `a` variable contained a `_constAstNode` pointer
to the AstNode containing `1`. This pointer was checked during
AST optimization and used for constant propagation, and remained
unused afterwards.
As we are tracking variable definitions during AST optimization in
a map anyway, this PR now removes the `_constAstNode` member from
`Variable` and simply relies on this map. This also allowed removal
of a few methods in `Ast` that became unused.
This is an internal change and should have no user-visible impact.
Thus also no CHANGELOG entry.
No backports are planned.
> remove internal `_constAstNode` from `Variable` struct

- tests/rb/HttpInterface/api-http-spec.rb
via ruby since we've got the more thorough shell-foxx-api-spec.js doing that now.
> delete test since  test for gzip transfer encoding /_api/version

- lib/Logger/LogContext.h
Follow-up PR to https://github.com/arangodb/arangodb/pull/15574. Contains the same changes as the original PR, but now has a CI-compatible branch name.
Add a suppression for UBSan that removes a false positive from being reported at server startup.
This affects only the `LogContext` object, which has been added in 3.10/devel only. So no backports are needed.
> add a suppression for UBSan

- Documentation/DocuBlocks/Rest/Administration/delete_api_shutdown.md
Intended to be used with load balancer, Coordinator to be removed from LB before soft-shutdown, continues to process requests!
> BTS-758 | Docs: Clarify intended usage and describe actual behavior of Coordinator soft-shutdown

- tests/js/server/aql/aql-inverted-index.js
- tests/js/server/aql/aql-iresearch-view-executor-regression.js
+ Add missing cleanup for the inverted index test. 
+ Removes asserton from tearDownAll of another test as assertions are not intened to be used in the tearDown and broke testing frameworks. Also there are plenty of tests in the aql-view-arangosearch-feature.js that checks proper analyzer add/remove
> add cleanup

- CHANGELOG
- arangod/Graph/GraphManager.cpp
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/862
Fix the creation of satellite graphs with a `numberOfShards` value != 1. 
This combination is invalid and is now rejected properly on the server side.
> Fix creation of satellite graphs with a `numberOfShards` value != 1.

- arangod/Aql/QueryList.cpp
- arangod/Aql/QueryList.h
devel fix will be part of #15514; other backports are not necessary because the faulty change was not backported to 3.8.
The problem was that when the QueryList acquires the shared_ptr, it can happen that once it drops that reference, it has to call the destructor (because this was the _last_ reference), which would then try to remove the query from the QueryList. For that we need to acquire the write lock, but since we are calling from some QueryList function that already holds the read lock, this results in a dead lock.
> Fix a potential deadlock in QueryList introduced in #15515

- lib/Basics/debugging.cpp
Several profiling runs showed high contention on the failure points lock when running with a maintainer build.
> Reduce overhead for checking failure points when none are set.

- lib/Logger/LogContext.h
- tests/Logger/LogContextTest.cpp
Previously chained `with<key>(value)` calls resulted in a quadratic number of moves/copies.
> Refactor LogContext to produce less moves/copies

- CHANGELOG
- client-tools/Dump/DumpFeature.cpp
- client-tools/Restore/RestoreFeature.cpp
This PR adds more detail to the log messages that display the total time consumption and total amount of data parsed for the client tools arangodump and arangorestore. 
No backports required.
> Added more detail to time consumption and data amount parsed log

- CHANGELOG
- arangod/RocksDBEngine/RocksDBOptionFeature.cpp
* Adjust interal RocksDB setting `optimize_filters_for_hits` for Documents
column family, setting it from `false` to `true`. This should reduce memory
and disk space requirements for the bottom-most .sst files of the documents
column family.
This PR only changes the value of an internal option. There is no need for end-user documentation or backports.
> Use `optimize_filters_for_hits` for documents CF

- 3rdParty/velocypack/include/velocypack/Slice.h
- 3rdParty/velocypack/src/Validator.cpp
- 3rdParty/velocypack/tests/testsValidator.cpp
Harden velocypack validator after fuzz testing.
Changes are from upstream https://github.com/arangodb/velocypack/pull/111
> Harden velocypack validator after fuzz testing

- arangod/Replication2/ReplicatedLog/AgencyLogSpecification.cpp
- arangod/Replication2/ReplicatedLog/AgencyLogSpecification.h
- arangod/Replication2/ReplicatedLog/Supervision.cpp
- tests/js/server/replication2/replication2-supervision-replicated-log-target-cluster.js
The log supervision tests were unstable because of an incorrect implementation of graceful leader change; we now select a new leader from the set of participants and dictate leadership again.
Also changes some tests to do what they say on the tin and wait for events correctly.
Does not fix error-reporting yet.
> [CINFRA-237] fix graceful leader replacement

- arangod/RocksDBEngine/RocksDBEngine.cpp
On startup, RocksDBEngine and LanguageSelectorFeature were racing to
update/access the global collator object. This PR adds some defined
order for these two features.
Fix verified manually using some database directory snapshot that triggered 
compaction early after server restart.
It is very likely this problem only occurs since the very recent changes to
ApplicationFeature and ApplicationServer, which could have had an impact
on startup order between two features that did not have a directly declared
dependency.
No backports are planned.
> fix startup dependency between features

- CHANGELOG
- arangod/Cluster/SynchronizeShard.cpp
Fix potentially dangling references in cancellation check of shard synchronization.
It is possible that some of the objects passed to the cancellation check lambda by reference are outlived by the cancellation check itself. This can cause undefined behavior when accessing these objects in the cancellation check lambda later.
This PR disables the extra cancellation check for shard synchronization, which was introduced in 3.8.5. The behavior for shard synchronization cancellation with this PR will be the same as in 3.8.4. The cancellation check will be fixed and reactivated with a follow-up PR.
This does not need to be backported to 3.7 as 3.7 did not get the cancellation check changes.
> fix potentially dangling references

- arangod/Cluster/CreateDatabase.cpp
Reduce log noise in development; only log severety of cluster database creation messages is decreased from INFO to DEBUG
> decrease loglevel for less noise in development.

- arangod/Agency/AsyncAgencyComm.cpp
- arangod/Agency/AsyncAgencyComm.h
- arangod/Cluster/ClusterInfo.cpp
- arangod/Cluster/ClusterInfo.h
- arangod/Replication2/Methods.cpp
- arangod/Replication2/ReplicatedLog/LogStatus.cpp
- arangod/Replication2/ReplicatedLog/LogStatus.h
- tests/Replication2/Serialization/LogStatusTest.cpp
- tests/js/common/shell/shell-replicated-logs-cluster.js
- tests/js/server/replication2/replication2-supervision-replicated-log-target-cluster.js
This PR add more information to the replicated log global status.
- It connects to the agency and queries for `Current/ReplicatedLogs/<db>/<logid>/supervision`.
- It connects to all participants and collects their local log status.
- It uses the local known plan for that. The plan used to gather information is added to the response as well.
> [CINFRA-239] Detailed global status

- arangod/Cluster/UpdateReplicatedLogAction.cpp
- arangod/Cluster/UpdateReplicatedStateAction.cpp
- js/server/modules/@arangodb/testutils/replicated-logs-helper.js
This PR tries to fix a timeout in Jenkins:
1. Put the Replicated Log/State actions on the fast track. Otherwise it can happen that they are executed after SynchronizeShard actions. This leads to timeouts in the test.
2. Increase the test timeout to two minutes. Jenkins is not a realtime system.
> [CINFRA-249] Replicated Maintenance Actions Fast Track

- CHANGELOG
- arangod/Aql/OptimizerRulesCluster.cpp
- arangod/Aql/RegisterPlan.cpp
- arangod/Aql/SingleRemoteModificationExecutor.cpp
- tests/js/server/aql/aql-optimizer-rule-optimize-cluster-single-document-operations.js
Fixed the issue restricted to cluster mode in which queries containing the keywords UPDATE or REPLACE together with the keyword WITH and the same key value would result in an error. For example: 
`UPDATE 'key1' WITH {_key: 'key1'} IN Collection`
because the same key used to update was provided in the object to update the document with. 
3.8 backport.
> Bug fix 3.8/bts 750

- CHANGELOG
- arangod/RocksDBEngine/RocksDBOptionFeature.cpp
- arangod/Transaction/Methods.cpp
*Consistent RocksDB throttling, when compactions are pending*. The RocksDB throttle is only effective when RocksDB goes into "stall", otherwise it is ignored. Therefore this setting prevents oscillations between "full speed writing" leading to compaction debt, and complete RocksDB stops.
> [3.8] more consistent rocksdb throttle in compating

- CHANGELOG
- arangod/Agency/Supervision.cpp
- arangod/Cluster/SynchronizeShard.cpp
- arangod/Replication/DatabaseInitialSyncer.cpp
- arangod/Replication/DatabaseInitialSyncer.h
- tests/js/client/shell/shell-abort-replication-cluster.js
Reintroduce shard synchronization cancellation check after it was previously disabled.
This PR reintroduces periodic checks during shard synchronization, so that the synchronization on followers is cancelled when the leader is marked as failed by the supervision.
The feature was introduced before in 3.8.5 but had a flaw, so we disabled it there.
The PR contains a new test that triggers the previously problematic code section, which led to issues in the previous version of the cancellation check.
Established that the new code works by running
```
for i in `seq 1 10`; do scripts/unittest shell_client --test tests/js/client/shell/shell-abort-replication-cluster.js  --cluster true; if [[ "x$?" != "x0" ]]; then echo "error!"; break; fi; done
```
No backports for 3.7 are needed, because it …
> reintroduce disabled shard synchronisation cancellation check

- CHANGELOG
- arangod/Aql/WindowExecutor.cpp
- tests/Aql/WindowExecutorTest.cpp
Backport of https://github.com/arangodb/arangodb/pull/15690
No conflicts, code has not been altered in devel.
If the WINDOW statement is placed within a Subquery there is an unlikely chance it skips over a block of data. This only happens if the internal batching cuts of exactly between the last dataRow and the shadowRow (indicating completeness of one SubqueryRun), and there are more than 1000 rows ahead (more than another block).
> Bug fix/window executor in subqueries (#15690)

- arangod/RocksDBEngine/RocksDBVPackIndex.cpp
- arangod/RocksDBEngine/RocksDBVPackIndex.h
Remove unused `_allowPartialIndex` attribute, make `_format` instance variable const.
This is an internal code cleanup. It doesn't change behavior or adds new functionality. No documentation needed. No backports are planned.
> remove unused `_allowPartialIndex` attribute

- arangod/Replication2/ReplicatedLog/LogFollower.cpp
- arangod/Replication2/ReplicatedLog/LogFollower.h
- arangod/Replication2/ReplicatedLog/LogLeader.cpp
- arangod/Replication2/ReplicatedLog/ReplicatedLog.cpp
- tests/Replication2/Mocks/FakeReplicatedLog.h
Instead of an assertion it is now a fatal error if the spearheads term is bigger than the current term. If this happens in production there is no way to continue. https://arangodb.atlassian.net/browse/CINFRA-128
> [CINFRA-128] Spearhead.term to big

- tests/js/server/replication2/replication2-replicated-log-entry-cluster.js
The test in question updated plan, instead of Target. This introduced a race, between the test finishing and the supervision detecting the difference between Target and Plan. If the supervision is faster, the test will see 3 log entries instead of two.
> [CINFRA-257] Test Error due to Plan update

- CHANGELOG
- arangod/RocksDBEngine/Listeners/RocksDBMetricsListener.cpp
*As we are contantly in stall regime, stall related log messages are demoted to `DEBUG`*
> debug logging for rocksdb stall events only

- CHANGELOG
- arangod/RocksDBEngine/Listeners/RocksDBMetricsListener.cpp
*As we are contantly in stall regime, stall related log messages are demoted to `DEBUG`*
> [3.8] debug logging for rocksdb stall events only

- arangod/Agency/Inception.cpp
- arangod/Agency/Inception.h
Avoid a deadlock in agency, when Inception::gossip() acquired a mutex, then could call Agent under the mutex, and Agent could finally could call Inception::signalConditionVar(), which would try to acquire the mutex again.
It is yet unclear if this needs to be backported.
> avoid deadlock in agency

- CHANGELOG
- arangod/RocksDBEngine/Listeners/RocksDBMetricsListener.cpp
*As we are contantly in stall regime, stall related log messages are demoted to `DEBUG`*
> [3.9] debug logging for rocksdb stall events only

- .clang-format
Do not let clang-format guess what alignment we want for pointer and reference modifiers as this can under ceratain circumstances lead to gratuitous reformatting.
> Set DerivePointerAlignment: false in .clang-format

- arangod/Cluster/ClusterFeature.cpp
> --cluster.max-number-of-move-shards introduced in 3.9.0

- arangod/Cluster/SynchronizeShard.cpp
- arangod/Replication/DatabaseInitialSyncer.cpp
- js/client/modules/@arangodb/test-helper.js
- tests/js/server/replication/sync/replication-sync.js
https://arangodb.atlassian.net/browse/BTS-801
Re-enable intermediate commits during initial sync phase of the replication.
The issue only affects devel. No backport is needed for this.
> reenable intermediate commits during replication

- arangod/Cluster/FailureOracleFeature.cpp
- arangod/RestServer/UpgradeFeature.cpp
This aims to fix the following error: `caught exception during start of feature 'FailureOracle': feature 'Cluster' is not enabled (exception location: /work/ArangoDB/lib/ApplicationFeatures/ApplicationServer.h:466)`.
It is suspected that during `UpgradeFeature` the `ClusterFeature` gets disabled, and thus other features which depend on it should too.
> [BTS-800] Cluster not enabled exception

- .clang-format
- .githooks/pre-commit
- scripts/clang-format.sh
Backport of https://github.com/arangodb/arangodb/pull/15800
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/898
Small improvement for clang-formatting script: make script and docker container react on CTRL-C, and don't block the signal.
Also backport changes that others made to `.clang-format` in devel.
> improve clang-format script

- CHANGELOG
- arangod/RestHandler/RestCollectionHandler.cpp
- arangod/V8Server/v8-vocindex.cpp
- arangod/VocBase/Methods/Collections.cpp
- arangod/VocBase/Methods/Collections.h
Backport of (https://github.com/arangodb/arangodb/pull/15795)
No Conflicts.
In order to get DC-2-DC to work, we need to allow the ArangoSync process to set more (and dangerous) options when creating the Collections, it cannot use the GraphsAPI (like the user can), as it needs a bit more fine-grained control about the sharing being identical on source and target datacenter.
Tests for this are in ArangoSync repository.
> [3.9] Give superpowers to arangsync for SmartGraphs

- js/client/modules/@arangodb/testsuites/recovery_cluster.js
This improves test result handling, so the test flow will not be abortet by exceptions in mid air, and fail to deliver results as seen here: 
```
caught exception during test execution!
cluster startup: pid 18275 no longer alive! bailing out!
Error: cluster startup: pid 18275 no longer alive! bailing out!
at /work/ArangoDB/js/client/modules/@arangodb/testutils/process-utils.js:1924:15
at Array.forEach (<anonymous>)
at checkClusterAlive (/work/ArangoDB/js/client/modules/@arangodb/testutils/process-utils.js:1895:27)
at Object.reStartInstance (/work/ArangoDB/js/client/modules/@arangodb/testutils/process-utils.js:2566:5)
at runArangodRecovery (/work/ArangoDB/js/client/modules/@arangodb/testsuites/recovery_cluster.js:187:8)
at Object.recovery [as recovery_cluster] …
```
> catch probable test exception so we have good results

- arangod/Agency/Supervision.cpp
- arangod/Replication2/ReplicatedLog/ParticipantsHealth.h
- arangod/Replication2/ReplicatedLog/Supervision.cpp
- arangod/Replication2/ReplicatedLog/Supervision.h
- tests/Replication2/ReplicatedLog/SupervisionTest.cpp
For the purposes of the Supervision of ReplicatedLogs, we previously treated servers marked as BAD as not healthy (which triggers a leadership election). 
With this patch we treat a BAD server as not failed and continue operation.
> [CINFRA-266] Treat BAD servers as OK

- tests/Replication2/Mocks/PersistedLog.cpp
- tests/Replication2/Mocks/PersistedLog.h
- tests/Replication2/ReplicatedLog/WaitForSyncTest.cpp
This PR adds unit tests for the LogLeader and LogFollower. These tests check if both units forward the waitForSynch flag to the persistor as expected.
> [CINFRA-271] WaitForSync Persistor Test

- arangod/Replication2/DeferredExecution.h
- arangod/Replication2/ReplicatedState/FollowerStateManager.h
- arangod/Replication2/ReplicatedState/FollowerStateManager.tpp
- arangod/Replication2/ReplicatedState/LeaderStateManager.h
- arangod/Replication2/ReplicatedState/LeaderStateManager.tpp
- arangod/Replication2/ReplicatedState/ReplicatedState.h
- arangod/Replication2/ReplicatedState/ReplicatedState.tpp
- arangod/Replication2/ReplicatedState/StateInterfaces.h
- arangod/Replication2/ReplicatedState/UnconfiguredStateManager.h
- arangod/Replication2/ReplicatedState/UnconfiguredStateManager.tpp
- tests/CMakeLists.txt
- tests/Replication2/Mocks/FakeReplicatedState.h
- tests/Replication2/ReplicatedState/FollowerWaitForTest.cpp
Adds a `waitForApplied` function to follower states and the follower state manager. It returns a future that is resolved if either the given index was applied or the participant has resigned. This is used for reading on follower to synchronize with writes on leader.
> [CINFRA-260] waitForApplied for FollowerStateManager

- 3rdParty/velocypack/include/velocypack/Parser.h
This is a follow-up to bugfix PR https://github.com/arangodb/arangodb/pull/15661. This PR fixes a theoretical issue in VelocyPack when exceeding the maximum nesting level when parsing a JSON value. When invoking the `parse` method multiple times on the same Parser object, the `_nesting` attribute of the Parser was not reset back to 0 when starting the parsing.
This is only a theoretical issue because no maximum nesting level is set for JSON/VPack objects before 3.10/devel. Anyway, it should be fixed in 3.9 too in case a maximum nesting level is introduced at some later point.
Test cases are added via the arangodb/velocypack repository: https://github.com/arangodb/velocypack/pull/122
Other, still open velocypack-related backports for 3.8 and 3.7 have been adjusted so they now include the …
> reset nesting level on each invocation of parse

- arangod/Agency/Supervision.cpp
- arangod/Replication2/ReplicatedLog/Supervision.cpp
- arangod/Replication2/ReplicatedLog/Supervision.h
- arangod/Replication2/ReplicatedLog/SupervisionAction.cpp
- arangod/Replication2/ReplicatedLog/SupervisionAction.h
- tests/Replication2/ReplicatedLog/SupervisionTest.cpp
- tests/js/server/replication2/replication2-supervision-replicated-log-target-cluster.js
This is the first half of #15830 
The rationale behind doing the refactor in two steps is to make sure we break less code on the way, hence making debugging easier (ideally not necessary).
This half refactors SupervisionActions into a variant of simple structs which can be `std::visit`ed using an (also fairly simple) `Exectutor` struct, which itlsef encapsulates some information that was previously assembled manually, such as the path-prefix that is used for writing into the agency.
> [CINFRA-273] Refactor ReplicatedLog SupervisionAction

- js/client/modules/@arangodb/testutils/test-utils.js
if the windows testen vironment lacks a rspec installation return a propper error message so no guesswork is needed
https://github.com/arangodb/arangodb/pull/15849
> better error message in testfailures.txt if an incomplete rspec install is there

- CHANGELOG
- arangod/Agency/Inception.cpp
- arangod/Agency/Inception.h
Backport of https://github.com/arangodb/arangodb/pull/15773
Avoid a deadlock in agency, when Inception::gossip() acquired a mutex, then could call Agent under the mutex, and Agent could finally could call Inception::signalConditionVar(), which would try to acquire the mutex again.
> avoid deadlock in agency (#15773)

- CHANGELOG
- arangod/RocksDBEngine/RocksDBEngine.cpp
Log a better startup error in case an ArangoDB 3.8 is started on a too new database directory (3.9 or higher).
> Improve startup error logging

- arangod/Transaction/Methods.cpp
This PR should fix a devel-only compile error with AppleClang when compiling in non-maintainer mode:
```
/Users/jenkins/hw35-mac/oskar/work/ArangoDB/arangod/Transaction/Methods.cpp:1483:37: error: lambda capture 'numExclusions' is not used [-Werror,-Wunused-lambda-capture]
auto workForOneDocument = [this, &numExclusions, &operation, &options,
~~~^~~~~~~~~~~~~
1 error generated.
```
The code in question is not in any other versions than devel, so no backports are needed.
> fix compile error in non-maintainer mode on AppleClang

- arangod/IResearch/IResearchDataStore.cpp
- arangod/IResearch/IResearchDataStore.h
- arangod/IResearch/IResearchInvertedIndex.cpp
- arangod/IResearch/IResearchInvertedIndex.h
- arangod/IResearch/IResearchLink.cpp
- arangod/IResearch/IResearchLink.h
- arangod/IResearch/IResearchLinkCoordinator.cpp
- arangod/IResearch/IResearchLinkCoordinator.h
- arangod/IResearch/IResearchRocksDBInvertedIndex.cpp
- arangod/IResearch/IResearchRocksDBLink.cpp
- arangod/IResearch/IResearchRocksDBLink.h
- tests/IResearch/IResearchInvertedIndexIteratorTest.cpp
- tests/IResearch/IResearchViewDBServerTest.cpp
- tests/IResearch/IResearchViewTest.cpp
- tests/Mocks/StorageEngineMock.cpp
Fix SEARCH-294: remove DataStore when not valid initialization
Also, fix possible leak physical DataStore directory
> Fix SEARCH-294: remove DataStore when not valid initialization

- arangod/Aql/Ast.cpp
- arangod/Aql/AstNode.h
- arangod/Aql/BindParameters.cpp
- arangod/Aql/BindParameters.h
- tests/js/server/aql/aql-bind.js
Less copying of repeatedly used bind parameter values in AQL queries.
This reduces memory overhead for queries that access large bind parameter values (large arrays or objects) via repeatedly refering to them by name (e.g. `FOR doc IN collection FILTER doc.value == CONCAT(@largeBind['foo'], @largeBind['bar'], @largeBind[...], ...`).
The bind parameter values are only once converted into an AstNode per query, and from the on only shallow-cloned when accessed.
In some example query this decreased memory usage by 99%.
> less copying of repeatedly used bind parameter values

- arangod/Cluster/AgencyCallback.cpp
- arangod/Cluster/AgencyCallback.h
- arangod/Cluster/FailureOracleFeature.cpp
- tests/js/server/replication2/replication2-replicated-log-entry-cluster.js
This PR adds a second parameter to agency callback functions. It contains the raft index of the entry that triggered the callback. This is then used in the Failure Oracle to skip callbacks for older indexes if a later updates has already been received.
> [CINFRA-265] Update race in Failure Oracle

- tests/Replication2/ReplicatedState/ReplicatedStateTest.cpp
This PR fixes compiler warnings in the arangodb tests.
> Fixing compiler warnings.

- arangod/Replication2/Methods.cpp
- arangod/Replication2/Methods.h
- arangod/RestHandler/RestLogHandler.cpp
- arangod/V8Server/v8-replicated-logs.cpp
- js/client/modules/@arangodb/replicated-logs.js
- tests/js/common/shell/shell-replicated-logs-cluster.js
- tests/js/server/replication2/replication2-supervision-replicated-log-target-cluster.js
`_api/log/<id>/global-status` now by default uses a direct read from the agency instead of the local cache. This is to make sure, that we do not run into caching issues. If you want to access the local cache, you can specify the `useLocalCache`.
> [CINFRA-234] Remote Global Status Specification

- CHANGELOG
- arangod/StorageEngine/HotBackupCommon.h
This is a small bug fix to get the counts and file size sum in hotbackup
META files correct. The problem was that due to a bug in the accounting
directories have been counted, rendering the sums incorrect. This PR
is accompanied by an enterprise PR and together they fix the sums and
add a new filed to recognize new style META files.
- Get counts in hotbackup META files right.
- CHANGELOG.
This is the first quick step towards fulfilling this ticket.
> Fix counts and size sum in hotbackup META files APM-409

- CHANGELOG
Fix 3.8 changelog:
A few PRs were merged after the release of v3.8.6, and the newer changes should be attributed to the v3.8.7 CHANGELOG.
This PR only modifies the CHANGELOG.
> move some CHANGELOG entries to 3.8.7, where they belong

- tests/js/common/shell/shell-replicated-logs-cluster.js
Because of some timestamps that got into the log status values, two close requests are not guaranteed to yield the same results. The purpose of this test is to make sure that coordinator/status and coordinator/global-status are the same thing, so comparing only the keys would suffice.
> [CINFRA-298] Fix for testStatus

- arangod/Replication2/Methods.cpp
- arangod/Replication2/Methods.h
- arangod/Replication2/ReplicatedLog/Supervision.cpp
- arangod/Replication2/ReplicatedLog/SupervisionAction.cpp
- arangod/Replication2/ReplicatedLog/SupervisionAction.h
- arangod/RestHandler/RestLogHandler.cpp
- arangod/RestHandler/RestReplicatedStateHandler.cpp
When a replicated log or replicated state is created, the Methods now fill up missing participants according to the replication factor. The servers are selected randomly.
> [CINFRA-302] Select Participants in RestHandler

- arangod/WasmServer/Methods.cpp
- arangod/WasmServer/Methods.h
- arangod/WasmServer/RestWasmHandler.cpp
- arangod/WasmServer/WasmCommon.cpp
- arangod/WasmServer/WasmCommon.h
- arangod/WasmServer/WasmServerFeature.cpp
- arangod/WasmServer/WasmServerFeature.h
- js/client/modules/@arangodb/aql/wasmFunctions.js
This PR includes changes for two tickets:
- PREG-78 Write RestHandler to GET all registered wasm functions
I also improved the responses of all handler functions and corrected the add-function functionality (now functions are overwritten when you post a function with an already existing name)
- PREG-60 Write JavaScript module to install/remove/query wasm functions
> [PREG-60 and PREG-78]

- arangod/Replication2/StateMachines/Prototype/PrototypeStateMachine.cpp
- arangod/Replication2/StateMachines/Prototype/PrototypeStateMachine.h
- tests/Replication2/ReplicatedState/PrototypeStateMachineTest.cpp
There was a problem with the serialization of newly inserted state machine entries, when sending them to the replicated log. Therefore, only one out of multiple key-value pairs would get inserted into the state machine.
This PR fixes the serialization method and improves the `PrototypeStateMachineTest`. For that, an additional get method was introduced on the `PrototypeFollowerState`.
> [CINFRA-299] Invalid Log Entries Created from Prototype

- arangod/RocksDBEngine/RocksDBReplicationIterator.cpp
We can get away with calling Compare() here, because we have set iterate_upper_bound on the rocksdb::Iterator.
This is a small performance optimization, very likely negligible.
There is no intention to backport this change.
> speed up comparisons in replication iterator

- tests/js/server/replication/sync/replication-sync-malarkey.js
Test-only bugfix: the previous version of the replication-sync-malarkey test retrieved large documents from the server, which could have overwhelmed V8 in terms of memory usage. now use a simpler version.
> fix potential tests failure in replication_sync test

- arangod/WasmServer/Methods.cpp
- arangod/WasmServer/Methods.h
- arangod/WasmServer/RestWasmHandler.cpp
- arangod/WasmServer/WasmCommon.cpp
- arangod/WasmServer/WasmCommon.h
- arangod/WasmServer/WasmServerFeature.cpp
- arangod/WasmServer/WasmServerFeature.h
- tests/WasmServer/WasmFunctionSliceTest.cpp
- Renames variables and functions to make clear when a function and when a module is relevant
- Includes wrapping types for FunctionName and ModuleName to assure type safety
- When executing a function, now you need to give a module name and a function name
> [PREG-86] Separate module and function concepts

- CHANGELOG
- UnitTests/OskarTestSuitesBlockList
This PR adds fuzzer tests to oskar blocklist in version 3.7, as they only should be triggered in devel. 
The tests were introduced in https://github.com/arangodb/arangodb/pull/15828 and registered in oskar in https://github.com/arangodb/oskar/pull/379.
There's no PR for adding this restriction on devel, but I'll consider as backport as there is gonna be the same PR in 3.9 and 3.8 as well, so this is the 3.7 backport.
> Feature 3.7/add fuzzer to tests blocklist

- lib/CMakeLists.txt
- lib/Rest/PathMatch.h
- tests/CMakeLists.txt
- tests/Rest/PathMatchTest.cpp
Provide a simple way to pattern-match REST-paths.
> rest::Match

- CHANGELOG
- arangod/Aql/AqlFunctionFeature.cpp
- arangod/Aql/Functions.cpp
- arangod/Aql/Functions.h
- js/apps/system/_admin/aardvark/APP/react/public/assets/src/mode-aql.js
- tests/js/server/aql/aql-functions-brute.js
- tests/js/server/aql/aql-functions.js
- tests/js/server/aql/aql-stresstest-nightly.js
We have the function pair `UNSET()` and `KEEP()` but no counterpart to `UNSET_RECURSIVE()`. A user asked for `KEEP_RECURSIVE()` in the community slack and it turns out that the functionality is already there, just needing to be exposed and unit-tested.
> AQL: Add `KEEP_RECURSIVE()` function

- arangod/Replication2/ReplicatedLog/LogCommon.cpp
- arangod/Replication2/ReplicatedLog/LogCommon.h
- arangod/Replication2/ReplicatedLog/LogCore.cpp
- arangod/Replication2/ReplicatedLog/LogCore.h
- arangod/Replication2/ReplicatedLog/PersistedLog.h
- arangod/Replication2/ReplicatedLog/ReplicatedLog.cpp
- arangod/Replication2/ReplicatedLog/ReplicatedLog.h
- arangod/Replication2/ReplicatedState/ReplicatedState.h
- arangod/Replication2/ReplicatedState/ReplicatedState.tpp
- arangod/Replication2/StateMachines/BlackHole/BlackHoleStateMachine.cpp
- arangod/Replication2/StateMachines/BlackHole/BlackHoleStateMachine.h
- arangod/Replication2/StateMachines/Prototype/PrototypeStateMachine.cpp
- arangod/Replication2/StateMachines/Prototype/PrototypeStateMachine.h
- arangod/RocksDBEngine/RocksDBEngine.cpp
- arangod/RocksDBEngine/RocksDBPersistedLog.cpp
- arangod/RocksDBEngine/RocksDBPersistedLog.h
- tests/Replication2/Mocks/FakeReplicatedState.h
- tests/Replication2/Mocks/PersistedLog.cpp
- tests/Replication2/ReplicatedLog/RocksDBLogTest.cpp
- tests/Replication2/ReplicatedState/LeaderRecoveryTest.cpp
- tests/Replication2/ReplicatedState/StateMachines/MyStateMachine.cpp
- tests/Replication2/ReplicatedState/StateMachines/MyStateMachine.h
This PR adds the `constructCore(LogId)` method to the replicated states factory. This allows for more flexibility, as currently there is no way of passing additional arguments to the constructor of `core`.
Our use-case is to pass a `TransactionDB`, that's going to be used for RocksDB serialization.
> [CINFRA-312] Add constructCore method to factory

- CHANGELOG
- lib/Logger/LogTopic.cpp
We found that replication document writes are audit logged on the DEBUG
log level of the topic "audit-document". Seemingly accidentally the
default log level for this topic is currently DEBUG. This leads to
extreme delays for shards trying to get in sync, since there there is
an audit log call for every single document being replicated. Since
a synchronously written audit log can delay writing a document by up
to a factor of 1000 and since the document write has already been audit
logged on the leader, we propose to set the default log level for
"audit-document" to INFO, which was probably intended in the first
place.
Similarly, the default log level for "audit-authentication" is also
DEBUG. This leads that non-authentication events for low priority things
like credentials missing for …
> Do not audit log replication writes by default [BTS-826]

- arangod/Aql/Functions.cpp
- arangod/WasmServer/Methods.cpp
- arangod/WasmServer/Methods.h
- arangod/WasmServer/RestWasmHandler.cpp
- arangod/WasmServer/Wasm3cpp.h
- arangod/WasmServer/WasmServerFeature.cpp
- arangod/WasmServer/WasmServerFeature.h
- tests/js/client/shell/shell-wasm.js
Execution time is not down to 0.02 s for wasm addition vs something between 0.01 0.02 s for native addition (10.000 rows).
Runtime is created when the feature is constructed.
A set makes sure that we load modules only once into the runtime.
Unclear:
- Currently there is no possibility to delete a module from the runtime
- Not sure if the loadedModules set has to be guarded, nothing is deleted from it so far, therefore I think it should be ok like it is right now
> [PREG-107] Improve wasm execution time

- CHANGELOG
- UnitTests/OskarTestSuitesBlockList
This PR adds fuzzer tests to oskar blocklist in version 3.8, as they only should be triggered in devel. 
The tests were introduced in https://github.com/arangodb/arangodb/pull/15828 and registered in oskar in https://github.com/arangodb/oskar/pull/379.
There's no PR for adding this restriction on devel, but I'll consider as backport as there is gonna be the same PR in 3.9 and 3.7 as well, so this is the 3.8 backport.
> Feature 3.8/add fuzzer to tests blocklist

- CHANGELOG
- UnitTests/OskarTestSuitesBlockList
This PR adds fuzzer tests to oskar blocklist in version 3.9, as they only should be triggered in devel. 
The tests were introduced in https://github.com/arangodb/arangodb/pull/15828 and registered in oskar in https://github.com/arangodb/oskar/pull/379.
There's no PR for adding this restriction on devel, but I'll consider as backport as there is gonna be the same PR in 3.8 and 3.7 as well, so this is the 3.9 backport.
> Feature 3.9/add fuzzer to tests blocklist

- arangod/Agency/AgencyFeature.h
- arangod/Aql/Functions.cpp
- arangod/Aql/Query.h
- arangod/RestHandler/RestControlPregelHandler.cpp
- arangod/RestServer/ServerFeature.cpp
- arangod/V8Server/v8-collection-util.cpp
- arangod/V8Server/v8-collection.cpp
- arangod/V8Server/v8-collection.h
- arangod/VocBase/Methods/Collections.cpp
- arangod/VocBase/Methods/Collections.h
- arangod/VocBase/Methods/Databases.cpp
- arangod/VocBase/Methods/Indexes.cpp
Remove a few unused includes of headers that rely on v8.
Move some functions that are not v8-related out of v8-related code files.
This PR contains only an internal refactoring and should not change user-visibile behavior.
No backports are planned.
> make some internal code parts not unnecessarily depend on v8

- lib/Inspection/Access.h
- lib/Inspection/InspectorBase.h
- lib/Inspection/Result.h
- lib/Inspection/VPack.h
- lib/Inspection/VPackLoadInspector.h
- lib/Inspection/VPackSaveInspector.h
- lib/Inspection/detail/traits.h
- tests/Basics/InspectionTest.cpp
- tests/CMakeLists.txt
Adds a type inspection framework for simple serialization/deserialization of custom types from/to velocypack.
The underlying concept is very generic, so it should be easy to extend it and implement inspectors for (de)serializion from/to agency nodes.
This PR only adds the framework itself + tests.
Documentation is still missing and will be added in a separate PR.
> Add type inspection for VPack de/serialization.

- tests/js/server/replication/sync/replication-sync-malarkey.js
Backport of https://github.com/arangodb/arangodb/pull/15879
Test-only bugfix: the previous version of the replication-sync-malarkey test retrieved large documents from the server, which could have overwhelmed V8 in terms of memory usage. now use a simpler version.
> fix potential tests failure in replication_sync test (#15879)

- arangod/Cache/CacheManagerFeature.cpp
- arangod/RestServer/TtlFeature.cpp
- arangod/RocksDBEngine/RocksDBEngine.cpp
Allow turning off edge cache and background TTL thread ia config options as advertised by their respective startup options help texts.
No backports are planned for this.
> allow turning off edge cache and TTL thread

- arangod/RestServer/EnvironmentFeature.cpp
- arangod/RocksDBEngine/RocksDBBuilderIndex.cpp
- arangod/RocksDBEngine/RocksDBBuilderIndex.h
- arangod/RocksDBEngine/RocksDBCollection.cpp
- arangod/RocksDBEngine/RocksDBSettingsManager.cpp
- client-tools/Benchmark/testcases/CustomQueryTestCase.h
- lib/ApplicationFeatures/LanguageFeature.cpp
- lib/ApplicationFeatures/LanguageFeature.h
- lib/Basics/FileUtils.cpp
- lib/Basics/FileUtils.h
- tests/Basics/icu-helper.cpp
- tests/Basics/icu-helper.h
- for loading icudtl.dat. previously a string buffer was built up
incrementally while reading the binary input file, while triggered
some resize operations and some final overallocation along the way. as
the size of the input file is precisely known when loading the file,
we can get away with reserving a buffer of exactly the required size
instead.
- when creating initial indexes for initial collections: previously, a
(temporary) memory allocation of 32MB was done per index creation.
this is now reduced to smaller amounts of memory if the indexes are
expected to contain few documents
No backports are planned for these changes
> reduce memory usage at startup

- arangod/Metrics/ClusterMetricsFeature.cpp
- arangod/RestHandler/RestCompactHandler.cpp
- arangod/RocksDBEngine/RocksDBLogValue.cpp
- arangod/RocksDBEngine/RocksDBValue.cpp
- arangod/VocBase/Identifiers/RevisionId.cpp
- arangod/VocBase/Identifiers/RevisionId.h
Remove compile-time dependency on RocksDB headers for code that doesn't need them.
Simple refactoring. No backports are needed for this change.
> remove compile dependency on RocksDB from unrelated code

- lib/Inspection/Access.h
- lib/Inspection/InspectorBase.h
- lib/Inspection/VPackLoadInspector.h
- lib/Inspection/VPackSaveInspector.h
- tests/Basics/InspectionTest.cpp
Some improvements for the type inspection library.
- Allow keeping the current value as fallback.
- Allow passing const& values when saving.
> Improvements for the type inspection library

- arangod/GeneralServer/AuthenticationFeature.cpp
> BTS-820 | Clarify effect of `--server.session-timeout`

- Documentation/DocuBlocks/Rest/Transactions/post_api_transaction.md
- Documentation/DocuBlocks/Rest/Transactions/post_api_transaction_begin.md
The JS Transaction endpoint `_api/transaction` and the Stream Transaction endpoint `_api/transaction/begin` accept a parameter `lockTimeout`. We fail to mention the unit (https://github.com/arangodb/docs/issues/938). It is **seconds** according to @jsteemann.
TODO: What is the default value that is mentioned?
> If not specified, a default value will be used.
Does it refer to the startup option `--transaction.streaming-lock-timeout` in case of Stream Transactions?
What about JS Transactions? There is another startup option `--rocksdb.transaction-lock-timeout` but the unit is milliseconds and it seems unrelated to me (storage engine).
> Docs: Add unit to lockTimeout (seconds)

- scripts/unittest
When `scripts/unittest` got passed a build directory via `--build`, it didn't take this into account when looking for the `arangosh` binary. This PR fixes that, preferring to use that `arangosh` executable if available (unless the environment variable `ARANGOSH` is set).
> Prefer arangosh from --build directory

- tests/js/client/shell/api/async.js
Fix spuriously failing query-analysis test. The test failures are due to another test not cleaning up properly.
This is an issue only in testing, and it only affects devel. No backports are needed.
> fix spuriously failing test

- arangod/Cluster/MaintenanceFeature.cpp
- arangod/RestServer/EndpointFeature.cpp
- arangod/RestServer/WindowsServiceFeature.cpp
- client-tools/Backup/BackupFeature.cpp
- client-tools/Benchmark/BenchFeature.cpp
- client-tools/Dump/DumpFeature.cpp
- client-tools/Export/ExportFeature.cpp
- client-tools/Import/ImportFeature.cpp
- client-tools/Restore/RestoreFeature.cpp
- client-tools/Shell/ClientFeature.cpp
- client-tools/Shell/ShellConsoleFeature.cpp
- client-tools/Shell/ShellFeature.cpp
- client-tools/Shell/V8ShellFeature.cpp
- client-tools/VPack/VPackFeature.cpp
- lib/ApplicationFeatures/ApplicationFeature.cpp
- lib/ApplicationFeatures/ApplicationFeature.h
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/916
Removes the _requiresElevatedPrivileges flag from ApplicationFeature.
That flag was set by different features, but it had no effect, because the flag's value was nowhere read later.
This change does not need to be backported.
> remove obsolete flag from ApplicationFeature

- client-tools/CMakeLists.txt
Do not make arango{dump,restore,import} depend on fuerte.
None of these client tools uses fuerte, so there should be no compile-time dependency on it.
> do not make dump/restore/import depend on fuerte

- CHANGELOG
- client-tools/Restore/RestoreFeature.cpp
In case the new data format (useEnvelope = false) was used with arangodump, arangorestore can submit multiple batches with documents concurrently. That way a restore can be multi-threaded even for a single collection. Due to some invalid if condition, the logic was reversed and parallelism was turned off when using the new format.
This probably needs a backport to 3.9, will check.
> Improve restore parallelism for new data format

- arangod/Scheduler/SupervisedScheduler.cpp
- tests/js/client/server_parameters/test-return-queue-time-header-on.js
Attempt to stabilize a test that sporadically failed depending on the current server load.
The test checks for queuing times on the server, so it is obviously load-dependent.
The changes in this PR try to give the test more room for the desired situation to kick in.
This is a test-only fix. The server behavior is not affected.
This PR is a follow-up to https://github.com/arangodb/arangodb/pull/16033, which did not fully solve the instability.
> try to stabilize test even more

- lib/Basics/ConditionLocker.cpp
- lib/Basics/ConditionLocker.h
- lib/Basics/Locking.h
- lib/Basics/MutexLocker.h
- lib/Basics/MutexUnlocker.h
- lib/Basics/ReadLocker.h
- lib/Basics/WriteLocker.h
- lib/Logger/LogThread.cpp
Remove obsolete `#ifdef`s from code in locking classes:
* `ARANGODB_SHOW_LOCK_TIME`
* `TRI_SHOW_LOCK_THRESHOLD`
These ifdefs were used in the olden days of ArangoDB 2.x to conditionally compile some time measurement functionality for locking-related code.
There is no official way (e.g. via CMake) to activate these ifdefs, so it is effectively code that hasn't been used for years.
> remove obsolete #ifdef sections from the code

- arangod/Replication2/ReplicatedLog/Supervision.cpp
- arangod/Replication2/ReplicatedLog/SupervisionAction.h
Remove `EvictLeaderAction` as it simulated a failed leader by just removing the leader from the Plan.
This is harmful and was due to my earlier lack of understanding of replicated logs.
> [CINFRA-343] EvictLeaderAction considered harmful

- arangod/Cluster/AgencyCache.cpp
- arangod/Cluster/AgencyCache.h
- arangod/Replication2/AgencyMethods.cpp
- arangod/Replication2/AgencyMethods.h
- arangod/Replication2/Methods.cpp
- arangod/Replication2/Methods.h
- arangod/RestHandler/RestReplicatedStateHandler.cpp
- js/server/modules/@arangodb/testutils/replicated-logs-helper.js
- js/server/modules/@arangodb/testutils/replicated-logs-predicates.js
- js/server/modules/@arangodb/testutils/replicated-state-helper.js
- js/server/modules/@arangodb/testutils/replicated-state-predicates.js
- tests/js/server/replication2/replication2-maintenance-replicated-log-cluster.js
- tests/js/server/replication2/replication2-maintenance-replicated-state-cluster.js
- tests/js/server/replication2/replication2-regression.js
- tests/js/server/replication2/replication2-replicated-log-entry-cluster.js
- tests/js/server/replication2/replication2-replicated-state-http-api-cluster.js
- tests/js/server/replication2/replication2-soft-write-concern-replicated-log-cluster.js
- tests/js/server/replication2/replication2-supervision-replicated-log-target-cluster.js
- tests/js/server/replication2/replication2-supervision-replicated-state-target-cluster.js
- tests/js/server/resilience/failover/resilience-failure-oracle.js
The HTTP API to replace the participant of a replicated state did not touch the state's `leader` property. This PR changes this: If the to-be-replaced participant currently is the leader, the API call will also set the leader to be the new participant.
Additional minor changes:
* Fixed a race in `tests/js/server/replication2/replication2-regression.js` / `testFailedServerDoesNotPreventProgress`
* Moved log predicates into their own file `replicated-logs-predicates.js`
> [CINFRA-342] Bug fix/update leader property when replacing leader

- arangod/Replication2/ReplicatedLog/Supervision.cpp
- arangod/Replication2/ReplicatedLog/SupervisionAction.h
- js/client/modules/@arangodb/testsuites/replication2.js
- tests/js/server/replication2/replication2-supervision-replicated-log-target-cluster.js
This PR reorganises the ReplicatedLog Supervision to execute the adding/removal of participants as follows:
* If there are participants to be added, add them
* If there are participants that are *not currently the leader* to remove, phase them out and remove them
* If the participant that is currently the leader has been removed from Target, it will remain as the last participant; leadership is transfered to a different eligible participant.   
> [CINFRA-344] Remove Multiple Participants

- arangod/Replication2/Methods.cpp
- arangod/Replication2/Methods.h
- arangod/Replication2/ReplicatedLog/AgencyLogSpecification.h
- arangod/Replication2/ReplicatedLog/Supervision.cpp
- arangod/Replication2/ReplicatedLog/SupervisionAction.cpp
- arangod/RestHandler/RestLogHandler.cpp
- arangod/V8Server/v8-replicated-logs.cpp
- js/client/modules/@arangodb/arango-database.js
- tests/js/common/shell/shell-replicated-logs-cluster.js
- tests/js/server/replication2/replication2-replicated-log-create-api-cluster.js
Better log creation api. The old api expected a log id to be specified. The new api selects it randomly but uniquely. You can also specify if you want to wait for the log to be finished. (which is now default)
> [CINFRA-345] proper replicated log creation

- lib/Zip/crypt.h
- lib/Zip/unzip.cpp
- lib/Zip/zip.cpp
fix global buffer overflow in minizip after zlib upgrade
minizip is a contribution to zlib, and needs to be updated in sync with a zlib library update. 
This PR updates our version of minizip so that the overflow is fixed.
We only upgraded zlib in devel recently (for good reasons), so this bugfix does not need to be backported.
The overflow was detected by ASan builds and according to a local ASan run, is now fixed.
> fix global buffer overflow in minizip after zlib upgrade

- arangod/Replication2/ReplicatedLog/ParticipantsHealth.h
- arangod/Replication2/ReplicatedLog/Supervision.cpp
> [CINFRA-348] Use `getRebootId` instead of directly accessing _health

- CHANGELOG
- js/common/modules/@arangodb/aql/explainer.js
* Only show slowest optimizer rules in explain output for optimizer rules
that took a considerable amount of time (>= 0.0002 seconds). Previously
the slowest 5 optimizer rules were shown, regardless of how long they
took to execute and even if they executed sufficiently fast.
This is only a simplification for the explain output and does not need to be backported.
> Slightly simplify explain output

- tests/Maintenance/MaintenanceFeatureTest.cpp
Emergency PR to disable a test which was found to sometimes block.
> Emergency unblock test

- tests/Maintenance/MaintenanceFeatureTest.cpp
This fixes a test which could block by setting a description attribute
which was left out. Reactivates test.
- [*] Tests
> Fix blocking test

- arangod/Replication2/ReplicatedLog/Algorithms.cpp
- arangod/Replication2/ReplicatedLog/LogLeader.cpp
- arangod/Replication2/ReplicatedLog/LogLeader.h
- tests/Replication2/ReplicatedLog/EstablishLeadershipTest.cpp
- tests/Replication2/ReplicatedLog/UpdateParticipantsFlags.cpp
Minor changes: shuffle some logic around. In essence, change the signature of `updateParticipantsConfig` from
```cpp
auto updateParticipantsConfig(
std::shared_ptr<ParticipantsConfig const> config,
std::size_t previousGeneration,
std::unordered_map<ParticipantId, std::shared_ptr<AbstractFollower>> additionalFollowers,
std::vector<ParticipantId> const& followersToRemove
) -> LogIndex;
```
to
```cpp
auto updateParticipantsConfig(
std::shared_ptr<ParticipantsConfig const> const& config,
std::function<std::shared_ptr<AbstractFollower>(ParticipantId const&)> const& buildFollower
) -> LogIndex;
```
.
> [CINFRA-213] Move some logic in a more fitting place

- tests/js/common/aql/aql-view-arangosearch-feature.js
(sorry, branch name should have been `bug-fix-3.9/fix-test-with-random-execution-time` :facepalm:)
Fix tests that had unpredictable execution times that depended on the state of
the `_key` generator.
The fix will be made in devel via https://github.com/arangodb/arangodb/pull/16055.
This is a test-only bugfix.
> fix a test that had random execution times

- arangod/RocksDBEngine/RocksDBPersistedLog.cpp
This is to avoid the persistor thread executing arbitrary code, which can lead to erratic slowdown of the persistor thread and deadlocks.
> [CINFRA-337] Let RocksDB Log Persistor resolve promises with its executor

- lib/Inspection/VPackLoadInspector.h
Attempt to fix the following compile warning on MSVC:
```
lib/Inspection/VPackLoadInspector.h(98,1): error C2220: the following warning is treated as an error
lib/Inspection/VPackLoadInspector.h(92): message : while compiling class template member function 'arangodb::inspection::Status arangodb::inspection::VPackLoadInspectorImpl<true>::value(arangodb::velocypack::HashedStringRef &)'
lib/Inspection/Access.h(55): message : see reference to function template instantiation 'arangodb::inspection::Status arangodb::inspection::VPackLoadInspectorImpl<true>::value(arangodb::velocypack::HashedStringRef &)' being compiled
tests/Basics/InspectionTest.cpp(1547): message : see reference to class template instantiation 'arangodb::inspection::VPackLoadInspectorImpl<true>' being compiled …
```
> attempt to fix compile warning on MSVC

- scripts/cluster-run-common.sh
For most experiments related to replication, 2 DB servers is not enough. Using 3 servers by default does not really affect the startup speed, while making the `startLocalCluster.sh` more universal, being better suited for observing a cluster that contains a stopped server.
This is just for convenience, as most of the time when you tell someone to start a local cluster, they would use the default parameters. By changing the number of DB servers to 3, we make sure there's not going to be any issue with that.
> [CINFRA-361] Use 3 DB Servers by Default

- CHANGELOG
- arangod/RocksDBEngine/RocksDBEngine.cpp
- arangod/RocksDBEngine/RocksDBOptionFeature.cpp
- arangod/RocksDBEngine/RocksDBOptionFeature.h
* Added startup option `--rocksdb.transaction-lock-stripes` to configure the number of lock stripes to be used by RocksDB transactions. The option defaults to the number of available cores, but is bumped to a value of 16 if the number of cores is lower.
Docs PR: https://github.com/arangodb/docs/pull/978
> Make transaction lock stripes configurable

- CHANGELOG
- arangod/Cluster/MaintenanceFeature.h
- arangod/Cluster/SynchronizeShard.cpp
- tests/Maintenance/MaintenanceFeatureTest.cpp
A situation can arise in which a planned shard leader cannot assume
its leadership since one of its `SynchronizeShard` jobs is in the
Maintenance work queue and is locking the shard. If this happens
multiple times in the same cluster, everything can get stuck.
- [*] Tests
- [*] Backports: This is the backport for 3.8. Original PR: https://github.com/arangodb/arangodb/pull/16019
- [*] GitHub issue / Jira ticket: https://arangodb.atlassian.net/browse/BTS-662
This supersedes https://github.com/arangodb/arangodb/pull/15241, which is somehow failed for technical reasons.
> Deadlocked SynchronizeShards BTS-662

- CHANGELOG
- arangod/Aql/grammar.cpp
- arangod/Aql/grammar.h
- arangod/Aql/grammar.hpp
- arangod/Aql/grammar.y
- tests/js/server/aql/aql-optimizer-collect-methods.js
- tests/js/server/aql/aql-optimizer-keep.js
Backport of https://github.com/arangodb/arangodb/pull/16126
* Improve validation for variables used in the `KEEP` part of AQL COLLECT
operations. Previously referring to a variable that was introduced by the
COLLECT itself from out of the KEEP part triggered an internal error. The
case is detected properly now and handled with a descriptive error message.
> Improve validation of COLLECT KEEP variables

- .github/workflows/clang-format.yml
- arangod/Aql/SortExecutor.cpp
The clang-format check executed via Github actions suddenly started failing last week, without having made any changes to the Github action or the invoked Docker container. So Github seems to have changed something in their Github actions environment.
This PR repairs the Github action so that it doesn't fail with git errors anymore.
Relies on code in another repository: https://github.com/arangodb/clang-format-action/releases/tag/1.0.3
> Fix clang-format check

- CMakeLists.txt
- arangod/Aql/Query.cpp
- arangod/Aql/Query.h
- arangod/Aql/QueryList.cpp
- arangod/Aql/QueryList.h
- arangod/RocksDBEngine/RocksDBMetadata.h
- tests/Network/MethodsTest.cpp
Try to fix some of data races that tsan reported
https://jenkins.arangodb.biz:3456/job/arangodb-ANY-linux-san.x86-64/1078/EDITION=enterprise,SAN_MODE=TSan,STORAGE_ENGINE=rocksdb,TEST_SUITE=single,limit=linux&&test&&x86-64/
Everything except unsafe calls, velocypack function initilization, and agency lock-order-inversion 
TSAN build: https://jenkins.arangodb.biz:3456/job/arangodb-ANY-linux-san.x86-64/1082/
> Try to fix some of data races that tsan reported

- .github/workflows/clang-format.yml
- arangod/Aql/SortExecutor.cpp
Backport of https://github.com/arangodb/arangodb/pull/16139
The clang-format check executed via Github actions suddenly started failing last week, without having made any changes to the Github action or the invoked Docker container. So Github seems to have changed something in their Github actions environment.
This PR repairs the Github action so that it doesn't fail with git errors anymore.
Relies on code in another repository: https://github.com/arangodb/clang-format-action/releases/tag/1.0.3
> fix clang-format Github action

- js/client/modules/@arangodb/testutils/testrunner.js
https://github.com/arangodb/arangodb/pull/15998 introduced a main overhaul of the test framework, and added users testing. However, the function signature and SUT failure resillience of the newly introduced users module wasn't good. 
A testrun would abort like this, and not give propper error output to testfailures.txt:
```
caught exception during test execution!
not connected
ArangoError: not connected
at Object.exports.all (c:\gce-win-22dbmn\oskar\work\ArangoDB\js\client\modules\@arangodb\users.js:148:38)
at Object.setUp (c:\gce-win-22dbmn\oskar\work\ArangoDB\js\client\modules\@arangodb\testutils\testrunner.js:49:35)
at runOnArangodRunner.run (c:\gce-win-22dbmn\oskar\work\ArangoDB\js\client\modules\@arangodb\testutils\testrunner.js:463:63)
at Object.replication2Server [as …
```
> fix users checking

- CHANGELOG
- client-tools/Export/ExportFeature.cpp
- client-tools/Export/ExportFeature.h
- js/client/modules/@arangodb/testsuites/export.js
* Added option `--custom-query-file` to arangoexport, so that a custom query
string can also be read from an input file.
> Added `--custom-query-file` option to arangoexport

- js/client/modules/@arangodb/testsuites/importing.js
- js/client/modules/@arangodb/testutils/process-utils.js
- make imporiting binary config and handling similar to dumping.
- move client tool invocation function up
-  fix exception handling in the importing testsuites so it actually produces errors in the result.
> Adjust importing test structure to be more similar to dumping

- js/client/modules/@arangodb/testsuites/ldap.js
- js/client/modules/@arangodb/testutils/ldap-generic-failover.js
- js/client/modules/@arangodb/testutils/testrunner.js
- js/common/modules/jsunity/jsunity.js
in https://github.com/arangodb/arangodb/pull/15998 we adjusted the structure of the tests, however, ldap tests weren't run in the PR hence this issue went unnoticed.
- fix member reference names
- disable user checking of test infrastructure, we don't do that in other auth tests as well.
> fix reference of server JWT

- CHANGELOG
- arangod/Cluster/Maintenance.cpp
Partial Backport of: https://github.com/arangodb/arangodb/pull/16166
In the Maintenance there is a lock-shard mechanism that ensures only one Job should run at a time.
However it does not react correctly, if within the same Maintenance loop two different actions for the same shard are found. (e.g. update a property and change shard leader). IN that case two jobs would be queued and the lock was off-by-one.
In production this race is highly unlikely, all operations triggering it are seldom, furthermore if the bug occurs the behavior of maintenance is sub-optimal, but nothing critical is performed.
> Bug fix/3.9 maintanence lock shard

- CHANGELOG
- arangod/RocksDBEngine/RocksDBRecoveryManager.cpp
Minimal backport of https://github.com/arangodb/arangodb/pull/16185
Improve log output for WAL recovery, by providing more information and by making the meaning more clear.
> improve log output for WAL recovery

- arangod/RocksDBEngine/RocksDBChecksumEnv.cpp
- arangod/RocksDBEngine/RocksDBChecksumEnv.h
We need to suppress warnings when deletion of such fails, because RocksDB can call its DeleteFile method even for files it does not create...
Only affects devel.
> dont show errors when trying to delete non-existing files

- CHANGELOG
- arangod/ClusterEngine/ClusterIndex.cpp
- arangod/RocksDBEngine/RocksDBTtlIndex.cpp
- arangod/RocksDBEngine/RocksDBVPackIndex.h
- tests/js/common/shell/shell-index-estimates.js
- tests/js/common/shell/shell-ttl.js
- tests/js/server/recovery/indexes-ttl.js
Backport of https://github.com/arangodb/arangodb/pull/16165
* Make sure that newly created TTL indexes do not use index estimates, which
wouldn't be used for TTL indexes anyway.
> Disable index estimates for TTL indexes

- CHANGELOG
- arangod/Agency/Inception.cpp
Fix agency startup when one of the gossip peers returns a non-Ok response.
In that case, the response may not contain a JSON object with the expected attributes in it.
The previous code assumed the attributes would be present, and triggered an exception if not. That exception lead to the agent process terminating itself.
Now unexpected responses are handled gracefully.
> fix agency startup when gossip peers return HTTP 503

- UnitTests/OskarTestSuitesBlockList
- js/client/modules/@arangodb/testsuites/replication.js
- tests/js/common/replication_api/shell-api-replication-global.js
- tests/js/common/replication_api/shell-api-replication.js
in https://github.com/arangodb/arangodb/pull/16084 we missed adding the converted http_replication testsuite from the devel PR. This commit brings it back, and flushes the testsuites from the blackists.
> add testsuite missing in backport

- tests/js/server/replication2/replication2-maintenance-replicated-state-cluster.js
- tests/js/server/replication2/replication2-replicated-state-http-api-cluster.js
- tests/js/server/replication2/replication2-supervision-replicated-state-target-cluster.js
Supervision and maintenance tests are executed with the prototype state machine, apart from the black-hole. The following tests are affected by the change:
- replication2-supervision-replicated-state-target-cluster.js
- replication2-maintenance-replicated-state-cluster.js
The `replication2-replicated-state-http-api-cluster.js` file has just been refactored for convenient switching between the two.
`replication2-supervision-replicated-state-cluster.js` was already written this way, thus it remains untouched.
> [CINFRA-329] Run supervision and maintenance tests using prototype

- arangod/Replication2/Methods.h
- arangod/Replication2/ReplicatedLog/LogFollower.cpp
- arangod/Replication2/ReplicatedLog/LogFollower.h
- arangod/Replication2/ReplicatedLog/LogLeader.cpp
- arangod/Replication2/ReplicatedLog/LogLeader.h
- arangod/Replication2/ReplicatedLog/LogUnconfiguredParticipant.cpp
- arangod/Replication2/ReplicatedLog/LogUnconfiguredParticipant.h
- arangod/Replication2/ReplicatedLog/WaitForBag.cpp
- arangod/Replication2/ReplicatedLog/WaitForBag.h
- tests/CMakeLists.txt
- tests/Replication2/ReplicatedLog/ParticipantResignTest.cpp
Calling `waitForResign()` when a participant was resigned already did not properly resolve the promise.
> [CINFRA-322] wait for resign race

- CMakeLists.txt
- lib/Basics/UnshackledMutex.cpp
- lib/Basics/UnshackledMutex.h
One futex instead of two
Props:
* Simpler
* Have a kind of fast path (fast lock with cond, unlock without waiters). 
So it better when there is no contention on mutex
* `noexcept`
Cons:
* Every unlock is possible notify. So we make unnecessary condition check in `absl::Mutex::unlock` in `UnshackledMutex::lock`
About notification counts.
I think it is smaller with absl, because:
* with std we have always have `notify_one`, and two `std::mutex::unlock`
* with absl only two `absl::Mutex::unlock`
> Improve UnshackledMutex via absl::Mutex

- CMakeLists.txt
There is a CMake option `USE_STRICT_OPENSSL_VERSION`, but it was not properly honored in all places.
This could break compilation with other versions of libssl when USE_STRICT_OPENSSL_VERSION was set to `Off`.
> allow compilation with libssl3 when using USE_STRICT_OPENSSL_VERSION=Off

- lib/Inspection/VPackLoadInspector.h
- lib/Inspection/VPackSaveInspector.h
- tests/Basics/InspectionTest.cpp
Support empty objects in VelocyPack inspection.
> Velocypack Inspection for Empty Objects

- tests/js/server/recovery/view-arangosearch-link-recover-view-not-again-noncluster.js
Attempt to fix a sometimes-unstable test that runs into this assertion:
```
* Test "recovery_2"
[FAILED]  tests/js/server/recovery/view-arangosearch-link-recover-view-not-again-noncluster.js
"testIResearchRecoverWithTickInPast" failed: Error: at assertion #3: { "storedTick1" : "2037", "storedTick2" : "2043", "storedTick3" : "2105", "recoverTick" : "2041" }: (false) does not evaluate to true
(Error
at assertTrue (/work/ArangoDB/js/common/modules/jsunity/jsunity.js:71:19)
at Object.testIResearchRecoverWithTickInPast (tests/js/server/recovery/view-arangosearch-link-recover-view-not-again-noncluster.js:85:7)
```
This change only affects the test code. The change has been made in devel already. 3.8 and 3.7 do not have the test in question.
> try to fix test

- tests/js/client/load-balancing/load-balancing-key-generator-noauth-cluster.js
Added load-balancing tests for generating keys with the padded key generator.
We expect the keys to be sequential if the underlying collection only has a single shard. 
This PR only adds the tests for that.
Previous versions of ArangoDB cannot guarantee the sequentiality of keys.
> added tests for padded key generator keys

- CMakeLists.txt
Backport of https://github.com/arangodb/arangodb/pull/16231.
There is a CMake option USE_STRICT_OPENSSL_VERSION, but it was not properly honored in all places.
This could break compilation with other versions of libssl when USE_STRICT_OPENSSL_VERSION was set to Off.
> allow building 3.9 with non-matching libssl version

- CHANGELOG
- arangod/Agency/State.cpp
*Do not fatal error on missing local timestamp in persisted log entries in agent*
> [3.7] no fatal error missing local timestamp agency state

- CHANGELOG
- arangod/Agency/State.cpp
*Do not fatal error on missing local timestamp in persisted log entries in agent*
> [3.8] no fatal error missing local timestamp agency state

- CHANGELOG
- arangod/VocBase/vocbase.cpp
Backport of https://github.com/arangodb/arangodb/pull/16273
* Fixed a potential hang on shutdown, when there were still document operations
queued.
The same bugfix has been made in devel in December, and does not seem to have caused any issues since then.
> Fix shutdown hang

- CHANGELOG
- arangod/Aql/OptimizerRules.cpp
- tests/js/server/aql/aql-optimizer-rule-interchange-adjacent-enumerations-cluster.js
- tests/js/server/aql/aql-optimizer-rule-interchange-adjacent-enumerations-noncluster.js
Backport of https://github.com/arangodb/arangodb/pull/16283
Fixed Github issue #16279: assertion failure/crash in AQL query optimizer when permuting adjacent FOR loops that depended on each other.
> fixed issue #16279

- lib/Basics/datetime.cpp
> Fix ambiguity between date::format and std::format with MSVC 16.11.14

- Documentation/DocuBlocks/Rest/Pregel/get_api_control_pregel_overview.md
- Documentation/DocuBlocks/Rest/Pregel/get_api_control_pregel_status.md
Backport of https://github.com/arangodb/arangodb/pull/16277
Docs PR: https://github.com/arangodb/docs/pull/992
Add documentation for Pregel API that lists currently ongoing jobs.
> add documentation for Pregel jobs API

- js/server/modules/@arangodb/arango-collection.js
The JS server-side module of a collection does now deliver the shard list in ascending order.
> JS Server Module: arango-collection - shard sort order now in ascending order

- arangod/Agency/Inception.cpp
Previously, when the inception received an HTTP 503 error, it could fail
with a VelocyPack error when trying to unserialize data in the response
body that was not there. This issue was fixed about a week ago. Now an
agent will handle 503 responses correctly, but it will go to a 10
seconds sleep. This is too long, because it delays the cluster start
unnecessarily. Reduce the sleep duration to 500ms when getting an HTTP
503.
The original bugfix with the 10 seconds sleep time was not released yet.
So no extra CHANGELOG entry is added for reducing the sleep duration.
> decrease wait time in agency inception in case of HTTP 503

- CHANGELOG
This PR adds the new metrics for the IO heartbeat to the CHANGELOG
- [*] Backport for 3.9: https://github.com/arangodb/arangodb/pull/16294
- [*] Backport for 3.8: This is 3.8.
> Improve CHANGELOG for IO heartbeat

- CHANGELOG
- arangod/Utils/SingleCollectionTransaction.cpp
- js/client/modules/@arangodb/testutils/testrunner.js
- js/common/modules/jsunity.js
- js/common/modules/jsunity/jsunity.js
- tests/js/client/shell/api/view-instead-of-collection.js
Fix behavior when accessing document APIs with view names.
Now a proper error is returned on such attempts.
This PR also fixes some issues in testing.js when it returned negative numbers for setup/teardown or test durations, and also failed on cleaning up leftover collections/databases from tests if it wasn't already in the `_system` database.
Also fixes line endings (\n instead of \r\n) in some JavaScript file.
> Fix behavior when accessing document APIs with view names

- CHANGELOG
- arangod/IResearch/IResearchFilterFactory.cpp
- tests/IResearch/IResearchFilterFunction-test.cpp
Fix boost propagation in STARTS_WITH function. 
Fix in newer version was merged as part of #14744
> [3.8] Fix for ES-1147

- js/server/modules/@arangodb/testutils/replicated-logs-helper.js
- js/server/modules/@arangodb/testutils/replicated-logs-predicates.js
- tests/js/server/replication2/replication2-supervision-replicated-log-target-cluster.js
This rescues over a test from #16226 which becomes out-of-date by the supervision refactor.
> [CINFRA-xxx] Test failed dictated leader

- arangod/RocksDBEngine/Methods/RocksDBTrxMethods.cpp
- tests/js/client/shell/shell-transaction-intermediate-commit-cluster.js
`testSingleTransactionIntermediateCommitsOnFollowerWithRollback` failed recently with error
```
* Test "shell_client_3"
[FAILED]  tests\js\client\shell\shell-transaction-intermediate-commit-cluster.js
"testSingleTransactionIntermediateCommitsOnFollowerWithRollback" failed: Error: at assertion #3: assertEqual: (20) is not equal to (19)
```
This PR adds debug output to hopefully fix the issue with the additional information.
> Add debug information.

- tests/Replication2/Helper/ModelChecker/AgencyState.h
- tests/Replication2/ModelChecker/Predicates.h
- tests/Replication2/ReplicatedState/SupervisionModelChecker.cpp
Model Checker tests for replicated state have previously been disabled. Now we can enable them again. Small bug-fixes were necessary.
> [CINFRA-342] Enable MC tests for replicated state

- CHANGELOG
- arangod/RocksDBEngine/RocksDBEngine.cpp
- arangod/RocksDBEngine/RocksDBOptionFeature.cpp
- arangod/RocksDBEngine/RocksDBOptionFeature.h
Add support for LZ4 and LZ4HC compression in RocksDB. The default is still to use Snappy compression.
This PR allows us to make tests with LZ4 and LZ4HC, so we can decide if we want to move away from Snappy or not.
> add support for LZ4 and LZ4HC compression in RocksDB

- arangod/Replication2/StateMachines/Prototype/PrototypeCore.h
The ongoing state of the prototype leader works like a deque: newer states, containing operations that were only applied locally, are always appended at the back. When state machine operations (log entries) have been replicated and committed, we look at the last log iterator to be applied and pop from the front of the deque until we reach that index.
The problem is that sometimes we could get entries that were not inserted by a user (meta entries), which means the prototype leader doesn’t know about the existence of these entries. These entries still add up to the log index, which could cause our leader to pop from the deque when it’s not supposed to do so.
Consider the following entries: 101 (operation), 102 (meta), 103 (operation). The deque will contain the states at 101, followed by …
> [CINFRA-385] Incorrect ongoing state in prototype

- arangod/Replication2/ReplicatedLog/LogFollower.cpp
- arangod/Replication2/ReplicatedLog/LogLeader.cpp
- tests/Replication2/ReplicatedLog/MultiTermTest.cpp
LogLeader and LogFollower classes did not check if they already resigned before they called release on a (then nullptr) LogCore.
> [CINFRA-386] Check Resigned before release

- 3rdParty/CMakeLists.txt
Don't install RocksDB include files when building RocksDB as part of ArangoDB.
> don't install RocksDB headers

- arangod/Cluster/Maintenance.cpp
The maintenance writes to State/Current even if the replicated state is already deleted from State/Plan. This PR adds a precondition on `State/Plan/<database>/<state-id>/id` to be equal to `<state-id>`. This precondition fails if and only if the entry in Plan is gone. Sadly the maintenance code enforces a certain format on the preconditions and it is not possible to formulate a less cryptic precondition.
> [CINFRA-407] Prevent write to current if State/Plan is deleted

- arangod/CMakeLists.txt
- arangod/Cluster/ClusterInfo.cpp
- arangod/Replication2/Methods.h
- arangod/Replication2/StateMachines/Document/DocumentStateMachine.cpp
- arangod/Replication2/StateMachines/Document/DocumentStateMachine.h
- arangod/Replication2/StateMachines/Document/DocumentStateMachineFeature.cpp
- arangod/Replication2/StateMachines/Document/DocumentStateMachineFeature.h
- arangod/RestServer/arangod.cpp
- arangod/RestServer/arangod.h
This is just a skeleton for the document state. We replaced the `black-hole` with `document` state machine inside the create collection method.
> [CINFRA-408] Document State Implementation

- CHANGELOG
- arangod/RocksDBEngine/RocksDBMetadata.cpp
- arangod/RocksDBEngine/RocksDBMetadata.h
- arangod/RocksDBEngine/RocksDBReplicationContext.cpp
- arangod/RocksDBEngine/RocksDBReplicationContext.h
Fixed BTS-875: https://arangodb.atlassian.net/browse/BTS-875
When multiple followers are trying to get in sync with the leader at the same time, and more than one follower tries to update the collection count value on the leader, this could result in a race, so that more than one follower applies the collection count update on the leader. This will again lead to the count on the leader being wrong.
This PR fixes the issue by using a ticket id for all callers that want to update the counts, and having only one caller succeed for the same ticket id.
> fixed BTS-875

- arangod/RocksDBEngine/RocksDBCollection.cpp
- arangod/Transaction/Methods.cpp
- arangod/Utils/OperationOptions.h
- arangod/VocBase/LogicalCollection.cpp
- arangod/VocBase/LogicalCollection.h
Backport of https://github.com/arangodb/arangodb/pull/16350
Fetch collection's schema only once per batch operation, not once per document.
Because the schema is an atomic shared_ptr, fetching it only once per batch can reduce contention when dealing with large concurrent batch operations.
> fetch schema only once per batch operation

- tests/sepp/Execution.cpp
- tests/sepp/Options.h
- tests/sepp/Runner.cpp
- tests/sepp/Server.cpp
Fix race when calculating the size of the db directory.
Also make clearing the db folder before startup optional.
> SEPP: fix db size calculation

- tests/js/client/shell/shell-collection-counts-cluster.js
Some tests relied on shard data in the agency plan, but it was not guaranteed that shards were already present on followers after changing the replicationFactor. This led to spuriously failing test runs.
This is a test-only bugfix.
> Fix unstable test

- arangod/RocksDBEngine/RocksDBOptionFeature.cpp
We deliberately limit `_maxSubcompactions` by the number of threads for low priority operations ( `--rocksdb.num-threads-priority-low`). This number of threads is initialized to zero and if it is not specified, it is dynamically calculated.
However, the code to limit `_maxSubcompactions` to `_numThreadsLow` was executed _before_ that calculation was done, so unless the user explicitly set  `--rocksdb.num-threads-priority-low`, `_maxSubcompactions` was always set to zero.
> Fix initialization of _maxSubcompactions.

- CHANGELOG
- arangod/Aql/ClusterNodes.cpp
Allow parallel access to the shards of smart edge collections in AQL via parallel GatherNodes.
> allow parallel access to the shards of smart edge collections in AQL

- arangod/Cluster/ClusterInfo.cpp
- arangod/Cluster/ClusterInfo.h
- arangod/Replication2/ReplicatedState/AgencySpecification.cpp
- arangod/Replication2/ReplicatedState/AgencySpecification.h
- arangod/Replication2/ReplicatedState/ReplicatedState.h
- arangod/Replication2/ReplicatedState/ReplicatedState.tpp
- arangod/Replication2/ReplicatedState/UpdateReplicatedState.cpp
- arangod/Replication2/StateMachines/BlackHole/BlackHoleStateMachine.h
- arangod/Replication2/StateMachines/Document/DocumentStateMachine.cpp
- arangod/Replication2/StateMachines/Document/DocumentStateMachine.h
- arangod/Replication2/StateMachines/Document/DocumentStateMachineFeature.cpp
- arangod/Replication2/StateMachines/Prototype/PrototypeStateMachine.h
- lib/Inspection/VPackLoadInspector.h
- lib/Inspection/VPackSaveInspector.h
- lib/Inspection/detail/traits.h
- tests/CMakeLists.txt
- tests/Replication2/ReplicatedState/DocumentStateMachineTest.cpp
- tests/Replication2/ReplicatedState/FollowerSnapshotTest.cpp
- tests/Replication2/ReplicatedState/LeaderRecoveryTest.cpp
- tests/Replication2/ReplicatedState/PrototypeConcurrencyTest.cpp
- tests/Replication2/ReplicatedState/PrototypeStateMachineTest.cpp
- tests/Replication2/ReplicatedState/ReplicatedStateTest.cpp
- tests/Replication2/ReplicatedState/StateMachines/MyStateMachine.h
This PR adds a new `parameters` field to the `properties/implementation` object, used by replicated states in `Target` and `Plan`. This field is supposed to hold generic velocypack data, which is then serialized and de-serialized accordingly by the replicated state. The presence of this field is optional, hence only the `DocumentState` is using it so far to store the ID of a collection. If not `nullopt`, it is passed to the core during its creation.
The corresponding `CoreParameterType` of the `DocumentState` is `DocumentCoreParameters`. All other replicated states have `CoreParemeterType=void`.
A basic unit tests has been added for `DocumentState`, just to make sure there are no errors. The document-store JS tests also cover these changes.
On the side, we have added serialization and …
> [CNFRA-414] Add CoreParameterType to Replicated States

- arangod/Replication2/ReplicatedState/ReplicatedState.tpp
- lib/Inspection/VPackLoadInspector.h
- tests/Replication2/ReplicatedState/FollowerWaitForTest.cpp
We had various issues caused by the `CoreParameterType`, introduced for replicated states. When compiled with `gcc-10` on Linux, DB servers used to crash with `SIGSEGV`. I can't really explain why, just that it had to do with the velocypack deserialization. This PR fixes that, along with a change requires for `MSVC`.
Jenkins: https://jenkins.arangodb.biz:3456/view/PR/job/arangodb-matrix-pr/21899/
> [CINFRA-415] Core Parameter Type

- js/server/modules/@arangodb/testutils/collection-modification-aql-generic-tests.js
This is a backport to https://github.com/arangodb/arangodb/pull/16383, which removes a deletion that was requested to be removed after BTS-750 was merged.
> Bug fix 3.9/remove deletion after bts 750

- CMakeLists.txt
- tests/sepp/Execution.cpp
- tests/sepp/Execution.h
- tests/sepp/ExecutionThread.cpp
- tests/sepp/ExecutionThread.h
- tests/sepp/Options.h
- tests/sepp/Runner.cpp
- tests/sepp/Workloads/GetByPrimaryKey.cpp
- tests/sepp/Workloads/GetByPrimaryKey.h
- tests/sepp/Workloads/InsertDocuments.cpp
- tests/sepp/Workloads/IterateDocuments.cpp
Performance-test only...
Adds a new workload to fetch data by primary key, either document keys only, or the full documents in addition.
Key values are supposed to be contiguous numeric values, optionally starting with a prefix.
Example config:
```
{
"rocksdb": {},
"workload": {
"getByPrimaryKey": {
"default": {
"collection": "peter",
"fillBlockCache": true,
"fetchFullDocument": false,
"keyPrefix": "testmann",
"minNumericKeyValue" : 0,
"maxNumericKeyValue" : 100000
},
"stopAfter": {
"runtime": 10000
},
"threads": 1
}
}
}
```
> add getByPrimaryKey workload

- CHANGELOG
- arangod/RocksDBEngine/RocksDBOptionFeature.cpp
- tests/sepp/RocksDBOptions.cpp
Change default `format_version` for RocksDB .sst files from 3 to 5.
We haven't measured consistent performance improvements with version 5 (over versions 3 or 4), but we also haven't seen no negative effects in testing.
The RocksDB comments about format version 5 are:
> Can be read by RocksDB's versions since 6.6.0. Full and partitioned
> filters use a generally faster and more accurate Bloom filter
> implementation, with a different schema.
> Change default `format_version` for RocksDB .sst files from 3 to 5.

- arangod/Cluster/ClusterMethods.cpp
Potential fix for BTS-885: https://arangodb.atlassian.net/browse/BTS-885
Fix response handling for cluster-internal messages in case a non-HTTP 200 error was returned for a count/revision/figures/truncate request. Some of these operations handled errors properly, and some didn't. the error processing for the ops is now unified so that errors are properly reported.
This could be a solution to https://arangodb.atlassian.net/browse/BTS-885
> fix response handling for cluster-internal messages

- arangod/Pregel/Graph.h
- arangod/Pregel/GraphStore.cpp
This PR is the first one in a series of "repair" PRs gradually moving to cleaner code in the Pregel subsystem.
The goal of this PR is to simplify storage and handling of the `Vertex` and `Edge` structs as well as the code responsible for loading graphs.
> [PREGEL] Replace Vertex Key store by std::string

- arangod/Replication2/ReplicatedState/Supervision.cpp
- arangod/Replication2/ReplicatedState/SupervisionAction.h
- tests/Replication2/Helper/AgencyLogBuilder.h
- tests/Replication2/ReplicatedState/SupervisionTest.cpp
- tests/js/server/replication2/replication2-supervision-replicated-state-target-cluster.js
This PR forwards a configuration change from a replicated state to the replicated log.
> [CINFRA-383] Forward Config to Log

- arangod/Replication2/Methods.cpp
- arangod/Replication2/Methods.h
- arangod/Replication2/StateMachines/Prototype/PrototypeStateMethods.cpp
- arangod/Replication2/StateMachines/Prototype/PrototypeStateMethods.h
- tests/js/server/replication2/replication2-replicated-log-create-api-cluster.js
(Re-)add the `numberOfServers` parameter when creating a replicated log or a prototype replicated state. These have been removed in the past due to some refactoring of the LogConfig.
> [CINFRA-390] Added number of servers parameter

- arangod/Pregel/GraphStore.cpp
- arangod/Pregel/GraphStore.h
- arangod/Pregel/Worker.cpp
Extracts shard retrieval logic from inside loadEdges function to a separate object - the ShardResolver interface. This ShardResolver has a cluster and a single server version. The concrete type is given to GraphStore on creation, therefore the cluster check does not need to be done every time a edge is loaded.
Compiles and pregel runs through with the cit-Patents data set with no relevant timing changes and the same number of gss.
> [PREGEL] Extract shard retrieval

- 3rdParty/rocksdb/6.27/db/db_impl/db_impl.cc
- CHANGELOG
Backport of https://github.com/arangodb/arangodb/pull/16422
* Fixed potential resource leak when reusing `rocksdb::PinnableSlice` instances
without resetting them first. This issue can lead to the block cache filling
up with data that will not be evicted from the block cache anymore.
Fixed in upstream RocksDB via https://github.com/facebook/rocksdb/pull/10166
> Fix potential resource leak when reusing PinnableSlice instances

- CHANGELOG
- lib/Rest/GeneralResponse.cpp
- tests/js/server/recovery/crash-handler-abort-noasan.js
- tests/js/server/recovery/crash-handler-assert-noasan.js
- tests/js/server/recovery/crash-handler-segfault-noasan.js
- tests/js/server/recovery/crash-handler-terminate-active-noasan.js
- tests/js/server/recovery/crash-handler-terminate-noasan.js
Fixes two issues:
1. Broken crash handler tests
These tests were broken since the general test verbosity was reduced in devel a few months ago. these tests check for specific log messages, which were not emitted after the log verbosity was reduced. Now the tests specifically enable the log topic in question, so that all required log messages for the tests are emitted again.
2. Adjust HTTP response code for error number 1521 from 500 to 400
Error 1521 (query collection lock failed) is nowadays only emitted in traversals, when a collection is accessed during the traversal that has not been specified in the WITH statement of the query. Thus returning HTTP 500 is not a good idea, as it is clear a user error that triggered the problem.
No backports are planned for this.
> fix broken tests

- arangod/IResearch/IResearchDataStore.cpp
There was a small glitch between actual taking commitLock and reading the tick from engine.
If other commit could sneak by that will lead to assertion failure in the FlushSubscription.
The behaviour is covered by existing tests. No new tests introduced.
- [] :hammer: Refactoring/simplification
> Fix committed tick adjustments

- UnitTests/OskarTestSuitesBlockList
- tests/test-definitions.txt
- Migrate this branch to use `test-definitions.txt`
- So far we would have the `OskarTestSuitesBlockList` to stop removed testsuites to be executed in PR runs.
Since now the Branch has the `test-definitions.txt` the contents of the Blacklist can simply be removed from the test definition, 
and the blacklist be emptied.
> Feature 3.9/remove blacklist contents

- UnitTests/OskarTestSuitesBlockList
- tests/test-definitions.txt
- Migrate this branch to use `test-definitions.txt`
- So far we would have the `OskarTestSuitesBlockList` to stop removed testsuites to be executed in PR runs.
Since now the Branch has the `test-definitions.txt` the contents of the Blacklist can simply be removed from the test definition, 
and the blacklist be emptied.
> Feature 3.8/remove blacklist contents

- arangod/Replication2/ReplicatedLog/Supervision.cpp
- tests/Replication2/Helper/ModelChecker/Actors.cpp
- tests/Replication2/Helper/ModelChecker/Actors.h
- tests/Replication2/Helper/ModelChecker/AgencyTransition.cpp
- tests/Replication2/Helper/ModelChecker/AgencyTransitions.h
- tests/Replication2/ReplicatedLog/SupervisionSimulationTest.cpp
- tests/Replication2/ReplicatedLog/SupervisionTest.cpp
When the log supervision was trying to force a participant to become
leader and then waited for that configuration to be committed, it did
not put a NoActionPossibleAction into the context which lead to the
forced flag on the selected participant to be reset again.
> [CINFRA] Bugfix Log Supervision Loop

- tests/js/client/load-balancing/load-balancing-key-generator-noauth-cluster.js
This test doesn't use persistent connections yet, resulting in many collections in `TIME_WAIT` state.
> start converting test to use fuerte connection instead of single requsts

- arangod/Replication2/StateMachines/Document/DocumentStateMachineFeature.cpp
There is a problem during the upgrade tests, when the `ClusterFeature` is not enabled, but the `DocumentStateMachineFeature` tries to access it, and thus triggers an exception during startup.
> [CINFRA] Fix Document State Feature Dependencies

- arangod/Cluster/ClusterInfo.cpp
- arangod/Cluster/ClusterInfo.h
- arangod/Cluster/ClusterMethods.cpp
- arangod/Cluster/ClusterMethods.h
- arangod/IResearch/IResearchLinkCoordinator.cpp
- arangod/Metrics/ClusterMetricsFeature.cpp
- arangod/Metrics/ClusterMetricsFeature.h
- arangod/Metrics/CollectMode.h
- arangod/Metrics/MetricsFeature.cpp
- arangod/Metrics/MetricsFeature.h
- arangod/Metrics/Types.h
- arangod/Network/Methods.h
- arangod/RestHandler/RestMetricsHandler.cpp
- arangod/RestHandler/RestMetricsHandler.h
- js/client/modules/@arangodb/test-helper.js
- tests/js/client/shell/api/coordinator-metrics-cluster.js
- tests/js/client/shell/api/coordinator-metrics-noncluster.js
- tests/js/common/aql/aql-view-arangosearch-ddl-cluster.js
This PR adds volatile distributed cache between coordinators for DBservers metrics that are accumulated on Coordinators.
This cache is implemented using `ClusterMetricsFeature` and `Agency`.
1) Agency stores the current leader (master) among all coordinators (its `ServerID` (`std::string`) and `RebootId` (`uint64_t`)), and the current cache version (`uint64_t`))
2) At the start of each coordinator (ClusterMetricsFeature::start) we try to offer ourselves as a leader (master) for this cache.
We try (make a record in the Agency) until we succeed, or we realize that someone else had become the leader.
3) `ClusterMetricsFeature` has an `update(CollectMode::TriggerGlobal)` method that triggers a async local cache update.
3.1) At the beginning we read from `agencyCache()` who is the current …
> Search-184: Distributed volatile cache for accumulated metrics

- CHANGELOG
- arangod/Cluster/ClusterInfo.cpp
- lib/Basics/CrashHandler.cpp
- lib/Basics/Thread.cpp
- lib/Basics/Thread.h
- lib/Logger/Logger.cpp
- lib/Logger/Logger.h
* Fix thread ids and thread names in log output for threads that are not
started directly by ArangoDB code, but indirectly via library code.
Previously, the ids of these threads were always reported as "1", and
the thread name was "main". Now return proper thread ids and names.
> Fix thread ids and names in logs for 3rd party code threads

- lib/Basics/CrashHandler.cpp
Micro optimization: fix duplication acquisition of thread name in case we are going to crash.
> fix duplicate acquisition of thread name

- lib/Ssl/SslInterface.cpp
- lib/Ssl/SslInterface.h
Make an overload of `SslInterface::sslMD5()` easier to use.
This is an internal-only change.
> simplify internal API for sslMD5 overload

- CHANGELOG
- lib/Basics/datetime.h
- lib/Logger/LogTimeFormat.cpp
- lib/Logger/LogTimeFormat.h
- tests/Basics/LoggerTest.cpp
This adds the timeformat for log messages "utc-datestring-micros", which
is useful when hunting concurrency bugs, in particular for RocksDB.
- [*] Tests
- [*] Backports: none
> Add time format utc-datestring-micros

- CHANGELOG
- arangod/Aql/grammar.cpp
- arangod/Aql/grammar.y
- tests/js/server/aql/aql-graph-k-shortest-path-range-syntax-regression.js
before this fix the parser accepted `FOR path IN 1..4 OUTBOUND K_SHORTEST_PATHS` as valid; the range was subsequently ignored, and does not make much sense in this context. This is now a syntax error.
> [AQL] Disallow range in K_SHORTEST_PATHS

- arangod/Replication2/ReplicatedLog/AgencyLogSpecification.h
- arangod/Replication2/ReplicatedLog/AgencySpecificationInspectors.h
- arangod/Replication2/ReplicatedLog/Supervision.cpp
- arangod/Replication2/ReplicatedLog/SupervisionAction.h
- tests/Replication2/Helper/ModelChecker/Actors.cpp
- tests/Replication2/Helper/ModelChecker/Actors.h
- tests/Replication2/Helper/ModelChecker/AgencyTransition.cpp
- tests/Replication2/Helper/ModelChecker/AgencyTransitions.h
- tests/Replication2/Helper/ModelChecker/Predicates.h
- tests/Replication2/ReplicatedLog/SupervisionSimulationTest.cpp
User can change the setting of `waitForSync` for a ReplicatedState/ReplicatedLog.
> [CINFRA-442] Configuration change:  waitForSync

- arangod/Replication2/ReplicatedLog/Supervision.cpp
- tests/Replication2/Helper/AgencyLogBuilder.h
- tests/Replication2/Helper/AgencyStateBuilder.h
- tests/Replication2/ReplicatedLog/SupervisionTest.cpp
The ReplicatedLog Supervision now waits for the leadership of the log to be established. Without this, a log might be declared converged although it is not yet and the first request to the leader might fail.
> [CINFRA-479] Convergence waits for Leadership

- arangod/Aql/AstNode.cpp
- arangod/Aql/grammar.cpp
- arangod/Aql/grammar.y
- tests/js/server/aql/aql-array-access.js
Fix the behavior of AstNode::clearFlags(). This method previously cleared all flags except one. This could have led to some information on the AstNode being lost.
> fix the behavior of AstNode::clearFlags()

- CHANGELOG
- Documentation/Metrics/arangodb_dirty_read_queries_total.yaml
- Documentation/Metrics/arangodb_dirty_read_transactions_total.yaml
- Documentation/Metrics/arangodb_potential_dirty_document_reads_total.yaml
- Documentation/Metrics/arangodb_potentially_dirty_document_reads_total.yaml
- arangod/Aql/ShardLocking.cpp
- arangod/Cluster/ClusterFeature.cpp
- arangod/Cluster/ClusterFeature.h
- arangod/Cluster/ClusterMethods.cpp
- arangod/ClusterEngine/ClusterTransactionState.cpp
- arangod/Statistics/Descriptions.cpp
- arangod/Statistics/ServerStatistics.cpp
- arangod/Statistics/ServerStatistics.h
- arangod/Statistics/StatisticsWorker.cpp
- arangod/Transaction/Options.cpp
- arangod/V8Server/v8-statistics.cpp
- tests/js/server/aql/aql-graph-traversal-generic-cluster.js
This PRs adds some metrics for the read-from-followers feature:
```
arangodb_dirty_read_transactions_total
arangodb_potentially_dirty_document_reads_total
arangodb_dirty_read_queries_total
```
These are only exposed on coordinators, because that is where they only
make sense. Furthermore, a failure point to make dirty reads the default
is added to allow for more testing in the enterprise repo.
- [*] Tests
- [*] Backports: no backports
- [*] Docs PR: https://github.com/arangodb/docs/pull/1048
- [*] Enterprise PR: ???
- [*] GitHub issue / Jira …
> Add metrics and failure point for read-from-followers, APM-296

- arangod/Replication2/ReplicatedLog/ReplicatedLog.cpp
- arangod/Replication2/ReplicatedLog/Supervision.cpp
- lib/Logger/LogTopic.cpp
- tests/Replication2/ReplicatedLog/LogParticipantWaitForResignTests.cpp
- tests/Replication2/ReplicatedLog/ReplicatedLogTest.cpp
Since the maintenance can create multiple actions it can happen that two replicated log actions are scheduled and both try to update a replicated log become the leader. Previously both succeeded, which resulted in the leader to be recreated. The replicated log was modified to only allow new replicated logs to be created with a higher term.
> [CINFRA] BugFix Replicated Log Maintenance Race

- js/client/modules/@arangodb/testutils/process-utils.js
When creating instance.js the crash-utils should get the structure of this object for better visualisation.
This verry case `pu.executeAndWait` would invoke this with a fake structure without this method. Here we add a dummy.
> we have to mimic the instanceInfo structure better in order to work with the crash-utils

- arangod/Pregel/Conductor.cpp
- arangod/Pregel/GraphStore.cpp
- arangod/Pregel/GraphStore.h
- arangod/Pregel/Status/ConductorStatus.h
- arangod/Pregel/Status/Status.h
- arangod/Pregel/Worker.cpp
- tests/CMakeLists.txt
- tests/Pregel/StatusTest.cpp
Measure number of vertices, number of edges and memory used when loading the graph into pregel.
Measurements of workers are aggregated only when required.
> [PREGEL] APM-538 Add reporting for loading state observables

- arangod/RocksDBEngine/ReplicatedRocksDBTransactionCollection.cpp
- arangod/RocksDBEngine/ReplicatedRocksDBTransactionCollection.h
- arangod/RocksDBEngine/ReplicatedRocksDBTransactionState.cpp
- arangod/RocksDBEngine/RocksDBTransactionCollection.h
- arangod/Transaction/Methods.cpp
- arangod/Transaction/Methods.h
- arangod/VocBase/LogicalCollection.cpp
- arangod/VocBase/LogicalCollection.h
- js/common/bootstrap/errors.js
- lib/Basics/errors.dat
At the beginning of each transaction, save the replicated state for each collection / shard only once, and reuse it during the transaction. The same transaction must not use different instances of the same replicated state.
> [CINFRA-475] use same leader state during transaction

- arangod/Replication2/ReplicatedState/FollowerStateManager.tpp
- arangod/Replication2/StateMachines/Prototype/PrototypeFollowerState.cpp
- tests/Replication2/Mocks/FakeReplicatedState.h
- tests/Replication2/ReplicatedState/FollowerSnapshotTest.cpp
This PR fixes two things:
1. The prototype states `applyEntries` is declared as noexcept but wasn't. This is because `getStream` could throw an exception. 
2. This pointed at another problem: the follower state manager did not properly initialise the stream reference on the state after it was constructed **and** the snapshot was already available. Added tests for that.
> [CINFRA-493] Missing Stream if snapshot complete

- js/client/modules/@arangodb/test-helper.js
- js/common/modules/@arangodb/test-helper-common.js
- tests/js/client/shell/shell-replication-responses-cluster.js
- tests/js/server/resilience/failover-failure/resilience-synchronous-repl-failureAt-cluster.js
`resilience-synchronous-repl-failureAt-cluster.js` would be broken by the [instance rework](https://github.com/arangodb/arangodb/pull/16566). this fixes it.
> fix tests; need to load the UUID from the file

- js/client/modules/@arangodb/testutils/instance-manager.js
- js/client/modules/@arangodb/testutils/testrunner.js
aftermath of https://github.com/arangodb/arangodb/pull/16566 : when handling deadlines, make sure the test result turns to crashy.
> make sure a hit deadline produces a bad result

- js/client/modules/@arangodb/testsuites/go.js
Fix invocation of golang tests via `scripts/unittest`. They previously failed because they called a non-existing function. The function was removed by some previous refactoring.
> fix invocation of golang tests

- CHANGELOG
- lib/ApplicationFeatures/ApplicationServer.cpp
- lib/ApplicationFeatures/ConfigFeature.cpp
- lib/Basics/exitcodes.dat
- lib/ProgramOptions/ArgumentParser.h
- lib/ProgramOptions/IniFileParser.cpp
- lib/ProgramOptions/ProgramOptions.cpp
- lib/ProgramOptions/ProgramOptions.h
- tests/ProgramOptions/InifileParserTest.cpp
Docs PR: https://github.com/arangodb/docs/pull/1073
Added more specific process exit codes for arangod and all client tools, and changed the executables' exit code for the following situations:
- an unknown startup option name is used: previously the exit code was 1. Now the exit code when using an invalid option is 3 (symbolic exit code name EXIT_INVALID_OPTION_NAME).
- an invalid value is used for a startup option (e.g. a number that is outside the allowed range for the option's underlying value type, or a string value is used for a numeric option): previously the exit code was 1. Now the exit code for these case is 4 (symbolic exit code name EXIT_INVALID_OPTION_VALUE).
- a config file is specified that does not exist: previously the exit code was either 1 or 6 (symbolic exit code name …
> use more specific exit codes for invalid startup options

- arangod/VocBase/ComputedValues.cpp
- arangod/VocBase/ComputedValues.h
- tests/js/client/shell/shell-computed-values-cluster.js
- tests/js/client/shell/shell-dump-integration.js
- tests/js/client/shell/shell-restore-integration.js
- tests/js/common/shell/shell-collection-computed-values.js
- tests/js/server/dump/dump-setup-common.inc
- tests/js/server/dump/dump-test.inc
Rename "override" attribute for computed values to "overwrite", as decided by @ansoboleva and @joerg84.
> rename "override" attribute for computed values to "overwrite"

- CHANGELOG
- arangod/RocksDBEngine/RocksDBOptionFeature.cpp
This PR changes the default rocksdb compression type from `snappy` to `lz4`. 
[x] 3.10 https://github.com/arangodb/arangodb/pull/16613
> Changed rocksdb default compression type from snappy to lz4

- arangod/Replication2/StateMachines/Prototype/PrototypeStateMethods.cpp
- arangod/Replication2/StateMachines/Prototype/PrototypeStateMethods.h
- arangod/RestHandler/RestPrototypeStateHandler.cpp
- arangod/V8Server/v8-prototype-states.cpp
- js/client/modules/@arangodb/arango-prototype-state.js
- tests/js/common/shell/shell-prototype-state-cluster.js
- tests/js/server/replication2/replication2-prototype-replicated-state-cluster.js
In `PrototypeStateMethods`, if the leader state is not available, we read from the follower, without checking if the user intended that. While a request is in flight, a leader can become a follower, thus we might return obsolete data.
> [CINFRA-495] Unintentional Dirty Read

- js/client/modules/@arangodb/testsuites/server_permissions.js
- js/client/modules/@arangodb/testutils/instance-manager.js
- js/client/modules/@arangodb/testutils/process-utils.js
- killRemainingProcesses() needs to make sure the deadline is not engaged.
- instanceManager.shutdownInstance() should revert to force terminate, if anything goes wrong during shutdown.
Related:
- aftermath of https://github.com/arangodb/arangodb/pull/16566
- https://github.com/arangodb/arangodb/pull/15979
> BTS-824: make sure all are dead on abort

- js/client/modules/@arangodb/testutils/crash-utils.js
- js/client/modules/@arangodb/testutils/instance.js
testing.js would not produce aborted dumps in the proper place where oskar expects them. This could lead to crashdump zips not being generated / not containing the neccessary information.
> try to better align windows core dump handling to jenkins and the crash handler

- arangod/Replication2/LoggerContext.h
- arangod/Replication2/ReplicatedState/FollowerStateManager.tpp
- arangod/Replication2/ReplicatedState/LeaderStateManager.tpp
- arangod/Replication2/ReplicatedState/ReplicatedState.h
- arangod/Replication2/ReplicatedState/ReplicatedState.tpp
- arangod/Replication2/ReplicatedState/StateInterfaces.h
- arangod/Replication2/ReplicatedState/UnconfiguredStateManager.h
- arangod/Replication2/ReplicatedState/UnconfiguredStateManager.tpp
- arangod/Replication2/StateMachines/Prototype/PrototypeLeaderState.cpp
- arangod/Replication2/StateMachines/Prototype/PrototypeLeaderState.h
- tests/Replication2/ReplicatedState/FollowerSnapshotTest.cpp
- tests/main.cpp
* Prevent situations where a resigned manager could trigger a rebuild of its successor, possibly even resulting in a rebuild-loop.
* Make onSnapshotComplete `noexcept`, to make it more explicity that every exception but a `ParticipantResignedException`, which can be silently ignored, would result in an abort anyway.
* Renamed `forceRebuild` to `rebuildMe`
> [CINFRA-443] Fix remaining concurrency issues

- tests/js/client/shell/transaction/shell-transaction.js
This PR adds a test for a truncate operation inside a transaction that gets aborted.
This doesn't seem to have been covered before.
> add a test for aborting a truncate operation in a trx

- lib/Basics/UnshackledMutex.cpp
- lib/Basics/UnshackledMutex.h
Reverts arangodb/arangodb#16554
This is necessary because the libstdc++ and libc++ semaphore implementations are currently broken (see https://gcc.gnu.org/bugzilla/show_bug.cgi?id=104928).
Backport of #16642
> [3.10] Revert "Use std::semaphore for UnshackledMutex"

- lib/Basics/UnshackledMutex.cpp
- lib/Basics/UnshackledMutex.h
Reverts arangodb/arangodb#16554
This is necessary because the libstdc++ and libc++ semaphore implementations are currently broken (see https://gcc.gnu.org/bugzilla/show_bug.cgi?id=104928).
> Revert "Use std::semaphore for UnshackledMutex"

- arangod/Aql/Ast.cpp
- arangod/Aql/Ast.h
- arangod/Aql/StandaloneCalculation.cpp
- arangod/Sharding/ShardingInfo.cpp
- arangod/Sharding/ShardingInfo.h
- arangod/VocBase/ComputedValues.cpp
- arangod/VocBase/ComputedValues.h
- arangod/VocBase/LogicalCollection.cpp
- arangod/VocBase/Methods/Collections.cpp
- tests/js/common/shell/shell-collection-computed-values.js
Backport of https://github.com/arangodb/arangodb/pull/16639
Prevent a startup failure when there are invalid computed values definitions stored for a collection.
While it is not possible for a user to store an invalid computed values definition for a collection, an existing computed values definition may become unintentionally invalid after an upgrade, for example if in a future ArangoDB version the computed values' AQL query string becomes invalid for some reason (introduction of new keywords, disallowed language constructs etc.).
In that case, starting an instance would immediately fail because of the invalid computed values definition, and there is no way anymore to make it start.
This PR instead disables the computed values in that case, logs an error the log containing the problem …
> prevent a startup failure with invalid computed values

- arangod/Pregel/Conductor.cpp
- arangod/Pregel/Status/Status.h
When store=false, Done state directly follows Running state without
cleaning up. Cleanup just happens when run is canceled, therefore the
total timer ran until the Pregel run was canceled and not - as it
should - until the computation is done.
Now the total timer stops directly when entering Done state and not storing.
Additionally, correct memory label in status output
> [PREGEL] Bugfix: stop total pregel time correctly when not storing results

- arangod/Replication2/ReplicatedState/FollowerStateManager.tpp
- arangod/Replication2/ReplicatedState/StateStatus.h
- tests/Replication2/ReplicatedState/FollowerSnapshotTest.cpp
- tests/js/server/replication2/replication2-replicated-state-http-api-cluster.js
Expose the lastAppliedIndex in the replicated state status object. This is usefull for testing.
> [CINFRA-506] Add index to status.

- arangod/IResearch/IResearchInvertedIndexMeta.cpp
- arangod/IResearch/IResearchRocksDBInvertedIndex.cpp
- arangod/Indexes/IndexFactory.cpp
- tests/IResearch/IResearchInvertedIndexMetaTest.cpp
- tests/js/server/aql/aql-inverted-index.js
Allow to define fields as strings in inverted indexes
Allow to have index with empty fields definition but includeAllFields set
> Bug fix/search 325 fields as strings

- arangod/Aql/Functions.cpp
- arangod/Pregel/Conductor.cpp
- tests/js/common/shell/shell-pregel-basics-example.js
Bug: When running pregel with store: true, PREGEL_RESULT throwed an error in cluster-mode, but not in single-server-mode (there the PREGEL_RESULT is just empty)
With this PR, PREGEL_RESULT will always return an empty array if store: true was used in the config.
Additionally, it adds some more tests regarding querying PREGEL_RESULT
> Bugfix 3.10/pregel result is empty when store equals true

- arangod/GeneralServer/CommTask.cpp
- arangod/GeneralServer/GeneralServer.cpp
- arangod/GeneralServer/GeneralServer.h
- arangod/GeneralServer/GeneralServerFeature.cpp
Backport of https://github.com/arangodb/arangodb/pull/16659
when using `--server.early-connections`, the REST API is opened
early during startup and returns HTTP 200 for requests to `/_api/version`
and `/_admin/status`. this is as advertised, however, later in the
startup procedure the server will switch to maintenance mode, and then
it returned HTTP 503 for the same requests. this is inconsistent.
now, when using `--server.early-connections`, the server will keep
responding with HTTP 200 to the mentioned APIs during the entire
startup phase.
> Fix version to 3.10.0

- arangod/RestServer/TimeZoneFeature.cpp
currently:
```cpp
} catch (const std::runtime_error& ex) {
```
proposed change:
```cpp
} catch (std::runtime_error const& ex) {
```
A long time ago I read a PR comment in this repository that `const` should look like this.  
I also found a reference in the [STYLEGUIDE.md](https://github.com/arangodb/arangodb/blob/devel/STYLEGUIDE.md) 
Question: sould line 112 and 113
```cpp
std::string binaryExecutionPath = context->getBinaryPath();
std::string binaryName = context->binaryName();
```
also be const?
> const&  as per style guide in TimeZoneFeature.cpp

- arangod/CMakeLists.txt
- arangod/Pregel/Conductor.cpp
- arangod/Pregel/Conductor.h
- arangod/Pregel/Conductor/LoadingState.cpp
- arangod/Pregel/Conductor/LoadingState.h
- arangod/Pregel/Conductor/State.h
- arangod/Pregel/Worker.cpp
- arangod/Pregel/WorkerConductorMessages.h
Adds a finite state machine to the conductor to improve readability: The behavior of the conductor will now be determined by the conductor state. Before, the conductor only had a enum type `_state`, which had to be checked many times. Now state changes will be defined inside a specific conductor state and can happen when the state runs or gets a message.
This is only the first PR concerning the state machine: It adds only the LoadingState and AnotherState which is just a placeholder for the following state - it will be removed later on. This PR will not break anything, the old enum type `_state` will be deleted once all conductor states are added.
> [PREGEL] Add Conductor state machine and use it for the Loading state

- .gitignore
The following files can now be removed from `.gitignore`, as they are not generated inside the source directory anymore:
* lib/Basics/error-registry.h
* lib/Basics/exitcodes.h
* lib/Basics/voc-errors.h
Nowadays these files are auto-generated inside the build directory, so they do not need to be git-ignored.
Ignoring the files has the downside of ArangoDB builds potentially including outdated versions of these files should they still exist in the file system (e.g. after switching from an older branch to devel). Git-ignoring these files then just hides this problem.
This issue was randomly found during development, but will not affect anyone but developers that switch between old branches and devel in the same checkout directory.
> remove obsolete files from .gitignore

- arangod/CMakeLists.txt
- arangod/Pregel/Conductor.cpp
- arangod/Pregel/Conductor.h
- arangod/Pregel/Conductor/CanceledState.h
- arangod/Pregel/Conductor/DoneState.h
- arangod/Pregel/Conductor/InErrorState.cpp
- arangod/Pregel/Conductor/InErrorState.h
- arangod/Pregel/Conductor/LoadingState.h
- arangod/Pregel/Conductor/RecoveringState.cpp
- arangod/Pregel/Conductor/RecoveringState.h
- arangod/Pregel/Conductor/State.h
- arangod/Pregel/Worker.cpp
- arangod/Pregel/WorkerConductorMessages.h
Fifth PR for adding a state machine to the pregel conductor.
Adds InError and Recovering states to conductor state machine. Recovering is triggered from outside and is just allowed when state is Running or InError, therefore I created a new state-machine method recover(), which starts the Recovery state only from InError and Running (not yet implemented) state.
> [Pregel] Add recovering to conductor state machine

- arangod/CMakeLists.txt
- arangod/Pregel/Conductor.cpp
- arangod/Pregel/Conductor.h
- arangod/Pregel/Conductor/CanceledState.cpp
- arangod/Pregel/Conductor/CanceledState.h
- arangod/Pregel/Conductor/DoneState.cpp
- arangod/Pregel/Conductor/DoneState.h
- arangod/Pregel/Conductor/FatalErrorState.cpp
- arangod/Pregel/Conductor/FatalErrorState.h
- arangod/Pregel/Conductor/InErrorState.cpp
- arangod/Pregel/Conductor/InErrorState.h
- arangod/Pregel/Conductor/LoadingState.h
- arangod/Pregel/Conductor/RecoveringState.cpp
- arangod/Pregel/Conductor/RecoveringState.h
- arangod/Pregel/Conductor/State.h
- arangod/Pregel/Conductor/StoringState.cpp
- arangod/Pregel/Conductor/StoringState.h
Sixth PR for adding a state machine to the pregel conductor.
- Adds FatalError to conductor state machine. 
- Pregel results are only given via the conductor state to AQL. This ensures that the results are only given if the conductor is in the Done or FatalError state (although I'm really not sure why FatalError - in my opinion results should only be available in the Done state).
> [PREGEL] Add fatal error state and getResults method to conductor state machine

- arangod/IResearch/IResearchDataStore.cpp
- arangod/IResearch/IResearchDataStore.h
> Fix incorrect destroy order that cause data race

- arangod/Replication2/ReplicatedLog/Supervision.cpp
- arangod/Replication2/ReplicatedLog/SupervisionAction.h
- tests/Replication2/Helper/AgencyLogBuilder.h
- tests/Replication2/ReplicatedLog/SupervisionTest.cpp
This patch causes the supervision to set `effectiveWriteConcern` and `assumedWriteConcern` right when the leader election happens;
> [CINFRA-508] LeaderElection sets write concern

- arangod/ClusterEngine/ClusterCollection.cpp
- arangod/ClusterEngine/ClusterIndex.cpp
- arangod/ClusterEngine/ClusterIndex.h
- tests/js/common/shell/shell-collection.js
Backport of https://github.com/arangodb/arangodb/pull/16708
Fix UB in collection properties updating if the collection had at least one inverted index and the operation was carried out in a cluster
> fix UB in collection properties updating

- arangod/Aql/AqlFunctionFeature.cpp
- arangod/Aql/Functions.cpp
- arangod/Aql/Functions.h
- tests/js/server/aql/aql-functions.js
Add VALUE AQL function for dynamic access by a specified attribute path.
> `VALUE` AQL function

- CHANGELOG
- Documentation/DocuBlocks/Rest/Administration/get_admin_log.md
- arangod/RestHandler/RestAdminLogHandler.cpp
- arangod/RestHandler/RestAdminLogHandler.h
- tests/js/client/shell/shell-admin-log.js
Allows you to forward the request to another server. On Coordinators we can use normal user authentication. This is not available on DBServers and therefore until know it was necessary to work with JWT headers.
> Added serverId for _admin/log/level

- arangod/Aql/ClusterQuery.cpp
- arangod/Aql/ClusterQuery.h
- arangod/Aql/Query.cpp
- arangod/Aql/Query.h
- arangod/Aql/QueryOptions.h
- js/client/modules/@arangodb/testutils/test-utils.js
- lib/Futures/Future.h
- tests/Cache/Rebalancer.cpp
- tests/Cache/TransactionsWithBackingStore.cpp
- tests/Fuerte/ConnectionFailuresTest.cpp
- tests/Futures/FutureTest.cpp
- tests/IResearch/IResearchFeatureTest.cpp
- tests/IResearch/IResearchViewNodeTest.cpp
- tests/Network/MethodsTest.cpp
- tests/Replication2/ModelChecker/ModelChecker.h
- tsan_arangodb_suppressions.txt
> Fix few tsan issues

- lib/Inspection/Access.h
- tests/Basics/InspectionTest.cpp
Make the inspector able to handle a VPackBuilder inside a struct. This makes refactoring of old code to use Inspectors easier: Nested datastructures don't need to be refactored all the way down to use Inspectors, just put them inside a VPackBuilder in the struct. Then you can refactor this nested datastructure at another point and don't have to do it all at once.
> Make inspector able to read and write VPackBuilder

- arangod/RocksDBEngine/RocksDBTempStorage.cpp
Fix a shutdown memleak in case the temporary storage for RocksDB is used.
> fix shutdown memleak for temp storage db

- arangod/Aql/Ast.cpp
- arangod/Aql/Ast.h
- tests/js/server/aql/aql-queries-optimizer.js
Fix an invalid attribute access in query optimization.
Without the fix, an input query such as
```
LET data = { 
"a": [ 
{ "id":123,"search":"","data":[] }, 
{ "id":456,"search":"","data":[] } 
], 
"b": [] 
} 
FOR d IN data["a"] 
RETURN d
```
could fail with error "invalid operand to FOR loop, expecting Array".
> fix an invalid attribute access

- tests/CMakeLists.txt
- tests/VocBase/ComputedValuesTest.cpp
Backport of https://github.com/arangodb/arangodb/pull/16713
Added unit tests for computed values
> added unit tests for computed values (#16713)

- arangod/Pregel/Conductor.cpp
- arangod/Pregel/Conductor.h
- arangod/Pregel/Conductor/CanceledState.cpp
- arangod/Pregel/Conductor/RecoveringState.cpp
- arangod/Pregel/Conductor/StoringState.cpp
- arangod/Pregel/Statistics.h
- arangod/Pregel/Worker.cpp
- arangod/Pregel/Worker.h
- arangod/Pregel/WorkerConductorMessages.h
- lib/Inspection/Access.h
- tests/Basics/InspectionTest.cpp
- Make inspector able to read and write VPackBuilder to ease the use of Inspectors for nested data structures
- Use message structs for StartGss, GssFinished and CleanupFinished messages
- Use VPackBuilder for aggregators in other structs (here I revert a change I made before to be able to create messages: Now with the VPackBuilder ability for Inspectors, we can change the aggregators back to be unique_ptrs (as they were originally).
> [PREGEL] Use message structs everywhere possible

- arangod/Aql/Functions.cpp
- arangod/Pregel/Conductor.cpp
- arangod/Pregel/Conductor.h
- arangod/Pregel/Conductor/CanceledState.cpp
- arangod/Pregel/Conductor/DoneState.cpp
- arangod/Pregel/Conductor/FatalErrorState.cpp
- arangod/Pregel/Conductor/RecoveringState.cpp
- arangod/Pregel/Conductor/StoringState.cpp
- arangod/Pregel/PregelFeature.cpp
- arangod/Pregel/Statistics.h
- arangod/Pregel/Worker.cpp
- arangod/Pregel/WorkerConductorMessages.h
Rewrite Conductor::sendToAllDBServers function to get a struct (the message that is send to all workers) and return a vector of structs (the responses from all servers) instead of handling with VPackBuilders and callbacks.
> [PREGEL] Hide (de)serialization of messages inside Conductor::sendToAllDBServers function

- arangod/Graph/GraphOperations.cpp
- lib/Rest/GeneralResponse.cpp
- tests/js/client/shell/api/general-graph.js
Fixed edge/vertex documents not checked origin collection during creation.
Added missing type-check (isString) during creation. Added tests for both cases. Changed HTTP Code for ERROR_GRAPH_REFERENCED_VERTEX_COLLECTION_NOT_USED from 400 to 404 do be in sync with the way we handle the edges as well.
> BTS-325 Collection Validation Edge/Vertex API Gharial

- client-tools/Dump/DumpFeature.cpp
- client-tools/Dump/DumpFeature.h
- client-tools/Restore/RestoreFeature.cpp
- client-tools/Restore/RestoreFeature.h
- client-tools/Utils/ClientTaskQueue.h
Fix potential data races in task queue used by arangodump & arangorestore.
There could have been a race between the main arangodump/arangorestore thread checking if all jobs have been finished, and a queue worker thread popping a job from the job queue and only afterwards reporting as busy.
Tries to fix https://jenkins01.arangodb.biz/job/arangodb-ANY-linux-san.x86-64/1228/EDITION=enterprise,SAN_MODE=TSan,STORAGE_ENGINE=rocksdb,TEST_SUITE=single,limit=linux&&test&&x86-64/artifact/tsan.log.arangorestore.139376.log
> fix potential data races in dump/restore queue

- Documentation/DocuBlocks/Rest/Graph/general_graph_create_http_examples.md
*THis is a documentation only PR, it adds new DocuBlocks to describe creation of the different graph types over HTTP (that's the only place where thy differ API wise)*
This Branch on purpose has no JENKINS, as it does not touch any Production code.
> Added docublocks for HTTP Graph creation API

- tests/test-definitions.txt
tests must not be twice in the test definitions without specifying parameters that create different behaviour and logfiles.
> remove duplicates

- js/apps/system/_admin/aardvark/APP/react/src/views/g6graphs/AddEdgeModal.js
- js/apps/system/_admin/aardvark/APP/react/src/views/g6graphs/G6JsGraph.jsx
A After pressing the SHIFT key on the keyboard and clicking two nodes in the canvas the drawn edge would not be removed after cancelling the process in the popped up modal. This fix solves the issue.
> Bug fix/fe 142 remove edge after cancel

- js/apps/system/_admin/aardvark/APP/react/src/views/g6graphs/Headerinfo.js
- js/apps/system/_admin/aardvark/APP/react/src/views/g6graphs/HelpModal.js
To give users instructions on how to for example draw an edge between two nodes I added a help button that opens a modal with help and instructions.
> bug-fix/FE-141 Add a help modal

- js/apps/system/_admin/aardvark/APP/aardvark.js
After clicking the "run"-button an unwanted stroke was added in the wrong color to the nodes. This PR fixes the issue.
> bug-fix/FE-139 Apply node color correctly after receiving data

- Documentation/DocuBlocks/Rest/Documents/delete_mutliple_documents.md
- Documentation/DocuBlocks/Rest/Pregel/1_struct.md
- Documentation/DocuBlocks/Rest/Pregel/delete_api_control_pregel_cancel.md
- Documentation/DocuBlocks/Rest/Pregel/get_api_control_pregel_overview.md
- Documentation/DocuBlocks/Rest/Pregel/get_api_control_pregel_status.md
- Documentation/DocuBlocks/Rest/Pregel/post_api_control_pregel_start.md
- The Pregel status overview endpoint includes the `detail` attribute
- `vertexCount` and `edgeCount` are top-level attributes
- `reports` is only used by Custom Pregel / AIR
- Create a shared struct for Pregel status
> Docs: Fix `/_api/control_pregel` HTTP API descriptions

- arangod/RestServer/TtlFeature.cpp
Attempt to fix a TSan issue in TtlFeature. Some properties were accessed without holding a mutex during startup.
This should be safe (as there should be no concurrency at startup), but doesn't match the mutex usage in other code locations.
> attempt to fix a TSan issue

- CHANGELOG
- arangod/Aql/OptimizerRules.cpp
- tests/js/server/aql/aql-optimizer-rule-distribute-in-cluster.js
Backport of https://github.com/arangodb/arangodb/pull/16764
Since ArangoDB 3.8 there was a loophole for creating duplicate keys in the same collection. The requirements were:
- cluster deployment
- needs at least two collections (source and target), and the target collection must have more than one shard and must use a custom shard key.
- inserting documents into the target collection must have happened via an AQL query like `FOR doc IN source INSERT doc INTO target`.
In this particular combination, the document keys (`_key` attribute) from the source collection were used as-is for insertion into the target collection. However, as the target collection is not sharded by `_key` and uses a custom shard key, it is actually not allowed to specify user-defined values for `_key`. That check was …
> Fix loophole for creating duplicate keys

- arangod/Replication2/ReplicatedLog/SupervisionAction.h
- tests/Replication2/Helper/ModelChecker/Predicates.h
- tests/Replication2/ReplicatedLog/SupervisionSimulationTest.cpp
Set `assumedWaitForSync` on log creation
> [CINFRA-523] Set assumedWaitForSync when creating replicated log

- CMakeLists.txt
Require `CMake 3.21` for building ArangoDB; This is mostly to introduce useful `CMakePresets` as done in #16687 ; presets were introduced in cmake 3.19 and gained some more features in subsequent versions.
3.21 was chosen because this is the version that comes bundled with current CLion as to not disrupt developers workflow.
> [CMake] Require more recent cmake

- arangod/Replication2/Version.h
- arangod/RestServer/DatabaseFeature.cpp
- arangod/RestServer/DatabaseFeature.h
- arangod/VocBase/VocbaseInfo.cpp
When starting `arangod` one can now give the parameter `--database.default-replication-version <replicationVersion>` to set the default replication to either `1` or `2`.
> [CINFRA-528] Add commandline option to set default replication version.

- CMakeLists.txt
- arangod/Aql/OptimizerUtils.cpp
- arangod/RocksDBEngine/RocksDBCollection.cpp
- tests/js/server/aql/aql-inverted-index.js
Adds handling of NOT operator for  nested search 
fixes SEARCH-346
fixes MSVC version check
> Bug fix/handle not in nested search and SEARCH-346

- arangod/Aql/EngineInfoContainerDBServerServerBased.cpp
Backport of https://github.com/arangodb/arangodb/pull/16812
Fix a potentially invalid assertion, and assertion message in case of an error
> fix assertion

- CMakeLists.txt
Requiring a minimum CMakeVersion enables features that have been released in CMake up to that version; 
I would like to use CMakePresets.
In a previous PR our build was broken by the introduction of `CMAKE_MSVC_RUNTIME_LIBRARY`; this should now be fixed.
> [CMAKE] Require CMake 3.21

- tests/Aql/AqlSharedExecutionBlockImplTest.cpp
Fix use-after-scope in test
```
=================================================================
==arangodbtests==79553==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7fff5e966ff8 at pc 0x5597cca6ba32 bp 0x7fff5e963160 sp 0x7fff5e963150
READ of size 8 at 0x7fff5e966ff8 thread T0
#0 0x5597cca6ba31 in std::__uniq_ptr_impl<arangodb::RocksDBTempStorage, std::default_delete<arangodb::RocksDBTempStorage> >::_M_ptr() const /usr/include/c++/11/bits/unique_ptr.h:173
#1 0x5597cca6ba31 in std::unique_ptr<arangodb::RocksDBTempStorage, std::default_delete<arangodb::RocksDBTempStorage> >::get() const /usr/include/c++/11/bits/unique_ptr.h:422
#2 0x5597cca6ba31 in std::unique_ptr<arangodb::RocksDBTempStorage, std::default_delete<arangodb::RocksDBTempStorage> >::operator*() const …
```
> fix use-after-scope in test

- js/apps/system/_admin/aardvark/APP/frontend/js/templates/indicesView.ejs
List the downsides of sparse indexes, so that end users are aware of them.
This PR only changes a help text in the web interface.
> add hint for sparse indexes to UI

- arangod/IResearch/IResearchDataStore.cpp
- arangod/IResearch/IResearchDataStore.h
- arangod/IResearch/IResearchInvertedIndex.cpp
- arangod/IResearch/IResearchKludge.cpp
- arangod/IResearch/IResearchKludge.h
- arangod/IResearch/IResearchLink.cpp
Fix prev doc tracking  in PK column used for removals
> SEARCH-329 fix prev-doc tracking

- js/client/modules/@arangodb/testutils/test-utils.js
Exclude crash recovery tests from TSan runs as well (they were already excluded from ASan runs).
> exclude some tests from TSan runs as well

- js/client/modules/@arangodb/testutils/test-utils.js
Backport of https://github.com/arangodb/arangodb/pull/16853
Exclude crash recovery tests from TSan runs as well (they were already excluded from ASan runs).
> exclude some tests from TSan runs as well (#16853)

- arangod/IResearch/IResearchInvertedIndex.cpp
- tests/js/server/aql/aql-inverted-index.js
Fixes SEARCH-328.
Both FILTER and REMOVE use "index pointer" as cookie key for storing  data in the AQL transaction context. 
So there will be conflict for query like FOR d IN  col OPTIONS { indexHint : "boo" } FILTER d.foo == '1' REMOVE d IN col
As a solution "cookie key" for snapshot is  now [index pointer + 1]
> Bug fix/search 328 fix cookie key

- arangod/Aql/TraversalExecutor.cpp
- arangod/Aql/TraversalExecutor.h
- arangod/Graph/Enumerators/OneSidedEnumerator.cpp
Backport of: https://github.com/arangodb/arangodb/pull/16774
> Cleanup of ast-modifications in TraversalExecutor (3.10)

- js/client/modules/@arangodb/testutils/instance-manager.js
use a proper error object when throwing, so we have stacktraces etc.
> throw proper error object

- js/client/modules/@arangodb/testsuites/resilience.js
- js/client/modules/@arangodb/testutils/instance.js
at the end of the test we should dump the agency - just in case. This fixes the authentification to fix dumping.
> fix dumping of active failover agency

- js/client/modules/@arangodb/testutils/instance.js
- js/client/modules/@arangodb/testutils/testing.js
as seen previously forgetting debug logging in tests leads to unstable CI. Assert this for green tests.
> Bug fix/limit size of arangodlogs

- arangod/Aql/OptimizerUtils.cpp
- tests/js/server/aql/aql-inverted-index.js
Adds handling of possibly non-const array comparison operators to the index
> SEARCH-368 fix handling of array comparison

- arangod/Aql/AqlFunctionFeature.cpp
- arangod/Aql/Functions.cpp
- tests/IResearch/IResearchQueryAndTest.cpp
- tests/js/server/aql/aql-functions-string.js
Make SUBSTRING_BYTES work similar to SUBSTRING
> Make SUBSTRING_BYTES work similar to SUBSTRING

- lib/Basics/ErrorCode.h
- lib/Basics/Result.cpp
- lib/Basics/Result.h
- lib/Basics/ResultError.h
- lib/Basics/ResultT.h
- lib/Inspection/Access.h
- tests/Basics/InspectionTest.cpp
This PR adds a VPack Inspector for Result and ResultT types, such that serialization and deserialization of those types is easy.
> Add inspector for ResultT

- tests/Replication2/ReplicatedState/DocumentStateMachineTest.cpp
Fixes compile warning in replication2 tests:
``` 
/home/jan/ArangoDevel/tests/Replication2/ReplicatedState/DocumentStateMachineTest.cpp: In member function ‘virtual std::unique_ptr<arangodb::replication2::replicated_state::document::IDocumentStateTransactionHandler> MockDocumentStateHandlersFactory::createTransactionHandler(arangodb::replication2::GlobalLogIdentifier)’:
/home/jan/ArangoDevel/tests/Replication2/ReplicatedState/DocumentStateMachineTest.cpp:193:21: warning: redundant move in return statement [-Wredundant-move]
193 |     return std::move(th);
|            ~~~~~~~~~^~~~
/home/jan/ArangoDevel/tests/Replication2/ReplicatedState/DocumentStateMachineTest.cpp:193:21: note: remove ‘std::move’ call
```
> fix a compile warning in replication2 tests

- arangod/IResearch/IResearchFilterFactory.cpp
- arangod/IResearch/IResearchFilterFactory.h
Fixes handling of empty nested filter ( "[?]" ) Before it was silently converted to "all documents". that is wrong as this filter should return all documents having any array as a field. So now it is forced to ByExpression filter
> SEARCH-322 fix empty nested condition

- lib/Basics/ThreadGuard.h
- tests/Basics/MemoryUsageTest.cpp
- tests/Basics/RecursiveLockerTest.cpp
- tests/Fuerte/ConnectionConcurrentTest.cpp
- tests/Metrics/MetricsTest.cpp
- tests/Replication2/ModelChecker/ModelChecker.h
- tests/Replication2/ReplicatedLog/ConcurrencyTests.cpp
- tests/Replication2/Streams/MultiplexerConcurrencyTest.cpp
In #16913 @MBkkt addressed an issue where threads created in a test were potentially not joined if an exception was thrown and the test scope was left.
This PR attempts to improve the suggested code a little bit by introducing a `ThreadGuard`, which is just a struct that wraps a vector of threads and joins them on request and on destruction.
> Introduce ThreadGuard 

- arangod/Pregel/Conductor/Conductor.cpp
- arangod/Pregel/Conductor/Conductor.h
- arangod/Pregel/Conductor/States/LoadingState.cpp
- arangod/Pregel/Conductor/States/LoadingState.h
- arangod/Pregel/GraphStore.cpp
- arangod/Pregel/GraphStore.h
- arangod/Pregel/PregelFeature.cpp
- arangod/Pregel/Worker/Worker.cpp
- arangod/Pregel/Worker/Worker.h
- arangod/Pregel/WorkerConductorMessages.h
- arangod/Pregel/WorkerInterface.h
This PR introduces futures to load the graph. This is used initialize the loading at the conductor, request loading the graph for all workers and continue the work on the conductor as soon as all workers have finished loading.
This PR includes the inspector for ResultT because I need it here already. I already created a PR for devel on that (https://github.com/arangodb/arangodb/pull/16891), so you don't have to look at the code changes in lib in this PR.
> [PREGEL] implement load graph with future

- tests/Fuerte/ConnectionConcurrentTest.cpp
When introducing the `ThreadGuard` I changed a lambda capture from `[=]` to
`[&]` overlooking an implicitly captured variable.
This patch changes the code to explicitly capture variables.
> Fix stack-use-after-scope in fuertetest

- lib/Basics/ThreadGuard.h
- tests/Basics/MemoryUsageTest.cpp
- tests/Basics/RecursiveLockerTest.cpp
- tests/Fuerte/ConnectionConcurrentTest.cpp
- tests/Metrics/MetricsTest.cpp
This is a backport of #16918 
* Introduce ThreadGuard
A ThreadGuard is a struct that wraps a vector of threads and ensures
all threads are (tried to be) joined if the scope is left.
This is for example important if an excpetion is thrown and the scope
is left without completing the control flow.
Co-authored-by: Valery Mironov <valera.mironow@gmail.com>
**IMPORTANT**: when this PR gets merged, please also merge https://github.com/arangodb/arangodb/pull/16933!
> [3.10] Introduce ThreadGuard

- arangod/IResearch/GeoAnalyzer.cpp
- arangod/RestServer/EnvironmentFeature.cpp
- arangod/Utils/UrlHelper.cpp
- lib/VPackDeserializer/parameter-list.h
Backport of https://github.com/arangodb/arangodb/pull/16879
Fix issues uncovered by cppcheck:
```
12:21:48 duplicateExpression: Same expression "opts.maxCells<0" found multiple times in chain of "||" operators.
12:21:48     arangod/IResearch/GeoAnalyzer.cpp:73
12:21:48 
12:21:48 accessForwarded: Access of forwarded variable "ctx".
12:21:48     lib/VPackDeserializer/parameter-list.h:400
12:21:48     lib/VPackDeserializer/parameter-list.h:396
12:21:48 
12:21:48 returnTempReference: Reference to temporary returned.
12:21:48     arangod/Utils/UrlHelper.cpp:48
12:21:48 
12:21:48 containerOutOfBounds: Either the condition "end<cpuAlignment.size()" is redundant or "end" can have the value cpuAlignment.size(). Expression "cpuAlignment[end]" cause access out of bounds.
12:21:48 …
```
> try to fix issues reported by cppcheck (#16879)

- js/client/modules/@arangodb/testutils/instance.js
Fix a puzzling error message in testing.js.
String substitution wasn't used correctly, and the unit for the file size returned was also wrong.
The error message only appears during tests, so this fix does not need to be backported.
> fix puzzling error message

- utils/cppcheck.sh
-------
Updates C++ version to C++20 in cppcheck skript.
PR https://github.com/arangodb/arangodb/pull/16891 used constraints for the first time (in ResultT.h) - a C++20 feature. The old cppcheck used C++17 and therefore generated an error for ResultT.h when running.
> Updates C++ version in cppcheck

- arangod/Aql/Projections.cpp
- tests/js/server/aql/aql-optimizer-rule-reduce-extraction-to-projection.js
Fix extracing `_id` sub-attribute with projections.
Fixes https://arangodb.atlassian.net/browse/SEARCH-366
> fix extracing _id sub attribute with projections

- CHANGELOG
- js/common/modules/@arangodb/aql/explainer.js
Backport of https://github.com/arangodb/arangodb/pull/16957
Following a suggestion by @joerg84 , make the AQL query explainer show that a non-covering index scan requires extra document lookups. The explainer will now not only display "index scan" in this case, but "index + document lookup".
Hopefully this helps understanding the execution plans and their costs better.
> make it clear in query explain output that there are document lookups

- CHANGELOG
- Documentation/Metrics/arangodb_sync_rebuilds_total.yaml
- arangod/Cluster/SynchronizeShard.cpp
- tests/js/client/shell/shell-collection-counts-cluster.js
Backport of https://github.com/arangodb/arangodb/pull/16955
Do not drop follower shard after too many failed shard sync attempts.
> Do not drop follower shard after too many failed shard sync attempts.

- arangod/Replication2/StateMachines/Document/DocumentFollowerState.cpp
- arangod/Replication2/StateMachines/Document/DocumentFollowerState.h
- arangod/Replication2/StateMachines/Document/DocumentLeaderState.cpp
- arangod/Replication2/StateMachines/Document/DocumentLeaderState.h
On the follower, it is possible to `resign` during `applyEntries`.
On the leader, it is possible to `resign` during `recoverEntries`.
This PR fixes these issues, by using a lock on the core.
> [CINFRA-538] Resign and apply race condition

- js/client/modules/@arangodb/testutils/crash-utils.js
- js/client/modules/@arangodb/testutils/instance-manager.js
- js/client/modules/@arangodb/testutils/instance.js
- tests/test-definitions.txt
so far we would use the default coredump generation process in order to generate coredumps. 
This 
- doesn't always work on mac
- generates coredumps regardless of the expected filesize
- if one wouldn't generate the coredump, all information would be lost hence attach the debugger to the process
> add a way to generate stacktraces and coredumps via the debugger

- CHANGELOG
- arangod/RocksDBEngine/RocksDBEngine.cpp
- arangod/RocksDBEngine/RocksDBOptionFeature.cpp
- arangod/RocksDBEngine/RocksDBOptionFeature.h
Backport of https://github.com/arangodb/arangodb/pull/16982
Docs PR: https://github.com/arangodb/docs/pull/1104
Added startup option `--rocksdb.periodic-compaction-ttl`
This option controls the TTL (in seconds) for periodic compaction of .sst files in RocksDB, based on the .sst file age. The default value from RocksDB is ~30 days. To avoid periodic auto-compaction, the option can be set to 0.
> Added startup option `--rocksdb.periodic-compaction-ttl`

- tests/js/client/restart/test-soft-shutdown-cluster.js
This PR attempts to address some test failures seen in CI due to assertions triggering when there was an unexpected number of transactions (2 vs 1);
Since the test cannot be certain how many transactions are open, as other workers on the cluster might have opened transactions, assert that there is more than one transaction present.
Also, add some messages on the assertions so that future failures are more obvious to categorise.
> Make assertions in soft shutdown cluster test more stable.

- Documentation/Metrics/arangodb_search_num_out_of_sync_links.yaml
- arangod/IResearch/IResearchFeature.cpp
Adjust target version for new arangosearch options (3.9.4) and also a few message texts ("failed" => "out of sync").
For 3.10, the changes will be included in https://github.com/arangodb/arangodb/pull/16900
> adjust target version and messages

- CHANGELOG
- arangod/Pregel/Algos/ConnectedComponents.h
- arangod/Pregel/Algos/EffectiveCloseness/EffectiveCloseness.h
- arangod/Pregel/Algos/HITS.h
- arangod/Pregel/Algos/LabelPropagation.h
- arangod/Pregel/Algos/LineRank.cpp
- arangod/Pregel/Algos/PageRank.cpp
- arangod/Pregel/Algos/RecoveringPageRank.h
- arangod/Pregel/Algos/SCC.h
- arangod/Pregel/Algos/SSSP.h
- arangod/Pregel/Algos/WCC.h
- js/client/modules/@arangodb/air/single-source-shortest-paths.js
- js/client/modules/@arangodb/air/strongly-connected-components.js
- tests/js/client/load-balancing/load-balancing-pregel-noauth-cluster.js
- tests/js/common/shell/shell-pregel-random.js
Replaced "PageRank" by "pagerank" in the internal and the API of Pregel. 
Now when the PageRank algorithm is run, `... GET /_api/control_pregel/{id}` returns 
```
{
...
"algorithm": "pagerank",
...
}
```
instead of 
```
{
...
"algorithm": "PageRank",
...
}
```
> [PREGEL]replaced "PageRank" by "pagerank" everywhere in the API

- js/client/modules/@arangodb/testsuites/server_permissions.js
- js/client/modules/@arangodb/testutils/crash-utils.js
- js/client/modules/@arangodb/testutils/instance-manager.js
- js/client/modules/@arangodb/testutils/instance.js
On slower systems firing up all instances at once and waiting for the dust to settle doesn't seem to work out in all cases.
- first start the agency and wait for it to be ready.
- add a way to dynamically wait for instance readyness for `server_parameter` tests and copying of javascript files
- fix lldb attach + coredump
- filter verbose lldb writing coredump messages
- give more time for active failover to detect a leader
- fix managing of agency URLs in agency config
> BTS-1000: wait for agency to give us a good state before we start firing up the rest of the instance

- arangod/Pregel/CMakeLists.txt
- arangod/Pregel/Conductor/CMakeLists.txt
- arangod/Pregel/Conductor/ClusterWorkerApi.cpp
- arangod/Pregel/Conductor/ClusterWorkerApi.h
- arangod/Pregel/Conductor/Conductor.cpp
- arangod/Pregel/Conductor/Conductor.h
- arangod/Pregel/Conductor/SingleServerWorkerApi.cpp
- arangod/Pregel/Conductor/SingleServerWorkerApi.h
- arangod/Pregel/Conductor/States/ComputingState.cpp
- arangod/Pregel/Conductor/States/LoadingState.cpp
- arangod/Pregel/NetworkConnection.cpp
- arangod/Pregel/NetworkConnection.h
- arangod/Pregel/PregelFeature.cpp
- arangod/Pregel/Worker/Worker.cpp
- arangod/Pregel/Worker/Worker.h
- arangod/Pregel/WorkerConductorMessages.h
- arangod/Pregel/WorkerInterface.h
Use future to prepare the global super step
Move ConductorWorkers into their own files and in the conductor namespace and rename them to ClusterWorkerApi and SingleServerWorkerApi.
> [PREGEL] Use future to prepare global super step

- client-tools/Dump/DumpFeature.cpp
- client-tools/Dump/DumpFeature.h
- client-tools/Restore/RestoreFeature.cpp
- client-tools/Restore/RestoreFeature.h
- client-tools/Utils/ClientTaskQueue.h
Backport of https://github.com/arangodb/arangodb/pull/16775
Fix potential data races in task queue used by arangodump & arangorestore.
There could have been a race between the main arangodump/arangorestore thread checking if all jobs have been finished, and a queue worker thread popping a job from the job queue and only afterwards reporting as busy.
Tries to fix https://jenkins01.arangodb.biz/job/arangodb-ANY-linux-san.x86-64/1228/EDITION=enterprise,SAN_MODE=TSan,STORAGE_ENGINE=rocksdb,TEST_SUITE=single,limit=linux&&test&&x86-64/artifact/tsan.log.arangorestore.139376.log
> fix potential data races in dump/restore queue (#16775)

- tests/Fuerte/ConnectionConcurrentTest.cpp
Backport of #16932 to be merged after #16926 
When introducing the ThreadGuard I changed a lambda capture from [=] to
[&] overlooking an implicitly captured variable.
This patch changes the code to explicitly capture variables.
> [3.10] Fix stack-use-after-scope in fuertetest

- arangod/IResearch/IResearchDataStore.cpp
- arangod/IResearch/IResearchDataStore.h
- arangod/IResearch/IResearchInvertedIndex.cpp
- arangod/IResearch/IResearchInvertedIndex.h
- arangod/IResearch/IResearchLink.cpp
- arangod/IResearch/IResearchLink.h
- arangod/IResearch/IResearchLinkCoordinator.cpp
- arangod/IResearch/IResearchLinkCoordinator.h
- arangod/IResearch/IResearchMetricStats.h
- arangod/IResearch/IResearchRocksDBInvertedIndex.cpp
- arangod/IResearch/IResearchRocksDBInvertedIndex.h
- arangod/IResearch/IResearchRocksDBLink.h
- arangod/Metrics/ClusterMetricsFeature.h
- tests/Mocks/IResearchInvertedIndexMock.cpp
- tests/Mocks/IResearchInvertedIndexMock.h
- tests/Mocks/IResearchLinkMock.h
- tests/js/common/aql/aql-view-arangosearch-ddl-cluster.js
* SEARCH-341 Stats for inverted index are not shown in arangosh
* SEARCH-340 Metrics for inverted index do not exist
cherry picked from commit dcbce7f28a51aa47b736cb4b891a59c91a0c930a
> Inverted index stats and metric backport for 3.10

- arangod/RocksDBEngine/Listeners/RocksDBMetricsListener.cpp
- arangod/RocksDBEngine/Listeners/RocksDBMetricsListener.h
Backport of https://github.com/arangodb/arangodb/pull/16996
Add optional log messages whenever RocksDB begins or completes a compaction. The log messages will show the base level and target level plus the number of files and reason for the compaction.
Log message will look like:
```
2022-09-06T10:34:35Z [24630] DEBUG [1367c] {engines} rocksdb compaction begin in column family Documents from base input level 5 to output level 6, input files: 3, output files: 0, reason: total size of level > MaxBytesForLevel()
```
Log messages will only be displayed if log level ENGINES <= debug
> add optional log output for RocksDB compactions

- tests/js/server/aql/aql-vector-functions.js
Make a specific AQL test use less memory, by reducing the maximum array size used in the test by one order of magnitude.
The change only affects tests.
> BTS-1003: make test use less memory

- Documentation/DocuBlocks/Rest/Indexes/post_api_index_geo.md
Fix wrong type for geoJson attribute (string -> boolean) in API documentation.
> fix wrong type for geoJson attribute (string -> boolean)

- tests/Replication2/ReplicatedLog/SupervisionSimulationTest.cpp
- tests/Replication2/ReplicatedState/SupervisionModelChecker.cpp
This fixes some warnings about uninitialized fields in the Supervision Model Checker.
> [CINFRA] Fix compiler warningns in SupervisionModelChecker tests

- arangod/Replication2/StateMachines/Document/DocumentLeaderState.cpp
- arangod/Replication2/StateMachines/Document/DocumentLeaderState.h
- arangod/Replication2/StateMachines/Document/DocumentStateMachine.cpp
- arangod/Replication2/StateMachines/Document/DocumentStateMachine.h
- arangod/Replication2/StateMachines/Document/DocumentStateMachineFeature.cpp
- arangod/Transaction/Manager.h
- tests/Replication2/ReplicatedLog/RocksDBLogTest.cpp
- tests/Replication2/ReplicatedLog/TestHelper.h
- tests/Replication2/ReplicatedState/DocumentStateMachineTest.cpp
Abort transactions and register tombstones in the transaction manager for any remaining transactions when the leader resigns, as well as transactions that are still pending after finishing recovery.
> [CINFRA-511] Improve transaction handling in leader state

- arangod/Pregel/Conductor.cpp
Make log IDs unique again in Pregel.
Not a real issue, but log ids are supposed to be unique across the entire code.
> make Pregel log ids unique again

- CHANGELOG
- arangod/RocksDBEngine/RocksDBMetaCollection.cpp
- arangod/RocksDBEngine/RocksDBMetaCollection.h
- arangod/RocksDBEngine/RocksDBReplicationContext.cpp
- arangod/RocksDBEngine/RocksDBReplicationContext.h
- arangod/RocksDBEngine/RocksDBRestReplicationHandler.cpp
- arangod/RocksDBEngine/RocksDBV8Functions.cpp
- arangod/StorageEngine/PhysicalCollection.cpp
- arangod/StorageEngine/PhysicalCollection.h
This PR attacks the problem described in
https://arangodb.atlassian.net/browse/BTS-989
The problem is that if one orders a batch (aka
RocksDBReplicationContext), which includes a snapshot of RocksDB, it is
not guaranteed that one can subsequently fetch a revision tree for some
collection/shard which corresponds to the sequence number of the
snapshot in this batch. This is because the revision tree of the
collection might already have been rolled forward.
This PR makes it so that in case a batch is bound to a specific
collection (which happens when SynchronizeShard on the follower
tries to get in sync with the leader), then the revision tree for
that collection is prefetched and buffered in the batch.
This means that later when the revision tree is requested by the
follower, it is …
> Prefetch for revision trees - BTS-989

- arangod/Aql/Quantifier.cpp
- tests/js/server/aql/aql-array-access.js
Backport of https://github.com/arangodb/arangodb/pull/16945
Fix a bug randomly reported via Slack about "Haustiere" results.
> fix random haustier bug

- Documentation/DocuBlocks/Rest/Collections/1_structs.md
- Documentation/DocuBlocks/Rest/Collections/post_api_collection.md
- Documentation/DocuBlocks/Rest/Collections/put_api_collection_properties.md
Docs PR: https://github.com/arangodb/docs/pull/1065 (will be copied from 3.10 when version 3.11 is created in the docs repo)
> DOC-123 | Add `computedValues` collection property for Computed Values

- tests/js/server/shell/shell-index-background.js
static timeouts don't work well on small hardware.
Increase timeout if we see progress.
> BTS-1002: make timeout in tests progressive if we monitor test progress

- tests/js/server/aql/aql-optimizer-collect-count.js
tests/js/server/aql/aql-optimizer-collect-count.js was wastefull with resources. Fixed hereby.
> BTS-998: use setupAll, split writing tests

- arangod/IResearch/IResearchDataStore.cpp
- tests/js/server/shell/shell-arangosearch-out-of-sync-noncluster.js
Backport of https://github.com/arangodb/arangodb/pull/17046
do not carry out insert/remove in out-of-sync links, in case we want queries to fail on out-of-sync links. otherwise, carry out these operations.
> do not carry out insert/remove in out-of-sync links

- arangod/RocksDBEngine/RocksDBRestReplicationHandler.cpp
Fix a potential nullptr dereferencing in revision tree prefetching.
The issue was found during testing (https://jenkins01.arangodb.biz/job/arangodb-matrix-pr-linux.aarch64/2895/EDITION=community,STORAGE_ENGINE=rocksdb,TEST_SUITE=cluster,limit=linux&&test&&aarch64/artifact/testfailures.txt):
```
...
#9  0x0000000003a57ba4 in abort () at src/exit/abort.c:11
#10 0x0000000002379f34 in killProcess () at /work/ArangoDB/lib/Basics/CrashHandler.cpp:138
#11 0x000000000237ade0 in crashHandlerSignalHandler () at /work/ArangoDB/lib/Basics/CrashHandler.cpp:518
#12 <signal handler called>
#13 arangodb::Mutex::lock () at /work/ArangoDB/lib/Basics/Mutex.cpp:67
#14 0x0000000000535eb4 in arangodb::basics::MutexLocker<arangodb::Mutex>::lock () at /work/ArangoDB/lib/Basics/MutexLocker.h:110
#15 …
```
> fix a potential nullptr dereference in revision tree fetching

- cmake/InstallArangoDBJSClient.cmake
Backport of https://github.com/arangodb/arangodb/pull/17054
* Remove special handling for `is-wsl` node module during packaging. There is no `is-wsl` module directly underneath `js/node/node_modules`. There is only one in `js/node/node_modules/node-netstat/node_modules/is-wsl`, but `node-netstat` is already excluded from packaging.
* Also exclude `parse-prometheus-text-format` from packaging, as it is only used from the UI and for testing.
> remove special handling for is-wsl node module (#17054)

- CHANGELOG
- arangod/IResearch/IResearchDataStore.cpp
- arangod/IResearch/IResearchDataStore.h
- arangod/IResearch/IResearchFeature.cpp
- arangod/IResearch/IResearchFeature.h
Backport of https://github.com/arangodb/arangodb/pull/16994
Displays progress report during arangosearch link recovery, e.g.
```
...
2022-09-05T18:02:00Z [65850] INFO [d1f18] {arangosearch} recovering arangosearch link 4792073 (stage1, operation 1/1 (0%)
2022-09-05T18:03:00Z [65850] INFO [d1f18] {arangosearch} recovering arangosearch link 4792073 (stage3, operation 67/209 (31%)
2022-09-05T18:04:01Z [65850] INFO [d1f18] {arangosearch} recovering arangosearch link 4792073 (stage3, operation 136/209 (64%)
2022-09-05T18:05:01Z [65850] INFO [d1f18] {arangosearch} recovering arangosearch link 4792073 (stage3, operation 208/209 (99%)
2022-09-05T18:05:03Z [65850] INFO [d1f18] {arangosearch} recovering arangosearch link 5507397 (stage1, operation 1/1 (0%)
2022-09-05T18:06:04Z [65850] INFO [d1f18] …
```
> display progress during link recovery

- arangod/RestHandler/RestIndexHandler.cpp
- arangod/VocBase/Methods/Indexes.cpp
Add `selectivityEstimate` attribute to the return value of `/_api/index/<collection>/<index-id>`.
> add selectivityEstimate to index detail API

- tests/js/server/aql/aql-vector-functions.js
Backport of https://github.com/arangodb/arangodb/pull/16999
Make a specific AQL test use less memory, by reducing the maximum array size used in the test by one order of magnitude.
The change only affects tests.
> make test use less memory (#16999)

- client-tools/Export/ExportFeature.cpp
Improve summary message of arangoexport
It previously always displayed "Processed 0 collection(s)" even when running a custom query or exporting a graph. this was misleading. it will now display either "Processed x collection(s)", "Processed 1 query" or "Processed 1 graph", depending on the invocation.
> improve summary message of arangoexport

- js/client/modules/@arangodb/testutils/crash-utils.js
- js/client/modules/@arangodb/testutils/instance-manager.js
- js/client/modules/@arangodb/testutils/instance.js
- we would show errnous process flow when the arangod died in advance.
This patch detects it, and avoids the situation alltogether. 
- properly print the instance name in information message
- aggregate the debugger processes when we shutdown-deadline-kill an arangod
- if the debugger is unable to terminate the process, we must not hand, but hard kill the process on our own.
> Testframework: Fix handling in crash analysis

- arangod/Transaction/Methods.cpp
Verify the obtained shared_pointer to `LogicalCollection` so that when it is a nullptr, we do not dereference it and crash, but fail with a proper error message instead.
> BTS-970: verify collection pointer before dereferencing it

- tests/js/server/recovery/out-of-sync-link.js
This PR fixes a potential instability in a recovery test.
Without this fix, the test may fail intermittently.
> improve test stability

- js/client/modules/@arangodb/testutils/instance.js
- tests/js/client/restart/test-soft-shutdown-pregel-cluster.js
backport of https://github.com/arangodb/arangodb/pull/17091
> Testframework: if we timeout waiting for an instance shutdown, properly pick up the debugger again

- lib/ProgramOptions/Parameters.cpp
Avoid potential static initialization order fiasco between PhysicalMemory.cpp and Parameters.cpp
> avoid static init order fiasco

- tests/js/client/load-balancing/load-balancing-pregel-noauth-cluster.js
After sending the request to delete a pregel run, the run is beeing canceled and deletes all its components. This deletion can take an unknown amount of time. Therefore requesting the pregel status directly after the deletion request run can still show the deleted run.
> [PREGEL] Delete brittle pregel test assertion

- arangod/VocBase/LogicalCollection.cpp
Update fmt to 9.1.0; 
This requires a small fix in the LogicalCollection code: automatic use of `ostream<<` for `fmt` has been deprecated because of problems with ODR violations.
Two options exist: either explicit formatter specialisation with a helper struct `ostream_formatter` or using `fmt::streamed`; the latter seemed less intrusive for now.
> Update fmt to version 9.1.0

- arangod/Pregel/Conductor/ClusterWorkerApi.cpp
- arangod/Pregel/Conductor/ClusterWorkerApi.h
- arangod/Pregel/Conductor/Conductor.cpp
- arangod/Pregel/Conductor/Conductor.h
- arangod/Pregel/Conductor/States/ComputingState.cpp
- arangod/Pregel/GraphStore.cpp
- arangod/Pregel/NetworkConnection.cpp
- arangod/Pregel/NetworkConnection.h
- arangod/Pregel/PregelFeature.cpp
- arangod/Pregel/Utils.cpp
- arangod/Pregel/Utils.h
- arangod/Pregel/Worker/Worker.cpp
- arangod/Pregel/Worker/Worker.h
- arangod/Pregel/WorkerConductorMessages.h
Adds a general message (and a response) that includes an std::variant of different message types. This way, message handling in the feature becomes more readable: We can use the same Rest path for all message types and Feature::handleWorkerRequests delegates the decision what happens with the message to the worker. The worker does pattern matching (with std::visit) on the message type to decide what to do with which message type.
This PR uses this general messages only where we already use futures. A second PR will convert the rest.
> [PREGEL] Send general messages between worker and conductor

- arangod/IResearch/IResearchInvertedIndex.cpp
- arangod/IResearch/IResearchInvertedIndexMeta.cpp
- arangod/IResearch/IResearchInvertedIndexMeta.h
- arangod/IResearch/IResearchLinkMeta.h
- arangod/IResearch/IResearchRocksDBInvertedIndex.cpp
- arangod/IResearch/IResearchRocksDBInvertedIndex.h
- tests/IResearch/IResearchInvertedIndexMetaTest.cpp
> Make collection name available for inverted index on DBServer

- lib/Inspection/Format.h
- lib/Inspection/VPack.h
- tests/Basics/InspectionTest.cpp
* Adds `auto serialize(T& v) -> SharedSlice` for inspectable `T`.
* Adds `inspection_formatter` that allows explicit specialisation of `fmt::formatter` for types that are inspectable. This is inspired by the `ostream_formatter` from `fmt 9.1.0`.
* Requires `fmt-9.1.0` which is added in #17123 
The helper formats using the added `serialize` function and either `toJson` (not pretty) or `toString` (prettier) using format strings `{:u}` and `{:p}`.
```
struct Foo { uint32_t v; };
template<typename Inspector>
auto inspect(Inspector f, Foo& v) {
return f.object(v).fields(f.field("v", v.v));
}
template<>
struct fmt::formatter<Foo> : arangodb::inspection::inspection_formatter {};
fmt::print("A Foo: {}", Foo{.v = 15});
```
It is worth keeping in mind that every serialisation will create a …
> Inspector formatting (pedestrian #[derive(Debug)])

- lib/Basics/process-utils.cpp
ArangoDB is very trigger happy with blocking signals on startup by calling `maskAllSignals`; this propagates to children, and thus prevented me from running `ctest` from the `unittests` script.
This is an attempt at a fix: just `unmaskAllSignals` in the child after a fork.
> Allow children to have children

- CHANGELOG
- arangod/GeneralServer/H2CommTask.cpp
- arangod/GeneralServer/HttpCommTask.cpp
Backport of https://github.com/arangodb/arangodb/pull/17093
Fixes https://arangodb.atlassian.net/browse/BTS-1018
Previously, request logging did not work well for binary velocypack payloads. now, JSON and velocypack request payloads are properly logged if request logging is enabled. other binary payloads are logged as "potential binary data".
> BTS-1018: fix stringification of binary request payload (#17093)

- arangod/Aql/IResearchViewExecutor.cpp
- arangod/Aql/IResearchViewOptimizerRules.cpp
- arangod/IResearch/IResearchFilterFactory.cpp
- arangod/IResearch/IResearchFilterFactory.h
- arangod/IResearch/IResearchInvertedIndex.cpp
- arangod/IResearch/IResearchInvertedIndexMeta.cpp
- arangod/IResearch/IResearchLinkMeta.cpp
- arangod/IResearch/IResearchLinkMeta.h
- arangod/IResearch/Search.cpp
- tests/js/common/aql/aql-view-arangosearch-cluster.inc
- tests/js/common/aql/aql-view-arangosearch-noncluster.js
Use warnings instead of errors for search-alias views
> [SEARCH-396] Use warnings instead of errors for search-alias views

- CHANGELOG
- lib/Basics/process-utils.cpp
- lib/Basics/process-utils.h
This is a backport to 3.10 from devel.
This attacks the problem described in
https://arangodb.atlassian.net/browse/BTS-987
Namely, the usage of `rclone` is changed. We use
- `--include *.hash --include *.crc64ir` for bulk upload of empty hash files
- we batch not only small files, but all files
- we use `--files-from FILEWITHNAMES --no-traverse` for batches to make
use of parallelism in `rclone` and avoid remote directory listing
for each batch
These changes are in the accompanying enterprise PR: https://github.com/arangodb/enterprise/pull/1084
We need some changes in the main repository to improve error handling of
the rclone calls. Now, the standard error output of rclone is reported
back to `arangod` and thus the user.
There are also new tests.
This is a relatively local change
- [*] …
> Hotbackup up/download speedup - BTS-987

- arangod/Auth/UserManager.cpp
- arangod/RestServer/EnvironmentFeature.cpp
- lib/ApplicationFeatures/ConfigFeature.cpp
- lib/Basics/StringUtils.cpp
- lib/Basics/StringUtils.h
- lib/Endpoint/Endpoint.cpp
- lib/Logger/LoggerFeature.cpp
- lib/ProgramOptions/IniFileParser.cpp
- lib/Utilities/ShellBase.cpp
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/1088
Remove functions StringUtils::isPrefix and StringUtils::isSuffix, and replace them with std::string::starts_with and std::string_ends_with.
This will not be backported.
> remove StringUtils::isPrefix & StringUtils::isSuffix

- js/client/modules/@arangodb/testutils/crash-utils.js
- js/client/modules/@arangodb/testutils/result-processing.js
- scripts/examine_results.js
so far the reason to generate crashdumps would be ommitted after the rework.
- this adds it back into `testfailures.txt`
- saves it to the json structure and enables loading it
> test-infrastructure: put crashdump into json file; put reason string into crashinfo

- js/client/modules/@arangodb/testutils/crash-utils.js
- js/client/modules/@arangodb/testutils/result-processing.js
- scripts/examine_results.js
backport of https://github.com/arangodb/arangodb/pull/new/bug-fix-3.10/put-info-string-into-crashdump
> put crashdump into json file; put reason string into crashinfo (#17172)

- js/apps/system/_admin/aardvark/APP/frontend/js/templates/queryView.ejs
- js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
Backport of #17089
It is very difficult to find and remember the query a user has been saving recently. I added a checkbox (and the logic) to toggle sorting alphabetically and sorting by history (last query saved displayed first).
> [3.10][ES-1195] Add sorting by history

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/arango/arango.js
- js/apps/system/_admin/aardvark/APP/frontend/js/views/graphViewer.js
Backport of #17031
After clicking a node or an edge in the graph viewer the properties are displayed in blue tags underneath the canvas. With this PR on hover over these tags the values will be displayed in a tooltip.
> [3.10] APM-517: Show values upon hover on blue attribute labels

- .github/workflows/clang-format.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
> GitHub Workflows security hardening

- tests/js/client/shell/shell-collection-counts-cluster.js
- tests/js/client/shell/shell-dropped-followers-elcheapo-commit-cluster.js
- tests/js/client/shell/shell-following-term-id-cluster.js
These tests rely on specific behavior of the old replication protocol, so it makes so sense to run them with replication 2.
> [CINFRA-548] Disable collection-count tests for replication 2.0

- tests/CMakeLists.txt
- tests/Cache/LockStressTest.cpp
`Cache/LockStressTest.cpp` wasn't listed in CMakeLists.txt, and hence neither compiled nor run.
It was also broken.
> Activate and fix LockStressTest.cpp

- js/client/modules/@arangodb/testsuites/export.js
- Parameters weren't properly aligned
- specify proper timeouts
- no information connecting the result to the part of the log was printed
> BTS-1046: print test-info, correct invoking of exports

- js/client/modules/@arangodb/testsuites/gtest.js
- tests/CMakeLists.txt
- tests/Zkd/CMakeLists.txt
- tests/Zkd/Conversion.cpp
- tests/Zkd/main.cpp
Build a binary `arangodb_zkd` using its own `CMakeLists.txt`.
Also build in a way to run this binary via the unittests script;
The Zkd tests are intentionally not yet removed from the full blown `arangodbtests` executable until there is a reliable way to run separate test binaries on jenkins.
> [CMAKE] Build Zkd Test with its own CMakeLists.txt

- arangod/Aql/IndexExecutor.cpp
- tests/js/server/aql/aql-index-skip-regression.js
This fixes the `IndexExecutor` so that it skips as many rows as it can.
Before this patch the IndexExecutor only skipped once, leading to unpredictable skips and assertions being triggered in maintainer mode.
This bug should not have any impact on correctness of returned results, just on performance.
> [BTS-1043] Fix index executor

- arangod/Replication2/ReplicatedState/ReplicatedState.h
- arangod/Replication2/ReplicatedState/ReplicatedState.tpp
- arangod/VocBase/vocbase.cpp
- tests/Replication2/ReplicatedState/StateCleanupTest.cpp
Drop replicated states during database shutdown. Without this, a replicated state could be kept alive after the database is gone, possibly resulting in unexpected errors.
> Drop replicated states during database shutdown

- tests/js/client/shell/transaction/shell-transaction.js
- tests/js/server/replication2/replication2-supervision-replicated-log-target-cluster.js
Previously, we had to wait a second after each replication2 test, making sure that the collection is not deleted while the follower is still processing ongoing transactions. This wait is no longer needed, because the replicated state is now responsible for removing its own collection.
> Removing intentional sleep from tests

- CHANGELOG
- arangod/Replication/TailingSyncer.cpp
- tests/js/server/replication/ongoing/global/replication-ongoing-global.js
- tests/js/server/replication/ongoing/replication-ongoing.js
- tests/js/server/replication/static/replication-static.js
Fix issue https://arangodb.atlassian.net/browse/BTS-1036
Partial backport of https://github.com/arangodb/arangodb/pull/17177
* Fix an issue with replication of arangosearch view change entries in single server replication and active failover. Previously, when changing the properties of existing views, the changes were not properly picked up by followers in these setups. Cluster setups were not affected.
> Fix view properties change replication

- js/client/modules/@arangodb/testutils/crash-utils.js
This causes some tests to fail.
> Removing debuggerInfo dereference

- lib/Inspection/Format.h
- lib/Inspection/README.md
- lib/Inspection/Types.h
- lib/Inspection/VPackLoadInspector.h
- lib/Inspection/VPackSaveInspector.h
- lib/Inspection/detail/traits.h
- tests/Basics/InspectionTest.cpp
Adds the concept of variant "inline types" to the inspector. Inline types are types without a dedicated type field and are instead parsed by "trying" to parse each type. This is particularly useful for scalar types like string, int, etc.
> [Inspector] Add inline types for variants

- js/server/modules/@arangodb/testutils/aql-graph-traversal-generic-tests.js
Improve test execution performance by reducing amount of start nodes our parallelExecution test framework.
> improve test execution performance by limiting amount of startvertices

- arangod/Pregel/Conductor/Conductor.cpp
- arangod/Pregel/Conductor/Conductor.h
- arangod/Pregel/Conductor/States/CanceledState.cpp
- arangod/Pregel/Conductor/States/CanceledState.h
- arangod/Pregel/Conductor/States/ComputingState.cpp
- arangod/Pregel/Conductor/States/ComputingState.h
- arangod/Pregel/Conductor/States/DoneState.cpp
- arangod/Pregel/Conductor/States/DoneState.h
- arangod/Pregel/Conductor/States/FatalErrorState.cpp
- arangod/Pregel/Conductor/States/FatalErrorState.h
- arangod/Pregel/Conductor/States/StoringState.cpp
- arangod/Pregel/Conductor/States/StoringState.h
- arangod/Pregel/Conductor/WorkerApi.cpp
- arangod/Pregel/Conductor/WorkerApi.h
- arangod/Pregel/WorkerConductorMessages.h
This PR combines the worker apis into one api:
When we call the workers from the conductor, we send the same message to all workers (with one exception). This PR combines the worker apis into one api such that the conductor (or mostly the conductor states) don't have to manage sending the messages to the correct workers, but leave that to the worker api.
There is one exception: When loading the graph, we send different messages to each worker: Each worker gets a list of shards on its DBServer of the vertex and edge collections involved. The solution used here is not robust, it is fixed in the next PR: https://github.com/arangodb/arangodb/pull/17175.
I also made the run functions of the condcutor states better readable.
And I deleted the unused message interface inside …
> [PREGEL] Combine worker apis

- arangod/Pregel/AlgoRegistry.cpp
- arangod/Pregel/AlgoRegistry.h
- arangod/Pregel/Conductor/Conductor.cpp
- arangod/Pregel/Conductor/Conductor.h
- arangod/Pregel/Conductor/States/LoadingState.cpp
- arangod/Pregel/Conductor/States/LoadingState.h
- arangod/Pregel/Conductor/WorkerApi.cpp
- arangod/Pregel/Conductor/WorkerApi.h
- arangod/Pregel/Connection/Connection.h
- arangod/Pregel/Connection/DirectConnection.cpp
- arangod/Pregel/PregelFeature.cpp
- arangod/Pregel/Utils.cpp
- arangod/Pregel/Utils.h
- arangod/Pregel/Worker/Worker.cpp
- arangod/Pregel/Worker/Worker.h
- arangod/Pregel/Worker/WorkerConfig.cpp
- arangod/Pregel/Worker/WorkerConfig.h
- arangod/Pregel/WorkerConductorMessages.h
This PR separates the worker creation from the graph loading: This makes more clear what is happening: The conductor first asks to create the workers and only when this is successful the conductor asks the workers to load the graph.
Also, the payload to create workers is now a proper struct.
> [PREGEL] Separate worker creation from loading graph

- arangod/Pregel/Conductor/States/CanceledState.cpp
- arangod/Pregel/Conductor/States/ComputingState.cpp
- arangod/Pregel/Conductor/States/DoneState.cpp
- arangod/Pregel/Conductor/States/FatalErrorState.cpp
- arangod/Pregel/Conductor/States/LoadingState.cpp
- arangod/Pregel/Conductor/States/StoringState.cpp
- arangod/Pregel/Conductor/WorkerApi.h
- arangod/Pregel/WorkerConductorMessages.h
When a worker responds to a conductor request, the similar actions are executed, regardless of the request type that was send. Therefore, this PR moves these actions defined in the different conductor states to a single point: the Worker API.
After all workers responded back, the responses are first aggregated (via the new add function of the messages) and only the aggregate is given back to the conductor state where the conductor properties are changed depending on the aggregate.
This has several advantages:
- The states do not have to worry about responses from single workers, this is all handled inside the worker API
- The Worker API implements the NewIWorker interface
- The actions executed when workers respond back are now streamlined for all message types send by workers to the …
> [PREGEL] Aggregate response results

- arangod/Pregel/Algos/ShortestPath.cpp
- arangod/Pregel/Conductor/Conductor.cpp
- arangod/Pregel/Conductor/Conductor.h
- arangod/Pregel/Conductor/States/CanceledState.cpp
- arangod/Pregel/Conductor/States/ComputingState.cpp
- arangod/Pregel/Conductor/States/ComputingState.h
- arangod/Pregel/Conductor/States/StoringState.cpp
- arangod/Pregel/MasterContext.h
- arangod/Pregel/Statistics.h
- arangod/Pregel/VertexComputation.h
- arangod/Pregel/Worker/Worker.cpp
- arangod/Pregel/Worker/Worker.h
- arangod/Pregel/Worker/WorkerContext.h
- arangod/Pregel/WorkerConductorMessages.h
- tests/js/client/load-balancing/load-balancing-pregel-noauth-cluster.js
This PR deletes unused methods in the conductor and worker master contexts, most of them were remnants of async mode.
Additionally, I did some small changes: Fixed two brittle tests that failed on my machine (The algorithm is finished so fast that the status is already done when we query the pregel status where we assert that the status is still loading or running), Deleted another unused worker method and refactored a small part in the conductor computation state.
> [PREGEL] Delete unused master context methods

- CHANGELOG
- arangod/IResearch/Search.cpp
- js/common/modules/@arangodb/mocha-runner.js
- tests/js/client/authentication/auth-analyzer-view-integration.js
- tests/js/client/authentication/user-access-right-create-view-arangosearch-spec.js
- tests/js/client/authentication/user-access-right-drop-view-arangosearch-spec.js
- tests/js/client/authentication/user-access-right-read-view-arangosearch-spec.js
- tests/js/client/authentication/user-access-right-task-create-view-arangosearch-search-alias-spec.js
- tests/js/client/authentication/user-access-right-task-create-view-arangosearch-spec.js
- tests/js/client/authentication/user-access-right-task-drop-view-arangosearch-spec.js
- tests/js/client/authentication/user-access-right-task-read-view-arangosearch-spec.js
- tests/js/client/authentication/user-access-right-task-update-view-arangosearch.js
- tests/js/client/authentication/user-access-right-update-view-arangosearch.js
Previously, "search-alias" views were visible to users that didn't have read permissions on the underlying referenced collections. This was inconsistent, because "arangosearch" views weren't shown to users that didn't have read permissions on the underlying links. Now, the behavior for "search-alias" views is the same as for "arangosearch" views, i.e. "search-alias" views are not shown and are not accessible for users that don't have at least read permissions on the underlying collections.
> adjust permission checking of search-alias views

- js/client/modules/@arangodb/testutils/test-utils.js
impropper brackets would disable all tests from running under asan / tsan; this fixes that.
> add proper brackets to fix asan test

- arangod/RocksDBEngine/Listeners/RocksDBMetricsListener.cpp
- arangod/RocksDBEngine/Listeners/RocksDBMetricsListener.h
Log reason for RocksDB flushes to ArangoDB log file
> log reason for rocksdb flushes

- 3rdParty/README_maintainers.md
- 3rdParty/snappy/snappy-1.1.9/CMakeLists.txt
- lib/CMakeLists.txt
As an alternative to #17256 we could build snappy with RTTI and just keep our hands off these fragile games with mixing -fno-rtti code with -frtti.
Probably much more robust than the hack in #17256, except that the next update to snappy will break this again...
> Build Snappy with RTTI (and fix MacOS exceptions)

- lib/V8/v8-utils.cpp
If we try to acquired the process statistics of a no more rurnning process, we would run into a division by zero here.
This is mostly relevant to testing, since arangod running this on self has the warranty to acquire a running process.
> avoid possible division by zero if the process may not be running etc.

- js/client/modules/@arangodb/testutils/crash-utils.js
- js/client/modules/@arangodb/testutils/instance-manager.js
- js/client/modules/@arangodb/testutils/instance.js
- handle the state that arangoshs waitpid on killed arangod may output after the debugger terminating it
- improve messages so we better know which process we loop on
- reset pid of instance after its really gone
- check for instance being alive before trying to http-request it
- non-force shutdown only if all instances survived to the end of the test
> fix flow after shutdown by gdb; don't deadlock on gone instances

- tests/js/client/shell/shell-following-term-id-cluster.js
Disable shell-following-term-id-cluster tests when running with replication 2.0 since these are specific to the old replication protocol.
> Disable replication1 specific test for replication2

- Documentation/DocuBlocks/Rest/Indexes/post_api_index_inverted.md
- Documentation/DocuBlocks/Rest/Views/patch_api_view_properties_searchalias.md
- Documentation/DocuBlocks/Rest/Views/post_api_view_searchalias.md
- Documentation/DocuBlocks/Rest/Views/put_api_view_properties_searchalias.md
- Clarify inheritance of analyzer and features in inverted indexes
- `search-alias` Views accept index IDs (without collection prefix)
> Docs: ArangoSearch v2 corrections

- arangod/Aql/TraversalConditionFinder.cpp
Suppresses error message "Traversal optimizer encountered node: array filter" in maintainer mode (only) if an AQL query that contains a traversal also contains an array filter operator (`[? FILTER ...]`).
> suppress an error message in traversal condition finder

- arangod/Replication2/StateMachines/Document/DocumentStateHandlersFactory.cpp
This PR enables range deletes for truncate operations on followers. Before this, the followers always used remove operations, regardless of what the leader did.
> [CINFRA-579] Enabling range deletes on followers

- CHANGELOG
- arangod/RestServer/EnvironmentFeature.cpp
- lib/Basics/operating-system.h
- lib/Rest/Version.cpp
This fixes BTS 1061. On MAC and Linux ARM was not correctly recognised and not reported correctly in "--version".
> BTS-1061: fixed recoginition of ARM on Apple M1

- arangod/RestHandler/RestReplicationHandler.cpp
- arangod/Sharding/ShardingFeature.cpp
- arangod/Sharding/ShardingFeature.h
- arangod/VocBase/LogicalCollection.h
- tests/js/server/dump/dump-test.inc
Follow up PR related to: https://github.com/arangodb/arangodb/pull/16893
Info: We tried to optimize/generate non available sharding strategies at the wrong location.
Previous approach can lead to trouble in upgrade scenarios, e.g. (3.4 -> ... 3.10)
> Bug fix/enterprise graphs dump restore tests v2

- 3rdParty/fuerte/include/fuerte/message.h
- arangod/Network/Methods.cpp
```
fix warning about potentially uninitialized variable
In file included from arangod/Network/Methods.h:33,
from arangod/Network/Methods.cpp:24:
In copy constructor ‘arangodb::fuerte::v1::MessageHeader::MessageHeader(const arangodb::fuerte::v1::MessageHeader&)’,
inlined from ‘arangodb::fuerte::v1::ResponseHeader::ResponseHeader(const arangodb::fuerte::v1::ResponseHeader&)’ at 3rdParty/fuerte/include/fuerte/message.h:122:8,
inlined from ‘typename std::_MakeUniq<_Tp>::__single_object std::make_unique(_Args&& ...) [with _Tp = arangodb::fuerte::v1::Response; _Args = {arangodb::fuerte::v1::ResponseHeader&}]’ at /usr/include/c++/11/bits/unique_ptr.h:962:69,
inlined from ‘std::unique_ptr<arangodb::fuerte::v1::Response> arangodb::network::buildResponse(arangodb::fuerte::v1::StatusCode, const …
```
> fix warning about potentially uninitialized variable

- CHANGELOG
- arangod/Cluster/ServerState.cpp
Usability improvements for cluster start problems diagnosis.
If upon cluster instance start, it is detected that two servers use the same endpoint (IP address), a warning message was logged. This warning message only mentioned one of the servers of the duplicate pair, but not both. 
With this PR, both servers will be mentioned in the error message, and the full endpoints configuration is also logged in addition for better diagnosis.
Before:
```
WARNING [9a134] {cluster} found duplicate server entry for endpoint 'tcp://[::1]:8629', already used by other server CRDN-9343808f-98fc-4409-a64e-3d4a49d65f3d. it looks like this is a (mis)configuration issue
```
After:
```
WARNING [9a134] {cluster} found duplicate server entry for endpoint 'tcp://[::1]:8629' when processing endpoints configuration …
```
> log extra diagnosis data when duplicate endpoints are configured

- tests/IResearch/IResearchQueryCommon.h
Add parameter for viewName in checkView method
> Added default parameter to checkView

- arangod/Replication/DatabaseInitialSyncer.cpp
- arangod/RestHandler/RestReplicationHandler.cpp
Because the Ranges protocol can now return only-HLC encoded values, the follower should react on that.
> ad-hoc fix for BTS-1073 improvement

- arangod/Aql/AqlTransaction.cpp
- arangod/Aql/AqlTransaction.h
- arangod/Aql/BlocksWithClients.cpp
- arangod/Cluster/TraverserEngine.cpp
- arangod/Graph/BaseOptions.cpp
Allow passing transaction::Context shared_ptr as rvalue reference when creating an AqlTransaction instance.
In the best case, this saves an atomic value update. In the worst case, it doesn't change anything.
> allow rvalue contexts when creating AqlTransaction

- CHANGELOG
- arangod/RocksDBEngine/RocksDBEngine.cpp
- tests/js/client/server_parameters/wal-archive-size-limit-large-noncluster.js
- tests/js/client/server_parameters/wal-archive-size-limit-small-noncluster.js
Fixed issue https://arangodb.atlassian.net/browse/ES-1312
Fix handling of reaching the WAL archive capacity limit.
> ES-1312: fix handling of reaching WAL archive capacity limit

- 3rdParty/fuerte/src/H1Connection.cpp
- CHANGELOG
- Documentation/DocuBlocks/Rest/Collections/get_api_collection_revision.md
- arangod/Cluster/ClusterMethods.cpp
- arangod/GeneralServer/HttpCommTask.cpp
- arangod/GeneralServer/VstCommTask.cpp
- arangod/Replication/DatabaseInitialSyncer.cpp
- arangod/Replication/utilities.cpp
- arangod/Replication/utilities.h
- arangod/RestHandler/RestCollectionHandler.cpp
- arangod/RestHandler/RestGraphHandler.cpp
- arangod/RestHandler/RestReplicationHandler.cpp
- arangod/RestHandler/RestVocbaseBaseHandler.cpp
- arangod/StorageEngine/PhysicalCollection.cpp
- arangod/Transaction/Helpers.cpp
- arangod/V8Server/v8-util.cpp
- arangod/VocBase/Identifiers/RevisionId.cpp
- arangod/VocBase/Identifiers/RevisionId.h
- lib/Basics/HybridLogicalClock.h
- lib/Basics/StaticStrings.cpp
- lib/Basics/StaticStrings.h
- lib/Containers/MerkleTree.cpp
- lib/Rest/HttpRequest.cpp
- lib/Rest/Version.cpp
- lib/Rest/Version.h
- tests/Basics/HybridLogicalClockTest.cpp
- tests/CMakeLists.txt
- tests/Containers/MerkleTreeTest.cpp
- tests/Rest/HttpRequestTest.cpp
- tests/js/server/replication/sync/replication-sync-malarkey.js
Backport of https://github.com/arangodb/arangodb/pull/17310
Fixes BTS-1073: https://arangodb.atlassian.net/browse/BTS-1073
* Fix encoding and decoding of revision ids in replication incremental sync protocol. Previously, the encoding of revision ids could be ambiguous under some circumstances when sending them to the `/_api/replication/ranges` leader API endpoint, which could prevent shards from getting into sync. The fix is validated by a new test suite.
* Fixed parsing of empty URL parameters in incoming HTTP requests, which previously produced a wrong result. For example, sending `?a=b&c=&d=e` produced `["a":"b", "c": "&d", "d":"e" ]` (i.e. the value of `c` was wrong). The fix is validated by new tests.
* Fixed aborting the server process if an exception was thrown in C++ code that was …
> BTS-1073: Fix revision ids in replication

- arangod/IResearch/IResearchFilterFactory.cpp
- arangod/IResearch/IResearchKludge.cpp
- arangod/IResearch/IResearchKludge.h
- tests/IResearch/ExpressionFilterTest.cpp
- tests/IResearch/GeoDistanceFilterTest.cpp
- tests/IResearch/GeoFilterTest.cpp
- tests/IResearch/IResearchFilterFunctionTest.cpp
- tests/IResearch/IResearchFilterNestedTest.cpp
- tests/IResearch/IResearchViewTest.cpp
- tests/IResearch/common.cpp
* Fix handling of ALL quantifier for boolean expansion for views.
* Allow `EXISTS` function to check presence of nested fields.
* Allow using ALL quantifier for arangosearch views.
> [SEARCH-407] [SEARCH-405] [SEARCH-404] Fix handling of ALL quantifier 

- 3rdParty/iresearch/core/index/index_writer.cpp
- 3rdParty/iresearch/core/index/segment_writer.cpp
- 3rdParty/iresearch/core/index/segment_writer.hpp
- tests/IResearch/IResearchView-test.cpp
Fix handling of removals in presence of primary sort
> [SEARCH-406] Fix handling of removals in presence of primary sort

- arangod/Pregel/Conductor/Conductor.cpp
- arangod/Pregel/Conductor/States/ComputingState.cpp
- arangod/Pregel/Conductor/States/ComputingState.h
- arangod/Pregel/Conductor/WorkerApi.cpp
- arangod/Pregel/Conductor/WorkerApi.h
- arangod/Pregel/Messaging/WorkerMessages.h
- arangod/Pregel/PregelFeature.cpp
- arangod/Pregel/Worker/Worker.cpp
- arangod/Pregel/Worker/Worker.h
This PR tidies up the Computing state:
- Inside the conductor Computing state, it adjusts the code order to the actual execution order, thus making it more readable: For each superstep (gss) there is first a preGss action on the conductor side, then data is exchanged with the workers when first preparing the gss and then running the gss and finally a postGss action is executed on the conductor.
- It merges the prepareGss and runGss message send from the conductor to the workers into a single message from conductor to workers. 
Before, the prepareGss message was used as a synchronization point: It made sure that each worker got the new gss number and exchanged its read and write cache before the real computation (initiated with the runGss message) started. 
Now we don't have this …
> [PREGEL] Combine prepare and run superstep

- CHANGELOG
- arangod/Cluster/SynchronizeShard.cpp
- arangod/Cluster/SynchronizeShard.h
Log documents counts from leader and follower at the end of each successful shard synchronization.
> log document counts in replication

- CHANGELOG
- arangod/Aql/ExecutionNode.cpp
- tests/js/server/aql/aql-optimizer-rule-remove-sort-rand-limit.js
* Improve cardinality estimate for AQL EnumerateCollectionNode in case a `SORT RAND() LIMIT 1` is used. Here, the estimated number of items is at most 1.
> improve estimate for EnumerateCollectionNode

- js/common/modules/@arangodb/arango-collection-common.js
To celebrate the **10th anniversary** of this bug, let's fix it so that we can actually show how the `collection.iterate()` method works in the documentation 🎉 
- `db` is undefined despite the `require("@arangodb").db` import
- higher probability values make it less likely to pick a document  (unless it's >= 1.0)
Commit from January 2013 that added the code (and example): https://github.com/arangodb/arangodb/commit/9c87607f461a34e20fd1c62123e107f166b58e3a
I think we can ignore all of the below because no one noticed until Chris found the confusing example in the docs this year.
I manually tested the fix in `arangosh` and `arangod --console`.
> JS API: Fix undefined reference and logic of collection.iterate()

- arangod/Pregel/Conductor/Conductor.cpp
- arangod/Pregel/Conductor/Conductor.h
- arangod/Pregel/Conductor/States/ComputingState.cpp
- arangod/Pregel/Conductor/States/ComputingState.h
- arangod/Pregel/Conductor/WorkerApi.cpp
- arangod/Pregel/Conductor/WorkerApi.h
- arangod/Pregel/Messaging/ConductorMessages.h
- arangod/Pregel/Messaging/WorkerMessages.h
- arangod/Pregel/OutgoingCache.cpp
- arangod/Pregel/OutgoingCache.h
- arangod/Pregel/Worker/Worker.cpp
- arangod/Pregel/Worker/Worker.h
The previous PR #17332 merges the prepareGss and runGss message send from the conductor to the workers into a single message from conductor to workers. It turned out that when running the pregel tests several times in cluster mode, not all messages were delivered. We never check inside the Worker that for every superstep all send messages are also received. Before merging the two messages, there was possibly enough time to deliver all messages, but now this missing check results sometimes in wrong results.
This PR fixes this: In the worker - or more exact in the OutCache - we have a counter for each send message in a gss. When the worker is finished with its gss, it send this count back to the conductor - more exact the ComputingState. In the next gss, the Computing states sends to each …
> [PREGEL] Wait until Worker received all messages that were sent to it

- arangod/Pregel/Conductor/Conductor.cpp
- arangod/Pregel/Conductor/Conductor.h
- arangod/Pregel/Conductor/States/ComputingState.cpp
- arangod/Pregel/Conductor/States/ComputingState.h
- arangod/Pregel/Conductor/States/LoadingState.cpp
- arangod/Pregel/Conductor/WorkerApi.cpp
- arangod/Pregel/Conductor/WorkerApi.h
- arangod/Pregel/PregelFeature.cpp
- arangod/Pregel/Worker/ConductorApi.cpp
- arangod/Pregel/Worker/ConductorApi.h
- arangod/Pregel/Worker/Worker.cpp
- arangod/Pregel/Worker/Worker.h
This PR continues the refactoring to use the actor model for communication between conductor and workers (see previous PR https://github.com/arangodb/arangodb/pull/17280)
This adapts the communication in the computation state: sending RunGlobalSuperstep from Conductor to Workers and GlobalSuperStepFinished from Workers to Conductor.
> [PREGEL] Separate sending and receiving messages to run gss

- arangod/Pregel/Conductor/States/CanceledState.cpp
- arangod/Pregel/Conductor/States/CanceledState.h
- arangod/Pregel/Conductor/States/StoringState.cpp
- arangod/Pregel/Conductor/States/StoringState.h
- arangod/Pregel/Conductor/WorkerApi.cpp
- arangod/Pregel/Conductor/WorkerApi.h
- arangod/Pregel/PregelFeature.cpp
- arangod/Pregel/PregelFeature.h
- arangod/Pregel/Worker/Worker.cpp
- arangod/Pregel/Worker/Worker.h
This PR continues the refactoring to use the actor model for communication between conductor and workers (see initial PR https://github.com/arangodb/arangodb/pull/17280): This adapts the communication when cleaning up the Workers (in Storing and Canceled state): sending Cleanup from Conductor to Workers and CleanupFinished from Workers to Conductor.
> Separate sending and receiving messages when cleaning up

- js/common/modules/@arangodb/testutils/replicated-logs-predicates.js
This missing condition affects the `testTransactionLeaderChangeBeforeCommit` test from `shell-transaction-cluster.js`. It is possible that no leader exchange occurred since we bumped the term, thus the test fails.
> [CINFRA-586] Leader Change Test Fix

- arangod/Replication2/ReplicatedState/FollowerStateManager.tpp
- arangod/Replication2/ReplicatedState/LeaderStateManager.tpp
- arangod/Replication2/StateMachines/Document/DocumentFollowerState.cpp
- arangod/Replication2/StateMachines/Document/DocumentLeaderState.cpp
- arangod/Replication2/StateMachines/Document/DocumentStateHandlersFactory.cpp
This serves as a temporary fix. If the vocbase has been already dropped, we return instead of causing the dbserver to stop. The replicated state is about to be destroyed anyway.
> [CINFRA-588] Document State vocbase race

- client-tools/Restore/RestoreFeature.cpp
- client-tools/Restore/RestoreFeature.h
Remove sending unused URL parameter "useEnvelope" from arangorestore. The parameter was sent to an API that doesn't process it.
> remove unused URL parameter "useEnvelope"

- arangod/Pregel/Conductor/Conductor.cpp
- arangod/Pregel/Conductor/States/CanceledState.h
- arangod/Pregel/Conductor/States/ComputingState.cpp
- arangod/Pregel/Conductor/States/ComputingState.h
- arangod/Pregel/Conductor/States/DoneState.cpp
- arangod/Pregel/Conductor/States/DoneState.h
- arangod/Pregel/Conductor/States/FatalErrorState.cpp
- arangod/Pregel/Conductor/States/FatalErrorState.h
- arangod/Pregel/Conductor/States/InitialState.h
- arangod/Pregel/Conductor/States/LoadingState.cpp
- arangod/Pregel/Conductor/States/LoadingState.h
- arangod/Pregel/Conductor/States/State.h
- arangod/Pregel/Conductor/States/StoringState.cpp
- arangod/Pregel/Conductor/States/StoringState.h
This PR is a preparation of the coming PR: It makes the conductor states responsible to change into the Cancel state by adding a function cancel to the state machine.
> [PREGEL]: Add cancel function to state machine

- arangod/Pregel/Conductor/States/ComputingState.cpp
- arangod/Pregel/Conductor/States/LoadingState.cpp
- arangod/Pregel/Conductor/WorkerApi.h
- arangod/Pregel/Worker/Worker.cpp
When sending messages from conductor to workers via worker api: Wrap lock around both future creation and getting the future because it is not defined when the future will resolve.
Additionally, improve some logging.
> [PREGEL] Bugfix: Lock future creation

- CHANGELOG
- arangod/Aql/Query.cpp
- arangod/Aql/Query.h
- arangod/Aql/QueryContext.h
- arangod/Aql/QueryList.cpp
- arangod/Aql/QueryList.h
- arangod/Aql/QueryProfile.h
- arangod/Aql/QueryString.cpp
- arangod/Graph/BaseOptions.cpp
- arangod/Graph/BaseOptions.h
- arangod/Indexes/IndexIterator.cpp
- arangod/Indexes/IndexIterator.h
- arangod/RestServer/QueryRegistryFeature.cpp
- arangod/RestServer/QueryRegistryFeature.h
- arangod/RocksDBEngine/RocksDBVPackIndex.cpp
- tests/js/client/server_parameters/log-queries-failed-and-memory.js
This is a cherry-picking exercise for a special bugfix release 3.9.4.1.
It takes in the following two changes, which will be in 3.9.5, but are
not yet in 3.9.4:
- Prevent excessive memory use in multi index iterator.
- Better logging for high memory consuming or failed queries.
- [*] Bugfix
- [*] Better logging and control of logging
- [*] Tests
- [*] GitHub issue / Jira ticket: https://arangodb.atlassian.net/browse/BTS-1088
> Prevent excessive memory usage in multi iterator and better logging for high mem queries

- lib/ProgramOptions/Parameters.cpp
Avoid a static init order fiasco.
This change has already been made in other versions before.
> avoid static init order fiasco (#17114)

- arangod/RestServer/DatabaseFeature.cpp
During shutdown, only open databases were stopped, while dropped databases were left running. This lead to problems (in a WIP replication 2 branch), because the databases and its still running jobs were only stopped during `unprepare`, at which point the Scheduler already stopped.
> Stop dropped databases as well

- arangod/Replication2/Methods.cpp
- arangod/Replication2/Methods.h
- arangod/Replication2/ReplicatedLog/ILogInterfaces.h
- arangod/Replication2/ReplicatedLog/LogFollower.cpp
- arangod/Replication2/ReplicatedLog/LogFollower.h
- arangod/Replication2/ReplicatedLog/LogLeader.cpp
- arangod/Replication2/ReplicatedLog/LogLeader.h
- arangod/Replication2/ReplicatedLog/LogUnconfiguredParticipant.cpp
- arangod/Replication2/ReplicatedLog/LogUnconfiguredParticipant.h
- arangod/RestHandler/RestLogHandler.cpp
- arangod/RestHandler/RestLogHandler.h
- arangod/V8Server/v8-replicated-logs.cpp
- js/client/modules/@arangodb/replicated-logs.js
- tests/Replication2/Mocks/AsyncFollower.cpp
- tests/Replication2/Mocks/AsyncFollower.h
- tests/Replication2/Mocks/AsyncLeader.cpp
- tests/Replication2/Mocks/AsyncLeader.h
- tests/Replication2/Mocks/FakeFollower.h
- tests/Replication2/Mocks/FakeLeader.h
- tests/Replication2/Mocks/FakeReplicatedLog.h
- tests/js/common/shell/shell-replicated-logs-cluster.js
This PR adds an explicit `compact` API. When this api is called, all participants compact as many log entries as possible. Compaction might be blocked by the state machine. 
If called on a coordinator, the request is forwarded to all participants.
> Add an explicit compact API call for logs.

- CMakePresets.json
This PR adds `CMakePresets` which can be used to share settings for building ArangoDB between platforms and developers and make for a consistent build environment.
Example use
```
Available configure presets:
"community"                       - Build ArangoDB Community Edition
"enterprise"                      - Build ArangoDB Enterprise Edition
"community-developer"             - Build ArangoDB Community Edition (Developer Build)
"enterprise-developer"            - Build ArangoDB Enterprise Edition (Developer Build)
"community-developer-tsan"        - Build ArangoDB Community Edition (TSAN Build)
"enterprise-developer-tsan"       - Build ArangoDB Enterprise Edition (TSAN Build)
"community-developer-asan-ubsan"  - Build ArangoDB Community Edition (ASAN and UBSAN Build) …
```
> [BUILD] Add CMakePresets.json

- CHANGELOG
- arangod/Aql/AttributeNamePath.cpp
- arangod/Aql/AttributeNamePath.h
- arangod/Aql/Projections.cpp
- arangod/Aql/Projections.h
- arangod/Indexes/Index.cpp
- arangod/RocksDBEngine/RocksDBOptimizerRules.cpp
- tests/Aql/ProjectionsTest.cpp
- tests/js/common/shell/shell-index-stored-values.js
- tests/js/server/aql/aql-filter-projections.js
- tests/js/server/aql/aql-projections.js
Fixed issue #17394: Unnecessary document-lookup instead of Index-Only query. This change improves projection handling so that more projections can be served from indexes.
This also required a few adjustments of existing tests. From the test adjustments it can be seen that now we can serve projections from indexes in more cases than before.
> Fixed issue #17394

- tests/js/common/shell/shell-replicated-logs-cluster.js
This PR changes the configuration of a test, which could fail from time to time due to a race.
After compaction, we expected the `firstIndex` of the log to be the highest possible. Because `compactionStop` is calculated as `min(lowestIndexToKeep, releaseIndex)` and `lowestIndexToKeep` depends on the last acknowledged commit index of all followers, WC is now set to 3, so we make sure that all followers have the entire log, which allows us to run full compaction.
> [CINFRA-593] Compaction Test Fix

- lib/CMakeLists.txt
Right now this doesn't provide any benefits, but it will allow linking things to arango_static_strings in the future without having to link to everything else in `lib`.
> move StaticStrings into a library of its own

- arangod/RestHandler/RestDocumentStateHandler.cpp
Remove always-true subcondition.
Fixes compile warning
``` 
arangod/RestHandler/RestDocumentStateHandler.cpp: In member function ‘arangodb::RestStatus arangodb::RestDocumentStateHandler::handleGetSnapshot(const arangodb::replication2::DocumentStateMethods&, arangodb::replication2::LogId)’:
arangod/RestHandler/RestDocumentStateHandler.cpp:91:67: warning: comparison of unsigned expression in ‘< 0’ is always false [-Wtype-limits]
91 |   if (!waitForIndexParam.has_value() || waitForIndexParam.value() < 0) {
|                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
```
> remove always-true subcondition

- CHANGELOG
- arangod/Aql/OptimizerRules.cpp
- tests/js/server/aql/aql-optimizer-collect-count.js
- tests/js/server/aql/aql-optimizer-rule-collect-in-cluster.js
Enable "collect-in-cluster" optimizer rule for SmartGraph edge collections, too.
Previously SmartGraph edge collections were excluded from the optimization because they report to have 0 shards.
> Enable "collect-in-cluster" optimizer rule for SmartGraph edge collections

- arangod/Replication2/Methods.cpp
- arangod/Replication2/Methods.h
- arangod/Replication2/ReplicatedLog/ILogInterfaces.h
- arangod/Replication2/ReplicatedLog/LogEntries.cpp
- arangod/Replication2/ReplicatedLog/LogEntries.h
- arangod/Replication2/ReplicatedLog/LogLeader.cpp
- arangod/Replication2/ReplicatedLog/LogLeader.h
- arangod/RestHandler/RestLogHandler.cpp
- arangod/RestHandler/RestLogHandler.h
- arangod/V8Server/v8-replicated-logs.cpp
- js/client/modules/@arangodb/replicated-logs.js
- tests/Replication2/Mocks/AsyncLeader.h
- tests/Replication2/Mocks/FakeLeader.h
- tests/js/common/shell/shell-replicated-logs-cluster.js
- tests/js/server/replication2/replication2-replicated-log-entry-cluster.js
This PR adds a new `ping` function on a replicated log. This function inserts an meta log entry and is designed for debugging. It does not interfere with the state machine based on the replicated log. The javascript function accepts an optional string parameter `message` that is put into the ping log entry. The rest handler optionally accepts an object with key `message`.
> [CINFRA] Ping Replicated Log

- tests/js/client/active-failover/basic.js
- tests/js/client/active-failover/readonly.js
test would run code outside of regular test plans, and hence produce broken results. Move code to `setUpAll`.
> test must not assert during test setup to get proper results!

- tests/test-definitions.txt
this comment of the test-defitions.txt was left over from a previous development stage.
>  [testing][documentation] fix link to the oskar documentation

- lib/Basics/files.cpp
Fix BTS-944: https://arangodb.atlassian.net/browse/BTS-944
Fix disk space metrics `rocksdb_free_disk_space` and `rocksdb_total_disk_space` on macOS. Previously, they seem to have reported wrong values.
> BTS-944: fix disk space metrics on macOS

- CHANGELOG
- js/common/modules/@arangodb/aql/explainer.js
Backport of https://github.com/arangodb/arangodb/pull/17538
Show number of HTTP requests in cluster query profiles
> Show number of HTTP requests in cluster query profiles.

- arangod/Pregel/Algos/DMID/DMIDMessageFormat.h
- arangod/Pregel/Algos/DMID/VertexSumAggregator.h
- arangod/Pregel/CommonFormats.h
- arangod/Pregel/Worker/GraphStore.cpp
- arangod/Pregel/Worker/WorkerConfig.cpp
Cast PregelShard input explicitly to uint16_t to fix windows build that treats this as an error
> [PREGEL] Cast PregelShard input explicitly to uint16_t

- js/client/modules/@arangodb/testsuites/resilience.js
don't spawn sub-shell for running the tests
> [testing] don't spawn test in its own arangosh

- js/client/modules/@arangodb/arango-database.js
- js/server/modules/@arangodb/arango-database.js
Previously, `db._profileQuery(...)` only accepted positional parameters. This is in contrast to `db._query(...)` and `db._explain(...)`, which both accept positional parameters and named parameters inside an object input parameter.
With this PR, one can now do:
db._profileQuery(queryString, bindVars, options);
as well as
db._profileQuery({ query: queryString, bindVars: bindVars, options: options });
This PR also fixes the issue that profiling modifies the `options` input parameter, so that when it is used for multiple calls, it is not treated as const.
> fix handling of parameters for `db._profileQuery(object)`

- arangod/Agency/Job.cpp
Fix compile warnings with g++-11.3
``` 
[ 89%] Building CXX object arangod/Agency/CMakeFiles/arango_agency.dir/Job.cpp.o
/home/jan/ArangoDevel/arangod/Agency/Job.cpp: In static member function ‘static std::optional<arangodb::replication2::replicated_state::agency::Target> arangodb::consensus::Job::readStateTarget(const arangodb::consensus::Node&, const string&, arangodb::replication2::LogId)’:
/home/jan/ArangoDevel/arangod/Agency/Job.cpp:1171:19: warning: redundant move in return statement [-Wredundant-move]
1171 |   return std::move(target);
|          ~~~~~~~~~^~~~~~~~
/home/jan/ArangoDevel/arangod/Agency/Job.cpp:1171:19: note: remove ‘std::move’ call
/home/jan/ArangoDevel/arangod/Agency/Job.cpp: In static member function ‘static …
```
> fix compile warnings with g++-11.3

- arangod/RestServer/EnvironmentFeature.cpp
Print CPU and RAM info on non-mac systems, too at startup.
Previously the information was only printed out for Linux, because the code was located inside an ifdef.
> print CPU and RAM info on non-mac systems, too

- 3rdParty/CMakeLists.txt
- tests/CMakeLists.txt
- tests/Replication2/CMakeLists.txt
Builds gtest directly using cmake without going through a custom bit of CMake code.
> Build googletest like CMake exists

- CHANGELOG
- arangod/IResearch/IResearchFeature.h
- arangod/IResearch/IResearchLinkHelper.cpp
- arangod/IResearch/IResearchLinkHelper.h
- arangod/IResearch/IResearchView.h
- arangod/IResearch/IResearchViewCoordinator.h
- arangod/IResearch/IResearchViewMeta.cpp
- arangod/IResearch/IResearchViewMeta.h
- tests/IResearch/IResearchIndex-test.cpp
- tests/IResearch/IResearchViewMeta-test.cpp
- tests/js/common/aql/aql-view-arangosearch-ddl.js
Fixes handling of primarySortCache and primaryKeyCache properties
Enterprise PR: https://github.com/arangodb/enterprise/pull/1146
> Bug-fix 3.9 BTS-1125

- CHANGELOG
- arangod/Aql/Functions.cpp
- tests/js/server/aql/aql-document.js
Backport of https://github.com/arangodb/arangodb/pull/17566/
Fixes https://arangodb.atlassian.net/browse/BTS-1075
BTS-1075: unify behavior of DOCUMENT() function with empty keys
> BTS-1075: unify behavior of DOCUMENT() function with empty keys

- js/client/modules/@arangodb/testsuites/rta_makedata.js
- js/client/modules/@arangodb/testutils/testrunner.js
Developers may want to filter testcases in makedata / checkdata; This implements the testing.js side to support this
Related: https://github.com/arangodb/release-test-automation/pull/303
> [testing] Feature/test filtering for rta make checkdata

- CHANGELOG
- arangod/Aql/ExecutionPlan.cpp
- arangod/Aql/Expression.cpp
- arangod/Aql/Expression.h
- tests/js/common/aql/aql-prune-expressions.js
- tests/js/server/aql/aql-prune-expressions.js
Fix issue #17291 
Traversal PRUNE expressions containing JavaScript user-defined functions (UDFs) are now properly rejected in single server and cluster mode. PRUNE expressions that use UDFs require a V8 context for execution, which is not available on DB-servers in a cluster, and also isn't necessarily available for regular queries on single servers (a V8 context is only available if such query was executed inside Foxx or from inside a JS transaction, but not otherwise).
> fixed issue #17291

- CHANGELOG
- arangod/RestServer/EnvironmentFeature.cpp
- arangod/RestServer/arangod.h
- arangod/RestServer/arangod_includes.h
- client-tools/Backup/arangobackup.cpp
- client-tools/Benchmark/arangobench.cpp
- client-tools/Dump/arangodump.cpp
- client-tools/Export/arangoexport.cpp
- client-tools/Import/arangoimport.cpp
- client-tools/Restore/arangorestore.cpp
- client-tools/Shell/arangosh.cpp
- client-tools/Utils/ArangoClient.h
- client-tools/VPack/arangovpack.cpp
- client-tools/VPack/arangovpack.h
- lib/ApplicationFeatures/ApplicationServer.cpp
- lib/ApplicationFeatures/OptionsCheckFeature.cpp
- lib/ApplicationFeatures/OptionsCheckFeature.h
- lib/CMakeLists.txt
- tests/js/server/recovery/check-warnings-exitzero.js
Centralize checking options in new ApplicationFeature.
This is a new central place that can be used to check all startup options for appropriateness, e.g.
* if an option is obsolete
* if an option is deprecated
* if an option is experimental
* if an option is renamed
> centralize options checks in new ApplicationFeature

- CHANGELOG
- arangod/Aql/QueryOptions.cpp
- tests/js/client/server_parameters/test-memory-limit.js
Backport of https://github.com/arangodb/arangodb/pull/17613
* Fix setting query memory limit to 0 for certain queries if a global memory limit is set, but overriding the memory limit is allowed.
> Fix setting query memory limit to 0 (unbounded)

- js/client/modules/@arangodb/testsuites/dump.js
we would recently see servers fail during asan dump_with_crashes runs. 
However, logfiles would be cleared, hence no post mortem analysis of the incident would be possible.
This PR will check the server health and turn the status to bad if the server is gone.
> [testing]if after a restore attempt the server isn't healthy anymore properly abort the test so we don't clean up

- arangod/IResearch/AqlHelper.cpp
- tests/js/server/aql/aql-inverted-index.js
Fixes SEARCH-427 by ensuring that trackListPositions enabled field is not used in FILTER coverage
Enterprise PR: https://github.com/arangodb/enterprise/pull/1151
> SEARCH-427 fix and test

- CHANGELOG
- arangod/GeneralServer/AuthenticationFeature.cpp
`--server.disable-authentication-unix-sockets` and `--server.disable-authentication` were deprecated in v3.0 and mapped to `--server.authentication` and `--server.authentication-unix-sockets`, which made them do the opposite of what their names suggest. It's time to remove them.
> Make two deprecated `--server.disable-authentication*` server startup options obsolete

- lib/V8/v8-environment.cpp
- tests/test-definitions.txt
Fixes reading environment variable for windows.
First attempt is made via static 8k buffer. And only if it is not enough dynamic allocation is made.
> Fix v8 environment variable buffer overrun 

- arangod/RocksDBEngine/ReplicatedRocksDBTransactionCollection.cpp
- arangod/RocksDBEngine/ReplicatedRocksDBTransactionState.cpp
- arangod/Transaction/Methods.cpp
In case the leader resigns while inside `replicateOperation`, accessing the stream will throw an exception. This is now handled by all callers of this method, which was pretty easy to implement since all of them already return some type of `Result`.
For the `doCommit`, we need a `ScopeGuard` that makes sure all ongoing futures are resolved before returning from the function. This is because the underlying `TransactionCollection`'s are captured by reference and might not be around when the `thenValue` is executed.
> [CINFRA-613] Leader stream can throw in replicateOperation

- js/client/modules/@arangodb/testsuites/replication.js
- tests/test-definitions.txt
This test runs very long, hence start it from the very beginning, so it doesn't run alone (up to 10 minutes observed in runs) wasting machine time. 
However, its only launched 30s in, try to split it by buckets - though its only 2 suites
Needed to add splitter code to the suite.
> [testing] the replication sync test takes very long, launch it right at the start

- Documentation/DocuBlocks/Rest/Views/post_api_view_arangosearch.md
> DOC-266 | Documentation 3.9/arangosearch column cache

- Documentation/DocuBlocks/Rest/Indexes/post_api_index_inverted.md
- Documentation/DocuBlocks/Rest/User Management/README.md
- Documentation/DocuBlocks/Rest/Views/post_api_view_arangosearch.md
Backport of https://github.com/arangodb/arangodb/pull/17683
Forward port of https://github.com/arangodb/arangodb/pull/17603, plus ArangoSearch caching options for inverted indexes
> DOC-266 | Documentation 3.10/arangosearch column cache

- tests/Replication2/CMakeLists.txt
- tests/test-definitions-rlog.txt
- tests/test-definitions.txt
Due to a previous change, the separate arangodb replication2 tests were not build. This PR fixes that.
> [CINFRA] Fixing CI

- CHANGELOG
- Documentation/Metrics/arangodb_client_connection_statistics_bytes_received.yaml
- Documentation/Metrics/arangodb_client_connection_statistics_bytes_sent.yaml
- Documentation/Metrics/arangodb_client_user_connection_statistics_bytes_received.yaml
- Documentation/Metrics/arangodb_client_user_connection_statistics_bytes_sent.yaml
- arangod/Statistics/StatisticsFeature.cpp
- tests/js/client/shell/traffic/shell-check-metrics-move-noncluster.js
This addresses https://arangodb.atlassian.net/browse/BTS-1133
We need user only request traffic accounting, which is so far 
only in `/_admin/statistics` and not in metrics.
* Add missing metrics for user traffic: Histograms:
`arangodb_client_user_connection_statistics_bytes_received`
`arangodb_client_user_connection_statistics_bytes_sent`
These numbers were so far only published via the statistics API.
This is needed for Oasis traffic accounting.
- [*] Backport for 3.8: This is the backport for 3.8
- [*] GitHub issue / Jira ticket: …
> Add missing metrics for traffic accounting - BTS-1133

- js/client/modules/@arangodb/testutils/instance.js
Currently tests will fail when passing the `--rr true` argument to `unittest`: `2022-12-01T11:15:15Z [13119] INFO [24783] {general} created database directory '[object Object]'`
This PR fixes the command line arguments passed to arangod, when rr is used.
> Fixing rr debugger arguments

- CHANGELOG
- arangod/Agency/Job.cpp
- arangod/Agency/Job.h
- arangod/Agency/MoveShard.cpp
- arangod/Agency/MoveShard.h
- arangod/Agency/ResignLeadership.cpp
- arangod/Agency/ResignLeadership.h
- arangod/Agency/Supervision.cpp
- arangod/Agency/Supervision.h
- arangod/RestHandler/RestAdminClusterHandler.cpp
- arangod/RestHandler/RestAdminClusterHandler.h
- tests/Agency/MoveShardTest.cpp
- tests/Agency/MoveShardTest.json
- tests/js/server/resilience/move/moving-shards-cluster.js
The purpose of this PR is https://arangodb.atlassian.net/browse/BTS-1104. The design document is here:
https://github.com/arangodb/documents/pull/122
1. The `resignLeadership` job will schedule its `MoveShard` jobs with a `tryUndo: true` attribute.
2. This will lead to the effect that the `MoveShard` job (for leader change) is undone once the old leader has been restarted.
3. This works by putting an entry in `/Target/ReturnLeadership` which the `Supervision` observes.
For detailed rules see the design document.
- [*] Backport for 3.9: This is it.
- [*] GitHub issue / Jira ticket: https://arangodb.atlassian.net/browse/BTS-1104
- [*] Design document: https://github.com/arangodb/documents/pull/122
- [*] Devel PR: …
> [BTS-1104] Undo ResignLeadership

- CHANGELOG
- arangod/GeneralServer/GeneralCommTask.cpp
Fixes https://arangodb.atlassian.net/browse/ES-1366
* Don't log Boost ASIO warnings such as `asio IO error: 'stream truncated'` when a peer closes an SSL/TLS connection without performing a proper connection shutdown.
> ES-1366: suppress "stream truncated" warnings

- arangod/IResearch/IResearchFilterFactory.cpp
- tests/js/server/aql/aql-inverted-index.js
For IN and Array IN operators attribute name check was moved earlier. So it is not skipped during optimization phase
> SEARCH-433 make field name check earlier + test

- lib/Basics/VelocyPackHelper.cpp
- lib/Rest/GeneralRequest.cpp
- lib/Rest/GeneralRequest.h
- lib/Rest/VstResponse.h
- lib/SimpleHttpClient/SimpleHttpClient.cpp
- tests/IResearch/RestHandlerMock.h
Reduce dependency on `StringBuffer` where it is not actually needed.
> reduce dependency on StringBuffer

- tests/js/client/shell/transaction/replication2_recovery/shell-transaction-replication2-recovery.js
During `testFailoverDuringTransaction` we encountered a very strange behavior, on Windows, which we were not able to reproduce nor explain. After a failover has occurred successfully, we start a streaming transaction, but when we try to commit it, the coordinator seems to contact the old leader.
This PR does not provide a bug fix, but it enhances test logging.
> [CINFRA-623] Enhanced logging

- arangod/Agency/CMakeLists.txt
- arangod/Aql/CMakeLists.txt
- arangod/CMakeLists.txt
- arangod/Cache/CMakeLists.txt
- arangod/Cluster/CMakeLists.txt
- arangod/ClusterEngine/CMakeLists.txt
- arangod/Graph/CMakeLists.txt
- arangod/IResearch/CMakeLists.txt
- arangod/Indexes/CMakeLists.txt
- arangod/Metrics/CMakeLists.txt
- arangod/Network/CMakeLists.txt
- arangod/Pregel/CMakeLists.txt
- arangod/Replication/CMakeLists.txt
- arangod/Replication2/CMakeLists.txt
- arangod/RestHandler/CMakeLists.txt
- arangod/RocksDBEngine/CMakeLists.txt
- arangod/StorageEngine/CMakeLists.txt
- arangod/Utils/CMakeLists.txt
- arangod/V8Server/CMakeLists.txt
- arangod/VocBase/CMakeLists.txt
- arangod/arangoserver.cmake
- tests/CMakeLists.txt
Deletes duplicate compile-warnings options: Options are already added via add_compile_warnings_flags function.
> Delete duplicate compile-warnings options

- tests/js/common/shell/shell-collection-noncluster.js
Attempt to fix an unstable test.
The edge cache behavior depends on timing (loading is done asynchronously, and cache grow requests are also executed asynchronously). Thus run the test up to 3 times, and only let it fail in run 3.
> attempt to fix unstable test

- CHANGELOG
- arangod/VocBase/VocbaseInfo.cpp
- arangod/VocBase/VocbaseInfo.h
- tests/js/client/server_parameters/test-sharding-restrictions-cluster.js
Backport of https://github.com/arangodb/arangodb/pull/17728.
Validate `replicationFactor` when creating new databases.
* Disallow creating new databases with a `replicationFactor` value set to a value lower than `--cluster.min-replication-factor` or higher than `--cluster.max-replication-factor`. Previously the `replicationFactor` settings for new databases were not bounds-checked, only for new collections.
> validate `replicationFactor` when creating new databases

- CHANGELOG
- arangod/Agency/AgencyFeature.cpp
- arangod/Agency/AgencyFeature.h
- arangod/Agency/Agent.cpp
- arangod/Agency/AgentConfiguration.cpp
- arangod/Agency/AgentConfiguration.h
- arangod/Agency/FailedLeader.cpp
- arangod/Agency/FailedLeader.h
- arangod/Agency/FailedServer.cpp
- arangod/Agency/FailedServer.h
- arangod/Agency/Supervision.cpp
- arangod/Agency/Supervision.h
- tests/Agency/FailedLeaderTest.cpp
- tests/Agency/FailedServerTest.cpp
- tests/Agency/FailedServerTest.json
We found that a FailedLeader job automatically deploys a new follower.
This is probably not desirable. An AddFollower will do the work later
anyway. Therefore this proposes to make the new follower configurable.
- [*] Tests
- [*] Backport for 3.9.6 branch (for 3.9.6.2): This is it
- [*] GitHub issue / Jira ticket: https://arangodb.atlassian.net/browse/BTS-1162
- [*] Design document: https://github.com/arangodb/documents/pull/123
- [*] Original PR for devel: https://github.com/arangodb/arangodb/pull/17785
> FailedLeader does not add follower - BTS-1162

- lib/Geo/ShapeContainer.cpp
Also:
* Don't use deprecated s2 functions (they are same, they just call contains(*p)).
> Speedup geo intersects rectangle with polygon

- lib/Basics/Guarded.h
Ported forward from #17528 
* remove some superflous headers
* add a isLocked method that determines whether a guarded is locked
* remove two superflous std::invoke calls
> Small updates for Guarded

- scripts/clang-format.ps1
Unbreaks the PowerShell wrapper script. Starting with pwsh v7.3.0, the call operator seems to forward a variable with an empty string as such, causing the `clang-format.sh` script not to find any files (unless explicitly specified).
> clang-format.ps1: Fix for call operator change in pwsh 7.3.0

- arangod/RocksDBEngine/RocksDBIndexCacheRefillFeature.cpp
Fix wrong version number for 3.10 version in "introduced in" description. Found by @neunhoef
> fix "introduced in" version number for 3.10

- arangod/Agency/AgencyFeature.cpp
- arangod/RestServer/QueryRegistryFeature.cpp
- arangod/RocksDBEngine/RocksDBIndexCacheRefillFeature.cpp
According to @Simran-B , future versions should be mentioned in "setIntroducedIn" of earlier versions.
The rule is also written down here: https://github.com/arangodb/arangodb/blob/devel/CONTRIBUTING.md#adding-startup-options
> remove future versions from startup option help

- CONTRIBUTING.md
- js/client/modules/@arangodb/testutils/instance.js
we so far can put args to arangods launched by testing.js one could specify `--extraArgs:log.level debug` - now one can set this per instance type to be launched.
> QA-326: [testing] add way to specify per instance extra arg

- arangod/RestHandler/RestTransactionHandler.cpp
~willify~ improve an error message when a transaction ID is sent in a request to begin a transaction.
Sending a transaction ID is unexpected, and previously produced a "Not supported on this server type" error message.
> improve user message for end users

- arangod/Cache/TransactionalCache.cpp
Fix duplicate reporting of find hits/misses in transactional cache
> fix duplicate cache stats reporting

- arangod/Cache/TransactionalCache.cpp
Backport of https://github.com/arangodb/arangodb/pull/17857
Fix duplicate reporting of find hits/misses in transactional cache
> fix duplicate reporting of cache stats

- arangod/Replication2/StateMachines/Document/DocumentLeaderState.cpp
- arangod/Replication2/StateMachines/Document/DocumentStateHandlersFactory.cpp
The problem was triggered in the following scenario:
A replicated state is created at the beginning of a JS test. One follower is stopped and we wait until the server is FAILED. The test continues and finished, but in the `tearDown` the server is brought back up. Immediately, the suite proceeds with `tearDownAll` and drops the database. At this point, the replicated state is still there and the follower is initialized again. During initialization, we use `lookupDatabase` to get a pointer to the vocbase, in order to create the `snapshotHandler`. If the database is being dropped, but we're still in the constructor of the follower, we won't be able to initialize the `snapshotHandler`. Eventually, when we'll get to `resign`, we'll try to access the `snapshotHandler` and crash.
This PR handler …
> The snapshotHandler might not be initialized

- arangod/Replication2/StateMachines/Document/DocumentStateTransactionHandler.cpp
- arangod/RocksDBEngine/SimpleRocksDBTransactionState.h
- arangod/Transaction/Methods.cpp
- tests/js/server/replication2/replication2-replicated-state-document-store.js
This PR enables error reporting for babies operations on followers.
For replication1, it is important to avoid building the result on followers, because it saves both time and network traffic. However, for replication2, we now mostly care for reporting the transaction result. We no longer have the problem of additional network traffic, and it comes in handy when debugging.
I tried to leave the path taken by the current replication1 code untouched, while creating a couple of special conditions for replication2.
> [CINFRA-614] Error Reporting In Transaction Handler

- 3rdParty/jemalloc/CMakeLists.txt
- 3rdParty/jemalloc/v5.3.0/src/jemalloc.c
- CHANGELOG
This "fixes" an option of jemalloc which can safe considerable amounts
of memory without impacting performance (according to our measurements).
In this PR, we add configurability of this option from the environment
(forgotten in jemalloc) and at the same time set the default to `false`.
- Make `cache_oblivious` configurable for jemalloc from ENV.
- Make `cache_oblivious:false` the default for jemalloc.
This option does the following:
If set to true (old default), jemalloc allocates for every allocation
of 16384 or more bytes one additional page (4k) to change the base
address that it is not divisible by 4096. This could potentially make
sense since it helps the CPU caches, in the case that lots of accesses
to the beginning of such blocks happen (because of the limited
associativity) of …
> jemalloc cache_oblivious configurable, default false

- arangod/Cluster/ClusterTypes.h
- arangod/Cluster/ServerState.cpp
- arangod/Cluster/ServerState.h
`ServerState::getRebootId()` and `ServerState::setRebootId()` can be called simultaneously, but this was a data race. This makes `ServerState::_rebootId` an atomic to fix this.
`setRebootId()` is called once in the startup phase; here, no race can happen. After that, `setRebootId()` is (only) called when the Supervision marks the server as failed (e.g. due to a network split or SIGSTOP), and the server reconnects without actually having been restarted. This is an unlikely event, and this data race having visible impact seems very unlikely.
> Make ServerState::_rebootId atomic

- arangod/Aql/RemoteExecutor.cpp
- arangod/Aql/RemoteExecutor.h
Remove long-unused methods from RemoteExecutor.
These methods had no callers, because the underlying API functionality was removed a while ago.
> remove unused methods from RemoteExecutor

- arangod/RocksDBEngine/RocksDBOptionFeature.cpp
- arangod/RocksDBEngine/RocksDBOptionFeature.h
Added startup option to configure the number of bloom bits per key. The default value is 10, which is downwards-compatible to the previously hard-coded value.
> add startup option to configure number of bloom bits

- arangod/Network/Methods.cpp
- arangod/Network/Methods.h
BTS-163: arangodb::network::sendRequest is potentially used in an unsafe fashion
Make `network::Request::slice()` noexcept. The BTS ticket in question is more than 2 years old, and in practice we haven't seen any problems with potential exceptions originating from the `slice()` method. However, make it formally noexcept now and handle any potential exceptions internally.
https://arangodb.atlassian.net/browse/BTS-163
> BTS-163: no network::Response::slice() noexcept

- arangod/Replication2/ReplicatedState/ReplicatedState.h
- arangod/Replication2/ReplicatedState/ReplicatedState.tpp
Since #17850, the DocumentFollowerState no longer synchronizes resigning with calling release on the stream. But calls to release on a resigned stream caused a nullptr-deref. This PR changes that, so it throws an exception instead.
> [CINFRA-647] Make the Stream throw an exception after resign

- arangod/GeneralServer/AcceptorTcp.cpp
- arangod/GeneralServer/SslServerFeature.cpp
- arangod/RocksDBEngine/RocksDBChecksumEnv.cpp
- lib/SimpleHttpClient/SslClientConnection.cpp
- lib/Ssl/ssl-helper.cpp
- lib/Ssl/ssl-helper.h
These guards checked whether OpenSSL was version < OpenSSL 1.1.1, which are not supported anymore and should hence always evaluate to `false` anyway.
> Remove superflous OPENSSL version guards

- CHANGELOG
- arangod/Aql/Ast.cpp
- arangod/Aql/AstNode.cpp
- arangod/Aql/AstNode.h
- arangod/Aql/EngineInfoContainerDBServerServerBased.cpp
- arangod/Aql/Functions.cpp
- arangod/Aql/Query.cpp
- arangod/Aql/QueryExecutionState.cpp
- arangod/Aql/QueryExecutionState.h
- arangod/Aql/QueryProfile.h
- arangod/Aql/TraversalNode.cpp
- arangod/Aql/TraverserEngineShardLists.cpp
- arangod/Aql/Variable.cpp
- arangod/Aql/Variable.h
- arangod/Aql/VariableGenerator.cpp
- js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
- js/common/modules/@arangodb/aql/explainer.js
- js/server/modules/@arangodb/testutils/aql-profiler-test-helper.js
Improve query plan serialization time
* Added new stage "instantiating executors" to the query profiling output. The time spent in "instantiating executors" is the time needed to create the query executors from the final query execution time. In cluster mode, this stage also includes the time needed for physically distributing the query snippets to the participating database servers. Previously, the time spent for instantiating executors and the physical distribution was contained in the "optimizing plan" stage, which was misleading.
* Remove constant values for query variables from query plan serialization in cases they were not needed. Previously, constant values of query variables were always serialized for all occurrences of a variable in a query plan. If the constant values were …
> improve query plan serialization time

- 3rdParty/jemalloc/v5.2.1/src/jemalloc.c
- CHANGELOG
This "fixes" an option of jemalloc which can safe considerable amounts
of memory without impacting performance (according to our measurements).
In this PR, we add configurability of this option from the environment
(forgotten in jemalloc).
- Make `cache_oblivious` configurable for jemalloc from ENV.
This option does the following:
If set to true (old default), jemalloc allocates for every allocation
of 16384 or more bytes one additional page (4k) to change the base
address that it is not divisible by 4096. This could potentially make
sense since it helps the CPU caches, in the case that lots of accesses
to the beginning of such blocks happen (because of the limited
associativity) of the CPU caches.
However, on the flip side, it "wastes" 4K for every allocation. Since
the RocksDB buffer …
> Make cache_oblivious configurable via env for jemalloc

- CHANGELOG
- arangod/Cluster/HeartbeatThread.cpp
- arangod/RestHandler/RestAdminServerHandler.cpp
- arangod/RestServer/DatabaseFeature.cpp
- arangod/VocBase/VocbaseInfo.cpp
- arangod/VocBase/VocbaseInfo.h
Backport of https://github.com/arangodb/arangodb/pull/17883
Allow database server start in cluster even in case there are existing databases that would violate the settings `--cluster.min-replication-factor` or `--cluster.max-replication-factor`. This allows upgrading from older versions in which the replication factor validation for databases was not yet present.
A more thorough validation for replication factor settings for databases was added in 3.10.2, which is appropriate when creating new databases. However, the more strict validation added in 3.10.2 prevents servers with improper replication factor settings in existing databases from starting.
[OASIS-24944]: https://arangodb.atlassian.net/browse/OASIS-24944?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …
> Allow database server start with invalid repl factor settings

- .gitignore
- tests/CMakeLists.txt
- tests/Futures/CMakeLists.txt
- tests/Zkd/CMakeLists.txt
Adds cmake user presets file to gitignore - Each user should be able to define his/her own presets.
Links zkd tests library into arangodbtests instead of adding test files manually to arangodbtests.
> [cmake] Ignore user presets

- CHANGELOG
- arangod/Aql/AqlCallList.cpp
- arangod/Aql/AqlCallStack.cpp
- arangod/Aql/Ast.cpp
- arangod/Aql/AstNode.cpp
- arangod/Aql/AstNode.h
- arangod/Aql/Condition.cpp
- arangod/Aql/ExecutionPlan.cpp
- arangod/Aql/Expression.cpp
- arangod/Aql/OptimizerRules.cpp
- arangod/Aql/OptimizerUtils.cpp
- arangod/Aql/SortingGatherExecutor.cpp
- arangod/IResearch/AqlHelper.cpp
- arangod/IResearch/AqlHelper.h
- arangod/IResearch/IResearchFilterFactory.cpp
- arangod/IResearch/IResearchFilterFactoryCommon.h
- arangod/RocksDBEngine/RocksDBPrimaryIndex.cpp
- js/common/modules/@arangodb/aql/explainer.js
- js/server/modules/@arangodb/aql-helper.js
- tests/Aql/AstNodeTest.cpp
- tests/CMakeLists.txt
- tests/js/server/aql/aql-optimizer-condition.js
- tests/js/server/aql/aql-optimizer-geoindex.js
Follow-up PR to https://github.com/arangodb/arangodb/pull/17897
* Use more compact and efficient representation for arrays and objects during AQL AST serialization and deserialization. This can help to reduce the size of messages exchanged between coordinator and database servers during query setup, and also reduce the time needed for parsing these messages. This especially helps when there are large bind parameter values that are arrays or objects.
> Improve efficiency of array/object serialization in query plans

- CMakePresets.json
Small improvements for cmake presets
- turn off jemalloc for ASan/UBSan builds, because no other memory allocator should be used with ASan
- use the same ASan/UBSan options as we currently do in Oskar (they were recently changed there)
- fix "incorrect" preset names
> Small improvements for cmake presets

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/views/navigationView.js
In addition to the original PR #15776 , we also must disable error notifications for the actual licence call itself - if parameter: `--server.harden true` is being set. Otherwise the attempted effect (original pr) does not take into account.
Original scope (part1): 
> Non-root users has no access to the api endpoint "/_admin/time" which we use to calculate and display license info below the navigation bar and therefore returns a 403 error. Meaning those users got the info "Error: Failed to fetch license information" all the time what is bad user experience. As this license information is just an information for the user we removed error handling at fetching the license information to not show errors in the Web UI. In this specific case we improve the user experience in not showing errors.
> [FE-48] only admin see license info PART2

- arangod/Replication2/ReplicatedLog/ILogInterfaces.h
- arangod/Replication2/ReplicatedLog/LogLeader.h
- arangod/Replication2/ReplicatedLog/ReplicatedLog.cpp
- js/common/modules/@arangodb/testutils/replicated-logs-helper.js
- tests/Replication2/ReplicatedLog/ReplicatedLogConnectTest.cpp
Collection and Database creation was slow with replication 2. The reason for this was, that changes in replicated states were not reported to the agency asap. This was, because the database was not marked as dirty. This PR changes that. Once a leader is established, the database is marked as dirt, which triggers a maintenance run, which then reports the changes to the agency. Similar code was already in place for updates.
Additionally I changes the times in `waitFor` for testing. Usually replicated states react faster than .5s. I was able (at least on my machine) to push the test run time for `replication2-supervision-replicated-log-target-cluster.js` from 2.5 minutes to 1.5 minutes. Most of the time was spend in waitFor, waiting for the system to converge (which it already did).
> [CINFRA] State Creation Speedup

- lib/Basics/memory-map-posix.cpp
- lib/Basics/memory-map-win32.cpp
- lib/CrashHandler/CrashHandler.cpp
- lib/Logger/Logger.h
- lib/Logger/LoggerStream.cpp
- lib/Logger/LoggerStream.h
Remove unused functionality from Logger/LoggerStream: `Logger::CHARS`, Logger::RANGE` and `Logger::BINARY`.
Adjust a few places that still used it to use something else instead.
This is an internal change that should not have any effect on the user-visible behavior.
> remove unused functionality from LoggerStream

- arangod/Agency/AsyncAgencyComm.cpp
- arangod/Agency/AsyncAgencyComm.h
- arangod/Cluster/AgencyCache.cpp
- arangod/Cluster/AgencyCache.h
- arangod/Replication2/AgencyMethods.cpp
- arangod/RestHandler/RestLogHandler.cpp
I did two things in this PR:
1. I added `waitForLastCommitIndex()` to the agency cache. The function calls the agency and looks for the current commit index. Then it waits for this index to be visible in the local cache. Doing that ensures, that writes that were performed on a different coordinator before a call to `waitForLastCommitIndex` are visible locally.
2. To implement the above function I added `getCurrentCommitIndex` to the AsyncAgencyComm.
3. The replace-participant call, that failed due to a wrong cache, is not patched. See below for more details, why the test failed.
4. I added a precondition, that was missing and allowed the write, although something else was already present in the agency. Just having this precondition, wouldn't have fixed the test. Instead it would have …
> [CINFRA] Replace Participant Race with Agency Cache

- arangod/Replication2/StateMachines/Document/DocumentFollowerState.cpp
- arangod/Replication2/StateMachines/Document/DocumentFollowerState.h
- tests/Replication2/ReplicatedState/DocumentStateMachineTest.cpp
The user may remove and add the server again. The leader might do a compaction which the follower won't notice if the process is stopped. From the follower's perspective, the leader compacted something without waiting for itself. Hence, a new snapshot is required. This can happen so quick, that one snapshot transfer is not yet completed before another one is requested.
Before we start transferring the snapshot, we truncate the shard. In case an older snapshot transfer is still ongoing, we make sure that it's not going to apply transactions anymore.
As a remark, currently there's no way to abort a snapshot on the leader, except sending a `finish` request. This would be changed later on, but for now it does suffice.
> [CINFRA-645] acquireSnapshot could be called concurrently

- CHANGELOG
- arangod/GeneralServer/RestHandler.h
- arangod/RestHandler/RestWalAccessHandler.cpp
Change the request lane for replication catchup requests that leaders in active failover receive from their followers from medium to high. This will give catchup requests from followers highest priority, so that the leader will preferrably execute them compared to regular requests.
The change will likely not help a lot, because catchup requests have been on the medium request lane before already, which already has higher priority than the lanes that normal write operations run on.
Potentially slightly helps https://arangodb.atlassian.net/browse/ES-1398.
> Change request lane for active failover catchup requests

- Documentation/DocuBlocks/Rest/Indexes/post_api_index_inverted.md
- Documentation/DocuBlocks/Rest/Views/post_api_view_arangosearch.md
See https://github.com/arangodb/docs/pull/1238
> DOC-312 | Inverted indexes and `arangosearch` Views accept an array of strings for `storedValues`

- tests/js/client/shell/shell-admin-cluster-rebalance.js
This PR fixes incorrect assumption of return value of a request to be always 202, but, when there are no possible moves to execute in a request to rebalance shards, the return value is 200. It's only 202 when the moves are accepted, meaning the amount of possible moves is not zero. Related to https://github.com/arangodb/arangodb/pull/17154.
> Fixed assumption about return value

- arangod/Replication2/StateMachines/Document/DocumentFollowerState.cpp
- arangod/Replication2/StateMachines/Document/DocumentLeaderState.cpp
Returning a failed result triggers an assertion further down the line, which causes the server to crash. This happens when the `vocbase` is not found during the construction of the replicated state, therefore some important members cannot be initialized. We know about the issue and it's being fixed in [CINFRA-588](https://arangodb.atlassian.net/browse/CINFRA-588) and [CINFRA-649](https://arangodb.atlassian.net/browse/CINFRA-649), but for now let's not crash in devel.
We still use logging to report the problem.
[CINFRA-588]: https://arangodb.atlassian.net/browse/CINFRA-588?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CINFRA-649]: https://arangodb.atlassian.net/browse/CINFRA-649?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJ …
> [CINFRA-657] Return a successful result such that we don't crash

- arangod/Replication2/StateMachines/Document/DocumentCore.cpp
- arangod/Replication2/StateMachines/Document/DocumentCore.h
- arangod/Replication2/StateMachines/Document/DocumentFollowerState.cpp
- arangod/Replication2/StateMachines/Document/DocumentFollowerState.h
- arangod/Replication2/StateMachines/Document/DocumentLeaderState.cpp
- arangod/Replication2/StateMachines/Document/DocumentLogEntry.h
- arangod/Replication2/StateMachines/Document/DocumentStateShardHandler.cpp
- arangod/Replication2/StateMachines/Document/DocumentStateShardHandler.h
- tests/Replication2/Mocks/DocumentStateMocks.h
- tests/Replication2/ReplicatedState/DocumentStateMachineTest.cpp
**Context**
The plan is to get rid of the `agencyHandler` from the `DocumentCore`. The maintenance will create the shard on the leader, which in turn will instruct the followers to do the same.
**In this PR**
We are introducing two new operations: `CreateShard` and `DropShard`. We make sure to handle them during `applyEntries` on the follower and `recoverEntries` on the leader.
The `DocumentStateShardHandler` no longer uses the `shardId` of the core, but expects to get one as parameter.
Shard operations are not currently issued by the leader, so in reality the follower is not going to see these in the log.
[CINFRA-653](https://arangodb.atlassian.net/browse/CINFRA-654) is also handled here.
[CINFRA-653]: https://arangodb.atlassian.net/browse/CINFRA-653?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3 …
> [CINFRA-654] Introduce shard operations on follower

- Documentation/Metrics/arangodb_replication2_replicated_log_append_entries_rtt.yaml
- Documentation/Metrics/arangodb_replication2_replicated_log_creation_total.yaml
- Documentation/Metrics/arangodb_replication2_replicated_log_deletion_total.yaml
- Documentation/Metrics/arangodb_replication2_replicated_log_follower_append_entries_rt.yaml
- Documentation/Metrics/arangodb_replication2_replicated_log_follower_number.yaml
- Documentation/Metrics/arangodb_replication2_replicated_log_inactive_number.yaml
- Documentation/Metrics/arangodb_replication2_replicated_log_inserts_bytes.yaml
- Documentation/Metrics/arangodb_replication2_replicated_log_inserts_rtt.yaml
- Documentation/Metrics/arangodb_replication2_replicated_log_leader_number.yaml
- Documentation/Metrics/arangodb_replication2_replicated_log_leader_took_over_total.yaml
- Documentation/Metrics/arangodb_replication2_replicated_log_number.yaml
- Documentation/Metrics/arangodb_replication2_replicated_log_number_accepted_entries_total.yaml
- Documentation/Metrics/arangodb_replication2_replicated_log_number_committed_entries_total.yaml
- Documentation/Metrics/arangodb_replication2_replicated_log_number_compacted_entries_total.yaml
- Documentation/Metrics/arangodb_replication2_replicated_log_number_meta_entries_total.yaml
- Documentation/Metrics/arangodb_replication2_replicated_log_started_following_total.yaml
- Documentation/Metrics/arangodb_replication2_replicated_state_acquire_snapshot_errors_total.yaml
- Documentation/Metrics/arangodb_replication2_replicated_state_applied_entries_total.yaml
- Documentation/Metrics/arangodb_replication2_replicated_state_apply_entries_errors_total.yaml
- Documentation/Metrics/arangodb_replication2_replicated_state_follower_acquire_snapshot_rt.yaml
- Documentation/Metrics/arangodb_replication2_replicated_state_follower_apply_entries_rt.yaml
- Documentation/Metrics/arangodb_replication2_replicated_state_follower_number.yaml
- Documentation/Metrics/arangodb_replication2_replicated_state_follower_waiting_for_leader_number.yaml
- Documentation/Metrics/arangodb_replication2_replicated_state_follower_waiting_for_snapshot_number.yaml
- Documentation/Metrics/arangodb_replication2_replicated_state_leader_number.yaml
- Documentation/Metrics/arangodb_replication2_replicated_state_leader_recover_entries_rt.yaml
- Documentation/Metrics/arangodb_replication2_replicated_state_leader_waiting_for_recovery_number.yaml
- Documentation/Metrics/arangodb_replication2_replicated_state_number.yaml
- Documentation/Metrics/arangodb_replication2_replicated_state_processed_entries_total.yaml
Fix wrong version numbers in `introducedIn` attribute of replication2 metrics.
All these metrics will appear in 3.11, not in previous versions.
> fix wrong version numbers in `introducedIn` of metrics

- arangod/Pregel/PregelFeature.cpp
- arangod/Pregel/PregelFeature.h
- arangod/Pregel/PregelOptions.h
- arangod/Pregel/REST/CMakeLists.txt
- arangod/Pregel/REST/RestControlPregelHandler.cpp
- arangod/Pregel/REST/RestOptions.cpp
- arangod/Pregel/REST/RestOptions.h
- arangod/V8Server/v8-pregel.cpp
- tests/js/client/load-balancing/load-balancing-pregel-noauth-cluster.js
Uses a struct for the pregel options instead of handling everything with a velocypack.
Extracting the pregel parameters (e.g. "store", "shartKeyAttribute", ...) is a bit more work because it involves using structs in all algorithms for their algorithm-specific parameters instead of plain velocypack, therefore this will be done later in another PR.
Additionally, I moved the code that processes the options from the REST handler into the feature, such that the REST handler is doing no business work and processing the options is done at one place: The feature.
> [PREG-207] Use struct for pregel options

- tests/CMakeLists.txt
- tests/Graph/CMakeLists.txt
- tests/Replication2/CMakeLists.txt
Gets rid of duplicated linking in graph and rep2 tests and uses PRIVATE where appropriate.
> [cmake] Get rid of duplicated dependencies in graph and rep2 tests

- arangod/Aql/Ast.cpp
- arangod/Aql/Ast.h
- arangod/Aql/StandaloneCalculation.cpp
Remove public willUseV8() / setWillUseV8() APIs as they are not needed. only use the flag internally, but don't expose it.
While we are on it, remove a few unnecessary namespace prefixes and move string concatenation to `absl::StrCat`.
The changes in this PR should not affect behavior in any way.
> remove public willUseV8() / setWillUseV8() APIs

- arangod/Pregel/CommonFormats.h
- arangod/Pregel/ExecutionNumber.h
- arangod/Pregel/Status/ConductorStatus.h
- arangod/Pregel/Status/ExecutionStatus.h
- arangod/Pregel/Status/Status.h
- lib/Assertions/ProdAssert.h
- tests/CMakeLists.txt
- tests/Pregel/CMakeLists.txt
Adds `CMakeLists.txt` for `tests/Pregel`, which adds a test executable `arangodbtests_pregel` and a test case `pregel`;
Note that `typedbuffer.cpp` is not included in this test-binary intentionally because of its large dependency footprint and the fact that we plan to remove that class. It is still tested by `arangodbtests`.
> [PREGEL] Provide test binary for Pregel

- CHANGELOG
- arangod/Agency/AgentConfiguration.cpp
- arangod/Agency/State.cpp
This tries to address https://arangodb.atlassian.net/browse/BTS-1185
There is currently a problem with an agent which might have lost its
data directory and thus has forgotten its UUID. It then tries to join
the agency with a new UUID. There are situations in which this can
confuse the agency configuration.
- [*] Backport for 3.8: This is the one for 3.8.
- [*] GitHub issue / Jira ticket: https://arangodb.atlassian.net/browse/BTS-1185
- [*] PR for devel: https://github.com/arangodb/arangodb/pull/17919
> Make agency watertight against illegal agents with new UUIDs BTS-1185

- js/client/modules/@arangodb/testutils/instance.js
By default, crash info and crash stack traces are suppressed during test execution, because for test execution the log verbosity for all log topics is set to `error`.
This PR fixes that by explicitly setting the log verbosity for the `crash` log topic to `info`.
This PR only affects logging during test execution, and thus only has impact on tests.
The change contained in this PR has already been made in devel before.
3.9 and 3.8 do not need this change, because test execution is very verbose in these branches anyway.
> log crash info in tests

- tests/js/client/server_parameters/auto-refill-index-caches-on-modify-noncluster-off.js
- tests/js/client/server_parameters/auto-refill-index-caches-on-modify-noncluster-on.js
test-only bugfix
the previous version of the tests could sporadically fail if inserting data into the in-memory index caches failed. this is possible, because inserting index entries into the in-memory cache is not guaranteed to work. inserting into the cache will fail if:
- the global memory budget of the cache subsystem is exceeded
- the cache's underlying hash table is in a "migration" phase it is thus rarely possible that the insertion of any index entries into an in-memory cache fails for a certain amount of time. the fix in this PR is to try again in case of failure. up to 3 attempts are made so that the tests do no execute endlessly.
> fix failing test, next attempt

- CHANGELOG
- arangod/RocksDBEngine/RocksDBChecksumEnv.cpp
Backport of https://github.com/arangodb/arangodb/pull/17948
This PR fixes a potential race during hot backup creation, described in https://arangodb.atlassian.net/browse/BTS-1192:
There has been a report about the following error occuring every hour:
```
ERROR [d5f51] {backup} Source file engine_rocksdb/002516.sst does not have a hash file.
```
More details can be found in the BTS ticket.
> BTS-1192: fix potential race in sha file creation

- CHANGELOG
- arangod/Aql/Ast.h
- arangod/Aql/AstNode.cpp
- arangod/Aql/ExecutionNode.cpp
- arangod/Aql/Expression.cpp
- arangod/Aql/Function.cpp
- arangod/Aql/Functions.cpp
- arangod/Transaction/V8Context.cpp
- tests/js/common/aql/aql-view-arangosearch-cluster.inc
- tests/js/common/aql/aql-view-arangosearch-common-noncluster.inc
- tests/js/server/aql/aql-multiple-snippets-javascript-cluster.js
Fix coordinator segfault in AQL queries in which the query is invoked from within a JavaScript context (e.g. from Foxx or from the server's console mode) **and** the query has multiple coordinator snippets of which except the outermost one invokes a JavaScript function. 
Instead of crashing, coordinators will now respond with the exception "no v8 context available to enter for current transaction context". 
For AQL queries that called one of the AQL functions `CALL` or `APPLY` with a fixed function name, e.g. `APPLY('CONCAT', ...)`, it is now also assumed correctly that no JavaScript is needed if the fixed function name refers to a built-in function, and if the function call parameters also don't require the usage of JavaScript.
A follow-up PR will fix that multiple coordinator snippets …
> Fix OASIS-24962

- arangod/Pregel/AlgoRegistry.cpp
- arangod/Pregel/AlgoRegistry.h
- arangod/Pregel/Conductor/Conductor.cpp
- arangod/Pregel/Conductor/Conductor.h
- arangod/Pregel/Conductor/Messages.h
- arangod/Pregel/PregelFeature.cpp
- arangod/Pregel/Utils.cpp
- arangod/Pregel/Utils.h
- arangod/Pregel/Worker/Worker.cpp
- arangod/Pregel/Worker/Worker.h
- arangod/Pregel/Worker/WorkerConfig.cpp
- arangod/Pregel/Worker/WorkerConfig.h
Use structs instead of plain velocypack for messages sent from conductor to workers. A simliar PR for messages from workers to conductor will follow.
This is a preparation step for using a proper messaging framework for Pregel.
> [PREG-226] Use structs for conductor messages

- lib/Inspection/Format.h
- tests/Basics/InspectionTest.cpp
The inspection formatter uses now serializeWithErrorT instead of serialize in formatter. This comes handy if you want to use the formatter, but don't want to link to the full arango that includes exceptions.
> Make inspection formatter independent of exceptions

- lib/ProgramOptions/UnitsHelper.cpp
- tests/ProgramOptions/ParametersTest.cpp
we previously allowed kb, mb, gb, tb, but not b.
now it is possible to specify things with a unit of bytes as well, e.g. `--rocksdb.block-cache-size=1073741824b`.
docs PR: https://github.com/arangodb/docs/pull/1253
> allow usage of suffix `b` in startup option values

- arangod/Cluster/ActionBase.cpp
- arangod/Cluster/ActionBase.h
- arangod/Cluster/HeartbeatThread.cpp
- arangod/Cluster/HeartbeatThread.h
- arangod/Cluster/MaintenanceRestHandler.cpp
- arangod/Cluster/RestClusterHandler.cpp
- arangod/RestServer/ServerFeature.cpp
Small cleanup w.r.t. HeartbeatThread
- removed a few unnecessary includes of HeartbeatThread.h
- turned a static variable in HeartbeatThread.cpp into an instance variable
> small cleanup w.r.t. HeartbeatThread

- js/client/modules/@arangodb/testutils/testing.js
Gcov enabled binaries aren't as quick similar to *SAN give them more time to run the test.
> testing: relax timeout of tests under gcov

- js/client/modules/@arangodb/testsuites/rta_makedata.js
We should enable arangosearch cache by specifying the parameter `--arangosearch.columns-cache-limit <N>` in RTA script in main repository.
> added server options for arangosearch cache in RTA

- .gitignore
- CMakePresets.json
This PR adds some of the work that is currently in #17792 to `devel`.
The `pr` presets are used to build arangodb for testing on circleci and are currently set up to mimic the setup that is used on the Jenkins testing infrastructure.
I have also hidden a few of the "base" presets that do not constitute a usable preset for configuring/building and added a few missing build presets.
We should probably think about how to test that presets are valid and usable (beyond the fact that if you make a syntax mistake in the presets file, CI won't even run if it relies on cmake presets).
> [CMake] Add PR presets and clean up a bit

- arangod/RestHandler/RestStatusHandler.cpp
[BTS](https://arangodb.atlassian.net/browse/BTS-899)
Do not expose the reboot id on agents, because there is none.
> [BTS-899] _admin/status crash on agents

- js/client/modules/@arangodb/testsuites/server_permissions.js
- tests/test-definitions.txt
Improve parallelism by bucketing test
> testing: split the long running server_parameters testsuite into buckets for better parallelism.

- tests/js/server/replication2/replication2-prototype-replicated-state-cluster.js
The test for the prototype state correctly waits for the replicated log to become ready. When the log is ready, the prototype state itself might not be yet be ready. Either it is not build or in recovery. 
I added an additional check to wait for the status request to return `200`.
This should fix some sporadic jenkins failures.
> [CINFRA] PrototypeState check ready

- arangod/Aql/Functions.cpp
- arangod/Pregel/Conductor/Conductor.cpp
- arangod/Pregel/Conductor/Conductor.h
- arangod/Pregel/IncomingCache.cpp
- arangod/Pregel/IncomingCache.h
- arangod/Pregel/OutgoingCache.cpp
- arangod/Pregel/OutgoingCache.h
- arangod/Pregel/PregelFeature.cpp
- arangod/Pregel/Statistics.h
- arangod/Pregel/Worker/Messages.h
- arangod/Pregel/Worker/Worker.cpp
- arangod/Pregel/Worker/Worker.h
Use structs instead of plain velocypack for messages sent from worker to conductor.
This is a preparation step for using a proper messaging framework for Pregel.
> [PREG-226] Use structs for worker messages

- CMakeLists.txt
Disable `maybe-uninitialized` warnings as errors on GCC. The warning stays enabled, but it's no longer a build error.
This is changed because we've seen too many false positives over the last years.
> Disable "maybe-uninitialized" warnings as errors for GCC

- lib/Assertions/ProdAssert.h
I found that I cannot compile devel with maintainer mode switched off on
Ubuntu with gcc 11.2.0 and glibc. It seems an include is missing. This
PR adds the include.
> Add missing include for gcc 11.2 with glibc

- arangod/Agency/ActiveFailoverJob.cpp
- arangod/Agency/AddFollower.cpp
- arangod/Agency/CleanOutServer.cpp
- arangod/Agency/FailedFollower.cpp
- arangod/Agency/FailedLeader.cpp
- arangod/Agency/FailedServer.cpp
- arangod/Agency/MoveShard.cpp
- arangod/Agency/RemoveFollower.cpp
- arangod/Agency/ResignLeadership.cpp
- arangod/Agency/Supervision.cpp
- arangod/Cluster/DropCollection.cpp
- arangod/Cluster/DropIndex.cpp
- arangod/Cluster/EnsureIndex.cpp
- arangod/Cluster/ResignShardLeadership.cpp
- arangod/Cluster/TakeoverShardLeadership.cpp
- arangod/Cluster/UpdateCollection.cpp
- arangod/Replication/TailingSyncer.cpp
Fix inefficient creation of temporary string objects for use with the logger.
Instead of
```
LOG_TOPIC(...) << a + b + c 
```
now use
```
LOG_TOPIC(...) << a << b << c
```
if a, b and c are strings.
None of the adjusted places is performance-critical.
> fix inefficient temporary string creation for log messages

- arangod/Agency/AddFollower.cpp
- arangod/Agency/CleanOutServer.cpp
- arangod/Agency/FailedFollower.cpp
- arangod/Agency/FailedLeader.cpp
- arangod/Agency/FailedServer.cpp
- arangod/Agency/Job.cpp
- arangod/Agency/JobContext.cpp
- arangod/Agency/JobContext.h
- arangod/Agency/MoveShard.cpp
- arangod/Agency/RemoveFollower.cpp
- arangod/Agency/ResignLeadership.cpp
- arangod/Agency/Store.cpp
- arangod/Agency/Store.h
- arangod/Agency/Supervision.cpp
- arangod/Agency/Supervision.h
- tests/Agency/SupervisionTest.cpp
Small code improvements for agency code
- use symbols Supervision::HEALTH_STATUS_XXX instead of strings
"GOOD", "BAD", "FAILED" to indicate health status
- use std::string_views in more cases, to avoid creation of temporary
std::strings (e.g. in conjuction with velocypack::Slice::copyString())
- rename Supervision::removeTransactionBuilder() to
Supervision::buildRemoveTransaction() to better indicate what the
function does
- avoid a few copies of std::shared_ptrs and std::strings
The PR does not intend to change the observable behavior in any way.
> small code improvements for agency code

- arangod/Pregel/Conductor/Conductor.cpp
Deletes an unused function and with this a duplicated log id.
> [PREGEL] Delete duplicated log id

- tests/test-definitions.txt
We have these errors atm, and will work on them later:
```
=== chaos ===
* Test "chaos"
[FAILED]  tests\js\client\chaos\test-module-chaos-load-cluster-nightly.js__no_IntermediateCommits_no_FailurePoints_no_Delays_no_StreamingTransactions_with_Truncate_with_VaryingOverwriteMode
"testWorkInParallel_no_IntermediateCommits_no_FailurePoints_no_Delays_no_StreamingTransactions_with_Truncate_with_VaryingOverwriteMode" failed: Error: at assertion #28: assertEqual: (600) is not equal to (599)
(Error
at assertEqual (d:\win05-colo2\oskar\work\ArangoDB\js\common\modules\jsunity\jsunity.js:108:19)
at checkView (d:\win05-colo2\oskar\work\ArangoDB\tests\js\client\chaos\test-chaos-load-common.inc:136:5)
at checkViewConsistency (d:\win05-colo2\oskar\work\ArangoDB\tests\js\client\chaos\test-chaos-load-common …
```
> disable full chaos run on windows for the nightlies until s.b. wants to work on it

- arangod/Cluster/Utils/EvenDistribution.cpp
- tests/js/client/shell/transaction/shell-transaction-intermediate-commit-cluster.js
The `testMultiAqlIntermediateCommitsOnFollower` sometimes fails on our staging branch, since we introduced `CollectionGroups`. The test tries to setup two different collections, having different leaders but the same follower. Once the first collection _c1_ is successfully setup, we try to setup _c2_ in a loop, such that the follower stays the same, and the leader of _c1_ is marked as avoided. Because there are only 3 servers and one of them is avoided, _c2_ is left with only two possible participants, so there are two possible combinations of (leader, follower), out of which only one will be accepted, which means there's a 50% change to fail. The order of the  `availableServers` list might only change when the agency cache is reloaded. We shuffle the list to avoid getting stuck.
> [CINFRA] Intermediate Commits Flaky Test

- arangod/Agency/Node.cpp
- arangod/Agency/Node.h
- arangod/Agency/NodeDeserialization.h
- arangod/Agency/NodeLoadInspector.h
- arangod/Agency/Store.cpp
- arangod/Agency/Store.h
- arangod/Agency/Supervision.cpp
- arangod/Replication2/ReplicatedState/ReplicatedState.tpp
- lib/Inspection/Access.h
- lib/Inspection/InspectorBase.h
- lib/Inspection/LoadInspectorBase.h
- lib/Inspection/Status.h
- lib/Inspection/VPackLoadInspector.h
- lib/Inspection/ValidateInspector.h
- lib/Inspection/detail/Fields.h
- tests/Basics/Inspection/NodeLoadTest.cpp
- tests/CMakeLists.txt
This PR adds a node load inspector that allows to read of data structures from agency nodes.
This is currently a draft because it is based on the changes in #17283. Once that PR is merged I will rebase this branch onto devel.
> [CINFRA-357] NodeLoadInspector

- arangod/Replication2/StateMachines/Document/DocumentLeaderState.cpp
- js/common/modules/@arangodb/testutils/replicated-logs-helper.js
- tests/js/client/shell/transaction/replication2_recovery/shell-transaction-replication2-recovery.js
* Disabled a check with spurious failures in the test `testCannotReachWriteConcernDuringTransaction` (of `shell-transaction-replication2-recovery.js`). The cause is laid out in [CINFRA-668](https://arangodb.atlassian.net/browse/CINFRA-668), and it can be re-enabled afterwards.
* In `replicated-logs-helper.js`, add functions that stop or resume multiple servers. This speeds up some tests, as we can wait for all of them to be stopped (or resumed) in parallel.
* Use a more appropriate error code in one situation.
* In the document state, resign the core before everything else: This was made possible by #17999, and seems sensible, so places that rely on `didResign()` rather than `_isResigning` are informed before other parts are resigned.
[CINFRA-668]: …
> Minor changes, following cinfra-666

- js/common/modules/@arangodb/testutils/replicated-logs-helper.js
- tests/js/client/shell/transaction/replication2_recovery/shell-transaction-replication2-recovery.js
In order to get rid of the spurious failures of `testCannotReachWriteConcernDuringTransaction` in Jenkins more quickly, get this relevant part of #18044 directly to devel.
> Port #18044 directly to devel

- js/common/modules/@arangodb/graph/pregel-test-effective-closeness-helpers.js
- js/common/modules/@arangodb/graph/pregel-test-helpers.js
- js/common/modules/@arangodb/graph/pregel-test-read-write-helpers.js
- tests/js/client/load-balancing/load-balancing-pregel-auth-cluster.js
- tests/js/client/load-balancing/load-balancing-pregel-noauth-cluster.js
- tests/js/common/shell/shell-pregel-basics-example.js
- tests/js/common/shell/shell-pregel-components.js
- tests/js/common/shell/shell-pregel-multicollection-edgecol.js
- tests/js/common/shell/shell-pregel-random.js
- tests/js/common/shell/shell-pregel-start-cluster.js
Use a function everywhere where a test waits for pregel to finsh successfully. This makes sure that all tests check against the correct pregel status and give helpful error message if the pregel run did not finish successfully.
> [PREGEL] Make pregel js tests more stable

- arangod/Aql/DocumentProducingNode.cpp
- arangod/Aql/ShadowAqlItemRow.cpp
- lib/Basics/ErrorT.h
- lib/Basics/SourceLocation.h
Fix the following issues reported by cppcheck:
```
<results version="2">
<cppcheck version="2.8"/>
<errors>
<error id="virtualCallInConstructor" severity="style" msg="Virtual function 'setFilter' is called from constructor 'DocumentProducingNode(ExecutionPlan*plan,arangodb::velocypack::Slice slice)' at line 66. Dynamic binding is not used." verbose="Virtual function 'setFilter' is called from constructor 'DocumentProducingNode(ExecutionPlan*plan,arangodb::velocypack::Slice slice)' at line 66. Dynamic binding is not used." file0="arangod/Aql/DocumentProducingNode.cpp">
<location file="./work/ArangoDB/arangod/Aql/DocumentProducingNode.h" line="71" column="16" info="setFilter is a virtual function"/>
<location file="./work/ArangoDB/arangod/Aql/DocumentProducingNode.cpp" line="66" column="5" …
```
> fix issues reported by cppcheck

- arangod/Aql/ShortestPathExecutor.tpp
Removes a debugging LOG_DEVEL that was left in the code.
> Remove stray LOG_DEVEL

- CHANGELOG
- arangod/Aql/Ast.cpp
- arangod/V8Server/V8DealerFeature.cpp
- arangod/V8Server/V8DealerFeature.h
- lib/ProgramOptions/ProgramOptions.cpp
- tests/js/client/server_parameters/javascript-user-defined-functions-off.js
Backport of https://github.com/arangodb/arangodb/pull/18048
Added startup option `--javascript.user-defined-functions`.
This option controls whether JavaScript user-defined functions (UDFs) can
be used in AQL queries. The option defaults to `true`. The option can be
set to `false` to disallow using JavaScript UDFs from inside AQL queries.
In that case, a parse error will be thrown when trying to run a query that
invokes a UDF.
> Added startup option --javascript.user-defined-functions.

- 3rdParty/jemalloc/CMakeLists.txt
- CHANGELOG
Backport of https://github.com/arangodb/arangodb/pull/17870
Set the cache_oblivious option of jemalloc to `false` by default. This helps to save 4096 bytes of RAM for every allocation which is at least 16384 bytes large. This is particularly beneficial for the RocksDB buffer cache.
After we have added configurability for jemalloc's cache_oblivious option to 3.10.3 with a previous PR, this PR now disables the cache_oblivious option. This should help to save memory for allocations of size 16kb.
Note: we need to check performance results for this PR, because it can have an effect on allocator performance.
> disable jemalloc cache_oblivious behavior

- CHANGELOG
- arangod/Cluster/ClusterInfo.cpp
- tests/js/client/shell/shell-dump-integration.js
- tests/js/client/shell/shell-restore-integration.js
- tests/js/common/shell/shell-validation.js
Backport for https://github.com/arangodb/arangodb/pull/18014.
PR related to https://arangodb.atlassian.net/browse/BTS-1193.
Fix for schema update. When removing a field and then inserting a new field into the schema, previously, both old and new schema would be merged, meaning it would maintain the old field and add the new one.
> BTS-1193 backport for 3.9

- arangod/Replication2/StateMachines/Document/DocumentLeaderState.cpp
- arangod/Replication2/StateMachines/Document/DocumentLeaderState.h
- arangod/RocksDBEngine/ReplicatedRocksDBTransactionCollection.cpp
- arangod/RocksDBEngine/ReplicatedRocksDBTransactionState.cpp
- arangod/Transaction/Methods.cpp
- tests/Replication2/ReplicatedState/DocumentStateMachineTest.cpp
Use explicit shards for replicated operations.
> [CINFRA-672] Use explicit shards for replicated operations.

- arangod/Pregel/Actor/CMakeLists.txt
- arangod/Pregel/Actor/README.md
- arangod/Pregel/Actor/include/Actor/Actor.h
- arangod/Pregel/Actor/include/Actor/ActorBase.h
- arangod/Pregel/Actor/include/Actor/ActorList.h
- arangod/Pregel/Actor/include/Actor/ActorPID.h
- arangod/Pregel/Actor/include/Actor/Assert.h
- arangod/Pregel/Actor/include/Actor/HandlerBase.h
- arangod/Pregel/Actor/include/Actor/MPSCQueue.h
- arangod/Pregel/Actor/include/Actor/Message.h
- arangod/Pregel/Actor/include/Actor/Runtime.h
- arangod/Pregel/CMakeLists.txt
- tests/CMakeLists.txt
- tests/Pregel/Actor/ActorListTest.cpp
- tests/Pregel/Actor/ActorTest.cpp
- tests/Pregel/Actor/Actors/FinishingActor.h
- tests/Pregel/Actor/Actors/PingPongActors.h
- tests/Pregel/Actor/Actors/SpawnActor.h
- tests/Pregel/Actor/Actors/TrivialActor.h
- tests/Pregel/Actor/CMakeLists.txt
- tests/Pregel/Actor/MPSCQueueTest.cpp
- tests/Pregel/Actor/MultiRuntimeTest.cpp
- tests/Pregel/Actor/RuntimeTest.cpp
- tests/Pregel/Actor/ThreadPoolScheduler.h
- tests/Pregel/CMakeLists.txt
Adds a self-written actor framework that implements the actor model.
This framework will be used for messaging in Pregel and will simplify the Pregel code. Several PRs will follow in which this framework will be used inside Pregel. In the long run it can be beneficial to use the C++ Actor Framework instead of our own implementation because it is much more powerful, but for the first usage we did not want to pull a full framework into ArangoDB.
The idea of the actor model is that you have several units of computation (the actors) that run concurrently and possibly distributed. Actors only interact via messages. In our implementation, an actor has a message queue where receiving messages are buffered. Inside the actor everything runs non-concurrently: An actor takes a message from the …
> [PREGEL] Add actor framework

- js/client/modules/@arangodb/testutils/instance-manager.js
- js/client/modules/@arangodb/testutils/instance.js
since CI allways dumps the agency and zip is cheaper and distributed than the final 7z, zip them right after getting them.
7z takes ~5 minutes on a successfull run, hopefully this improves that.
> [testing] compress agency dumps

- js/client/modules/@arangodb/testutils/result-processing.js
instead of
```
=== dump_encrypted ===
Incomplete testrun with these testsuites: 'dump_encrypted'
and these options: {"testOutput":"/work/ArangoDB/testrun/report/dump_encrypted","dumpAgencyOnError":true,"coreCheck":true,"disableMonitor":true,"writeXmlReport":true,"skipNondeterministic":true,"skipTimeCritical":true,"buildType":"RelWithDebInfo","minPort":13700,"maxPort":13799,"skipGrey":true,"onlyGrey":false,"testOutputDirectory":"/work/ArangoDB/testrun/report/dump_encrypted/","agencySize":3,"agencyWaitForSync":false,"agencySupervision":true,"build":"","cleanup":true,"cluster":false,"concurrency":3,"configDir":"etc/testing","coordinators":1,"coreDirectory":"/var/tmp","coreGen":true,"dbServers":2,"duration":10,"encryptionAtRest":false,"extraArgs":{},"extremeVerbosity":false,"force":true,"force …
```
> pimp testfailures.txt in fatal abort situation

- js/client/modules/@arangodb/testsuites/endpoints.js
we had ARM testruns where subsequent launches would overlap with old runs. give it more time.
> [testing]: it seems ARM tends to be slower on shutdown; lets give it some more time

- js/client/modules/@arangodb/testsuites/dump.js
- js/client/modules/@arangodb/testsuites/export.js
- js/client/modules/@arangodb/testsuites/server_permissions.js
- js/client/modules/@arangodb/testutils/instance-manager.js
- js/client/modules/@arangodb/testutils/instance.js
- tests/js/client/shell/shell-dump-integration.js
- tests/js/client/shell/shell-restore-integration.js
- dump tests would not cleanup their work data on success in all cases, fix this.
- export tests would not clean up their database directories
- server_permissions tests would not clean up temporary files created along with the tests
- `shell-dump-integration.js` & `shell-restore-integration.js` would not clean up
> [testing] make sure tests cleanup their instances directories and temporary files

- arangod/Cluster/ClusterInfo.cpp
- arangod/Cluster/ClusterInfo.h
- arangod/Cluster/CreateCollection.cpp
- arangod/Cluster/CreateCollection.h
- arangod/Cluster/Maintenance.cpp
- arangod/Replication2/StateMachines/Document/DocumentCore.cpp
- arangod/Replication2/StateMachines/Document/DocumentFollowerState.cpp
- arangod/Replication2/StateMachines/Document/DocumentLeaderState.cpp
- arangod/Replication2/StateMachines/Document/DocumentLeaderState.h
- arangod/Replication2/StateMachines/Document/DocumentLogEntry.h
- tests/Replication2/ReplicatedState/DocumentStateMachineTest.cpp
The purpose of this PR is to create a shard on the leader document state via the maintenance. The shard creation is then replicated and only then the shard is actually created. Followers will create the shard if they apply the corresponding log entry.
There will be two follow up PRs. Once for deleting a shard and another one for changing the collection properties of a shard.
> [CINFRA-656] CreateCollection on Leader Maintenance

- arangod/Auth/UserManager.cpp
- arangod/RestHandler/RestAdminRoutingHandler.cpp
- arangod/V8Server/CMakeLists.txt
- arangod/V8Server/GlobalContextMethods.cpp
- arangod/V8Server/GlobalContextMethods.h
- arangod/V8Server/V8Context.cpp
- arangod/V8Server/V8Context.h
- arangod/V8Server/V8DealerFeature.cpp
- arangod/V8Server/V8DealerFeature.h
- arangod/V8Server/v8-actions.cpp
- arangod/VocBase/Methods/AqlUserFunctions.cpp
- arangod/VocBase/Methods/AqlUserFunctions.h
- arangod/VocBase/Methods/Databases.cpp
- arangod/VocBase/Methods/Databases.h
- js/server/modules/@arangodb/foxx/manager.js
- lib/V8/JavaScriptSecurityContext.cpp
- lib/V8/JavaScriptSecurityContext.h
extract GlobalContextMethods from V8Context.h header and move it to a file of its own.
also simplify the implementation and do not allow using arbitrary GlobalContextMethods, but just the defined ones.
additionally add a few `noexcept` declarations and move a few functions from .h to .cpp files.
finally, move away from `char const*` and `std::string` in a few places and replace with `std::string_view`.
> extract GlobalContextMethods from V8Context.h header

- CHANGELOG
- arangod/Aql/AstNode.cpp
- arangod/Aql/AstNode.h
- arangod/Aql/Condition.cpp
- arangod/Aql/Condition.h
- arangod/Aql/ExecutionPlan.cpp
- arangod/Aql/Expression.cpp
- arangod/Aql/Expression.h
- arangod/Aql/GraphNode.cpp
- arangod/Aql/GraphNode.h
- arangod/Aql/OptimizerRules.cpp
- arangod/Aql/PruneExpressionEvaluator.cpp
- arangod/Aql/TraversalConditionFinder.cpp
- arangod/Aql/TraversalNode.cpp
- arangod/Aql/types.h
- js/common/modules/@arangodb/aql/explainer.js
- js/server/modules/@arangodb/testutils/aql-graph-traversal-generic-tests.js
- tests/js/common/aql/aql-graph-traverser-pruneTraversal.js
- tests/js/server/aql/aql-graph-traverser-complexFiltering.js
- tests/js/server/aql/aql-optimizer-rule-optimize-traversals-spec.js
Backport of https://github.com/arangodb/arangodb/pull/16622 
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/1206
Note: Includes additional fix for (#17291)
Note: also includes unrelated change (backport of https://github.com/arangodb/arangodb/pull/18088)
PR for some traversal optimizations. The PR includes the following changes regarding traversal filter conditions:
**Less post-filtering for vertex or edge filters**
Vertex or edge filters that were pulled into the traversal were previously not removed as post filters. 
That means the filter condition for vertex or edge filters was evaluated inside the traversal and _additionally_ as a post filter. This is unnecessarily expensive.
This PR fixes that, at least for simple filter conditions. Conditions such as `FILTER …
> Improve Filter optimizations on Traversals in AQL

- CHANGELOG
- arangod/Aql/OptimizerUtils.cpp
- tests/js/server/aql/aql-subquery.js
- tests/js/server/aql/aql-traversal-projections.js
Backport of https://github.com/arangodb/arangodb/pull/18090
Allow usage of projections in more cases
* Allow usage of document projections and traversal projections in slightly more cases, specifically when the document's or traversal's output variables were used in subqueries. Previously the usage of the document or traversal output variables in subqueries could lead to projections being disabled.
> Allow usage of projections in more cases

- tests/js/client/shell/multi/shell-inventory-cluster.js
- tests/test-definitions.txt
Some tests for cluster are not being executed since https://github.com/arangodb/arangodb/pull/17724.
This PR enable them.
But there is an open question: should we enable http2 and vst for testing them?
> Enable some cluster tests

- js/client/modules/@arangodb/testsuites/endpoints.js
ARM seems to need even more than 20s to shutdown arangod.
- increase timeout to 30s
- if we still fail, force shutdown so we see where its hanging about.
> increase timeout even more, add missing forced shutdown if we still fail

- CHANGELOG
- arangod/ClusterEngine/ClusterTransactionState.cpp
- arangod/RestHandler/RestDocumentHandler.cpp
- arangod/RestHandler/RestDocumentHandler.h
- arangod/Transaction/Methods.cpp
- arangod/V8Server/v8-collection.cpp
*FIXED: Concurrent batch insert/update CRUD operations into
SmartEdgeCollections on conflicting edge keys could get the
smart edge caching out-of-sync, which would yield different results
for OUTBOUND/INBOUND search over edges. This is now fixed, however there
is now a slightly higher chance to get a CONFLICT response back on those
queries.*
> Bug fix/3.10 smartedges race condition

- arangod/Cluster/CreateCollection.cpp
- arangod/Cluster/Maintenance.cpp
- arangod/Replication2/ReplicatedLog/LogCommon.h
- arangod/Replication2/StateMachines/Document/DocumentCore.cpp
- arangod/Replication2/StateMachines/Document/DocumentCore.h
- arangod/Replication2/StateMachines/Document/DocumentFollowerState.cpp
- arangod/Replication2/StateMachines/Document/DocumentFollowerState.h
- arangod/Replication2/StateMachines/Document/DocumentLeaderState.cpp
- arangod/Replication2/StateMachines/Document/DocumentLeaderState.h
- arangod/Replication2/StateMachines/Document/DocumentStateMachine.cpp
- arangod/Replication2/StateMachines/Document/DocumentStateSnapshotHandler.cpp
- arangod/Replication2/StateMachines/Document/DocumentStateSnapshotHandler.h
- arangod/Replication2/StateMachines/Document/ShardProperties.h
- tests/Replication2/Mocks/DocumentStateMocks.cpp
- tests/Replication2/Mocks/DocumentStateMocks.h
- tests/Replication2/ReplicatedState/DocumentStateMachineTest.cpp
We are adding support for multiple shards in `DocumentCore`. Until now, we used to have the `shardId` property for referencing the corresponding shard. This PR replaces that with a map, *ShardId -> ShardProperties*.
Because on the followers we create and drop shards through the use of log entries, we are now in a situation in which, during a replay of the log, a transaction might reference a dropped shard. Or, the follower tries to create an already existing shard. The document state checks for the existence of a shard before applying any transaction.
> [CINFRA-679] Document State Tracks Multiple Shards

- .circleci/config.yml
This should silence the CircleCI Github integration from spamming stable branches with failed runs.
> Add an empty .circleci/config.yml to 3.8 branch

- .circleci/config.yml
This should silence the CircleCI Github integration from spamming stable branches with failed runs.
> Add an empty .circleci/config.yml to 3.10 branch

- tests/Pregel/Actor/MPSCQueueTest.cpp
- tests/Pregel/Actor/MultiRuntimeTest.cpp
- tests/Pregel/Actor/RuntimeTest.cpp
ASAN/UBSAN detected a load of memory leaks, all caused by not shutting down the runtimes for actors. 
This patch fixes the immediate problem; We will look at better solutions for shutting down runtimes gracefully.
To verify this locally I used the following commands
```
```
> [GORDO-1518] Fix memory leak in tests

- CMakeLists.txt
- CMakePresets.json
* Add CMake presets to build with coverage
* Fix `CMakeLists.txt` to work when using clang.
> Coverage Presets, Small fix for CMakeLists.txt to work with clang

- scripts/build/arangodb-build.Dockerfile
Somehow the sccache links in the build container got lost - this PR fixes that.
Note - no build is needed for this PR. The container is already built and pushed and used in current CircleCI builds.
> Add missing sccache links

- arangod/Replication2/StateMachines/Document/DocumentLeaderState.cpp
The `createShard` and `dropShard` functions accessed the stream without acquiring the mutex first and thus could access the stream even after resign was called.
> [CINFRA] Create/DropShard vs resign mutex

- arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
Upgrade to latest version of velocypack, which changes naming in the IStringFromParts interface.
> upgrade velocypack to latest version

- arangod/Replication2/Supervision/CollectionGroupSupervision.cpp
- arangod/Replication2/Supervision/CollectionGroupSupervision.h
During a code review, we found that `version` of a replicated log in target was not incremented by the collection group supervision when it modified the target. This could lead to a _converged_ state, although the replicated log did not actually converge, yet.
> Fixing missing version increment.

- arangod/RestServer/DatabaseFeature.cpp
- arangod/VocBase/vocbase.cpp
- arangod/VocBase/vocbase.h
This PR fixes a shutdown hanger. The reason for the hanger was, that on a dropped database, replicated logs are not immediately resigned. This could cause the maintenance feature to wait for an action to finish, this action in turn waits for a replicated log to replicated some log entries. Since all other servers are already down, this is essentially a dead lock.
> Resign replicated logs when a database is dropped.

- arangod/Cluster/FollowerInfo.cpp
On replication two it can happen that a server has to take over leadership of a shard even though it is in the failover candidates (because failover candidates can be outdated and are not used for replication 2).
> [CINFRA] Maintenance TakeoverShardLeadership crash fix

- 3rdParty/linenoise-ng/LICENSE-wcwidth.txt
- 3rdParty/linenoise-ng/src/wcwidth.cpp
- LICENSES-OTHER-COMPONENTS.md
Update `wcwdith` function (used from `3rdParty/linenoise`) to the current version, maintained at https://github.com/termux/wcwidth/blob/master/wcwidth.c.
This adds support for Unicode 15.
> update wcwidth to current version

- js/common/modules/jsunity/jsunity.js
So far we will output the full javascript stacktrace with test-errors. 
most of this callstack contains references to boilerplate code we usually aren't interested in.
This PR: 
- will filter out any line containing `jsunity.js` - hence the function doing the assert itself, and any other from jsunity
- all lines in stackframes above `RunTest` (our main integration point to jsunity) 
- all lines in stackframes above `Object.run` (the integration point to the individual jsunity test cases, may be in the stack above `RunTest`)
So, from:
```
[FAILED]  enterprise/tests/js/common/aql/aql-arangosearch-views-nested-search.js
"testSubNested" failed: Error: at assertion #9: assertEqual: (6) is not equal to (3)
(Error
at assertEqual (/work/ArangoDB/js/common/modules/jsunity/jsunity.js:108:19)
at …
```
> [testing]: lean jsunity callstack

- CHANGELOG
- arangod/GeneralServer/CommTask.cpp
- arangod/GeneralServer/ServerSecurityFeature.cpp
- arangod/GeneralServer/ServerSecurityFeature.h
- arangod/Utils/ExecContext.cpp
- arangod/Utils/ExecContext.h
- arangod/V8Server/FoxxFeature.cpp
- arangod/V8Server/FoxxFeature.h
- tests/js/client/server_parameters/foxx-enable-false.js
- tests/js/client/server_parameters/foxx-enable-true.js
Implement https://arangodb.atlassian.net/browse/BTS-1249
* BTS-1249: Add startup option `--foxx.enable`. This startup option determines whether access to user-defined Foxx services is possible for the instance. It defaults to `true`. If the option is set to `false`, access to Foxx services is forbidden and will be responded with an HTTP 403 Forbidden error. Access to ArangoDB's built-in web interface, which is also a Foxx service, is still possible even with the option set to `false`. When setting the option to `false`, access to the management APIs for Foxx services will also be disabled. This is the same as manually setting the option `--foxx.api false`.
> BTS-1249: Add startup option `--foxx.enable`.

- js/common/modules/jsunity/jsunity.js
we would ignore exceptions in jsunity tearDownAll functions.
> QA-367: fix tearDownAll error reporting, lint

- CHANGELOG
- arangod/RestHandler/RestReplicationHandler.cpp
This is about https://arangodb.atlassian.net/browse/BTS-1232 .
Short description: 
arangorestore uses the (undocumented) API /_api/replication/restore-data
implemented in the RestReplicationHandler. Since ArangoDB 3.8, we
create new _rev values during the restore operation. Unfortunately,
this creation of _rev values was done on the coordinator(s) and since
these are hybrid logical clock (HLC) values, it can happen that the
generated _rev values on two different coordinators are the same for
two different documents. This will clash on the leader of the OneShard
database, since there, the newly generated _rev values are used as
internal document IDs, which directly translate into a RocksDB key in
the DocumentsColumnFamily. This leads to a collision and this manifests
itself as a lock …
> Fix arangorestore API to create _rev on shard leader [BTS-1232].

- arangod/Pregel/Actor/include/Actor/ActorPID.h
- arangod/Pregel/Actor/include/Actor/HandlerBase.h
- arangod/Pregel/Actor/include/Actor/Message.h
- arangod/Pregel/Actor/include/Actor/Runtime.h
- arangod/Pregel/ArangoExternalDispatcher.h
- arangod/Pregel/CMakeLists.txt
- arangod/Pregel/Conductor/Actor.h
- arangod/Pregel/Conductor/Conductor.cpp
- arangod/Pregel/Conductor/Messages.h
- arangod/Pregel/PregelFeature.cpp
- arangod/Pregel/PregelFeature.h
- arangod/Pregel/REST/RestPregelHandler.cpp
- arangod/Pregel/SpawnActor.h
- arangod/Pregel/SpawnMessages.h
- arangod/Pregel/Worker/Actor.h
- arangod/Pregel/Worker/Messages.h
- tests/Pregel/Actor/ActorTest.cpp
- tests/Pregel/Actor/Actors/TrivialActor.h
- tests/Pregel/Actor/MultiRuntimeTest.cpp
- tests/Pregel/Actor/RuntimeTest.cpp
Uses actor framework in pregel:
When the pregel run now starts, a conductor actor is started. As soon as the involved DBServers are known, one worker actor is started on each of these servers. The conductor and worker actors are currently very simple. Code from the worker and conductor will be moved into these actors in following PRs.
For that to work, this PR:
- Adds an external dispatcher for arangodb and handles messages from this external dispatcher in the RestPregelHandler.
- To send REST messages, we need the specific database we are working on. Therefore, the database is now part of the ActorPID.
- To spawn an actor on another server, we start a spawn actor on each involved server. Because of the database addition to our ActorPID, the spawn server needs to be specific per database, …
> [GORDO-1509] Use actor framework in pregel

- arangod/Pregel/Conductor/Conductor.cpp
- arangod/Pregel/Conductor/Conductor.h
- arangod/Pregel/PregelFeature.cpp
- arangod/Pregel/PregelFeature.h
- arangod/Pregel/PregelOptions.h
- arangod/Pregel/Worker/WorkerConfig.cpp
- arangod/Pregel/Worker/WorkerConfig.h
- tests/js/common/shell/shell-pregel-multicollection-edgecol.js
Combines all constant values of a pregel run in one struct to tidy up the conductor. For this, all theses constant value during a pregel run are specified in the feature, just before the conductor is created.
Additionally, I did some small cleanups like
- deleted redundant function input to Conductor::initializeWorkers
- deleted unused method Conductor::ensureUniqueResponse(VPackSlice)
> [PREGEL] Use struct for pregel constants

- tests/js/server/aql/aql-geo.js
Backport for https://github.com/arangodb/arangodb/pull/18218.
This PR removes a comment from a test after the fix for BTS-1184 in https://github.com/arangodb/arangodb/pull/18086.
> Removed comment from test in BTS-1184 3.10 backport

- .circleci/base_config.yml
Before this change, because of how the shell is configured in a CircleCI step, a non-zero exit code from the test runner would lead to test-result XMLs not being uploaded.
> Make sure testresults are also copied when test fails

- arangod/Replication/ReplicationClients.cpp
- arangod/RocksDBEngine/RocksDBMetaCollection.cpp
Improve usefulness of a replication debug message, which previously was only available in maintainer builds.
Also add a missing space character to another debug message.
> improve usefulness of debug messages

- utils/jslint.sh
Adjust jslint script to not search for files in now-nonexisting directory `UnitTests`.
> don't try to jslint files in UnitTests

- .circleci/base_config.yml
Install GDB in the docker runners for tests to be able to pull stack traces.
> Install GDB in testing dockers

- CHANGELOG
- Documentation/Metrics/arangodb_replication_clients.yaml
- arangod/Replication/ReplicationClients.cpp
- arangod/Replication/ReplicationClients.h
- arangod/Replication/ReplicationFeature.cpp
- arangod/Replication/ReplicationFeature.h
- arangod/RocksDBEngine/RocksDBBackgroundThread.cpp
- arangod/RocksDBEngine/RocksDBEngine.cpp
- arangod/RocksDBEngine/RocksDBMetadata.cpp
- arangod/RocksDBEngine/RocksDBSettingsManager.cpp
- arangod/VocBase/vocbase.cpp
- tests/Replication/ReplicationClientsProgressTrackerTest.cpp
Backport of https://github.com/arangodb/arangodb/pull/18223
Better diagnostics for tracking WAL lower bound values.
* Added log messages for per-database replication lower bound-influencing values
* Added log messages for per-collection/shard lower bound-influencing values
* Added metric `arangodb_replication_clients` showing the number of currently active/connected replication clients for a server.
The additional log messages will only appear when log topic `ENGINES` is set to `DEBUG` or lower.
Manually tested in cluster and single server.
> Added metric for observing the number of replication clients

- tests/js/common/shell/multi/shell-ttl.js
The coverage runs can't cope with the amount of data that well.
> reduce the number of elements and timeout for the coverage runs

- tests/Replication2/Helper/ModelChecker/Actors.cpp
GCC 11.3 will complain about this uninitialized variable.
> Silence compiler warning

- tests/Replication2/Helper/ModelChecker/Actors.cpp
GCC 11.3 will complain about this uninitialised variable.
> Silence Compiler Warning (forward port to staging branch)

- tests/js/common/shell/shell-prototype-state-cluster.js
This tests is based on dirty reads and therefore it has been seen failing sometimes. To decrease the chance of that happening, I am instructing the state to wait for the entries to be committed before returning from the write call.
> [CINFRA] Prototype State Flaky Test

- js/client/modules/@arangodb/testutils/result-processing.js
If the testsuite run aborts on crash or timeout, the generated XML would not reflect this error.
> testing: SKIPPED testcase should now indicate the full error

- arangod/Replication2/ReplicatedLog/Components/AppendEntriesManager.cpp
- arangod/Replication2/ReplicatedLog/Components/AppendEntriesManager.h
- arangod/Replication2/ReplicatedLog/Components/IAppendEntriesManager.h
- arangod/Replication2/ReplicatedLog/Components/LogFollower.cpp
- tests/Replication2/ReplicatedLog/LogFollower/AppendEntriesTest.cpp
During work on tests in https://github.com/arangodb/arangodb/pull/18215, two bugs manifested in the follower component AppendEntriesManager.
1) If one of the `store` operations `removeBack` or `appendEntries` returned an error, the `guard` variable was accessed before it was locked again, resulting in a nullptr-deref.
2) Additionally in the same situation, if the follower already resigned, the snapshot manager was accessed - however, this is a (possible) use-after-free, as the managers might be destroyed after resign.
> [CINFRA-696] Fix crashes in AppendEntriesManager on store errors or resign race

- arangod/Replication2/ReplicatedLog/Components/LogFollower.cpp
- arangod/Replication2/ReplicatedLog/Components/SnapshotManager.cpp
- arangod/Replication2/ReplicatedLog/Components/SnapshotManager.h
- tests/Replication2/ReplicatedLog/Components/SnapshotManagerTest.cpp
The LogFollower calls becomeFollower() on the state handle in its constructor. But the snapshot manager is constructed before that, which in turn called acquireSnapshot() on that state handle. However, the acquireSnapshot call must be delegated to the FollowerStateManager, which is constructed only during becomeFollower. This PR fixes that order.
> [CINFRA-699] Call acquireSnapshot after becomeFollower

- .circleci/base_config.yml
CircleCI executes the steps in a test one at a time, but by default skips remaining steps on failure.
The `when` attribute ensures we upload test results (if they are available).
> Upload test results even if test fails

- tests/js/common/shell/multi/shell-query-spec.js
Tixed error in query-test spec if it runs too long.
The test failed on Windows with an unexpected query runtime of 141s: https://jenkins.arangodb.biz/job/arangodb-matrix-pr-windows/20295/
> fixed error in query-test spec if it runs too long

- client-tools/Shell/ClientFeature.cpp
when starting arangosh with `--server.endpoint none`, the user explicitly asks for no endpoint to connect to.
previously doing so caused an error message when starting the shell: `invalid value for --server.endpoint (none)`.
the message is now suppressed, because it is not relevant.
> suppress a useless error message

- tests/js/common/shell/multi/shell-query-spec.js
on Windows, 5000 * 0.0001s of sleep produces a runtime of 79s. :clap: :clap: :clap:
The specific test case does not exist in 3.10 or previous versions. Thus no backports needed.
> fix test failure on windows

- CHANGELOG
- Documentation/Metrics/arangodb_flush_subscriptions.yaml
- Documentation/Metrics/rocksdb_live_wal_files.yaml
- Documentation/Metrics/rocksdb_wal_released_tick_flush.yaml
- Documentation/Metrics/rocksdb_wal_released_tick_replication.yaml
- arangod/IResearch/IResearchLink.cpp
- arangod/RestServer/FlushFeature.cpp
- arangod/RestServer/FlushFeature.h
- arangod/RocksDBEngine/RocksDBBackgroundThread.cpp
- arangod/RocksDBEngine/RocksDBBackgroundThread.h
- arangod/RocksDBEngine/RocksDBBuilderIndex.cpp
- arangod/RocksDBEngine/RocksDBEngine.cpp
- arangod/RocksDBEngine/RocksDBEngine.h
- tests/RestServer/FlushFeature-test.cpp
Backport of most of https://github.com/arangodb/arangodb/pull/18269
Adds more log messages for log topic `engines` in DEBUG and TRACE mode to see what's going on w.r.t. to pruning obsolete WAL files. 
Adds the following new metrics for tracking WAL files:
- `rocksdb_live_wal_files`: number of alive WAL files (not archived)
- `rocksdb_wal_released_tick_flush`: lower bound sequence number from which
onwards WAL files will be kept (i.e. not deleted from the archive) because
of external flushing needs. Candidates for these are arangosearch links
and background index creation.
- `rocksdb_wal_released_tick_replication`: lower bound sequence number from
which onwards WAL files will be kept because they may be needed by the
replication.
- `arangodb_flush_subscriptions`: number of currently active …
> add more transparency for WAL file deletions

- CHANGELOG
- arangod/ClusterEngine/ClusterEngine.h
- arangod/RocksDBEngine/RocksDBBackgroundThread.cpp
- arangod/RocksDBEngine/RocksDBEngine.cpp
- arangod/RocksDBEngine/RocksDBEngine.h
- arangod/RocksDBEngine/RocksDBRestWalHandler.cpp
Backport of https://github.com/arangodb/arangodb/pull/18299
* Auto-flush RocksDB WAL files and in-memory column family data if the number of live WAL files exceeds a certain threshold. This is to make sure that WAL files are moved to the archive when there are a lot of live WAL files present (e.g. after a restart; in this case RocksDB does not count any previously existing WAL files when calculating the size of WAL files and comparing it `max_total_wal_size`. The feature can be configured via the following startup options:
- `--rocksdb.auto-flush-min-live-wal-files`: minimum number of live WAL files that triggers an auto-flush. Defaults to `10`.
- `--rocksdb.auto-flush-check-interval`: interval (in seconds) in which auto-flushes are executed. Defaults to `3600`. Note that an auto-flush is …
> Auto-flushing of WAL and column family data

- arangod/RestServer/DatabaseFeature.cpp
Add missing version info to startup option
Reference: https://github.com/arangodb/arangodb/pull/16060
> Docs: Add 3.9.2 as version for `--database.io-heartbeat`

- tests/js/server/replication2/replication2-regression.js
Two tests did not drop the replicated logs they created.
> Add missing deleteLog code for tests.

- CMakeLists.txt
Don't loose `EXTRA_*_FLAGS` in favor of external `-DCMAKE_*_FLAGS` usage when options are provided outside.
> Don't loose EXTRA_*_FLAGS in favor of external -DCMAKE_*_FLAGS usage (3.8)

- CMakeLists.txt
Don't loose `EXTRA_*_FLAGS` in favor of external `-DCMAKE_*_FLAGS` usage when options are provided outside.
> Don't loose EXTRA_*_FLAGS in favor of external -DCMAKE_*_FLAGS usage (3.9)

- CMakeLists.txt
Don't loose `EXTRA_*_FLAGS` in favor of external `-DCMAKE_*_FLAGS` usage when options are provided outside.
> Don't loose EXTRA_*_FLAGS in favor of external -DCMAKE_*_FLAGS usage (3.10)

- arangod/Cluster/Utils/EvenDistribution.cpp
- arangod/Replication2/Supervision/CollectionGroupSupervision.cpp
*Fix _system database _system collections in Replication 2*
*Actually added error handling in case no servers are available when creating a Collection*
> Error hanlding if no DBServers are available for CollectionCreation

- arangod/VocBase/LogicalCollection.cpp
- lib/Rest/GeneralResponse.cpp
Previously when a replicated state was not yet available the server would return an internal server error. However, usually this is just a temporary condition, so 503 is more applicable.
> Return service unavailable if state is unavailable.

- Documentation/DocuBlocks/Rest/Graph/general_graph_edge_create_http_examples.md
Backport of https://github.com/arangodb/arangodb/pull/18318/
Adjust DocuBlock to reflect behavior since https://github.com/arangodb/arangodb/pull/16790
> BTS-325 | Docs: Referencing a vertex collection in _from/_to that is not in named graph returns 404

- CHANGELOG
- arangod/Aql/EngineInfoContainerDBServerServerBased.cpp
- arangod/Cluster/ClusterInfo.cpp
- arangod/Cluster/ClusterInfo.h
- tests/js/server/resilience/failover-view/resilience-synchronous-repl-with-arangosearch-view-cluster.js
- tests/js/server/resilience/failover/resilience-synchronous-repl-cluster.inc
This is about https://arangodb.atlassian.net/browse/BTS-1235
An investigation has shown the following: It is not safe to assume that
running an AQL query directly after a leader of a collection has been
stopped (before the failover has happened). In many cases this works, 
because the query optimizer has to query collection counts or
selectivity estimates before running the query and these can be retried
until the failover has happened. But if these values are cached on the
coordinator, the query directly proceeds to run on the supposed leader
of the collections in question. And if this leader is failed but no
failover has happened yet, the query will run into an error.
The fix in this PR acknowledges this fact of life and adjusts the
resilience tests accordingly, making them more stable. …
> Make resilience tests stable again [BTS-1235].

- arangod/Cluster/CreateCollection.cpp
- arangod/VocBase/LogicalCollection.cpp
- tests/js/client/restart/test-restart-replication2-database.js
This PR does two things:
1. it stores the replicated state id as part of the persisted information of a shard. During restart this information is loaded, if available.
2. The maintenance now passes the replicated state id directly during collection construction and does not set if after the fact.
> [CINFRA] LogicalCollection Shard store replicated state id

- arangod/Replication2/ReplicatedLog/Components/FollowerCommitManager.cpp
- arangod/Replication2/ReplicatedLog/Components/LogFollower.cpp
- arangod/Replication2/ReplicatedLog/Components/LogFollower.h
- arangod/Replication2/ReplicatedLog/ReplicatedLog.cpp
- tests/Replication2/ReplicatedLog/LogFollower/AppendEntriesTest.cpp
The Follower Manager used a default constructed LoggerContext, which is missing crutial information. Now it inherits the logger context from the replicated log.
> Forward correct logger context to Follower Manager.

- tests/js/server/shell/shell-general-graph-creation-cluster.js
creating the maximum number of available shards with the preconfigured number of replications is quiet resource intense. 
Disable replication for this test, since it primarily wants to check whether the limit is respected.
> if shell-general-graph-creation-cluster.js is ran with coverage instrumented binaries, this test will not finish any time soon

- arangod/Agency/AsyncAgencyComm.cpp
Backport of https://github.com/arangodb/arangodb/pull/14891
This is a trivial bug fix for a corner case.
If in maintainer mode, or if the log topic AgencyComm is set to DEBUG
or TRACE mode, and all agents are gone, then the first element of
an empty deque is dereferenced. With STL debugging on this leads to
a crash.
> Fix some undefined behaviour in some maintainer mode code (#14891)

- arangod/Aql/ExecutionEngine.cpp
- arangod/Aql/Query.cpp
- arangod/Cluster/ClusterTrxMethods.cpp
- arangod/Cluster/TakeoverShardLeadership.cpp
Simplify some assertion code that uses substr() and compare() for string prefix checking.
> use std::string::starts_with

- arangod/Agency/CleanOutServer.cpp
- arangod/VocBase/VocBaseLogManager.cpp
- tests/Agency/CleanOutServerTest.json
There is currently a [problem ](https://jenkins01.arangodb.biz/job/arangodb-matrix-pr-mac-onlycatch.x86-64/23685/EDITION=enterprise,limit=mac&&test&&x86-64/artifact/buildArangoDB.log)with our branch building on mac.
Jenkins run on mac: https://jenkins.arangodb.biz:3456/job/arangodb-matrix-pr-mac-onlycatch.x86-64/23700/
> [CINFRA] Fixing mac build

- arangod/Utils/SupportInfoBuilder.cpp
- lib/SimpleHttpClient/GeneralClientConnection.cpp
A few very small improvements:
* `GeneralClientConnection::factory()` will always return a connection object now, or throw an exception in case an invalid encryption type was used. The latter should never happen in practice. However, the caller of the function can now be sure that the function will either return a new connection object, or throw. It can never return a nullptr anymore, so callers don't need to check for that.
* remove "unknown" collections from telemetrics, because they don't exist. Collections are either document collections or edge collections.
* avoid the creation of an std::vector in an inner loop, and simply use a constexpr std::array instead. This is more efficient.
> very small improvements for telemetrics

- arangod/Pregel/Conductor/ExecutionStates/CollectionLookup.h
- arangod/Pregel/Conductor/ExecutionStates/CreateWorkersState.cpp
- arangod/Pregel/Conductor/ExecutionStates/CreateWorkersState.h
- arangod/Pregel/Conductor/ExecutionStates/LoadingState.cpp
- arangod/Pregel/Conductor/ExecutionStates/LoadingState.h
- arangod/Pregel/Conductor/Handler.h
- arangod/Pregel/Conductor/Messages.h
- arangod/Pregel/DatabaseTypes.h
- arangod/Pregel/OutgoingCache.cpp
- arangod/Pregel/OutgoingCache.h
- arangod/Pregel/Statistics.h
- arangod/Pregel/VertexComputation.h
- arangod/Pregel/Worker/Handler.h
- arangod/Pregel/Worker/Messages.h
- arangod/Pregel/Worker/State.h
- arangod/Pregel/Worker/Worker.cpp
- arangod/Pregel/Worker/WorkerConfig.h
- arangod/Pregel/WorkerContext.h
This PR adds code in the worker actor to execute one gss - so everything between getting the message RunGlobalSuperStep from the conductor and sending GlobalSuperStepFinished message back to the conductor.
Additionally, some preparation is needed for this to work: The conductor CreateWorkers execution state now keeps track of which worker actors are responsible for which shards, gives this information to the Loading execution state which sends this information to all workers. This information is needed inside each worker because workers send messages around to other workers and in the actor framework they have to know to which actor they should send these messages to.
This PR also adds two actor-specific OutCaches: ArrayOutActorCache (for sending arrays of messages) and …
> [GORDO-1549] Execute one gss in worker

- arangod/Replication/DatabaseInitialSyncer.cpp
- js/client/modules/@arangodb/testsuites/replication.js
- tests/js/server/replication/sync/replication-sync-malarkey.inc
- tests/js/server/replication/sync/replication-sync.js
single-to-single replication that used HTTP authentication to authenticate requests on the leader could be broken if the collections on the leader were created with 3.8 or later, and thus used the Merkle tree protocol to exchange different document revisions. the revisions API was extended with a document prefetching capability about a year ago, and this prefetching capability uses the NetworkFeature to send the requests out to the leader. The NetworkFeature does not support HTTP authentication however, so on a leader that used HTTP authentication, the requests were rejected with HTTP 401 or HTTP 403, and replication failed.
when using JWTs, everything worked fine, but the single-to-single replication also support HTTP authentication with different credentials per database. …
> fix single-to-single replication with authentication

- arangod/Replication2/ReplicatedLog/Components/AppendEntriesManager.cpp
- arangod/Replication2/ReplicatedLog/Supervision.cpp
- arangod/Replication2/StateMachines/Document/DocumentStateNetworkHandler.cpp
- arangod/Replication2/StateMachines/Document/DocumentStateShardHandler.cpp
- tests/Replication2/ReplicatedLog/Supervision/SupervisionTest.cpp
In some cases the supervision excluded a server from the quorum. If not all snapshots are available, this could create a deadlock.
Therefore we only consider excluding a server from the quorum, when after the exclusion there is still enough participants with a snapshot.
Additionally, if the flag `allowedInQuorum=false` is already in place, we undo it, _unless_ it was specified by the user in Target.
> [CINFRA-715] Supervision Deadlock Snapshot Missing

- CHANGELOG
- arangod/Network/ConnectionPool.cpp
- arangod/Network/ConnectionPool.h
- tests/Network/ConnectionPoolTest.cpp
Backport of https://github.com/arangodb/arangodb/pull/18394
The metric for the number of connections in the pool (arangodb_connection_pool_connections_current) was not counted down properly in case all connections to a specific endpoint (IP address + port) were canceled. Cancelation happens when another DB server or coordinator, identified by its IP address + port, is identified as “failed”. That happens, for example, a few seconds after a process crash or after a process is being OOM-killed by the OOM killer.
In this cases, the connections to the failed server were correctly closed, but the metric for the number of connections in the pool was not counted down at all. So even though the connections were effectively gone, due to the wrong metric values returned, it may have seemed that …
> BTS-1272: correct counting of connections in pool

- arangod/Pregel/Algorithm.h
- arangod/Pregel/Conductor/ExecutionStates/ComputingState.cpp
- arangod/Pregel/Conductor/ExecutionStates/LoadingState.cpp
- arangod/Pregel/Conductor/ExecutionStates/StoringState.h
- arangod/Pregel/Conductor/Handler.h
- arangod/Pregel/Conductor/Messages.h
- arangod/Pregel/MasterContext.h
In the Computing conductor state: After all workers send a GlobalSuperStepFinshed message to the conductor, the Computing state decides how to continue:
- Start next super step by creating a new Computation state or
- Finish computation and change into Storing state (if pregel results should be stored in database) or
- Finish computation and change into ProduceAqlResults state (if pregel results should *not* be stored in database).
> [GORDO-1549] Finish gss and decide how to continue in conductor

- arangod/RestServer/FlushFeature.cpp
- arangod/RocksDBEngine/RocksDBEngine.cpp
Backport of https://github.com/arangodb/arangodb/pull/18346
add more TRACE logging at startup to emit collection and views metadata.
> add more TRACE logging at startup for collection metadata

- arangod/Replication2/ReplicatedLog/Components/FollowerCommitManager.cpp
- arangod/Replication2/ReplicatedLog/Components/FollowerCommitManager.h
- arangod/Replication2/ReplicatedLog/Components/IStorageManager.h
- arangod/Replication2/ReplicatedLog/Components/LogFollower.cpp
- arangod/Replication2/ReplicatedLog/Components/StorageManager.cpp
- arangod/Replication2/ReplicatedLog/Components/StorageManager.h
- tests/Replication2/ReplicatedLog/Components/CompactionManagerTest.cpp
- tests/Replication2/ReplicatedLog/Components/FollowerCommitManagerTest.cpp
- tests/Replication2/ReplicatedLog/Components/SnapshotManagerTest.cpp
Finaly step of evicting log entries from memory is to remove the function `getCommittedLog`. After that, it is no longer possible to get a _global_ view of the entire log at once, but instead the only option is to receive a log iterator. 
This iterator can be served from disk easily.
> [CINFRA] Remove getCommittedLog finally.

- CHANGELOG
- arangod/Pregel/Conductor/Conductor.cpp
- arangod/Pregel/Conductor/ExecutionStates/CreateWorkersState.cpp
- arangod/Pregel/PregelFeature.cpp
- arangod/Pregel/PregelFeature.h
- arangod/Pregel/PregelOptions.h
- arangod/Pregel/Utils.cpp
- arangod/Pregel/Utils.h
- arangod/Pregel/Worker/Messages.h
- arangod/Pregel/Worker/WorkerConfig.cpp
- arangod/Pregel/Worker/WorkerConfig.h
We do not support memory mapped files for Pregel anymore, so mark the command line options obsolete and remove the Pregel parameter in other places too.
> Mark mmaped-files commandline options obsolete

- arangod/Replication2/ReplicatedLog/Components/AppendEntriesManager.cpp
- arangod/Replication2/ReplicatedLog/Components/IStorageManager.h
- arangod/Replication2/ReplicatedLog/Components/StorageManager.cpp
- arangod/Replication2/ReplicatedLog/Components/StorageManager.h
- arangod/Replication2/ReplicatedLog/TermIndexMapping.cpp
- arangod/Replication2/ReplicatedLog/TermIndexMapping.h
- tests/Replication2/ReplicatedLog/Components/CompactionManagerTest.cpp
- tests/Replication2/ReplicatedLog/Components/SnapshotManagerTest.cpp
Remove all InMemoryLogs from StorageManager. On the leader on the uncommitted and not locally persisted log entries reside in memory. On the follower, only those not yet persisted.
> [CINFRA] Remove InMemoryLogs from StorageManager

- arangod/Pregel/Conductor/ExecutionStates/AQLResultsAvailableState.cpp
- arangod/Pregel/Conductor/ExecutionStates/AQLResultsAvailableState.h
- arangod/Pregel/Conductor/ExecutionStates/CMakeLists.txt
- arangod/Pregel/Conductor/ExecutionStates/CanceledState.cpp
- arangod/Pregel/Conductor/ExecutionStates/CanceledState.h
- arangod/Pregel/Conductor/ExecutionStates/CleanedUpState.h
- arangod/Pregel/Conductor/ExecutionStates/DoneState.cpp
- arangod/Pregel/Conductor/ExecutionStates/DoneState.h
- arangod/Pregel/Conductor/ExecutionStates/FatalErrorState.cpp
- arangod/Pregel/Conductor/ExecutionStates/FatalErrorState.h
- arangod/Pregel/Conductor/ExecutionStates/StoringState.cpp
- arangod/Pregel/Conductor/Handler.h
- arangod/Pregel/Conductor/Messages.h
- arangod/Pregel/ResultMessages.h
- arangod/Pregel/SpawnActor.h
- arangod/Pregel/SpawnMessages.h
- arangod/Pregel/Worker/Handler.h
- arangod/Pregel/Worker/Messages.h
- arangod/Pregel/Worker/State.h
Adds cancel state that cleans up worker and spawn actors (meaning they are set to finished, such that garbage collection can delete them).
I changed all other final states (Done, FatalError and AQLResultsAvailable) do the same cleanup.
When the cleanup is finished in all these states, the conductor changes its execution state to Finished state, which cleans up the conductor.
> [GORDO-1552] Implement conductor canceled state

- CHANGELOG
- arangod/Cluster/ClusterInfo.cpp
- arangod/Cluster/Maintenance.cpp
- arangod/VocBase/Methods/Databases.cpp
- arangod/VocBase/VocbaseInfo.cpp
- arangod/VocBase/VocbaseInfo.h
- js/client/modules/@arangodb/test-helper.js
- tests/js/client/server_parameters/database-invalid-replication-factor-cluster.js
Backport of https://github.com/arangodb/arangodb/pull/18431
When a database has made it into the Plan part of the agency with some settings, e.g. `replicationFactor` that would violate the current settings for databases (e.g. `--cluster.min-replication-factor` and `--cluster.max-replication-factor`), and then a new DB server is added, it will try to create the database locally with the settings from the Plan.
As these settings however violate the min/max replication factor values, the database is not created on the new DB server and an error is written into Current instead.
This can cause follow-up errors and the PlanSyncer complaining about missing databases for analyzers etc.
> fix issues with deferred database creation

- arangod/Replication2/StateMachines/Document/DocumentFollowerState.cpp
- tests/Replication2/ReplicatedState/DocumentStateMachineTest.cpp
On a former leader, there could still be some transactions open. If a snapshot transfer is required, the open transactions prevent dropping the shards.
This is a quick fix for this. In future the transaction handler should be stored in the Leader/Follower and not in the core, since transactions are explicitly not shared between terms.
> [CINFRA] QuickFix for deadlock

- scripts/cluster-run-common.sh
- scripts/startLocalCluster.sh
Add `-r|--replication-version` parameter to the `startLocalCluster.sh` script. If not set, the default replication version is used.
> Add replication-version parameter to startLocalCluster.sh

- js/client/modules/@arangodb/testsuites/endpoints.js
we found out startup may be slow inside of rocksdb, drill further down.
> testing: enable rocksdb logging

- arangod/Replication2/ReplicatedLog/Components/CompactionManager.cpp
- arangod/Replication2/ReplicatedState/ReplicatedState.tpp
1. Fix a deadlock in the compaction manager. 
2. Move the iterator creation into a separate thread. This should reduce the appendEntries roundtrip time.
> [CINFRA] Compaction Manager Deadlock

- arangod/Pregel/Worker/Handler.h
Moves a log statement before a return statement, which resulted in spurious errors.
> [PREGEL bugfix] Move log before return

- CHANGELOG
- arangod/Cache/Cache.cpp
- arangod/Cache/Cache.h
- arangod/Cache/Manager.cpp
- arangod/Cache/Manager.h
- arangod/Cache/ManagerTasks.cpp
- arangod/Cache/ManagerTasks.h
- arangod/Cache/Metadata.cpp
- arangod/Cache/Table.cpp
- arangod/Cache/Table.h
This reverts commit 05c2154505a1a330169317c9b4e7ddde7495d633.
This change had unintended side effects.
Reverting the commit may bring back assertion failures in the in-memory cache in maintainer mode during Jenkins test runs.
> Revert "fix races in in-memory cache system (#18243) (#18265)"

- arangod/Cache/Cache.cpp
- arangod/Cache/Cache.h
- arangod/Cache/Manager.cpp
- arangod/Cache/Manager.h
- arangod/Cache/ManagerTasks.cpp
- arangod/Cache/ManagerTasks.h
- arangod/Cache/Metadata.cpp
- arangod/Cache/Table.cpp
- arangod/Cache/Table.h
This reverts commit ebb6b47a9b03bfed439772465508696ccb0761f2.
This change had unintended side effects.
Reverting the commit may bring back assertion failures in the in-memory cache in maintainer mode during Jenkins test runs.
> Revert "fix races in in-memory cache system (#18243)"

- arangod/Replication2/ReplicatedLog/Components/AppendEntriesManager.cpp
- arangod/Replication2/ReplicatedLog/LogLeader.cpp
- arangod/Replication2/ReplicatedState/ReplicatedState.tpp
- arangod/Replication2/StateMachines/Document/DocumentFollowerState.cpp
1. Sometimes a follower refuses to accept an append entries, because a previous one is still in flight. This is because the `requestGuard` was not reset explicitly at the end of the coroutine. It would then be reset once the coroutine is destroyed and (similar to futures) this can happen whenever the system feels like.
2. `recoverEntries` can deadlock with `updateCommitIndex`. However, `updateCommitIndex` is not used on the leader, therefore I removed the call (for now),
3. If we post the append entries on the scheduler, we have to make sure that the methods are still there. Otherwise we might get a nullptr access.
> [CINFRA] Deadlock 456823

- scripts/unittest
Running `scripts/unittest <testsuite>` was broken since the last commit to `scripts/unittest`. Fix it.
> fix running tests

- arangod/Replication2/ReplicatedLog/Supervision.cpp
- arangod/Replication2/ReplicatedLog/SupervisionContext.h
- js/common/modules/@arangodb/testutils/replicated-logs-helper.js
- tests/js/server/replication2/replication2-supervision-replicated-log-target-cluster.js
When a server was selected as leader in the target, but also had the flag `allowedAsLeader: false`, the Supervision still set `forced: true` as a first step for the leader change. This is then immediately reverted, assuming its target config has `forced: false`. This flaps back and forth endlessly as long as the target configuration stays unchanged.
> [CINFRA-724] Prevent flag flapping

- arangod/Replication2/ReplicatedLog/Supervision.cpp
- arangod/RestHandler/RestReplicationHandler.cpp
- tests/Replication2/Helper/ModelChecker/AgencyState.h
- tests/Replication2/Helper/ModelChecker/AgencyTransition.cpp
- tests/Replication2/Helper/ModelChecker/Predicates.h
- tests/Replication2/ModelChecker/ModelChecker.h
- tests/Replication2/ModelChecker/Predicates.h
- tests/Replication2/ReplicatedLog/Supervision/SupervisionSimulationTest.cpp
- tests/js/server/replication2/replication2-supervision-replicated-log-target-cluster.js
When the existing leader in a replicated log is replaced by a dbserver that's not a participant yet, it usually comes to two leader switches. This is because the previous leader is also removed as a participant from the log. So while the new server is not yet ready to become a leader (it hasn't fetched all necessary data yet), the old one is already removed and thus replaced by some of the other participants first, only to be replaced shortly after by the intended one.
While the current behavior is correct - it does not loose data, and it arrives at the targeted configuration - the first leader switch is undesirable, at least because it has an avoidable service interruption. It's also a small avoidable amount of work for the cluster.
> [CINFRA-717] Avoid double leader switch

- js/client/modules/@arangodb/test-helper.js
- js/client/modules/@arangodb/testutils/testing.js
flush instanceInfo after a test suite is done
because otherwise tests may refer to outdated instanceInfo if suites start different sets of servers
> flush instanceInfo after a test suite is done

- arangod/Scheduler/SupervisedScheduler.cpp
Properly count down the value of `_jobsSubmitted` in case adding to the scheduler's queue failed and threw an exception.
> properly decrease _jobsSubmitted if we can't submit to q

- Documentation/Metrics/arangodb_replication2_replicated_log_append_entries_num_entries.yaml
- Documentation/Metrics/arangodb_replication2_replicated_log_append_entries_size.yaml
- Documentation/Metrics/arangodb_replication2_replicated_log_follower_entry_drop_count.yaml
- Documentation/Metrics/arangodb_replication2_replicated_log_leader_append_entries_error_count.yaml
- arangod/Replication2/ReplicatedLog/Components/AppendEntriesManager.cpp
- arangod/Replication2/ReplicatedLog/Components/StorageManager.cpp
- arangod/Replication2/ReplicatedLog/LogLeader.cpp
- arangod/Replication2/ReplicatedLog/ReplicatedLogMetrics.h
- arangod/Replication2/ReplicatedLog/ReplicatedLogMetrics.tpp
- arangod/Replication2/ReplicatedLog/ReplicatedLogMetricsDeclarations.h
This PR adds four new metrics:
1. Histogram of number of log entries per append-entries request
2. Histogram of append-entries request sizes
3. Number of log entries dropped by a follower before appending the log
4. Number of failed append-entries requests (only counting true errors, not NoPrevLogMatch)
> [CINFRA] Added more metrics to the log leader.

- arangod/Replication2/AgencyCollectionSpecification.h
- arangod/Replication2/ReplicatedLog/Supervision.cpp
- tests/Replication2/ReplicatedLog/Supervision/SupervisionTest.cpp
- tests/js/server/replication2/replication2-supervision-replicated-log-target-cluster.js
Previously, a server that should be removed couldn't be if `softWriteConcern == replicationFactor`.
> [CINFRA-723] Remove unwanted server if possible

- arangod/Pregel/PregelFeature.cpp
- arangod/Pregel/PregelFeature.h
- arangod/Pregel/REST/RestControlPregelHandler.cpp
- arangod/Pregel/REST/RestPregelHandler.cpp
- arangod/Pregel/StatusActor.h
- arangod/Pregel/StatusMessages.h
- arangod/V8Server/v8-pregel.cpp
Adds a new status actor for every conductor.
If a pregel run ist started using actors, the pregel status is provided by the state this actor.
> [GORDO-1596] Query pregel actor status

- arangod/Cluster/ClusterInfo.cpp
- arangod/Cluster/ClusterInfo.h
Currently the supervision for collection groups updates the shard map in plan. This shard map is copied by the leader into current. This will always contains the correct server as leader. Thus we can rely on the replication 1 way of looking up the shard.
This is much simpler than the previous code and it is correct! Once we got rid of the old shard map, we have touch this code anyways again.
> [CINFRA-700] Fix getResponsibleServer by relying on the supervision.

- arangod/Cluster/Maintenance.cpp
- arangod/Replication2/ReplicatedLog/LogLeader.cpp
- arangod/Replication2/ReplicatedLog/LogStatus.h
The goal of this PR is to fix the display of servers in the webui for a given shard. We only want to report those servers in current that actually have received a snapshot from the leader (or already have one).
> [CINFRA-726] Expose snapshot status as part of the leader status.

- arangod/Pregel/Actor/include/Actor/ActorList.h
- arangod/Pregel/Actor/include/Actor/Runtime.h
- arangod/Pregel/Conductor/ExecutionStates/AQLResultsAvailableState.h
- arangod/Pregel/Conductor/ExecutionStates/CanceledState.cpp
- arangod/Pregel/Conductor/ExecutionStates/CanceledState.h
- arangod/Pregel/Conductor/ExecutionStates/DoneState.h
- arangod/Pregel/Conductor/ExecutionStates/FatalErrorState.h
- arangod/Pregel/Conductor/ExecutionStates/State.h
- arangod/Pregel/Conductor/Handler.h
- arangod/Pregel/Conductor/Messages.h
- arangod/Pregel/PregelFeature.cpp
- arangod/Pregel/PregelFeature.h
- arangod/Pregel/REST/RestControlPregelHandler.cpp
- arangod/Pregel/REST/RestPregelHandler.cpp
- arangod/Pregel/ResultActor.h
- arangod/Pregel/ResultMessages.h
- arangod/Pregel/SpawnMessages.h
- arangod/V8Server/v8-pregel.cpp
With this PR you are able to cancel a pregel run. This does two things:
1. If pregel is still running: Cancel the run and cleanup the conductor (setting it to finished such that actor garbage collection can remove it). For that we now have now another map of execution number to conductor pid inside the pregel feature, such that we can find the conductor for the corresponding execution number.
2. Independent of pregel running or already finished: Cleanup all result actors (on conductor and workers). For this to work, the result actor on the coordinator has to know the actor pids of the result actors on the dbservers: In the RestPregelHandler this pid is send to the result actor on the coordinator after a result actor is created on the dbserver.
This PR adds the contains function to the …
> [GORDO-1582] Cancel pregel run

- js/client/modules/@arangodb/testutils/instance.js
If we intend to crash the server, we need to deregister its PID from the monitor.
> one more place where we need to deregister the PID from the monitor.

- tests/js/server/replication2/replication2-collectiongroups-cluster.js
Sometimes this test failed, because an empty collection group was still present, when the next test starts.
> [CINFRA-719] Fix CollectionGroups test

- arangod/Pregel/IncomingCache.cpp
- arangod/Pregel/IncomingCache.h
- arangod/Pregel/Worker/Handler.h
- arangod/Pregel/Worker/State.h
- arangod/Pregel/Worker/Worker.cpp
Makes the InCache independent of worker config as it only used the set of pregel shards as a local shard index.
> Make InCaches independent of WorkerConfig

- arangod/Pregel/Conductor/Handler.h
- arangod/Pregel/GraphStore/GraphLoader.cpp
- arangod/Pregel/GraphStore/GraphLoader.h
- arangod/Pregel/GraphStore/GraphStorer.cpp
- arangod/Pregel/GraphStore/GraphStorer.h
- arangod/Pregel/SpawnActor.h
- arangod/Pregel/SpawnMessages.h
- arangod/Pregel/Statistics.h
- arangod/Pregel/StatusActor.h
- arangod/Pregel/StatusMessages.h
- arangod/Pregel/Worker/Handler.h
- arangod/Pregel/Worker/State.h
- arangod/Pregel/Worker/Worker.cpp
Sends status updates from the worker actor to the status actor. There are 3 different message types for the different phases loading, computing (one message per global superstep) and storing.
The loading and storing messages are sent from the GraphLoader and GraphStorer, I adapted them a bit such you can now either give it an old status update callback (such that these two still work with the old pregel) or a callback to call the actor-dispatch function. (After we delete the old pregel without actors, we should think about how to not need to use a callback here.)
The status actor updates the status of each worker separately and aggregates the status of the workers to get a total value on all the variables.
> [GORDO-1598] Send status updates from worker

- arangod/Replication2/CMakeLists.txt
- arangod/Replication2/ReplicatedLog/CMakeLists.txt
- arangod/Replication2/ReplicatedLog/Components/AppendEntriesManager.cpp
- arangod/Replication2/ReplicatedLog/Components/AppendEntriesManager.h
- arangod/Replication2/ReplicatedLog/Components/FollowerCommitManager.cpp
- arangod/Replication2/ReplicatedLog/Components/FollowerCommitManager.h
- arangod/Replication2/ReplicatedLog/Components/IFollowerCommitManager.h
- arangod/Replication2/ReplicatedLog/Components/IMessageIdManager.h
- arangod/Replication2/ReplicatedLog/Components/IMethodsProvider.cpp
- arangod/Replication2/ReplicatedLog/Components/IMethodsProvider.h
- arangod/Replication2/ReplicatedLog/Components/ISnapshotManager.h
- arangod/Replication2/ReplicatedLog/Components/IStateHandleManager.h
- arangod/Replication2/ReplicatedLog/Components/LogFollower.cpp
- arangod/Replication2/ReplicatedLog/Components/LogFollower.h
- arangod/Replication2/ReplicatedLog/Components/MessageIdManager.cpp
- arangod/Replication2/ReplicatedLog/Components/MessageIdManager.h
- arangod/Replication2/ReplicatedLog/Components/MethodsProvider.cpp
- arangod/Replication2/ReplicatedLog/Components/MethodsProvider.h
- arangod/Replication2/ReplicatedLog/Components/SnapshotManager.h
- arangod/Replication2/ReplicatedLog/Components/StateHandleManager.cpp
- arangod/Replication2/ReplicatedLog/Components/StateHandleManager.h
- arangod/Replication2/ReplicatedState/CMakeLists.txt
- arangod/Replication2/ReplicatedState/ReplicatedState.tpp
- tests/Replication2/ReplicatedLog/Components/FollowerCommitManagerTest.cpp
- tests/Replication2/ReplicatedLog/Components/SnapshotManagerTest.cpp
Fix the following lock inversion, as detected by TSan in `StateManagerTest.get_follower_state_machine_early_with_snapshot_without_truncate`:
```mermaid
graph LR
SHM_BF["StateHandleManager::becomeFollower"]
RSM_BF["ReplicatedStateManager&lt;S>::becomeFollower"]
RL_UC["ReplicatedLog::updateConfig"]
FCM_GCI["FollowerCommitManager::getCommitIndex()"]
FSM_GSM["FollowerStateManager&ltS>::getStateMachine()"]
RSM_GF["ReplicatedStateManager&ltS>::getFollower()"]
AEM_AE["AppendEntriesManager::appendEntries"]
FCM_UCI["FollowerCommitManager::updateCommitIndex"]
SHM_UCI["StateHandleManager::updateCommitIndex"]
RL_UC -.-> SHM_BF -.-> RSM_BF
RSM_GF -.-> FSM_GSM  -.-> FCM_GCI
AEM_AE -.-> FCM_UCI -.-> SHM_UCI
subgraph ReplicatedStateManager
RSM_GF
RSM_BF
end
subgraph ReplicatedLog
RL_UC
end
subgraph …
```
> [CINFRA-730] Fix lock inversions in the follower

- .circleci/base_config.yml
The build itself is started for a specific commit, but creating a shallow clone requires a branch name. It can happen that during the time the build is started, but before the clone command is executed, another commit is pushed to the branch. As a result, the branch will point to the new commit. Previously we tried to work around such a situation by resetting to the specified commit, but since we are creating a shallow clone this does not work because that commit is not known.
This PR tries a different approach to fetch only the specific commit.
> Fix potential race when cloning repository in CircleCI

- arangod/Pregel/GraphStore/CMakeLists.txt
- arangod/Pregel/GraphStore/GraphLoader.cpp
- arangod/Pregel/GraphStore/GraphLoader.h
- arangod/Pregel/GraphStore/GraphLoaderBase.h
- arangod/Pregel/GraphStore/GraphVPackBuilderStorer.cpp
- arangod/Pregel/GraphStore/GraphVPackBuilderStorer.h
- arangod/Pregel/GraphStore/Magazine.cpp
- arangod/Pregel/GraphStore/Magazine.h
- arangod/Pregel/GraphStore/Quiver.h
- arangod/Pregel/VertexComputation.h
- arangod/Pregel/Worker/Handler.h
- arangod/Pregel/Worker/State.h
- arangod/Pregel/Worker/Worker.cpp
- arangod/Pregel/Worker/Worker.h
As a pre-step to re-parallelisation support multiple `Quiver<V, E>` in a Worker; they are summarised in a `Magazine<V,E>`.
Currently there is a 1-1 correspondence between `Quiver<V,E>`s and a shard of a vertex collection, so we can load vertex shards concurrently, and later process `Quiver<V,E>`s concurrently.
> [GORDO-1600] Multiple Quiver<V,E>s in a Worker

- arangod/Replication2/Supervision/CollectionGroupSupervision.cpp
There is not much to say about this: I was lazy and did not add preconditions to the agency transactions generated by the collection group supervision. This bit us and now I added them.
In almost all cases, it is required that the collection group in question is still in Target. If it is not, the only sensible action is to remove it everywhere else.
> [CINFRA] Add missing preconditions to collection groups supervision

- arangod/Replication2/ReplicatedLog/CMakeLists.txt
- arangod/Replication2/ReplicatedLog/Components/IInMemoryLogManager.h
- arangod/Replication2/ReplicatedLog/Components/IStorageManager.h
- arangod/Replication2/ReplicatedLog/Components/InMemoryLogManager.cpp
- arangod/Replication2/ReplicatedLog/Components/InMemoryLogManager.h
- arangod/Replication2/ReplicatedLog/Components/StorageManager.h
- arangod/Replication2/ReplicatedLog/LogLeader.cpp
- arangod/Replication2/ReplicatedLog/LogLeader.h
- tests/Replication2/CMakeLists.txt
- tests/Replication2/Mocks/StorageManagerMock.h
- tests/Replication2/ReplicatedLog/Components/CompactionManagerTest.cpp
- tests/Replication2/ReplicatedLog/Components/FollowerCommitManagerTest.cpp
- tests/Replication2/ReplicatedLog/Components/SnapshotManagerTest.cpp
Fix the following lock inversion, as detected by TSan in `StateManagerTest.get_leader_state_machine_early`:
```mermaid
graph LR
RSM_LE["ReplicatedStateManager&lt;S>::leadershipEstablished"]
LL_EAER["LogLeader::executeAppendEntriesRequests"]
LL_EAER -.-> RSM_LE
LSM_GSM["LeaderStateManager&lt;S>::getStateMachine()"]
RSM_GL["ReplicatedStateManager&lt;S>::getLeader()"]
RSM_GL -.-> LSM_GSM
LL_GLCI["LogLeader::getLogConsumerIterator"]
LSM_RE["LeaderStateManager&lt;S>::recoverEntries()"]
LSM_RE -.-> LL_GLCI
subgraph ReplicatedStateManager
RSM_LE
RSM_GL
end
subgraph LogLeader
LL_EAER
LL_GLCI
end
subgraph LeaderStateManager
LSM_GSM
LSM_RE
end
ReplicatedStateManager --> LeaderStateManager --> LogLeader --> ReplicatedStateManager
```
This is fixed by moving both `_commitIndex` and `_inMemoryLog` …
> [CINFRA-732] Fix lock inversions in the leader

- tests/js/client/shell/transaction/shell-transaction.js
It's best to disable replication2 transaction tests for now, until we update replication2.
> [CINFRA] Disabled transaction tests

- arangod/VocBase/VocbaseInfo.cpp
If defaultReplicationFactor is zero, the minReplicationFactor is supposed to be used.
> Use minReplicationFactor instead of default.

- CMakePresets.json
- arangod/Replication2/ReplicatedLog/Components/InMemoryLogManager.cpp
- arangod/Replication2/ReplicatedLog/Components/InMemoryLogManager.h
- arangod/Replication2/ReplicatedLog/LogLeader.cpp
- arangod/Replication2/ReplicatedLog/LogLeader.h
- lib/Inspection/include/Inspection/SaveInspectorBase.h
Fix the following lock inversion:
```mermaid
graph LR
LL_I["LogLeader::insert"]
LSM_RE["LeaderStateManager&lt;S>::recoverEntries()"]
LSM_RE -.-> LL_I
RSM_LE["ReplicatedStateManager&lt;S>::leadershipEstablished"]
LL_EAER["LogLeader::executeAppendEntriesRequests"]
LL_EAER -.-> RSM_LE
LSM_GSM["LeaderStateManager&lt;S>::getStateMachine()"]
RSM_GL["ReplicatedStateManager&lt;S>::getLeader()"]
RSM_GL -.-> LSM_GSM
subgraph LeaderStateManager
LSM_RE
LSM_GSM
end
subgraph ReplicatedStateManager
RSM_LE
RSM_GL
end
subgraph LogLeader
LL_I
LL_EAER
end
LeaderStateManager --> LogLeader --> ReplicatedStateManager --> LeaderStateManager
```
This PR removes the need for the LogLeader to acquire its mutex in `insert()`. Most of the work was moved to the `InMemoryLogManager` in #18578 already: Now …
> [CINFRA-735] Fix lock inversion on the Leader Log/State

- CONTRIBUTING.md
- js/client/modules/@arangodb/testutils/instance.js
in clusters one may want to divert log facilities into individual files. Use similar mechanism as the starter provides
> add possibility to provide Arguments to cluster instances similar as to the starter

- tests/js/client/shell/transaction/shell-transaction.js
Transaction tests have been disabled in devel before the last merge. This PR enables then again in staging.
> [CINFRA-740] Enable Transaction Tests

- 3rdParty/date/src/tz.cpp
fix for date library printing #STDOFF messages during parsing of tzdata files at startup.
fix forward-ported from upstream fix
https://github.com/HowardHinnant/date/commit/22ceabf205d8d678710a43154da5a06b701c5830
> fix for date library printing #STDOFF messages

- js/client/modules/@arangodb/test-helper.js
- tests/js/client/communication/test-communication.js
the runInClient implementation dropped to serialize the instance manager.
Hence tests must now use the `global.instanceManager` to work with instances.
> testing: on the client we now only have the global instanceManager object anymore.

- arangod/Pregel/REST/RestControlPregelHandler.cpp
We made the pregel API in devel more restrictive because some values did not at all make sense to use (i.e.g you should either give a graph OR vertex and edge collections where pregel should run on, not both).
But we don't want any changes in the API in 3.11, therefore this is reverted with this PR.
> [PREGEL] Make pregel API again backwards compatible to 3.10

- js/client/modules/@arangodb/testutils/instance.js
Change log levels on agents to debug for the `agency` log topic. There have been cases of slow agency startup. This hopefully helps to see why.
> Set agency log level to debug on agents.

- tests/Pregel/DurationTest.cpp
Although with very low probability, the *DurationTest* test has been [seen failing on the mac](https://jenkins01.arangodb.biz/job/arangodb-ANY-mac-matrix.arm64/290/EDITION=enterprise,STORAGE_ENGINE=rocksdb,TEST_SUITE=single,limit=mac&&test&&arm64/artifact/testfailures.txt).
```
"test" failed: /Users/jenkins/hw33-mac-m1/oskar/work/ArangoDB/tests/Pregel/DurationTest.cpp:46
Expected: (moreElapsed) > (elapsed), actual: 8-byte object <A3-F9 B2-A0 6F-8C 66-3E> vs 8-byte object <A3-F9 B2-A0 6F-8C 66-3E>
```
This looks like the test ran so fast that the time turned out to be the same when comparing `moreElapsed` to `elapsed`. ~~I added a few timeouts to prevent this from happening~~. I replaced `ASSERT_GT` with `ASSERT_GE`.
> Using ASSERT_EQ in DurationTest

- arangod/Aql/RestAqlHandler.cpp
- lib/Futures/include/Futures/SharedState.h
- lib/Futures/include/Futures/Try.h
The first server to simulate the query abortion reports back to the coordinator, which will then send abort requests to all db servers. These abort requests then race with the previous use requests. If the abort request is processed before the use request, the assertions we had in the code did not hold.
> Fix race in kill queries test

- arangod/Replication2/ReplicatedState/ReplicatedStateFeature.h
The string `name` passed to `assertWasInserted` after being moved in the `try_emplace` above.
Provides one of the fixes from https://github.com/arangodb/arangodb/pull/18630
> [CINFRA] Use after move

- js/client/modules/@arangodb/testutils/result-processing.js
a testcase might not have the message attribute. don't trip over this while generating the xml:
```
Exception occured in running tests: Cannot read property 'replace' of undefined
TypeError: Cannot read property 'replace' of undefined
at stripAnsiColors (/Users/jenkins/hw41-mac/oskar/work/ArangoDB/js/client/modules/@arangodb/testutils/result-processing.js:235:14)
at Object.testCase (/Users/jenkins/hw41-mac/oskar/work/ArangoDB/js/client/modules/@arangodb/testutils/result-processing.js:312:38)
at iterateTestResults (/Users/jenkins/hw41-mac/oskar/work/ArangoDB/js/client/modules/@arangodb/testutils/result-processing.js:164:22)
at Object.saveToJunitXML (/Users/jenkins/hw41-mac/oskar/work/ArangoDB/js/client/modules/@arangodb/testutils/result-processing.js:274:3)
at main …
```
> don't trip over a testcase not having a message

- arangod/Transaction/Methods.cpp
- tests/js/client/shell/shell-replication-intermediate-commits-cluster.js
Test only: adds the test from https://github.com/arangodb/arangodb/pull/18648 to ensure the replication performs intermediate commits.
> added test for intermediate commits

- CHANGELOG
- arangod/Replication/DatabaseInitialSyncer.cpp
- arangod/Transaction/Methods.cpp
- tests/js/client/shell/shell-replication-intermediate-commits-cluster.js
BTS-1307: https://arangodb.atlassian.net/browse/BTS-1307
Apply intermediate commits for replication transactions during initial sync phase of replication in case the follower already had documents. This fixes issues with large replication transactions consuming a lot of memory on followers during getting shards in sync.
> Apply intermediate commits during getting shards in sync

- tests/js/common/shell/shell-index.js
Previously this test suite could run into the situation that tasks that were created by a previous test would interfere with the current test case.
This PR adapts the teardown method to make sure all tasks that were started by a test have actually finished (or fail by means of a timeout otherwise)
This should fix failures of this type https://jenkins01.arangodb.biz/job/arangodb-matrix-pr-windows/21100/EDITION=community,ST[…]b,TEST_SUITE=cluster,limit=windows&&test&&!rta&&!release/
> Fix testCreateInParallel

- lib/Basics/win-utils.cpp
silence the windows ports warning if a subprocess closes a pipe; We see these when forking netstat and it exits.
> silence windows warning while reading pipes

- CONTRIBUTING.md
- tests/js/client/shell/transaction/shell-transaction-part1-R1.js
- tests/js/client/shell/transaction/shell-transaction-part1-R2.js_DISABLED
- tests/js/client/shell/transaction/shell-transaction-part2-R1.js
- tests/js/client/shell/transaction/shell-transaction-part2-R2.js_DISABLED
- tests/js/client/shell/transaction/shell-transaction.inc
- tests/test-definitions-rlog.txt
Due to the file reaching the 15min time limitation on macOS, we are splitting it up into two parts, containing roughly the same number of tests.
replication2 tests currently remain disabled.
> Splitting shell-transaction tests

- CHANGELOG
- arangod/Aql/TraversalNode.cpp
- js/server/modules/@arangodb/testutils/aql-graph-traversal-generic-graphs.js
- js/server/modules/@arangodb/testutils/aql-graph-traversal-generic-tests.js
Backport of https://github.com/arangodb/arangodb/pull/18602
*In Traversals If we use a variable as the StartVertex and also for Filtering like this:
FOR candidate IN ["vertices/1", "vertices/2"]
FOR v,e,p IN 1 OUTBOUND candidate GRAPH "myGraph"
FILTER e.MostLikedNeighbor == candidate
RETURN v
The variable candidate can be erased too early if another optimizer rule replaces the InputVaribale (e.g. for Distribution in DisjointSmartGraph case)
*
> Bug fix-3.10/mds 1098 dropping variable content to early

- js/client/modules/@arangodb/testutils/instance-manager.js
- js/client/modules/@arangodb/testutils/instance.js
Set the log level to info after startup. It was set to debug to investigate the startup behavior of agents.
> Reset log level to normal on agents after startup.

- .circleci/config.yml
Right now CircleCI is set up to run every time we merge a PR to devel.
during the fixing of nightlies phase, this is a waste of resources.
> Remove automatic circleci run on devel branch

- js/server/modules/@arangodb/test-helper.js
- tests/js/common/shell/shell-pregel-multicollection-edgecol.js
Fixes "Error: at assertion #12023: assertEqual: (6) is not equal to (8) (Error at tests/js/common/shell/shell-pregel-multicollection-edgecol.js:242:9 at Object.testMultiWCCParallelism (tests/js/common/shell/shell-pregel-multicollection-edgecol.js:234:22) at tests/js/common/shell/shell-pregel-multicollection-edgecol.js:365:9 .... at Object.shellClient [as shell_client] (/Users/jenkins/hw43-mac/oskar/work/ArangoDB/js/client/modules/@arangodb/testsuites/aql.js:208:79) - test failed"
Happening on mac, e.g.: "https://jenkins01.arangodb.biz/job/arangodb-ANY-mac-matrix.x86-64/EDITION=community,STORAGE_ENGINE=rocksdb,TEST_SUITE=single,limit=mac&&test&&x86-64/4292/"
If the requested parallelism is larger than the number of cores on the running machine, pregel uses the number of cores for …
> [PREGEL] Use number of cores as upper cut for pregel parallelism

- arangod/Pregel/Iterators.h
- arangod/Pregel/Statistics.h
- arangod/Pregel/Worker/CMakeLists.txt
- arangod/Pregel/Worker/VertexProcessor.cpp
- arangod/Pregel/Worker/VertexProcessor.h
- arangod/Pregel/Worker/Worker.cpp
- arangod/Pregel/Worker/Worker.h
The parallelism parameter was ignored for processing vertices and one future per shard is started per DBSServer. This could be considered a bug.
With this PR one `parallelism` many futures are started and work on shards one after the other.
As a pre-step to this, all code pertaining to processing vertices is moved out of the `Worker` struct into its own `VertexProcessor` struct.
> [GORDO-1619] Fix parallelism for processing vertices

- CHANGELOG
- arangod/IResearch/IResearchDataStore.cpp
- arangod/Metrics/Batch.h
- arangod/Metrics/ClusterMetricsFeature.cpp
- arangod/Metrics/ClusterMetricsFeature.h
- arangod/Metrics/Counter.cpp
- arangod/Metrics/Counter.h
- arangod/Metrics/Gauge.h
- arangod/Metrics/Histogram.h
- arangod/Metrics/IBatch.h
- arangod/Metrics/Metric.h
- arangod/Metrics/MetricsFeature.cpp
- arangod/Metrics/MetricsFeature.h
- arangod/Statistics/StatisticsFeature.cpp
- arangod/Statistics/StatisticsFeature.h
- js/client/modules/@arangodb/test-helper.js
- js/server/modules/@arangodb/test-helper.js
- tests/IResearch/IResearchLinkTest.cpp
- tests/Metrics/MetricsFeatureTest.cpp
- tests/Metrics/MetricsTest.cpp
- tests/js/client/server_parameters/test-ensure-whitespace-metrics-format-off.js
- tests/js/client/server_parameters/test-ensure-whitespace-metrics-format-on.js
Backport of https://github.com/arangodb/arangodb/pull/18702
* Added startup option `--server.ensure-whitespace-metrics-format`, which controls whether additional whitespace is used in the metrics output format. If set to `true`, then whitespace is emitted between the exported metric value and the preceeding token (metric name or labels). Using whitespace may be required to make the metrics output compatible with some processing tools, although Prometheus itself doesn't need it.
The option defaults to `true`, which adds additional whitespace by default.
This should fix issues https://github.com/arangodb/arangodb/issues/18692 and https://arangodb.atlassian.net/browse/ES-1515.
> ES-1515: Make metrics output format configurable

- tests/js/server/recovery/foxx-directories.js
This PR aims at making _foxx-directories.js_ tests somewhat more stable. It has been known to fail when the system is under heavy load.
The test creates a database which is then dropped. After dropping the database, it waits for the database folder to be deleted. This relies on the `DatabaseManagerThread` to kick in and do the cleanup, which is already problematic when the operating system is under stress. However, even if this succeeds, it's not entirely impossible that we could encounter a scenario where the directory entry is still available in the operating system cache even after the directory has been deleted.
Such situations are rare and usually occur only in cases of high file system load. This is an attempt to ensure that the information is up-to-date, as trying to read the …
> Trying to work around OS cache

- arangod/Replication2/StateMachines/Document/DocumentFollowerState.cpp
- arangod/RestHandler/RestBaseHandler.cpp
- arangod/RestHandler/RestBaseHandler.h
- arangod/RestHandler/RestDocumentStateHandler.cpp
- arangod/RestHandler/RestDocumentStateHandler.h
This PR removed the _DefaultCustomTypeHandler called_ message from being logged, by adding a custom type handler in the `RestDocumentStateHandler`.
> [CINFRA-595] Custom type handler

- arangod/Auth/TokenCache.cpp
- arangod/Auth/UserManager.cpp
- arangod/Auth/UserManager.h
Do not make `_globalVersion` in UserManager go backwards. Otherwise it may prevent the `_basicCache` from being invalidated in case it must be invalidated.
> do not make _globalVersion go backwards

- js/client/modules/@arangodb/testsuites/gtest.js
- js/client/modules/@arangodb/testutils/clusterstats.js
- js/client/modules/@arangodb/testutils/result-processing.js
- tests/test-definitions.txt
- gtests could overwrite their results in `basics` which doesn't properly relate to anything in first place, use a real name
- use filters rather from .js code than from the test-definitions.txt
- map crashes into an own crasheport xml.
> testing: proper namespacing for gtests

- lib/Basics/files.cpp
- lib/Logger/LogAppenderFile.cpp
This fixes a deadlock situation in a rare case of trace logging together
with log rotation. The problem is described in detail here:
https://arangodb.atlassian.net/browse/BTS-1326
The only actual change is to remove a log message in TRI_RenameFile
which can do harm.
- [*] Backport for 3.10: https://github.com/arangodb/arangodb/pull/18738
- [*] Backport for 3.9: https://github.com/arangodb/arangodb/pull/18739
- [*] Jira ticket: https://arangodb.atlassian.net/browse/PRESUPP-556
- [*] BTS ticket: https://arangodb.atlassian.net/browse/BTS-1326
> Avoid lockup with trace logging and log rotation, BTS-1326.

- arangod/Pregel/Conductor/Conductor.cpp
- arangod/Pregel/Conductor/Conductor.h
- arangod/Pregel/PregelFeature.cpp
- arangod/Pregel/PregelOptions.h
- tests/js/client/load-balancing/load-balancing-pregel-auth-cluster.js
Should fix https://jenkins01.arangodb.biz/job/arangodb-matrix-pr-windows/21263/EDITION=community,STORAGE_ENGINE=rocksdb,TEST_SUITE=cluster,limit=windows&&test&&!rta&&!release/testReport/junit/EE_load_balancing_auth__tests_js_client_load-balancing_load-balancing-pregel-auth-cluster/js/EE_testPregelForwardingSameUser/
We now write the correct user into the historic pregel collection. Before, we wrote `ExecContext::current().user()` into the collection, which first can be null depending on which thread this is executed on (this null gave us the occasional bug) and second is not correct: We want to always write the user that started the pregel run.
Additionally, the test is improved: In the test we now make sure that the pregel run was created before we request its status, same for canceling …
> [PREGEL] Fix load-balancing-pregel-auth-cluster test

- arangod/Agency/Constituent.cpp
- arangod/Agency/Constituent.h
Sometimes the agent decided to candidate, but waits on a mutex. During that time the agent is converted into a follower. This can have the strange effect that a new follower immediately candidates.
> Do not candidate if we became follower just before.

- tests/js/client/shell/api/pregel.js
- tests/js/common/shell/shell-pregel-components.js
Do not specify replicationFactor and numberOfShards if distribute shards like is used.
> Do not specify invalid replicationFactor and numberOfShards.

- tests/js/server/resilience/move/moving-shards-cluster.inc
This is a "backport" of https://github.com/arangodb/arangodb/pull/18748 for the replication2 staging branch. This is where the issue was first visible.
> [CINFRA-746] MoveShard flaky tests

- tests/test-definitions.txt
This is just a quick fix. Long term we should identify the tests that cause the memory usage to grow so much and either optimize them or move them to a separate "large" suite.
> Increase container size for shell_server_aql tests to avoid OOM kills

- js/client/modules/@arangodb/testsuites/rta_makedata.js
- js/client/modules/@arangodb/testutils/test-utils.js
- js/client/modules/@arangodb/testutils/testing.js
By default arangosh doesn't log stack traces. This can be turned on by setting `V8=debug`. 
We couple this with `--extremeVerbosity true` here, to aid testing.js and rta-makedata test development.
```
2023-04-21T10:05:00Z [3832633] ERROR [8a210] {general} JavaScript exception in file '/home/willi/src/devel/js/client/modules/@arangodb/arango-database.js' at 1203,7: ArangoError 1228: database not found
2023-04-21T10:05:00Z [3832633] ERROR [409ee] {general} !      throw err;
2023-04-21T10:05:00Z [3832633] ERROR [cb0bd] {general} !      ^
2023-04-21T10:05:00Z [3832633] DEBUG [cb0bf] {v8} !stacktrace: ArangoError: database not found\n    at Object.exports.checkRequestResult (/home/willi/src/devel/js/client/modules/@arangodb/arangosh.js:91:21)\n    at Proxy.ArangoDatabase._queryProperties …
```
> testing: rta-makedata debugging

- CHANGELOG
- Documentation/Metrics/arangodb_sync_tree_rebuilds_total.yaml
- arangod/Cluster/ClusterFeature.cpp
- arangod/Cluster/ClusterFeature.h
- arangod/Cluster/MaintenanceFeature.h
- arangod/Cluster/SynchronizeShard.cpp
- arangod/Replication/DatabaseInitialSyncer.cpp
- arangod/Replication/ReplicationFeature.cpp
- arangod/Replication/ReplicationFeature.h
- arangod/RestHandler/RestReplicationHandler.cpp
- arangod/RestHandler/RestReplicationHandler.h
- arangod/RocksDBEngine/RocksDBTransactionCollection.cpp
- tests/Mocks/Servers.cpp
- tests/js/client/shell/shell-replication-auto-repair-cluster.js
Backport of https://github.com/arangodb/arangodb/pull/18710
Automatically repair revision trees after several failed shard synchronization attempts. This can help to get permanently out-of-sync shards back into sync.
The functionality can be turned off by setting the startup option `--replication.auto-repair-revision-trees` to `false` on DB-Servers.
> Automatically repair revision trees after shard sync failures

- CHANGELOG
- Documentation/Metrics/arangodb_sync_tree_rebuilds_total.yaml
- arangod/Cluster/ClusterFeature.cpp
- arangod/Cluster/ClusterFeature.h
- arangod/Cluster/MaintenanceFeature.h
- arangod/Cluster/SynchronizeShard.cpp
- arangod/Replication/DatabaseInitialSyncer.cpp
- arangod/Replication/ReplicationFeature.cpp
- arangod/Replication/ReplicationFeature.h
- arangod/RestHandler/RestReplicationHandler.cpp
- arangod/RestHandler/RestReplicationHandler.h
- arangod/RocksDBEngine/RocksDBTransactionCollection.cpp
- tests/Mocks/Servers.cpp
- tests/js/client/shell/shell-replication-auto-repair-cluster.js
Backport of https://github.com/arangodb/arangodb/pull/18710
Automatically repair revision trees after several failed shard synchronization attempts. This can help to get permanently out-of-sync shards back into sync.
The functionality can be turned off by setting the startup option `--replication.auto-repair-revision-trees` to `false` on DB-Servers.
>  Automatically repair revision trees after shard sync failures

- .circleci/config.yml
Enable setup workflow for pipelines started by a scheduled pipeline trigger. This allows to at least have nightly PR builds for the devel branch since we have currently disabled the push based devel builds.
> Enable scheduled pipeline triggers on CircleCI

- js/client/modules/@arangodb/testsuites/dump.js
testsuites would cleanup their directory though errors occured. 
This was due to the global failure count wasn't aggregated yet.
> QA-411: fix counting of test failures

- tests/js/client/shell/shell-auto-refill-index-caches-on-modify-noncluster.js
Attempt to fix unstable test
```
[FAILED]  tests/js/client/shell/shell-auto-refill-index-caches-on-modify-noncluster.js
"testReplaceEdgeBatchEnabled" failed: Error: at assertion #5003: { 
"writesExecuted" : 0, 
"writesIgnored" : 0, 
"scannedFull" : 0, 
"scannedIndex" : 5000, 
"cursorsCreated" : 1, 
"cursorsRearmed" : 4999, 
"cacheHits" : 0, 
"cacheMisses" : 5000, 
"filtered" : 0, 
"httpRequests" : 0, 
"executionTime" : 0.05387298599998758, 
"peakMemoryUsage" : 98304, 
"intermediateCommits" : 0 
}: (false) does not evaluate to true
(Error
at runCheck (tests/js/client/shell/shell-auto-refill-index-caches-on-modify-noncluster.js:66:7)
at Object.testReplaceEdgeBatchEnabled (tests/js/client/shell/shell-auto-refill-index-caches-on-modify-noncluster.js:296:7)
at …
```
> fix unstable cache test

- arangod/Cluster/ClusterFeature.cpp
- arangod/Cluster/ServerState.cpp
- arangod/Cluster/ServerState.h
- arangod/Cluster/v8-cluster.cpp
- js/server/modules/@arangodb/cluster.js
Not related to 3.11 stabilization
simplify ServerState
- remove dependency on ReadWriteSpinLock (use regular RW lock instead)
- remove _initialized boolean variable, which was not thread-safe and used from only one place in `js/server/modules/@arangodb/cluster.js`.
> simplify ServerState

- arangod/RestServer/FrontendFeature.cpp
- arangod/V8Server/V8DealerFeature.cpp
- arangod/V8Server/v8-vocbase.cpp
fix value of `internal.extendedNames` after restart when startup option `--database.extended-names` was not explicitly specified, but a previous run set it to `true`.
in this case, the value was reported as `false`, although it should have been reported as `true`.
manually tested
> fix value of `internal.extendedNames` after restart

- Documentation/Scripts/exampleHeader.js
- tests/js/common/shell/aql-index-usage.js
- utils/generateExamples.py
the information available in asserts in the examples is pretty limited. Dump out the function to give the user some context
instead of the very limited:
```
09:20:56 RUN FAILED: RestViewDeleteViewIdentifierArangoSearch from testfile: /work/ArangoDB/Documentation/DocuBlocks/Rest/Views/delete_api_view_view.md, Error: assertion RestViewDeleteViewIdentifierArangoSearch in file /work/ArangoDB/Documentation/DocuBlocks/Rest/Views/delete_api_view_view.md failed
09:20:56 Error: assertion RestViewDeleteViewIdentifierArangoSearch in file /work/ArangoDB/Documentation/DocuBlocks/Rest/Views/delete_api_view_view.md failed
09:20:56     at globalAssert (/work/ArangoDB/arangosh.examples.js:166:11)
09:20:56     at assert (/work/ArangoDB/arangosh.examples.js:15807:30)
09:20:56     at testFunc …
```
> documentation: print the function surce so the user can better allocate the assert

- arangod/RestHandler/RestViewHandler.cpp
- tests/js/client/shell/api/view-arangosearch.js
Allow deletion by view id again.
This functionality broke due to a recent commit, and this went undetected because we did not have a test for it.
> re-allow deletion by view id

- arangod/Replication2/ReplicatedLog/Components/InMemoryLogManager.cpp
Fixing metric `arangodb_replication2_replicated_log_inserts_bytes`.
> Fix arangodb_replication2_replicated_log_inserts_bytes metric.

- js/client/modules/@arangodb/test-helper.js
As we see sometimes chaos test clients run into "Execution deadline reached" error. This leads to inconsistent chaos tests results. 10s is not enough to finish executions, so this PR increases it to 60s. 
> Increase chaos client timeout

- arangod/Pregel/PregelFeature.cpp
- arangod/Pregel/PregelFeature.h
- arangod/Pregel/REST/RestControlPregelHandler.cpp
- arangod/Pregel/REST/RestPregelHandler.cpp
- arangod/Pregel/ResultActor.h
- arangod/Pregel/StatusActor.h
- arangod/V8Server/v8-pregel.cpp
- tests/Pregel/Actor/Actors/EgressActor.h
- tests/Pregel/Actor/CMakeLists.txt
- tests/Pregel/Actor/EgressActorTest.cpp
When running pregel with actors, we have to get the pregel result and the status out of an actor. The method `getActorStateByID` we used before is not save because the state is moved back and forth when the actor is working and results in sporadic test failures.
This PR solves this by having a shared_ptr to the needed data inside the actor state. This ptr is saved in the feature and is used when the feature requests the data.
> [GORDO-1617] Get data out of actors safely

- tests/js/server/dump/dump-test.inc
Backport for https://github.com/arangodb/arangodb/pull/18792.
This PR aims to fix the following error which repeats for 3 different tests cases in `tests/js/server/dump/dump-test.inc`: testKeygenAutoInc_cluster, testKeygenPadded_cluster and testKeygenUuid_cluster
in the error, one cannot insert documents into the collection because it's in read-only state, which, deductively, would mean that the shards are not in sync yet, making the collection not ready to be used in transactions.
> Bug fix 3.11/test failure backup dump collections not ready

- tests/js/client/shell/abort-long-running-operations-noncluster.js
This fixes the tests in
tests/js/client/shell/abort-long-running-operations-noncluster.js
There, one of the tests is that if the working database is dropped, some
long running operations stop. The test is implemented using background
tasks on the server.
The test was unstable since the dropping of the database could have
prevented the `shutdownTask` procedure from working, since it could
run into a `database not found` error. Therefore it was not properly
waiting for the task to complete.
A single additional `db._useDatabase("_system");` should fix the
problem.
- [*] Tests
- [*] Backport for 3.11: https://github.com/arangodb/arangodb/pull/18840
> Fix broken test (abort long running)

- CHANGELOG
- arangod/IResearch/IResearchViewCoordinator.cpp
- tests/js/common/aql/aql-view-arangosearch-ddl.js
Backport of https://github.com/arangodb/arangodb/pull/18682
> Fix SEARCH-466 3.9

- lib/Basics/RocksDBUtils.cpp
- tests/js/common/shell/shell-error-messages.js
change error message for document not found error
3.10 threw a "document not found" error with a nice error message. 3.11/devel unintentionally changed this error message to just "NotFound:", because it is the underlying error message from RocksDB.
this PR changes the error message back to how it should be.
> change error message for document not found error

- scripts/startLocalCluster.sh
Disable version check in scripts/startLocalCluster.sh
This allows us to switch between different executable versions easier, without having to start with `--database.auto-upgrade true` before.
This change only affects a helper script for developers.
> Disable version check in scripts/startLocalCluster

- CHANGELOG
- arangod/Transaction/Manager.cpp
- arangod/Transaction/Methods.cpp
- tests/js/client/shell/transaction/replication2_recovery/shell-transaction-replication2-recovery.js
- tests/js/client/shell/transaction/shell-transaction-dropped-followers-cluster.js
- tests/js/client/shell/transaction/shell-transaction-intermediate-commit-cluster.js
When we have a query that results in a failure this will cause the leaders to abort the transaction on the followers. However, if the followers have transactions that are shared with leaders of other shards, and if one of those leaders has not yet seen the error, then it will happily continue to replicate to that follower. But if the follower has already aborted the transaction, then it will reject the replication request. Previously this would cause the follower to be dropped, but now this should be handled gracefully.
> Fix handling of premature follower trx abortion

- CHANGELOG
- arangod/Transaction/Manager.cpp
- arangod/Transaction/Methods.cpp
- tests/js/client/shell/transaction/replication2_recovery/shell-transaction-replication2-recovery.js
- tests/js/client/shell/transaction/shell-transaction-dropped-followers-cluster.js
- tests/js/client/shell/transaction/shell-transaction-intermediate-commit-cluster.js
When we have a query that results in a failure this will cause the leaders to abort the transaction on the followers. However, if the followers have transactions that are shared with leaders of other shards, and if one of those leaders has not yet seen the error, then it will happily continue to replicate to that follower. But if the follower has already aborted the transaction, then it will reject the replication request. Previously this would cause the follower to be dropped, but now this should be handled gracefully.
> [3.11] Fix handling of premature follower trx abortion

- js/common/bootstrap/modules.js
Add debug output to better understand failing test in https://arangodb.atlassian.net/browse/BTS-1373.
The debug output can be removed again once we have a better understanding of why the error occurs.
> add try...catch for debugging

- arangod/Agency/State.cpp
Debug aid for https://arangodb.atlassian.net/browse/BTS-1395
Add debug output in case a segfault happens when fetching agency logs.
> add debug output for agency segfault

- CHANGELOG
Documentation-only fix.
Remove a duplicate entry from the 3.9.11 CHANGELOG.
> remove duplicate entry from CHANGELOG

- js/client/modules/@arangodb/testutils/crash-utils.js
- js/client/modules/@arangodb/testutils/instance.js
temporarily restore the PID for locating coredumps on disk
> testing: we need to know the PID in order to calculate the filename

- arangod/Replication2/ReplicatedState/ReplicatedState.tpp
- arangod/Replication2/ReplicatedState/StateInterfaces.h
- arangod/Replication2/StateMachines/BlackHole/BlackHoleStateMachine.cpp
- arangod/Replication2/StateMachines/BlackHole/BlackHoleStateMachine.h
- arangod/Replication2/StateMachines/Document/DocumentFollowerState.cpp
- arangod/Replication2/StateMachines/Document/DocumentFollowerState.h
- tests/Replication2/Mocks/DocumentStateMocks.h
- tests/Replication2/Mocks/FakeReplicatedState.h
- tests/Replication2/ReplicatedState/StateMachines/DocumentState/CoreTest.cpp
- tests/Replication2/ReplicatedState/StateMachines/DocumentState/FollowerTest.cpp
- tests/Replication2/ReplicatedState/StateMachines/DocumentState/SnapshotTest.cpp
The _waitForIndex_ parameter is no longer needed. It was previously used during `acquireSnapshot`. This PR removes it.
> [CINFRA-708] Removing waitForIndex parameter

- CHANGELOG
- js/client/modules/@arangodb/test-helper.js
This tries to fix https://arangodb.atlassian.net/browse/BTS-1356 .
What happens is that there is currently a global timeout of 10s for all
`arangosh` subshells which are spawned by our testing framework. The
chaos tests use this for parallelism and at the same time they create
many situations in which shard followers get out of sync. The catchup
phase of a follower with its leader needs to stop writes to the shard
for some time, which can in testing situations be well more than 10s.
Therefore, we often hit timeouts in this situation.
The solution is to remove the artificial timeout of 10s for subshells
and go back to the default timeout of 1200s.
- [*] Tests
- [*] Backport for 3.11: …
> Fix chaos test timeouts: BTS-1356

- arangod/Scheduler/SupervisedScheduler.cpp
- arangod/Scheduler/SupervisedScheduler.h
- tests/js/client/server_parameters/test-return-queue-time-header-on.js
Backport of https://github.com/arangodb/arangodb/pull/18929
Try to make test more robust.
Previously the test sometimes produced the following error:
```
=== server_parameters_1 ===
* Test "server_parameters_1"
[FAILED]  tests/js/client/server_parameters/test-return-queue-time-header-on.js
"testQueueTimeHeaderNonZero" failed: Error: at assertion #754: assertTrue: (false) does not evaluate to true
(Error
at Object.testQueueTimeHeaderNonZero (tests/js/client/server_parameters/test-return-queue-time-header-on.js:98:7)
at tests/js/client/server_parameters/test-return-queue-time-header-on.js:170:9
at tests/js/client/server_parameters/test-return-queue-time-header-on.js:172:3
......    at Object.server_parameters (/work/ArangoDB/js/client/modules/@arangodb/testsuites/server_permissions.js:287:62 …
```
> attempt to stabilize a flaky test

- arangod/IResearch/GeoFilter.cpp
- tests/js/server/aql/aql-geo.inc
In case of query like GEO_DISTANCE(....) >0 custom storage value encoding was not set for internal filter. Now internal filter gets a copy of outer filter options and only then applies custom overrides.
> BTS-1398 Fix GEO_DISTANCE filter

- arangod/Aql/OptimizerRules.cpp
- tests/js/server/aql/aql-optimizer-rule-parallelize-gather-cluster.js
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/1269
disable `parallelize-gather` optimizer rules for some cases in which it can lead to "query id ... not found" errors. this change reverts the behavior of the `parallelize-gather` optimizer rule to the same state it had in 3.10. the rule will be disabled for some queries for which it was previously enabled only in devel/3.11. the rule will be enabled again for these queries with a separate PR that will contain a fix for the "query id ... not found" error and reenable the rule.
> disable `parallelize-gather` optimizer rules for some cases

- arangod/VocBase/Methods/Collections.cpp
- arangod/VocBase/vocbase.cpp
- tests/js/client/server_parameters/test-telemetrics-true-auth.js
*This just removes some singleServer checks around default replication factor. We always have the ClusterFeature, so we can just use it in any case.*
> [CINFRA] Reduce difference between single server and cluster again

- js/client/modules/@arangodb/testutils/result-processing.js
- use correct EE/CE prefix
- only include `time` attribute if we have valid data
- set the `failed` attribute to the number of failed tests instead of to some message
> Fix issues in junit xml generator

- arangod/Pregel/Algorithm.h
- arangod/Pregel/Algos/SSSP/SSSP.cpp
- arangod/Pregel/Algos/SSSP/SSSP.h
- arangod/Pregel/GraphStore/GraphSerdeConfig.h
- arangod/Pregel/IncomingCache.cpp
- arangod/Pregel/IncomingCache.h
- arangod/Pregel/OutgoingCache.cpp
- arangod/Pregel/OutgoingCache.h
- arangod/Pregel/Worker/Handler.h
- arangod/Pregel/Worker/State.h
- arangod/Pregel/Worker/VertexProcessor.cpp
- arangod/Pregel/Worker/VertexProcessor.h
- arangod/Pregel/Worker/Worker.cpp
- arangod/Pregel/Worker/Worker.h
Since we saw the little buggers in the profile, try and replace them with the abseil alternatives; while this might address the immediate pains of the performance regression between 3.10 and 3.11/devel it is not really a solution to the underlying performance problem.
This PR also reintroduces scaling the batch size for message caches as it was in 3.10; this is also a rather desparate move to get a handle on the performance differences between 3.10 and 3.11
> [GORDO-1642] Try and address some obvious timewasters

- arangod/Aql/QueryRegistry.cpp
- arangod/Aql/QueryRegistry.h
- arangod/Aql/RestAqlHandler.cpp
- arangod/Aql/RestAqlHandler.h
- tests/js/client/shell/shell-aql-regression-cluster.js
Previously an upstream operation that took longer than 30s would cause the request to abort with an error "query ID xxx not found"
> [BTS-1400] Fix query not found issue with parallel-gather

- arangod/Agency/State.cpp
Random willification of code:
change `TRI_ASSERT(...)` to `ADB_PROD_ASSERT(...)` so that we get the assertion failure and its output during RTA (release test automation), which builds in release mode with maintainer mode turned off.
> random code willification
