LICENSES-OTHER-COMPONENTS.md

Update version of fmt library in LICENSES-OTHER-COMPONENTS file.
Documentation-only PR

update version of fmt in documentation

---

arangod/Aql/IResearchViewExecutor.cpp
arangod/Aql/IResearchViewOptimizerRules.cpp
arangod/IResearch/IResearchFilterFactory.cpp
arangod/IResearch/IResearchFilterFactory.h
arangod/IResearch/IResearchInvertedIndex.cpp
arangod/IResearch/IResearchInvertedIndexMeta.cpp
arangod/IResearch/IResearchLinkMeta.cpp
arangod/IResearch/IResearchLinkMeta.h
arangod/IResearch/Search.cpp
tests/js/common/aql/aql-view-arangosearch-cluster.inc
tests/js/common/aql/aql-view-arangosearch-noncluster.js

[SEARCH-396] Use warnings instead of errors for search-alias views

---

CHANGELOG
arangod/Aql/OptimizerRules.cpp
arangod/Aql/OptimizerUtils.cpp
arangod/IResearch/IResearchInvertedIndex.cpp
arangod/IResearch/Search.cpp
tests/js/common/shell/shell-view-search-alias.js

Backport of https://github.com/arangodb/arangodb/pull/17158
Enterprise PR:  https://github.com/arangodb/enterprise/pull/1092

Bug fix 3.10/search 393

---

arangod/RocksDBEngine/RocksDBBuilderIndex.cpp
arangod/RocksDBEngine/RocksDBBuilderIndex.h
arangod/RocksDBEngine/RocksDBEngine.cpp
arangod/Transaction/Options.h
arangod/VocBase/Methods/Indexes.cpp

[CINFRA-556] Fix drop index operation with replication 2.0

---

tests/js/common/shell/shell-community-sharding-compat-cluster.js

one more test that was missing bulk inserts

one more place missing bulk insert

---

js/client/modules/@arangodb/testutils/crash-utils.js
js/client/modules/@arangodb/testutils/instance-manager.js
js/client/modules/@arangodb/testutils/testrunner.js

explain in more detail why we're killing the arangod here.

[testInfrastructure]: improve shutdown force messages

---

js/server/modules/@arangodb/aql-helper.js
tests/js/server/aql/aql-modify-Insert-noncluster.js
tests/js/server/aql/aql-modify-Modify-noncluster.js
tests/js/server/aql/aql-modify-Remove-noncluster.js
tests/js/server/aql/aql-modify-Update-noncluster.js
tests/js/server/aql/aql-modify-cluster.js
tests/js/server/aql/aql-modify-subqueries.js
tests/js/server/replication/static/replication-static.js

Remove redundant code from tests.
Only affects tests.

simplify tests

---

tests/js/client/shell/shell-transaction-intermediate-commit-cluster.js

Fix a test that often failed. Test-only bugfix.
The changes have been made in 3.9 and higher already.

fix failing test

---

arangod/Pregel/Conductor/Conductor.cpp
arangod/Pregel/Conductor/States/ComputingState.cpp
arangod/Pregel/Conductor/States/DoneState.cpp
arangod/Pregel/Conductor/WorkerApi.cpp
arangod/Pregel/Statistics.h
arangod/Pregel/Worker/Worker.cpp
arangod/Pregel/Worker/Worker.h
arangod/Pregel/WorkerConductorMessages.h

Uses inspector for pregel statistics and deletes some unused properties.

[PREGEL] Pregel use inspector for statistics

---

arangod/IResearch/IResearchInvertedIndex.cpp
arangod/IResearch/IResearchInvertedIndex.h
arangod/IResearch/IResearchRocksDBInvertedIndex.cpp
arangod/Indexes/Index.h
arangod/VocBase/LogicalCollection.cpp
tests/js/client/shell/shell-inventory-cluster.js
tests/js/client/shell/shell-inventory-noncluster.js
tests/js/server/dump/dump-authentication.js
tests/js/server/dump/dump-setup-cluster.js
tests/js/server/dump/dump-setup-common.inc
tests/js/server/dump/dump-setup-mixed.js
tests/js/server/dump/dump-setup.js
tests/js/server/dump/dump-test.inc

Search-401 Fix inverted index inventory

---

arangod/Pregel/CMakeLists.txt
arangod/Pregel/TypedBuffer.h

seens that our compiler environment on jenkins is inconsistent with everything that we run locally.

[PREGEL] Compilation fixes for pregel staging.

---

arangod/Cluster/AutoRebalance.cpp
arangod/Cluster/AutoRebalance.h
arangod/RestHandler/RestAdminClusterHandler.cpp

Small cleanup of rebalancing code.

small cleanup for rebalancing

---

tests/js/server/replication/ongoing/global/replication-ongoing-global.js
tests/js/server/replication/ongoing/replication-ongoing.js

Attempt to improve stability of replication tests. Test-only bugfix.

try to improve stability of replication tests

---

Documentation/DocuBlocks/Rest/Indexes/post_api_index_inverted.md
Documentation/DocuBlocks/Rest/Views/patch_api_view_properties_searchalias.md
Documentation/DocuBlocks/Rest/Views/post_api_view_searchalias.md
Documentation/DocuBlocks/Rest/Views/put_api_view_properties_searchalias.md

Docs: ArangoSearch v2 corrections

---

arangod/Pregel/Connection/NetworkConnection.cpp
tests/js/client/load-balancing/load-balancing-pregel-auth-cluster.js

Fixes jenkins errors on staging:
- Deletes brittle assertion in test
- Uses exception variables to make MSVC happy

[PREGEL] Bugfix/fix jenkins on staging

---

arangod/Aql/Expression.cpp
arangod/Aql/IndexNode.cpp
arangod/Aql/OptimizerUtils.cpp
arangod/Aql/OptimizerUtils.h
arangod/Aql/TraversalNode.cpp
arangod/Graph/BaseOptions.cpp
arangod/IResearch/IResearchDataStore.cpp
arangod/IResearch/IResearchFeature.cpp
arangod/IResearch/IResearchFilterFactory.cpp
tests/IResearch/IResearchInvertedIndexConditionTest.cpp
tests/js/server/aql/aql-inverted-index.js

SEARCH-402 Fix GEO_DISTANCE and others
SEARCH-403 Enable EXISTS for inverted indexes

SEARCH-402/403 Fixes

---

ubsan_arangodb_suppressions.txt

Suppress one more false-positive UB message in RocksDB code.

suppress more false-positive UB messages in rocksdb

---

tests/js/server/replication2/replication2-replicated-state-document-store.js

Fix a test that inserted too many documents in a replication2-related test for truncate operations.
No backports necessary.

fix replication2 test that inserted too many documents

---

tests/js/client/server_parameters/exclusive-collections-off.js

Test-only change.
The same change has been made in devel already, and for unknown reasons it has helped to stabilize the test.

stabilize a test

---

js/client/modules/@arangodb/testutils/test-utils.js

backport of https://github.com/arangodb/arangodb/pull/17259

add proper brackets to fix asan test

---

js/client/modules/@arangodb/testsuites/export.js

backport of https://github.com/arangodb/arangodb/pull/17207

BTS-1046: print test-info, correct invoking of exports (#17207)

---

tests/js/common/shell/shell-community-sharding-compat-cluster.js

backport of https://github.com/arangodb/arangodb/pull/17189

one more place missing bulk insert (#17189)

---

CHANGELOG
tests/js/client/shell/api/api-gharial-spec.js
tests/js/client/shell/api/cluster-metrics-cluster-spec.js

3.10 Backport of: 
- https://github.com/arangodb/arangodb/pull/17203
Please see info there.

BTS-943: testing: move test out of non-existing suite, adjust to new instance methods

---

arangod/Aql/Expression.cpp
arangod/Aql/IndexNode.cpp
arangod/Aql/OptimizerUtils.cpp
arangod/Aql/OptimizerUtils.h
arangod/Aql/TraversalNode.cpp
arangod/Graph/BaseOptions.cpp
arangod/IResearch/IResearchDataStore.cpp
arangod/IResearch/IResearchFeature.cpp
arangod/IResearch/IResearchFilterFactory.cpp
tests/IResearch/IResearchInvertedIndexConditionTest.cpp
tests/js/server/aql/aql-inverted-index.js

SEARCH-402/403 Fixes 3.10

---

arangod/Aql/IResearchViewExecutor.cpp
arangod/Aql/IResearchViewOptimizerRules.cpp
arangod/IResearch/AqlHelper.cpp
arangod/IResearch/AqlHelper.h
arangod/IResearch/ExpressionFilter.cpp
arangod/IResearch/ExpressionFilter.h
arangod/IResearch/IResearchFilterContext.h
arangod/IResearch/IResearchFilterFactory.cpp
arangod/IResearch/IResearchFilterFactory.h
arangod/IResearch/IResearchFilterFactoryCommon.h
arangod/IResearch/IResearchInvertedIndex.cpp
arangod/IResearch/IResearchKludge.cpp
arangod/IResearch/IResearchKludge.h
arangod/IResearch/Search.h
tests/IResearch/ExpressionFilterTest.cpp
tests/IResearch/GeoAnalyzerTest.cpp
tests/IResearch/IResearchFilterArrayInTest.cpp
tests/IResearch/IResearchFilterBooleanTest.cpp
tests/IResearch/IResearchFilterCompareTest.cpp
tests/IResearch/IResearchFilterFunctionTest.cpp
tests/IResearch/IResearchFilterGeoTest.cpp
tests/IResearch/IResearchFilterInTest.cpp
tests/IResearch/IResearchQueryOrTest.cpp
tests/IResearch/common.cpp
tests/IResearch/common.h

[SEARCH-391] Correctly handle negations in conjunction with nested queries. (#17186)

---

arangod/Cluster/ClusterInfo.cpp
arangod/Replication2/ReplicatedState/ReplicatedState.tpp
arangod/Replication2/StateMachines/Document/DocumentStateAgencyHandler.cpp
arangod/Replication2/StateMachines/Document/DocumentStateAgencyHandler.h
arangod/Replication2/StateMachines/Document/DocumentStateHandlersFactory.cpp
arangod/Replication2/StateMachines/Document/DocumentStateHandlersFactory.h
arangod/Replication2/StateMachines/Document/DocumentStateMachine.h
arangod/Replication2/StateMachines/Document/DocumentStateMachineFeature.cpp
tests/js/client/shell/transaction/replication2_recovery/shell-transaction-replication2-recovery.js

This PR enables an older test that was disabled until now due to the maintenance dropping replicated states. Apart from that, an additional test has been added.
Some unexpected bug-fixes (race between replicated state drop and creation) and refactoring were done on the side.

[CINFRA-531] Move Shard Tests

---

CHANGELOG
arangod/Graph/GraphOperations.cpp
tests/js/client/shell/api/general-graph.js

Backport of: https://github.com/arangodb/arangodb/pull/17261
Please see info there.

Removal of already deleted orphan collections out of graph definition

---

3rdParty/README_maintainers.md
3rdParty/snappy/snappy-1.1.9/CMakeLists.txt
lib/CMakeLists.txt

[3.9] Build Snappy with RTTI (and fix MacOS exceptions) 

---

tests/js/common/shell/shell-pregel-components.js

bulk inserts of test setup to save computing bandwith.

bulk test, don't use graph module

---

arangod/IResearch/IResearchFeature.cpp
tests/IResearch/IResearchFeatureTest.cpp
tests/IResearch/IResearchLinkTest.cpp

Fix handling of removals in presence of primary sort

[SEARCH-406] Fix handling of removals in presence of primary sort

---

arangod/RestHandler/RestCollectionHandler.cpp
arangod/VocBase/LogicalCollection.cpp
arangod/VocBase/LogicalCollection.h

This is a suggested improvement for  #16845

Suggested improvement for #16845

---

tests/IResearch/IResearchQueryCommon.h

Add parameter for viewName in checkView method

Added default parameter to checkView

---

CHANGELOG

Added forgotten changelog entry for original (already merged) PR:
* https://github.com/arangodb/arangodb/pull/16845

[ForgottenChangelog] Bug fix/ee edges shards method

---

tests/IResearch/IResearchQueryAggregateTest.cpp
tests/IResearch/IResearchQueryBooleanTermTest.cpp
tests/IResearch/IResearchQueryCommon.h
tests/IResearch/IResearchQueryExistsTest.cpp
tests/IResearch/IResearchQueryGeoContainsTest.cpp
tests/IResearch/IResearchQueryGeoDistanceTest.cpp
tests/IResearch/IResearchQueryGeoInRangeTest.cpp
tests/IResearch/IResearchQueryGeoIntersectsTest.cpp
tests/IResearch/IResearchQueryInTest.cpp
tests/IResearch/IResearchQueryJoinTest.cpp
tests/IResearch/IResearchQueryLateMaterializationTest.cpp
tests/IResearch/IResearchQueryLevenshteinMatchTest.cpp
tests/IResearch/IResearchQueryMinMatchTest.cpp
tests/IResearch/IResearchQueryNGramMatchTest.cpp
tests/IResearch/IResearchQueryNoMaterializationTest.cpp
tests/IResearch/IResearchQueryNullTermTest.cpp
tests/IResearch/IResearchQueryNumericTermTest.cpp
tests/IResearch/IResearchQueryOptimizationTest.cpp
tests/IResearch/IResearchQueryOptionsTest.cpp
tests/IResearch/IResearchQueryOrTest.cpp
tests/IResearch/IResearchQueryPhraseTest.cpp
tests/IResearch/IResearchQueryScorerTest.cpp
tests/IResearch/IResearchQuerySelectAllTest.cpp
tests/IResearch/IResearchQueryStartsWithTest.cpp
tests/IResearch/IResearchQueryStringTermTest.cpp
tests/IResearch/IResearchQueryTokensTest.cpp
tests/IResearch/IResearchQueryTraversalTest.cpp
tests/IResearch/IResearchQueryValueTest.cpp
tests/IResearch/IResearchQueryWildcardTest.cpp

Add tests for query search-alias view

---

arangod/IResearch/IResearchFilterFactory.cpp
arangod/IResearch/IResearchKludge.cpp
arangod/IResearch/IResearchKludge.h
tests/IResearch/ExpressionFilterTest.cpp
tests/IResearch/GeoDistanceFilterTest.cpp
tests/IResearch/GeoFilterTest.cpp
tests/IResearch/IResearchFilterFunctionTest.cpp
tests/IResearch/IResearchFilterNestedTest.cpp
tests/IResearch/IResearchViewTest.cpp
tests/IResearch/common.cpp

[SEARCH-407] [SEARCH-405] [SEARCH-404] Fix handling of ALL quantifier

---

tests/js/client/server_parameters/wal-archive-size-limit-large-noncluster.js
tests/js/client/server_parameters/wal-archive-size-limit-small-noncluster.js
tests/js/client/server_parameters/wal-archive-size-limit.inc

Simplify test code.
Test-only refactoring.

simplify WAL archive size limit test code

---

CHANGELOG
arangod/RestHandler/RestUsersHandler.cpp
tests/js/client/shell/api/users.js

3.10 backport of https://github.com/arangodb/arangodb/pull/16675.

Fixed BTS-852

---

arangod/Aql/CMakeLists.txt
arangod/Aql/Inspectors/BaseInspectors/BaseNode.h
arangod/Aql/Inspectors/ReturnNode.h
arangod/Aql/Inspectors/Types/Types.h
arangod/Aql/Optimizer2/CMakeLists.txt
arangod/Aql/Optimizer2/Optimizer2.cpp
arangod/Aql/Optimizer2/Optimizer2.h
arangod/Aql/Optimizer2/ReturnNode.h
arangod/Aql/Optimizer2/VPackInspection.h
arangod/Aql/Query.cpp
arangod/Aql/Query.h
arangod/RestHandler/RestExplainHandler.cpp
arangod/V8Server/v8-vocbase.cpp
tests/Optimizer2/CMakeLists.txt
tests/Optimizer2/PlanNodes/CMakeLists.txt
tests/Optimizer2/PlanNodes/ReturnNode.cpp

Just some scaffolding to write tests for optimizer stuff.

[OPTIMIZER-2.0] Testbed

---

CHANGELOG
arangod/RestHandler/RestUsersHandler.cpp
tests/js/client/shell/api/users.js

3.9 backport of https://github.com/arangodb/arangodb/pull/16675.

Fix for BTS-852

---

tests/js/client/shell/transaction/shell-transaction-cluster.js

Improved log information in case of failure.

Adding extra log info

---

tests/test-definitions.txt

re-order testcases, fix parallelity for smaller systems to smoothen test execution.

[testing] re-shuffle testcases

---

js/client/modules/@arangodb/testutils/crash-utils.js
js/client/modules/@arangodb/testutils/instance.js

bypass all report logic and hot exit if in interactive mode and SUT is not healthy anymore.

[testing] when running interactive bail out quick on error

---

tests/js/common/shell/shell-pregel-multicollection-edgecol.js

reduce test resource usage by properly bulking test data creation

BTS-1077: bulk test data creation

---

CHANGELOG
arangod/Cluster/ClusterInfo.cpp
arangod/RestHandler/RestCollectionHandler.cpp
arangod/Sharding/ShardingInfo.cpp
arangod/Sharding/ShardingInfo.h
arangod/VocBase/LogicalCollection.cpp
arangod/VocBase/LogicalCollection.h
js/server/modules/@arangodb/testutils/aql-graph-traversal-generic-graphs.js
js/server/modules/@arangodb/testutils/aql-graph-traversal-generic-tests.js

Backport for original PR: 
* https://github.com/arangodb/arangodb/pull/16845
Please see all details there.
**There is also an EE Companion:**
* https://github.com/arangodb/enterprise/pull/1109

[BTS-941] EnterpriseGraph edge shards() method bug-fix

---

Documentation/DocuBlocks/Rest/Collections/1_structs.md
Documentation/DocuBlocks/Rest/Collections/post_api_collection.md
Documentation/DocuBlocks/Rest/Cursors/post_api_cursor.md
Documentation/DocuBlocks/Rest/Documents/delete_mutliple_documents.md
Documentation/DocuBlocks/Rest/Documents/delete_remove_document.md
Documentation/DocuBlocks/Rest/Documents/patch_update_document.md
Documentation/DocuBlocks/Rest/Documents/patch_update_multiple_documents.md
Documentation/DocuBlocks/Rest/Documents/post_create_document.md
Documentation/DocuBlocks/Rest/Documents/post_create_multiple_document.md
Documentation/DocuBlocks/Rest/Documents/put_replace_document.md
Documentation/DocuBlocks/Rest/Documents/put_replace_multiple_documents.md
Documentation/DocuBlocks/Rest/Graph/general_graph_create_http_examples.md
Documentation/DocuBlocks/Rest/Graph/general_graph_edge_definition_add_http_examples.md
Documentation/DocuBlocks/Rest/Graph/general_graph_edge_definition_modify_http_examples.md
Documentation/DocuBlocks/Rest/Graph/general_graph_vertex_collection_add_http_examples.md
Documentation/DocuBlocks/Rest/Indexes/post_api_index.md
Documentation/DocuBlocks/Rest/Indexes/post_api_index_geo.md
Documentation/DocuBlocks/Rest/Indexes/post_api_index_inverted.md
Documentation/DocuBlocks/Rest/Indexes/post_api_index_persistent.md
Documentation/DocuBlocks/Rest/Pregel/1_struct.md
arangod/Replication/DatabaseInitialSyncer.cpp
js/client/modules/@arangodb/arango-collection.js

Documentation-3.10/api-fixes-2022-10-06

---

arangod/IResearch/IResearchDataStoreMeta.h
tests/IResearch/IResearchFilterMinHashMatchTest.cpp
tests/IResearch/IResearchFilterNestedTest.cpp
tests/js/common/aql/aql-arangosearch-offset-info-community.js
utils/generateExamples.py

Fix license headers for files, as reported in Github issue #17435

Fix license headers for files

---

js/common/modules/@arangodb/graph/pregel-test-helpers.js
tests/js/client/load-balancing/load-balancing-pregel-noauth-cluster.js
tests/js/common/shell/shell-pregel-basics-example.js
tests/js/common/shell/shell-pregel-components.js
tests/js/common/shell/shell-pregel-multicollection-edgecol.js
tests/js/common/shell/shell-pregel-random.js
tests/js/common/shell/shell-pregel-start-cluster.js

Use a js-helper function to check if a pregel run is finished to make everywhere the same check and to be able to change that function easily if e.g. our state names change.

[PREGEL] Check if pregel is finished with helper function

---

arangod/RocksDBEngine/RocksDBChecksumEnv.cpp

Potentially fix an assertion on macOS.

BTS-1097: potentially fix assertion on mac

---

arangod/IResearch/Search.cpp
tests/js/client/chaos/test-chaos-load-common.inc

Add views to chaos test

---

Documentation/Scripts/exampleHeader.js
utils/generateExamples.py

Forward port of #17452
Jenkins green https://jenkins.arangodb.biz/view/Documentation/job/arangodb-ANY-examples/2544/

Expose assert() function in @EXAMPLE_ARANGOSH_OUTPUT (JS API) examples

---

CHANGELOG
arangod/Cluster/ClusterMethods.cpp

Backport of https://github.com/arangodb/arangodb/pull/17425.

[3.10][BTS-1085] create collection shard balance

---

arangod/IResearch/IResearchDataStore.cpp
arangod/IResearch/IResearchDataStore.h
arangod/IResearch/IResearchDocument.cpp
arangod/IResearch/IResearchDocument.h
arangod/IResearch/IResearchLinkHelper.cpp
arangod/Transaction/Helpers.cpp
arangod/Transaction/Methods.cpp
tests/IResearch/IResearchDocumentTest.cpp
tests/js/client/chaos/test-chaos-load-common.inc

https://github.com/arangodb/enterprise/pull/1127

SEARCH-418 Fix _id for primarySort

---

tests/js/client/shell/shell-iterators-read-standalone.js
tests/js/client/shell/shell-iterators-read-transaction.js
tests/js/client/shell/shell-iterators-write-standalane.js
tests/js/client/shell/shell-iterators-write-transaction.js
tests/js/client/shell/shell-iterators.inc

backport of https://github.com/arangodb/arangodb/pull/17198

setUpAll/tearDownAll for performance reasons (#17322)

---

arangod/Pregel/Conductor/Conductor.cpp
arangod/Pregel/Conductor/States/CanceledState.cpp
arangod/Pregel/Conductor/States/CanceledState.h
arangod/Pregel/Conductor/States/ComputingState.cpp
arangod/Pregel/Conductor/States/ComputingState.h
arangod/Pregel/Conductor/States/FatalErrorState.h
arangod/Pregel/Conductor/States/InitialState.cpp
arangod/Pregel/Conductor/States/InitialState.h
arangod/Pregel/Conductor/States/LoadingState.cpp
arangod/Pregel/Conductor/States/LoadingState.h
arangod/Pregel/Conductor/States/State.h
arangod/Pregel/Conductor/States/StoringState.cpp
arangod/Pregel/Conductor/States/StoringState.h
arangod/Pregel/Conductor/WorkerApi.h
arangod/Pregel/Messaging/Aggregate.h
arangod/Pregel/Messaging/Message.h
arangod/Pregel/Messaging/MessageQueue.h
arangod/Pregel/PregelFeature.cpp
arangod/Pregel/Worker/ConductorApi.cpp
arangod/Pregel/Worker/Worker.cpp
arangod/Pregel/Worker/Worker.h
tests/Pregel/Messaging/AggregateTest.cpp
tests/Pregel/Messaging/CMakeLists.txt
tests/Pregel/Messaging/MessageQueueTest.cpp

This PR does some cleanup: It
-  cleans up the status update call in the worker,
- deletes the unused AggregateCount struct.

[PREGEL] Cleanup

---

arangod/Cluster/ClusterMethods.cpp

Remove unused variable from count method.

remove unused variable from count method

---

arangod/RocksDBEngine/RocksDBTransactionState.cpp

remove unused lambda capture

---

js/client/modules/@arangodb/testsuites/recovery.js
js/client/modules/@arangodb/testutils/test-utils.js
js/client/modules/@arangodb/testutils/testing.js
tests/js/server/recovery/check-warnings.js

backport of https://github.com/arangodb/arangodb/pull/17276

[testing] 3.8: Bug fix/asan timeouts, disable coredumping #17276

---

js/client/modules/@arangodb/testsuites/recovery.js
js/client/modules/@arangodb/testutils/test-utils.js
js/client/modules/@arangodb/testutils/testing.js
tests/js/server/recovery/check-warnings.js

backport of https://github.com/arangodb/arangodb/pull/17276

 [testing] 3.9: Bug fix/asan timeouts, disable coredumping #17276 

---

js/client/modules/@arangodb/testsuites/recovery.js
js/client/modules/@arangodb/testutils/crash-utils.js
js/client/modules/@arangodb/testutils/instance.js
js/client/modules/@arangodb/testutils/test-utils.js
js/client/modules/@arangodb/testutils/testing.js
tests/js/server/recovery/check-warnings.js

backport of https://github.com/arangodb/arangodb/pull/17276

[testing] 3.10: Bug fix/asan timeouts, disable coredumping

---

tests/js/client/shell/shell-iterators-read-standalone.js
tests/js/client/shell/shell-iterators-read-transaction.js
tests/js/client/shell/shell-iterators-write-standalane.js
tests/js/client/shell/shell-iterators-write-transaction.js
tests/js/client/shell/shell-iterators.inc
tests/js/common/shell/shell-community-sharding-compat-cluster.js
tests/js/common/shell/shell-pregel-components.js
tests/js/common/shell/shell-pregel-multicollection-edgecol.js
tests/js/server/aql/aql-optimizer-collect-count.js

Backports collection of:
- https://github.com/arangodb/arangodb/pull/17329 -  tests/js/common/shell/shell-pregel-multicollection-edgecol.js
- https://github.com/arangodb/arangodb/pull/17322 -  split shell iterators suite
- https://github.com/arangodb/arangodb/pull/17319 -  tests/js/common/shell/shell-pregel-components.js
- https://github.com/arangodb/arangodb/pull/17189 -  tests/js/common/shell/shell-community-sharding-compat-cluster.js
- https://github.com/arangodb/arangodb/pull/17038 -  tests/js/server/aql/aql-optimizer-collect-count.js

BTS-999: Bug fix 3.8/bulk inserts

---

tests/Pregel/Messaging/MessageQueueTest.cpp

Use thread instead of jthread in order to fix Mac and Windows runs

[PREGEL] Bugfix/fix pregel staging

---

CHANGELOG
js/common/modules/@arangodb/aql/explainer.js

Show number of HTTP requests in cluster query profiles

Show number of HTTP requests in cluster query profiles.

---

3rdParty/README_maintainers.md

Remove patch instruction for snowball, as the memory leak it referred to has been fixed in upstream snowball.

remove patch instruction for snowball

---

tests/js/server/resilience/failover/resilience-synchronous-repl-cluster.js
tests/test-definitions.txt

make sure no servers are left behind in stopped mode, so we don't get useless core analysis.

BTS-1098: Bug fix/fix resillience teardown

---

CMakeLists.txt

Without this change it not possible to
```cpp
make -j arangodb
./scripts/unittest
```

Add missing targets

---

lib/Ssl/SslInterface.cpp
scripts/startLocalCluster.sh

Enterprise companion PR: https://github.com/arangodb/enterprise/pull/1143
fixes a potential memleak in case of OpenSSL initialization going wrong, suppresses an OpenSSL warning about invalid padding.

cleanup of license manager code

---

arangod/Pregel/CommonFormats.h
tests/Pregel/Messaging/MessageQueueTest.cpp

Try to fix staging Jenkins run:
- Fix windows run by circumventing implicit conversion
- Fix Mac run by deleting failing tests that will be redundant anyway when we use a different queue

[PREGEL] Bugfix/fix staging build

---

tsan_arangodb_suppressions.txt

Add suppression for iresearch

---

tests/js/client/server_parameters/wal-archive-size-limit-large-noncluster.js
tests/js/client/server_parameters/wal-archive-size-limit-small-noncluster.js
tests/js/client/server_parameters/wal-archive-size-limit.inc

Decrease chance of test failing due to not running for long enough.

increase test timeout

---

tests/test-definitions.txt

similar tests would be launching to close, probably producing bad load patterns.

[testing] distribute these tests, so the same tests don't run in parallel

---

tests/test-definitions.txt

as we saw in one testcases the agency was unable to form due to missing system resources.
Project more system resources to this test.

[testing] increase resource usage

---

tests/test-definitions.txt

backport of https://github.com/arangodb/arangodb/pull/17579

increase resource usage

---

tests/test-definitions.txt

backport of https://github.com/arangodb/arangodb/pull/17446

give the cluster fuzzer tests more resources

---

tests/js/client/server_parameters/wal-archive-size-limit-small-noncluster.js

Backport of https://github.com/arangodb/arangodb/pull/17589
Decrease chance of test failing due to not running for long enough.

willify a test

---

Documentation/DocuBlocks/Rest/Collections/put_api_collection_load_indexes_in_memory.md

Follow-up on https://github.com/arangodb/arangodb/pull/17478

Improve put_api_collection_load_indexes_into_memory DocuBlock

---

lib/V8/v8-utils.cpp

Fix division by zero

---

3rdParty/iresearch/core/index/segment_writer.cpp
3rdParty/iresearch/core/index/segment_writer.hpp
arangod/IResearch/IResearchLink.cpp
tests/js/client/chaos/test-chaos-load-common.inc

Finally fix issues with inconsistency of remove/inserts order

IResearch backports 3.9

---

arangod/IResearch/IResearchLinkHelper.cpp
arangod/Indexes/IndexFactory.cpp
arangod/Indexes/IndexFactory.h
arangod/RestHandler/RestReplicationHandler.cpp
arangod/RocksDBEngine/RocksDBCollection.cpp
tests/js/common/aql/aql-arangosearch-inverted-index-search-alias-community.js

Now we check index exist before create index

SEARCH-385 and other fixes

---

arangod/IResearch/IResearchDataStore.h

Search fix asan

---

arangod/IResearch/IResearchDataStore.h
arangod/IResearch/IResearchLinkHelper.cpp
arangod/Indexes/IndexFactory.cpp
arangod/Indexes/IndexFactory.h
arangod/RestHandler/RestReplicationHandler.cpp
arangod/RocksDBEngine/RocksDBCollection.cpp
tests/js/client/chaos/test-chaos-load-common.inc
tests/js/common/aql/aql-arangosearch-inverted-index-search-alias-community.js

SEARCH backports to 3.10

---

tests/js/server/aql/aql-temp-rocksdb-storage.js

Enterprise companion PR: https://github.com/arangodb/enterprise/pull/1152
Fix tests on Windows that were not executed on Windows before.

fix test on Windows

---

Documentation/DocuBlocks/Rest/Views/patch_api_view_properties_arangosearch.md
Documentation/DocuBlocks/Rest/Views/post_api_view_arangosearch.md
Documentation/DocuBlocks/Rest/Views/put_api_view_properties_arangosearch.md

See https://github.com/arangodb/docs/pull/1191 (to be merged for v3.9.6)

arangosearch Views: Add primarySortCache and primaryKeyCache options to DocuBlocks

---

arangod/Aql/Expression.cpp
arangod/Aql/V8Executor.cpp
arangod/Aql/V8Executor.h

Remove unused code parts and parameters from V8Executor::handleV8Error.

simplify V8Executor method

---

Documentation/DocuBlocks/Rest/Administration/get_admin_server_tls.md
Documentation/DocuBlocks/Rest/Pregel/delete_api_control_pregel_cancel.md
Documentation/DocuBlocks/Rest/Pregel/get_api_control_pregel_status.md
Documentation/DocuBlocks/Rest/Replication/get_api_wal_access_tail.md

Backport of https://github.com/arangodb/arangodb/pull/17687

DOC-268 | Documentation 3.8/fix-swagger-issues

---

Documentation/DocuBlocks/Rest/Administration/get_admin_server_tls.md
Documentation/DocuBlocks/Rest/Pregel/delete_api_control_pregel_cancel.md
Documentation/DocuBlocks/Rest/Pregel/get_api_control_pregel_status.md
Documentation/DocuBlocks/Rest/Replication/get_api_wal_access_tail.md

Backport of https://github.com/arangodb/arangodb/pull/17687

DOC-268 | Documentation 3.9/fix-swagger-issues

---

Documentation/DocuBlocks/Rest/Administration/get_admin_server_tls.md
Documentation/DocuBlocks/Rest/Pregel/delete_api_control_pregel_cancel.md
Documentation/DocuBlocks/Rest/Pregel/get_api_control_pregel_status.md
Documentation/DocuBlocks/Rest/Pregel/post_api_control_pregel_start.md
Documentation/DocuBlocks/Rest/Replication/get_api_wal_access_tail.md

DOC-268 | Documentation 3.10/fix swagger issues

---

Documentation/Metrics/arangodb_http1_connections_total.yaml

Metrics: Adjust version of `arangodb_http1_connections_total`

---

lib/CMakeLists.txt

Remove unnecessary line

---

tests/js/client/shell/transaction/shell-transaction-cluster.js

This is a quick fix for devel, equivalent of https://github.com/arangodb/arangodb/pull/17660

Fix term bumping

---

arangod/ClusterEngine/ClusterTransactionState.cpp
arangod/IResearch/IResearchLink.cpp
arangod/IResearch/IResearchLink.h
arangod/RocksDBEngine/Methods/RocksDBTrxBaseMethods.cpp
arangod/RocksDBEngine/Methods/RocksDBTrxBaseMethods.h
arangod/StorageEngine/TransactionState.h
arangod/Transaction/Methods.cpp
arangod/Transaction/Methods.h
tests/Mocks/StorageEngineMock.cpp
tests/js/client/chaos/test-chaos-load-common.inc

https://arangodb.atlassian.net/browse/SEARCH-430

Backport intermediate commit 3.9

---

CONTRIBUTING.md
Documentation/Metrics/template.yaml

Also see https://github.com/arangodb/docs/pull/1210

README: How to add .setIntroducedIn() and metrics version info

---

CHANGELOG
tests/IResearch/IResearchIndex-test.cpp
tests/IResearch/IResearchLinkMeta-test.cpp

Backport of https://github.com/arangodb/arangodb/pull/17772 
Enterprise PR: https://github.com/arangodb/enterprise/pull/1174

Bug fix 3.9.6/BTS-1153 geojson search cache

---

arangod/IResearch/IResearchAnalyzerFeature.cpp

Fixes analyzers loading for oneshard database. In case of oneshard assumption is broken (satellite collection/dirty-reads) just regular analyzer loading is executed
Enterprise PR: https://github.com/arangodb/enterprise/pull/1175

Fix SEARCH-429 OneShard analyzers loading optimization

---

tsan_arangodb_suppressions.txt

Fix namespace in suppression

---

CHANGELOG
arangod/IResearch/IResearchFilterFactory.cpp
arangod/RestServer/TtlFeature.cpp
arangod/V8Server/V8Context.cpp
arangod/V8Server/V8Context.h
arangod/V8Server/V8DealerFeature.cpp
tests/js/server/aql/aql-inverted-index.js
tsan_arangodb_suppressions.txt

Backports
#17751 
#17733 
#17731 
#17720 
Enterprise PR: https://github.com/arangodb/enterprise/pull/1165

Bug fix 3.10/search 433 make field name check earlier + tsan issues

---

arangod/IResearch/GeoFilter.cpp
arangod/IResearch/GeoFilter.h

Fixes for ArangoSearch geo support revealed by `aql-geo.js`.

Bug fix/geo filter

---

3rdParty/iresearch/core/formats/formats_burst_trie.cpp

Backport of https://github.com/arangodb/arangodb/pull/17816

[3.9] Bug fix/geo filter

---

arangod/InternalRestHandler/InternalRestTraverserHandler.cpp

fix assertion failure

---

arangod/Transaction/Methods.cpp

Augment assertion failure with diagnostic output, so that we can understand the cause of the assertion failure better.

add debug output to understand assertion failure

---

tests/js/common/shell/shell-pregel-basics-example.js
tests/js/common/shell/shell-pregel-start-cluster.js

I missed this in the previous PR (https://github.com/arangodb/arangodb/pull/17802)
Enterprise PR: https://github.com/arangodb/enterprise/pull/1178

[PREG-183] remove async in tests

---

arangod/Replication2/ReplicatedState/FollowerStateManager.tpp

Downgrade a log error message to a log debug message in case of (expected) retry in replication2.

downgrade a log error message to a log debug message

---

js/client/modules/@arangodb/test-helper.js
lib/V8/v8-deadline.cpp
tests/js/client/chaos/test-chaos-load-common.inc

We had a test lock up without precise information. Improve the situation.

better indicate test state during shutdown

---

arangod/RocksDBEngine/RocksDBIterators.cpp
arangod/RocksDBEngine/RocksDBIterators.h

This reverst some unnecessary changes from 
https://github.com/arangodb/arangodb/pull/17778
which were found after merging.
- [*] :hammer: Refactoring/simplification

Undo some unnecessary changes

---

arangod/Pregel/Actor/Actor.h
arangod/Pregel/Actor/ActorBase.h
arangod/Pregel/Actor/ActorPID.h
arangod/Pregel/Actor/Dispatcher.h
arangod/Pregel/Actor/HandlerBase.h
arangod/Pregel/Actor/Message.h
arangod/Pregel/Actor/Runtime.h
arangod/Pregel/tests/Actor/MultiRuntimeTest.cpp
arangod/Pregel/tests/Actor/PingPongActors.h
lib/Inspection/Format.h

Add formatters for all actor types like Actor, Runtime, Messages and States.

[PREG-220] Add formatters

---

arangod/Replication2/StateMachines/Document/DocumentFollowerState.cpp
arangod/Replication2/StateMachines/Document/DocumentFollowerState.h

I lost my patience with git while merging staging back into  #17759.

[CINFRA-619] Deadlock in DocumentFollowerState

---

lib/Basics/ThreadGuard.h

This class is anti-pattern for common code (it shouldn't create threads).
It's ok in tests but only in them.

Restrict test only deps

---

client-tools/Shell/V8ClientConnection.cpp

Small fix to make the initial connection also use JSON-based communication.

arangosh: Force JSON in request for connection check if --server.force-json is enabled

---

arangod/Sharding/ShardingStrategyDefault.cpp
arangod/Sharding/ShardingStrategyDefault.h
lsan_arangodb_suppressions.txt
ubsan_arangodb_suppressions.txt

Fix san issues in cluster

---

arangod/Aql/ModificationExecutorAccumulator.h

Use a compact velocypack array in ModificationExecutorAccumulator.
This allows using a velocypack array representation without an index table, which leads to smaller size and less overhead when closing the array (the index table would be constructed upon close).
The performance overhead may be minimal, but this also allows saving a bit of memory.

use a compact velocypack array in ModificationExecutorAccumulator

---

arangod/Aql/AqlCall.h
arangod/Aql/BlocksWithClients.cpp
arangod/Aql/BlocksWithClients.h

BlocksWithClients contained some dead code, which is removed by this PR.

clean up BlocksWithClients

---

arangod/Aql/Functions.cpp

Improve performance of AQL distance functions `COSINE_SIMILARITY`, `L1_DISTANCE` and `L2_DISTANCE`, at least slightly.
Previously, each array member was accessed via `VPackSlice::at(pos)`. this can have considerable overhead, because for each member the `at()` function needs to determine the velocypack array type, look up the index table etc.
Instead, now use a VPackArrayIterator to iterate over the array members. this does not need any additional time for accessing an element, because the iterator is positioned at the right location automatically.

improve performance of distance functions

---

arangod/RestServer/DatabaseFeature.cpp

This PR fixes some formatting issues that were unintentionally brought to devel.

Fixing formatting issues

---

README.md

Updated ArangoDB logo.

---

README.md

Remove broken image reference from readme.

---

tests/js/client/shell/shell-admin-cluster-rebalance.js

Backport for https://github.com/arangodb/arangodb/pull/17933.

Bug fix 3.10/rebalance test request

---

arangod/RocksDBEngine/RocksDBChecksumEnv.cpp

This PR fixes a potential race during hot backup creation, described in https://arangodb.atlassian.net/browse/BTS-1192:
There has been a report about the following error occuring every hour:
```
ERROR [d5f51] {backup} Source file engine_rocksdb/002516.sst does not have a hash file.
```
More details can be found in the BTS ticket.

BTS-1192: fix potential race in sha creation during hot backup

---

3rdParty/s2geometry/master/CMakeLists.txt
3rdParty/s2geometry/master/src/python/pywraps2_test.py
3rdParty/s2geometry/master/src/python/s2_common.i
3rdParty/s2geometry/master/src/s2/encoded_s2point_vector.cc
3rdParty/s2geometry/master/src/s2/s2loop.cc
3rdParty/s2geometry/master/src/s2/s2loop.h
3rdParty/s2geometry/master/src/s2/s2polygon.cc
3rdParty/s2geometry/master/src/s2/util/gtl/compact_array.h
LICENSES-OTHER-COMPONENTS.md

Minimal s2 update to fix sanitizer issue

---

3rdParty/README_maintainers.md

Added documentation for a jemalloc patch, upon request of @dothebart

added documentation for jemalloc patch

---

js/client/modules/@arangodb/testsuites/rta_makedata.js

* added server options for arangosearch cache in RTA
Backport of https://github.com/arangodb/arangodb/pull/17978

added server options for arangosearch cache in RTA

---

CHANGELOG
js/apps/system/_admin/aardvark/APP/frontend/js/views/navigationView.js

3.9 Backport of:
* https://github.com/arangodb/arangodb/pull/17916
Please see all details there.

[FE-48] only admin see license info PART2 

---

tests/js/client/shell/api/api-gharial-spec.js
tests/js/client/shell/api/cluster-metrics-cluster-spec.js

Backport of https://github.com/arangodb/arangodb/pull/17203

BTS-943: testing: move test out of non-existing suite, adjust to new instance methods (#17203)

---

tsan_arangodb_suppressions.txt

Fix devel tsan suppressions

---

arangod/IResearch/GeoAnalyzer.cpp
arangod/IResearch/GeoAnalyzer.h
arangod/IResearch/GeoFilter.cpp
tests/IResearch/GeoAnalyzerTest.cpp
tests/js/server/aql/aql-geo.js

Shape centroid not necessarily contained in this shape.
So we should add centroid terms in index in such case.

[SEARCH-284] Fix geo distance/in_range for search

---

arangod/Aql/Functions.cpp
arangod/Replication2/Methods.cpp
arangod/Replication2/ReplicatedLog/NetworkMessages.cpp
arangod/RestHandler/RestAdminClusterHandler.cpp
arangod/RocksDBEngine/RocksDBVPackIndex.cpp
lib/Basics/VelocyPackHelper.cpp
lib/Basics/VelocyPackHelper.h
tests/Aql/EnumeratePathsExecutorTest.cpp
tests/Aql/ExecutionBlockImplTest.cpp
tests/Aql/QueryHelper.cpp
tests/Mocks/StorageEngineMock.cpp
tests/VPackDeserializer/test-types.h

Upgrade velocypack version to latest version, and make the changes in ArangoDB so that everything still compiles.

upgrade velocypack to latest version

---

CHANGELOG
arangod/IResearch/IResearchAnalyzerFeature.cpp
js/client/modules/@arangodb/testsuites/server_permissions.js

Backport for https://github.com/arangodb/arangodb/pull/17974.

Added backport for BTS-266

---

arangod/VocBase/vocbase.cpp

After a database is dropped, all states are resigned. This is relied upon; this PR makes sure no new states can be created after the database was marked as dropped.
See https://arangodb.atlassian.net/browse/CINFRA-588, and possibly https://arangodb.atlassian.net/browse/CINFRA-666, and https://arangodb.atlassian.net/browse/CINFRA-649 for more background.

[CINFRA-588] Don't create new states after the database was dropped

---

js/client/modules/@arangodb/testsuites/arangosh.js

we don't have any tests outputting our version - launch arangosh printing its version details.

launch it printing version information

---

arangod/Aql/ModificationOptions.cpp
arangod/Graph/Enumerators/OneSidedEnumerator.cpp
arangod/Graph/Enumerators/OneSidedEnumerator.h
arangod/Graph/Enumerators/OneSidedEnumeratorInterface.h
arangod/Graph/PathManagement/PathValidatorOptions.h

Small cleanup of code that claimed some deprecated functionality could be removed in current devel.

small internal code cleanup

---

CHANGELOG
arangod/VocBase/LogicalCollection.cpp
tests/js/common/shell/shell-collection-computed-values.js

Fixed issue #18053: Computed Values become null when Schema is modified

---

CHANGELOG
arangod/Cluster/ClusterInfo.cpp
tests/js/client/shell/shell-dump-integration.js
tests/js/client/shell/shell-restore-integration.js
tests/js/common/shell/shell-validation.js

Backport for https://github.com/arangodb/arangodb/pull/18014.
PR related to https://arangodb.atlassian.net/browse/BTS-1193.
Fix for schema update. When removing a field and then inserting a new field into the schema, previously, both old and new schema would be merged, meaning it would maintain the old field and add the new one.

BTS-1193 backport for 3.8

---

CHANGELOG
arangod/Cluster/ClusterInfo.cpp
tests/js/client/shell/shell-dump-integration.js
tests/js/client/shell/shell-restore-integration.js
tests/js/common/shell/shell-validation.js

Backport for https://github.com/arangodb/arangodb/pull/18014.
PR related to https://arangodb.atlassian.net/browse/BTS-1193.
Fix for schema update. When removing a field and then inserting a new field into the schema, previously, both old and new schema would be merged, meaning it would maintain the old field and add the new one.

BTS-1193 backport for 3.10

---

arangod/Agency/NodeLoadInspector.h
lib/Inspection/Access.h
lib/Inspection/VPackLoadInspector.h
tests/Basics/Inspection/NodeLoadTest.cpp
tests/Basics/Inspection/VPackLoadTest.cpp

Add support for VPackBuilder to NodeLoadInspector

---

README
README.md
utils/generateREADME.sh

- Oasis -> ArangoGraph
- Rework feature list
- Update logo including GitHub dark/light theme support
- Improvements to clarity

DOC-330 | Overhaul README

---

client-tools/Benchmark/BenchmarkThread.h
client-tools/Benchmark/testcases/CustomQueryTestCase.h
js/client/modules/@arangodb/testsuites/arangobench.js

Fix error handling for expected errors in arangobench test case.
test-only bugfix.

fix error handling in arangobench test case for expected errors

---

tests/Pregel/Actor/ActorTest.cpp

We will have a look at the test and fix it in another PR, but for now it will not make unrelated Jenkins runs fail.

[GORDO-1511] Disable unstable test

---

arangod/VocBase/LogicalCollection.cpp
arangod/VocBase/LogicalCollection.h

Add the information about the Collection group to LogicalCollection

Make the collectionGroupId available in the LogicalCollection

---

arangod/Agency/Supervision.cpp
arangod/Agency/Supervision.h

This code is a left over of the old replicated state supervision.

[CINFRA] Remove old supervision code

---

arangod/Replication2/StateMachines/Document/CollectionReader.cpp
arangod/Replication2/StateMachines/Document/CollectionReader.h
arangod/Replication2/StateMachines/Document/DocumentFollowerState.cpp
arangod/Replication2/StateMachines/Document/DocumentLeaderState.cpp
arangod/Replication2/StateMachines/Document/DocumentStateHandlersFactory.cpp
arangod/Replication2/StateMachines/Document/DocumentStateSnapshot.cpp
arangod/Replication2/StateMachines/Document/DocumentStateSnapshot.h
arangod/Replication2/StateMachines/Document/DocumentStateSnapshotHandler.cpp
arangod/Replication2/StateMachines/Document/DocumentStateSnapshotHandler.h
tests/Replication2/Mocks/DocumentStateMocks.cpp
tests/Replication2/Mocks/DocumentStateMocks.h
tests/Replication2/ReplicatedState/DocumentStateMachineTest.cpp

Prepare for transferring multiple shards during snapshot transfer.

[CINFRA-673] Multi shard snapshot transfer

---

.circleci/config.yml

Enable circle ci for pushes to `staging/replication-2.0`.

[CINFRA] CircleCI for staging/replication-2.0 push

---

.circleci/base_config.yml

Fix CircleCI config

---

js/client/modules/@arangodb/testutils/instance-manager.js
js/client/modules/@arangodb/testutils/instance.js

backport of https://github.com/arangodb/arangodb/pull/18083

[testing] compress agency dumps (#18083)

---

.circleci/base_config.yml
.circleci/config.yml

Run a reduced test set for CINFRA PRs.

[CINFRA] CircleCI reduced test set

---

.circleci/base_config.yml
scripts/build/README.md
scripts/build/arangodb-build.Dockerfile

OpenSSL has been updated to 1.1.1t, reflect this in Dockerfile

Update OpenSSL in Dockerfile

---

scripts/test/async_client.py
scripts/test/test_launch_controller.py

This allows us to have colored output in CircleCI.

Use PTY for test output redirect.

---

arangod/Agency/Supervision.cpp
arangod/Replication2/AgencyCollectionSpecification.h
arangod/Replication2/AgencyCollectionSpecificationInspectors.h
arangod/Replication2/Supervision/CollectionGroupSupervision.cpp
arangod/Replication2/Supervision/CollectionGroupSupervision.h

The previous fix just waited for the collection to appear in current. This version will also wait for all shards to show up.

Wait for shard to appear in current, not only collection.

---

.circleci/base_config.yml
scripts/test/testing_runner.py

Do not cleanup test output and store xml files as test artifacts

---

tests/js/client/shell/transaction/replication2_recovery/shell-transaction-replication2-recovery.js
tests/js/server/replication2/replication2-replicated-state-document-store.js

Until the Collection Group Supervision was implemented, we had to reply on a hack to synchronize the participants of a shard in `Plan/Collections` with the participants of the corresponding replicated log. This is now done in the supervision.

[CINFRA-513] Remove syncShardsWithLogs from tests

---

arangod/Aql/ClusterNodes.h
arangod/Aql/ModificationExecutorHelpers.cpp
arangod/Aql/ModificationExecutorHelpers.h
arangod/Aql/ModificationNodes.cpp
arangod/Aql/ModificationNodes.h
arangod/Aql/ModificationOptions.cpp
arangod/Aql/ModificationOptions.h
arangod/Aql/OptimizerUtils.h
arangod/Aql/RemoveModifier.cpp
arangod/Aql/UpdateReplaceModifier.cpp
arangod/Indexes/IndexIterator.h
lib/Basics/StaticStrings.cpp
lib/Basics/StaticStrings.h

Minor code cleanup.
Should not affect functionality/behavior at all.

small code cleanup (2)

---

js/common/modules/jsunity/jsunity.js
tests/js/server/replication/aql/replication-aql.js
tests/js/server/replication/random/replication-random.js

backport of https://github.com/arangodb/arangodb/pull/18205

QA-367: fix tearDownAll error reporting, lint (#18205)

---

arangod/Cluster/ServerState.h
arangod/RestHandler/RestDatabaseHandler.cpp
arangod/VocBase/Methods/Databases.cpp
js/apps/system/_admin/aardvark/APP/frontend/js/views/databaseView.js
lib/V8/v8-utils.cpp
tests/js/client/shell/shell-auto-refill-index-caches-on-modify-noncluster.js
tests/js/client/shell/shell-in-background-failures-noncluster.js
tests/test-definitions.txt

Backport of https://github.com/arangodb/arangodb/pull/18207
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/1218
This PR combines 2 independent improvements: Improve debuggability of database creation failures (in case of exceptions) and make a test more robust.

improve debuggability of errors upon database creation failure

---

CHANGELOG
arangod/Cluster/ClusterMethods.cpp
tests/js/common/shell/shell-document-babies.js
tests/js/common/shell/shell-keygen.js
tests/js/server/aql/aql-optimizer-undistribute-remove-regression.js

3.10 Backport of: https://github.com/arangodb/arangodb/pull/18214
Please see all details there.
**There is also an EE Companion:** 
* https://github.com/arangodb/enterprise/pull/1222

[GORDO-1554] Key generation ASSERT inspection

---

tests/test-definitions-rlog.txt

Replication2 gtests were run twice in CI previously.

[CINFRA] Run gtests only once

---

arangod/Pregel/Algos/ColorPropagation/ColorPropagation.cpp
arangod/Pregel/Algos/ColorPropagation/ColorPropagation.h
arangod/Pregel/Algos/ConnectedComponents/ConnectedComponents.cpp
arangod/Pregel/Algos/DMID/DMID.cpp
arangod/Pregel/Algos/EffectiveCloseness/EffectiveCloseness.cpp
arangod/Pregel/Algos/HITS/HITS.cpp
arangod/Pregel/Algos/HITSKleinberg/HITSKleinberg.cpp
arangod/Pregel/Algos/LabelPropagation/LabelPropagation.cpp
arangod/Pregel/Algos/LineRank/LineRank.h
arangod/Pregel/Algos/PageRank/PageRank.cpp
arangod/Pregel/Algos/ReadWrite/ReadWrite.cpp
arangod/Pregel/Algos/RecoveringPageRank/RecoveringPageRank.h
arangod/Pregel/Algos/SCC/SCC.cpp
arangod/Pregel/Algos/SLPA/SLPA.cpp
arangod/Pregel/Algos/SSSP/SSSP.cpp
arangod/Pregel/Algos/ShortestPath/ShortestPath.cpp
arangod/Pregel/Algos/WCC/WCC.cpp
arangod/Pregel/GraphFormat.h

Long standing TODO item: Remove dependency of GraphFormat on ApplicationServer.

Remove dependency on ApplicationServer from GraphFormat

---

arangod/Pregel/Actor/include/Actor/Actor.h
tests/IResearch/ExpressionFilterTest.cpp
tests/IResearch/GeoDistanceFilterTest.cpp
tests/IResearch/GeoFilterTest.cpp
utils/jslint-2.0.sh

Fix MSVC build issues + don't try to jslint files in UnitTests

---

arangod/Agency/AsyncAgencyComm.cpp
arangod/Cluster/AgencyCache.cpp
arangod/GeneralServer/RestHandlerFactory.cpp
arangod/Replication/common-defines.cpp
arangod/V8Server/V8DealerFeature.cpp
arangod/VocBase/Methods/Indexes.cpp
lib/ProgramOptions/Translator.cpp

simplify code

---

arangod/Pregel/AlgoRegistry.cpp
arangod/Pregel/AlgoRegistry.h
arangod/Pregel/Algorithm.h
arangod/Pregel/Algos/ColorPropagation/ColorPropagation.h
arangod/Pregel/Algos/ConnectedComponents/ConnectedComponents.cpp
arangod/Pregel/Algos/ConnectedComponents/ConnectedComponents.h
arangod/Pregel/Algos/DMID/DMID.h
arangod/Pregel/Algos/EffectiveCloseness/EffectiveCloseness.h
arangod/Pregel/Algos/HITS/HITS.h
arangod/Pregel/Algos/HITSKleinberg/HITSKleinberg.h
arangod/Pregel/Algos/LabelPropagation/LabelPropagation.cpp
arangod/Pregel/Algos/LabelPropagation/LabelPropagation.h
arangod/Pregel/Algos/LineRank/LineRank.cpp
arangod/Pregel/Algos/LineRank/LineRank.h
arangod/Pregel/Algos/PageRank/PageRank.cpp
arangod/Pregel/Algos/PageRank/PageRank.h
arangod/Pregel/Algos/ReadWrite/ReadWrite.cpp
arangod/Pregel/Algos/ReadWrite/ReadWrite.h
arangod/Pregel/Algos/RecoveringPageRank/RecoveringPageRank.h
arangod/Pregel/Algos/SCC/SCC.h
arangod/Pregel/Algos/SLPA/SLPA.h
arangod/Pregel/Algos/SSSP/SSSP.cpp
arangod/Pregel/Algos/SSSP/SSSP.h
arangod/Pregel/Algos/ShortestPath/ShortestPath.cpp
arangod/Pregel/Algos/ShortestPath/ShortestPath.h
arangod/Pregel/Algos/WCC/WCC.h
arangod/Pregel/Conductor/Conductor.cpp

remove applicationserver dependency out of Algorithm

[GORDO-1565] Remove ApplicationServer dependency out of Algorithm

---

lib/Inspection/include/Inspection/Access.h
lib/Inspection/include/Inspection/LoadInspectorBase.h
lib/Inspection/include/Inspection/SaveInspectorBase.h
lib/Inspection/include/Inspection/VPackLoadInspector.h
lib/Inspection/include/Inspection/detail/traits.h
tests/Inspection/JsonPrintTest.cpp
tests/Inspection/VPackLoadTest.cpp
tests/Inspection/VPackSaveTest.cpp
tests/Inspection/include/Inspection/InspectionTestHelper.h

Implement Inspection for std::set, std::unordered_set and the like

---

arangod/Pregel/Conductor/ExecutionStates/CreateWorkers.cpp
arangod/Pregel/Conductor/ExecutionStates/LoadingState.h
arangod/Pregel/Conductor/Handler.h
arangod/Pregel/Conductor/State.h
arangod/Pregel/PregelFeature.cpp
arangod/Pregel/REST/RestPregelHandler.cpp
arangod/Pregel/SpawnActor.h
arangod/Pregel/SpawnMessages.h
arangod/Pregel/Worker/Actor.h
arangod/Pregel/Worker/Handler.h
arangod/Pregel/Worker/State.h
tests/Pregel/ConductorStateTest.cpp

Adds vocbase and algorithm to worker actor state. Algorithm makes the worker generic over Vertex-, Edge- and Message-Type which are all dependent on the algorithm used.

[GORDO-1557] Create proper worker actor state

---

arangod/Pregel/Conductor/Conductor.cpp

Fixes a compile error in current devel.
No backports necessary.

[PREGEL] Fix using aggregator

---

arangod/Replication2/ReplicatedState/ReplicatedState.h
arangod/Replication2/ReplicatedState/ReplicatedState.tpp

Add mutex to guard the methods in the stream. There was a race between resign and release.

Add a mutex to guard the methods in the stream proxy.

---

arangod/RestServer/DatabaseFeature.cpp

Docs: Add 3.9.2 as version for `--database.io-heartbeat`

---

js/common/modules/@arangodb/testutils/document-state-helper.js
tests/js/server/replication2/replication2-replicated-state-document-store.js

JS linting currently fails in Jenkins.

[CINFRA] Fixing linting issues

---

tests/js/common/aql/aql-geo-distance-range.js

Speedup of the geo tests

---

js/client/modules/@arangodb/testsuites/endpoints.js
js/client/modules/@arangodb/testutils/instance.js

We still seem to have problems with the endpoints tests on ARM. 
- log startup before launching the instance
- properly skip test subsequent execution if we failed to launch once
- add more logging to the startup monitoring
- give even more time

[testing] work on endpoints test

---

js/client/modules/@arangodb/test-helper.js

better let arangosh itself run in deadlines, than being hard-killed from the outside

[testing] use execution deadlines in chaos tests to avoid hard killing

---

arangod/Replication2/StateMachines/Document/ActiveTransactionsQueue.cpp
tests/Replication2/ReplicatedState/StateManagerTest.cpp

[CINFRA] Fix a compile error

---

js/client/modules/@arangodb/testsuites/endpoints.js

debuggers may have been spawned in background, need to wait for them to exit.

[testing] wait for spawned debuggers to join

---

js/client/modules/@arangodb/testutils/result-processing.js

make sure xml filenames aren't to long.

[testing] shorten filenames, DRY

---

tests/test-definitions.txt

it seems chaos runs into overload; give it more resources beforehand

give chaos more resources

---

arangod/RestHandler/RestWalAccessHandler.cpp
arangod/RocksDBEngine/RocksDBWalAccess.cpp
arangod/StorageEngine/WalAccess.h

Add a debug message to an assertion, so in case it fails we will have more data to look at.

added debug message to assertion

---

arangod/Agency/CMakeLists.txt
arangod/Agency/CleanOutServer.cpp
arangod/Agency/CleanOutServer.h
arangod/Agency/Job.cpp
arangod/Agency/Job.h
arangod/Agency/JobContext.cpp
arangod/Agency/ReconfigureReplicatedLog.cpp
arangod/Agency/ReconfigureReplicatedLog.h
arangod/Agency/ResignLeadership.cpp
arangod/Agency/ResignLeadership.h
js/client/modules/@arangodb/testsuites/replication2.js
js/common/modules/@arangodb/testutils/replicated-logs-helper.js
js/common/modules/@arangodb/testutils/replicated-logs-predicates.js
tests/js/server/replication2/replication2-supervision-replicated-log-target-cluster.js

I added a supervision job that applies a modification to a replicated log.
Next steps are to update CleanOutServer and ResignLeadership Jobs to use this new job instead of move shard.

[CINFRA] Fix CleanOut and ResignLeadership

---

arangod/Pregel/Conductor/ExecutionStates/DoneState.h

Pregel: Added "Done" ExecutionState.

[GORDO-1575] Implemented 'done' conductor state

---

.circleci/base_config.yml
js/client/modules/@arangodb/testutils/result-processing.js
tests/js/common/shell/shell-pregel-components.js

* Do not use verbose SSH 
* Repair the upload of Junit XML results by stripping ANSI color codes from the output before putting it into `CDATA`, as they are not valid in XML output

Improve enterprise checkout a bit

---

arangod/Aql/QueryRegistry.cpp
arangod/Aql/RestAqlHandler.cpp
tests/js/common/shell/test-kill-queries.js

BTS-1148 has already been fixed as part of  #18274. This PR just adds some additional tests.

[BTS-1148] Add tests and failure points

---

.circleci/base_config.yml
.circleci/config.yml

`arangodbtests_replication2` was missing from the targets list.

[CINFRA] Fix CircleCI Job

---

CONTRIBUTING.md
js/client/modules/@arangodb/testutils/testing.js

we now can specify individual arguments for multiple consecutively launched testsuites.

add the possibility to launch testsuites with different arguments

---

utils/generateErrorfile.py

With the changes in #18409 a file that is generated on compile but committed to the repo was changed. This fixes the generator script.

Fix changing a generated file in the repo

---

CHANGELOG

*Description see enterprise counterpart*
Backport: https://github.com/arangodb/arangodb/pull/18422/

Bug-Fix 3.9: ES-1508 (EE only) (#18422)

---

client-tools/Shell/ProcessMonitoringFeature.cpp
client-tools/Shell/ProcessMonitoringFeature.h

Suggestions

---

client-tools/Shell/TelemetricsHandler.cpp
client-tools/Shell/TelemetricsHandler.h

Fix "unused member" compile warning on macOS

fix unused member in non-maintainer mode

---

js/common/modules/@arangodb/graph/pregel-test-helpers.js
tests/js/client/shell/shell-pregel-status-writer.js
tests/js/common/shell/shell-pregel-status-writer.js

Small follow-up PR which improves the readability of a pregel test suite by separating httponly test code into its own testsuite/testfile.

[GORDO-1595] Simplify Pregel JavaScript suite

---

CHANGELOG
etc/testing/arangosh.conf
scripts/test/site_config.py
scripts/unittest
scripts/unittest.ps1

Backport of https://github.com/arangodb/arangodb/pull/18348.

Change test path for config files from relative to testing (3.9)

---

js/client/modules/@arangodb/testsuites/rta_makedata.js

when RTA launches cluster tests, it will execute `wait_for_shards_in_sync.js` which is missing here.

testing: invoke check sync as well

---

CHANGELOG

Backport of https://github.com/arangodb/arangodb/pull/18427
Enterprise companion: https://github.com/arangodb/enterprise/pull/1239

Bug-Fix 3.9.10: ES-1508 (EE only)

---

js/client/modules/@arangodb/testutils/instance-manager.js

the monitoring may kick us during gathering the netstat info, handle it appropriately.

testing: one more place to work with the deadline handling.

---

js/client/modules/@arangodb/testutils/testrunner.js
tests/js/client/chaos/test-chaos-load-common.inc
tests/js/server/shell/shell-transactions-view-noncluster.js

add the infrastructure to revalidate the analyzers in the system

QA-365: check for tests cleaning up their analyzers

---

tests/js/client/shell/api/multi/async.js

Remove some redundant tests that added no extra value (or were simply duplicates).
Test-only bugfix

remove redundant tests

---

arangod/Replication2/AgencyCollectionSpecification.h
arangod/Replication2/StateMachines/Document/DocumentStateTransactionHandler.cpp
tests/Replication2/Mocks/DocumentStateMocks.cpp
tests/Replication2/Mocks/DocumentStateMocks.h
tests/Replication2/ReplicatedState/DocumentStateMachineTest.cpp

Fix some UBSan errors in the unit test suite.

[CINFRA] Fix gtest ubsan errors

---

arangod/Cluster/MaintenanceFeature.cpp
arangod/Cluster/MaintenanceFeature.h
tests/Maintenance/MaintenanceFeatureMock.h
tests/Maintenance/MaintenanceFeatureTest.cpp

Fix a small race in a test that caused sporadic jenkins failures.

Bug fix/fix maintenance test error

---

js/client/modules/@arangodb/testutils/testrunner.js

Fix a typo in a JavaScript function name (used only for testing)

fix a typo inside a JavaScript function name

---

CHANGELOG
js/apps/system/_admin/aardvark/APP/react/src/views/visgraphs/GraphHeader.tsx
js/apps/system/_admin/aardvark/APP/react/src/views/visgraphs/GraphNetwork.tsx
js/apps/system/_admin/aardvark/APP/react/src/views/visgraphs/SmartGraphEmptyState.tsx
js/apps/system/_admin/aardvark/APP/react/src/views/visgraphs/VisGraphData.types.ts

As SmartGraphs are not supported in the new Graph Viewer yet we display a message with a button to open the old Graph Viewer instead.

FE-200: Display SmartGraph info in Graph Viewer

---

arangod/Replication2/IScheduler.h
arangod/Replication2/ReplicatedLog/Components/FollowerCommitManager.cpp
arangod/Replication2/ReplicatedLog/Components/FollowerCommitManager.h
arangod/Replication2/ReplicatedLog/Components/LogFollower.cpp
arangod/Replication2/ReplicatedLog/Components/LogFollower.h
arangod/Replication2/ReplicatedLog/Components/StorageManager.cpp
arangod/Replication2/ReplicatedLog/Components/StorageManager.h
arangod/Replication2/ReplicatedLog/LogLeader.cpp
arangod/Replication2/ReplicatedLog/ReplicatedLog.cpp
tests/Replication2/Mocks/SchedulerMocks.h
tests/Replication2/ReplicatedLog/Components/FollowerCommitManagerTest.cpp
tests/Replication2/ReplicatedLog/Components/StorageManagerTest.cpp
tests/Replication2/ReplicatedLog/LogFollower/AppendEntriesTest.cpp
tests/Replication2/ReplicatedState/StateManagerTest.cpp

Use the scheduler to resolve promises in the storage manager. I added the same code to the FollowerCommitManager as well.

[CINFRA-722] use scheduler storage manager

---

arangod/VocBase/Properties/ClusteringConstantProperties.cpp
arangod/VocBase/Properties/UserInputCollectionProperties.cpp

Fix red test caused by logic merge conflict when reintegrating devel

---

README
README.md
js/apps/system/_admin/aardvark/APP/frontend/js/templates/navigationView.ejs
js/apps/system/_admin/aardvark/APP/frontend/js/templates/supportView.ejs
utils/generateREADME.sh

Fix the link for joining our Slack community space, remove broken status badge from README
https://arangodb.slack.com/archives/C9PPCJ4HF/p1680172554322059

Bug-fix/slack-community

---

arangod/Replication2/IScheduler.h
arangod/Replication2/ReplicatedLog/LogLeader.cpp
arangod/Replication2/ReplicatedLog/ReplicatedLogMetrics.h
arangod/Replication2/ReplicatedLog/TermIndexMapping.cpp
arangod/Replication2/ReplicatedState/ReplicatedState.tpp

Applied some equivalence transformation to the code to satisfy cppcheck.

[CINFRA] fix cppcheck warnings

---

tests/js/common/shell/shell-pregel-basics-example.js
tests/js/common/shell/shell-pregel-multicollection-edgecol.js
tests/js/common/shell/shell-pregel-random.js
tests/js/common/shell/shell-pregel-start-cluster.js

Remove some tests for code that was removed in previous PRs.

[GORDO-xxx] Speed up testing

---

arangod/Aql/QueryRegistry.cpp

Fix cppcheck issue in QueryRegistry

---

README
README.md
js/apps/system/_admin/aardvark/APP/frontend/js/templates/navigationView.ejs
js/apps/system/_admin/aardvark/APP/frontend/js/templates/supportView.ejs

Backport of https://github.com/arangodb/arangodb/pull/18510

Bug fix 3.9/slack community

---

README
README.md
js/apps/system/_admin/aardvark/APP/frontend/js/templates/navigationView.ejs
js/apps/system/_admin/aardvark/APP/frontend/js/templates/supportView.ejs

Bug fix 3.10/slack community

---

etc/testing/arangod-common.conf

Enable certain log topics for testing.

Enable debug logging for tests.

---

js/client/modules/@arangodb/testutils/instance-manager.js
js/client/modules/@arangodb/testutils/testrunner.js

It seems the code was there, but it wasn't actually exeuted

testing: need to actually invoke the code :/

---

CONTRIBUTING.md

add the documentation, upgrade RTA-makedata
- related RTA-makedata PR: https://github.com/arangodb/rta-makedata/pull/3

adjust RTA makedata docu.

---

tests/js/client/server_parameters/foxx-enable-true.js

testing: stabilize test by disabling deferred foxx startup

---

arangod/RestHandler/RestGraphHandler.cpp
arangod/RestHandler/RestGraphHandler.h
arangod/RocksDBEngine/Methods/RocksDBTrxBaseMethods.cpp
arangod/RocksDBEngine/RocksDBMetaCollection.cpp
arangod/RocksDBEngine/RocksDBRecoveryManager.cpp
arangod/RocksDBEngine/RocksDBVPackIndex.cpp
arangod/RocksDBEngine/RocksDBVPackIndex.h
arangod/StorageEngine/PhysicalCollection.cpp
arangod/Utils/CollectionNameResolver.cpp
utils/cppcheck.sh

fix more cppcheck errors

---

arangod/Utils/CollectionNameResolver.cpp

Devel part addressed as part of https://github.com/arangodb/arangodb/pull/18570
Fix potential undefined behavior in CollectionNameResolver

fix potential UB in CollectionNameResolver

---

arangod/Cluster/ClusterInfo.cpp
js/common/modules/@arangodb/testutils/replicated-logs-helper.js
js/common/modules/@arangodb/testutils/replicated-logs-predicates.js
lib/Rest/GeneralResponse.cpp
tests/js/client/restart/test-restart-replication2-database.js

Although the server has been restarted, it might not yet be ready. Recovery could still be in progress.

[CINFRA] Race in Restart Tests

---

arangod/Pregel/GraphStore/GraphStorer.cpp
arangod/Pregel/GraphStore/GraphStorer.h
arangod/Pregel/GraphStore/GraphStorerBase.h
arangod/Pregel/GraphStore/GraphVPackBuilderStorer.cpp
arangod/Pregel/GraphStore/GraphVPackBuilderStorer.h
arangod/Pregel/Worker/Handler.h
arangod/Pregel/Worker/Worker.cpp

This PR moves the responsibility for storing a `Magazine` into a storer, as this seems to be the cleaner interface.
We then store concurrently per shard in the `Magazine`.

[GORDO-1599] Re-parallelise graph storing

---

js/client/modules/@arangodb/testsuites/server_permissions.js

this testsuite would delete its datasets while failures occured. fix this.

testing: make sure to disable test cleanup after failure

---

arangod/RocksDBEngine/RocksDBEngine.cpp

[CINFRA-736] Fix memory leaks in RocksDBEngine

---

tests/js/client/server_parameters/foxx-enable-true.js

backport of https://github.com/arangodb/arangodb/pull/18568

testing: stabilize test by disabling deferred foxx startup (#18568)

---

CHANGELOG

Re APM-407, be more precise in CHANGELOG

correct a CHANGELOG entry

---

tests/js/server/replication2/replication2-replicated-state-document-store.js

This PR fixes the `testSnapshotDiscardedOnRebootIdChange` replication2 test.
When the leader gets a `/snapshot/start` request from a follower whose reboot ID has changed in the meantime, it will initiate a cleanup procedure for the to-be-created snapshot.
However, the cleanup procedure is enqueued on the scheduler, which means that we might end up with leader returning an error, but there's also the possibility of a successful response (if the snapshot was cleaned up instantly). In that case, we got to try and fetch the snapshot status later, in order to check that it has been cleared.

[CINFRA-739] Flaky JS test

---

tests/js/client/server_parameters/www-authenticate.js

improve error messages for debugeability

testing: better test errors

---

arangod/IResearch/IResearchFilterFactoryCommon.h

Remove a global namespace declaration from a header file.

remove global namespace declaration

---

utils/eslint.sh
utils/jslint.sh

use jslint on rta-makedata as well.

testing: use jslint in RTA-makedata

---

tests/js/client/server_parameters/foxx-enable-true.js

don't lean on internet download for this test.
replace https://github.com/arangodb/arangodb/pull/18640 which had more errnous commits

use local foxx zip to reduce test flakyness

---

tests/Cache/PlainCache.cpp

Instead of just showing `false is not true`, please show what the _wrong_ value was. Maybe its just of by a little.

Use proper gtest macros for more visibility.

---

tests/js/client/server_parameters/foxx-enable-true.js

backport of https://github.com/arangodb/arangodb/pull/18643/files

use local foxx zip to reduce test flakyness (#18643)

---

.circleci/base_config.yml
js/client/modules/@arangodb/testsuites/chaos.js
js/client/modules/@arangodb/testutils/result-processing.js
js/client/modules/@arangodb/testutils/testing.js
js/client/modules/@arangodb/testutils/testrunner.js
scripts/test/site_config.py
scripts/test/test_config.py

add a separate parameter for the xml report files

switch output directory for xml files

---

arangod/Pregel/GraphStore/GraphStorer.cpp
arangod/Pregel/GraphStore/GraphStorer.h
arangod/Pregel/GraphStore/Magazine.h
arangod/Pregel/Worker/Handler.h
arangod/Pregel/Worker/Worker.cpp

Re-respect the parallelism parameter while storing results of a Pregel computation  back into the database.

[GORDO-1621] Respect parallelism while storing results

---

arangod/Pregel/DatabaseTypes.h
arangod/Pregel/GraphStore/GraphLoader.cpp
arangod/Pregel/GraphStore/GraphLoader.h
arangod/Pregel/GraphStore/LoadableVertexShard.h

Re-respect the parallelism parameter when loading a graph from the database into the Pregel system.

[GORDO-1620] Respect parallelism for graph loading

---

Documentation/DocuBlocks/Rest/Collections/1_structs.md
Documentation/DocuBlocks/Rest/Collections/post_api_collection.md
Documentation/DocuBlocks/Rest/Collections/put_api_collection_collection_loadIndexesIntoMemory.md
Documentation/DocuBlocks/Rest/Collections/put_api_collection_collection_properties.md
Documentation/DocuBlocks/Rest/Databases/post_api_database.md
Documentation/DocuBlocks/Rest/Graphs/1_structs.md
Documentation/DocuBlocks/Rest/Graphs/post_api_gharial.md
Documentation/DocuBlocks/Rest/Indexes/post_api_index_inverted.md
Documentation/DocuBlocks/Rest/Replication/get_api_replication_dump.md
Documentation/DocuBlocks/Rest/Replication/get_api_replication_logger_follow.md
Documentation/DocuBlocks/Rest/Replication/get_api_wal_access_tail.md
Documentation/DocuBlocks/Rest/Views/post_api_view_arangosearch.md
Documentation/Metrics/arangodb_shards_not_replicated.yaml
Documentation/Metrics/arangodb_shards_out_of_sync.yaml
arangod/IResearch/IResearchFeature.cpp

Backport of https://github.com/arangodb/arangodb/pull/18714

Documentation 3.10/cache only leaders

---

arangod/RestServer/EnvironmentFeature.cpp

In case /proc/cpu/alignment does not exist, there is no need to complain about it.
Inspired by the following log output from an ARM build:
```
2023-04-19T21:12:15Z [1] WARNING [b8a20] {memory} unable to detect CPU alignment settings. could not process file '/proc/cpu/alignment'. this may cause arangod to abort with SIGBUS. it may be necessary to set the value in '/proc/cpu/alignment' to 2
```
Now, if /proc/cpu/alignment is not present, we don't bother to log this warning.

avoid startup warnings on ARM

---

arangod/IResearch/GeoAnalyzer.cpp
arangod/RestServer/EnvironmentFeature.cpp
arangod/Utils/UrlHelper.cpp
lib/VPackDeserializer/parameter-list.h

Fix issues reported by cppcheck. The fixes were already done in devel. This PR simply backports them.

fix issues reported by cppcheck

---

js/client/modules/@arangodb/testsuites/chaos.js
js/client/modules/@arangodb/testutils/result-processing.js
js/client/modules/@arangodb/testutils/testing.js
js/client/modules/@arangodb/testutils/testrunner.js
scripts/test/site_config.py

backports of https://github.com/arangodb/arangodb/pull/18675, https://github.com/arangodb/arangodb/pull/18647 , https://github.com/arangodb/arangodb/pull/18359

backport xml fixes

---

js/client/modules/@arangodb/testsuites/gtest.js
js/client/modules/@arangodb/testutils/result-processing.js

backport of https://github.com/arangodb/arangodb/pull/18725

Bug fix 3.10/proper namespacing for gtests

---

arangod/Transaction/Manager.h
tests/js/client/chaos/test-chaos-load-common.inc

Changed hash function to improve transaction distribution into buckets. That should reduce contention.
Anyway as timeout is still possible on transaction action -  changed chaos test client code to be prepared,
Improved logging of ArangoSearch views validation output in case of failure

Bug fix/make chaos resilient for commit timeout

---

arangod/RestServer/EnvironmentFeature.cpp

even though these exceptions are caught and handled, they are in the way when debugging _real_ exceptions. avoid unnecessary exceptions where possible, so that one can concentrate on the actually interesting exceptions.

don't throw exceptions on the normal startup path

---

arangod/Pregel/Conductor/ExecutionStates/CanceledState.cpp
arangod/Pregel/Conductor/ExecutionStates/ComputingState.cpp
arangod/Pregel/Conductor/ExecutionStates/ComputingState.h
arangod/Pregel/Conductor/ExecutionStates/CreateWorkersState.cpp
arangod/Pregel/Conductor/ExecutionStates/LoadingState.cpp
arangod/Pregel/Conductor/Handler.h
arangod/Pregel/Conductor/Messages.h
arangod/Pregel/Conductor/State.h
arangod/Pregel/GraphStore/GraphVPackBuilderStorer.h
arangod/Pregel/PregelFeature.cpp
arangod/Pregel/PregelFeature.h
arangod/Pregel/REST/RestControlPregelHandler.cpp
arangod/Pregel/REST/RestPregelHandler.cpp
arangod/Pregel/ResultActor.h
arangod/Pregel/SenderMessage.h
arangod/Pregel/Statistics.h
arangod/Pregel/StatusActor.h
arangod/Pregel/StatusMessages.h
arangod/Pregel/Worker/Handler.h
arangod/Pregel/Worker/State.h
arangod/Pregel/Worker/VertexProcessor.cpp
arangod/Pregel/Worker/VertexProcessor.h
arangod/Pregel/Worker/Worker.cpp
arangod/V8Server/v8-pregel.cpp
js/common/modules/@arangodb/graph/pregel-test-helpers.js
tests/js/client/load-balancing/load-balancing-pregel-auth-cluster.js
tests/js/client/load-balancing/load-balancing-pregel-noauth-cluster.js
tests/js/common/shell/shell-pregel-basics-example.js
tests/js/common/shell/shell-pregel-random.js
tests/js/common/shell/shell-pregel-start-cluster.js

Fix more actor stuff, have a look at the commits to see what was done.

[PREGEL] Fix even more actor stuff

---

client-tools/Shell/V8ShellFeature.cpp
js/client/modules/@arangodb/testsuites/recovery_cluster.js
tests/js/server/recovery/view-arangosearch-link-populate-crash-after-release.js
tests/js/server/recovery/view-arangosearch-link-populate-no-callbacks.js
tests/js/server/recovery/view-arangosearch-link-populate-no-release.js
tests/js/server/recovery/view-arangosearch-link-populate-no-sync.js
tests/js/server/recovery/view-arangosearch-link-populate-transaction-multiple-batches-no-flushthread.js
tests/js/server/recovery/view-arangosearch-link-populate-transaction-no-flushthread.js
tests/js/server/recovery/view-arangosearch-link-populate-transaction-single-batch-no-flushthread.js
tests/js/server/recovery/view-arangosearch-link-populate-transaction.js
tests/js/server/recovery/view-search-alias-populate-crash-after-release.js
tests/js/server/recovery/view-search-alias-populate-no-callbacks.js
tests/js/server/recovery/view-search-alias-populate-no-release.js
tests/js/server/recovery/view-search-alias-populate-no-sync.js
tests/js/server/recovery/view-search-alias-populate-transaction-multiple-batches-no-flushthread.js
tests/js/server/recovery/view-search-alias-populate-transaction-no-flushthread.js
tests/js/server/recovery/view-search-alias-populate-transaction-single-batch-no-flushthread.js
tests/js/server/recovery/view-search-alias-populate-transaction.js

backport of https://github.com/arangodb/arangodb/pull/18778

Bug fix/handle setup test errors (#18778)

---

js/common/modules/@arangodb/graph/pregel-test-helpers.js

Fix for nightly failure https://jenkins01.arangodb.biz/job/arangodb-ANY-linux-matrix.x86-64/EDITION=enterprise,STORAGE_ENGINE=rocksdb,TEST_SUITE=cluster,limit=linux&&test&&x86-64/4315/artifact/testfailures.txt.

Increase test timeout for pregel garbage collection

---

CHANGELOG
arangod/Cluster/SynchronizeShard.cpp
arangod/Cluster/SynchronizeShard.h
arangod/Replication/DatabaseInitialSyncer.cpp
arangod/Replication/DatabaseInitialSyncer.h
arangod/Replication/DatabaseTailingSyncer.cpp
arangod/Replication/DatabaseTailingSyncer.h
arangod/Replication/TailingSyncer.h
arangod/Replication/utilities.cpp
arangod/RestHandler/RestReplicationHandler.cpp
arangod/Transaction/Methods.cpp
tests/js/client/shell/shell-replication-drop-follower-shard.js

Support upgrading from 3.9.2 to 3.10 in case a very specific issue is triggered.

add support for a special case of 3.9.2 upgrades

---

client-tools/Shell/V8ClientConnection.cpp

backport of https://github.com/arangodb/arangodb/pull/18863

BTS-1347: add debug logging to arangosh connect code

---

arangosh/Shell/V8ClientConnection.cpp

backport of https://github.com/arangodb/arangodb/pull/18863

Bug fix 3.9/add debug logging to arangosh connect code

---

arangod/Pregel/Worker/VertexProcessor.h

[PREGEL] Fix performance regression (3.11 backport)

---

js/client/modules/@arangodb/testutils/crash-utils.js
js/client/modules/@arangodb/testutils/instance.js

backport of https://github.com/arangodb/arangodb/pull/18885

we need to know the PID in order to calculate the filename

---

arangod/Pregel/PregelFeature.cpp
arangod/Pregel/PregelFeature.h

[BTS-1392] "Fix" lock order inversion TSAN failure

---

arangod/Pregel/StatusActor.h
arangod/Pregel/StatusMessages.h

[PREGEL] pregel with actors fixes

---

arangod/Pregel/PregelFeature.cpp
arangod/Pregel/PregelFeature.h

[BTS-1392] [3.11] "Fix" lock order inversion 

---

CHANGELOG
arangod/Aql/Collection.cpp
arangod/Aql/ExecutionPlan.cpp
tests/js/server/aql/aql-traversal-restrict-collections.js

Follow-up to https://arangodb.atlassian.net/browse/ES-1566
add more tests and better error handling when specifying invalid values for `edgeCollections` and `vertexCollections` options of a traversal

add more tests and better error handling

---

CHANGELOG
arangod/IResearch/GeoFilter.cpp
tests/js/server/aql/aql-geo.inc

Backport of https://github.com/arangodb/arangodb/pull/18972

Bug fix 3.11/BTS-1398 fix range geo filter

---

CHANGELOG
arangod/IResearch/GeoFilter.cpp
tests/js/server/aql/aql-geo.inc

Backport https://github.com/arangodb/arangodb/pull/18972

Bug fix 3.10/BTS-1398 fix range geo filter

---

arangod/Pregel/IncomingCache.cpp
arangod/Pregel/IncomingCache.h
arangod/Pregel/OutgoingCache.cpp
arangod/Pregel/OutgoingCache.h
arangod/Pregel/Worker/State.h
arangod/Pregel/Worker/VertexProcessor.cpp
arangod/Pregel/Worker/VertexProcessor.h
arangod/Pregel/Worker/Worker.cpp
arangod/Pregel/Worker/WorkerConfig.h

[GORDO-1642] [3.11] Try and address some obvious timewasters

---

arangod/IResearch/GeoFilter.cpp

Remove unnecessary assign

---

client-tools/Shell/ShellFeature.cpp
client-tools/Shell/ShellFeature.h
client-tools/Shell/TelemetricsHandler.cpp
client-tools/Shell/TelemetricsHandler.h

Fix TSan race on arangosh shutdown

fix TSan race

---

CHANGELOG

fix duplicate changelog entry, and move it to correct version

fix duplicate changelog entry, and move it to correct version

---

CHANGELOG
lib/Basics/FileUtils.cpp
lib/Basics/error.cpp
lib/Basics/error.h
lib/Basics/win-utils.cpp

Backport of https://github.com/arangodb/arangodb/pull/18958
*  Improved error reporting for system calls on Windows and fixed a
Windows-specific issue of the IOHeartbeatThread.

Add the functionality for truncating files on Windows

---

CHANGELOG
js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js

bug-fix-3.10/FE-266-use-fromGeoJson

---

js/client/modules/@arangodb/testsuites/aql.js

we would not create testresults according to our internal data structures. fix that.

fix result processing of the v8-shell suite

---

arangod/Aql/QueryRegistry.cpp

[BTS-1400] [3.11] Use correct lane

---

scripts/test/testing_runner.py

Forward port https://github.com/arangodb/oskar/pull/517 to circle ci

testing: as in oskar show stacktraces

---

arangod/Network/NetworkFeature.cpp

Backport of https://github.com/arangodb/arangodb/pull/19032

[3.9] Remove duplicate division.

---

arangod/Cache/PlainBucket.h
arangod/Cache/TransactionalBucket.h
lib/Basics/fasthash.cpp
lib/Basics/operating-system.h
lib/Rest/HttpRequest.cpp
lib/Rest/Version.cpp

https://github.com/arangodb/arangodb/pull/19096
https://github.com/arangodb/arangodb/pull/19096#issuecomment-1562698215
https://godbolt.org/z/cbv8xKrfe (same asm as without memcpy)

remove outdated defines from the codebase 2

---

arangod/Network/Methods.cpp
arangod/Network/NetworkFeature.cpp
arangod/Network/NetworkFeature.h

Previously if a request decided to be retried, it would post that on the scheduler but keep the work item for itself. During shutdown, the work item wouldn't be cancelled. Now the NetworkFeature keeps track of those requests.
https://arangodb.atlassian.net/browse/BTS-1407

[BTS-1407] Cancel Requests in retry

---

arangod/Network/NetworkFeature.cpp

Backport of https://github.com/arangodb/arangodb/pull/19032.

[3.11] Remove duplicate divison.

---

arangod/Network/NetworkFeature.cpp

Previously during shutdown there was the following race: 
1. the resume lambda was posted on the scheduler and executed.
2. The lambda was able to obtain the `self` pointer.
3. The shutdown code was executed and called `_retryRequests.clear()`
4. The lambda attempted to erase a missing key. Then resumed the already cancelled request.

Fixing a shutdown issue.

---

js/common/modules/@arangodb/aql/explainer.js
tests/js/client/shell/shell-debug-dump.js

Improve debug dumps
* make tests not print explain output
* make debug dumps deserialize database correctly
* make debug dumps deserialize version number correctly

improve debug dumps

---

CHANGELOG
arangod/Aql/Expression.cpp
arangod/Aql/OptimizerRules.cpp
tests/js/server/aql/aql-remove-regression.js

Backport of https://github.com/arangodb/arangodb/pull/19165
Fix https://arangodb.atlassian.net/browse/BTS-1435

fixed BTS-1435

---

.circleci/base_config.yml
scripts/build/README.md
scripts/build/arangodb-build.Dockerfile
scripts/build/build-image.sh
scripts/build/install-openssl.sh

Update OpenSSL in build container

---

.circleci/base_config.yml
scripts/build/README.md
scripts/build/arangodb-build.Dockerfile
scripts/build/build-image.sh

[3.11] Update OpenSSL in build container

---

tests/js/server/replication2/replication2-soft-write-concern-replicated-log-cluster.js

This PR addresses the following issues:
- there is a comment saying the test is disable, when its not, so I removed the comment
- the test is not using the appropriate helper functions, which we kept updating along the way

Adjust soft-write-concern tests

---

arangod/Agency/Agent.cpp
arangod/Agency/State.cpp
arangod/Cluster/ClusterMethods.cpp
arangod/Metrics/ClusterMetricsFeature.cpp
arangod/Network/Methods.cpp
arangod/Replication/ReplicationApplier.cpp
arangod/Replication2/ReplicatedLog/LogLeader.cpp
arangod/Replication2/ReplicatedState/ReplicatedState.tpp

Fix issues reported by cppcheck.
Mostly suppression for issue in cppcheck  https://trac.cppcheck.net/ticket/11751
And possible out-of-bounds access in  arangod\Agency\State.cpp

[BTS-1452] fix cppcheck issues

---

CHANGELOG
arangod/Aql/AqlItemBlock.cpp
arangod/Aql/AsyncExecutor.cpp
arangod/Aql/AsyncExecutor.h
arangod/Aql/ExecutionEngine.cpp
arangod/Aql/ExecutionEngine.h
arangod/Aql/ExecutionNodeId.h
arangod/Aql/ExecutionState.cpp
arangod/Aql/ExecutionState.h
arangod/Aql/Query.cpp
arangod/Aql/Query.h
arangod/Aql/SharedQueryState.cpp
arangod/Aql/SharedQueryState.h
lib/Assertions/AssertionConditionalLogger.h
lib/Basics/Identifier.h
tests/Aql/AqlExecutorTestCase.cpp
tests/Aql/AqlExecutorTestCase.h
tests/Aql/AsyncExecutorTest.cpp
tests/Aql/ExecutorTestHelper.cpp
tests/Aql/ExecutorTestHelper.h
tests/Aql/WaitingExecutionBlockMock.cpp
tests/Aql/WaitingExecutionBlockMock.h
tests/CMakeLists.txt
tests/IResearch/IResearchViewNodeTest.cpp
tests/Mocks/FakeScheduler.cpp
tests/Mocks/FakeScheduler.h
tests/Mocks/MockQuery.h
tests/Mocks/Servers.cpp
tests/Mocks/Servers.h

Backport of https://github.com/arangodb/arangodb/pull/18729; see there for details.

[BTS-1325] [3.11] Don't go to sleep forever

---

CHANGELOG
arangod/Aql/AqlItemBlock.cpp
arangod/Aql/AsyncExecutor.cpp
arangod/Aql/AsyncExecutor.h
arangod/Aql/ExecutionEngine.cpp
arangod/Aql/ExecutionEngine.h
arangod/Aql/ExecutionNodeId.h
arangod/Aql/ExecutionState.cpp
arangod/Aql/ExecutionState.h
arangod/Aql/Query.cpp
arangod/Aql/Query.h
arangod/Aql/SharedQueryState.cpp
arangod/Aql/SharedQueryState.h
lib/Basics/Identifier.h
tests/Aql/AqlExecutorTestCase.cpp
tests/Aql/AqlExecutorTestCase.h
tests/Aql/AsyncExecutorTest.cpp
tests/Aql/ExecutorTestHelper.cpp
tests/Aql/ExecutorTestHelper.h
tests/Aql/WaitingExecutionBlockMock.cpp
tests/Aql/WaitingExecutionBlockMock.h
tests/CMakeLists.txt
tests/Mocks/FakeScheduler.cpp
tests/Mocks/FakeScheduler.h
tests/Mocks/MockQuery.h
tests/Mocks/Servers.cpp
tests/Mocks/Servers.h

Backport of https://github.com/arangodb/arangodb/pull/18729; see there for details.

[BTS-1325] [3.10] Don't go to sleep forever

---

CHANGELOG
arangod/IResearch/IResearchDataStore.cpp
arangod/IResearch/IResearchDataStore.h
arangod/IResearch/IResearchFeature.cpp
arangod/IResearch/IResearchFeature.h
arangod/IResearch/IResearchPrimaryKeyFilter.cpp
arangod/IResearch/IResearchPrimaryKeyFilter.h
arangod/IResearch/IResearchRocksDBInvertedIndex.h
arangod/IResearch/IResearchRocksDBLink.h
arangod/IResearch/IResearchRocksDBRecoveryHelper.cpp
arangod/IResearch/IResearchRocksDBRecoveryHelper.h
arangod/IResearch/Search.cpp
arangod/IResearch/Search.h
arangod/RocksDBEngine/RocksDBRecoveryHelper.h
tests/IResearch/IResearchInvertedIndexIteratorTest.cpp
tests/IResearch/IResearchLinkTest.cpp
tests/IResearch/IResearchViewTest.cpp
tests/Mocks/IResearchInvertedIndexMock.cpp
tests/Mocks/IResearchLinkMock.cpp
tests/Mocks/IResearchLinkMock.h

Backport this https://github.com/arangodb/arangodb/pull/19173
And update iresearch to corresponding 1.3 branch (it contains other bug-fixes)

Search backports 3.11

---

arangod/IResearch/IResearchFeature.h

Supress cppcheck error.

---

client-tools/Dump/DumpFeature.cpp

CI found a data race that I couldn't reproduce locally.

Data Race in ArangoDump

---

Documentation/DocuBlocks/Rest/Indexes/post_api_index_geo.md

DOC-474 | Add `legacyPolygons` option to geo index DocuBlock

---

arangod/IResearch/IResearchFeature.h

Backport of cppcheck fixes from https://github.com/arangodb/arangodb/pull/19225

Supress cppcheck error. (#19225)

---

tests/js/server/replication2/replication2-soft-write-concern-replicated-log-cluster.js

Try to stabilize a possibly flaky test.

Try to stabilize a possibly flaky test

---

Documentation/DocuBlocks/Rest/Views/delete_api_view.md
Documentation/DocuBlocks/Rest/Views/get_api_view_name.md
Documentation/DocuBlocks/Rest/Views/get_api_view_properties.md
Documentation/DocuBlocks/Rest/Views/get_api_views.md
Documentation/DocuBlocks/Rest/Views/patch_api_view_properties_arangosearch.md
Documentation/DocuBlocks/Rest/Views/post_api_view_arangosearch.md
Documentation/DocuBlocks/Rest/Views/put_api_view_properties_arangosearch.md
Documentation/DocuBlocks/Rest/Views/put_api_view_rename.md

DOC-398 | DOC-477 | Improve View examples

---

lib/Basics/TimeString.h

Backport of #19149. 
A slightly more general, albeit risky, fix for the problem shown in https://github.com/arangodb/arangodb/pull/19138: rewrite timepointToString and stringToTimepoint to use the date.h C++ library instead of subtly incompatible C functions.

[3.11] Simplify and fix timepointToString and stringToTimepoint

---

tests/IResearch/IResearchLinkTest.cpp

Fix unstable test: if consolidation enabled we could write more columns than expected in the test

Fix unstable test

---

CHANGELOG
arangod/Aql/OptimizerRule.h
arangod/Aql/OptimizerRulesFeature.cpp
arangod/Aql/OptimizerRulesFeature.h
arangod/RestHandler/RestQueryHandler.cpp
arangod/RocksDBEngine/RocksDBOptimizerRules.cpp

Backport of https://github.com/arangodb/arangodb/pull/19246

DOC-347 | DOC-460 | Add `description` field to optimizer rules & add missing

---

lib/Basics/TimeString.h

Backport of https://github.com/arangodb/arangodb/pull/19149.
A slightly more general, albeit risky, fix for the problem shown in https://github.com/arangodb/arangodb/pull/19138: rewrite timepointToString and stringToTimepoint to use the date.h C++ library instead of subtly incompatible C functions.

[3.10] Simplify and fix timepointToString and stringToTimepoint

---

client-tools/Dump/DumpFeature.cpp

Fix data race.

---

Documentation/DocuBlocks/Rest/Documents/patch_api_document_collection.md
Documentation/DocuBlocks/Rest/Documents/patch_api_document_collection_key.md
Documentation/DocuBlocks/Rest/Documents/post_api_document_collection.md
Documentation/DocuBlocks/Rest/Documents/post_api_document_collection_multiple.md
Documentation/DocuBlocks/Rest/Graphs/patch_api_gharial_graph_edge_collection_edge.md
Documentation/DocuBlocks/Rest/Graphs/patch_api_gharial_graph_vertex_collection_vertex.md
Documentation/DocuBlocks/Rest/Graphs/put_api_gharial_graph_edge_collection_edge.md
Documentation/DocuBlocks/Rest/Graphs/put_api_gharial_graph_vertex_collection_vertex.md

https://github.com/arangodb/arangodb/issues/19017
Backports:
- 3.11: https://github.com/arangodb/arangodb/pull/19297
- 3.10: https://github.com/arangodb/arangodb/pull/19298
Docs: https://github.com/arangodb/docs/pull/1418

Docs: `keepNull: false` does not remove attributes in arrays

---

tests/js/server/replication2/replication2-replicated-state-document-store.js

The _testSnapshotDiscardedOnRebootIdChange_ does the following:
1. Start a snapshot for one of the replication2 followers
2. Stop the follower
3. Expect the snapshot to have been canceled
Step (3) depends on the follower's rebootId to be increased as a consequence of step (2). However, if the test runs fast enough, there's no guarantee of a rebootID change between (2) and (3).
This PR moves a misplaced `waitFor` right after the follower is stopped.

[CINFRA] Waiting for rebootId to change

---

arangod/Aql/Condition.cpp
arangod/Aql/Condition.h
arangod/Aql/ConditionFinder.cpp
arangod/Aql/ConditionFinder.h
arangod/Aql/IResearchViewOptimizerRules.cpp
arangod/Aql/OptimizerUtils.cpp
arangod/IResearch/IResearchFilterFactory.cpp
tests/js/common/aql/aql-arangosearch-inverted-index-optimization.js

Backport of https://github.com/arangodb/arangodb/pull/19292

Fixed BTS-1495 Inverted index cause incorrect plan optimization 3.11

---

tests/js/server/replication2/replication2-supervision-replicated-log-target-cluster.js

This is a test-only fix targeting `testChangeLeaderToNewFollower`, which seems to be flaky.
The test replaces the leader of a replicated log with a new participant.
Previously, there was a specific order in which the supervision actions where expected to occur:
1) Remove the old leader
```
'UpdateParticipantFlagsAction',  // remove force of leader (previous old follower)
'UpdateParticipantFlagsAction',  // disallow old leader from quorum
'RemoveParticipantFromPlanAction',  // remove old leader
```
2) Prepare the new server for taking over leadership
```
'UpdateParticipantFlagsAction',  // allow new participant as a leader
'UpdateParticipantFlagsAction',  // force new participant
```
Actually, (2) may occur before (1), without affecting the correctness of the system. I have adapted so this …

[CINFRA-791] Fix supervision flaky test

---

.circleci/base_config.yml

Use CircleCI context for sccache config

---

arangod/Aql/Condition.cpp
arangod/Aql/Condition.h
arangod/Aql/ConditionFinder.cpp
arangod/Aql/ConditionFinder.h
arangod/Aql/IResearchViewOptimizerRules.cpp
arangod/Aql/OptimizerUtils.cpp
arangod/IResearch/IResearchFilterFactory.cpp
tests/js/common/aql/aql-arangosearch-inverted-index-optimization.js

https://github.com/arangodb/arangodb/pull/19292

Fixed BTS-1495 Inverted index cause incorrect plan optimization 3.10

---

CHANGELOG
arangod/RocksDBEngine/RocksDBMetaCollection.cpp
arangod/Transaction/Manager.h
lib/Basics/ReadWriteLock.cpp
lib/Basics/ReadWriteLock.h
tests/Basics/ReadWriteLockTest.cpp

*Optimise runtime lock performance*

Optimise runtime lock performance [3.10]

---

tests/js/client/shell/api/multi/document-read.js

Original ticket: https://github.com/arangodb/arangodb/pull/19364
Added a regression test only. 
Bug-itself is fixed in this branch already, see: https://github.com/arangodb/arangodb/pull/19059

[OASIS-25344][DEVEL] API inconsistency regression test 

---

CHANGELOG
arangod/Cluster/ClusterMethods.cpp
tests/js/client/shell/api/document-read.js

Identical Backport of: https://github.com/arangodb/arangodb/pull/19364
Please read all details there.

[OASIS-25344][3.9] Fix document API inconsistency

---

client-tools/Backup/arangobackup.cpp
client-tools/Import/SenderThread.cpp
client-tools/Utils/ManagedDirectory.cpp

As title: fix small issues in `client-tools`. These issues were fixed in devel already, but weren't backported before.

fix small issues in client-tools

---

arangod/RestHandler/RestVocbaseBaseHandler.cpp

Small code simplifications, which should not affect functionality in any way.

small code simplifications

---

CHANGELOG
arangod/GeneralServer/H2CommTask.cpp
arangod/GeneralServer/HttpCommTask.cpp
arangod/RestHandler/RestDumpHandler.cpp
client-tools/Dump/DumpFeature.cpp
lib/Rest/HttpResponse.h
lib/SimpleHttpClient/SimpleHttpClient.cpp
tests/js/client/server_permissions/test-foxx-service-access-denied.js

Forward port of https://github.com/arangodb/arangodb/pull/19363

Bug fix/read write connect error retry

---

arangod/Replication2/ReplicatedLog/Components/StorageManager.cpp

This PR just adds error messages to some exceptions, to aid with debugging.

[CINFRA] Adding error messages

---

js/client/modules/@arangodb/testsuites/resilience.js
js/client/modules/@arangodb/testutils/instance-manager.js
js/client/modules/@arangodb/testutils/instance.js
js/client/modules/@arangodb/testutils/testrunner.js
tests/js/client/active-failover/basic.js
tests/js/client/active-failover/disconnected-leader-nonwindows.js
tests/js/client/active-failover/readonly.js

The active_failover tests would run without monitoring. 
This PR does all thats neccessary to work with the instance manager to fix this.

Bug fix/fix active failover tests

---

tests/test-definitions.txt

we were dumping for wisdom, but we know now and fixed it.

testing: don't sniff anymore

---

js/client/modules/@arangodb/testsuites/resilience.js
js/client/modules/@arangodb/testutils/instance-manager.js
js/client/modules/@arangodb/testutils/instance.js
js/client/modules/@arangodb/testutils/testrunner.js
tests/js/client/active-failover/basic.js
tests/js/client/active-failover/disconnected-leader-nonwindows.js
tests/js/client/active-failover/readonly.js

backport of https://github.com/arangodb/arangodb/pull/19393

Bug fix 3.11/fix active failover tests

---

js/client/modules/@arangodb/testutils/instance-manager.js
js/client/modules/@arangodb/testutils/instance.js
js/client/modules/@arangodb/testutils/testing.js

backport of https://github.com/arangodb/arangodb/pull/19348

QA-451: testing: implement san logfile reading in testing.js (#19348)

---

arangod/IResearch/IResearchDataStore.cpp
scripts/test/testing_runner.py

backport of https://github.com/arangodb/arangodb/pull/19407

BTS-1512: Bug fix 3.11/fix crash state

---

arangod/IResearch/IResearchLink.cpp

backport of https://github.com/arangodb/arangodb/pull/19407

BTS-1512: disable coredumps in this case

---

arangod/RocksDBEngine/RocksDBEngine.cpp

Backport of https://github.com/arangodb/arangodb/pull/19391
Adjust LZ4 parameter documentation.

adjust LZ4 parameter documentation

---

arangod/Replication2/ReplicatedLog/LogLeader.cpp
arangod/Replication2/ReplicatedLog/ReplicatedLog.h
arangod/Replication2/ReplicatedState/StreamProxy.h
arangod/Replication2/ReplicatedState/StreamProxy.tpp
arangod/Replication2/StateMachines/Document/DocumentLeaderState.cpp
arangod/Replication2/StateMachines/Document/DocumentStateMachine.h
arangod/Replication2/Streams/Streams.h
arangod/Transaction/Methods.cpp
tests/Replication2/Mocks/DocumentStateMocks.h
tests/Replication2/ReplicatedState/StateMachines/DocumentState/LeaderTest.cpp

Pass waitForSync parameter per operation.

[CINFRA-805] Pass waitForSync parameter per operation (e.g. document modification)

---

arangod/Cluster/CreateCollection.cpp
arangod/Cluster/CreateCollection.h
arangod/Graph/Graph.cpp
arangod/Graph/GraphManager.cpp
arangod/VocBase/Methods/UpgradeTasks.cpp
arangod/VocBase/vocbase.h

*Just removed an include, where we could get away with forwards. No logic change included.*

Removed an unnecessary header include and fixed aftermath

---

js/client/modules/@arangodb/testsuites/gtest.js

[3.11] Do not run LongRunning google tests

---

arangod/Agency/Node.cpp
arangod/Replication2/Storage/RocksDB/AsyncLogWriteBatcher.cpp
lib/Rest/GeneralRequest.cpp
lib/Rest/HttpRequest.cpp
lib/Rest/VstRequest.cpp

Fixing cppcheck errors. All bogus.

cppcheck suppressions

---

tests/js/client/communication/test-communication.js

this is an oversight of https://github.com/arangodb/arangodb/pull/19126 to adjust a test to use the instance manager.

QA-433: Bug fix 3.10/missing backport communication

---

arangod/Agency/Node.cpp

Attempt to fix a compile error on Windows.

fix compilation with msvc

---

arangod/RestHandler/RestReplicationHandler.cpp

Backport of https://github.com/arangodb/arangodb/pull/19481
Fix wrong assertion and return error correctly.

fix wrong assertion and return error correctly

---

CHANGELOG
arangod/IResearch/IResearchDataStore.cpp
arangod/IResearch/IResearchDataStore.h
arangod/IResearch/IResearchFeature.cpp
arangod/IResearch/IResearchFeature.h
arangod/IResearch/IResearchRocksDBInvertedIndex.h
arangod/IResearch/IResearchRocksDBLink.h
arangod/IResearch/IResearchRocksDBRecoveryHelper.cpp
arangod/Indexes/Index.h
arangod/Metrics/ClusterMetricsFeature.cpp
arangod/Metrics/ClusterMetricsFeature.h
arangod/RestServer/DatabaseFeature.cpp
arangod/RestServer/DatabaseFeature.h
arangod/RocksDBEngine/RocksDBBuilderIndex.cpp
arangod/RocksDBEngine/RocksDBBuilderIndex.h
arangod/RocksDBEngine/RocksDBCollection.cpp
arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
arangod/RocksDBEngine/RocksDBEdgeIndex.h
arangod/RocksDBEngine/RocksDBIndex.cpp
arangod/RocksDBEngine/RocksDBIndex.h
arangod/RocksDBEngine/RocksDBVPackIndex.cpp
arangod/RocksDBEngine/RocksDBVPackIndex.h
tests/IResearch/IResearchLinkTest.cpp
tests/Mocks/IResearchInvertedIndexMock.cpp
tests/Mocks/IResearchInvertedIndexMock.h
tests/Mocks/StorageEngineMock.cpp
tests/js/server/recovery/view-arangosearch-link-populate-truncate-replay-noncluster.js
tests/js/server/recovery/view-search-alias-populate-truncate-replay-noncluster.js
tsan_arangodb_suppressions.txt

* Fix unstable test (#19281)
* Try to make cluster tests tsan run more useful (#19344) 
* Fix SEARCH-465 (#19360)
* Make post recovery callbacks parallel (#19428)

Backports to 3.10

---

arangod/RocksDBEngine/RocksDBCollection.cpp

As @jsteemann mentioned it was possible that indexes list changed after truncateBegin but before truncateCommit
This PR addresses this issue.

[3.10] Fix potential logical race condition

---

arangod/IResearch/IResearchAnalyzerFeature.cpp
arangod/IResearch/IResearchFeature.cpp
arangod/IResearch/IResearchFeature.h
arangod/IResearch/IResearchInvertedIndex.cpp

Suppress some cppcheck issue 3.10

---

arangod/RocksDBEngine/RocksDBMetaCollection.cpp
tests/js/client/active-failover/disconnected-leader-nonwindows-nocov-noasan.js
tests/js/client/shell/shell-collection-counts-cluster.js

try to improve flaky test

---

scripts/toolbox/HotBackupConsistencyTest.py

Import `ServerConnectionError` exception and add a catch-all exception branch

Fix HotBackupConsistencyTest.py 

---

tests/js/client/server_parameters/test-return-queue-time-header-on.js

Try to decrease likelihood of test failure although there is still no 100% guarantee that the test will succeed.

try to decrease likelihood of test failure

---

arangod/IResearch/IResearchFeature.cpp

Suppress high cppcheck issues

---

tests/js/client/server_parameters/exclusive-collections-off.js

Fix incomplete assertion in test.

fix incomplete assertion in test

---

CMakeLists.txt

Backport of https://github.com/arangodb/arangodb/pull/19429

[3.11] FIx version generation for Release and Nightly builds

---

CMakeLists.txt

Backport of https://github.com/arangodb/arangodb/pull/19429

[3.10] FIx version generation for Release and Nightly builds

---

Documentation/Metrics/arangodb_agency_node_memory_usage.yaml

See PR description: slightly improve description of a metric

improve metric description

---

tests/js/server/aql/aql-index-cache.js

Make failure in aql-index-cache test less likely, although it is still not guaranteed that the tests all pass.

decrease possibility of test failure

---

lib/Basics/SizeLimitedString.h

Fix compilation on Windows target

---

arangod/Replication2/ReplicatedLog/Algorithms.cpp
arangod/Replication2/ReplicatedLog/LogCommon.cpp
arangod/Replication2/ReplicatedLog/LogCommon.h
arangod/Replication2/ReplicatedLog/LogLeader.cpp
tests/Replication2/Mocks/FakeStorageEngineMethods.cpp
tests/Replication2/ReplicatedLog/Algorithms/CalcCommitIndexTest.cpp

Make NonEligibleServerRequiredForQuorum::Why a class enum

---

CHANGELOG
arangod/RocksDBEngine/RocksDBCollection.cpp
arangod/RocksDBEngine/RocksDBPrimaryIndex.cpp
arangod/RocksDBEngine/RocksDBTransactionState.cpp
arangod/RocksDBEngine/RocksDBTransactionState.h
arangod/RocksDBEngine/SimpleRocksDBTransactionState.cpp
arangod/RocksDBEngine/SimpleRocksDBTransactionState.h
arangod/Transaction/Hints.cpp
arangod/Transaction/Hints.h
arangod/arangoserver.cmake

Added better diagnostic messages in case documents<->primarx index corruption occurs.

Added better diagnostic messages

---

arangod/Pregel/PregelFeature.cpp

Backport of https://github.com/arangodb/arangodb/pull/19565

[3.10] Make Pregel work on OneShard databases without issues

---

.circleci/base_config.yml
js/apps/system/_admin/aardvark/APP/frontend/js/arango/arango.js

*The nightly Jenkins run fails on recent change for JSlint we did for CircleCI. This should work for both.*

Fixed red JSLint job on nightly Jenkins

---

CHANGELOG

Reduce memory and cpu usage for insertion and consolidation

Update iresearch 3.10

---

arangod/Pregel/PregelFeature.cpp

Backport of https://github.com/arangodb/arangodb/pull/19565

[3.11] Make Pregel work on OneShard databases without issues

---

.circleci/base_config.yml
js/apps/system/_admin/aardvark/APP/frontend/js/arango/arango.js
scripts/build/arangodb-build.Dockerfile
scripts/build/install-openldap.sh
scripts/build/install-openssl.sh

Update build container with OpenSSL 3.0.10 and OpenLDAP 2.6.6

Update build container to OpenSSL 3.0.10

---

CHANGELOG
arangod/Agency/AgencyComm.cpp
arangod/Cluster/ClusterInfo.cpp
arangod/RestHandler/RestAdminServerHandler.cpp
arangod/VocBase/VocbaseInfo.cpp
arangod/VocBase/VocbaseInfo.h
arangod/VocBase/vocbase.cpp
arangod/VocBase/vocbase.h

3.11 Backport of: https://github.com/arangodb/arangodb/pull/19542
Please see all details there.
There is an EE PR: https://github.com/arangodb/enterprise/pull/1352

[BTS-1544][3.11] _system db not reporting its sharding property correctly

---

arangod/Aql/IResearchViewExecutor.h
arangod/Aql/IResearchViewExecutor.tpp
arangod/IResearch/ExpressionFilter.cpp
arangod/IResearch/ExpressionFilter.h
arangod/IResearch/GeoFilter.cpp
arangod/IResearch/GeoFilter.h
arangod/IResearch/IResearchInvertedIndex.cpp
arangod/IResearch/IResearchPrimaryKeyFilter.h
arangod/IResearch/ResourceManager.hpp
tests/IResearch/ExpressionFilterTest.cpp
tests/IResearch/GeoDistanceFilterTest.cpp
tests/IResearch/GeoFilterTest.cpp
tests/IResearch/IResearchDocumentTest.cpp

ArangoDB part of accounting tested automatically via assert in ResourceMonitor object dtor

APM-670 account prepared statements memory 

---

arangod/Agency/AgencyComm.cpp
arangod/Aql/IResearchViewOptimizerRules.cpp
arangod/Aql/IndexExecutor.cpp
arangod/Aql/MultipleRemoteModificationExecutor.cpp
arangod/Aql/OptimizerRules.cpp
arangod/Aql/UpsertModifier.cpp
arangod/Cluster/MaintenanceRestHandler.cpp
arangod/IResearch/IResearchAnalyzerFeature.cpp
arangod/Pregel/AlgoRegistry.cpp
arangod/RestHandler/RestAdminClusterHandler.cpp
arangod/RestHandler/RestLogHandler.cpp
arangod/RestServer/CheckVersionFeature.cpp
arangod/RestServer/VocbaseContext.cpp
arangod/StorageEngine/HotBackup.cpp
arangod/V8Server/V8DealerFeature.cpp
arangod/V8Server/v8-pregel.cpp
arangod/VocBase/VocBaseLogManager.cpp
lib/Basics/files.cpp
lib/Basics/signals.cpp
lib/Maskings/Maskings.cpp
scripts/shutdownLocalCluster.sh

Enterprise companion PR: https://github.com/arangodb/enterprise/pull/1357
Remove dead code. Found by compiling with `-Wunreachable-*`

dead code removal

---

CHANGELOG
arangod/Aql/AqlCall.h
arangod/Aql/LimitExecutor.cpp
tests/Aql/LimitExecutorTest.cpp

3.9 Backport of: https://github.com/arangodb/arangodb/pull/19592
See details there.

[BTS-1553][3.9] Fix wrong limit value use in LimitExecutor

---

arangod/RocksDBEngine/RocksDBValue.cpp

Just two slight nitpicks I noticed while viewing a diff too late in #19641.

Assert same size of uint64_t and double for bitcast

---

3rdParty/iresearch/external/kaldi/src/fstext/determinize-star-inl.h
CHANGELOG

Fix wildcard specific utf8 issue 3.9

---

arangod/Agency/AgencyComm.cpp

Small efficiency improvement for AgencyComm.
Pulled out of other PR to make it smaller.

small efficiency improvement for AgencyComm

---

js/client/modules/@arangodb/testsuites/rta_makedata.js

the rta_makedata suite would clean up though failures occured. Fix the result handling so we have proper signalling for that.

fix testresult handling

---

arangod/GeneralServer/CommTask.cpp
arangod/GeneralServer/RestHandler.cpp
arangod/RestHandler/RestMetricsHandler.cpp

Avoid duplicate gzip-encoding of contents in metrics handler

avoid duplicate content-encoding

---

arangod/Replication2/Supervision/CollectionGroupSupervision.cpp
client-tools/Restore/RestoreFeature.cpp

Fix windows build

---

arangod/RocksDBEngine/RocksDBSettingsManager.cpp

Remove 2 unused lines of code.

remove unused options

---

CHANGELOG
arangod/Cluster/ClusterFeature.cpp

backport of https://github.com/arangodb/arangodb/pull/19611

Added minimal bug-fix (#19611)

---

lib/Containers/FlatHashMap.h
lib/Containers/FlatHashSet.h

sizeof is different in such case

Fix compile with address sanitizer

---

arangod/Pregel/Algos/LineRank/LineRank.cpp
js/common/modules/@arangodb/graph/pregel-test-helpers.js
tests/js/common/shell/shell-pregel-components.js

In `preApplication` the number of edges is not yet initialized. However, in `preGlobalSuperstep` it is.

[OASIS-25486] Fix line rank computation.

---

js/client/modules/@arangodb/testutils/test-utils.js

we wouldn't properly evaluate the result of arangosh subshell tests in some case. fix this.

we need to reflect whether running the arangosh was successfull or not.

---

arangod/Pregel/Algos/LineRank.cpp
js/common/modules/@arangodb/graph/pregel-test-helpers.js
tests/js/common/shell/shell-pregel-components.js

Backport of https://github.com/arangodb/arangodb/pull/19761

[3.10] [OASIS-25486] fix line rank computation

---

arangod/Pregel/Algos/LineRank/LineRank.cpp
js/common/modules/@arangodb/graph/pregel-test-helpers.js
tests/js/common/shell/shell-pregel-components.js

[3.11] [OASIS-25486] fix line rank computation

---

js/apps/system/_admin/aardvark/APP/frontend/js/collections/arangoQueries.js

3.10 quickfix eslint related to: https://github.com/arangodb/arangodb/pull/19799

[3.10] fix eslint

---

js/apps/system/_admin/aardvark/APP/frontend/js/collections/arangoQueries.js

quick eslint fix for 3.11 branch only

[3.11] fix eslint

---

client-tools/Shell/ProcessMonitoringFeature.cpp
client-tools/Shell/v8-deadline.cpp
lib/Basics/FileUtils.cpp
lib/Basics/process-utils.cpp
lib/Basics/process-utils.h
lib/V8/v8-deadline.h
lib/V8/v8-no-deadline.cpp
lib/V8/v8-utils.cpp

backport of https://github.com/arangodb/arangodb/pull/19789

Make our waitpid implementation interupteable by the monitoring thread

---

lib/Basics/VelocyPackHelper.cpp
tests/js/client/shell/multi/shell-vpack.js

Detect numeric attribute ids in returned VelocyPack data and sanitize it to use string attribute names

detect numeric attribute ids in returned VelocyPack data

---

arangod/Aql/AqlItemBlock.cpp
arangod/Aql/AsyncExecutor.cpp
arangod/Aql/CalculationExecutor.cpp
arangod/Aql/DistinctCollectExecutor.h
arangod/Aql/DocumentProducingNode.cpp
arangod/Aql/DocumentProducingNode.h
arangod/Aql/ExecutionStats.h
arangod/Aql/HashedCollectExecutor.cpp
arangod/Aql/ModificationNodes.h
arangod/Aql/OutputAqlItemRow.cpp
arangod/Aql/OutputAqlItemRow.h
arangod/Aql/Query.cpp
arangod/Aql/SortedCollectExecutor.cpp
arangod/Aql/SortedCollectExecutor.h

Some unrelated small cleanups:
- fix include order
- mark functions as noexcept
- use absl::StrCat

small code cleanup, pulled out of larger PR

---

arangod/RestServer/EnvironmentFeature.cpp

See PR title.
If we should ever add a target platform that does not satisfy these requirements, we will know quickly because compilation will fail.

assert that atomic ops on basic integral types are always lock-free

---

CMakeLists.txt

Backport of https://github.com/arangodb/arangodb/pull/19849

Bugfix 3.11: Fix build of arangodb target

---

.gitmodules
js/client/modules/@arangodb/testsuites/dump.js
js/client/modules/@arangodb/testsuites/rta_makedata.js
js/client/modules/@arangodb/testutils/instance-manager.js
js/client/modules/@arangodb/testutils/instance.js
js/client/modules/@arangodb/testutils/process-utils.js
js/client/modules/@arangodb/testutils/test-utils.js
js/client/modules/@arangodb/testutils/testing.js
tests/js/common/test-data/maskings/maskings1.json
tests/js/server/dump/dump-check-dump-files-compressed.js
tests/js/server/dump/dump-check-dump-files-uncompressed.js
tests/js/server/dump/dump-maskings.js
tests/js/server/dump/dump-setup-multiple.js
tests/js/server/dump/dump-test.inc
tests/test-definitions.txt

backport of https://github.com/arangodb/arangodb/pull/19718 + some more changes

sync dump + rta changes

---

arangod/RestHandler/RestCursorHandler.cpp
client-tools/Restore/RestoreFeature.cpp
lib/Basics/ArangoGlobalContext.cpp
lib/Basics/VelocyPackHelper.cpp
lib/Basics/VelocyPackHelper.h
tests/Aql/SortLimitTest.cpp

Improve error message for wrong batchSize values.
Also clean up generic error messages and APIs in VelocyPackHelper a bit.

improve error message for wrong batchSize values

---

arangod/Cluster/ClusterInfo.cpp
arangod/Scheduler/Scheduler.h
arangod/Scheduler/SupervisedScheduler.cpp

Added code documentation to scheduler API header file

add code documentation to scheduler API

---

arangod/Cache/Manager.cpp
tests/Cache/Manager.cpp

Fix a potential recursive lock invocation.
This only happened if the cache manager was destroyed while caches were still in use. 
In this case, the Manager's dtor called `Manager::shutdown()`, which went through all still-available caches, and called `Cache::shutdown()` on them. The Cache shutdown would call `Manager::unregisterCache(), which could acquire the Manager `_lock`, and then remove the Cache object from the map of caches (_caches). If the last shared_ptr to the Cache was destroyed, the Cache's dtor could try to call into the Manager for a memory allocation ajdusted. this could against acquire the Manager's `_lock` again, so there would be a recursive invocation.
This only happened upon shutdown, and in no released versions.

fix potential recursive lock invocation

---

arangod/Graph/GraphOperations.cpp

Enterprise companion PR: https://github.com/arangodb/enterprise/pull/1388
Remove unused V8 include

remove unused include

---

arangod/Indexes/IndexIterator.h

Just documentation.
This resolves an internal code comment by @MBkkt

add code documentation for IndexIterator

---

tests/IResearch/common.cpp

BTS-1632 Fix data race between truncate and abort transaction in iresearch

---

CHANGELOG
js/apps/system/_admin/aardvark/APP/react/src/views/views/constants.ts

backport for https://github.com/arangodb/arangodb/pull/19857

bug-fix-3.11/FE-323: allow 'nested' property in view JSON UI

---

CHANGELOG
js/apps/system/_admin/aardvark/APP/frontend/js/arango/arangoValidationHelper.js
js/apps/system/_admin/aardvark/APP/frontend/js/views/graphManagementView.js
js/apps/system/_admin/aardvark/APP/react/src/App.js

Adds graph name validation in 3.10 (same as 3.11)

bug-fix-3.10/FE-317: add graph name validation

---

CHANGELOG
js/apps/system/_admin/aardvark/APP/react/src/views/views/constants.ts

backport for https://github.com/arangodb/arangodb/pull/19857

bug-fix-3.10/FE-323: allow 'nested' property in view JSON UI

---

tests/js/server/replication2/replication2-replicated-state-document-store.js

The `testCreateMultipleCollections` has been sometimes failing in CircleCI, for unrelated PRs.  
The actual problem comes from the `checkCollectionShards`. This method is used to check that servers (i.e. the state machines of these servers) are aware of the fact that they need to host a particular shard. Now, on the leaders, this information is guaranteed to become available as soon as the collection is reported as created, since the leaders are the ones reporting to Current. However, the followers might experience some delay, especially if the replication factor is greater than the write concern. So, this depends on whether the maintenance is fast enough to create the log and the shard on each follower, before we perform the check.
This PR adds `waitFor` when checking the followers, but …

[CINFRA-843] Fix flaky test

---

arangod/IResearch/IResearchInvertedIndexMeta.h
arangod/IResearch/IResearchLinkMeta.cpp

[BTS-1634] Fix has nested for links

---

arangod/Aql/JoinExecutor.cpp
arangod/Aql/JoinNode.cpp
arangod/RocksDBEngine/RocksDBVPackIndex.cpp
js/common/modules/@arangodb/aql/explainer.js
tests/js/server/aql/aql-index-join-noncluster.js

Polish the join node. This PR includes:
- fixing the calculation of the estimates.
- adding more tests for unique indexes.
- fixing a bug when using a unique index for joins (thanks to the tests)
- added more details to the explainer

Join Node polish

---

.circleci/base_config.yml
arangod/GeneralServer/GeneralServerFeature.cpp
arangod/RestHandler/RestAqlUserFunctionsHandler.cpp
arangod/RestHandler/RestAqlUserFunctionsHandler.h
arangod/arangoserver.cmake

fix compile error with -DUSE_V8=Off

---

arangod/RocksDBEngine/RocksDBOptionFeature.cpp

Fix incorrect ifdef that unnecessary disabled rocksdb feature

---

arangod/Cluster/ClusterMethods.cpp

Slightly improve cluster-internal error handling in a few cases.

small improvement for cluster-internal error handling

---

arangod/Aql/AqlValue.cpp
arangod/Aql/AqlValue.h
arangod/Aql/DocumentProducingHelper.cpp
arangod/Aql/IResearchViewExecutor.h
arangod/Aql/IResearchViewExecutor.tpp
arangod/Aql/JoinExecutor.cpp
arangod/Aql/MaterializeExecutor.cpp
arangod/Aql/MultiGet.h
arangod/Aql/OutputAqlItemRow.cpp
arangod/Cluster/TraverserEngine.cpp
arangod/Graph/Cache/RefactoredTraverserCache.cpp
arangod/Graph/Cursors/RefactoredSingleServerEdgeCursor.cpp
arangod/Graph/SingleServerEdgeCursor.cpp
arangod/Graph/TraverserCache.cpp
arangod/Indexes/IndexIterator.h
arangod/Pregel/GraphStore/GraphLoader.cpp
arangod/Replication/DatabaseInitialSyncer.cpp
arangod/RocksDBEngine/RocksDBCollection.cpp
arangod/RocksDBEngine/RocksDBGeoIndex.cpp
arangod/RocksDBEngine/RocksDBIncrementalSync.cpp
arangod/RocksDBEngine/RocksDBIterators.cpp
arangod/RocksDBEngine/RocksDBVPackIndex.cpp
arangod/Transaction/Methods.cpp
arangod/V8Server/v8-query.cpp
arangod/VocBase/Methods/Collections.cpp
tests/Aql/SpliceSubqueryOptimizerRuleTest.cpp
tests/Graph/TraverserCacheTest.cpp
tests/Mocks/PhysicalCollectionMock.cpp
tests/VocBase/ComputedValuesTest.cpp

* Resolve todo (about not using ability to store pointer to string in aql value)
* Make interface (DocumentCallback) more user friendly

Improve reading document from collection

---

arangod/IResearch/IResearchInvertedIndexMeta.h
arangod/IResearch/IResearchLinkMeta.cpp

Backport this https://github.com/arangodb/arangodb/pull/19912

[BTS-1634] backport to 3.10

---

js/client/modules/@arangodb/testutils/instance-manager.js

backport of https://github.com/arangodb/arangodb/pull/19913

distribute memory in a way that all tests work (#19913)

---

arangod/IResearch/IResearchInvertedIndexMeta.h
arangod/IResearch/IResearchLinkMeta.cpp

Backport this https://github.com/arangodb/arangodb/pull/19912

[BTS-1634] backport to 3.11

---

cmake/packages/client/nsis.txt
cmake/packages/nsis.cmake

forward V8 flag into client package

---

arangod/Agency/Supervision.cpp

fix crash in supervision if no indexes are present. this should normally not happen, but could happen under some circumstances after the supervision wrote entries into the agency without a suitable precondition

fix a crash in supervision

---

arangod/Aql/IndexStreamIterator.h
arangod/Aql/JoinNode.cpp
arangod/Aql/OptimizerRules.cpp
arangod/ClusterEngine/ClusterIndex.cpp
arangod/ClusterEngine/ClusterIndex.h
arangod/RocksDBEngine/RocksDBVPackIndex.cpp
arangod/RocksDBEngine/RocksDBVPackIndex.h
tests/js/server/aql/aql-index-join.js

Ask the index if it supports the stream interface instead of assuming its alsways the vpack index.

JoinNode check index supports stream

---

lib/Basics/Exceptions.h

make exception macros more versatile

make exception macros more versatile

---

arangod/Aql/MaterializeExecutor.cpp

Just for check

---

arangod/Aql/ShortestPathExecutor.h
arangod/Aql/ShortestPathExecutor.tpp
arangod/Graph/Enumerators/OneSidedEnumeratorInterface.cpp
arangod/Graph/Providers/ClusterProvider.cpp
arangod/Graph/Providers/ClusterProvider.h
arangod/Graph/Providers/ProviderTracer.cpp
arangod/Graph/Providers/ProviderTracer.h
arangod/Graph/Providers/SingleServerProvider.cpp
arangod/Graph/Providers/SingleServerProvider.h
arangod/Graph/ShortestPathOptions.cpp
arangod/Graph/ShortestPathOptions.h
arangod/Graph/algorithm-aliases.h

* renames `WeightedEnumeratorRefactored` to `WeightedEnumerator`
* Removes some now unused code from ShortestPathOptions
* Removes some now unused code from ShortestPathExecutor
Requires Enterprise companion  https://github.com/arangodb/enterprise/pull/1396

Some cleanups in graph code

---

3rdParty/tzdata/windowsZones.xml

Refresh timezone database as of 16.10.2023.

Refresh timezone database as of 16.10.2023 (3.10)

---

3rdParty/tzdata/windowsZones.xml

Refresh timezone database as of 16.10.2023.

Refresh timezone database as of 16.10.2023

---

tests/js/server/aql/aql-complex-queries-callstack-noinstr.js

This is a backport from devel to make the test pass in 3.11 again.

Adjust callstack limit in test

---

tests/js/client/server_parameters/dump-limits-noncluster-nonwindows.js

Fix often-failing `server_parameters` dump test.
The test in question sets a low overall memory limit (16MB) for the server for creating dumps. Then it orders 3 dumps, all of which are intentionally trying to exceed the overall memory limit.
The bug in the test was that it tries to fetch data from all 3 dumps in sequential order by making a blocking call for each dump, e.g.
1. `/_api/dump/1/next`
2. `/_api/dump/2/next`
3. /`_api/dump/3/next`
However, it is possible that the 3 dumps execute out of order on the server side. For example, if dump 2 or dump 3 produce their output before dump 1 and hit the memory limit, dump 1 cannot produce any output.
Thus the call to fetch output for dump 1 can block, which eventually makes the test abort or fail.

fix `server_parameters` dump test

---

lib/Basics/FileDescriptors.cpp

the previous implementation did not allow to start arangod under Valgrind instrumentation, because under Valgrind's influence, any setrlimit calls fail that try to increase the number of file descriptors too much.

do not fail when trying to increase file descriptors limit

---

tsan_arangodb_suppressions.txt

TSAN still has noise which we won't fix. Add missing suppressions

add missing suppression

---

arangod/Aql/IResearchViewExecutor.h
arangod/Aql/IResearchViewExecutor.tpp

Search parallelization fix leftovers [1/N]

---

arangod/RocksDBEngine/RocksDBPrimaryIndex.cpp

Those options are not required. Therefore deleted.

Cleanup RocksDBPrimaryIndexStreamOptions

---

3rdParty/fuerte/src/jwt.cpp
arangod/Agency/AgencyCommon.h
arangod/Replication2/Storage/WAL/FileWriterImpl.cpp

Fix compile errors with newer versions of clang / libc++

fix compile errors

---

3rdParty/V8/v7.9.317/src/utils/utils.h

Fix compilation of ArangoDB with clang-16.

fix compilation with clang-16

---

js/client/modules/@arangodb/testutils/result-processing.js

backport of https://github.com/arangodb/arangodb/pull/20075

don't output 'undefined' - this will give NaN in the xml

---

arangod/VocBase/LogicalCollection.cpp

Remove a few lines of legacy compatibility code that is potentially irrelevant now.

remove small legacy code part

---

tests/js/server/dump/dump-test.inc

Add debug context in case of test failure.
Test-only change.

add debug output for test

---

arangod/Aql/IResearchViewExecutor.tpp
tests/js/client/aql/aql-view-bitset-join.js

Additional tests and performance improvement for APM-701

Search view bitset join leftovers

---

arangod/Cluster/ClusterMethods.cpp
arangod/RestServer/LanguageCheckFeature.cpp
arangod/RestServer/LanguageCheckFeature.h
lib/Logger/LogContext.h

Enterprise companion PR: https://github.com/arangodb/enterprise/pull/1408
Fix several compile issues with gcc-13.
Fix for `LogContext.h` provided by @mpoeter.

fix several gcc-13 compile issues

---

arangod/Aql/IResearchViewExecutor.h
arangod/Aql/IResearchViewExecutor.tpp
arangod/IResearch/IResearchInvertedIndex.cpp
arangod/IResearch/ViewSnapshot.cpp
arangod/IResearch/ViewSnapshot.h

Search view bitset join memory accounting

---

arangod/Aql/DocumentProducingHelper.cpp
arangod/Aql/DocumentProducingHelper.h
arangod/Aql/EnumerateCollectionExecutor.cpp
arangod/Aql/IndexExecutor.cpp
arangod/Aql/Stats.h
tests/Aql/EnumerateCollectionExecutorTest.cpp

Addition to [EF-1]: Lookup stats for IndexExecutor + EnumerateCollectionExecutor

---

scripts/test/async_client.py

Write some messages to stdout as well so they also show up in CircleCI

[CircleCI] Improve log output in some error cases

---

lib/Logger/LoggerFeature.cpp

Documentation-3.10/options-wording

---

arangod/Aql/AttributeNamePath.cpp
arangod/Aql/AttributeNamePath.h
arangod/Aql/OptimizerRules.cpp
js/client/modules/@arangodb/testutils/joinHelper.js
tests/js/client/aql/aql-index-join.js
tests/js/client/aql/aql-optimizer-rule-optimize-projections.js

Optimize projections in join nodes more aggressively. With this PR the optimizer eliminates all projections in a join node that are no longer needed later in the query.

[JOIN] More optimized projections

---

lib/Logger/LogAppenderSyslog.cpp

This is an alternative implementation of the fix in #20112 not requiring an extra file compiled as C and using suppressions.

Fix compilation with newer clang versions and musl (Alternative approach)

---

Documentation/Metrics/arangodb_agency_node_memory_usage.yaml
Documentation/Metrics/arangodb_dump_threads_blocked_total.yaml
Documentation/Metrics/arangodb_internal_cluster_info_memory_usage.yaml
Documentation/Metrics/arangodb_search_execution_threads_demand.yaml
Documentation/Metrics/arangodb_search_mapped_memory.yaml
utils/generateAllMetricsDocumentation.py

Validate introducedIn in metric YAML files better, reword and format some of the new metric descriptions

Docs: Rephrase some metric descriptions, add version pattern check

---

arangod/Aql/ExecutionNode.cpp
arangod/Aql/QueryContext.h
arangod/Cache/CacheManagerFeature.cpp
etc/relative/arangobench.conf

Various small unrelated changes. See individual commit messages for details.

Small unrelated changes

---

arangod/Replication2/StateMachines/Document/DocumentStateSnapshot.h
arangod/RestServer/DatabaseFeature.cpp

This PR fixes the Windows build.
An unrelated comment has been added (which I intended to add in a previous PR but I forgot).

Fixing windows build

---

3rdParty/CMakeLists.txt
3rdParty/V8/CMakeLists.txt
lib/V8/v8-mkpeephole.in
lib/V8/v8-mksnapshot.in

Remove generated files from repository.
It seems that these files are not needed for the V8 build.

remove generated files

---

arangod/Pregel/PregelFeature.cpp
arangod/Pregel/REST/RestPregelHandler.cpp
lib/Actor/include/Actor/DistributedRuntime.h
lib/Actor/include/Actor/HandlerBase.h
tests/Actor/DistributedRuntimeTest.cpp
tests/Actor/EgressActorTest.cpp
tests/Actor/MultiRuntimeTest.cpp

Make spawn return a complete ActorPID instead of just the ID,

Refactor: make spawn return an ActorPID

---

scripts/docker/build/windows/arangodb-build-win.Dockerfile

so we are consistent with the VS version used in Jenkins.

Update Windows image to use MSVC 17.3.6

---

tests/Basics/FpConvTest.cpp

Fix an MSVC test expectation.
Test-only bugfix

fix MSVC test expectation

---

lib/Actor/include/Actor/BaseRuntime.h
lib/Actor/include/Actor/DistributedRuntime.h
lib/Actor/include/Actor/LocalActorPID.h
lib/Actor/include/Actor/LocalRuntime.h
lib/Actor/include/Actor/Message.h
tests/Actor/Actors/PingPongActors.h
tests/Actor/CMakeLists.txt
tests/Actor/MultiRuntimeTest.cpp
tests/Actor/RuntimeTest.cpp

This PR introduces a new `LocalRuntime` type for actors that is optimized for local execution. It is largely identical to the `DistributedRuntime` but uses a simpler (and cheaper) PID type and obviously does not support dispatching messages to other servers. The existing runtime tests have been generalized to cover both runtimes.

Introduce actor LocalRuntime

---

arangod/Aql/Aggregator.cpp
arangod/Aql/OptimizerRules.cpp
arangod/IResearch/ViewSnapshot.cpp
arangod/Replication2/Storage/WAL/LogReader.cpp
arangod/RestServer/DaemonFeature.cpp
lib/Basics/FloatingPoint.h

Fix some compile warnings with elevated warning options.

fix some compile warnings

---

js/apps/system/_admin/aardvark/APP/frontend/js/views/loading.js

Reverts arangodb/arangodb#20224

Revert "FE-386 | Fix global imports in loading.js"

---

tests/js/client/shell/api/api-replication.js

*On Replication2 we expose the GroupID of every collection. This modifies the API test to assert that the GroupID is exported properly.*

Replication2: Api RestoreTests include GroupID

---

arangod/Cluster/ClusterFeature.cpp
arangod/Cluster/ClusterInfo.cpp
arangod/Cluster/ClusterInfo.h
tests/Mocks/ClusterInfoMock.cpp
tests/Mocks/Servers.cpp

Speculative fix for https://arangodb.atlassian.net/browse/BTS-1671

BTS-1671: force shutdown of syncers in ClusterFeature shutdown

---

CHANGELOG

arangorestore, not arangodump:
https://github.com/arangodb/arangodb/pull/20020
Duplicated line:
https://github.com/arangodb/arangodb/pull/19943

Fix changelog entry

---

CHANGELOG

https://github.com/arangodb/arangodb/pull/20218 was missing the CHANGELOG entry.

Add CHANGELOG entry for #20218 

---

arangod/ClusterEngine/ClusterIndex.cpp
arangod/Indexes/IndexFactory.cpp
arangod/Indexes/IndexFactory.h
arangod/RocksDBEngine/RocksDBValue.cpp
arangod/RocksDBEngine/RocksDBValue.h
arangod/RocksDBEngine/RocksDBZkdIndex.cpp
arangod/RocksDBEngine/RocksDBZkdIndex.h
tests/js/client/aql/aql-optimizer-zkdindex-stored-values.js
tests/js/client/aql/aql-optimizer-zkdindex-unique.js

Add stored values to zkd index.

Stored Values

---

tests/js/client/server_parameters/dump-limits-noncluster-nonwindows.js

Try to improve robustness of server_parameter's dump test.

(hopefully) make test more robust

---

tests/js/client/shell/shell-admin-cluster-rebalance.js

*In Replication1 a new backup Server is instantiated as follower as soon as a Server is flagged as "FAILED" for all its shards. In Replication2 we are a bit more optimistic with this, as long as the server is "known" we assume it will return. We will instantiate new Followers as soon as server is actively marked as GONE.
The Test changed here is waiting for Instanciation of Follower and hence stuck.
Bonus Points: The test actually has a 300s timeout, which was placed in the wrong loop (it was skipped whenever the Dead server was still found, and only triggered on any good situation reached after 300s, so in case we ever stay dead we skipped over it.). Moved the timeout now to a place where it is considered if we stay "unexpected" for 300s or more.
*
*(Please reference tickets / …

CINFRA - Test adaption ShardRebalance Test

---

arangod/IResearch/Wildcard/Analyzer.cpp
arangod/IResearch/Wildcard/Analyzer.h

Fix gcc build

---

arangod/VocBase/VocBaseLogManager.cpp

Fix compile error with clang-14:
https://jenkins.arangodb.biz/job/arangodb-ANY-linux-san.x86-64/EDITION=enterprise,SAN_MODE=AULSan,STORAGE_ENGINE=rocksdb,TEST_SUITE=single,limit=linux&&test&&cloud&&x86-64/2241/artifact/buildArangoDB.log

fix compile error with clang-14

---

arangod/Sharding/ShardingFeature.cpp
arangod/Sharding/ShardingInfo.cpp
arangod/Sharding/ShardingStrategyDefault.cpp

Usability improvement: Improve error messages for unknown sharding strategies.

improve error messages for unknown sharding strategies

---

tests/js/client/shell/multi/shell-validation.js

Fix flaky schema validation test.

fix flaky schema validation test

---

arangod/Aql/TraverserEngineShardLists.cpp
arangod/Aql/TraverserEngineShardLists.h
arangod/IResearch/IResearchAnalyzerFeature.cpp

Two small unrelated changes:
- remove extraneous whitespace from error message
- make QueryContext parameter const in TraverserEngineShardList ctor

minor code cleanup

---

scripts/test/async_client.py

CI would try to kill svchost.exe - don't do that.

work around wintendo pid grabbing CI issue

---

arangod/Graph/Enumerators/WeightedTwoSidedEnumerator.cpp
arangod/Graph/Enumerators/WeightedTwoSidedEnumerator.h

Reverts arangodb/arangodb#20366

Revert "Fix copy + use after free in path search code"

---

arangod/Graph/Enumerators/WeightedTwoSidedEnumerator.cpp
arangod/Graph/Enumerators/WeightedTwoSidedEnumerator.h

Revert the revert of #20366 . And fix the actual issue.

Revert revert 20366 bug fix/dangling references

---

arangod/RocksDBEngine/RocksDBReplicationContext.cpp

Fix https://arangodb.atlassian.net/browse/BTS-1728.

BTS-1728: don't hold mutex while co_awaiting

---

arangod/RestServer/EndpointFeature.cpp

https://github.com/arangodb/arangodb/pull/19715

Update `--server.endpoint` description for endpoint schema aliases

---

arangod/Scheduler/SupervisedScheduler.cpp

Simplify scheduler code parts as suggested by @mpoeter

simplify scheduler code parts

---

arangod/Aql/EngineInfoContainerDBServerServerBased.cpp
arangod/Aql/ExecutionBlockImpl.h
arangod/Aql/ExecutionBlockImpl.tpp
arangod/Cluster/ClusterMethods.cpp
arangod/RestHandler/RestCollectionHandler.cpp
arangod/RestHandler/RestDocumentHandler.cpp
arangod/RocksDBEngine/ReplicatedRocksDBTransactionState.cpp
arangod/StorageEngine/TransactionState.h

More usages of StrCat. Pulled out of a larger PR to make that PR smaller

more usages of StrCat

---

ubsan_arangodb_suppressions.txt

Suppress yet one more UBSan issue in the immer library

Suppress yet one more UBSan issue in the immer library

---

scripts/unittest

only try to use suppressions file if it actually exists

only try to use suppressions file if it actually exists

---

CHANGELOG
arangod/StorageEngine/TransactionState.cpp

Fix issue https://arangodb.atlassian.net/browse/BTS-1731
The PR fixes the test described in the BTS. 
Unfortunately I wasn't yet able to devise a minimal, reproducible example test case for our own repository.

fix BTS-1731

---

Documentation/Metrics/arangodb_collection_leader_reads_total.yaml
Documentation/Metrics/arangodb_collection_leader_writes_total.yaml
arangod/Metrics/MetricsFeature.cpp
arangod/Network/Utils.cpp
arangod/Network/Utils.h
arangod/Pregel/PregelFeature.cpp
arangod/RestHandler/RestAdminLogHandler.cpp
arangod/RestHandler/RestMetricsHandler.cpp
arangod/RestHandler/RestUsageMetricsHandler.cpp
arangod/Utils/SupportInfoBuilder.cpp
arangod/VocBase/Methods/Queries.cpp

Clean up APM-828 code a bit after code review.

some cleanup for APM-828 after code review

---

arangod/IResearch/IResearchAnalyzerFeature.cpp
tests/js/client/shell/api/analyzer.js

Add multi delimiter analyser.

---

arangod/Aql/IndexNode.h
arangod/Aql/OptimizerRuleBatchMaterializeDocuments.cpp
tests/js/client/aql/aql-index-batch-materialize.js

- Allow IndexNodes that use the same index for multiple conditions.

Improve Batch Materialize

---

arangod/Cluster/ClusterMethods.cpp
arangod/Cluster/ClusterMethods.h
arangod/RestHandler/RestCollectionHandler.cpp

add missing cluster support for REST compact handler on collection level

add missing cluster support for REST compact handler

---

js/apps/system/_admin/aardvark/APP/react/src/components/hooks/useJobSync.ts

Fixes missing error for index creation progress

FE-416: show error when index creation job has failed on web UI

---

CHANGELOG
js/apps/system/_admin/aardvark/APP/frontend/js/views/shardsView.js

FE-349: show full error message when moving shards

---

js/apps/system/_admin/aardvark/APP/frontend/js/views/notificationView.js
js/apps/system/_admin/aardvark/APP/frontend/scss/_notification.scss

FE-417: adjust margin for button overlap

---

js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/CollectionIndicesView.tsx

fixes stat position by removing linewrap and adjsuting line height

FE-394: fix index stat positioning on web UI

---

js/apps/system/_admin/aardvark/APP/react/src/components/table/ListHeader.tsx

Fix a warning produced by the yarn build compile job.

[Bug-Fix] fix ui build

---

js/client/modules/@arangodb/testutils/instance-manager.js

Testing would check for aardvark being ready. We may not have aardvark nowadays on developers systems.

rather check for foxx than aardvark readyness

---

Documentation/Metrics/arangodb_collection_requests_bytes_read_total.yaml
Documentation/Metrics/arangodb_collection_requests_bytes_written_total.yaml
arangod/Metrics/Builder.cpp
arangod/Metrics/Builder.h
arangod/StorageEngine/TransactionState.cpp
arangod/StorageEngine/TransactionState.h
tests/js/client/server_parameters/test-export-shard-usage-metrics-bytes-per-shard-cluster.js
tests/js/client/server_parameters/test-export-shard-usage-metrics-bytes-per-shard-per-user-cluster.js

Ex-post performance optimizations for APM-828

performance optimizations for APM-828

---

arangod/Replication2/StateMachines/Document/Actor/ApplyEntries.cpp

https://arangodb.atlassian.net/browse/CINFRA-874

Update comment about DropShard aborting transactions

---

lib/Actor/include/Actor/Actor.h

Concurrent finish requests could race on setting the exitReason.

Fix data race in actor framework

---

arangod/Replication2/ReplicatedLog/Components/LogFollower.cpp
arangod/Replication2/ReplicatedLog/types.h
arangod/Replication2/ReplicatedState/FollowerStateManager.tpp
arangod/Replication2/ReplicatedState/StateStatus.h
lib/Basics/StaticStrings.h
tests/js/server/replication2/replication2-replicated-state-document-store.js

Report the latest applied index on followers, to make visible how close they are to the latest state.

Report the applied index on followers

---

CHANGELOG
arangod/Cluster/Action.h
arangod/Cluster/ActionBase.cpp
arangod/Cluster/ActionBase.h
arangod/Cluster/EnsureIndex.cpp
arangod/ClusterEngine/ClusterCollection.cpp
arangod/ClusterEngine/ClusterCollection.h
arangod/Indexes/Index.cpp
arangod/Indexes/Index.h
arangod/RestHandler/RestIndexHandler.cpp
arangod/RestServer/TtlFeature.cpp
arangod/RestServer/TtlFeature.h
arangod/RocksDBEngine/RocksDBBuilderIndex.cpp
arangod/RocksDBEngine/RocksDBBuilderIndex.h
arangod/RocksDBEngine/RocksDBCollection.cpp
arangod/RocksDBEngine/RocksDBCollection.h
arangod/StorageEngine/PhysicalCollection.h
arangod/VocBase/LogicalCollection.cpp
arangod/VocBase/LogicalCollection.h
arangod/VocBase/Methods/Indexes.cpp
arangod/VocBase/Methods/Indexes.h
tests/Maintenance/MaintenanceFeatureMock.h
tests/Mocks/StorageEngineMock.cpp
tests/Mocks/StorageEngineMock.h
tests/js/client/shell/shell-index.js
tests/js/common/shell/multi/shell-ttl.js

Enterprise companion PR: https://github.com/arangodb/enterprise/pull/1441
Backport of index https://github.com/arangodb/arangodb/pull/18516 on _api/index*
Also includes forward port of the changes included in the 3.10 PR https://github.com/arangodb/arangodb/pull/20530

[3.11] Index progress visibility

---

CHANGELOG
js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/Analyzer.types.ts
js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/AnalyzersHelpers.ts
js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/addAnalyzer/AnalyzerTypeForm.tsx
js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/addAnalyzer/forms/MultiDelimiterConfig.tsx
js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/addAnalyzer/forms/PipelineConfig.tsx
js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/addAnalyzer/forms/WildcardConfig.tsx

FE-425: adds missing Analyzer types on web UI - "multi_delimiter" & "wildcard"

---

Documentation/Metrics/arangodb_agency_cache_callback_number.yaml
Documentation/Metrics/arangodb_agency_callback_registered_total.yaml
Documentation/Metrics/arangodb_heartbeat_failures_total.yaml
Documentation/Metrics/arangodb_heartbeat_send_time_msec.yaml

Remove mentioning of "active failover"

clean up more metrics

---

arangod/Aql/ClusterQuery.cpp
arangod/Aql/ClusterQuery.h
arangod/Aql/ExecutionBlockImpl.h
arangod/Aql/ExecutionBlockImpl.tpp
arangod/StorageEngine/TransactionState.cpp
arangod/StorageEngine/TransactionState.h
arangod/Transaction/Methods.cpp
arangod/Transaction/Methods.h
arangod/Utils/ExecContext.cpp
arangod/Utils/ExecContext.h

Fix potential UB in non-released code

potentially fix UB

---

Documentation/Metrics/arangodb_agency_cache_callback_number.yaml

Fix an inaccurate metrics description

fix inaccurate metrics description

---

arangod/IResearch/IResearchAnalyzerFeature.cpp

Move adding aql functions from start phase to prepare phase

[BTS-1766] Fix data race in search init

---

js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/addAnalyzer/forms/WildcardConfig.tsx

FE-425: fix ngramSize input type for wildcard analyzer

---

CONTRIBUTING.md

Clean up outdated documentation

clean up some outdated documentation

---

arangod/Aql/ExecutionBlockImpl.tpp

https://arangodb.atlassian.net/browse/BTS-1778
Fix TSan errors from BTS-1778

fix TSan errors from BTS-1778

---

.circleci/base_config.yml

Reduce circleci workspace size by omitting unnecessary js stuff.

Reduce circleci workspace size

---

js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/addAnalyzer/AddAnalyzerModal.tsx
js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/listAnalyzers/AnalyzersTable.tsx
js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/useReinitializeForm.ts

FE=431: odd behaviour in analyzer json view

---

js/apps/system/_admin/aardvark/APP/frontend/js/arango/arango.js
js/apps/system/_admin/aardvark/APP/frontend/js/views/infoView.js

FE-430: don't disable navigation bar on info tab

---

js/common/modules/@arangodb/foxx/store.js

Fixes [BTS-1801](https://arangodb.atlassian.net/browse/BTS-1801), the `shell-fishbowl-replacement.js` suite
See devel PR https://github.com/arangodb/arangodb/pull/20672
[BTS-1801]: https://arangodb.atlassian.net/browse/BTS-1801?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fixing Prerelease Incompatibility

---

client-tools/Dump/DumpFeature.cpp

arangodump: Set all parallel dump versions

---

tests/js/client/shell/api/analyzer.js

Update iresearch 3rdParty to include rename of multi_delimiter parameter from delimiter to delimiters

update iresearch and adjusted test to multi_delimiter change

---

.git-blame-ignore-revs

Add .git-blame-ignore-revs file as suggested by @MBkkt

add .git-blame-ignore-revs file

---

.github/PULL_REQUEST_TEMPLATE.md

Enterprise companion PR: https://github.com/arangodb/enterprise/pull/1460
Move PULL_REQUEST_TEMPLATE.md into subdirectory and update version numbers of stable branches in it.

move PULL_REQUEST_TEMPLATE.md to .github folder

---

client-tools/Shell/V8ClientConnection.cpp

Remove unnecessary to dependency to Boost header file, as Boost is not used in that file at all.

remove unneeded dependency to boost

---

js/client/modules/@arangodb/testutils/process-utils.js

backport of https://github.com/arangodb/arangodb/pull/20715

Feature 3.12/capture dump imp via logfile

---

js/client/modules/@arangodb/testutils/process-utils.js

backport of https://github.com/arangodb/arangodb/pull/20715

make arangodump/restore write logfies, so we can report errors. (#20715)

---

.circleci/base_config.yml

backport of https://github.com/arangodb/arangodb/pull/20720

turn of python line buffering in circle ci (#20720)

---

tests/js/client/recovery/big-transaction-durability.js

*Test only fix. In the test file fixed here we are on purpose doing a long-running operation on the server. If the server is built with sanitizer options the operation is even slower, which gets it close to the default timeout used on arangosh during tests. Sometimes the test then turns red because it get's into timeout. In order to avoid the situation for this specific test we increase the timeout by a factor of 4 on the client side.*

[EF-57] Timeout big-transaction-durability.js with sanitizer

---

lib/Basics/system-functions.cpp
lib/Basics/system-functions.h

Remove now-unused code (memrchr overload for system that don't support it).

remove now-unused code

---

js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/addAnalyzer/AddAnalyzerModal.tsx
js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/addAnalyzer/forms/MinHashConfig.tsx

fix minhash analyzer creation, also remove unecessary init

FE-438: fix minhash analyzer

---

js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/addAnalyzer/AddAnalyzerModal.tsx
js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/addAnalyzer/forms/MinHashConfig.tsx

backport for https://github.com/arangodb/arangodb/pull/20745

bug-fix-3.12/FE-438: fix minhash analyzer

---

lib/Basics/Utf8Helper.h

Remove an outdated and unused forward declaration from a header file

remove an outdated and unused forward declaration

---

arangod/Aql/ExecutionPlan.cpp

improve ExecutionPlan::show()
* fix a potential crash in the stringification of IndexNodes in case the IndexNode did not have a lookup condition (e.g. in case of a full index scan). the condition part was previously dereferenced unconditionally. this was not a problem in any released versions, as ExecutionPlan::show() is only compiled in maintainer mode and used for internal debugging.
* extended output by including filter conditions of EnumerateCollectionNode and IndexNode types, and by displaying the sort conditions of SortNodes

improve ExecutionPlan::show()

---

js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/useReinitializeForm.ts

backport for https://github.com/arangodb/arangodb/pull/20758

bug-fix-3.12/FE-440: fix properties initilization in analyzer form

---

arangod/RestHandler/RestReplicationHandler.cpp
arangod/VocBase/LogicalCollection.cpp
arangod/VocBase/LogicalCollection.h
js/client/modules/@arangodb/testsuites/dump.js
tests/js/server/dump/dump-multiple.js
tests/js/server/dump/dump-teardown-multiple.js
tests/js/server/dump/dump-test.inc

backport of https://github.com/arangodb/arangodb/pull/20760
enterprise companion PR: https://github.com/arangodb/enterprise/pull/1464

[3.11] Repair dump/restore tests

---

arangod/RestHandler/RestReplicationHandler.cpp
arangod/VocBase/LogicalCollection.cpp
arangod/VocBase/LogicalCollection.h
js/client/modules/@arangodb/testsuites/dump.js
tests/js/server/dump/dump-multiple.js
tests/js/server/dump/dump-teardown-multiple.js
tests/js/server/dump/dump-test.inc

backport of https://github.com/arangodb/arangodb/pull/20760
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/1465

[3.10] Repair dump/restore tests

---

LICENSES-OTHER-COMPONENTS.md

Rectify some outdated license information for third party libraries

rectify some 3rd party license information

---

arangod/VocBase/vocbase.cpp
js/client/modules/@arangodb/testutils/instance.js
js/client/modules/@arangodb/testutils/process-utils.js
js/client/modules/@arangodb/testutils/testing.js
tests/test-definitions.txt

To launch locally, use:
`./scripts/unittest rta_makedata --forceOneShard`

add oneshard tests

---

arangod/RestServer/ServerFeature.cpp
arangod/RocksDBEngine/RocksDBEngine.cpp
tests/js/client/shell/shell-verify-sst-noncluster.js

Fix .sst file verification file path handling, add more diagnostic output, and add a test.

Fix filename handling in offline .sst file verification

---

tests/Aql/Executor/AsyncExecutorTest.cpp

Remove an incorrect assertion that causes spurious test failures

---

tests/js/client/restart/test-restart-replication2-syncer-thread-off.js

Sometimes the cluster restart tests were failing with the following error:
``` 
[FAILED]  tests/js/client/restart/test-restart-replication2-syncer-thread-off.js
"testRestartReplicationAndCreate" failed: ArangoError: executing createSystemCollectionsAndIndices (creates all system collections including their indices) failed: the number of current DB-Servers is lower than the requested replicationFactor/writeConcern
at ArangoDatabase._createDatabase (/root/project/js/client/modules/@arangodb/arango-database.js:1101:11)
at Object.testRestartReplicationAndCreate (tests/js/client/restart/test-restart-replication2-syncer-thread-off.js:133:10)
at tests/js/client/restart/test-restart-replication2-syncer-thread-off.js:175:9
..    at broadcastInstance.run …
```

try to fix restart test

---

CHANGELOG
arangod/Cluster/Maintenance.cpp

First compute the shard map outside of the loop. Otherwise we end up with a quadratic algorithm.
Furthermore, while I'm at it, I replaced some adhoc velocypack with some proper c++ data structure.

Maintenance Speedup + Small Refactoring

---

CHANGELOG
arangod/Cluster/ClusterInfo.cpp

3.11.8 port of https://github.com/arangodb/arangodb/pull/20852

Bug fix 3.11.8/thread detach get responsible server

---

arangod/Agency/Supervision.cpp

Backport of https://github.com/arangodb/arangodb/pull/20891
Fix potential "bad optional access" in the supervision.

fix potential "bad optional access" in the supervision

---

arangod/Cluster/HeartbeatThread.cpp
tests/js/client/load-balancing/load-balancing-async-auth-cluster.js
tests/js/client/load-balancing/load-balancing-async-noauth-cluster.js
tests/js/client/load-balancing/load-balancing-cursor-auth-cluster.js
tests/js/client/load-balancing/load-balancing-cursor-noauth-cluster.js
tests/js/client/load-balancing/load-balancing-tasks-auth-cluster.js
tests/js/client/load-balancing/load-balancing-tasks-noauth-cluster.js
tests/js/client/load-balancing/load-balancing-transactions-auth-cluster.js
tests/js/client/load-balancing/load-balancing-transactions-noauth-cluster.js

Add code comments for partially redundant code, and for `wait` calls in tests.

add code comments

---

arangod/Cluster/ClusterInfo.cpp
arangod/Cluster/ClusterInfo.h
arangod/Network/Utils.cpp
lib/Basics/ReadLocker.h

Add more information in error messages about getLeader(s)ForShard.

Improved error messages returned by getLeader(s)ForShard

---

arangod/Cluster/ClusterMethods.cpp

Enterprise companion PR: https://github.com/arangodb/enterprise/pull/1483
Improve debug logging for hot backup locking.
This PR adds log messages for some cases, and also fixes the mentioning of "db servers" in log messages when in fact they are about coordinators.

improve debug logging for hot backup locking

---

arangod/RestHandler/RestIndexHandler.cpp

make latest indexes visible when calling GET /_api/index?withHidden=true.
we need to wait here for the latest index information being present in the agency cache. if we don't wait, we risk not seeing a just-created index if the local agency cache has not fully caught up, and the supervision declares the just-created index ready.
This fixes spurious test errors such as 
```
=== shell_client_3 ===
* Test "shell_client_3"
[FAILED]  tests/js/client/shell/shell-index.js
"testIndexProgressIsReported" failed: Error: at assertion #31: [ { "fields" : [ "_key" ], "id" : "c0l/0", "name" : "primary", "selectivityEstimate" : 1, "sparse" : false, "type" : "primary", "unique" : true } ]: (1) is not equal to (2)
(Error
at Object.testIndexProgressIsReported (tests/js/client/shell/shell-index.js:98:9)
at …
```

make latest indexes visible

---

tests/js/client/recovery/check-warnings-exitzero.js
tests/js/client/shell/shell-arango-secure-installation-noncluster.js
tests/js/server/recovery/crash-handler-assert-noinstr.js
tests/js/server/recovery/crash-handler-terminate-active-noinstr.js
tests/js/server/recovery/crash-handler-terminate-noinstr.js

remove code from tests that checks for Linux platform. these checks are obsolete in devel

remove code from tests that checks for Linux platform

---

arangod/Cluster/ClusterInfo.cpp

Include the shard name in log message. This allows for easier debugging.

Include the shard name in log message. This allows for easier debugging.

---

CHANGELOG
arangod/Aql/ExecutionBlockImpl.tpp
arangod/Aql/SkipResult.cpp
arangod/Aql/SkipResult.h
js/common/modules/@arangodb/test-generators/subquery-chaos-test.js
tests/js/server/aql/aql-subquery-chaos-nightly.js

Backport of https://github.com/arangodb/arangodb/pull/20992

[3.11] [BTS-1813] Adjust SubqueryEnd depth offset

---

arangod/Transaction/Methods.cpp

Backport of https://github.com/arangodb/arangodb/pull/20996
Move resolution of replication callback to high prio lane
// use a HIGH priority lane to execute the callback when the
// response arrives. we must not skip the scheduler entirely here
// because the callback may execute an intermediate commit in
// RocksDB or carry out agency communication in case a follower
// needs to be dropped. the HIGH priority is justified here
// because the callback must make progress: the callback can
// unblock other block threads on the leader that synchronously
// wait for this future to be resolved.

move resolution of replication callback to high prio lane

---

CHANGELOG

CHANGELOG-only changes: add CHANGELOG entries for the most recent changes in 3.11.

add CHANGELOG entries for most recent changes

---

LICENSES-OTHER-COMPONENTS.md

This is just changing a file listing the licenses of software we use.
We add glibc.

Adjust licenses other components file

---

js/client/modules/@arangodb/testutils/san-file-handler.js

Currently the same sanitizer reports my be processed multiple times and therefore also end up multiple times in the testfailures.txt. This PR fixes that.

Don't process same sanitizer report twice

---

js/apps/system/_admin/aardvark/APP/react/src/views/query/QueryViewWrap.tsx

FE-452: fix query UI height when enterprise expiry message is visible

---

.circleci/config.yml

At the moment CircleCI has no good way to see the parameter values that have been specified for a pipeline. This PR adds a simple step that prints the known CircleCI parameters with their respective values

Print pipeline parameter values

---

js/common/modules/@arangodb/aql/explainer.js

Fix a potential exception in query plan explainer, in case parallel traversals are used.

fix a potential exception in query plan explainer

---

arangod/Replication/DatabaseInitialSyncer.cpp

Fix another usage of JobSynchronizer, reported by TSan: https://circleci.com/api/v1.1/project/github/arangodb/arangodb/2004682/output/103/0?file=true&allocation-id=666b95c3cdc99f103f5e318a-0-build%2FABCDEFGH

fix another usage of JobSynchronizer

---

arangod/RestServer/LanguageCheckFeature.cpp
lib/Basics/Utf8Helper.cpp
lib/Basics/Utf8Helper.h
tests/RestServer/LanguageFeatureTest.cpp

Fix bug in LanguageFeature for C.UTF8 locale 

---

.circleci/base_config.yml
scripts/docker/build/linux/Dockerfile.arm64
scripts/docker/build/linux/Dockerfile.x86-64

Add netstat to build container: required for testing.

Add netstat to build container

---

CONTRIBUTING.md

Updated CONTRIBUTING.md with CLA.

---

arangod/RestServer/DatabaseFeature.cpp

This can happen when we abort the startup due to some issue.

Make sure we delete created databases in case of exception

---

CHANGELOG
arangod/Aql/Aggregator.cpp
tests/js/server/aql/aql-optimizer-collect-aggregate.js

Backport of https://github.com/arangodb/arangodb/pull/21092

[3.11] [BTS-1909] Fix cluster unique aggregation

---

arangod/Aql/AqlValue.cpp

Use `std::bit_cast<T>` instead of memcpying the data into T.

use std::bit_cast instead of memcpy

---

js/client/modules/@arangodb/testutils/crash-utils.js
lib/CrashHandler/CrashHandler.cpp

Fix some quirks in testing.js coredump location, and print working directories for easier debugging if coredumps aren't found by testing.js.

Bug fix/fix testing coredump location

---

arangod/Aql/IndexHint.cpp

Simplify IndexHint setup code.

simplify setup of IndexHint

---

arangod/Cluster/Utils/EvenDistribution.cpp
arangod/RocksDBEngine/RocksDBCollection.cpp
arangod/RocksDBEngine/RocksDBPrimaryIndex.cpp

Remove crash handler from code parts that do not need it

remove crash handler from unrelated code

---

arangod/Aql/ExecutionPlan.cpp
arangod/Aql/ExecutionPlan.h
arangod/Aql/Optimizer.cpp
arangod/Aql/Optimizer.h
arangod/Aql/Query.cpp

Move code that checks for index hints in an execution plan from Optimizer.cpp into ExecutionPlan.cpp.

small refactoring PR for index hints

---

arangod/Aql/IndexHint.cpp
tests/js/client/aql/aql-index-hints.js

Fix an issue when multiple index hints were specified.

fix an issue when multiple index hints were specified for a level

---

CHANGELOG
arangod/Agency/MoveShard.cpp
tests/Agency/MoveShardTest.cpp
tests/js/client/resilience/move/moving-shards-cluster.inc

Forward Port of https://github.com/arangodb/arangodb/pull/21137

[devel] Fix a nullptr access, when a MoveShard is aborted for a dropped

---

arangod/Aql/QueryProfile.cpp
arangod/RestServer/TtlFeature.cpp
arangod/RocksDBEngine/Methods/RocksDBSstFileMethods.cpp
arangod/RocksDBEngine/RocksDBPrimaryIndex.cpp
arangod/RocksDBEngine/RocksDBSortedRowsStorageContext.cpp
arangod/Utils/ExecContext.cpp
arangod/VocBase/Methods/Queries.cpp
tests/js/client/shell/test-kill-queries.js

Various small refactorings pulled out of other PRs to make them smaller and more focused.

small refactorings

---

tests/js/client/aql/aql-index-hints.js

Fix flaky test for traversal index hints by giving each index a unique selectivity.

fix flaky traversal hint test

---

arangod/Scheduler/SchedulerFeature.cpp

Docs: Fix --server.scheduler introduced in version

---

js/common/modules/@arangodb/aql/explainer.js
tests/js/client/shell/shell-debug-dump.js

* Initial commit
* Fix jslint
* tests are in progess
* test is ready
* make js lint happy
* Update tests/js/client/shell/shell-debug-dump.js
---------

Backport of Improvements for explainer.js 

---

arangod/FeaturePhases/BasicFeaturePhaseServer.cpp
arangod/RestServer/arangod.h
arangod/RocksDBEngine/RocksDBChecksumEnv.h
arangod/arangoserver.cmake
lib/ApplicationFeatures/ApplicationServer.h
lib/Basics/ArangoGlobalContext.cpp
lib/Logger/Logger.cpp

Remove more windows remnants

---

3rdParty/README_maintainers.md

Update some internal documentation in README_maintainers.md.

update information in README_maintainers.md

---

client-tools/Import/SenderThread.cpp

Response to https://github.com/arangodb/arangodb/pull/21189/files#r1687767356 .

Make locking less coarse.

---

tests/js/client/shell/shell-abort-replication-cluster.js
tests/js/server/dump/dump-test.inc

be more patient with coverage binaries

---

tests/js/client/aql/aql-complex.js
tests/js/client/dump/dump-test.inc
tests/js/client/shell/multi/shell-admin-log.js
tests/js/client/shell/shell-abort-replication-cluster.js

increase timeout for coverage runs, better error messages.

be more patient with instrumented tests

---

tests/js/server/dump/dump-test.inc

backport improved error messages

Feature 3.11/better error messages

---

CHANGELOG
arangod/Aql/AqlValue.cpp
arangod/Aql/AqlValue.h
arangod/Aql/Ast.cpp
arangod/RestHandler/RestAdminClusterHandler.cpp
arangod/RestHandler/RestAdminClusterHandler.h
arangod/RocksDBEngine/RocksDBComparator.cpp
arangod/RocksDBEngine/RocksDBComparator.h
arangod/RocksDBEngine/RocksDBEngine.cpp
arangod/RocksDBEngine/RocksDBEngine.h
arangod/RocksDBEngine/RocksDBOptionsProvider.cpp
arangod/RocksDBEngine/RocksDBOptionsProvider.h
arangod/RocksDBEngine/RocksDBVPackIndex.cpp
arangod/StorageEngine/CMakeLists.txt
arangod/StorageEngine/VPackSortMigration.cpp
arangod/StorageEngine/VPackSortMigration.h
js/common/bootstrap/errors.js
lib/Basics/VelocyPackHelper.cpp
lib/Basics/VelocyPackHelper.h
lib/Basics/errors.dat
tests/Aql/AqlValueCompare.cpp
tests/Basics/VelocyPackHelperTest.cpp
tests/CMakeLists.txt
tests/RocksDBEngine/KeyTest.cpp
tests/js/client/server_parameters/legacy-sorting-cluster.js
tests/js/client/server_parameters/legacy-sorting-noncluster.js

Hotfix 3.11.7 VPack number ordering

---

lib/Async/Registry/thread_registry.h
tests/Basics/VelocyPackHelperCompareRandomTest.cpp

Fix heap-use-after-free when garbage collecting.

Fix heap-use-after-free when garbage collecting.

---

js/client/modules/@arangodb/testutils/crash-utils.js
js/client/modules/@arangodb/testutils/process-utils.js

some oversight while backporting test infra

fix two backport issues in test infra

---

arangod/Aql/QueryInfoLoggerFeature.cpp

The QueryInfoLoggerThread can schedule a delayed task in the scheduler but did not make sure that this task is cancelled when shutting down. Since the scheduler is stopped later, this could cause the task to be executed when the  QueryInfoLoggerThread was already destroyed.
The QueryInfoLoggerFeature was only introduced a month ago, so no backports necessary

Fix potential data race in QueryInfoLoggerThread shutdown

---

tests/test-definitions.txt

Merge some more CircleCI test jobs.
The tests are executed correctly in all configuration, but the reporting is broken ATM - each test-suite is only contained once in the UNITTEST_RESULTS.json and also the XML (the suffix is not processed correctly).

Group some more tests

---

arangod/Aql/ExecutionNode/JoinNode.cpp
arangod/Aql/ExecutionNode/JoinNode.h
arangod/Aql/Executor/JoinExecutor.cpp
arangod/Aql/Executor/JoinExecutor.h
arangod/Aql/IndexJoin/TwoIndicesUniqueMergeJoin.h
arangod/Aql/IndexJoinStrategy.cpp
arangod/Aql/IndexJoinStrategy.h
arangod/Aql/Optimizer/Rule/OptimizerRulesJoin.cpp
arangod/ClusterEngine/ClusterIndex.cpp
arangod/ClusterEngine/ClusterIndex.h
arangod/Indexes/Index.h
arangod/RocksDBEngine/RocksDBPrimaryIndex.cpp
arangod/RocksDBEngine/RocksDBPrimaryIndex.h
arangod/RocksDBEngine/RocksDBVPackIndex.cpp
arangod/RocksDBEngine/RocksDBVPackIndex.h
tests/js/client/aql/aql-index-join.js

Bugfix for https://github.com/arangodb/arangodb/issues/21243. For a detailed explanation and workaround see [here](https://github.com/arangodb/arangodb/issues/21243#issuecomment-2303966376).

Join with Unique Index Prefix Fix

---

arangod/Cluster/ClusterInfo.cpp
tests/js/client/shell/shell-shard-groups-cluster-info.js

Remove a shard from a collection group leaders shard list when dropped.

Fix ClusterInfo Shard Groups

---

utils/README.md

Documentation  for @mpoeter s llvm symbolizer

add documentation

---

3rdParty/README_maintainers.md
CHANGELOG

This just finishes some paperwork for a change which was already
done in another PR. Namely, CHANGELOG and a note in
3rdParty/README_maintainers.md
Original PR: https://github.com/arangodb/arangodb/pull/21273
- [*] :hankey: Bugfix (paperwork)

Paperwork for RocksDB fix

---

js/client/modules/@arangodb/testsuites/rta_makedata.js
js/client/modules/@arangodb/testutils/agency.js
js/client/modules/@arangodb/testutils/instance-manager.js
js/client/modules/@arangodb/testutils/instance.js

during rta tests to an in place restart to simulate an upgrade action

attempt to restart in place

---

.circleci/base_config.yml
.circleci/config.yml

enable the UI tests in circle-ci by default

enable ui tests by default

---

js/client/modules/@arangodb/testsuites/rta_makedata.js
js/client/modules/@arangodb/testutils/instance-manager.js

forward port error handling so we have proper testresults. Switch sequence for more potential errors.

add handling for failures so we get propper result

---

tests/js/client/aql/aql-object-enumeration.js

Adding more tests with limit for enumerate object.

EnumerateObject + Limit Tests

---

js/client/modules/@arangodb/testsuites/dump.js
js/client/modules/@arangodb/testutils/client-tools.js
tests/js/client/dump/dump-check-dump-files-compressed.js
tests/test-definitions.txt

we were missing tests about dump/restore for vpack on disk representation.

QA-561: Feature/test vpack dumping

---

js/client/modules/@arangodb/testsuites/arangosh.js

backport of https://github.com/arangodb/arangodb/pull/21343 ; the referenced Bug in arangosh didn't make it to 3.11 yet. However, we should have this test fixed.

fix detection of exit code tests (#21343)

---

CHANGELOG
arangod/RestServer/FileDescriptorsFeature.cpp
arangod/RestServer/FileDescriptorsFeature.h
arangod/Utils/SupportInfoBuilder.cpp

Add file descriptor data to telemetrics

---

.circleci/base_config.yml

ease turnaround by completely disabling rta-makedata for UI tests

add param to disable makedata

---

.circleci/config.yml
CHANGELOG
arangod/RestServer/FileDescriptorsFeature.cpp
arangod/RestServer/FileDescriptorsFeature.h
arangod/RestServer/TtlFeature.cpp
arangod/Utils/SupportInfoBuilder.cpp

*Hot fix release for HPE to include file descriptors in exported api and fix TTL deletion errors in the cluster*

hotfix 3.12.2.2

---

arangod/Aql/Optimizer/Rule/OptimizerRulePushDownLateMaterialization.cpp
tests/js/client/aql/aql-index-batch-materialize.js

Do not push past calculation if the amount of projections would exceed the max allowed projections.

Push Down Materialize + Max Projections

---

.circleci/base_config.yml
.circleci/config.yml
.circleci/generate_config.py
js/client/modules/@arangodb/testutils/san-file-handler.js

ui tests would not set tsan environment hence instrumented runs will fail for missing configuration like blacklist.

set san environment for rta as well

---

js/client/modules/@arangodb/test-helper.js
js/client/modules/@arangodb/testutils/client-tools.js
tests/js/client/communication/test-communication-cluster.js

Make testresults better observeable by adding logging.  We use the filename for filtering cluster only operations.

Bug fix/improve test debuggeability

---

arangod/Cluster/ClusterFeature.cpp

Has been changed in the v3.12 web interface

Docs: Adjust capitalization of UI elements in startup option description

---

tests/js/client/communication/test-cluster-multi-shard-transaction.js

when running instrumented, be more patient.

more patient with instrumentation

---

CHANGELOG
arangod/RestHandler/RestDumpHandler.cpp
arangod/RocksDBEngine/RocksDBDumpContext.cpp
tests/test-definitions.txt

Fix how is dumped data sanitized in VPack mode.

Fix sanitization of dumped data

---

arangod/Agency/State.cpp

Add an production assertion that there is no out of bounds access to the log.
https://arangodb.atlassian.net/browse/BTS-1928

Agency Potential Out of Bounds Access

---

tests/js/client/communication/test-cluster-multi-shard-transaction.js
tests/js/client/communication/test-communication-cluster.js
tests/js/client/communication/test-kill.js

Backport changes to the communication tests

be more patient on windows too

---

.circleci/base_config.yml
js/client/modules/@arangodb/testutils/client-tools.js

better messaging of state - try to catch missing waitpid

---

tests/test-definitions.txt

Add missing suffixes to tests to differ between executions with/without VPack

Add suffix to dump tests with vpack

---

js/client/modules/@arangodb/testsuites/recovery_cluster.js

make sure we don't clean up if the SUT aborts

we mustn't clean up if we bail out of here by assert

---

js/client/modules/@arangodb/testsuites/recovery.js

Forward port of https://github.com/arangodb/arangodb/pull/21383 -  we must expect throws from startup.

if the startup throws, we need to catch and handle this.

---

tests/test-definitions.txt

increase size of SUT

---

js/client/modules/@arangodb/testutils/agency.js

backport of  https://github.com/arangodb/arangodb/pull/21399

Feature 3.11/fix agency alive check trigger

---

lib/Futures/include/Futures/Future.h
tests/Futures/FutureTest.cpp

Was missing, therefore some dependent stacktraces of the async registry were shown as two disconnected stacktraces.

Set missing waiter for inner function of future continuations

---

scripts/test/arangosh.py
scripts/test/testing_runner.py

a previous commit would break the logic.

fix logging string

---

js/client/modules/@arangodb/testutils/client-tools.js
tests/js/client/load-balancing/load-balancing-foxx-installation-noauth-cluster.js
tests/js/client/restart/test-soft-shutdown-cluster.js

longer timeouts for several tests in coverage.

allow longer timeouts for coverage runs

---

js/client/modules/@arangodb/testsuites/rta_makedata.js
js/client/modules/@arangodb/testutils/instance-manager.js
js/client/modules/@arangodb/testutils/instance.js
js/client/modules/@arangodb/testutils/result-processing.js
js/client/modules/@arangodb/testutils/testrunners.js

backport of 
https://github.com/arangodb/arangodb/pull/21412#event-15182057863

QA-575: unwrap line breaks when printing out errors in testfailures.txt for better readability

---

scripts/test/launch_handler.py
scripts/test/overload_thread.py
scripts/test/site_config.py
scripts/test/tools/killall.py

Implement logging of processes and threads in case of the system going into overload, forward port of
https://github.com/arangodb/release-test-automation/pull/521

QA-577: implement process + thread logging if the system goes into overload.

---

js/client/modules/@arangodb/testsuites/rta_makedata.js
js/client/modules/@arangodb/testutils/client-tools.js
js/client/modules/@arangodb/testutils/testrunner.js

backport of https://github.com/arangodb/arangodb/pull/21432

Feature 3.11/rta abort without cleanup

---

js/client/modules/@arangodb/testutils/agency.js
tests/test-definitions.txt

- more time for the agency to come alive
- fix names of tests
- more heap size

Bug fix/more time for agency

---

js/client/modules/@arangodb/testutils/client-tools.js
tests/js/client/load-balancing/load-balancing-foxx-installation-noauth-cluster.js
tests/test-definitions.txt

for coverage runs give more timeouts & resources

give more resources, prolongue timeouts

---

CHANGELOG
arangod/StorageEngine/TransactionState.cpp

Fix blockage occurring with MultipleRemoteModification

---

CHANGELOG
arangod/StorageEngine/TransactionState.h

Fix deadlock. For details, see https://github.com/arangodb/arangodb/pull/21440.
- [*] Backport for 3.11: this is it
- [*] GitHub issue / Jira ticket: https://github.com/arangodb/arangodb/pull/21440

Fix blockage occurring with MultipleRemoteModification [BTS-2012]

---

CHANGELOG

BTS-2018 UPDATE CHANGELOG

---

.circleci/base_config.yml
.circleci/config.yml

Adjust to new build image and CircleCI requirements.

Enable build image for vector index

---

tests/js/client/communication/test-communication-cluster.js
tests/js/client/communication/test-kill.js
tests/js/server/dump/dump-test.inc

Related to https://github.com/arangodb/arangodb/pull/21442 - prolongue timeouts.

Bug fix 3.11/longer coverage timeouts

---

arangod/Aql/AqlFunctionFeature.cpp
arangod/Aql/AqlFunctionFeature.h

See devel PR https://github.com/arangodb/arangodb/pull/21457

Fix tsan data race in 3.11

---

arangod/Aql/AqlFunctionFeature.cpp
arangod/IResearch/ApplicationServerHelper.cpp
arangod/IResearch/ApplicationServerHelper.h

See https://github.com/arangodb/arangodb/pull/21461

3.11 Additional fix to aql functions data race

---

js/client/modules/@arangodb/testutils/client-tools.js

Bug fix 3.11/no cleanup on failure

---

arangod/Agency/AddFollower.cpp
arangod/Agency/FailedLeader.cpp
arangod/Agency/MoveShard.cpp
arangod/Agency/RemoveFollower.cpp

Add preconditions that all clone shards still exist to various agency jobs.

[BTS-2019] Missing Preconditions

---

arangod/Agency/AddFollower.cpp
arangod/Agency/FailedFollower.cpp
arangod/Agency/FailedLeader.cpp
arangod/Agency/Job.cpp
arangod/Agency/Job.h
arangod/Agency/MoveShard.cpp
arangod/Agency/RemoveFollower.cpp

Backport of https://github.com/arangodb/arangodb/pull/21465

[3.11][BTS-2019] Missing Preconditions

---

js/client/modules/@arangodb/testutils/crash-utils.js

attempt to locate the minidump

try to locate the minidump insite of the instance roots tmp folder

---

js/client/modules/@arangodb/testutils/client-tools.js
js/client/modules/@arangodb/testutils/test-utils.js
scripts/test/async_client.py
tests/js/client/aql/aql-subquery-chaos-nightly.js
tests/js/client/communication/test-communication-cluster.js
tests/js/client/communication/test-kill.js
tests/js/client/dump/dump-test.inc
tests/js/client/load-balancing/load-balancing-foxx-installation-noauth-cluster.js
tests/js/client/recovery/search/view-search-alias-populate-remove.js
tests/js/client/restart/test-restart-cluster.js
tests/js/client/restart/test-soft-shutdown-cluster.js
tests/test-definitions.txt

send SIG_BUS to get coredump and crash.

send abort, de-silence long running tests

---

arangod/Aql/Optimizer/Rule/OptimizerRulePushDownLateMaterialization.cpp
tests/js/client/aql/aql-index-batch-materialize.js

Implements a special case improvement for pushing down materialization even further down.

Push down materialization in a unique index scenario

---

js/client/modules/@arangodb/testutils/crash-utils.js

continue effort to find self written minidump

be more verbose, fix check

---

arangod/Cluster/ClusterInfo.cpp

Fix heap-use-after-free in IResearchViewCoordinatorTest, see e.g. [here](https://jenkins.arangodb.biz/job/arangodb-ANY-linux-san.x86-64/2548/EDITION=enterprise,SAN_MODE=AULSan,STORAGE_ENGINE=rocksdb,TEST_SUITE=single,limit=linux&&test&&cloud&&x86-64/artifact/testfailures.txt)
A callback accesses members of the SyncerThread when it was already destoryed, fixed by using a shared pointer.

Fix use after free in cluster info

---

arangod/Agency/Supervision.cpp

This fixes a small case which was overlooked and found by asan tests.
- [*] Tests
- [*] ASAN/TSAN

Small fix for corner case

---

tests/test-definitions.txt

fix config not to enable this test.

disable if not full

---

tests/js/client/communication/test-kill.js

we expect a certain number of operations to have been executed; prolongue the duration for these to have happened in coverage
forward port of https://github.com/arangodb/arangodb/pull/21499

give instrumented test execution more time to yield more runs

---

arangod/Agency/Supervision.cpp

This fixes a small oversight which can lead to assertion failures.
This has already been fixed in devel in a separate PR.

Small fix for cleanup of finished and failed jobs

---

tests/js/client/communication/test-communication-cluster.js

wait longer here too

---

arangod/Agency/Supervision.cpp

Cleanup:
- **Take out two LOG_DEVELs.**

Remove two unnecessary LOG_DEVEL commands

---

js/common/modules/@arangodb/test-generators/subquery-chaos-test.js
tests/js/client/chaos_subq/aql-subquery-chaos-nightly.js

invoke heap cleanup, fix prints

---

tests/Agency/SupervisionTest.cpp

This fixes some UB in tests, which did not pose problems in normal
runs but which crashed UBSAN runs.

Fix UB in tests

---

js/client/modules/@arangodb/testutils/client-tools.js

backport of https://github.com/arangodb/arangodb/pull/21511

longer timeouts for instrummented communication suite subshells

---

js/common/modules/jsunity.js
js/common/modules/jsunity/jsunity.js

backport of https://github.com/arangodb/arangodb/pull/21520

Feature 3.11/timestamp in failures

---

tests/js/client/communication/test-communication-cluster.js

Partial backport of https://github.com/arangodb/arangodb/pull/21524

disable tests that won't succed in coverage environments.

---

js/common/modules/@arangodb/test-generators/subquery-chaos-test.js
lib/V8/V8PlatformFeature.cpp
lib/V8/v8-utils.cpp
tests/js/client/chaos_subq/aql-subquery-chaos-nightly.js
tests/test-definitions.txt

we should set this flag when forcing a collect so we see the propper log message.

BTS-2045: set the forced collect flag here too, improve test stability

---

arangod/Aql/Aggregator.cpp
tests/js/client/aql/aql-optimizer-collect-aggregate.js

The PUSH aggregator collects all its inputs into an array. 
```
FOR doc IN c COLLECT x = doc.i AGGREGATE y = PUSH(doc.j) RETURN [x, y]
```
Example output
```
[ 
[ 
1, 
[ 
1, 
2, 
5, 
7, 
8, 
9, 
4, 
6, 
10, 
3 
] 
], 
[ 
2, 
[ 
4, 
5, 
9, 
2, 
3, 
8, 
1, 
6, 
7, 
10 
] 
], 
```

Push Aggregator

---

tests/js/client/aql/aql-optimizer-collect-aggregate.js

Fix a test introduced with the push aggregator PR.

Fixing test for PUSH aggregator.

---

tests/js/client/communication/test-kill.js
tests/js/client/shell/shell-index-visibility-nocov-fp.js

backport changes to test, including rename

Bug fix 3.11/backport shell index visibility

---

tests/js/client/aql/vector/aql-vector.js

Add a vector index test case that checks that vector index usage fails with multiple sort attribute

Add additional vector index test case

---

3rdParty/README_maintainers.md
CHANGELOG
js/server/assets/swagger/swagger-initializer.js

Swagger UI: Remove fragment identifiers from request URLs

---

js/client/modules/@arangodb/testutils/client-tools.js

We already had this option, make it the way to handle things everywhere.

make sure that the client request timeout is handled via the central option

---

CHANGELOG
js/apps/system/_admin/aardvark/APP/foxxes.js

[3.11] [BTS-2074] Fix load balancing Foxx test

---

js/client/modules/@arangodb/testutils/filter_gdb_stacks.json

backport of https://github.com/arangodb/arangodb/pull/21584

more idle stacks (#21584)

---

js/server/assets/swagger/index.css

Web interface: Make Try out button in Swagger UI stand out more (#21585)

---

tests/js/client/shell/shell-admin-cluster-rebalance.js

more time for coverage

---

tests/js/client/shell/shell-replication-auto-repair-cluster.js
tests/js/common/shell/shell-index.js

Bug fix/stretch timout coverage

---

tests/js/client/load-balancing/load-balancing-foxx-installation-noauth-cluster.js

also assert that we may find a string...

also assert that we don't have that string

---

CHANGELOG
arangod/Scheduler/SchedulerFeature.cpp

This addresses https://arangodb.atlassian.net/browse/BTS-2077
- [*] Original PR: https://github.com/arangodb/arangodb/pull/21598

Deactivate cluster overwhelm on agents [BTS-2077]

---

js/apps/system/_admin/aardvark/APP/foxxes.js
tests/js/client/load-balancing/load-balancing-foxx-installation-noauth-cluster.js

This is a backport of #21596 for 3.11.

[BTS-2074] [3.11] Forward response body as-is

---

client-tools/Shell/V8ShellFeature.cpp
client-tools/Shell/v8-deadline.cpp
js/client/modules/@arangodb/test-helper.js
js/client/modules/@arangodb/testsuites/rta_makedata.js
js/client/modules/@arangodb/testutils/agency.js
js/client/modules/@arangodb/testutils/testrunners.js

fix timeout

---

client-tools/Shell/V8ShellFeature.cpp
client-tools/Shell/V8ShellFeature.h
client-tools/Shell/v8-deadline.cpp
js/client/modules/@arangodb/test-helper.js
js/client/modules/@arangodb/testsuites/rta_makedata.js
js/client/modules/@arangodb/testutils/agency.js
js/client/modules/@arangodb/testutils/testrunners.js
lib/V8/v8-deadline.h
lib/V8/v8-no-deadline.cpp

Backport https://github.com/arangodb/arangodb/pull/21601

Feature 3.11/execution deadline cli trigger

---

client-tools/Dump/DumpFeature.cpp
client-tools/Export/ExportFeature.cpp
client-tools/Import/ImportFeature.cpp
lib/Logger/LoggerFeature.cpp

Docs: Improve the descriptions of a few startup options

---

tests/js/client/shell/shell-index-visibility-nocov-fp.js

Forward port test stability change

Bug fix/forward port test precision

---

CHANGELOG
js/apps/system/_admin/aardvark/APP/react/src/views/query/QueryContextProvider.tsx
js/apps/system/_admin/aardvark/APP/react/src/views/query/queryResults/CancelQueryButton.tsx
js/apps/system/_admin/aardvark/APP/react/src/views/query/queryResults/QueryExecuteResult.tsx
js/apps/system/_admin/aardvark/APP/react/src/views/query/queryResults/QueryProfileResult.tsx
js/apps/system/_admin/aardvark/APP/react/src/views/query/queryResults/QueryResultError.tsx
js/apps/system/_admin/aardvark/APP/react/src/views/query/queryResults/QueryResultLoading.tsx
js/apps/system/_admin/aardvark/APP/react/src/views/query/queryResults/QueryResults.tsx
js/apps/system/_admin/aardvark/APP/react/src/views/query/queryResults/RemoveResultButton.tsx
js/apps/system/_admin/aardvark/APP/react/src/views/query/useQueryExecutors.tsx
js/apps/system/_admin/aardvark/APP/react/src/views/query/useQueryResultHandlers.tsx

FE-515 - fix to ensure unique keys to prevent incorrect react reconciliation (Query Editor UI > Query results)

---

tests/js/client/shell/shell-index-visibility-nocov-fp.js

print out the loop count as well

---

CMakeLists.txt

Avoid header files being install by "make install"

do not install headers

---

CHANGELOG
arangod/Indexes/IndexFactory.cpp
tests/js/client/aql/vector/aql-vector-agency-wrong-definition-cluster.js

Fix vector index comparison when optional attributes are absent.

Fix vector index comparison in maintance

---

CHANGELOG
js/apps/system/_admin/aardvark/APP/frontend/js/views/navigationView.js
js/apps/system/_admin/aardvark/APP/frontend/scss/_alert.scss

FE-528: adds diskusage license info to UI

---

scripts/test/arangosh.py

during ci also try to get cgroups v2 memory limit

add cgroups v2 memory limit detection

---

CHANGELOG
js/apps/system/_admin/aardvark/APP/react/src/views/query/editor/QueryEditorPane.tsx

FE-503 - fix losing bind params when resizing query editor

---

js/client/modules/@arangodb/test-helper.js

backport of https://github.com/arangodb/arangodb/pull/21666

if we don't waitpid, we leave zombies. Don't do that.

---

js/client/modules/@arangodb/testutils/crash-utils.js
scripts/test/test_config.py
tests/js/client/shell/multi/shell-aql-kill.js

(re-)implement option to SIG_ABRT, use it in circle-ci.

circle ci doesn't allow us to attach a GDB. Hence we need to SIG_ABRT processes

---

js/client/modules/@arangodb/testutils/crash-utils.js
scripts/test/test_config.py

backport of https://github.com/arangodb/arangodb/pull/21670

Bug fix 3.11/circle ci dont gdb attach

---

js/apps/system/_admin/aardvark/APP/frontend/js/views/navigationView.js

fixes missing semicolon which leads to CI fail

fix: missing semicolon

---

client-tools/Shell/V8ClientConnection.cpp

backport of https://github.com/arangodb/arangodb/pull/21679

abort fuzzing if we loose the connection to the arangod

---

arangod/GeneralServer/Acceptor.cpp
arangod/GeneralServer/Acceptor.h
arangod/GeneralServer/AcceptorTcp.cpp
arangod/GeneralServer/AcceptorTcp.h
arangod/GeneralServer/AcceptorUnixDomain.cpp
arangod/GeneralServer/AcceptorUnixDomain.h
arangod/GeneralServer/GeneralServer.cpp
arangod/GeneralServer/GeneralServer.h

Backport to https://github.com/arangodb/arangodb/pull/21682

Backport: Fix datarace in tcp acceptor

---

js/client/modules/@arangodb/testsuites/dump.js
tests/js/server/dump/check-foxx.js
tests/js/server/dump/dump-test.inc

backport of https://github.com/arangodb/arangodb/pull/21686

Feature/no subshell arangosh in dump tests (#21686)

---

scripts/test/testing_runner.py

we still might have assert logs where they could be usefull for deciphering line numbers

save binaries if we don't have coredumps 

---

js/client/modules/@arangodb/testutils/san-file-handler.js

if we're not inspecting an instrumentation, also don't add its suppression file to the options.

only set value on the structure if we actually have that instrumentation

---

CHANGELOG
arangod/Aql/ExecutionBlock.cpp
arangod/Aql/ExecutionBlock.h
arangod/Aql/ExecutionBlockImpl.h
arangod/Aql/ExecutionBlockImpl.tpp
arangod/Aql/ExecutionEngine.cpp
scripts/test/arangosh.py
tests/js/client/aql/aql-optimizer-rule-async-prefetch-noncluster-fp.js

Backport of https://github.com/arangodb/arangodb/pull/21709

[3.12.4] Fix crash during async prefetch

---

js/client/modules/@arangodb/testutils/client-tools.js
tests/js/client/aql/vector/aql-vector-agency-wrong-definition-cluster.js
tests/js/client/aql/vector/aql-vector-create-and-remove.js
tests/js/client/aql/vector/aql-vector-full-count.js
tests/js/client/aql/vector/aql-vector-nprobe.js
tests/js/client/aql/vector/aql-vector.js

circle ci ARM is currently known to break faiss. STFU.

disable vector index on ARM for now, faiss is known to be crashy now.

---

.circleci/base_config.yml
.circleci/config.yml
CMakeLists.txt
cmake/frontend/aardvark.cmake
scripts/docker/build/linux/Dockerfile.arm64
scripts/docker/build/linux/Dockerfile.x86-64
scripts/docker/build/linux/tools/install.sh

optionally extract pre packaged node_modules instead of  'yarn install'ing them.

optionally choose pre-packaged node modules

---

.circleci/base_config.yml
.circleci/config.yml
CHANGELOG
arangod/Aql/SharedQueryState.cpp
arangod/Aql/SharedQueryState.h
js/client/modules/@arangodb/testutils/client-tools.js
tests/js/client/aql/vector/aql-vector-create-and-remove.js
tests/js/client/aql/vector/aql-vector-full-count.js
tests/js/client/aql/vector/aql-vector-nprobe.js
tests/js/client/aql/vector/aql-vector.js

*This bug fix deals with the failure to catch the tasks number having being reduced to 0 already*
Backport of https://github.com/arangodb/arangodb/pull/21635

Sleeping barber in SharedQueryState

---

tests/js/client/shell/shell-duplicate-collection-names-cluster.js

Stabilize test for ASAN using larger timeout, take2

---

scripts/test/site_config.py

hide private environment variables from tests

hide credentials from tests

---

CHANGELOG
arangod/Aql/ModificationExecutorHelpers.cpp
lib/Futures/include/Futures/Future.h

*Optimise wait and detach in AQL modification executer helper*

optimise wait and detach

---

.circleci/generate_config.py
arangod/RestServer/arangod.h
client-tools/Shell/arangosh.h
client-tools/Utils/ArangoClient.h
client-tools/VPack/arangovpack.h

more places to disable the ProcessEnvironmentFeature in non-maintainer mode.

Bug fix/fix non maintainer mode

---

js/client/modules/@arangodb/testsuites/dump.js
js/client/modules/@arangodb/testutils/client-tools.js
js/client/modules/@arangodb/testutils/instance.js
tests/test-definitions.txt

launch two clusters so we restore into an empty cluster in dump_multiple

use two different clusters for dump_multiple test

---

scripts/startLocalCluster.sh

*local cluster script with all endpoints and compression*

local cluster to allow external access / compression

---

CHANGELOG
arangod/Utils/SupportInfoBuilder.cpp
tests/js/client/server_parameters/test-telemetrics-true-auth.js
tests/js/common/test-data/telemetry/telemetrySchema.json

Vector index `n_vector` was missing in telemetrics is now added.

Fix vector index missing in telemetrics

---

CHANGELOG
arangod/RocksDBEngine/RocksDBVectorIndex.cpp
js/common/modules/@arangodb/testutils/seededRandom.js
tests/js/client/aql/vector/aql-vector.js

Fix the cosine similarity score returning values greater than 1. This fixes a bug in cosine metrics vector indexes. And it is reccomended for everyone to **rebuild their cosine indexes**.

Fix cosine similarity score

---

README.md

Adjust for CE including the EE features
- https://github.com/arangodb/docs-hugo/pull/681

Update README.md for v3.12.5+

---

arangod/RestHandler/RestAdminServerHandler.cpp
arangod/RestServer/ApiRecordingFeature.cpp
arangod/RestServer/ApiRecordingFeature.h
lib/Logger/LoggerFeature.cpp
tests/js/client/shell/recording.js

This is a push to polish the outlook of the API and AQL recording
feature. We bring more consistency with other parts of the system,
both in the output of the AQL recording API and the memory limits.
- **More consistent output of AQL recording.**
- **Adapt tests to new output.**
- **Round memory limits to KiB, MiB and GiB.**
- [*] :hammer: Refactoring/simplification
- [*] Tests

Polish api/aql recording stuff

---

js/client/modules/@arangodb/testutils/instance-manager.js
tests/js/client/fuzz/http-fuzz-fp.js

see how many ports are used in parts of the fuzzing test

list the used ports all through out the fuzzing

---

tests/js/client/resilience/move/moving-shards-cluster.inc

longer timeouts for coverage
- [ x] :hankey: Bugfix

longer timeouts for coverage

---

tests/js/client/resilience/move/moving-shards-cluster.inc

even longer sleeps for coverage

---

lib/V8/v8-utils.cpp

parameter sequence count still was off.

adjust counters

---

CHANGELOG

bump rocksdb version to fix compaction picker nullptr access.

---

CHANGELOG

Bump iresearch: Fix for address_table memory over-allocation

---

scripts/startLocalCluster.sh

This fixes an accidental change in a debug script.

Revert an accidental change in a debug script

---

client-tools/Shell/RequestFuzzer.cpp
client-tools/Shell/RequestFuzzer.h
client-tools/Shell/V8ClientConnection.cpp
js/client/modules/@arangodb/testutils/instance-manager.js
tests/js/client/fuzz/http-fuzz-fp.js

move lists for fuzzer from c++ -> js

move fuzzing lists over to .js

---

.circleci/config.yml
tests/test-definitions.txt

we see failures in the phase without any deeper info. This PR will preserve this info and add error handling.

as sugested by @Chungjung dump out the github API response and test for errors

---

arangod/Cluster/ClusterMethods.cpp
arangod/Graph/Providers/ClusterProvider.cpp
arangod/RestHandler/RestVocbaseBaseHandler.cpp
arangod/RestHandler/RestVocbaseBaseHandler.h

Fix initialization order issue found in latest [nightly](https://app.circleci.com/pipelines/github/arangodb/arangodb/38012).

Fix initialization order fiasco

---

js/client/modules/@arangodb/testutils/instance-manager.js
js/client/modules/@arangodb/testutils/instance.js

re-fix the subprocess env instance info structure

QA-666: fix generating of subprocess env with the available instance data
