arangod/Pregel/Conductor/Conductor.cpp, arangod/Pregel/PregelFeature.cpp, arangod/Pregel/PregelFeature.h
To address a race condition between a client knowing an execution number for a pregel run and this execution number appearing in the Pregel status collection ready to query, create the entry in the status collection before the execution number is communicated to the client.
=> [GORDO-1643] Create Pregel Status Collection entry on creation

client-tools/Shell/V8ClientConnection.cpp, tests/js/client/server_parameters/database-password-noncluster.js
Backport of https://github.com/arangodb/arangodb/pull/18997
Keep original JWT secret in arangosh when using `arango.reconnect(...)` when not overriding the JWT.
This restores behavior that used to work in 3.9.
=> keep jwt secret when using `arango.reconnect(...)`

CMakePresets.json
Add `CMakePresets.json` to the 3.10 branch to ease the use of tooling to build documentation and CI in the future.
This should normally not affect anyone who doesn't use presets. 
It could also be one step towards being able to run CircleCI on the 3.10 branch.
=> CMakePresets.json in 3.10 branch

CHANGELOG, arangod/StorageEngine/TransactionState.cpp, arangod/StorageEngine/TransactionState.h, tests/js/client/shell/shell-transaction.js
This race could happen in the cluster when a collection is sharded by a different attribute than `_key` and a document lookup by _key is performed. This requires the lookup to be sent to each shard, since we cannot deduce the shard based on the `_key` value. If this lookup is done as part of a stream transaction, and if the collection has not been declared in the transaction's `read` list, then the collection is added lazily. Previously this would result in a race if multiple shards are located on the same server.
For transactions with `allowDirtyReads` set to true, read collections are always added lazily, which made this race more likely.
=> [BTS-1181] [3.9] Fix data race on the collection list in TransactionState

arangod/StorageEngine/TransactionState.cpp, lib/Basics/DebugRaceController.cpp, lib/Basics/DebugRaceController.h
Fix a possible crash in a failure test, when the race controller is reset unexpectedly early.
This strictly only affects failure test code, which is not part of production executables. It also shouldn't occur when the tests run as expected, without "external" failures.
Previous PRs this is based on:
- https://github.com/arangodb/arangodb/pull/13207
- https://github.com/arangodb/arangodb/pull/16244
=> [BTS-1373] fix error in test code

arangod/Aql/OptimizerRules.cpp, tests/js/server/aql/aql-optimizer-rule-parallelize-gather-cluster.js
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/1272
This reverts commit c112152fbcaa6720c98a5f6bb2b714c1a7967285.
We merged that PR last week as a emergency fix to turn off optimizer rule enhancements in 3.11.
Once the bugfix PRs https://github.com/arangodb/arangodb/pull/18978 and https://github.com/arangodb/arangodb/pull/19001 are merged into 3.11, the optimizer rule can be turned back on.
No ports to other versions are required.
=> Revert "disable `parallelize-gather` optimizer rules for some cases (#18977)"

.circleci/base_config.yml, arangod/Pregel/Conductor/Conductor.cpp, utils/checkLogIds.py
The `checkLogIds.py` script looked like it was written for a purpose different from what it was used for.
In particular, it was renamed from `generateLogIds.py` in the past, and the checking logIds for uniqueness was hardcoded, so the script itself was not usable for any other purpose.
For the purpose of checking logIds it was also broken: it did not check whether a logId it found was valid leading to code passing CircleCI checks and failing Jenkins checks.
All the unused code is now deleted and replaced by code that explicitly does the following:
* collect all places that have invalid logIds. A logId consists of precisely 5 characters from the set `[a-f0-9]`.
* collect logIds that are used more than once
* print this information in a vaguely useful way.
Note that the check that is run on …
=> Fixup and cleanup checkLogIds

CHANGELOG, arangod/Aql/Collections.cpp, arangod/Aql/Collections.h, arangod/Cluster/ClusterMethods.cpp, arangod/RestServer/QueryRegistryFeature.cpp, arangod/RestServer/QueryRegistryFeature.h, tests/js/client/server_parameters/max-collections-per-query-cluster.js
Backport of https://github.com/arangodb/arangodb/pull/19066
Should fix https://arangodb.atlassian.net/browse/ES-1588
* Added startup option `--query.max-collections-per-query` to adjust the limit for the maximum number of collections/shards per query. The option defaults to `2048`, which is equivalent to the previous hardcoded value.
=> Added `--query.max-collections-per-query` option

arangod/Cluster/DBServerAgencySync.cpp
It happens from time to time that servers update Current with information that are already present. It appears as if the server does not see its own previous write. Indeed, there is no mechanism that ensures that the maintenance sees its own writes of a previous round.
This PR fixes that.
Note: Some noop-writes are still possible because of the `FollowerInfo`. When it updates the failover candidates after the first write, it might report the same data again.
=> Wait for writes to Current to become visible locally.

tests/js/client/server_parameters/test-return-queue-time-header-on.js
For some reason the changed assert sometimes fails with `result.code` being `undefined`; add output of the result to be able to tell slightly better what's going on once this test fails agian.
=> Add a more verbose message to sporadically failing assert

3rdParty/fuerte/src/H1Connection.h, CHANGELOG, arangod/VocBase/Methods/Databases.cpp
As I'm finding this issue quite hard to reproduce (and understand), I decided to provide detailed information in the body of this PR. Feel free to jump directly to **Solution** if you only want to read about the actual changes.
**Background**
During one of the replication2 restart tests, we noticed that sometimes the `database.drop()` call returned _cluster internal HTTP connection broken_. After investigating this, it turned out to originate from a transaction started by the coordinator. A database drop, on the coordinator, involves two steps:
1. Remove the database entry from the agency.
2. Remove the corresponding permissions from the `_users` collection. This is the transaction that used to fail sporadically.
The test that reproduced this failure most often **restarted one of the …
=> Retry in case the connection is aborted

arangod/Replication2/Version.h, arangod/RestServer/DatabaseFeature.cpp, arangod/RestServer/DatabaseFeature.h
`arangod --dump-options` reported, for the option `database.default-replication-version`, the `"type": "replicationVersion"`; change this to `"type": "string"`.
=> Change reported parameter type from "replicationVersion" to "string"

js/common/modules/@arangodb/testutils/replicated-logs-predicates.js
The _testDropReplicatedState_ failed while creating the replicated log. This is not due to the test itself, as the problem I'm going to describe could occur in any other replication2 integration test that uses the `createReplicatedLogWithState` function, available in the `replicated-logs-helper`.
The `createReplicatedLogWithState` works by writing the necessary entry to _Target_ and then waiting on the `replicatedLogLeaderEstablished` predicate to be satisfied. It's important to note that the `maxActionsTraceLength` parameter is used in _Target_, which allows the supervision to write actions into _Current_ (for debugging purposes). This might create a rather unexpected state: depending on the supervision's timing, we might end up with an entry in _Current_, before having a valid entry in …
=> [CINFRA-750] Fix flaky test

arangod/GeneralServer/CommTask.cpp, arangod/GeneralServer/RestHandler.cpp, arangod/GeneralServer/RestHandler.h, arangod/RestHandler/RestBatchHandler.cpp, tests/js/client/shell/api/multi/foxx-spec.js
Avoid duplicate gzip encoding in the `/_api/job` API.
=> avoid duplicate gzip encoding

3rdParty/V8/v7.9.317/src/base/logging.h, 3rdParty/V8/v7.9.317/src/base/macros.h, 3rdParty/V8/v7.9.317/src/inspector/v8-string-conversions.h, arangod/Aql/AttributeNamePath.h, arangod/Aql/IndexHint.h, arangod/Aql/QueryString.h, arangod/Graph/Helpers/TraceEntry.h, arangod/Utils/UrlHelper.h, arangod/Zkd/ZkdHelper.h, lib/Basics/conversions.h, lib/Basics/threads.h, lib/Containers/details/HashSetImpl.h, lib/Rest/CommonDefines.h, lib/Ssl/SslInterface.h
Missing include caused build error for new libstdc++
=> Update iresearch and fix missing include

arangod/RocksDBEngine/RocksDBEngine.cpp, arangod/RocksDBEngine/RocksDBEngine.h
Backport of https://github.com/arangodb/arangodb/pull/19063
Dont delete empty WAL files at startup.
We dont need to maintain such functionality on our own, as RocksDB has implemented that functionality itself in an upcoming version (8.3). It is also not important to keep it, because the empty WAL files dont do harm except use a few inodes unnecessarily.
=> Dont delete empty WAL files at startup.

js/client/modules/@arangodb/testsuites/dump.js, js/client/modules/@arangodb/testutils/instance-manager.js
the dump tests should catch errors, and use our facilities to force shutdown & debug the SUT so we have an easier life.
=> make dump tests better aware of sudden instance death in mid-air, so we get better results

lib/Inspection/CMakeLists.txt, lib/Inspection/include/Inspection/Transformers.h, tests/Inspection/CMakeLists.txt, tests/Inspection/TransformerTest.cpp
Previously the implementation of `TimeStampTransformer`, which takes a `std::chrono::system_clock::time_point` and transforms it into a string used the ArangoDB library function `timepointToString`.
This function in turn converted the `time_point` into a `time_t` and then uses `TRI_gmtime` to format the `time_point`.
If one uses std::chrono::system_clock::time_point::min() as input value to timepointToString, this yields an invalid time_t on some platforms (in particular here Windows), leading to an error in gmtime.
The ArangoDB library function ignores that error and continues.
This leads to invalid characters being left in the serialisation of the timepoint.
This PR changes the `TimeStampTransformer` to use formatting and parsing functions from the `date.h` library to perform …
=> Fix TimeStampTransformer

arangod/IResearch/IResearchDataStore.cpp, arangod/IResearch/IResearchDataStore.h, arangod/IResearch/IResearchInvertedIndexMeta.h, arangod/IResearch/IResearchPrimaryKeyFilter.cpp, arangod/IResearch/IResearchPrimaryKeyFilter.h, tests/IResearch/IResearchDocumentTest.cpp
`n * 1 * 8 + с1` instead of `n * 11 * 8 + с2` bytes
`c1 = sizeof PrimaryKeysFilter (8*12) + two counters in shared_ptr (8*2)`, probably can be less (2 score_t, counters, a lot of vptr are unnecessary.
`c2 = sizeof PrimaryKeyFilterContainer(8*12) + two counters in shared_ptr (8*2)`
So I assume new memory layout always smaller, except zero removes case
=> SEARCH-479 Use less memory for n removes in single transaction

tests/test-definitions.txt
Hot backup tests are too close to the 2GB limit of the small container.
=> Use medium container for hot backup tests to avoid OOM kills.

CHANGELOG, arangod/RocksDBEngine/RocksDBVPackIndex.cpp, tests/js/server/aql/aql-index-rearming.js
Backport of https://github.com/arangodb/arangodb/pull/19154
https://arangodb.atlassian.net/browse/OASIS-25262
* OASIS-25262: Fixed undefined behavior in IN lookup in unique indexes when the lookup array had to be rebuilt in memory.
=> Fix IN lookup

arangod/Cluster/ClusterInfo.cpp
**Background**
The replication2 restart tests used to get stuck sometimes in a _shutdown hanger_. During the test, one or more servers were being restarted gracefully through the shutdown API.  
The system waits for the _Heartbeat thread_ to be gracefully shut stopped. The _Heartbeat thread_ hangs during `DBServerAgencySync::execute()`, where the DBServer is supposed to wait for its own writes to become visible in its local copy of _Current_:
```cpp
AgencyCommResult r = comm.sendTransactionWithFailover(currentTransaction);
if (!r.successful()) {
//...
} else {
// wait for own writes to become visible locally in Current
auto waitIndex = resultsSlice[0].getNumber<uint64_t>();
std::ignore = clusterInfo.waitForCurrent(waitIndex).get();
// the above Future might not be resolved
}
```
For …
=> Maintenance shutdown hanger

client-tools/Backup/arangobackup.cpp
If `arangobackup` exits with an exception it used to show `arangodump` as the command that failed. This might be confusing so it might well be fixed right away. It is unclear to me how one could even trigger this kind of failure, though.
=> Fix typos in hotbackup error messages

arangod/IResearch/IResearchDataStore.cpp, arangod/IResearch/IResearchDataStore.h, arangod/IResearch/IResearchDocument.cpp, arangod/IResearch/IResearchFeature.cpp, arangod/IResearch/IResearchFeature.h, arangod/IResearch/IResearchPrimaryKeyFilter.cpp, arangod/IResearch/IResearchPrimaryKeyFilter.h, arangod/IResearch/IResearchRocksDBInvertedIndex.h, arangod/IResearch/IResearchRocksDBLink.h, arangod/IResearch/IResearchRocksDBRecoveryHelper.cpp, arangod/IResearch/IResearchRocksDBRecoveryHelper.h, arangod/IResearch/Search.cpp, arangod/IResearch/Search.h, arangod/RocksDBEngine/RocksDBRecoveryHelper.h, tests/IResearch/IResearchInvertedIndexIteratorTest.cpp, tests/IResearch/IResearchLinkTest.cpp, tests/IResearch/IResearchViewTest.cpp, tests/Mocks/IResearchInvertedIndexMock.cpp, tests/Mocks/IResearchLinkMock.cpp, tests/Mocks/IResearchLinkMock.h
* Remove arangodb transaction abstractions from ArangoSearch recovery
* Add caching for get links/indexes in PutCF/DeleteCF
* Add batching for removes in recovery (for inserts too, but for them almost no difference)
* Also make OutOfSync more optimistic:
Before these changes, even if link doesn't need recovery it can be marked as OutOfSync
For single link and 1e6 replaces (remove/insert) in recovery this PR improves time in 2 times:
30 sec instead of 1 min
For multiple links improvement could be in a few times better.
=> [SEARCH-480] [APM-766] Speedup ArangoSearch recovery

arangod/Replication2/ReplicatedState/ReplicatedState.tpp
Don't abandon the shared state to facilitate proper error handling down the line.
=> Don't abandon promise

arangod/Cluster/Maintenance.cpp, arangod/Replication2/ReplicatedLog/AgencyLogSpecification.cpp, arangod/Replication2/ReplicatedLog/AgencyLogSpecification.h, arangod/Replication2/ReplicatedLog/AgencySpecificationInspectors.h, arangod/Replication2/ReplicatedLog/Supervision.cpp, tests/Replication2/ReplicatedLog/Supervision/SupervisionTest.cpp
Necessary ex ante work to implement conservative leader election (which is necessary for waitForSync=false); see https://arangodb.atlassian.net/wiki/spaces/CInfra/pages/2061369370/Concept+Conservative+leader+election for details.
On leader election, all participants now report their current RebootId to `Current/`, along with their spearhead and status. This RebootId is then used when a leader is elected, instead of the one from `Health/`, which is prone to races (with waitForSync=false).
=> [CINFRA-780] Report reboot id and use in election

arangod/Agency/ActiveFailoverJob.cpp, arangod/Agency/AddFollower.cpp, arangod/Agency/CleanOutServer.cpp, arangod/Agency/FailedFollower.cpp, arangod/Agency/FailedLeader.cpp, arangod/Agency/FailedServer.cpp, arangod/Agency/Job.cpp, arangod/Agency/MoveShard.cpp, arangod/Agency/Node.cpp, arangod/Agency/Node.h, arangod/Agency/NodeLoadInspector.h, arangod/Agency/RemoveFollower.cpp, arangod/Agency/ResignLeadership.cpp, arangod/Agency/Store.cpp, arangod/Agency/Supervision.cpp, tests/Agency/NodeLoadTest.cpp, tests/Maintenance/MaintenanceTest.cpp
Lets get rid of the `std::optional<std::reference_wrapper<T>>` abomination, which was caused by a brain fart of mine. Now, I'm aware of the fact, that the agency will crash with a nullptr access, instead of just logging `std::bad_optional_access` over and over again. I think it is better now, because you see _where_ the nullptr access happened.
=> Fixing Node API.

.circleci/base_config.yml
Fixes reporting for clang-format on CircleCI for enterprise and community version.
Previously the script just exited when there was a diff in the community repository and did not upload any artefacts. Now diffs are printed and the clang-format job appropriately fails if any one of community or enterprise repositories have clang-format problems.
=> [CIRCLECI] Fix clang format job

arangod/IResearch/IResearchDataStore.cpp
In very old format we don't have two ticks, so second is uint64_t::max
=> Fix set out of sync for very old iresearch links

arangod/IResearch/IResearchDataStore.cpp
https://github.com/arangodb/arangodb/pull/19221
=> Fix set out of sync for very old iresearch links 3.10

arangod/IResearch/IResearchDataStore.cpp
https://github.com/arangodb/arangodb/pull/19221
=> Fix set out of sync for very old iresearch links 3.11

arangod/Cluster/ClusterCollectionMethods.cpp
*We are too eager to report an error to the user and not retry to create a collection. This is actually not necessary at all. This also solves the issue of "precondition failed" handed out to the user.*
Detected by driver tests (this work is based on arangojs) so under integration test there.
=> Reenable retry createCollection for Replication1

arangod/Utils/SupportInfoBuilder.cpp
Backport to https://github.com/arangodb/arangodb/pull/19233.
This PR forces the value put in the velocypack object respective to persisted id to be a string when the server has no persisted id value and its id is used instead to prevent this error in the endpoint's parser:
```
Saving messages in BiqQuery failed: '400 Provided Schema does not match Table telemetrics-project:telemetrics_dataset.telemetrics_table. Field deployment.persisted_id has changed type from STRING to INTEGER``
```
=> Bug fix 3.11/telemetrics force string persisted

CHANGELOG, arangod/Aql/Query.cpp, arangod/Cluster/AgencyCache.cpp, tests/js/client/shell/shell-med-queue-blocked-cluster.js
This PR addresses two BTS tickets:
- https://arangodb.atlassian.net/browse/BTS-1475
- https://arangodb.atlassian.net/browse/BTS-1486
which both describe failures and lockups actually seen in production.
The details of the problems are described in the above BTS tickets.
The solution is twofold:
- for BTS-1475 we make it so that responses to agency poll calls are
handled without scheduler involvement, they just trigger a wakeup
in the thread of the AgencyCache, which does the actual processing then.
- for BTS-1486 we use the lane `CLUSTER_INTERNAL` on the HIGH prio queue
to receive the response to the AQL shutdown requests to the dbservers.
Both achieve to avoid the deadlocks.
This is a backport of https://github.com/arangodb/arangodb/pull/19254
*(Please describe the changes in this PR for …
=> Medium prio lockups in AgencyCache and Query shutdown, BTS-1475, BTS-1486

lib/Basics/TimeString.h
A slightly more general, albeit risky, fix for the problem shown in #19138: rewrite `timepointToString` and `stringToTimepoint` to use the `date.h` C++ library instead of subtly incompatible C functions.
=> Simplify and fix timepointToString and stringToTimepoint

arangod/Replication2/StateMachines/Document/ReplicatedOperation.h, lib/Inspection/include/Inspection/Access.h, lib/Inspection/include/Inspection/Factory.h, lib/Inspection/include/Inspection/LoadInspectorBase.h, tests/Inspection/VPackLoadTest.cpp, tests/Inspection/VPackSaveTest.cpp, tests/Inspection/include/Inspection/InspectionTestHelper.h
Allow to inspect, and in particular deserialize, types that aren't default constructible. A static factory can be specialized to allow the Inspection library to create values.
=> Allow to specify a factory for non default-constructible types

arangod/Replication2/ReplicatedLog/LogLeader.cpp, arangod/Replication2/ReplicatedLog/LogLeader.h
Ticket: https://arangodb.atlassian.net/browse/CINFRA-787
The following describes a small refactoring of updating the committed configuration in the LogLeader, which is necessary to implement https://arangodb.atlassian.net/browse/CINFRA-781 correctly; without it, there would be data races that are very hard to handle correctly.
The current implementation is complicated and has a lot of boilerplate code (try/catch etc.) to make it safe. This is because it is completely asynchronous, and we have to handle (i.a.) multiple racing updates correctly.
It is much simpler to do this in updateCommitIndexLeader, which immediately does everything in order and sequential. It also makes it more reliable from an external perspective: The config update is currently not immediately visible when the …
=> [CINFRA-787] Commit participants config sequentially

arangod/Graph/Graph.cpp, arangod/Graph/Graph.h, arangod/Graph/GraphManager.cpp
*As our windows tests are started with a different default configuration they unveiled a bug in GraphManager when creating enterprise grade graphs in OneShard database. The feature is not really a practical use-case however now Graphs again honor OneShard rules.*
=> cinfra - Made all Graphs OneShard aware

CHANGELOG, arangod/Aql/Condition.cpp, tests/js/server/aql/aql-traversal-graph-object-regression.js
Backport of https://github.com/arangodb/arangodb/pull/19188
Fix an issue and added a regression test for issue #19175, found by a community user.
The issue was caused by the following:
The expected usage of an AQL `Condition` object is to append things to it via `Condition::andCombine(...)` any number of times, and then at the end call `Condition::normalize(...)` exactly once on it. And then not call `Condition::andCombine(...)` on the already normalized object anymore. This is because `andCombine(...)` will throw if it is invoked on an already normalized condition.
However, there was one glitch: up to including 3.10, an AQL `Condition` object would not set its `_isNormalized` boolean flag when calling `Conndition::normalize(...)`, so the fact that the condition was normalized was not …
=> [BTS-1443] Fix Github issue #19175

arangod/Agency/AgencyPaths.h, arangod/Cluster/ClusterTypes.cpp, arangod/Cluster/ClusterTypes.h, arangod/Cluster/Maintenance.cpp, arangod/Cluster/RebootTracker.cpp, arangod/Cluster/RebootTracker.h, arangod/Replication2/ReplicatedLog/AgencyLogSpecification.h, arangod/Replication2/ReplicatedLog/AgencySpecificationInspectors.h, arangod/Replication2/ReplicatedLog/CMakeLists.txt, arangod/Replication2/ReplicatedLog/DefaultRebootIdCache.cpp, arangod/Replication2/ReplicatedLog/DefaultRebootIdCache.h, arangod/Replication2/ReplicatedLog/IRebootIdCache.h, arangod/Replication2/ReplicatedLog/LogEntries.cpp, arangod/Replication2/ReplicatedLog/LogEntries.h, arangod/Replication2/ReplicatedLog/LogLeader.cpp, arangod/Replication2/ReplicatedLog/LogLeader.h, arangod/Replication2/ReplicatedLog/LogStatus.h, arangod/Replication2/ReplicatedLog/ReplicatedLog.cpp, arangod/Replication2/ReplicatedLog/ReplicatedLog.h, arangod/Replication2/StateMachines/Document/DocumentStateSnapshotHandler.cpp, arangod/Transaction/Options.h, arangod/VocBase/VocBaseLogManager.cpp, js/common/modules/@arangodb/testutils/replicated-logs-helper.js, lib/Basics/RebootId.h, tests/Replication2/CMakeLists.txt, tests/Replication2/Mocks/RebootIdCacheMock.h, tests/Replication2/ReplicatedState/StateManagerTest.cpp, tests/js/server/replication2/replication2-maintenance-replicated-log-cluster.js, tests/js/server/replication2/replication2-regression.js, tests/js/server/replication2/replication2-replicated-log-entry-cluster.js
https://arangodb.atlassian.net/browse/CINFRA-781
The leader has to track its participant’s RebootIds and report them to Current.
In order to do that, on startup it has to:
* copy the map participantId => rebootId from the agency cache (before establishing leadership)
* report the map to current after leadership has been established
Later, if any participant’s RebootId changes (register callback in the RebootTracker):
* get the RebootId of the participant from the agency cache
* insert an empty log entry
* after the log entry has been committed, report the map to current
=> [CINFRA-781] Have leaders track their participants' RebootIds

lib/Inspection/CMakeLists.txt, lib/Inspection/include/Inspection/Transformers.h
This is a backport of #19138 and #19261
Previously the implementation of TimeStampTransformer, which takes a std::chrono::system_clock::time_point and transforms it into a string used the ArangoDB library function timepointToString.
This function in turn converted the time_point into a time_t and then
uses TRI_gmtime to format the time_point.
If one uses std::chrono::system_clock::time_point::min() as input value to timepointToString, this yields an invalid time_t on some platforms (in particular here Windows), leading to an error in gmtime.
The ArangoDB library function ignores that error and continues.
This leads to invalid characters being left in the serialisation of the timepoint.
This PR changes the TimeStampTransformer to use formatting and parsing functions from the date.h library …
=> [3.11] Fix TimeStampTransformer

arangod/Replication2/ReplicatedLog/Components/ISnapshotManager.h, arangod/Replication2/ReplicatedLog/Components/IStateHandleManager.h, arangod/VocBase/Properties/KeyGeneratorProperties.h
without this fix it's impossible to use new libstdc++ (gcc libs 13 package)
=> Fix missing includes

CHANGELOG, lib/ProgramOptions/Option.cpp
Trivial change: if a startup option has a dynamic default value (e.g. if the default value depends on the amount of available RAM), display a "dynamic default" hint when invoking `--help`.
=> Show "dynamic default" hint for startup options

CHANGELOG, arangod/RocksDBEngine/RocksDBMetaCollection.cpp
*Avoid busy looping when locking collections with a timeout*
=> Avoid busy looping when locking collections with a timeout [3.10]

CHANGELOG
Set date in CHANGELOG and moved wrong entry to 3.10.9
=> Fixed wrong changelog entry

arangod/Aql/Condition.cpp, arangod/Aql/Condition.h, arangod/Aql/ConditionFinder.cpp, arangod/Aql/ConditionFinder.h, arangod/Aql/IResearchViewOptimizerRules.cpp, arangod/Aql/OptimizerUtils.cpp, arangod/IResearch/IResearchFilterFactory.cpp, tests/js/common/aql/aql-arangosearch-inverted-index-optimization.js
The aql generate plan without all filter variables, so inverted index incorrectly consider it handles all filter conditions in such case
=> BTS-1495 Inverted index cause incorrect plan optimization

CHANGELOG, arangod/Aql/OptimizerRules.cpp, tests/js/common/shell/shell-explain-cluster.js, tests/js/server/aql/aql-optimizer-rule-undistribute-remove-after-enum-coll-cluster.js
Backport of https://github.com/arangodb/arangodb/pull/19306
Fixed "note 2" from https://arangodb.atlassian.net/browse/BTS-1490.
* BTS-1490: Allow performing AQL updates locally without using DISTRIBUTE in case the update AQL is of the pattern
FOR doc IN collection
UPDATE <doc> IN collection
Previously the optimization was only possible if the update AQL was of the pattern
FOR doc IN collection
UPDATE <key> WITH <doc> IN collection
Both <key> and <doc> refer to data from the collection enumeration variable `doc` here.
Also fix the optimization in case a shard key attribute is updated with a value from a different attribute, e.g.
FOR doc IN collection
UPDATE { _key: doc.abc, abc: doc._key } IN collection
In this case the optimization was previously applied although it shouldn't.
=> Fixes second issue of BTS-1490

CHANGELOG, arangod/Aql/ModificationExecutor.cpp, tests/js/server/aql/aql-memory-limit.js
Backport of https://github.com/arangodb/arangodb/pull/19299
Fixes https://arangodb.atlassian.net/browse/BTS-1490 (first part) and https://arangodb.atlassian.net/browse/OASIS-25321.
* BTS-1490: query can use a lot more memory when using COLLECT WITH COUNT.
=> Fixed BTS-1490

js/client/modules/@arangodb/testutils/instance-manager.js
Since we mess with SUT by stopping processes now and then, we should not loose hope to acquire an agency dump even if we are in force shutdown.
=> testing: try to acquire an agency dump even if we are in force shutdown

CHANGELOG
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/1307
when a hot backup is executed, it will store data in a temporary directoy named `CREATING_{number}`, where `{number}` is a number between 1m and 2m. If the backup succeeds, the temporary directory is given a name that contains both a timestamp and the backup id. but if the hot backup fails in the middle, the temporary directory is left behind. as the leftover directory contains backups, this can lead to large amounts of disk space being used for it or the files that it still links to.
this change now removes the temporary directory in case the hot backup goes wrong.
=> clean up temporary backup directory if backup fails

arangod/Agency/Supervision.cpp, arangod/Metrics/ClusterMetricsFeature.cpp, arangod/Metrics/ClusterMetricsFeature.h, arangod/Pregel/PregelFeature.cpp, tsan_arangodb_suppressions.txt
* Suppress very popular and easy to reproduce replication2 lock order inversions
These errors make all report unreadable because they spam it
* Fix 3 simple data races
* Remove already unnecessary suppressions
=> Try to make cluster tests tsan run more useful

.circleci/base_config.yml
This change is just a micro-optimisation to checkout the enterprise repository only when compiling enterprise.
=> Checkout enterprise only when building enterprise

arangod/Replication2/ReplicatedLog/Components/AppendEntriesManager.cpp, client-tools/Import/SenderThread.cpp, tsan_arangodb_suppressions.txt
Try to make cluster tsan blue except known issues.
https://jenkins.arangodb.biz/job/arangodb-ANY-linux-san.x86-64/1946/EDITION=enterprise,SAN_MODE=TSan,STORAGE_ENGINE=rocksdb,TEST_SUITE=cluster,limit=linux&&test&&x86-64/
=> [APM-750] Fix some data races

CHANGELOG, arangod/RocksDBEngine/RocksDBEngine.cpp, arangod/RocksDBEngine/RocksDBOptionFeature.cpp, lib/ApplicationFeatures/OptionsCheckFeature.cpp
Adjust options for RocksDB WAL file deletion as follows:
* Set threshold for RocksDB automatic WAL file deletion by age from 30 days to 30 years. This should effectively not change any behavior, as we don't rely on RocksDB's built-in WAL file deletion mechanism. Instead, we tell RocksDB explicitly to delete which WAL files, depending on what other functionality (e.g. replication, index creation) still needs them or not.
* Deprecate the startup option `--rocksdb.wal-archive-size-limit` because it can be unsafe to use in environments that use replication (cluster, active failover, single-to-single replication). When using the option and limiting the total size of the WAL files in the archive, this may lead to still-needed WAL files being pruned too early. This can have side effects, such as …
=> adjust options for RocksDB WAL file deletion

arangod/Replication2/ReplicatedLog/Components/AppendEntriesManager.cpp, arangod/Replication2/ReplicatedLog/LogLeader.cpp, arangod/Replication2/ReplicatedLog/LogLeader.h, arangod/Replication2/ReplicatedLog/NetworkMessages.cpp, arangod/Replication2/ReplicatedLog/NetworkMessages.h, tests/Replication2/ReplicatedLog/LogFollower/AppendEntriesTest.cpp
Followers report their `syncIndex` to the leader (in the `AppendEntriesResponse`), and let the leader track it for all participants.
This is the continuation of https://github.com/arangodb/arangodb/pull/19285
=> [CINFRA-777] Report syncIndex to the leader

tests/js/server/aql/aql-index-cache.js
Make workaround for aql-index-cache tests even more forgiving.
=> fix a failing cache test

tests/js/server/replication2/replication2-supervision-replicated-log-target-cluster.js
Small correction applied to https://github.com/arangodb/arangodb/pull/19333
It is enough to disallow the old leader from quorum in order remove it from Plan. Therefore, `RemoveParticipantFromPlanAction` might also appear on the 5th index.
=> [CINFRA-791] Fix supervision flaky test

arangod/Cache/PlainCache.cpp, arangod/Cache/TransactionalCache.cpp, tests/Cache/PlainCache.cpp
Adjust hits rates ranges in cache test.
The hit rates tracking does not guarantee exact values.
=> adjust hit rates test

CHANGELOG, arangod/Cluster/ClusterMethods.cpp, tests/js/client/shell/api/document-read.js
Fix unintended API difference between SingleServer and Cluster. 
Whenever a PUT requests has been made against: `/_api/document/{aCollection}?onlyget=true`
and the body just contains an empty list `[]`, the server replied with a `internal server error`. 
The cluster environment now behaves the same as the SingleServer api and just returns the
correct result with the correct error code.
=> [OASIS-25344][3.10] Fix document API inconsistency 

tests/js/client/shell/api/multi/document-read.js
Original ticket: https://github.com/arangodb/arangodb/pull/19364
Added a regression test only. 
Bug-itself is fixed in this branch already, see: https://github.com/arangodb/arangodb/pull/19059
=> [OASIS-25344][3.11] API inconsistency regression test 

CHANGELOG, arangod/Agency/Job.cpp, arangod/Agency/Supervision.cpp, arangod/Cluster/TraverserEngine.cpp, arangod/GeneralServer/H2CommTask.cpp, arangod/GeneralServer/HttpCommTask.cpp, arangod/Pregel/Algos/RecoveringPageRank.cpp, arangod/RestHandler/RestDumpHandler.cpp, arangod/RestHandler/RestReplicationHandler.cpp, client-tools/Dump/DumpFeature.cpp, lib/Rest/HttpResponse.h, lib/SimpleHttpClient/SimpleHttpClient.cpp, tests/js/client/server_permissions/test-foxx-service-access-denied.js
Also retry on write, read and connect errors. Initially I thought there was no way of knowing why the request failed, but I was wrong. Additionally retry creating dump contexts.
The following things have also been changes:
1. The server enforces a empty response body if the response code is `204 No Content`. This already almost always true. The problematic exception was the new dump api.
2. The `SimpleHttpClient` will drop the body of all http responses that have response code `204`. This is done by dropping the connection if the `Content-Length` is not zero and the response code is `204`.
3. The dump api now explicitly creates an empty body in case 204.
=> [DUMP] Retry on write, read and connect errors

client-tools/Backup/arangobackup.cpp, client-tools/Dump/DumpFeature.cpp, client-tools/Dump/DumpFeature.h, client-tools/Import/SenderThread.cpp, client-tools/Restore/RestoreFeature.cpp, client-tools/Restore/RestoreFeature.h, client-tools/Utils/ManagedDirectory.cpp, js/client/modules/@arangodb/testsuites/dump.js, js/client/modules/@arangodb/testutils/process-utils.js, tests/js/client/shell/shell-dump-integration.js, tests/js/client/shell/shell-restore-integration.js, tests/test-definitions.txt
Wire the `--split-files` option for arangodump, so that arangodump can produce multiple output files for a single shard when using `--use-experimental-dump`. Also wire arangorestore support for restoring multiple files.
This is a backport of functionality that already exists in 3.11 and devel.
The option is experimental though.
=> fix small issues in client-tools, add split file support for dump/restore

arangod/GeneralServer/H2CommTask.cpp, arangod/GeneralServer/HttpCommTask.cpp, arangod/GeneralServer/RestHandler.cpp, arangod/RestHandler/RestBaseHandler.cpp, arangod/RestHandler/RestBaseHandler.h, arangod/RestHandler/RestBatchHandler.cpp, arangod/RestHandler/RestImportHandler.cpp, lib/Rest/GeneralRequest.cpp, lib/Rest/GeneralRequest.h, lib/Rest/HttpRequest.cpp, lib/Rest/HttpRequest.h, lib/Rest/VstRequest.cpp, lib/Rest/VstRequest.h, tests/IResearch/RestHandlerMock.cpp, tests/IResearch/RestHandlerMock.h, tests/js/client/shell/api/multi/import-novst.js
Track request sizes more accurately. Includes HTTP and VST requests.
Overheads of contains (capacity vs. size) are not tracked, but only payload sizes.
Correctness is currently validated via assertions in the destructors.
The PR also slightly cleans up the internal APIs of HttpRequest and GeneralRequest and moves responsibilities for a few things.
=> track sizes of requests more accurately

CHANGELOG, arangod/Cluster/HeartbeatThread.cpp, arangod/GeneralServer/CommTask.cpp, arangod/Replication/ReplicationFeature.cpp, arangod/Replication/ReplicationFeature.h, tests/js/client/active-failover/basic.js, tests/js/client/active-failover/disconnected-leader-nonwindows.js
Potential fix for https://arangodb.atlassian.net/browse/BTS-1488
Backport of https://github.com/arangodb/arangodb/pull/19339 
* Added startup option `--replication.active-failover-leader-grace-period`. This startup option can be used to set the amount of time (in seconds) for which the current leader in an active failover setup will continue to assume its leadership even if it lost connection to the agency.
In case the leader cannot contact the agency anymore, the agency will elect a new leader after the supervision grace period has elapsed. In order to avoid a split-brain situation with multiple servers assuming leadership, this option can be used to make a disconnected leader refuse any incoming write operations after the grace period controled by this option has elapsed. Ideally the …
=> Add grace period for disconnected leaders in active failover

js/client/modules/@arangodb/testsuites/gtest.js
Filter was meant well, but wrong.
=> Do not run LongRunning google tests

arangod/IResearch/IResearchDataStore.cpp, scripts/test/testing_runner.py
- forward port of https://github.com/arangodb/oskar/pull/526/files to circle ci
- don't create coredumps on failure points
=> BTS-1512: testing: if we have a crashdump, test state must be failed

js/client/modules/@arangodb/test-helper.js
Backport of https://github.com/arangodb/arangodb/pull/19409
Attempt to fix chaos tests.
Potentially some of the existing timeouts have been too low. This PR adjusts them.
=> attempt to fix chaos tests

tsan_arangodb_suppressions.txt
A lock-order inversion inside the replication2 code has been suppressed. My initial response was that it's a false positive. I have just double checked together with @goedderz and we confirmed it.
This PR adds an explanation in the TSAN suppressions file.
=> [BTS-1428] Explaining the reson for suppression

.circleci/config.yml
Build `devel` on PR merges automatically again; this should allow detecting PR merges that break `devel` more quickly.
=> Reactivate building devel in CI on merge.

scripts/toolbox/HotBackupConsistencyTest.py
1. After a restore the cluster is not immediately ready for action. (For example AQL instantiation fails with missing shard). Hence we added a small grace period.
2. The streaming transaction test (el cheapo) did not use transactions at all. Obviously it failed.
=> Fixing Hotbackup Test

CHANGELOG, arangod/RestServer/DatabaseFeature.cpp, arangod/RestServer/DatabaseFeature.h, arangod/VocBase/Methods/Databases.cpp, tests/js/client/server_parameters/max-databases-limit.js, tests/js/client/server_parameters/max-databases-unlimited.js
Backport of https://github.com/arangodb/arangodb/pull/19417
* Added startup option `--database.max-databases` to limit the maximum number of databases that can exist in parallel on a deployment. This option can be used to limit resources used by database objects. If the option is used and there already exist as many databases as configured by this option, any attempt to create an additional database will fail with error 32 (`ERROR_RESOURCE_LIMIT`). Additional databases can then only be created if other databases are dropped first. The default value for this option is unlimited, so technically an arbitrary amount of databases can be created (although effectively the number of databases is limited by memory and processing resources).
=> Add `--database.max-databases` (#19417)

Documentation/Metrics/arangodb_agency_node_memory_usage.yaml, arangod/Agency/Helpers.cpp, arangod/Agency/Helpers.h, arangod/Agency/Node.cpp, arangod/Agency/Node.h, arangod/Metrics/MetricsFeature.cpp
Memory accounting for agency nodes. Some members are not yet accounted for, because that would change the API to much. (For example the keys of the `Children` map are still `std::string`s.)
=> Memory Accounting Agency Nodes

CHANGELOG, arangod/Aql/OptimizerRulesCluster.cpp, lib/Basics/ReadWriteLock.cpp, tests/Basics/ReadWriteLockTest.cpp, tests/js/server/aql/aql-temp-rocksdb-storage.js
* Fix lock code when a timeout occurs. In this case it was possible that a queued writer was not notified.
* Disable multi-insert optimization in AQL when it is executed as part of a streaming transaction. This is necessary because the multi-insert optimization will start its own sub-transaction, and does not know about if it is invoked from an outer streaming transaction. If it is invoked from inside a streaming transaction that holds write locks and then starts its own transaction that tries to acquire the same locks, it will deadlock.
* (unimportant) Adjust a test so that it does not acquire a lock recursively on the same collection 3 times.
=> fix lock code when a lock timeout occurs

CHANGELOG, arangod/Agency/State.cpp
Backport of https://github.com/arangodb/arangodb/pull/19446
when loading configuration with an AQL query (which acquires the collection's status lock) and then starting a transaction on the same collection (acquires the status lock once more) while the query object is still in scope. this leads to the same thread locking the same rw lock in read mode twice, which can be dangerous if a writer is queued for the lock. then the two threads will deadlock.
=> avoid recursive locking in agency

CHANGELOG, arangod/Agency/State.cpp
Backport of https://github.com/arangodb/arangodb/pull/19446
when loading configuration with an AQL query (which acquires the collection's status lock) and then starting a transaction on the same collection (acquires the status lock once more) while the query object is still in scope. this leads to the same thread locking the same rw lock in read mode twice, which can be dangerous if a writer is queued for the lock. then the two threads will deadlock.
=> avoid recursive locking agency

scripts/toolbox/HotBackupConsistencyTest.py
Same as for DocumentGetError. Cluster is not yet ready.
=> hotbakcup test stabilization

CHANGELOG, arangod/RestServer/DatabaseFeature.cpp, arangod/RestServer/DatabaseFeature.h, arangod/VocBase/Methods/Databases.cpp, tests/js/client/server_parameters/max-databases-limit.js, tests/js/client/server_parameters/max-databases-unlimited.js
Backport of https://github.com/arangodb/arangodb/pull/19417
* Added startup option `--database.max-databases` to limit the maximum number
of databases that can exist in parallel on a deployment. This option can be
used to limit resources used by database objects. If the option is used and
there already exist as many databases as configured by this option, any
attempt to create an additional database will fail with error 32
(`ERROR_RESOURCE_LIMIT`). Additional databases can then only be created if
other databases are dropped first.
The default value for this option is unlimited, so technically an arbitrary
amount of databases can be created (although effectively the number of
databases is limited by memory and processing resources).
=> Add --database.max-databases

CHANGELOG, arangod/RocksDBEngine/RocksDBOptionFeature.cpp, arangod/RocksDBEngine/RocksDBOptionFeature.h
Optionally allow partitioning of .sst files for different collections/shards and indexes.
This is a potential performance improvement which allows RocksDB compactions to be more efficient.
We don't have performance test results yet, so it is only a _potential_ improvement that we need to try out.
* Added experimental startup options for RocksDB .sst file partitioning:
- `--rocksdb.partition-files-for-documents`
- `--rocksdb.partition-files-for-primary-index`
- `--rocksdb.partition-files-for-edge-index`
- `--rocksdb.partition-files-for-persistent-index`
Enabling any of these options will make RocksDB's compaction write the 
data for different collections/shards/indexes into different .sst files. 
Otherwise the document data from different collections/shards/indexes 
can be mixed and …
=> optionally allow partitioning of .sst files

arangod/RocksDBEngine/RocksDBEngine.cpp
The issue described in BTS-1526 is caused by ArangoDB's DBEngine deleting a file from under RocksDB's snapshot code (as amended by ArangoDB to store all WAL files).
This patch removes some code that eagerly prunes WAL files even if the lock on these files is held. The enterprise companion makes sure that HotBackup takes the lock while a hotbackup is in progress.  
Requires: https://github.com/arangodb/enterprise/pull/1331
=> [BTS-1526] Prevent purging WAL files during HotBackup

lib/Basics/HybridLogicalClock.h, tests/Basics/HybridLogicalClockTest.cpp
Added tests to verify that HLC values are actually ever-increasing, even with delayed physical clocks.
Test-only PR: intentionally no CHANGELOG entry.
=> added tests to verify HLC behavior

CHANGELOG, arangod/Cache/Manager.cpp, arangod/Cache/Manager.h, arangod/Cache/ManagerTasks.cpp, tests/Cache/Rebalancer.cpp
Backport of https://github.com/arangodb/arangodb/pull/19475
Fixed potential deadlock() in cache::Manager::unprepareTask() in case a MigrateTask could not be scheduled successfully (in case of a full scheduler queue on DB servers).
This issue was found during testing changes that were made in devel. This PR backports also backports a test that can reproduce the problem.
=> fixed potential deadlock() in cache::Manager::unprepareTask()

CHANGELOG, arangod/Aql/AqlValue.cpp, arangod/Aql/AqlValue.h, tests/Aql/AqlValueMemoryLayoutTest.cpp, tests/Aql/SortExecutorTest.cpp
Backport of https://github.com/arangodb/arangodb/pull/19449.
Changes to `lib/` aren't backported, therefore the tests use velocypack::SharedSlice instead of velocypack::String. Also, `VelocyPackStringLiteral.h` doesn't exist yet, so added an ad-hoc implementation of `operator""_vpack`.
=> [3.9] [BTS-1511] Fix AqlValues with 7-byte integers

CHANGELOG, arangod/Aql/AqlValue.cpp, arangod/Aql/AqlValue.h, tests/Aql/AqlValueMemoryLayoutTest.cpp, tests/Aql/SortExecutorTest.cpp
Backport of https://github.com/arangodb/arangodb/pull/19449.
Changes to `lib/` aren't backported, therefore the tests use velocypack::SharedSlice instead of velocypack::String. Also, `VelocyPackStringLiteral.h` doesn't exist yet, so added an ad-hoc implementation of `operator""_vpack`.
=> [3.10] [BTS-1511] Fix AqlValues with 7-byte integers

tests/js/client/chaos/test-chaos-load-common.inc
Merkeltrees can be equal while still having a different range of keys.
=> Fix nightly issue merkel trees

CHANGELOG, arangod/Pregel/IndexHelpers.cpp, arangod/RestHandler/RestDocumentHandler.cpp, arangod/RestHandler/RestImportHandler.cpp, arangod/Transaction/Methods.cpp, arangod/Transaction/Methods.h
* Wrap imports into SmartGraph edge collections via the REST import API (POST `/_api/import`) into a managed transaction, so that edge data is either completely inserted or not at all.
=> Wrap imports into SmartGraph edge collection into managed trx

arangod/RocksDBEngine/RocksDBCollection.cpp, arangod/RocksDBEngine/RocksDBKey.cpp, arangod/RocksDBEngine/RocksDBKey.h, arangod/RocksDBEngine/RocksDBTransactionState.cpp, arangod/RocksDBEngine/RocksDBTransactionState.h, arangod/RocksDBEngine/SimpleRocksDBTransactionState.cpp, arangod/RocksDBEngine/SimpleRocksDBTransactionState.h, arangod/StorageEngine/TransactionState.h, arangod/Transaction/Hints.cpp, arangod/Transaction/Hints.h, arangod/arangoserver.cmake, tests/js/server/shell/shell-transactions.js
Add diagnostic information when incosistency is found between primary index and documents cf. Also validate document existence and lock document keys properly when isRestore=true and we are in maintainer mode.
=> add diagnostic information when incosistency is found

CHANGELOG, arangod/Cache/CacheOptionsFeature.cpp, arangod/Cache/CacheOptionsProvider.h, arangod/Cache/Manager.cpp, arangod/Cache/Manager.h
* Expose the "high water multiplier" for the in-memory cache subsystem via a new startup option `--cache.high-water-multiplier`. The high water multiplier is used to calculate the effective memory usage limit for the in-memory cache subsystem. The cache's configured memory usage limit (`--cache.size`) is multiplied by the high water multiplier, and the resulting value is used as the effective memory limit. It defaults to 95% of the configured cache size.
Note that this is a behavior change. Previous versions of ArangoDB set the high water multiplier to effectively 56% of the configured memory. The value was hard-coded in versions before 3.11.3, and is exposed since then with a default value of 56%. 3.12 now sets the default value for the high water multiplier to 95%, so that the …
=> expose high water multiplier

arangod/Aql/Functions.cpp, lib/Geo/Ellipsoid.h, tests/Geo/GeoFunctionsTest.cpp
Before this patch we silently fell back to `sphere`. Now we generate an aql error.
=> [BTS-1264] Report a warning if an unknown ellipsoid is used.

arangod/RocksDBEngine/RocksDBCollection.cpp, tests/js/client/shell/transaction/shell-transaction.inc, tests/js/server/shell/shell-transactions.js
Prevent assertions in RocksDBCollection::insert() and RocksDBCollection::modify() to be triggered from normal tests.
=> fix test assertions

CHANGELOG, arangod/Aql/Collections.cpp, arangod/Aql/GraphNode.cpp, tests/js/server/aql/aql-traversal-restrict-collections.js, tests/js/server/aql/aql-traversal-restrict-edge-collections.js, tests/js/server/aql/aql-traversal-restrict-graph-collections-cluster.js
Backport of https://github.com/arangodb/arangodb/pull/19507
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/1337
Prevent potential nullptr dereferencing.
We have seen a backtrace from method `void aql::GraphNode::addEdgeCollection(aql::Collection& col)`, indicating that there is a potentiall nullptr access in there. We do not know yet how to reproduce the problem.
This PR adjusts the said method to not derefence potential nullptrs anymore, but instead throw a proper exception.
This will still make the AQL query fail, but not crash the coordinator.
=> prevent potential nullptr deref

arangod/Cluster/Maintenance.cpp, tests/js/client/shell/multi/shell-computed-values-cluster.js
Backport of https://github.com/arangodb/arangodb/pull/19515
https://arangodb.atlassian.net/browse/BTS-1539
Backport a change from devel that relaxes a comparison made in the cluster maintenance for computed values. 
Not having computed values is stored as `null` normally, but under some condition not having computed values can also be stored as an empty array in devel. 
Both values should be treated equal by the maintenance. If the maintenance treats `null` and `[]` as different, it may initiate a busy loop, trying forever to adjust the `computedValues` property of the shard.
Although we believe that in 3.11 having no computed values is always stoted as `null`, this backport is made to avoid potential issues during upgrades or in case other changes are backported from devel. the added …
=> BTS-1539: backport a change from devel

js/client/modules/@arangodb/test-helper.js, tests/js/client/chaos/test-chaos-load-common.inc
Extend (nightly) chaos tests so that they also test running in a OneShard database.
This adds a OneShard parameter to the tests, which will result in more test combinations available.
Effectively, adding a new parameter to the tests will **double** the number of test combinations. So this change is not without downsides, as it increases the overall runtime of the chaos tests considerably.
=> extended chaos tests so that they run on OneShard too

arangod/RocksDBEngine/RocksDBBuilderIndex.cpp, tests/js/client/shell/shell-index-background.js
Do not skip documents that have been inserted, when removing in same transaction.
When indexes are created in background a temporary IndexBuilder index is inserted as placeholder for the actual index. This index records which documents are inserted and removed during index creation. However, we limited this recording to a single event per document per transaction.
If the same document is inserted and removed within the same transaction during an index background creation, the document will eventually show up in the index.
Furthermore, the comment "don't track documents more than once" is a bit misleading. Since we use the local document id to track documents, any such id will show up in insert at most once.
=> Index Background Creation Bug

arangod/RocksDBEngine/RocksDBOptionFeature.cpp, arangod/RocksDBEngine/RocksDBOptionFeature.h
for `--rocksdb.recycle-log-file-num`. The option does not make any difference to use with the default WAL recovery mode we are using. RocksDB automatically sanitizes the option to a value of `0`.
Previously we exposed this startup option as a boolean value, but it should rather be a size_t. Interestingly, the RocksDB code also uses the option with a wrong type in at least one place of their code.
This change should not modify the behavior in any way, except if the option is now set to a non-zero value and non-default recovery mode is selected.
=> fix wrong underlying parameter type

js/common/modules/@arangodb/testutils/replicated-logs-helper.js, tests/js/server/replication2/replication2-maintenance-replicated-log-cluster.js
As it aims to test the maintenance, the `testCheckExcludedServers` is a plan-only test. This means there is no supervision involved. The test itself is simple:
1. Write a replicated log configuration to plan and wait for all server to report in current.
2. Disallow the followers from the quorum.
3. Expect the leader to report that it cannot commit.
I have seen the test failing due to high system load. When heartbeat responses are slow, the leader's reboot ID might be increased. This is unrelated to the test, but it causes it to fail.
High system load cannot be prevented. If the leader restarts, the test is doomed to fail. This PR adds the code to detect reboot ID changes and print a message, skipping the test if necessary. The decision to skip the test is a trade off between the test's …
=> [CINFRA] Preventing test from failing due to high system load

arangod/Aql/IResearchViewExecutor.h, arangod/Aql/IResearchViewExecutor.tpp, arangod/Aql/IResearchViewNode.h, arangod/Aql/IResearchViewOptimizerRules.cpp, arangod/IResearch/GeoFilter.cpp, tests/IResearch/ExpressionFilterTest.cpp, tests/IResearch/GeoDistanceFilterTest.cpp, tests/IResearch/GeoFilterTest.cpp, tests/IResearch/IResearchOrderTest.cpp, tests/IResearch/IResearchViewTest.cpp, tests/IResearch/common.cpp
This change implement wand for conjunction, min_match and disjunction more than 2 iterators
=> APM-709 Update iresearch with wand

CHANGELOG, arangod/RestServer/arangod.cpp, lib/Basics/CrashHandler.cpp, lib/Basics/CrashHandler.h, lib/Basics/SizeLimitedString.h, tests/Basics/SizeLimitedStringTest.cpp, tests/CMakeLists.txt
Backport of https://github.com/arangodb/arangodb/pull/19540
This fixes a buffer overflow in the crash dumper, which was observed in the wild and prevented us from getting stack traces at all.
=> BTS-1546: Fix buffer overflow in crashdump

CHANGELOG, arangod/GeneralServer/H2CommTask.cpp, arangod/GeneralServer/H2CommTask.h
Backport of https://github.com/arangodb/arangodb/pull/19554
Harden callback functions against exceptions.
These callback functions are called from C code which cannot handle exceptions in any way. Instead, we need to return HPE_INTERNAL (or whatever other error) to the C code to signal that an error occurred.
Also replaced previous occurrences of `return 0` which `return HPE_OK`. `HPE_OK` is defined to `0` in llhttp.h, and is more telling than `return 0`.
=> harden callback functions against exceptions

CMakeLists.txt, tests/Replication2/CMakeLists.txt, tests/Replication2/ReplicatedLog/Components/SnapshotManagerTest.cpp
Disable warning for missing field initializers. It prevents using them partially, which can be useful and convenient.
=> Disable missing-field-initializers warnings

.circleci/base_config.yml, js/apps/system/_admin/aardvark/APP/frontend/js/arango/arango.js
The "sudden" failure is caused by the fact that the CircleCI lint action just installs eslint of the day. This likelly got updated and is now complaining.
This PR fixes the immediate redness, a better fix will be to fix the eslint version for linting jobs.
=> Fix devel CI build.

CHANGELOG, arangod/Pregel/GraphStore/GraphSerdeConfigBuilderCluster.cpp, arangod/Pregel/PregelFeature.cpp
Pregel can work without issues on a OneShard database, so don't error out in that case.
Enterprise part with a test: https://github.com/arangodb/enterprise/pull/1350
=> Make Pregel work on OneShard databases without issues

tests/js/common/shell/shell-collection-api.js
*SmartJoins only work in combination with distributeShardsLike. However old versions allowed to create SmartJoins without it.
This PR reactivates this invalid creation of Collections to avoid breaking change in API. Actual change in Enterprise code*
As this is in no released version on Purpose no CHANGLOG entry written
=> Fixed a backwards incompatible change on SmartJoins

CHANGELOG, arangod/Aql/ExecutionNode.cpp, arangod/Aql/WindowNode.cpp, tests/js/server/aql/aql-window-cumulative-sum.js
*Serialization and deserialization of WINDOW Node in AQL was not working. This caused WINDOW to break on OneShard deployments *
Backport of: https://github.com/arangodb/arangodb/pull/19570
- [] **integration tests**
=> [3.10] Bug fix/window on oneshard (#19570)

js/client/modules/@arangodb/testutils/instance.js
Backport of: https://github.com/arangodb/arangodb/pull/19588
*This PR is supposed to help with collecting information on failed Jenkins runs. It does not apply any bug-fix by itself. It is inspired by the failure visible in this. Jenkins run: https://jenkins01.arangodb.biz/job/arangodb-ANY-linux-matrix.aarch64/640/EDITION=enterprise,STORAGE_ENGINE=rocksdb,TEST_SUITE=cluster,limit=linux&&test&&aarch64/*
In Above Jenkins run we had some issue (which does not matter) and tried to collection AgencyState for it for analytics. This triggered an OOM situation on the arangosh side.
This PR also does not protect against OOM in the situation, but it should reduce the memory footprint of 3times keeping AgencyState in V8 memory down to 2times, reducing the OOM chance, and increasing chance to get …
=> [3.10] Reduce memory footprint while collecting agencydump

js/client/modules/@arangodb/testutils/instance.js
Backport of: https://github.com/arangodb/arangodb/pull/19588
*This PR is supposed to help with collecting information on failed Jenkins runs. It does not apply any bug-fix by itself. It is inspired by the failure visible in this. Jenkins run: https://jenkins01.arangodb.biz/job/arangodb-ANY-linux-matrix.aarch64/640/EDITION=enterprise,STORAGE_ENGINE=rocksdb,TEST_SUITE=cluster,limit=linux&&test&&aarch64/*
In Above Jenkins run we had some issue (which does not matter) and tried to collection AgencyState for it for analytics. This triggered an OOM situation on the arangosh side.
This PR also does not protect against OOM in the situation, but it should reduce the memory footprint of 3times keeping AgencyState in V8 memory down to 2times, reducing the OOM chance, and increasing chance to get …
=> [3.11] Reduce memory footprint while collecting agencydump

js/client/modules/@arangodb/testutils/instance.js
*This PR is supposed to help with collecting information on failed Jenkins runs. It does not apply any bug-fix by itself. It is inspired by the failure visible in this. Jenkins run: https://jenkins01.arangodb.biz/job/arangodb-ANY-linux-matrix.aarch64/640/EDITION=enterprise,STORAGE_ENGINE=rocksdb,TEST_SUITE=cluster,limit=linux&&test&&aarch64/*
In Above Jenkins run we had some issue (which does not matter) and tried to collection AgencyState for it for analytics. This triggered an OOM situation on the arangosh side.
This PR also does not protect against OOM in the situation, but it should reduce the memory footprint of 3times keeping AgencyState in V8 memory down to 2times, reducing the OOM chance, and increasing chance to get usable output.
This is limited to State, because we will look at …
=> Reduce memory footprint while collecting agencydump

arangod/RestHandler/RestDumpHandler.cpp, arangod/RestServer/VocbaseContext.cpp, arangod/RestServer/VocbaseContext.h, arangod/RocksDBEngine/RocksDBDumpManager.cpp, arangod/Utils/CollectionNameResolver.cpp, arangod/Utils/CollectionNameResolver.h, client-tools/Dump/DumpFeature.cpp, lib/Rest/RequestContext.h, tests/js/client/shell/shell-dump-integration.js
https://arangodb.atlassian.net/browse/BTS-1549
BTS-1549: adjust collection access permissions for experimental dump so that they behave as in non-experimental dump
=> BTS-1549: adjust collection access permissions

CHANGELOG, arangod/Aql/ExecutionNode.cpp, arangod/Aql/WindowNode.cpp, tests/js/server/aql/aql-window-cumulative-sum.js
*Serialization and deserialization of WINDOW Node in AQL was not working. This caused WINDOW to break on OneShard deployments *
Backport of: https://github.com/arangodb/arangodb/pull/19570
- [] **integration tests**
=> [3.9] Bug fix/window on oneshard (#19570)

CHANGELOG, arangod/Indexes/IndexIterator.cpp, tests/js/server/aql/aql-index-or-aggregation.js
This addresses https://arangodb.atlassian.net/browse/BTS-1554
See description there.
Original PR for devel: https://github.com/arangodb/arangodb/pull/19571
The bad behaviour comes from the fact that the generic 
IndexIterator::skipImpl which uses the `nextImpl` method
does not look at the return value of `nextImpl` and forgets
to loop to indeed skip as much as required.
- [*] Tests
- [*] Backport for 3.11: This is the backport for 3.11
- [*] Jira ticket: https://arangodb.atlassian.net/browse/BTS-1554
- [*] Jira ticket: https://arangodb.atlassian.net/browse/MDS-1147
=> Fix bug with index in iterator and count aggregation [BTS-1554]

tests/js/common/shell/shell-collection-api.js
**No production impact**
*This PR only adds a test for the existing API. We detected a backwards incompatibly change moving from 3.11 to devel on this specific test. So we add this test in 3.11 as well. to make sure API in 3.11 stays identical.*
=> [3.11][Test_only] Add another test for backwards compatibility on SmartJoins

CHANGELOG, arangod/Aql/ExecutionNode.cpp, arangod/Aql/WindowNode.cpp, tests/js/server/aql/aql-window-cumulative-sum.js
*Serialization and deserialization of WINDOW Node in AQL was not working. This caused WINDOW to break on OneShard deployments *
Backport of: https://github.com/arangodb/arangodb/pull/19570
- [] **integration tests**
=> Bug-Fix 3.11: WINDOW on OneShard

.circleci/base_config.yml, js/apps/system/_admin/aardvark/APP/frontend/js/arango/arango.js
The "sudden" failure is caused by the fact that the CircleCI lint action just installs eslint of the day. This likelly got updated and is now complaining.
This PR fixes the immediate redness, a better fix will be to fix the eslint version for linting jobs.
=> [3.11] Fix devel CI build

arangod/GeneralServer/RestHandler.cpp, arangod/RestHandler/RestDumpHandler.cpp
Fix differences in permission handling between experimental dump and non-experimental dump.
Fixes a nightly test (`scripts/unittest authentication --test dump --cluster true`).
=> fix authentication differences in experimental dump

tests/js/server/replication2/replication2-supervision-replicated-log-target-cluster.js
Fix a flaky test with an overly tight assertion.
=> Fix flaky testChangeLeaderImmediatelyToNewFollower

arangod/RocksDBEngine/RocksDBDumpContext.cpp
Small performance optimization for experimental dump:
Reserve 64k of initial memory in batch string buffers. Ideally this saves the first few reallocations in the buffer, without creating too much overhead in case not much data needs to be produced.
=> micro-performance optimization for experimental dump

client-tools/Dump/DumpFeature.cpp
- build URLs with absl::StrCat instead of simple string concatenation
- remove unused URL parameters "flush" and "ticks" from REST API calls. these parameters had no meaning for a long time
- warn user about overhead when setting `--envelope=true`
=> cleanup PR for arangodump

tests/js/server/aql/aql-window-cumulative-sum.js
*Backport PRs have shown an issue in the test modified here. Namely the non _key sharded collection was empty and hence did not actually run the test. So we now revert to not use any sharding value in the test. Also I accidentially disabled the existing test suite.*
=> Bug-Fix: Window on OneShard Part2

CHANGELOG, arangod/Cluster/ClusterFeature.cpp
*When we shutdown the server, and still have open AgencyCommunication, this could get into crashes. So we now actively cancel all AgencyRequests very late in the shutdown, but before we get into dangerous area. Such a crash should not yield any real issue, as all required steps for a clean shutdown are taken, we are just freeing in-memory objects after it.*
=> [Bug-Fix BTS-1556] Cancel ongoing AgencyCommunication on shutdown

js/apps/system/_admin/aardvark/APP/frontend/js/routers/startApp.js
a single line change - removed `global` keyword at the top of `startApp.js`, which throws a cryptic error and crashes the frontend
Introduced here: https://github.com/arangodb/arangodb/pull/18449/files#diff-0216a3b0e5813d32feeee0f6edbaba7c757c2fcfd573aac1332aed224cc0d790
=> fix: frontend build broken due to a stray keyword

arangod/RocksDBEngine/RocksDBEngine.cpp, arangod/RocksDBEngine/RocksDBSyncThread.cpp, arangod/RocksDBEngine/RocksDBSyncThread.h
This PR attempts to fix the current TSAN issues that were introduced in https://github.com/arangodb/arangodb/pull/19285
- protect the `_syncListeners` with the `_syncListenersMutex`
- `std::move()` the additional `logPersistor` copy
Here is the [tsan.log](https://jenkins.arangodb.biz/job/arangodb-ANY-linux-san.x86-64/2056/EDITION=enterprise,SAN_MODE=TSan,STORAGE_ENGINE=rocksdb,TEST_SUITE=single,limit=linux&&test&&x86-64/artifact/tsan.log.arangod.47013.log) file
Jenkins: https://jenkins01.arangodb.biz/job/arangodb-ANY-linux-san.x86-64/2063/
=> [CINFRA-826] Fix replication2 TSAN

arangod/Cluster/ClusterInfo.cpp, arangod/Network/Methods.cpp, js/client/modules/@arangodb/testutils/instance.js
Slightly improve debuggability:
* when restarting/stopping/resuming instances during testing, we now print not only the instance name but also its address (IP address plus port). this makes it easier to understand from the test output which servers were affected by restarting/stopping/resuming.
* suppress useless error message "did not understand destination ''" from the NetworkFeature that is expected temporarily after a server has unregistered itself from the cluster.
* remove some leftover debug code that was not used anymore.
=> slightly improve debuggability

CMakeLists.txt
Avoid errors on MSVC:
```
cl : Command line error D8021: invalid numeric argument '/Wl,--version' [D:\win03-colo2\oskar\work\ArangoDB\build\package-arangodb-server-nsis.vcxproj]
```
introduced by https://github.com/arangodb/arangodb/pull/19635.
=> Exclude linker detection on MSVC

CHANGELOG, arangod/Cluster/ServerState.cpp
When applying a new license, we are responding slightly earlier than we should. This is just a timing issue and does not impact the license application itself. See the enterprise PR for more details.
[BTS-1124]: https://arangodb.atlassian.net/browse/BTS-1124?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BTS-1124] Waiting for license to be applied

lib/Basics/terminal-utils.cpp
Fix compile error.
This went undetected previously because the code in question was inside some #ifdef and wasn't compiled on any of our targets
=> fix compile error

arangod/Auth/TokenCache.cpp
cppcheck failed during nighly: https://jenkins01.arangodb.biz/job/arangodb-devel-cppcheck/848/  
The warning was related to the `verifyHMAC` call: "Using object that points to local variable 'message' that is out of scope.. Pointer to container is created here.".
cppcheck is overly cautious in this context.  There's nothing indicating that message goes out of scope within the function. The only usage of `validateJwtHMAC256Signature` occurs here:
```cpp
std::string const message = header + "." + body;
if (!validateJwtHMAC256Signature(message, signature)) {
//...
}
```
The underlying data referenced by the `string_view` remains valid for its entire use. Therefore, I suppressed this warning.
cppcheck: https://jenkins01.arangodb.biz/job/arangodb-ANY-cppcheck/980/
=> Suppressing cppcheck warning

Documentation/DocuBlocks/Rest/Administration/get_admin_database_target_version.md
Deprecate `/_admin/database/target-version` API from 3.11 onwards, remove it in 3.12.
Docs PR: https://github.com/arangodb/docs/pull/1448
=> deprecate `/_admin/database/target-version` API

arangod/Agency/Node.cpp, arangod/Agency/Node.h, arangod/Cluster/ClusterInfo.cpp, arangod/Cluster/ClusterInfo.h
https://arangodb.atlassian.net/browse/BTS-1577
Include more data in ClusterInfo memory accounting.
=> BTS-1577: include more data in cluster info memory accounting

CHANGELOG, arangod/GeneralServer/CommTask.cpp, arangod/GeneralServer/RestHandler.cpp, arangod/RestHandler/RestMetricsHandler.cpp
Backport of https://github.com/arangodb/arangodb/pull/19627
Allow compression content-negotation in metrics API, so that responses from the metrics API at `/_admin/metrics` can be sent compressed if the client supports it.
The metrics returned by the `/_admin/metrics` API are returned as a big text string, using only a very limited alphabet. The data should be very well compressible. As metrics are queried from all servers pretty often, we could probably save a lot of traffic at least on idle servers. For busy servers the traffic reduction is probably not significant.
According to the Prometheus docs, it supports content-negotiation and the "gzip" content encoding:
https://prometheus.io/docs/instrumenting/exposition_formats/#text-based-format
Local experiments show that enabling gzip …
=> Allow content negotation for metrics API responses

arangod/Network/Methods.cpp
Potentially fixes https://arangodb.atlassian.net/browse/BTS-1590
`options` object was captured by reference (also in previous versions), but it wasn't guaranteed that it was still alive and valid when the lambda was executed.
Hopefully this fixes the UBSan error
```
/work/ArangoDB/arangod/Network/NetworkFeature.cpp:387:40: runtime error: load of value 94, which is not a valid value for type 'bool'
```
=> BTS-1590: fix undefined behavior

CHANGELOG, js/common/bootstrap/errors.js, lib/Basics/errors.dat, tests/js/client/shell/api/multi/general-graph.js, tests/js/common/aql/aql-insert-multiple-cluster.js
Improve error message when parsing of edge document fails.
This is not an ideal solution, but the error reporting facilities currently do not allow for an error message that reports exactly what the parse error is.
=> [BTS-842] Attempt to somewhat improve error message

PULL_REQUEST_TEMPLATE.md
Remove 3.9 from PR Template, as it is EOL.
=> Remove 3.9 from PR Template

CHANGELOG, arangod/Agency/State.cpp
access to _log needs to be done in mutex. Else other access may garble.
=> BTS-1598: Bug fix/fix unprotected access

client-tools/Dump/DumpFeature.cpp
This PR deprecates the following arangodump startup options:
* `--envelope`: setting this option to true previously wrapped every dumped document into a {data, type} envelope. This was useful for the MMFiles storage engine, where dumps could also include document removals. With the RocksDB storage engine, the envelope only caused overhead and increased the size of the dumps. The default value of `--envelope` was changed to false in ArangoDB 3.9 already, so by default all arangodump invocations since then created non-envelope dumps.
* `--tick-start`: setting this option allowed to restrict the dumped data to some time range with the MMFiles storage engine. It has no effect for the RocksDB storage engine.
* `--tick-end`: setting this option allowed to restrict the dumped data to some time …
=> deprecate arangodump startup options

arangod/Replication2/Methods.cpp, arangod/Replication2/Methods.h, arangod/Replication2/ReplicatedLog/Components/LogFollower.cpp, arangod/Replication2/ReplicatedLog/Components/LogFollower.h, arangod/Replication2/ReplicatedLog/ILogInterfaces.h, arangod/Replication2/ReplicatedLog/LogLeader.cpp, arangod/Replication2/ReplicatedLog/LogLeader.h, arangod/Replication2/ReplicatedState/ReplicatedState.h, arangod/Replication2/ReplicatedState/ReplicatedStateFeature.h, arangod/Replication2/StateMachines/BlackHole/BlackHoleStateMachine.cpp, arangod/Replication2/StateMachines/BlackHole/BlackHoleStateMachine.h, arangod/Replication2/StateMachines/BlackHole/BlackHoleStateMachineFeature.cpp, tests/Replication2/Mocks/FakeFollower.cpp, tests/Replication2/Mocks/FakeFollower.h, tests/Replication2/ReplicatedLog/ReplicatedLogConnectTest.cpp, tests/Replication2/ReplicatedState/StateManagerTest.cpp, tests/js/common/shell/shell-replicated-logs-cluster.js
Remove the public release API of replicated logs: It must only ever be used by the corresponding replicated state.
In order to keep js-tests working, implement `release` via the `black-hole` state machine (only).
Improved runtime of `testRelease` in `shell-replicated-logs-cluster.js`.
=> [CINFRA-825] Remove external release api from replicated log

client-tools/Dump/DumpFeature.cpp
Small internal improvements for arangodump:
- add trace log messages to see what it is doing
- save collection name in shard => file map to avoid extra lookup later
- rename a function to make its purpose more clear
- make sure started threads are properly shut down even if an exception happens
=> minor internal improvements for arangodump

CHANGELOG, js/common/modules/@arangodb/aql/explainer.js
Fix https://arangodb.atlassian.net/browse/BTS-1380 and https://arangodb.atlassian.net/browse/BTS-1381
* BTS-1380: Added traversal order (dfs, bfs, weighted) to explain output.
=> Fixed BTS-1380

CHANGELOG, arangod/RocksDBEngine/RocksDBEngine.cpp, arangod/RocksDBEngine/RocksDBUpgrade.cpp
Docs PR: https://github.com/arangodb/docs/pull/1465
* Refuse server startup with outdated little-endian on-disk format. The little-endian on-disk format was used for deployments that were created with either ArangoDB 3.2 or 3.3 when using the RocksDB storage engine. Since ArangoDB 3.4, a big-endian on-disk format was used for the RocksDB storage engine, which is more performant. Deployments that were set up with the RocksDB storage engine using ArangoDB 3.2 or 3.3 and that have been upgraded since then will still use the old format. This should not affect many users, because the default storage engine in ArangoDB 3.2 and 3.3 was the MMFiles storage engine. Furthermore, deployments that have been recreated from an arangodump since ArangoDB 3.4 will not be affected, because restoring an …
=> Refuse server startup with outdated little-endian on-disk format.

CHANGELOG, arangod/Pregel/Conductor/Conductor.cpp, arangod/Pregel/PregelFeature.cpp, arangod/Pregel/PregelFeature.h, js/common/modules/@arangodb/graph/pregel-test-helpers.js, tests/js/common/shell/shell-pregel-basics-example.js, tests/js/common/shell/shell-pregel-random.js, tests/js/common/shell/shell-pregel-start-cluster.js, tests/js/common/shell/shell-pregel-status-writer.js
Fix issues with Pregel garbage-collection
When dropping a database, the Pregel conductor will still hold a ref count for the already-dropped database, until the conductor is garbage-collected.
Garbage-collection for conductors only happens every ~20s, and by default only after a timeout that is too long for being useful in integration tests.
This PR changes the conductor garbage collection so that conductors of dropped databases can be cleaned up even before their TTL has expired.
The PR also adds an extra round of garbage collection in the stop phase of the PregelFeature, because when performing the garbage collection in the unprepare phase only, assertion failures can occur. The problem is that garbage-collecting conductors can post to the scheduler, which is already forbidden during …
=> fix issues with Pregel garbage-collection

CHANGELOG, arangod/Aql/Ast.cpp, arangod/Aql/Ast.h, arangod/Aql/grammar.cpp, arangod/Aql/grammar.hpp, arangod/Aql/grammar.y, tests/js/server/aql/aql-collect-subquery-scope-regression.js
Minimal backport of https://github.com/arangodb/arangodb/pull/19709
* Fixed a loophole in COLLECT variable name validation: in COLLECT INTO expressions it was possible to refer to variables that the COLLECT just introduced. This was undefined behavior and not caught by the previous version of COLLECT's variable checking.
=> Fixed COLLECT variable validation loophole

CHANGELOG, arangod/RocksDBEngine/RocksDBBuilderIndex.cpp, arangod/RocksDBEngine/RocksDBDumpManager.cpp, arangod/RocksDBEngine/RocksDBEngine.cpp, arangod/RocksDBEngine/RocksDBEngine.h, arangod/RocksDBEngine/RocksDBKeyBounds.cpp, arangod/RocksDBEngine/RocksDBUpgrade.cpp, arangod/RocksDBEngine/RocksDBUpgrade.h, js/common/bootstrap/errors.js, lib/Basics/errors.dat, tests/RocksDBEngine/KeyTest.cpp
This addresses https://arangodb.atlassian.net/browse/BTS-1541
Overview: In 3.2 and 3.3 we have created the ArangoDB/RocksDB instance
with little endian key encoding, which was a very bad idea for
performance. Newer versions use big endian key encoding, which is much
better. However, legacy databases created in 3.2 and 3.3 continue to use
the old encoding and new versions should be compatible with this.
This PR fixes some compatibility problems and ensures that newer code,
which relies on the old encoding cannot be executed any more, if the
underlying format is still little endian key encoding.
More specifically:
- A method in RocksDBKeyBounds.cpp is fixed which computes a wrong
key range for persistent indexes in the little endian key encoding
case.
- Another method which computes a range …
=> Fix bugs around legacy little endian key encoding format

CHANGELOG, arangod/Aql/QueryRegistry.cpp, arangod/Aql/RemoteExecutor.cpp, tests/js/server/aql/aql-failures-cluster.js
If a query throws an error right now (most likely timeout) all DBServers are informed with this error, that the query will fail. However so far they only react on "query killed" to locally abort. With this PR we enable that every error triggers a kill query on all snippets, so we avoid to wait for garbage collection and can quickly stop working on the query.
=> [BTS-1460][3.10] Directly kill aborted query, do not wait for GC 

arangod/Agency/Node.cpp, arangod/Agency/Node.h
Due to an oversight, velocypack data in arrays was not accounted for.
Should improve memory accounting and fix an issue reported in https://arangodb.atlassian.net/browse/BTS-1584
=> Fix MemoryAccounting Agency Node Array

arangod/RocksDBEngine/RocksDBMethodsMemoryTracker.cpp
Fix an assertion failure during chaos testing (`scripts/unittest chaos --cluster true --skipNightly false`).
=> fix an assertion failure in chaos tests

arangod/RocksDBEngine/RocksDBMethodsMemoryTracker.cpp
Fix assertion failure in memory tracking that happens during chaos tests
=> Der Tragödie zweiter Teil

arangod/Aql/Functions.cpp
This is a follow-up commit to slightly optimize some new code from
```
commit d5bf9079c948d1ded3532efca1c0dbf86c1f1fb0
Date:   Tue Sep 12 15:39:50 2023 +0200
Build up result object in a map for non-recursive array case. (#19754)
```
The PR changes the iteration order for objects from index table order to sequential order, which is advantageous for prefetching data and to avoid "random" jumps in memory.
This should not change any other behavior or functionality.
=> This is a follow-up commit to slightly optimize some new code from

arangod/RestServer/DatabaseFeature.cpp
Fix wrong version number in options documentation.
Option currently reports 3.11.20, but should be 3.11.2.
=> fix wrong version number in options documentation

CHANGELOG, arangod/IResearch/IResearchAnalyzerFeature.cpp
If analyzers collection was imported on single server from cluster dump - analyzers might have non zero revisions.
That was preventing load of analyzer as Single server also checked the revision but expected only 0.
This PR disables checking revisions for SingleServer
=> [BTS-1613] Do not check revisions on single

arangod/Network/NetworkFeature.cpp, arangod/Network/NetworkFeature.h
Fix UB in NetworkFeature
in case a specific failure point was set for the NetworkFeature, this could lead to two threads racing for modifying the same Promise. this could cause random failures, the most prominent one seems to have been the exception "Promise already satisfied.".
This does not affect any released version.
=> fix UB in NetworkFeature

etc/testing/arangod-common.conf, tests/js/client/server_parameters/log-json-no-shorten.js, tests/js/client/server_parameters/log-json-shorten.js, tests/js/client/server_parameters/log-json.js
Add thread-id to log output during tests.
This improves usability of logs when debugging multi-thread issues.
=> add thread-id to log output during tests

arangod/Aql/AqlCall.cpp, arangod/Aql/AqlCall.h, arangod/Aql/EnumerateCollectionExecutor.cpp, arangod/Aql/EnumerateListExecutor.cpp, arangod/Aql/EnumeratePathsExecutor.cpp, arangod/Aql/IResearchViewExecutor.tpp, arangod/Aql/SortExecutor.cpp, arangod/Aql/SubqueryStartExecutor.cpp, arangod/Aql/TraversalExecutor.cpp, tests/Aql/ExecutionBlockImplTest.cpp, tests/Aql/SplicedSubqueryIntegrationTest.cpp
Clean up AqlCall.
Remove AqlCall::shouldSkip(), because its implementation was redundant with AqlCall::needSkipMore(), and adjust all callers to call AqlCall::needSkipMore() instead.
Also fix typos in AqlCall error messages and remove an unused include.
=> clean up AqlCall

arangod/Aql/AqlCall.h, arangod/Aql/AqlCallList.cpp, arangod/Aql/AqlCallList.h, arangod/Aql/AqlCallStack.cpp, arangod/Aql/AqlCallStack.h, arangod/Aql/AqlItemBlockInputRange.cpp, arangod/Aql/AqlItemBlockInputRange.h, arangod/Aql/AsyncExecutor.cpp, arangod/Aql/AsyncExecutor.h, arangod/Aql/ConstFetcher.cpp, arangod/Aql/ConstFetcher.h, arangod/Aql/DependencyProxy.cpp, arangod/Aql/DependencyProxy.h, arangod/Aql/ExecutionBlockImpl.tpp, arangod/Aql/IResearchViewExecutor.tpp, arangod/Aql/MultiDependencySingleRowFetcher.cpp, arangod/Aql/MultiDependencySingleRowFetcher.h, arangod/Aql/OutputAqlItemRow.cpp, arangod/Aql/OutputAqlItemRow.h, arangod/Aql/RemoveModifier.cpp, arangod/Aql/SingleRowFetcher.cpp, arangod/Aql/SingleRowFetcher.h, arangod/Aql/UpdateReplaceModifier.cpp, arangod/Aql/UpsertModifier.cpp, arangod/Graph/PathManagement/PathValidatorOptions.h, arangod/Pregel/Algos/ShortestPath/ShortestPath.cpp, tests/Aql/DependencyProxyMock.cpp, tests/Aql/DependencyProxyMock.h
Some further small AQL refactoring:
- make several methods const and/or noexcept
- make `AqlCallStack` parameters const where applicable
- avoid copy of `_dependencySkipReports` in MultiDependencySingleRowFetcher.cpp
- remove unused includes
- added `operator<<` support for `OutputAqlItemBlock`
=> some further small AQL refactoring

js/client/modules/@arangodb/testsuites/dump.js
The wrong testsuite had this disabled for working around BTS-1617
=> disable the right test

tests/js/client/shell/api/arangosearch-memory-metrics.inc
Attempt to fix this error in latest nightly build:
```
=== shell_client_0 ===
* Test "shell_client_0"
[FAILED]  tests/js/client/shell/shell-improved-metrics-accounting-cluster.js
"testArangoSearchMetrics_Repl" failed: Error: at assertion #9: assertTrue: (false) does not evaluate to true
(Error
at Object.testArangoSearchMetrics (tests/js/client/shell/api/arangosearch-memory-metrics.inc:101:11)
at tests/js/client/shell/shell-improved-metrics-accounting-cluster.js:83:9
at tests/js/client/shell/shell-improved-metrics-accounting-cluster.js:99:3
...    at Object.shellClient [as shell_client] (/work/ArangoDB/js/client/modules/@arangodb/testsuites/aql.js:226:79)
- test failed
Suites failed: 1 Tests Failed: 1
```
=> Fix test for arangodb_search_writers_memory_usage

CHANGELOG, arangod/Replication/DatabaseInitialSyncer.cpp, arangod/Replication/DatabaseInitialSyncer.h, arangod/Replication/DatabaseTailingSyncer.cpp, arangod/Replication/DatabaseTailingSyncer.h, arangod/Replication/Syncer.cpp, arangod/Replication/Syncer.h
Make replication WAL tailing schedule prefetch requests via the global scheduler, in the same way as the initial dump phase does. In the best case, this can speed up the getting-in-sync phase when getting shards in sync.
Prefetching is automatically enabled and will be used during shard synchronization, in single-to-single replication and active failover.
The PR also improves the existing `JobSynchronizer` in Syncer.h/cpp to not wait for the job to be executed by the scheduler if the main thread is actually quicker. This can further improve replication performance on servers that have longer scheduler queues. Now the prefetching will be executed by either the scheduler or by the main thread, whichever is first.
=> Add prefetching for WAL tailing

CHANGELOG, arangod/Transaction/Methods.cpp, tests/js/client/chaos/test-chaos-load-common.inc, tests/js/client/shell/shell-document-keepnull-cluster.js
Backport of https://github.com/arangodb/arangodb/pull/19807
Fixed issue with `keepNull=false` updates not being properly replicated to followers.
=> Fixed issue with `keepNull=false` updates

CHANGELOG
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/1382
Remove special handling for backups taken with ArangoDB 3.5 in hot backup restore.
=> Remove special handling for backups taken with ArangoDB 3.5

CHANGELOG, arangod/Cache/PlainCache.cpp, arangod/Cache/PlainCache.h, arangod/Cache/TransactionalCache.cpp, arangod/Cache/TransactionalCache.h
The previous implementation of the function called `getBucket()` for each slot it looked at. 
`getBucket()` then acquired a shared pointer on the underlying table, which is not lock-free on x86_64. Instead, the calls to `Cache::table()` are guarded via a pthread_mutex_lock and _unlock, which has prohibitive costs when called too often.
The code is now changed so that there is a `getBucket()` overload which gets the Table pointer from the outside, avoiding repeated calls to acquire the Table pointer from `freeMemoryWhile()`.
=> make {Plain,Transactional}Cache::freeMemoryWhile() cheaper

CHANGELOG
Fixes https://arangodb.atlassian.net/browse/MDS-1157
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/1384
v3.11.3 always reported "potentiallyInconsistent": true for all backups
taken, regardless of whether they were actually consistent.
this is a regression compared to v3.11.2.
now all backups taken report as "potentiallyInconsistent": false,
because of the changed way that hot backups are taken since v3.11.3
(there are no inconsistent backups anymore).
=> fix taking hot backups with allowInconsistent=false

arangod/Cache/PlainCache.cpp
Improve PlainCache::freeMemoryWhile() performance as in other branches.
The last merged PR did not fully implement the improvement.
Note: PlainCache is not used in devel, so effectively this won't make any difference.
=> improve PlainCache::freeMemoryWhile() performance

arangod/Cache/Cache.cpp, arangod/Cache/PlainCache.cpp, arangod/Cache/TransactionalCache.cpp
Further improve performance of `freeMemoryWhile`, by not invoking the callback function if nothing was reclaimed.
=> further improve performance of `freeMemoryWhile`

arangod/Aql/ExecutionBlockImpl.tpp, arangod/Aql/ExecutionNode.cpp, arangod/Aql/MaterializeExecutor.cpp, arangod/Aql/MaterializeExecutor.h
This is the first clean up step for the materialize executor. The executor had two template parameters, but only two of the possible four combinations were used, while only three of them were actually compiled.
In the end, what matters is if the documents are materialized using a local document id or a arango search document id.
More simplifications will follow.
=> Remove weird template parameter.

CHANGELOG, Documentation/Metrics/rocksdb_cache_free_memory_tasks_duration_total.yaml, Documentation/Metrics/rocksdb_cache_free_memory_tasks_total.yaml, Documentation/Metrics/rocksdb_cache_migrate_tasks_duration_total.yaml, Documentation/Metrics/rocksdb_cache_migrate_tasks_total.yaml, arangod/Cache/Manager.cpp, arangod/Cache/Manager.h, arangod/Cache/ManagerTasks.cpp, arangod/RocksDBEngine/RocksDBEngine.cpp
Backport of https://github.com/arangodb/arangodb/pull/19841
* Added the following metrics to improve observability of in-memory cache subsystem:
- `rocksdb_cache_free_memory_tasks_total`: total number of `freeMemory` tasks scheduled
- `rocksdb_cache_migrate_tasks_total`: total number of `migrate` tasks scheduled
- `rocksdb_cache_free_memory_tasks_duration_total`: total time (microseconds) spent in `freeMemory` tasks
- `rocksdb_cache_migrate_tasks_duration_total`: total time (microseconds) spent in `migrate` tasks
=> add more cache metrics

arangod/Cluster/ClusterTypes.h, arangod/Cluster/ServerState.cpp, arangod/Cluster/ServerState.h
Backport of https://github.com/arangodb/arangodb/pull/17878
Fix https://arangodb.atlassian.net/browse/BTS-1440 in 3.10.
=> Make ServerState::_rebootId atomic (#17878)

arangod/Aql/ExecutionNode.cpp, arangod/Aql/ExecutionNode.h, arangod/Aql/IndexNodeOptimizerRules.cpp, arangod/Aql/MaterializeExecutor.cpp, arangod/Aql/MaterializeExecutor.h
1. Remove unused template parameter from `MaterializeSingleNode`.
2. Rename `MaterializeSingleNode` to `MaterializeRocksDBNode` because that is what it does.
3. Remove template parameter from `MaterializeExecutorInfos` and simplify. Store aql collection pointer instead of collection name.
=> More MaterializeExecutor cleanup.

arangod/V8Server/V8DealerFeature.cpp
Fix misleading text in documentation for startup option `--javascript.enable`.
=> fix documentation for startup option

CHANGELOG, arangod/Cluster/ClusterMethods.cpp, arangod/Transaction/Manager.cpp, arangod/Transaction/Manager.h
* Abandon expired local hot backup locks on coordinators a bit later than before. Previously, the timeout was `timeout + 5` seconds on each coordinator. There can be issues when multiple coordinators need to acquire the lock, so that the first coordinator acquires the lock successfully and its unlock clock starts ticking, whereas the subsequent coordinators may need to lock acquire the lock. In this case, the lock on the first coordinators could have been released already, even though the backup hasn't even started. This PR increases the per-coordinator timeout to `timeout + 30` seconds, which improves the situation, but is still not 100% safe.
* Improve logging in case hot backup locks cannot be taken on coordinators.
=> better reporting for hotbackup errors

CHANGELOG, arangod/Aql/IndexNode.cpp, arangod/Aql/IndexNode.h, tests/js/server/aql/aql-projections.js
The purpose of this PR is to **prevent** a bug that has affected 3.10. The bug does not occur in devel, due to changes in optimizer behavior and [projections handling](https://github.com/arangodb/arangodb/pull/17465). However, because the prevention mechanism is pretty simple, it's well worth doing it. In case the projections algorithm ever becomes more pessimistic, this would prevent the bug.
Also, I believe the integration test would be a good addition to our suite.
For an in-depth explanation, see https://github.com/arangodb/arangodb/pull/19864
=> [BTS-1618] Prevent projection problems

CHANGELOG, arangod/Aql/IndexNode.cpp, arangod/Aql/IndexNode.h, tests/js/server/aql/aql-projections.js
_For a more in-depth explanation, see this [recording](https://drive.google.com/file/d/1xd9Dm0H_Nnra_8gPcAXPdLPhFQleZvDG/view?usp=sharing)_
**Problem**
Assume we have a collection where each document has the field "p", with subfields "s" and "k". For example:
```
{"p": {"s": 1234, "k": "hund"}}
{"p": {"s": 1235, "k": "katze"}}
```
There's an index created on ["p.s", "p.k"].
Given the following query:
```aql
FOR doc in @@coll
FILTER doc.p.k == 'hund'
SORT doc.p.s DESC
RETURN doc.p.s
```
This should return `[1234]`, but on 3.10 it returns `[]`.
**Key observations**
Notice the sub-optimal usage of the index. If we were to create the index on ["p.k", "p.s"], not only the query would be faster, but the returned result would be correct. However, the bug is still there.  
It is also important to …
=> [BTS-1618] Empty AQL Query Result

arangod/Cache/Manager.cpp, tests/Cache/Manager.cpp
Backport of https://github.com/arangodb/arangodb/pull/19853
Fix a potential recursive lock invocation.
This only happened if the cache manager was destroyed while caches were still in use. 
In this case, the Manager's dtor called `Manager::shutdown()`, which went through all still-available caches, and called `Cache::shutdown()` on them. The Cache shutdown would call `Manager::unregisterCache(), which could acquire the Manager `_lock`, and then remove the Cache object from the map of caches (_caches). If the last shared_ptr to the Cache was destroyed, the Cache's dtor could try to call into the Manager for a memory allocation ajdusted. this could against acquire the Manager's `_lock` again, so there would be a recursive invocation.
This only happened upon shutdown, and in no released …
=> fix potential recursive lock invocation

arangod/RocksDBEngine/RocksDBMetaCollection.cpp
Fix assertion failure
UseSyncByRevision() can return false nowadays once a collection is marked as deleted. The deletion can even happen while RocksDBSettingsManager::sync() is running. We can thus ignore all collections here for which useSyncByRevision() returns false.
No backports required because the behavior is different in previous versions.
=> fix assertion failure

arangod/Graph/Cache/RefactoredTraverserCache.cpp
Performance optimization: 
Avoid duplicate creation of edge AqlValues inside single-server- or DB-server-based traversals. 
The previous version of the code always built the AqlValue container for the edge data twice, both when no projections were used and when projections were used. when projections were used, the result value was always reverted to the full edge, e.g. the projections optimization was not used.
Backport of https://github.com/arangodb/arangodb/pull/19889
=> avoid duplicate creation of edge AqlValues

arangod/Aql/IndexJoin/GenericMerge.h, arangod/Aql/JoinExecutor.cpp, arangod/Aql/JoinExecutor.h, arangod/Aql/JoinNode.cpp, arangod/Aql/JoinNode.h, arangod/Aql/OptimizerRules.cpp, arangod/RocksDBEngine/RocksDBVPackIndex.cpp, js/common/modules/@arangodb/aql/explainer.js, tests/js/server/aql/aql-index-join-noncluster.js
This PR adds support for projections to the JoinNode/JoinExecutor. Now it can handle queries like
```
for doc1 in c1
sort doc1.c
for doc2 in c2
filter doc1.x == doc2.y
return [doc1.x, doc2.y]
```
without loading the documents. It should have support for stored values already, but this I haven't tested yet.
=> Projections for JoinNode

CHANGELOG, arangod/ClusterEngine/ClusterCollection.cpp, tests/js/common/shell/shell-index.js
Backport of https://github.com/arangodb/arangodb/pull/19900
* Fix updating of collection properties (schema) when the collection has a view on top.
Fixes https://arangodb.atlassian.net/browse/OASIS-25523
=> Fix updating of collection properties when there are views

arangod/Aql/JoinExecutor.cpp, arangod/Aql/JoinNode.cpp, tests/js/server/aql/aql-index-join-noncluster.js
The projections PR only added projections for values from the index. But arangodb assumes that we also support projections from documents.
=> Add document projections for join nodes.

js/common/modules/@arangodb/testutils/document-state-helper.js, tests/js/server/replication2/replication2-replicated-state-document-store.js
After we drop an index, we expect the `DropIndex` log entry to be replicated. However, we can only know for sure that this happened once the index is removed from the `Current` entry of the shard. Before, in `isIndexInCurrent` we used `Object.values(shards).every(...)`, which checks that every shard still has the index. However, some shards may remove the index before others, so using `every` is prone to errors. We have to use `some` instead, which signals that the index is still in `Current` even if if that's true for only one shard.
=> [CINFRA-851] Fixing DropIndex test

arangod/Aql/OptimizerRulesFeature.cpp, tests/js/server/aql/aql-optimizer-stats-noncluster.js
The Join rule is currently disabled by default. To use the join node, it has to be explicitly enabled.
This PR changes this behavior.  As a consequence of this, some queries in the tests will be optimized differently.
=> Enable Join Rule

.circleci/base_config.yml, CMakePresets.json
Adds building without V8 which was added in ~#19879~ #19907 to CircleCI to prevent bitrot.
=> Build without V8 on CircleCI

js/client/modules/@arangodb/arango-query-cursor.js, js/common/modules/@arangodb/aql/explainer.js, tests/js/client/shell/api/cursor.js, tests/js/client/shell/shell-statement.js
improve client-side cursor API by providing the follow extra functions for ArangoQueryCursor:
- cached(): returns true if the cursor result came from a cached query, false otherwise
- stream(): returns true if the cursor is from a streaming query, false otherwise
- retriable(): returns true if the cursor supports retriable fetching of the last batch, false otherwise
also improve explain output for `JoinNode`, so that it looks similar to the output from IndexNodes.
=> improve client-side cursor API

arangod/Aql/Functions.cpp, arangod/Aql/SkipResult.cpp, arangod/Graph/GraphManager.cpp, arangod/IResearch/IResearchAnalyzerFeature.cpp, arangod/IResearch/VelocyPackHelper.cpp, arangod/RestHandler/RestImportHandler.cpp, arangod/RestHandler/RestIndexHandler.cpp, arangod/RocksDBEngine/RocksDBOptimizerRules.cpp
Replace several calls to deprecated APIs with alternatives.
Deprecated APIs are APIs that are marked with the `[[deprecated]]` attribute and thus produce compile warnings when compiling with `-Wdeprecated-declarations`.
=> replace several calls to deprecated APIs

CHANGELOG, arangod/Aql/Projections.cpp, arangod/ClusterEngine/ClusterIndexFactory.cpp, arangod/IResearch/IResearchRocksDBInvertedIndex.cpp, arangod/Indexes/IndexFactory.cpp, arangod/Indexes/IndexFactory.h, arangod/RocksDBEngine/RocksDBIndexFactory.cpp, arangod/RocksDBEngine/RocksDBVPackIndex.cpp, tests/js/common/shell/shell-index-stored-values.js
Docs PR: https://github.com/arangodb/docs-hugo/pull/275
Allow usage of `_id` attribute in stored values of persistent indexes.
Using the `_id` attribute in stored values was previously forbidden. It is still unsupported to use the `_id` attribute as part of normal index attributes.
TODO: adjust existing tests, add new tests.
=> Allow usage of `_id` attribute in stored values of persistent indexes

arangod/RestHandler/RestQueryHandler.cpp
Docs PR: https://github.com/arangodb/docs-hugo/pull/272
Always return `warnings` attribute for `/_api/query`.
Previously the attribute was only returned if there were warnings. This puts unnecessary burden on the caller.
=> always return `warnings` attribute for `/_api/query`

3rdParty/tzdata/windowsZones.xml
Refresh timezone database as of 16.10.2023.
=> Refresh timezone database as of 16.10.2023 (3.11)

CHANGELOG, arangod/Aql/AqlCallStack.cpp, arangod/Aql/AqlCallStack.h, arangod/Aql/ExecutionBlockImpl.cpp, arangod/Aql/OutputAqlItemRow.cpp, arangod/Aql/ShadowAqlItemRow.cpp, arangod/Aql/SubqueryStartExecutionNode.cpp, tests/Aql/AqlItemBlockHelper.h, tests/Aql/CalculationExecutorTest.cpp, tests/Aql/CountCollectExecutorTest.cpp, tests/Aql/DistinctCollectExecutorTest.cpp, tests/Aql/EnumerateCollectionExecutorTest.cpp, tests/Aql/EnumerateListExecutorTest.cpp, tests/Aql/ExecutorTestHelper.h, tests/Aql/FilterExecutorTest.cpp, tests/Aql/HashedCollectExecutorTest.cpp, tests/Aql/NoResultsExecutorTest.cpp, tests/Aql/ReturnExecutorTest.cpp, tests/Aql/ShadowRowForwardingTest.cpp, tests/Aql/SortExecutorTest.cpp, tests/Aql/SortedCollectExecutorTest.cpp, tests/Aql/SplicedSubqueryIntegrationTest.cpp, tests/Aql/SubqueryStartExecutorTest.cpp, tests/Aql/WindowExecutorTest.cpp, tests/CMakeLists.txt, tests/js/server/aql/aql-subquery-splicing-regression-2.js
Backport of: https://github.com/arangodb/arangodb/pull/19778
Mostly Straight forward Cherry-pick
Only the ExecutionBlockImpl file is reordered in comparison to 3.11 and newer.
Non-relevant shadow rows (which mark the end of an iteration of an _outer_ subquery) must make an execution block return the output it has accumulated so far. When an aql item block starts with a non-relevant shadow row (i.e. it ends the iteration of an _outer_ subquery), this previously did not happen correctly, and nodes would collect more output into the same block. This would then lead pass-through nodes to return early (when encountering the non-relevant shadow row), thereby dropping some rows. In maintainer mode, this would lead to an assertion.
What was missing is that in such a scenario, a node must pop …
=> 3.10: [BTS-1610] Fix shadowrow forwarding 

CHANGELOG, arangod/Cache/Cache.cpp, arangod/Cache/Cache.h, arangod/Cache/Manager.cpp, arangod/Cache/Manager.h, arangod/Cache/ManagerTasks.cpp, arangod/Cache/PlainCache.cpp, arangod/Cache/PlainCache.h, arangod/Cache/Table.cpp, arangod/Cache/TransactionManager.cpp, arangod/Cache/TransactionManager.h, arangod/Cache/TransactionalCache.cpp, arangod/Cache/TransactionalCache.h, arangod/RocksDBEngine/RocksDBEngine.cpp, tests/Cache/TransactionManager.cpp
Backport of https://github.com/arangodb/arangodb/pull/19958
Reduce number of shared_ptr copies in cache subsystem
- `Cache::migrate()` migrates data for all buckets in a cache table. for each bucket, it calls `migrateBucket(...)`. `migrateBucket` created a copy of the table's atomic shared_ptr, which internally uses a lock. this is now changed so that the table pointer is passed into the call to `migrateBucket`, so that we do not need to copy the shared_pointer repeatedly. this saves n copies of the atomic shared_ptr, where n is the size of the table.
- `Cache::requestMigrate(...)` also created a copy of the table's atomic shared_ptr, which is now saved by passing the table pointer into the function.
- `Cache::reportInsert()` could be called after inserting data into a cache table. …
=> Reduce number of shared_ptr copies in cache subsystem

arangod/RestHandler/RestBaseHandler.cpp
Potential bugfix.
Add potentially missing response header to all `generateResult(...)` overloads. Previously, the response header was only set in one of the overloads, which looks strange.
=> add potentially missing response headers

arangod/Utils/CursorRepository.h
Do not restrict AQL cursor garbage collection too much.
Otherwise it may have trouble keeping up with foreground query work, and cursors may pile up and consume lots of memory.
=> do not restrict AQL cursor garbage collection too much

arangod/Aql/Aggregator.cpp, arangod/Aql/AqlFunctionsInternalCache.cpp, arangod/Aql/AqlItemBlock.cpp, arangod/Aql/AqlValue.cpp, arangod/Aql/AqlValue.h, arangod/Aql/AqlValueMaterializer.cpp, arangod/Aql/AqlValueMaterializer.h, arangod/Aql/Ast.cpp, arangod/Aql/Expression.cpp, arangod/Aql/FixedVarExpressionContext.cpp, arangod/Aql/Functions.cpp, arangod/Aql/HashedCollectExecutor.cpp, arangod/Aql/IndexExecutor.cpp, arangod/Aql/Query.cpp, arangod/Aql/QueryCursor.cpp, arangod/Aql/SortedCollectExecutor.cpp, arangod/Aql/SubqueryEndExecutor.cpp, arangod/Aql/Variable.cpp, arangod/Graph/BaseOptions.cpp, arangod/Graph/Cursors/RefactoredSingleServerEdgeCursor.cpp, arangod/IResearch/AqlHelper.h, arangod/IResearch/IResearchFeature.cpp, arangod/VocBase/ComputedValues.cpp, tests/Aql/AqlValueMemoryLayoutTest.cpp
It reduces complexity and speedup cases without externals.
ManagedDoc currently used inside execution block, for things like early pruning.
In such cases using slice with pointer almost same, exception is only some unrealistic cases like:
```
FOR d in c FILTER [d] == [...] RETURN ...
FOR d in c FILTER {"...": d} == {...} RETURN ...
```
TODO:
* remove AqlValueMaterializer
* remove most call resolveExternal(s)
=> Remove ManagedDoc and resolveExternals

.circleci/base_config.yml
This way our own timeout mechanism can kick in and gather more information.
=> Increase the CircelCI no_output_timeout

tests/js/client/shell/transaction/shell-transaction-cluster.js
Follow-up to https://github.com/arangodb/arangodb/pull/19984
Also disabling the replication2 part of `shell-transaction-cluster.js`
=> Disable one more replication2 test

lib/ProgramOptions/ProgramOptions.cpp
Do not ignore `--javascript.*` startup options when building with V8. The previous implementation accepted all `--javascript.*` startup options unconditionally even when V8 was enabled.
=> do not ignore `--javascript.*` startup options

arangod/Cluster/ClusterInfo.cpp, arangod/Cluster/ClusterInfo.h
Remove `_clusterId` member.
This member was only populated once when querying the list of databases, but it was not used for anything afterwards. It was also not thread-safe.
=> remove `_clusterId` member

tests/js/client/active-failover/basic.js
Retry requests in active_failover test.
The motivation is to make tests more reliable when servers get suspended and restarted.
Test-only change.
=> retry requests in active_failover test

CHANGELOG, arangod/Aql/AqlCallStack.cpp, arangod/Aql/AqlCallStack.h, arangod/Aql/ExecutionBlockImpl.tpp, arangod/Aql/OutputAqlItemRow.cpp, arangod/Aql/ShadowAqlItemRow.cpp, arangod/Aql/SubqueryStartExecutionNode.cpp, tests/Aql/AqlItemBlockHelper.h, tests/Aql/CalculationExecutorTest.cpp, tests/Aql/CountCollectExecutorTest.cpp, tests/Aql/DistinctCollectExecutorTest.cpp, tests/Aql/EnumerateCollectionExecutorTest.cpp, tests/Aql/EnumerateListExecutorTest.cpp, tests/Aql/ExecutorTestHelper.h, tests/Aql/FilterExecutorTest.cpp, tests/Aql/HashedCollectExecutorTest.cpp, tests/Aql/NoResultsExecutorTest.cpp, tests/Aql/ReturnExecutorTest.cpp, tests/Aql/ShadowRowForwardingTest.cpp, tests/Aql/SortExecutorTest.cpp, tests/Aql/SortedCollectExecutorTest.cpp, tests/Aql/SplicedSubqueryIntegrationTest.cpp, tests/Aql/SubqueryStartExecutorTest.cpp, tests/Aql/WindowExecutorTest.cpp, tests/CMakeLists.txt, tests/js/server/aql/aql-subquery-splicing-regression-2.js
Backport of: https://github.com/arangodb/arangodb/pull/19778
Straight forward Cherry-pick
Non-relevant shadow rows (which mark the end of an iteration of an _outer_ subquery) must make an execution block return the output it has accumulated so far. When an aql item block starts with a non-relevant shadow row (i.e. it ends the iteration of an _outer_ subquery), this previously did not happen correctly, and nodes would collect more output into the same block. This would then lead pass-through nodes to return early (when encountering the non-relevant shadow row), thereby dropping some rows. In maintainer mode, this would lead to an assertion.
What was missing is that in such a scenario, a node must pop calls from all call lists with a depth lower than the encountered shadow row; i.e., from …
=> 3.11: [BTS-1610] Fix shadowrow forwarding 

arangod/Aql/IndexExecutor.cpp
Fix query performance regression for queries that used projections that were covered by indexes.
The regression was unintentionally introduced by d13e0a2232e4393a0e086ef7cae95b1091f284a3, and made queries with covering indexes not use projections from the index data.
=> fix query performance regression

.circleci/base_config.yml
At the moment we build the community instead of enterprise version.
=> Rename CircleCI Windows job

arangod/Agency/Node.h
Since this bug is still present https://github.com/arximboldi/immer/issues/182 we should use a different memory policy for the agency nodes.
=> Agency Nodes Free list Fix

tests/js/client/active-failover/disconnected-leader-nonwindows-nocov-noasan.js
As the comment says, it might or might not happen that the collection `cname + "2"` is created. If it is created, the test does not bother cleaning it up. And the test framework complains about a missing cleanup.
Thus, create it and then delete it again.
=> Clean up collection if it was created successfully.

arangod/Aql/AqlCallStack.cpp, arangod/Aql/AqlCallStack.h, arangod/Aql/ExecutionBlock.cpp, arangod/Aql/ExecutionBlockImpl.tpp
instead of setting up the execution block with a callstack with one item and then immediately discarding the item from the callstack, we can set up the execution block with an empty callstack.
=> simplify execution block setup

CHANGELOG, arangod/Transaction/Manager.cpp, tests/Transaction/ManagerTest.cpp
https://arangodb.atlassian.net/browse/BTS-1669
* Fixed BTS-1669 Transaction Manager returns Error if we Abort an Expired Transaction. There was a small time window of around 2 seconds in which aborting expired transactions would return "transaction aborted" instead of returning success. The time window was between when a transaction expired (according to its TTL value) and when the transaction manager's garbage collection aborted the transaction. The issue only happened for transactions which outlived their TTL value and for which an abort operation was attempted in that time window.
=> Fixed BTS-1669

CHANGELOG, CONTRIBUTING.md, arangod/Cluster/ClusterInfo.cpp, arangod/Cluster/DBServerAgencySync.cpp, arangod/Cluster/SynchronizeShard.cpp, arangod/Cluster/TakeoverShardLeadership.cpp, arangod/RestHandler/RestReplicationHandler.cpp, js/client/modules/@arangodb/testutils/instance-manager.js, lib/Basics/FileUtils.cpp, lib/Basics/FileUtils.h, lib/Basics/GlobalSerialization.cpp, lib/Basics/GlobalSerialization.h, lib/Basics/win-utils.cpp, lib/CMakeLists.txt, tests/js/client/shell/shell-move-shard-sync-fail-cluster.js
This deals with https://arangodb.atlassian.net/browse/BTS-1647.
This is a backport of https://github.com/arangodb/arangodb/pull/19996
Short problem description:
Due to a race during moveShard for leader change it is possible that a shard gets into a state such that both leader and follower believe they are in sync, but the FollowerTermId is incorrectly set in the follower. This means that the follower is dropped on the first write operation to the shard.
This PR fixes this by properly cleaning up `_theLeader` on the follower in case of an error.
Furthermore, we ensure that something is logged on INFO level whenever a shard synchronization fails. This is crucial for debugging.
Testing this is tricky. Therefore we introduce a new system to serialize events in a local cluster globally. This …
=> Deal with race in leader change [BTS-1647][BTS-1658]

lib/Futures/include/Futures/Try.h
We have 3 overloads `Value, Value const&, Value&&`.
For some cases it causes compiler error about ambiguities.
Also first overload is unnecessary.
=> Fix set_exception overloads for Try

CHANGELOG, arangod/Network/Methods.cpp, arangod/Scheduler/SchedulerFeature.cpp
This addresses https://arangodb.atlassian.net/browse/BTS-1671.
It is to silence TSAN in some shutdown cases in RTA.
There is a global pointer called SchedulerFeature::SCHEDULER. On
shutdown, we set this pointer to nullptr in the
SchedulerFeature::unprepare method. In various other places, we read out
the pointer.
The logic of ApplicationFeatures should ensure that nobody will read
the pointer out after the SchedulerFeature has run its unprepare
method. Sometimes the TSAN sanitizer cannot recognize this indirect
synchronization and complains about reads that have happened before the
write there, but are not officially inter-thread synchronized. We use
atomic references in some places to silence TSAN.
- [*] Backport for 3.11: …
=> Silence TSAN w.r.t. SCHEDULER pointer on shutdown [BTS-1671]

arangod/Cluster/DBServerAgencySync.cpp, tests/js/client/shell/shell-move-shard-sync-fail-cluster.js
*Test only PR. We do not necessarily wait for Phase two to be complete in that test. The event can happen earlier, namely between writing to Current and the end of Phase two.*
=> Fix race in MoveShardSyncFail Test

arangod/Replication/InitialSyncer.cpp
In the destructor of `InitialSyncer`, it hands `_progress` to `replication::BatchInfo::finish(...)`. That method can invoke `_progress` under some conditions. If it does, then it will call `DatabaseInitialSyncer::setProgress(...)`, which refers to the already destroyed `DatabaseInitialSyncer` derived class.
This PR is a potential bugfix for this.
=> attempt to fix invalid vptr in InitialSyncer dtor

arangod/Cluster/DBServerAgencySync.cpp, tests/js/client/shell/shell-move-shard-sync-fail-cluster.js
Backport of https://github.com/arangodb/arangodb/pull/20066
*Test only change. We do not necessarily need to wait for one condition in the Test so I removed it. There is a timewindow where the removed condition was triggered only after the following one was seen on a different server, causing the test tu stuck.*
=> [3.10] Fix race in MoveShardSyncFail Test

arangod/Cluster/DBServerAgencySync.cpp, tests/js/client/shell/shell-move-shard-sync-fail-cluster.js
Backport of https://github.com/arangodb/arangodb/pull/20066
*Test only change. We do not necessarily need to wait for one condition in the Test so I removed it. There is a timewindow where the removed condition was triggered only after the following one was seen on a different server, causing the test tu stuck.*
=> [3.11] Fix race in MoveShardSyncFail Test

js/client/modules/@arangodb/testutils/result-processing.js
we would output NaN into the xml file, this came from the value `undefined`.
=> don't output 'undefined' - this will give NaN in the xml

arangod/Cluster/ClusterIndexMethods.cpp
*When we create an index in Replication 2, we need to wait for the RaftIndex of the "isBuilding" removal, this is now happening. Also replace the complex waiting logic by a easier to understand future based approach.*
[CINFRA-830]: https://arangodb.atlassian.net/browse/CINFRA-830?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CINFRA] Fix race when creating an Index in Rep2. reporting success too early

arangod/VocBase/Properties/CreateCollectionBody.cpp, lib/Containers/MerkleTree.cpp
Fix 2 small issues that g++-13 finds unacceptable to compile.
These changes are not relevant for other compiler versions, but shouldn't cause any issues either.
=> fix 2 issues that g++-13 rants about

arangod/RestHandler/RestCollectionHandler.cpp, arangod/RestHandler/RestVocbaseBaseHandler.cpp, arangod/RocksDBEngine/ReplicatedRocksDBTransactionCollection.cpp, arangod/Transaction/Methods.cpp
*In the Document and Collection API if we send an Replication1 type request, the Replication2 API now returns the same error codes if send to wrong server (leader and follower). Fixes parts of: https://arangodb.atlassian.net/browse/BTS-1565*
=> [CINFRA] Make ResponseCodes of Replication2 compatible to Replication1

CHANGELOG, arangod/Network/Methods.cpp, arangod/Scheduler/SchedulerFeature.cpp, tsan_arangodb_suppressions.txt
This is a backport of https://github.com/arangodb/arangodb/pull/20056 .
This addresses https://arangodb.atlassian.net/browse/BTS-1671.
It is to silence TSAN in some shutdown cases in RTA.
There is a global pointer called SchedulerFeature::SCHEDULER. On
shutdown, we set this pointer to nullptr in the
SchedulerFeature::unprepare method. In various other places, we read out
the pointer.
The logic of ApplicationFeatures should ensure that nobody will read
the pointer out after the SchedulerFeature has run its unprepare
method. Sometimes the TSAN sanitizer cannot recognize this indirect
synchronization and complains about reads that have happened before the
write there, but are not officially inter-thread synchronized. We use
atomic references in some places to silence TSAN.
- [*] :hankey: …
=> Silence TSAN w.r.t. SCHEDULER pointer on shutdown

js/client/modules/@arangodb/testutils/joinHelper.js, tests/js/client/aql/aql-index-join-multi-unique-false-sort-false-bucket0_3.js, tests/js/client/aql/aql-index-join-multi-unique-false-sort-false-bucket1_3.js, tests/js/client/aql/aql-index-join-multi-unique-false-sort-false-bucket2_3.js, tests/js/client/aql/aql-index-join-multi-unique-false-sort-true-bucket0_3.js, tests/js/client/aql/aql-index-join-multi-unique-false-sort-true-bucket1_3.js, tests/js/client/aql/aql-index-join-multi-unique-false-sort-true-bucket2_3.js, tests/js/client/aql/aql-index-join-multi-unique-true-sort-false-bucket0_3.js, tests/js/client/aql/aql-index-join-multi-unique-true-sort-false-bucket1_3.js, tests/js/client/aql/aql-index-join-multi-unique-true-sort-false-bucket2_3.js, tests/js/client/aql/aql-index-join-multi-unique-true-sort-true-bucket0_3.js, tests/js/client/aql/aql-index-join-multi-unique-true-sort-true-bucket1_3.js, tests/js/client/aql/aql-index-join-multi-unique-true-sort-true-bucket2_3.js, tests/js/client/aql/aql-index-join-unique.js, tests/js/client/aql/aql-index-join.js
According to @dothebart, the CI doesn't like execution of the join tests.
This PR adds more code and complexity to the testing by manually splitting the join tests into buckets to make things work again.
=> Add more complexity to testing

CHANGELOG, arangod/RestServer/DaemonFeature.cpp, lib/Logger/LogAppender.cpp, lib/Logger/LogAppender.h, lib/Logger/LogAppenderFile.cpp, lib/Logger/LogAppenderFile.h, lib/Logger/LogThread.cpp, lib/Logger/LogThread.h, lib/Logger/Logger.cpp, lib/Logger/Logger.h, lib/Logger/LoggerFeature.cpp, lib/Logger/LoggerFeature.h, tests/Basics/LoggerTest.cpp, tests/main.cpp
*Right now the Logger holds a very large lock. The lock is held whenever the background thread flushes a queued log message, which is potentially slowed down by IO. If we try to do a new direct log entry in that period we need to wait for this lock to be released. With this PR the Lock is changed such that: We get a WriteLock whenever we modify the Loggers we use, but we only take a read-lock when we let the loggers print. This way we can have two or more threads using the loggers.
In turn the output message of the Logger, which does the IO operation, is guarded with a WriteLock.
In addition this PR adds an upper bound to the amount of messages in the queue. This is right now hard-coded and should not have effect under normal circumstances. If the logging is configured to use an extremely …
=> [3.10] Improve locking in Async Logger (#19989)

CHANGELOG, arangod/RestServer/DaemonFeature.cpp, lib/Logger/LogAppender.cpp, lib/Logger/LogAppender.h, lib/Logger/LogAppenderFile.cpp, lib/Logger/LogAppenderFile.h, lib/Logger/LogThread.cpp, lib/Logger/LogThread.h, lib/Logger/Logger.cpp, lib/Logger/Logger.h, lib/Logger/LoggerFeature.cpp, lib/Logger/LoggerFeature.h, tests/Basics/LoggerTest.cpp, tests/main.cpp
*Right now the Logger holds a very large lock. The lock is held whenever the background thread flushes a queued log message, which is potentially slowed down by IO. If we try to do a new direct log entry in that period we need to wait for this lock to be released. With this PR the Lock is changed such that: We get a WriteLock whenever we modify the Loggers we use, but we only take a read-lock when we let the loggers print. This way we can have two or more threads using the loggers.
In turn the output message of the Logger, which does the IO operation, is guarded with a WriteLock.
In addition this PR adds an upper bound to the amount of messages in the queue. This is right now hard-coded and should not have effect under normal circumstances. If the logging is configured to use an extremely …
=> [3.11] Improve locking in Async Logger (#19989)

arangod/Network/Methods.cpp
Just clarify a comment about TSAN silencing.
This was requested by reviewers in a backport pR, but the PR was already
merged in devel.
https://github.com/arangodb/arangodb/pull/20062#discussion_r1381713603
=> Clarify comment

lib/Logger/LogAppender.cpp
*The LogAppenders do have a lock on the lists of appenders. We recently moved some of it from write to read lock. Now make sure we do not write under deadlock by using `.at()` instead of `[]` which could write implicitly. I do not think this has a real effect as the lists should be filled after startup.*
=> LogAppender: Ensure we do not implicitly add ones under ReadLock

CHANGELOG, client-tools/Dump/DumpFeature.cpp, client-tools/Restore/RestoreFeature.cpp
Previously the arangodump collection properties from single server dumps contained the following attributes:
- replicationFactor
- writeConcern
- numberOfShards
- minReplicationFactor
- shards
- shardKeys
It is not really useful to write these attributes out when taking single server dumps, because they don't have useful values.
=> remove cluster-only attributes from single server dumps

arangod/Aql/JoinExecutor.cpp, arangod/Aql/JoinExecutor.h, arangod/Aql/JoinNode.cpp, arangod/Aql/JoinNode.h, arangod/Aql/OptimizerRules.cpp, tests/js/client/aql/aql-index-join.js
Remove unnecessary projections from JoinNode if the projected attributes are only used inside the JoinNode itself but not later, and are not referring to the join attributes.
=> remove unnecessary projection attributes from JoinNode

CMakeLists.txt
Add special compiler directives for g++-13 or higher.
g++-13 emits tons of false positives when compiling 3rdParty libraries such as date, fmt and immer. Upgrading to the newest versions of these libraries doesn't help either, because the checks are just flawed.
Hopefully these false positives will be addressed in future versions of g++.
Compilers other than g++ should not be affected and no compile directives are changed for them by this PR.
=> add special compile directives for g++-13

lib/Logger/LogAppender.cpp
Backport of https://github.com/arangodb/arangodb/pull/20102
*The LogAppenders do have a lock on the lists of appenders. We recently moved some of it from write to read lock. Now make sure we do not write under deadlock by using `.at()` instead of `[]` which could write implicitly. I do not think this has a real effect as the lists should be filled after startup.*
=> [3.10] LogAppender: Ensure we do not implicitly add ones under ReadLock #20102

.circleci/base_config.yml
This makes the docker container that is built with a pipeline parameter. Reduces the number of places to edit when updating, and enables testing docker images without changing the repository.
=> Make the docker tag to build with a parameter

arangod/Aql/JoinNode.cpp, arangod/Aql/OptimizerRulesJoin.cpp, tests/js/client/aql/aql-index-join.js
The costs for multiple nodes are *added*, the join node multiplied the costs for indexes, which made it _very_ expensive and most of the time, i.e. indexes > 3, the optimizer would bail out and not create a join node.
=> [EF-19] Join Node Estimations

tests/Basics/ReadWriteLockTest.cpp
This stabilizes the new ReadWriteLock test for Windows. I simply
increase some timeouts, which have been shown to be critical on Windows.
I have tried out the same fix in my not yet merged branch for devel.
- [*] Tests
=> Stabilize ReadWriteLock test

arangod/Pregel/ArangoExternalDispatcher.h, arangod/Pregel/Conductor/Handler.h, arangod/Pregel/MetricsActor.h, arangod/Pregel/PregelFeature.cpp, arangod/Pregel/PregelFeature.h, arangod/Pregel/ResultActor.h, arangod/Pregel/SpawnActor.h, arangod/Pregel/StatusActor.h, arangod/Pregel/Worker/Handler.h, lib/Actor/include/Actor/Actor.h, lib/Actor/include/Actor/ActorBase.h, lib/Actor/include/Actor/ActorList.h, lib/Actor/include/Actor/DistributedRuntime.h, lib/Actor/include/Actor/IWorkable.h, lib/Actor/include/Actor/LazyWorker.h, lib/Actor/include/Actor/Message.h, tests/Actor/ActorListTest.cpp, tests/Actor/Actors/TrivialActor.h, tests/Actor/MockScheduler.h, tests/Actor/MultiRuntimeTest.cpp, tests/Actor/ThreadPoolScheduler.h
Follow up PR of #20111 in preparation of the parallel follower implementation.
Some generic messages previously relied on the `DistributedActorPID`, but other runtime implementations may use different PID types, so these messages are now templatized on the PID type. Similarly the `ActorBase` has been templatized for the same reason, and a new interface has been extracted so that the `IScheduler` has a minimal dependency (interface segregation principle).
=> Make the actor implementation a bit more generic

3rdParty/CMakeLists.txt
Enable interprocedural optimization (IPO) / link time optimization (LTO) for third party modules.
IPO/LTO was previously disabled for third party modules.
There is potentially no legitimate reason anymore to disable it, except potentially longer build/link times.
=> add IPO/LTO for third party modules

3rdParty/CMakeLists.txt
Remove some CMake directives that supported building the ArangoDB starter if it was checked out in `3rdParty/arangodb-starter`.
It was confirmed by several people that we are not using this functionality for builds or tests.
=> remove integration of starter building from CMake

arangod/Pregel/PregelFeature.cpp, lib/Actor/include/Actor/Actor.h, lib/Actor/include/Actor/DistributedRuntime.h, lib/Actor/include/Actor/HandlerBase.h, tests/Actor/CMakeLists.txt, tests/Actor/DistributedRuntimeTest.cpp
Previously the runtime required the user to periodically call `garbageCollect` to clean out actors that are finished and idle.
However, the actor itself knows when it is finished and idle, so this change allows the actor to remove itself at that point. This means the `garbageCollect` function is no longer necessary.
=> Automatically remove finished actors

scripts/test/testing_runner.py
Limit the CI idle timeout to 15 minutes of silence, so we're quicker than circleci to detect & abort this.
=> allow 15 minutes of silence when running testing.js

arangod/Aql/StandaloneCalculation.cpp, arangod/IResearch/IResearchAnalyzerFeature.cpp
Fix compilation. In some environments, `FALSE` seems to be undefined or redefined via macros.
=> fix compilation

CHANGELOG, js/common/modules/@arangodb/common.js
Remove version check at arangosh startup.
This can speed up the startup of the arangosh considerably, as it won't make a network request to www.arangodb.com anymore.
=> remove version check at arangosh startup

js/client/modules/@arangodb/arango-collection.js, tests/js/common/shell/shell-collection-api.js
*This PR contains two changes:
1) The properties wrapper on Client side now passes the "groupId" as returned from API into arangosh. It does not allow to pass in the value to try and change it.
2) Adapt the api-collection test to expect to always find a "groupdId" on Replication2 collections. It does not do specific tests on correctness of those Ids yet.
*
=> [CINFRA] Update collection API test to expect groupId for Replication2 collections 

arangod/Pregel/Conductor/Handler.h, arangod/Pregel/MetricsActor.h, arangod/Pregel/ResultActor.h, arangod/Pregel/SpawnActor.h, arangod/Pregel/StatusActor.h, arangod/Pregel/Worker/Handler.h, lib/Actor/include/Actor/Actor.h, lib/Actor/include/Actor/ActorBase.h, lib/Actor/include/Actor/ActorID.h, lib/Actor/include/Actor/ActorList.h, lib/Actor/include/Actor/Assert.h, lib/Actor/include/Actor/DistributedRuntime.h, lib/Actor/include/Actor/Error.h, lib/Actor/include/Actor/ExitReason.h, lib/Actor/include/Actor/HandlerBase.h, lib/Actor/include/Actor/Message.h, tests/Actor/ActorListTest.cpp, tests/Actor/ActorTest.cpp, tests/Actor/Actors/FinishingActor.h, tests/Actor/Actors/MonitoringActor.h, tests/Actor/DistributedRuntimeTest.cpp
This PR adds monitoring support for actors. At the moment this is limited to the local server, so an actor can only monitor other actors running on the same server (in the same runtime to be precise). When an actor is stopped, it sends `ActorDown` messages to all monitoring actors. This message includes the PID of the finished actor, together with an error code indicating the reason why the actor stopped. If an actor tries to monitor an actor that no longer exists (or may have never existed - don't have enough information to differentiate the two cases), we immediately send an `ActorDown` message to that actor with reason `UknownActor`.
=> Implement actor monitoring

lib/Inspection/include/Inspection/InspectorBase.h, lib/Inspection/include/Inspection/detail/Fields.h, tests/Inspection/VPackSaveTest.cpp
This PR fixes an issue when inspecting temporaries with `embedFields`. It was always possible to pass rvalue references to the inspector, e.g. the result of a getter. While this does not make a load of sense for load operations, it is perfectly valid for serialization. However, in combination with `embedFields` this has previously resulted in undefined behavior. The reason is, that `Inspector::field()` creates a field that stores the relevant information for later processing. Normally this processing happens during execution of `Inspector::fields()`, at which point the temporary which has been passed to `Inspector::field()` is still valid. But in case of `embedFields`, `Inspector::fields()` produces a special result that captures all the passed fields, so they can be processed by the …
=> Fix issue when inspecting temporaries with embedFields

CHANGELOG, Documentation/Metrics/arangodb_connection_statistics_memory_usage.yaml, Documentation/Metrics/arangodb_request_statistics_memory_usage.yaml, arangod/GeneralServer/CommTask.cpp, arangod/GeneralServer/CommTask.h, arangod/GeneralServer/H2CommTask.cpp, arangod/GeneralServer/HttpCommTask.cpp, arangod/GeneralServer/RestHandler.cpp, arangod/GeneralServer/RestHandler.h, arangod/GeneralServer/VstCommTask.cpp, arangod/Statistics/ConnectionStatistics.cpp, arangod/Statistics/ConnectionStatistics.h, arangod/Statistics/RequestStatistics.cpp, arangod/Statistics/RequestStatistics.h, arangod/Statistics/StatisticsFeature.cpp, arangod/Statistics/StatisticsFeature.h, arangod/Statistics/StatisticsWorker.cpp, tests/Basics/FpConvTest.cpp, tests/js/client/server_parameters/statistics-off.js, tests/js/client/server_parameters/statistics-on.js
Fix issues with statistics memory usage
* Track memory usage of internal connection statistics and request statistics:
- `arangodb_connection_statistics_memory_usage`
- `arangodb_requests_statistics_memory_usage` These metrics will remain at 0 if the server is started with the option `--server.statistics false`. Otherwise they will contain the memory usage used by connection and request statistics. Memory usage should remain pretty constant over time, unless there are bursts of new connections and/or requests.
* Avoid memory leak in case an arangod instance is started with the option `--server.statistics false`. Previously, with that setting the request and connection statistics were built up in memory, but were never released because the statistics background thread was not running.
=> Fix issues with statistics memory usage

arangod/Aql/EnumeratePathsNode.cpp, arangod/Aql/ExecutionPlan.cpp, arangod/Graph/ShortestPathOptions.cpp, arangod/Graph/ShortestPathOptions.h
This PR does a small cleanup of `struct ShortestPathOptions`;
* removes the unused members `bidirectional` and `multiThreaded`, `start` and `end`
* renames `minDepth`, and `maxDepth` to `_minDepth` and `_maxDepth` and accesses them through accessors
=> Cleanup ShortestPathOptions

tests/Actor/MockScheduler.h, tests/Actor/RuntimeTest.cpp, tests/Actor/ThreadPoolScheduler.h
Sometimes one of the actor unit tests fails (eg. https://app.circleci.com/pipelines/github/arangodb/arangodb/19228/workflows/cf02640f-d09e-4252-86ae-c510828c264e/jobs/927780)
The reason is that the finish message is processed asynchronously, and the idle flag is set before the actor is removed and the down messages are dispatched. The `waitForAllMessagesToBeProcessed` function only indicates that the messages have been processed based on the idle state, but we don't know yet if the down messages have already been dispatched. So we have to wait until the system has converged to our expected state.
=> Try to stabilize actor test

arangod/Pregel/Worker/Handler.h, lib/Actor/include/Actor/Actor.h, lib/Actor/include/Actor/BaseRuntime.h, lib/Actor/include/Actor/DistributedRuntime.h, lib/Actor/include/Actor/HandlerBase.h, lib/Actor/include/Actor/LocalRuntime.h, lib/Inspection/include/Inspection/LoadInspectorBase.h, tests/Actor/Actors/TrivialActor.h
Previously the actor library could not handle move-only message types and the inspector could not deserialize move-only types.
=> Improve compatibiltiy of actor and inspector libraries for move-only types

arangod/Aql/ExecutionPlan.cpp, arangod/Aql/Optimizer.cpp, arangod/Aql/OptimizerRule.h, arangod/Aql/OptimizerRuleReplaceEqualAttributeAccess.cpp, arangod/Aql/OptimizerRulesFeature.cpp, tests/js/client/aql/aql-optimizer-rule-optimize-projections.js, tests/js/client/aql/aql-optimizer-rule-replace-equal-attribute-access-noncluster.js
The `replace-equal-attribute-access` rule now works for subqueries as well. Furthermore, if one side is already a single variable expression, it uses this variable instead of introducing another alias variable.
Finally the optimizer rule was moved after `moveFiltersUpRule2` which ensures that we can replace as many values as possible.
=> Improve replace-equal-attribute-access rule.

arangod/Cluster/ClusterIndexMethods.cpp, arangod/Cluster/ClusterInfo.h
The replication2 index creation code (_ensureIndexCoordinatorReplication2Inner_) is affected by a race. This PR provides the fix.
**Problem we're trying to fix**
There are 3 things that have play along:
- clusterInfo.loadPlan()
- callbackRegistry.waitFor()
- clusterInfo.waitForPlan()
The race is as follows:
1. We try to create the index. Coordinator writes index to Target. Agency sees the index in Target, writes it to Plan and increments Plan/Version.
2. Coordinator is slow. Before even registering the callback for the index in Plan, ClusterInfo (via the syncer thread on coordinator) does `loadPlan()` and observes the change (because the plan version is updated). This also updates the raft index in ClusterInfo.
3. Before the coordinator registers the Plan agency callback, something random …
=> [CINFRA] Index Creation Race

arangod/RocksDBEngine/RocksDBOptionFeature.cpp
Remove artificial limitation for `--rocksdb.max-background-jobs`.
When the option was set to a value != -1, then the maximum value was 128. This is an artificial limitation which may not make sense on servers with many cores.
=> remove artificial limitation for `--rocksdb.max-background-jobs`

CHANGELOG, tests/js/client/server_parameters/detach-threads-noncluster.js
The test in question needs a certain number of threads and is unstable
otherwise. Therefore it is moved to the server_parameters suite and a
specific number of threads is used. This makes it stable.
- Fix test.
- CHANGELOG.
- [*] Tests
- [*] Backport for 3.11: This is the backport for 3.11
- [*] PR with the corresponding change for devel: https://github.com/arangodb/arangodb/pull/20162, 3.10 is not affected.
=> Stabilize detach threads test

js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/addIndex/invertedIndex/InvertedIndexFormJSONEditor.tsx
This fixes the broken undo behaviour by switching to using onChangeText, which gives the proper updated JSON
=> FE-396: fix JSON editor undo broken for inverted index addition

js/common/modules/@arangodb/testutils/document-state-helper.js, tests/js/server/replication2/replication2-replicated-state-document-store.js
There's been a few cases (quite rarely) when I noticed something really weird: we try to insert a key into a newly created replication2 collection and fail. The key is definitely unique, there's no way it could have been there before, yet we get a unique constraint violation.
For example:
```
ArangoError: unique constraint violated - in index primary of type primary over '_key'; conflicting key: testDoubleCreateDropIndex-0
```
Inspecting the agency shows nothing wrong (I would've expected to see at least some failover).
**This PR adds extra logging information that should aid in investigating such failures.**
=> [CINFRA] Extra logging in case of failure

arangod/Graph/PathManagement/PathValidator.cpp, arangod/Graph/PathManagement/PathValidator.h, arangod/Graph/PathManagement/PathValidatorOptions.cpp, arangod/Graph/PathManagement/PathValidatorOptions.h, tests/Graph/PathValidatorTest.cpp, tests/Mocks/MockGraphProvider.cpp
The PathValidator class can already enforce a global condition on all vertices; this patch also allows it to filter all edges on a path.
=> Teach PathValidator a global condition on edges

arangod/Aql/Ast.cpp, arangod/Aql/CMakeLists.txt, arangod/Aql/EdgeConditionBuilder.cpp, arangod/Aql/EdgeConditionBuilder.h, arangod/Aql/EdgeConditionBuilderContainer.cpp, arangod/Aql/EdgeConditionBuilderContainer.h, arangod/Aql/EnumeratePathsNode.h, arangod/Aql/GraphNode.h, arangod/Aql/QueryContext.h, arangod/Aql/ShortestPathNode.h, arangod/Aql/TraversalNode.h, arangod/Graph/Graph.cpp, arangod/Graph/GraphManager.cpp, arangod/Pregel/IndexHelpers.h, arangod/RestHandler/RestEdgesHandler.cpp
Technically part of one of the Graph Refactors or cleanups: Graphs.h/Graphs.cpp
contained two classes: EdgeConditionBuilder and EdgeConditionBuilderContainer.
Split those files into the two headers and only include them wehere they are used.
Requires Enterprise PR: https://github.com/arangodb/enterprise/pull/1415
=> Split Graphs.h/Graphs.cpp and cleanup

tests/js/client/shell/transaction/shell-transaction-intermediate-commit-cluster.js
This PR provides the necessary adaptations for the `shell-transaction-intermediate-commit-cluster.js` suite, making it run-able with replication2 default.
Most of these changes revolve around the following two differences:
- In replication2 we do not "drop" followers
- In replication2, followers do not perform intermediate commits by themselves, unless the leader replicates an `IntermediateCommit` operation. This means that if intermediate commits are disabled on the leader, they are inherently disabled on the follower.
Although they were initially targeted at replication1-specific behavior, I believe the suite is still relevant for replication2, at least from the perspective of a more general sanity check: making sure we don't crash, and the leader and follower are kept in sync.
=> [CINFRA] Replication2 adaptation of shell-transaction-intermediate-commit-cluster

lib/Basics/signals.cpp, lib/Basics/signals.h, lib/CrashHandler/CrashHandler.cpp
Print signal sub code when crash handler is invoked.
This can help to shed more light on the crash that occurred.
=> print signal sub code when crash handler is invoked

.circleci/base_config.yml, .circleci/config.yml
*CircleCI only change:
We now allow the two parameters:
c-compiler : string
cxx-compiler : string
This allows us to select a specific compiler on Linux.
The compiler needs to be installed on the build image we are using right now, it will not be installed.
e.g.
c-compiler: gcc (default)
and
c-compiler: clang
Both work with our current build image, including their resp. c++ variants.
*
=> Allow CircleCI to optionally hand in a compiler name

.circleci/base_config.yml, .circleci/config.yml
If a pipeline parameter is set explicitly, this value will implicitly be forwarded to the continuation pipeline. If a value is not explicitly set. but has a default value, then this value is _not_ implicitly forwarded. It can be explicitly forwarded by using the continuation's parameters, but if we do that unconditionally, this causes a problem once the parameter is again set explicitly, because then we get a "Conflicting pipeline parameters." error because the parameter is forwarded twice (once implicitly and once explicitly).
=> Set build-docker-image default value in base config

js/client/modules/@arangodb/testutils/crash-utils.js
properly iterate the array instead of only taking the indices. 
- Backports:
=> fix array iteration in coredump location

tests/Basics/ReadWriteLockTest.cpp
Fix issue in ReadWriteLockTest.
The test could spend potentially endless time in `waitForStart()`, because the relevant synchronization mutex was held while the thread went to sleep.
=> fix issue in ReadWriteLockTest

arangod/Graph/Enumerators/TwoSidedEnumerator.cpp, arangod/Graph/Enumerators/WeightedTwoSidedEnumerator.cpp, arangod/Graph/PathManagement/PathValidator.cpp, arangod/Graph/PathManagement/PathValidator.h, tests/Graph/AllShortestPathsFinderTest.cpp, tests/Graph/WeightedShortestPathTest.cpp
This PR attempts to be a small solution to the problem that presents itself with path searches and global conditions on vertices and edges.
The code that executes path/vertex conditions while enumerating paths was as yet untested and hence crashed on the first use.
This is due to the fact that path validation, inspecting the vertex documents on the path, was called at a time when the vertex document wasn't known yet.
This PR moves the full path validation that inspects a vertex document to a point where the vertex document is known.
This is after the vertex has been popped from the (priority-)queue, but retains redundancy checks on expansion, that is if a vertex-id has been seen already it is not put on the queue again for the enumerator without weights.
The weighted two sided enumerator …
=> Fix K_SHORTEST_PATHS

tests/IResearch/IResearchFeatureTest.cpp
Test uses invalid shard ids that can trigger an assertion in `loadCurrent`.
=> Invalid Shard Ids

tests/js/client/replication2/replication2-cluster.js
*_createDatabase() will use the default replication version. Adjusted the test to be flexible for V1 and V2 was hard-coded to V1*
=> CINFRA: Adapt create Database test to ensure correct default version is used

CHANGELOG, arangod/Aql/ClusterQuery.cpp, arangod/Aql/ClusterQuery.h, arangod/Aql/EngineInfoContainerDBServerServerBased.cpp, arangod/Aql/EngineInfoContainerDBServerServerBased.h, arangod/Aql/RestAqlHandler.cpp, arangod/RocksDBEngine/RocksDBMetaCollection.cpp, arangod/Transaction/Manager.cpp, arangod/V8Server/v8-vocbase.cpp, lib/Basics/StaticStrings.cpp, lib/Basics/StaticStrings.h, tests/js/client/shell/shell-dropped-followers-elcheapo-commit-cluster.js
Fix BTS-1714.
The short locking timeout of 2s should only be used for the AQL setup
collection locking and not for later operations like write replications.
This is a backport of: https://github.com/arangodb/arangodb/pull/20287
- [*] Tests
- [*] GitHub issue / Jira ticket: https://arangodb.atlassian.net/browse/BTS-1714
=> Fast path locking timeout only for AQL setup

arangod/IResearch/CMakeLists.txt, arangod/IResearch/IResearchAnalyzerFeature.cpp, arangod/IResearch/IResearchAnalyzerFeature.h, arangod/IResearch/IResearchDataStore.cpp, arangod/IResearch/IResearchDocument.cpp, arangod/IResearch/IResearchFilterFactory.cpp, arangod/IResearch/IResearchKludge.cpp, arangod/IResearch/IResearchRocksDBRecoveryHelper.cpp, arangod/IResearch/Wildcard/Analyzer.cpp, arangod/IResearch/Wildcard/Analyzer.h, arangod/IResearch/Wildcard/Filter.cpp, arangod/IResearch/Wildcard/Filter.h, arangod/IResearch/Wildcard/Options.cpp, arangod/IResearch/Wildcard/Options.h, tests/IResearch/IResearchAnalyzerFeatureTest.cpp, tests/IResearch/IResearchQueryNGramMatchTest.cpp, tests/js/client/aql/aql-arangosearch-wildcard-analyzer.js
Using ngram to approximate wildcard queries
For 11 * 1e6 strings, with average length 800 and pattern like `"%fjdkajfkajdgagh%"`:
|cold | hot | memory | analyzer|
|----| ----| ---|---|
| \>= 200s | 35s | 8.3Gb | identity |
| 7ms | 6ms | 20.9Gb | wildcard 3 (position) |
| 20ms | < 1ms | 21.3Gb | wildcard 4 (position) |
| 25ms | < 1ms | 12.9Gb | wildcard 5 (without position) |
csd -- 8.5 Gb, can be compressed...
Can be done in the future:
1. Avoiding additional compute for positions
2. Implement another analyzer without column.
3. Allowing reads from analyzer column
4. Optimize "in" for such field (disjunction of ngram_matches)
=> Implement wildcard analyzer

arangod/Aql/Query.cpp, arangod/Cluster/Maintenance.cpp, arangod/VocBase/VocBaseLogManager.cpp, arangod/VocBase/VocBaseLogManager.h
*When we drop a shard we acquired the VocBaseLogManager GuardedData lock, and then the Collection Status lock on drop.
On other operations (e.g. queries) we get first CollectionStatusLock and then the GuardedDataLock.
This lead to a deadlock. Now we release the GuardedDataLock on Drop earlier.
*
=> CINFRA: Fix DeadLock on DropShard / DropCollection

lib/Actor/include/Actor/Actor.h, lib/Actor/include/Actor/ActorList.h, lib/Actor/include/Actor/BaseRuntime.h, lib/Actor/include/Actor/HandlerBase.h, tests/Actor/RuntimeTest.cpp
- Add synchronous shutdown method that waits until all actors have finished
- Add getter in HandlerBase so we can access the runtime
- Instantiate actor with the derived Runtime type, not the BaseRuntime
- Avoid copying messages
- Fix potential data race when finishing actor
=> Improvements to the actor library

lib/Inspection/include/Inspection/Transformers.h, tests/Inspection/VPackLoadTest.cpp, tests/Inspection/VPackSaveTest.cpp, tests/Inspection/include/Inspection/InspectionTestHelper.h
The VPack inspector requires maps to use string keys (or at least types that can be implicitly converted to strings). So in order to inspect other maps, this converter converts any map to an std::vector of a type with explicit key/value members.
=> Add generic MapToListTransformer

arangod/RocksDBEngine/RocksDBDumpContext.cpp, arangod/RocksDBEngine/RocksDBDumpContext.h, tests/js/client/shell/api/dump-cluster.js
This PR augments the dump endpoint with very simple filtering; by adding a field
```
filters: {"type": "simple", "conditions": [{"attributePath": ["colour"], "value": "green"}]}
```
while dumping the condition whether the attributes at the given path have the given value is tested using `VelocyPackHelper::equal()` on every document.
Only documents that satisfy all filters are dumped out.
=> Simple filter support for dumps

3rdParty/jemalloc/CMakeLists.txt, CHANGELOG
It turns out that we have to give the include path for jemalloc to
find our own libunwind in the CPPFLAGS rather than the CFLAGS. Otherwise
it can happen that the configure/make system cannot compute the
dependencies correctly. This problem hits if there is no system wide
libunwind installed.
- Minor fix for jemalloc build setup.
- CHANGELOG.
=> Fix jemalloc cmake setup for building with glibc images

arangod/Agency/FailedFollower.cpp, arangod/Agency/FailedLeader.cpp, arangod/Agency/Job.cpp, arangod/Agency/Job.h, tests/Agency/FailedFollowerTest.cpp, tests/Agency/FailedLeaderTest.cpp
Check that collections that are shared like the prototype collection still exist when the job is moving to pending. Otherwise we write to an already delete collection.
=> [BTS-1642] Failover Jobs checking for clones

tests/js/client/shell/shell-cluster-collection.js, tests/js/client/shell/shell-replication-auto-repair-cluster.js, tests/js/client/shell/shell-replication-intermediate-commits-cluster.js
Test Only change:
1. This makes sure we clean up if a test fails, this removes some false negative follow up tests in the Suite. This does not change anything in the test logic itself.
2. Do not run a Replication1 specific test in Replication2
=> Fix some shell_client tests when run with replication2

arangod/Cluster/Maintenance.cpp, arangod/Replication2/Supervision/CollectionGroupSupervision.cpp, tests/js/client/shell/multi/shell-validation.js
~Previously, if the planned slice did not contain a property, we simply ignored it, even if we still had that property in local. Now we always consider this property as null for the comparison. However, for replication2 we must not compare WriteConcern and WaitForSync, because there these properties are managed differently.~
The proposed maintenance fix does not work, because it does not correctly handle cases of old agency schemas where a property did not yet exist.
Instead we now fixed the supervision code to set the schema to null instead of completely removing it.
Also fixes potential race in a test -  when fetching the schema, the coordinator only looks in plan, but this does not guarantee that the DB servers have picked up and applied the update.
=> Fix supervision: set schema to null instead of removing it

.circleci/base_config.yml, 3rdParty/V8/CMakeLists.txt, CMakeLists.txt, js/client/modules/@arangodb/testutils/unittest.js, lib/ApplicationFeatures/LanguageFeature.cpp, tests/js/client/aql/aql-view-arangosearch-feature.js, tests/js/client/authentication/user-access-right-create-search-alias-arangosearch-spec.js, tests/js/client/authentication/user-access-right-create-view-arangosearch-spec.js
Various unrelated cleanups. These changes were pulled out of the larger v8 upgrade PR to simplify the latter.
The following changes are made:
* remove `CROSS_COMPILING` cmake option. this option was only used for the V8 subdirectory and not maintained.
* remove mentions of non-existing `UnitTests` directory from CircleCI configs. we previously had a directory of that name, but we removed it about a year ago in favor of the `tests` directory.
* make `scripts/unittest` run all tests with a fixed locale set. otherwise the actually used locale is system-dependent and may lead to tests behaving differently with different locales. the locale value is used when starting ArangoDB for the first time, when the value of the current locale is used as the default value for `--server.language`. this …
=> various unrelated cleanups

tests/js/server/recovery/view-search-alias-populate-cluster.js
*Test only change in recovery. During recovery it is allowed for replication 2 to have non-consolidated docs in the recovery. This is now handled by a relaxed condition.*
=> Cinfra: Adapted test for numDocs figures.

arangod/Pregel/PregelFeature.cpp
*Removed assertion in Feature that tests if we are in stopping mode. However if we encounter an issue during startup Like here: https://github.com/arangodb/arangodb/blob/0b0212a37f70c4e8b496b198af1bf4e4a925a21b/lib/ApplicationFeatures/ApplicationServer.cpp#L692 we would not be in stopping state.*
=> Cinfra: Remove incorrect assertion

arangod/Cluster/ClusterCollectionMethods.cpp, arangod/Cluster/Utils/DistributeShardsLike.cpp, arangod/Cluster/Utils/DistributeShardsLike.h, arangod/Cluster/Utils/EvenDistribution.cpp, arangod/Cluster/Utils/EvenDistribution.h, arangod/Cluster/Utils/IShardDistributionFactory.h, arangod/Cluster/Utils/SatelliteDistribution.cpp, arangod/Cluster/Utils/SatelliteDistribution.h, arangod/Cluster/Utils/TargetCollectionAgencyWriter.cpp, arangod/Cluster/Utils/TargetCollectionAgencyWriter.h, tests/Cluster/PlanCollectionEntryTest.cpp
In replication2 we plan the distribution of shards to the individual servers in the supervision. However, once the coordinator has written the relevant information to target, the agency has no way to report back any errors, but has to go through with it. So on the coordinator we at least have to check if the replicationFactor can be fulfilled with the number of available servers, before we write to target.
This should fix a couple of tests when run with replication2 as default.
=> Fix: check replicationFactor against number of available servers

arangod/Agency/Supervision.cpp
The isReplication2 check can return false when the db is not longer found. However, the returned undo action already handles the case when the DB is already gone, and in contrast to replication1, replication2 does not operate on plan, but on target, so this check was superfluous.
This sometimes lead to assertion failures in rebalance tests.
=> Fix: db can already be gone when we process the reconfigureReplicatedLog action

tests/js/client/restart/test-restart-replication2-view-recovery-cluster.js
Adjust a test that uses an invalid replication factor. Previously this worked, because in replication2 we were missing an according check. This was fixed recently, which broke this test.
=> Fix: cannot use rf=3 when we have only 2 servers

arangod/Transaction/Methods.cpp, tests/js/client/shell/shell-collection-properties-propagation-cluster.js, tests/js/client/shell/shell-dropped-followers-elcheapo-commit-cluster.js
- move a failure point so it works for replication 1 and 2
- disable tests that are not relevant for replication2
- with replication2 a replication factor update is propagated to all collections in the collection group
=> Fix more shell_client tests for replication2

arangod/Aql/Ast.cpp, arangod/Aql/Functions.cpp
use absl::StrCat in various places in AQL to simplify string building
=> use absl::StrCat in various places

CHANGELOG, arangod/Aql/grammar.cpp, arangod/Aql/grammar.y, tests/js/client/aql/aql-modify-Modify-noncluster.js
Fixed issue https://arangodb.atlassian.net/browse/BTS-1703.
=> Fixed BTS-1703: Cannot chain multiple UPSERTS

CHANGELOG, tests/js/client/server_parameters/detach-threads-noncluster.js
Stabilize detach-threads test so it does not depend on the local environment (number of cores, specifically).
The previous version of the test (without this fix) failed when the test was executed on a host system with 16 cores or less.
=> Stabilize detach threads test (#20209)

3rdParty/jemalloc/CMakeLists.txt, CHANGELOG, CMakeLists.txt
* Added CMake option `USE_JEMALLOC_CHECKS` to toggle the usage of extra safety checks in jemalloc. The option is currently enabled by default, but can be turned off when there are performance concerns.
=> Added USE_JEMALLOC_CHECKS cmake option

tests/js/client/shell/shell-database-failures-creation-cluster.js
This test coves an update scenario that is only relevant for old versions that predate replication2.
=> Disable a test that is not relevant for replication2

scripts/test/testing_runner.py
if the inner zip is huge, don't waste effort on the some kb of outer files to zip that chunk again and have timeouts
=> don't double compress huge files

arangod/RocksDBEngine/RocksDBCollection.cpp, tests/js/client/chaos/test-chaos-load-common.inc
In replication2 the modification operations on the follower MUST NOT fail!
If they do, we conclude that something else must have gone terribly wrong and therefore abort the process.
=> Disable some chaos failure points for replication2

arangod/Graph/Enumerators/WeightedTwoSidedEnumerator.cpp, arangod/Graph/Enumerators/WeightedTwoSidedEnumerator.h
The old code took a copy of the queue of candidates and then stored pointers into that copy for fetching results. This blew up in recent tests after simplification.
This fix isn't exactly pretty, but is modeled after the `getLooseEnds` in other Queue constructs in path search and addresses the immediate problem.
I am working on further patches that simplify this code but they will take longer to materialise.
=> Fix copy + use after free in path search code

arangod/Cluster/ClusterInfo.cpp
*In Replication2 we do not have the internal concept of distributeShardsLike anymore. Hence we need to adapt the reporting of "realLeaders" which was based on this value internally. For compatibility reasons distributeShardsLike is still exposed and used via API and internally translated.*
=> Fix counting for RealLeaders on Replication2

arangod/Cluster/ClusterCollectionMethods.cpp, arangod/VocBase/Properties/CollectionConstantProperties.cpp, arangod/VocBase/Properties/CollectionConstantProperties.h, arangod/VocBase/Properties/CollectionMutableProperties.h, tests/VocBase/Properties/CollectionConstantPropertiesTest.cpp, tests/VocBase/Properties/CollectionMutablePropertiesTest.cpp, tests/js/client/shell/shell-index.js
Enterprise companion: https://github.com/arangodb/enterprise/pull/1426
Collection creation/update agency operations must skip the scheduler
This is necessary to ensure that the collection creation works even when the medium queue is full
The collection property cacheEnabled is actually mutable.
Note: the enterprise companion also contains some test fixes, but these are actually unrelated to the ones in this PR.
=> Fix more shell_client replication2 test

arangod/Aql/AstNode.cpp, arangod/Aql/AstNode.h, arangod/Aql/AstResources.cpp, lib/Basics/FixedSizeAllocator.h, tests/Basics/FixedSizeAllocatorTest.cpp
Fix a crash that could occur when an exception was thrown during recursive creation of AstNodes from VelocyPack.
In this case, the FixedSizeAllocator that was responsible for creating and destroying the AstNodes inside its own memory buffers was assuming that the exception was thrown by the creation of the current AstNode. But in fact the exception could have been thrown by a nested AstNode as well. In this case, the cleanup procedure may not have worked.
This PR fixes it by not attempting to roll back the last allocation, but rather to patch the memory hole with a default-constructed AstNode.
This is a relatively small fix that can easily be backported, and it can be improved later.
The issue fixed by this bugfix happened when AstNodes were created on DB servers from a VelocyPack query …
=> fix crash upon exception during recursive AstNode creation [BTS-1720]

CHANGELOG, arangod/ClusterEngine/ClusterIndex.cpp, arangod/Indexes/IndexFactory.cpp, arangod/Indexes/IndexFactory.h, arangod/RocksDBEngine/RocksDBValue.cpp, arangod/RocksDBEngine/RocksDBValue.h, arangod/RocksDBEngine/RocksDBZkdIndex.cpp, arangod/RocksDBEngine/RocksDBZkdIndex.h, js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/addIndex/useCreateZKDIndex.ts, tests/js/server/aql/aql-optimizer-zkdindex-stored-values.js, tests/js/server/aql/aql-optimizer-zkdindex-unique.js
Backport of stored values for zkd index.
Actually this is a forward port of https://github.com/arangodb/arangodb/pull/20356
=> Backport ZKD Stored Values 3.11

CMakeLists.txt
This fixes a problem with hotfix releases. Now release tag value is calculated based on ARANGODB_PLAIN_VERSION, which does not include the hotfix number.
ARANGODB_VERSION variable holds the full correct version, this must be used to derive release tag value.
=>  [cmake] fix release tag value for hotfixes

CMakeLists.txt
This fixes a problem with hotfix releases. Now release tag value is calculated based on ARANGODB_PLAIN_VERSION, which does not include the hotfix number.
ARANGODB_VERSION variable holds the full correct version, this must be used to derive release tag value.
=> [cmake] fix release tag value for hotfixes (backport to 3.11)

CMakeLists.txt
This fixes a problem with hotfix releases. Now release tag value is calculated based on ARANGODB_PLAIN_VERSION, which does not include the hotfix number.
ARANGODB_VERSION variable holds the full correct version, this must be used to derive release tag value.
=> [cmake] fix release tag value for hotfixes (backport to 3.10)

arangod/Replication2/StateMachines/Document/Actor/ApplyEntries.cpp, arangod/Replication2/StateMachines/Document/DocumentFollowerState.cpp
We cannot rely on softShutdown to finish all actors, because we have a race - a concurrently running ApplyEntries actor can spawn new actors after softShutdown has been called. This would cause the runtime shutdown to wait for an actor that was never going to be finished
=> Make sure we finish all TransactionActors when resigning

arangod/Cluster/CreateCollection.cpp
*On Replication2 there is an expected uncritical race on new shard creation together with the log. They are both detected at the same time and sometimes the Shard is actually executed before the log. Then the CreateShard job is going to fail quickly and be retried in the next iteration. Only this situation is now put on DEBUG log level so we have the option if we ever get stuck on shard-creation to increase the LogLevel and still see the error, but not raise unnecessary alarms.*
This is the log line in question:
`P ERROR [63687] {maintenance} creating local shard '_system/s2775' for central '_system/573080' failed: {"errorNum":1427,"errorMessage":"replicated state 2772 not found"}`
=> [CINFRA] Only DEBUG output expected error situation

arangod/Aql/AqlFunctionFeature.cpp, tests/js/client/aql/aql-functions-numeric.js
added `RANDOM()` AQL function as an alias for `RAND()` for better interoperability with other databases and easier discovery of functions.
=> added `RANDOM()` AQL function as an alias for `RAND()`

CHANGELOG, arangod/GeneralServer/GeneralServerFeature.cpp, arangod/RestHandler/RestKeyGeneratorsHandler.cpp, arangod/RestHandler/RestKeyGeneratorsHandler.h, arangod/VocBase/KeyGenerator.cpp, arangod/VocBase/KeyGenerator.h, arangod/arangoserver.cmake, tests/js/client/shell/shell-keygen.js
* Added REST API `/_api/key-generators` to query the available key generators for collections.
This can be used by callers (e.g. the web UI) to determine which key generators are available.
=> Added REST API `/_api/key-generators`

arangod/Aql/EnumerateListExecutor.cpp, arangod/Aql/EnumerateListExecutor.h, arangod/Aql/ExecutionNode.cpp, arangod/Aql/RegisterPlan.cpp, arangod/Aql/RegisterPlan.h, arangod/Aql/VarInfoMap.h, arangod/Aql/types.h, tests/Aql/EnumerateListExecutorTest.cpp
The register planning could insert different variables with the same register id into the VarInfoMap.
The info from the VarInfoMap was later copied into a vector. VarInfoMap is an unordered container with no guaranteed iteration order. Thus it was not deterministic which of the inserted variables with the same register id value was found first.
The issue did not occur in any of the Linux builds, potentially because there the iteration order for unordered containers is more deterministic than on Windows, for better or worse. It was a bug anyway, and the iteration order must not play a role here.
The issue was uncovered by a recent change in EnumerateListExecutor, which was made only in devel. Thus no backports needed.
=> fix non-deterministic behavior on Windows

tests/js/client/shell/shell-replication-responses-cluster.js
*Test Only Change. The Test change here tests the Replication1 workflow with some FailurePoints. The codepath is different on Replication2 and hence gives different response code.*
=> [CINFRA] Adapt Replication1 specific Test

CHANGELOG, arangod/RocksDBEngine/RocksDBEngine.cpp, arangod/RocksDBEngine/RocksDBEngine.h
Don't schedule concurrent compactions for the same column family
* Only schedule a single compaction per RocksDB column family at any given time. Scheduling mutliple concurrent compactions on the same column family can lead to scheduler threads being stalled under some adverse conditions that lead to a stall inside RocksDB.
=> Don't schedule concurrent compactions for the same column family

arangod/Indexes/IndexFactory.cpp, arangod/RocksDBEngine/RocksDBZkdIndex.cpp, arangod/RocksDBEngine/RocksDBZkdIndex.h, arangod/VocBase/Methods/Indexes.cpp, tests/js/client/aql/aql-zkdindex-prefix-fields.js, tests/js/client/aql/aql-zkdindex-unique-cluster.js, tests/js/client/aql/aql-zkdindex-unique.js, tests/js/client/aql/aql-zkdindex.js
This PR fixes a few smaller bugs:
- Indexes did not compare correctly and did not account for `prefixFields`.
- `fieldValueTypes: double` was required for creation but not stored when serialized.
=> [ZKD] BugFix PR

arangod/ClusterEngine/ClusterIndexFactory.cpp, arangod/Indexes/Index.cpp, arangod/Indexes/IndexFactory.cpp
Treat indexes of types "zkd" and "mdi" as equal when comparing them.
Also treat "zkd" indexes with missing "sparse" attribute as equal to those with "sparse=false".
=> treat "zkd" and "mdi" indexes as equal when comparing 'em

tests/js/client/shell/shell-index-cleanup-cluster.js
*This test specifically tests behavior of Replication1 index creation if the Coordinator dies in the Process.
We have moved responsibility to the Agency already (tested) making this test obsolete for Rep2.*
=> Disabled Rep1 specific test suite for Rep2

CHANGELOG, arangod/RestServer/UpgradeFeature.cpp, arangod/VocBase/Methods/Upgrade.cpp
Fix BTS-1727: https://arangodb.atlassian.net/browse/BTS-1727
=> BTS-1727: Return proper EXIT_UPGRADE_REQUIRED in cluster mode

arangod/Aql/TraversalExecutor.cpp, arangod/Aql/TraversalExecutor.h, arangod/Aql/TraversalNode.cpp
Adjust/remove code comments that refer to "refactored" or "new" traversal variants, as we now only have these and not their older counterparts.
=> remove now-obsolete code comments

CHANGELOG, Documentation/Metrics/arangodb_scheduler_num_detached_threads.yaml, Documentation/Metrics/arangodb_scheduler_num_worker_threads.yaml, arangod/RocksDBEngine/RocksDBMetaCollection.cpp, arangod/Scheduler/Scheduler.cpp, arangod/Scheduler/Scheduler.h, arangod/Scheduler/SchedulerFeature.cpp, arangod/Scheduler/SchedulerFeature.h, arangod/Scheduler/SupervisedScheduler.cpp, arangod/Scheduler/SupervisedScheduler.h, arangod/Transaction/Manager.cpp, arangod/Transaction/Methods.cpp, js/common/bootstrap/errors.js, lib/Basics/errors.dat, tests/Cluster/RebootTrackerTest.cpp, tests/js/client/server_parameters/detach-threads-cluster.js, tests/js/client/server_parameters/detach-threads-noncluster.js
Backport of https://github.com/arangodb/arangodb/pull/20067
This is one measure to resolve https://arangodb.atlassian.net/browse/BTS-1670
In this PR we create a possiblity that a SchedulerThread can notice that it might be up to some longer running task (like waiting for a lock) and then voluntarily decide to detach itself from the scheduler to make room for a new thread to avoid starvation of jobs on the queue.
For now, we use this for acquiring a collection level lock (as read lock for write operations and as write lock for exclusive access), if we cannot acquire the lock within 1s. This will then allow the scheduler to create new threads to continue work on whatever priority is suitable.
=> Implement SupervisedScheduler::detachThread [BTS-1670]

ubsan_arangodb_suppressions.txt
Add a suppression for RocksDB-related UBSan errors to our suppression file:
```
/home/tobias/Documents/ArangoDB/arangodb/arangodb/3rdParty/rocksdb/util/crc32c.cc:672:40: runtime error: load of misaligned address 0x7f638df3b006 for type 'uint32_t' (aka 'unsigned int'), which requires 4 byte alignment
0x7f638df3b006: note: pointer points here
9f 5b 06 00 01 02  00 03 02 04 00 00 00 00  00 66 72 69 63 61 2f 41  62 69 64 6a 61 6e 00 00  00 00
^
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/tobias/Documents/ArangoDB/arangodb/arangodb/3rdParty/rocksdb/util/crc32c.cc:672:40 in
/home/tobias/Documents/ArangoDB/arangodb/arangodb/3rdParty/rocksdb/util/crc32c.cc:1236:9: runtime error: load of misaligned address 0x7f638dcb8006 for type 'uint64_t' (aka 'unsigned long'), which requires 8 …
```
=> Suppress alignment errors in rocksdb's crc32c.cc

scripts/startLocalCluster.sh
`./scripts/startLocalCluster.sh` prints an `arangosh` cmd line that connects to `[::1]`, while the (default) address used is `localhost` (since https://github.com/arangodb/arangodb/pull/19144) - this is not necessarily the same. It now prints the actual address.
=> Use actual address in output

tests/js/client/shell/shell-one-shard.js
Having different `writeConcern`s for collections in the same `distributeShardsLike` group is not possible in Replication 2.0: this PR fixes a test accordingly.
=> [CINFRA-870] Fix test

arangod/RocksDBEngine/RocksDBMetaCollection.cpp
Subtraction of `detachThreshold` from `timeout_us` should only happen when timeout_us is greater than detachThreshold. Otherwise it could underflow.
=> fix lock timeout

js/common/modules/@arangodb/aql/explainer.js
Fix profile output when connecting a devel arangosh to older versions of arangod.
=> fix AQL query profile output with older arangod versions

arangod/Aql/RestAqlHandler.cpp
This PR adds more context output when a certain error condition is triggered.
It should help us find the root cause for a specific problem found in the tests:
```
[FAILED]  tests/js/client/aql/aql-view-arangosearch-ddl-combined.js
"testIndexAnalyzerCollection" failed: ArangoError: failure to remove dangling analyzers from 'TestNameDroppedDB' Aql error: (4) AQL: continued non-continuable method for /_api/aql. Please check: PRMR-b1276db6-efb7-43e1-90da-4d351cf68e10 (exception location: /root/project/arangod/Aql/ExecutionEngine.cpp:727). Please report this error to arangodb.com (while instantiating executors)
at Object.exports.checkRequestResult (/root/project/js/client/modules/@arangodb/arangosh.js:91:21)
at Object.exports.save (/root/project/js/client/modules/@arangodb/analyzers.js:156:19) …
```
=> add debug information when things go wrong

ubsan_arangodb_suppressions.txt
(temporarily) suppress UBSan warnings for immer library.
This is a workaround so that the remaining sanitizer errors actually get visible again.
=> (temporarily) suppress UBSan warnings for immer library

cmake/frontend/aardvark.cmake
The output dependency did not work as intended, because the existence of the build folder alone was already enough for make to conclude that there was nothing to do.
=> Simplify and fix cmake frontend build

lib/ProgramOptions/ProgramOptions.cpp
Fix a test that fails only on Windows, due to a wrong file extension expectation.
=> fix test that fails on Windows

CMakePresets.json
Enable full debug info for PR builds, so we have more information in CI-generated coredumps.
=> Enable full debug info for PR builds

3rdParty/README_maintainers.md, 3rdParty/date/src/tz.cpp
It turns out that the date library we use (3rdParty) performs a user
database lookup for no good reason. Namely, when we set the folder
for tzdata, then a static string variable is first automatically
initialized to ~/Downloads, which is then immediately overwritten
by the path we set. Unfortunately, the ~ in the path is looked up
via the getpwuid glibc-internally. This poses problems on static
glibc builds when /etc/nsswitch.conf is configured in a certain way
and a different glibc version is available on the host system than
the one with which we build.
This PR fixes this by replacing `~/Downloads` with
`/home/arangodb/Downloads` which has no further consequences.
=> Get rid of initgroups avoid nsswitch, take 3

arangod/Cluster/DropIndex.cpp, arangod/Cluster/DropIndex.h, arangod/Cluster/EnsureIndex.cpp, arangod/Cluster/EnsureIndex.h, arangod/Cluster/Maintenance.cpp
*This PR fixes a deserver side race during modifyLink on views. In Replication2 DBServers can actually see the index on a view being dropped, and a new one on the same fields being created in the same roundtrip. Therefore we now serialize creation of View indexes, and dropping of view indexes to One per Shard.
Note: We have the option to enhance this for One Per Shard Per View (where every view can at most have one per collection) with a bit more effort.
*
=> Bug fix/cinfra fix race link modify

arangod/RocksDBEngine/RocksDBColumnFamilyManager.cpp, arangod/RocksDBEngine/RocksDBOptionFeature.cpp
Rename the external name of the ZkdIndex cf to mdi.
=> Zkd External CF Name

arangod/Agency/Node.cpp, arangod/Agency/Node.h
Lazily initialize `dummyChildren` global variable.
This may or may not prevent initialization order issues across static variables.
Otherwise it should not do any harm.
=> lazily initialize dummyChildren global

CHANGELOG, arangod/V8Server/V8DealerFeature.cpp
This PR fixes the unnecessary copy of the `node_modules` folder located in the frontend area.
This issue has been (accidentally) found by our Windows test runs.
It got uncovered as Windows run into issues with the maximum path length:
```
Microsoft Windows has a MAX_PATH limit of ~256 characters.
```
This will now also speed up the server start as the V8Feature will NOT copy those files anymore
(As usually any node_modules directory consists of a lot of files and a lot of sub-directories).
=> [Bug-Fix] Do not copy UI's node_modules folder in V8

CHANGELOG, arangod/StorageEngine/TransactionState.cpp
Backport of https://github.com/arangodb/arangodb/pull/20458
Fix issue https://arangodb.atlassian.net/browse/BTS-1731
The PR fixes the test described in the BTS. 
Unfortunately I wasn't yet able to devise a minimal, reproducible example test case for our own repository.
=> fix BTS-1731

arangod/IResearch/IResearchDataStore.cpp
*The two failure points modified in this PR potentially produce debug errors on the followers for Replication2.
Replication2 assumes the follower cannot fail to insert a document, if the leader can do it, otherwise we would break protocol guarantees.*
in the test activating the failure point I have seen the following, valid!, race happening:
1) Insert documents on Leader
2) Replicate Documents to Follower
3) Follower confirms it has written the Replication to Replication2 Log, but not yet applied.
4) Leader continues with the test, and successfully passes the next assertion.
5) Failure Point activated
6) Do another Insert
7) Leader successfully triggers the failure point an throws error as expected.
8) Now the Follower applies the insert (1) to Storage, and hits the FailurePoint (which …
=> For replication2 activate failure points only on leaders

tests/js/client/recovery/search/view-arangosearch-link-populate-truncate-no-flushthread.js, tests/js/client/recovery/search/view-arangosearch-link-populate-truncate.js
*This temporarily disables two recovery tests for replication2.*
Description of what happens, and can also be enabled again as soon as the following ticket is fixed:
https://arangodb.atlassian.net/browse/CINFRA-876
=> Temporarily disable search recovery/truncate tests, linked a ticket to fix them

3rdParty/v8-build/CMakeLists.txt, CMakeLists.txt, tsan_arangodb_suppressions.txt
ATM we build V8 with sanitizers _disabled_, so the V8 code is not instrumented which means the sanitizer cannot observe the synchronizations inside that code. So when the V8 code calls back into instrumented code (e.g. the C runtime), TSan might report potential data races because of these missing synchronizations. For that reason we simply need to ignore _all_ data races coming from V8.
In addition this PR changes the build settings in V8 to only generate minimal debug information. For V8 we don't care about local variables etc.; function names are enough so that we can generate back traces. Also, this PR enables compression of debug sections for all executables to significantly reduce their sizes.
=> Suppress all data races coming from within V8 and improve build settings

CHANGELOG, arangod/RocksDBEngine/RocksDBVPackIndex.cpp, tests/js/common/shell/shell-index-stored-values.js
Backport of https://github.com/arangodb/arangodb/pull/20508
Fix https://arangodb.atlassian.net/browse/BTS-1741
* BTS-1741: fix updates of values in unique persistent indexes with stored values defined for them. When such an index value was updated, it was possible that the stored value was not correctly updated, so that subsequent reads of the index value would run into exceptions such as `Expecting type Array or Object`.
=> Fixed issue BTS-1741

CHANGELOG, arangod/RocksDBEngine/RocksDBVPackIndex.cpp, tests/js/client/shell/shell-index-stored-values.js
Fix https://arangodb.atlassian.net/browse/BTS-1741
* BTS-1741: fix updates of values in unique persistent indexes with stored values defined for them. When such an index value was updated, it was possible that the stored value was not correctly updated, so that subsequent reads of the index value would run into exceptions such as `Expecting type Array or Object`.
=> Fixed BTS-1741

arangod/Cluster/ClusterInfo.cpp
*The HotRestore did not erase ReplicatedLogs and CollectionGroups from Current (Replication2). This could leave behind the two in case the log was created after the Hotbackup was taken, eventually causing issues when removing dead servers being responsible in Current for Logs that in fact do not exist anymore.*
=> [CINFRA] Let Hotbackup remove ReplicatedLogs and CollectionGroups from current

tests/js/client/recovery/search/view-search-alias-populate-truncate-no-flushthread.js, tests/js/client/recovery/search/view-search-alias-populate-truncate.js
Addition to: https://github.com/arangodb/arangodb/pull/20490
*The tests in here are flaky and require some help from Search Core team to be sorted out. Disable them for now on Replication2 only*
=> Disable more Flaky View Recovery tests

CHANGELOG, arangod/Cache/CacheOptionsProvider.h
Lower memory usage high water mark multiplier for in-memory caches to 56% of the configured cache size value.
These 56% are the same value that was used in previous version of ArangoDB. We temporarily increased the value in devel, but it turned out that the cache can still overcommit memory because its memory reclamation procedure is asynchronous and can run in parallel to other tasks that insert new data.
To stay on the safe side and not overcommit more memory usage than before, the default high water multiplier value is reverted to 56%, the same value as used in all previous versions.
=> lower memory usage high water mark multiplier for in-memory cache

tests/js/server/replication2/replication2-supervision-wait-for-sync-false.js
*The test here performs a server crash and then wants to write on the new leader. It did only wait for a new server to be planned as leader, but not actually taking leadership. The race should now be gone.*
=> CINFRA: Test fix: Wait for leadership to be established.

js/common/modules/@arangodb/aql/explainer.js
When running `db._profileQuery(...)` directly on a DB-Server, this previously resulted in the following, rather cryptic error message:
```
JavaScript exception in file '/home/jan/Arango311NoAsan/js/common/modules/@arangodb/aql/explainer.js' at 852,22: TypeError: Cannot read property 'nodes' of undefined
!  recursiveWalk(plan.nodes, 0, 'COOR');
!                     ^
stacktrace: TypeError: Cannot read property 'nodes' of undefined
```
This is because DB-Servers do not return profiling information, only Coordinators and single servers do.
Instead of returning this cryptic error message, trying to profile a query on a DB-Server will now result in the more understandable error
```
Incomplete query execution plan data - this should not happen unless when connected to a DB-Server. fetching …
```
=> emit a proper error message when profiling on a DB-Server

CHANGELOG, arangod/RestHandler/RestIndexHandler.cpp, arangod/RestServer/TtlFeature.cpp, tests/js/client/shell/shell-index.js
A previous PR changed the coordinator `indexes()` method to list all available indexes to also return in-flight indexes.
This PR reverts this change.
It also suppresses the logging of expected error messages during progress reporting for shards that have not yet started creating their local index parts.
=> do not expose hidden indexes by default

CHANGELOG, CMakeLists.txt, arangod/RestServer/TtlFeature.cpp, arangod/RestServer/TtlFeature.h, tests/js/common/shell/shell-ttl.js
Improvements for TTL index removal queries:
- do not have max query runtime affect TTL index removal queries
- do not favor certain databases/collections/shards in the removals, but give them more or less equal probability of being picked
- reduce the default amount of documents to be removed per collection (`--ttl.max-collection-removes` startup option`) from 1m to 40k. this allows different databases/collections/shards to be picked in a single TTL background thread iteration
- do not use an AQL query for removing documents from the TTL index. using an AQL query initiated on the DB server is not ideal because it will intermediate commit on followers but can be rolled back on leaders
=> improvements for TTL index removal queries

arangod/Aql/OptimizerRules.cpp, tests/js/client/aql/aql-optimizer-collect-into.js
Allow removal of CalculationNodes that are just aliases if a query contains a COLLECT ... INTO expression with an expression output variable, e.g. `INTO x = expr`.
Query execution plan without this PR:
```
Query String (98 chars, cacheable: false):
for doc in prices   collect ticker = doc.TICKER   into dates = doc.date   return { ticker, dates }
Id   NodeType          Calls    Par     Items   Filtered   Runtime [s]   Comment
1   SingletonNode         1      -         1          0       0.00001   * ROOT
9   IndexNode          5773   5772   5772655          0       1.65867     - FOR doc IN prices   /* persistent index scan, index only (projections: `TICKER`, `date`) */    LET #8 = doc.`TICKER`, #9 = doc.`date`   
3   CalculationNode    5773   5771   5772655          0 …
```
=> allow more optimization for specific COLLECT ops

Documentation/Metrics/arangodb_agency_callback_number.yaml
Backport of https://github.com/arangodb/arangodb/pull/20543
Fix an inaccurate description for `agency_callback_number` metric.
=> fix metric documentation

js/client/bootstrap/modules/internal.js, tests/js/client/server_parameters/test-export-shard-usage-metrics-bytes-per-shard-per-user-cluster.js
*Test-Environment only fix. Failurepoints in Clusters with authentication stopped working in devel. Unfortunately the Suite still reports Success it just does not run tests as it claims FailurePoints are not available, which is allowed in general. This PR fixes the test for availability to actually ask the coordinator. Furthermore the call to activate FailurePoints now expects a JWT token, so it can activate them on DBSevers / Agents as well.*
=> [bug-fix] Fixed Cluster Failure Points while using authentication

CHANGELOG, arangod/VocBase/LogicalCollection.cpp, tests/js/client/shell/shell-collection-properties-propagation-cluster.js
Allow changing writeConcern of dependent collections.
Previously changing the `writeConcern` property of collections that also have
their `distributeShardsLike` property set was disallowed. This is now allowed.
=> allow changing writeConcern of dependent collections

tests/js/client/shell/multi/shell-ttl-nocov.js
Increase test timeout inside a flaky test
=> increase test timeout

arangod/RocksDBEngine/RocksDBMetaCollection.cpp, tests/js/client/shell/shell-dropped-followers-elcheapo-commit-cluster.js
A certain test was assuming that all queries would have specific AQL timeout values set.
This assumption however cannot be satisfied, because there may be other, cluster-internal queries going on concurrently to the test, e.g. statistics gathering, cleanup etc.
=> fix a too general assertion

arangod/Aql/ExecutionBlockImpl.h, arangod/Aql/ExecutionBlockImpl.tpp
Async prefetching could post a task onto the scheduler. If this task is not picked up in time, we could claim that task for ourselves and simply to the work directly. However, we could post yet another task for the next batch. This could go on and on, filling up the scheduler queue. As a side effect, there was also a race where an old task could be executed with an old AqlCallStack. To avoid this, we now rearm the already posted task with the current AqlCallStack and set it to pending. This way we can ensure that either the updated task is available to be picked up, or if it was picked up before we could make it available again, we will realize and can then repost it on the scheduler.
=> Fix issue that prefetch tasks could flood the scheduler queue

arangod/RestHandler/RestDumpHandler.cpp, arangod/RestHandler/RestDumpHandler.h, arangod/StorageEngine/EngineSelectorFeature.cpp, arangod/VocBase/Methods/Databases.cpp
A new check that was added recently could result in undefined behavior on the coordinator, because we tried to access the RocksDBEngine which is not available on Coordinators.
To avoid such mistakes in the future this PR also adds an assertion that we do not cast to the wrong engine type.
=> RocksDBEngine is only available on dbservers

arangod/Replication2/StateMachines/Document/DocumentLeaderState.cpp
Normally, before the log leader tries to apply a resource update locally (e.g. drop a shard), it first has to replicate the same update on followers. If replication succeeds, but the leader itself is unable to apply the operation locally, we consider the leader unable to continue and kill it.
However, if the operation fails due to the leader being shut down, there's no reason to panic. All we have to do is make sure to keep the log entry around (not calling release anymore), and let the shutdown continue. That is the purpose of this PR.
Additionally, a couple of `std::move` around shard IDs were removes, as they became obsolete since now ShardID is trivially copyable.
=> [CINFRA] Handle shutdown gracefully

js/apps/system/_admin/aardvark/APP/react/src/views/query/queryResults/QueryTableView.tsx
Fixes a UI crashing due to handling of nulls and relying on the first item in the collection. Now finds the first valid item.
if some item in the array is null, it will show like this:
=> FE-428: add null/undefined handling for rows in query table result

js/client/modules/@arangodb/testutils/instance.js, js/client/modules/@arangodb/testutils/testing.js
*When you run scripts/unittests --replicationVersion 2  it is supposed to set the settings for replication version 2. In case you omit this value it would always set replication version 1 and ignore what is defined in etc/testing/xxx.conf. Now there is no default value in the testing options anymore, so if you omit above option etc/testing/xxxx.conf will win again.*
=> Test Only Fix: ReplicationVersion in scripts/unittests

tests/js/client/server_parameters/test-early-connections-noncluster.js
When there is high load on the test system, 30s might not be enough for the single server to come up.
=> nightly fix startup 

arangod/RestServer/TtlFeature.cpp, tests/js/client/shell/multi/shell-ttl-nocov.js
*The TTL background thread to skip over followers only worked on Replication1. Now we use the shared mechanism that works in both cases.
Also slightly adapted the test to be more resilient against "bad luck" the test can only wait if any DBServer has performed a TTL cleanup, if things are unlucky we have a server that only has Followers, so it does nothing, which would cause the test to fail. Now we wait for at least 4 runs of TTL, which increases the odds that at least one leader hat the chance to perform one.*
=> Fixed check if a Shard is a leader for Replication2 in TTL BG thread

tests/js/client/restart/test-restart-replication2-syncer-thread-off.js
The test is meant to check that we disallow the creation of replication2 databases in case the syncer thread is off. However, if there are already replication2 databases on disk (which is the case of `_system` when replication2 is on by default), it is not allowed to switch the syncer thread off, and therefore the test does not make sense in that context.
This PR checks the version of the `_system` database and skips the test accordingly.
=> [CINFRA] Adjust replication2 test

scripts/startActiveFailover.sh, scripts/startLocalCluster.sh, scripts/startStandAloneAgency.sh
Backport of https://github.com/arangodb/arangodb/pull/20591
The path to self-signed server certificate previously was "UnitTests/server.pem", but the "UnitTests" directory got removed a while ago. The certificate file was then moved to "etc/testing/server.pem" without the startup scripts having being adjusted properly.
This PR fixes the certificate path in the startup scripts.
=> fix wrong certificate path in startup scripts

tests/js/client/server_parameters/test-export-shard-usage-metrics-bytes-per-shard-per-user-cluster.js
The user metrics test is flaky when using the replication2 setup: https://app.circleci.com/pipelines/github/arangodb/arangodb/22931/workflows/3abdccff-48dc-4582-aabf-d5486b65a1d5/jobs/1551236/tests#failed-test-0
For the collection that has 5 shards, sometimes 24 documents might not be enough to populate all of them, causing an assertion to fail, because fewer shards are used. By increasing the number of documents, the problem goes away.
=> [CINFRA] Metrics replication2 flaky test

arangod/Replication2/StateMachines/Document/DocumentStateErrorHandler.cpp, arangod/RocksDBEngine/RocksDBCollection.cpp
In a [previous PR](https://github.com/arangodb/arangodb/pull/20581), the replication step of the `CreateIndex` operation has been moved into the `RocksDBCollection::createIndex` method, mainly with the purpose of avoiding deadlocks caused by the ordering of transaction and index operations in the replicated log.
However, this now leaves a time window during which the replicated state is fetched during index creation, but there is nothing to stop the state from becoming unavailable. Dropping the state in this case doesn't cause any harm - it is ok to abort the index creation and move on, it's not going to matter anymore whether the index has been finished or not.
This PR adds a quick fix to that, by marking the `REPLICATED_STATE_NOT_FOUND` error as safe in the context of a `CreateIndex` …
=> [CINFRA] Index Creation Error

CHANGELOG, arangod/Cluster/ClusterInfo.cpp, tests/js/server/dump/dump-cluster.js
*Hot restores are missing [ES-1892](https://arangodb.atlassian.net/browse/ES-1892)*
[ES-1892]: https://arangodb.atlassian.net/browse/ES-1892?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [3.10] analyzers restored after hot restore

CHANGELOG, arangod/Cluster/ClusterInfo.cpp, tests/js/server/dump/dump-cluster.js
*Hot restores are missing [ES-1892](https://arangodb.atlassian.net/browse/ES-1892)*
[ES-1892]: https://arangodb.atlassian.net/browse/ES-1892?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [3.11] analyzers restored after hot restore

tests/js/client/chaos/test-chaos-load-common.inc
Enable debug logging for chaos tests.
This is only a temporary means so that we can better understand chaos test failures.
=> enable debug logging for chaos tests

CHANGELOG, arangod/Cluster/ClusterInfo.cpp, tests/js/server/dump/dump-cluster.js
*Hot fix 3.11.7-1 [ES-1892](https://arangodb.atlassian.net/browse/ES-1892)*
[ES-1892]: https://arangodb.atlassian.net/browse/ES-1892?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix missing analyzers after hot restore

tests/Replication2/ReplicatedState/StateMachines/DocumentState/SnapshotTest.cpp
This fixes a compilation error in non-maintainer builds in the unit
tests.
We just add a return statement which is never reached, but the compiler
is not aware of this.
=> Fix compilation of Replication2 unit tests on non-maintainer builds

arangod/ClusterEngine/ClusterCollection.cpp, arangod/ClusterEngine/ClusterCollection.h, arangod/Replication2/StateMachines/Document/DocumentLeaderState.cpp, arangod/Replication2/StateMachines/Document/DocumentStateErrorHandler.cpp, arangod/Replication2/StateMachines/Document/DocumentStateShardHandler.cpp, arangod/Replication2/StateMachines/Document/DocumentStateShardHandler.h, arangod/Replication2/StateMachines/Document/MaintenanceActionExecutor.cpp, arangod/Replication2/StateMachines/Document/MaintenanceActionExecutor.h, arangod/RocksDBEngine/RocksDBCollection.cpp, arangod/RocksDBEngine/RocksDBCollection.h, arangod/StorageEngine/PhysicalCollection.h, arangod/VocBase/LogicalCollection.cpp, arangod/VocBase/LogicalCollection.h, arangod/VocBase/Methods/Indexes.cpp, arangod/VocBase/Methods/Indexes.h, tests/Mocks/PhysicalCollectionMock.cpp, tests/Mocks/PhysicalCollectionMock.h, tests/Replication2/Mocks/DocumentStateMocks.h
**Problem**
The problem has been occurring mainly withing Search tests that create indexes and drop servers. I will briefly explain it below:
_Thread 1_
- one Actor thread is executing the `CreateIndex` operation
- gets stuck at `RocksDBCollection::createIndex()` while trying to fetch the replicated state, because fetching the replicated state requires locking `VocBaseLogManager::_guardedData`
_Thread 2_
- an `UpdateReplicatedLogAction` maintenance job that tries to resign the log
- it has already acquired the `VocBaseLogManager::_guardedData` lock during `VocBaseLogManager::updateReplicatedState()`
- resigning the log requires all the Actors to do a soft shutdown
- shutting down is not possible, as one of the Actors is stuck in _Thread 1_
**Solution**
It is possible to avoid fetching the …
=> [CINFRA] Fix shutdown hanger

arangod/Replication2/ReplicatedLog/Components/StateHandleManager.cpp, tests/Replication2/CMakeLists.txt, tests/Replication2/Mocks/FollowerCommitManagerMock.h, tests/Replication2/ReplicatedState/StateHandleManagerTest.cpp
*We use a protected structure in the StateHandleManager where we make sure it cannot be access in parallel.
However there exists a path where the protected element gets a nullptr shortly before it is freed, namely resign(). Between resign and deallocation however there can be another shared_ptr instance that access the protected element. The functions fixed here just dereferenced it without doing nullptr tests.
For two of them it is save because they share the same outside lock, so I added an ASSERT that we do not have a nullptr.
For one (the case we triggered) I added a throw.
For the last one (acquireSnapshot) the method is actually a noexcept and does not return anything. So I made it only do action if it is still possible.
*
=> [BTS-1774] Fix potential nullptr access in StateHandleManager

arangod/Aql/QuerySnippet.cpp, tests/js/client/aql/aql-index-join.js
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/1450
Local expansion for joins for shards on the same dbserver was not enabled. This could lead to wrong results, because only one shard was read from each server.
=> [BTS-1789] Fix local expansion for join nodes

arangod/Indexes/IndexFactory.cpp, client-tools/Restore/RestoreFeature.cpp, client-tools/Utils/ClientTaskQueue.h, tests/test-definitions.txt
This PR fixes a sporadic failure of the testRestoreIndexesFulltextLengthZero test, but the underlying issue that caused this sporadic failure is even more severe.
Similar to a previous bugfix (#20526), the fulltext index is always sparse, which must be considered in the index compare function. Because this was not the case, the maintenance would first create the index and report to the agency, but in the next iteration when we compare the local indexes against the plan, the comparison would yield false, so we drop the index again - so the db servers keep creating, dropping, creating, dropping, ....
In case the supervision observes the situation where all servers have reported the index in current, it clears the `isBuilding` flag which indicates to the client that the request has been …
=> Fix testRestoreIndexesFulltextLengthZero

arangod/Graph/PathManagement/SingleProviderPathResult.cpp
When cleaning up the path result, only `_vertices` and `_edges` were previously cleared. `_weights` were not cleared. This looks fishy.
=> also clean weights when result is cleaned up

CHANGELOG, arangod/RocksDBEngine/RocksDBChecksumEnv.cpp, arangod/RocksDBEngine/RocksDBChecksumEnv.h, lib/Basics/files.cpp
Add progress reporting for RocksDB .sst file checksum computation.
Upon startup, ArangoDB Enterprise Edition will check if for every RocksDB .sst file there is a corresponding .hash file with the SHA256 hash value of the .sst file's contents. Otherwise such .hash file will be created at startup.
Normally, the .hash file creation is triggered by RocksDB whenever an .sst file is written to disk. So there should not be many .hash files missing on a restart. In case of a crash, a few .hash files may be missing and may be recomputed. This should be quick and unintrusive.
However, when upgrading an existing database from the Community Edition to the Enterprise Edition, there will be no .hash files initially, as they are only written out in the Enterprise Edition. So the startup will lead to all …
=> add progress reporting for RocksDB .sst file checksum computation

.circleci/base_config.yml, js/client/modules/@arangodb/testutils/instance.js
...and make sure report files are written to the path that was originally configured in the sanitizer options.
This should make sure that the sanitizer reports are published as artifacts.
=> Refactor how sanitizer logs paths are maintained... 

arangod/Aql/RestAqlHandler.cpp, js/common/bootstrap/errors.js, lib/Basics/errors.dat
Fix sporadic query setup errors.
During testing there were sporadic errors when setting up AQL queries via the route POST `/_api/aql/setup`:
AQL: continued non-continuable method for POST /_api/aql/setup
This error is due to setupClusterQuery() returning a future, which is being waited for using waitForFuture(). waitForFuture() returns RestStatus::DONE if the future was already executed, and everything is fine then.
If the future was not already executed, waitForFuture() returns RestStatus::WAITING, so that eventually the RestHandler is restarted via its continueExecute() method. For the RestAqlHandler, this always triggered the above error if restarting was done for the HTTP POST setup request.
The fix is to allow restarting the RestHandler in case of HTTP POST as well, and then simply …
=> fix sporadic query setup errors

arangod/Aql/Collection.cpp, arangod/Aql/Collection.h
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/1456
Removed unused code and potential access of an empty vector returned by getResponsibleServer.
=> cleanup uses of getResponsibleServer

js/common/modules/@arangodb/foxx/store.js
Once we branched off 3.12, the `shell-fishbowl-replacement.js` started failing. The version name (at the time of this PR) is `3.12.0-alpha1`. We're using the `semver` package to check whether a foxx module is compatible with the server version, and if so, include in the list of modules.
However, by default, prerelease versions (like '3.12.0-alpha1') will not satisfy ranges specified without a prerelease tag due to the way semantic versioning treats prerelease versions as lower than the corresponding version without the prerelease tag. If you want prerelease versions to be considered as satisfying the range, you need to include the `includePrerelease` option.
This is why we end up with less packaged than expected and the test fails.
=> Fixing Prerelease Incompatibility

arangod/Aql/OptimizerRule.h, arangod/Aql/OptimizerRulePushDownLateMaterialization.cpp, tests/js/client/aql/aql-index-join.js
Consider the following query:
```
for doc1 in A
sort doc1.x
for doc2 in B
filter doc2.x == doc1.x
sort doc2.x
limit 20
filter doc1.z == 0
return [doc1, doc2]
```
Before this PR, this query was optimized as
```
Id   NodeType          Par   Est.   Comment
1   SingletonNode              1   * ROOT
19   JoinNode                 100     - JOIN
19   JoinNode                 100       - FOR doc1 IN A   /* index scan + document lookup with late materialization */
19   JoinNode                   1       - FOR doc2 IN B   /* index scan + document lookup with late materialization */
17   MaterializeNode          100     - MATERIALIZE doc2 INTO #10
8   CalculationNode          100     - LET #4 = #10.`x`   /* attribute expression */
9   SortNode                 100     - SORT #4 ASC …
```
=> More Push-Down-Materialize with Joins

CMakeLists.txt
provide more control over build date generation
- when setting the CMake variable `ARANGODB_BUILD_DATE` to an arbitrary date/time string, it will be picked up by the build and used as the build date string placed in `build/lib/Basics/build-date.h`.
- when not setting the CMake variable `ARANGODB_BUILD_DATE` or setting it to an empty string, it will be checked if the file `build/lib/Basics/build-date.h` already exists or not. if it already exists, the build date in the file will be kept unaltered. this is to avoid rebuilding files unnecessarily. if the file does not yet exist, the current date/time will be put into this file, so that upon the next cmake invocation, the file will be there and the build date will be reused.
=> provide more control over build date generation

.circleci/base_config.yml, .circleci/config.yml
We check if our current branch has an associated PR on github, if yes then we use the base branch as default.
Otherwise, if our current branch is a release branch (i.e., matches the pattern `^[0-9]+\.[0-9]+(\.[0-9]+)$`), then we use the current branch as default. Otherwise we fall back to `devel`.
=> Improve logic to determine enterprise-branch

.circleci/base_config.yml, .circleci/config.yml
Previously we had the CircleCI "auto-cancel redundant workflows" feature activated, which automatically cancelled any pending workflows whenever an new build was triggered for the same branch (including whenever something was pushed to that branch) - except for the default branch (in our case "devel"). While this could be helpful in some cases to avoid wasting build credits, it was sometimes also rather annoying (e.g., because pushing an CHANGELOG update would cancel the previously started build). Worse, for scheduled builds on branches other then devel, concurrently triggered pipelines would cancel other scheduled pipelines (e.g., the tsan pipeline could cancel the alubsan pipline or vice versa).
Instead of relying on the "auto-cancel redundant workflows" feature, this PR implements …
=> Implement custom pipeline cancellation

client-tools/Dump/DumpFeature.cpp
Mainly for documentation (a user noticed the incorrect version numbers in older versions)
=> arangodump: Set all parallel dump versions

CHANGELOG, arangod/RestHandler/RestReplicationHandler.cpp, arangod/RestHandler/RestTransactionHandler.cpp, arangod/Transaction/Manager.cpp, arangod/Transaction/Manager.h, arangod/Utils/ExecContext.h, tests/Transaction/ManagerTest.cpp, tests/js/client/shell/transaction/shell-transaction.inc
Transactions are bound to the user who started it, and the database it was started for. However, there was a code path that was missing the database check, which allowed the transaction id to be used in a request to a different database. The request would not return an error, but it would actually be executed in the context of the original database, and not the one specified in the request.
With this fix, such a request will now return an ERROR_TRANSACTION_NOT_FOUND.
=> Verify transaction database name

arangod/RocksDBEngine/RocksDBTransactionCollection.cpp
This PR fixes an assertion that sporadically occurs in replication2 tests (primarily in tsan/ubsan builds, but not exclusively).
In the test, we only communicate the leader, and once we have received the response from the leader, we consider the test finished, so the teardown cleans up and deletes the database. The problem is, that with replication2, the follower perform operations asynchronously, so it can happen that the test drops the database while the follower is still busy applying the changes. Even though we do not immediately drop the DB while it is still in use, we mark the DB and all its collections as deleted, and at the same time _remove all the indexes from the collection_. And this then caused the assertion failure when we try to commit the ongoing transaction and realize …
=> Fix: indexes are removed when collection is marked as deleted

CHANGELOG, arangod/RocksDBEngine/RocksDBZkdIndex.cpp
https://arangodb.atlassian.net/browse/BTS-1808
* BTS-1808: fix arangodump format for ZKD indexes. Previously the structural dump of ZKD indexes was missing the "fieldValueTypes" attribute, which was necessary to restore a ZKD index at least in the cluster.
A test for this is contained in most recent versions of `rta_makedata`.
- [] Enterprise PR:
=> Fix BTS-1808

js/client/modules/@arangodb/testutils/process-utils.js
dump/restore tests would only anounce failing due to arangodump/restore exit codes. 
The actual error wasn't captured.
This PR makes these write logfiles, and reads them into the results, so `testfailures.txt` gets the error messages as well.
=> make arangodump/restore write logfies, so we can report errors.

.circleci/base_config.yml
Tests are ran via python. python does line buffering for high through-put. 
However, our throughput isn't high, and there may be lines printed minutes appart which would reset this circle-ci-timer.
Hence we rather turn of the python line buffering, so we immediately see whats printed.
See https://stackoverflow.com/questions/107705/disable-output-buffering for details.
=> turn of python line buffering in circle ci

arangod/Aql/Ast.cpp, arangod/Aql/Ast.h, arangod/Aql/BindParameters.cpp, arangod/Aql/BindParameters.h, arangod/Aql/Condition.cpp, arangod/Aql/IResearchViewOptimizerRules.cpp, arangod/Aql/OptimizerRules.cpp, arangod/Aql/Query.cpp, arangod/Aql/TraversalConditionFinder.cpp, arangod/Aql/grammar.cpp, arangod/Aql/grammar.y, arangod/GeoIndex/Index.cpp, arangod/Indexes/Index.cpp, arangod/Indexes/SortedIndexAttributeMatcher.cpp
Initial development for https://arangodb.atlassian.net/browse/EF-54
split injection of bind parameters into query AST into 2 different functions:
1. injection of all bind parameters that are absolutely required by the optimizer to figure out the sense of the query. this phase will inject collection bind parameter values (e.g. `@@collection`) and bind parameters that include attribute names (e.g. `doc.@attr`). no value bind parameters will be injected in this phase.
2. injection of all value bind parameters into the query.
by splitting the bind parameter injection into 2 functions, we can later move the second injection to a later point in the query processing, so that value bind parameters can get injected into the query after the final query plan has been created.
this could help future …
=> split injection of bind parameters into query AST

CHANGELOG, arangod/Cluster/AutoRebalance.cpp, arangod/RestHandler/RestAdminClusterHandler.cpp, tests/Cluster/ShardAutoRebalancerTest.cpp
This is a backport from devel: https://github.com/arangodb/arangodb/pull/20719
This fixes a problem in shard rebalancing. Here is a description of the
problem:
https://arangodb.atlassian.net/browse/BTS-1814
If for some collection a server is not the leader for any of its
shards, but has some follower shards. Then the leader imbalance score
does not take into account this server. Therefore, the system does not
consider leader moves to this server, since they often do not
improve the score. Therefore the rebalancer often only rebalances
leaders between servers which already have leader shards.
Furthermore, there is another small problem that some parameter of the
algorithm is only set from the user's input after the computation of the
imbalance score "before" has already happened. This is …
=> Fix shard rebalancer [BTS-1814]

CHANGELOG, arangod/Cluster/AutoRebalance.cpp, arangod/RestHandler/RestAdminClusterHandler.cpp, tests/Cluster/ShardAutoRebalancerTest.cpp
This is a backport from devel: https://github.com/arangodb/arangodb/pull/20719
to 3.12.0
This fixes a problem in shard rebalancing. Here is a description of the
problem:
https://arangodb.atlassian.net/browse/BTS-1814
If for some collection a server is not the leader for any of its
shards, but has some follower shards. Then the leader imbalance score
does not take into account this server. Therefore, the system does not
consider leader moves to this server, since they often do not
improve the score. Therefore the rebalancer often only rebalances
leaders between servers which already have leader shards.
Furthermore, there is another small problem that some parameter of the
algorithm is only set from the user's input after the computation of the
imbalance score "before" has already happened. …
=> Repair shard rebalancer [BTS-1814]

.circleci/base_config.yml
Without this fix the CircleCI output contains these errors/warnings:
```
/bin/bash: line 2: [: =: unary operator expected
/bin/bash: line 7: [: =: unary operator expected
```
=> Fix a small issue in a bash-if that causes a confusing warnings

CHANGELOG, lib/Logger/LogTimeFormat.cpp, lib/Logger/LoggerFeature.h
Update default log format. Include thread id and utc mirco seconds timestamp.
=> Update default log format

CHANGELOG, arangod/Cluster/SynchronizeShard.cpp, arangod/Cluster/SynchronizeShard.h, arangod/RestHandler/RestReplicationHandler.cpp, arangod/Sharding/ShardDistributionReporter.cpp
* Improve debug logging for shard synchronization by adding database name/shard name to most debug messages.
* Remove "read" lock acquisition on leader when trying to get shard follower in sync. The exclusive lock phase remains unchanged. Acquiring a read lock on the leader is not necessary, as under RocksDB this does nothing.
* The leader-side code that can handle "read" lock acquisitions still remains unchanged, because followers running older ArangoDB versions may still call it.
* Reduce timeout for acquiring the exclusive lock on the leader from 300s to 240s. The network request timeout still stays at 300s, but the leader-side lock acquisition timeout is now 240s. This is not perfect, but it prevents many cases in which the follower declares the request failed (because of network …
=> simplify shard synchronization code

arangod/Aql/Ast.cpp, arangod/Aql/BindParameters.cpp, arangod/Aql/BindParameters.h
use FlatHashMap for bind parameters
this allows us to do heterogeneous lookups in the map of bind parameter names using std::string_view keys, and thus saves us from converting any lookup value into an std::string first.
potential changes in iterator invalidation behavior when moving from std::unordered_map to FlatHashMap have been considered and are not relevant. the map in question is only used internally in the BindParameters class and all usages are safe.
=> use FlatHashMap for bind parameters

CHANGELOG, arangod/RestServer/LanguageCheckFeature.cpp
This addresses https://arangodb.atlassian.net/browse/BTS-1824
This is the backport for 3.12.0.
Original PR: https://github.com/arangodb/arangodb/pull/20748
The problem is that the ICU library was updated for 3.12. The new
version detects the language settings differently for the case that the
locale is set to "C". The new version then uses "en_US_POSIX", whereas
the old version sometimes takes "" (empty string) and sometimes uses
"en_US" (depending on the charset settings). This is a problem in
upgrades, which use the LanguageFeatureCheck feature to FATAL exit,
if the detected language setting is different from the one found during
database directory creation.
This PR "fixes" this problem by being more tolerant in the check, thus
allowing seamless upgrades. Furthermore, new databases in …
=> Accept legcy LANGUAGE detections for C locale [BTS-1824]

arangod/Agency/Constituent.cpp, arangod/Aql/Query.h, arangod/Aql/QueryCursor.h, arangod/Auth/TokenCache.cpp, arangod/Auth/TokenCache.h, arangod/Cluster/ClusterFeature.cpp, arangod/RocksDBEngine/RocksDBBackgroundThread.cpp, arangod/Statistics/StatisticsFeature.cpp, arangod/Statistics/StatisticsFeature.h, arangod/Utils/CMakeLists.txt, arangod/Utils/Cursor.cpp, arangod/Utils/Cursor.h, arangod/Utils/CursorRepository.cpp
Reduce dependencies on `system-functions.h` header file.
The header file `system-functions.h` was previous included by 4 header files, of which 2 were very essential.
So any change to `system-functions.h` would trigger a rebuild of the majority of files.
This PR removes the include directives for `system-functions.h` from the header files and moves them into the appropriate .cpp files. A few other unused directives in header files have also been removed and have been replaced with forward declarations.
=> reduce dependencies on system-functions.h

arangod/Cluster/HeartbeatThread.cpp
*This PR introduces a flush in the Heartbeat thread again which has been removed in 3.12 but has side-effects. This introduced a regression to 3.11..
As we still want to remove the flush here, we created a ticket: https://arangodb.atlassian.net/browse/EF-61 to handle a more targeted replacement.
*
=> BTS-1820: Flush ClusterInfo in Heartbeat again

arangod/Cluster/HeartbeatThread.cpp
*This PR introduces a flush in the Heartbeat thread again which has been removed in 3.12 but has side-effects. This introduced a regression to 3.11..
As we still want to remove the flush here, we created a ticket: https://arangodb.atlassian.net/browse/EF-61 to handle a more targeted replacement.
*
=> [3.12.0] BTS-1820: Flush ClusterInfo in Heartbeat again

js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/useReinitializeForm.ts
fixes an issue with property reinit
=> FE-440: fix properties initilization in analyzer form

CHANGELOG, arangod/GeneralServer/Acceptor.h, arangod/GeneralServer/AcceptorTcp.cpp, arangod/GeneralServer/AcceptorTcp.h, arangod/GeneralServer/AcceptorUnixDomain.cpp, arangod/GeneralServer/AcceptorUnixDomain.h, arangod/GeneralServer/AsioSocket.h, arangod/GeneralServer/GeneralCommTask.cpp, arangod/GeneralServer/GeneralCommTask.h, arangod/GeneralServer/H2CommTask.cpp, arangod/GeneralServer/H2CommTask.h, arangod/GeneralServer/HttpCommTask.cpp, arangod/GeneralServer/HttpCommTask.h, arangod/GeneralServer/VstCommTask.cpp, arangod/GeneralServer/VstCommTask.h
Late backport of https://github.com/arangodb/arangodb/pull/19727
Fix BTS-1489: https://arangodb.atlassian.net/browse/BTS-1489
All AsioSocket instances are now created via `std::make_shared()`. This allows us to pass a shared_ptr to an AsioSocket into a lambda, so the lambda can still safely refer to the AsioSocket without any lifetime issues.
With the fix it is possible that the AsioSocket posts a lambda with a this pointer (to the AsioSocket), and the lambda being executed after the AsioSocket is destroyed.
This fix is already included in 3.12.0 and devel.
=> BTS-1489: Race condition in AsioSocket shutdown when using SSL.

js/apps/system/_admin/aardvark/APP/frontend/js/views/infoView.js, js/apps/system/_admin/aardvark/APP/frontend/js/views/settingsView.js
Currently, on settings and info tab, there's some async API calls made before the render can happen. 
Eg. (all this on a slow network, but can also happen on large collections for eg)
1. open a collection, click on 'Settings'
2. Before it finishes loading, click on another tab, like 'Content'
3. At first you will see Content tab, but after a second it gets replaced with 'Settings'
See:
This adds a fix for adding a check after the async calls and before render. If the current route doesn't match, we return early
=> FE-433: prevent rendering of tabs if the route doesn't match

lib/Logger/LoggerStream.cpp
Do not copy log message.
Since c++20 there is a `view()` method to access an ostream's contents without copying it.
This PR is attempt to figure out if we can use this operator in all environments that we need to support.
=> do not copy log message

arangod/Aql/ClusterQuery.cpp, arangod/Aql/ClusterQuery.h, arangod/Aql/ExecutionPlan.cpp, arangod/Aql/ExecutionPlan.h, arangod/Aql/IResearchViewOptimizerRules.cpp, arangod/Aql/IndexJoinStrategy.cpp, arangod/Aql/Query.cpp, arangod/Aql/Query.h, arangod/Aql/QueryOptions.cpp, arangod/Aql/QueryOptions.h, arangod/Aql/RestAqlHandler.cpp, arangod/Aql/grammar.cpp, arangod/Aql/grammar.y, arangod/Aql/types.h, arangod/Cluster/ClusterTrxMethods.cpp, arangod/Cluster/TraverserEngine.cpp, arangod/Cluster/TraverserEngine.h, arangod/Indexes/SortedIndexAttributeMatcher.cpp, arangod/RestHandler/RestReplicationHandler.cpp, arangod/RocksDBEngine/RocksDBVPackIndex.cpp, arangod/StorageEngine/TransactionCollection.cpp, arangod/StorageEngine/TransactionState.cpp, arangod/Utils/SingleCollectionTransaction.cpp, arangod/V8Server/v8-vocbase.cpp, arangod/VocBase/AccessMode.h, js/client/modules/@arangodb/aql-helper.js, tests/js/client/aql/aql-graph-traverser-multiCollectionGraph.js
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/1462
Refactor `Query`/`ClusterQuery`
So that a `Query` can be prepared from velocypack input without having to create an artificial/inappropriate `ClusterQuery` instance.
Also clean up a bit of unrelated code in terms of used include directives and naming conventions.
This is a preparation PR to allow queries to be restored from serialized execution plans in the future.
=> refactor Query/ClusterQuery

arangod/Aql/ExecutionPlan.cpp, arangod/Aql/OptimizerRules.cpp, arangod/Aql/RegisterId.cpp, arangod/Aql/RegisterPlan.h, tests/js/client/aql/aql-optimizer-rule-move-calculations-down.js
Do not move uncorrelated subqueries down via optimizer rule `move-calculations-down`.
Doing so can cause performance degradations during query plan optimization for no good reason.
For example, if there is the following query
```
FOR doc IN ...
LET result1 = (...)
LET result2 = (...)
...
```
and `result1` and `result2` are uncorrelated, then there is no benefit in moving `result1` down past `result2`. 
Doing so anyway will trigger a recalculation of which variables are valid in the plan at any step, which is expensive and thus we want to avoid doing this unnecessarily.
=> do not move uncorrelated subqueries down

CHANGELOG, arangod/Sharding/ShardingFeature.cpp, arangod/Sharding/ShardingInfo.cpp, arangod/Sharding/ShardingStrategy.h, arangod/Sharding/ShardingStrategyDefault.cpp, arangod/Sharding/ShardingStrategyDefault.h, arangod/VocBase/Properties/CreateCollectionBody.cpp, client-tools/Dump/DumpFeature.cpp, client-tools/Restore/RestoreFeature.cpp, js/client/modules/@arangodb/testsuites/dump.js, tests/IResearch/IResearchAnalyzerFeatureTest.cpp, tests/Mocks/Servers.cpp, tests/js/client/dump/dump-multiple.js, tests/js/client/dump/dump-teardown-cluster.js, tests/js/client/dump/dump-teardown-multiple.js, tests/js/client/dump/dump-test.inc, tests/js/client/shell/api/api-replication.js
We would return false while the rta-checkdata test result is true. This would skip further tests. It was introduced in #19718, and since then those tests haven't been run.
Necessary changes to fix the by-now failing tests are also part of this PR. The most notable changes are the following:
- Change the default of shardingStrategy from `enterprise-compat`/`community-compat` to `hash` in the restore API, and adjust the tests accordingly. This is now consistent with the collection API, and the more sensible default. An inconsistent default would lead to test failures.
- Revert https://github.com/arangodb/arangodb/pull/20096: there are a bunch of tests that check that restoring a cluster-dump to a single server preserves the cluster-specific attributes that were removed in that PR. Other …
=> Repair dump/restore tests

CHANGELOG, arangod/Cluster/ClusterTrxMethods.cpp, js/client/modules/@arangodb/testsuites/chaos.js, tests/js/client/chaos/test-deadlock-cluster.js, tests/test-definitions.txt
Fix potential deadlocks in fast lock round
* Fix potential deadlocks in "fast lock round" when starting transactions in cluster. The "fast lock round" is used to send out transaction begin requests to multiple leaders concurrently, without caring about the order in whic requests are send out. This can potentially lead to deadlock with other out-of-order requests. Thus the intention of the "fast lock round" is to use a very low timeout for these requests, so that deadlocks would be detected and rolled back quickly. However, there was a code path that triggered the "fast lock round" with long request timeouts, which could lead to long wait times until deadlocks were detected and rolled back.
This PR also adds a new 3 minute chaos test `deadlock` that runs pseudo-random operations …
=> Fix potential deadlocks in fast lock round

CHANGELOG, arangod/VocBase/vocbase.cpp, tests/js/client/shell/agency-oneshard-regression-nocluster.js
*Alternative fix for: Fix upgrade of agents to 3.12.0 if --cluster.force-one-shard is set.*
https://github.com/arangodb/arangodb/pull/20786
=> Correctly return the Sharding Prototype of Agents

CHANGELOG, arangod/VocBase/Methods/Upgrade.cpp, arangod/VocBase/Methods/UpgradeTasks.cpp, arangod/VocBase/Methods/UpgradeTasks.h
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/1467
Add upgrade task to drop _pregel_queries system collections.
These collections are unneeded from 3.12.0 onwards, so we can as well delete them.
=> Add upgrade task to drop `_pregel_queries` system collections.

CHANGELOG, arangod/VocBase/vocbase.cpp, tests/js/client/shell/agency-oneshard-regression-nocluster.js
Backport of: https://github.com/arangodb/arangodb/pull/20788
*Fixed a sharding prototype mismatch on Agents, when they are started with force-one-shard and auto-upgrade at the same time.*
=> [3.12] Correctly return the Sharding Prototype of Agents

lib/Basics/ReadWriteLock.cpp, lib/Basics/ReadWriteLock.h, tests/Basics/ReadWriteLockTest.cpp
Add helper function to stringify the internal state of an RW lock.
The function is currently not used, but it can be used everywhere for debugging/development purposes.
=> add method to stringify RW lock state

CHANGELOG, arangod/GeneralServer/RestHandler.cpp
Log an info message if a request was queued for 30 seconds or longer in the scheduler queue.
This is a sign of severe overload or blockage, so we should make this visible to users.
=> Log info message for requests with queue time >= 30s

arangod/RocksDBEngine/RocksDBReplicationContext.cpp
Fix an invalid assertion in replication code.
The assumptions made in the assertion are correct for the case when a snapshot is taken under an exclusive lock. In this case, the number of documents in the collection and the snapshot are taken together under the lock.
However, if the number of documents is determined independent of the snapshot, there is no guarantee that the number of documents determined and the actual number of documents in the snapshot are identical.
This PR adjusts an assertion accordingly.
=> fix an invalid assertion during replication

arangod/RestHandler/RestCursorHandler.cpp, arangod/RestHandler/RestReplicationHandler.cpp, arangod/RestHandler/RestReplicationHandler.h, arangod/RestHandler/RestVocbaseBaseHandler.cpp, arangod/Transaction/Manager.cpp, arangod/Transaction/Manager.h, lib/Basics/FutureSharedLock.h, tests/Transaction/ManagerTest.cpp
Remove the detach thread thingy from the `leaderManagedTrx` function. Instead use a delayed future to make the current execution fiber sleep for some time. Previously we would block the thread and then eventually detach it.
=> Remove the detach thread code from transaction manager.

CHANGELOG, arangod/Scheduler/Scheduler.cpp, arangod/Scheduler/Scheduler.h, arangod/Scheduler/SchedulerFeature.cpp, arangod/Scheduler/SchedulerFeature.h, arangod/Scheduler/SupervisedScheduler.cpp, arangod/Scheduler/SupervisedScheduler.h, arangod/Transaction/Manager.cpp, tests/Cluster/RebootTrackerTest.cpp
Remove unused startup option for detaching threads.
The option became meaningless after commit https://github.com/arangodb/arangodb/commit/b0b9f026c2af1952c3218105f082c408e5c957d2.
=> obsolete now-unused startup option

CHANGELOG, arangod/Aql/RestAqlHandler.cpp, arangod/Cluster/ClusterTrxMethods.cpp, arangod/GeneralServer/RequestLane.h, arangod/GeneralServer/RestHandler.cpp, arangod/RestHandler/RestCollectionHandler.cpp, arangod/RestHandler/RestCollectionHandler.h, arangod/RestHandler/RestCursorHandler.cpp, arangod/RestHandler/RestCursorHandler.h, arangod/RestHandler/RestReplicationHandler.cpp, arangod/RestHandler/RestTransactionHandler.cpp, arangod/RestHandler/RestTransactionHandler.h, arangod/StorageEngine/TransactionState.cpp, arangod/StorageEngine/TransactionState.h, js/client/modules/@arangodb/test-helper.js, tests/js/client/shell/shell-transaction-commit-abort-overwhelm-cluster.js
* Prioritize requests for commiting or aborting streaming transactions on
leaders and followers, because they can unblock other operations. Also
prioritize requests in already started streaming transactions and AQL queries
over new requests because it is assumed that already started streaming
transactions and AQL queries can block other operations from starting, so
these should be completed first.
The following request priorities have changed:
- cluster-internal requests for continuing already started AQL queries have
changed their priority from low to medium. This excludes requests that
setup AQL queries on DB servers, which still run with low priority.
- requests that include the transaction id header are now elevated to run
with medium priority if they originally ran with low priority. …
=> Change request lane priorities

arangod/RocksDBEngine/RocksDBReplicationContext.cpp
*NO Production change, therefore no CHANGELOG entry made. This PR removes an assertion for the createKeys() replication API. The amount of _keys and the asynchronously stored count can be different. In the Method of the assertion there are Code-Paths where we get the Count and the _snapshot without holding required locks, so it is expected to be different. The assertion only triggered on the 0 vs some case, therefore it was seldom. We validated that the returned count is only used if we get the `documentCountAdjustmentTicket`, which is only set on the code-path where count and real number of docs should be synchronous. => We use the returned value to adjust the count of necessary.*
=> Removed incorrect assertion in bindCollectionIncremental

CHANGELOG, arangod/Cluster/HeartbeatThread.cpp
Fixes https://arangodb.atlassian.net/browse/BTS-1840.
In active failover mode, there is a potential connection leak for connections made to the agency on the leader, when there is a longer period with no leader changes.
In this case, the code that closes stale connections to the agency isn't executed, so the number of connections can keep increasing.
Other deployment modes (single server, cluster) are not affected by this issue.
=> fix BTS-1840

CHANGELOG, arangod/Aql/EngineInfoContainerDBServerServerBased.cpp, arangod/Aql/QueryRegistry.cpp, arangod/Aql/QueryRegistry.h, arangod/Aql/QueryString.h, arangod/Aql/RestAqlHandler.cpp, arangod/RestHandler/RestQueryHandler.cpp, arangod/RestHandler/RestQueryHandler.h, arangod/RestHandler/RestReplicationHandler.cpp, arangod/RestHandler/RestTransactionHandler.cpp, arangod/RestHandler/RestTransactionHandler.h, arangod/Transaction/Manager.cpp, arangod/Transaction/Manager.h, arangod/V8Server/v8-vocbase.cpp, tests/Transaction/ManagerTest.cpp, tests/js/client/server_parameters/test-query-registry-contents-cluster.js, tests/js/client/shell/test-trx-registry-contents-cluster.js
This PR adds internal APIs to dump the contents of the AQL query registry from DB-Servers plus the contents of the transaction manager on coordinators and DB-Servers.
The APIs are for internal use only, so they should not be considered part of the officially supported API, and thus do not need to be mentioned in our official documentation. The output of this API can change at any point without further notice.
=> add debug APIs

arangod/Replication2/StateMachines/Document/DocumentLeaderState.cpp, arangod/RestHandler/RestReplicationHandler.cpp, arangod/RestHandler/RestTransactionHandler.cpp, arangod/RestHandler/RestTransactionHandler.h, arangod/Scheduler/Scheduler.h, arangod/Transaction/Manager.cpp, arangod/Transaction/Manager.h, tests/Replication2/Mocks/DocumentStateMocks.h, tests/RocksDBEngine/TransactionManagerTest.cpp, tests/Transaction/ManagerTest.cpp
`commitManagedTrx` and `abortManagedTrx` now return a future. Instead of blocking and spinning in a busy loop, they yield the current thread and wait. However, this waiting is only done, if the transaction is in use by a different request, while also being committed/aborted.
=> Async trx commit/abort

arangod/RestHandler/RestDocumentHandler.cpp, arangod/RestHandler/RestDocumentHandler.h
the `RestDocumentHandler` had an instance variable `_activeTrx` in which the handler stored the transaction object that was started for the particular operation.
this was previously necessary, because the transaction still needs to be valid in some of the RestDocumentHandler's follow-up async continuations. because we did not pass the unique_ptr with the transaction to these async routines, they needed the instance variable to pick up the transaction later on.
after we changed the `RestDocumentHandler` to use coroutines, we can now remove the `_activeTrx` instance variable entirely, and simply store the transaction in a local variable. once the coroutine execution resumes, it still has access to that same local variable.
the changes should not affect the observable behavior at all.
=> remove `_activeTrx` instance variable

CHANGELOG, arangod/GeneralServer/Acceptor.h, arangod/GeneralServer/AcceptorTcp.cpp, arangod/GeneralServer/AcceptorTcp.h, arangod/GeneralServer/AcceptorUnixDomain.cpp, arangod/GeneralServer/AcceptorUnixDomain.h, arangod/GeneralServer/AsioSocket.h, arangod/GeneralServer/GeneralCommTask.cpp, arangod/GeneralServer/GeneralCommTask.h, arangod/GeneralServer/H2CommTask.cpp, arangod/GeneralServer/H2CommTask.h, arangod/GeneralServer/HttpCommTask.cpp, arangod/GeneralServer/HttpCommTask.h, arangod/GeneralServer/VstCommTask.cpp, arangod/GeneralServer/VstCommTask.h
3.11.7 backport of https://github.com/arangodb/arangodb/pull/20753
All AsioSocket instances are now created via `std::make_shared()`. This allows us to pass a shared_ptr to an AsioSocket into a lambda, so the lambda can still safely refer to the AsioSocket without any lifetime issues.
With the fix it is possible that the AsioSocket posts a lambda with a this pointer (to the AsioSocket), and the lambda being executed after the AsioSocket is destroyed.
=> BTS-1489: Race condition in AsioSocket shutdown when using SSL. (#20753)

js/client/modules/@arangodb/testsuites/fuerte.js, js/client/modules/@arangodb/testutils/instance.js
Try to reduce log output for CircleCI runs. We suspect that runs with a too large log output now automatically fail in CircleCI. This is a test PR to validate this hypothesis.
=> work around log output limits in circleci?

arangod/Cluster/ClusterInfo.cpp, arangod/RestHandler/RestReplicationHandler.cpp
Stop waiting when the collection/shard is dropped and return the _datasource not found_ error.
=> GetLeaderForShard Fix

arangod/GeneralServer/RestHandler.cpp, arangod/Replication2/Methods.cpp, arangod/Replication2/ReplicatedLog/Components/AppendEntriesManager.cpp, arangod/Replication2/ReplicatedLog/Components/CompactionManager.cpp, arangod/Replication2/ReplicatedLog/Components/FollowerCommitManager.cpp, arangod/Replication2/ReplicatedLog/Components/InMemoryLogManager.cpp, arangod/Replication2/ReplicatedLog/LogLeader.cpp, arangod/Replication2/ReplicatedState/FollowerStateManager.tpp, arangod/Replication2/ReplicatedState/ReplicatedState.tpp, arangod/Replication2/ReplicatedState/StreamProxy.tpp, arangod/VocBase/VocBaseLogManager.cpp, lib/Basics/Exceptions.cpp, lib/Basics/Exceptions.h, lib/Basics/FutureSharedLock.h, lib/Basics/SourceLocation.cpp, lib/Basics/SourceLocation.h, tests/Basics/CMakeLists.txt, tests/Basics/SourceLocationTest.cpp, tests/Replication2/Mocks/FakeFollower.cpp
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/1470
1) Make use of std::source_location in SourceLocation, instead of __FILE__ and __LINE__, to make it more usable
2) Strip the prefix of the content root from the file name.
A little explanation for 2): SourceLocation is generally used to show where an exception originated from. There's usually no use to have the absolute path of that file on the machine that built the binary. So SourceLocation now makes the path relative to the content root; e.g., instead of `/root/project/arangodb/lib/Basics/SourceLocation.h`, the file_name will contain `lib/Basics/SourceLocation.h`.
=> Use std::source_location, and make paths relative to the content root

arangod/RestServer/QueryRegistryFeature.cpp
This PR adds the option `--query.enable-debug-apis` as an obsolete option in devel.
The option was introduced in 3.11.9 via https://github.com/arangodb/arangodb/pull/20770 as actual feature flag for some debugging APIs. These APIs are always available in devel, and cannot be turned off.
So while setting this option has no effect in devel, the existence of the options allows users to upgrade from ArangoDB 3.11.9 with having the startup option explicitly set.
If devel would not recognize the startup option as a valid option, it would otherwise bail out with an error on startup, thus preventing a successful upgrade.
=> obsolete 3.11 feature flag

arangod/Aql/OptimizerRulesFeature.cpp
make the optimizer rule `async-prefetch` fully unavailable in 3.11, so that enabling it by accident does not cause any queries to execute the rule.
the motivation for this change is that although the `async-prefetch` optimizer rule already existed in 3.11, it was disabled by default and can lead to errors in query execution when enabled. thus it is better to fully disable the optimizer rule in 3.11 and only bring it back with version 3.12.0, where the rule's code has been rewritten and fixed.
no forward port to 3.12 is needed, as the optimizer rule has a different implementation there, and should be enabled by default.
=> make optimizer rule `async-prefetch` unavailable in 3.11.

js/apps/system/_admin/aardvark/APP/frontend/js/routers/versionCheck.js
Remove an obsolete check for new server versions from the web interface.
The called API does not return the list of new server versions anymore, so making the AJAX call to it is pointless.
Apart from that, the call is likely blocked anyway by browsers because it is a cross-domain request.
=> remove obsolete check for new versions from web interface

CONTRIBUTING.md
The related docs PR removes the outdated compile instructions from 3.12+: https://github.com/arangodb/docs-hugo/pull/513
=> Docs: Updated compile instructions for 3.12+

arangod/GeneralServer/RestHandler.cpp, arangod/GeneralServer/RestHandler.h, arangod/RestHandler/RestSupervisionStateHandler.cpp, arangod/RestHandler/RestSupervisionStateHandler.h
Add the `executeAsync` function to rest handlers. It can be implemented instead of the `execute` function. The future returned is automatically awaited and the rest handlers lifetime will exceed that of the execution of the future.
=> ExecuteAsync for RestHandlers

tests/RestServer/LanguageFeatureTest.cpp
Make ArangoLanguageFeature unit test independent from system locale (#20777)
* Initial commit
* test debug
* wip
* wip
* fix clang-format
* clear debug output
=> [3.11]: Make ArangoLanguageFeature unit test independent from system locale

tests/js/server/aql/aql-string-sort-order.js
Test string sort order w.r.t. to ICU 64 string comparisons.
This PR only adds a test and should not have any effect on the server outside the test.
=> test string sort order w.r.t. ICU 64

arangod/RocksDBEngine/RocksDBEngine.cpp, arangod/Scheduler/SupervisedScheduler.cpp, arangod/Transaction/ManagerFeature.cpp, lib/Logger/LogThread.cpp
Fix ASan errors in test.
Should fix the following test error with sanitizers enabled:
```
[FAILED]  tests/js/client/shell/shell-verify-sst-noncluster.js
"testVerify" failed: Error: at assertion #6: {
"pid" : 896,
"status" : "TERMINATED",
"exit" : 1
}: (1) is not equal to (0)
(Error
at verifySsts (tests/js/client/shell/shell-verify-sst-noncluster.js:106:9)
at tests/js/client/shell/shell-verify-sst-noncluster.js:116:11
at Object.testVerify (tests/js/client/shell/shell-verify-sst-noncluster.js:111:12)
....    at Object.shellClient [as shell_client] (/root/project/js/client/modules/@arangodb/testsuites/aql.js:209:79)
- test failed
```
=> fix ASan errors in test

CHANGELOG, Documentation/Metrics/arangodb_logger_messages_dropped_total.yaml, arangod/RestServer/LogBufferFeature.cpp, arangod/RestServer/LogBufferFeature.h, lib/Logger/LogThread.cpp, lib/Logger/LogThread.h, lib/Logger/Logger.cpp, lib/Logger/Logger.h, lib/Logger/LoggerFeature.h, tests/js/client/server_parameters/log-dropped-messages-noncluster.js
* Added metric `arangodb_logger_messages_dropped_total` to count the number of log messages that were discarded by the logger if its log queue was full.
=> Added metric `arangodb_logger_messages_dropped_total`

tests/IResearch/IResearchLinkTest.cpp
Try to improve an unstable iresearch test.
The following test failure was often seen:
[FAILED]  IResearchLinkTest
"test" failed: /root/project/tests/IResearch/IResearchLinkTest.cpp:1714
Expected equality of these values:
std::make_tuple(size_t(1), size_t(0), size_t(1))
Which is: (1, 0, 1)
feature.stats(ThreadGroup::_1)
Which is: (0, 1, 1)
The failure is due to a race between the iresearch thread pool picking up and starting a task and the test checking for the task to be started.
=> try to improve non-deterministic test

arangod/Aql/Executor/RemoteExecutor.cpp, arangod/Aql/Executor/RemoteExecutor.h
The old code circumvented the network features methods and effectively duplicated the code. Use the network feature methods instead.
=> Use the network feature in the remote executor.

arangod/RocksDBEngine/Methods/RocksDBTrxBaseMethods.cpp, tests/js/client/server_parameters/test-streaming-max-transaction-size.js
The `maxTransactionSize` option is there to limit the memory usage of a given transaction. Upon reaching this limitation, any subsequent operations are being rejected, but the transaction can be continued and even committed. However, the error message is misleading, as it states the the transaction is being *aborted*, which is not the case.
This PR modifies the error message and adds a clear test, showcasing the expected behavior.
=> Transactions reaching max size

arangod/VocBase/Properties/CreateCollectionBody.cpp
While working on the Python driver, I noticed that an error message looks rather strange: `Value cannot be empty. on attribute distributeShardsLike`. It's nothing bad really, but due to the way the string gets formatted in some cases we get a dot before the on _attribute..._, which looks as if the sentence is incomplete.
This PR simply adds some parenthesis around that, to make it look more like an additional explanation of the previous sentence: `Value cannot be empty. (on attribute "distributeShardsLike")`
=> Adding parenthesis around error message

.circleci/generate_config.py
Disable building with `-DUSE_V8=Off` in every CI run. This is an attempt to reduce (cumulated) build times/container usage times and thus CI costs.
=> disable non-v8 build in the CI

js/common/modules/@arangodb/test-generators/subquery-chaos-test.js, tests/js/client/aql/aql-subquery-chaos-nightly.js
Try to reduce memory usage in subquery chaos test.
The subquery chaos test previously always built up full results in memory in order to compare the results of two identical queries that were run with different options. The result sets of the produced queries could grow arbitrarily large.
Instead of loading the entire query result into memory at once, we are now querying the result set using a batch size of 10, so that we only need to buffer up to 10 result rows in memory. Instead of memoizing all of them, we keep a rolling hash of the rows we have seen, so that the test only produces a single md5 value instead of a large result array.
The failure we are trying to fix looks as follows in the CI:
https://app.circleci.com/pipelines/github/arangodb/arangodb/22966/workflows/bfa6ff18-5c99-48c3- …
=> try to reduce memory usage of subquery chaos test

CHANGELOG, arangod/Cluster/Maintenance.cpp
*There was a quadratic increase in runtime of collection creation within the same database. @maierlars found the blocking line, and we could trivially move it outside of one loop. This drastically improves creation/deletion time for collections and indexes on databases with hundreds of Collections.*
=> Improved the time required to create a new collection into a large database

client-tools/Shell/ClientFeature.cpp
Use @ENV_VAR@ value, escaping a literal at like @@
=> Docs: Clarify what at signs do in startup options

tests/js/client/aql/aql-arangosearch-constrained-sort-optimization.inc
Reduce the amount of data in a test that takes multiple minutes without this modification.
=> reduce amount of data in test

3rdParty/boost/1.78.0/boost/asio/ssl/detail/engine.hpp, 3rdParty/boost/1.78.0/boost/asio/ssl/detail/impl/engine.ipp, 3rdParty/boost/1.78.0/boost/asio/ssl/detail/stream_core.hpp
Fixes two move assignments in boost asio. One that causes an invalid pointer and heap-use-after-free, and one leaking resources.
=> [3.11] Fix move assignments in boost asio

arangod/GeneralServer/H2CommTask.cpp, arangod/GeneralServer/H2CommTask.h, tests/js/client/shell/api-job-different-protocols.js
Fix protocol confusion.
When an async job was created via the jobs API via HTTP/1.1, the job result was stored as an `HttpResponse`. 
When the job result was retrieved via HTTP/2, the server code expected the response to be an `H2Response` (a struct that is derived from `HttpResponse`). This could lead to the wrong response class to be used, and thus potential UB. 
The situation in which this happens is rare though, because it requires usage of the jobs API and a protocol change.
=> fix protocol confusion

arangod/Replication/InitialSyncer.cpp
Fix invalid vptr access in InitialSyncer dtor, reported by ASan/UBSan.
The same change has been made in devel a while ago via https://github.com/arangodb/arangodb/pull/20070.
=> fix invalid vptr access

arangod/VocBase/Methods/Upgrade.cpp, tests/js/client/restart/test-restart-replication2-syncer-thread-off.js
Try to fix restart test, attempt 2.
The previous implementation that executed upgrade tasks always swallowed the original error, and unconditionally turned it into a `TRI_ERROR_INTERNAL` error. Thus checking for a specific error code did not work.
=> try to fix restart test

arangod/RocksDBEngine/RocksDBEngine.cpp, arangod/Scheduler/SupervisedScheduler.cpp, arangod/Transaction/ManagerFeature.cpp, arangod/Transaction/ManagerFeature.h, lib/Logger/LogThread.cpp
Fix a potential issue during transaction manager shutdown.
Also contains backports of more ASan fixes from https://github.com/arangodb/arangodb/pull/20861.
=> fix potential issue during transaction manager shutdown

arangod/Aql/Query.cpp
Retry query shutdown in case no connection can be established.
Also double the request timeout for query shutdown.
=> retry query shutdown in case no connection can be established

CHANGELOG, js/apps/system/_admin/aardvark/APP/frontend/js/views/documentView.js
This restores a behaviour which existed pre-3.11 jsoneditor upgrade. Previously, jsoneditor would auto-repair the doucments on format; not we have to call the `repair()` function on our own. 
ref: https://github.com/josdejong/jsoneditor/issues/1107#issuecomment-693509237
=> FE-448: auto-repair collection JSON on save

CHANGELOG
Backport of https://github.com/arangodb/arangodb/pull/20924
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/1481
prevent parallel index creation thread from hanging indefinitely, in case the thread objects were created successfully but starting a thread returned an error.
in this case, the threads that were unable to start would never call the completion function on the shared env, so that the main index creation thread would wait forever for all threads to complete. now, if a thread cannot be started successfully, we immediately count down the number of threads to wait for in the shared env.
The actual fix is in https://github.com/arangodb/enterprise/pull/1481
=> prevent parallel index creation thread from hanging

arangod/Cluster/HeartbeatThread.cpp
allow larger database ids (larger than UINT32_MAX) in agency plan handling
=> allow larger database ids (larger than UINT32_MAX)

3rdParty/fuerte/src/loop.cpp, arangod/Cluster/ClusterFeature.cpp, arangod/GeneralServer/GeneralServerFeature.cpp, arangod/Network/ConnectionPool.cpp, arangod/Network/ConnectionPool.h, arangod/Network/NetworkFeature.cpp, arangod/Network/NetworkFeature.h
* remove artificial limit of 8 for the number of ClusterComm IO threads (`--network.io-threads`)
* remove artificial limit of 16 for the number of GeneralServer IO threads (`--server.io-threads`)
* unify default value generation for the above two config variables as `max(1, # cores / 4)`
=> remove artificial limit of 8 for the number of ClusterComm IO threads

arangod/RocksDBEngine/RocksDBMetaCollection.cpp
fix a race between collection deletion and revision tree persistence
if a collection is marked as deleted, by deleting its underlying database, then there is a small window of time in which revision tree persistence is running while the collection is being deleted. during deletion, the collection's syncByRevision attribute can be flipped from true to false. this can clash with the revision tree persistence functionality, which asserts that the collection's syncByRevision attribute is always true.
this could cause spurios failures such as
```
caught unexpected signal 6 (SIGABRT) in state "in wait": assertion failed in arangod/RocksDBEngine/RocksDBMetaCollection.cpp:753 [rocksdb::SequenceNumber arangodb::RocksDBMetaCollection::serializeRevisionTree(std::string &, rocksdb::SequenceNumber, …
```
=> fix a race between collection deletion and revision tree persistence

tests/Fuerte/ConnectionFailuresTest.cpp
Fix logical error in test assertion.
This fixes spurious
```
[FAILED]  fuerte
"test" failed: exit code of 'Mon May 13 2024 08:23:29 GMT+0000 (GMT) executeAndWait: cmd =build/bin/fuertetest args =["--gtest_output=json:/tmp/ArangoDB/0/arangosh_a9IRiY/fuertetest/testResults.json","--log.line-number","false","--endpoint=ssl://127.0.0.1:7044","--authentication=basic:root:"]' was 1
[FAILED]  ConnectionFailureTest
"test" failed: /root/project/tests/Fuerte/ConnectionFailuresTest.cpp:159
Expected: (n) <= (failureCallbacksCalled), actual: 100 vs 99
```
test errors.
=> fix logical error in test assertion

tests/js/client/chaos/test-chaos-load-common.inc
Fix a false positive report of Merkle tree differences.
This is a late 3.11 backport of https://github.com/arangodb/arangodb/pull/19502
=> fix a false positive report of Merkle tree differences

js/client/modules/@arangodb/testutils/instance.js, js/client/modules/@arangodb/testutils/process-utils.js, js/client/modules/@arangodb/testutils/san-file-handler.js
backport of  https://github.com/arangodb/arangodb/pull/20898
=> QA-536: move san file handling in its own class

arangod/Cluster/ClusterCollectionMethods.cpp
Currently, a Coordinator that's creating a Replication 2 collection does not wait for its own ClusterInfo to catch up, which can sometimes lead to "collection not found" errors on that same coordinator after a successful collection creation. This also leads to some spurious test failures.
This PR waits for CI to catch up.
=> Wait for ClusterInfo to catch up after creating a collection

arangod/Cluster/ClusterMethods.cpp
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/1482
Improve debug logging for hot backup locking.
This PR adds log messages for some cases, and also fixes the mentioning of "db servers" in log messages when in fact they are about coordinators.
=> improve debug logging for hot backup locking

tests/js/client/shell/shell-index.js
Add debug information for a spuriously failing test:
```
=== shell_client_3 ===
* Test "shell_client_3"
[FAILED]  tests\js\client\shell\shell-index.js
"testIndexProgressIsReported" failed: TypeError: Cannot read property 'name' of undefined
at Object.testIndexProgressIsReported (tests\js\client\shell\shell-index.js:92:25)
at tests\js\client\shell\shell-index.js:159:11
at tests\js\client\shell\shell-index.js:163:3
at Object.shellClient [as shell_client] (c:\gce-win-6jakv0\oskar\work\ArangoDB\js\client\modules\@arangodb\testsuites\aql.js:226:79)
- test failed
```
=> add debug information for spuriously failing test

tests/js/client/chaos/test-deadlock-cluster.js
Backport of https://github.com/arangodb/arangodb/pull/20933
Fix another false positive about Merkle tree differences in a chaos test.
=> fix test false positive about Merkle tree differences

arangod/Cluster/ClusterFeature.cpp, arangod/Network/ConnectionPool.cpp, arangod/Network/ConnectionPool.h, arangod/Network/NetworkFeature.cpp, arangod/Network/NetworkFeature.h, arangod/Network/Utils.cpp, arangod/RestServer/arangod.cpp, tests/AsyncAgencyComm/AsyncAgencyCommTest.cpp, tests/IResearch/IResearchAnalyzerFeatureTest.cpp, tests/Mocks/Servers.cpp, tests/Network/ConnectionPoolTest.cpp, tests/Network/MethodsTest.cpp
Remove the direct dependency of the ConnectionPool from the MetricsFeature.
=> ConnectionPool without MetricsFeature

arangod/Agency/Supervision.cpp, arangod/Agency/Supervision.h, arangod/GeneralServer/IoContext.cpp, lib/Basics/Thread.cpp, lib/Basics/Thread.h, lib/Logger/LogThread.cpp, lib/Logger/LogThread.h, lib/Logger/Logger.cpp, lib/Logger/Logger.h, lib/Logger/LoggerFeature.cpp, tests/main.cpp
Remove dependency on the Server of Logger and Thread; this makes it easier to instantiate them in tests.
This removes a check whether a thread may be started depending on the server's state (in `Thread::start`).
=> Remove server dependency of Logger and Thread

arangod/Cluster/ClusterInfo.cpp, arangod/Cluster/ClusterMethods.cpp, tests/js/client/shell/shell-hotbackup-cluster-nonwindows.js
*This PR fixes a bug which happens on Hotbackup restore, that only shows up on **clusters that started with 3.6 or older**. And was upgraded ever since. If such a deployment goes to 3.11.8, and wants to restore a backup this will fail.*
=> Bug fix 3.11/hotbackup restore analyzers

tests/js/client/chaos/test-deadlock-cluster.js
Fix another false positive about Merkle tree differences in a chaos test.
=> fix false positive about Merkle tree differences

arangod/Aql/ExecutionNode/DocumentProducingNode.cpp, arangod/Aql/ExecutionNode/GraphNode.cpp, arangod/Aql/ExecutionNode/GraphNode.h, arangod/Aql/ExecutionNode/MaterializeRocksDBNode.cpp, arangod/Aql/ExecutionNode/MaterializeRocksDBNode.h, arangod/Aql/ExecutionNode/TraversalNode.cpp, arangod/Aql/ExecutionNode/TraversalNode.h, arangod/Aql/ExecutionNode/WindowNode.cpp, arangod/Aql/ExecutionNode/WindowNode.h, arangod/Aql/OptimizerRuleBatchMaterializeDocuments.cpp, arangod/Aql/OptimizerRules.cpp, tests/js/client/aql/aql-projections.js
Honor `maxProjections` option in IndexNodes when the IndexNode data is later materialized using a MaterializeNode.
=> honor `maxProjections` options for MaterializeNode projections

arangod/RestHandler/RestIndexHandler.cpp
Backport of https://github.com/arangodb/arangodb/pull/20941
make latest indexes visible when calling GET /_api/index?withHidden=true.
we need to wait here for the latest index information being present in the agency cache. if we don't wait, we risk not seeing a just-created index if the local agency cache has not fully caught up, and the supervision declares the just-created index ready.
This fixes spurious test errors such as 
```
=== shell_client_3 ===
* Test "shell_client_3"
[FAILED]  tests/js/client/shell/shell-index.js
"testIndexProgressIsReported" failed: Error: at assertion #31: [ { "fields" : [ "_key" ], "id" : "c0l/0", "name" : "primary", "selectivityEstimate" : 1, "sparse" : false, "type" : "primary", "unique" : true } ]: (1) is not equal to (2)
(Error
at …
```
=> make latest indexes visible

tests/Fuerte/ConnectionTimeoutsTest.cpp
the fuerte timeout tests are unreliable and often fail with "Request timeout" messages on Windows. disable them on Windows only.
this fixes spurious test failures such as
```
=== fuerte_http ===
* Test "fuerte"
[FAILED]  fuerte
"test" failed: exit code of 'Thu May 16 2024 02:16:04 GMT+0200 (Central European Summer Time) executeAndWait: cmd =build\bin\RelWithDebInfo\fuertetest.exe args =["--gtest_output=json:c:\\gce-win-0v8vdp\\oskar\\work\\tmp\\ArangoDB\\46\\arangosh_a25384\\fuertetest\\testResults.json","--log.line-number","false","--endpoint=tcp://127.0.0.1:12124","--authentication=basic:root:"]' was 1
[FAILED]  RequestTimeout
"test" failed: C:\gce-win-0v8vdp\oskar\work\ArangoDB\tests\Fuerte\ConnectionTimeoutsTest.cpp:110
Expected equality of these values:
e
Which is: 2-byte object …
```
=> skip fuerte timeout tests on Windows

CHANGELOG, arangod/GeneralServer/GeneralServerFeature.cpp, arangod/Network/NetworkFeature.cpp
Backport of https://github.com/arangodb/arangodb/pull/20922
* remove artificial limit of 8 for the number of ClusterComm IO threads (`--network.io-threads`)
* remove artificial limit of 64 for the number of GeneralServer IO threads (`--server.io-threads`)
=> Remove artificial upper bounds for IO threads configuration

CHANGELOG, arangod/RestHandler/RestAdminClusterHandler.cpp
shardIds returns a shared_ptr copy which must stay alive long enough. However, if we dereference the shared_ptr as part of the range expression, then we only keep the reference to the ShardMap, but the temporary is immediately destroyed and does not guarantee that the map stays around.
=> Fix potential race in collectRebalanceInformation

arangod/Cluster/ClusterFeature.cpp, arangod/Network/ConnectionPool.cpp, arangod/Network/NetworkFeature.cpp
Try to fix more shutdown errors:
AsyncAgencyComm requests may still be in flight when the server is shutting down. Try to fix this.
=> try to fix more shutdown errors

arangod/Transaction/Manager.cpp
Pass correct database name when registering a CallbackGuard that is supposed to shut down the transaction should the coordinator die or reboot.
Not passing the database name will lead to an assertion failure should the callback fire.
=> pass database name in callback guard

arangod/RestHandler/RestAdminClusterHandler.cpp, arangod/Sharding/ShardingInfo.cpp
Add assertions to ShardingInfo.cpp to always ensure that no nullptr is used as the `_shardMap`.
Also add another assertion to verify that every shard has at least one DB server assigned before accessing the 0th DB server via its index.
=> add assertions to detect nullptr derefs in ShardingInfo

CHANGELOG, arangod/Cluster/ClusterInfo.cpp, arangod/Cluster/ClusterMethods.cpp, tests/js/client/shell/shell-hotbackup-cluster-nonwindows.js
*Forward Port of: https://github.com/arangodb/arangodb/pull/20940 and https://github.com/arangodb/arangodb/pull/20947
This fixes two issues:
1) This PR fixes a bug which happens on Hotbackup restore, that only shows up on clusters that started with 3.6 or older. And was upgraded ever since. If such a deployment goes to 3.11.8, and wants to restore a backup this will fail.
2) Listing Database Names after HotRestore or adding a new empty DBServer was for a very short period of time empty, until all DBServers have successfully reported back to the Agency. This situation is now resolved.*
=> BugFix: hotbackup restore analyzers

CHANGELOG, arangod/Aql/Executor/IndexExecutor.cpp, tests/js/client/aql/aql-index-batch-materialize.js
Fixes https://arangodb.atlassian.net/issues/OASIS-25823
* Fixed OASIS-25823: when late materialization was used together with skipping over documents or the `fullCount` operation, it was possible for AQL queries to fail with errors such as `bad_function_call`.
The issue occurred when an index was used together with late document materialization, and either `fullCount` was used or a `LIMIT x, y` with `x > 0`.
3.11 is not affected by this issue.
=> OASIS-25823

CHANGELOG, arangod/Cluster/ClusterInfo.cpp
* Detach get responsible server if waiting longer than one second. Back porterd from 3.11.8.2*
=> Bug fix 3.11.7.4/detach get responsible server

CHANGELOG, lib/Basics/process-utils.cpp
Use `posix_spawn` instead of fork + exec calls.
This solves a problem in hotbackup upload via rclone.
devel PR: https://github.com/arangodb/arangodb/pull/20961
This is the 3.11.7.5 backport.
=> Use posix_spawn instead of fork+exec

lib/Basics/process-utils.cpp
improve error message for failed `posix_spawn` calls, by including the name of the executable that we tried to spawn.
=> improve error message for failed `posix_spawn` calls

CHANGELOG, arangod/Aql/AqlFunctionFeature.cpp, arangod/Aql/Function/ObjectFunctions.cpp, arangod/Aql/Functions.h, tests/js/client/aql/aql-functions.js
`ENTRIES` takes a single object argument and returns a list of key-value pairs, similar to JS `Object.entries()`.
This PR is part of a bigger effort to make iteration over objects in aql more memory efficient and performant.
Currently the only way of iteration over objects is
```
LET keys = ATTRIBUTES(object)
FOR key IN keys
LET value = object[key]
```
This requires `object` to be copied past the `FOR` loop. Secondly, we have to build the `ATTRIBUTES` array and then do a binary search in the object to look up the value.
This PR alone does not improve the situation by much, however, it allows to write
```
FOR pair in ENTRIES(object)
let key = pair[0]
let value = pair[1]
```
Which already eliminates the copy of `object` if it is not used after the `FOR` loop.
A follow up PR will introduce a …
=> ENTRIES for AQL

tests/js/client/chaos/test-chaos-load-common.inc
https://arangodb.atlassian.net/browse/BTS-1775
View counts are known to sometimes differ from collection counts when the DeleteRange version of truncate is used. This is noted in BTS-1775. Until there is a proper fix for the view counts when using DeleteRange, we should disable the count check in the chaos test, in order to avoid spurious failed tests for known reasons
=> BTS-1775: disable checking of view counts in chaos test

arangod/RestHandler/RestIndexHandler.cpp
The index API that returns in-progress indexes had the following issues:
- the previous version first fetched all ready indexes and then fetched all in-progress indexes. this leaves room for a small window of time in which an index can transition from being in progress to ready, which will make it evade both fetch calls: in the first fetch call the index will not yet be ready, and in the second fetch call it is not in progress anymore.
- there was a potential inconsistency in the return values between the indexes present in the "indexes" attribute, and the indexes present in the "identifiers" attribute. both should always contain the same indexes.
=> fix failing index test that queries in-progress indexes

3rdParty/fuerte/include/fuerte/FuerteLogger.h, 3rdParty/fuerte/src/AsioSockets.h, arangod/Agency/AsyncAgencyComm.h, arangod/Aql/Condition.cpp, arangod/Aql/Executor/RemoteExecutor.cpp, arangod/Aql/Executor/RemoteExecutor.h, arangod/Network/ClusterUtils.h, lib/Logger/LoggerFeature.cpp
Enable TCP_NODELAY on fuerte tcp connections.
The TCP_NODELAY option wasn't previously set for fuerte TCP connections that did not use SSL/TLS.
Now it is being set explicitly.
I could not measure a significant performance difference between setting and not setting the option on the socket, but this change at least unifies the socket options between the TCP (non-SSL/TLS) and the SSL/TLS socket implementations. The SSL/TLS socket implementation did already set the TCP_NODELAY flag on the socket before, but the TCP (non-SSL/TLS) implementation did not.
This PR also slightly cleans up the fuerte logging code and reduces dependencies on fuerte include files in some ArangoDB header files.
=> enable TCP_NODELAY on fuerte tcp connections

js/apps/system/_admin/aardvark/APP/react/public/assets/src/mode-aql.js
Pregel has been removed, some new functions have been added in 3.12
=> Aardvark: Update list of known AQL functions for code highlighting

arangod/Cluster/ClusterInfo.cpp
Include the shard name in log message. This allows for easier debugging.
=> include shard name in log message

arangod/Aql/Query.cpp
Skip scheduler for query shutdown.
During query shutdown, we definitely want to skip the scheduler, because normally the thread that orders the query shutdown is blocked and waits synchronously until the shutdown requests have been responded to. we thus must guarantee progress here, even in case all scheduler threads are otherwise blocked.
=> skip scheduler for query shutdown

arangod/Cluster/ClusterInfo.cpp, arangod/Transaction/CountCache.cpp, arangod/Transaction/CountCache.h, arangod/Transaction/Methods.cpp, tests/Transaction/CountCacheTest.cpp
Backport of https://github.com/arangodb/arangodb/pull/20990
Reduce the possibility of stampedes during collection count cache refilling.
This is not a perfect solution, but it should greatly reduce the opportunity for request stampedes to happen when updating the cached value for collection counts.
=> reduce the possibility of stampedes

CHANGELOG, arangod/Aql/ExecutionNode/EnumerateListNode.cpp, tests/js/client/aql/aql-optimizer-rule-move-filters-into-enumerate.js
Fixes https://arangodb.atlassian.net/browse/MDS-1230
* Fixed MDS-1230: added missing variable replacement for inline filters of EnumerateListNodes.
=> Fixed MDS-1230

arangod/Aql/AqlCallList.cpp, arangod/Aql/AqlCallList.h, arangod/Aql/AqlCallStack.cpp, arangod/Aql/AqlCallStack.h
The `AqlCallList` class previously contained an `std::vector<AqlCall>` member, which was allowed to have at most one entry. to save to heap memory allocation associated with pushing something into the vector, this PR replaces the vector with an `std::optional<AqlCall>`.
=> micro-optimize AqlCallList

arangod/Cluster/ClusterMethods.cpp, arangod/Cluster/ClusterTrxMethods.cpp, arangod/Cluster/ClusterTrxMethods.h, arangod/ClusterEngine/ClusterTransactionState.cpp
Make beginTransaction on a Coordinator asynchronous (i.e., don't block a thread when waiting for network responses).
=> Make beginTransaction async

arangod/Aql/QueryResult.h, arangod/Cluster/ClusterMethods.cpp, arangod/Cluster/CreateCollection.cpp, arangod/Cluster/CreateDatabase.cpp, arangod/Cluster/DropDatabase.cpp, arangod/Graph/GraphManager.cpp, arangod/Graph/GraphOperations.cpp, arangod/IResearch/IResearchAnalyzerFeature.cpp, arangod/Replication/Syncer.cpp, arangod/Replication/TailingSyncer.cpp, arangod/Replication2/Storage/WAL/FileIterator.cpp, arangod/Replication2/Storage/WAL/LogReader.cpp, arangod/RestHandler/RestVocbaseBaseHandler.cpp, arangod/RestServer/UpgradeFeature.cpp, arangod/RocksDBEngine/RocksDBEngine.cpp, arangod/RocksDBEngine/RocksDBMultiDimIndex.cpp, arangod/RocksDBEngine/RocksDBReplicationTailing.cpp, arangod/Transaction/Methods.cpp, arangod/Utils/OperationResult.h
This is a simple refactoring to use the slightly more expressive `Result.is()` / `Result.isNot()` in favor of `Result.errorNumber() == ...` / `Result.errorNumber() != ...`. 
This PR should not change the behavior of existing code.
=> use Result.is() / Result.isNot() where appropriate

CMakeLists.txt
By default, CMake variables default to "OFF". This case was not handled separately for the `ARANGODB_BUILD_DATE` cmake variable. We only compared the value of this variable to the empty string. This PR adjusts the cmake code to also take into account the special value of "OFF", so that the build date for an ArangoDB executable will not be set to "OFF" if the build date is not explicitly set via the `ARANGODB_BUILD_DATE` cmake variable.
=> honor special case "OFF" for ARANGODB_BUILD_DATE cmake var

arangod/Transaction/Methods.cpp
Move resolution of replication callback to high prio lane
// use a HIGH priority lane to execute the callback when the
// response arrives. we must not skip the scheduler entirely here
// because the callback may execute an intermediate commit in
// RocksDB or carry out agency communication in case a follower
// needs to be dropped. the HIGH priority is justified here
// because the callback must make progress: the callback can
// unblock other block threads on the leader that synchronously
// wait for this future to be resolved.
=> move resolution of replication callback to high prio lane

CHANGELOG, arangod/Aql/Executor/IndexExecutor.cpp, tests/js/client/aql/aql-index-batch-materialize.js
Fixes https://arangodb.atlassian.net/browse/MDS-1229
Fixes an issue when late document materialization is used in queries together with skipping over documents (`LIMIT x, y` with `x` > 0). Such queries could fail with internal errors and error messages such as "bad_function_call".
This bugfix follows https://arangodb.atlassian.net/browse/OASIS-25823 (https://github.com/arangodb/arangodb/pull/20960), which fixed a similar issue already, but apparently only for queries that used a post-filter on the IndexNode. The case of IndexNodes not using post-filters had been overlooked in the initial bugfix PR.
The bug affects 3.12.0, but not 3.11.x. The reason is that late materialization is used in a lot more cases in 3.12 than in 3.11, so now there are additional cases to consider.
=> Fixed MDS-1229 (bad_function_call with batch materialization)

CHANGELOG, arangod/Cluster/FollowerInfo.cpp, arangod/Cluster/FollowerInfo.h, arangod/RestHandler/RestReplicationHandler.cpp, tests/js/client/shell/shell-leader-resign-cluster-noinstr-nonwindows.js, tests/js/client/shell/shell-leader-resign-cluster-noinstr.js
Avoid dropping of followers in the following scenario:
- leader has in-sync follower(s) for a given shard
- resignLeadership is called for current leader
- resignLeadership is reverted, so that old leader is now again the leader
- write to the shard
Previously this led to dropping the followers when the write operation was executed, because the leader's session id changed when taking over shard leadership again. The new session id was propagated to all followers, but it wasn't picked up because the leader server id did not change.
=> avoid dropping of followers in some case

arangod/Cluster/FollowerInfo.cpp, arangod/Cluster/FollowerInfo.h, arangod/RestHandler/RestReplicationHandler.cpp
this PR adds a new method `setTheLeaderConditional` to FollowerInfo, so that the leader only gets changed if the current leader is still as expected. this avoids potential races if concurrent leader changes are going on.
=> avoid potential races during controlled leader change

js/client/modules/@arangodb/testutils/instance.js, js/client/modules/@arangodb/testutils/testing.js, tests/js/server/dump/dump-setup-common.inc, tests/js/server/dump/dump-test.inc, tests/test-definitions.txt
Backport of https://github.com/arangodb/arangodb/pull/20838 
Enterprise PR: https://github.com/arangodb/enterprise/pull/1494
=> QA-531: start implementing single-shard dump/restore

CHANGELOG, arangod/Aql/SimpleModifier.cpp
This addresses a blockage which can occur if many threads on a leader
perform AQL writes at the same time, all replicate their operations on
their followers and are all waiting for responses.
Since this is AQL execution, this usually happens on MEDIUM priority.
But due to a (for now unresolvable) bug in the scheduler, it is
sometimes possible that more threads than allowed engage in this
activity. If the number grows to more than the number of HIGH priority
operations which are allowed concurrently, we have a blockage, since 
no thread can make progress any more as no HIGH priority tasks are
executed any more (due to a shortage of free threads).
This is a special bandaid for 3.11. The problem is solved more
thoroughly in 3.12 by making this particular operation truly
asynchronous.
Here, …
=> Resolve blockage by detaching a thread in AQL write on leader waiting for replication

lib/SimpleHttpClient/ConnectionCache.cpp, lib/SimpleHttpClient/ConnectionCache.h
Fixes one part of https://arangodb.atlassian.net/browse/BTS-1868
fix a data race in ConnectionCache by turning `_preventRecycling` into an atomic variable
=> fix a data race in ConnectionCache

js/client/modules/@arangodb/testsuites/ldap.js
It seems these tests are ran just nightly, hence changes would not conflict...
=> add missing signature change to the ldap tests

arangod/Aql/EngineInfoContainerDBServerServerBased.cpp, arangod/Aql/EngineInfoContainerDBServerServerBased.h, arangod/Network/Utils.cpp, arangod/RocksDBEngine/RocksDBSavePoint.cpp, arangod/RocksDBEngine/RocksDBSavePoint.h, arangod/RocksDBEngine/RocksDBTransactionCollection.cpp, arangod/RocksDBEngine/RocksDBTransactionState.cpp
Refactorings pulled out of a larger PR to make PR sizes more managable:
* prefer the usage of `absl::StrCat()` over other methods
* reduce warning log messages for expected cases (lock timeout in case fast path round is used during AQL setup)
* add assertions to RocksDBSavepoint
* make RocksDBSavepoint non-copyable
=> code simplifications / refactorings

CHANGELOG, arangod/Transaction/Methods.cpp, arangod/Transaction/Methods.h
There are some lifetime issues in the transaction methods, which in some situations can lead to UB during certain document operations on DBServers.
=>   Fix some transaction::Methods lifetime issues

tests/Containers/MerkleTreeTest.cpp
Fix compilation of a C++ unit test in case the define `ARANGODB_ENABLE_FAILURE_TESTS` was not set.
=> fix compilation of tests without failure test mode

arangod/RocksDBEngine/Methods/RocksDBReadOnlyBaseMethods.cpp, arangod/RocksDBEngine/Methods/RocksDBTrxBaseMethods.cpp
Fix a data race reported by TSan in Methods::MultiGet().
The instance variable `_readOptions` is temporarily modified by the `MultiGet()` w/ snapshot method. This method can run in parallel with other threads that read the `_readOptions` member of the same object.
This PR fixes it by making a copy of the `_readOptions` member, and then modifying only the copy.
No backport is needed for 3.11 as MultiGet is not used in 3.11.
=> fix a TSan data race in Methods::MultiGet()

lib/Basics/Thread.cpp, lib/Basics/Thread.h
We often use a pattern like `while (thread.isRunning()) { /* wait */ }` during shutdown. `isRunning` returns false once the internal thread state has been set to `STOPPED`. However, previously this load used `memory_order_relaxed` and therefore did not synchronize with the operation that updated the state. Thus, we did not have a happens-before relation and strictly speaking any access to data that was previously accessed by the just stopped thread could potentially result in a data race.
=> Use correct memory order to properly synchronize with stopping thread

js/client/modules/@arangodb/testutils/result-processing.js, js/client/modules/@arangodb/testutils/unittest.js
Previously some details like sanitizer reports were only printed when `writeXmlReport` was set to true, which was confusing, especially when running sanitizer tests locally.
=> Make sure we always report crash output

arangod/Cluster/FollowerInfo.cpp, arangod/Cluster/FollowerInfo.h
Backport of https://github.com/arangodb/arangodb/pull/21047
fix data race in FollowerInfo
`FollowerInfo::newShardEntry()` could read instance variables without acquiring the RW lock when called from `FollowerInfo::add()`. this could lead to a situation in which a thread in `newShardEntry` reads the instance variables without synchronization, while another thread modifies the instance variables (and correctly using the RW lock in write mode when doing so).
Fixes https://circleci.com/api/v1.1/project/github/arangodb/arangodb/1993201/output/103/1?file=true&allocation-id=6669824eda09200e7e356462-1-build%2FABCDEFGH
=> fix data race in FollowerInfo

arangod/Replication/DatabaseInitialSyncer.cpp, arangod/Replication/Syncer.cpp, arangod/Replication/Syncer.h, arangod/Replication/TailingSyncer.cpp
Backport of https://github.com/arangodb/arangodb/pull/21044
the variable `requestPayload` was only present inside a certain block of code, and would be destroyed when leaving the code block. however, tasks could have been scheduled that still referred to this variable by reference, so the tasks referring to the variable could outlive the lifetime of the variable itself.
this is now fixed by moving the `requestPayload` variable outside of the scope, so it is guaranteed to stay valid until the very end of the scope.
=> fix potential use-after-free in replication

.circleci/base_config.yml, scripts/test/arangosh.py, scripts/test/launch_handler.py, scripts/test/site_config.py, scripts/test/test_launch_controller.py
This allows specifying the build directory to be used. By default we just use the local "build" folder. The specified build folder is also forwarded to testing.js.
This PR also removes the unused `--definitions` parameter.
=> Add --build parameter to test launcher

arangod/Replication/DatabaseInitialSyncer.cpp
Backport of https://github.com/arangodb/arangodb/pull/21055
Fix another usage of JobSynchronizer, reported by TSan: https://circleci.com/api/v1.1/project/github/arangodb/arangodb/2004682/output/103/0?file=true&allocation-id=666b95c3cdc99f103f5e318a-0-build%2FABCDEFGH
=> fix another usage of JobSynchronizer

arangod/Cluster/ClusterFeature.cpp, lib/ApplicationFeatures/ApplicationServer.cpp
Previously when a feature returned an error during the startup phase we would shut down all started features, but also only unprepare those started features. Features that were prepared but not yet started would not be unprepared.
In the ClusterFeature we would create and start the AgencyCache thread during prepare. In a test scenario we cancel the start before we call ClusterFeature::start, so previously this feature would neither be stopped or unprepared. Thus the AgencyCache thread would keep running and potentially access data and features that are getting cleaned up during the shutdown.
=> Fix shutdown of partially started server

js/common/modules/@arangodb/aql/explainer.js
fix AQL query explainer for MaterializeNode
MaterializeNodes got additional properties in 3.12 and higher, but they are not present in 3.11 yet. When restoring data from a 3.11 debug dump, these properties were not present, so the explainer would with an exception when trying to explain 3.11 queries.
=> fix AQL query explainer for MaterializeNode

js/common/modules/@arangodb/aql/explainer.js
Fix errors when restoring debug dumps
the collection creation API changed in 3.12 and now complains about invalid attributes that are specified upon collection creation.
for example, when restoring 3.11 debug dumps into 3.12, there can be error messages logged as follows:
ERROR [ee638] {deprecation} The createCollection request contains an illegal combination and will be rejected in the future: {"errorNum":10,"errorMessage":"Found unexpected attribute 'objectId'"}
this PR removes a few invalid attributes from the debug dump, so that they will not be used when creating the collection from the dump.
=> fix errors when restoring debug dumps

arangod/Aql/ExecutionNode/ExecutionNode.cpp, arangod/Aql/ExecutionNode/ShortestPathNode.cpp, arangod/Aql/ExecutionNode/ShortestPathNode.h, arangod/Aql/ExecutionNode/SubqueryEndExecutionNode.cpp, arangod/Aql/ExecutionNode/SubqueryStartExecutionNode.cpp, arangod/Aql/ExecutionNode/TraversalNode.cpp, arangod/Aql/Executor/SubqueryStartExecutor.cpp
Clean up a few code parts:
- remove a few unused variables
- prefer container.contains() over container.find() != container.end()
- remove leading underscore for private method names
- use std::move() in several more cases
All changes done by this PR should be internal and not change the behavior of any existing functionality.
=> clean up a few code parts

lib/Basics/process-utils.cpp
make sure environment variable names are unique
when starting an external process, we pass a list of environment variables to the system call that starts the process. the names of environment variables are not guaranteed to be unique, so when an environment variable is specified multiple times, it is not guaranteed that the last occurrence wins. this is problematic in case we pass additional environment variables to the process, which should always win over whatever settings were originally in the environment.
note that this assumes that there should not be multiple mentions of the same environment variable, e.g. `USER=foo USER=bar`. this is technically valid, and up to now, the 2 values would be passed to the new process. with this change, we will only pass a single value to the new …
=> BTS-1893: make sure environment variable names are unique

CHANGELOG, js/apps/system/_admin/aardvark/APP/frontend/js/views/documentView.js
Fixes a regression caused in https://github.com/arangodb/arangodb/pull/20894, where the JSON editor was not saving in "tree" mode
=> FE-454: Fix saving document in "Tree" mode 

arangod/Aql/QueryRegistry.cpp, arangod/Aql/RestAqlHandler.cpp, arangod/RocksDBEngine/Methods/RocksDBTrxBaseMethods.cpp
This race could implicitly occur when we try to start the query on the fast path in EngineInfoContainerDBServerServerBased, in case of a timeout send the cancel request and then start the new query on the slow path. It could happen that the setup request on the fast path had already inserted the query, but is still holding the shared_ptr. So the cancel request would actually find the query and remove it from the registry, but it would not yet be destroyed. Only once the shared_ptr is dropped would the query be destroyed and the memory tracker updated. But this would now race with the subsequent query on the slow path. For read-only operations we don't actually track anything in the RocksDBMethods, so we now disable tracker updates for all read-only queries, so that actual concurrent usage …
=> Fix a potential data race when running multiple read-only queries on the same streaming transaction.

CHANGELOG, arangod/Aql/ExecutionNode/TraversalNode.cpp, tests/js/client/aql/aql-optimizer-rule-optimize-projections.js
Fixes https://arangodb.atlassian.net/browse/OASIS-25850
OASIS-25850: Fix incomplete replacing of projection variables in traversals
This fixes a regression introduced in 3.12.0.
=> OASIS-25850: Fix incomplete replacing of projection variables in traversals

arangod/Aql/Query.cpp, arangod/Aql/Query.h, arangod/GeneralServer/AsyncJobManager.cpp, arangod/RestHandler/RestCursorHandler.cpp, arangod/RestHandler/RestCursorHandler.h
canceling an async job that executes an AQL query via the RestJobHandler's `cancel` operation could lead to a race between the RestJobHandler calling `cancel` on the RestCursorHandler which owns the query, and the RestCursorHandler object that currently executed the query.
the cancel operation could lead to the query being shut down while it was operating, which was not race-free. instead of trying to attempt a full shutdown during a cancel operation, we are now only setting the kill flag on the coordinator in a soft way, which avoids all potential races, but may lead to a later shutdown of the query. this is potentially a good tradeoff, as the RestJobHandler's cancel operation should be used only very rarely in practice.
=> fix a potential race when killing queries

CHANGELOG, arangod/Cluster/ClusterCollectionMethods.cpp, arangod/Cluster/ClusterInfo.cpp, tests/js/client/shell/shell-cluster-collection.js
Collection creation (with Replication 1) on a Coordinator waited for the ClusterInfo to catch up with a recent enough Plan to see the collection, but did not wait for Current. This can lead to races where accessing a collection right after creation might lead to errors (e.g. getResponsibleServer cannot find servers for a shard of the collection).
Similar fix for Replication 2.0 collection creation: https://github.com/arangodb/arangodb/pull/20929
=> Wait for ClusterInfo to catch up after collection creation

arangod/Aql/Executor/EnumerateCollectionExecutor.cpp, arangod/Aql/StandaloneCalculation.cpp, arangod/IResearch/IResearchAnalyzerFeature.cpp, arangod/Transaction/Methods.cpp, arangod/Transaction/Methods.h, arangod/V8Server/v8-query.cpp, arangod/VocBase/Methods/Collections.cpp, lib/Futures/include/Futures/coro-helper.h, tests/IResearch/IResearchAnalyzerFeatureTest.cpp, tests/IResearch/IResearchInvertedIndexIteratorTest.cpp
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/1495
* Rewrite Future-based code in transaction::Methods as coroutines.
* Fix a few places where begin()'s return value (of a trx) was ignored
* Made countLocal async (affecting count on single- or DBServers), and a few other places
* Unify namespace qualification (sorry for the diff)
When reviewing, please note that the SmartGraph related control flow in the enterprise repo is complex, and the related changes need particular attention.
=> Rewrite Future-based code in transaction::Methods as coroutines

tsan_arangodb_suppressions.txt
The reference counting of exception_ptr is part of the prebuilt glibc and is therefore not instrumented by TSan, so TSan is not aware of the synchronization that happens there. That means we have to ignore all races in destructors of exceptions as a result of a `__exception_ptr` release that causes the refcnt to drop to zero.
=> Add TSan suppression for exception_ptr

tests/js/server/replication2/replication2-replicated-state-document-store.js
For some reason this test has failed several times in the past in the CI. This is an attempt to improve the output in case of a failure so we get more information.
=> Improve output in case of test failure

arangod/Cluster/HeartbeatThread.cpp
TSan reported a leaked thread and indeed, the maintenance thread is not joined (although we wait for it to terminate).
=> Join maintenance thread on shutdown

CHANGELOG, arangod/RestHandler/RestJobHandler.cpp, lib/Rest/GeneralResponse.h, lib/Rest/HttpResponse.cpp, lib/Rest/HttpResponse.h, tests/IResearch/RestHandlerMock.h, tests/js/client/shell/multi/shell-async-request.js
**Intruduction**
Sending an async request (using the `X-Arango-Async` header) may involve storing the result on the server, which can later be retrieved via a PUT request. The PUT request is supposed to return the `Content-Length` along with the body of the original async request.
**Problem**
A [HEAD request](https://docs.arangodb.com/3.11/develop/http-api/documents/#get-a-document-header) is used to lookup a document, while retrieving only the document headers, without any content. However, the `Content-Length` header is returned, which offers a good indication of the document's size. This is allowed for a HEAD request. But, when such a request is made in _async_ mode, the client no longer retrieves the response through the initial HEAD request, but through a PUT instead. This causes a …
=> Request hangs when async HEAD request is retrieved

arangod/Aql/EdgeConditionBuilder.cpp, arangod/Aql/EdgeConditionBuilder.h, arangod/Aql/ExecutionNode/EnumeratePathsNode.cpp, arangod/Aql/ExecutionNode/EnumeratePathsNode.h, arangod/Aql/ExecutionNode/ShortestPathNode.cpp, arangod/Aql/ExecutionNode/ShortestPathNode.h, arangod/Aql/ExecutionNode/TraversalNode.cpp, arangod/Aql/Expression.cpp, arangod/Aql/Optimizer/Rules/EnumeratePathsFilter/EnumeratePathsFilterMatcher.cpp, js/common/modules/@arangodb/aql/explainer.js, tests/js/client/aql/aql-graph-enumerate-path-filter.js, tests/js/client/aql/aql-optimizer-rule-optimize-projections.js
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/1496
Replace additional variables in various members of `TraversalNode`, `EnumeratePathsNode` and `ShortestPathNode` for the projection optimization.
Also fix variable replacement in filter conditions inside `EnumeratePathsNode` for filters of type `FILTER p.edges[*].value ALL op value`. Previously this only supported filters of type `FILTER p.edges[* RETURN ...] op value` and ran into exceptions "unsupported node type no-op" with the other form.
=> replace more variables for projections

CHANGELOG, arangod/Aql/Aggregator.cpp, tests/js/client/aql/aql-optimizer-collect-aggregate.js
Fix `COLLECT ... AGGREGATE x = UNIQUE(y)` in a cluster sometimes missing results. The coordinator implementation was buggy. Both hashed and sorted variants had the same bug. COUNT_UNIQUE had the same, which was obscured by another bug (which only affected performance negatively).
=> [BTS-1909] Fix cluster unique aggregation

CHANGELOG, arangod/Aql/ModificationExecutorHelpers.cpp, arangod/Aql/ModificationExecutorHelpers.h, arangod/Aql/SimpleModifier.cpp, arangod/Aql/UpsertModifier.cpp
Follow-up on https://github.com/arangodb/arangodb/pull/21020: Detach UPSERT threads waiting on replication like other modification operations.
https://github.com/arangodb/arangodb/pull/21020
forward-port: https://github.com/arangodb/arangodb/pull/21095
=> [3.11] Detach AQL threads in UPSERT when waiting on replication for too long

arangod/ClusterEngine/ClusterIndex.cpp, arangod/ClusterEngine/ClusterIndex.h
Fix data-race reported by TSan via https://circleci.com/api/v1.1/project/github/arangodb/arangodb/2046644/output/103/0?file=true&allocation-id=667a128865532b545d433b6f-0-build%2FABCDEFGH
=> fix data race in cluster selectivity estimates

arangod/RocksDBEngine/RocksDBMetaCollection.cpp, arangod/RocksDBEngine/RocksDBMetaCollection.h
Otherwise the mutex could be locked in one thread but unlocked in a different one, which is not supported by std::mutex
=> We cannot use a std::mutex in a function that is a coroutine

arangod/RocksDBEngine/RocksDBMetaCollection.cpp
Fix an assertion failure in applyUpdatesForTransaction if a collection is set to deleted shortly before the call executes.
=> fix a potential assertion failure in RocksDBMetaCollection

CHANGELOG, arangod/Aql/Executor/ModificationExecutor.h, arangod/Aql/SimpleModifier.cpp, arangod/Aql/SimpleModifier.h, arangod/Aql/UpsertModifier.cpp, arangod/Aql/UpsertModifier.h, tests/js/client/shell/multi/shell-aql-kill.js, tests/js/server/replication2/replication2-replicated-state-document-store.js
Make AQL UPSERT operations asynchronous.
Related PR: https://github.com/arangodb/arangodb/pull/21068
=> Make AQL UPSERT asynchronous

3rdParty/README_maintainers.md, CHANGELOG, js/server/assets/swagger/swagger-initializer.js
They are merely used to disambiguate polymorphic endpoints in the OpenAPI descriptions.
Example: `/_api/index#persistent` is the path we use for persistent indexes. We also have other index types with different sets of attributes and we want to document them separately. It is not possible to use the same path multiple times because it is used as an attribute key in the OpenAPI JSON. We use fragment identifiers (aka anchors) as a workaround but this can break the "Try out" feature of Swagger UI.
Consider this request URL: `http://localhost:8529/_api/index#persistent?collection=coll`
Anything after `#` does not make it over the wire, or is at least ignored, cutting off the required query parameter.
This patch intercepts the "Try out" requests and removes any fragment identifier while …
=> Swagger UI: Remove fragment identifiers from request URLs

arangod/Aql/AqlValue.cpp, arangod/Aql/Expression.cpp, arangod/Aql/Expression.h
Privatize internal `_type` enum value in Expression, and use naming convention for naming its members.
=> Privatize internal Expression type

tests/IResearch/IResearchLinkTest.cpp
Fix a flaky IResearch test. 
There was previous fix attempt for this test, which made the test retry in case the thread numbers were not yet as expected. This is sensible because the thread numbers depend on thread scheduling, which is beyond control of this particular test.
The intention of the previous fix was to make the test spin until the thread numbers are as expected, and only then validate them. Unfortunately I forgot to remove the initial line that checks the thread numbers before spinning, which rendered the previous fix attempt useless.
=> fix a flaky test

arangod/Aql/IndexHint.cpp
`basics::VelocyPackHelper::getStringValue` returns a `std::string` which is assigned to a `std::string_view`, which then becomes dangling.
=> use-after-free in IndexHint

arangod/Aql/ExecutionBlockImpl.tpp, tests/js/client/aql/aql-subquery-chaos-nightly.js
Fix a bug discovered by the subquery chaos tests. It led to an assertion due to a violation of an internal API convention.
To get into detail, the following query
```
FOR fv0 IN col 
UPSERT { value: fv0.value } INSERT { value: fv0.value } UPDATE {updated: true} IN col
LIMIT 5,0
RETURN {fv0: UNSET_RECURSIVE(fv0,"_rev", "_id", "_key")}
```
, run on `col` (with `{numberOfShards: 1, replicationFactor: 2}`) containing `{value: 1}`...`{value: 10}`, ran into the assertion `inputRange.skippedInFlight() == 0` at `Aql/Executor/LimitExecutor.cpp:180`. Which means upstream (in this case the UpsertNode) reported more skipped rows, than the LimitNode ordered. This is a violation of AQL's internal API.
Namely, the LimitNode orders to skip 5 rows, and then stop. The UpsertNode still has to fetch and …
=> Save and restore call not just during SKIP

CHANGELOG, js/common/modules/@arangodb/request.js, lib/SimpleHttpClient/SslClientConnection.cpp, lib/SimpleHttpClient/SslClientConnection.h, lib/V8/v8-utils.cpp
optional HTTPS certificate verification in requests module
* Added `verifyCertificates` attribute option for the `requests` JavaScript module. This option defaults to false, so that no certificates will be verified in an HTTPS connection made with the `requests` module. If the option is set to true, the server certificate of the remote server will be verified using the default certificate store of the system. There is also a `verifyDepth` attribute to limit the maximum length of the certificate chain that counts as valid.
=> optional HTTPS certificate verification in requests module

arangod/Cluster/ClusterFeature.cpp, arangod/Network/NetworkFeature.cpp
Stop the connection pool in NetworkFeature stop to ensure that all requests are processed and the IO threads are stopped. Previously this was not guaranteed which would lead to data races and other kinds of undefined behavior because things could get destroyed even though some network callbacks would still try to access them.
=> Fix shutdown race

CHANGELOG, arangod/Aql/ExecutionNode/ShortestPathNode.cpp, arangod/Aql/grammar.cpp, arangod/Aql/grammar.y, tests/js/client/aql/aql-destructuring.js, tests/js/client/aql/aql-parse.js
Revive https://github.com/arangodb/arangodb/pull/4718.
* Added array and object destructuring to AQL LET statements.
* Array Destructuring: Array destructuring is the assignment of array values
into one or multiple variables with a single `LET` assignment. This can be
achieved by putting the target assignment variables of the `LET` assignment
into angular brackets.
For example, the statement:
LET [y, z] = [1, 2]
will assign the value `1` to variable `y` and the value `2` to variable `z`.
The mapping of input array members to the target variables is positional.
It is also possible to skip over unneeded array values. The following 
assignment will assign the value `2` to variable `y` and the value `3` to 
variable `z`. The array member with value `1` will not be assigned to any 
variable: …
=> array & object destructuring

CHANGELOG, arangod/Aql/Query.cpp, js/common/modules/@arangodb/aql/explainer.js, tests/js/client/aql/aql-failures-noncluster.js
Backport of https://github.com/arangodb/arangodb/pull/21129
Fix serialization of query plans when multiple query plans need to be serialized, using the `allPlans: true` value when explaining. In this case the explainer returned an error because the `plan` attribute was missing from the result, although the result contained a `plans` attribute.
Also fix an issue with memory accounting when plan serialization to velocypack goes wrong and throws an exception (which it should not do under normal conditions, but it will do if plan serialization runs into OOM or has a logical error).
=> fix serialization of multiple query plans and its memory accounting

arangod/Cluster/DBServerAgencySync.cpp, arangod/Replication2/StateMachines/Document/DocumentStateSnapshot.cpp, arangod/Replication2/StateMachines/Document/MaintenanceActionExecutor.cpp, arangod/Replication2/StateMachines/Document/MaintenanceActionExecutor.h, arangod/Replication2/StateMachines/Document/ReplicatedOperation.cpp, arangod/RestHandler/RestReplicationHandler.cpp, arangod/RocksDBEngine/RocksDBEngine.cpp, arangod/VocBase/LogicalCollection.cpp, arangod/VocBase/LogicalDataSource.h, arangod/VocBase/vocbase.cpp, tests/IResearch/IResearchQueryLateMaterializationTest.cpp, tests/IResearch/IResearchQueryNoMaterializationTest.cpp, tests/IResearch/IResearchQueryNumericTermTest.cpp, tests/IResearch/IResearchQueryOptimizationTest.cpp, tests/IResearch/IResearchQueryOptionsTest.cpp, tests/IResearch/IResearchQueryOrTest.cpp, tests/IResearch/IResearchQueryScorerTest.cpp, tests/IResearch/IResearchQuerySelectAllTest.cpp, tests/IResearch/IResearchQueryStartsWithTest.cpp, tests/IResearch/IResearchQueryStringTermTest.cpp, tests/IResearch/IResearchViewCoordinatorTest.cpp, tests/IResearch/IResearchViewCountApproximateTest.cpp, tests/IResearch/IResearchViewDBServerTest.cpp, tests/IResearch/IResearchViewTest.cpp, tests/Replication2/Mocks/DocumentStateMocks.h, tests/js/server/replication2/replication2-replicated-state-document-store.js
During Replication 2 snapshot transfer, collection properties were passed including its object id (etc.), which is a strictly local property. This caused to run the tests sometimes run into the assertion
```
assertion failed in arangod/RocksDBEngine/RocksDBEngine.cpp:2371 [void arangodb::RocksDBEngine::addCollectionMapping
(uint64_t, TRI_voc_tick_t, DataSourceId)]: it->second.second == cid
```
, meaning a duplicate object id was encountered.
=> Don't transfer oid etc of collections to other servers

arangod/GeneralServer/AcceptorTcp.cpp, arangod/GeneralServer/AcceptorUnixDomain.cpp
During shutdown we previously simply closed the acceptors, not considering that we may still have active IO threads operating on the same acceptor instances. To avoid data races and other issues, we now perform these operations via the io_context.
=> Make sure we run any acceptor operations via the io_context

arangod/Aql/Executor/MaterializeExecutor.cpp, arangod/Aql/Optimizer/Rule/OptimizerRuleBatchMaterializeDocuments.cpp, arangod/Aql/Optimizer/Rule/OptimizerRulePushDownLateMaterialization.cpp, tests/js/client/aql/aql-index-batch-materialize.js, tests/js/client/aql/aql-optimizer-rule-late-document-materialization.js
Fix issues with late materialization optimizer rules that depend on the optimize-projections rule to also run.
Also fix a case in which the late materialization actually produced no output values.
=> fix two issues with late materialization

arangod/GeneralServer/AcceptorTcp.cpp, arangod/GeneralServer/AcceptorUnixDomain.cpp
Backport of #21131
During shutdown we previously simply closed the acceptors, not considering that we may still have active IO threads operating on the same acceptor instances. To avoid data races and other issues, we now perform these operations via the io_context.
=> [3.11] Make sure we run any acceptor operations via the io_context

CHANGELOG, lib/ApplicationFeatures/ConfigFeature.cpp, lib/ApplicationFeatures/ConfigFeature.h
This is the next try to solve the problems described in
https://arangodb.atlassian.net/wiki/spaces/DEV/pages/2188673090/etc+nsswitch.conf+incompatibility+with+glibc+static+executables
This PR uses the function `__nss_configure_lookup` to opt out of the
usage of /etc/nsswitch.conf for host name lookup and for user lookup.
It hard codes the lookup to /etc/hosts and normal DNS lookup, as well
as to /etc/passwd and /etc/group. There is a command line switch to
disable this opt out.
Note that this is an unofficial functionality of glibc. We only use
it when building under Linux and with glibc. Future versions might
not support it although this seems unlikely since glibc uses it in their
own tests.
This should prevent crashes of our static executables on systems which
provide a different glibc …
=> Opt out of /etc/nsswitch.conf for host and user lookup

arangod/Aql/Executor/JoinExecutor.cpp, arangod/Aql/Executor/JoinExecutor.h, tests/js/client/aql/aql-primary-index-join.js
Fix a memory accounting error in JoinExecutor
=> fix a memory accounting error in JoinExecutor

CHANGELOG, lib/ApplicationFeatures/ConfigFeature.cpp, lib/ApplicationFeatures/ConfigFeature.h
This is the 3.11 backport.
This is the next try to solve the problems described in
https://arangodb.atlassian.net/wiki/spaces/DEV/pages/2188673090/etc+nsswitch.conf+incompatibility+with+glibc+static+executables
This PR uses the function `__nss_configure_lookup` to opt out of the
usage of /etc/nsswitch.conf for host name lookup and for user lookup.
It hard codes the lookup to /etc/hosts and normal DNS lookup, as well
as to /etc/passwd and /etc/group. There is a command line switch to
disable this opt out.
Note that this is an unofficial functionality of glibc. We only use
it when building under Linux and with glibc. Future versions might
not support it although this seems unlikely since glibc uses it in their
own tests.
This should prevent crashes of our static executables on systems which …
=> Opt out of nsswitch to prevent crashes

arangod/Aql/Optimizer/Rule/OptimizerRulesJoin.cpp, tests/js/client/aql/aql-index-join.js
This PR adds a missing check, if the index supports streaming with the required projections. This check was missing and caused an internal error later, when the streams were constructed.
In particular the PrimaryIndex does not support projecting the `_id` attribute in streaming mode. (We should fix that in the future)
=> Check projections when optimizing for joins.

CHANGELOG, arangod/RocksDBEngine/RocksDBMetadata.cpp, arangod/VocBase/KeyGenerator.cpp, arangod/VocBase/KeyGenerator.h
Backport of https://github.com/arangodb/arangodb/pull/21156
* Fixed MDS-1216: restoring the previous value of the "padded" key generator could lead to the key generator's sequence being set to a too low value after recovery.
=> Fixed MDS-1216

CHANGELOG, arangod/Aql/Function/ObjectFunctions.cpp, tests/js/client/aql/aql-functions.js
Fix "invalid document type" exception when applying the AQL ENTRIES function on a database document/edge.
=> fix AQL ENTRIES function

.circleci/base_config.yml, CMakePresets.json, tsan_blacklist.txt, utils/llvm-symbolizer-client.py, utils/llvm-symbolizer-server.py
Add tsan_blacklist and use it in tsan preset to blacklist functions with known races to avoid instrumentation and the overhead involved
Add simple client/server scripts to manage a shared llvm-symbolizer instance and set the client script as external symbolizer in the sanitizer options. This allows all processes to use a shared llvm-symbolizer instance and thereby save a lot of memory.
=> Attempt to stabilize sanitizer builds

CHANGELOG, lib/Basics/files.cpp, lib/Basics/operating-system.h, lib/Basics/tri-zip.cpp, lib/Logger/LogAppenderFile.cpp, lib/Logger/LogTopic.cpp, lib/Logger/Logger.h
Remove unused "mmap" log topic.
Also remove a few unused defines from `operating-system.h`. These defines were unused since 3.12.0.
=> remove unused "mmap" log topic

arangod/Aql/Ast.cpp, arangod/Aql/Ast.h, arangod/Aql/AstNode.cpp, arangod/Aql/ClusterQuery.cpp, arangod/Aql/ClusterQuery.h, arangod/Aql/DocumentExpressionContext.cpp, arangod/Aql/EngineInfoContainerDBServerServerBased.cpp, arangod/Aql/ExecutionEngine.cpp, arangod/Aql/ExecutionEngine.h, arangod/Aql/ExecutionNode/SingletonNode.cpp, arangod/Aql/ExecutionNode/SingletonNode.h, arangod/Aql/ExecutionPlan.cpp, arangod/Aql/Optimizer/Rule/OptimizerRulesReplaceFunctions.cpp, arangod/Aql/Parser.cpp, arangod/Aql/Query.cpp, arangod/Aql/Query.h, arangod/Aql/QueryList.cpp, arangod/Aql/QueryOptions.cpp, arangod/Aql/QueryOptions.h, arangod/Aql/RegisterPlan.cpp, arangod/Aql/RestAqlHandler.cpp, arangod/Aql/Variable.cpp, arangod/Aql/Variable.h, arangod/Aql/types.h, js/common/modules/@arangodb/aql/explainer.js, tests/js/client/aql/aql-bind-parameter-variables.js
This PR adds a special flag to the query options `optimizePlanForCaching`. If this flag is set to true, bind parameters will be replaced with variables before optimization. The resulting plan can be executed with a different set of bind parameters and yields the correct result. As a side effect, the bind parameters have to sent to the database servers at query setup time. For now, whether the flag is specified or not, the query should be executed correctly.
For now there is no user of this flag, but any query plan caching strategy will make use of this feature eventually.
=> BindParameters to Variables

arangod/Aql/ExecutionNode/ExecutionNode.cpp, arangod/Aql/ExecutionNode/ExecutionNode.h, arangod/Aql/ExecutionNode/GatherNode.cpp, arangod/Aql/ExecutionNode/MultipleRemoteModificationNode.cpp, arangod/Aql/ExecutionNode/SingleRemoteOperationNode.cpp, arangod/Aql/ExecutionNode/SortNode.cpp, arangod/Aql/ExecutionNode/SortNode.h, arangod/Aql/ExecutionPlan.cpp, arangod/Aql/Executor/JoinExecutor.cpp, arangod/Aql/Executor/SortingGatherExecutor.cpp, arangod/Aql/Executor/SortingGatherExecutor.h, arangod/Aql/Optimizer/Rule/OptimizerRulesReplaceFunctions.cpp, arangod/Aql/OptimizerRules.cpp, arangod/Aql/SortElement.cpp, arangod/Aql/SortElement.h, arangod/Aql/SortRegister.cpp, arangod/Aql/SortRegister.h, tests/Aql/Executor/GatherExecutorCommonTest.cpp, tests/Aql/Executor/SortExecutorTest.cpp
move creation of SortElements into factory functions
the goal of this PR is to make it easier to see and control who can set the initial data for SortElement objects, and who is able to modify them later on.
=> move creation of SortElements into factory functions

js/common/modules/@arangodb/test-generators/subquery-chaos-test.js
Add an increased TTL value for query cursors in nightly subquery chaos tests
=> Increase cursor TTL for subquery chaos test

arangod/Agency/Supervision.h, client-tools/Import/SenderThread.cpp
Fixing two tsan issues that are not critical.
1. During tests we change some values in the supervision. This is done using the API. The RestHandler updates those values in the supervision which might read at the same time, causing a data race. See introduction of atomics below.
2. In the import tool, `_hasError` was accessed without acquiring the mutex first.
=> Fixing tsan issues

CHANGELOG, arangod/Aql/CalculationExecutor.cpp, arangod/Aql/CalculationExecutor.h, arangod/Aql/EnumerateListExecutor.cpp, arangod/Aql/EnumerateListExecutor.h, arangod/Aql/ExecutionBlockImpl.tpp, arangod/Aql/ExecutionNode.cpp, arangod/RestServer/BootstrapFeature.cpp, arangod/RestServer/BootstrapFeature.h, tests/Aql/EnumerateListExecutorTest.cpp
Backport of https://github.com/arangodb/arangodb/pull/21196
Should address https://github.com/arangodb/arangodb/issues/13156#issuecomment-2244724718
Forcefully kill all running AQL queries on server shutdown.
This allows for a faster server shutdown even if there are some long-running AQL queries ongoing.
The query killing is done in the "stop" phase of the BootstrapFeature and thus only after the "beginShutdown" phase. Thus it should not interfere with the "soft shutdown" feature at all, and queries can still run to completion in case of a soft shutdown.
=> Forcefully kill all running AQL queries on server shutdown.

arangod/Aql/Ast.cpp, arangod/Aql/Collections.cpp, arangod/Aql/Collections.h, arangod/Aql/EngineInfoContainerDBServerServerBased.cpp, arangod/Aql/Query.cpp, arangod/Aql/ShardLocking.cpp, arangod/Aql/ShardLocking.h, arangod/Cluster/ClusterInfo.cpp, tests/js/client/aql/aql-bind.js, tests/js/client/shell/shell-debug-dump.js
do not include numeric collection ids in debug packages
previously, when a query execution plan was serialized to velocypack in cluster mode, the list of collections used also included the stringified collection ids of collections that were used by views in the query. these stringified collection ids do not need to be serialized at all, as they will only lead to problems down the line.
=> do not include numeric collection ids in debug packages

arangod/Aql/ExecutionPlan.cpp, arangod/Aql/QueryInfoLoggerFeature.cpp, arangod/IResearch/IResearchLinkMeta.cpp
Avoid a few unnecessary exceptions from being thrown:
1. when the query info logger was not enabled, it still tried to periodically run the garbage collection on the `_queries` system collection. This runs into a (handled) exception when the collection is not present. This exception can be avoided by not executing the garbage collection at all if query info logging is not enabled.
2. when unserializing a query plan from velocypack, the attribute "asyncPrefetchNodes" can unserialized into a numeric value speculatively. If the attribute is not set, then the `velocypack::Slice::isNumber(...)` throws an exception, which is handled. This exception can be avoided by not trying to serialize the value into a number if it is not set at all.
3. same for some the optional" view/link attribute
All …
=> avoid a few unnecessary exceptions

CHANGELOG, arangod/Aql/AqlValue.cpp, arangod/Aql/AqlValue.h, arangod/Aql/Ast.cpp, lib/Basics/VelocyPackHelper.cpp, lib/Basics/VelocyPackHelper.h, tests/Aql/AqlValueCompare.cpp, tests/Basics/VelocyPackHelperTest.cpp, tests/CMakeLists.txt
This fixes numerical sorting for AQLValues.
The changes are very similar (and use the same methods) as the one
we did for VelocyPackHelper.
- Make cross-type numerical sorting routines available.
- Implement proper numerical sorting in AQLValues.
- [*] PR for VelocyPackHelper changes: https://github.com/arangodb/arangodb/pull/21179
=> Fix numerical sorting for AQLValue fast track optimizations

arangod/RocksDBEngine/RocksDBEngine.cpp, arangod/StorageEngine/VPackSortMigration.cpp
This fixes two small problems with the vpack sorting migration, which
were spotted during tests:
1. The timeout for the cluster internal communication was too low for
large databases.
2. On database upgrade, an agent did not correctly detect that it is an
agent and did not do auto-migration.
- [*] Backport for 3.11: unnecessary, since backport PR already fixed
=> Fix migration for vpack sorting

arangod/Cluster/ClusterInfo.cpp, arangod/Graph/Graph.cpp, arangod/Graph/Graph.h, arangod/Graph/GraphManager.cpp, arangod/Graph/GraphOperations.cpp, arangod/VocBase/vocbase.cpp, lib/Basics/StaticStrings.cpp, lib/Basics/StaticStrings.h
Remove duplicate string definition for `_graphs` collection.
We previously had `StaticStrings::GraphsCollection` and `StaticString::GraphCollection`.
We now go only with the former definition for simplicity.
=> remove duplicate string definition for _graphs collection

CHANGELOG
Fix slightly wrong option names in CHANGELOG entry.
Documentation-only bugfix.
=> fix wrong option names in CHANGELOG

CHANGELOG, js/server/modules/@arangodb/aql.js, tests/js/common/shell/multi/shell-aqlfunctions.js
Backport of https://github.com/arangodb/arangodb/pull/21210
https://arangodb.atlassian.net/browse/MDS-1225
* Fixed MDS-1225: reloading of AQL user-defined functions inside AQL queries could cause trouble if the `_aqlfunctions` collection is located on different DB server than the leader shards of other collections used in the same query.
=> Fixed MDS-1225

CHANGELOG, arangod/RestHandler/RestAdminClusterHandler.cpp, arangod/RestHandler/RestAdminClusterHandler.h, arangod/RocksDBEngine/RocksDBComparator.cpp, arangod/RocksDBEngine/RocksDBComparator.h, arangod/RocksDBEngine/RocksDBEngine.cpp, arangod/RocksDBEngine/RocksDBEngine.h, arangod/RocksDBEngine/RocksDBOptionsProvider.cpp, arangod/RocksDBEngine/RocksDBOptionsProvider.h, arangod/RocksDBEngine/RocksDBVPackIndex.cpp, arangod/StorageEngine/CMakeLists.txt, arangod/StorageEngine/VPackSortMigration.cpp, arangod/StorageEngine/VPackSortMigration.h, js/common/bootstrap/errors.js, lib/Basics/VelocyPackHelper.cpp, lib/Basics/VelocyPackHelper.h, lib/Basics/errors.dat, tests/Basics/VelocyPackHelperTest.cpp, tests/RocksDBEngine/KeyTest.cpp, tests/js/client/server_parameters/legacy-sorting-cluster.js, tests/js/client/server_parameters/legacy-sorting-noncluster.js
This addresses vpack number comparison. Previous versions had a
comparison function, which was not transitive, which can lead to data
corruption in RocksDB keys in the VPackIndex as well as to wrong results
because numerical values were compared incorrectly.
This is a backport of https://github.com/arangodb/arangodb/pull/21179
See details there.
It should only be merged once 3.12.2 is out.
- [*] Tests
- [*] Backport for 3.11: this is it
- [*] Enterprise PR: https://github.com/arangodb/enterprise/pull/1505
=> Fix numerical sorting for VelocyPackHelper

tests/js/client/server_parameters/legacy-sorting-cluster.js
Make test more stable.
Unfortunately, it is possible that some follower still has the bad
indexes for some time. Need to repeat the test until good or abort
after 60s.
- [*] Backport for 3.11: done there already.
=> Make cluster vpack sorting migration test more stable

arangod/RocksDBEngine/RocksDBEngine.cpp
fix a potential hanger on shutdown when the shutdown waits for RocksDB compactions to finish, but compactions wait for flushes which will not happen because we are in shutdown.
this is forwarded-ported from a bugfix that @neunhoef made in 3.11 (https://github.com/arangodb/arangodb/pull/21205).
=> fix a potential shutdown hanger

.circleci/base_config.yml, .circleci/generate_config.py, tests/test-definitions.txt
This servers three purposes:
- it makes issues with the frontend build better visible (e.g. when fetching the npm packages failes)
- it slightly reduces costs, because the webpack build is largely serial and does not profit from a bigger machine, so we can use a smaller resource class
- the frontend build now runs parallel to the C++ build. Previously the frontend was built as yet another cmake target, but since cmake targets are built serially this added ~3min to the total runtime of the build.
=> Move frontend build to separate job

CHANGELOG
Follow-up to https://github.com/arangodb/arangodb/pull/20834
There is no truncation here unlike Jan originally wrote:
https://arangodb.slack.com/archives/C06HYC4KBFF/p1722371457380259?thread_ts=1722355304.163519&cid=C06HYC4KBFF
=> Fix changelog: No truncation of bindVars in query log

CHANGELOG, js/apps/system/_admin/aardvark/APP/foxxes.js, js/apps/system/_admin/aardvark/APP/frontend/js/models/foxx.js, tests/js/client/server_permissions/test-foxx-apis-off.js, tests/js/client/server_permissions/test-foxx-apis-on.js
Foxx service download fails sometimes with a 500, this fixes the issue by using a different endpoint for downloading
=> FE-459: fix failing foxx service download

arangod/Cluster/ClusterIndexMethods.cpp, arangod/Cluster/Maintenance.cpp, arangod/ClusterEngine/ClusterIndex.cpp, arangod/Indexes/Index.cpp, arangod/Indexes/Index.h
Small refactoring of  `Compare` and `CompareIdentifiers` methods from Index.h
=> Refactor `Compare` and `CompareIdentifiers` methods

client-tools/Shell/V8ClientConnection.cpp, tests/js/server/recovery/view-arangosearch-link-populate-crash-after-release.js, tests/js/server/recovery/view-arangosearch-link-populate-no-callbacks.js, tests/js/server/recovery/view-arangosearch-link-populate-no-release.js, tests/js/server/recovery/view-arangosearch-link-populate-no-sync.js, tests/js/server/recovery/view-search-alias-populate-crash-after-release.js, tests/js/server/recovery/view-search-alias-populate-no-callbacks.js, tests/js/server/recovery/view-search-alias-populate-no-release.js, tests/js/server/recovery/view-search-alias-populate-no-sync.js
Backport https://github.com/arangodb/arangodb/pull/21242
* map missing fuerte error codes
* fix tests that would lean on sluggish translated fuerte error codes
=> map missing fuerte error codes (#21242)

lib/Async/Registry/promise.h, lib/Async/Registry/registry.h, lib/Async/Registry/registry_variable.cpp, lib/Async/Registry/thread_registry.h
We missed some ref-counting in `for_promise` when copying the vector of thread registries. To circumvent any further mistakes, I replaced everything with `shared_ptr`.
=> Use shared_ptr for thread_registry ref counting.

CHANGELOG, arangod/RestHandler/RestAdminClusterHandler.cpp, arangod/RestHandler/RestAdminClusterHandler.h, arangod/RocksDBEngine/RocksDBEngine.h, arangod/StorageEngine/VPackSortMigration.cpp, arangod/StorageEngine/VPackSortMigration.h, tests/js/client/server_parameters/legacy-sorting-cluster.js, tests/js/client/server_parameters/legacy-sorting-noncluster.js
This adds an API to check the status of the migration for vpack sorting.
The API is available on dbservers and indicates the status of the
SORTING file on disk (migration status after next restart) as well as
the current status in the running process. The API is also available on
coordinators to fan out to dbservers and query all of them at once.
- Implement new API call.
- Add tests.
- CHANGELOG
- [*] Tests
=> API to check migration status for vpack sort migration

.circleci/base_config.yml
The arangodb target consists of arangod and the list of client-tools which already conditionally contains arangobackup and arangosh, depending on whether we build in enterprise mode, and whether we build with V8 or not.
This should also improve build times because this way the individual targets can be built in parallel (a list of individual targets is built serially).
=> Use custom arangodb target instead if list of targets

js/client/modules/@arangodb/testutils/instance.js
By default we only add a stdout appender if we have a TTY, but some tests depend on the existence of a stdout appender, so make sure we always configure one.
=> Make sure testing.js always configures an stdout appender

CHANGELOG, arangod/RestHandler/RestAdminClusterHandler.cpp, arangod/RestHandler/RestAdminClusterHandler.h, arangod/RocksDBEngine/RocksDBEngine.h, arangod/StorageEngine/VPackSortMigration.cpp, arangod/StorageEngine/VPackSortMigration.h, lib/Basics/Utf8Helper.cpp, tests/js/client/server_parameters/legacy-sorting-cluster.js, tests/js/client/server_parameters/legacy-sorting-noncluster.js
Backport of
https://github.com/arangodb/arangodb/pull/21249
and 
https://github.com/arangodb/arangodb/pull/21219
to 3.12.2.
=> Backport finishing touches for vpack sorting

CHANGELOG, arangod/Aql/OptimizerRules.cpp, tests/js/client/aql/aql-explain-cluster.js, tests/js/client/aql/aql-explain-noncluster.js, tests/js/client/aql/aql-optimizer-collect-methods.js
Extend COLLECT optimizer rule to to consider existing SORT nodes that cover all group variables. Previously the following query would use a hash collect instead of a sorted collect:
```
FOR d IN docs
SORT d.value DESC
COLLECT v = d.value
RETURN v
```
The reason is that previously the rule unconditionally created a SORT node with all group variables sorted in ascending order, but because that resulted in a plan with two different SORT nodes which obviously is more expensive than the hash collect, which was thus preferred.
The sorted collect doesn't need the values to be sorted in a particular order, it just needs the values to be grouped correctly. So the new version now checks if there are existing SORT nodes that already cover all the group values, and in that case does not create an …
=> Extend specializeCollecRule to consider existing SORT nodes that cover all group variables

js/client/modules/@arangodb/testutils/testing.js, tests/test-definitions.txt
tests in optionsJson need to be able to specify their result namespace.
=> add suffix option, so we can differenciate the testresults

.circleci/base_config.yml, .circleci/config.yml
Introduce a new pipeline parameter to enable/disable minimal debug info and default it to true. This results in much smaller executables (~650MB vs ~1.8GB) which improves CI turnaround times a bit (reduces build times somewhat, but mainly reduces the time required to persist/attach workspaces).
=> Make minimal debug info configurable for CircleCI

CHANGELOG, arangod/RocksDBEngine/RocksDBMultiDimIndex.cpp, tests/js/client/aql/aql-mdi-stored-values.js, tests/js/client/aql/aql-mdi.js
Previously searching with the MDI only non-strict ranges were supported directly. Given a strict comparison, a post filter was inserted. This can become a bottle neck if the result set is huge. This PR adds support for non-strict ranges without a post filter. 
```
Query String (54 chars, cacheable: true):
FOR d IN @@value0 FILTER 0 < d.x && d.x < 1 RETURN d.x
Id   NodeType        Par   Est.   Comment
1   SingletonNode            1   * ROOT 
7   IndexNode         ✓    715     - FOR d IN UnitTestMdiIndexCollection   /* mdi index scan, index scan + document lookup (projections: `x`) */    LET #3 = d.`x`   
6   ReturnNode             715       - RETURN #3
Indexes used:
By   Name       Type   Collection                   Unique   Sparse   Cache   Selectivity   Fields …
```
=> Natively support strict ranges using MDI.

utils/README.md
fix typos & syntax of internal utility documentation - forward port from https://github.com/arangodb/arangodb/pull/21278
=> as sugested by @jbajic in the backport PR, fix the syntax in the documentation

CHANGELOG, arangod/Cluster/ClusterFeature.cpp
This stabilizes some tests around the --cluster.force-one-shard option.
The reality is that the option has to be set the same on all dbservers 
and coordinators, since it is random which of the servers initializes
the agency and thus whose setting takes effect. This PR documents this
properly and the accompanying enterprise PR
https://github.com/arangodb/enterprise/pull/1511
fixes the tests.
- Adjust documentation of force-one-shard option.
- CHANGELOG.
- [*] Tests
- [*] Enterprise PR: https://github.com/arangodb/enterprise/pull/1511
=> Fix unstable tests around force-one-shard

.circleci/config.yml, CHANGELOG
This fixes a problem with the enterprise branch in the circleci setup,
which was accidentally introduced in 928c642590ec
Some template replacement strings were lost in translation. The effect
was that a user specified enterprise-branch setting was not always
picked up correctly. Actually, if an enterprise branch with the same
name as the community branch name existed, an explicit setting for
enterprise branch for circleci was ignored by this bug.
=> Fix circleci setup w.r.t. circleci branch

CHANGELOG
This fixes a file descriptor leak bug in the rocksdb library we use.
- Move subproject commit for 3rdParty rocksdb.
- CHANGELOG.
Original PR for devel: https://github.com/arangodb/arangodb/pull/21273
- [*] Backport for 3.12.2: This is it.
=> IO uring rocksdb file descript leak bug fix

CHANGELOG, arangod/Cluster/ClusterInfo.cpp, arangod/Cluster/ClusterInfo.h, arangod/Cluster/SynchronizeShard.cpp
This solves a deadlock found in RTA on upgrade with resignLeadership.
Explanation:
In SynchronizeShard we do some agency communication using
AsyncAgencyComm. We should use `skipScheduler` there such that we
are not blocked if all scheduler threads are busy or there are queues.
This resolves a deadlock where all maintenance threads were blocked
in SynchronizeShard and therefore no TakeoverShardLeadership jobs could
be executed.
- Only use skipScheduler in SynchronizeShard.
- CHANGELOG.
- [*] Jira ticket: https://arangodb.atlassian.net/browse/BTS-1965
=> Solve deadlock around SynchronizeShard

CHANGELOG, arangod/Cluster/ClusterInfo.cpp, arangod/Cluster/ClusterInfo.h, arangod/IResearch/IResearchMetricStats.h
This is solving a deadlock situation which arises with dynamic metrics.
The very high priority metrics REST handler was using
getResponsibleServer, which can block indefinitely when there is a
resigned leader. It was doing this under a lock, which can prevent
the deletion of dynamic metrics, which might become necessary during
DropCollection. Therefore, DropCollection jobs could block the whole
slow track maintenance which would prevent a server from taking over
shard leadership.
The fix is to use the new getResponsibleServerNoDelay function in the
RestMetricsHandler. This means that progress is always possible.
- Use getResponsibleServerNoDelay in metrics rest handler.
- CHANGELOG.
- [*] …
=> Solve deadlock around dynamic metrics [BTS-1965]

CHANGELOG, arangod/Cluster/ClusterInfo.cpp, arangod/Cluster/ClusterInfo.h, arangod/Cluster/SynchronizeShard.cpp, js/client/modules/@arangodb/testsuites/rta_makedata.js, js/client/modules/@arangodb/testutils/instance-manager.js, js/client/modules/@arangodb/testutils/instance.js
This solves a deadlock found in RTA on upgrade with resignLeadership.
This is a backport of https://github.com/arangodb/arangodb/pull/21302.
Explanation:
In SynchronizeShard we do some agency communication using
AsyncAgencyComm. We should use `skipScheduler` there such that we
are not blocked if all scheduler threads are busy or there are queues.
This resolves a deadlock where all maintenance threads were blocked
in SynchronizeShard and therefore no TakeoverShardLeadership jobs could
be executed.
- Only use skipScheduler in SynchronizeShard.
- CHANGELOG.
- [*] Devel original PR: …
=> Solve deadlock around SynchronizeShard [BTS-1965]

js/client/modules/@arangodb/testutils/instance.js, tests/test-definitions.txt
default for clusters is medium. we need this size here as well hence delete the desperate choice of small.
=> set size of cluster machine to medium

lib/Async/Registry/registry.h, lib/Async/Registry/thread_registry.h, tests/Async/AsyncTest.cpp, tests/Async/CMakeLists.txt, tests/Async/ExpectedTest.cpp, tests/Async/Registry/RegistryTest.cpp, tests/Async/Registry/ThreadRegistryTest.cpp, tests/CMakeLists.txt
Enables the execution of the async tests in arangodbtests. They were not executed before because of a missing cmake subdirectory command.
The test included some small errors which were not seen because they did not run, these are fixed now.
=> Bugfix: Enable async tests

arangod/Agency/Inception.cpp
This adds more logging for a failure case we have observerd.
- [*] GitHub issue / Jira ticket: https://arangodb.atlassian.net/browse/BTS-1971
=> More diagnostics for agency inception failure [BTS-1971]

tests/RestServer/LanguageFeatureTest.cpp
The locale was changed but not reset. This can lead to test failures on systems with non-default locale.
=> Reset Locale in Tests

arangod/AsyncRegistryServer/CMakeLists.txt, arangod/AsyncRegistryServer/Feature.cpp, arangod/AsyncRegistryServer/Feature.h, arangod/AsyncRegistryServer/RestHandler.cpp, arangod/AsyncRegistryServer/RestHandler.h, arangod/GeneralServer/GeneralServerFeature.cpp, lib/Async/Registry/Metrics.h, lib/Async/Registry/promise.h, lib/Async/Registry/registry.cpp, lib/Async/Registry/registry.h, lib/Async/Registry/registry_variable.cpp, lib/Async/Registry/registry_variable.h, lib/Async/Registry/thread_registry.cpp, lib/Async/Registry/thread_registry.h, tests/Async/Registry/RegistryTest.cpp, tests/Async/Registry/ThreadRegistryTest.cpp
Adds a rest handler that prints all non-deleted async calls that are registered in the async registry.
=> Add async registry rest handler

CHANGELOG, arangod/Aql/Condition.cpp, arangod/RocksDBEngine/RocksDBMultiDimIndex.cpp, tests/js/client/aql/aql-mdi-prefix-fields.js, tests/js/client/aql/aql-mdi-sparse.js
While the optimizer correctly handled sparse MDI queries, it did not choose the best utilization available. With sparse indexes, `null` values have to explicitly excluded, otherwise range queries containing `doc.x < 5` can not be optimized. This is because `null` is smaller than all numbers and thus would have to be returned, but those documents are not stored in the index because of sparseness. Thus it does not use the index.
If you add the condition `doc.x != NULL` it will use the index, but did not optimize away the null check.
```
FOR doc IN col 
FILTER doc.x <= 6 
FILTER doc.y >= 8 
FILTER doc.created != NULL 
FILTER doc.p == 5 
RETURN doc.foo
Id   NodeType        Par   Est.   Comment
1   SingletonNode            1   * ROOT 
13   IndexNode         ✓      0     - FOR …
```
=> Optimize MDI Sparse Condition Matcher

arangod/AsyncRegistryServer/Feature.h, arangod/AsyncRegistryServer/RestHandler.cpp, lib/Async/Registry/promise.h, lib/Async/Registry/registry.h, lib/Async/Registry/registry_variable.cpp, lib/Async/Registry/registry_variable.h, lib/Async/Registry/thread_registry.cpp, lib/Async/Registry/thread_registry.h, lib/Async/include/Async/async.h, tests/Async/AsyncTest.cpp, tests/Async/Registry/RegistryTest.cpp, tests/Async/Registry/ThreadRegistryTest.cpp
This is just a pure refactoring PR, it does two renamings:
- renaming the global variable `coroutine_registry` to `registry` because it is supposed to be used not only for coroutines but also for other async constructs
- renaming `PromiseInList` to `Promise`, which is shorter and still descriptive (and unique because it is part of the namespace `async_registry`)
=> Refactor names in async registry

CHANGELOG, arangod/ClusterEngine/ClusterIndex.cpp, arangod/ClusterEngine/ClusterIndex.h
Fix data-race reported by TSan via https://jenkins.arangodb.biz/job/arangodb-ANY-linux-san.x86-64/2526/EDITION=enterprise,SAN_MODE=TSan,STORAGE_ENGINE=rocksdb,TEST_SUITE=single,limit=linux&&test&&cloud&&x86-64/artifact/testfailures.txt
- [*] GitHub issue / Jira ticket: https://arangodb.atlassian.net/browse/BTS-1973
- [*] Original PR: https://github.com/arangodb/arangodb/pull/21098
=> Backport of fix for data race in cluster selectivity estimates [BTS-1973]

arangod/Aql/Condition.cpp, tests/js/client/aql/aql-mdi.js
Fix an issue with the `IN_RANGE` function call on MDI index when there are multiple IN_RANGE function calls and when the IN_RANGE is on non-first indexed field.
=> Fix `IN_RANGE` on MDI index

arangod/Aql/ExecutionNode/SubqueryNode.cpp, arangod/Aql/ExecutionPlan.cpp, arangod/Aql/OptimizerRules.cpp, arangod/IResearch/IResearchDocument.cpp, arangod/RocksDBEngine/RocksDBOptimizerRules.cpp, arangod/RocksDBEngine/RocksDBOptionFeature.cpp
Small refactoring, make initializer_list `static constexpr` where possible
=> Make initializer_list constexpr if possible

arangod/AsyncRegistryServer/Feature.h, lib/Async/Registry/registry.cpp, lib/Async/Registry/registry.h, lib/Async/Registry/registry_variable.cpp, lib/Async/Registry/thread_registry.cpp, lib/Async/Registry/thread_registry.h, tests/Async/Registry/RegistryTest.cpp
The global registry includes a list of all thread registries. A thread registry should only be deleted from this list after it is not used any more, aka when the corresponding thread was destroyed AND all promises inside the thread registry are marked for deletion. Before, the latter condition was ignored.
=> Fix thread registry beeing removed too early

CHANGELOG, tests/js/client/shell/aql-string-conversion.js
This is a backport of https://github.com/arangodb/arangodb/pull/21332
This addresses https://arangodb.atlassian.net/browse/BTS-1969
in a different way than previously planned.
This PR "fixes" JSON dumping for large double values.
- Our normal API uses JSON as input and output format. In most APIs,
however, it is nowadays also possible to use VelocyPack (ContentType:
application/x-velocypack).
- Internally, we only store VelocyPack.
- VelocyPack has essentially three different number types: Unsigned
Integers (0 <= x < 2^64), Signed Integers (-2^63 <= x < 2^63) and
Doubles (IEEE-754), but JSON has only one number type.
- Our JSON parser (to VPack) tries its best to parse any JSON number to
"something sensible", if the number does not contain a "." or an "e" it 
uses integer types as much as …
=> Fix JSON dumping of large numbers

tests/Fuerte/ConnectionFailuresTest.cpp
Don't access the waiting threads stack after signaling the wait group.
=> Fuerte Test stack-use-after-free

js/client/modules/@arangodb/testsuites/arangosh.js
The test status of running sub-arangoshes with files  would not be evaluated correctly - fixed.
This fix would have found https://github.com/arangodb/arangodb/pull/21334 in first place during CI.
=> QA-563: fix detection of exit code tests

CHANGELOG, arangod/RestServer/TtlFeature.cpp
*Bind vars for TTL deletions shouold not be moved when reused*
No need to backport: In 3.11 the bindVars are not moved
`scripts/unittest shell_client --test ttl` triggers the added assertion with old code version
=> ttl deletions are now retried. bind vars should not be moved anymore.

lib/Async/Registry/promise.h, lib/Async/Registry/thread_registry.cpp
Make previous pointer an atomic to synchronize access to it.
=> Bug fix tsan garbage collection

lib/Basics/ResourceUsage.h
Newer version of libstdc++ failed to compile with the custom allocator. This PR rectifies this.
=> Fix compilation for new libstdc++.

tests/js/client/recovery/check-warnings-exitzero.js
It seems we can't avoid this warning hence ignore it as well:
"2024-10-14T11:44:13.934702Z [103-1] S WARNING [a1690] {threads} Scheduler received shutdown, but there are still tasks on the queue: jobsSubmitted=15 jobsDone=14"
=> ignore warning

arangod/Utils/ExecContext.h, lib/Async/CMakeLists.txt, lib/Async/include/Async/async.h, lib/Async/include/Async/coro-utils.h, lib/Futures/CMakeLists.txt, tests/Async/AsyncTest.cpp
Saves execution context in async-coroutine, such that when such a coroutine is resumed, the previous execution context of the coroutine is loaded. And when a coroutine is suspended, the execution context is changed back to the one of the caller.
This is achieved by the `await_transform` function of the coroutine promise, which is called on `expr` in  `co_await expr` before the co_await operator is applied. This function is now written in such a way that it can be called on any coroutine-type that defines how co_await is handled:
- On types that define the co_await operator as a member function, 
- on types that have a co_await operator defined on them and
-  on types that just define the co_await-functions (`await_ready`, `await_suspend` and `await_resume`) as member functions.
=> Add execution context to async

js/client/modules/@arangodb/testutils/process-utils.js
the windows implementation of `pu.executeAndWait` would not actually wait properly. Fix that.
=> fix timeout handling of spawned processes

arangod/Scheduler/Scheduler.cpp
disable assert for the connectivity-check items
=> we know the wintendo looses connectivity checks, ignore it.

js/client/modules/@arangodb/testutils/client-tools.js
we need to waitpid to purge it from our PID-list.
=> Bug fix/missing status external

CHANGELOG, lib/ApplicationFeatures/LanguageFeature.cpp, lib/ApplicationFeatures/LanguageFeature.h
This tries to address https://arangodb.atlassian.net/browse/BTS-1792
There it was found that the ICU library does not seem to be initialized
when the AgencyCache tries to use it.
We move the call to `setLocale` from the start method into the prepare
method of the LanguageFeature.
- **Move setLocale into prepare in LanguageFeature.**
- [*] Backport for 3.11: https://github.com/arangodb/arangodb/pull/21385
- [*] GitHub issue / Jira ticket: https://arangodb.atlassian.net/browse/BTS-1792
=> Call setLocale earlier in LanguageFeature [BTS-1792]

CHANGELOG, arangod/Aql/ExecutionBlockImpl.tpp, arangod/Aql/ExecutionNode/EnumeratePathsNode.cpp, arangod/Aql/ExecutionNode/ShortestPathNode.cpp, arangod/Aql/Executor/ShortestPathExecutor.cpp, arangod/Graph/EdgeDocumentToken.h, arangod/Graph/Enumerators/CMakeLists.txt, arangod/Graph/Enumerators/WeightedShortestPathEnumerator.cpp, arangod/Graph/Enumerators/WeightedShortestPathEnumerator.h, arangod/Graph/Enumerators/WeightedTwoSidedEnumerator.cpp, arangod/Graph/Enumerators/WeightedTwoSidedEnumerator.h, arangod/Graph/Enumerators/YenEnumerator.cpp, arangod/Graph/PathManagement/PathResult.h, arangod/Graph/Providers/SingleServerProvider.cpp, arangod/Graph/Providers/SingleServerProvider.h, arangod/Graph/algorithm-aliases.h, lib/Basics/StaticStrings.cpp, lib/Basics/StaticStrings.h, tests/Graph/GraphMockProviderInstances.cpp, tests/Graph/WeightedShortestPathTest.cpp, tests/js/client/aql/aql-graph-enumerate-path-filter.js, tests/js/client/aql/aql-graph-k-shortest-path-0-weight-regression.js, tests/js/client/aql/aql-graph-k-shortest-path-early-abort-regression.js, tests/js/client/aql/aql-graph-k-shortest-path.js, tests/js/client/aql/aql-memory-limit.js
Tune shortest paths to bring back 3.10 performance. This PR does not quite achieve this, but it brings the YenEnumerator and the WeightedShortestPathEnumerator in a state that they perform the same search as in 3.10.
The performance is still not on 3.10 level, since the underlying infrastructure has been weakened, too. In particular the `SingleServerProvider` does less caching than the corresponding code in 3.10 did. This will be addressed by a separate PR.
This effort comes from an investigation as to why Version 3.10 performed weighted shortest path computations (and as a consequence also Yen k-shortest-path computations) much faster than 3.12.
The finding is the following: In both implementations we use a two sided enumeration. We essentially use the same Dijkstra-like algorithm, but …
=> Refactor shortest path

lib/Async/Registry/promise.h, lib/Async/include/Async/async.h, lib/Futures/include/Futures/Future.h, lib/Futures/include/Futures/Promise.h, lib/Futures/include/Futures/Utilities.h, lib/Futures/include/Futures/coro-helper.h, tests/Futures/FutureTest.cpp
Async registry waiter is now set for
- future coroutines
- futures continuations (then, thenValue, thenError)
- future collections (collectAll, collect, gather)
Addtionally, the source location is now updated in future coroutines.
=> Set waiter in future functions

lib/Async/Registry/promise.h, lib/Async/Registry/thread_registry.cpp, lib/Async/include/Async/async.h, lib/Futures/include/Futures/Promise.h, lib/Futures/include/Futures/SharedState.h, lib/Futures/include/Futures/coro-helper.h, tests/Async/AsyncTest.cpp, tests/Futures/CMakeLists.txt, tests/Futures/FutureCoroutineTest.cpp, tests/Futures/FutureTest.cpp
Adds a state to the async registry promise, which can be either Running, Suspended, Resolved or MarkedForDeletion.
The object that creates the promise is responsible for updating this state:
async<T> coroutine:
- Is Running when created and resumed
- Is Suspended when it suspends
- Is Resolved when it hits co_return
- Is Deleted when the coroutine is destroyed
Future<T> coroutine:
same as for async<T> coroutine
plain Future<T> which is not resolved on creation:
- Is Suspended when created
- Is Resolved when its Promise<T> is resolved or its callback is finished running
- Is Running when its callback is running
- Is Deleted when the future is destroyed
=> Add promise state to registry

CHANGELOG, arangod/Aql/Executor/JoinExecutor.cpp, tests/js/client/aql/aql-index-join.js
Add missing accounting for document look ups in JOIN nodes when late materialization is enabled. Although the documents are lookup up in the materialize node, we account for it in the Join node, because the Materialize Node is pass through and thus only supports `NoStats`.
=> Bug fix/join late materialize doc lookup counter

arangod/AsyncRegistryServer/RestHandler.cpp, lib/Async/Registry/promise.h, lib/Async/Registry/registry.h, lib/Async/Registry/thread_registry.h, tests/Async/AsyncTest.cpp, tests/Async/AsyncTestLineNumbers.tpp, tests/Async/Registry/RegistryTest.cpp, tests/Async/Registry/ThreadRegistryTest.cpp, tests/Futures/FutureCoroutineTest.cpp, tests/Futures/FutureTest.cpp
When iterating over all promises in the async registry, we now iterate over a new snapshot object and not a ptr to the object itself. This makes the iteration easier to use.
=> [Async Registry] Iterate over promise snapshot instead of promise ptr

arangod/ClusterEngine/ClusterIndex.cpp
Exclude prefixFields from being added twice.
=> Exclude prefixFields from being added twice.

arangod/AsyncRegistryServer/pretty_printer/README.md, arangod/AsyncRegistryServer/pretty_printer/pretty_printer.py
Adds a script to transform the async-registry REST output into pretty-printed stacktraces with ascii-branches.
=> Pretty print async-registry REST output

arangod/AsyncRegistryServer/CMakeLists.txt, arangod/AsyncRegistryServer/Feature.cpp, arangod/AsyncRegistryServer/Feature.h, arangod/AsyncRegistryServer/RestHandler.cpp, arangod/AsyncRegistryServer/RestHandler.h, arangod/arangoserver.cmake
Uses an async mutex (FutureSharedLock) to achieve that.
Additionally, adds authentication and forwarding from coordinator to other other instances.
=> Make sure that async registry REST handler is running more than once at the same time

tests/js/client/load-balancing/load-balancing-foxx-installation-noauth-cluster.js
fix test error handling: 
```
=== cl_load_balancing ===
* Test "load_balancing"
[FAILED]  tests/js/client/load-balancing/load-balancing-foxx-installation-noauth-cluster.js
"testFoxxZipUploadWithRedirect" failed: TypeError: Cannot read properties of undefined (reading 'hasOwnProperty')
at installFoxxZipFile (/work/ArangoDB/tests/js/client/load-balancing/load-balancing-foxx-installation-noauth-cluster.js:111:28)
at Object.testFoxxZipUploadWithRedirect (/work/ArangoDB/tests/js/client/load-balancing/load-balancing-foxx-installation-noauth-cluster.js:194:7)
at /work/ArangoDB/tests/js/client/load-balancing/load-balancing-foxx-installation-noauth-cluster.js:239:9
...    at Function.forEach (/work/ArangoDB/js/node/node_modules/lodash/lodash.js:9410:14)
```
=> we may receive an undefined body and later on struggle over that.

js/apps/system/_admin/aardvark/APP/frontend/js/models/arangoCollectionModel.js
Set details to `false`, to remove the need for key range scans in RocksDB.
=> Remove details fetching to avoid key range counts

arangod/AsyncRegistryServer/RestHandler.cpp, arangod/AsyncRegistryServer/pretty_printer/pretty_printer.py, arangod/Scheduler/WorkStealingThreadPool.cpp, lib/Async/Registry/promise.h, lib/Async/include/Async/async.h, lib/Futures/include/Futures/Future.h, lib/Futures/include/Futures/Promise.h, tests/Async/AsyncTest.cpp, tests/Futures/FutureTest.cpp
You can wait synchronously on a future. The corresponding promise in the async registry does now know the thread id of the thread that does the waiting. This enables the user to connect normal and async stacktraces.
A promise does now have an optional waiter:
- If no sync or async operation awaits this promise, this promise has no waiter
- If this promise is awaited by an async operation, this promise has an async waiter (which includes the id of the waiter promise)
- If this promise is awaited by a sync operation (which happens when a thread waits on a future), this promise has a sync waiter (which includes the id of the waiting thread)
one waiter which is either 
Additionally, this PR adds garbage collection also in the new scheduler (same is already done in the old (supervised) …
=> Promise can have an async or sync waiter

CHANGELOG, arangod/Cluster/Maintenance.cpp, arangod/ClusterEngine/ClusterIndex.cpp, client-tools/Dump/DumpFeature.cpp, lib/Basics/VelocyPackHelper.cpp
*Hotfix 3.12.3.1 to include race fix for synchronise shard where the old leader falls out of sync. MDI index presence breaks arangodump with malformed JSON error*
=> Hot fix for synchronise shard race and arangodump malformed JSON with MDI

js/client/modules/@arangodb/testutils/result-processing.js
ye olde V8 doesn't have replaceAll()
=> QA-580: the old v8 doesn't have replaceAll

arangod/Cluster/Maintenance.cpp
Refuse sync only after check if sync is necessary. Add more details to the log message.
=> Refuse Sync Log Message Improvements

arangod/RestServer/QueryRegistryFeature.cpp
Backports fixes made in https://github.com/arangodb/arangodb/pull/21177/ to indicate that the query result cache is single server-only (not to be confused with the query plan cache) and that the optimizer max plans startup option is for single server and Coordinators.
=> Fix query cache / optimizer startup option flags

CHANGELOG, arangod/RocksDBEngine/RocksDBMultiDimIndex.cpp, arangod/Zkd/CMakeLists.txt, arangod/Zkd/ZkdHelper.cpp, arangod/Zkd/ZkdHelper.h, tests/Zkd/CMakeLists.txt, tests/Zkd/Conversion.cpp, tests/js/client/aql/aql-mdi-prefix-fields.js
Implements a faster encoding of doubles to a memcmp format.
* Makes it a cmake option
* Makes sure that it does not produce different values as the old/slower implementation
* Removes unneeded db._explain in a test
=> MDI performance improvements

CHANGELOG, arangod/Cluster/FollowerInfo.cpp
Fix delay if write hits directly after a hotbackup restore.
Analysis see: https://arangodb.atlassian.net/browse/BTS-2014
- [*] :fire: Performance improvement
- [*] Tests
- [*] RTA
- [*] GitHub issue / Jira ticket: BTS-2014
- [*] Corresponding devel PR: https://github.com/arangodb/arangodb/pull/21445
=> Fix delay in maintenance if write hots directly after hotbackup restore [BTS-2014]

CHANGELOG, arangod/Agency/CleanOutServer.cpp, tests/Agency/CleanOutServerTest.cpp, tests/Agency/CleanOutServerTest.json
Otherwise the MoveShardJob will fail.
=> [BTS-2017] Set remainsFollower=true for satellite collections.

arangod/Aql/AqlFunctionFeature.cpp, arangod/Aql/AqlFunctionFeature.h
https://jenkins.arangodb.biz/job/arangodb-ANY-linux-san.x86-64/2540/EDITION=enterprise,SAN_MODE=TSan,STORAGE_ENGINE=rocksdb,TEST_SUITE=cluster,limit=linux&&test&&cloud&&x86-64/artifact/testfailures.txt
Wraps mutex around function names map via the guarded struct to avoid the data race.
Backport for 3.11 is required as this tsan failure was seen there.
=> Fix tsan data race

arangod/AsyncRegistryServer/RestHandler.cpp, arangod/AsyncRegistryServer/pretty_printer/pretty_printer.py, lib/Async/Registry/promise.cpp, lib/Async/Registry/promise.h, lib/Async/Registry/registry_variable.cpp, lib/Async/Registry/thread_registry.cpp, lib/Async/Registry/thread_registry.h, lib/Basics/Thread.cpp, lib/Basics/Thread.h, lib/Futures/include/Futures/Future.h, tests/Async/AsyncTest.cpp, tests/Async/Registry/RegistryTest.cpp, tests/Async/Registry/ThreadRegistryTest.cpp, tests/Futures/FutureCoroutineTest.cpp, tests/Futures/FutureTest.cpp
- Prints LWPID instead of std::thread::Id (LWPID is handy because debugging tools like gdb and top directly give this number, it is only Linux-specific)
- Prints promise id in hexadecimal representation
- Prints thread name for requesting thread
=> Improve readability of async registry output

CHANGELOG, arangod/Aql/Query.cpp, arangod/Aql/QueryOptions.h, js/common/bootstrap/errors.js, lib/Basics/errors.dat, tests/js/client/aql/aql-query-plan-cache.js
This strives to make the behaviour of the query plan cache more
coherent. In cases in which the user has requested query plan caching
with the option usePlanCache set to true, but the query is not eligible
for caching, error out.
Also check these conditions on `explain`, so that explain behaves the same as normal query execution.
- [*] Tests
- [*] Backports: no backports necessary
none
=> Error out if usePlanCache=true and query not eligible for plan caching

arangod/Aql/Query.cpp, arangod/Aql/Query.h, arangod/Aql/QueryPlanCache.cpp, arangod/Aql/QueryPlanCache.h, arangod/V8Server/v8-vocbase.cpp, tests/js/client/aql/aql-optimizer-rule-late-document-materialization-arangosearch.inc
If a query explain was loaded from the query plan cache, the query was instantiated (e.g., snippets created on the dbservers etc.). This PR changes that, so instantiation no longer happens during explain.
=> Don't instantiate query during explain

arangod/Agency/Job.cpp
Replaces inefficient iterator advance with a second lookup vector.
The second vector where we cache the keys of the map allows for a simple `std::transform` and by-index access, instead of the `std::andvance` on the `immer::map` iterator.
=> Removes Quadratic Algorithm

arangod/RocksDBEngine/RocksDBDumpContext.cpp, tests/js/client/shell/api/dump-cluster.js
Fix bug introduced during refactoring. If a projection access a non-existing path, it is not added to the result.
=> Dump Projection Bug

arangod/Cluster/ClusterInfo.cpp
Backport of https://github.com/arangodb/arangodb/pull/21484
=> 3.11 backport: Fix use-after-free in ClusterInfo SyncerThread

CHANGELOG, arangod/RestHandler/RestAdminClusterHandler.cpp
This addresses https://arangodb.atlassian.net/browse/BTS-2040
The API /_admin/cluster/removeServer does not work any more if a cluster
was upgraded from 3.11 to 3.12. The reason is that the entries under
/arango/Databases do not yet have an attribute replicationVersion set to
a string. Some place in the implementation of this API assumes however
that there is a string and throws an exception if not.
The fix is simple, just ignore if the attribute is not set and treat it
as if there were a string "1" there.
- [*] Backports: none needed
- [*] GitHub issue / Jira ticket: https://arangodb.atlassian.net/browse/BTS-2040
=> Fix remove server API [BTS-2040]

CHANGELOG, arangod/Agency/Supervision.cpp, arangod/Agency/Supervision.h, tests/Agency/SupervisionTest.cpp
This addresses https://arangodb.atlassian.net/browse/BTS-2022.
The issue is the following: Our regular cleanup of failed jobs in the
agency can clean up failed MoveShard jobs which are part of a
CleanOutServer job which is still Pending. This means that the
CleanOutServer job at the end might not detect that it has in fact
failed, and some data remains on the to be cleaned out server.
The bugfix is simple: Do not clean up jobs which are subjobs of a Pending
superjob.
- [*] Backport for 3.11: https://github.com/arangodb/arangodb/pull/21488
- [*] GitHub issue / Jira ticket: *(Please reference tickets / specification / other PRs etc)*
=> Do not clean up failed jobs before their parent is finished [BTS-2022]

arangod/Agency/Job.cpp
Replaces inefficient iterator advance with a second lookup vector.
The second vector where we cache the keys of the map allows for a simple `std::transform` and by-index access, instead of the `std::andvance` on the `immer::map` iterator.
=> [3.11][BTS-2027] Removes Quadratic Algorithm

CHANGELOG, arangod/Agency/AgencyFeature.cpp, arangod/Agency/AgencyFeature.h, arangod/Agency/AgentConfiguration.cpp, arangod/Agency/AgentConfiguration.h, arangod/Agency/Supervision.cpp, arangod/Agency/Supervision.h, arangod/Cluster/ClusterFeature.cpp, arangod/Cluster/ClusterFeature.h, arangod/Cluster/HeartbeatThread.cpp, arangod/Cluster/HeartbeatThread.h, tests/Agency/SupervisionTest.cpp
This addresses https://arangodb.atlassian.net/browse/BTS-2039
We found there that hotbacks do not work if there are old servers
configured in the agency which do no longer exist.
The root cause of this problem is that the cleanup of expired servers
in the agency did not work. This PR repairs the functionality.
The reason why the expiration did not work is the following:
1. DBServers and Coordinators send hearbeats to `transient:/arango/Sync/ServerStates/<ID>` and send their time in the `time` attribute.
2. The Supervision considers all servers in `agency:/arango/Plan/Coordinators` or `agency:/arango/Plan/DBServers` respectively and copies the entries in `transient:/arango/Sync/ServerStates` to `transient:/arango/Supervision/Health/<ID>`.
3. There is a sublety here: Since servers send …
=> Fix expiration of servers in agency [BTS-2039]

arangod/Pregel/Conductor/Conductor.cpp, arangod/Pregel/GraphStore/GraphLoader.cpp, arangod/Pregel/Worker/Worker.cpp
for regular execution loglevel WARN is not advised.
=> no WARN for regular execution.

CHANGELOG, arangod/Aql/grammar.y
In a query like
```
FOR doc IN col
COLLECT a = doc.a INTO b = doc.b KEEP doc
RETURN a
```
The `KEEP` statement has no effect, because `INTO` is used with a projection expression. Now a parser error is triggered.
=> Disallow KEEP with INTO var = expr.

CHANGELOG, arangod/Cluster/SynchronizeShard.cpp, arangod/Network/ConnectionPool.h, arangod/Replication/DatabaseInitialSyncer.cpp, arangod/Replication/DatabaseTailingSyncer.cpp, arangod/Replication/DatabaseTailingSyncer.h, arangod/Replication/ReplicationFeature.cpp, lib/SimpleHttpClient/ConnectionCache.cpp, lib/SimpleHttpClient/ConnectionCache.h, tests/SimpleHttpClient/ConnectionCacheTest.cpp
This addresses
https://arangodb.atlassian.net/browse/BTS-2011
and 
https://arangodb.atlassian.net/browse/BTS-2042
The common theme is TCP/IP connections within the cluster, which are sometimes broken by external actors in the cloud, or indeed by our own `arangod`. This PR adds a timeout for idle TCP/IP connections in the `ConnectionCache` of 120s. Furthermore, there is a fix for `SynchronizeShard`, which leased a connection for the `DatabaseTailingSyncer` too early in the process, so that it could be stale until the `DatabaseTailingSyncer` was actually used.
Finally, it increases a few timeouts in replication for larger or slower
cases.
- [*] Backport for 3.11:  https://github.com/arangodb/arangodb/pull/21529
- [*] GitHub issue / Jira ticket: …
=> Expire idle connections [BTS-2041] [BTS-2011]

CHANGELOG, arangod/Aql/Aggregator.cpp, arangod/Aql/CollectOptions.cpp, arangod/Aql/CollectOptions.h, arangod/Aql/ExecutionNode/CollectNode.cpp, arangod/Aql/ExecutionNode/CollectNode.h, arangod/Aql/ExecutionPlan.cpp, arangod/Aql/OptimizerRules.cpp, arangod/Aql/SortElement.cpp, arangod/Aql/SortElement.h, tests/js/client/aql/aql-collect-output-aggregation-optimization-cluster.js, tests/js/client/aql/aql-optimizer-collect-methods.js, tests/js/client/aql/aql-optimizer-keep.js, tests/js/client/aql/aql-optimizer-rule-use-index-for-sort-cluster.js
Given a query like this
```
FOR doc IN ${collection}
COLLECT a = doc.a INTO b = doc.b
RETURN [a, b]
```
Previously the optimizer did not push the collect statement onto the database servers. This resulted in a query like this:
```
Query String (59 chars, results cachable: true):
FOR doc IN c COLLECT a = doc.a INTO b = doc.b RETURN [a, b]
Id   NodeType          Site  Par   Est.   Comment
1   SingletonNode     DBS            1   * ROOT 
9   IndexNode         DBS     ✓   1000     - FOR doc IN c   /* persistent index scan, index only (projections: `a`, `b`), 3 shard(s) */    LET #8 = doc.`a`, #9 = doc.`b`   
12   RemoteNode        COOR        1000       - REMOTE
13   GatherNode        COOR        1000       - GATHER #8 ASC  /* parallel, sort mode: minelement */
5   CollectNode …
```
=> Collect Performance Improvement

arangod/AsyncRegistryServer/pretty_printer.py, arangod/AsyncRegistryServer/pretty_printer/README.md
- Moves the pretty_print script on level up (the extra directory is not needed)
- Adds some pretty-print documentation
- Improves the tree printout:
Before:
```
─ futures::Future<arangodb::Result> arangodb::AgencyCache::waitFor(index_t, Executor) (/home/jvolmer/code/arangodb/arangod/Cluster/AgencyCache.cpp:165), CurrentSyncer(28104), Suspended
CurrentSyncer(28104)
```
After:
```
┌ futures::Future<arangodb::Result> arangodb::AgencyCache::waitFor(index_t, Executor) (/home/jvolmer/code/arangodb/arangod/Cluster/AgencyCache.cpp:165), CurrentSyncer(28104), Suspended
─ CurrentSyncer(28104)
```
=> [Async Observability] Improve async registry pretty print

CHANGELOG, arangod/Aql/OptimizerRules.cpp, tests/js/client/aql/aql-geo-cluster.js
This addresses https://arangodb.atlassian.net/browse/BTS-2046.
Performance of geo queries like this are much worse with a geo index than without in the cluster with a collection with multiple shards:
```
FOR c IN crimes
SORT GEO_DISTANCE(c.geo, [-118.3556633, 34.0638005]) ASC
LIMIT 1000
RETURN c._key
```
The reason is that an unnecessary and bad SORT node is moved to the dbserver. This node leads to the fact that the whole collection is read from the geo index, rather than just the needed documents and an additional sort step is performed.
The fix is relatively simple by just saying that this SORT node should not be inserted in the critical circumstances.
Commits:
- **Avoid a bad SORT node in the cluster when a geo index is used.**
- [*] :fire: …
=> Improve geo index performance in the cluster [BTS_2046]

CHANGELOG
Add missing CHANGELOG entry for the https://github.com/arangodb/arangodb/pull/21503
=> Add missing CHANELOG entry for refactor vector index

CHANGELOG, arangod/RestHandler/RestImportHandler.cpp, arangod/RestHandler/RestImportHandler.h, arangod/RocksDBEngine/RocksDBMethodsMemoryTracker.cpp, arangod/Transaction/ManagerFeature.h, client-tools/Import/ImportFeature.cpp
This addresses https://arangodb.atlassian.net/issues/BTS-2047 .
See explanation there. We basically decrease the default batch size and
increase the limit for streaming transactions, which are used for smart
edge collection in `arangoimport`.
Furthermore, we make the `RestImportHandler` asynchronous.
- **Remove unnecessary includes.**
- **Adjust batch size and maximal streaming transaction size.**
- **Make RestImportHandler asynchronous.**
- 
This is not relevant in 3.11, where the accounting does not cover
this memory usage.
=> Make arangoimport great again [BTS-2047]

arangod/Indexes/VectorIndexDefinition.h
Remove duplicated nLists from the vector index definition.
=> Fix vpack representation of vector index definition

CHANGELOG, client-tools/Restore/RestoreFeature.cpp, client-tools/Restore/RestoreFeature.h, lib/Basics/StaticStrings.cpp, lib/Basics/StaticStrings.h
A vector index needs training data. Therefore, it cannot be created
before data import in arangorestore. We must delay the creation of the
vector index until after data import in arangorestore.
This addresses https://arangodb.atlassian.net/browse/BTS-2058
- [*] GitHub issue / Jira ticket: https://arangodb.atlassian.net/browse/BTS-2058
=> Let arangorestore vector indexes only after data import [BTS-2058]

arangod/GeneralServer/H2CommTask.cpp
Fixes a off-by-one which leads to a double delete call.
=> Fixes crash in H2CommTask

js/client/modules/@arangodb/test-helper.js, js/client/modules/@arangodb/testsuites/arangosh.js, tests/js/client/shell/agency-oneshard-regression-nocluster.js, tests/js/client/shell/shell-arango-secure-installation-noncluster.js, tests/js/client/shell/shell-dump-integration.js, tests/js/client/shell/shell-restore-integration.js, tests/js/client/shell/shell-verify-sst-noncluster.js
Extract function, preparation for backport (which is needed to fix red test in https://github.com/arangodb/arangodb/pull/21504).
Unfortunately currently not testable because the tsan runs fail due to the linking issue with lapack.
=> Extract executeExternalAndWaitWithSanitizer function

js/client/modules/@arangodb/testutils/testing.js
The `testfailures.txt` will now contain this instead of a json dump of the test attributes:
```
* Test "arangosh"
[FAILED]  currentTest
"test" failed: caught exception in testsuite: snatoehusnatoehu
Error: snatoehusnatoehu
at runTest (/home/willi/src/devel/js/client/modules/@arangodb/testsuites/arangosh.js:108:11)
at Object.arangosh (/home/willi/src/devel/js/client/modules/@arangodb/testsuites/arangosh.js:184:3)
at iterateTests (/home/willi/src/devel/js/client/modules/@arangodb/testutils/testing.js:451:38)
at unitTest (/home/willi/src/devel/js/client/modules/@arangodb/testutils/testing.js:551:12)
at main (js/client/modules/@arangodb/testutils/unittest.js:102:14)
at js/client/modules/@arangodb/testutils/unittest.js:156:14
Suites failed: 1 Tests Failed: 0
Marking crashy!
```
=> if we have an infrastructure failure make sure that we still have a meaningfull testfailurse.txt

js/client/modules/@arangodb/testutils/client-tools.js
It seems the non-instrumented time needs to be longer.
=> increase non-instrumented timeout

js/server/assets/swagger/index.css
Before:
Uses the ArangoDB dark green but keeps the original style for the Cancel button it changes to.
This is an improvement that has been requested by Tilman.
=> Web interface: Make Try it out button in Swagger UI stand out more

CHANGELOG, tests/Network/ConnectionPoolTest.cpp
This tries to fix an unstable test for the NetworkConnectionPool.
First we move away from existing endpoints, since we never know how
long they are going to take to respond.
Secondly, we prolong the timeout and then add further logging in
case things go wrong.
=> Fix unstable network pool test

CHANGELOG, arangod/Scheduler/SchedulerFeature.cpp
This addresses https://arangodb.atlassian.net/browse/BTS-2077
- [*] Backports:
-     - 3.11: https://github.com/arangodb/arangodb/pull/21600
=> Deactivate cluster overwhelm on agents [BTS-2077]

client-tools/Shell/V8ShellFeature.cpp, client-tools/Shell/V8ShellFeature.h, client-tools/Shell/v8-deadline.cpp, js/client/modules/@arangodb/testutils/testrunners.js, lib/V8/v8-deadline.h, lib/V8/v8-no-deadline.cpp
spawning one sub-shell per test wouldn't implement the timeout yet. Add this.
=> forward the deadline into sub-shell arangoshs

arangod/Aql/AqlCall.cpp
The definition arangodb::aql::to_string was missing. This resulted in a linker error when compiling in a conda environment.
=> Added missing 'to_string' implementation

tests/js/client/aql/vector/aql-vector-create-and-remove.js
Fixes the flakiness of the test when tested in cluster mode. Since the distribution of documents is not guaranteed, and the documents may end up all in one or two shards, then creating a vector index fails. Found from logs in https://arangodb.atlassian.net/browse/BTS-2085
=> Fix flaky vector test

tests/js/client/aql/aql-index-choice.js
Old PR from Lars:
Make sure that the execution plan includes an IndexNode (which the test asserts) and not an IndexCollectNode by disabling the responsible optimizer rule.
=> Disable optimizer rule that is sensitive for selectivity estimates.

CHANGELOG, arangod/Aql/SharedQueryState.cpp, arangod/Aql/SharedQueryState.h
*This addresses https://arangodb.atlassian.net/browse/BTS-2087*
Backport of https://github.com/arangodb/arangodb/pull/21635.
We found the issue to be an improper use of an atomic counter in
connection with a condition variable. This is in SharedQueryState and
the methods asyncExecuteAndWakeup and invalidate.
=> cig backport

CHANGELOG, arangod/RestHandler/RestIndexHandler.cpp
When used with the `withHidden=true` option, it can happen that
a newly created index is not shown at all or it is shown twice,
once with `isBuilding:true` and once without. Both only happen
directly after successful index creation.
The reason is that two sources are combined in the API implementation:
the agency which does show indexes currently being built and the
LogicalCollection object which is local on the coordinator.
See source code comments in the patch for details.
This has made some tests unstable.
- [*] Tests
- [*] Backport for 3.11: …
=> Fix index api shortly after successful creation [BTS-2044]

CHANGELOG, arangod/RestHandler/RestIndexHandler.cpp
When used with the `withHidden=true` option, it can happen that
a newly created index is not shown at all or it is shown twice,
once with `isBuilding:true` and once without. Both only happen
directly after successful index creation.
The reason is that two sources are combined in the API implementation:
the agency which does show indexes currently being built and the
LogicalCollection object which is local on the coordinator.
See source code comments in the patch for details.
This has made some tests unstable.
- [*] Tests
- [*] Backport for 3.11: https://github.com/arangodb/arangodb/pull/21649
- [*] GitHub issue / Jira ticket: …
=> Fix index api shortly after successful creation

CHANGELOG, lib/Logger/LoggerFeature.cpp
Double log lines with --log.output=+. Due to a small regression/behaviour with 3.12.2: if you had `--log.output=+` in a tty environment it would lead to double log-lines per log. One to stdout and one to stderr. This PR will remove this automatic stdout output if the stderr is already defined by the user.
=> Fixes a bug with unintentional double-log-line spam.

js/client/modules/@arangodb/test-helper.js
As can be observed in client-tools.js we need to waitpid after killing, else zombies will occur:
https://github.com/arangodb/arangodb/blob/devel/js/client/modules/%40arangodb/testutils/client-tools.js#L522
=> if we don't waitpid, we leave zombies. Don't do that.

client-tools/Shell/V8ClientConnection.cpp
when our connection goes away we should no longer hammer it - the server is dead.
=> abort fuzzing if we loose the connection to the arangod

CHANGELOG, arangod/VocBase/vocbase.cpp
This is a backport of https://github.com/arangodb/arangodb/pull/21675.
This addresses BTS-2103.
We need to already hold the _statusLock on a LogicalCollection object
when we read its name.
This fixes a TSAN issue.
- [*] Tests
- [*] TSAN-tests
- [*] Backport for 3.11: this is it
- [*] Jira ticket: https://arangodb.atlassian.net/browse/BTS-2103
=> Fix TSAN issue in LogicalCollection

arangod/GeneralServer/Acceptor.cpp, arangod/GeneralServer/Acceptor.h, arangod/GeneralServer/AcceptorTcp.cpp, arangod/GeneralServer/AcceptorTcp.h, arangod/GeneralServer/AcceptorUnixDomain.cpp, arangod/GeneralServer/AcceptorUnixDomain.h, arangod/GeneralServer/GeneralServer.cpp, arangod/GeneralServer/GeneralServer.h
Tsan stacktrace: https://jenkins.arangodb.biz/job/arangodb-ANY-linux-san.x86-64/2608/EDITION=enterprise,SAN_MODE=TSan,STORAGE_ENGINE=rocksdb,TEST_SUITE=cluster,limit=linux&&test&&cloud&&x86-64/artifact/testfailures.txt
An `AcceptorTcp` was deleted but at the same time a lambda (instantiated inside `AcceptorTcp::asyncAccept`) ran which captured `this` ptr to this instance by reference.
Solved this by using shared ptrs to the Acceptor instead of unique ptrs, now we capture a weak ptr to `this`, such that if the instance is destroyed before (e.g. via shutting down everything), nothing is executed any more but if the instance still exists it makes sure that it lives as long as the lambda runs.
To make sure that the `AcceptorTcp` is only created as a shared ptr, I made the constructor private …
=> Fix datarace in tcp acceptor

CHANGELOG, arangod/Aql/RestAqlHandler.cpp
While the RestAqlHandler is only for internal use in a cluster, it still can be called on a single server. So the assertion is out of place and was triggered during a fuzz test. Proper error handling is already implemented in ::execute().
This does not affect production builds, only maintainer mode.
Backport of https://github.com/arangodb/arangodb/pull/21694
=> Remove overeager assertion

.circleci/base_config.yml
Use arangodb/rclone-arangodb not oskar to download rclone within CircleCI.
=> CircleCI: update rclone usage (after it was removed from oskar)

arangod/Aql/Optimizer/Rule/OptimizerRuleCollectWithIndex.cpp, arangod/RocksDBEngine/RocksDBVPackIndex.cpp, tests/js/client/aql/aql-index-collect.js
The index collect optimizer rule that was recently added checks the selectivity of the index to decide whether the rule should be applied. The estimate that was done here was actually not correct (it was too conservative) in cluster mode: 
The rule should be applied if k / n < 1 / log n, where k is the number of distinct values, n is the number of documents and k/n is the selectivity. In cluster mode each shard has its own selectivity k_shard / n_shard, but also its own number of documents n_shard. The selectivity estimate used in the rule is the average over all shards, but before this PR the right hand side 1/ log n used the total number of documents in a collection rather than the average number of documents per shard, which is fixed now.
Actually, to have a correct estimate, we would …
=> Fix selectivity estimate based optimizer rule in cluster

arangod/RestHandler/RestCollectionHandler.cpp, arangod/RestHandler/RestCollectionHandler.h, arangod/RestHandler/RestIndexHandler.cpp, arangod/RestHandler/RestIndexHandler.h, arangod/VocBase/Methods/Collections.cpp, arangod/VocBase/Methods/Collections.h, lib/Async/include/Async/async.h, tests/Async/AsyncTest.cpp
Removes explicit synchronous/wait code from Index and Collection Rest Handler.
Adds simple get method to the Collections method.
Makes async-type nondiscard.
Fix nodiscard errors in tests.
=> Make RestCollectionHandler and RestIndexHandler async

CHANGELOG, arangod/Aql/ExecutionBlock.h, arangod/Aql/ExecutionBlockImpl.h, arangod/Aql/ExecutionBlockImpl.tpp
For our hunt of a sleeper we add further diagnosis:
1. The `PrefetchTask::waitFor` gets a loop with a timeout and
more logging if the timeout occurs.
2. We detect, if an ExecutionBlock is used by more than one
thread concurrently w.r.t. `execute()` and the destructor.
3. We detect, if more than one thread is waiting for a PrefetchTask
concurrently.
- [*] Visibility
=> Add more visibility to catch sleeping barber

tests/Mocks/Servers.cpp
[TSAN](https://app.circleci.com/pipelines/github/arangodb/arangodb/22966/workflows/2cbfe9bb-ca27-4857-858f-3453fca821ef/jobs/3021932) showed a data race between increasing the member variable `_commitIndex` (line 512) and reading it later to trigger some waiting (line 530). There is locked mutex, but it is released before the read. As far as I understand, we want to trigger some waiting with the index we just increased, therefore we now save the current commit index in a local variable that is then used for the triggering.
=> Fix data race in AgencyCache::applyTestTransaction

lib/Async/include/Async/async.h, lib/Async/include/Async/context.h, lib/Futures/include/Futures/coro-helper.h, tests/Futures/CMakeLists.txt, tests/Futures/FutureCoroutineTest.cpp
This PR makes a future coroutine set the execution context correctly, a unit test is added which failed before the changes.
Additionally, this PR does some refactoring of Futures/coro-helper.h (it gets rid of some code-duplications) and extracts a context struct that includes all contexts that need to be updated when a coroutine suspends or restores. This context can now be used easily for the coroutine definition of both async and future. Currently this context only includes only two variables, but there are more to come.
=> Fix exec context in future coroutines

CHANGELOG, arangod/GeneralServer/HttpCommTask.cpp, arangod/GeneralServer/HttpCommTask.h
Previously, when the URL in an HTTP request was corrupt, the server
would simply close the connection. With this fix here, a proper
HTTP 400 BAD REQUEST response is sent.
This fixes https://arangodb.atlassian.net/browse/BTS-2112
- **Handle corrupt URL gracefully.**
- [*] Tests
- [*] GitHub issue / Jira ticket: https://arangodb.atlassian.net/browse/BTS-2112
=> Handle corrupt URLs in HTTP requests gracefully [BTS-2112]

CHANGELOG, tests/js/client/shell/shell-write-concern-read-only-metric-cluster.js
This stabilizes a test involving write concern. It is possible that a
write concern change is done in the agency but has not yet propagated
to all involved leaders. Therefore one has to put a short retry loop
around the next write request which is supposed to work.
- [*] Tests
=> Stabilize write concern test

lib/SimpleHttpClient/ConnectionCache.cpp, lib/SimpleHttpClient/ConnectionCache.h
Fix data race shown in in [arangodb-3.11-asan-and-coverage-biweekly run this Saturday](https://jenkins.arangodb.biz/job/arangodb-ANY-linux-san.x86-64/2637/EDITION=enterprise,SAN_MODE=TSan,STORAGE_ENGINE=rocksdb,TEST_SUITE=single,limit=linux&&test&&cloud&&x86-64/artifact/testfailures.txt).
This was already fixed in devel by using an atomic instead of a plain boolean variable in #21026.
=> [3.11] Fix data race in connection cache

js/client/modules/@arangodb/testutils/instance.js, lib/Basics/PhysicalMemory.cpp
in case we fail to parse the environment variable bail out with a meaningfull error message instead of throwing uncaught.
=> don't let libc abort it

arangod/Agency/RestAgencyHandler.cpp, arangod/Agency/RestAgencyHandler.h, arangod/GeneralServer/RestHandler.h, arangod/RestHandler/RestAdminClusterHandler.cpp, arangod/RestHandler/RestAdminClusterHandler.h, arangod/RestHandler/RestAdminLogHandler.cpp, arangod/RestHandler/RestAdminLogHandler.h, arangod/RestHandler/RestDocumentHandler.cpp, arangod/RestHandler/RestDocumentHandler.h, arangod/RestHandler/RestGraphHandler.cpp, arangod/RestHandler/RestGraphHandler.h, arangod/RestHandler/RestImportHandler.cpp, arangod/RestHandler/RestImportHandler.h, arangod/RestHandler/RestLogHandler.cpp, arangod/RestHandler/RestLogHandler.h, arangod/RestHandler/RestLogInternalHandler.cpp, arangod/RestHandler/RestLogInternalHandler.h, arangod/RestHandler/RestMetricsHandler.cpp, arangod/RestHandler/RestMetricsHandler.h, arangod/RestHandler/RestReplicationHandler.cpp, arangod/RestHandler/RestReplicationHandler.h, arangod/RestHandler/RestTransactionHandler.cpp, arangod/RestHandler/RestTransactionHandler.h, arangod/RestHandler/RestUsageMetricsHandler.cpp, arangod/RestHandler/RestUsageMetricsHandler.h
As a prerequisite to rewriting the RestHandler's state machine (`runHandlerStateMachine()`) into a coroutine, which in turn is a prerequisite to e.g. make AQL setup & shutdown operations asynchronous, we need to get rid of existing async/WAITING glue code, namely the `waitForFuture()` methods of `RestHandler`.
This PR refactors most existing RestHandlers using that, so they consistently use `async<T>` or `futures::Future<T>`  instead of `WAITING` mechanisms, starting at implementing `executeAsync()` instead of `execute()`. This gets rid of both any `waitForFuture` calls, and any need for `RestStatus::WAITING`, and thus mostly of `RestStatus` as a whole.
The only missing RestHandlers are the AQL-related ones: RestCursorHandler and its derivatives RestSimpleHandler and …
=> Refactor rest handlers into coroutines

lib/TaskMonitoring/include/TaskMonitoring/task.h, lib/TaskMonitoring/task.cpp, tests/TaskMonitoring/TaskRegistryTest.cpp
Use-after-free happened in nightly alubsan run.
The mark for deletion of a node after all its references are gone was actually much too complicated: I wanted to make sure that if there is a hierarchy of parents where each parent has only one child and the lowest child is marked for deletion like this:
```
parent
child
child of child
child of child of child (marked for deletion)
```
all parents in the hierarchy are directly marked for deletion as well and we don't have to run the garbage collection several times to do that (A node has a shared pointer to its parent: when the shared pointer to the parent is destroyed - normally happening in the garbage collection - the node is marked for deletion). In the old behaviour, we cascaded through the full hierarchy and marked parents for deletion …
=> Get rid of use-after-free in async registry

js/common/modules/jsunity.js
#16021 accidentally broke `testing.js`'s ability to parse multiple `--testCase` arguments. This PR fixes that.
=> Fix matching multiple --testCase options

tests/js/client/shell/shell-index-visibility-nocov-fp.js
see how the index develops until the test eventually breaks
=> track the progress on the index buildup

arangod/Indexes/IndexFactory.cpp
Calling the `/_api/engine` always returns a vector index, even when not enabled. This fixes that.
=> Fix supported indexes API

arangod/SystemMonitor/AsyncRegistry/PrettyPrinter/src/asyncregistry/gdb_data.py, arangod/SystemMonitor/AsyncRegistry/PrettyPrinter/src/asyncregistry/gdb_forest.py, arangod/SystemMonitor/AsyncRegistry/PrettyPrinter/src/pretty-printer.py, arangod/SystemMonitor/AsyncRegistry/RestHandler.cpp, lib/Async/Registry/promise.cpp, lib/Async/Registry/promise.h, lib/Async/include/Async/async.h, lib/Async/include/Async/context.h, lib/Async/include/Async/coro-utils.h, lib/Containers/Concurrent/CMakeLists.txt, lib/Containers/Concurrent/shared.h, lib/Containers/Concurrent/thread.cpp, lib/Containers/Concurrent/thread.h, lib/Futures/include/Futures/Future.h, lib/Futures/include/Futures/Promise.h, lib/Futures/include/Futures/Utilities.h, lib/Futures/include/Futures/coro-helper.h, tests/Async/AsyncTest.cpp, tests/Async/Registry/RegistryTest.cpp, tests/Containers/Concurrent/CMakeLists.txt, tests/Containers/Concurrent/SharedTest.cpp, tests/Futures/FutureCoroutineTest.cpp, tests/Futures/FutureTest.cpp, tests/SystemMonitor/AsyncRegistry/PrettyPrinter/gdb_integration/async_registry_gdb_pretty_printer_test.cpp
[PR](https://github.com/arangodb/arangodb/pull/21776) got rid of printing the involved thread names in the async registry due to a bug. This PR adds the thread name back in, but now we directly save the thread name string when creating the `ThreadInfo` object that includes all needed thread infos for the async registry. We use this `ThreadInfo` object several times. To save the object - and therefore the string - only once, we wrap the ThreadInfo object into a shared resource object. A `ThreadInfo` instance is deleted when all its references are gone.
With this PR we use the shared `ThreadInfo` resource in two places of a promise in the async registry:
1. the owning thread of a promise (this is set during creation of the promise and never changes)
2. the parent of a promise, which can …
=> Add thread name back in

arangod/SystemMonitor/AsyncRegistry/PrettyPrinter/src/asyncregistry/gdb_data.py, arangod/SystemMonitor/AsyncRegistry/PrettyPrinter/src/asyncregistry/gdb_forest.py, arangod/SystemMonitor/AsyncRegistry/PrettyPrinter/src/pretty-printer.py, arangod/SystemMonitor/AsyncRegistry/RestHandler.cpp, lib/Async/Registry/promise.cpp, lib/Async/Registry/promise.h, lib/Async/include/Async/async.h, lib/Async/include/Async/context.h, lib/Async/include/Async/coro-utils.h, lib/Containers/Concurrent/CMakeLists.txt, lib/Containers/Concurrent/shared.h, lib/Containers/Concurrent/thread.cpp, lib/Containers/Concurrent/thread.h, lib/Futures/include/Futures/Future.h, lib/Futures/include/Futures/Promise.h, lib/Futures/include/Futures/Utilities.h, lib/Futures/include/Futures/coro-helper.h, tests/Async/AsyncTest.cpp, tests/Async/Registry/RegistryTest.cpp, tests/Containers/Concurrent/CMakeLists.txt, tests/Containers/Concurrent/SharedTest.cpp, tests/Futures/FutureCoroutineTest.cpp, tests/Futures/FutureTest.cpp, tests/SystemMonitor/AsyncRegistry/PrettyPrinter/gdb_integration/async_registry_gdb_pretty_printer_test.cpp
Unfortunately we had to revert the merge of https://github.com/arangodb/arangodb/pull/21791 into devel due to a missing memory leak. This PR includes all the commits from the previous PR and the memory leak fix commit.
=> Add thread name back in, this time without a memory leak

tests/js/client/fuzz/http-fuzz-fp.js
we could forget our connection string during the tests, hence remember it only *once* at the start.
=> properly handle connection and make sure we don't forget it

lib/Containers/Concurrent/ThreadOwnedList.h
This fixes the load memory order in the ThreadOwnedList which is used in the async registry. Using `memory_order_release` for a load operation does not make sense and can lead to compiler or runtime errors. Unfortunately, the combination of clang and libstdc++ does not seem to catch this error during compilation.
This wrong memory order usage can lead to a data race in the async registry but which is not really relevant: this data race can happen when we run the garbage collection on the async registry which can lead to an entry in the async registry not beeing deleted. But the garbage collection runs regularly, per default every second, so in the next run the item can the be deleted properly.
This is most likely the issue leading to https://github.com/arangodb/arangodb/issues/21811.
=> Fix load memory order

CHANGELOG, arangod/Aql/AqlFunctionFeature.cpp, arangod/Aql/Function/GeoFunctions.cpp, lib/Geo/GeoJson.cpp, tests/Geo/GeoJsonTest.cpp, tests/js/client/aql/aql-geo-distance-range.js
Fix BTS-213: GeoJSON coordinate validation for Point geometries, now we accept `lat,lng, z` but still ignore `z` value during calculation.
The fix ensures GeoJSON Point geometries with optional Z coordinates are properly validated and processed according to the [GeoJSON specification](https://datatracker.ietf.org/doc/html/rfc7946#section-3.1.1).
=> BTS-2139: Accept `z` in GEO position definition

CHANGELOG, js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/CollectionIndex.types.ts, js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/addIndex/vectorIndex/useCreateVectorIndex.ts
Adds support for the newly introduced **`innerProduct` metric** for vector indexes in the collection **Indexes view** of the core DB UI.  
The **`innerProduct`** option is now available in the **Metric** dropdown when creating a vector index, alongside the existing **Cosine** and **L2 (Euclidean)** options.
=> FE-664 | Added innerProduct metric in vector index form

CHANGELOG, arangod/GeneralServer/HttpCommTask.cpp, arangod/GeneralServer/HttpCommTask.h
The fuzzer has noticed that there is no response if an HTTP header
is corrupt. This PR improves this.
- **Handle corrupt headers in HttpCommTask.**
- [*] Tests
- [*] Backports: non planned
=> Handle corrupt HTTP/1.1 headers more gracefully

tests/js/client/shell/shell-in-background-failures-noncluster-fp.js
wait longer for all instrumented runs.
=> longer timeout for instrumented runs

arangod/Aql/Query.cpp, arangod/Aql/Query.h
Fixes a tsan issue in trackExecutionStart and trackExecutionEnd:
```
WARNING: ThreadSanitizer: data race (pid=575)
Read of size 1 at 0x72780014931a by thread T66 (mutexes: write M0):
#0 arangodb::aql::Query::trackExecutionEnd() /root/project/arangod/Aql/Query.cpp:1739 (arangod+0x3013d09) (BuildId: ba89abee79794c7f356015a532dac020273392c4)
#1 arangodb::aql::Query::cleanupPlanAndEngine(bool) /root/project/arangod/Aql/Query.cpp:1895 (arangod+0x300a000) (BuildId: ba89abee79794c7f356015a532dac020273392c4)
#2 arangodb::aql::Query::kill() /root/project/arangod/Aql/Query.cpp:317 (arangod+0x300ab45) (BuildId: ba89abee79794c7f356015a532dac020273392c4)
Previous write of size 1 at 0x72780014931a by thread T65 (mutexes: write M1):
#0 trackExecutionStart /root/project/arangod/Aql/Query.cpp:1734 …
```
=> Fix TSAN error in trackExecutionStart and trackExecutionEnd

CHANGELOG, arangod/RestServer/UpgradeFeature.cpp, arangod/RestServer/UpgradeFeature.h, lib/Basics/exitcodes.dat
This adds a switch --database.auto-upgrade-full-compaction option. This
is good to perform a cluster upgrade to prevent problems due to sorting
issues. With this option it is possible to upgrade a dbserver (after it
has resigned from its shard leaderships), go to a new version and verify
any sorting problems on upgrade by means of a full RocksDB compaction,
which would surface any potential sorting problem. If this goes wrong,
one can still go back to the previous version and run a full dbserver
replacement.
This is at the same time a new feature and a bug fix, since it addresses
the problems in index-sorting.
- **Implement feature.**
=> Add switch --database.auto-upgrade-full-compaction

tests/Mocks/MockTcpDummyServer.h, tests/Network/ConnectionPoolTest.cpp
The test was pinging a random site, and one test case always checks the status code of the response. That is a flaky behaviour since the server can block our requests if they happen many times... This eliminates the reliance on a random URL and utilizes a dummy TCP server.
=> Fix flaky test `acquire_endpoint` 

CHANGELOG, arangod/Aql/BlocksWithClients.cpp, arangod/Aql/BlocksWithClients.h, arangod/Aql/DistributeClientBlock.cpp, arangod/Aql/DistributeClientBlock.h, arangod/Aql/Executor/ScatterExecutor.cpp, arangod/Aql/Executor/ScatterExecutor.h, tests/Aql/Executor/AsyncExecutorTest.cpp, tests/Aql/WaitingExecutionBlockMock.cpp, tests/Aql/WaitingExecutionBlockMock.h, tests/Mocks/MockTcpDummyServer.h, tests/Network/ConnectionPoolTest.cpp
* Added a test for the MutexExecutor accessing above rows
* Simplified test setup
* Added a test suite to define the expected improved behaviour of the MutexExecutor
* Added assertions that all rows are used up by hardlimit. The test is red for now
* Fixed crash
* Added CHANGELOG entry
* Discard blocks on distirbution Node if we already have seen the HardLimit
* Removed an assert, for code i assumed to be unreachable, but it is reached within our own tests
* Fixed memory leak
* Applied clangformat
* Update arangod/Aql/BlocksWithClients.cpp
* Update arangod/Aql/BlocksWithClients.cpp
---------
=> Hotfix: bts-2152 fix overfetch input on parallel traversals

CHANGELOG, arangod/Aql/AqlFunctionFeature.cpp, arangod/Aql/Functions.cpp, lib/Geo/GeoJson.cpp, tests/Geo/GeoJsonTest.cpp, tests/js/common/aql/aql-geo-distance-range.js
This is a backport of https://github.com/arangodb/arangodb/pull/21829
=> Fix geo point definition to accept z value

CHANGELOG, arangod/Aql/Condition.cpp, scripts/startLocalCluster.sh, tests/js/client/aql/aql-optimizer-rule-remove-filter-covered-by-traversal-spec.js
Filter nodes are not being properly handled when `!=` operator is present when it is coming before TraversalNode. e.g. for the query:
```
FOR v, e IN 1 OUTBOUND 'col1/node_0' Graph myGraph
OPTIONS {edgeCollections:['ec1'], vertexCollections:['col1']}
FILTER e.type == 'ec1'
FILTER (v['value'] > 1000) AND v.value2 != true
RETURN 1
```
The generated plan was:
```
Id   NodeType          Site  Par   Est.   Comment
1   SingletonNode     COOR           1   * ROOT
2   TraversalNode     COOR           7     - FOR v  /* vertex (projections: `value2`, `value`) */, e  /* edge (projections: `_from`, `_id`, `_to`, `type`) */ IN 1..1  /* min..maxPathDepth */ OUTBOUND 'col1/node_0' /* startnode */  GRAPH 'myGraph' /* order: dfs */
10   CalculationNode   COOR           7       - LET #4 = (v.`value2` != …
```
=> Fix BTS-2182 filters not pushed in Traversal node

CHANGELOG, arangod/Cluster/Maintenance.cpp, arangod/Cluster/MaintenanceFeature.cpp, arangod/Cluster/MaintenanceFeature.h
This fixes https://arangodb.atlassian.net/browse/BTS-2202.
This bug is a regression introduced by another bug fix, which limited
the number of scheduled SynchronizeShard jobs.
The details are described in the above ticket.
- **Fix miscounting bug.**
- [*] GitHub issue / Jira ticket: https://arangodb.atlassian.net/browse/BTS-2202.
- [*] Backport to 3.12.5: https://github.com/arangodb/arangodb/pull/21894
=> Fix miscounting bug for scheduled SynchronizeShard jobs [BTS-2202]

CHANGELOG, arangod/Aql/Executor/IndexAggregateScanExecutor.cpp, arangod/Aql/Executor/IndexAggregateScanExecutor.h, arangod/Aql/Optimizer/Rule/OptimizerRuleCollectWithIndex.cpp, tests/js/client/aql/aql-index-collect.js
This already worked for simple collect statements due to the selectivity check done there.
Now we also don't use the rule for aggregate collect if the collection is empty.
=> [BTS-2201] Don't apply index-collect optimizer rule to empty collection

arangod/Aql/DistributeClientBlock.cpp
This fixes possible crashes in maintainer mode, no production impact. Was introduced in https://github.com/arangodb/arangodb/pull/21808.
=> [BTS-2194] Avoid nullptr deref in maintainer-mode assertion

js/client/modules/@arangodb/testutils/result-processing.js
We pick more fields from the gtest outputs to our own failure message:
{
"name": "acquire_endpoint",
* "file": "/root/project/tests/Network/ConnectionPoolTest.cpp",
"line": 135,
"status": "RUN",
"result": "COMPLETED",
"timestamp": "2025-08-05T11:06:38Z",
"time": "60.201s",
"classname": "NetworkConnectionPoolTest",
"failures": [
{
"failure": "unknown file\nUnknown C++ exception thrown in the test body.",
"type": ""
}
]
},
=> add more details to failures

CHANGELOG, arangod/Replication2/Version.h, arangod/RestServer/DatabaseFeature.cpp, arangod/RocksDBEngine/RocksDBEngine.cpp, arangod/RocksDBEngine/RocksDBSyncThread.cpp
A test running into a maintainer mode assertion in a commit during shutdown revealed possible races regarding the RocksDBSyncThread during shutdown.
The following changes are made in this PR:
* After the RocksDBSyncThread has been stopped, it no longer executes listeners.
This directly addresses [BTS-1732](https://arangodb.atlassian.net/browse/BTS-1732), where the listener scheduled a task after the Scheduler was stopped.
* The thread is still stopped in `RocksDBEngine::stop()`, but its destruction was moved to `RocksDBEngine::unprepare()`.
Data structures should always be destroyed and deleted in unprepare, not in stop. This could have lead to use-after-free errors during shutdown ([BTS-2177](https://arangodb.atlassian.net/browse/BTS-2177)).
* When Replication 2 is disabled, the …
=> [BTS-1732, BTS-2177] Fix stopping the rocksdb sync thread during shutdown

.circleci/base_config.yml, .circleci/build_test_image.yml
we can't lean on the upstream docker library for the UI-RTA docker images. Hence we need to store them in our own as well.
https://github.com/arangodb/release-test-automation/pull/559 related RTA pull picking up this.
=> QA-675: start adding circle-ci UI images

CHANGELOG, arangod/VocBase/Methods/UpgradeTasks.cpp
Fix a hang on singleserver upgrades. Some of the Upgrade tasks needed the UserManager to function properly.
=> Fixes singleserver upgrade.

CHANGELOG, lib/ApplicationFeatures/ApplicationServer.cpp
If an error happens during `ApplicationServer::start()`, the function attempts to shutdown all previously started features.
During startup only the enabled features are started, non-enabled features are skipped.
The shutdown loop was missing the code skipping non-enabled features and hence ran into an `ADB_PROD_ASSERT.
Testing the above fix I also found that the server is not put into the correct state when stopping and unpreparing features, so that code is added, too.
=> [BTS-2217] Attempting to STOP a non-started feature

CHANGELOG, arangod/Cluster/ClusterFeature.cpp, arangod/VocBase/KeyGenerator.cpp
In a recent PR the KeyGenerator was changed so that it is always guaranteed to produce unique IDs on INSERT or UPGRADE in a cluster. This was achieved by using cluster wide unique key generation which relies on the Cluster feature to be started.
When a database upgrade happens in a Cluster, all LogicalCollections are created on startup and initialise their KeyGenerator as part of that process. Crucially the Cluster feature is not started during upgrades.
This PR introduces a UpgradeKeyGenerator that is created when the ArangoDB process is opening collections in upgrade mode. If any code tries creating a key the database process crashes.
With this PR the arangod process also crashes if any code tries to access the `_clusterInfo` member of the Cluster feature in any state other than the …
=> [BTS-2220] Fix for CI not available on upgrade

lib/Async/include/Async/SuspensionCounter.h
The `waitingFunToCoro` function was capturing the function parameter F by reference, but not moving it into the coroutine frame. This caused a use-after-free when the coroutine continued executing after the calling function returned, leading to SIGSEGV crashes in debug builds.
=> Fix coroutine argument goes out of scope

CMakeLists.txt, cmake/CheckCompilerVersion.cmake
Compiling with gcc does not work any more, so this gets rid some minimal gcc version in our cmake files and now always warns when arangodb is build with gcc.
=> Always give cmake warning when compiling with gcc

CHANGELOG, arangod/RocksDBEngine/RocksDBOptionFeature.cpp
*Default for #subcompaction, max wal size and compaction read ahead adjusted to the established*
=> Revert rocksdb parameters to the established

CHANGELOG, arangod/Cluster/ClusterFeature.cpp, arangod/IResearch/IResearchAnalyzerFeature.cpp, arangod/IResearch/IResearchDataStore.cpp, arangod/IResearch/IResearchFeature.cpp, arangod/IResearch/IResearchLink.cpp, arangod/IResearch/IResearchViewCoordinator.cpp
=> ES-2678: Added checks to verify that clusterInfo() is

arangod/Aql/Executor/MaterializeExecutor.cpp
- MaterializeExecutor have one builder object `_projectionsBuilder`. Refactored it to be supervised.
- This class also has `_buffer`. This is already monitored by a custom buffer implementation.
=> [BTS-2203] Add SupervisedBuffer to MaterializeExecutor
