arangodb/arangodb

- arangod/IResearch/IResearchView.cpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/3784/
> iResearch asan issue

- arangod/GeoIndex/Near.h
- arangod/RocksDBEngine/RocksDBGeoIndex.cpp
> Fix issue with geo iterator reset.

- arangod/GeoIndex/Near.h
- arangod/RocksDBEngine/RocksDBGeoIndex.cpp
> [3.4] Fix issue with geo iterator reset.

- Documentation/Books/Manual/Installation/MacOSX.md
- Documentation/Books/Manual/Installation/README.md
Please review the installation paths and improve the Graphical App + Command Line App sections.
> Improve MacOSX Installation page

- tests/rb/HttpInterface/api-view-arangosearch-spec-noncluster.rb
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/2616/
> Add http_server test for creating view with links

- tests/rb/HttpInterface/api-view-arangosearch-spec-noncluster.rb
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/2617/
> Add http_server test for creating view with links (3.4)

- Documentation/Books/AQL/Graphs/Traversals.md
- Documentation/Books/Manual/Architecture/DeploymentModes/MasterSlave/Architecture.md
- Documentation/Books/Manual/Deployment/ActiveFailover/ManualStart.md
- Documentation/Books/Manual/Deployment/Cluster/ManualStart.md
- Documentation/Books/Manual/Deployment/SingleInstance/ManualStart.md
- Documentation/Books/Manual/Indexing/Hash.md
- Documentation/Books/Manual/Indexing/IndexBasics.md
- Documentation/Books/Manual/Indexing/Skiplist.md
- Documentation/Books/Manual/ReleaseNotes/NewFeatures34.md
- Documentation/Books/Manual/Upgrading/GeneralInfo/README.md
- Documentation/DocuBlocks/Rest/AQL/post_api_aqlfunction.md
Internal Ref:
- https://github.com/arangodb/planning/issues/3426
Should fix build errors
> Docs: Fix whitespace and triple-backticks

- Documentation/Books/AQL/Functions/Miscellaneous.md
> Doc - check_function

- Documentation/Books/AQL/Functions/Miscellaneous.md
> Doc - check_document

- Documentation/Books/AQL/Functions/Miscellaneous.md
- Documentation/Books/Manual/Programs/Arangorestore/Examples.md
> Doc - check_document + arangorestore improvements

- CHANGELOG
- arangod/Auth/TokenCache.cpp
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/2680/
> Bug fix 3.4/jwt base64url encoded

- CHANGELOG
- arangod/Auth/TokenCache.cpp
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/2683/
> Bug fix 3.3/jwt base64url encoded

- Documentation/Books/HTTP/Replications/README.md
- Documentation/Books/Manual/Administration/MasterSlave/ReplicationApplier.md
Backport of https://github.com/arangodb/arangodb/pull/7891
http://jenkins01.arangodb.biz:8080/view/Documentation/job/arangodb-documentation/239/
> Doc - Update remark about per-database replication (3.4)

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
> fix #7900 - null bind values do not change to empty string anymore

- Documentation/Books/Manual/Transactions/Limitations.md
Internal Ref:
- https://github.com/arangodb/planning/issues/3476
> Add a paragraph that JS JS trxs are excluded from intermediate commits.

- Documentation/Books/Manual/Transactions/Limitations.md
> 3.4 - Add a paragraph that JS JS trxs are excluded from intermediate commits.

- CHANGELOG
- arangod/Cluster/SynchronizeShard.cpp
- lib/Logger/LogTopic.cpp
Log levels in maintenance from devel
> releveling logging in maintenance module

- arangod/Aql/QueryCursor.cpp
- arangod/V8Server/v8-voccursor.cpp
- tests/js/common/shell/shell-transactions.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/3949/
> Fix stream cursor bug

- Documentation/Books/Manual/Architecture/SingleInstanceVsCluster.md
- Documentation/Books/Manual/Deployment/Modes.md
- Documentation/Books/Manual/Deployment/README.md
- Documentation/Books/Manual/SUMMARY.md
Forward port some minor changes made in 3.4 PR https://github.com/arangodb/arangodb/pull/7849
Also change link label once more (no need to backport).
> Doc - Single Instance vs. Cluster (update)

- arangod/Aql/AqlItemMatrix.cpp
- arangod/Aql/ExecutionNode.cpp
- arangod/Aql/ReturnExecutor.cpp
- arangod/Aql/ReturnExecutor.h
- tests/Aql/ReturnExecutorTest.cpp
- tests/js/server/aql/aql-optimizer-query-stats.js
> fix full count and failure tests

- arangod/Aql/grammar.cpp
- arangod/Aql/grammar.h
- arangod/Aql/grammar.hpp
- arangod/Aql/grammar.y
- lib/Basics/HashSet.h
- tests/Basics/HashSetTest.cpp
- tests/IResearch/IResearchFeature-test.cpp
- fixes move ctor & move assignment of HashSet
- fixes memleaks in IResearchFeature test
- fixes use-after-free in IResearchFeature test
> Bug fix/fix catch issues

- js/common/modules/@arangodb/aql/explainer.js
This allows showing all execution plans:
```
db._explain(query, bind, { allPlans: true });
```
> allow explaining with allPlans: true

- CHANGELOG
> Changelog 3.4.2

- arangod/RestHandler/RestQueryHandler.cpp
- arangod/Transaction/Methods.cpp
- arangosh/Shell/ClientFeature.h
- arangosh/Shell/V8ClientConnection.cpp
- arangosh/Shell/V8ClientConnection.h
- js/client/client.js
Port of https://github.com/arangodb/arangodb/pull/8012 to devel
> Bug fix/misc issues

- arangod/RocksDBEngine/RocksDBReplicationContext.cpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/4067/
> reduce timeout for write-lock

- Documentation/Books/AQL/Functions/Miscellaneous.md
Backport of https://github.com/arangodb/arangodb/pull/8003
> Doc - Improve description of CHECK_DOCUMENT() AQL function (3.4)

- tests/CMakeLists.txt
> modify cmake to support fakeit dtor mock

- Documentation/Books/Manual/Deployment/ActiveFailover/UsingTheStarter.md
- Documentation/Books/Manual/Deployment/Cluster/UsingTheStarter.md
- Documentation/Books/Manual/Deployment/Kubernetes/DeploymentResource.md
- Documentation/Books/Manual/Deployment/SingleInstance/UsingTheStarter.md
- Documentation/Books/Manual/Tutorials/Starter/README.md
http://jenkins01.arangodb.biz:8080/view/Documentation/job/arangodb-documentation/288/
http://web01.arangodb.biz/documentation-3.4/sync-2019-01-30/Manual/
> Doc: sync external repos - 2019-01-30

- Documentation/Books/Manual/Deployment/ActiveFailover/UsingTheStarter.md
- Documentation/Books/Manual/Deployment/Cluster/UsingTheStarter.md
- Documentation/Books/Manual/Deployment/Kubernetes/DeploymentResource.md
- Documentation/Books/Manual/Deployment/SingleInstance/UsingTheStarter.md
- Documentation/Books/Manual/Tutorials/Starter/README.md
> Doc - Sync external repos (#8063)

- Documentation/Books/Manual/Programs/Arangodump/Maskings.md
- Documentation/Examples/arangodump.json
- arangosh/Dump/DumpFeature.cpp
- Added missing default values
- More detailed descriptions
- also see https://github.com/arangodb/enterprise/pull/198
> Doc - Maskings - Forward port improvement from 3.3

- arangod/RocksDBEngine/RocksDBBuilderIndex.cpp
- arangod/RocksDBEngine/RocksDBCollection.cpp
- arangod/RocksDBEngine/RocksDBMethods.cpp
- arangod/RocksDBEngine/RocksDBMethods.h
- arangod/RocksDBEngine/RocksDBTransactionState.cpp
- arangod/RocksDBEngine/RocksDBTransactionState.h
- tests/js/server/shell/shell-index-rocksdb.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/4137/
> Fix background indexing 

- CHANGELOG
- Documentation/Books/Manual/Programs/Arangodump/Maskings.md
- Documentation/Examples/arangodump.json
- arangosh/Dump/DumpFeature.cpp
Also see https://github.com/arangodb/enterprise/pull/199
> Doc - Maskings - Forward port improvement from 3.3 (3.4)

- tests/js/server/shell/shell-database-mmfiles-noncluster.js
- tests/js/server/shell/shell-database-rocksdb-noncluster.js
Fix regex in test to deal with https://github.com/arangodb/documents/blob/master/DesignDocuments/04_IMPLEMENTED/Packaging/Versioning.md
> Update shell-database-{rocksdb|mmfiles}-noncluster.js 3.4

- Documentation/Books/Manual/Downgrading/README.md
Needs backport to 3.4 after review
> Doc - More downgrade options (solving challenging situations)

- arangod/RocksDBEngine/RocksDBCollection.cpp
- arangod/V8Server/v8-voccursor.cpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/4201/
> fix error handling in V8Cursor::New

- arangod/RocksDBEngine/RocksDBBuilderIndex.cpp
- tests/js/server/recovery/indexes-inbackground-rocksdb.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/4198/
> test for broken indexes

- Documentation/Books/Manual/DataModeling/Concepts.md
> Doc - Fixes link

- CHANGELOG
- arangod/Aql/Expression.h
- arangod/Aql/OptimizerRules.cpp
- tests/js/server/aql/aql-optimizer-rule-simplify-conditions.js
Should fix https://github.com/arangodb/arangodb/issues/8108
> fixed issue #8108

- Documentation/Books/Manual/Deployment/ProductionChecklist.md
forward port from 3.4 https://github.com/arangodb/arangodb/pull/7991
> Doc - Production Checklist Improvements

- Documentation/Books/AQL/Graphs/Traversals.md
- Documentation/Books/AQL/Views/ArangoSearch/README.md
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/2957/
> [3.4] Note that ArangoSearch views cannot be used as edge collections in traversals

- Documentation/Books/AQL/Graphs/Traversals.md
- Documentation/Books/AQL/Views/ArangoSearch/README.md
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/2955/
> Note that ArangoSearch views cannot be used as edge collections in traversals

- arangod/Scheduler/SchedulerFeature.cpp
- arangod/Scheduler/SupervisedScheduler.cpp
- arangod/Scheduler/SupervisedScheduler.h
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/4219/
> Fix shutdown race in supervised scheduler

- arangod/RestHandler/RestRepairHandler.cpp
- arangod/Scheduler/SupervisedScheduler.h
- arangod/VocBase/Methods/Databases.cpp
This contains the changes from https://github.com/arangodb/arangodb/pull/8119
Our jenkins is not able to test PRs from other remotes than arangodb/arangodb.
> Bug fix/m0ppers fix warnings

- arangod/VocBase/KeyGenerator.cpp
These locks are not really significant (performance wise), but this is a low hanging fruit.
> Make single server key generators lockfree.

- arangod/Cluster/ClusterMethods.cpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/4261/
> Properly translate cluster comm errors

- CHANGELOG
- js/common/modules/@arangodb/common.js
This is a port of #8141 for 3.4.
> Fix isAqlQuery with empty query (3.4)

- Documentation/DocuBlocks/Rest/Cursors/post_api_cursor.md
> Doc - Added default ttl for cursor

- Documentation/DocuBlocks/Rest/Cursors/post_api_cursor.md
> Doc - Added default ttl for cursor (3.4)

- arangod/RocksDBEngine/RocksDBCollection.cpp
- arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
- arangod/RocksDBEngine/RocksDBFulltextIndex.cpp
- arangod/RocksDBEngine/RocksDBGeoIndex.cpp
- arangod/RocksDBEngine/RocksDBMethods.cpp
- arangod/RocksDBEngine/RocksDBMethods.h
- arangod/RocksDBEngine/RocksDBVPackIndex.cpp
Backport of some PutUntracked operations from devel to 3.4
> use PutUntracked

- arangod/Aql/CalculationExecutor.cpp
- arangod/Aql/CalculationExecutor.h
- arangod/Aql/ReturnExecutor.cpp
- arangod/Aql/ReturnExecutor.h
- tests/Aql/ReturnExecutorTest.cpp
This inlines straight forward AQL itemBlocks for performance
> Inline Return and CalculationExecutor. Also avoid an unnecessary copy.

- arangod/Aql/AllRowsFetcher.cpp
- arangod/Aql/AllRowsFetcher.h
- arangod/Aql/ConstFetcher.h
- arangod/Aql/ExecutionBlockImpl.cpp
- arangod/Aql/SingleRowFetcher.h
- tests/Aql/AllRowsFetcherTest.cpp
Jenkins:
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/3077/
> SortExecutor optimization for few lines from upstream

- arangod/RestHandler/RestReplicationHandler.cpp
Improve error messages in case restore encounters invalid JSON input data
> improve error messages when restoring from invalid JSON data

- Documentation/Books/AQL/ExecutionAndPerformance/ExplainingQueries.md
- Documentation/Books/AQL/Operators.md
- Documentation/Books/Manual/Highlights.md
Backport of https://github.com/arangodb/arangodb/pull/7972
http://jenkins01.arangodb.biz:8080/view/Documentation/job/arangodb-documentation/310/
> Doc - Complete the highlights page (#7972)

- Documentation/Books/Manual/Deployment/MigratingSingleInstanceCluster.md
Ref:
- https://github.com/arangodb/planning/issues/3664#issuecomment-466370787
http://jenkins01.arangodb.biz:8080/view/Documentation/job/arangodb-documentation/318/
Preview:
- http://web01.arangodb.biz/documentation/migrating2cluster-hintboxes/Manual/Deployment/MigratingSingleInstanceCluster.html
> Doc - Improve hint boxes on page MigratingSingleInstanceCluster.md

- Documentation/Books/Manual/Installation/Windows.md
> Doc - Windows Installation - Use code tags and env vars (#8232)

- arangod/Cluster/ClusterInfo.cpp
> issue 521.1: do not mark loadPlan as valid unless all instances were created successfully

- arangod/IResearch/IResearchLinkHelper.cpp
- tests/CMakeLists.txt
- tests/IResearch/IResearchIndex-test.cpp
- tests/IResearch/IResearchLinkHelper-test.cpp
- tests/IResearch/IResearchQueryAnd-test.cpp
- tests/IResearch/IResearchQueryBooleanTerm-test.cpp
- tests/IResearch/IResearchQueryComplexBoolean-test.cpp
- tests/IResearch/IResearchQueryExists-test.cpp
- tests/IResearch/IResearchQueryIn-test.cpp
- tests/IResearch/IResearchQueryJoin-test.cpp
- tests/IResearch/IResearchQueryNullTerm-test.cpp
- tests/IResearch/IResearchQueryNumericTerm-test.cpp
- tests/IResearch/IResearchQueryOr-test.cpp
- tests/IResearch/IResearchQueryPhrase-test.cpp
- tests/IResearch/IResearchQueryTraversal-test.cpp
> issue 519.1: fix typo, add tests, supress extraneous test log output

- arangod/Cluster/HeartbeatThread.cpp
- arangod/MMFiles/MMFilesRestReplicationHandler.cpp
- arangod/MMFiles/MMFilesWalAccess.cpp
- arangod/MMFiles/mmfiles-replication-dump.cpp
- arangod/Replication/DatabaseInitialSyncer.cpp
- arangod/Replication/GlobalInitialSyncer.cpp
- arangod/Replication/ReplicationApplierConfiguration.cpp
- arangod/Replication/ReplicationApplierConfiguration.h
- arangod/Replication/TailingSyncer.cpp
- arangod/Replication/common-defines.cpp
- arangod/Replication/common-defines.h
- arangod/RestHandler/RestWalAccessHandler.cpp
- arangod/RocksDBEngine/RocksDBReplicationContext.cpp
- arangod/RocksDBEngine/RocksDBReplicationContext.h
- arangod/RocksDBEngine/RocksDBReplicationTailing.cpp
- arangod/RocksDBEngine/RocksDBRestReplicationHandler.cpp
- arangod/StorageEngine/WalAccess.cpp
- arangod/StorageEngine/WalAccess.h
- js/server/modules/@arangodb/foxx/queues/manager.js
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-linux/4423/
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/3165/
> Sync Foxx Queues

- CHANGELOG
- arangod/Pregel/PregelFeature.cpp
- arangod/V8Server/v8-collection.cpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/4441/
> Pregel Nullptr checks

- CHANGELOG
- arangosh/Shell/V8ClientConnection.cpp
see http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/3177/
(needs to be cherry-pick into devel  as well if jenkins is green)
> Bug fix 3.4/fix reconnect with jwt

- CHANGELOG
- arangosh/Shell/V8ClientConnection.cpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/3186/
> fix reconnect with jwt (#8260)

- arangod/IResearch/IResearchViewNode.cpp
- tests/IResearch/IResearchQueryJoin-test.cpp
- tests/js/common/aql/aql-view-arangosearch-cluster.js
- tests/js/common/aql/aql-view-arangosearch-noncluster.js
> Fix bug #8213

- Documentation/Books/Manual/Administration/Cluster/README.md
- Documentation/Books/Manual/DataModeling/Collections/DatabaseMethods.md
- Documentation/Books/Manual/Graphs/Pregel/README.md
- Documentation/Books/Manual/ReleaseNotes/NewFeatures31.md
- Documentation/Books/Manual/ReleaseNotes/NewFeatures32.md
- Documentation/Books/Manual/ReleaseNotes/UpgradingChanges34.md
- Documentation/DocuBlocks/Rest/Collections/post_api_collection.md
- Documentation/DocuBlocks/Rest/Graph/1_structs.md
- Documentation/DocuBlocks/Rest/Graph/general_graph_list_http_examples.md
Backport of #8014
http://jenkins01.arangodb.biz:8080/view/Documentation/job/arangodb-documentation/336/
> Doc - Use proper terms for editions (esp. shardingStrategy) (#8014)

- Documentation/Books/Manual/Architecture/DeploymentModes/ActiveFailover/Architecture.md
Internal Ref:
- https://github.com/arangodb/planning/issues/3676
http://jenkins01.arangodb.biz:8080/view/Documentation/job/arangodb-documentation/339/
Adding simran as doc lead. Simon as AF dev. Frank and MaxN as eng. leads
Hoping for approval from Simran and Simon at least
Thanks,
Preview:
- http://web01.arangodb.biz/documentation/af-arch-impr/Manual/Architecture/DeploymentModes/ActiveFailover/Architecture.html
> Doc - AF improvements

- Documentation/Books/Manual/Architecture/DeploymentModes/ActiveFailover/Architecture.md
backport from devel
Build:
- http://jenkins01.arangodb.biz:8080/job/arangodb-documentation/341/
> Doc - AF improvements 

- Documentation/Books/Manual/Architecture/DeploymentModes/Cluster/Architecture.md
- Documentation/Books/stash/ClusterArchitecture.md
Backport from devel
Build:
- http://jenkins01.arangodb.biz:8080/job/arangodb-documentation/342/
> Doc - Cluster Architecture Improvements 

- Documentation/Books/Manual/BackupRestore/README.md
- Documentation/Books/Manual/Programs/Arangodump/Examples.md
- Documentation/Books/Manual/Programs/Arangorestore/Examples.md
- Documentation/Books/Manual/Programs/Arangorestore/FastClusterRestore.md
- Documentation/Books/Manual/Programs/Arangorestore/README.md
- Documentation/Books/Manual/SUMMARY.md
backport from devel - there was a strange conflict that I resolved just copy / pasting the current file from devel in this branch, and only after applying the cherry pick
the file from devel was the more recent anyway - simran FYI if you want to understand more
>  Doc - Fast Cluster Restore Procedure

- Documentation/Books/Manual/Deployment/Kubernetes/Drain.md
- Documentation/Books/Manual/Tutorials/Kubernetes/README.md
Copied from kube-arangodb repo
http://jenkins01.arangodb.biz:8080/view/Documentation/job/arangodb-documentation/345/
> Doc - Update Kubernetes (Tutorial/Drain)

- Documentation/Books/Manual/Deployment/Cloud/Azure.md
Ingo's feedback 
Internal Ref:
- https://github.com/arangodb/planning/issues/3108
> Doc - Update Azure.md

- Documentation/Books/Manual/Deployment/Kubernetes/Drain.md
- Documentation/Books/Manual/Tutorials/Kubernetes/README.md
Backport of #8295
http://jenkins01.arangodb.biz:8080/view/Documentation/job/arangodb-documentation/351/
> Doc - Update Kubernetes (Tutorial/Drain) (#8295)

- Documentation/Books/Manual/Deployment/Cloud/Azure.md
Backport of #8149 
http://jenkins01.arangodb.biz:8080/view/Documentation/job/arangodb-documentation/349/
> Doc - Azure Deployment: Make statement clearer (#8149)

- js/client/modules/@arangodb/process-utils.js
since they wouldn't deliver good values anymore
> when in activefailover mode detect leader changes, and abort tests

- arangod/Cluster/HeartbeatThread.cpp
- arangod/MMFiles/MMFilesPrimaryIndex.cpp
- lib/Basics/AssocMulti.h
- lib/Basics/AssocMultiHelpers.h
- lib/Basics/AssocUnique.h
- lib/Basics/AssocUniqueHelpers.h
- lib/Basics/IndexBucket.h
Cleanup of some stuff that was not used
> remove some unused stuff

- Documentation/Books/Manual/Administration/MasterSlave/DatabaseSetup.md
- Documentation/Books/Manual/Administration/MasterSlave/ReplicationApplier.md
- Documentation/Books/Manual/Administration/MasterSlave/ServerLevelSetup.md
This should make documentation compile again
> Doc - Fix ReplicationApplier.md hint box

- arangod/MMFiles/MMFilesEngine.cpp
- arangod/RocksDBEngine/RocksDBEngine.cpp
> issue 527.1: ensure the cause of the failure is reported to the user

- arangod/Agency/FailedFollower.cpp
- arangod/Agency/FailedLeader.cpp
Check if transaction failed before accessing the result.
> [3.4] Agency Failed leader crash

- arangod/RestHandler/RestHotBackupHandler.cpp
- arangod/RocksDBEngine/RocksDBHotBackup.cpp
- arangod/RocksDBEngine/RocksDBHotBackup.h
- tests/RocksDBEngine/HotBackupTest.cpp
This is incremental to feature-3.4/hotbackup-rest.
This code updates the hot backup restore command to use Max's new restartAction functor.
> Feature-3.4:  Hotbackup restore supporting Max new restartAction.

- arangod/CMakeLists.txt
- arangod/GeneralServer/GeneralServerFeature.cpp
- arangod/RestHandler/RestHotBackupHandler.cpp
- arangod/RestHandler/RestHotBackupHandler.h
- arangod/RocksDBEngine/CMakeLists.txt
- arangod/RocksDBEngine/RocksDBCollection.cpp
- arangod/RocksDBEngine/RocksDBEngine.cpp
- arangod/RocksDBEngine/RocksDBEngine.h
- arangod/RocksDBEngine/RocksDBEventListener.cpp
- arangod/RocksDBEngine/RocksDBEventListener.h
- arangod/RocksDBEngine/RocksDBHotBackup.cpp
- arangod/RocksDBEngine/RocksDBHotBackup.h
- arangod/RocksDBEngine/RocksDBHotBackupCoord.h
- js/common/bootstrap/errors.js
- lib/Basics/FileUtils.cpp
- lib/Basics/FileUtils.h
- lib/Basics/errors.dat
- lib/Basics/files.cpp
- lib/Basics/files.h
- lib/Basics/voc-errors.cpp
- lib/Basics/voc-errors.h
- tests/Basics/files-test.cpp
- tests/CMakeLists.txt
- tests/Maintenance/MaintenanceFeatureTest.cpp
- tests/Maintenance/MaintenanceRestHandlerTest.cpp
- tests/RocksDBEngine/HotBackupTest.cpp
- tests/RocksDBEngine/ShaEventListener.cpp
This replaces branch feature-3.4/hotbackup-1.  The previous branch also contained extensive changes to restart rocksdb.  This branch removes those changes.
This branch DOES NOT support the new restart code.  That will arrive in an independent (and smaller) PR.
> Feature-3.4:  Hot backup rest handler for community edition

- Documentation/Books/AQL/Extending/Functions.md
- Documentation/Books/AQL/Extending/README.md
Backport of #8340 
http://jenkins01.arangodb.biz:8080/view/Documentation/job/arangodb-documentation/365/
> Doc - AQL UDFs: Manage on coordinator, improve warning (#8340)

- Documentation/Books/AQL/Functions/Geo.md
- Documentation/Books/AQL/Graphs/Traversals.md
- Documentation/Books/Manual/Indexing/README.md
- Documentation/Examples/GRAPHTRAV_01_create_graph.generated
- Documentation/Examples/GRAPHTRAV_04_traverse_4a.generated
- Documentation/Examples/GRAPHTRAV_04_traverse_4b.generated
- Documentation/Examples/GRAPHTRAV_05_traverse_5a.generated
- Documentation/Examples/GRAPHTRAV_05_traverse_5b.generated
- Documentation/Examples/GRAPHTRAV_06_traverse_6a.generated
- Documentation/Examples/GRAPHTRAV_06_traverse_6b.generated
- Documentation/Examples/GRAPHTRAV_06_traverse_6c.generated
- Documentation/Examples/GRAPHTRAV_07_traverse_7.generated
- Documentation/Examples/GRAPHTRAV_07_traverse_8.generated
- Documentation/Examples/GRAPHTRAV_graphFilterCombine.generated
- Documentation/Examples/GRAPHTRAV_graphFilterEdges.generated
- Documentation/Examples/GRAPHTRAV_graphFilterEntirePath.generated
- Documentation/Examples/GRAPHTRAV_graphFilterPathAnyEdge.generated
- Documentation/Examples/GRAPHTRAV_graphFilterVertices.generated
- Documentation/Examples/GRAPHTRAV_graphPruneCollection.generated
- Documentation/Examples/GRAPHTRAV_graphPruneEdges.generated
- Documentation/Examples/GRAPHTRAV_graphPruneVertices.generated
- Documentation/Examples/aqlGeoLineString_1.generated
- Documentation/Examples/aqlGeoMultiLineString_1.generated
- Documentation/Examples/aqlGeoMultiPoint_1.generated
- Documentation/Examples/aqlGeoMultiPolygon_1.generated
- Documentation/Examples/aqlGeoPolygon_1.generated
- Documentation/Examples/aqlGeoPolygon_2.generated
- Documentation/Examples/arangoinspect.json
- Documentation/Examples/arangosh.json
Backport of #8336
http://jenkins01.arangodb.biz:8080/view/Documentation/job/arangodb-documentation/368/
> Doc - Fix/improve graph traversal/background indexing pages, console history and examples/options (#8336)

- Documentation/Books/AQL/book.json
- Documentation/Books/Cookbook/book.json
- Documentation/Books/HTTP/book.json
- Documentation/Books/Manual/book.json
**Please do not merge for now**
---
Internal ref:
- https://github.com/arangodb/planning/issues/3339
Depends on: https://github.com/arangodb/arangodb/pull/7737
> Doc - EOL Note for 3.2

- Documentation/Books/AQL/Functions/Array.md
- Documentation/Books/AQL/Functions/Document.md
- Documentation/Books/AQL/Functions/Miscellaneous.md
- Documentation/Books/AQL/Functions/Numeric.md
- Documentation/Books/AQL/Functions/String.md
- Documentation/Books/AQL/Functions/TypeCast.md
- Documentation/Books/AQL/SUMMARY.md
Backport of #8242
http://jenkins01.arangodb.biz:8080/view/Documentation/job/arangodb-documentation/372/
> Doc - Add cross-refs & better AQL function descriptions (#8242)

- js/client/modules/@arangodb/testsuites/replication.js
- tests/js/server/replication/replication-aql.js
- tests/js/server/replication/replication-fuzz.js
- tests/js/server/replication/replication-ongoing.js
- tests/js/server/replication/replication-random.js
- tests/js/server/replication/replication-static.js
Use `requireFromPresent` and barriers in more cases.
> use requireFromPresent and barriers in more cases

- Documentation/Books/AQL/book.json
- Documentation/Books/Cookbook/book.json
- Documentation/Books/HTTP/book.json
- Documentation/Books/Manual/book.json
- arangodb-outdated plugin extended to support setting an EoL date
- containers for old and new jenkins need to be updated
> Doc - Set EoL date for 3.2

- Documentation/Books/Drivers/JS/Reference/Collection/DocumentCollection.md
- Documentation/Books/Drivers/JS/Reference/Collection/EdgeCollection.md
- Documentation/Books/Drivers/SparkConnector/Reference/Java.md
- Documentation/Books/Manual/Programs/Starter/Options.md
- Documentation/Books/Manual/SUMMARY.md
- Documentation/Books/Manual/Tutorials/Kubernetes/EKS.md
> Doc - Sync external repos 2019-03-13 (devel)

- Documentation/Books/Drivers/JS/Reference/Collection/DocumentCollection.md
- Documentation/Books/Drivers/JS/Reference/Collection/EdgeCollection.md
- Documentation/Books/Drivers/SparkConnector/Reference/Java.md
- Documentation/Books/Manual/Programs/Starter/Options.md
- Documentation/Books/Manual/Tutorials/Kubernetes/EKS.md
> Doc - Sync external repos 2019-03-13 (3.4)

- 3rdParty/iresearch/core/formats/formats_burst_trie.cpp
> [3.4] bug-fix/internal-issue-#528

- CHANGELOG
- Documentation/Books/Manual/Programs/Arangod/Log.md
- lib/Logger/LogAppenderFile.cpp
- lib/Logger/LogAppenderFile.h
- lib/Logger/LoggerFeature.cpp
- lib/Logger/LoggerFeature.h
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/3515/
> added options log.file-mode and log.file-group

- Documentation/Books/Manual/ReleaseNotes/NewFeatures35.md
Fixes duplicate anchor doc build error
> Doc - Fix Client Tools section in NewFeatures35.md

- Documentation/Books/Manual/Administration/Cluster/README.md
- Documentation/Books/Manual/Deployment/Kubernetes/Drain.md
- Documentation/DocuBlocks/Rest/Cluster/get_cluster_health.md
Sync of https://github.com/arangodb/kube-arangodb/pull/355
http://jenkins01.arangodb.biz:8080/view/Documentation/job/arangodb-documentation/377/
> Doc - Make cleanOutServer step mandatory in drain documentation

- Documentation/Books/Manual/Monitoring/LogLevels.md
- Documentation/Books/Manual/Monitoring/README.md
- Documentation/Books/Manual/Programs/Arangod/Log.md
- Documentation/Books/Manual/SUMMARY.md
Ref: https://github.com/arangodb/documents/pull/47
- http://jenkins01.arangodb.biz:8080/view/Documentation/job/arangodb-documentation/378/
- http://web01.arangodb.biz/documentation/log-levels/Manual/Monitoring/LogLevels.html
> Doc - Add log level description under Monitoring

- Documentation/Books/Manual/Monitoring/LogLevels.md
- Documentation/Books/Manual/Monitoring/README.md
- Documentation/Books/Manual/Programs/Arangod/Log.md
- Documentation/Books/Manual/SUMMARY.md
Backport of #8461 
http://jenkins01.arangodb.biz:8080/view/Documentation/job/arangodb-documentation/380/
> Add log level description under Monitoring (#8461)

- tests/js/common/shell/shell-statement.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/3098/
> Add testTemplateStringBuilderEmptyInlines test for https://github.com/arangodb/arangodb/pull/8142

- js/client/modules/@arangodb/testsuites/upgrade-data.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/3542/
> Fix upgrade_data tests (3.4)

- js/client/modules/@arangodb/testsuites/upgrade-data.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/3541/
> Fix upgrade_data tests

- Documentation/Books/Manual/Administration/Cluster/README.md
- Documentation/Books/Manual/Deployment/Kubernetes/Drain.md
- Documentation/DocuBlocks/Rest/Cluster/get_cluster_health.md
Backport of #8462 
http://jenkins01.arangodb.biz:8080/view/Documentation/job/arangodb-documentation/381/
>  Doc - Make cleanOutServer step mandatory in drain documentation (#8462)

- CHANGELOG
- arangod/Agency/Supervision.cpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/3510/
> [3.3] followers can get stuck in supervision runs

- arangod/GeneralServer/AuthenticationFeature.cpp
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/2768/
> Bug fix/jwt secret file logging

- Documentation/Books/Manual/Programs/Arangod/Log.md
- lib/Logger/LogAppenderFile.cpp
- lib/Logger/LogAppenderFile.h
- lib/Logger/LoggerFeature.cpp
- lib/Logger/LoggerFeature.h
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/3519/
> added --log.file-mode and --log.file-group

- js/client/modules/@arangodb/testing.js
- tests/OskarTestSuitesBlackList
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/3556/
> Add bucket number info to testfailures output (3.4)

- tests/js/common/shell/shell-statement.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/3099/
> Add testTemplateStringBuilderEmptyInlines test for https://github.com/arangodb/arangodb/pull/8141

- js/client/modules/@arangodb/testing.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/3551/
> Add bucket number info to testfailures output

- utils/generateExamples.sh
> Doc - Dump program options only if on Enterprise Edition (3.4)

- .gitignore
- UnitTests/OskarTestSuitesBlackList
- js/client/modules/@arangodb/test-utils.js
- js/client/modules/@arangodb/testing.js
- js/client/modules/@arangodb/testsuites/upgrade-data.js
- js/server/tests/upgrade-data/upgrade-data-basics-msv3.2.1.js
http://jenkins01.arangodb.biz:8080/view/3.3/job/arangodb-3.3-linux-matrix/392/
http://jenkins01.arangodb.biz:8080/view/3.3/job/arangodb-3.3-windows-matrix/360/
http://jenkins01.arangodb.biz:8080/view/3.3/job/arangodb-3.3-mac-matrix/248/
> Add upgrade_data_<VER>_<STORAGE> tests execution possibility

- arangod/Aql/Condition.cpp
- arangod/Aql/Condition.h
- arangod/IResearch/IResearchFeature.cpp
- arangod/IResearch/IResearchFilterFactory.cpp
- arangod/IResearch/IResearchViewOptimizerRules.cpp
- tests/CMakeLists.txt
- tests/IResearch/IResearchFilterBoolean-test.cpp
- tests/IResearch/IResearchFilterFunction-test.cpp
- tests/IResearch/IResearchQueryInRange-test.cpp
- tests/IResearch/IResearchQueryOptimization-test.cpp
- tests/IResearch/common.cpp
- tests/IResearch/common.h
- tests/js/common/aql/aql-view-arangosearch-cluster.js
- tests/js/common/aql/aql-view-arangosearch-noncluster.js
> [3.4] bug-fix/issue-#8294

- Documentation/Examples/arangod.json
A new option `--query.smart-joins` was implemented in #8440
> Add smart-joins to program option JSON

- arangod/VocBase/Methods/Indexes.cpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/4928/
> Fix edge index selectivity

- arangod/Aql/RemoteExecutor.cpp
- arangod/Aql/RemoteExecutor.h
Jenkins:
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/3620/
> Fix a race in RemoteExecutor

- Documentation/Examples/arangod.json
Introduced in #8492, but missing in option dump
> Doc - Add RocksDB IOPS program options 

- scripts/startLocalCluster.sh
> Revert change in scripts/startLocalCluster.sh

- arangod/RocksDBEngine/RocksDBCollection.cpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/4989/
> Fix asan error in truncate

- arangod/RocksDBEngine/RocksDBCollection.cpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/4992/
> Bug fix 3.4/rocksdb truncate asan

- arangod/Aql/ModificationBlocks.cpp
- arangod/Aql/ModificationBlocks.h
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/3598/
> better aql error message

- arangod/Indexes/Index.cpp
- arangod/Indexes/IndexFactory.cpp
- lib/Basics/Result.h
> Improved index error messages.

- js/apps/system/_admin/aardvark/APP/frontend/js/views/collectionsView.js
WebUI collection creation broken in community edition.
> Dont access #smart-join-attribute in community edition.

- arangod/RocksDBEngine/CMakeLists.txt
- arangod/RocksDBEngine/RocksDBBackgroundErrorListener.cpp
- arangod/RocksDBEngine/RocksDBBackgroundErrorListener.h
- arangod/RocksDBEngine/RocksDBEngine.cpp
Backport of https://github.com/arangodb/arangodb/pull/8535
> Add RocksDB background error listener.

- arangod/Aql/AllRowsFetcher.cpp
> Fixed sequence point warning in all rows fetcher

- arangod/Aql/ModificationExecutorTraits.cpp
> stop after receiving first error message

- js/client/modules/@arangodb/testsuites/endpoints.js
> use dummyDir for unix socket files

- CHANGELOG
- arangod/Aql/ModificationBlocks.cpp
- tests/js/server/aql/aql-modify.js
Fix original PR and add test
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/3716/
> Feature 3.4/better aql error message

- arangod/Cluster/DBServerAgencySync.cpp
- arangod/VocBase/LogicalCollection.cpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/5081/
> Hide in progress indexes

- UnitTests/OskarTestSuitesBlackList
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/3735/
> Blacklist dump_multiple suite in 3.2

- UnitTests/OskarTestSuitesBlackList
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/3733/
> Blacklist dump_multiple suite in 3.4

- UnitTests/OskarTestSuitesBlackList
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/3734/
> Blacklist dump_multiple suite in 3.3

- js/server/modules/@arangodb/foxx/router/request.js
- tests/js/client/authentication/foxx-arango-auth-spec.js
same as https://github.com/arangodb/arangodb/pull/8352
> Bug fix 3.4/foxx auth req object

- js/client/tests/authentication/foxx-arango-auth-spec.js
- js/server/modules/@arangodb/foxx/router/request.js
same as: https://github.com/arangodb/arangodb/pull/8352
> Bug fix 3.3/foxx auth req object

- README_maintainers.md
- lib/V8/v8-utils.cpp
- utils/generateLogIds.py
> fix generateLogIds.py

- Documentation/Books/Manual/BackupRestore/README.md
> small typo

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/views/shardsView.js
Same as: https://github.com/arangodb/arangodb/pull/8583
> Bug fix 3.4/improve shards ui

- Documentation/Books/Manual/BackupRestore/README.md
> Doc - Backup and Restore - Small typo

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
Same as: https://github.com/arangodb/arangodb/pull/8579
https://github.com/arangodb/planning/issues/3789
> Bug fix 3.4/custom query names

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/views/loginView.js
Same as: https://github.com/arangodb/arangodb/pull/8590
> Bug fix 3.4/ui database dropdown sorting

- Documentation/Examples/arangobench.json
- Documentation/Examples/arangod.json
- Documentation/Examples/arangodump.json
- Documentation/Examples/arangoexport.json
- Documentation/Examples/arangoimport.json
- Documentation/Examples/arangoinspect.json
- Documentation/Examples/arangorestore.json
- Documentation/Examples/arangosh.json
- `log.ids`
- `query.smart-joins`
- `rocksdb.allow-fallocate`
- `rocksdb.limit-open-files-at-startup`
- `rocksdb.recycle-log-file-num`
- `rocksdb.wal-archive-size-limit`
- `all-databases`
> Doc - Update program option dumps 2019-03-28

- tests/Aql/ShortestPathExecutorTest.cpp
SingleRowFetcherHelper has its own AqlItemBlockManager. So the OutputAqlItemRow can hold an InputAqlItemRow referencing a block allocated with this manager and must thus be destroyed before the SingleRowFetcherHelper.
> Fix stack-use-after-scope in ShortestPathExecutorTest

- lib/Basics/Thread.cpp
> [3.3] Fix bug in thread creation failure handling.

- CHANGELOG
- arangod/Graph/GraphOperations.cpp
- arangod/RestHandler/RestGraphHandler.cpp
Internal Ref:
- https://github.com/arangodb/planning/issues/3815
> fixed smg collections within the transaction, added gharial decoding

- CHANGELOG
- arangod/Graph/GraphOperations.cpp
- arangod/RestHandler/RestGraphHandler.cpp
same as https://github.com/arangodb/arangodb/pull/8621
> Bug fix/gharial rm vertex smart fix

- js/client/modules/@arangodb/process-utils.js
- js/client/modules/@arangodb/test-utils.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/3842/
> Backport testing improvement from devel 29.03.2019

- js/client/modules/@arangodb/test-utils.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/3863/
> Try 2700s timeout for server tests

- arangod/ClusterEngine/ClusterTransactionState.cpp
- arangod/MMFiles/MMFilesTransactionState.cpp
- arangod/RestHandler/RestHotBackupHandler.h
- arangod/RocksDBEngine/RocksDBEngine.cpp
- arangod/RocksDBEngine/RocksDBEventListener.cpp
- arangod/RocksDBEngine/RocksDBEventListener.h
- arangod/RocksDBEngine/RocksDBTransactionManager.h
- arangod/RocksDBEngine/RocksDBTransactionState.cpp
- arangod/StorageEngine/TransactionState.cpp
- arangod/StorageEngine/TransactionState.h
- arangod/Transaction/Context.cpp
- arangod/Transaction/Context.h
- arangod/Transaction/Methods.cpp
- lib/Basics/ReadWriteLock.cpp
This branch contains TODO items that were the result of PR#8615.
The initial check-in does NOT contain code to address the RocksDBTransactionManager.h changes.
> Feature 3.4:  Address TODO items suggested by Jan

- arangod/Aql/Collection.cpp
- arangod/Aql/Collection.h
- arangod/Aql/OptimizerRules.cpp
Corresponding enterprise PR: https://github.com/arangodb/enterprise/pull/234
> optimize lookups by shard key for smart vertex collections

- arangod/RocksDBEngine/RocksDBCollectionMeta.cpp
- arangod/RocksDBEngine/RocksDBCollectionMeta.h
- arangod/RocksDBEngine/RocksDBCuckooIndexEstimator.h
- arangod/RocksDBEngine/RocksDBSettingsManager.cpp
- tests/RocksDBEngine/IndexEstimatorTest.cpp
> Fix RocksDB recovery ticks

- arangod/Transaction/Methods.cpp
- tests/js/server/aql/aql-error-messages.js
- tests/js/server/aql/aql-modify.js
Don't absorb error messages somewhere en route, but pass them on to end users.
> finally fix AQL error messages in all contexts, so that they are usable

- CHANGELOG
- arangod/Graph/BreadthFirstEnumerator.cpp
- arangod/Graph/NeighborsEnumerator.cpp
- arangod/Graph/PathEnumerator.cpp
Related enterprise repository PR: https://github.com/arangodb/enterprise/pull/242
> Bug fix 3.4/fix prune memleak

- arangod/Pregel/Conductor.cpp
- arangod/Pregel/Worker.cpp
- arangod/Replication/GlobalInitialSyncer.h
- arangod/Replication/InitialSyncer.cpp
- arangod/Replication/Syncer.h
- arangod/Scheduler/Scheduler.cpp
- arangod/Scheduler/Scheduler.h
- arangod/Transaction/ManagerFeature.cpp
- arangod/Transaction/ManagerFeature.h
- arangod/VocBase/Methods/Tasks.cpp
> Bug fix/fix scheduler shutdown task assertion

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/views/graphManagementView.js
https://github.com/arangodb/planning/issues/2946
> Bug fix 3.3/auto complete graph ui

- 3rdParty/iresearch/core/formats/formats_burst_trie.cpp
- 3rdParty/iresearch/core/formats/formats_burst_trie.hpp
- 3rdParty/iresearch/core/utils/fst.hpp
- 3rdParty/iresearch/core/utils/fst_string_weight.h
- 3rdParty/iresearch/external/openfst/fst/fst.h
- 3rdParty/iresearch/external/openfst/fst/vector-fst.h
- CHANGELOG
> bug-fix/internal-issue-#536

- 3rdParty/iresearch/core/formats/formats_burst_trie.cpp
> bug-fix/internal-issue-#536.1

- 3rdParty/iresearch/core/formats/formats_burst_trie.cpp
- 3rdParty/iresearch/core/utils/fst.hpp
- 3rdParty/iresearch/core/utils/fst_string_weight.h
- 3rdParty/iresearch/external/openfst/fst/fst.h
- 3rdParty/iresearch/external/openfst/fst/vector-fst.h
> bug-fix-3.4/internal-issue-#536

- js/client/modules/@arangodb/test-utils.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/4038/
> Restore 1800s timeout on server tests

- arangod/Aql/LimitExecutor.cpp
Jenkins:
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/4037/
> Fixed compile warning of false-positive return-type

- arangod/Aql/EngineInfoContainerDBServer.cpp
- arangod/Cluster/ClusterComm.cpp
- arangod/Cluster/ClusterComm.h
- arangod/Pregel/Algos/DMID/DMID.cpp
- arangod/Pregel/Algos/DMID/DMIDMessageFormat.h
- arangod/Pregel/Algos/DMID/VertexSumAggregator.h
- arangod/Pregel/Algos/PageRank.cpp
- arangod/Pregel/CommonFormats.h
- arangod/Pregel/Conductor.cpp
- arangod/Pregel/Conductor.h
- arangod/Pregel/Graph.h
- arangod/Pregel/GraphStore.cpp
- arangod/Pregel/GraphStore.h
- arangod/Pregel/IncomingCache.cpp
- arangod/Pregel/IncomingCache.h
- arangod/Pregel/OutgoingCache.cpp
- arangod/Pregel/Utils.cpp
- arangod/Pregel/Utils.h
- arangod/Pregel/Worker.cpp
- arangod/Pregel/WorkerConfig.cpp
- arangod/Pregel/WorkerConfig.h
- lib/Basics/StringHeap.cpp
- lib/Basics/StringHeap.h
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/5476/
> Pregel fixes 

- arangod/Aql/ShortestPathExecutor.cpp
- arangod/Graph/AttributeWeightShortestPathFinder.cpp
- arangod/Graph/AttributeWeightShortestPathFinder.h
- arangod/Graph/ConstantWeightShortestPathFinder.cpp
- arangod/Graph/ConstantWeightShortestPathFinder.h
- arangod/Graph/ShortestPathFinder.h
- arangod/Graph/ShortestPathOptions.cpp
- arangod/Graph/ShortestPathOptions.h
- tests/Aql/ShortestPathExecutorTest.cpp
- tests/Graph/ConstantWeightShortestPathFinder.cpp
This is a side-effect of the work on #8715
> Add isQueryKilled callback to ShortestPathOptions and use it

- CHANGELOG
- Documentation/Books/Manual/DataModeling/Documents/DocumentMethods.md
- Documentation/Books/Manual/ReleaseNotes/NewFeatures35.md
- js/common/modules/@arangodb/arango-collection-common.js
- js/common/modules/@arangodb/common.js
- tests/js/common/shell/shell-document.js
This adds the long overdue method for turning document keys into document IDs.
> Add collection.documentId method

- arangod/Replication/TailingSyncer.cpp
- js/client/modules/@arangodb/testsuites/replication.js
Should fix spurious errors in replication-fuzz.js
> increase the timeout for more reliable test results

- Documentation/Books/AQL/Functions/Geo.md
- Documentation/Books/Manual/Indexing/Geo.md
Internal ref:
- https://github.com/arangodb/planning/issues/2489
> Doc - Add version info for Geo features added in v3.4.0

- tests/rb/HttpInterface/api-collection-rocksdb-spec.rb
Simpler implementation of https://github.com/arangodb/arangodb/pull/8171
> fix collection unload test

- arangod/Auth/TokenCache.cpp
- lib/V8/v8-utils.cpp
Salvation of the relevant parts of PR https://github.com/arangodb/arangodb/pull/7968
> don't reveal secrets via log or to JavaScript apps

- arangod/Auth/TokenCache.cpp
- lib/V8/v8-utils.cpp
Salvation of the relevant parts of PR https://github.com/arangodb/arangodb/pull/7968
> don't reveal information via logs or to JavaScript apps

- arangod/Graph/AttributeWeightShortestPathFinder.cpp
- arangod/Graph/AttributeWeightShortestPathFinder.h
- arangod/Graph/KShortestPathsFinder.cpp
- arangod/Graph/KShortestPathsFinder.h
- arangod/Graph/ShortestPathPriorityQueue.h
- tests/Basics/priorityqueue-test.cpp
it seems the usages have been correct everywhere (so no leaks) but memory responibility was hard to understand, should now be much simpler.
Jenkins:
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/4084/
> USe smart-pointer in Priority Queue

- arangod/Indexes/IndexIterator.cpp
- arangod/Indexes/IndexIterator.h
- arangod/RocksDBEngine/RocksDBOptimizerRules.cpp
- arangod/Transaction/Methods.h
- arangod/VocBase/LogicalCollection.h
Related enterprise PR: https://github.com/arangodb/enterprise/pull/249
> Bug fix/fix skip inaccessible

- Documentation/Books/AQL/ExecutionAndPerformance/Optimizer.md
> Additional documentation for sort-limit optimization.

- 3rdParty/iresearch/core/analysis/text_token_stream.cpp
> issue 537.1: backport from iresearch upstream: ensure key is cached too

- arangod/IResearch/IResearchLink.cpp
- arangod/IResearch/IResearchLinkMeta.cpp
- arangosh/Restore/RestoreFeature.cpp
- tests/IResearch/IResearchLinkMeta-test.cpp
- tests/js/client/authentication/user-access-right-task-update-view-arangosearch.js
- tests/js/client/authentication/user-access-right-update-view-arangosearch.js
- tests/js/common/aql/aql-view-arangosearch-ddl-cluster.js
- tests/js/common/aql/aql-view-arangosearch-ddl-noncluster.js
- tests/js/server/dump/dump-mmfiles-cluster.js
- tests/js/server/dump/dump-mmfiles.js
- tests/js/server/dump/dump-rocksdb-cluster.js
- tests/js/server/dump/dump-rocksdb.js
> issue 545.1.1: output short analyzer prefixes for user definitions

- Documentation/Books/Manual/Administration/Cluster/README.md
**I am sending in the CLA shortly**
> clustering docs typos

- tests/js/common/aql/aql-view-arangosearch-cluster.inc
- tests/js/common/aql/aql-view-arangosearch-s1r1-cluster.js
- tests/js/common/aql/aql-view-arangosearch-s1r2-cluster.js
- tests/js/common/aql/aql-view-arangosearch-s4r1-cluster.js
- tests/js/common/aql/aql-view-arangosearch-s4r3-cluster.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/4189/
> Fix db object visibility for ArangoSearch tests

- Installation/Jenkins/build.sh
> Bug fix 3.3/dont abort on empty openssl dll

- Documentation/Books/AQL/Tutorial/Join.md
Backport of https://github.com/arangodb/arangodb/pull/8792
> Doc - AQL tutorial: Add FOR loop based joins (#8792)

- Documentation/Books/Manual/Administration/Cluster/README.md
Backport of https://github.com/arangodb/arangodb/pull/8804
> Doc - clustering docs typos (#8804)

- Documentation/Books/Manual/Programs/Arangodump/Examples.md
- Documentation/Books/Manual/Security/Encryption/README.md
> Doc - Small typos

- arangod/Aql/BlockFetcher.cpp
- arangod/Aql/BlockFetcher.h
- arangod/Aql/EnumerateCollectionExecutor.cpp
- arangod/Aql/EnumerateCollectionExecutor.h
- arangod/Aql/ExecutionBlockImpl.cpp
- arangod/Aql/IndexExecutor.cpp
- arangod/Aql/IndexExecutor.h
- arangod/Aql/SubqueryExecutor.cpp
> Added custom initializeCursor implementations for Index and EnumerateCollection

- js/common/modules/jsunity.js
- js/common/modules/jsunity/jsunity.js
exposed to the json report file to be enabled along with the junit xml report files.
> record the times used for the setup/teardown methods of jsunity tests

- arangod/Aql/HashedCollectExecutor.cpp
- arangod/Aql/HashedCollectExecutor.h
Jenkins:
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/4230/
> Do less copying in HashedCollect

- lib/ApplicationFeatures/EnvironmentFeature.cpp
- lib/Basics/FileUtils.cpp
- lib/Basics/FileUtils.h
The changes have been added to reduce the noise during startup.
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-linux/5683/ -- cluster red - probably unrelated
http://jenkins01.arangodb.biz:8080/job/arangodb-ANY-check-log-id/240/ -- blue
> Avoid some exceptions in environment feature when reading files.

- arangod/Aql/RegexCache.cpp
- lib/ApplicationFeatures/V8SecurityFeature.cpp
- lib/Basics/StringUtils.cpp
- lib/Basics/StringUtils.h
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/4244/
> escape internal REs

- arangod/MMFiles/MMFilesWalRecoverState.cpp
- arangod/VocBase/Methods/Version.cpp
- arangod/VocBase/Methods/Version.h
- lib/Basics/VelocyPackHelper.cpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/4243/
> also fsync underlying directory, otherwise data may not reach disk

- arangod/RocksDBEngine/RocksDBCollection.cpp
- arangod/RocksDBEngine/RocksDBCollectionMeta.cpp
- arangod/RocksDBEngine/RocksDBEngine.cpp
- arangod/RocksDBEngine/RocksDBRecoveryManager.cpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/5728/
> fix assertion in RocksDBCollectionMeta

- arangod/Indexes/SimpleAttributeEqualityMatcher.cpp
- arangod/RocksDBEngine/RocksDBRecoveryManager.cpp
- tests/js/server/recovery/collection-keygen-traditional.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/5720/
> Fix tick overflow (#8840)

- Documentation/Books/Manual/Transactions/Durability.md
http://jenkins01.arangodb.biz:8080/job/arangodb-documentation/413/
> Update Durability section

- arangod/RocksDBEngine/RocksDBCuckooIndexEstimator.h
- tests/RocksDBEngine/IndexEstimatorTest.cpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/5739/
> Improve estimator apply algo + test

- arangod/RocksDBEngine/RocksDBCuckooIndexEstimator.h
- tests/RocksDBEngine/IndexEstimatorTest.cpp
> Backport fix for truncate selectivity

- arangod/Agency/AgencyComm.cpp
- arangod/Agency/AgencyComm.h
- arangod/Cluster/ServerState.cpp
- arangod/Cluster/ServerState.h
Changed clientId to format <serverid>:<uuid>, if serverid is known.
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/3879/
> [3.4] ClientID Agency Transaction

- Documentation/Books/Manual/Graphs/SmartGraphs/README.md
_Via Luigi:_
When a traversal is smart and how sharding works and is inherited should be explained in the docs:
https://arangodb.slack.com/archives/C1PJT16QP/p1536607786000100
> Doc - SmartGraphs formatting

- js/apps/system/_admin/aardvark/APP/frontend/js/templates/navigationView.ejs
Changed the graphs (diagram) icon for graphs to something more like graphs: 
https://fontawesome.com/icons/sitemap?style=solid
> Graph Icon in UI

- arangod/RestServer/DatabaseFeature.cpp
- arangod/Transaction/Manager.cpp
- arangod/Transaction/Manager.h
- arangod/Transaction/ManagerFeature.cpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/5771/
> Make sure no managed trx are created during shutdown

- lib/Basics/VelocyPackHelper.cpp
- lib/Basics/VelocyPackHelper.h
- lib/Rest/GeneralRequest.cpp
- lib/Rest/GeneralRequest.h
- lib/SimpleHttpClient/SimpleHttpResult.cpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/5772/
> Do not store ptr to local options

- tests/IResearch/ExpressionFilter-test.cpp
- tests/IResearch/IResearchIndex-test.cpp
- tests/IResearch/IResearchQueryAggregate-test.cpp
- tests/IResearch/IResearchQueryAnd-test.cpp
- tests/IResearch/IResearchQueryComplexBoolean-test.cpp
- tests/IResearch/IResearchQueryExists-test.cpp
- tests/IResearch/IResearchQueryIn-test.cpp
- tests/IResearch/IResearchQueryInRange-test.cpp
- tests/IResearch/IResearchQueryJoin-test.cpp
- tests/IResearch/IResearchQueryNumericTerm-test.cpp
- tests/IResearch/IResearchQueryOptions-test.cpp
- tests/IResearch/IResearchQueryOr-test.cpp
- tests/IResearch/IResearchQueryPhrase-test.cpp
- tests/IResearch/IResearchQueryScorer-test.cpp
- tests/IResearch/IResearchQueryStartsWith-test.cpp
- tests/IResearch/IResearchQueryStringTerm-test.cpp
- tests/IResearch/IResearchQueryTokens-test.cpp
- tests/IResearch/IResearchQueryTraversal-test.cpp
- tests/IResearch/IResearchQueryValue-test.cpp
- tests/IResearch/common.cpp
- tests/IResearch/common.h
alternatively, pick up the directory from environment variable
`IRESEARCH_TEST_RESOURCE_DIR`
> auto-locate directory to IResearch test resources

- Documentation/Books/Manual/Architecture/DeploymentModes/DC2DC/Introduction.md
- Documentation/Books/Manual/Deployment/DC2DC/KafkaZookeeper.md
Internal ref:
- https://github.com/arangodb/planning/issues/3575
> Doc - DC2DC: DirectMQ vs. Kafka

- Documentation/Books/Manual/Architecture/DeploymentModes/DC2DC/Introduction.md
- Documentation/Books/Manual/Deployment/DC2DC/KafkaZookeeper.md
Forward port of https://github.com/arangodb/arangodb/pull/8859
> Doc - DC2DC: DirectMQ vs. Kafka (#8859)

- Documentation/Books/Manual/Administration/Cluster/README.md
Backport of https://github.com/arangodb/arangodb/pull/8744
> Doc - Fix cleanout server example (#8744)

- Documentation/Books/Manual/Deployment/StandaloneAgency/README.md
Backport of https://github.com/arangodb/arangodb/pull/8742
> Doc - Changes to standalone agency example (#8742)

- Documentation/Books/HTTP/General/README.md
Backport of https://github.com/arangodb/arangodb/pull/8835
> Doc - Small typos (#8835)

- Documentation/Books/AQL/Functions/Document.md
- Documentation/Books/AQL/Functions/Numeric.md
- Documentation/Books/AQL/Functions/String.md
Backport of https://github.com/arangodb/arangodb/pull/8299
> Doc - Correct AQL function examples (#8299)

- Documentation/Books/Manual/Programs/Arangorestore/Examples.md
Backport of https://github.com/arangodb/arangodb/pull/8095
> Doc - Arangorestore - Number-of-shards and replication-factor (#8095)

- Documentation/Books/Manual/Installation/MacOSX.md
Backport of https://github.com/arangodb/arangodb/pull/7964
> Doc - macOS - Remove Graphical App, improve CLI install steps, Starter inclusion

- Documentation/Books/Manual/Graphs/SmartGraphs/README.md
Backport of https://github.com/arangodb/arangodb/pull/6486
> Doc - SmartGraphs formatting (#6486)

- Documentation/Books/Manual/Views/ArangoSearch/DetailedOverview.md
- Documentation/DocuBlocks/Rest/Views/patch_api_view_properties_iresearch.md
- Documentation/DocuBlocks/Rest/Views/post_api_view_iresearch.md
- Documentation/DocuBlocks/Rest/Views/put_api_view_properties_iresearch.md
Backport of https://github.com/arangodb/arangodb/pull/7032/files
> Doc - Fix Views markup

- tests/js/client/active-failover/basic.js
- tests/js/client/active-failover/readonly.js
https://jenkins.arangodb.biz/job/arangodb-matrix-pr-linux/5826/
> address issues with active failover

- arangod/RocksDBEngine/RocksDBCollection.cpp
- arangod/RocksDBEngine/RocksDBPrimaryIndex.cpp
- arangod/RocksDBEngine/RocksDBTransactionState.cpp
- arangod/RocksDBEngine/RocksDBTransactionState.h
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/5840/
> do not acquire a snapshot for a single read op

- arangod/Aql/IndexNode.cpp
- arangod/Aql/OptimizerRules.cpp
- arangod/Cache/CacheManagerFeature.cpp
- arangod/GeoIndex/Near.cpp
- arangod/Graph/EdgeCollectionInfo.cpp
- arangod/Indexes/IndexIterator.h
- arangod/MMFiles/MMFilesGeoIndex.cpp
- arangod/Pregel/Conductor.cpp
- arangod/Pregel/Conductor.h
- arangod/Pregel/Graph.h
- arangod/Pregel/GraphStore.cpp
- arangod/Pregel/GraphStore.h
- arangod/Pregel/IncomingCache.cpp
- arangod/Pregel/IncomingCache.h
- arangod/Pregel/OutgoingCache.cpp
- arangod/Pregel/PregelFeature.cpp
- arangod/Pregel/Utils.cpp
- arangod/Pregel/Utils.h
- arangod/Pregel/Worker.cpp
- arangod/Pregel/Worker.h
- arangod/Pregel/WorkerConfig.cpp
- arangod/Pregel/WorkerConfig.h
- arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
- arangod/RocksDBEngine/RocksDBEdgeIndex.h
- arangod/RocksDBEngine/RocksDBGeoIndex.cpp
- lib/Geo/GeoParams.h
- tests/js/server/shell/shell-pregel.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/5757/
> Pregel various fixes

- arangod/Graph/KShortestPathsFinder.cpp
- arangod/Graph/KShortestPathsFinder.h
* Only consider spur paths from after the branchpoint
from the previous path
* Cache neighbourhoods around vertices
> Improve k Shortest Paths performance

- arangod/Aql/CollectNode.cpp
- arangod/Aql/ExecutionEngine.cpp
- arangod/Aql/ExecutionNode.cpp
- arangod/Aql/OptimizerRules.cpp
- arangod/Aql/TraversalConditionFinder.cpp
There were a few places where K_SHORTEST_PATHS was not handled. This
commit adds them.
> Add K_SHORTEST_PATHS handling to optimizer and executor

- js/client/modules/@arangodb/analyzers.js
> issue 564.1: remove return value and propagate 'force'

- CHANGELOG
- arangod/Agency/RestAgencyHandler.cpp
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/4372/
> Do not skip the check if there is only a single agent.

- arangod/Pregel/GraphStore.cpp
- arangod/Pregel/Utils.cpp
- arangod/Pregel/Worker.cpp
- arangod/Pregel/WorkerConfig.cpp
- arangod/Pregel/WorkerConfig.h
- tests/js/server/shell/shell-pregel.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/4392/
> fix issues with pregel

- arangod/Pregel/GraphStore.cpp
- arangod/Pregel/Utils.cpp
- arangod/Pregel/Worker.cpp
- arangod/Pregel/WorkerConfig.cpp
- arangod/Pregel/WorkerConfig.h
- tests/js/server/shell/shell-pregel.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/
> Forward port some changes

- arangod/Transaction/Methods.cpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/5930/
> do not allocate string for _id value temporary

- arangod/V8Server/v8-analyzers.cpp
- js/client/modules/@arangodb/analyzers.js
- js/server/modules/@arangodb/analyzers.js
> issue 561.1: add pretty-printing to analyzers in JavaScript

- arangod/IResearch/IResearchAnalyzerFeature.cpp
- arangod/IResearch/IResearchAnalyzerFeature.h
- arangod/RestHandler/RestAnalyzerHandler.cpp
- arangod/V8Server/v8-analyzers.cpp
- tests/IResearch/IResearchAnalyzerFeature-test.cpp
- tests/RestHandler/RestAnalyzerHandler-test.cpp
- tests/V8Server/v8-analyzers-test.cpp
> issue 563.1: include static analyzers in analyzer listing

- js/client/modules/@arangodb/analyzers.js
> add missing quote

- arangod/RestHandler/RestAnalyzerHandler.cpp
- arangod/V8Server/v8-analyzers.cpp
> issue 562.1: represent analyzer properties as object when possible

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/views/graphSettingsView.js
fixed: https://github.com/arangodb/arangodb/issues/8841
> Bug fix/issue 8841

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/views/graphSettingsView.js
same as https://github.com/arangodb/arangodb/pull/8979
> Bug fix 3.4/issue 8841

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/arango/arango.js
Same as: https://github.com/arangodb/arangodb/pull/8967
Fixing: https://github.com/arangodb/arangodb/issues/7011
> Bug fix 3.4/issue 7011

- arangod/IResearch/IResearchAnalyzerFeature.cpp
- arangod/IResearch/IResearchViewMeta.cpp
- tests/IResearch/IResearchViewMeta-test.cpp
- tests/js/common/aql/aql-view-arangosearch-ddl-cluster.js
- tests/js/common/aql/aql-view-arangosearch-ddl-noncluster.js
> switch to tiered consolidation by default

- js/actions/api-cluster.js
Fixed lost precondition when removing server.
> [3.4] RemoveServer Prec

- js/actions/api-cluster.js
Fixed lost precondition when removing server.
> [devel] RemoveServer Prec

- js/actions/api-cluster.js
Fixed lost precondition when removing server.
> [3.3] RemoveServer Precs

- arangod/Aql/AqlFunctionFeature.cpp
- arangod/Aql/Functions.cpp
- arangod/Pregel/Conductor.cpp
- arangod/Pregel/Conductor.h
- arangod/Pregel/PregelFeature.cpp
- arangod/Pregel/Worker.cpp
- arangod/Pregel/Worker.h
- arangod/V8Server/v8-collection.cpp
- tests/js/server/shell/shell-pregel.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/5980/
> prgl switcheroo

- arangod/Agency/AgencyFeature.cpp
- arangod/IResearch/IResearchAnalyzerFeature.cpp
> disable arangosearch analyzers in agency

- arangod/VocBase/Methods/Databases.cpp
Retry updating user collection.
> [3.4] CreateDropDatabase conflict

- arangod/Graph/GraphOperations.cpp
- arangod/RestHandler/RestTransactionHandler.cpp
- arangod/Transaction/ManagerFeature.cpp
- lib/Rest/GeneralRequest.cpp
- lib/Rest/GeneralRequest.h
- tests/CMakeLists.txt
- tests/IResearch/RestHandlerMock.h
- tests/Transaction/Context-test.cpp
- tests/Transaction/Manager-test.cpp
- tests/Transaction/ManagerSetup.h
- tests/Transaction/RestTransactionHandler-test.cpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/4454/
> New tests for Transaction API

- arangod/VocBase/Methods/Databases.cpp
Retry updating user collection.
> [devel] CreateDropDatabase conflict

- arangod/Aql/EngineInfoContainerDBServer.cpp
- arangod/Aql/EngineInfoContainerDBServer.h
Backport of https://github.com/arangodb/arangodb/pull/8946
> [3.4] Let only on shard per collection, not per DBServer, be responsible for initialize cursor (and shutdown)

- tests/IResearch/IResearchViewSorted-test.cpp
- tests/IResearch/common.cpp
- tests/IResearch/common.h
> fix asan error

- arangod/Pregel/Conductor.cpp
- arangod/Pregel/Worker.cpp
- arangod/RestHandler/RestControlPregelHandler.cpp
- arangod/V8Server/v8-collection.cpp
- tests/js/server/shell/shell-pregel.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/6004/
> Bug fix 3.4/pregel gr

- arangod/IResearch/IResearchAnalyzerFeature.cpp
- arangod/IResearch/IResearchView.cpp
- tests/IResearch/IResearchAnalyzerFeature-test.cpp
- tests/IResearch/IResearchFeature-test.cpp
- tests/IResearch/IResearchLinkMeta-test.cpp
- tests/RestHandler/RestAnalyzerHandler-test.cpp
- tests/V8Server/v8-analyzers-test.cpp
> bug-fix/arangosearch-upgrade

- PULL_REQUEST_TEMPLATE.md
This PR is intended to add some guidelines for new PRs.
> pr template

- PULL_REQUEST_TEMPLATE.md
Jörg made some small suggestions that I wanted to incorporate
> slight wording updates to PR template

- arangod/CMakeLists.txt
- arangod/Cluster/ClusterCollectionCreationInfo.cpp
- arangod/Cluster/ClusterCollectionCreationInfo.h
- arangod/Cluster/ClusterInfo.cpp
- arangod/Cluster/ClusterInfo.h
- arangod/Cluster/ClusterMethods.cpp
- arangod/Cluster/ClusterMethods.h
- arangod/Graph/GraphManager.cpp
- arangod/RestHandler/RestReplicationHandler.cpp
- arangod/VocBase/Methods/CollectionCreationInfo.h
- arangod/VocBase/Methods/Collections.cpp
- arangod/VocBase/Methods/Collections.h
- lib/Basics/StaticStrings.cpp
- lib/Basics/StaticStrings.h
This PR is supposed to speedup creation of multiple collections in the cluster (especially when creating graphs)
It also fixes undesired side effects in some error cases.
> Bug fix 3.4/collection babies

- arangod/Aql/Aggregator.cpp
- tests/js/server/aql/aql-optimizer-collect-aggregate.js
devel companion PR for https://github.com/arangodb/arangodb/pull/9052
> fix result of AQL function `MIN` in case the first input element is `null`

- arangod/Aql/GraphNode.cpp
- arangod/Aql/GraphNode.h
- js/common/modules/@arangodb/aql/explainer.js
Reverts arangodb/arangodb#9049
Sorry accidentally merged without waiting for Jenkins. Jenkins unhappy
> Revert "(K_)SHORTEST PATHS: Display correct directions in explainer/profiler"

- arangod/RestServer/CheckVersionFeature.cpp
- arangod/VocBase/Methods/Upgrade.cpp
3.4 companion PR for https://github.com/arangodb/arangodb/pull/9076
> fix VERSION file handling on upgrade

- CHANGELOG
This change is already covered by existing tests, such as *all graph tests*.
Additionally:
> All new …
> Added missing changelog entry

- arangod/IResearch/IResearchView.cpp
> temporary disable upgrade for views

- arangod/IResearch/IResearchView.cpp
- tests/IResearch/IResearchFeature-test.cpp
> Bug fix/disable upgrade for views again 2

- arangod/Agency/AgencyCommon.h
- arangod/Graph/KShortestPathsFinder.h
- arangod/Replication/Syncer.cpp
- arangod/Replication/TailingSyncer.cpp
- arangod/RestServer/DatabaseFeature.h
- arangod/Transaction/Methods.cpp
- arangosh/Dump/DumpFeature.cpp
> fix various small annoyances

- Documentation/Examples/RestTransactionBeginAbort.generated
- Documentation/Examples/RestTransactionBeginCommit.generated
- Documentation/Examples/RestTransactionBeginNonExisting.generated
- Documentation/Examples/RestTransactionBeginSingle.generated
- Documentation/Examples/RestTransactionGet.generated
> add missing examples

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/templates/loadingTableView.ejs
- js/apps/system/_admin/aardvark/APP/frontend/js/templates/loggerView.ejs
- js/apps/system/_admin/aardvark/APP/frontend/js/templates/loggerViewEntries.ejs
same as: https://github.com/arangodb/arangodb/pull/9092
pls merge asap.
> Bug fix 3.4/logger ejs templates

- CHANGELOG
- arangod/VocBase/Methods/UpgradeTasks.cpp
- tests/js/server/shell/shell-foxx-queues.js
https://github.com/arangodb/planning/issues/3980
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/6164/
> Bug fix 3.4/jobs indexes

- tests/Cache/PlainCache.cpp
- tests/Cache/TransactionalCache.cpp
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/4616/
> Fix two nondeterministically failing cache tests

- CHANGELOG
- js/server/modules/@arangodb/aql-graph-traversal-generic-graphs.js
- js/server/modules/@arangodb/aql-graph-traversal-generic-tests.js
- tests/js/server/aql/aql-graph-traversal-generic-cluster.js
- tests/js/server/aql/aql-graph-traversal-generic-noncluster.js
- tests/js/server/dump/dump-mmfiles-cluster.js
- tests/js/server/dump/dump-rocksdb-cluster.js
- tests/js/server/dump/dump-setup-cluster.js
This is a backport of https://github.com/arangodb/arangodb/pull/9041
*(Please pick either of the …
> [3.4] Bugfix of DFS path uniqueness implementation

- arangod/Scheduler/SupervisedScheduler.cpp
- arangod/Scheduler/SupervisedScheduler.h
> Fixed UBSan error in the scheduler

- CHANGELOG
- arangod/VocBase/Methods/UpgradeTasks.cpp
- tests/js/server/shell/shell-foxx-queues.js
Fix a nonesensical index definition that was wrongly converted from js to the cpp version
- [x Bug-Fix for a *released version* (did you remember to port this to all relevant release branches?)
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/6172/
> Bug fix/jobs indexes

- CMakeLists.txt
Setup CLCACHE specific options for fast compilation.
> Add USE_CLCACHE_MODE to have specific build options

- 3rdParty/V8/CMakeLists.txt
- 3rdParty/V8/v7.1.302.28/gypfiles/standalone.gypi
Should now propagate /Z7 to all V8-related projects.
> Add /Z7 switch to V8 gyp

- js/client/modules/@arangodb/process-utils.js
- js/client/modules/@arangodb/test-utils.js
- js/client/modules/@arangodb/testing.js
- js/client/modules/@arangodb/testsuites/arangobench.js
- js/client/modules/@arangodb/testsuites/authentication.js
- js/client/modules/@arangodb/testsuites/backup.js
- js/client/modules/@arangodb/testsuites/dump.js
- js/client/modules/@arangodb/testsuites/endpoints.js
- js/client/modules/@arangodb/testsuites/export.js
- js/client/modules/@arangodb/testsuites/foxxmanager.js
- js/client/modules/@arangodb/testsuites/importing.js
- js/client/modules/@arangodb/testsuites/permissions_server.js
- js/client/modules/@arangodb/testsuites/queryCacheAuthorization.js
- js/client/modules/@arangodb/testsuites/readOnly.js
- js/client/modules/@arangodb/testsuites/replication.js
- js/client/modules/@arangodb/testsuites/single.js
- js/client/modules/@arangodb/testsuites/stress.js
- fixes testing behviour in shutdown error cases where no test failures occured before.
This functionality comes into account when the shutdown of actual tests fails.
> preserve the instance shutdown state, and if its bad, don't clean up the test directory

- tests/js/server/aql/aql-graph-traverser.js
> Round estimatedCost in some tests

- arangod/Aql/GraphNode.cpp
- arangod/Aql/GraphNode.h
- js/common/modules/@arangodb/aql/explainer.js
This is a reincarnation of #9049. Lets make sure Jenkins is happy this time.
> (K_)SHORTEST PATHS: Display correct directions in explainer/profiler

- tests/js/client/agency/agency-test.js
> Fix yet another agency test with clientid.

- tests/Greylist.txt
- tests/js/server/resilience/repair/repair-distribute-shards-like-spec-grey.js
- tests/js/server/resilience/repair/repair-distribute-shards-like-spec.js
This is a backport of https://github.com/arangodb/arangodb/pull/9135 and https://github.com/arangodb/arangodb/pull/9151.
*(Please reference tickets / …
> [3.4] Wait for replication before inserting

- CHANGELOG
- arangod/Aql/TraversalBlock.cpp
> [3.4] Fixed incorrect tracing in TraversalBlock

- arangod/Pregel/GraphStore.cpp
- arangod/Pregel/GraphStore.h
- arangod/Pregel/TypedBuffer.h
Catch more error messages in Pregel. Display better error message when a memory mapped file cannot be created.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/4695/
> improve error message

- arangod/Pregel/Conductor.cpp
- arangod/Pregel/Conductor.h
- arangod/Pregel/GraphStore.cpp
- arangod/Pregel/Iterators.h
- arangod/Pregel/TypedBuffer.h
devel companion PR for https://github.com/arangodb/arangodb/pull/9178
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/4723/
> Bug fix/pregel micro improvements

- tests/js/client/permissions/endpoints.js
> add arango reconnect test

- Documentation/DocuBlocks/Rest/Analyzers/delete_api_analyzer.md
- Documentation/DocuBlocks/Rest/Analyzers/get_api_analyzer.md
- Documentation/DocuBlocks/Rest/Analyzers/post_api_analyzer.md
https://jenkins01.arangodb.biz/view/Documentation/job/arangodb-ANY-examples/99/
> Fixed REST API examples for new analyzer naming

- CHANGELOG
- arangod/Pregel/Conductor.cpp
- arangod/Pregel/Iterators.h
- arangod/Pregel/PregelFeature.cpp
- tests/js/common/shell/shell-pregel-start-cluster.js
This is a backport of: https://github.com/arangodb/arangodb/pull/9149
issue: https://github.com/arangodb/team-orco-planning/issues/135
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/4754/
> pregel: changeable shardkeyattribute (3.4)

- tests/js/server/aql/aql-modify-cluster.js
just add a test:
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/4749/
> add limits test (3.4)

- CHANGELOG
- arangod/Cluster/AgencyCallback.cpp
- arangod/Cluster/AgencyCallback.h
- arangod/Cluster/ClusterInfo.cpp
- arangod/VocBase/Methods/CollectionCreationInfo.h
*Speedup collection creation process if callbacks from agency are missed or not delivered*
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/4726/
> Fix missed callbacks race condition

- js/server/modules/@arangodb/aql-graph-traversal-generic-graphs.js
> Allow generic graph tests to work without enterprise checkout

- js/server/modules/@arangodb/aql-graph-traversal-generic-graphs.js
> [3.4] Allow generic graph tests to work without enterprise checkout

- CHANGELOG
- arangod/Agency/Node.cpp
- js/client/tests/agency/agency-test.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/4766/
> [3.3] fix ttl handling for object assigments

- CHANGELOG
- arangod/Agency/Node.cpp
- tests/js/client/agency/agency-test.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/4777/
> [devel] fix ttl handling for object assigments

- arangod/Aql/AqlItemMatrix.h
- arangod/Aql/ConstrainedSortExecutor.cpp
- arangod/Aql/ConstrainedSortExecutor.h
- arangod/Aql/IResearchViewExecutor.cpp
- arangod/MMFiles/MMFilesCollection.cpp
- arangod/MMFiles/MMFilesCollection.h
- arangod/Pregel/GraphStore.cpp
- arangod/Pregel/GraphStore.h
- arangod/Pregel/TypedBuffer.h
- tests/Aql/HashedCollectExecutorTest.cpp
- tests/Basics/HashSetTest.cpp
- tests/Basics/InifileParserTest.cpp
- tests/CMakeLists.txt
- tests/IResearch/common.cpp
- tests/Pregel/typedbuffer.cpp
fix compiler warnings / errors on windows
> fix windows warnings / compile errors

- arangod/RocksDBEngine/RocksDBBackgroundErrorListener.cpp
Display actual reason for background error, and ignore all background errors that are caused because of a server shutdown.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/4773/
> display reason for error in background listener, plus ignore shutdown

- CHANGELOG
- also updates the release date
> Update Changelog - add starter entry

- CHANGELOG
also removes a double new line in the 3.4.7 part
> Changelog - adds 3.4.6.1 entries

- arangod/Cluster/ClusterCollectionCreationInfo.cpp
- arangod/Cluster/ClusterCollectionCreationInfo.h
Fix various small issues in the previous version of the code
> fix issues

- tests/js/client/agency/agency-test.js
Fix failing agency test, clean up test code slightly
> fix failing agency test

- arangod/Scheduler/SupervisedScheduler.cpp
The 3.4 scheduler recently reserved half of the scheduler threads for HIGH priority actions.  That logic was not previously adopted in the rewritten scheduler of devel/3.5.  A test with 1,000 simultaneous connections proved the same logic was needed in this branch.  
I am unclear if another PR is needed for 3.5.  Awaiting clarification.
> BugFix:  Prevent scheduler lock-up under heavy load

- 3rdParty/iresearch/core/search/sort.cpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/4842/
> bug-fix/internal-issue-#589.2

- arangod/Cluster/ClusterInfo.cpp
Revert change of shared_ptr to simple atomic in ClusterInfo. Should fix some crashes.
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/4844/
> Revert change to shared_ptr in ClusterInfo

- 3rdParty/iresearch/external/snowball/CMakeLists.txt
This fixes the dependency chain so the snowball executeable is built before its invoked
> fix snowball invocation and dependencies

- arangod/Aql/RemoteExecutor.h
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/4918/
> Fix warning about unused field

- CHANGELOG
- arangod/Graph/GraphOperations.cpp
- arangod/Graph/GraphOperations.h
- tests/js/client/http/api-gharial-spec.js
- tests/rb/HttpInterface/api-general-graph-spec.rb
pls ignore branch name (wrong name chosen). 
PR same as https://github.com/arangodb/arangodb/pull/9177, but only for `3.4`
> Bug fix/gharial 3 4 edge from and tos verification

- CHANGELOG
- arangod/Cluster/ClusterCollectionCreationInfo.cpp
- arangod/Cluster/ClusterInfo.cpp
Backward-port of: https://github.com/arangodb/arangodb/pull/9296
It fixes are very rare race condition where a coordinator can overwrite an attempt of the agency to fix collection distribution on server death. 
*(or)*
*(or)*
- Did you add tests for a new *RestHandler* subclass ?
- Did you add new mocks of underlying code layers to be able to verify your functionality ? 
- ...
Additionally:
*(Include link to …
> Bug fix 3.4/create collections better preconditions

- js/actions/api-cluster.js
When removing a server via api (or webui) the coordinator will write an info msg to the log file and store the removal date of that server in the agency.
This is to keep track of removed servers.
https://github.com/arangodb/planning/issues/4135#event-2420129595
This change is a trivial work.
> Log Server Removal

- CHANGELOG
- Documentation/Books/Manual/Security/SecurityOptions.md
- arangod/V8Server/v8-statistics.cpp
- lib/ApplicationFeatures/V8SecurityFeature.cpp
Allows always access to statistics:
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/4931/
https://github.com/arangodb/docs/pull/88 -- related PR
> fix cluster statistics

- CHANGELOG
Changelog entry for coordinator route for agency dump added. Assumes it is in 3.3.23, per internal discussion, but I did not check the code myself
--- …
> 3.3.23 changelog 

- CHANGELOG
- links internal issue
- rephrase a bit to adapt to the fact that the internal issue is linked - but main point was to add the internal issue
> Improves changelog for version 3.4.7 

- js/client/modules/@arangodb/process-utils.js
attempting to kill the SUT with *nix coredump enabled signals
> add a function that will use procdump to generate a core before 

- arangod/IResearch/IResearchView.cpp
- arangod/IResearch/IResearchViewCoordinator.cpp
- tests/IResearch/IResearchViewCoordinator-test.cpp
- tests/js/common/aql/aql-view-arangosearch-ddl-cluster.js
- tests/js/common/aql/aql-view-arangosearch-ddl-noncluster.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/4952/
> bug-fix/internal-issue-#597

- js/client/modules/@arangodb/process-utils.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/4955/
> add a function that will use procdump to generate a core before (3.4)

- 3rdParty/velocypack/src/Builder.cpp
-### Scope & Purpose
Try to avoid thread locals which do heap allocations on construction
This seems to cause issues at least in some MSVC/Windows environments
If this works, please close PR https://github.com/arangodb/arangodb/pull/9251.
This change is already covered by existing tests, such as _nearly all tests_.
VelocyPack test suite also passes for the change without issues.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/4947/
> attempt to fix thread-local issues with non-trivial constructions

- arangod/RocksDBEngine/RocksDBCollection.cpp
- arangod/RocksDBEngine/RocksDBCollection.h
- arangod/RocksDBEngine/RocksDBIndex.cpp
- arangod/RocksDBEngine/RocksDBIndex.h
- tests/js/server/shell/shell-pregel.js
simplify the setup of the hash cache
This change is already covered by existing tests, such as the existing caching tests
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/6570/
> Bug fix/simplify cache setup

- arangod/StorageEngine/PhysicalCollection.cpp
- arangod/StorageEngine/PhysicalCollection.h
- tests/CMakeLists.txt
- tests/StorageEngine/PhysicalCollectionTest.cpp
Add a test for `PhysicalCollection::newObjectForInsert`, as we were unsure if it works as we expected.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/4982/
> added test for object creation

- CHANGELOG
- arangod/Agency/Constituent.cpp
- arangod/Agency/Constituent.h
> Fix agency election lock step bug.

- arangod/IResearch/IResearchAnalyzerFeature.cpp
- tests/js/common/aql/aql-view-arangosearch-feature.js
Added missing commit call for analyzer removal transaction.
Added db collection check after analyzer removal in tests
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/4992/
> Bug fix/fixed analyzer removal from db

- arangod/Cluster/v8-cluster.cpp
- arangod/V8Server/v8-collection.cpp
- js/server/modules/@arangodb/cluster.js
Remove unused code
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/4994/
> remove unused functionality

- arangod/Cluster/ClusterTrxMethods.cpp
- arangod/Cluster/FollowerInfo.cpp
- arangod/Cluster/FollowerInfo.h
- arangod/RestHandler/RestReplicationHandler.cpp
- arangod/Transaction/Methods.cpp
- tests/js/server/shell/shell-followers-cluster.js
Make `FollowerInfo::add` return if adding the follower succeeded or not.
It is unclear to me if adding/dropping followers is covered by existing tests. Probably it isn't yet.
What's the best place/test suite to add automated tests for this functionality?
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/4990/
> actually honor the return value of FollowerInfo::addFollower

- js/server/modules/@arangodb/aql.js
Remove unused JS code
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/4997/
> remove unused JS function

- js/common/modules/@arangodb/aql/explainer.js
http://jenkins01.arangodb.biz:8080/job/arangodb-ANY-jslint/1121/
> fix arangosearch query explanation

- tests/Mocks/StorageEngineMock.cpp
- tests/js/client/authentication/auth-analyzer.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/5012/
http://jenkins01.arangodb.biz:8080/view/Windows/job/arangodb-matrix-pr-windows-onlycatch/2831/
> Fix authentication and catch tests in devel

- README
> undo README removal 

- CHANGELOG
> Consistent formatting of CHANGELOG.

- arangod/Cluster/ClusterMethods.cpp
- arangod/RestHandler/RestHotBackupHandler.cpp
- arangod/RocksDBEngine/RocksDBHotBackup.cpp
- arangod/RocksDBEngine/RocksDBHotBackup.h
- arangod/VocBase/Methods/Version.cpp
- arangod/VocBase/Methods/Version.h
- arangosh/Backup/BackupFeature.cpp
- tests/RocksDBEngine/HotBackupTest.cpp
> [3.4] HotBackup Version Check

- 3rdParty/velocypack/include/velocypack/Builder.h
- 3rdParty/velocypack/include/velocypack/Slice.h
Port some small VelocyPack improvements from arangodb/velocypack to arangodb/arangodb
This change is already covered by existing tests, such as *velocypack tests*.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5041/
> @maierlars :heart_eyes:

- js/client/modules/@arangodb/process-utils.js
Fix an obvious bug using the wrong variable
> Don't use non-existent variable

- arangod/Agency/AgencyComm.cpp
- arangod/Agency/FailedLeader.cpp
- arangod/Agency/Job.cpp
- arangod/Agency/Store.cpp
- arangod/Agency/Supervision.cpp
- arangod/Aql/Functions.cpp
- arangod/Cluster/AgencyCallback.cpp
- arangod/Cluster/ClusterInfo.cpp
- arangod/Cluster/ClusterMethods.cpp
- arangod/RestServer/BootstrapFeature.cpp
Replace binary comparisons of VPack Slices with logical ones.
This change is already covered by existing tests, such as all cluster tests.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5020/
> use logical comparisons instead of binary ones

- arangod/Agency/AgencyComm.cpp
- arangod/Agency/FailedLeader.cpp
- arangod/Agency/Job.cpp
- arangod/Agency/Store.cpp
- arangod/Agency/Supervision.cpp
- arangod/Aql/Functions.cpp
- arangod/Cluster/AgencyCallback.cpp
- arangod/Cluster/ClusterInfo.cpp
- arangod/Cluster/ClusterMethods.cpp
- arangod/Cluster/Maintenance.cpp
- arangod/RestServer/BootstrapFeature.cpp
Replace potentially unsafe binary VPack comparisons with logical comparisons
This change is already covered by existing tests, all agency & cluster tests.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5019/
> replace potentially unsafe binary comparisons with logical ones

- CHANGELOG
- arangod/Cluster/DBServerAgencySync.cpp
- arangod/Cluster/DBServerAgencySync.h
- arangod/Cluster/FollowerInfo.cpp
- arangod/Cluster/Maintenance.cpp
- arangod/Transaction/Methods.cpp
- tests/Agency/FailedLeaderTest.cpp
- tests/Agency/FailedServerTest.cpp
- tests/Agency/RemoveFollowerTest.cpp
> Leader updates Current precondition fixes.

- tests/js/server/permissions/test-oasis.js
> add test for oasis statistics

- arangod/IResearch/IResearchFeature.cpp
- arangod/IResearch/IResearchFeature.h
- arangod/IResearch/IResearchLink.cpp
- arangod/IResearch/IResearchLink.h
- arangod/RestServer/FlushFeature.cpp
- arangod/RestServer/FlushFeature.h
- arangod/Utils/FlushThread.cpp
- tests/IResearch/IResearchLink-test.cpp
- tests/Mocks/StorageEngineMock.cpp
- tests/RestServer/FlushFeature-test.cpp
- release tick before committing changes to iresearch
> Bug fix/internal issue #605

- 3rdParty/CMakeLists.txt
- 3rdParty/fuerte/include/fuerte/VpackInit.h
- 3rdParty/fuerte/include/fuerte/connection.h
- 3rdParty/fuerte/include/fuerte/detail/vst.h
- 3rdParty/fuerte/include/fuerte/helper.h
- 3rdParty/fuerte/include/fuerte/message.h
- 3rdParty/fuerte/include/fuerte/types.h
- 3rdParty/fuerte/src/AsioSockets.h
- 3rdParty/fuerte/src/GeneralConnection.cpp
- 3rdParty/fuerte/src/GeneralConnection.h
- 3rdParty/fuerte/src/HttpConnection.cpp
- 3rdParty/fuerte/src/HttpConnection.h
- 3rdParty/fuerte/src/MessageStore.h
- 3rdParty/fuerte/src/VstConnection.cpp
- 3rdParty/fuerte/src/VstConnection.h
- 3rdParty/fuerte/src/helper.cpp
- 3rdParty/fuerte/src/http.h
- 3rdParty/fuerte/src/http_parser/http_parser.c
- 3rdParty/fuerte/src/http_parser/http_parser.h
- 3rdParty/fuerte/src/loop.cpp
- 3rdParty/fuerte/src/types.cpp
- 3rdParty/fuerte/src/vst.cpp
- 3rdParty/fuerte/src/vst.h
- arangosh/Benchmark/BenchFeature.cpp
- arangosh/Import/ImportHelper.cpp
- arangosh/Shell/V8ClientConnection.cpp
- arangosh/Shell/V8ClientConnection.h
- arangosh/Shell/V8ShellFeature.cpp
- arangosh/Utils/ClientManager.cpp
- arangosh/V8Client/ArangoClientHelper.cpp
First PR split of from the comm-task refactoring branch.
This change is already covered by existing tests, such as all testsuites using the arangosh
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/5115/
> Fuerte changes from comm-task-refactor branch

- arangod/Aql/IResearchViewExecutor.cpp
- arangod/Aql/IResearchViewOptimizerRules.cpp
- arangod/IResearch/IResearchFilterFactory.cpp
- tests/CMakeLists.txt
- tests/IResearch/IResearchQueryFilter-test.cpp
- tests/IResearch/IResearchQueryMinMatch-test.cpp
- tests/IResearch/IResearchQueryOptions-test.cpp
- tests/IResearch/IResearchQueryPhrase-test.cpp
- tests/IResearch/IResearchQueryScorer-test.cpp
add more unit tests for ArangoSearch
> Bug fix/internal issue #414

- tests/js/server/recovery/view-arangosearch-link-populate.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/5152/
> Temporarily suppress failure

- arangod/Statistics/StatisticsFeature.cpp
- arangod/Statistics/StatisticsFeature.h
- arangod/Statistics/StatisticsWorker.cpp
Remove bogus warnings
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5154/
> remove bogus warnings about statistics thread

- UnitTests/OskarTestSuitesBlackList
- tests/OskarTestSuitesBlackList
Depends on https://github.com/arangodb/oskar/pull/152
> Rename permissions_server suite

- tests/IResearch/IResearchAnalyzerFeature-test.cpp
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/5160/
> Enabled and fixed disabled tests in ArangoSearch

- 3rdParty/fuerte/.clang-format
- 3rdParty/fuerte/include/fuerte/VpackInit.h
- 3rdParty/fuerte/include/fuerte/asio_ns.h
- 3rdParty/fuerte/include/fuerte/connection.h
- 3rdParty/fuerte/include/fuerte/detail/vst.h
- 3rdParty/fuerte/include/fuerte/helper.h
- 3rdParty/fuerte/include/fuerte/jwt.h
- 3rdParty/fuerte/include/fuerte/message.h
- 3rdParty/fuerte/include/fuerte/types.h
- 3rdParty/fuerte/include/fuerte/waitgroup.h
- 3rdParty/fuerte/src/AsioSockets.h
- 3rdParty/fuerte/src/GeneralConnection.cpp
- 3rdParty/fuerte/src/GeneralConnection.h
- 3rdParty/fuerte/src/HttpConnection.cpp
- 3rdParty/fuerte/src/HttpConnection.h
- 3rdParty/fuerte/src/VstConnection.cpp
- 3rdParty/fuerte/src/VstConnection.h
- 3rdParty/fuerte/src/http.h
Fix sporadic timeouts and errors when using fuerte based connections to the server
This change is already covered by existing tests, such as all _shell_client_ tests
http://jenkins01.arangodb.biz:8080/view/Windows/job/arangodb-ANY-windows-matrix/333/
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/5257/
> Fix Arangosh windows instability (3.5)

- CHANGELOG
- arangod/Aql/EngineInfoContainerDBServer.cpp
- arangod/Aql/EngineInfoContainerDBServer.h
Backport of https://github.com/arangodb/arangodb/pull/9416.
This change is already covered by existing tests, such as the `shell_server_aql` suite.
> [3.4] Fix query snippet responsibility for views

- Documentation/Books/Manual/ReleaseNotes/UpgradingChanges35.md
- Documentation/DocuBlocks/Rest/Replication/get_api_wal_access_tail.md
- arangod/CMakeLists.txt
- arangod/Cluster/SynchronizeShard.cpp
- arangod/Cluster/SynchronizeShard.h
- arangod/MMFiles/MMFilesRestReplicationHandler.cpp
- arangod/Replication/ReplicationApplierConfiguration.h
- arangod/Replication/ReplicationClients.cpp
- arangod/Replication/ReplicationClients.h
- arangod/Replication/Syncer.cpp
- arangod/Replication/Syncer.h
- arangod/Replication/utilities.cpp
- arangod/Replication/utilities.h
- arangod/RestHandler/RestReplicationHandler.cpp
- arangod/RestHandler/RestWalAccessHandler.cpp
- arangod/RocksDBEngine/RocksDBReplicationContext.cpp
- arangod/RocksDBEngine/RocksDBReplicationContext.h
- arangod/RocksDBEngine/RocksDBReplicationManager.cpp
- arangod/RocksDBEngine/RocksDBReplicationManager.h
- arangod/RocksDBEngine/RocksDBRestReplicationHandler.cpp
- arangod/Utils/UrlHelper.cpp
- arangod/Utils/UrlHelper.h
- js/apps/system/_admin/aardvark/APP/frontend/js/templates/replicationView.ejs
- js/apps/system/_admin/aardvark/APP/frontend/js/views/replicationView.js
- tests/Replication/ReplicationClientsProgressTrackerTest.cpp
Backport of https://github.com/arangodb/arangodb/pull/9473
> Bug fix 3.5/clean replication api wal tracking

- arangod/GeneralServer/SocketTask.cpp
- arangod/Scheduler/SupervisedScheduler.cpp
Fix an uninitialized value
Fix a typo in a message
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5300/
> Bug fix 3.5/fix uninitialized value

- 3rdParty/velocypack/include/velocypack/Iterator.h
- 3rdParty/velocypack/src/Builder.cpp
Use latest changes from velocypack upstream library
This change is already covered by existing tests, such as *velocypack library tests*.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5321/
> velocypack library upgrade

- 3rdParty/iresearch/core/index/index_writer.cpp
- 3rdParty/iresearch/core/index/index_writer.hpp
- 3rdParty/iresearch/core/index/segment_writer.cpp
- arangod/IResearch/IResearchLink.cpp
- arangod/IResearch/IResearchRocksDBRecoveryHelper.cpp
backport of https://github.com/arangodb/arangodb/pull/9528
> properly handle removals during recovery (#9528)

- lib/Basics/threads-win32.cpp
Fix a potential resource leak in thread shutdown on Windows
This change is already covered by existing tests, such as *windows tests*.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5336/
https://jenkins01.arangodb.biz/job/arangodb-ANY-windows-matrix/340/
> fix leak in thread shutdown

- arangod/IResearch/IResearchRocksDBRecoveryHelper.cpp
Backport of https://github.com/arangodb/arangodb/pull/9528
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/5340/
> Fix typo and restructure to match.

- arangod/Cluster/ClusterComm.cpp
- arangod/Cluster/ClusterComm.h
- lib/Basics/Thread.cpp
- lib/Basics/Thread.h
- lib/Basics/threads-win32.cpp
Backport of https://github.com/arangodb/arangodb/pull/9369 to 3.5
This change is already covered by existing tests, such as *any cluster PR run*.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5328/
https://jenkins01.arangodb.biz/job/arangodb-ANY-windows-matrix/341/
> Bug fix 3.5/fix thread shutdown

- CHANGELOG
- Documentation/DocuBlocks/Rest/Collections/1_structs.md
- Documentation/DocuBlocks/Rest/Graph/1_structs.md
- Documentation/DocuBlocks/Rest/Graph/general_graph_create_http_examples.md
- Documentation/DocuBlocks/collectionProperties.md
- arangod/Agency/Job.cpp
- arangod/Cluster/ClusterInfo.cpp
- arangod/Cluster/ClusterInfo.h
- arangod/Cluster/ClusterMethods.cpp
- arangod/Cluster/FollowerInfo.cpp
- arangod/Cluster/MaintenanceFeature.cpp
- arangod/RestHandler/RestReplicationHandler.cpp
- arangod/RestHandler/RestReplicationHandler.h
- arangod/Scheduler/SupervisedScheduler.h
- js/apps/system/_admin/aardvark/APP/frontend/js/views/collectionsView.js
- js/apps/system/_admin/aardvark/APP/frontend/js/views/graphManagementView.js
- tests/IResearch/IResearchAnalyzerFeature-test.cpp
Forward Port of latest changes applied to minReplicationFactor in 3.5 review.
(sorry branch Name is incorrect...)
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/5365/
> Forward Port of changes in 3.5 review

- arangod/Aql/IResearchViewNode.cpp
- arangod/IResearch/IResearchLink.cpp
- arangod/RocksDBEngine/RocksDBCollection.cpp
- arangod/RocksDBEngine/RocksDBIndex.cpp
- arangod/RocksDBEngine/RocksDBIndex.h
- arangod/Transaction/Manager.cpp
- arangod/VocBase/Methods/Transactions.cpp
- tests/js/server/shell/shell-transactions-view-noncluster.js
backport of https://github.com/arangodb/arangodb/pull/9536
> Bug fix/iresearch trx (#9536)

- CMakeLists.txt
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/5381/
> Backport of MACOSX_DEPLOYMENT_TARGET from devel

- CHANGELOG
- arangod/Aql/Functions.cpp
- tests/js/server/aql/aql-functions-string.js
Fix Github issue #9558
- [] Bug-Fix for *devel-branch* (i.e. no need for backports?)
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5401/
> fixed a bug in RTRIM implementation, fixed issue #9558

- Documentation/DocuBlocks/Rest/Administration/get_admin_statistics.md
- arangod/Statistics/Descriptions.cpp
- arangod/Statistics/StatisticsWorker.cpp
- arangod/V8Server/V8DealerFeature.cpp
- arangod/V8Server/V8DealerFeature.h
- arangod/V8Server/v8-statistics.cpp
- arangosh/Shell/V8ShellFeature.cpp
- lib/ApplicationFeatures/V8PlatformFeature.cpp
- lib/V8/v8-globals.cpp
- lib/V8/v8-globals.h
- lib/V8/v8-utils.cpp
- tests/V8Server/v8-analyzers-test.cpp
- tests/V8Server/v8-users-test.cpp
- tests/V8Server/v8-views-test.cpp
Backport of https://github.com/arangodb/arangodb/pull/9567
> Feature 3.5/add js isolate mem statistics

- js/common/modules/@arangodb/testrunner.js
backport of https://github.com/arangodb/arangodb/pull/9576
> fix test result handling of tests running in own spawned arangosh

- Documentation/DocuBlocks/Rest/Administration/get_admin_statistics.md
- arangod/Statistics/Descriptions.cpp
- arangod/Statistics/StatisticsWorker.cpp
- arangod/V8Server/V8DealerFeature.cpp
- arangod/V8Server/V8DealerFeature.h
- arangod/V8Server/v8-statistics.cpp
- lib/ApplicationFeatures/V8PlatformFeature.cpp
- lib/V8/v8-globals.cpp
- lib/V8/v8-globals.h
- lib/V8/v8-utils.cpp
- tests/V8Server/v8-users-test.cpp
- tests/V8Server/v8-views-test.cpp
backport of https://github.com/arangodb/arangodb/pull/9567
> Feature 3.4/add js isolate mem statistics

- arangod/Statistics/StatisticsWorker.cpp
backport of https://github.com/arangodb/arangodb/pull/9581
> Bug fix 3.4/dont keep memstats

- arangod/RestHandler/RestReplicationHandler.cpp
- tests/js/client/load-balancing/load-balancing-transactions-auth-cluster.js
- tests/js/client/load-balancing/load-balancing-transactions-noauth-cluster.js
Fix test failures in replication and load_balancing tests
This change is already covered by existing tests, such as *replication tests* and *load balancing tests*.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5470/
> Bug fix/fix replication failures

- js/client/modules/@arangodb/test-utils.js
- js/client/modules/@arangodb/testsuites/recovery.js
backport of https://github.com/arangodb/arangodb/pull/9588
> Bug fix 3.5/fix arangosh result evaluation

- arangod/RestHandler/RestReplicationHandler.cpp
- tests/js/client/load-balancing/load-balancing-transactions-auth-cluster.js
- tests/js/client/load-balancing/load-balancing-transactions-noauth-cluster.js
Fix test failures in replication and load_balancing tests
This change is already covered by existing tests, such as *replication tests* and *load balancing tests*.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5471/
> Bug fix 3.5/fix replication failures

- arangod/RestHandler/RestViewHandler.cpp
- arangod/RestServer/ViewTypesFeature.cpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/5479/
> Bug fix 3.5/fix view creation errors

- arangod/RestHandler/RestViewHandler.cpp
- arangod/RestServer/ViewTypesFeature.cpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/5480/
> Fix ArangoSearch view creation errors

- tests/js/client/shell/shell-transaction.js
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5557/
> add error to failure

- arangod/Agency/AgencyComm.cpp
- arangod/Agency/AgencyComm.h
- arangod/Agency/AgencyCommon.h
- arangod/Agency/Agent.cpp
- arangod/Cluster/ClusterInfo.cpp
- arangod/VocBase/LogicalCollection.cpp
* Copy less data, especially in ClusterInfo::loadPlan()
* Automatically turn-off smart collections in Community mode
This change is already covered by existing tests, such as *all cluster tests*.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5563/
> Bug fix/optimizations 06 08 2019

- CHANGELOG
- arangod/Agency/FailedLeader.cpp
- arangod/Agency/FailedLeader.h
- tests/Agency/FailedLeaderTest.cpp
> [3.5.1] Fail the FailedLeader Job if the new leader fails.

- lib/Basics/SharedPRNG.cpp
- lib/Basics/SharedPRNG.h
- lib/Basics/xoroshiro128plus.h
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/5580/
> Add constructors to fix cppcheck warnings.

- arangod/Agency/AgencyComm.cpp
- arangod/Agency/AgencyComm.h
- arangod/Agency/AgencyCommon.h
- arangod/Agency/Agent.cpp
- arangod/Cluster/ClusterInfo.cpp
Copy less data, but move more :truck: :truck: :truck:
This change is already covered by existing tests, such as *all cluster tests*.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5575/
> less copying, more moving! :truck:

- arangod/Aql/ExecutionPlan.cpp
- arangod/Aql/ExecutionPlan.h
- arangod/Aql/RestAqlHandler.cpp
- js/server/modules/@arangodb/aql-profiler-test-helper.js
Remove unused instance variable in ExecutionPlan
This change is already covered by existing tests, such as *cluster AQL tests*.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5598/
> remove unused instance variable

- arangod/GeneralServer/HttpCommTask.cpp
- arangod/Transaction/Manager.cpp
- lib/Geo/GeoParams.h
- lib/Geo/GeoUtils.cpp
Fixes segmentation fault due to a missing shared_ptr in the timeout handler
> Bug fix/simon 19 08 07

- arangod/Aql/GraphNode.cpp
- arangod/Aql/KShortestPathsNode.cpp
- arangod/Aql/ShortestPathNode.cpp
- arangod/Replication/TailingSyncer.cpp
- arangod/RestHandler/RestReplicationHandler.cpp
- arangod/RestServer/DatabaseFeature.h
Some adjustments to pacify cppcheck.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5629/
> miscellaneous adjustments to pacify cppcheck

- utils/generateExamples.js
- utils/generateExamples.py
- utils/generateExamples.sh
> add the ability to have cluster special examples

- arangod/Cluster/HeartbeatThread.cpp
- arangod/Replication/Syncer.cpp
- arangod/Replication/Syncer.h
- arangod/Replication/TailingSyncer.cpp
- arangod/Replication/TailingSyncer.h
- arangod/RocksDBEngine/RocksDBEngine.cpp
- arangod/RocksDBEngine/RocksDBIncrementalSync.cpp
Various replication improvements
- better debuggability (more log details)
- shorter minimum wait delay in active failover
- fixed too early pruning of WAL files on leaders
This change is already covered by existing tests, such as *replication tests*.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5625/
> various replication improvements:

- arangod/Agency/RestAgencyHandler.cpp
> Consistent punctuation.

- arangod/CMakeLists.txt
- arangod/Cluster/ClusterInfo.cpp
- arangod/Cluster/ClusterInfo.h
- arangod/Cluster/ClusterTypes.cpp
- arangod/Cluster/ClusterTypes.h
- arangod/Cluster/RebootTracker.cpp
- arangod/Cluster/RebootTracker.h
- arangod/Cluster/ServerState.cpp
- arangod/Cluster/ServerState.h
- js/actions/api-cluster.js
- js/common/bootstrap/errors.js
- lib/ApplicationFeatures/ApplicationServer.h
- lib/Basics/errors.dat
- lib/Basics/voc-errors.cpp
- lib/Basics/voc-errors.h
- tests/CMakeLists.txt
- tests/Cluster/RebootTrackerTest.cpp
- tests/IResearch/AgencyMock.cpp
- tests/Mocks/Servers.cpp
- tests/Mocks/Servers.h
- tests/V8Server/v8-users-test.cpp
Backport of #9523, already includes https://github.com/arangodb/arangodb/pull/9686.
> [3.5] Feature/rebootid notice changes, backport of #9523

- arangod/IResearch/IResearchOrderFactory.cpp
- tests/IResearch/IResearchQueryScorer-test.cpp
- tests/js/common/aql/aql-view-arangosearch-cluster.inc
- tests/js/common/aql/aql-view-arangosearch-noncluster.js
fix for https://github.com/arangodb/arangodb/issues/9660
> bug-fix/issue-#9660

- CHANGELOG
- arangod/Aql/AqlFunctionFeature.cpp
- arangod/Aql/Functions.cpp
- arangod/Aql/Functions.h
- lib/Geo/ShapeContainer.cpp
- lib/Geo/ShapeContainer.h
- lib/Geo/Utils.cpp
- lib/Geo/Utils.h
- tests/Geo/ShapeContainerTest.cpp
> Add area calculations

- 3rdParty/iresearch/core/analysis/text_token_stream.cpp
- arangod/IResearch/IResearchAnalyzerFeature.cpp
- arangod/IResearch/IResearchAnalyzerFeature.h
- arangod/IResearch/IResearchLinkHelper.cpp
- arangod/RestHandler/RestAnalyzerHandler.cpp
- arangod/RestHandler/RestAnalyzerHandler.h
- arangod/V8Server/v8-analyzers.cpp
- tests/IResearch/IResearchAnalyzerFeature-test.cpp
- tests/RestHandler/RestAnalyzerHandler-test.cpp
- tests/V8Server/v8-analyzers-test.cpp
- tests/js/common/aql/aql-view-arangosearch-ddl-cluster.js
- tests/js/common/aql/aql-view-arangosearch-ddl-noncluster.js
- tests/js/common/aql/aql-view-arangosearch-feature.js
Fix for issue #9652
Fixed analyzer names resolving in DDL requests
Added tests
Backport to 3.5 will be needed
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/5672/
> Bug fix/issue #9652

- 3rdParty/iresearch/core/analysis/text_token_stream.cpp
- CHANGELOG
- arangod/IResearch/IResearchAnalyzerFeature.cpp
- arangod/IResearch/IResearchAnalyzerFeature.h
- arangod/IResearch/IResearchLinkHelper.cpp
- arangod/IResearch/IResearchLinkMeta.cpp
- arangod/RestHandler/RestAnalyzerHandler.cpp
- arangod/RestHandler/RestAnalyzerHandler.h
- arangod/V8Server/v8-analyzers.cpp
- arangod/V8Server/v8-views.cpp
- tests/IResearch/IResearchAnalyzerFeature-test.cpp
- tests/IResearch/IResearchLinkHelper-test.cpp
- tests/IResearch/IResearchLinkMeta-test.cpp
- tests/RestHandler/RestAnalyzerHandler-test.cpp
- tests/V8Server/v8-analyzers-test.cpp
- tests/js/common/aql/aql-view-arangosearch-ddl-cluster.js
- tests/js/common/aql/aql-view-arangosearch-ddl-noncluster.js
- tests/js/common/aql/aql-view-arangosearch-feature.js
- tests/js/common/shell/shell-view-arangosearch.js
Port of issue #9652 fix from devel
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/5722/
> Porting fix for issue #9652

- arangod/Aql/SharedQueryState.cpp
- arangod/Cache/CacheManagerFeature.cpp
- arangod/Pregel/Conductor.cpp
- arangod/Pregel/GraphStore.cpp
- arangod/Pregel/PregelFeature.cpp
- arangod/Pregel/Recovery.cpp
- arangod/Pregel/Worker.cpp
- arangod/Replication/InitialSyncer.cpp
- arangod/RestHandler/RestShutdownHandler.cpp
- arangod/Scheduler/Scheduler.cpp
- arangod/Scheduler/Scheduler.h
- arangod/Transaction/ManagerFeature.cpp
- arangod/VocBase/Methods/Tasks.cpp
- arangod/VocBase/Methods/Tasks.h
- lib/Basics/FunctionUtils.cpp
- lib/Basics/FunctionUtils.h
- lib/CMakeLists.txt
Enterprise PR: https://github.com/arangodb/enterprise/pull/286
Jenkins: http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/5685/
> Check scheduler queue return value.

- CHANGELOG
- lib/Utilities/ShellBase.cpp
backport of https://github.com/arangodb/arangodb/pull/9742
> Bug fix 3.5/fix arangosh documentation paste

- CHANGELOG
- lib/Utilities/ShellBase.cpp
backport of https://github.com/arangodb/arangodb/pull/9742
> Bug fix 3.4/fix arangosh documentation paste

- CHANGELOG
Cite bug number in the changelog entry..
> Changelog 3.4.8

- CHANGELOG
- arangod/Aql/SharedQueryState.cpp
- arangod/Cache/CacheManagerFeature.cpp
- arangod/Pregel/Conductor.cpp
- arangod/Pregel/GraphStore.cpp
- arangod/Pregel/PregelFeature.cpp
- arangod/Pregel/Recovery.cpp
- arangod/Pregel/Worker.cpp
- arangod/Replication/InitialSyncer.cpp
- arangod/RestHandler/RestShutdownHandler.cpp
- arangod/Scheduler/Scheduler.cpp
- arangod/Scheduler/Scheduler.h
- arangod/Transaction/ManagerFeature.cpp
- arangod/VocBase/Methods/Tasks.cpp
- arangod/VocBase/Methods/Tasks.h
- lib/Basics/FunctionUtils.cpp
- lib/Basics/FunctionUtils.h
- lib/CMakeLists.txt
Backport of https://github.com/arangodb/arangodb/pull/9754
Jenkins: http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/5778/
> [3.5] Check scheduler queue return value

- arangod/IResearch/IResearchAnalyzerFeature.cpp
- arangod/IResearch/IResearchAnalyzerFeature.h
- arangod/RestServer/DatabaseFeature.cpp
- tests/js/common/aql/aql-view-arangosearch-ddl-cluster.js
- tests/js/common/aql/aql-view-arangosearch-ddl-noncluster.js
Added ArangoSearch analyzers invalidation as part of database drop procedure.
Added tests.
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/5824/
> Bug fix/internal issue #622

- CHANGELOG
- arangod/IResearch/IResearchAnalyzerFeature.cpp
- arangod/IResearch/IResearchAnalyzerFeature.h
- arangod/RestServer/DatabaseFeature.cpp
- tests/js/common/aql/aql-view-arangosearch-ddl-cluster.js
- tests/js/common/aql/aql-view-arangosearch-ddl-noncluster.js
Port of fix for internal issue #622 for 3.5
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/5834/
> Bug fix 3.5/internal issue #622

- CHANGELOG
- arangod/IResearch/IResearchFilterFactory.cpp
- tests/IResearch/IResearchFilterIn-test.cpp
- tests/IResearch/IResearchQueryIn-test.cpp
- tests/IResearch/IResearchQueryInRange-test.cpp
- tests/js/common/aql/aql-view-arangosearch-cluster.js
- tests/js/common/aql/aql-view-arangosearch-noncluster.js
Fix for issue  #9795 
Fixed building ArangoSearch filter for NOT IN clause
Added tests for NOT IN / NOT IN_RANGE clauses.
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/5870/
> Bug fix 3.4/issue #9795

- CHANGELOG
- adds the number of the internal issue in a changelog entry
> Changelog 3408

- CHANGELOG
- lib/Geo/GeoJson.cpp
Improve the error messages for loop validation
- [x ] Bug-Fix for *devel-branch* (i.e. no need for backports?)
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/7580/
> Improve error messages for loop validation

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/aardvark.js
Same as: https://github.com/arangodb/arangodb/pull/9831
ALready reviewed.
> Bug fix 3.5/ui optimize graph load

- CHANGELOG
- lib/Geo/GeoJson.cpp
Improve the error messages for loop validation
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/7581/
>  Improve error messages for loop validation 

- CHANGELOG
- lib/Utilities/ShellBase.cpp
backport of https://github.com/arangodb/arangodb/pull/9742
> Bug fix 3.3/fix arangosh documentation paste

- js/apps/system/_admin/aardvark/APP/foxxes.js
- js/apps/system/_admin/aardvark/APP/frontend/js/arango/arango.js
- js/apps/system/_admin/aardvark/APP/frontend/js/collections/foxxCollection.js
- js/apps/system/_admin/aardvark/APP/frontend/js/views/foxxRepoView.js
- js/apps/system/_admin/aardvark/APP/frontend/js/views/installGitHubServiceView.js
- js/apps/system/_admin/aardvark/APP/frontend/js/views/installNewServiceView.js
- js/apps/system/_admin/aardvark/APP/frontend/js/views/installUploadServiceView.js
- js/apps/system/_admin/aardvark/APP/frontend/js/views/installUrlServiceView.js
This is an attempt to fix the underlying issue in #9719.
> Bug fix/curb aardvark foxx cthulhu

- CHANGELOG
- arangod/RocksDBEngine/RocksDBPrimaryIndex.cpp
- tests/js/server/aql/aql-primary-index-noncluster.js
Fix Github issue #9862
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5964/
> fixed issue #9862

- CHANGELOG
- arangod/Aql/RestAqlHandler.cpp
- arangod/Graph/GraphOperations.cpp
- arangod/Graph/GraphOperations.h
- arangod/RestHandler/RestCursorHandler.cpp
- arangod/RestHandler/RestGraphHandler.cpp
- arangod/RestHandler/RestVocbaseBaseHandler.cpp
- arangod/RestHandler/RestVocbaseBaseHandler.h
- arangod/V8Server/v8-general-graph.cpp
- tests/js/client/shell/shell-graph-transaction.js
Make graphs in general-graph transaction aware
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/302
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/5945/
> make graphs transaction-aware

- CHANGELOG
- arangod/Cluster/ServerState.cpp
- arangod/Cluster/ServerState.h
Backport of https://github.com/arangodb/arangodb/pull/9860 for 3.5.
Additionally:
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/5962/
> check for duplicate server endpoints on cluster startup

- CHANGELOG
- arangod/Agency/Agent.cpp
- arangod/Cluster/ClusterMethods.cpp
- tests/js/common/shell/shell-babies.js
Fix non-deterministic occurrences of "document not found" errors when doing multi-document lookups on a sharded collection with custom shard keys
This change is already covered by existing tests, such as *babies tests, but only partly covered*.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/5977/
> Bug fix 3.4/babies unknown shard

- arangod/Cluster/ClusterMethods.cpp
- arangod/VocBase/Methods/Collections.cpp
- tests/js/common/shell/shell-view-arangosearch.js
Fix test `audit_client` and `audit_server` in cluster mode.
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/307
Oskar companion PR: https://github.com/arangodb/oskar/pull/173
This change is already covered by existing tests, such as *audit_client*.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/6002/
> fix audit test

- tests/js/client/shell/shell-analyzer-rest-api.js
- tests/js/common/shell/shell-view-arangosearch.js
Bug fix for missing cleanup in tests.
Once always missing
Other missing on failure, causing side effects in same suite.
No production change.
Jenkins:
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/6047/
> Added cleanup for analyzer test and view test

- CHANGELOG
- arangod/Aql/IResearchViewNode.cpp
- arangod/IResearch/IResearchFeature.cpp
- tests/IResearch/IResearchFilterBoolean-test.cpp
- tests/IResearch/IResearchQueryMinMatch-test.cpp
- tests/IResearch/IResearchQueryPhrase-test.cpp
- tests/IResearch/IResearchQueryScorer-test.cpp
- tests/js/common/aql/aql-view-arangosearch-cluster.inc
- tests/js/common/aql/aql-view-arangosearch-noncluster.js
Port of fix for internal issue #633 to 3.5
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/6033/
> Bug fix 3.5/internal issue #633

- arangod/Cluster/ClusterComm.h
- [*] Bug-Fix for *devel-branch* (i.e. no need for backports?)
- [*] There are tests in an external testing repository (i.e. node-resilience tests, chaos tests): go-driver tests
> Sort out google cloud storage as remote.

- tests/IResearch/IResearchQueryOptimization-test.cpp
This is just a refactoring of a single google test file.
Previously it compiled ~15minutes (on my machine) now it is sub minute.
> Bug fix/refactor i research query optimization test

- CHANGELOG
- arangod/Aql/ExecutionPlan.cpp
- arangod/Cluster/ClusterInfo.h
- arangod/Network/Methods.cpp
- arangod/Statistics/ServerStatistics.h
Fix various issues reported by cppcheck
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/6153/
> various issues reported by cppcheck

- arangod/Cluster/FollowerInfo.h
Assertion only fix.
Maintainer mode only, no effect on production.
Jenkins:
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/6170/
> Fixed and enabled an accidentially disabled assertion

- arangod/Cluster/FollowerInfo.h
No Production Change.
Fixed an accidentally disabled assertion.
Jenkins:
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/6171/
> Bug fix 3.5/fixed disabled assertion follower info

- arangod/IResearch/IResearchAnalyzerFeature.cpp
- arangod/IResearch/IResearchLinkMeta.cpp
- arangod/RestHandler/RestAnalyzerHandler.cpp
- arangod/V8Server/v8-analyzers.cpp
Removes undesired attempts to load external library for analyzer features
This change is a trivial rework / code cleanup without any test covera
https://jenkins.arangodb.biz/job/arangodb-matrix-pr-linux/7871/
> Bug fix internal issue #635

- CHANGELOG
- arangod/IResearch/IResearchFeature.cpp
- arangod/IResearch/IResearchViewNode.cpp
- tests/IResearch/IResearchFilterBoolean-test.cpp
- tests/IResearch/IResearchQueryComplexBoolean-test.cpp
- tests/IResearch/IResearchQueryPhrase-test.cpp
- tests/js/common/aql/aql-view-arangosearch-cluster.js
- tests/js/common/aql/aql-view-arangosearch-noncluster.js
Port for fix internal issue #633 to 3.4
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/6064/
> Bug fix 3.4/internal issue #633

- CHANGELOG
- js/client/modules/@arangodb/general-graph.js
- js/common/modules/@arangodb/general-graph-common.js
- tests/js/common/shell/general-graph-creation-cluster-spec.js
- tests/js/common/shell/shell-general-graph.js
Same as: https://github.com/arangodb/arangodb/pull/9926
> Bug fix 3.4/arangosh gharial vertex deletion

- arangod/Aql/ShortestPathNode.cpp
- arangod/Cluster/ClusterMethods.cpp
- arangod/Cluster/ClusterMethods.h
- arangod/GeneralServer/HttpCommTask.cpp
- arangod/GeneralServer/VstCommTask.cpp
- arangod/IResearch/IResearchViewCoordinator.cpp
- arangod/MMFiles/MMFilesCollection.cpp
- arangod/MMFiles/MMFilesEdgeIndex.cpp
- arangod/MMFiles/MMFilesRestReplicationHandler.cpp
- arangod/Network/Methods.cpp
- arangod/Network/Utils.cpp
- arangod/Network/Utils.h
- arangod/RestHandler/RestDocumentHandler.cpp
- arangod/RestHandler/RestDocumentHandler.h
- arangod/RestHandler/RestVocbaseBaseHandler.cpp
- arangod/Transaction/Helpers.cpp
- arangod/Transaction/Methods.cpp
- arangod/Transaction/Methods.h
- arangod/Utils/OperationResult.h
Make update / replace non blocking in the REST API
This change is already covered by existing tests, such as all existing http tests
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/6157/
> Non block modify

- CHANGELOG
- arangod/Aql/ConstrainedSortExecutor.cpp
- arangod/Aql/ConstrainedSortExecutor.h
- arangod/Aql/ExecutionBlockImpl.cpp
- arangod/Aql/OutputAqlItemRow.h
- tests/js/server/aql/aql-queries-optimizer-sort-limit.js
Backport of https://github.com/arangodb/arangodb/pull/9981
> [3.5] Make AQL's constrained heap play nice with fullCount

- arangod/GeneralServer/GeneralCommTask.cpp
- arangod/GeneralServer/GeneralCommTask.h
- arangod/GeneralServer/HttpCommTask.cpp
Catch unhandled protocl exceptions
This change is already covered by existing tests
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/6245/
> Catch unhandled exceptions

- arangod/Aql/ConstrainedSortExecutor.cpp
- js/server/modules/@arangodb/aql-profiler-test-helper.js
- tests/js/server/aql/aql-profiler.js
- tests/js/server/aql/aql-queries-optimizer-sort-limit.js
Backport of https://github.com/arangodb/arangodb/pull/10010.
> [3.5] Additional sort-limit tests

- CHANGELOG
- arangod/Aql/OptimizerRule.h
- arangod/Aql/OptimizerRules.cpp
- tests/js/server/aql/aql-queries-optimizer-sort-limit.js
> [3.5] Bug fix/sort limit rule too lax

- arangod/Cluster/ClusterMethods.cpp
- arangod/Pregel/Algos/AsyncSCC.cpp
- arangod/Pregel/Algos/SCC.cpp
- lib/Logger/LogAppenderFile.cpp
Minor fixes:
- Fixed ODR violation in Pregel
- Removed unused code in ClusterMethods
- Avoid possible uninitialized variable usage
> Fixed some problems found with IPO enabled

- CHANGELOG
- arangod/Cluster/v8-cluster.cpp
- tests/js/client/active-failover/basic.js
Backport of https://github.com/arangodb/arangodb/pull/9881
> [3.4] Bug fix 3.4/allow agency ops in active failover

- arangod/Cluster/ClusterInfo.cpp
- arangod/Cluster/ClusterInfo.h
- arangod/Cluster/ClusterMethods.cpp
- arangod/Cluster/ClusterTypes.h
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/6362/
> rebootIds instead of boot stamps

- lib/Basics/ArangoGlobalContext.cpp
> Extended the range of a suppressed warning for MSVC

- CHANGELOG
- arangod/Aql/Functions.cpp
- js/common/modules/@arangodb/aql/explainer.js
- tests/js/server/aql/aql-functions-list.js
Fix Github issue #10062 
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/6404/
> fixed issue #10062: AQL: Could not extract custom attribute

- arangod/Aql/OptimizerRules.cpp
- arangod/RocksDBEngine/RocksDBFulltextIndex.h
- tests/js/server/aql/aql-optimizer-rule-use-index-for-sort-noncluster.js
- tests/js/server/aql/aql-optimizer-rule-use-index-for-sort.js
Fix Github issue #10078
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/6430/
> Bug fix/issue 10078

- arangosh/Backup/BackupFeature.cpp
> Documentation 3.5/arangobackup ops

- CHANGELOG
- arangod/Aql/OptimizerRules.cpp
- arangod/RocksDBEngine/RocksDBFulltextIndex.h
- tests/js/server/aql/aql-optimizer-rule-use-index-for-sort-noncluster.js
- tests/js/server/aql/aql-optimizer-rule-use-index-for-sort.js
Fix Github issue #10078
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/6432/
> Bug fix 3.4/issue 10078

- tests/IResearch/IResearchAnalyzerFeature-test.cpp
Fixes (valid) compiler warnings.
Jenkins: https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/6473/
> Fix handling of systemdb pointer (warnings).

- arangod/Agency/Agent.cpp
- arangod/Agency/Agent.h
- arangod/Agency/Constituent.h
- arangod/Agency/Supervision.h
- arangod/Aql/BlocksWithClients.cpp
- arangod/Aql/BlocksWithClients.h
- arangod/Aql/ExpressionContext.h
- arangod/Aql/Functions.cpp
- arangod/Aql/QueryExpressionContext.cpp
- arangod/Aql/QueryExpressionContext.h
- arangod/Cluster/ClusterComm.h
- arangod/Pregel/Recovery.h
- arangod/Replication/ReplicationApplierConfiguration.h
- arangod/RestServer/DatabaseFeature.h
- arangod/RocksDBEngine/RocksDBEventListener.h
- arangod/Statistics/StatisticsFeature.cpp
- arangod/StorageEngine/HotBackup.h
- lib/Basics/Thread.cpp
- lib/Basics/Thread.h
Various small issues:
- use explicit constructors
- remove attribute from Agent that is also inherited from its base class
- simplify query kill logic
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/6468/
> Bug fix/cppcheck issues

- arangod/Agency/AgentCallback.cpp
Fix Windows compile error from a previous branch that got merged without Windows Jenkins test. https://github.com/arangodb/arangodb/pull/10110
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-windows/578/
> Fix Windows compile error from network namespace.

- arangod/Graph/GraphManager.cpp
- arangod/Sharding/ShardingInfo.cpp
- tests/js/server/shell/shell-general-graph-creation-cluster.js
Honor sharding & replication restrictions when creating general graphs and smart graphs
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/334
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/6533/
> honor restrictions when creating graphs

- arangod/Cluster/ClusterFeature.cpp
- arangod/Graph/GraphManager.cpp
- tests/js/server/shell/shell-general-graph-creation-cluster.js
Honor sharding & replication restrictions also when creating a new graph based on existing collections.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/6555/
> Bug fix 3.5/honor sharding restrictions

- arangod/Aql/KShortestPathsExecutor.cpp
- arangod/Aql/KShortestPathsNode.cpp
- arangod/Aql/ShortestPathNode.cpp
- arangod/Aql/TraversalExecutor.cpp
- arangod/Graph/KShortestPathsFinder.cpp
- tests/js/server/aql/aql-graph-traverser.js
Fixed issue #10158
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/6583/
> fixed issue #10158

- arangod/Aql/InputAqlItemRow.cpp
- arangod/Aql/InputAqlItemRow.h
Improve performance decline of AQL sort through #10025 again.
> Implement copying/moving constructors of InputAqlItemRow

- arangosh/Backup/BackupFeature.cpp
Add for which backup operation an option is meant
> Docs: Add which option is used by which ArangoBackup operation

- js/client/modules/@arangodb/result-processing.js
- scripts/examine_results.js
fixes counting of failed testcases in a testsuite for the result summary.
- have a testsuite fail some tests
- run testsuite containing these failures
- count of tests should equal those failed:
```
* Overall state: Fail
Suites failed: 1 Tests Failed: 3
```
> Bug fix/result evaluation test counting

- arangod/VocBase/VocbaseInfo.cpp
- arangod/VocBase/VocbaseInfo.h
- arangod/VocBase/vocbase.cpp
- arangod/VocBase/vocbase.h
> first small clean-up pr

- CHANGELOG
See https://github.com/arangodb/arangodb/pull/10190
> Updated CHANGELOG regarding #10190

- tests/js/common/aql/aql-view-arangosearch-cluster.inc
- tests/js/common/aql/aql-view-arangosearch-noncluster.js
Tests for https://github.com/arangodb/arangodb/pull/10164.
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/6654/
> Add tests for issue #10090

- 3rdParty/iresearch/core/search/conjunction.hpp
- 3rdParty/iresearch/core/search/phrase_iterator.hpp
- CHANGELOG
- tests/js/common/aql/aql-view-arangosearch-cluster.inc
- tests/js/common/aql/aql-view-arangosearch-noncluster.js
Fixed repeatable seek to the same document
Backport https://github.com/arangodb/arangodb/pull/10164
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-linux/8294/
> Bug fix 3.5/issue #10090

- arangosh/Utils/ManagedDirectory.cpp
backport of https://github.com/arangodb/arangodb/pull/10201
> Bug fix 3.4/dont scan recursive for whether dir empty

- arangosh/Utils/ManagedDirectory.cpp
backport of https://github.com/arangodb/arangodb/pull/10201
> Bug fix 3.5/dont scan recursive for whether dir empty

- CHANGELOG
- lib/Basics/FileUtils.cpp
- lib/Basics/files.cpp
backport of https://github.com/arangodb/arangodb/pull/10073
> Fix windows path handling not to slip into UNC lookup (#10073)

- arangod/Aql/ExecutionBlock.cpp
- arangod/Aql/RemoteExecutor.cpp
- arangod/Aql/RemoteExecutor.h
- arangod/Aql/SharedQueryState.cpp
- arangod/Aql/SharedQueryState.h
Fix some races in the RemoteExecutor
> Bug fix/fix remote executor races

- 3rdParty/fuerte/include/fuerte/message.h
- 3rdParty/fuerte/include/fuerte/types.h
- arangod/ClusterEngine/ClusterCollection.cpp
- arangod/ClusterEngine/ClusterCollection.h
- arangod/MMFiles/MMFilesCollection.h
- arangod/MMFiles/MMFilesCollectionExport.cpp
- arangod/MMFiles/MMFilesCollectionKeys.cpp
- arangod/MMFiles/MMFilesIncrementalSync.h
- arangod/RestHandler/RestCollectionHandler.cpp
- arangod/RocksDBEngine/RocksDBMetaCollection.cpp
- arangod/RocksDBEngine/RocksDBMetaCollection.h
- arangod/StorageEngine/PhysicalCollection.h
- arangod/Transaction/Methods.cpp
- arangod/Transaction/Methods.h
- arangod/V8Server/v8-query.cpp
- arangod/VocBase/LogicalCollection.cpp
- arangod/VocBase/LogicalCollection.h
- arangod/VocBase/Methods/Collections.cpp
- arangod/VocBase/Methods/Collections.h
- arangosh/Shell/V8ClientConnection.cpp
- tests/Mocks/StorageEngineMock.cpp
- tests/Mocks/StorageEngineMock.h
Remove old CRUD api
This change is already covered by existing tests, such as all mmfiles replication tests
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/6677/
> Remove invokeOnAllElements

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/manifest.json
This is a port of #10215 to devel.
> [devel] Fix document search (Ctrl+F/Cmd+F)

- 3rdParty/iresearch/core/search/conjunction.hpp
- 3rdParty/iresearch/core/search/phrase_iterator.hpp
- CHANGELOG
- tests/js/common/aql/aql-view-arangosearch-cluster.js
- tests/js/common/aql/aql-view-arangosearch-noncluster.js
Fixed repeatable seek to the same document
Backport #10164
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-linux/8366/
> Bug fix 3.4/issue #10090

- lib/Logger/LoggerFeature.cpp
> Doc - Added "log-output" example

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/manifest.json
Same as: https://github.com/arangodb/arangodb/pull/10215
> Bug fix 3.4/aardvark document search

- CHANGELOG
- arangod/Agency/Store.cpp
- arangod/Agency/Store.h
- tests/Agency/StoreTest.cpp
Backport of https://github.com/arangodb/arangodb/pull/10189
This change is already covered by existing tests, such as *scripts/unittest agency*.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/6691/
> Improved performance of some agency helper functions.

- arangod/GeneralServer/RestHandler.cpp
HEAD-requests shouldn't send a body. This is true for vst and HTTP. 
Right now we may answer VST  head-requests with an error boddy. 
This is incompatible API behaviour i.e. in case of checking the existence of documents using HEAD requests.
> if we answer a head request, we mustn't create a body for errors

- arangod/Cluster/ClusterInfo.cpp
- arangod/Cluster/HeartbeatThread.cpp
- arangod/ClusterEngine/ClusterEngine.cpp
- arangod/ClusterEngine/ClusterEngine.h
- arangod/MMFiles/MMFilesEngine.cpp
- arangod/MMFiles/MMFilesEngine.h
- arangod/MMFiles/MMFilesWalRecoverState.cpp
- arangod/RestHandler/RestAdminServerHandler.cpp
- arangod/RestServer/DatabaseFeature.cpp
- arangod/RestServer/DatabaseFeature.h
- arangod/RocksDBEngine/RocksDBEngine.cpp
- arangod/RocksDBEngine/RocksDBEngine.h
- arangod/StorageEngine/StorageEngine.h
- arangod/VocBase/Methods/Databases.cpp
- arangod/VocBase/VocbaseInfo.cpp
- arangod/VocBase/VocbaseInfo.h
- arangod/VocBase/vocbase.cpp
- arangod/VocBase/vocbase.h
- tests/IResearch/IResearchView-test.cpp
- tests/Mocks/StorageEngineMock.cpp
- tests/Mocks/StorageEngineMock.h
devel only
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/6728/
> more vocbase clean up

- 3rdParty/iresearch/appveyor.yml
- 3rdParty/iresearch/core/shared.hpp
- 3rdParty/iresearch/core/utils/attributes.hpp
- 3rdParty/iresearch/core/utils/block_pool.hpp
- 3rdParty/iresearch/tests/index/consolidation_policy_tests.cpp
- 3rdParty/iresearch/tests/index/index_tests.cpp
- 3rdParty/iresearch/tests/utils/async_utils_tests.cpp
- 3rdParty/iresearch/tests/utils/object_pool_tests.cpp
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/6749/
> Merge changes related to VS2019 support from IResearch upstream

- 3rdParty/fuerte/include/fuerte/message.h
- 3rdParty/fuerte/src/HttpConnection.cpp
- arangod/Network/Methods.cpp
- lib/Futures/Future.h
- lib/Futures/Promise.h
- lib/Futures/SharedState.h
micro improvements for Future and friends
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/6770/
> micro improvements for futures

- arangod/Aql/EnumerateListExecutor.cpp
- tests/js/server/aql/aql-queries-simple.js
Fix Github issue #10270 
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/6774/
> fixed issue #10270

- CHANGELOG
- arangod/Cluster/v8-cluster.cpp
- js/client/tests/active-failover/basic.js
> [3.3] Bug fix 3.3/allow agency ops in active failover

- arangod/Aql/Functions.cpp
- arangod/Cluster/ClusterMethods.cpp
- arangod/GeneralServer/HttpCommTask.cpp
- arangod/IResearch/IResearchFilterFactory.cpp
- arangod/IResearch/IResearchViewSort.cpp
- arangod/RestHandler/RestBatchHandler.cpp
- arangod/RestHandler/RestEdgesHandler.cpp
- arangod/Scheduler/SupervisedScheduler.cpp
- arangod/VocBase/Methods/AqlUserFunctions.cpp
- lib/Basics/StringUtils.cpp
- lib/Basics/StringUtils.h
- lib/Futures/SharedState.h
- lib/Geo/GeoJson.cpp
- lib/Rest/HttpRequest.cpp
- lib/Rest/HttpResponse.cpp
- lib/Rest/VstResponse.cpp
- lib/SimpleHttpClient/SimpleHttpResult.cpp
- lib/V8/v8-utils.cpp
- tests/Basics/StringUtilsTest.cpp
Make StringUtils::tolower|toupper not depend on selected locale, and make it fast.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/6804/
> micro optimizations for case conversion

- lib/Basics/xxh3.h
- lib/Basics/xxhash.cpp
- lib/Basics/xxhash.h
Upgrade bundled version of xxhash library
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/6897/
> upgrade xxhash library version

- arangod/Cluster/ClusterMethods.cpp
Make coordinator handling database servers a bit more resilient when at least one shard cannot send the answer due to database/collection not found.
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/6929/
> try to make coordinator more resilient when database/collection does not exist

- 3rdParty/fuerte/src/vst.cpp
- arangosh/Shell/V8ClientConnection.cpp
- js/client/modules/@arangodb/foxx/manager.js
- allow sending custom content-types for accept and content-type header
- use it to upload with proper content type.
> fix custom contenttype handling, set upload contenttype

- arangod/Aql/EngineInfoContainerDBServer.cpp
- arangod/Cluster/ClusterTrxMethods.cpp
Fix the cleanup of AQL engines, add another sanity check for el-cheapo
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/8735/
> fix cleanupEngines, add another sanity check

- arangod/Aql/QueryString.h
- arangod/IResearch/IResearchAnalyzerFeature.cpp
- arangod/IResearch/IResearchAnalyzerFeature.h
- tests/IResearch/IResearchAnalyzerFeature-test.cpp
fixes for analyzer related issues with rolling upgrade
> bug-fix/internal-issue-#652

- js/actions/api-cluster.js
Store a removed dbserver with date of removal in the agency.
> Store a removed server with date in the agency.

- 3rdParty/fuerte/src/vst.cpp
- arangod/Cluster/ClusterInfo.cpp
Fix small issues (compile error in Debug mode in fuerte) plus added assertions for ClusterInfo
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7078/
> small fixes

- arangod/Graph/KShortestPathsFinder.cpp
- arangod/Graph/KShortestPathsFinder.h
- tests/Graph/GraphTestTools.h
- tests/Graph/KShortestPathsFinder.cpp
Fixes #10371 (see also internal planning ticket).
This change is already covered by existing tests, such as the K_SHORTEST_PATHS C++ and unit tests. This PR also adds tests that were used to verify all changes:
> Bug fix for K_SHORTEST_PATHS

- CHANGELOG
- arangod/Graph/KShortestPathsFinder.cpp
- arangod/Graph/KShortestPathsFinder.h
- tests/Graph/GraphTestTools.h
- tests/Graph/KShortestPathsFinder.cpp
> Bug fix 3.5/k shortest paths

- CHANGELOG
- js/server/modules/@arangodb/foxx/manager.js
This seems unnecessary and never worked in the cluster.
> Remove code which puts system services to _app.

- arangod/Replication/utilities.cpp
- arangod/RocksDBEngine/RocksDBIncrementalSync.cpp
Fix the error messages in the syncer code
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-linux/8914/
> Improve syncer error message

- arangod/Aql/ClusterNodes.cpp
- arangod/Aql/SortingGatherExecutor.cpp
- tests/js/server/aql/aql-optimizer-rule-parallelize-gather-cluster.js
Fetch data from all dependencies in the initialization phase of the `SortingGatherExecutor`
This change is already covered by existing tests, such as the _shell_server_aql_ testsuite
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-linux/8918/
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/7136/
> Parallel SortingGatherExecutor

- arangod/Aql/Query.cpp
- arangod/Aql/QueryResultV8.h
- arangod/Statistics/figures.h
- arangod/V8Server/v8-query.cpp
- arangod/V8Server/v8-vocbase.cpp
Fix very minor issues found by cppcheck
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7172/
> fix issues found by cppcheck

- arangosh/CMakeLists.txt
See PR title
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7170/
> rename `lib_libarango_shell` to `libarango_shell`.

- arangod/Aql/IResearchViewOptimizerRules.cpp
- arangod/Aql/IResearchViewOptimizerRules.h
- arangod/Aql/IndexNodeOptimizerRules.cpp
- arangod/Aql/IndexNodeOptimizerRules.h
- tests/js/server/aql/aql-optimizer-rule-late-document-materialization-arangosearch.js
- tests/js/server/aql/aql-optimizer-rule-late-document-materialization-rocksdb.js
Reverts arangodb/arangodb#10439
> Revert "Fixed applying late materialization with calc node between sort an limit"

- arangod/Aql/IResearchViewOptimizerRules.cpp
- arangod/Aql/IResearchViewOptimizerRules.h
- arangod/Aql/IndexNodeOptimizerRules.cpp
- arangod/Aql/IndexNodeOptimizerRules.h
- tests/js/server/aql/aql-optimizer-rule-late-document-materialization-arangosearch.js
- tests/js/server/aql/aql-optimizer-rule-late-document-materialization-rocksdb.js
fix late materialization used after sort
> Bug fix/fix late materialization used after sort

- arangod/Aql/SingleRowFetcher.cpp
Fix a compile error on windows when google tests are disabled.
> Fix template instantiation for MSVC

- Documentation/DocuBlocks/Rest/Cursors/post_api_cursor.md
Add missing option to docublock
> add timeout to docublock

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/collections/arangoDocuments.js
- js/apps/system/_admin/aardvark/APP/frontend/js/views/documentsView.js
Yep, that fix needs to be backported aswell. 
Please see issue: https://github.com/arangodb/arangodb/issues/10470
There is a description that describes how to reproduce. The reported failure should not happen anymore (No error message was displayed in case of an error).
https://github.com/arangodb/arangodb/issues/10470
> fixing issue #10470

- tests/js/client/shell/shell-inventory-cluster.js
- tests/js/client/shell/shell-inventory-noncluster.js
Added tests for `/_api/replication/inventory` and `/_api/replication/clusterInventory`
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7306/
> add tests for inventory (#10464)

- arangod/Auth/User.cpp
- arangod/Auth/UserManager.cpp
- arangod/Cluster/ClusterRepairOperations.cpp
- arangod/Replication/SyncerId.cpp
- arangod/Utils/CollectionNameResolver.cpp
- arangod/Utils/UrlHelper.cpp
- lib/Basics/FloatingPoint.h
- lib/Basics/StringUtils.cpp
- lib/Basics/conversions.cpp
- lib/Geo/GeoJson.cpp
- lib/V8/v8-utils.cpp
Remove usage of (mostly locale-dependent) cctype functons
Enterprise companion PR: https://github.com/arangodb/enterprise/pull/364
No extra tests added in this PR. However, none of the existing tests should fail.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7314/
> remove cctype

- 3rdParty/iresearch/core/analysis/ngram_token_stream.cpp
- arangod/IResearch/IResearchAnalyzerFeature.cpp
> fix compilation on mac

- CHANGELOG
> Update CHANGELOG regarding spliced subqueries, gather and remote

- arangod/GeneralServer/HttpCommTask.cpp
Follow up to https://github.com/arangodb/arangodb/pull/10474
> Put the write into the IoContext.

- arangod/Aql/ExecutionBlockImpl.cpp
> Set internal state to DONE when upstream is DONE

- arangod/Cluster/ClusterComm.h
- arangod/GeneralServer/CommTask.cpp
- arangod/GeneralServer/CommTask.h
- arangod/GeneralServer/HttpCommTask.cpp
- arangod/GeneralServer/HttpCommTask.h
- arangod/GeneralServer/VstCommTask.cpp
- js/server/modules/@arangodb/cluster.js
- lib/Basics/StaticStrings.cpp
- lib/Basics/StaticStrings.h
- lib/Rest/HttpRequest.cpp
- lib/Rest/HttpRequest.h
Make some performance changes to comm tasks
This change is already covered by existing tests, such as all of them.
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr-linux/9134/
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/7362/
> Make some changes to Comm Tasks

- CHANGELOG
- Documentation/DocuBlocks/Rest/Cursors/post_api_cursor.md
- arangod/Aql/Query.cpp
- arangod/Aql/Query.h
- arangod/Aql/QueryOptions.cpp
- arangod/Aql/QueryOptions.h
- tests/js/server/aql/aql-options.js
> rename timeout to maxRuntime

- tests/rb/HttpInterface/api-query-analysis-spec.rb
Un-greylist query-analysis-spec test and make it more robust & deterministic
This change is already covered by existing tests, such as *scripts/unittest http_server --test query-analysis*.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7415/
> ungreylist the test

- arangod/RestHandler/RestStatusHandler.cpp
- arangosh/Restore/RestoreFeature.cpp
- tests/js/client/server_permissions/test-hardened-rest-apis.js
> check before foxx-heal

- tests/js/server/upgrade-data/upgrade-data-views-msv3.2.1.js
backport of https://github.com/arangodb/arangodb/pull/10588
> Bug fix 3.4/cleanup view

- tests/js/server/upgrade-data/upgrade-data-views-msv3.2.1.js
backport of https://github.com/arangodb/arangodb/pull/10588
> Bug fix 3.5/cleanup view

- arangod/Aql/IResearchViewNode.cpp
- arangod/Aql/IndexNode.cpp
- tests/Aql/IndexNodeTest.cpp
- tests/IResearch/IResearchViewNode-test.cpp
Decapitalized json in late materialization. They were capitalized by mistake.
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/7520/
> decapitalized json in late materialization

- js/common/modules/@arangodb/aql/explainer.js
Decapitalized json in late materialization (explainer.js)
> decapitalize json in late materialization (explainer.js)

- js/client/modules/@arangodb/process-utils.js
- js/client/modules/@arangodb/test-utils.js
- js/client/modules/@arangodb/testing.js
- js/client/modules/@arangodb/testsuites/audit.js
- js/client/modules/@arangodb/testsuites/config.js
- js/client/modules/@arangodb/testsuites/dfdb.js
- js/client/modules/@arangodb/testsuites/export.js
- js/client/modules/@arangodb/testsuites/gtest.js
- js/client/modules/@arangodb/testsuites/recovery.js
- js/client/modules/@arangodb/testsuites/upgrade.js
- js/client/modules/@arangodb/testsuites/version.js
- lib/Basics/debugging.cpp
- tests/js/server/aql/aql-query-cache-noncluster.js
- tests/js/server/replication/ongoing/replication-ongoing.js
- tests/js/server/replication/static/replication-static.js
- tests/js/server/replication/sync/replication-sync.js
- tests/rb/HttpInterface/api-view-arangosearch-spec-noncluster.rb
backport of https://github.com/arangodb/arangodb/pull/10580 + more.
> wait for suicide to actually take place before we fail this

- arangod/ClusterEngine/ClusterEngine.cpp
- arangod/ClusterEngine/ClusterEngine.h
- arangod/MMFiles/MMFilesEngine.cpp
Print that MMFiles is deprecated.
Jenkins:
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/7549/
> Show MMFiles deprecation warning

- arangod/VocBase/Methods/UpgradeTasks.cpp
unconditionally create statistics collections when the database is created
it is not advisable to not create them when the statistics are turned off, because the server may later be restarted with statistics turn on. and then the collections will be missing
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7598/
> always create the statistics collections

- arangod/RestServer/MetricsFeature.cpp
- tests/rb/HttpInterface/api-statistics-spec.rb
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/7604/
> [3.6] admin statistics uptime broken

- CHANGELOG
- arangod/RestServer/MetricsFeature.cpp
- tests/rb/HttpInterface/api-statistics-spec.rb
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/7605/
> admin statistics uptime broken

- utils/jslint.sh
> allow jslint to check external files

- js/server/modules/@arangodb/aql-helper.js
- tests/js/server/aql/aql-graph-traverser.js
Same as:  https://github.com/arangodb/arangodb/pull/10638
Info: There is also an EE branch: https://github.com/arangodb/enterprise/pull/373
> Bug fix 3.6/round costs to remove costs

- arangod/MMFiles/MMFilesCollection.cpp
- arangod/MMFiles/MMFilesEngine.cpp
- arangod/RocksDBEngine/RocksDBBuilderIndex.cpp
- arangod/RocksDBEngine/RocksDBCollection.cpp
- arangod/RocksDBEngine/RocksDBEngine.cpp
- arangod/RocksDBEngine/RocksDBMetadata.cpp
- arangod/RocksDBEngine/RocksDBMetadata.h
- arangod/RocksDBEngine/RocksDBPrimaryIndex.cpp
- arangod/RocksDBEngine/RocksDBSettingsManager.cpp
- arangod/RocksDBEngine/RocksDBVPackIndex.cpp
- arangod/VocBase/LogicalCollection.cpp
- arangod/VocBase/LogicalCollection.h
- arangod/VocBase/vocbase.cpp
Backport of https://github.com/arangodb/arangodb/pull/10621
Jenkins: http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/7636/
> [3.6] avoid modifying  vector without acquiring its write-lock

- arangod/RocksDBEngine/RocksDBEngine.cpp
this is a security precaution so that when repeatedly trying to start
an instance, an instant instance failure will not lead to the disk
filling up so quickly with WAL file data.
the WAL file size is increased later on in the startup sequence, so
everything should be fine if the startup works.
this will fix a problem with the disk filling up quickly when the
arangodb starter tries to start an instance 100 times in a row but
instantaneously gets a failure back from it.
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7656/
> when starting the RocksDB engine, first create small-sized WAL files

- tests/js/server/aql/aql-graph-traverser.js
Fix a test that fails undeterministically.
The test runs a DFS traversal with an undeterministic result. The asserts in the tests didn't sufficiently account for that.
* *3.6* backport: #10694 
* *3.5* backport: #10695 
* *3.4* backport: #10696
> Bug fix/fix undeterministic traversal test

- CHANGELOG
- arangod/Graph/GraphOperations.cpp
- tests/js/common/shell/shell-general-graph.js
Same as: https://github.com/arangodb/arangodb/pull/10690
> bug-fix 3.6 single-edge-definition-editing

- tests/js/server/aql/aql-graph-traverser.js
> [3.6] Bug fix/fix undeterministic traversal test

- js/common/modules/jsunity/jsunity.js
> if we have timeouts, the SUT is unstable and we should abort to avoid lengthy useless testruns

- tests/js/common/aql/aql-view-arangosearch-feature.js
> add test (#10702)

- arangod/Aql/CalculationNodeVarFinder.cpp
- arangod/Aql/CalculationNodeVarFinder.h
- arangod/Aql/IResearchViewOptimizerRules.cpp
- arangod/Aql/IndexNodeOptimizerRules.cpp
- arangod/CMakeLists.txt
- tests/js/server/aql/aql-optimizer-rule-late-document-materialization-arangosearch-2.js
- tests/js/server/aql/aql-optimizer-rule-late-document-materialization-rocksdb.js
If a subquery uses document in not calc node do not apply optimization
> subquery uses document in not calc nodes

- arangod/Aql/OptimizerRulesFeature.cpp
Backport of https://github.com/arangodb/arangodb/pull/10717
Jenkins: http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/7727/
> Fix disabling of optimizer rules.

- 3rdParty/velocypack/include/velocypack/Serializable.h
- arangod/Agency/Supervision.cpp
- arangod/Agency/Supervision.h
- arangod/CMakeLists.txt
- arangod/Cluster/AgencyPaths.cpp
- arangod/Cluster/AgencyPaths.h
- arangod/Cluster/ClusterCollectionCreationInfo.cpp
- arangod/Cluster/ClusterCollectionCreationInfo.h
- arangod/Cluster/ClusterInfo.cpp
- arangod/Cluster/ClusterMethods.cpp
- arangod/Cluster/ServerState.cpp
- arangod/Cluster/ServerState.h
- arangod/Cluster/SynchronizeShard.cpp
- cmake/custom/ArangoDB_FindOpenSSL_WIN32.cmake
- lib/Basics/StaticStrings.cpp
- lib/Basics/StaticStrings.h
- tests/IResearch/IResearchFeature-test.cpp
- tests/IResearch/IResearchLinkCoordinator-test.cpp
- tests/Mocks/Servers.cpp
Backport of https://github.com/arangodb/arangodb/pull/10720
> [3.6] Bug fix/replace create collection safety ttl with rebootid

- CHANGELOG
- arangod/Aql/ClusterNodes.cpp
- js/client/modules/@arangodb/test-utils.js
- tests/js/client/server_permissions/test-optimizer-rules.js
- tests/js/client/server_permissions/test-parallel-gather-writes-cluster-off.js
- tests/js/client/server_permissions/test-parallel-gather-writes-cluster-on.js
Added tests for `--query.optimizer-rules` and `--query.parallelize-gather-writes`.
Fixed a bug in handling the value of `--query.parallelize-gather-writes`
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7733/
> added tests & bugfix for query options

- 3rdParty/iresearch/core/search/tfidf.cpp
- CHANGELOG
- arangod/Agency/Node.cpp
- arangod/Agency/Node.h
- tests/js/client/agency/agency-test.js
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/
> Bug fix/agency ttl handle

- tests/js/server/aql/aql-view-arangosearch-server.js
Fix for QA ticket arangodb/release-3.6#43
Reviewed code for mmfiles collection. Currently looks like this failure is test-related.
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/7747/
> Made test tolerate FS latency

- tests/js/server/aql/aql-view-arangosearch-server.js
Fix for QA ticket https://github.com/arangodb/release-3.6/issues/43
Reviewed code for mmfiles collection. Currently looks like this failure is test-related.
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/7746/
> Bug fix 3.6/fix remove arangosearch link test

- 3rdParty/velocypack/include/velocypack/Slice.h
- arangod/Agency/Node.cpp
- arangod/Agency/Node.h
Fix mismatch of integral types. Followup of https://github.com/arangodb/arangodb/pull/10731.
> Fixed integer mismatch

- arangod/Aql/CollectionAccessingNode.h
- arangod/Aql/Query.cpp
- arangod/VocBase/LogicalCollection.cpp
- arangod/VocBase/Methods/Collections.cpp
- js/client/modules/@arangodb/arango-collection.js
- js/client/modules/@arangodb/arango-database.js
- js/client/modules/@arangodb/arango-view.js
- js/common/modules/@arangodb/aql/explainer.js
* JavaScript code cleanup
* Potential formatting bugfix for AQL query explain output (for https://github.com/arangodb/release-3.6/issues/30#issuecomment-567443630)
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7782/
> clean up several js bits

- arangod/Aql/CollectionAccessingNode.h
- arangod/Aql/Query.cpp
- js/common/modules/@arangodb/aql/explainer.js
Potential formatting bugfix for AQL query explain output
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7781/
> potential formatting fix for explainer

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/collections/arangoDocuments.js
Same as: https://github.com/arangodb/arangodb/pull/10750
> Bug fix 3.6/issue 10725

- arangod/Sharding/ShardingInfo.cpp
- arangod/VocBase/Methods/Collections.cpp
- js/common/modules/jsunity/jsunity.js
- tests/js/common/shell/shell-one-shard.js
Fixes a few usability issues reported via https://github.com/arangodb/release-3.6/issues/41
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7794/
> a few usability fixes for minReplicationFactor/writeConcern

- arangod/Cluster/ClusterInfo.cpp
- tests/js/common/shell/shell-cluster-collection.js
Backport of https://github.com/arangodb/arangodb/pull/10756.
> [3.6] Bug fix/collection create failure cleanup

- Documentation/DocuBlocks/Rest/Administration/get_admin_metrics.md
- Documentation/DocuBlocks/Rest/Administration/get_api_cluster_endpoints.md
- Documentation/DocuBlocks/Rest/Analyzers/delete_api_analyzer.md
- Documentation/DocuBlocks/Rest/Analyzers/get_api_analyzer.md
- Documentation/DocuBlocks/Rest/Analyzers/get_api_analyzers.md
- Documentation/DocuBlocks/Rest/Analyzers/post_api_analyzer.md
- Documentation/DocuBlocks/Rest/BackupRestore/post_admin_backup_download.md
- Documentation/DocuBlocks/Rest/BackupRestore/post_admin_backup_upload.md
- Documentation/DocuBlocks/Rest/Collections/1_structs.md
- Documentation/DocuBlocks/Rest/Collections/post_api_collection.md
- Documentation/DocuBlocks/Rest/Database/get_api_database_current.md
- Documentation/DocuBlocks/Rest/Database/get_api_database_new.md
- Documentation/DocuBlocks/Rest/Graph/1_structs.md
- Documentation/DocuBlocks/Rest/Graph/general_graph_create_http_examples.md
- Documentation/DocuBlocks/Rest/Graph/general_graph_list_http_examples.md
- Documentation/DocuBlocks/collectionProperties.md
- Documentation/DocuBlocks/serverSSLProtocol.md
- Documentation/Scripts/codeBlockReader.py
- README_maintainers.md
- arangod/MMFiles/MMFilesCompactionFeature.cpp
Backport of #10663
https://github.com/arangodb/docs/pull/278 ✅
> Docs: More fixes for write concern (#10663)

- arangod/Replication/utilities.cpp
- arangod/RocksDBEngine/RocksDBIncrementalSync.cpp
Cherry-picked from 3.5 / devel
https://172.16.10.101/view/PR/job/arangodb-matrix-pr/7178/
> Improve syncer error message (#10404)

- CHANGELOG
- arangod/Cluster/ClusterInfo.cpp
- arangod/Cluster/ClusterInfo.h
- arangod/RestHandler/RestReplicationHandler.cpp
- arangod/RestHandler/RestReplicationHandler.h
- arangod/Utils/ExecContext.h
Similar to, same purpose: https://github.com/arangodb/arangodb/pull/10603
**This PR relies on**: https://github.com/arangodb/arangodb/pull/10539/
**and needs to be merged first.** 
After the merge of # 10539, we need to start a Jenkins run for this PR.
> Bug fix 3.4/restore feature perms

- CHANGELOG
- arangod/RestHandler/RestReplicationHandler.cpp
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/7846/
> [3.6] reboot tracking for empty rebootid

- CHANGELOG
- arangod/Aql/OptimizerRulesCluster.cpp
Backport of #10577.
The enterprise part is in https://github.com/arangodb/enterprise/pull/372.
> [3.4] Bug fix/smart bfs stack size

- CHANGELOG
- arangod/Graph/GraphOperations.cpp
- tests/js/common/shell/shell-general-graph.js
Same as: https://github.com/arangodb/arangodb/pull/10690
> bug-fix 3.4 single-edge-definition-editing 

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/collections/arangoDocuments.js
Same as: https://github.com/arangodb/arangodb/pull/10750
> fixed issue 10725

- CHANGELOG
- arangod/Cluster/ClusterInfo.cpp
- js/actions/api-cluster.js
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/7883/
> Bug fix 3.5/hot backup maintenance mode with ttl

- cmake/packages/client/nsis.txt
backport of https://github.com/arangodb/arangodb/pull/10822
> 3.4: propagate js version variable into the client package

- cmake/packages/client/nsis.txt
backport of https://github.com/arangodb/arangodb/pull/10822
> 3.5: propagate js version variable into the client package

- Documentation/DocuBlocks/Rest/Graph/general_graph_create_http_examples.md
Forward port of https://github.com/arangodb/arangodb/pull/10807
> Docs: Add missing orphanCollections property

- Documentation/DocuBlocks/Rest/Graph/general_graph_create_http_examples.md
Issue: https://github.com/arangodb/docs/issues/280
Preview PR: https://github.com/arangodb/docs/pull/288
> Add missing orphanCollections property

- lib/Logger/LogAppender.cpp
Avoid one more dynamic memory allocation for logging, by using std::function's (assumed) SSO feature.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/7958/
> slightly slightly improve logging efficiency

- js/server/modules/@arangodb/aql-helper.js
- tests/js/server/aql/aql-graph-traverser.js
Fixed test:
- tests/js/server/aql/aql-graph-traverser.js
- Execute Jenkins or
`./scripts/unittest shell_server_aql --cluster false --test tests/js/server/aql/aql-graph-traverser.js`
> changed roundCosts to removeCosts

- CHANGELOG
- Installation/Windows/Plugins/BaseDir.nsh
- Installation/Windows/Templates/NSIS.template.in
backport of https://github.com/arangodb/arangodb/pull/10832
* switch log-file location depending on all/user installation, remove on uninstall
* Update NSIS.template.in
* adjust layout
* work on texts as discussed with @kvs85
* fix wording
* Update CHANGELOG
> switch log-file location depending on all/user installation, remove on uninstallation (#10832)

- CHANGELOG
- arangod/Aql/AstNode.cpp
- arangod/Aql/AstNode.h
- arangod/Aql/ExecutionPlan.cpp
- arangod/Aql/TraversalConditionFinder.cpp
- lib/Basics/StaticStrings.cpp
- lib/Basics/StaticStrings.h
> Bug fix 3.6/ast node string compare

- CHANGELOG
- arangod/Aql/ExecutionBlockImpl.cpp
- arangod/Aql/InputAqlItemRow.cpp
- arangod/Aql/OutputAqlItemRow.cpp
- arangod/Aql/SingleRowFetcher.cpp
- arangod/Aql/SingleRowFetcher.h
- arangod/Aql/SubqueryEndExecutor.cpp
- arangod/Aql/SubqueryEndExecutor.h
- arangod/Aql/SubqueryStartExecutor.cpp
- arangod/Aql/SubqueryStartExecutor.h
- tests/Aql/SpliceSubqueryOptimizerRuleTest.cpp
Backport of https://github.com/arangodb/arangodb/pull/10865
> [3.6] Bug fix/issue 10852

- tests/js/common/shell/shell-ttl.js
Backport of https://github.com/arangodb/arangodb/pull/10642.
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/8001/
> try to make shell-ttl less time-dependent

- CHANGELOG
- arangod/Aql/TraversalBlock.cpp
- arangod/Cluster/ClusterMethods.cpp
- arangod/Cluster/ClusterMethods.h
- arangod/Cluster/ClusterTraverser.cpp
- arangod/Cluster/ClusterTraverser.h
- arangod/Graph/ShortestPathOptions.cpp
- arangod/Graph/SingleServerTraverser.cpp
- arangod/Graph/SingleServerTraverser.h
- arangod/Graph/Traverser.h
- arangod/Graph/TraverserCache.cpp
- arangod/Graph/TraverserCache.h
- lib/Basics/StringHeap.cpp
- lib/Basics/StringHeap.h
Same as: https://github.com/arangodb/arangodb/pull/10854
> Bug fix 3.4/traversal cache

- Documentation/DocuBlocks/Rest/BackupRestore/post_admin_backup_create.md
- Documentation/DocuBlocks/Rest/BackupRestore/post_admin_backup_download.md
- Documentation/DocuBlocks/Rest/BackupRestore/post_admin_backup_upload.md
- Documentation/DocuBlocks/Rest/Graph/general_graph_create_http_examples.md
- Documentation/DocuBlocks/Rest/Indexes/post_api_index_hash.md
- Documentation/DocuBlocks/Rest/Indexes/post_api_index_skiplist.md
- Documentation/DocuBlocks/Rest/Transactions/post_api_transaction.md
- Documentation/DocuBlocks/Rest/Transactions/post_api_transaction_begin.md
- Documentation/DocuBlocks/Rest/User Management/README.md
Backport of #10807 + https://github.com/arangodb/arangodb/pull/10475/commits/69fd22edbde2099521d66be509db7ec6b98d97f3
I can confirm that icons + info work for this slightly different patch.
> Documentation 3.5/graph orphan collections

- Documentation/DocuBlocks/Rest/Graph/general_graph_create_http_examples.md
- Documentation/DocuBlocks/Rest/Indexes/post_api_index_hash.md
- Documentation/DocuBlocks/Rest/Indexes/post_api_index_skiplist.md
- Documentation/DocuBlocks/Rest/Transactions/post_api_transaction.md
- Documentation/DocuBlocks/Rest/User Management/README.md
Backport of #10807 + https://github.com/arangodb/arangodb/pull/10475/commits/69fd22edbde2099521d66be509db7ec6b98d97f3
> Documentation 3.4/graph orphan collections

- CHANGELOG
- arangod/CMakeLists.txt
> Bug fix 3.4/windows exe product info

- CHANGELOG
- arangod/CMakeLists.txt
> Bug fix 3.5/windows exe product info

- arangod/Agency/MoveShard.cpp
> [3.4] moveshard insync follower part 2

- arangod/Agency/MoveShard.cpp
> [3.5] moveshard insync follower part 2

- CMakeLists.txt
- arangod/Aql/ExecutionBlockImpl.cpp
- arangod/Aql/SubqueryStartExecutor.cpp
- arangod/Aql/SubqueryStartExecutor.h
- tests/Aql/SpliceSubqueryOptimizerRuleTest.cpp
Fix for https://github.com/arangodb/arangodb/issues/10852#issuecomment-574711451. Related to #10865, but addresses different problems.
> Bug fix/issue 10852 part2

- CHANGELOG
- arangod/Agency/Job.cpp
- arangod/Agency/Job.h
- arangod/Agency/MoveShard.cpp
> [3.6] moveshard checks _to in sync for shard group

- tests/js/server/aql/aql-traversal-graph-object-regression.js
> [3.6] Add regression test for AstNode string comparison fix

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/react/public/index.html
- js/apps/system/_admin/aardvark/APP/react/src/setupProxy.js
Make the react proxy work with test files and not fully build files.
> optimise react dev mode proxy

- js/apps/system/_admin/aardvark/APP/react/config/webpack.config.dev.js
- js/apps/system/_admin/aardvark/APP/react/public/index.html
- js/apps/system/_admin/aardvark/APP/react/scripts/start.js
an important addition to react dev mode to NOT modify the production environment as it is now.
> properly redirect, do not modify production env!

- CHANGELOG
- arangod/Aql/IResearchViewOptimizerRules.cpp
- js/server/modules/@arangodb/foxx/queues/manager.js
- tests/js/server/aql/aql-optimizer-rule-late-document-materialization-arangosearch.js
- tests/js/server/aql/aql-traversal-graph-object-regression.js
- tests/js/server/aql/aql-view-arangosearch-server.js
Fixes a crash described in https://github.com/arangodb/arangodb/issues/10845#issuecomment-575723029
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8130/
> bugfix for https://github.com/arangodb/arangodb/issues/10845#issuecomment-575723029

- CMakeLists.txt
- arangod/Aql/ExecutionBlockImpl.cpp
- arangod/Aql/SubqueryStartExecutor.cpp
- arangod/Aql/SubqueryStartExecutor.h
- tests/Aql/SpliceSubqueryOptimizerRuleTest.cpp
Backport of https://github.com/arangodb/arangodb/pull/10905.
> [3.6] Bug fix/issue 10852 part2

- CHANGELOG
Change issue number from: #10371 (wrong issue) to #10601 (correct issue)
> Changelog: Fix issue number

- js/apps/system/_admin/aardvark/APP/aardvark.js
- js/apps/system/_admin/aardvark/APP/frontend/js/routers/versionCheck.js
- js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
- js/common/modules/@arangodb/common.js
* Decrease wait timeout in community arangosh
* Remove unused code from web UI
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8245/
> Bug fix/js cleanup

- UnitTests/OskarTestSuitesBlackList
Add a future test suite to this branch's blacklist
> add new test suite to blacklist

- UnitTests/OskarTestSuitesBlackList
Add a future test suite to this branch's blacklist
> blacklist new test suite

- CHANGELOG
> Add CHANGELOG entry for fix for #10949

- tests/js/server/shell/shell-database-mmfiles-noncluster.js
- tests/rb/HttpInterface/api-export-spec-noncluster.rb
Attempt to reduce diagnose two mmfiles test failures
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8318/
> hopefully reduce number of test issues

- arangod/Aql/ExecutionBlockImpl.cpp
> fix undefined pointer

- CHANGELOG
- arangod/Graph/KShortestPathsFinder.cpp
- arangod/Graph/KShortestPathsFinder.h
- tests/js/server/aql/aql-graph-k-shortest-path-0-weight-regression.js
> Bug fix 3.6/k shortest paths kaputt

- arangod/Aql/OptimizerRules.cpp
- arangod/RestHandler/RestDocumentHandler.cpp
- js/common/modules/@arangodb/aql/explainer.js
- tests/js/common/shell/shell-figures-mmfiles-noncluster.js
- tests/js/server/shell/shell-compaction-mmfiles-noncluster.js
Wild mix of small bugfixes
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8344/
> Bug fix/20200130

- 3rdParty/iresearch/core/analysis/text_token_stream.cpp
- CHANGELOG
- arangod/Aql/Ast.cpp
- arangod/Aql/AstNode.cpp
- arangod/Aql/AstNode.h
- arangod/Aql/Condition.cpp
- arangod/Aql/Condition.h
- arangod/Aql/IResearchViewNode.cpp
- arangod/Aql/IResearchViewNode.h
- arangod/Aql/IResearchViewOptimizerRules.cpp
- arangod/IResearch/IResearchFilterFactory.cpp
- arangod/StorageEngine/PhysicalCollection.cpp
- arangod/Transaction/Methods.cpp
- tests/IResearch/IResearchAnalyzerFeature-test.cpp
- tests/IResearch/IResearchFilterArrayInterval-test.cpp
- tests/IResearch/IResearchQueryOptimization-test.cpp
- tests/IResearch/IResearchViewNode-test.cpp
- tests/IResearch/common.cpp
- tests/js/common/aql/aql-view-arangosearch-cluster.inc
- tests/js/common/aql/aql-view-arangosearch-noncluster.js
Port for fix for internal issue #596 
(contains changes from both #10781 and #10714)
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/8394/
> Bug fix 3.6/internal issue #596

- tests/rb/HttpInterface/api-async-spec.rb
Ungreylist a test by making it less dependent on timings
This change is already covered by existing tests, such as *scripts/unittest http_server --test api-async*.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8370/
> attempt to ungreylist test

- arangod/Agency/Agent.cpp
Remove debug log muell introduced by https://github.com/arangodb/arangodb/pull/10745
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8452/
> fix log muell

- CHANGELOG
- arangod/Aql/DocumentProducingNode.h
- arangod/Aql/IndexNodeOptimizerRules.cpp
- tests/js/server/aql/aql-optimizer-rule-move-filters-into-enumerate.js
Fix Github issue #11051 
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8454/
> fixed issue #11051

- arangod/Aql/ExecutionBlockImpl.cpp
- arangod/Aql/ExecutionBlockImpl.h
- arangod/Aql/FilterExecutor.cpp
- arangod/Aql/FilterExecutor.h
- arangod/Aql/LimitExecutor.cpp
- arangod/Aql/ReturnExecutor.cpp
- arangod/Aql/ReturnExecutor.h
- arangod/Aql/ShortestPathExecutor.cpp
- arangod/Aql/ShortestPathExecutor.h
- arangod/Aql/SortedCollectExecutor.cpp
- arangod/Aql/SortedCollectExecutor.h
- tests/Aql/AqlItemBlockInputRangeTest.cpp
- tests/Aql/ExecutionBlockImplTest.cpp
- tests/Aql/FilterExecutorTest.cpp
- tests/Aql/ShortestPathExecutorTest.cpp
- tests/Aql/SortedCollectExecutorTest.cpp
- tests/Aql/TestLambdaExecutor.cpp
- tests/Aql/TestLambdaExecutor.h
Internal TeamGordo PR.
High Priority.
Modifies the skipRowsRange API to include stats as well.
Jenkins:
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/8511/
> Added Stats return value to skipRowsRange

- CHANGELOG
- arangosh/Restore/RestoreFeature.cpp
- arangosh/Shell/ClientFeature.cpp
Fix error message when database creation fails for `--create-database` option
additionally, pass the specified replication factor from `--replication-factor` option when creating a database.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8517/
> Bug fix 3.6/arangorestore fix create database

- 3rdParty/jemalloc/CMakeLists.txt
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/8527/
> Bugfix 3.6/fix jemaloc integration

- tests/Cache/Rebalancer.cpp
- tests/Cache/TransactionsWithBackingStore.cpp
Fixed evil thread creation and make it safe
This change is already covered by existing tests, such as *arangodbtests*.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8535/
> fix sketchy tests

- arangod/Aql/InputAqlItemRow.cpp
- arangod/Aql/InputAqlItemRow.h
- arangod/Aql/OutputAqlItemRow.cpp
- arangod/Aql/ShadowAqlItemRow.cpp
- arangod/Aql/ShadowAqlItemRow.h
- tests/Aql/AqlItemRowTest.cpp
Replaced the operator== and operator!= with `isSameBlockAndIndex`. Feel free to discuss the name.
> *AqlRowItem::operator== replacment

- lib/Basics/CrashHandler.cpp
Add a separate stack for the crash handler
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8557/
> add separate stack for signal handler

- js/client/modules/@arangodb/process-utils.js
- tests/js/common/shell/shell-collection-rocksdb-noncluster.js
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/8604/
> add try/catch

- arangod/Aql/AqlItemBlock.cpp
fixes aql shrink method.
Same as: https://github.com/arangodb/arangodb/pull/11121
> fix shrink method in aqlitemblock

- 3rdParty/jemalloc/CMakeLists.txt
- arangod/V8Server/v8-actions.cpp
- js/client/modules/@arangodb/process-utils.js
- js/client/modules/@arangodb/testing.js
- lib/Basics/process-utils.cpp
backport of https://github.com/arangodb/arangodb/pull/11118
> Bug fix 3.6/fix external test timeout

- 3rdParty/fuerte/include/fuerte/loop.h
- 3rdParty/fuerte/src/loop.cpp
- arangod/Agency/Store.cpp
- arangod/Aql/Condition.cpp
- arangod/Aql/Functions.cpp
- arangod/Cluster/ClusterFeature.cpp
- arangod/Cluster/ClusterMethods.cpp
- arangod/Network/ConnectionPool.cpp
- arangod/Network/ConnectionPool.h
- arangod/Network/NetworkFeature.cpp
- arangod/Replication/Syncer.cpp
- arangod/RocksDBEngine/RocksDBEventListener.cpp
- lib/Basics/files.cpp
- lib/Logger/LogThread.cpp
- lib/Logger/LogThread.h
- lib/ProgramOptions/Option.cpp
See commit messages
Expectation: should pass all existing tests.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8651/
> Bug fix/fixes 19022020

- CHANGELOG
- arangod/Aql/OptimizerRules.cpp
- tests/js/server/aql/aql-optimizer-collect-count.js
Backport of relevant parts from #11101.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8632/
> fix collect-in-cluster rule with limit

- 3rdParty/V8/gypfiles/shim_headers.gypi
- 3rdParty/V8/gypfiles/v8.gyp
one more place where the python interpreter has to be properly specified.
> fix python invocation

- js/client/modules/@arangodb/crash-utils.js
- js/client/modules/@arangodb/process-utils.js
backport of https://github.com/arangodb/arangodb/pull/11158
> Bug fix/crash detection (#11158)

- UnitTests/OskarTestSuitesBlackList
- arangod/GeneralServer/AcceptorTcp.cpp
- arangod/GeneralServer/AcceptorUnixDomain.cpp
> Activate server_secrets tests.

- arangod/Cluster/TraverserEngine.cpp
Fix some logically senseless code.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8752/
> Bug fix 3.6/fix invalid array handling in traverser

- CHANGELOG
- arangod/Cluster/ClusterInfo.cpp
> [3.6] maintenance mode detection unlocking agency hot backups

- CHANGELOG
- arangod/Cluster/ClusterInfo.cpp
> fix supervision mode detection when unlocking agency in hot backup

- arangod/Aql/TraversalExecutor.cpp
> AqlSubqueryExecution: Fix memory leak in traversal executor

- arangod/Aql/TraversalExecutor.cpp
> AqlSubqueryExecutionBlockImplExecuteImplementation use moveValueInto instead of cloneValueInto

- js/client/modules/@arangodb/testsuites/resilience.js
http://jenkins.arangodb.biz:8080/job/arangodb-ANY-linux-matrix-only-grey/793/
> Set 1800s timeout for resilience modules tests

- arangod/VocBase/Validators.cpp
- tests/js/common/shell/shell-validation-rocksdb.js
> Use plain JSON Schema.

- 3rdParty/json-schema-validation/CMakeLists.txt
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8873/
> Lower CMake version requirement to match project requirements.

- arangod/V8Server/v8-actions.cpp
- arangosh/Shell/V8ClientConnection.cpp
- lib/Rest/GeneralResponse.cpp
- lib/Rest/GeneralResponse.h
- lib/Rest/HttpResponse.h
- lib/Rest/VstResponse.cpp
- tests/js/client/shell/shell-foxx-interface.js
- tests/js/common/test-data/apps/interface/index.js
- tests/js/common/test-data/apps/interface/manifest.json
backport of most parts of https://github.com/arangodb/arangodb/pull/11097
> Bug fix 3.6/foxx allow post body on delete request 2

- tests/js/server/shell/shell-index-rocksdb.js
backport of https://github.com/arangodb/arangodb/pull/11204
> fix performance of very resource intensive test (#11204)

- tests/js/server/shell/shell-index-rocksdb.js
backport of https://github.com/arangodb/arangodb/pull/11204
> fix performance of very resource intensive test (#11204) 

- CHANGELOG
- arangod/Agency/Supervision.cpp
> [3.5] supervision maintenance legacy mode

- arangod/Agency/Supervision.cpp
> Wrong assertion

- tests/Aql/AqlItemBlockHelper.h
- tests/Aql/CalculationExecutorTest.cpp
- tests/Aql/FilterExecutorTest.cpp
> Add some FilterExecutor and CalculationExecutor tests

- Documentation/DocuBlocks/Rest/Collections/post_api_collection.md
- Documentation/DocuBlocks/Rest/Collections/put_api_collection_properties.md
- Documentation/DocuBlocks/collectionDatabaseCreate.md
- Documentation/DocuBlocks/collectionProperties.md
> Docs: Add DocuBlocks for document validation.

- arangod/Aql/QuerySnippet.cpp
Do not instantiate snipped if not collection is found on the server.
> AQL Satellite Traversal

- js/apps/system/_admin/aardvark/APP/react/public/assets/src/mode-aql.js
update the list of AQL functions for the frontend
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9061/
> add latest AQL functions

- CHANGELOG
- arangod/Cluster/FollowerInfo.cpp
> Fix an endless loop in FollowerInfo::persistInAgency.

- CHANGELOG
- arangod/RocksDBEngine/RocksDBVPackIndex.cpp
- tests/js/common/shell/shell-hash-index.js
Fixed Github issue https://github.com/arangodb/arangodb/issues/11275
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9089/
> Bug fix 3.5/issue 11275

- arangod/Graph/Graph.cpp
This lead to wrong in instantiation in single server mode
> added a missing check for replicationFactor equals satellite (string)

- arangod/Aql/MultiAqlItemBlockInputRange.cpp
- arangod/Aql/UnsortedGatherExecutor.cpp
- tests/js/server/aql/aql-fullcount.js
Fixes some failing queries.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9121/
> fix failing query

- CHANGELOG
- arangod/Agency/FailedLeader.cpp
- arangod/Cluster/ClusterMethods.cpp
- arangod/Pregel/Algos/DMID/DMID.cpp
- arangod/Pregel/Algos/DMID/VertexSumAggregator.h
- arangod/Pregel/Algos/SLPA.cpp
- arangod/RestServer/Metrics.cpp
- arangod/RestServer/Metrics.h
- arangod/RestServer/counter.h
- arangod/Statistics/StatisticsWorker.cpp
- arangod/Statistics/StatisticsWorker.h
- tests/Aql/EnumerateCollectionExecutorTest.cpp
- tests/Aql/ExecutorTestHelper.h
> compilation fixes for clang-10s more strict checking

- arangod/Cluster/ClusterMethods.cpp
- tests/rb/HttpInterface/api-collection-rocksdb-spec.rb
Fix "fix" for collection figures
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9135/
> fix "fix" for collection figures

- CHANGELOG
This contains the CHANGELOG entry only, see https://github.com/arangodb/enterprise/pull/413 for the actual changes.
> [3.6] Bug fix/fix one shard satellite access

- cmake/custom/ArangoDB_FindOpenSSL_WIN32.cmake
Check MSVC compiler version instead of the generator.
> Check MSVC_VERSION instead of CMAKE_GENERATOR

- arangod/Aql/GraphNode.cpp
- arangod/Aql/OptimizerRulesFeature.cpp
- js/common/modules/@arangodb/aql/explainer.js
Exported isSatelliteNode and isUsedAsSatellite.
> Satellite Graph / Parallel Gather Tests

- CHANGELOG
- arangod/Agency/Job.cpp
- arangod/Agency/Supervision.cpp
This could temporarily consider a FAILED server as GOOD after an agency
leader change.
> Fix an agency supervision bug.

- arangod/ClusterEngine/ClusterRestExportHandler.cpp
- arangod/ClusterEngine/ClusterRestExportHandler.h
- arangod/RestServer/FlushFeature.cpp
Remove some unused includes
Just needs to compile
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9319/
> Bug fix/headers cleanup

- arangod/Aql/QueryList.cpp
- arangod/Aql/QueryList.h
Slightly simplify QueryList implementation
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9318/
> simplify query list

- 3rdParty/iresearch/core/search/boolean_filter.cpp
- 3rdParty/iresearch/core/search/boolean_filter.hpp
- CHANGELOG
- tests/js/common/aql/aql-view-arangosearch-cluster.inc
- tests/js/common/aql/aql-view-arangosearch-noncluster.js
fixed #11104
FOR s IN v-site
SEARCH ANALYZER(s.attributes.country.value != "w" OR false, "identity")
RETURN s.attributes.country.value
Empty result.
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/9334/
> fixed iresearch analyzer NOT OR FALSE

- tests/js/client/authentication/auth.js
Add a test for authentication-API related return codes
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9328/
> Feature 3.6/add authentication test

- Documentation/DocuBlocks/Rest/Collections/1_structs.md
- Documentation/DocuBlocks/Rest/Collections/post_api_collection.md
- Documentation/DocuBlocks/Rest/Database/get_api_database_new.md
- Documentation/DocuBlocks/Rest/Graph/1_structs.md
- Documentation/DocuBlocks/Rest/Graph/general_graph_create_http_examples.md
- Documentation/DocuBlocks/Rest/Graph/general_graph_list_http_examples.md
- Documentation/DocuBlocks/collectionProperties.md
Implement graph API changes described in https://github.com/arangodb/docs/pull/372 for DocuBlocks
> Docs: Graph replicationFactor: "satellite" & isSatellite property

- CHANGELOG
- arangod/Cluster/Maintenance.cpp
This is a port of a change in devel.
> Fix a maintenance bug.

- lib/Basics/StaticStrings.cpp
- lib/Basics/StaticStrings.h
> added disjoint flag

- tests/js/client/http/cluster-metrics-cluster-spec.js
> Fix QueryTimeWatcher to check >=, not >

- arangod/Aql/NoResultsExecutor.cpp
> Force upstream call to be forwarded in NoResultsExecutor

- arangod/Aql/IResearchViewExecutor.cpp
- arangod/Aql/IResearchViewExecutor.h
Stored values optimizations.
https://github.com/arangodb/backlog/issues/677
One time allocations.
Stored values buffer allocation.
Merge executor readers allocation.
> IResearch view stored values optimizations

- tests/js/client/load-balancing/response-header.js
Align test expectations with changes from https://github.com/arangodb/arangodb/pull/11402
Jenkins: http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/9438/
> [3.6] Fix test expectations regarding header forwarding

- tests/js/client/load-balancing/response-header.js
Align test expectations with changes from https://github.com/arangodb/arangodb/pull/11401
Jenkins: http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/9439/
> Fix test expectations regarding header forwarding

- arangod/Aql/IndexNodeOptimizerRules.cpp
- tests/js/server/aql/aql-optimizer-rule-late-document-materialization-rocksdb.js
Fixed late materialization with several indexes when one of them is primary.
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/9443/
> Fixed invalid index id

- CHANGELOG
> fix CHANGELOG

- js/apps/system/_admin/aardvark/APP/frontend/js/templates/graphManagementView.html
- js/apps/system/_admin/aardvark/APP/frontend/js/views/graphManagementView.js
As the title says. 
Modifications:
1.) Mark as Disjoint Smart Graph
2.) During creation
3.) During edit
> added disjoint smart graphs to ui

- arangod/Aql/IndexNodeOptimizerRules.cpp
Late materialization does not support several indexes, e.g. `FILTER cond1 OR cond2` covered by two indexes. The code is simplified.
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/9510/
> late materialization. explicit single index

- CHANGELOG
- arangod/RocksDBEngine/RocksDBEngine.cpp
- arangod/StorageEngine/RocksDBOptionFeature.cpp
- arangod/StorageEngine/RocksDBOptionFeature.h
Implement feature request #11447 
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9528/
> issue #11447: expose `--rocksdb.target-file-size-base` and `--rocksdb.target-file-size-multiplier`

- arangod/Aql/SortExecutor.cpp
- arangod/Aql/SubqueryEndExecutor.cpp
Micro optimization for subqueries
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9532/
> micro optimizations

- js/server/modules/@arangodb/aql-graph-traversal-generic-graphs.js
added DSM to traversal testsuite.
> added disjoint smart graphs to traversal test suite

- Documentation/DocuBlocks/Rest/Administration/get_admin_modules_flush.md
Backport of https://github.com/arangodb/arangodb/commit/8079d11747934722fd0d98ce50f321394286885e
> Docs: Add missing log levels

- tests/js/client/agency/agency-test.js
Make agency tests less sensitive to timing issues
This change is already covered by existing tests, such as *scripts/unittest agency*.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9661/
> make the agency tests less sensitive to timing problems

- arangod/Agency/Agent.cpp
- arangod/Agency/Agent.h
> promises must be a multimap to allow emplacements with identical time

- arangod/Aql/PruneExpressionEvaluator.cpp
- tests/js/server/aql/aql-traversal-wrong-assertion-regression.js
This is really only relevant in maintainer mode, in released versions the code behaves as expected.
> Remove invalid assertion

- js/apps/system/_admin/aardvark/APP/frontend/js/collections/arangoDocument.js
- js/apps/system/_admin/aardvark/APP/frontend/js/templates/modalTable.html
- js/apps/system/_admin/aardvark/APP/frontend/js/views/documentsView.js
- js/apps/system/_admin/aardvark/APP/frontend/js/views/graphViewer.js
- js/apps/system/_admin/aardvark/APP/frontend/js/views/modalView.js
in order to create documents that have to fullfill json schemas
> add ability to create documents with a specified body 

- CHANGELOG
- arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
- arangod/RocksDBEngine/RocksDBEngine.cpp
- arangod/RocksDBEngine/RocksDBEngine.h
- tests/js/common/shell/shell-edge-index.js
Fix issue #11303 
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9736/
> fix issue #11303

- arangod/Aql/AllRowsFetcher.cpp
- arangod/Aql/AllRowsFetcher.h
- arangod/Aql/Query.h
- arangod/Cluster/ClusterMethods.cpp
- arangod/Cluster/MaintenanceFeature.cpp
- arangod/Graph/ShortestPathPriorityQueue.h
- arangod/RestHandler/RestCursorHandler.cpp
- arangod/RestServer/DatabaseFeature.cpp
- arangod/RestServer/VocbaseContext.h
- lib/Rest/GeneralRequest.h
Make some methods non-virtual that don't have overloads.
Fix typos
Code still needs to compile fine in all build versions.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9771/
> internal cleanup

- 3rdParty/V8/v7.9.317/src/execution/isolate.h
- arangod/Aql/DocumentExpressionContext.cpp
- arangod/Aql/DocumentIndexExpressionContext.cpp
- arangod/Aql/ExecutionStats.cpp
- arangod/Aql/ExecutorExpressionContext.cpp
- arangod/Aql/IResearchViewExecutor.cpp
- arangod/Aql/RegexCache.cpp
- [x ] Bug-Fix for *devel-branch* (i.e. no need for backports?)
> Fix compatibility issues

- arangod/Aql/ClusterNodes.cpp
- arangod/Aql/ClusterNodes.h
- arangod/Aql/DistributeExecutor.cpp
- arangod/Aql/DistributeExecutor.h
- arangod/Aql/OptimizerRules.cpp
- arangod/Aql/QuerySnippet.cpp
Internal Team Gordo PR.
Added a method to use the Distribute Executor for Traversals.
Test in Enterprise Branch (Only triggered there)
Jenkins:
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/9766/
Enterprise Part:
https://github.com/arangodb/enterprise/pull/450
> Distribute Traversal fixup

- arangod/Aql/ConditionFinder.cpp
- arangod/Aql/ExecutionNode.cpp
- arangod/Aql/ExecutionNode.h
- arangod/Aql/IResearchViewOptimizerRules.cpp
- arangod/Aql/OptimizerRules.cpp
- arangod/Aql/TraversalConditionFinder.cpp
- arangod/Aql/types.h
Added methods similar to the old api.
> Old API for getVarsValid/getVarsUsedLater 

- arangod/Cluster/AgencyCache.cpp
- arangod/Cluster/AgencyCache.h
Micro optimizations
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9814/
> cosmetic changes

- arangod/Aql/IResearchViewExecutor.cpp
- arangod/Aql/IResearchViewExecutor.h
speedup reading from iresearch columnstore, covered by existing unit and integration tests
> Speedup reading from ArangoSearch columnstore

- Documentation/DocuBlocks/Rest/Documents/delete_mutliple_documents.md
- Documentation/DocuBlocks/Rest/Documents/post_create_document.md
- Documentation/DocuBlocks/Rest/Documents/post_create_multiple_document.md
Clarify ignoreRevs, add proper examples
> Docs: Delete multiple documents with HTTP API

- arangod/Aql/GraphNode.cpp
GraphNode -> collections() -> only return unique elements within vector 
(use vector still, to prevent api change)
> Bug fix/disjoint graph crash fix

- README.md
> Remove skiplist mention from Readme.

- CHANGELOG
- arangod/RestHandler/RestCursorHandler.cpp
- arangod/RestHandler/RestDocumentHandler.cpp
- arangod/RestHandler/RestQueryHandler.cpp
- arangod/RestHandler/RestTasksHandler.cpp
- arangod/RestHandler/RestTransactionHandler.cpp
- arangod/RestHandler/RestVocbaseBaseHandler.cpp
- arangod/RestHandler/RestVocbaseBaseHandler.h
- tests/js/client/load-balancing/load-balancing-transactions-noauth-cluster.js
Backport of https://github.com/arangodb/arangodb/pull/11585
Jenkins: https://jenkins.arangodb.biz/job/arangodb-matrix-pr/9953/
> [3.5] Forward requests to correct coordinator based on transaction header

- CHANGELOG
- arangod/RestHandler/RestControlPregelHandler.cpp
- arangod/RestHandler/RestCursorHandler.cpp
- arangod/RestHandler/RestDocumentHandler.cpp
- arangod/RestHandler/RestQueryHandler.cpp
- arangod/RestHandler/RestReplicationHandler.cpp
- arangod/RestHandler/RestTasksHandler.cpp
- arangod/RestHandler/RestTransactionHandler.cpp
- arangod/RestHandler/RestVocbaseBaseHandler.cpp
- arangod/RestHandler/RestVocbaseBaseHandler.h
- tests/js/client/load-balancing/load-balancing-transactions-noauth-cluster.js
Backport of https://github.com/arangodb/arangodb/pull/11585
Jenkins: https://jenkins.arangodb.biz/job/arangodb-matrix-pr/9955/ (blue except an unrelated failure)
> [3.6] Forward requests to correct coordinator based on transaction header

- arangod/Agency/AsyncAgencyComm.h
Properly support gcc-10 :smile:
Test plan: check compilation output for warnings/errors.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/9958/
> support gcc-10

- CHANGELOG
- arangosh/Dump/DumpFeature.cpp
- arangosh/Restore/RestoreFeature.cpp
- arangosh/Utils/ManagedDirectory.cpp
- arangosh/Utils/ManagedDirectory.h
- js/client/modules/@arangodb/testsuites/dump.js
Backport of https://github.com/arangodb/arangodb/pull/11616
Jenkins: https://jenkins.arangodb.biz/job/arangodb-matrix-pr/9964/ (all blue)
> [3.5] Fix issues with arangodump encryption and compression

- CHANGELOG
- arangod/Cluster/ClusterInfo.cpp
This is a backport of a bug fix which was done in devel.
> Added a forgotten Plan/Version increment.

- CHANGELOG
- arangosh/Dump/DumpFeature.cpp
- arangosh/Restore/RestoreFeature.cpp
- arangosh/Utils/ManagedDirectory.cpp
- arangosh/Utils/ManagedDirectory.h
- js/client/modules/@arangodb/testsuites/dump.js
Backport of https://github.com/arangodb/arangodb/pull/11616
Jenkins: https://jenkins.arangodb.biz/job/arangodb-matrix-pr/9963/ (all blue)
> [3.6] Fix issues with arangodump encryption and compression

- CHANGELOG
Only the changelog entry for disjoint smart graphs
> disjoint smart graphs changelog

- arangod/Aql/ExecutionNode.h
- arangod/Aql/RegisterPlan.cpp
This is just removing an include that is not required.
> Remove unnecessary include of HeaderFile

- CHANGELOG
- arangosh/Restore/RestoreFeature.cpp
- arangosh/Utils/ManagedDirectory.cpp
- arangosh/Utils/ManagedDirectory.h
- js/client/modules/@arangodb/testsuites/dump.js
Backport of https://github.com/arangodb/arangodb/pull/11616
Jenkins: https://jenkins.arangodb.biz/job/arangodb-matrix-pr/9981/
> [3.4] Fix issues with arangodump encryption and compression

- lib/ApplicationFeatures/ConfigFeature.cpp
> Fix an arangod configuration bug (#11632)

- Documentation/DocuBlocks/Rest/Documents/delete_mutliple_documents.md
Backport of #11587
https://jenkins01.arangodb.biz/view/Documentation/job/arangodb-ANY-examples/624/
> Docs: Delete multiple documents with HTTP API (#11587)

- CHANGELOG
- arangod/Aql/ModificationExecutorHelpers.cpp
- arangod/Aql/ModificationExecutorHelpers.h
> [3.6] Also throw if result is not ok()

- arangod/Aql/ExecutionBlockImpl.cpp
Try to catch and Log velocypack errors in Aql.
This is bar far not complete, but better then nothing.
Example (with a faked error):
```
db._query("FOR x IN 1..100 RETURN x").toArray()
2020-05-18T21:52:28Z [19950] ERROR [feaa2] {queries} [query#14] Internal velocypack Error thrown by type=EnumerateListNode id=3 Message: Index out of bounds
```
Jenkins:
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/10001/
> Catch all VpackErrors, log them and throw ArangoException instead

- 3rdParty/fuerte/src/H1Connection.cpp
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/10012/
> fix for BTS-67

- arangod/Aql/GraphNode.cpp
- arangod/Aql/GraphNode.h
- arangod/Aql/OptimizerRules.cpp
- js/common/modules/@arangodb/aql/explainer.js
optimized explain output in case of local graph nodes. 
Before we only had the satellite case. Now we also support different (not only satellite) cases. (e.g. disjoint)
> optimized explain output

- tests/js/server/resilience/failover-view/resilience-synchronous-repl-with-arangosearch-view-cluster.js
https://arangodb.atlassian.net/browse/BTS-77
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/10159/
> Make test not loose failed leaders/followers

- tests/js/client/shell/shell-transaction.js
Added tests to make sure analyzers revision works with streaming transactions.
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/10173/
> Bug fix/add test analyzers revision to el cheapo transaction

- CHANGELOG
- CMakeLists.txt
> enforcing std=c++17 everywhere

- README_maintainers.md
> Documentation 3.6/gtest

- 3rdParty/fuerte/src/types.cpp
- CHANGELOG
- CMakeLists.txt
- arangod/Cluster/DBServerAgencySync.cpp
- arangod/Cluster/Maintenance.cpp
- arangod/Cluster/MaintenanceStrings.h
- arangod/Transaction/Methods.cpp
Backport of https://github.com/arangodb/arangodb/pull/11674/
> Bug fix 3.5/restart follower no leader set

- README_maintainers.md
> Documentation 3.5/gtest

- 3rdParty/iresearch/core/search/boolean_filter.cpp
- 3rdParty/iresearch/core/search/boolean_filter.hpp
- CHANGELOG
- tests/js/common/aql/aql-view-arangosearch-feature.js
Backport of fix for #11104
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/10188/
> Bug fix 3.5/issue #11104

- 3rdParty/iresearch/core/search/boolean_filter.cpp
- 3rdParty/iresearch/core/search/boolean_filter.hpp
- 3rdParty/iresearch/tests/search/boolean_filter_tests.cpp
- CHANGELOG
- tests/js/common/aql/aql-view-arangosearch-feature.js
> Bug fix 3.4/issue #11104

- lib/Basics/CrashHandler.cpp
- lib/Basics/debugging.cpp
- lib/Basics/debugging.h
- tests/js/server/recovery/crash-handler-abort.js
- tests/js/server/recovery/crash-handler-assert.js
- tests/js/server/recovery/crash-handler-segfault.js
- tests/js/server/recovery/crash-handler-terminate-active.js
- tests/js/server/recovery/crash-handler-terminate.js
Slightly simplify stack traces in case of a crash (a bit less deep stacks)
This change is already covered by existing tests, such as *scripts/unittest recovery*.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10214/
> simplify stack traces a bit

- CHANGELOG
- arangod/Network/Methods.cpp
- arangod/Network/Methods.h
> pimped up network send request robustness

- js/apps/system/_admin/aardvark/APP/frontend/js/views/shardsView.js
Fixed shards view (occured due disjoint smart graph integration). 
Does not need a changelog because that is not part of a released build.
> fix shards view due to disjoint smart graph integration

- Installation/Windows/client/Templates/NSIS.template.in
- Installation/Windows/client/Templates/arango-packer-template.nsi
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr-windows/4079/
> Improve Windows installer texts and backup creation

- arangod/Cluster/MaintenanceFeature.cpp
- arangod/Cluster/MaintenanceFeature.h
Remove now-unused variables from MaintenanceFeature
Test plan: must compile w/o errors
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10255/
> remove unused variables from MaintenanceFeature

- Documentation/DocuBlocks/Rest/Cursors/post_api_cursor.md
- js/apps/system/_admin/aardvark/APP/api-docs.json
Backport of https://github.com/arangodb/arangodb/commit/56dd7f6155ca40a2696fa548ecc1edb64ba3988b
> Docs: Fix data type of satelliteWaitSync option

- arangod/Cluster/MaintenanceFeature.cpp
- arangod/RocksDBEngine/RocksDBEventListener.cpp
- arangosh/Import/QuickHistogram.h
Fix a few occurrences of inefficient string logging.
Unimportant PR, just found these things by accident.
Test plan: must compile without errors.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10274/
> fix inefficient string logging

- 3rdParty/velocypack/src/Validator.cpp
- CHANGELOG
> correct validation of keys in velocypack

- js/apps/system/_admin/aardvark/APP/react/src/store/logging/middleware.tsx
Remove extraneous logging in the web UI in cluster mode
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10370/
> disable extraneous logging in web UI in cluster mode

- CHANGELOG
- js/apps/system/_admin/aardvark/APP/aardvark.js
- js/common/modules/@arangodb/aql/explainer.js
Fix "Create Debug Package" in web UI in cluster mode
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10377/
> fixed "Create Debug Package" in web UI in cluster mode

- 3rdParty/velocypack/src/Validator.cpp
- CHANGELOG
- js/apps/system/_admin/aardvark/APP/frontend/js/templates/nodesView.ejs
Augment cluster nodes view in web UI by displaying full node id (via `title` attribute) and displaying full datetime info in "Since" column. Previously, only the time part was displayed, and without timezone info
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10379/
> Bug fix/augment nodes view

- arangod/Aql/AqlItemBlock.cpp
Micro-optimizations for AqlItemBlock.
This change is already covered by existing tests, such as *scripts/unittest shell_server_aql, scripts/unittest gtest*.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10424/
> a bit less work for AqlItemBlock processing

- CHANGELOG
- arangod/GeneralServer/RestHandler.h
Same as: https://github.com/arangodb/arangodb/pull/11836
> Bug fix 3.7/rest handler handle exceptions

- 3rdParty/fuerte/include/fuerte/message.h
- 3rdParty/fuerte/include/fuerte/types.h
- 3rdParty/fuerte/src/types.cpp
- arangod/Cluster/SynchronizeShard.cpp
- arangod/Network/Methods.cpp
- arangod/Network/Methods.h
- arangod/Network/Utils.cpp
- arangod/Network/Utils.h
Backport of https://github.com/arangodb/arangodb/pull/11859
> [3.6] Bug fix/improve replication logging

- Documentation/DocuBlocks/Rest/Administration/get_admin_server_tls.md
- Documentation/DocuBlocks/Rest/BackupRestore/post_admin_backup_list.md
- README
- arangod/Cluster/ClusterMethods.cpp
- arangod/GeneralServer/H2CommTask.cpp
- arangod/GeneralServer/SslServerFeature.cpp
- arangod/RocksDBEngine/RocksDBEngine.h
- arangod/StorageEngine/HotBackupCommon.h
- arangosh/Backup/BackupFeature.cpp
- js/client/modules/@arangodb/testsuites/dump.js
- tests/js/client/server_secrets/tls-rotation.js
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr/10483/
> Hot-Backup encryption support (#11803)

- 3rdParty/iresearch/core/index/index_writer.cpp
- 3rdParty/iresearch/core/index/index_writer.hpp
- 3rdParty/iresearch/core/utils/noncopyable.hpp
- CHANGELOG
Ported fix for internal issue #701
Verified by upstream tests
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/10492/
> Ported fix for internal issue #701

- 3rdParty/iresearch/core/index/index_writer.cpp
- 3rdParty/iresearch/core/index/index_writer.hpp
- 3rdParty/iresearch/core/utils/noncopyable.hpp
- CHANGELOG
Fix for internal issue #701
Verified by upstream tests
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/10475/
> ported fix for internal  issue #701

- 3rdParty/velocypack/src/Validator.cpp
- CHANGELOG
> [3.5] correct validation of keys in velocypack

- arangosh/Restore/RestoreFeature.cpp
Improve error messages for failing file operations in arangorestore.
This could help debugging cases when the restore goes wrong in Jenkins runs for unknown reasons.
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/10537/
> better errors for failing arangorestore file ops

- arangod/Agency/Supervision.cpp
> [3.7] Leave isBuilding collections alone in the Supervision
